import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const B1_BUILD_UA_SENTENCES_1: BuildUaSentenceDict = {
  // =========================
  // LESSON 1 — Robota a kariéra
  // =========================
  [phraseKey("pracovná doba", "b1-1")]: {
    sk: "Moja pracovná doba je od ôsmej do štvrtej.",
    ua: "Мій робочий час — з восьмої до четвертої.",
    ru: "Моё рабочее время — с восьми до четырёх.",
    en: "My working hours are from eight to four.",
    uaTokens: ["Мій", "робочий", "час", "—", "з", "восьмої", "до", "четвертої", "."],
    ruTokens: ["Моё", "рабочее", "время", "—", "с", "восьми", "до", "четырёх", "."],
    enTokens: ["My", "working", "hours", "are", "from", "eight", "to", "four", "."],
    extraUaTokens: ["сьогодні", "ранку", "щодня"],
    extraRuTokens: ["сегодня", "утром", "каждый"],
    extraEnTokens: ["today", "morning", "daily"],
  },

  [phraseKey("nástup", "b1-1")]: {
    sk: "Nástup do práce mám od prvého marca.",
    ua: "Початок роботи в мене з першого березня.",
    ru: "Выход на работу у меня с первого марта.",
    en: "My start date at work is March first.",
    uaTokens: ["Початок", "роботи", "в", "мене", "з", "першого", "березня", "."],
    ruTokens: ["Выход", "на", "работу", "у", "меня", "с", "первого", "марта", "."],
    enTokens: ["My", "start", "date", "at", "work", "is", "March", "first", "."],
    extraUaTokens: ["офіційно", "саме", "цього"],
    extraRuTokens: ["официально", "именно", "этого"],
    extraEnTokens: ["officially", "exactly", "this"],
  },

  [phraseKey("skúšobná doba", "b1-1")]: {
    sk: "Skúšobná doba trvá tri mesiace.",
    ua: "Випробувальний термін триває три місяці.",
    ru: "Испытательный срок длится три месяца.",
    en: "The probation period lasts three months.",
    uaTokens: ["Випробувальний", "термін", "триває", "три", "місяці", "."],
    ruTokens: ["Испытательный", "срок", "длится", "три", "месяца", "."],
    enTokens: ["The", "probation", "period", "lasts", "three", "months", "."],
    extraUaTokens: ["зазвичай", "лише", "майже"],
    extraRuTokens: ["обычно", "только", "почти"],
    extraEnTokens: ["usually", "only", "almost"],
  },

  [phraseKey("pracovný pomer", "b1-1")]: {
    sk: "Pracovný pomer mi začína po podpise zmluvy.",
    ua: "Трудові відносини починаються після підпису договору.",
    ru: "Трудовые отношения начинаются после подписания договора.",
    en: "My employment begins after signing the contract.",
    uaTokens: ["Трудові", "відносини", "починаються", "після", "підпису", "договору", "."],
    ruTokens: ["Трудовые", "отношения", "начинаются", "после", "подписания", "договора", "."],
    enTokens: ["My", "employment", "begins", "after", "signing", "the", "contract", "."],
    extraUaTokens: ["офіційно", "лише", "одразу"],
    extraRuTokens: ["официально", "только", "сразу"],
    extraEnTokens: ["officially", "only", "immediately"],
  },

  [phraseKey("výplata", "b1-1")]: {
    sk: "Výplata mi chodí vždy pätnásteho.",
    ua: "Зарплату мені виплачують завжди п’ятнадцятого числа.",
    ru: "Зарплата приходит мне всегда пятнадцатого числа.",
    en: "I always get paid on the fifteenth.",
    uaTokens: ["Зарплату", "мені", "виплачують", "завжди", "п’ятнадцятого", "числа", "."],
    ruTokens: ["Зарплата", "приходит", "мне", "всегда", "пятнадцатого", "числа", "."],
    enTokens: ["I", "always", "get", "paid", "on", "the", "fifteenth", "."],
    extraUaTokens: ["кожного", "цього", "місяця"],
    extraRuTokens: ["каждого", "этого", "месяца"],
    extraEnTokens: ["every", "this", "month"],
  },

  [phraseKey("príspevok", "b1-1")]: {
    sk: "Firma mi dáva príspevok na cestovanie.",
    ua: "Фірма доплачує мені на проїзд.",
    ru: "Компания доплачивает мне на проезд.",
    en: "The company gives me a travel allowance.",
    uaTokens: ["Фірма", "доплачує", "мені", "на", "проїзд", "."],
    ruTokens: ["Компания", "доплачивает", "мне", "на", "проезд", "."],
    enTokens: ["The", "company", "gives", "me", "a", "travel", "allowance", "."],
    extraUaTokens: ["ще", "щомісяця", "частково"],
    extraRuTokens: ["ещё", "ежемесячно", "частично"],
    extraEnTokens: ["also", "monthly", "partly"],
  },

  [phraseKey("dochádzka", "b1-1")]: {
    sk: "Dochádzku si zapisujeme v aplikácii.",
    ua: "Табель ми відмічаємо в додатку.",
    ru: "Табель мы отмечаем в приложении.",
    en: "We record attendance in the app.",
    uaTokens: ["Табель", "ми", "відмічаємо", "в", "додатку", "."],
    ruTokens: ["Табель", "мы", "отмечаем", "в", "приложении", "."],
    enTokens: ["We", "record", "attendance", "in", "the", "app", "."],
    extraUaTokens: ["щодня", "самі", "зранку"],
    extraRuTokens: ["ежедневно", "сами", "утром"],
    extraEnTokens: ["daily", "ourselves", "morning"],
  },

  [phraseKey("benefit", "b1-1")]: {
    sk: "Ako benefit máme stravné a multisport kartu.",
    ua: "Як бонус у нас є харчування та мультиспорт-картка.",
    ru: "Как бонус у нас есть питание и мультиспорт-карта.",
    en: "As a benefit, we get meals and a multisport card.",
    uaTokens: ["Як", "бонус", "у", "нас", "є", "харчування", "та", "мультиспорт-картка", "."],
    ruTokens: ["Как", "бонус", "у", "нас", "есть", "питание", "и", "мультиспорт-карта", "."],
    enTokens: ["As", "a", "benefit", ",", "we", "get", "meals", "and", "a", "multisport", "card", "."],
    extraUaTokens: ["також", "ще", "додатково"],
    extraRuTokens: ["также", "ещё", "дополнительно"],
    extraEnTokens: ["also", "extra", "additionally"],
  },

  [phraseKey("nadriadený", "b1-1")]: {
    sk: "Môj nadriadený chce, aby som prišiel načas.",
    ua: "Мій керівник хоче, щоб я приходив вчасно.",
    ru: "Мой руководитель хочет, чтобы я приходил вовремя.",
    en: "My supervisor wants me to arrive on time.",
    uaTokens: ["Мій", "керівник", "хоче", ",", "щоб", "я", "приходив", "вчасно", "."],
    ruTokens: ["Мой", "руководитель", "хочет", ",", "чтобы", "я", "приходил", "вовремя", "."],
    enTokens: ["My", "supervisor", "wants", "me", "to", "arrive", "on", "time", "."],
    extraUaTokens: ["завжди", "на", "роботу"],
    extraRuTokens: ["всегда", "на", "работу"],
    extraEnTokens: ["always", "to", "work"],
  },

  [phraseKey("podriadený", "b1-1")]: {
    sk: "Ako vedúci musím podporiť aj nového podriadeného.",
    ua: "Як керівник я маю підтримати навіть нового підлеглого.",
    ru: "Как руководитель я должен поддержать даже нового подчинённого.",
    en: "As a manager, I must support even the new subordinate.",
    uaTokens: ["Як", "керівник", "я", "маю", "підтримати", "навіть", "нового", "підлеглого", "."],
    ruTokens: ["Как", "руководитель", "я", "должен", "поддержать", "даже", "нового", "подчинённого", "."],
    enTokens: ["As", "a", "manager", ",", "I", "must", "support", "even", "the", "new", "subordinate", "."],
    extraUaTokens: ["сьогодні", "добре", "молодого"],
    extraRuTokens: ["сегодня", "хорошо", "молодого"],
    extraEnTokens: ["today", "well", "young"],
  },

  // =========================
  // LESSON 2 — Komunikácia v tíme
  // =========================
  [phraseKey("nedorozumenie", "b1-2")]: {
    sk: "Vzniklo nedorozumenie, lebo sme sa zle pochopili.",
    ua: "Виникло непорозуміння, бо ми неправильно зрозуміли одне одного.",
    ru: "Возникло недоразумение, потому что мы неправильно поняли друг друга.",
    en: "A misunderstanding arose because we misunderstood each other.",
    uaTokens: ["Виникло", "непорозуміння", ",", "бо", "ми", "неправильно", "зрозуміли", "одне", "одного", "."],
    ruTokens: ["Возникло", "недоразумение", ",", "потому", "что", "мы", "неправильно", "поняли", "друг", "друга", "."],
    enTokens: ["A", "misunderstanding", "arose", "because", "we", "misunderstood", "each", "other", "."],
    extraUaTokens: ["просто", "спочатку", "трохи"],
    extraRuTokens: ["просто", "сначала", "немного"],
    extraEnTokens: ["just", "at", "first"],
  },

  [phraseKey("spolupráca", "b1-2")]: {
    sk: "Spolupráca medzi oddeleniami je pre projekt kľúčová.",
    ua: "Співпраця між відділами є ключовою для проєкту.",
    ru: "Сотрудничество между отделами ключевое для проекта.",
    en: "Cooperation between departments is key to the project.",
    uaTokens: ["Співпраця", "між", "відділами", "є", "ключовою", "для", "проєкту", "."],
    ruTokens: ["Сотрудничество", "между", "отделами", "ключевое", "для", "проекта", "."],
    enTokens: ["Cooperation", "between", "departments", "is", "key", "to", "the", "project", "."],
    extraUaTokens: ["справді", "дуже", "цього"],
    extraRuTokens: ["действительно", "очень", "этого"],
    extraEnTokens: ["really", "very", "this"],
  },

  [phraseKey("komunikácia", "b1-2")]: {
    sk: "Bez dobrej komunikácie sa tím rýchlo rozpadne.",
    ua: "Без хорошої комунікації команда швидко розвалиться.",
    ru: "Без хорошей коммуникации команда быстро развалится.",
    en: "Without good communication, the team will quickly fall apart.",
    uaTokens: ["Без", "хорошої", "комунікації", "команда", "швидко", "розвалиться", "."],
    ruTokens: ["Без", "хорошей", "коммуникации", "команда", "быстро", "развалится", "."],
    enTokens: ["Without", "good", "communication", ",", "the", "team", "will", "quickly", "fall", "apart", "."],
    extraUaTokens: ["майже", "повністю", "тоді"],
    extraRuTokens: ["почти", "полностью", "тогда"],
    extraEnTokens: ["almost", "completely", "then"],
  },

  [phraseKey("vyjadriť sa", "b1-2")]: {
    sk: "Môžeš sa k tomu vyjadriť ešte dnes?",
    ua: "Можеш висловитися щодо цього ще сьогодні?",
    ru: "Можешь высказаться по этому поводу ещё сегодня?",
    en: "Can you comment on this today?",
    uaTokens: ["Можеш", "висловитися", "щодо", "цього", "ще", "сьогодні", "?"],
    ruTokens: ["Можешь", "высказаться", "по", "этому", "поводу", "ещё", "сегодня", "?"],
    enTokens: ["Can", "you", "comment", "on", "this", "today", "?"],
    extraUaTokens: ["спокійно", "коротко", "будь"],
    extraRuTokens: ["спокойно", "кратко", "пожалуйста"],
    extraEnTokens: ["calmly", "briefly", "please"],
  },

  [phraseKey("navrhnúť", "b1-2")]: {
    sk: "Navrhol som riešenie, ktoré šetrí čas aj peniaze.",
    ua: "Я запропонував рішення, яке економить час і гроші.",
    ru: "Я предложил решение, которое экономит время и деньги.",
    en: "I suggested a solution that saves time and money.",
    uaTokens: ["Я", "запропонував", "рішення", ",", "яке", "економить", "час", "і", "гроші", "."],
    ruTokens: ["Я", "предложил", "решение", ",", "которое", "экономит", "время", "и", "деньги", "."],
    enTokens: ["I", "suggested", "a", "solution", "that", "saves", "time", "and", "money", "."],
    extraUaTokens: ["добре", "нам", "усім"],
    extraRuTokens: ["хорошо", "нам", "всем"],
    extraEnTokens: ["well", "for", "everyone"],
  },

  [phraseKey("súhlas", "b1-2")]: {
    sk: "Potrebujem tvoj súhlas, aby sme mohli pokračovať.",
    ua: "Мені потрібна твоя згода, щоб ми могли продовжити.",
    ru: "Мне нужно твоё согласие, чтобы мы могли продолжить.",
    en: "I need your approval so we can continue.",
    uaTokens: ["Мені", "потрібна", "твоя", "згода", ",", "щоб", "ми", "могли", "продовжити", "."],
    ruTokens: ["Мне", "нужно", "твоё", "согласие", ",", "чтобы", "мы", "могли", "продолжить", "."],
    enTokens: ["I", "need", "your", "approval", "so", "we", "can", "continue", "."],
    extraUaTokens: ["далі", "роботу", "спокійно"],
    extraRuTokens: ["дальше", "работу", "спокойно"],
    extraEnTokens: ["further", "work", "calmly"],
  },

  [phraseKey("nesúhlas", "b1-2")]: {
    sk: "Vyjadril nesúhlas, ale navrhol aj alternatívu.",
    ua: "Він висловив незгоду, але запропонував і альтернативу.",
    ru: "Он выразил несогласие, но предложил и альтернативу.",
    en: "He expressed disagreement but also suggested an alternative.",
    uaTokens: ["Він", "висловив", "незгоду", ",", "але", "запропонував", "і", "альтернативу", "."],
    ruTokens: ["Он", "выразил", "несогласие", ",", "но", "предложил", "и", "альтернативу", "."],
    enTokens: ["He", "expressed", "disagreement", "but", "also", "suggested", "an", "alternative", "."],
    extraUaTokens: ["свою", "кращу", "одразу"],
    extraRuTokens: ["свою", "лучшую", "сразу"],
    extraEnTokens: ["his", "better", "immediately"],
  },

  [phraseKey("vysvetlenie", "b1-2")]: {
    sk: "Ďakujem za vysvetlenie, už je mi to jasné.",
    ua: "Дякую за пояснення, тепер мені все ясно.",
    ru: "Спасибо за объяснение, теперь мне всё ясно.",
    en: "Thanks for the explanation, now it’s clear to me.",
    uaTokens: ["Дякую", "за", "пояснення", ",", "тепер", "мені", "все", "ясно", "."],
    ruTokens: ["Спасибо", "за", "объяснение", ",", "теперь", "мне", "всё", "ясно", "."],
    enTokens: ["Thanks", "for", "the", "explanation", ",", "now", "it’s", "clear", "to", "me", "."],
    extraUaTokens: ["повністю", "вже", "нарешті"],
    extraRuTokens: ["полностью", "уже", "наконец"],
    extraEnTokens: ["completely", "already", "finally"],
  },

  [phraseKey("upozorniť", "b1-2")]: {
    sk: "Chcem ťa upozorniť, že termín sa blíži.",
    ua: "Хочу звернути твою увагу, що термін наближається.",
    ru: "Хочу предупредить, что срок приближается.",
    en: "I want to warn you that the deadline is approaching.",
    uaTokens: ["Хочу", "звернути", "твою", "увагу", ",", "що", "термін", "наближається", "."],
    ruTokens: ["Хочу", "предупредить", ",", "что", "срок", "приближается", "."],
    enTokens: ["I", "want", "to", "warn", "you", "that", "the", "deadline", "is", "approaching", "."],
    extraUaTokens: ["вже", "швидко", "дуже"],
    extraRuTokens: ["уже", "быстро", "очень"],
    extraEnTokens: ["already", "quickly", "very"],
  },

  [phraseKey("reagovať", "b1-2")]: {
    sk: "Ak sa niečo zmení, reaguj prosím hneď.",
    ua: "Якщо щось зміниться, відреагуй, будь ласка, одразу.",
    ru: "Если что-то изменится, отреагируй, пожалуйста, сразу.",
    en: "If anything changes, please respond immediately.",
    uaTokens: ["Якщо", "щось", "зміниться", ",", "відреагуй", ",", "будь", "ласка", ",", "одразу", "."],
    ruTokens: ["Если", "что-то", "изменится", ",", "отреагируй", ",", "пожалуйста", ",", "сразу", "."],
    enTokens: ["If", "anything", "changes", ",", "please", "respond", "immediately", "."],
    extraUaTokens: ["на", "це", "тоді"],
    extraRuTokens: ["на", "это", "тогда"],
    extraEnTokens: ["to", "this", "then"],
  },

  // =========================
  // LESSON 3 — Cestovanie a doprava
  // =========================
  [phraseKey("príručná batožina", "b1-3")]: {
    sk: "Príručnú batožinu si beriem so sebou do kabíny.",
    ua: "Ручну поклажу я беру з собою в салон.",
    ru: "Ручную кладь я беру с собой в салон.",
    en: "I take my carry-on baggage with me into the cabin.",
    uaTokens: ["Ручну", "поклажу", "я", "беру", "з", "собою", "в", "салон", "."],
    ruTokens: ["Ручную", "кладь", "я", "беру", "с", "собой", "в", "салон", "."],
    enTokens: ["I", "take", "my", "carry-on", "baggage", "with", "me", "into", "the", "cabin", "."],
    extraUaTokens: ["завжди", "лише", "маленьку"],
    extraRuTokens: ["всегда", "только", "маленькую"],
    extraEnTokens: ["always", "only", "small"],
  },

  [phraseKey("nástup", "b1-3")]: {
    sk: "Nástup do lietadla začne o dvadsať minút.",
    ua: "Посадка на літак почнеться за двадцять хвилин.",
    ru: "Посадка на самолёт начнётся через двадцать минут.",
    en: "Boarding will start in twenty minutes.",
    uaTokens: ["Посадка", "на", "літак", "почнеться", "за", "двадцять", "хвилин", "."],
    ruTokens: ["Посадка", "на", "самолёт", "начнётся", "через", "двадцать", "минут", "."],
    enTokens: ["Boarding", "will", "start", "in", "twenty", "minutes", "."],
    extraUaTokens: ["приблизно", "вже", "скоро"],
    extraRuTokens: ["примерно", "уже", "скоро"],
    extraEnTokens: ["approximately", "already", "soon"],
  },

  [phraseKey("cestujúci", "b1-3")]: {
    sk: "Cestujúci musia mať lístok pripravený na kontrolu.",
    ua: "Пасажири повинні мати готовий квиток до перевірки.",
    ru: "Пассажиры должны иметь билет готовым к проверке.",
    en: "Passengers must have their ticket ready for inspection.",
    uaTokens: ["Пасажири", "повинні", "мати", "готовий", "квиток", "до", "перевірки", "."],
    ruTokens: ["Пассажиры", "должны", "иметь", "билет", "готовым", "к", "проверке", "."],
    enTokens: ["Passengers", "must", "have", "their", "ticket", "ready", "for", "inspection", "."],
    extraUaTokens: ["усі", "заздалегідь", "свій"],
    extraRuTokens: ["все", "заранее", "свой"],
    extraEnTokens: ["all", "in", "advance"],
  },

  [phraseKey("zrušenie", "b1-3")]: {
    sk: "Zrušenie spoja nám spôsobilo veľké meškanie.",
    ua: "Скасування рейсу спричинило нам велике запізнення.",
    ru: "Отмена рейса вызвала у нас большую задержку.",
    en: "The cancellation caused us a major delay.",
    uaTokens: ["Скасування", "рейсу", "спричинило", "нам", "велике", "запізнення", "."],
    ruTokens: ["Отмена", "рейса", "вызвала", "у", "нас", "большую", "задержку", "."],
    enTokens: ["The", "cancellation", "caused", "us", "a", "major", "delay", "."],
    extraUaTokens: ["сьогодні", "дуже", "неприємне"],
    extraRuTokens: ["сегодня", "очень", "неприятную"],
    extraEnTokens: ["today", "very", "unpleasant"],
  },

  [phraseKey("prestupovať", "b1-3")]: {
    sk: "V Bratislave budeme prestupovať na rýchlik.",
    ua: "У Братиславі ми будемо робити пересадку на швидкий потяг.",
    ru: "В Братиславе мы будем делать пересадку на скорый поезд.",
    en: "In Bratislava, we will transfer to an express train.",
    uaTokens: ["У", "Братиславі", "ми", "будемо", "робити", "пересадку", "на", "швидкий", "потяг", "."],
    ruTokens: ["В", "Братиславе", "мы", "будем", "делать", "пересадку", "на", "скорый", "поезд", "."],
    enTokens: ["In", "Bratislava", ",", "we", "will", "transfer", "to", "an", "express", "train", "."],
    extraUaTokens: ["потім", "ще", "там"],
    extraRuTokens: ["потом", "ещё", "там"],
    extraEnTokens: ["later", "also", "there"],
  },

  [phraseKey("cestovný doklad", "b1-3")]: {
    sk: "Bez cestovného dokladu ťa do vlaku nepustia.",
    ua: "Без проїзного документа тебе не пустять у потяг.",
    ru: "Без проездного документа тебя не пустят в поезд.",
    en: "Without a travel document, they won’t let you onto the train.",
    uaTokens: ["Без", "проїзного", "документа", "тебе", "не", "пустять", "у", "потяг", "."],
    ruTokens: ["Без", "проездного", "документа", "тебя", "не", "пустят", "в", "поезд", "."],
    enTokens: ["Without", "a", "travel", "document", ",", "they", "won’t", "let", "you", "onto", "the", "train", "."],
    extraUaTokens: ["просто", "взагалі", "туди"],
    extraRuTokens: ["просто", "вообще", "туда"],
    extraEnTokens: ["simply", "at", "all"],
  },

  [phraseKey("bezpečnostná kontrola", "b1-3")]: {
    sk: "Na bezpečnostnej kontrole si musím vybrať opasok.",
    ua: "На контролі безпеки я маю зняти ремінь.",
    ru: "На контроле безопасности я должен снять ремень.",
    en: "At the security check, I have to take off my belt.",
    uaTokens: ["На", "контролі", "безпеки", "я", "маю", "зняти", "ремінь", "."],
    ruTokens: ["На", "контроле", "безопасности", "я", "должен", "снять", "ремень", "."],
    enTokens: ["At", "the", "security", "check", ",", "I", "have", "to", "take", "off", "my", "belt", "."],
    extraUaTokens: ["також", "швидко", "там"],
    extraRuTokens: ["также", "быстро", "там"],
    extraEnTokens: ["also", "quickly", "there"],
  },

  [phraseKey("palubný lístok", "b1-3")]: {
    sk: "Palubný lístok si uložím do mobilu aj do peňaženky.",
    ua: "Посадковий талон збережу і в телефоні, і в гаманці.",
    ru: "Посадочный талон сохраню и в телефоне, и в кошельке.",
    en: "I’ll save the boarding pass in my phone and in my wallet.",
    uaTokens: ["Посадковий", "талон", "збережу", "і", "в", "телефоні", ",", "і", "в", "гаманці", "."],
    ruTokens: ["Посадочный", "талон", "сохраню", "и", "в", "телефоне", ",", "и", "в", "кошельке", "."],
    enTokens: ["I’ll", "save", "the", "boarding", "pass", "in", "my", "phone", "and", "in", "my", "wallet", "."],
    extraUaTokens: ["про", "всяк", "випадок"],
    extraRuTokens: ["на", "всякий", "случай"],
    extraEnTokens: ["just", "in", "case"],
  },

  [phraseKey("odovzdať batožinu", "b1-3")]: {
    sk: "Pri prepážke musím odovzdať batožinu.",
    ua: "На стійці реєстрації я маю здати багаж.",
    ru: "У стойки регистрации я должен сдать багаж.",
    en: "At the check-in counter, I have to check in my luggage.",
    uaTokens: ["На", "стійці", "реєстрації", "я", "маю", "здати", "багаж", "."],
    ruTokens: ["У", "стойки", "регистрации", "я", "должен", "сдать", "багаж", "."],
    enTokens: ["At", "the", "check-in", "counter", ",", "I", "have", "to", "check", "in", "my", "luggage", "."],
    extraUaTokens: ["зараз", "великий", "свій"],
    extraRuTokens: ["сейчас", "большой", "свой"],
    extraEnTokens: ["now", "large", "my"],
  },

  [phraseKey("colná kontrola", "b1-3")]: {
    sk: "Na colnej kontrole sa ma pýtali, čo prevážam.",
    ua: "На митному контролі мене питали, що я везу.",
    ru: "На таможенном контроле меня спрашивали, что я везу.",
    en: "At customs, they asked me what I was carrying.",
    uaTokens: ["На", "митному", "контролі", "мене", "питали", ",", "що", "я", "везу", "."],
    ruTokens: ["На", "таможенном", "контроле", "меня", "спрашивали", ",", "что", "я", "везу", "."],
    enTokens: ["At", "customs", ",", "they", "asked", "me", "what", "I", "was", "carrying", "."],
    extraUaTokens: ["із", "собою", "туди"],
    extraRuTokens: ["с", "собой", "туда"],
    extraEnTokens: ["with", "me", "there"],
  },

  // =========================
  // LESSON 4 — Zdravie a lekár
  // =========================
  [phraseKey("liečba", "b1-4")]: {
    sk: "Liečba bude trvať asi dva týždne.",
    ua: "Лікування триватиме приблизно два тижні.",
    ru: "Лечение будет длиться примерно две недели.",
    en: "The treatment will last about two weeks.",
    uaTokens: ["Лікування", "триватиме", "приблизно", "два", "тижні", "."],
    ruTokens: ["Лечение", "будет", "длиться", "примерно", "две", "недели", "."],
    enTokens: ["The", "treatment", "will", "last", "about", "two", "weeks", "."],
    extraUaTokens: ["ще", "майже", "усього"],
    extraRuTokens: ["ещё", "почти", "всего"],
    extraEnTokens: ["still", "almost", "only"],
  },

  [phraseKey("vyšetriť", "b1-4")]: {
    sk: "Lekár ma vyšetrel a odporučil mi oddych.",
    ua: "Лікар мене оглянув і порадив відпочинок.",
    ru: "Врач меня осмотрел и посоветовал отдых.",
    en: "The doctor examined me and recommended rest.",
    uaTokens: ["Лікар", "мене", "оглянув", "і", "порадив", "відпочинок", "."],
    ruTokens: ["Врач", "меня", "осмотрел", "и", "посоветовал", "отдых", "."],
    enTokens: ["The", "doctor", "examined", "me", "and", "recommended", "rest", "."],
    extraUaTokens: ["повний", "домашній", "спокій"],
    extraRuTokens: ["полный", "домашний", "покой"],
    extraEnTokens: ["complete", "home", "rest"],
  },

  [phraseKey("predpísať", "b1-4")]: {
    sk: "Doktorka mi predpísala antibiotiká.",
    ua: "Лікарка призначила мені антибіотики.",
    ru: "Врач назначила мне антибиотики.",
    en: "The doctor prescribed antibiotics for me.",
    uaTokens: ["Лікарка", "призначила", "мені", "антибіотики", "."],
    ruTokens: ["Врач", "назначила", "мне", "антибиотики", "."],
    enTokens: ["The", "doctor", "prescribed", "antibiotics", "for", "me", "."],
    extraUaTokens: ["нові", "сильні", "сьогодні"],
    extraRuTokens: ["новые", "сильные", "сегодня"],
    extraEnTokens: ["new", "strong", "today"],
  },

  [phraseKey("zhoršiť sa", "b1-4")]: {
    sk: "V noci sa mi stav zhoršil a mal som horúčku.",
    ua: "Вночі мій стан погіршився, і в мене була температура.",
    ru: "Ночью моё состояние ухудшилось, и у меня была температура.",
    en: "At night, my condition worsened and I had a fever.",
    uaTokens: ["Вночі", "мій", "стан", "погіршився", ",", "і", "в", "мене", "була", "температура", "."],
    ruTokens: ["Ночью", "моё", "состояние", "ухудшилось", ",", "и", "у", "меня", "была", "температура", "."],
    enTokens: ["At", "night", ",", "my", "condition", "worsened", "and", "I", "had", "a", "fever", "."],
    extraUaTokens: ["висока", "знову", "сильно"],
    extraRuTokens: ["высокая", "снова", "сильно"],
    extraEnTokens: ["high", "again", "badly"],
  },

  [phraseKey("zlepšiť sa", "b1-4")]: {
    sk: "Po liekoch sa mi výrazne zlepšilo dýchanie.",
    ua: "Після ліків у мене помітно покращилося дихання.",
    ru: "После лекарств у меня заметно улучшилось дыхание.",
    en: "After the medicine, my breathing improved noticeably.",
    uaTokens: ["Після", "ліків", "у", "мене", "помітно", "покращилося", "дихання", "."],
    ruTokens: ["После", "лекарств", "у", "меня", "заметно", "улучшилось", "дыхание", "."],
    enTokens: ["After", "the", "medicine", ",", "my", "breathing", "improved", "noticeably", "."],
    extraUaTokens: ["вже", "сьогодні", "значно"],
    extraRuTokens: ["уже", "сегодня", "значительно"],
    extraEnTokens: ["already", "today", "significantly"],
  },

  [phraseKey("hospitalizácia", "b1-4")]: {
    sk: "Hospitalizácia nebola nutná, stačila domáca liečba.",
    ua: "Госпіталізація не була потрібна, вистачило домашнього лікування.",
    ru: "Госпитализация не понадобилась, хватило домашнего лечения.",
    en: "Hospitalization was not necessary; home treatment was enough.",
    uaTokens: ["Госпіталізація", "не", "була", "потрібна", ",", "вистачило", "домашнього", "лікування", "."],
    ruTokens: ["Госпитализация", "не", "понадобилась", ",", "хватило", "домашнего", "лечения", "."],
    enTokens: ["Hospitalization", "was", "not", "necessary", ";", "home", "treatment", "was", "enough", "."],
    extraUaTokens: ["цього", "разу", "лише"],
    extraRuTokens: ["этот", "раз", "только"],
    extraEnTokens: ["this", "time", "only"],
  },

  [phraseKey("príznak", "b1-4")]: {
    sk: "Hlavný príznak bol silný kašeľ.",
    ua: "Головним симптомом був сильний кашель.",
    ru: "Главным симптомом был сильный кашель.",
    en: "The main symptom was a severe cough.",
    uaTokens: ["Головним", "симптомом", "був", "сильний", "кашель", "."],
    ruTokens: ["Главным", "симптомом", "был", "сильный", "кашель", "."],
    enTokens: ["The", "main", "symptom", "was", "a", "severe", "cough", "."],
    extraUaTokens: ["сухий", "дуже", "довгий"],
    extraRuTokens: ["сухой", "очень", "долгий"],
    extraEnTokens: ["dry", "very", "long"],
  },

  [phraseKey("zdravotný stav", "b1-4")]: {
    sk: "Môj zdravotný stav sa postupne stabilizuje.",
    ua: "Мій стан здоров’я поступово стабілізується.",
    ru: "Моё состояние здоровья постепенно стабилизируется.",
    en: "My health condition is gradually stabilizing.",
    uaTokens: ["Мій", "стан", "здоров’я", "поступово", "стабілізується", "."],
    ruTokens: ["Моё", "состояние", "здоровья", "постепенно", "стабилизируется", "."],
    enTokens: ["My", "health", "condition", "is", "gradually", "stabilizing", "."],
    extraUaTokens: ["вже", "нарешті", "добре"],
    extraRuTokens: ["уже", "наконец", "хорошо"],
    extraEnTokens: ["already", "finally", "well"],
  },

  [phraseKey("zotavenie", "b1-4")]: {
    sk: "Na úplné zotavenie potrebujem ešte pár dní.",
    ua: "Для повного одужання мені потрібно ще кілька днів.",
    ru: "Для полного выздоровления мне нужно ещё несколько дней.",
    en: "I need a few more days for a full recovery.",
    uaTokens: ["Для", "повного", "одужання", "мені", "потрібно", "ще", "кілька", "днів", "."],
    ruTokens: ["Для", "полного", "выздоровления", "мне", "нужно", "ещё", "несколько", "дней", "."],
    enTokens: ["I", "need", "a", "few", "more", "days", "for", "a", "full", "recovery", "."],
    extraUaTokens: ["спокою", "вдома", "трохи"],
    extraRuTokens: ["покоя", "дома", "немного"],
    extraEnTokens: ["rest", "at", "home"],
  },

  [phraseKey("predpis", "b1-4")]: {
    sk: "Dodržiavam predpis a beriem lieky pravidelne.",
    ua: "Я дотримуюся призначення і приймаю ліки регулярно.",
    ru: "Я соблюдаю предписание и принимаю лекарства регулярно.",
    en: "I follow the prescription and take the medicine regularly.",
    uaTokens: ["Я", "дотримуюся", "призначення", "і", "приймаю", "ліки", "регулярно", "."],
    ruTokens: ["Я", "соблюдаю", "предписание", "и", "принимаю", "лекарства", "регулярно", "."],
    enTokens: ["I", "follow", "the", "prescription", "and", "take", "the", "medicine", "regularly", "."],
    extraUaTokens: ["щодня", "сумлінно", "всі"],
    extraRuTokens: ["ежедневно", "добросовестно", "все"],
    extraEnTokens: ["daily", "carefully", "all"],
  },

  // =========================
  // LESSON 5 — Emócie a vzťahy
  // =========================
  [phraseKey("hádka", "b1-5")]: {
    sk: "Včera sme mali hádku kvôli maličkosti.",
    ua: "Вчора ми посварилися через дрібницю.",
    ru: "Вчера мы поссорились из-за мелочи.",
    en: "Yesterday we had an argument over a small thing.",
    uaTokens: ["Вчора", "ми", "посварилися", "через", "дрібницю", "."],
    ruTokens: ["Вчера", "мы", "поссорились", "из-за", "мелочи", "."],
    enTokens: ["Yesterday", "we", "had", "an", "argument", "over", "a", "small", "thing", "."],
    extraUaTokens: ["зовсім", "непотрібну", "маленьку"],
    extraRuTokens: ["совсем", "ненужную", "маленькую"],
    extraEnTokens: ["completely", "unnecessary", "tiny"],
  },

  [phraseKey("zmierenie", "b1-5")]: {
    sk: "Po rozhovore prišlo zmierenie a úľava.",
    ua: "Після розмови настало примирення і полегшення.",
    ru: "После разговора пришло примирение и облегчение.",
    en: "After the conversation, reconciliation and relief came.",
    uaTokens: ["Після", "розмови", "настало", "примирення", "і", "полегшення", "."],
    ruTokens: ["После", "разговора", "пришло", "примирение", "и", "облегчение", "."],
    enTokens: ["After", "the", "conversation", ",", "reconciliation", "and", "relief", "came", "."],
    extraUaTokens: ["нарешті", "велике", "справжнє"],
    extraRuTokens: ["наконец", "большое", "настоящее"],
    extraEnTokens: ["finally", "great", "real"],
  },

  [phraseKey("sklamať", "b1-5")]: {
    sk: "Nechcel som ťa sklamať, len som to nestihol.",
    ua: "Я не хотів тебе розчарувати, я просто не встиг.",
    ru: "Я не хотел тебя разочаровать, я просто не успел.",
    en: "I didn’t want to disappoint you; I just didn’t make it in time.",
    uaTokens: ["Я", "не", "хотів", "тебе", "розчарувати", ",", "я", "просто", "не", "встиг", "."],
    ruTokens: ["Я", "не", "хотел", "тебя", "разочаровать", ",", "я", "просто", "не", "успел", "."],
    enTokens: ["I", "didn’t", "want", "to", "disappoint", "you", ";", "I", "just", "didn’t", "make", "it", "in", "time", "."],
    extraUaTokens: ["тоді", "зовсім", "чесно"],
    extraRuTokens: ["тогда", "совсем", "честно"],
    extraEnTokens: ["then", "at", "all"],
  },

  [phraseKey("oceniť", "b1-5")]: {
    sk: "Veľmi si vážim, že to vieš oceniť.",
    ua: "Я дуже ціную, що ти вмієш це оцінити.",
    ru: "Я очень ценю, что ты умеешь это оценить.",
    en: "I really appreciate that you know how to value it.",
    uaTokens: ["Я", "дуже", "ціную", ",", "що", "ти", "вмієш", "це", "оцінити", "."],
    ruTokens: ["Я", "очень", "ценю", ",", "что", "ты", "умеешь", "это", "оценить", "."],
    enTokens: ["I", "really", "appreciate", "that", "you", "know", "how", "to", "value", "it", "."],
    extraUaTokens: ["справді", "добре", "правильно"],
    extraRuTokens: ["действительно", "хорошо", "правильно"],
    extraEnTokens: ["really", "well", "properly"],
  },

  [phraseKey("žiarlivosť", "b1-5")]: {
    sk: "Žiarlivosť často zničí aj dobrý vzťah.",
    ua: "Ревнощі часто руйнують навіть хороші стосунки.",
    ru: "Ревность часто разрушает даже хорошие отношения.",
    en: "Jealousy often destroys even a good relationship.",
    uaTokens: ["Ревнощі", "часто", "руйнують", "навіть", "хороші", "стосунки", "."],
    ruTokens: ["Ревность", "часто", "разрушает", "даже", "хорошие", "отношения", "."],
    enTokens: ["Jealousy", "often", "destroys", "even", "a", "good", "relationship", "."],
    extraUaTokens: ["дуже", "міцні", "інколи"],
    extraRuTokens: ["очень", "крепкие", "иногда"],
    extraEnTokens: ["very", "strong", "sometimes"],
  },

  [phraseKey("odpustiť", "b1-5")]: {
    sk: "Dokážem odpustiť, ale potrebujem čas.",
    ua: "Я можу пробачити, але мені потрібен час.",
    ru: "Я могу простить, но мне нужно время.",
    en: "I can forgive, but I need time.",
    uaTokens: ["Я", "можу", "пробачити", ",", "але", "мені", "потрібен", "час", "."],
    ruTokens: ["Я", "могу", "простить", ",", "но", "мне", "нужно", "время", "."],
    enTokens: ["I", "can", "forgive", ",", "but", "I", "need", "time", "."],
    extraUaTokens: ["ще", "трохи", "більше"],
    extraRuTokens: ["ещё", "немного", "больше"],
    extraEnTokens: ["still", "a", "bit"],
  },

  [phraseKey("rešpekt", "b1-5")]: {
    sk: "Bez rešpektu sa nedá budovať dôvera.",
    ua: "Без поваги неможливо будувати довіру.",
    ru: "Без уважения невозможно строить доверие.",
    en: "Without respect, trust cannot be built.",
    uaTokens: ["Без", "поваги", "неможливо", "будувати", "довіру", "."],
    ruTokens: ["Без", "уважения", "невозможно", "строить", "доверие", "."],
    enTokens: ["Without", "respect", ",", "trust", "cannot", "be", "built", "."],
    extraUaTokens: ["між", "людьми", "справжню"],
    extraRuTokens: ["между", "людьми", "настоящее"],
    extraEnTokens: ["between", "people", "real"],
  },

  [phraseKey("uraziť sa", "b1-5")]: {
    sk: "Neuraz sa, len som povedal svoj názor.",
    ua: "Не ображайся, я просто сказав свою думку.",
    ru: "Не обижайся, я просто сказал своё мнение.",
    en: "Don’t be offended; I just said my opinion.",
    uaTokens: ["Не", "ображайся", ",", "я", "просто", "сказав", "свою", "думку", "."],
    ruTokens: ["Не", "обижайся", ",", "я", "просто", "сказал", "своё", "мнение", "."],
    enTokens: ["Don’t", "be", "offended", ";", "I", "just", "said", "my", "opinion", "."],
    extraUaTokens: ["чесно", "лише", "відверто"],
    extraRuTokens: ["честно", "только", "откровенно"],
    extraEnTokens: ["honestly", "only", "openly"],
  },

  [phraseKey("zblížiť sa", "b1-5")]: {
    sk: "Na výlete sme sa viac zblížili.",
    ua: "Під час поїздки ми більше зблизилися.",
    ru: "Во время поездки мы больше сблизились.",
    en: "During the trip, we grew closer.",
    uaTokens: ["Під", "час", "поїздки", "ми", "більше", "зблизилися", "."],
    ruTokens: ["Во", "время", "поездки", "мы", "больше", "сблизились", "."],
    enTokens: ["During", "the", "trip", ",", "we", "grew", "closer", "."],
    extraUaTokens: ["дуже", "тоді", "разом"],
    extraRuTokens: ["очень", "тогда", "вместе"],
    extraEnTokens: ["very", "then", "together"],
  },

  [phraseKey("vzťah", "b1-5")]: {
    sk: "Dobrý vzťah stojí na úprimnosti a komunikácii.",
    ua: "Хороші стосунки тримаються на щирості та спілкуванні.",
    ru: "Хорошие отношения держатся на искренности и общении.",
    en: "A good relationship is built on honesty and communication.",
    uaTokens: ["Хороші", "стосунки", "тримаються", "на", "щирості", "та", "спілкуванні", "."],
    ruTokens: ["Хорошие", "отношения", "держатся", "на", "искренности", "и", "общении", "."],
    enTokens: ["A", "good", "relationship", "is", "built", "on", "honesty", "and", "communication", "."],
    extraUaTokens: ["взаємному", "довірі", "також"],
    extraRuTokens: ["взаимном", "доверии", "также"],
    extraEnTokens: ["mutual", "trust", "also"],
  },
};