import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const B1_BUILD_UA_SENTENCES_5: BuildUaSentenceDict = {
  // =========================
  // LESSON 21 — Krajiny
  // =========================
  [phraseKey("Slovensko", "b1-21")]: {
    sk: "Na Slovensku žijem už niekoľko rokov a cítim sa tu dobre.",
    ua: "У Словаччині я живу вже кілька років і почуваюся тут добре.",
    ru: "В Словакии я живу уже несколько лет и чувствую себя здесь хорошо.",
    en: "I have been living in Slovakia for several years already, and I feel good here.",
    uaTokens: ["У", "Словаччині", "я", "живу", "вже", "кілька", "років", "і", "почуваюся", "тут", "добре", "."],
    ruTokens: ["В", "Словакии", "я", "живу", "уже", "несколько", "лет", "и", "чувствую", "себя", "здесь", "хорошо", "."],
    enTokens: ["I", "have", "been", "living", "in", "Slovakia", "for", "several", "years", "already", ",", "and", "I", "feel", "good", "here", "."],
    extraUaTokens: ["дуже", "справді", "вже"],
    extraRuTokens: ["очень", "действительно", "уже"],
    extraEnTokens: ["really", "very", "now"],
  },

  [phraseKey("Česko", "b1-21")]: {
    sk: "Do Česka sa dá ísť rýchlo aj vlakom.",
    ua: "До Чехії можна швидко доїхати навіть потягом.",
    ru: "До Чехии можно быстро доехать даже поездом.",
    en: "You can get to the Czech Republic quickly even by train.",
    uaTokens: ["До", "Чехії", "можна", "швидко", "доїхати", "навіть", "потягом", "."],
    ruTokens: ["До", "Чехии", "можно", "быстро", "доехать", "даже", "поездом", "."],
    enTokens: ["You", "can", "get", "to", "the", "Czech", "Republic", "quickly", "even", "by", "train", "."],
    extraUaTokens: ["звідси", "дуже", "легко"],
    extraRuTokens: ["отсюда", "очень", "легко"],
    extraEnTokens: ["from", "here", "easily"],
  },

  [phraseKey("Poľsko", "b1-21")]: {
    sk: "Poľsko má veľa krásnych miest, ktoré stoja za návštevu.",
    ua: "У Польщі багато гарних місць, які варто відвідати.",
    ru: "В Польше много красивых мест, которые стоит посетить.",
    en: "Poland has many beautiful places that are worth visiting.",
    uaTokens: ["У", "Польщі", "багато", "гарних", "місць", ",", "які", "варто", "відвідати", "."],
    ruTokens: ["В", "Польше", "много", "красивых", "мест", ",", "которые", "стоит", "посетить", "."],
    enTokens: ["Poland", "has", "many", "beautiful", "places", "that", "are", "worth", "visiting", "."],
    extraUaTokens: ["справді", "дуже", "різних"],
    extraRuTokens: ["действительно", "очень", "разных"],
    extraEnTokens: ["really", "very", "different"],
  },

  [phraseKey("Nemecko", "b1-21")]: {
    sk: "V Nemecku je doprava často veľmi dobre organizovaná.",
    ua: "У Німеччині транспорт часто дуже добре організований.",
    ru: "В Германии транспорт часто очень хорошо организован.",
    en: "In Germany, transport is often very well organized.",
    uaTokens: ["У", "Німеччині", "транспорт", "часто", "дуже", "добре", "організований", "."],
    ruTokens: ["В", "Германии", "транспорт", "часто", "очень", "хорошо", "организован", "."],
    enTokens: ["In", "Germany", ",", "transport", "is", "often", "very", "well", "organized", "."],
    extraUaTokens: ["там", "справді", "все"],
    extraRuTokens: ["там", "действительно", "всё"],
    extraEnTokens: ["there", "really", "everything"],
  },

  [phraseKey("Rakúsko", "b1-21")]: {
    sk: "Rakúsko je blízko, takže tam chodíme na výlety.",
    ua: "Австрія близько, тому ми їздимо туди на екскурсії.",
    ru: "Австрия рядом, поэтому мы ездим туда на экскурсии.",
    en: "Austria is close, so we go there on trips.",
    uaTokens: ["Австрія", "близько", ",", "тому", "ми", "їздимо", "туди", "на", "екскурсії", "."],
    ruTokens: ["Австрия", "рядом", ",", "поэтому", "мы", "ездим", "туда", "на", "экскурсии", "."],
    enTokens: ["Austria", "is", "close", ",", "so", "we", "go", "there", "on", "trips", "."],
    extraUaTokens: ["часто", "ще", "звідси"],
    extraRuTokens: ["часто", "ещё", "отсюда"],
    extraEnTokens: ["often", "still", "from"],
  },

  [phraseKey("Maďarsko", "b1-21")]: {
    sk: "Do Maďarska sa mi páči ísť kvôli jedlu a kúpeľom.",
    ua: "Мені подобається їздити в Угорщину через їжу та термальні купальні.",
    ru: "Мне нравится ездить в Венгрию из-за еды и термальных купален.",
    en: "I like going to Hungary because of the food and thermal baths.",
    uaTokens: ["Мені", "подобається", "їздити", "в", "Угорщину", "через", "їжу", "та", "термальні", "купальні", "."],
    ruTokens: ["Мне", "нравится", "ездить", "в", "Венгрию", "из-за", "еды", "и", "термальных", "купален", "."],
    enTokens: ["I", "like", "going", "to", "Hungary", "because", "of", "the", "food", "and", "thermal", "baths", "."],
    extraUaTokens: ["дуже", "туди", "іноді"],
    extraRuTokens: ["очень", "туда", "иногда"],
    extraEnTokens: ["really", "there", "sometimes"],
  },

  [phraseKey("Francúzsko", "b1-21")]: {
    sk: "Francúzsko je známe kultúrou, módou aj gastronómiou.",
    ua: "Франція відома культурою, модою та гастрономією.",
    ru: "Франция известна культурой, модой и гастрономией.",
    en: "France is known for its culture, fashion, and gastronomy.",
    uaTokens: ["Франція", "відома", "культурою", ",", "модою", "та", "гастрономією", "."],
    ruTokens: ["Франция", "известна", "культурой", ",", "модой", "и", "гастрономией", "."],
    enTokens: ["France", "is", "known", "for", "its", "culture", ",", "fashion", ",", "and", "gastronomy", "."],
    extraUaTokens: ["дуже", "своєю", "також"],
    extraRuTokens: ["очень", "своей", "также"],
    extraEnTokens: ["very", "its", "also"],
  },

  [phraseKey("Taliansko", "b1-21")]: {
    sk: "V Taliansku by som chcel vidieť Rím a ochutnať pravú pizzu.",
    ua: "В Італії я хотів би побачити Рим і скуштувати справжню піцу.",
    ru: "В Италии я хотел бы увидеть Рим и попробовать настоящую пиццу.",
    en: "In Italy, I would like to see Rome and taste real pizza.",
    uaTokens: ["В", "Італії", "я", "хотів", "би", "побачити", "Рим", "і", "скуштувати", "справжню", "піцу", "."],
    ruTokens: ["В", "Италии", "я", "хотел", "бы", "увидеть", "Рим", "и", "попробовать", "настоящую", "пиццу", "."],
    enTokens: ["In", "Italy", ",", "I", "would", "like", "to", "see", "Rome", "and", "taste", "real", "pizza", "."],
    extraUaTokens: ["дуже", "там", "колись"],
    extraRuTokens: ["очень", "там", "когда-нибудь"],
    extraEnTokens: ["really", "there", "someday"],
  },

  [phraseKey("Španielsko", "b1-21")]: {
    sk: "Španielsko má teplé podnebie a veľmi živé mestá.",
    ua: "Іспанія має теплий клімат і дуже жваві міста.",
    ru: "Испания имеет тёплый климат и очень оживлённые города.",
    en: "Spain has a warm climate and very lively cities.",
    uaTokens: ["Іспанія", "має", "теплий", "клімат", "і", "дуже", "жваві", "міста", "."],
    ruTokens: ["Испания", "имеет", "тёплый", "климат", "и", "очень", "оживлённые", "города", "."],
    enTokens: ["Spain", "has", "a", "warm", "climate", "and", "very", "lively", "cities", "."],
    extraUaTokens: ["справді", "також", "влітку"],
    extraRuTokens: ["действительно", "также", "летом"],
    extraEnTokens: ["really", "also", "summer"],
  },

  [phraseKey("Ukrajina", "b1-21")]: {
    sk: "Ukrajina má bohatú tradíciu a silnú kultúru.",
    ua: "Україна має багаті традиції та сильну культуру.",
    ru: "Украина имеет богатые традиции и сильную культуру.",
    en: "Ukraine has rich traditions and a strong culture.",
    uaTokens: ["Україна", "має", "багаті", "традиції", "та", "сильну", "культуру", "."],
    ruTokens: ["Украина", "имеет", "богатые", "традиции", "и", "сильную", "культуру", "."],
    enTokens: ["Ukraine", "has", "rich", "traditions", "and", "a", "strong", "culture", "."],
    extraUaTokens: ["дуже", "свою", "глибоку"],
    extraRuTokens: ["очень", "свою", "глубокую"],
    extraEnTokens: ["very", "its", "deep"],
  },

  // =========================
  // LESSON 22 — Médiá a informácie
  // =========================
  [phraseKey("tlač", "b1-22")]: {
    sk: "Tlač často zverejňuje rôzne názory na tú istú tému.",
    ua: "Преса часто публікує різні погляди на одну й ту саму тему.",
    ru: "Пресса часто публикует разные мнения на одну и ту же тему.",
    en: "The press often publishes different views on the same topic.",
    uaTokens: ["Преса", "часто", "публікує", "різні", "погляди", "на", "одну", "й", "ту", "саму", "тему", "."],
    ruTokens: ["Пресса", "часто", "публикует", "разные", "мнения", "на", "одну", "и", "ту", "же", "тему", "."],
    enTokens: ["The", "press", "often", "publishes", "different", "views", "on", "the", "same", "topic", "."],
    extraUaTokens: ["сьогодні", "також", "ще"],
    extraRuTokens: ["сегодня", "также", "ещё"],
    extraEnTokens: ["today", "also", "still"],
  },

  [phraseKey("noviny", "b1-22")]: {
    sk: "Noviny si kupujem zriedka, skôr čítam správy online.",
    ua: "Газети купую рідко, частіше читаю новини онлайн.",
    ru: "Газеты покупаю редко, чаще читаю новости онлайн.",
    en: "I rarely buy newspapers; I usually read news online.",
    uaTokens: ["Газети", "купую", "рідко", ",", "частіше", "читаю", "новини", "онлайн", "."],
    ruTokens: ["Газеты", "покупаю", "редко", ",", "чаще", "читаю", "новости", "онлайн", "."],
    enTokens: ["I", "rarely", "buy", "newspapers", ";", "I", "usually", "read", "news", "online", "."],
    extraUaTokens: ["я", "зараз", "вже"],
    extraRuTokens: ["я", "сейчас", "уже"],
    extraEnTokens: ["I", "now", "already"],
  },

  [phraseKey("televízia", "b1-22")]: {
    sk: "V televízii pozerám hlavne dokumenty a správy.",
    ua: "По телевізору я дивлюся переважно документальні фільми та новини.",
    ru: "По телевизору я смотрю в основном документальные фильмы и новости.",
    en: "On TV, I mostly watch documentaries and news.",
    uaTokens: ["По", "телевізору", "я", "дивлюся", "переважно", "документальні", "фільми", "та", "новини", "."],
    ruTokens: ["По", "телевизору", "я", "смотрю", "в", "основном", "документальные", "фильмы", "и", "новости", "."],
    enTokens: ["On", "TV", ",", "I", "mostly", "watch", "documentaries", "and", "news", "."],
    extraUaTokens: ["увечері", "лише", "зазвичай"],
    extraRuTokens: ["вечером", "только", "обычно"],
    extraEnTokens: ["evening", "only", "usually"],
  },

  [phraseKey("rozhlas", "b1-22")]: {
    sk: "Rozhlas počúvam v aute, keď cestujem do práce.",
    ua: "Радіо слухаю в машині, коли їду на роботу.",
    ru: "Радио слушаю в машине, когда еду на работу.",
    en: "I listen to the radio in the car when I travel to work.",
    uaTokens: ["Радіо", "слухаю", "в", "машині", ",", "коли", "їду", "на", "роботу", "."],
    ruTokens: ["Радио", "слушаю", "в", "машине", ",", "когда", "еду", "на", "работу", "."],
    enTokens: ["I", "listen", "to", "the", "radio", "in", "the", "car", "when", "I", "travel", "to", "work", "."],
    extraUaTokens: ["часто", "вранці", "саме"],
    extraRuTokens: ["часто", "утром", "именно"],
    extraEnTokens: ["often", "morning", "exactly"],
  },

  [phraseKey("vysielanie", "b1-22")]: {
    sk: "Vysielanie bolo prerušené kvôli technickým problémom.",
    ua: "Трансляцію перервали через технічні проблеми.",
    ru: "Вещание прервали из-за технических проблем.",
    en: "The broadcast was interrupted because of technical problems.",
    uaTokens: ["Трансляцію", "перервали", "через", "технічні", "проблеми", "."],
    ruTokens: ["Вещание", "прервали", "из-за", "технических", "проблем", "."],
    enTokens: ["The", "broadcast", "was", "interrupted", "because", "of", "technical", "problems", "."],
    extraUaTokens: ["серйозні", "ці", "раптом"],
    extraRuTokens: ["серьёзные", "эти", "вдруг"],
    extraEnTokens: ["serious", "these", "suddenly"],
  },

  [phraseKey("reklama", "b1-22")]: {
    sk: "Reklama môže ovplyvniť rozhodnutie, ale nie vždy.",
    ua: "Реклама може вплинути на рішення, але не завжди.",
    ru: "Реклама может повлиять на решение, но не всегда.",
    en: "Advertising can influence a decision, but not always.",
    uaTokens: ["Реклама", "може", "вплинути", "на", "рішення", ",", "але", "не", "завжди", "."],
    ruTokens: ["Реклама", "может", "повлиять", "на", "решение", ",", "но", "не", "всегда", "."],
    enTokens: ["Advertising", "can", "influence", "a", "decision", ",", "but", "not", "always", "."],
    extraUaTokens: ["сильно", "дуже", "так"],
    extraRuTokens: ["сильно", "очень", "так"],
    extraEnTokens: ["strongly", "very", "so"],
  },

  [phraseKey("redaktor", "b1-22")]: {
    sk: "Redaktor sa ma pýtal na detaily, aby mal presné informácie.",
    ua: "Журналіст питав мене про деталі, щоб мати точну інформацію.",
    ru: "Журналист спрашивал меня о деталях, чтобы иметь точную информацию.",
    en: "The journalist asked me about details to have accurate information.",
    uaTokens: ["Журналіст", "питав", "мене", "про", "деталі", ",", "щоб", "мати", "точну", "інформацію", "."],
    ruTokens: ["Журналист", "спрашивал", "меня", "о", "деталях", ",", "чтобы", "иметь", "точную", "информацию", "."],
    enTokens: ["The", "journalist", "asked", "me", "about", "details", "to", "have", "accurate", "information", "."],
    extraUaTokens: ["усю", "ще", "необхідну"],
    extraRuTokens: ["всю", "ещё", "необходимую"],
    extraEnTokens: ["all", "still", "necessary"],
  },

  [phraseKey("titulok", "b1-22")]: {
    sk: "Titulok znel dramaticky, ale článok bol vyvážený.",
    ua: "Заголовок звучав драматично, але стаття була збалансована.",
    ru: "Заголовок звучал драматично, но статья была сбалансированной.",
    en: "The headline sounded dramatic, but the article was balanced.",
    uaTokens: ["Заголовок", "звучав", "драматично", ",", "але", "стаття", "була", "збалансована", "."],
    ruTokens: ["Заголовок", "звучал", "драматично", ",", "но", "статья", "была", "сбалансированной", "."],
    enTokens: ["The", "headline", "sounded", "dramatic", ",", "but", "the", "article", "was", "balanced", "."],
    extraUaTokens: ["дуже", "хоча", "не"],
    extraRuTokens: ["очень", "хотя", "не"],
    extraEnTokens: ["very", "although", "not"],
  },

  [phraseKey("uveriť", "b1-22")]: {
    sk: "Nie je ľahké uveriť všetkému, čo sa píše na internete.",
    ua: "Не так легко повірити всьому, що пишуть в інтернеті.",
    ru: "Не так легко поверить всему, что пишут в интернете.",
    en: "It is not easy to believe everything that is written on the internet.",
    uaTokens: ["Не", "так", "легко", "повірити", "всьому", ",", "що", "пишуть", "в", "інтернеті", "."],
    ruTokens: ["Не", "так", "легко", "поверить", "всему", ",", "что", "пишут", "в", "интернете", "."],
    enTokens: ["It", "is", "not", "easy", "to", "believe", "everything", "that", "is", "written", "on", "the", "internet", "."],
    extraUaTokens: ["одразу", "там", "просто"],
    extraRuTokens: ["сразу", "там", "просто"],
    extraEnTokens: ["immediately", "there", "simply"],
  },

  [phraseKey("verejná myšlienka", "b1-22")]: {
    sk: "Verejná myšlienka sa môže rýchlo zmeniť po jednej udalosti.",
    ua: "Громадська думка може швидко змінитися після однієї події.",
    ru: "Общественное мнение может быстро измениться после одного события.",
    en: "Public opinion can change quickly after a single event.",
    uaTokens: ["Громадська", "думка", "може", "швидко", "змінитися", "після", "однієї", "події", "."],
    ruTokens: ["Общественное", "мнение", "может", "быстро", "измениться", "после", "одного", "события", "."],
    enTokens: ["Public", "opinion", "can", "change", "quickly", "after", "a", "single", "event", "."],
    extraUaTokens: ["дуже", "сильно", "раптом"],
    extraRuTokens: ["очень", "сильно", "вдруг"],
    extraEnTokens: ["very", "strongly", "suddenly"],
  },

  // =========================
  // LESSON 23 — Internet a sociálne siete
  // =========================
  [phraseKey("webová stránka", "b1-23")]: {
    sk: "Na webovej stránke nájdeš všetky informácie aj kontakty.",
    ua: "На вебсайті знайдеш всю інформацію та контакти.",
    ru: "На веб-сайте найдёшь всю информацию и контакты.",
    en: "On the website, you will find all the information and contacts.",
    uaTokens: ["На", "вебсайті", "знайдеш", "всю", "інформацію", "та", "контакти", "."],
    ruTokens: ["На", "веб-сайте", "найдёшь", "всю", "информацию", "и", "контакты", "."],
    enTokens: ["On", "the", "website", ",", "you", "will", "find", "all", "the", "information", "and", "contacts", "."],
    extraUaTokens: ["там", "легко", "усю"],
    extraRuTokens: ["там", "легко", "всю"],
    extraEnTokens: ["there", "easily", "all"],
  },

  [phraseKey("sledovateľ", "b1-23")]: {
    sk: "Mám viac sledovateľov, odkedy zverejňujem pravidelne.",
    ua: "У мене більше підписників відтоді, як я публікую регулярно.",
    ru: "У меня больше подписчиков с тех пор, как я публикую регулярно.",
    en: "I have had more followers since I started posting regularly.",
    uaTokens: ["У", "мене", "більше", "підписників", "відтоді", ",", "як", "я", "публікую", "регулярно", "."],
    ruTokens: ["У", "меня", "больше", "подписчиков", "с", "тех", "пор", ",", "как", "я", "публикую", "регулярно", "."],
    enTokens: ["I", "have", "had", "more", "followers", "since", "I", "started", "posting", "regularly", "."],
    extraUaTokens: ["вже", "значно", "тепер"],
    extraRuTokens: ["уже", "значительно", "теперь"],
    extraEnTokens: ["already", "significantly", "now"],
  },

  [phraseKey("online", "b1-23")]: {
    sk: "Som online len večer, cez deň pracujem.",
    ua: "Я онлайн лише ввечері, вдень працюю.",
    ru: "Я онлайн только вечером, днём работаю.",
    en: "I am online only in the evening; during the day I work.",
    uaTokens: ["Я", "онлайн", "лише", "ввечері", ",", "вдень", "працюю", "."],
    ruTokens: ["Я", "онлайн", "только", "вечером", ",", "днём", "работаю", "."],
    enTokens: ["I", "am", "online", "only", "in", "the", "evening", ";", "during", "the", "day", "I", "work", "."],
    extraUaTokens: ["зазвичай", "тому", "лише"],
    extraRuTokens: ["обычно", "поэтому", "лишь"],
    extraEnTokens: ["usually", "therefore", "only"],
  },

  [phraseKey("offline", "b1-23")]: {
    sk: "Keď som offline, aspoň ma nič neruší.",
    ua: "Коли я офлайн, мене принаймні нічого не відволікає.",
    ru: "Когда я офлайн, меня по крайней мере ничто не отвлекает.",
    en: "When I am offline, at least nothing distracts me.",
    uaTokens: ["Коли", "я", "офлайн", ",", "мене", "принаймні", "нічого", "не", "відволікає", "."],
    ruTokens: ["Когда", "я", "офлайн", ",", "меня", "по", "крайней", "мере", "ничто", "не", "отвлекает", "."],
    enTokens: ["When", "I", "am", "offline", ",", "at", "least", "nothing", "distracts", "me", "."],
    extraUaTokens: ["тоді", "майже", "вже"],
    extraRuTokens: ["тогда", "почти", "уже"],
    extraEnTokens: ["then", "almost", "already"],
  },

  [phraseKey("profil", "b1-23")]: {
    sk: "Profil mám nastavený ako súkromný, aby som mal viac pokoja.",
    ua: "Профіль у мене приватний, щоб мати більше спокою.",
    ru: "Профиль у меня закрытый, чтобы было больше спокойствия.",
    en: "My profile is set to private so that I can have more peace.",
    uaTokens: ["Профіль", "у", "мене", "приватний", ",", "щоб", "мати", "більше", "спокою", "."],
    ruTokens: ["Профиль", "у", "меня", "закрытый", ",", "чтобы", "было", "больше", "спокойствия", "."],
    enTokens: ["My", "profile", "is", "set", "to", "private", "so", "that", "I", "can", "have", "more", "peace", "."],
    extraUaTokens: ["особистого", "ще", "трохи"],
    extraRuTokens: ["личного", "ещё", "немного"],
    extraEnTokens: ["personal", "more", "little"],
  },

  [phraseKey("komentovať", "b1-23")]: {
    sk: "Nemusíš to komentovať hneď, najprv si to premysli.",
    ua: "Не обов’язково коментувати одразу, спершу подумай.",
    ru: "Не обязательно комментировать сразу, сначала подумай.",
    en: "You do not have to comment on it right away; think first.",
    uaTokens: ["Не", "обов’язково", "коментувати", "одразу", ",", "спершу", "подумай", "."],
    ruTokens: ["Не", "обязательно", "комментировать", "сразу", ",", "сначала", "подумай", "."],
    enTokens: ["You", "do", "not", "have", "to", "comment", "on", "it", "right", "away", ";", "think", "first", "."],
    extraUaTokens: ["добре", "ще", "раз"],
    extraRuTokens: ["хорошо", "ещё", "раз"],
    extraEnTokens: ["well", "once", "again"],
  },

  [phraseKey("označiť", "b1-23")]: {
    sk: "Môžeš ma označiť na fotke, aby som to videl.",
    ua: "Можеш мене тегнути на фото, щоб я це побачив.",
    ru: "Можешь отметить меня на фото, чтобы я это увидел.",
    en: "You can tag me in the photo so that I can see it.",
    uaTokens: ["Можеш", "мене", "тегнути", "на", "фото", ",", "щоб", "я", "це", "побачив", "."],
    ruTokens: ["Можешь", "отметить", "меня", "на", "фото", ",", "чтобы", "я", "это", "увидел", "."],
    enTokens: ["You", "can", "tag", "me", "in", "the", "photo", "so", "that", "I", "can", "see", "it", "."],
    extraUaTokens: ["там", "також", "потім"],
    extraRuTokens: ["там", "также", "потом"],
    extraEnTokens: ["there", "also", "later"],
  },

  [phraseKey("zdieľať", "b1-23")]: {
    sk: "Ak je to užitočné, môžeš to zdieľať ďalej.",
    ua: "Якщо це корисно, можеш поширити це далі.",
    ru: "Если это полезно, можешь поделиться этим дальше.",
    en: "If it is useful, you can share it further.",
    uaTokens: ["Якщо", "це", "корисно", ",", "можеш", "поширити", "це", "далі", "."],
    ruTokens: ["Если", "это", "полезно", ",", "можешь", "поделиться", "этим", "дальше", "."],
    enTokens: ["If", "it", "is", "useful", ",", "you", "can", "share", "it", "further", "."],
    extraUaTokens: ["ще", "комусь", "спокійно"],
    extraRuTokens: ["ещё", "кому-то", "спокойно"],
    extraEnTokens: ["also", "someone", "calmly"],
  },

  [phraseKey("správa", "b1-23")]: {
    sk: "Poslal som ti správu, keď budeš mať čas, pozri si ju.",
    ua: "Я надіслав тобі повідомлення — як матимеш час, подивись.",
    ru: "Я отправил тебе сообщение — как будет время, посмотри.",
    en: "I sent you a message; when you have time, take a look.",
    uaTokens: ["Я", "надіслав", "тобі", "повідомлення", "—", "як", "матимеш", "час", ",", "подивись", "."],
    ruTokens: ["Я", "отправил", "тебе", "сообщение", "—", "как", "будет", "время", ",", "посмотри", "."],
    enTokens: ["I", "sent", "you", "a", "message", ";", "when", "you", "have", "time", ",", "take", "a", "look", "."],
    extraUaTokens: ["його", "будь", "ласка"],
    extraRuTokens: ["его", "пожалуйста"],
    extraEnTokens: ["it", "please", "later"],
  },

  [phraseKey("upozornenie", "b1-23")]: {
    sk: "Vypol som upozornenia, aby ma nič nevyrušovalo.",
    ua: "Я вимкнув сповіщення, щоб мене нічого не відволікало.",
    ru: "Я выключил уведомления, чтобы меня ничто не отвлекало.",
    en: "I turned off notifications so that nothing would distract me.",
    uaTokens: ["Я", "вимкнув", "сповіщення", ",", "щоб", "мене", "нічого", "не", "відволікало", "."],
    ruTokens: ["Я", "выключил", "уведомления", ",", "чтобы", "меня", "ничто", "не", "отвлекало", "."],
    enTokens: ["I", "turned", "off", "notifications", "so", "that", "nothing", "would", "distract", "me", "."],
    extraUaTokens: ["повністю", "всі", "зараз"],
    extraRuTokens: ["полностью", "все", "сейчас"],
    extraEnTokens: ["completely", "all", "now"],
  },

  // =========================
  // LESSON 24 — Na návšteve
  // =========================
  [phraseKey("pozvanie", "b1-24")]: {
    sk: "Dostal som pozvanie na večeru a veľmi ma to potešilo.",
    ua: "Я отримав запрошення на вечерю, і це мене дуже потішило.",
    ru: "Я получил приглашение на ужин, и это меня очень обрадовало.",
    en: "I received an invitation to dinner, and it made me very happy.",
    uaTokens: ["Я", "отримав", "запрошення", "на", "вечерю", ",", "і", "це", "мене", "дуже", "потішило", "."],
    ruTokens: ["Я", "получил", "приглашение", "на", "ужин", ",", "и", "это", "меня", "очень", "обрадовало", "."],
    enTokens: ["I", "received", "an", "invitation", "to", "dinner", ",", "and", "it", "made", "me", "very", "happy", "."],
    extraUaTokens: ["справді", "дуже", "вчора"],
    extraRuTokens: ["действительно", "очень", "вчера"],
    extraEnTokens: ["really", "very", "yesterday"],
  },

  [phraseKey("hostiteľ", "b1-24")]: {
    sk: "Hostiteľ nás privítal pri dverách s úsmevom.",
    ua: "Господар зустрів нас біля дверей з усмішкою.",
    ru: "Хозяин встретил нас у двери с улыбкой.",
    en: "The host welcomed us at the door with a smile.",
    uaTokens: ["Господар", "зустрів", "нас", "біля", "дверей", "з", "усмішкою", "."],
    ruTokens: ["Хозяин", "встретил", "нас", "у", "двери", "с", "улыбкой", "."],
    enTokens: ["The", "host", "welcomed", "us", "at", "the", "door", "with", "a", "smile", "."],
    extraUaTokens: ["одразу", "дуже", "щиро"],
    extraRuTokens: ["сразу", "очень", "искренне"],
    extraEnTokens: ["immediately", "very", "warmly"],
  },

  [phraseKey("hosť", "b1-24")]: {
    sk: "Ako hosť som sa snažil byť slušný a nenápadný.",
    ua: "Як гість я намагався бути ввічливим і ненав’язливим.",
    ru: "Как гость я старался быть вежливым и ненавязчивым.",
    en: "As a guest, I tried to be polite and unobtrusive.",
    uaTokens: ["Як", "гість", "я", "намагався", "бути", "ввічливим", "і", "ненав’язливим", "."],
    ruTokens: ["Как", "гость", "я", "старался", "быть", "вежливым", "и", "ненавязчивым", "."],
    enTokens: ["As", "a", "guest", ",", "I", "tried", "to", "be", "polite", "and", "unobtrusive", "."],
    extraUaTokens: ["там", "дуже", "просто"],
    extraRuTokens: ["там", "очень", "просто"],
    extraEnTokens: ["there", "very", "simply"],
  },

  [phraseKey("pohostenie", "b1-24")]: {
    sk: "Pohostenie bolo výborné, najmä domáci koláč.",
    ua: "Частування було чудове, особливо домашній пиріг.",
    ru: "Угощение было отличным, особенно домашний пирог.",
    en: "The treats were excellent, especially the homemade pie.",
    uaTokens: ["Частування", "було", "чудове", ",", "особливо", "домашній", "пиріг", "."],
    ruTokens: ["Угощение", "было", "отличным", ",", "особенно", "домашний", "пирог", "."],
    enTokens: ["The", "treats", "were", "excellent", ",", "especially", "the", "homemade", "pie", "."],
    extraUaTokens: ["дуже", "смачний", "той"],
    extraRuTokens: ["очень", "вкусный", "тот"],
    extraEnTokens: ["very", "tasty", "that"],
  },

  [phraseKey("priniesť darček", "b1-24")]: {
    sk: "Je slušné priniesť darček, aj keď len malú pozornosť.",
    ua: "Ввічливо принести подарунок, навіть якщо це маленька дрібничка.",
    ru: "Вежливо принести подарок, даже если это маленький знак внимания.",
    en: "It is polite to bring a gift, even if it is just a small token.",
    uaTokens: ["Ввічливо", "принести", "подарунок", ",", "навіть", "якщо", "це", "маленька", "дрібничка", "."],
    ruTokens: ["Вежливо", "принести", "подарок", ",", "даже", "если", "это", "маленький", "знак", "внимания", "."],
    enTokens: ["It", "is", "polite", "to", "bring", "a", "gift", ",", "even", "if", "it", "is", "just", "a", "small", "token", "."],
    extraUaTokens: ["якусь", "просту", "приємну"],
    extraRuTokens: ["какой-то", "простой", "приятный"],
    extraEnTokens: ["some", "simple", "nice"],
  },

  [phraseKey("slušnosť", "b1-24")]: {
    sk: "Slušnosť je základ, najmä keď niekoho navštíviš.",
    ua: "Ввічливість — це основа, особливо коли йдеш у гості.",
    ru: "Вежливость — основа, особенно когда идёшь в гости.",
    en: "Politeness is the foundation, especially when you visit someone.",
    uaTokens: ["Ввічливість", "—", "це", "основа", ",", "особливо", "коли", "йдеш", "у", "гості", "."],
    ruTokens: ["Вежливость", "—", "основа", ",", "особенно", "когда", "идёшь", "в", "гости", "."],
    enTokens: ["Politeness", "is", "the", "foundation", ",", "especially", "when", "you", "visit", "someone", "."],
    extraUaTokens: ["завжди", "дуже", "важлива"],
    extraRuTokens: ["всегда", "очень", "важна"],
    extraEnTokens: ["always", "very", "important"],
  },

  [phraseKey("privítať", "b1-24")]: {
    sk: "Prišli sme načas a hostiteľ nás hneď privítal.",
    ua: "Ми прийшли вчасно, і господар нас одразу привітав.",
    ru: "Мы пришли вовремя, и хозяин нас сразу поприветствовал.",
    en: "We arrived on time, and the host welcomed us immediately.",
    uaTokens: ["Ми", "прийшли", "вчасно", ",", "і", "господар", "нас", "одразу", "привітав", "."],
    ruTokens: ["Мы", "пришли", "вовремя", ",", "и", "хозяин", "нас", "сразу", "поприветствовал", "."],
    enTokens: ["We", "arrived", "on", "time", ",", "and", "the", "host", "welcomed", "us", "immediately", "."],
    extraUaTokens: ["дуже", "тепло", "там"],
    extraRuTokens: ["очень", "тепло", "там"],
    extraEnTokens: ["very", "warmly", "there"],
  },

  [phraseKey("ponúknuť", "b1-24")]: {
    sk: "Ponúkol mi kávu alebo čaj, tak som si vybral čaj.",
    ua: "Мені запропонували каву або чай, тож я обрав чай.",
    ru: "Мне предложили кофе или чай, и я выбрал чай.",
    en: "They offered me coffee or tea, so I chose tea.",
    uaTokens: ["Мені", "запропонували", "каву", "або", "чай", ",", "тож", "я", "обрав", "чай", "."],
    ruTokens: ["Мне", "предложили", "кофе", "или", "чай", ",", "и", "я", "выбрал", "чай", "."],
    enTokens: ["They", "offered", "me", "coffee", "or", "tea", ",", "so", "I", "chose", "tea", "."],
    extraUaTokens: ["гарячий", "звичайний", "собі"],
    extraRuTokens: ["горячий", "обычный", "себе"],
    extraEnTokens: ["hot", "regular", "for"],
  },

  [phraseKey("poďakovať sa", "b1-24")]: {
    sk: "Na konci som sa poďakoval za pozvanie aj za pohostenie.",
    ua: "Наприкінці я подякував за запрошення та частування.",
    ru: "В конце я поблагодарил за приглашение и угощение.",
    en: "At the end, I thanked them for the invitation and the treats.",
    uaTokens: ["Наприкінці", "я", "подякував", "за", "запрошення", "та", "частування", "."],
    ruTokens: ["В", "конце", "я", "поблагодарил", "за", "приглашение", "и", "угощение", "."],
    enTokens: ["At", "the", "end", ",", "I", "thanked", "them", "for", "the", "invitation", "and", "the", "treats", "."],
    extraUaTokens: ["щиро", "дуже", "їм"],
    extraRuTokens: ["искренне", "очень", "их"],
    extraEnTokens: ["sincerely", "very", "them"],
  },

  [phraseKey("rozlúčiť sa", "b1-24")]: {
    sk: "Rozlúčili sme sa a sľúbili sme si, že sa čoskoro uvidíme.",
    ua: "Ми попрощалися і пообіцяли, що скоро побачимося.",
    ru: "Мы попрощались и пообещали, что скоро увидимся.",
    en: "We said goodbye and promised that we would see each other soon.",
    uaTokens: ["Ми", "попрощалися", "і", "пообіцяли", ",", "що", "скоро", "побачимося", "."],
    ruTokens: ["Мы", "попрощались", "и", "пообещали", ",", "что", "скоро", "увидимся", "."],
    enTokens: ["We", "said", "goodbye", "and", "promised", "that", "we", "would", "see", "each", "other", "soon", "."],
    extraUaTokens: ["знову", "ще", "обов’язково"],
    extraRuTokens: ["снова", "ещё", "обязательно"],
    extraEnTokens: ["again", "still", "definitely"],
  },

  // =========================
  // LESSON 25 — Emócie a vnútorný stav
  // =========================
  [phraseKey("sklamanie", "b1-25")]: {
    sk: "Cítil som sklamanie, lebo som čakal iný výsledok.",
    ua: "Я відчував розчарування, бо очікував інший результат.",
    ru: "Я чувствовал разочарование, потому что ожидал другой результат.",
    en: "I felt disappointment because I had expected a different result.",
    uaTokens: ["Я", "відчував", "розчарування", ",", "бо", "очікував", "інший", "результат", "."],
    ruTokens: ["Я", "чувствовал", "разочарование", ",", "потому", "что", "ожидал", "другой", "результат", "."],
    enTokens: ["I", "felt", "disappointment", "because", "I", "had", "expected", "a", "different", "result", "."],
    extraUaTokens: ["сильне", "дуже", "тоді"],
    extraRuTokens: ["сильное", "очень", "тогда"],
    extraEnTokens: ["strong", "very", "then"],
  },

  [phraseKey("hrdosť", "b1-25")]: {
    sk: "Cítim hrdosť, keď vidím, koľko som sa naučil.",
    ua: "Я відчуваю гордість, коли бачу, скільки я навчився.",
    ru: "Я чувствую гордость, когда вижу, сколько я научился.",
    en: "I feel pride when I see how much I have learned.",
    uaTokens: ["Я", "відчуваю", "гордість", ",", "коли", "бачу", ",", "скільки", "я", "навчився", "."],
    ruTokens: ["Я", "чувствую", "гордость", ",", "когда", "вижу", ",", "сколько", "я", "научился", "."],
    enTokens: ["I", "feel", "pride", "when", "I", "see", "how", "much", "I", "have", "learned", "."],
    extraUaTokens: ["вже", "так", "багато"],
    extraRuTokens: ["уже", "так", "много"],
    extraEnTokens: ["already", "so", "much"],
  },

  [phraseKey("úľava", "b1-25")]: {
    sk: "Keď sa problém vyriešil, cítil som veľkú úľavu.",
    ua: "Коли проблема вирішилася, я відчув велике полегшення.",
    ru: "Когда проблема решилась, я почувствовал большое облегчение.",
    en: "When the problem was solved, I felt great relief.",
    uaTokens: ["Коли", "проблема", "вирішилася", ",", "я", "відчув", "велике", "полегшення", "."],
    ruTokens: ["Когда", "проблема", "решилась", ",", "я", "почувствовал", "большое", "облегчение", "."],
    enTokens: ["When", "the", "problem", "was", "solved", ",", "I", "felt", "great", "relief", "."],
    extraUaTokens: ["нарешті", "дуже", "сильне"],
    extraRuTokens: ["наконец", "очень", "сильное"],
    extraEnTokens: ["finally", "very", "strong"],
  },

  [phraseKey("neistota", "b1-25")]: {
    sk: "Neistota je normálna, keď začínaš niečo nové.",
    ua: "Невпевненість — це нормально, коли починаєш щось нове.",
    ru: "Неуверенность — это нормально, когда начинаешь что-то новое.",
    en: "Uncertainty is normal when you start something new.",
    uaTokens: ["Невпевненість", "—", "це", "нормально", ",", "коли", "починаєш", "щось", "нове", "."],
    ruTokens: ["Неуверенность", "—", "это", "нормально", ",", "когда", "начинаешь", "что-то", "новое", "."],
    enTokens: ["Uncertainty", "is", "normal", "when", "you", "start", "something", "new", "."],
    extraUaTokens: ["справді", "так", "іноді"],
    extraRuTokens: ["действительно", "так", "иногда"],
    extraEnTokens: ["really", "so", "sometimes"],
  },

  [phraseKey("frustrácia", "b1-25")]: {
    sk: "Frustrácia rastie, keď sa nič nemení napriek snahe.",
    ua: "Фрустрація зростає, коли нічого не змінюється попри зусилля.",
    ru: "Фрустрация растёт, когда ничего не меняется несмотря на усилия.",
    en: "Frustration grows when nothing changes despite the effort.",
    uaTokens: ["Фрустрація", "зростає", ",", "коли", "нічого", "не", "змінюється", "попри", "зусилля", "."],
    ruTokens: ["Фрустрация", "растёт", ",", "когда", "ничего", "не", "меняется", "несмотря", "на", "усилия", "."],
    enTokens: ["Frustration", "grows", "when", "nothing", "changes", "despite", "the", "effort", "."],
    extraUaTokens: ["дуже", "сильно", "вже"],
    extraRuTokens: ["очень", "сильно", "уже"],
    extraEnTokens: ["very", "strongly", "already"],
  },

  [phraseKey("pochybnosť", "b1-25")]: {
    sk: "Mal som pochybnosť, či je to správne rozhodnutie.",
    ua: "У мене був сумнів, чи це правильне рішення.",
    ru: "У меня было сомнение, правильное ли это решение.",
    en: "I had a doubt whether it was the right decision.",
    uaTokens: ["У", "мене", "був", "сумнів", ",", "чи", "це", "правильне", "рішення", "."],
    ruTokens: ["У", "меня", "было", "сомнение", ",", "правильное", "ли", "это", "решение", "."],
    enTokens: ["I", "had", "a", "doubt", "whether", "it", "was", "the", "right", "decision", "."],
    extraUaTokens: ["великий", "ще", "тоді"],
    extraRuTokens: ["большое", "ещё", "тогда"],
    extraEnTokens: ["big", "still", "then"],
  },

  [phraseKey("obava", "b1-25")]: {
    sk: "Mám obavu, že to nestihneme do termínu.",
    ua: "Я боюся, що ми не встигнемо до терміну.",
    ru: "Я опасаюсь, что мы не успеем к сроку.",
    en: "I am afraid that we will not make it by the deadline.",
    uaTokens: ["Я", "боюся", ",", "що", "ми", "не", "встигнемо", "до", "терміну", "."],
    ruTokens: ["Я", "опасаюсь", ",", "что", "мы", "не", "успеем", "к", "сроку", "."],
    enTokens: ["I", "am", "afraid", "that", "we", "will", "not", "make", "it", "by", "the", "deadline", "."],
    extraUaTokens: ["цього", "дуже", "справді"],
    extraRuTokens: ["этого", "очень", "действительно"],
    extraEnTokens: ["this", "very", "really"],
  },

  [phraseKey("spokojnosť", "b1-25")]: {
    sk: "Spokojnosť príde, keď uvidíš reálny pokrok.",
    ua: "Задоволення прийде, коли побачиш реальний прогрес.",
    ru: "Удовлетворение придёт, когда увидишь реальный прогресс.",
    en: "Satisfaction will come when you see real progress.",
    uaTokens: ["Задоволення", "прийде", ",", "коли", "побачиш", "реальний", "прогрес", "."],
    ruTokens: ["Удовлетворение", "придёт", ",", "когда", "увидишь", "реальный", "прогресс", "."],
    enTokens: ["Satisfaction", "will", "come", "when", "you", "see", "real", "progress", "."],
    extraUaTokens: ["справжній", "вже", "потім"],
    extraRuTokens: ["настоящий", "уже", "потом"],
    extraEnTokens: ["real", "already", "later"],
  },

  [phraseKey("bezmocnosť", "b1-25")]: {
    sk: "Bezmocnosť som cítil, keď som nemohol nič ovplyvniť.",
    ua: "Безсилля я відчував, коли не міг нічого змінити.",
    ru: "Бессилие я чувствовал, когда не мог ничего изменить.",
    en: "I felt helplessness when I could not change anything.",
    uaTokens: ["Безсилля", "я", "відчував", ",", "коли", "не", "міг", "нічого", "змінити", "."],
    ruTokens: ["Бессилие", "я", "чувствовал", ",", "когда", "не", "мог", "ничего", "изменить", "."],
    enTokens: ["I", "felt", "helplessness", "when", "I", "could", "not", "change", "anything", "."],
    extraUaTokens: ["повне", "майже", "тоді"],
    extraRuTokens: ["полное", "почти", "тогда"],
    extraEnTokens: ["complete", "almost", "then"],
  },

  [phraseKey("vyčerpanie", "b1-25")]: {
    sk: "Po náročnom týždni som cítil úplné vyčerpanie.",
    ua: "Після важкого тижня я відчував повне виснаження.",
    ru: "После тяжёлой недели я чувствовал полное истощение.",
    en: "After a difficult week, I felt complete exhaustion.",
    uaTokens: ["Після", "важкого", "тижня", "я", "відчував", "повне", "виснаження", "."],
    ruTokens: ["После", "тяжёлой", "недели", "я", "чувствовал", "полное", "истощение", "."],
    enTokens: ["After", "a", "difficult", "week", ",", "I", "felt", "complete", "exhaustion", "."],
    extraUaTokens: ["дуже", "сильне", "вже"],
    extraRuTokens: ["очень", "сильное", "уже"],
    extraEnTokens: ["very", "strong", "already"],
  },
};