import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_A2_BUILD_UA_SENTENCES_5: BuildUaSentenceDict = {
    // =========================
    // LESSON A2-21 — Дім (проблеми та майстер)
    // =========================
    [phraseKey("porucha", "a2-21")]: {
        sk: "V kuchyni došlo k poruše spotřebiče.",
        ua: "На кухні сталася поломка приладу.",
        ru: "На кухне произошла поломка прибора.",
        en: "A device broke down in the kitchen.",
        uaTokens: ["На", "кухні", "сталася", "поломка", "приладу", "."],
        ruTokens: ["На", "кухне", "произошла", "поломка", "прибора", "."],
        enTokens: ["A", "device", "broke", "down", "in", "the", "kitchen", "."],
        extraUaTokens: ["ванній", "ремонт", "вчора"],
        extraRuTokens: ["ванной", "ремонт", "вчера"],
        extraEnTokens: ["bathroom", "repair", "yesterday"],
    },

    [phraseKey("instalatér", "a2-21")]: {
        sk: "Zítra má přijít instalatér.",
        ua: "Завтра має прийти сантехнік.",
        ru: "Завтра должен прийти сантехник.",
        en: "The plumber is supposed to come tomorrow.",
        uaTokens: ["Завтра", "має", "прийти", "сантехнік", "."],
        ruTokens: ["Завтра", "должен", "прийти", "сантехник", "."],
        enTokens: ["The", "plumber", "is", "supposed", "to", "come", "tomorrow", "."],
        extraUaTokens: ["електрик", "сьогодні", "піти"],
        extraRuTokens: ["электрик", "сегодня", "уйти"],
        extraEnTokens: ["electrician", "today", "leave"],
    },

    [phraseKey("elektrikář", "a2-21")]: {
        sk: "Elektrikář opraví zásuvku odpoledne.",
        ua: "Електрик відремонтує розетку після обіду.",
        ru: "Электрик починит розетку после обеда.",
        en: "The electrician will fix the socket in the afternoon.",
        uaTokens: ["Електрик", "відремонтує", "розетку", "після", "обіду", "."],
        ruTokens: ["Электрик", "починит", "розетку", "после", "обеда", "."],
        enTokens: ["The", "electrician", "will", "fix", "the", "socket", "in", "the", "afternoon", "."],
        extraUaTokens: ["сантехнік", "вранці", "зламає"],
        extraRuTokens: ["сантехник", "утром", "сломает"],
        extraEnTokens: ["plumber", "morning", "break"],
    },

    [phraseKey("opravit", "a2-21")]: {
        sk: "Musíme co nejdřív opravit kotel.",
        ua: "Нам треба якнайшвидше відремонтувати котел.",
        ru: "Нам нужно как можно скорее отремонтировать котёл.",
        en: "We need to repair the boiler as soon as possible.",
        uaTokens: ["Нам", "треба", "якнайшвидше", "відремонтувати", "котел", "."],
        ruTokens: ["Нам", "нужно", "как", "можно", "скорее", "отремонтировать", "котёл", "."],
        enTokens: ["We", "need", "to", "repair", "the", "boiler", "as", "soon", "as", "possible", "."],
        extraUaTokens: ["замінити", "вчора", "двері"],
        extraRuTokens: ["заменить", "вчера", "дверь"],
        extraEnTokens: ["replace", "yesterday", "door"],
    },

    [phraseKey("vyměnit", "a2-21")]: {
        sk: "Bude nutné vyměnit starou baterii.",
        ua: "Буде необхідно замінити старий змішувач.",
        ru: "Нужно будет заменить старый смеситель.",
        en: "It will be necessary to replace the old faucet.",
        uaTokens: ["Буде", "необхідно", "замінити", "старий", "змішувач", "."],
        ruTokens: ["Нужно", "будет", "заменить", "старый", "смеситель", "."],
        enTokens: ["It", "will", "be", "necessary", "to", "replace", "the", "old", "faucet", "."],
        extraUaTokens: ["новий", "полагодити", "сьогодні"],
        extraRuTokens: ["новый", "починить", "сегодня"],
        extraEnTokens: ["new", "repair", "today"],
    },

    [phraseKey("protékání", "a2-21")]: {
        sk: "Protékání střechy je velký problém.",
        ua: "Протікання даху — велика проблема.",
        ru: "Протечка крыши — большая проблема.",
        en: "A leaking roof is a big problem.",
        uaTokens: ["Протікання", "даху", "—", "велика", "проблема", "."],
        ruTokens: ["Протечка", "крыши", "—", "большая", "проблема", "."],
        enTokens: ["A", "leaking", "roof", "is", "a", "big", "problem", "."],
        extraUaTokens: ["стіни", "маленька", "вчора"],
        extraRuTokens: ["стены", "маленькая", "вчера"],
        extraEnTokens: ["wall", "small", "yesterday"],
    },

    [phraseKey("upchání", "a2-21")]: {
        sk: "V koupelně je upchání odpadu.",
        ua: "У ванній є засмічення стоку.",
        ru: "В ванной засор в сливе.",
        en: "There is a drain blockage in the bathroom.",
        uaTokens: ["У", "ванній", "є", "засмічення", "стоку", "."],
        ruTokens: ["В", "ванной", "засор", "в", "сливе", "."],
        enTokens: ["There", "is", "a", "drain", "blockage", "in", "the", "bathroom", "."],
        extraUaTokens: ["кухні", "чистий", "сьогодні"],
        extraRuTokens: ["кухне", "чистый", "сегодня"],
        extraEnTokens: ["kitchen", "clean", "today"],
    },

    [phraseKey("zatekat", "a2-21")]: {
        sk: "Po dešti začalo do sklepa zatékat.",
        ua: "Після дощу в підвал почала затікати вода.",
        ru: "После дождя в подвал начала затекать вода.",
        en: "After the rain, water started leaking into the basement.",
        uaTokens: ["Після", "дощу", "в", "підвал", "почала", "затікати", "вода", "."],
        ruTokens: ["После", "дождя", "в", "подвал", "начала", "затекать", "вода", "."],
        enTokens: ["After", "the", "rain", ",", "water", "started", "leaking", "into", "the", "basement", "."],
        extraUaTokens: ["горище", "сухо", "вчора"],
        extraRuTokens: ["чердак", "сухо", "вчера"],
        extraEnTokens: ["attic", "dry", "yesterday"],
    },

    [phraseKey("poškození", "a2-21")]: {
        sk: "Na stěně je vidět poškození.",
        ua: "На стіні видно пошкодження.",
        ru: "На стене видно повреждение.",
        en: "Damage is visible on the wall.",
        uaTokens: ["На", "стіні", "видно", "пошкодження", "."],
        ruTokens: ["На", "стене", "видно", "повреждение", "."],
        enTokens: ["Damage", "is", "visible", "on", "the", "wall", "."],
        extraUaTokens: ["ремонт", "вчора", "чисто"],
        extraRuTokens: ["ремонт", "вчера", "чисто"],
        extraEnTokens: ["repair", "yesterday", "clean"],
    },

    [phraseKey("náhradní díl", "a2-21")]: {
        sk: "Na náhradní díl budeme čekat týden.",
        ua: "На запасну частину ми чекатимемо тиждень.",
        ru: "Запасную часть мы будем ждать неделю.",
        en: "We will wait a week for the spare part.",
        uaTokens: ["На", "запасну", "частину", "ми", "чекатимемо", "тиждень", "."],
        ruTokens: ["Запасную", "часть", "мы", "будем", "ждать", "неделю", "."],
        enTokens: ["We", "will", "wait", "a", "week", "for", "the", "spare", "part", "."],
        extraUaTokens: ["майстра", "два", "дні"],
        extraRuTokens: ["мастера", "два", "дня"],
        extraEnTokens: ["repairman", "two", "days"],
    },

    // =========================
    // LESSON A2-22 — Здоровʼя (аптека та лікування)
    // =========================
    [phraseKey("vedlejší účinky", "a2-22")]: {
        sk: "Tyto léky mohou mít vedlejší účinky.",
        ua: "Ці ліки можуть мати побічні ефекти.",
        ru: "Эти лекарства могут иметь побочные эффекты.",
        en: "These medicines may have side effects.",
        uaTokens: ["Ці", "ліки", "можуть", "мати", "побічні", "ефекти", "."],
        ruTokens: ["Эти", "лекарства", "могут", "иметь", "побочные", "эффекты", "."],
        enTokens: ["These", "medicines", "may", "have", "side", "effects", "."],
        extraUaTokens: ["користь", "вчора", "таблетки"],
        extraRuTokens: ["пользу", "вчера", "таблетки"],
        extraEnTokens: ["benefit", "yesterday", "pills"],
    },

    [phraseKey("dávkování", "a2-22")]: {
        sk: "Dodržujte doporučené dávkování.",
        ua: "Дотримуйтеся рекомендованого дозування.",
        ru: "Соблюдайте рекомендованную дозировку.",
        en: "Follow the recommended dosage.",
        uaTokens: ["Дотримуйтеся", "рекомендованого", "дозування", "."],
        ruTokens: ["Соблюдайте", "рекомендованную", "дозировку", "."],
        enTokens: ["Follow", "the", "recommended", "dosage", "."],
        extraUaTokens: ["лікування", "вчора", "збільшити"],
        extraRuTokens: ["лечение", "вчера", "увеличить"],
        extraEnTokens: ["treatment", "yesterday", "increase"],
    },

    [phraseKey("návod", "a2-22")]: {
        sk: "Nejdřív si přečtěte návod.",
        ua: "Спочатку прочитайте інструкцію.",
        ru: "Сначала прочитайте инструкцию.",
        en: "First, read the instructions.",
        uaTokens: ["Спочатку", "прочитайте", "інструкцію", "."],
        ruTokens: ["Сначала", "прочитайте", "инструкцию", "."],
        enTokens: ["First", ",", "read", "the", "instructions", "."],
        extraUaTokens: ["рецепт", "вчора", "напишіть"],
        extraRuTokens: ["рецепт", "вчера", "напишите"],
        extraEnTokens: ["prescription", "yesterday", "write"],
    },

    [phraseKey("lék proti bolesti", "a2-22")]: {
        sk: "Potřebuji silný lék proti bolesti.",
        ua: "Мені потрібне сильне знеболювальне.",
        ru: "Мне нужно сильное обезболивающее.",
        en: "I need a strong painkiller.",
        uaTokens: ["Мені", "потрібне", "сильне", "знеболювальне", "."],
        ruTokens: ["Мне", "нужно", "сильное", "обезболивающее", "."],
        enTokens: ["I", "need", "a", "strong", "painkiller", "."],
        extraUaTokens: ["слабке", "сироп", "вчора"],
        extraRuTokens: ["слабое", "сироп", "вчера"],
        extraEnTokens: ["weak", "syrup", "yesterday"],
    },

    [phraseKey("antibiotika", "a2-22")]: {
        sk: "Lékař mi předepsal antibiotika.",
        ua: "Лікар призначив мені антибіотики.",
        ru: "Врач прописал мне антибиотики.",
        en: "The doctor prescribed antibiotics for me.",
        uaTokens: ["Лікар", "призначив", "мені", "антибіотики", "."],
        ruTokens: ["Врач", "прописал", "мне", "антибиотики", "."],
        enTokens: ["The", "doctor", "prescribed", "antibiotics", "for", "me", "."],
        extraUaTokens: ["вітаміни", "вчора", "сам"],
        extraRuTokens: ["витамины", "вчера", "сам"],
        extraEnTokens: ["vitamins", "yesterday", "myself"],
    },

    [phraseKey("očkování", "a2-22")]: {
        sk: "Příští týden mám očkování.",
        ua: "Наступного тижня мені мають зробити щеплення.",
        ru: "На следующей неделе мне должны сделать прививку.",
        en: "I am supposed to get vaccinated next week.",
        uaTokens: ["Наступного", "тижня", "мені", "мають", "зробити", "щеплення", "."],
        ruTokens: ["На", "следующей", "неделе", "мне", "должны", "сделать", "прививку", "."],
        enTokens: ["I", "am", "supposed", "to", "get", "vaccinated", "next", "week", "."],
        extraUaTokens: ["операція", "вчора", "було"],
        extraRuTokens: ["операция", "вчера", "была"],
        extraEnTokens: ["operation", "yesterday", "was"],
    },

    [phraseKey("recept", "a2-22")]: {
        sk: "Bez receptu to v lékárně nedostanu.",
        ua: "Без рецепта я цього в аптеці не отримаю.",
        ru: "Без рецепта я это в аптеке не получу.",
        en: "I will not get it at the pharmacy without a prescription.",
        uaTokens: ["Без", "рецепта", "я", "цього", "в", "аптеці", "не", "отримаю", "."],
        ruTokens: ["Без", "рецепта", "я", "это", "в", "аптеке", "не", "получу", "."],
        enTokens: ["Without", "a", "prescription", ",", "I", "will", "not", "get", "it", "at", "the", "pharmacy", "."],
        extraUaTokens: ["лікаря", "сьогодні", "можу"],
        extraRuTokens: ["врача", "сегодня", "могу"],
        extraEnTokens: ["doctor", "today", "can"],
    },

    [phraseKey("bez receptu", "a2-22")]: {
        sk: "Tento sirup je bez receptu.",
        ua: "Цей сироп продається без рецепта.",
        ru: "Этот сироп продаётся без рецепта.",
        en: "This syrup is sold without a prescription.",
        uaTokens: ["Цей", "сироп", "продається", "без", "рецепта", "."],
        ruTokens: ["Этот", "сироп", "продаётся", "без", "рецепта", "."],
        enTokens: ["This", "syrup", "is", "sold", "without", "a", "prescription", "."],
        extraUaTokens: ["таблетки", "вчора", "за"],
        extraRuTokens: ["таблетки", "вчера", "по"],
        extraEnTokens: ["tablets", "yesterday", "for"],
    },

    [phraseKey("kontrola", "a2-22")]: {
        sk: "Za týden půjdu na kontrolu.",
        ua: "За тиждень я піду на огляд.",
        ru: "Через неделю я пойду на осмотр.",
        en: "In a week, I will go for a check-up.",
        uaTokens: ["За", "тиждень", "я", "піду", "на", "огляд", "."],
        ruTokens: ["Через", "неделю", "я", "пойду", "на", "осмотр", "."],
        enTokens: ["In", "a", "week", ",", "I", "will", "go", "for", "a", "check-up", "."],
        extraUaTokens: ["роботу", "вчора", "поїду"],
        extraRuTokens: ["работу", "вчера", "поеду"],
        extraEnTokens: ["work", "yesterday", "go"],
    },

    [phraseKey("uzdravovat se", "a2-22")]: {
        sk: "Po operaci se pomalu uzdravuje.",
        ua: "Після операції він повільно одужує.",
        ru: "После операции он медленно выздоравливает.",
        en: "He is recovering slowly after the operation.",
        uaTokens: ["Після", "операції", "він", "повільно", "одужує", "."],
        ruTokens: ["После", "операции", "он", "медленно", "выздоравливает", "."],
        enTokens: ["He", "is", "recovering", "slowly", "after", "the", "operation", "."],
        extraUaTokens: ["працює", "вчора", "швидко"],
        extraRuTokens: ["работает", "вчера", "быстро"],
        extraEnTokens: ["works", "yesterday", "quickly"],
    },

    // =========================
    // LESSON A2-23 — Місто (безпека та служби)
    // =========================
    [phraseKey("nehoda", "a2-23")]: {
        sk: "Na křižovatce se stala nehoda.",
        ua: "На перехресті сталася аварія.",
        ru: "На перекрёстке произошла авария.",
        en: "An accident happened at the intersection.",
        uaTokens: ["На", "перехресті", "сталася", "аварія", "."],
        ruTokens: ["На", "перекрёстке", "произошла", "авария", "."],
        enTokens: ["An", "accident", "happened", "at", "the", "intersection", "."],
        extraUaTokens: ["площа", "свято", "вчора"],
        extraRuTokens: ["площадь", "праздник", "вчера"],
        extraEnTokens: ["square", "holiday", "yesterday"],
    },

    [phraseKey("záchranka", "a2-23")]: {
        sk: "Někdo už zavolal záchranku.",
        ua: "Хтось уже викликав швидку допомогу.",
        ru: "Кто-то уже вызвал скорую помощь.",
        en: "Someone has already called an ambulance.",
        uaTokens: ["Хтось", "уже", "викликав", "швидку", "допомогу", "."],
        ruTokens: ["Кто-то", "уже", "вызвал", "скорую", "помощь", "."],
        enTokens: ["Someone", "has", "already", "called", "an", "ambulance", "."],
        extraUaTokens: ["поліцію", "вчора", "зупинив"],
        extraRuTokens: ["полицию", "вчера", "остановил"],
        extraEnTokens: ["police", "yesterday", "stopped"],
    },

    [phraseKey("hasiči", "a2-23")]: {
        sk: "Hasiči přijeli velmi rychle.",
        ua: "Пожежники приїхали дуже швидко.",
        ru: "Пожарные приехали очень быстро.",
        en: "The firefighters arrived very quickly.",
        uaTokens: ["Пожежники", "приїхали", "дуже", "швидко", "."],
        ruTokens: ["Пожарные", "приехали", "очень", "быстро", "."],
        enTokens: ["The", "firefighters", "arrived", "very", "quickly", "."],
        extraUaTokens: ["лікарі", "вчора", "пізно"],
        extraRuTokens: ["врачи", "вчера", "поздно"],
        extraEnTokens: ["doctors", "yesterday", "late"],
    },

    [phraseKey("policejní stanice", "a2-23")]: {
        sk: "Musíme jít na policejní stanici.",
        ua: "Нам треба піти до відділку поліції.",
        ru: "Нам нужно пойти в отделение полиции.",
        en: "We need to go to the police station.",
        uaTokens: ["Нам", "треба", "піти", "до", "відділку", "поліції", "."],
        ruTokens: ["Нам", "нужно", "пойти", "в", "отделение", "полиции", "."],
        enTokens: ["We", "need", "to", "go", "to", "the", "police", "station", "."],
        extraUaTokens: ["лікарні", "вчора", "бігти"],
        extraRuTokens: ["больницу", "вчера", "бежать"],
        extraEnTokens: ["hospital", "yesterday", "run"],
    },

    [phraseKey("svědek", "a2-23")]: {
        sk: "Svědek všechno přesně popsal.",
        ua: "Свідок усе точно описав.",
        ru: "Свидетель всё точно описал.",
        en: "The witness described everything accurately.",
        uaTokens: ["Свідок", "усе", "точно", "описав", "."],
        ruTokens: ["Свидетель", "всё", "точно", "описал", "."],
        enTokens: ["The", "witness", "described", "everything", "accurately", "."],
        extraUaTokens: ["винний", "вчора", "забув"],
        extraRuTokens: ["виновный", "вчера", "забыл"],
        extraEnTokens: ["guilty", "yesterday", "forgot"],
    },

    [phraseKey("krádež", "a2-23")]: {
        sk: "V centru došlo ke krádeži kola.",
        ua: "У центрі сталася крадіжка велосипеда.",
        ru: "В центре произошла кража велосипеда.",
        en: "A bicycle theft happened in the center.",
        uaTokens: ["У", "центрі", "сталася", "крадіжка", "велосипеда", "."],
        ruTokens: ["В", "центре", "произошла", "кража", "велосипеда", "."],
        enTokens: ["A", "bicycle", "theft", "happened", "in", "the", "center", "."],
        extraUaTokens: ["машини", "вчора", "знахідка"],
        extraRuTokens: ["машины", "вчера", "находка"],
        extraEnTokens: ["car", "yesterday", "discovery"],
    },

    [phraseKey("nahlásit", "a2-23")]: {
        sk: "Chci nahlásit ztrátu dokladů.",
        ua: "Я хочу заявити про втрату документів.",
        ru: "Я хочу сообщить о потере документов.",
        en: "I want to report the loss of my documents.",
        uaTokens: ["Я", "хочу", "заявити", "про", "втрату", "документів", "."],
        ruTokens: ["Я", "хочу", "сообщить", "о", "потере", "документов", "."],
        enTokens: ["I", "want", "to", "report", "the", "loss", "of", "my", "documents", "."],
        extraUaTokens: ["знайти", "вчора", "ключі"],
        extraRuTokens: ["найти", "вчера", "ключи"],
        extraEnTokens: ["find", "yesterday", "keys"],
    },

    [phraseKey("doklady", "a2-23")]: {
        sk: "V peněžence jsem měl všechny doklady.",
        ua: "У гаманці в мене були всі документи.",
        ru: "В кошельке у меня были все документы.",
        en: "I had all my documents in my wallet.",
        uaTokens: ["У", "гаманці", "в", "мене", "були", "всі", "документи", "."],
        ruTokens: ["В", "кошельке", "у", "меня", "были", "все", "документы", "."],
        enTokens: ["I", "had", "all", "my", "documents", "in", "my", "wallet", "."],
        extraUaTokens: ["квитки", "вчора", "один"],
        extraRuTokens: ["билеты", "вчера", "один"],
        extraEnTokens: ["tickets", "yesterday", "one"],
    },

    [phraseKey("ztratit", "a2-23")]: {
        sk: "Nechci ztratit telefon ani klíče.",
        ua: "Я не хочу загубити телефон чи ключі.",
        ru: "Я не хочу потерять телефон или ключи.",
        en: "I do not want to lose my phone or my keys.",
        uaTokens: ["Я", "не", "хочу", "загубити", "телефон", "чи", "ключі", "."],
        ruTokens: ["Я", "не", "хочу", "потерять", "телефон", "или", "ключи", "."],
        enTokens: ["I", "do", "not", "want", "to", "lose", "my", "phone", "or", "my", "keys", "."],
        extraUaTokens: ["знайти", "вчора", "гаманець"],
        extraRuTokens: ["найти", "вчера", "кошелёк"],
        extraEnTokens: ["find", "yesterday", "wallet"],
    },

    [phraseKey("najít", "a2-23")]: {
        sk: "Doufám, že se to podaří najít.",
        ua: "Сподіваюся, що це вдасться знайти.",
        ru: "Надеюсь, что это удастся найти.",
        en: "I hope it will be possible to find it.",
        uaTokens: ["Сподіваюся", ",", "що", "це", "вдасться", "знайти", "."],
        ruTokens: ["Надеюсь", ",", "что", "это", "удастся", "найти", "."],
        enTokens: ["I", "hope", "it", "will", "be", "possible", "to", "find", "it", "."],
        extraUaTokens: ["втратити", "вчора", "швидко"],
        extraRuTokens: ["потерять", "вчера", "быстро"],
        extraEnTokens: ["lose", "yesterday", "quickly"],
    },

    // =========================
    // LESSON A2-24 — Їжа (покупки та приготування)
    // =========================
    [phraseKey("ingredience", "a2-24")]: {
        sk: "Všechny ingredience už máme doma.",
        ua: "Усі інгредієнти вже є вдома.",
        ru: "Все ингредиенты уже есть дома.",
        en: "We already have all the ingredients at home.",
        uaTokens: ["Усі", "інгредієнти", "вже", "є", "вдома", "."],
        ruTokens: ["Все", "ингредиенты", "уже", "есть", "дома", "."],
        enTokens: ["We", "already", "have", "all", "the", "ingredients", "at", "home", "."],
        extraUaTokens: ["магазині", "вчора", "мало"],
        extraRuTokens: ["магазине", "вчера", "мало"],
        extraEnTokens: ["store", "yesterday", "few"],
    },

    [phraseKey("recept (kuchařský)", "a2-24")]: {
        sk: "Našel jsem jednoduchý recept na polévku.",
        ua: "Я знайшов простий кулінарний рецепт супу.",
        ru: "Я нашёл простой кулинарный рецепт супа.",
        en: "I found a simple cooking recipe for soup.",
        uaTokens: ["Я", "знайшов", "простий", "кулінарний", "рецепт", "супу", "."],
        ruTokens: ["Я", "нашёл", "простой", "кулинарный", "рецепт", "супа", "."],
        enTokens: ["I", "found", "a", "simple", "cooking", "recipe", "for", "soup", "."],
        extraUaTokens: ["лікарський", "вчора", "чай"],
        extraRuTokens: ["медицинский", "вчера", "чай"],
        extraEnTokens: ["medical", "yesterday", "tea"],
    },

    [phraseKey("nakrájet", "a2-24")]: {
        sk: "Nejdřív musíš nakrájet cibuli.",
        ua: "Спочатку ти маєш нарізати цибулю.",
        ru: "Сначала тебе нужно нарезать лук.",
        en: "First, you need to chop the onion.",
        uaTokens: ["Спочатку", "ти", "маєш", "нарізати", "цибулю", "."],
        ruTokens: ["Сначала", "тебе", "нужно", "нарезать", "лук", "."],
        enTokens: ["First", ",", "you", "need", "to", "chop", "the", "onion", "."],
        extraUaTokens: ["помити", "вчора", "м’ясо"],
        extraRuTokens: ["помыть", "вчера", "мясо"],
        extraEnTokens: ["wash", "yesterday", "meat"],
    },

    [phraseKey("smíchat", "a2-24")]: {
        sk: "Pak všechno dobře smíchej.",
        ua: "Потім добре все змішай.",
        ru: "Потом хорошо всё смешай.",
        en: "Then mix everything well.",
        uaTokens: ["Потім", "добре", "все", "змішай", "."],
        ruTokens: ["Потом", "хорошо", "всё", "смешай", "."],
        enTokens: ["Then", "mix", "everything", "well", "."],
        extraUaTokens: ["розріж", "вчора", "швидко"],
        extraRuTokens: ["разрежь", "вчера", "быстро"],
        extraEnTokens: ["cut", "yesterday", "quickly"],
    },

    [phraseKey("osmažit", "a2-24")]: {
        sk: "Maso je potřeba lehce osmažit.",
        ua: "М’ясо потрібно трохи підсмажити.",
        ru: "Мясо нужно слегка обжарить.",
        en: "The meat needs to be lightly fried.",
        uaTokens: ["М’ясо", "потрібно", "трохи", "підсмажити", "."],
        ruTokens: ["Мясо", "нужно", "слегка", "обжарить", "."],
        enTokens: ["The", "meat", "needs", "to", "be", "lightly", "fried", "."],
        extraUaTokens: ["зварити", "вчора", "рибу"],
        extraRuTokens: ["сварить", "вчера", "рыбу"],
        extraEnTokens: ["boil", "yesterday", "fish"],
    },

    [phraseKey("uvařit", "a2-24")]: {
        sk: "Brambory se musí nejdřív uvařit.",
        ua: "Картоплю потрібно спочатку зварити.",
        ru: "Картошку нужно сначала сварить.",
        en: "The potatoes need to be boiled first.",
        uaTokens: ["Картоплю", "потрібно", "спочатку", "зварити", "."],
        ruTokens: ["Картошку", "нужно", "сначала", "сварить", "."],
        enTokens: ["The", "potatoes", "need", "to", "be", "boiled", "first", "."],
        extraUaTokens: ["спекти", "вчора", "суп"],
        extraRuTokens: ["испечь", "вчера", "суп"],
        extraEnTokens: ["bake", "yesterday", "soup"],
    },

    [phraseKey("upéct", "a2-24")]: {
        sk: "Chci dnes upéct koláč.",
        ua: "Я хочу сьогодні спекти пиріг.",
        ru: "Я хочу сегодня испечь пирог.",
        en: "I want to bake a pie today.",
        uaTokens: ["Я", "хочу", "сьогодні", "спекти", "пиріг", "."],
        ruTokens: ["Я", "хочу", "сегодня", "испечь", "пирог", "."],
        enTokens: ["I", "want", "to", "bake", "a", "pie", "today", "."],
        extraUaTokens: ["купити", "вчора", "торт"],
        extraRuTokens: ["купить", "вчера", "торт"],
        extraEnTokens: ["buy", "yesterday", "cake"],
    },

    [phraseKey("ochutit", "a2-24")]: {
        sk: "Na konci to můžeš ochutit bylinkami.",
        ua: "Наприкінці ти можеш це приправити травами.",
        ru: "В конце можешь приправить это травами.",
        en: "At the end, you can season it with herbs.",
        uaTokens: ["Наприкінці", "ти", "можеш", "це", "приправити", "травами", "."],
        ruTokens: ["В", "конце", "можешь", "приправить", "это", "травами", "."],
        enTokens: ["At", "the", "end", ",", "you", "can", "season", "it", "with", "herbs", "."],
        extraUaTokens: ["цукром", "вчора", "забути"],
        extraRuTokens: ["сахаром", "вчера", "забыть"],
        extraEnTokens: ["sugar", "yesterday", "forget"],
    },

    [phraseKey("porce", "a2-24")]: {
        sk: "Tohle je velká porce pro dvě osoby.",
        ua: "Це велика порція на двох людей.",
        ru: "Это большая порция на двоих.",
        en: "This is a large portion for two people.",
        uaTokens: ["Це", "велика", "порція", "на", "двох", "людей", "."],
        ruTokens: ["Это", "большая", "порция", "на", "двоих", "."],
        enTokens: ["This", "is", "a", "large", "portion", "for", "two", "people", "."],
        extraUaTokens: ["маленька", "вчора", "трьох"],
        extraRuTokens: ["маленькая", "вчера", "троих"],
        extraEnTokens: ["small", "yesterday", "three"],
    },

    [phraseKey("zbytky", "a2-24")]: {
        sk: "Zbytky dáme do lednice.",
        ua: "Залишки їжі покладемо в холодильник.",
        ru: "Остатки еды положим в холодильник.",
        en: "We will put the leftovers in the fridge.",
        uaTokens: ["Залишки", "їжі", "покладемо", "в", "холодильник", "."],
        ruTokens: ["Остатки", "еды", "положим", "в", "холодильник", "."],
        enTokens: ["We", "will", "put", "the", "leftovers", "in", "the", "fridge", "."],
        extraUaTokens: ["смітник", "вчора", "одразу"],
        extraRuTokens: ["мусор", "вчера", "сразу"],
        extraEnTokens: ["trash", "yesterday", "immediately"],
    },

    // =========================
    // LESSON A2-25 — Подорожі (планування маршруту)
    // =========================
    [phraseKey("itinerář", "a2-25")]: {
        sk: "Připravil jsem si podrobný itinerář.",
        ua: "Я підготував детальний маршрут подорожі.",
        ru: "Я подготовил подробный план поездки.",
        en: "I prepared a detailed travel itinerary.",
        uaTokens: ["Я", "підготував", "детальний", "маршрут", "подорожі", "."],
        ruTokens: ["Я", "подготовил", "подробный", "план", "поездки", "."],
        enTokens: ["I", "prepared", "a", "detailed", "travel", "itinerary", "."],
        extraUaTokens: ["квиток", "вчора", "короткий"],
        extraRuTokens: ["билет", "вчера", "короткий"],
        extraEnTokens: ["ticket", "yesterday", "short"],
    },

    [phraseKey("přestup", "a2-25")]: {
        sk: "V Brně budeme mít krátký přestup.",
        ua: "У Брні в нас буде коротка пересадка.",
        ru: "В Брно у нас будет короткая пересадка.",
        en: "We will have a short transfer in Brno.",
        uaTokens: ["У", "Брні", "в", "нас", "буде", "коротка", "пересадка", "."],
        ruTokens: ["В", "Брно", "у", "нас", "будет", "короткая", "пересадка", "."],
        enTokens: ["We", "will", "have", "a", "short", "transfer", "in", "Brno", "."],
        extraUaTokens: ["затримка", "вчора", "довга"],
        extraRuTokens: ["задержка", "вчера", "долгая"],
        extraEnTokens: ["delay", "yesterday", "long"],
    },

    [phraseKey("spoj", "a2-25")]: {
        sk: "Tento spoj jede přímo do Prahy.",
        ua: "Цей рейс прямує прямо до Праги.",
        ru: "Этот рейс идёт прямо до Праги.",
        en: "This connection goes directly to Prague.",
        uaTokens: ["Цей", "рейс", "прямує", "прямо", "до", "Праги", "."],
        ruTokens: ["Этот", "рейс", "идёт", "прямо", "до", "Праги", "."],
        enTokens: ["This", "connection", "goes", "directly", "to", "Prague", "."],
        extraUaTokens: ["квиток", "вчора", "через"],
        extraRuTokens: ["билет", "вчера", "через"],
        extraEnTokens: ["ticket", "yesterday", "via"],
    },

    [phraseKey("zpoždění", "a2-25")]: {
        sk: "Na tabuli bylo napsáno zpoždění.",
        ua: "На табло було написано про затримку.",
        ru: "На табло было написано о задержке.",
        en: "It was written on the board that there was a delay.",
        uaTokens: ["На", "табло", "було", "написано", "про", "затримку", "."],
        ruTokens: ["На", "табло", "было", "написано", "о", "задержке", "."],
        enTokens: ["It", "was", "written", "on", "the", "board", "that", "there", "was", "a", "delay", "."],
        extraUaTokens: ["відміну", "вчора", "швидко"],
        extraRuTokens: ["отмене", "вчера", "быстро"],
        extraEnTokens: ["cancellation", "yesterday", "quickly"],
    },

    [phraseKey("zrušený", "a2-25")]: {
        sk: "Náš vlak byl bohužel zrušený.",
        ua: "Наш потяг, на жаль, був скасований.",
        ru: "Наш поезд, к сожалению, был отменён.",
        en: "Unfortunately, our train was cancelled.",
        uaTokens: ["Наш", "потяг", ",", "на", "жаль", ",", "був", "скасований", "."],
        ruTokens: ["Наш", "поезд", ",", "к", "сожалению", ",", "был", "отменён", "."],
        enTokens: ["Unfortunately", ",", "our", "train", "was", "cancelled", "."],
        extraUaTokens: ["затриманий", "вчора", "автобус"],
        extraRuTokens: ["задержан", "вчера", "автобус"],
        extraEnTokens: ["delayed", "yesterday", "bus"],
    },

    [phraseKey("odbavení", "a2-25")]: {
        sk: "Odbavení začíná dvě hodiny před odletem.",
        ua: "Реєстрація починається за дві години до вильоту.",
        ru: "Регистрация начинается за два часа до вылета.",
        en: "Check-in starts two hours before departure.",
        uaTokens: ["Реєстрація", "починається", "за", "дві", "години", "до", "вильоту", "."],
        ruTokens: ["Регистрация", "начинается", "за", "два", "часа", "до", "вылета", "."],
        enTokens: ["Check-in", "starts", "two", "hours", "before", "departure", "."],
        extraUaTokens: ["посадка", "вчора", "після"],
        extraRuTokens: ["посадка", "вчера", "после"],
        extraEnTokens: ["boarding", "yesterday", "after"],
    },

    [phraseKey("cestovní řád", "a2-25")]: {
        sk: "Cestovní řád najdeš na internetu.",
        ua: "Розклад руху ти знайдеш в інтернеті.",
        ru: "Расписание движения ты найдёшь в интернете.",
        en: "You will find the timetable on the internet.",
        uaTokens: ["Розклад", "руху", "ти", "знайдеш", "в", "інтернеті", "."],
        ruTokens: ["Расписание", "движения", "ты", "найдёшь", "в", "интернете", "."],
        enTokens: ["You", "will", "find", "the", "timetable", "on", "the", "internet", "."],
        extraUaTokens: ["квиток", "вчора", "на", "столі"],
        extraRuTokens: ["билет", "вчера", "на", "столе"],
        extraEnTokens: ["ticket", "yesterday", "table"],
    },

    [phraseKey("zpáteční lístek", "a2-25")]: {
        sk: "Prosím jeden zpáteční lístek do Olomouce.",
        ua: "Будь ласка, один квиток туди-назад до Оломоуца.",
        ru: "Пожалуйста, один билет туда-обратно до Оломоуца.",
        en: "One return ticket to Olomouc, please.",
        uaTokens: ["Будь", "ласка", ",", "один", "квиток", "туди-назад", "до", "Оломоуца", "."],
        ruTokens: ["Пожалуйста", ",", "один", "билет", "туда-обратно", "до", "Оломоуца", "."],
        enTokens: ["One", "return", "ticket", "to", "Olomouc", ",", "please", "."],
        extraUaTokens: ["в", "один", "бік", "вчора"],
        extraRuTokens: ["в", "одну", "сторону", "вчера"],
        extraEnTokens: ["one-way", "yesterday", "ticket"],
    },

    [phraseKey("jednosměrný lístek", "a2-25")]: {
        sk: "Tentokrát potřebuji jen jednosměrný lístek.",
        ua: "Цього разу мені потрібен лише квиток в один бік.",
        ru: "В этот раз мне нужен только билет в одну сторону.",
        en: "This time I only need a one-way ticket.",
        uaTokens: ["Цього", "разу", "мені", "потрібен", "лише", "квиток", "в", "один", "бік", "."],
        ruTokens: ["В", "этот", "раз", "мне", "нужен", "только", "билет", "в", "одну", "сторону", "."],
        enTokens: ["This", "time", "I", "only", "need", "a", "one-way", "ticket", "."],
        extraUaTokens: ["туди-назад", "вчора", "два"],
        extraRuTokens: ["туда-обратно", "вчера", "два"],
        extraEnTokens: ["return", "yesterday", "two"],
    },

    [phraseKey("cestovní lístek", "a2-25")]: {
        sk: "Nezapomeň si koupit cestovní lístek.",
        ua: "Не забудь купити квиток.",
        ru: "Не забудь купить билет.",
        en: "Do not forget to buy a ticket.",
        uaTokens: ["Не", "забудь", "купити", "квиток", "."],
        ruTokens: ["Не", "забудь", "купить", "билет", "."],
        enTokens: ["Do", "not", "forget", "to", "buy", "a", "ticket", "."],
        extraUaTokens: ["паспорт", "вчора", "знайти"],
        extraRuTokens: ["паспорт", "вчера", "найти"],
        extraEnTokens: ["passport", "yesterday", "find"],
    },
};