import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_A2_BUILD_UA_SENTENCES_6: BuildUaSentenceDict = {
  // =========================
  // LESSON A2-26 — Комунікація та інформація
  // =========================
  [phraseKey("zpráva", "a2-26")]: {
    sk: "Poslal jsem ti důležitou zprávu.",
    ua: "Я надіслав тобі важливе повідомлення.",
    ru: "Я отправил тебе важное сообщение.",
    en: "I sent you an important message.",
    uaTokens: ["Я", "надіслав", "тобі", "важливе", "повідомлення", "."],
    ruTokens: ["Я", "отправил", "тебе", "важное", "сообщение", "."],
    enTokens: ["I", "sent", "you", "an", "important", "message", "."],
    extraUaTokens: ["лист", "вчора", "коротке"],
    extraRuTokens: ["письмо", "вчера", "короткое"],
    extraEnTokens: ["letter", "yesterday", "short"],
  },

  [phraseKey("oznámení", "a2-26")]: {
    sk: "Na dveřích viselo nové oznámení.",
    ua: "На дверях висіло нове оголошення.",
    ru: "На двери висело новое объявление.",
    en: "A new notice was hanging on the door.",
    uaTokens: ["На", "дверях", "висіло", "нове", "оголошення", "."],
    ruTokens: ["На", "двери", "висело", "новое", "объявление", "."],
    enTokens: ["A", "new", "notice", "was", "hanging", "on", "the", "door", "."],
    extraUaTokens: ["лист", "вчора", "старе"],
    extraRuTokens: ["письмо", "вчера", "старое"],
    extraEnTokens: ["letter", "yesterday", "old"],
  },

  [phraseKey("článek", "a2-26")]: {
    sk: "Ráno jsem četl zajímavý článek.",
    ua: "Вранці я читав цікаву статтю.",
    ru: "Утром я читал интересную статью.",
    en: "In the morning I read an interesting article.",
    uaTokens: ["Вранці", "я", "читав", "цікаву", "статтю", "."],
    ruTokens: ["Утром", "я", "читал", "интересную", "статью", "."],
    enTokens: ["In", "the", "morning", "I", "read", "an", "interesting", "article", "."],
    extraUaTokens: ["книгу", "вчора", "нудну"],
    extraRuTokens: ["книгу", "вчера", "скучную"],
    extraEnTokens: ["book", "yesterday", "boring"],
  },

  [phraseKey("zdroj informací", "a2-26")]: {
    sk: "Internet není vždy spolehlivý zdroj informací.",
    ua: "Інтернет не завжди є надійним джерелом інформації.",
    ru: "Интернет не всегда является надёжным источником информации.",
    en: "The internet is not always a reliable source of information.",
    uaTokens: ["Інтернет", "не", "завжди", "є", "надійним", "джерелом", "інформації", "."],
    ruTokens: ["Интернет", "не", "всегда", "является", "надёжным", "источником", "информации", "."],
    enTokens: ["The", "internet", "is", "not", "always", "a", "reliable", "source", "of", "information", "."],
    extraUaTokens: ["книга", "вчора", "швидким"],
    extraRuTokens: ["книга", "вчера", "быстрым"],
    extraEnTokens: ["book", "yesterday", "fast"],
  },

  [phraseKey("uvést", "a2-26")]: {
    sk: "Tu zprávu chtějí uvést ještě dnes.",
    ua: "Це повідомлення хочуть опублікувати ще сьогодні.",
    ru: "Это сообщение хотят опубликовать ещё сегодня.",
    en: "They want to publish that message today.",
    uaTokens: ["Це", "повідомлення", "хочуть", "опублікувати", "ще", "сьогодні", "."],
    ruTokens: ["Это", "сообщение", "хотят", "опубликовать", "ещё", "сегодня", "."],
    enTokens: ["They", "want", "to", "publish", "that", "message", "today", "."],
    extraUaTokens: ["видалити", "вчора", "лист"],
    extraRuTokens: ["удалить", "вчера", "письмо"],
    extraEnTokens: ["delete", "yesterday", "letter"],
  },

  [phraseKey("zveřejnit", "a2-26")]: {
    sk: "Výsledky budou zveřejněny zítra.",
    ua: "Результати будуть оприлюднені завтра.",
    ru: "Результаты будут опубликованы завтра.",
    en: "The results will be published tomorrow.",
    uaTokens: ["Результати", "будуть", "оприлюднені", "завтра", "."],
    ruTokens: ["Результаты", "будут", "опубликованы", "завтра", "."],
    enTokens: ["The", "results", "will", "be", "published", "tomorrow", "."],
    extraUaTokens: ["сьогодні", "приховані", "вчора"],
    extraRuTokens: ["сегодня", "скрыты", "вчера"],
    extraEnTokens: ["today", "hidden", "yesterday"],
  },

  [phraseKey("reagovat", "a2-26")]: {
    sk: "Na kritiku musíme reagovat klidně.",
    ua: "На критику ми маємо реагувати спокійно.",
    ru: "На критику мы должны реагировать спокойно.",
    en: "We must react calmly to criticism.",
    uaTokens: ["На", "критику", "ми", "маємо", "реагувати", "спокійно", "."],
    ruTokens: ["На", "критику", "мы", "должны", "реагировать", "спокойно", "."],
    enTokens: ["We", "must", "react", "calmly", "to", "criticism", "."],
    extraUaTokens: ["голосно", "вчора", "мовчати"],
    extraRuTokens: ["громко", "вчера", "молчать"],
    extraEnTokens: ["loudly", "yesterday", "stay_silent"],
  },

  [phraseKey("diskuze", "a2-26")]: {
    sk: "Po přednášce následovala diskuze.",
    ua: "Після лекції відбулася дискусія.",
    ru: "После лекции последовала дискуссия.",
    en: "After the lecture, a discussion followed.",
    uaTokens: ["Після", "лекції", "відбулася", "дискусія", "."],
    ruTokens: ["После", "лекции", "последовала", "дискуссия", "."],
    enTokens: ["After", "the", "lecture", ",", "a", "discussion", "followed", "."],
    extraUaTokens: ["перерва", "вчора", "довга"],
    extraRuTokens: ["перерыв", "вчера", "долгий"],
    extraEnTokens: ["break", "yesterday", "long"],
  },

  [phraseKey("názor", "a2-26")]: {
    sk: "Každý má na to jiný názor.",
    ua: "Кожен має на це іншу думку.",
    ru: "У каждого на это другое мнение.",
    en: "Everyone has a different opinion on this.",
    uaTokens: ["Кожен", "має", "на", "це", "іншу", "думку", "."],
    ruTokens: ["У", "каждого", "на", "это", "другое", "мнение", "."],
    enTokens: ["Everyone", "has", "a", "different", "opinion", "on", "this", "."],
    extraUaTokens: ["відповідь", "вчора", "таку"],
    extraRuTokens: ["ответ", "вчера", "такой"],
    extraEnTokens: ["answer", "yesterday", "such"],
  },

  [phraseKey("vliv", "a2-26")]: {
    sk: "Reklama má velký vliv na lidi.",
    ua: "Реклама має великий вплив на людей.",
    ru: "Реклама оказывает большое влияние на людей.",
    en: "Advertising has a big influence on people.",
    uaTokens: ["Реклама", "має", "великий", "вплив", "на", "людей", "."],
    ruTokens: ["Реклама", "оказывает", "большое", "влияние", "на", "людей", "."],
    enTokens: ["Advertising", "has", "a", "big", "influence", "on", "people", "."],
    extraUaTokens: ["малий", "вчора", "дітей"],
    extraRuTokens: ["малое", "вчера", "детей"],
    extraEnTokens: ["small", "yesterday", "children"],
  },

  // =========================
  // LESSON A2-27 — Комунікація (заперечення та аргументи)
  // =========================
  [phraseKey("naopak", "a2-27")]: {
    sk: "Nemyslím si to, naopak mám jiný názor.",
    ua: "Я так не думаю, навпаки маю іншу думку.",
    ru: "Я так не думаю, наоборот у меня другое мнение.",
    en: "I do not think so, on the contrary I have a different opinion.",
    uaTokens: ["Я", "так", "не", "думаю", ",", "навпаки", "маю", "іншу", "думку", "."],
    ruTokens: ["Я", "так", "не", "думаю", ",", "наоборот", "у", "меня", "другое", "мнение", "."],
    enTokens: ["I", "do", "not", "think", "so", ",", "on", "the", "contrary", "I", "have", "a", "different", "opinion", "."],
    extraUaTokens: ["також", "вчора", "таку"],
    extraRuTokens: ["также", "вчера", "такое"],
    extraEnTokens: ["also", "yesterday", "such"],
  },

  [phraseKey("ve skutečnosti", "a2-27")]: {
    sk: "Ve skutečnosti to bylo úplně jinak.",
    ua: "Насправді все було зовсім інакше.",
    ru: "На самом деле всё было совсем иначе.",
    en: "In reality, everything was completely different.",
    uaTokens: ["Насправді", "все", "було", "зовсім", "інакше", "."],
    ruTokens: ["На", "самом", "деле", "всё", "было", "совсем", "иначе", "."],
    enTokens: ["In", "reality", ",", "everything", "was", "completely", "different", "."],
    extraUaTokens: ["так", "вчора", "майже"],
    extraRuTokens: ["так", "вчера", "почти"],
    extraEnTokens: ["so", "yesterday", "almost"],
  },

  [phraseKey("důkaz", "a2-27")]: {
    sk: "Na to nemáme žádný důkaz.",
    ua: "На це в нас немає жодного доказу.",
    ru: "У нас нет на это никаких доказательств.",
    en: "We have no evidence for that.",
    uaTokens: ["На", "це", "в", "нас", "немає", "жодного", "доказу", "."],
    ruTokens: ["У", "нас", "нет", "на", "это", "никаких", "доказательств", "."],
    enTokens: ["We", "have", "no", "evidence", "for", "that", "."],
    extraUaTokens: ["причини", "вчора", "багато"],
    extraRuTokens: ["причин", "вчера", "много"],
    extraEnTokens: ["reasons", "yesterday", "many"],
  },

  [phraseKey("argument", "a2-27")]: {
    sk: "To je silný argument proti tomu.",
    ua: "Це сильний аргумент проти цього.",
    ru: "Это сильный аргумент против этого.",
    en: "That is a strong argument against it.",
    uaTokens: ["Це", "сильний", "аргумент", "проти", "цього", "."],
    ruTokens: ["Это", "сильный", "аргумент", "против", "этого", "."],
    enTokens: ["That", "is", "a", "strong", "argument", "against", "it", "."],
    extraUaTokens: ["слабкий", "вчора", "за"],
    extraRuTokens: ["слабый", "вчера", "за"],
    extraEnTokens: ["weak", "yesterday", "for"],
  },

  [phraseKey("důvod", "a2-27")]: {
    sk: "K tomu máme dobrý důvod.",
    ua: "Для цього в нас є добра причина.",
    ru: "Для этого у нас есть хорошая причина.",
    en: "We have a good reason for that.",
    uaTokens: ["Для", "цього", "в", "нас", "є", "добра", "причина", "."],
    ruTokens: ["Для", "этого", "у", "нас", "есть", "хорошая", "причина", "."],
    enTokens: ["We", "have", "a", "good", "reason", "for", "that", "."],
    extraUaTokens: ["помилка", "вчора", "погана"],
    extraRuTokens: ["ошибка", "вчера", "плохая"],
    extraEnTokens: ["mistake", "yesterday", "bad"],
  },

  [phraseKey("výhoda", "a2-27")]: {
    sk: "Hlavní výhodou je nižší cena.",
    ua: "Головна перевага — нижча ціна.",
    ru: "Главное преимущество — более низкая цена.",
    en: "The main advantage is a lower price.",
    uaTokens: ["Головна", "перевага", "—", "нижча", "ціна", "."],
    ruTokens: ["Главное", "преимущество", "—", "более", "низкая", "цена", "."],
    enTokens: ["The", "main", "advantage", "is", "a", "lower", "price", "."],
    extraUaTokens: ["недолік", "вчора", "вища"],
    extraRuTokens: ["недостаток", "вчера", "высокая"],
    extraEnTokens: ["disadvantage", "yesterday", "higher"],
  },

  [phraseKey("nevýhoda", "a2-27")]: {
    sk: "Nevýhodou je dlouhé čekání.",
    ua: "Недоліком є довге очікування.",
    ru: "Недостаток — долгое ожидание.",
    en: "The disadvantage is a long wait.",
    uaTokens: ["Недоліком", "є", "довге", "очікування", "."],
    ruTokens: ["Недостаток", "—", "долгое", "ожидание", "."],
    enTokens: ["The", "disadvantage", "is", "a", "long", "wait", "."],
    extraUaTokens: ["перевага", "вчора", "швидкому"],
    extraRuTokens: ["преимущество", "вчера", "быстром"],
    extraEnTokens: ["advantage", "yesterday", "fast"],
  },

  [phraseKey("záleží", "a2-27")]: {
    sk: "Záleží na tom, co potřebuješ.",
    ua: "Це залежить від того, що тобі потрібно.",
    ru: "Это зависит от того, что тебе нужно.",
    en: "It depends on what you need.",
    uaTokens: ["Це", "залежить", "від", "того", ",", "що", "тобі", "потрібно", "."],
    ruTokens: ["Это", "зависит", "от", "того", ",", "что", "тебе", "нужно", "."],
    enTokens: ["It", "depends", "on", "what", "you", "need", "."],
    extraUaTokens: ["не", "вчора", "хочеться"],
    extraRuTokens: ["не", "вчера", "хочется"],
    extraEnTokens: ["not", "yesterday", "want"],
  },

  [phraseKey("přesvědčit", "a2-27")]: {
    sk: "Nebude snadné ho přesvědčit.",
    ua: "Його буде непросто переконати.",
    ru: "Его будет непросто убедить.",
    en: "It will not be easy to convince him.",
    uaTokens: ["Його", "буде", "непросто", "переконати", "."],
    ruTokens: ["Его", "будет", "непросто", "убедить", "."],
    enTokens: ["It", "will", "not", "be", "easy", "to", "convince", "him", "."],
    extraUaTokens: ["змусити", "вчора", "легко"],
    extraRuTokens: ["заставить", "вчера", "легко"],
    extraEnTokens: ["force", "yesterday", "easily"],
  },

  [phraseKey("souhlasit s tím", "a2-27")]: {
    sk: "Nemůžu s tím úplně souhlasit.",
    ua: "Я не можу з цим повністю погодитися.",
    ru: "Я не могу с этим полностью согласиться.",
    en: "I cannot fully agree with that.",
    uaTokens: ["Я", "не", "можу", "з", "цим", "повністю", "погодитися", "."],
    ruTokens: ["Я", "не", "могу", "с", "этим", "полностью", "согласиться", "."],
    enTokens: ["I", "cannot", "fully", "agree", "with", "that", "."],
    extraUaTokens: ["сперечатися", "вчора", "частково"],
    extraRuTokens: ["спорить", "вчера", "частично"],
    extraEnTokens: ["argue", "yesterday", "partly"],
  },

  // =========================
  // LESSON A2-28 — Технології (інтернет та безпека)
  // =========================
  [phraseKey("soukromí", "a2-28")]: {
    sk: "Na internetu je soukromí velmi důležité.",
    ua: "В інтернеті приватність дуже важлива.",
    ru: "В интернете приватность очень важна.",
    en: "Privacy is very important on the internet.",
    uaTokens: ["В", "інтернеті", "приватність", "дуже", "важлива", "."],
    ruTokens: ["В", "интернете", "приватность", "очень", "важна", "."],
    enTokens: ["Privacy", "is", "very", "important", "on", "the", "internet", "."],
    extraUaTokens: ["реклама", "вчора", "неважлива"],
    extraRuTokens: ["реклама", "вчера", "неважна"],
    extraEnTokens: ["advertising", "yesterday", "unimportant"],
  },

  [phraseKey("bezpečnost", "a2-28")]: {
    sk: "Musíme myslet na bezpečnost dat.",
    ua: "Ми маємо думати про безпеку даних.",
    ru: "Мы должны думать о безопасности данных.",
    en: "We must think about data security.",
    uaTokens: ["Ми", "маємо", "думати", "про", "безпеку", "даних", "."],
    ruTokens: ["Мы", "должны", "думать", "о", "безопасности", "данных", "."],
    enTokens: ["We", "must", "think", "about", "data", "security", "."],
    extraUaTokens: ["швидкість", "вчора", "фото"],
    extraRuTokens: ["скорость", "вчера", "фото"],
    extraEnTokens: ["speed", "yesterday", "photo"],
  },

  [phraseKey("ověření", "a2-28")]: {
    sk: "Bez ověření se nepřihlásíš.",
    ua: "Без верифікації ти не увійдеш.",
    ru: "Без подтверждения ты не войдёшь.",
    en: "Without verification, you will not log in.",
    uaTokens: ["Без", "верифікації", "ти", "не", "увійдеш", "."],
    ruTokens: ["Без", "подтверждения", "ты", "не", "войдёшь", "."],
    enTokens: ["Without", "verification", ",", "you", "will", "not", "log", "in", "."],
    extraUaTokens: ["пароля", "вчора", "зможеш"],
    extraRuTokens: ["пароля", "вчера", "сможешь"],
    extraEnTokens: ["password", "yesterday", "can"],
  },

  [phraseKey("dvojfaktorové ověření", "a2-28")]: {
    sk: "Mám zapnuté dvojfaktorové ověření.",
    ua: "У мене ввімкнена двофакторна автентифікація.",
    ru: "У меня включена двухфакторная аутентификация.",
    en: "I have two-factor authentication enabled.",
    uaTokens: ["У", "мене", "ввімкнена", "двофакторна", "автентифікація", "."],
    ruTokens: ["У", "меня", "включена", "двухфакторная", "аутентификация", "."],
    enTokens: ["I", "have", "two-factor", "authentication", "enabled", "."],
    extraUaTokens: ["одноразова", "вчора", "пошта"],
    extraRuTokens: ["одноразовая", "вчера", "почта"],
    extraEnTokens: ["one-time", "yesterday", "mail"],
  },

  [phraseKey("podvod", "a2-28")]: {
    sk: "Vypadalo to jako internetový podvod.",
    ua: "Це виглядало як інтернет-шахрайство.",
    ru: "Это выглядело как интернет-мошенничество.",
    en: "It looked like an internet scam.",
    uaTokens: ["Це", "виглядало", "як", "інтернет-шахрайство", "."],
    ruTokens: ["Это", "выглядело", "как", "интернет-мошенничество", "."],
    enTokens: ["It", "looked", "like", "an", "internet", "scam", "."],
    extraUaTokens: ["реклама", "вчора", "чесна"],
    extraRuTokens: ["реклама", "вчера", "честная"],
    extraEnTokens: ["advertising", "yesterday", "honest"],
  },

  [phraseKey("odkaz", "a2-28")]: {
    sk: "Neklikej na podezřelý odkaz.",
    ua: "Не натискай на підозріле посилання.",
    ru: "Не нажимай на подозрительную ссылку.",
    en: "Do not click on a suspicious link.",
    uaTokens: ["Не", "натискай", "на", "підозріле", "посилання", "."],
    ruTokens: ["Не", "нажимай", "на", "подозрительную", "ссылку", "."],
    enTokens: ["Do", "not", "click", "on", "a", "suspicious", "link", "."],
    extraUaTokens: ["файл", "вчора", "безпечне"],
    extraRuTokens: ["файл", "вчера", "безопасную"],
    extraEnTokens: ["file", "yesterday", "safe"],
  },

  [phraseKey("stáhnout soubor", "a2-28")]: {
    sk: "Nechci stáhnout neznámý soubor.",
    ua: "Я не хочу завантажувати невідомий файл.",
    ru: "Я не хочу скачивать неизвестный файл.",
    en: "I do not want to download an unknown file.",
    uaTokens: ["Я", "не", "хочу", "завантажувати", "невідомий", "файл", "."],
    ruTokens: ["Я", "не", "хочу", "скачивать", "неизвестный", "файл", "."],
    enTokens: ["I", "do", "not", "want", "to", "download", "an", "unknown", "file", "."],
    extraUaTokens: ["посилання", "вчора", "відоме"],
    extraRuTokens: ["ссылку", "вчера", "известный"],
    extraEnTokens: ["link", "yesterday", "known"],
  },

  [phraseKey("virus", "a2-28")]: {
    sk: "Ten počítač možná napadl virus.",
    ua: "Можливо, цей комп’ютер атакував вірус.",
    ru: "Возможно, этот компьютер атаковал вирус.",
    en: "The computer may have been attacked by a virus.",
    uaTokens: ["Можливо", ",", "цей", "комп’ютер", "атакував", "вірус", "."],
    ruTokens: ["Возможно", ",", "этот", "компьютер", "атаковал", "вирус", "."],
    enTokens: ["The", "computer", "may", "have", "been", "attacked", "by", "a", "virus", "."],
    extraUaTokens: ["хакер", "вчора", "захистив"],
    extraRuTokens: ["хакер", "вчера", "защитил"],
    extraEnTokens: ["hacker", "yesterday", "protected"],
    uaAltAnswers: [["Можливо", ",", "цей", "комп’ютер", "заразив", "вірус", "."]],
    ruAltAnswers: [["Возможно", ",", "этот", "компьютер", "заразил", "вирус", "."]],
  },

  [phraseKey("zablokovat", "a2-28")]: {
    sk: "Musel jsem ten účet zablokovat.",
    ua: "Мені довелося заблокувати той акаунт.",
    ru: "Мне пришлось заблокировать тот аккаунт.",
    en: "I had to block that account.",
    uaTokens: ["Мені", "довелося", "заблокувати", "той", "акаунт", "."],
    ruTokens: ["Мне", "пришлось", "заблокировать", "тот", "аккаунт", "."],
    enTokens: ["I", "had", "to", "block", "that", "account", "."],
    extraUaTokens: ["відновити", "вчора", "пошту"],
    extraRuTokens: ["восстановить", "вчера", "почту"],
    extraEnTokens: ["restore", "yesterday", "mail"],
  },

  [phraseKey("obnovit heslo", "a2-28")]: {
    sk: "Potřebuji obnovit heslo k e-mailu.",
    ua: "Мені потрібно відновити пароль до електронної пошти.",
    ru: "Мне нужно восстановить пароль к электронной почте.",
    en: "I need to reset the email password.",
    uaTokens: ["Мені", "потрібно", "відновити", "пароль", "до", "електронної", "пошти", "."],
    ruTokens: ["Мне", "нужно", "восстановить", "пароль", "к", "электронной", "почте", "."],
    enTokens: ["I", "need", "to", "reset", "the", "email", "password", "."],
    extraUaTokens: ["логін", "вчора", "змінити"],
    extraRuTokens: ["логин", "вчера", "изменить"],
    extraEnTokens: ["login", "yesterday", "change"],
  },

  // =========================
  // LESSON A2-29 — Емоції (розширено)
  // =========================
  [phraseKey("zklamaný", "a2-29")]: {
    sk: "Byl jsem z výsledku dost zklamaný.",
    ua: "Я був досить розчарований результатом.",
    ru: "Я был довольно разочарован результатом.",
    en: "I was quite disappointed with the result.",
    uaTokens: ["Я", "був", "досить", "розчарований", "результатом", "."],
    ruTokens: ["Я", "был", "довольно", "разочарован", "результатом", "."],
    enTokens: ["I", "was", "quite", "disappointed", "with", "the", "result", "."],
    extraUaTokens: ["задоволений", "вчора", "новиною"],
    extraRuTokens: ["доволен", "вчера", "новостью"],
    extraEnTokens: ["satisfied", "yesterday", "news"],
  },

  [phraseKey("naštvaný", "a2-29")]: {
    sk: "Kvůli té chybě byl hodně naštvaný.",
    ua: "Через ту помилку він був дуже злий.",
    ru: "Из-за той ошибки он был очень злой.",
    en: "Because of that mistake, he was very angry.",
    uaTokens: ["Через", "ту", "помилку", "він", "був", "дуже", "злий", "."],
    ruTokens: ["Из-за", "той", "ошибки", "он", "был", "очень", "злой", "."],
    enTokens: ["Because", "of", "that", "mistake", ",", "he", "was", "very", "angry", "."],
    extraUaTokens: ["спокійний", "вчора", "через"],
    extraRuTokens: ["спокойный", "вчера", "из-за"],
    extraEnTokens: ["calm", "yesterday", "because"],
  },

  [phraseKey("nadšený", "a2-29")]: {
    sk: "Děti byly z výletu nadšené.",
    ua: "Діти були в захваті від поїздки.",
    ru: "Дети были в восторге от поездки.",
    en: "The children were excited about the trip.",
    uaTokens: ["Діти", "були", "в", "захваті", "від", "поїздки", "."],
    ruTokens: ["Дети", "были", "в", "восторге", "от", "поездки", "."],
    enTokens: ["The", "children", "were", "excited", "about", "the", "trip", "."],
    extraUaTokens: ["розчаровані", "вчора", "уроком"],
    extraRuTokens: ["разочарованы", "вчера", "уроком"],
    extraEnTokens: ["disappointed", "yesterday", "lesson"],
  },

  [phraseKey("zmatený", "a2-29")]: {
    sk: "Po tom vysvětlení jsem byl zmatený.",
    ua: "Після того пояснення я був розгублений.",
    ru: "После того объяснения я был растерян.",
    en: "After that explanation, I was confused.",
    uaTokens: ["Після", "того", "пояснення", "я", "був", "розгублений", "."],
    ruTokens: ["После", "того", "объяснения", "я", "был", "растерян", "."],
    enTokens: ["After", "that", "explanation", ",", "I", "was", "confused", "."],
    extraUaTokens: ["упевнений", "вчора", "відповіддю"],
    extraRuTokens: ["уверен", "вчера", "ответом"],
    extraEnTokens: ["sure", "yesterday", "answer"],
  },

  [phraseKey("znepokojený", "a2-29")]: {
    sk: "Rodiče byli trochu znepokojení.",
    ua: "Батьки були трохи стурбовані.",
    ru: "Родители были немного обеспокоены.",
    en: "The parents were a bit worried.",
    uaTokens: ["Батьки", "були", "трохи", "стурбовані", "."],
    ruTokens: ["Родители", "были", "немного", "обеспокоены", "."],
    enTokens: ["The", "parents", "were", "a", "bit", "worried", "."],
    extraUaTokens: ["раді", "вчора", "дуже"],
    extraRuTokens: ["рады", "вчера", "очень"],
    extraEnTokens: ["happy", "yesterday", "very"],
  },

  [phraseKey("hrdý", "a2-29")]: {
    sk: "Jsem na tebe opravdu hrdý.",
    ua: "Я справді тобою пишаюся.",
    ru: "Я действительно тобой горжусь.",
    en: "I am really proud of you.",
    uaTokens: ["Я", "справді", "тобою", "пишаюся", "."],
    ruTokens: ["Я", "действительно", "тобой", "горжусь", "."],
    enTokens: ["I", "am", "really", "proud", "of", "you", "."],
    extraUaTokens: ["соромлюся", "вчора", "тебе"],
    extraRuTokens: ["стыжусь", "вчера", "тебя"],
    extraEnTokens: ["ashamed", "yesterday", "you"],
  },

  [phraseKey("vděčný", "a2-29")]: {
    sk: "Jsem ti za pomoc velmi vděčný.",
    ua: "Я дуже вдячний тобі за допомогу.",
    ru: "Я очень благодарен тебе за помощь.",
    en: "I am very grateful to you for your help.",
    uaTokens: ["Я", "дуже", "вдячний", "тобі", "за", "допомогу", "."],
    ruTokens: ["Я", "очень", "благодарен", "тебе", "за", "помощь", "."],
    enTokens: ["I", "am", "very", "grateful", "to", "you", "for", "your", "help", "."],
    extraUaTokens: ["злий", "вчора", "за"],
    extraRuTokens: ["зол", "вчера", "за"],
    extraEnTokens: ["angry", "yesterday", "for"],
  },

  [phraseKey("stydět se", "a2-29")]: {
    sk: "Nemusíš se za to stydět.",
    ua: "Тобі не треба цього соромитися.",
    ru: "Тебе не нужно этого стыдиться.",
    en: "You do not have to be ashamed of it.",
    uaTokens: ["Тобі", "не", "треба", "цього", "соромитися", "."],
    ruTokens: ["Тебе", "не", "нужно", "этого", "стыдиться", "."],
    enTokens: ["You", "do", "not", "have", "to", "be", "ashamed", "of", "it", "."],
    extraUaTokens: ["боятися", "вчора", "цього"],
    extraRuTokens: ["бояться", "вчера", "этого"],
    extraEnTokens: ["fear", "yesterday", "this"],
  },

  [phraseKey("litovat", "a2-29")]: {
    sk: "Nechci později ničeho litovat.",
    ua: "Я не хочу потім ні про що шкодувати.",
    ru: "Я не хочу потом ни о чём жалеть.",
    en: "I do not want to regret anything later.",
    uaTokens: ["Я", "не", "хочу", "потім", "ні", "про", "що", "шкодувати", "."],
    ruTokens: ["Я", "не", "хочу", "потом", "ни", "о", "чём", "жалеть", "."],
    enTokens: ["I", "do", "not", "want", "to", "regret", "anything", "later", "."],
    extraUaTokens: ["знати", "вчора", "усе"],
    extraRuTokens: ["знать", "вчера", "всё"],
    extraEnTokens: ["know", "yesterday", "everything"],
  },

  [phraseKey("ulevit se", "a2-29")]: {
    sk: "Po dobré zprávě se mi ulevilo.",
    ua: "Після доброї новини мені полегшало.",
    ru: "После хорошей новости мне стало легче.",
    en: "After the good news, I felt relieved.",
    uaTokens: ["Після", "доброї", "новини", "мені", "полегшало", "."],
    ruTokens: ["После", "хорошей", "новости", "мне", "стало", "легче", "."],
    enTokens: ["After", "the", "good", "news", ",", "I", "felt", "relieved", "."],
    extraUaTokens: ["гірше", "вчора", "після"],
    extraRuTokens: ["хуже", "вчера", "после"],
    extraEnTokens: ["worse", "yesterday", "after"],
  },

  // =========================
  // LESSON A2-30 — Повторення A2 (21–29)
  // =========================
  [phraseKey("náhradní díl", "a2-30")]: {
    sk: "Bez náhradního dílu to nepůjde opravit.",
    ua: "Без запасної частини це не вдасться відремонтувати.",
    ru: "Без запасной части это не получится починить.",
    en: "Without a spare part, it cannot be repaired.",
    uaTokens: ["Без", "запасної", "частини", "це", "не", "вдасться", "відремонтувати", "."],
    ruTokens: ["Без", "запасной", "части", "это", "не", "получится", "починить", "."],
    enTokens: ["Without", "a", "spare", "part", ",", "it", "cannot", "be", "repaired", "."],
    extraUaTokens: ["майстра", "вчора", "швидко"],
    extraRuTokens: ["мастера", "вчера", "быстро"],
    extraEnTokens: ["technician", "yesterday", "quickly"],
  },

  [phraseKey("dávkování", "a2-30")]: {
    sk: "Správné dávkování je velmi důležité.",
    ua: "Правильне дозування дуже важливе.",
    ru: "Правильная дозировка очень важна.",
    en: "Correct dosage is very important.",
    uaTokens: ["Правильне", "дозування", "дуже", "важливе", "."],
    ruTokens: ["Правильная", "дозировка", "очень", "важна", "."],
    enTokens: ["Correct", "dosage", "is", "very", "important", "."],
    extraUaTokens: ["неправильне", "вчора", "лікування"],
    extraRuTokens: ["неправильная", "вчера", "лечение"],
    extraEnTokens: ["incorrect", "yesterday", "treatment"],
  },

  [phraseKey("krádež", "a2-30")]: {
    sk: "Tu krádež už vyšetřuje policie.",
    ua: "Цю крадіжку вже розслідує поліція.",
    ru: "Эту кражу уже расследует полиция.",
    en: "The police are already investigating that theft.",
    uaTokens: ["Цю", "крадіжку", "вже", "розслідує", "поліція", "."],
    ruTokens: ["Эту", "кражу", "уже", "расследует", "полиция", "."],
    enTokens: ["The", "police", "are", "already", "investigating", "that", "theft", "."],
    extraUaTokens: ["аварію", "вчора", "лікарня"],
    extraRuTokens: ["аварию", "вчера", "больница"],
    extraEnTokens: ["accident", "yesterday", "hospital"],
  },

  [phraseKey("ingredience", "a2-30")]: {
    sk: "Na stole už byly všechny ingredience.",
    ua: "На столі вже були всі інгредієнти.",
    ru: "На столе уже были все ингредиенты.",
    en: "All the ingredients were already on the table.",
    uaTokens: ["На", "столі", "вже", "були", "всі", "інгредієнти", "."],
    ruTokens: ["На", "столе", "уже", "были", "все", "ингредиенты", "."],
    enTokens: ["All", "the", "ingredients", "were", "already", "on", "the", "table", "."],
    extraUaTokens: ["тарілки", "вчора", "мало"],
    extraRuTokens: ["тарелки", "вчера", "мало"],
    extraEnTokens: ["plates", "yesterday", "few"],
  },

  [phraseKey("itinerář", "a2-30")]: {
    sk: "Náš itinerář se trochu změnil.",
    ua: "Наш маршрут трохи змінився.",
    ru: "Наш маршрут немного изменился.",
    en: "Our itinerary changed a little.",
    uaTokens: ["Наш", "маршрут", "трохи", "змінився", "."],
    ruTokens: ["Наш", "маршрут", "немного", "изменился", "."],
    enTokens: ["Our", "itinerary", "changed", "a", "little", "."],
    extraUaTokens: ["квиток", "вчора", "загубився"],
    extraRuTokens: ["билет", "вчера", "потерялся"],
    extraEnTokens: ["ticket", "yesterday", "lost"],
  },

  [phraseKey("výplatní páska", "a2-30")]: {
    sk: "Výplatní pásku dostaneme e-mailem.",
    ua: "Розрахунковий листок ми отримаємо електронною поштою.",
    ru: "Расчётный листок мы получим по электронной почте.",
    en: "We will receive the payslip by email.",
    uaTokens: ["Розрахунковий", "листок", "ми", "отримаємо", "електронною", "поштою", "."],
    ruTokens: ["Расчётный", "листок", "мы", "получим", "по", "электронной", "почте", "."],
    enTokens: ["We", "will", "receive", "the", "payslip", "by", "email", "."],
    extraUaTokens: ["зарплату", "вчора", "звичайною"],
    extraRuTokens: ["зарплату", "вчера", "обычной"],
    extraEnTokens: ["salary", "yesterday", "regular"],
  },

  [phraseKey("argument", "a2-30")]: {
    sk: "Tohle není dost silný argument.",
    ua: "Це недостатньо сильний аргумент.",
    ru: "Это недостаточно сильный аргумент.",
    en: "This is not a strong enough argument.",
    uaTokens: ["Це", "недостатньо", "сильний", "аргумент", "."],
    ruTokens: ["Это", "недостаточно", "сильный", "аргумент", "."],
    enTokens: ["This", "is", "not", "a", "strong", "enough", "argument", "."],
    extraUaTokens: ["доказ", "вчора", "слабкий"],
    extraRuTokens: ["доказательство", "вчера", "слабый"],
    extraEnTokens: ["proof", "yesterday", "weak"],
  },

  [phraseKey("podvod", "a2-30")]: {
    sk: "Nakonec se ukázalo, že to byl podvod.",
    ua: "Зрештою виявилося, що це було шахрайство.",
    ru: "В итоге оказалось, что это было мошенничество.",
    en: "In the end, it turned out to be a scam.",
    uaTokens: ["Зрештою", "виявилося", ",", "що", "це", "було", "шахрайство", "."],
    ruTokens: ["В", "итоге", "оказалось", ",", "что", "это", "было", "мошенничество", "."],
    enTokens: ["In", "the", "end", ",", "it", "turned", "out", "to", "be", "a", "scam", "."],
    extraUaTokens: ["помилка", "вчора", "чесно"],
    extraRuTokens: ["ошибка", "вчера", "честно"],
    extraEnTokens: ["mistake", "yesterday", "honestly"],
  },

  [phraseKey("znepokojený", "a2-30")]: {
    sk: "Kvůli té situaci byl znepokojený.",
    ua: "Через ту ситуацію він був стурбований.",
    ru: "Из-за той ситуации он был обеспокоен.",
    en: "Because of that situation, he was worried.",
    uaTokens: ["Через", "ту", "ситуацію", "він", "був", "стурбований", "."],
    ruTokens: ["Из-за", "той", "ситуации", "он", "был", "обеспокоен", "."],
    enTokens: ["Because", "of", "that", "situation", ",", "he", "was", "worried", "."],
    extraUaTokens: ["спокійний", "вчора", "дуже"],
    extraRuTokens: ["спокоен", "вчера", "очень"],
    extraEnTokens: ["calm", "yesterday", "very"],
  },

  [phraseKey("záleží", "a2-30")]: {
    sk: "Všechno záleží na správném rozhodnutí.",
    ua: "Усе залежить від правильного рішення.",
    ru: "Всё зависит от правильного решения.",
    en: "Everything depends on the right decision.",
    uaTokens: ["Усе", "залежить", "від", "правильного", "рішення", "."],
    ruTokens: ["Всё", "зависит", "от", "правильного", "решения", "."],
    enTokens: ["Everything", "depends", "on", "the", "right", "decision", "."],
    extraUaTokens: ["помилки", "вчора", "не"],
    extraRuTokens: ["ошибки", "вчера", "не"],
    extraEnTokens: ["mistake", "yesterday", "not"],
  },
};