import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_A2_BUILD_UA_SENTENCES_7: BuildUaSentenceDict = {
  // =========================
  // LESSON A2-31 — Житло (пошук і оренда)
  // =========================
  [phraseKey("nabídka", "a2-31")]: {
    sk: "Ta nabídka bytu vypadá zajímavě.",
    ua: "Ця пропозиція квартири виглядає цікаво.",
    ru: "Это предложение квартиры выглядит интересно.",
    en: "This apartment offer looks interesting.",
    uaTokens: ["Ця", "пропозиція", "квартири", "виглядає", "цікаво", "."],
    ruTokens: ["Это", "предложение", "квартиры", "выглядит", "интересно", "."],
    enTokens: ["This", "apartment", "offer", "looks", "interesting", "."],
    extraUaTokens: ["будинку", "вчора", "дивно"],
    extraRuTokens: ["дома", "вчера", "странно"],
    extraEnTokens: ["house", "yesterday", "strange"],
  },

  [phraseKey("poptávka", "a2-31")]: {
    sk: "V centru je velká poptávka po bytech.",
    ua: "У центрі великий попит на квартири.",
    ru: "В центре большой спрос на квартиры.",
    en: "There is high demand for apartments in the center.",
    uaTokens: ["У", "центрі", "великий", "попит", "на", "квартири", "."],
    ruTokens: ["В", "центре", "большой", "спрос", "на", "квартиры", "."],
    enTokens: ["There", "is", "high", "demand", "for", "apartments", "in", "the", "center", "."],
    extraUaTokens: ["малій", "вчора", "будинки"],
    extraRuTokens: ["маленький", "вчера", "дома"],
    extraEnTokens: ["small", "yesterday", "houses"],
  },

  [phraseKey("prohlídka", "a2-31")]: {
    sk: "Zítra máme prohlídku bytu.",
    ua: "Завтра у нас огляд квартири.",
    ru: "Завтра у нас осмотр квартиры.",
    en: "Tomorrow we have an apartment viewing.",
    uaTokens: ["Завтра", "у", "нас", "огляд", "квартири", "."],
    ruTokens: ["Завтра", "у", "нас", "осмотр", "квартиры", "."],
    enTokens: ["Tomorrow", "we", "have", "an", "apartment", "viewing", "."],
    extraUaTokens: ["будинку", "вчора", "ремонт"],
    extraRuTokens: ["дома", "вчера", "ремонт"],
    extraEnTokens: ["house", "yesterday", "repair"],
  },

  [phraseKey("záloha", "a2-31")]: {
    sk: "Majitel požaduje zálohu předem.",
    ua: "Власник вимагає заставу наперед.",
    ru: "Владелец требует залог заранее.",
    en: "The owner requires a deposit in advance.",
    uaTokens: ["Власник", "вимагає", "заставу", "наперед", "."],
    ruTokens: ["Владелец", "требует", "залог", "заранее", "."],
    enTokens: ["The", "owner", "requires", "a", "deposit", "in", "advance", "."],
    extraUaTokens: ["знижку", "вчора", "потім"],
    extraRuTokens: ["скидку", "вчера", "потом"],
    extraEnTokens: ["discount", "yesterday", "later"],
  },

  [phraseKey("kauce", "a2-31")]: {
    sk: "Kauce je ve výši jednoho nájmu.",
    ua: "Кауція дорівнює вартості одного місяця оренди.",
    ru: "Депозит равен стоимости одного месяца аренды.",
    en: "The deposit equals one month's rent.",
    uaTokens: ["Кауція", "дорівнює", "вартості", "одного", "місяця", "оренди", "."],
    ruTokens: ["Депозит", "равен", "стоимости", "одного", "месяца", "аренды", "."],
    enTokens: ["The", "deposit", "equals", "one", "month's", "rent", "."],
    extraUaTokens: ["двох", "вчора", "кімнат"],
    extraRuTokens: ["двух", "вчера", "комнат"],
    extraEnTokens: ["two", "yesterday", "rooms"],
  },

  [phraseKey("měsíční platba", "a2-31")]: {
    sk: "Měsíční platba je dvanáct tisíc korun.",
    ua: "Щомісячна оплата становить дванадцять тисяч крон.",
    ru: "Ежемесячная оплата составляет двенадцать тысяч крон.",
    en: "The monthly payment is twelve thousand crowns.",
    uaTokens: ["Щомісячна", "оплата", "становить", "дванадцять", "тисяч", "крон", "."],
    ruTokens: ["Ежемесячная", "оплата", "составляет", "двенадцать", "тысяч", "крон", "."],
    enTokens: ["The", "monthly", "payment", "is", "twelve", "thousand", "crowns", "."],
    extraUaTokens: ["десять", "вчора", "євро"],
    extraRuTokens: ["десять", "вчера", "евро"],
    extraEnTokens: ["ten", "yesterday", "euros"],
  },

  [phraseKey("energie v ceně", "a2-31")]: {
    sk: "V inzerátu bylo napsáno energie v ceně.",
    ua: "В оголошенні було написано, що комунальні включені.",
    ru: "В объявлении было написано, что коммунальные включены.",
    en: "The ad said utilities are included.",
    uaTokens: ["В", "оголошенні", "було", "написано", ",", "що", "комунальні", "включені", "."],
    ruTokens: ["В", "объявлении", "было", "написано", ",", "что", "коммунальные", "включены", "."],
    enTokens: ["The", "ad", "said", "utilities", "are", "included", "."],
    extraUaTokens: ["окремо", "вчора", "оренда"],
    extraRuTokens: ["отдельно", "вчера", "аренда"],
    extraEnTokens: ["separately", "yesterday", "rent"],
  },

  [phraseKey("zařízený", "a2-31")]: {
    sk: "Hledáme zařízený byt v klidné části města.",
    ua: "Ми шукаємо мебльовану квартиру в тихій частині міста.",
    ru: "Мы ищем меблированную квартиру в тихой части города.",
    en: "We are looking for a furnished apartment in a quiet part of the city.",
    uaTokens: ["Ми", "шукаємо", "мебльовану", "квартиру", "в", "тихій", "частині", "міста", "."],
    ruTokens: ["Мы", "ищем", "меблированную", "квартиру", "в", "тихой", "части", "города", "."],
    enTokens: ["We", "are", "looking", "for", "a", "furnished", "apartment", "in", "a", "quiet", "part", "of", "the", "city", "."],
    extraUaTokens: ["немебльовану", "вчора", "селі"],
    extraRuTokens: ["немеблированную", "вчера", "деревне"],
    extraEnTokens: ["unfurnished", "yesterday", "village"],
  },

  [phraseKey("nezařízený", "a2-31")]: {
    sk: "Ten byt je úplně nezařízený.",
    ua: "Ця квартира зовсім немебльована.",
    ru: "Эта квартира совсем немеблированная.",
    en: "This apartment is completely unfurnished.",
    uaTokens: ["Ця", "квартира", "зовсім", "немебльована", "."],
    ruTokens: ["Эта", "квартира", "совсем", "немеблированная", "."],
    enTokens: ["This", "apartment", "is", "completely", "unfurnished", "."],
    extraUaTokens: ["мебльована", "вчора", "кімната"],
    extraRuTokens: ["меблированная", "вчера", "комната"],
    extraEnTokens: ["furnished", "yesterday", "room"],
  },

  [phraseKey("spolubydlení", "a2-31")]: {
    sk: "Spolubydlení je levnější než vlastní byt.",
    ua: "Спільне проживання дешевше, ніж окрема квартира.",
    ru: "Совместное проживание дешевле, чем отдельная квартира.",
    en: "Shared living is cheaper than having your own apartment.",
    uaTokens: ["Спільне", "проживання", "дешевше", ",", "ніж", "окрема", "квартира", "."],
    ruTokens: ["Совместное", "проживание", "дешевле", ",", "чем", "отдельная", "квартира", "."],
    enTokens: ["Shared", "living", "is", "cheaper", "than", "having", "your", "own", "apartment", "."],
    extraUaTokens: ["дорожче", "вчора", "будинок"],
    extraRuTokens: ["дороже", "вчера", "дом"],
    extraEnTokens: ["more_expensive", "yesterday", "house"],
  },

  // =========================
  // LESSON A2-32 — Робота (професійні навички)
  // =========================
  [phraseKey("schopnost", "a2-32")]: {
    sk: "Komunikace je důležitá schopnost.",
    ua: "Комунікація — важлива навичка.",
    ru: "Коммуникация — важный навык.",
    en: "Communication is an important skill.",
    uaTokens: ["Комунікація", "—", "важлива", "навичка", "."],
    ruTokens: ["Коммуникация", "—", "важный", "навык", "."],
    enTokens: ["Communication", "is", "an", "important", "skill", "."],
    extraUaTokens: ["помилка", "вчора", "неважлива"],
    extraRuTokens: ["ошибка", "вчера", "неважная"],
    extraEnTokens: ["mistake", "yesterday", "unimportant"],
  },

  [phraseKey("zručnost", "a2-32")]: {
    sk: "Tato zručnost se ti bude hodit v práci.",
    ua: "Ця навичка стане тобі в пригоді на роботі.",
    ru: "Этот навык пригодится тебе на работе.",
    en: "This skill will be useful to you at work.",
    uaTokens: ["Ця", "навичка", "стане", "тобі", "в", "пригоді", "на", "роботі", "."],
    ruTokens: ["Этот", "навык", "пригодится", "тебе", "на", "работе", "."],
    enTokens: ["This", "skill", "will", "be", "useful", "to", "you", "at", "work", "."],
    extraUaTokens: ["хобі", "вчора", "школі"],
    extraRuTokens: ["хобби", "вчера", "школе"],
    extraEnTokens: ["hobby", "yesterday", "school"],
  },

  [phraseKey("zkušenosti", "a2-32")]: {
    sk: "Máte už nějaké pracovní zkušenosti?",
    ua: "У вас уже є якийсь робочий досвід?",
    ru: "У вас уже есть какой-то рабочий опыт?",
    en: "Do you already have any work experience?",
    uaTokens: ["У", "вас", "уже", "є", "якийсь", "робочий", "досвід", "?"],
    ruTokens: ["У", "вас", "уже", "есть", "какой-то", "рабочий", "опыт", "?"],
    enTokens: ["Do", "you", "already", "have", "any", "work", "experience", "?"],
    extraUaTokens: ["освіта", "вчора", "трохи"],
    extraRuTokens: ["образование", "вчера", "немного"],
    extraEnTokens: ["education", "yesterday", "some"],
  },

  [phraseKey("odpovědný", "a2-32")]: {
    sk: "Hledáme odpovědného pracovníka.",
    ua: "Ми шукаємо відповідального працівника.",
    ru: "Мы ищем ответственного работника.",
    en: "We are looking for a responsible worker.",
    uaTokens: ["Ми", "шукаємо", "відповідального", "працівника", "."],
    ruTokens: ["Мы", "ищем", "ответственного", "работника", "."],
    enTokens: ["We", "are", "looking", "for", "a", "responsible", "worker", "."],
    extraUaTokens: ["ледачого", "вчора", "студента"],
    extraRuTokens: ["ленивого", "вчера", "студента"],
    extraEnTokens: ["lazy", "yesterday", "student"],
  },

  [phraseKey("samostatný", "a2-32")]: {
    sk: "Na této pozici musíš být samostatný.",
    ua: "На цій посаді ти маєш бути самостійним.",
    ru: "На этой должности ты должен быть самостоятельным.",
    en: "In this position, you must be independent.",
    uaTokens: ["На", "цій", "посаді", "ти", "маєш", "бути", "самостійним", "."],
    ruTokens: ["На", "этой", "должности", "ты", "должен", "быть", "самостоятельным", "."],
    enTokens: ["In", "this", "position", ",", "you", "must", "be", "independent", "."],
    extraUaTokens: ["несамостійним", "вчора", "швидким"],
    extraRuTokens: ["несамостоятельным", "вчера", "быстрым"],
    extraEnTokens: ["dependent", "yesterday", "fast"],
  },

  [phraseKey("přesný", "a2-32")]: {
    sk: "Při této práci je důležité být přesný.",
    ua: "У цій роботі важливо бути точним.",
    ru: "В этой работе важно быть точным.",
    en: "In this job, it is important to be precise.",
    uaTokens: ["У", "цій", "роботі", "важливо", "бути", "точним", "."],
    ruTokens: ["В", "этой", "работе", "важно", "быть", "точным", "."],
    enTokens: ["In", "this", "job", ",", "it", "is", "important", "to", "be", "precise", "."],
    extraUaTokens: ["повільним", "вчора", "акуратним"],
    extraRuTokens: ["медленным", "вчера", "аккуратным"],
    extraEnTokens: ["slow", "yesterday", "accurate"],
  },

  [phraseKey("spolehlivý", "a2-32")]: {
    sk: "Je to velmi spolehlivý kolega.",
    ua: "Він — дуже надійний колега.",
    ru: "Он — очень надёжный коллега.",
    en: "He is a very reliable colleague.",
    uaTokens: ["Він", "—", "дуже", "надійний", "колега", "."],
    ruTokens: ["Он", "—", "очень", "надёжный", "коллега", "."],
    enTokens: ["He", "is", "a", "very", "reliable", "colleague", "."],
    extraUaTokens: ["ненадійний", "вчора", "сусід"],
    extraRuTokens: ["ненадёжный", "вчера", "сосед"],
    extraEnTokens: ["unreliable", "yesterday", "neighbor"],
  },

  [phraseKey("komunikativní", "a2-32")]: {
    sk: "Na recepci je potřeba být komunikativní.",
    ua: "На ресепшені потрібно бути комунікабельним.",
    ru: "На ресепшене нужно быть коммуникабельным.",
    en: "At reception, you need to be communicative.",
    uaTokens: ["На", "ресепшені", "потрібно", "бути", "комунікабельним", "."],
    ruTokens: ["На", "ресепшене", "нужно", "быть", "коммуникабельным", "."],
    enTokens: ["At", "reception", ",", "you", "need", "to", "be", "communicative", "."],
    extraUaTokens: ["мовчазним", "вчора", "гостем"],
    extraRuTokens: ["молчаливым", "вчера", "гостем"],
    extraEnTokens: ["silent", "yesterday", "guest"],
  },

  [phraseKey("flexibilní", "a2-32")]: {
    sk: "Firma hledá flexibilní lidi.",
    ua: "Фірма шукає гнучких людей.",
    ru: "Фирма ищет гибких людей.",
    en: "The company is looking for flexible people.",
    uaTokens: ["Фірма", "шукає", "гнучких", "людей", "."],
    ruTokens: ["Фирма", "ищет", "гибких", "людей", "."],
    enTokens: ["The", "company", "is", "looking", "for", "flexible", "people", "."],
    extraUaTokens: ["жорстких", "вчора", "правил"],
    extraRuTokens: ["жёстких", "вчера", "правил"],
    extraEnTokens: ["rigid", "yesterday", "rules"],
  },

  [phraseKey("učit se rychle", "a2-32")]: {
    sk: "Musíš se umět rychle učit.",
    ua: "Ти маєш уміти швидко вчитися.",
    ru: "Ты должен уметь быстро учиться.",
    en: "You must be able to learn quickly.",
    uaTokens: ["Ти", "маєш", "уміти", "швидко", "вчитися", "."],
    ruTokens: ["Ты", "должен", "уметь", "быстро", "учиться", "."],
    enTokens: ["You", "must", "be", "able", "to", "learn", "quickly", "."],
    extraUaTokens: ["повільно", "вчора", "працювати"],
    extraRuTokens: ["медленно", "вчера", "работать"],
    extraEnTokens: ["slowly", "yesterday", "work"],
  },

  // =========================
  // LESSON A2-33 — Відпочинок і дозвілля
  // =========================
  [phraseKey("volný čas", "a2-33")]: {
    sk: "Ve volném čase rád čtu.",
    ua: "У вільний час я люблю читати.",
    ru: "В свободное время я люблю читать.",
    en: "In my free time, I like to read.",
    uaTokens: ["У", "вільний", "час", "я", "люблю", "читати", "."],
    ruTokens: ["В", "свободное", "время", "я", "люблю", "читать", "."],
    enTokens: ["In", "my", "free", "time", ",", "I", "like", "to", "read", "."],
    extraUaTokens: ["працювати", "вчора", "увечері"],
    extraRuTokens: ["работать", "вчера", "вечером"],
    extraEnTokens: ["work", "yesterday", "evening"],
  },

  [phraseKey("odpočinout si", "a2-33")]: {
    sk: "O víkendu si chci konečně odpočinout.",
    ua: "На вихідних я хочу нарешті відпочити.",
    ru: "На выходных я хочу наконец отдохнуть.",
    en: "On the weekend, I finally want to rest.",
    uaTokens: ["На", "вихідних", "я", "хочу", "нарешті", "відпочити", "."],
    ruTokens: ["На", "выходных", "я", "хочу", "наконец", "отдохнуть", "."],
    enTokens: ["On", "the", "weekend", ",", "I", "finally", "want", "to", "rest", "."],
    extraUaTokens: ["попрацювати", "вчора", "довго"],
    extraRuTokens: ["поработать", "вчера", "долго"],
    extraEnTokens: ["work", "yesterday", "long"],
  },

  [phraseKey("zábava", "a2-33")]: {
    sk: "Byla to skvělá zábava pro všechny.",
    ua: "Це була чудова розвага для всіх.",
    ru: "Это было отличное развлечение для всех.",
    en: "It was great fun for everyone.",
    uaTokens: ["Це", "була", "чудова", "розвага", "для", "всіх", "."],
    ruTokens: ["Это", "было", "отличное", "развлечение", "для", "всех", "."],
    enTokens: ["It", "was", "great", "fun", "for", "everyone", "."],
    extraUaTokens: ["робота", "вчора", "нудна"],
    extraRuTokens: ["работа", "вчера", "скучная"],
    extraEnTokens: ["work", "yesterday", "boring"],
  },

  [phraseKey("událost", "a2-33")]: {
    sk: "To je důležitá kulturní událost.",
    ua: "Це важлива культурна подія.",
    ru: "Это важное культурное событие.",
    en: "This is an important cultural event.",
    uaTokens: ["Це", "важлива", "культурна", "подія", "."],
    ruTokens: ["Это", "важное", "культурное", "событие", "."],
    enTokens: ["This", "is", "an", "important", "cultural", "event", "."],
    extraUaTokens: ["зустріч", "вчора", "коротка"],
    extraRuTokens: ["встреча", "вчера", "короткая"],
    extraEnTokens: ["meeting", "yesterday", "short"],
  },

  [phraseKey("festival", "a2-33")]: {
    sk: "V létě chceme jet na hudební festival.",
    ua: "Влітку ми хочемо поїхати на музичний фестиваль.",
    ru: "Летом мы хотим поехать на музыкальный фестиваль.",
    en: "In summer, we want to go to a music festival.",
    uaTokens: ["Влітку", "ми", "хочемо", "поїхати", "на", "музичний", "фестиваль", "."],
    ruTokens: ["Летом", "мы", "хотим", "поехать", "на", "музыкальный", "фестиваль", "."],
    enTokens: ["In", "summer", ",", "we", "want", "to", "go", "to", "a", "music", "festival", "."],
    extraUaTokens: ["виставку", "вчора", "зимою"],
    extraRuTokens: ["выставку", "вчера", "зимой"],
    extraEnTokens: ["exhibition", "yesterday", "winter"],
  },

  [phraseKey("vstupenka", "a2-33")]: {
    sk: "Koupil jsem dvě vstupenky online.",
    ua: "Я купив два квитки онлайн.",
    ru: "Я купил два билета онлайн.",
    en: "I bought two tickets online.",
    uaTokens: ["Я", "купив", "два", "квитки", "онлайн", "."],
    ruTokens: ["Я", "купил", "два", "билета", "онлайн", "."],
    enTokens: ["I", "bought", "two", "tickets", "online", "."],
    extraUaTokens: ["три", "вчора", "листівки"],
    extraRuTokens: ["три", "вчера", "открытки"],
    extraEnTokens: ["three", "yesterday", "postcards"],
  },

  [phraseKey("představení", "a2-33")]: {
    sk: "To divadelní představení bylo skvělé.",
    ua: "Та театральна вистава була чудовою.",
    ru: "Этот театральный спектакль был отличным.",
    en: "That theater performance was excellent.",
    uaTokens: ["Та", "театральна", "вистава", "була", "чудовою", "."],
    ruTokens: ["Этот", "театральный", "спектакль", "был", "отличным", "."],
    enTokens: ["That", "theater", "performance", "was", "excellent", "."],
    extraUaTokens: ["фільм", "вчора", "поганою"],
    extraRuTokens: ["фильм", "вчера", "плохим"],
    extraEnTokens: ["movie", "yesterday", "bad"],
  },

  [phraseKey("koncert", "a2-33")]: {
    sk: "Na koncert přišlo hodně lidí.",
    ua: "На концерт прийшло багато людей.",
    ru: "На концерт пришло много людей.",
    en: "A lot of people came to the concert.",
    uaTokens: ["На", "концерт", "прийшло", "багато", "людей", "."],
    ruTokens: ["На", "концерт", "пришло", "много", "людей", "."],
    enTokens: ["A", "lot", "of", "people", "came", "to", "the", "concert", "."],
    extraUaTokens: ["мало", "вчора", "акторів"],
    extraRuTokens: ["мало", "вчера", "актёров"],
    extraEnTokens: ["few", "yesterday", "actors"],
  },

  [phraseKey("výstava", "a2-33")]: {
    sk: "V muzeu je nová výstava.",
    ua: "У музеї є нова виставка.",
    ru: "В музее новая выставка.",
    en: "There is a new exhibition in the museum.",
    uaTokens: ["У", "музеї", "є", "нова", "виставка", "."],
    ruTokens: ["В", "музее", "новая", "выставка", "."],
    enTokens: ["There", "is", "a", "new", "exhibition", "in", "the", "museum", "."],
    extraUaTokens: ["старий", "вчора", "концерт"],
    extraRuTokens: ["старый", "вчера", "концерт"],
    extraEnTokens: ["old", "yesterday", "concert"],
  },

  [phraseKey("rezervovat místo", "a2-33")]: {
    sk: "Musíme si rezervovat místo předem.",
    ua: "Нам треба забронювати місце заздалегідь.",
    ru: "Нам нужно забронировать место заранее.",
    en: "We need to reserve a place in advance.",
    uaTokens: ["Нам", "треба", "забронювати", "місце", "заздалегідь", "."],
    ruTokens: ["Нам", "нужно", "забронировать", "место", "заранее", "."],
    enTokens: ["We", "need", "to", "reserve", "a", "place", "in", "advance", "."],
    extraUaTokens: ["скасувати", "вчора", "зустріч"],
    extraRuTokens: ["отменить", "вчера", "встречу"],
    extraEnTokens: ["cancel", "yesterday", "meeting"],
  },

  // =========================
  // LESSON A2-34 — Сервіс (майстерня, ремонт)
  // =========================

  [phraseKey("servis", "a2-34")]: {
    sk: "Auto je teď v servisu.",
    ua: "Авто зараз у сервісі.",
    ru: "Машина сейчас в сервисе.",
    en: "The car is in the service now.",
    uaTokens: ["Авто", "зараз", "у", "сервісі", "."],
    ruTokens: ["Машина", "сейчас", "в", "сервисе", "."],
    enTokens: ["The", "car", "is", "in", "the", "service", "now", "."],
    extraUaTokens: ["дорозі", "вчора", "було"],
    extraRuTokens: ["дороге", "вчера", "была"],
    extraEnTokens: ["on_the_road", "yesterday", "was"],
  },

  [phraseKey("objednat termín", "a2-34")]: {
    sk: "Potřebuji objednat termín na příští týden.",
    ua: "Мені потрібно домовитися про час на наступний тиждень.",
    ru: "Мне нужно договориться о времени на следующую неделю.",
    en: "I need to book an appointment for next week.",
    uaTokens: ["Мені", "потрібно", "домовитися", "про", "час", "на", "наступний", "тиждень", "."],
    ruTokens: ["Мне", "нужно", "договориться", "о", "времени", "на", "следующую", "неделю", "."],
    enTokens: ["I", "need", "to", "book", "an", "appointment", "for", "next", "week", "."],
    extraUaTokens: ["вчора", "сьогодні", "скасувати"],
    extraRuTokens: ["вчера", "сегодня", "отменить"],
    extraEnTokens: ["yesterday", "today", "cancel"],
  },

  [phraseKey("diagnostika", "a2-34")]: {
    sk: "Nejdřív udělají diagnostiku auta.",
    ua: "Спочатку вони зроблять діагностику авто.",
    ru: "Сначала они сделают диагностику машины.",
    en: "First, they will do a car diagnostic.",
    uaTokens: ["Спочатку", "вони", "зроблять", "діагностику", "авто", "."],
    ruTokens: ["Сначала", "они", "сделают", "диагностику", "машины", "."],
    enTokens: ["First", ",", "they", "will", "do", "a", "car", "diagnostic", "."],
    extraUaTokens: ["ремонт", "вчора", "телефону"],
    extraRuTokens: ["ремонт", "вчера", "телефона"],
    extraEnTokens: ["repair", "yesterday", "phone"],
  },

  [phraseKey("porucha", "a2-34")]: {
    sk: "Ta porucha se objevila znovu.",
    ua: "Ця несправність з’явилася знову.",
    ru: "Эта неисправность появилась снова.",
    en: "This malfunction appeared again.",
    uaTokens: ["Ця", "несправність", "з’явилася", "знову", "."],
    ruTokens: ["Эта", "неисправность", "появилась", "снова", "."],
    enTokens: ["This", "malfunction", "appeared", "again", "."],
    extraUaTokens: ["помилка", "вчора", "зникла"],
    extraRuTokens: ["ошибка", "вчера", "исчезла"],
    extraEnTokens: ["error", "yesterday", "disappeared"],
  },

  [phraseKey("oprava", "a2-34")]: {
    sk: "Oprava bude trvat dva dny.",
    ua: "Ремонт триватиме два дні.",
    ru: "Ремонт будет длиться два дня.",
    en: "The repair will take two days.",
    uaTokens: ["Ремонт", "триватиме", "два", "дні", "."],
    ruTokens: ["Ремонт", "будет", "длиться", "два", "дня", "."],
    enTokens: ["The", "repair", "will", "take", "two", "days", "."],
    extraUaTokens: ["три", "вчора", "хвилини"],
    extraRuTokens: ["три", "вчера", "минуты"],
    extraEnTokens: ["three", "yesterday", "minutes"],
  },

  [phraseKey("náhradní díly", "a2-34")]: {
    sk: "Na některé náhradní díly se čeká dlouho.",
    ua: "На деякі запасні частини довго чекають.",
    ru: "Некоторые запасные части приходится долго ждать.",
    en: "Some spare parts take a long time to arrive.",
    uaTokens: ["На", "деякі", "запасні", "частини", "довго", "чекають", "."],
    ruTokens: ["Некоторые", "запасные", "части", "приходится", "долго", "ждать", "."],
    enTokens: ["Some", "spare", "parts", "take", "a", "long", "time", "to", "arrive", "."],
    extraUaTokens: ["інструменти", "вчора", "швидко"],
    extraRuTokens: ["инструменты", "вчера", "быстро"],
    extraEnTokens: ["tools", "yesterday", "quickly"],
  },

  [phraseKey("ceník", "a2-34")]: {
    sk: "Ceník mají vyvěšený u vstupu.",
    ua: "Прейскурант у них вивішений біля входу.",
    ru: "Прайс-лист у них вывешен у входа.",
    en: "They have the price list posted by the entrance.",
    uaTokens: ["Прейскурант", "у", "них", "вивішений", "біля", "входу", "."],
    ruTokens: ["Прайс-лист", "у", "них", "вывешен", "у", "входа", "."],
    enTokens: ["They", "have", "the", "price", "list", "posted", "by", "the", "entrance", "."],
    extraUaTokens: ["вчора", "схований", "всередині"],
    extraRuTokens: ["вчера", "спрятан", "внутри"],
    extraEnTokens: ["yesterday", "hidden", "inside"],
  },

  [phraseKey("odhad ceny", "a2-34")]: {
    sk: "Nejdřív mi pošlou odhad ceny.",
    ua: "Спочатку вони надішлють мені оцінку вартості.",
    ru: "Сначала они пришлют мне оценку стоимости.",
    en: "First, they will send me a price estimate.",
    uaTokens: ["Спочатку", "вони", "надішлють", "мені", "оцінку", "вартості", "."],
    ruTokens: ["Сначала", "они", "пришлют", "мне", "оценку", "стоимости", "."],
    enTokens: ["First", ",", "they", "will", "send", "me", "a", "price", "estimate", "."],
    extraUaTokens: ["рахунок", "вчора", "відразу"],
    extraRuTokens: ["счёт", "вчера", "сразу"],
    extraEnTokens: ["invoice", "yesterday", "immediately"],
  },

  [phraseKey("schválit", "a2-34")]: {
    sk: "Musíte nejdřív schválit opravu.",
    ua: "Ви спочатку маєте схвалити ремонт.",
    ru: "Вы сначала должны одобрить ремонт.",
    en: "You must approve the repair first.",
    uaTokens: ["Ви", "спочатку", "маєте", "схвалити", "ремонт", "."],
    ruTokens: ["Вы", "сначала", "должны", "одобрить", "ремонт", "."],
    enTokens: ["You", "must", "approve", "the", "repair", "first", "."],
    extraUaTokens: ["скасувати", "вчора", "замовлення"],
    extraRuTokens: ["отменить", "вчера", "заказ"],
    extraEnTokens: ["cancel", "yesterday", "order"],
  },

  [phraseKey("záruka", "a2-34")]: {
    sk: "Na tuto opravu je záruka šest měsíců.",
    ua: "На цей ремонт є гарантія на шість місяців.",
    ru: "На этот ремонт даётся гарантия на шесть месяцев.",
    en: "This repair has a six-month warranty.",
    uaTokens: ["На", "цей", "ремонт", "є", "гарантія", "на", "шість", "місяців", "."],
    ruTokens: ["На", "этот", "ремонт", "даётся", "гарантия", "на", "шесть", "месяцев", "."],
    enTokens: ["This", "repair", "has", "a", "six-month", "warranty", "."],
    extraUaTokens: ["три", "вчора", "роки"],
    extraRuTokens: ["три", "вчера", "года"],
    extraEnTokens: ["three", "yesterday", "years"],
  },

  // =========================
  // LESSON A2-35 — В магазині (складніші ситуації)
  // =========================
  [phraseKey("dostupnost", "a2-35")]: {
    sk: "Nejdřív musím ověřit dostupnost zboží.",
    ua: "Спочатку мені треба перевірити наявність товару.",
    ru: "Сначала мне нужно проверить наличие товара.",
    en: "First, I need to check the availability of the product.",
    uaTokens: ["Спочатку", "мені", "треба", "перевірити", "наявність", "товару", "."],
    ruTokens: ["Сначала", "мне", "нужно", "проверить", "наличие", "товара", "."],
    enTokens: ["First", ",", "I", "need", "to", "check", "the", "availability", "of", "the", "product", "."],
    extraUaTokens: ["ціну", "вчора", "посилки"],
    extraRuTokens: ["цену", "вчера", "посылки"],
    extraEnTokens: ["price", "yesterday", "parcel"],
  },

  [phraseKey("skladem", "a2-35")]: {
    sk: "Tento model už bohužel není skladem.",
    ua: "Ця модель, на жаль, вже не в наявності.",
    ru: "Этой модели, к сожалению, уже нет в наличии.",
    en: "Unfortunately, this model is no longer in stock.",
    uaTokens: ["Ця", "модель", ",", "на", "жаль", ",", "вже", "не", "в", "наявності", "."],
    ruTokens: ["Этой", "модели", ",", "к", "сожалению", ",", "уже", "нет", "в", "наличии", "."],
    enTokens: ["Unfortunately", ",", "this", "model", "is", "no", "longer", "in", "stock", "."],
    extraUaTokens: ["є", "вчора", "магазині"],
    extraRuTokens: ["есть", "вчера", "магазине"],
    extraEnTokens: ["available", "yesterday", "shop"],
  },

  [phraseKey("vyprodáno", "a2-35")]: {
    sk: "Včera to ještě měli, dnes je vyprodáno.",
    ua: "Учора це ще було, а сьогодні вже розпродано.",
    ru: "Вчера это ещё было, а сегодня уже распродано.",
    en: "Yesterday they still had it, but today it is sold out.",
    uaTokens: ["Учора", "це", "ще", "було", ",", "а", "сьогодні", "вже", "розпродано", "."],
    ruTokens: ["Вчера", "это", "ещё", "было", ",", "а", "сегодня", "уже", "распродано", "."],
    enTokens: ["Yesterday", "they", "still", "had", "it", ",", "but", "today", "it", "is", "sold", "out", "."],
    extraUaTokens: ["дешево", "вчора", "залишилось"],
    extraRuTokens: ["дёшево", "вчера", "осталось"],
    extraEnTokens: ["cheaply", "yesterday", "remained"],
  },

  [phraseKey("objednat", "a2-35")]: {
    sk: "Můžeme to pro vás objednat.",
    ua: "Ми можемо це для вас замовити.",
    ru: "Мы можем это для вас заказать.",
    en: "We can order it for you.",
    uaTokens: ["Ми", "можемо", "це", "для", "вас", "замовити", "."],
    ruTokens: ["Мы", "можем", "это", "для", "вас", "заказать", "."],
    enTokens: ["We", "can", "order", "it", "for", "you", "."],
    extraUaTokens: ["скасувати", "вчора", "знайти"],
    extraRuTokens: ["отменить", "вчера", "найти"],
    extraEnTokens: ["cancel", "yesterday", "find"],
  },

  [phraseKey("dodání", "a2-35")]: {
    sk: "Dodání proběhne příští týden.",
    ua: "Поставка відбудеться наступного тижня.",
    ru: "Поставка произойдёт на следующей неделе.",
    en: "Delivery will take place next week.",
    uaTokens: ["Поставка", "відбудеться", "наступного", "тижня", "."],
    ruTokens: ["Поставка", "произойдёт", "на", "следующей", "неделе", "."],
    enTokens: ["Delivery", "will", "take", "place", "next", "week", "."],
    extraUaTokens: ["сьогодні", "вчора", "оплата"],
    extraRuTokens: ["сегодня", "вчера", "оплата"],
    extraEnTokens: ["today", "yesterday", "payment"],
  },

  [phraseKey("dodací lhůta", "a2-35")]: {
    sk: "Dodací lhůta je deset pracovních dnů.",
    ua: "Термін доставки — десять робочих днів.",
    ru: "Срок доставки — десять рабочих дней.",
    en: "The delivery time is ten working days.",
    uaTokens: ["Термін", "доставки", "—", "десять", "робочих", "днів", "."],
    ruTokens: ["Срок", "доставки", "—", "десять", "рабочих", "дней", "."],
    enTokens: ["The", "delivery", "time", "is", "ten", "working", "days", "."],
    extraUaTokens: ["п’ять", "вчора", "годин"],
    extraRuTokens: ["пять", "вчера", "часов"],
    extraEnTokens: ["five", "yesterday", "hours"],
  },

  [phraseKey("poškozené zboží", "a2-35")]: {
    sk: "Dostal jsem poškozené zboží.",
    ua: "Я отримав пошкоджений товар.",
    ru: "Я получил повреждённый товар.",
    en: "I received damaged goods.",
    uaTokens: ["Я", "отримав", "пошкоджений", "товар", "."],
    ruTokens: ["Я", "получил", "повреждённый", "товар", "."],
    enTokens: ["I", "received", "damaged", "goods", "."],
    extraUaTokens: ["новий", "вчора", "чек"],
    extraRuTokens: ["новый", "вчера", "чек"],
    extraEnTokens: ["new", "yesterday", "receipt"],
  },

  [phraseKey("vyměnit zboží", "a2-35")]: {
    sk: "Chci vyměnit zboží za jiné.",
    ua: "Я хочу обміняти товар на інший.",
    ru: "Я хочу обменять товар на другой.",
    en: "I want to exchange the goods for another one.",
    uaTokens: ["Я", "хочу", "обміняти", "товар", "на", "інший", "."],
    ruTokens: ["Я", "хочу", "обменять", "товар", "на", "другой", "."],
    enTokens: ["I", "want", "to", "exchange", "the", "goods", "for", "another", "one", "."],
    extraUaTokens: ["повернути", "вчора", "гроші"],
    extraRuTokens: ["вернуть", "вчера", "деньги"],
    extraEnTokens: ["return", "yesterday", "money"],
  },

  [phraseKey("vrátit peníze", "a2-35")]: {
    sk: "Můžete mi vrátit peníze na účet?",
    ua: "Можете повернути мені гроші на рахунок?",
    ru: "Можете вернуть мне деньги на счёт?",
    en: "Can you return the money to my account?",
    uaTokens: ["Можете", "повернути", "мені", "гроші", "на", "рахунок", "?"],
    ruTokens: ["Можете", "вернуть", "мне", "деньги", "на", "счёт", "?"],
    enTokens: ["Can", "you", "return", "the", "money", "to", "my", "account", "?"],
    extraUaTokens: ["картку", "вчора", "обміняти"],
    extraRuTokens: ["карту", "вчера", "обменять"],
    extraEnTokens: ["card", "yesterday", "exchange"],
  },

  [phraseKey("reklamační oddělení", "a2-35")]: {
    sk: "Musíte kontaktovat reklamační oddělení.",
    ua: "Вам потрібно зв’язатися з відділом рекламацій.",
    ru: "Вам нужно связаться с отделом рекламаций.",
    en: "You need to contact the complaints department.",
    uaTokens: ["Вам", "потрібно", "зв’язатися", "з", "відділом", "рекламацій", "."],
    ruTokens: ["Вам", "нужно", "связаться", "с", "отделом", "рекламаций", "."],
    enTokens: ["You", "need", "to", "contact", "the", "complaints", "department", "."],
    extraUaTokens: ["продажу", "вчора", "магазином"],
    extraRuTokens: ["продаж", "вчера", "магазином"],
    extraEnTokens: ["sales", "yesterday", "store"],
  },
};