import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_A2_BUILD_UA_SENTENCES_9: BuildUaSentenceDict = {
  // =========================
  // LESSON A2-41 — Плани та цілі
  // =========================
  [phraseKey("ambice", "a2-41")]: {
    sk: "Má velké ambice do budoucna.",
    ua: "Він має великі амбіції на майбутнє.",
    ru: "У него большие амбиции на будущее.",
    en: "He has big ambitions for the future.",
    uaTokens: ["Він", "має", "великі", "амбіції", "на", "майбутнє", "."],
    ruTokens: ["У", "него", "большие", "амбиции", "на", "будущее", "."],
    enTokens: ["He", "has", "big", "ambitions", "for", "the", "future", "."],
    extraUaTokens: ["малі", "вчора", "плани"],
    extraRuTokens: ["маленькие", "вчера", "планы"],
    extraEnTokens: ["small", "yesterday", "plans"],
  },

  [phraseKey("strategie", "a2-41")]: {
    sk: "Potřebujeme lepší strategii.",
    ua: "Нам потрібна краща стратегія.",
    ru: "Нам нужна лучшая стратегия.",
    en: "We need a better strategy.",
    uaTokens: ["Нам", "потрібна", "краща", "стратегія", "."],
    ruTokens: ["Нам", "нужна", "лучшая", "стратегия", "."],
    enTokens: ["We", "need", "a", "better", "strategy", "."],
    extraUaTokens: ["тактика", "вчора", "гірша"],
    extraRuTokens: ["тактика", "вчера", "хуже"],
    extraEnTokens: ["tactics", "yesterday", "worse"],
  },

  [phraseKey("odhodlání", "a2-41")]: {
    sk: "K úspěchu je potřeba odhodlání.",
    ua: "Для успіху потрібна рішучість.",
    ru: "Для успеха нужна решимость.",
    en: "Determination is needed for success.",
    uaTokens: ["Для", "успіху", "потрібна", "рішучість", "."],
    ruTokens: ["Для", "успеха", "нужна", "решимость", "."],
    enTokens: ["Determination", "is", "needed", "for", "success", "."],
    extraUaTokens: ["страх", "вчора", "роботи"],
    extraRuTokens: ["страх", "вчера", "работы"],
    extraEnTokens: ["fear", "yesterday", "work"],
  },

  [phraseKey("zvážit", "a2-41")]: {
    sk: "Musíme zvážit všechny možnosti.",
    ua: "Нам треба зважити всі варіанти.",
    ru: "Нам нужно рассмотреть все варианты.",
    en: "We need to consider all the options.",
    uaTokens: ["Нам", "треба", "зважити", "всі", "варіанти", "."],
    ruTokens: ["Нам", "нужно", "рассмотреть", "все", "варианты", "."],
    enTokens: ["We", "need", "to", "consider", "all", "the", "options", "."],
    extraUaTokens: ["дві", "вчора", "причини"],
    extraRuTokens: ["два", "вчера", "причины"],
    extraEnTokens: ["two", "yesterday", "reasons"],
  },

  [phraseKey("přizpůsobit se", "a2-41")]: {
    sk: "Člověk se musí přizpůsobit změnám.",
    ua: "Людина повинна пристосуватися до змін.",
    ru: "Человек должен приспособиться к изменениям.",
    en: "A person must adapt to changes.",
    uaTokens: ["Людина", "повинна", "пристосуватися", "до", "змін", "."],
    ruTokens: ["Человек", "должен", "приспособиться", "к", "изменениям", "."],
    enTokens: ["A", "person", "must", "adapt", "to", "changes", "."],
    extraUaTokens: ["звичок", "вчора", "опиратися"],
    extraRuTokens: ["привычкам", "вчера", "сопротивляться"],
    extraEnTokens: ["habits", "yesterday", "resist"],
  },

  [phraseKey("priorita", "a2-41")]: {
    sk: "Mou prioritou je teď práce.",
    ua: "Мій пріоритет зараз — робота.",
    ru: "Мой приоритет сейчас — работа.",
    en: "My priority right now is work.",
    uaTokens: ["Мій", "пріоритет", "зараз", "—", "робота", "."],
    ruTokens: ["Мой", "приоритет", "сейчас", "—", "работа", "."],
    enTokens: ["My", "priority", "right", "now", "is", "work", "."],
    extraUaTokens: ["відпочинок", "вчора", "був"],
    extraRuTokens: ["отдых", "вчера", "был"],
    extraEnTokens: ["rest", "yesterday", "was"],
  },

  [phraseKey("dosáhnout", "a2-41")]: {
    sk: "Chci letos dosáhnout svého cíle.",
    ua: "Я хочу цього року досягти своєї цілі.",
    ru: "Я хочу в этом году достичь своей цели.",
    en: "I want to achieve my goal this year.",
    uaTokens: ["Я", "хочу", "цього", "року", "досягти", "своєї", "цілі", "."],
    ruTokens: ["Я", "хочу", "в", "этом", "году", "достичь", "своей", "цели", "."],
    enTokens: ["I", "want", "to", "achieve", "my", "goal", "this", "year", "."],
    extraUaTokens: ["плану", "вчора", "забути"],
    extraRuTokens: ["плана", "вчера", "забыть"],
    extraEnTokens: ["plan", "yesterday", "forget"],
  },

  [phraseKey("pokrok", "a2-41")]: {
    sk: "Už vidím velký pokrok.",
    ua: "Я вже бачу великий прогрес.",
    ru: "Я уже вижу большой прогресс.",
    en: "I can already see big progress.",
    uaTokens: ["Я", "вже", "бачу", "великий", "прогрес", "."],
    ruTokens: ["Я", "уже", "вижу", "большой", "прогресс", "."],
    enTokens: ["I", "can", "already", "see", "big", "progress", "."],
    extraUaTokens: ["регрес", "вчора", "малий"],
    extraRuTokens: ["регресс", "вчера", "маленький"],
    extraEnTokens: ["regress", "yesterday", "small"],
  },

  [phraseKey("vytrvat", "a2-41")]: {
    sk: "Je důležité vytrvat až do konce.",
    ua: "Важливо витримати до кінця.",
    ru: "Важно выдержать до конца.",
    en: "It is important to endure until the end.",
    uaTokens: ["Важливо", "витримати", "до", "кінця", "."],
    ruTokens: ["Важно", "выдержать", "до", "конца", "."],
    enTokens: ["It", "is", "important", "to", "endure", "until", "the", "end", "."],
    extraUaTokens: ["здатися", "вчора", "одразу"],
    extraRuTokens: ["сдаться", "вчера", "сразу"],
    extraEnTokens: ["give up", "yesterday", "immediately"],
  },

  [phraseKey("pokračovat", "a2-41")]: {
    sk: "Chci v tom pokračovat.",
    ua: "Я хочу продовжувати це.",
    ru: "Я хочу продолжать это.",
    en: "I want to continue this.",
    uaTokens: ["Я", "хочу", "продовжувати", "це", "."],
    ruTokens: ["Я", "хочу", "продолжать", "это", "."],
    enTokens: ["I", "want", "to", "continue", "this", "."],
    extraUaTokens: ["зупинити", "вчора", "роботу"],
    extraRuTokens: ["остановить", "вчера", "работу"],
    extraEnTokens: ["stop", "yesterday", "work"],
  },

  // =========================
  // LESSON A2-42 — У місті (орієнтація)
  // =========================
  [phraseKey("směr", "a2-42")]: {
    sk: "Jdeme správným směrem.",
    ua: "Ми йдемо в правильному напрямку.",
    ru: "Мы идём в правильном направлении.",
    en: "We are going in the right direction.",
    uaTokens: ["Ми", "йдемо", "в", "правильному", "напрямку", "."],
    ruTokens: ["Мы", "идём", "в", "правильном", "направлении", "."],
    enTokens: ["We", "are", "going", "in", "the", "right", "direction", "."],
    extraUaTokens: ["неправильному", "вчора", "місту"],
    extraRuTokens: ["неправильном", "вчера", "городу"],
    extraEnTokens: ["wrong", "yesterday", "city"],
  },

  [phraseKey("odbočit", "a2-42")]: {
    sk: "Na další ulici musíte odbočit vlevo.",
    ua: "На наступній вулиці вам треба повернути ліворуч.",
    ru: "На следующей улице вам нужно повернуть налево.",
    en: "At the next street, you need to turn left.",
    uaTokens: ["На", "наступній", "вулиці", "вам", "треба", "повернути", "ліворуч", "."],
    ruTokens: ["На", "следующей", "улице", "вам", "нужно", "повернуть", "налево", "."],
    enTokens: ["At", "the", "next", "street", ",", "you", "need", "to", "turn", "left", "."],
    extraUaTokens: ["праворуч", "вчора", "швидко"],
    extraRuTokens: ["направо", "вчера", "быстро"],
    extraEnTokens: ["right", "yesterday", "quickly"],
  },

  [phraseKey("kruhový objezd", "a2-42")]: {
    sk: "Na kruhovém objezdu jeďte druhým výjezdem.",
    ua: "На кільці їдьте другим виїздом.",
    ru: "На кольце езжайте по второму съезду.",
    en: "At the roundabout, take the second exit.",
    uaTokens: ["На", "кільці", "їдьте", "другим", "виїздом", "."],
    ruTokens: ["На", "кольце", "езжайте", "по", "второму", "съезду", "."],
    enTokens: ["At", "the", "roundabout", ",", "take", "the", "second", "exit", "."],
    extraUaTokens: ["першим", "вчора", "поворотом"],
    extraRuTokens: ["первому", "вчера", "повороту"],
    extraEnTokens: ["first", "yesterday", "turn"],
  },

  [phraseKey("přechod pro chodce", "a2-42")]: {
    sk: "Počkejte u přechodu pro chodce.",
    ua: "Почекайте біля пішохідного переходу.",
    ru: "Подождите у пешеходного перехода.",
    en: "Wait by the pedestrian crossing.",
    uaTokens: ["Почекайте", "біля", "пішохідного", "переходу", "."],
    ruTokens: ["Подождите", "у", "пешеходного", "перехода", "."],
    enTokens: ["Wait", "by", "the", "pedestrian", "crossing", "."],
    extraUaTokens: ["світлофора", "вчора", "біжіть"],
    extraRuTokens: ["светофора", "вчера", "бегите"],
    extraEnTokens: ["traffic light", "yesterday", "run"],
  },

  [phraseKey("zákaz", "a2-42")]: {
    sk: "Tady platí zákaz vjezdu.",
    ua: "Тут діє заборона в’їзду.",
    ru: "Здесь действует запрет на въезд.",
    en: "Entry is prohibited here.",
    uaTokens: ["Тут", "діє", "заборона", "в’їзду", "."],
    ruTokens: ["Здесь", "действует", "запрет", "на", "въезд", "."],
    enTokens: ["Entry", "is", "prohibited", "here", "."],
    extraUaTokens: ["паркування", "вчора", "дозвіл"],
    extraRuTokens: ["парковки", "вчера", "разрешение"],
    extraEnTokens: ["parking", "yesterday", "permission"],
  },

  [phraseKey("povoleno", "a2-42")]: {
    sk: "Parkování je tu povoleno jen večer.",
    ua: "Паркування тут дозволено лише ввечері.",
    ru: "Парковка здесь разрешена только вечером.",
    en: "Parking is allowed here only in the evening.",
    uaTokens: ["Паркування", "тут", "дозволено", "лише", "ввечері", "."],
    ruTokens: ["Парковка", "здесь", "разрешена", "только", "вечером", "."],
    enTokens: ["Parking", "is", "allowed", "here", "only", "in", "the", "evening", "."],
    extraUaTokens: ["заборонено", "вчора", "вранці"],
    extraRuTokens: ["запрещена", "вчера", "утром"],
    extraEnTokens: ["forbidden", "yesterday", "morning"],
  },

  [phraseKey("objížďka", "a2-42")]: {
    sk: "Kvůli opravě silnice vede objížďka jinudy.",
    ua: "Через ремонт дороги об’їзд проходить іншою дорогою.",
    ru: "Из-за ремонта дороги объезд проходит по другому пути.",
    en: "Because of the road repair, the detour goes another way.",
    uaTokens: ["Через", "ремонт", "дороги", "об’їзд", "проходить", "іншою", "дорогою", "."],
    ruTokens: ["Из-за", "ремонта", "дороги", "объезд", "проходит", "по", "другому", "пути", "."],
    enTokens: ["Because", "of", "the", "road", "repair", ",", "the", "detour", "goes", "another", "way", "."],
    extraUaTokens: ["коротшою", "вчора", "вулицею"],
    extraRuTokens: ["короткому", "вчера", "маршруту"],
    extraEnTokens: ["shorter", "yesterday", "street"],
  },

  [phraseKey("zabloudit", "a2-42")]: {
    sk: "Ve starém městě jsem trochu zabloudil.",
    ua: "У старому місті я трохи заблукав.",
    ru: "В старом городе я немного заблудился.",
    en: "I got a little lost in the old town.",
    uaTokens: ["У", "старому", "місті", "я", "трохи", "заблукав", "."],
    ruTokens: ["В", "старом", "городе", "я", "немного", "заблудился", "."],
    enTokens: ["I", "got", "a", "little", "lost", "in", "the", "old", "town", "."],
    extraUaTokens: ["знайшовся", "вчора", "швидко"],
    extraRuTokens: ["нашёлся", "вчера", "быстро"],
    extraEnTokens: ["found", "yesterday", "quickly"],
  },

  [phraseKey("následovat", "a2-42")]: {
    sk: "Stačí následovat ty značky.",
    ua: "Достатньо слідувати тим знакам.",
    ru: "Достаточно следовать тем знакам.",
    en: "It is enough to follow those signs.",
    uaTokens: ["Достатньо", "слідувати", "тим", "знакам", "."],
    ruTokens: ["Достаточно", "следовать", "тем", "знакам", "."],
    enTokens: ["It", "is", "enough", "to", "follow", "those", "signs", "."],
    extraUaTokens: ["ігнорувати", "вчора", "людей"],
    extraRuTokens: ["игнорировать", "вчера", "людей"],
    extraEnTokens: ["ignore", "yesterday", "people"],
  },

  [phraseKey("orientovat se", "a2-42")]: {
    sk: "V tomhle městě se ještě neumím orientovat.",
    ua: "У цьому місті я ще не вмію орієнтуватися.",
    ru: "В этом городе я ещё не умею ориентироваться.",
    en: "I still do not know how to find my way around this city.",
    uaTokens: ["У", "цьому", "місті", "я", "ще", "не", "вмію", "орієнтуватися", "."],
    ruTokens: ["В", "этом", "городе", "я", "ещё", "не", "умею", "ориентироваться", "."],
    enTokens: ["I", "still", "do", "not", "know", "how", "to", "find", "my", "way", "around", "this", "city", "."],
    extraUaTokens: ["селі", "вчора", "добре"],
    extraRuTokens: ["деревне", "вчера", "хорошо"],
    extraEnTokens: ["village", "yesterday", "well"],
  },

  // =========================
  // LESSON A2-43 — Звички та рутина
  // =========================
  [phraseKey("zvyk", "a2-43")]: {
    sk: "Je to jen starý zvyk.",
    ua: "Це лише стара звичка.",
    ru: "Это всего лишь старая привычка.",
    en: "It is just an old habit.",
    uaTokens: ["Це", "лише", "стара", "звичка", "."],
    ruTokens: ["Это", "всего", "лишь", "старая", "привычка", "."],
    enTokens: ["It", "is", "just", "an", "old", "habit", "."],
    extraUaTokens: ["ідея", "вчора", "нова"],
    extraRuTokens: ["идея", "вчера", "новая"],
    extraEnTokens: ["idea", "yesterday", "new"],
  },

  [phraseKey("rutina", "a2-43")]: {
    sk: "Ranní rutina mi pomáhá začít den.",
    ua: "Ранкова рутина допомагає мені почати день.",
    ru: "Утренняя рутина помогает мне начать день.",
    en: "My morning routine helps me start the day.",
    uaTokens: ["Ранкова", "рутина", "допомагає", "мені", "почати", "день", "."],
    ruTokens: ["Утренняя", "рутина", "помогает", "мне", "начать", "день", "."],
    enTokens: ["My", "morning", "routine", "helps", "me", "start", "the", "day", "."],
    extraUaTokens: ["вечірня", "вчора", "закінчити"],
    extraRuTokens: ["вечерняя", "вчера", "закончить"],
    extraEnTokens: ["evening", "yesterday", "finish"],
  },

  [phraseKey("zvyknout si", "a2-43")]: {
    sk: "Na novou práci jsem si rychle zvykl.",
    ua: "До нової роботи я швидко звик.",
    ru: "К новой работе я быстро привык.",
    en: "I got used to the new job quickly.",
    uaTokens: ["До", "нової", "роботи", "я", "швидко", "звик", "."],
    ruTokens: ["К", "новой", "работе", "я", "быстро", "привык", "."],
    enTokens: ["I", "got", "used", "to", "the", "new", "job", "quickly", "."],
    extraUaTokens: ["відвик", "вчора", "школи"],
    extraRuTokens: ["отвык", "вчера", "школе"],
    extraEnTokens: ["unlearned", "yesterday", "school"],
  },

  [phraseKey("odvyknout si", "a2-43")]: {
    sk: "Není snadné si odvyknout od cukru.",
    ua: "Нелегко відвикнути від цукру.",
    ru: "Нелегко отвыкнуть от сахара.",
    en: "It is not easy to give up sugar.",
    uaTokens: ["Нелегко", "відвикнути", "від", "цукру", "."],
    ruTokens: ["Нелегко", "отвыкнуть", "от", "сахара", "."],
    enTokens: ["It", "is", "not", "easy", "to", "give", "up", "sugar", "."],
    extraUaTokens: ["солі", "вчора", "звикнути"],
    extraRuTokens: ["соли", "вчера", "привыкнуть"],
    extraEnTokens: ["salt", "yesterday", "get used"],
  },

  [phraseKey("pravidelně", "a2-43")]: {
    sk: "Snažím se pravidelně sportovat.",
    ua: "Я намагаюся регулярно займатися спортом.",
    ru: "Я стараюсь регулярно заниматься спортом.",
    en: "I try to do sports regularly.",
    uaTokens: ["Я", "намагаюся", "регулярно", "займатися", "спортом", "."],
    ruTokens: ["Я", "стараюсь", "регулярно", "заниматься", "спортом", "."],
    enTokens: ["I", "try", "to", "do", "sports", "regularly", "."],
    extraUaTokens: ["рідко", "вчора", "відпочивати"],
    extraRuTokens: ["редко", "вчера", "отдыхать"],
    extraEnTokens: ["rarely", "yesterday", "rest"],
  },

  [phraseKey("výjimka", "a2-43")]: {
    sk: "Dnešek je jen malá výjimka.",
    ua: "Сьогодні лише невеликий виняток.",
    ru: "Сегодня лишь небольшое исключение.",
    en: "Today is just a small exception.",
    uaTokens: ["Сьогодні", "лише", "невеликий", "виняток", "."],
    ruTokens: ["Сегодня", "лишь", "небольшое", "исключение", "."],
    enTokens: ["Today", "is", "just", "a", "small", "exception", "."],
    extraUaTokens: ["правило", "вчора", "великий"],
    extraRuTokens: ["правило", "вчера", "большое"],
    extraEnTokens: ["rule", "yesterday", "big"],
  },

  [phraseKey("zlepšit", "a2-43")]: {
    sk: "Chci zlepšit svůj denní režim.",
    ua: "Я хочу покращити свій щоденний режим.",
    ru: "Я хочу улучшить свой ежедневный режим.",
    en: "I want to improve my daily routine.",
    uaTokens: ["Я", "хочу", "покращити", "свій", "щоденний", "режим", "."],
    ruTokens: ["Я", "хочу", "улучшить", "свой", "ежедневный", "режим", "."],
    enTokens: ["I", "want", "to", "improve", "my", "daily", "routine", "."],
    extraUaTokens: ["погіршити", "вчора", "план"],
    extraRuTokens: ["ухудшить", "вчера", "план"],
    extraEnTokens: ["worsen", "yesterday", "plan"],
  },

  [phraseKey("zhoršit", "a2-43")]: {
    sk: "Stres může všechno zhoršit.",
    ua: "Стрес може все погіршити.",
    ru: "Стресс может всё ухудшить.",
    en: "Stress can make everything worse.",
    uaTokens: ["Стрес", "може", "все", "погіршити", "."],
    ruTokens: ["Стресс", "может", "всё", "ухудшить", "."],
    enTokens: ["Stress", "can", "make", "everything", "worse", "."],
    extraUaTokens: ["покращити", "вчора", "радість"],
    extraRuTokens: ["улучшить", "вчера", "радость"],
    extraEnTokens: ["improve", "yesterday", "joy"],
  },

  [phraseKey("zdravý styl", "a2-43")]: {
    sk: "Snažím se žít zdravým stylem.",
    ua: "Я намагаюся жити здоровим стилем життя.",
    ru: "Я стараюсь вести здоровый образ жизни.",
    en: "I try to live a healthy lifestyle.",
    uaTokens: ["Я", "намагаюся", "жити", "здоровим", "стилем", "життя", "."],
    ruTokens: ["Я", "стараюсь", "вести", "здоровый", "образ", "жизни", "."],
    enTokens: ["I", "try", "to", "live", "a", "healthy", "lifestyle", "."],
    extraUaTokens: ["хаотичним", "вчора", "днем"],
    extraRuTokens: ["хаотичный", "вчера", "день"],
    extraEnTokens: ["chaotic", "yesterday", "day"],
  },

  [phraseKey("disciplína", "a2-43")]: {
    sk: "Bez disciplíny to nepůjde.",
    ua: "Без дисципліни це не вийде.",
    ru: "Без дисциплины это не получится.",
    en: "Without discipline, it will not work.",
    uaTokens: ["Без", "дисципліни", "це", "не", "вийде", "."],
    ruTokens: ["Без", "дисциплины", "это", "не", "получится", "."],
    enTokens: ["Without", "discipline", ",", "it", "will", "not", "work", "."],
    extraUaTokens: ["мотивації", "вчора", "можна"],
    extraRuTokens: ["мотивации", "вчера", "можно"],
    extraEnTokens: ["motivation", "yesterday", "possible"],
  },

  // =========================
  // LESSON A2-44 — Характер і поведінка
  // =========================
  [phraseKey("chování", "a2-44")]: {
    sk: "Jeho chování mě překvapilo.",
    ua: "Його поведінка мене здивувала.",
    ru: "Его поведение меня удивило.",
    en: "His behavior surprised me.",
    uaTokens: ["Його", "поведінка", "мене", "здивувала", "."],
    ruTokens: ["Его", "поведение", "меня", "удивило", "."],
    enTokens: ["His", "behavior", "surprised", "me", "."],
    extraUaTokens: ["слова", "вчора", "заспокоїли"],
    extraRuTokens: ["слова", "вчера", "успокоили"],
    extraEnTokens: ["words", "yesterday", "calmed"],
  },

  [phraseKey("zdvořilý", "a2-44")]: {
    sk: "Byl ke všem velmi zdvořilý.",
    ua: "Він був до всіх дуже ввічливий.",
    ru: "Он был со всеми очень вежлив.",
    en: "He was very polite to everyone.",
    uaTokens: ["Він", "був", "до", "всіх", "дуже", "ввічливий", "."],
    ruTokens: ["Он", "был", "со", "всеми", "очень", "вежлив", "."],
    enTokens: ["He", "was", "very", "polite", "to", "everyone", "."],
    extraUaTokens: ["грубий", "вчора", "до"],
    extraRuTokens: ["груб", "вчера", "со"],
    extraEnTokens: ["rude", "yesterday", "to"],
  },

  [phraseKey("drzý", "a2-44")]: {
    sk: "To byla trochu drzá odpověď.",
    ua: "Це була трохи зухвала відповідь.",
    ru: "Это был немного дерзкий ответ.",
    en: "That was a slightly cheeky answer.",
    uaTokens: ["Це", "була", "трохи", "зухвала", "відповідь", "."],
    ruTokens: ["Это", "был", "немного", "дерзкий", "ответ", "."],
    enTokens: ["That", "was", "a", "slightly", "cheeky", "answer", "."],
    extraUaTokens: ["спокійна", "вчора", "реакція"],
    extraRuTokens: ["спокойный", "вчера", "реакция"],
    extraEnTokens: ["calm", "yesterday", "reaction"],
  },

  [phraseKey("trpělivý", "a2-44")]: {
    sk: "Musíš být trpělivý.",
    ua: "Ти маєш бути терплячим.",
    ru: "Ты должен быть терпеливым.",
    en: "You have to be patient.",
    uaTokens: ["Ти", "маєш", "бути", "терплячим", "."],
    ruTokens: ["Ты", "должен", "быть", "терпеливым", "."],
    enTokens: ["You", "have", "to", "be", "patient", "."],
    extraUaTokens: ["нервовим", "вчора", "тихим"],
    extraRuTokens: ["нервным", "вчера", "тихим"],
    extraEnTokens: ["nervous", "yesterday", "quiet"],
  },

  [phraseKey("netrpělivý", "a2-44")]: {
    sk: "Dnes jsem nějak netrpělivý.",
    ua: "Сьогодні я якийсь нетерплячий.",
    ru: "Сегодня я какой-то нетерпеливый.",
    en: "Today I am somehow impatient.",
    uaTokens: ["Сьогодні", "я", "якийсь", "нетерплячий", "."],
    ruTokens: ["Сегодня", "я", "какой-то", "нетерпеливый", "."],
    enTokens: ["Today", "I", "am", "somehow", "impatient", "."],
    extraUaTokens: ["спокійний", "вчора", "дуже"],
    extraRuTokens: ["спокойный", "вчера", "очень"],
    extraEnTokens: ["calm", "yesterday", "very"],
  },

  [phraseKey("ochotný", "a2-44")]: {
    sk: "Byla velmi ochotná mi pomoct.",
    ua: "Вона була дуже охоча мені допомогти.",
    ru: "Она была очень готова мне помочь.",
    en: "She was very willing to help me.",
    uaTokens: ["Вона", "була", "дуже", "охоча", "мені", "допомогти", "."],
    ruTokens: ["Она", "была", "очень", "готова", "мне", "помочь", "."],
    enTokens: ["She", "was", "very", "willing", "to", "help", "me", "."],
    extraUaTokens: ["відмовити", "вчора", "не"],
    extraRuTokens: ["отказать", "вчера", "не"],
    extraEnTokens: ["refuse", "yesterday", "not"],
  },

  [phraseKey("tvrdohlavý", "a2-44")]: {
    sk: "Můj bratr je dost tvrdohlavý.",
    ua: "Мій брат досить впертий.",
    ru: "Мой брат довольно упрямый.",
    en: "My brother is quite stubborn.",
    uaTokens: ["Мій", "брат", "досить", "впертий", "."],
    ruTokens: ["Мой", "брат", "довольно", "упрямый", "."],
    enTokens: ["My", "brother", "is", "quite", "stubborn", "."],
    extraUaTokens: ["гнучкий", "вчора", "сусід"],
    extraRuTokens: ["гибкий", "вчера", "сосед"],
    extraEnTokens: ["flexible", "yesterday", "neighbor"],
  },

  [phraseKey("přátelský", "a2-44")]: {
    sk: "Noví sousedé jsou velmi přátelští.",
    ua: "Нові сусіди дуже дружні.",
    ru: "Новые соседи очень дружелюбные.",
    en: "The new neighbors are very friendly.",
    uaTokens: ["Нові", "сусіди", "дуже", "дружні", "."],
    ruTokens: ["Новые", "соседи", "очень", "дружелюбные", "."],
    enTokens: ["The", "new", "neighbors", "are", "very", "friendly", "."],
    extraUaTokens: ["ворожі", "вчора", "люди"],
    extraRuTokens: ["враждебные", "вчера", "люди"],
    extraEnTokens: ["hostile", "yesterday", "people"],
  },

  [phraseKey("odpovědný", "a2-44")]: {
    sk: "Je to odpovědný a spolehlivý člověk.",
    ua: "Він відповідальний і надійний чоловік.",
    ru: "Он ответственный и надёжный человек.",
    en: "He is a responsible and reliable person.",
    uaTokens: ["Він", "відповідальний", "і", "надійний", "чоловік", "."],
    ruTokens: ["Он", "ответственный", "и", "надёжный", "человек", "."],
    enTokens: ["He", "is", "a", "responsible", "and", "reliable", "person", "."],
    extraUaTokens: ["ледача", "вчора", "ненадійна"],
    extraRuTokens: ["ленивый", "вчера", "ненадёжный"],
    extraEnTokens: ["lazy", "yesterday", "unreliable"],
  },

  [phraseKey("lenivý", "a2-44")]: {
    sk: "Nechci být celý den lenivý.",
    ua: "Я не хочу бути весь день ледачим.",
    ru: "Я не хочу быть ленивым весь день.",
    en: "I do not want to be lazy all day.",
    uaTokens: ["Я", "не", "хочу", "бути", "весь", "день", "ледачим", "."],
    ruTokens: ["Я", "не", "хочу", "быть", "ленивым", "весь", "день", "."],
    enTokens: ["I", "do", "not", "want", "to", "be", "lazy", "all", "day", "."],
    extraUaTokens: ["працьовитим", "вчора", "рано"],
    extraRuTokens: ["трудолюбивым", "вчера", "рано"],
    extraEnTokens: ["hardworking", "yesterday", "early"],
  },

  // =========================
  // LESSON A2-45 — Проблеми та рішення
  // =========================
  [phraseKey("situace", "a2-45")]: {
    sk: "To je opravdu těžká situace.",
    ua: "Це справді важка ситуація.",
    ru: "Это действительно трудная ситуация.",
    en: "This is really a difficult situation.",
    uaTokens: ["Це", "справді", "важка", "ситуація", "."],
    ruTokens: ["Это", "действительно", "трудная", "ситуация", "."],
    enTokens: ["This", "is", "really", "a", "difficult", "situation", "."],
    extraUaTokens: ["зустріч", "вчора", "легка"],
    extraRuTokens: ["встреча", "вчера", "лёгкая"],
    extraEnTokens: ["meeting", "yesterday", "easy"],
  },

  [phraseKey("problém", "a2-45")]: {
    sk: "Máme menší problém s autem.",
    ua: "У нас є невелика проблема з авто.",
    ru: "У нас небольшая проблема с машиной.",
    en: "We have a small problem with the car.",
    uaTokens: ["У", "нас", "є", "невелика", "проблема", "з", "авто", "."],
    ruTokens: ["У", "нас", "небольшая", "проблема", "с", "машиной", "."],
    enTokens: ["We", "have", "a", "small", "problem", "with", "the", "car", "."],
    extraUaTokens: ["велика", "вчора", "робота"],
    extraRuTokens: ["большая", "вчера", "работа"],
    extraEnTokens: ["big", "yesterday", "work"],
  },

  [phraseKey("řešení", "a2-45")]: {
    sk: "Teď hledáme nejlepší řešení.",
    ua: "Зараз ми шукаємо найкраще рішення.",
    ru: "Сейчас мы ищем лучшее решение.",
    en: "Now we are looking for the best solution.",
    uaTokens: ["Зараз", "ми", "шукаємо", "найкраще", "рішення", "."],
    ruTokens: ["Сейчас", "мы", "ищем", "лучшее", "решение", "."],
    enTokens: ["Now", "we", "are", "looking", "for", "the", "best", "solution", "."],
    extraUaTokens: ["проблему", "вчора", "найгірше"],
    extraRuTokens: ["проблему", "вчера", "худшее"],
    extraEnTokens: ["problem", "yesterday", "worst"],
  },

  [phraseKey("možnost", "a2-45")]: {
    sk: "Je tu ještě jedna možnost.",
    ua: "Тут є ще один варіант.",
    ru: "Здесь есть ещё один вариант.",
    en: "There is still one more option here.",
    uaTokens: ["Тут", "є", "ще", "один", "варіант", "."],
    ruTokens: ["Здесь", "есть", "ещё", "один", "вариант", "."],
    enTokens: ["There", "is", "still", "one", "more", "option", "here", "."],
    extraUaTokens: ["дві", "вчора", "відповіді"],
    extraRuTokens: ["два", "вчера", "ответа"],
    extraEnTokens: ["two", "yesterday", "answers"],
  },

  [phraseKey("riziko", "a2-45")]: {
    sk: "Bez rizika to někdy nejde.",
    ua: "Іноді без ризику не виходить.",
    ru: "Иногда без риска не получается.",
    en: "Sometimes it does not work without risk.",
    uaTokens: ["Іноді", "без", "ризику", "не", "виходить", "."],
    ruTokens: ["Иногда", "без", "риска", "не", "получается", "."],
    enTokens: ["Sometimes", "it", "does", "not", "work", "without", "risk", "."],
    extraUaTokens: ["безпеки", "вчора", "завжди"],
    extraRuTokens: ["безопасности", "вчера", "всегда"],
    extraEnTokens: ["safety", "yesterday", "always"],
  },

  [phraseKey("důsledek", "a2-45")]: {
    sk: "To byl důsledek špatného rozhodnutí.",
    ua: "Це був наслідок поганого рішення.",
    ru: "Это было следствием плохого решения.",
    en: "That was the consequence of a bad decision.",
    uaTokens: ["Це", "був", "наслідок", "поганого", "рішення", "."],
    ruTokens: ["Это", "было", "следствием", "плохого", "решения", "."],
    enTokens: ["That", "was", "the", "consequence", "of", "a", "bad", "decision", "."],
    extraUaTokens: ["причина", "вчора", "доброго"],
    extraRuTokens: ["причина", "вчера", "хорошего"],
    extraEnTokens: ["cause", "yesterday", "good"],
  },

  [phraseKey("výsledek", "a2-45")]: {
    sk: "Na výsledek si ještě počkáme.",
    ua: "На результат ми ще почекаємо.",
    ru: "Результата нам ещё придётся подождать.",
    en: "We will still have to wait for the result.",
    uaTokens: ["На", "результат", "ми", "ще", "почекаємо", "."],
    ruTokens: ["Результата", "нам", "ещё", "придётся", "подождать", "."],
    enTokens: ["We", "will", "still", "have", "to", "wait", "for", "the", "result", "."],
    extraUaTokens: ["відповідь", "вчора", "одразу"],
    extraRuTokens: ["ответа", "вчера", "сразу"],
    extraEnTokens: ["answer", "yesterday", "immediately"],
  },

  [phraseKey("zvládnout", "a2-45")]: {
    sk: "Věřím, že to zvládneme.",
    ua: "Я вірю, що ми з цим впораємося.",
    ru: "Я верю, что мы с этим справимся.",
    en: "I believe that we will handle it.",
    uaTokens: ["Я", "вірю", ",", "що", "ми", "з", "цим", "впораємося", "."],
    ruTokens: ["Я", "верю", ",", "что", "мы", "с", "этим", "справимся", "."],
    enTokens: ["I", "believe", "that", "we", "will", "handle", "it", "."],
    extraUaTokens: ["здамося", "вчора", "легко"],
    extraRuTokens: ["сдадимся", "вчера", "легко"],
    extraEnTokens: ["give up", "yesterday", "easily"],
  },

  [phraseKey("poradit si", "a2-45")]: {
    sk: "Musíme si s tím nějak poradit.",
    ua: "Ми маємо якось дати собі з цим раду.",
    ru: "Мы должны как-то с этим справиться.",
    en: "We have to deal with it somehow.",
    uaTokens: ["Ми", "маємо", "якось", "дати", "собі", "з", "цим", "раду", "."],
    ruTokens: ["Мы", "должны", "как-то", "с", "этим", "справиться", "."],
    enTokens: ["We", "have", "to", "deal", "with", "it", "somehow", "."],
    extraUaTokens: ["вчора", "забути", "це"],
    extraRuTokens: ["вчера", "забыть", "это"],
    extraEnTokens: ["yesterday", "forget", "it"],
  },

  [phraseKey("pokus", "a2-45")]: {
    sk: "Byl to dobrý první pokus.",
    ua: "Це була хороша перша спроба.",
    ru: "Это была хорошая первая попытка.",
    en: "It was a good first attempt.",
    uaTokens: ["Це", "була", "хороша", "перша", "спроба", "."],
    ruTokens: ["Это", "была", "хорошая", "первая", "попытка", "."],
    enTokens: ["It", "was", "a", "good", "first", "attempt", "."],
    extraUaTokens: ["остання", "вчора", "невдала"],
    extraRuTokens: ["последняя", "вчера", "неудачная"],
    extraEnTokens: ["last", "yesterday", "unsuccessful"],
  },
};