import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A0_BUILD_UA_SENTENCES_3: BuildUaSentenceDict = {
  // =========================
  // LESSON 11 — Числа
  // =========================
  [phraseKey("nula", "a0-11")]: {
    sk: "Je to nula.",
    ua: "Це нуль.",
    ru: "Это ноль.",
    en: "It is zero.",
    uaTokens: ["Це", "нуль", "."],
    ruTokens: ["Это", "ноль", "."],
    enTokens: ["It", "is", "zero", "."],
    extraUaTokens: ["один", "телефон", "день"],
    extraRuTokens: ["один", "телефон", "день"],
    extraEnTokens: ["one", "phone", "day"],
  },

  [phraseKey("jeden", "a0-11")]: {
    sk: "Mám jeden telefón.",
    ua: "У мене один телефон.",
    ru: "У меня один телефон.",
    en: "I have one phone.",
    uaTokens: ["У", "мене", "один", "телефон", "."],
    ruTokens: ["У", "меня", "один", "телефон", "."],
    enTokens: ["I", "have", "one", "phone", "."],
    extraUaTokens: ["нуль", "дні", "вихідних"],
    extraRuTokens: ["ноль", "дня", "выходных"],
    extraEnTokens: ["zero", "days", "off"],
  },

  [phraseKey("dva", "a0-11")]: {
    sk: "Mám dva dni voľno.",
    ua: "У мене два дні вихідних.",
    ru: "У меня два дня выходных.",
    en: "I have two days off.",
    uaTokens: ["У", "мене", "два", "дні", "вихідних", "."],
    ruTokens: ["У", "меня", "два", "дня", "выходных", "."],
    enTokens: ["I", "have", "two", "days", "off", "."],
    extraUaTokens: ["телефон", "нуль", "години"],
    extraRuTokens: ["телефон", "ноль", "часа"],
    extraEnTokens: ["phone", "zero", "hours"],
  },

  [phraseKey("tri", "a0-11")]: {
    sk: "Sú tri hodiny.",
    ua: "Зараз три години.",
    ru: "Сейчас три часа.",
    en: "It is three o’clock.",
    uaTokens: ["Зараз", "три", "години", "."],
    ruTokens: ["Сейчас", "три", "часа", "."],
    enTokens: ["It", "is", "three", "o’clock", "."],
    extraUaTokens: ["два", "телефон", "євро"],
    extraRuTokens: ["два", "телефон", "евро"],
    extraEnTokens: ["two", "phone", "euros"],
  },

  [phraseKey("štyri", "a0-11")]: {
    sk: "Sú štyri stoličky.",
    ua: "Є чотири стільці.",
    ru: "Есть четыре стула.",
    en: "There are four chairs.",
    uaTokens: ["Є", "чотири", "стільці", "."],
    ruTokens: ["Есть", "четыре", "стула", "."],
    enTokens: ["There", "are", "four", "chairs", "."],
    extraUaTokens: ["три", "євро", "день"],
    extraRuTokens: ["три", "евро", "день"],
    extraEnTokens: ["three", "euros", "day"],
  },

  [phraseKey("päť", "a0-11")]: {
    sk: "Je päť eur.",
    ua: "Це п’ять євро.",
    ru: "Это пять евро.",
    en: "It is five euros.",
    uaTokens: ["Це", "п’ять", "євро", "."],
    ruTokens: ["Это", "пять", "евро", "."],
    enTokens: ["It", "is", "five", "euros", "."],
    extraUaTokens: ["чотири", "стільці", "години"],
    extraRuTokens: ["четыре", "стула", "часа"],
    extraEnTokens: ["four", "chairs", "hours"],
  },

  [phraseKey("šesť", "a0-11")]: {
    sk: "Vstávam o šiestej.",
    ua: "Я встаю о шостій.",
    ru: "Я встаю в шесть.",
    en: "I get up at six.",
    uaTokens: ["Я", "встаю", "о", "шостій", "."],
    ruTokens: ["Я", "встаю", "в", "шесть", "."],
    enTokens: ["I", "get", "up", "at", "six", "."],
    extraUaTokens: ["вісім", "телефон", "нуль"],
    extraRuTokens: ["восемь", "телефон", "ноль"],
    extraEnTokens: ["eight", "phone", "zero"],
  },

  [phraseKey("sedem", "a0-11")]: {
    sk: "V týždni je sedem dní.",
    ua: "У тижні сім днів.",
    ru: "В неделе семь дней.",
    en: "There are seven days in a week.",
    uaTokens: ["У", "тижні", "сім", "днів", "."],
    ruTokens: ["В", "неделе", "семь", "дней", "."],
    enTokens: ["There", "are", "seven", "days", "in", "a", "week", "."],
    extraUaTokens: ["три", "години", "вихідних"],
    extraRuTokens: ["три", "часа", "выходных"],
    extraEnTokens: ["three", "hours", "off"],
  },

  [phraseKey("osem", "a0-11")]: {
    sk: "Prídem o ôsmej.",
    ua: "Я прийду о восьмій.",
    ru: "Я приду в восемь.",
    en: "I will come at eight.",
    uaTokens: ["Я", "прийду", "о", "восьмій", "."],
    ruTokens: ["Я", "приду", "в", "восемь", "."],
    enTokens: ["I", "will", "come", "at", "eight", "."],
    extraUaTokens: ["шостій", "дні", "телефон"],
    extraRuTokens: ["шесть", "дня", "телефон"],
    extraEnTokens: ["six", "days", "phone"],
  },

  [phraseKey("deväť", "a0-11")]: {
    sk: "Je deväť hodín.",
    ua: "Зараз дев’ята година.",
    ru: "Сейчас девять часов.",
    en: "It is nine o’clock.",
    uaTokens: ["Зараз", "дев’ята", "година", "."],
    ruTokens: ["Сейчас", "девять", "часов", "."],
    enTokens: ["It", "is", "nine", "o’clock", "."],
    extraUaTokens: ["восьмій", "євро", "стільці"],
    extraRuTokens: ["восемь", "евро", "стула"],
    extraEnTokens: ["eight", "euros", "chairs"],
  },

  // =========================
  // LESSON 12 — Кольори
  // =========================
  [phraseKey("farba", "a0-12")]: {
    sk: "Aká je to farba?",
    ua: "Який це колір?",
    ru: "Какой это цвет?",
    en: "What color is it?",
    uaTokens: ["Який", "це", "колір", "?"],
    ruTokens: ["Какой", "это", "цвет", "?"],
    enTokens: ["What", "color", "is", "it", "?"],
    extraUaTokens: ["білий", "папір", "телефон"],
    extraRuTokens: ["белый", "бумага", "телефон"],
    extraEnTokens: ["white", "paper", "phone"],
  },

  [phraseKey("biely", "a0-12")]: {
    sk: "Toto je biely papier.",
    ua: "Це білий папір.",
    ru: "Это белая бумага.",
    en: "This is white paper.",
    uaTokens: ["Це", "білий", "папір", "."],
    ruTokens: ["Это", "белая", "бумага", "."],
    enTokens: ["This", "is", "white", "paper", "."],
    extraUaTokens: ["колір", "чорний", "светр"],
    extraRuTokens: ["цвет", "чёрный", "свитер"],
    extraEnTokens: ["color", "black", "sweater"],
  },

  [phraseKey("čierny", "a0-12")]: {
    sk: "Mám čierny telefón.",
    ua: "У мене чорний телефон.",
    ru: "У меня чёрный телефон.",
    en: "I have a black phone.",
    uaTokens: ["У", "мене", "чорний", "телефон", "."],
    ruTokens: ["У", "меня", "чёрный", "телефон", "."],
    enTokens: ["I", "have", "a", "black", "phone", "."],
    extraUaTokens: ["білий", "папір", "синій"],
    extraRuTokens: ["белая", "бумага", "синий"],
    extraEnTokens: ["white", "paper", "blue"],
  },

  [phraseKey("červený", "a0-12")]: {
    sk: "To je červený kabát.",
    ua: "Це червоне пальто.",
    ru: "Это красное пальто.",
    en: "It is a red coat.",
    uaTokens: ["Це", "червоне", "пальто", "."],
    ruTokens: ["Это", "красное", "пальто", "."],
    enTokens: ["It", "is", "a", "red", "coat", "."],
    extraUaTokens: ["телефон", "білий", "дерево"],
    extraRuTokens: ["телефон", "белая", "дерево"],
    extraEnTokens: ["phone", "white", "tree"],
  },

  [phraseKey("modrý", "a0-12")]: {
    sk: "Mám modrý sveter.",
    ua: "У мене синій светр.",
    ru: "У меня синий свитер.",
    en: "I have a blue sweater.",
    uaTokens: ["У", "мене", "синій", "светр", "."],
    ruTokens: ["У", "меня", "синий", "свитер", "."],
    enTokens: ["I", "have", "a", "blue", "sweater", "."],
    extraUaTokens: ["чорний", "телефон", "колір"],
    extraRuTokens: ["чёрный", "телефон", "цвет"],
    extraEnTokens: ["black", "phone", "color"],
  },

  [phraseKey("zelený", "a0-12")]: {
    sk: "Zelený strom je veľký.",
    ua: "Зелене дерево велике.",
    ru: "Зелёное дерево большое.",
    en: "The green tree is big.",
    uaTokens: ["Зелене", "дерево", "велике", "."],
    ruTokens: ["Зелёное", "дерево", "большое", "."],
    enTokens: ["The", "green", "tree", "is", "big", "."],
    extraUaTokens: ["жовте", "сонце", "светр"],
    extraRuTokens: ["жёлтое", "солнце", "свитер"],
    extraEnTokens: ["yellow", "sun", "sweater"],
  },

  [phraseKey("žltý", "a0-12")]: {
    sk: "Žlté slnko svieti.",
    ua: "Жовте сонце світить.",
    ru: "Жёлтое солнце светит.",
    en: "The yellow sun is shining.",
    uaTokens: ["Жовте", "сонце", "світить", "."],
    ruTokens: ["Жёлтое", "солнце", "светит", "."],
    enTokens: ["The", "yellow", "sun", "is", "shining", "."],
    extraUaTokens: ["зелене", "дерево", "велике"],
    extraRuTokens: ["зелёное", "дерево", "большое"],
    extraEnTokens: ["green", "tree", "big"],
  },

  [phraseKey("oranžový", "a0-12")]: {
    sk: "Chcem oranžový džús.",
    ua: "Я хочу помаранчевий сік.",
    ru: "Я хочу оранжевый сок.",
    en: "I want orange juice.",
    uaTokens: ["Я", "хочу", "помаранчевий", "сік", "."],
    ruTokens: ["Я", "хочу", "оранжевый", "сок", "."],
    enTokens: ["I", "want", "orange", "juice", "."],
    extraUaTokens: ["жовте", "сонце", "папір"],
    extraRuTokens: ["жёлтое", "солнце", "бумага"],
    extraEnTokens: ["yellow", "sun", "paper"],
  },

  [phraseKey("ružový", "a0-12")]: {
    sk: "Ružové šaty sú pekné.",
    ua: "Рожева сукня гарна.",
    ru: "Розовое платье красивое.",
    en: "The pink dress is beautiful.",
    uaTokens: ["Рожева", "сукня", "гарна", "."],
    ruTokens: ["Розовое", "платье", "красивое", "."],
    enTokens: ["The", "pink", "dress", "is", "beautiful", "."],
    extraUaTokens: ["помаранчевий", "сік", "взуття"],
    extraRuTokens: ["оранжевый", "сок", "обувь"],
    extraEnTokens: ["orange", "juice", "shoes"],
  },

  [phraseKey("hnedý", "a0-12")]: {
    sk: "Hnedé topánky sú nové.",
    ua: "Коричневе взуття нове.",
    ru: "Коричневая обувь новая.",
    en: "The brown shoes are new.",
    uaTokens: ["Коричневе", "взуття", "нове", "."],
    ruTokens: ["Коричневая", "обувь", "новая", "."],
    enTokens: ["The", "brown", "shoes", "are", "new", "."],
    extraUaTokens: ["рожева", "сукня", "гарна"],
    extraRuTokens: ["розовое", "платье", "красивое"],
    extraEnTokens: ["pink", "dress", "beautiful"],
  },

  // =========================
  // LESSON 13 — Одяг
  // =========================
  [phraseKey("oblečenie", "a0-13")]: {
    sk: "Toto je moje oblečenie.",
    ua: "Це мій одяг.",
    ru: "Это моя одежда.",
    en: "These are my clothes.",
    uaTokens: ["Це", "мій", "одяг", "."],
    ruTokens: ["Это", "моя", "одежда", "."],
    enTokens: ["These", "are", "my", "clothes", "."],
    extraUaTokens: ["футболка", "штани", "куртку"],
    extraRuTokens: ["футболка", "брюки", "куртку"],
    extraEnTokens: ["T-shirt", "pants", "jacket"],
  },

  [phraseKey("tričko", "a0-13")]: {
    sk: "Mám nové tričko.",
    ua: "У мене нова футболка.",
    ru: "У меня новая футболка.",
    en: "I have a new T-shirt.",
    uaTokens: ["У", "мене", "нова", "футболка", "."],
    ruTokens: ["У", "меня", "новая", "футболка", "."],
    enTokens: ["I", "have", "a", "new", "T-shirt", "."],
    extraUaTokens: ["одяг", "чисті", "взуття"],
    extraRuTokens: ["одежда", "чистые", "обувь"],
    extraEnTokens: ["clothes", "clean", "shoes"],
  },

  [phraseKey("nohavice", "a0-13")]: {
    sk: "Tieto nohavice sú čisté.",
    ua: "Ці штани чисті.",
    ru: "Эти брюки чистые.",
    en: "These pants are clean.",
    uaTokens: ["Ці", "штани", "чисті", "."],
    ruTokens: ["Эти", "брюки", "чистые", "."],
    enTokens: ["These", "pants", "are", "clean", "."],
    extraUaTokens: ["футболка", "шафа", "теплий"],
    extraRuTokens: ["футболка", "шкаф", "тёплый"],
    extraEnTokens: ["T-shirt", "wardrobe", "warm"],
  },

  [phraseKey("bunda", "a0-13")]: {
    sk: "Je zima, dávam si bundu.",
    ua: "Холодно, я одягаю куртку.",
    ru: "Холодно, я надеваю куртку.",
    en: "It is cold, I am putting on a jacket.",
    uaTokens: ["Холодно", ",", "я", "одягаю", "куртку", "."],
    ruTokens: ["Холодно", ",", "я", "надеваю", "куртку", "."],
    enTokens: ["It", "is", "cold", ",", "I", "am", "putting", "on", "a", "jacket", "."],
    extraUaTokens: ["шапка", "светр", "чисті"],
    extraRuTokens: ["шапка", "свитер", "чистые"],
    extraEnTokens: ["hat", "sweater", "clean"],
  },

  [phraseKey("topánky", "a0-13")]: {
    sk: "Kde sú moje topánky?",
    ua: "Де моє взуття?",
    ru: "Где моя обувь?",
    en: "Where are my shoes?",
    uaTokens: ["Де", "моє", "взуття", "?"],
    ruTokens: ["Где", "моя", "обувь", "?"],
    enTokens: ["Where", "are", "my", "shoes", "?"],
    extraUaTokens: ["куртку", "шафі", "шапка"],
    extraRuTokens: ["куртка", "шкафу", "шапка"],
    extraEnTokens: ["jacket", "wardrobe", "hat"],
  },

  [phraseKey("kabát", "a0-13")]: {
    sk: "Kabát je v skrini.",
    ua: "Пальто в шафі.",
    ru: "Пальто в шкафу.",
    en: "The coat is in the wardrobe.",
    uaTokens: ["Пальто", "в", "шафі", "."],
    ruTokens: ["Пальто", "в", "шкафу", "."],
    enTokens: ["The", "coat", "is", "in", "the", "wardrobe", "."],
    extraUaTokens: ["взуття", "футболка", "сумці"],
    extraRuTokens: ["обувь", "футболка", "сумке"],
    extraEnTokens: ["shoes", "T-shirt", "bag"],
  },

  [phraseKey("šaty", "a0-13")]: {
    sk: "Šaty sú ružové.",
    ua: "Сукня рожева.",
    ru: "Платье розовое.",
    en: "The dress is pink.",
    uaTokens: ["Сукня", "рожева", "."],
    ruTokens: ["Платье", "розовое", "."],
    enTokens: ["The", "dress", "is", "pink", "."],
    extraUaTokens: ["пальто", "шафі", "теплий"],
    extraRuTokens: ["пальто", "шкафу", "тёплый"],
    extraEnTokens: ["coat", "wardrobe", "warm"],
  },

  [phraseKey("čiapka", "a0-13")]: {
    sk: "Potrebujem čiapku.",
    ua: "Мені потрібна шапка.",
    ru: "Мне нужна шапка.",
    en: "I need a hat.",
    uaTokens: ["Мені", "потрібна", "шапка", "."],
    ruTokens: ["Мне", "нужна", "шапка", "."],
    enTokens: ["I", "need", "a", "hat", "."],
    extraUaTokens: ["куртку", "светр", "одяг"],
    extraRuTokens: ["куртка", "свитер", "одежда"],
    extraEnTokens: ["jacket", "sweater", "clothes"],
  },

  [phraseKey("ponožky", "a0-13")]: {
    sk: "Ponožky sú v taške.",
    ua: "Шкарпетки в сумці.",
    ru: "Носки в сумке.",
    en: "The socks are in the bag.",
    uaTokens: ["Шкарпетки", "в", "сумці", "."],
    ruTokens: ["Носки", "в", "сумке", "."],
    enTokens: ["The", "socks", "are", "in", "the", "bag", "."],
    extraUaTokens: ["шапка", "пальто", "чисті"],
    extraRuTokens: ["шапка", "пальто", "чистые"],
    extraEnTokens: ["hat", "coat", "clean"],
  },

  [phraseKey("sveter", "a0-13")]: {
    sk: "Sveter je teplý.",
    ua: "Светр теплий.",
    ru: "Свитер тёплый.",
    en: "The sweater is warm.",
    uaTokens: ["Светр", "теплий", "."],
    ruTokens: ["Свитер", "тёплый", "."],
    enTokens: ["The", "sweater", "is", "warm", "."],
    extraUaTokens: ["футболка", "шапка", "сумці"],
    extraRuTokens: ["футболка", "шапка", "сумке"],
    extraEnTokens: ["T-shirt", "hat", "bag"],
  },

  // =========================
  // LESSON 14 — Тіло людини
  // =========================
  [phraseKey("telo", "a0-14")]: {
    sk: "Telo potrebuje oddych.",
    ua: "Тілу потрібен відпочинок.",
    ru: "Телу нужен отдых.",
    en: "The body needs rest.",
    uaTokens: ["Тілу", "потрібен", "відпочинок", "."],
    ruTokens: ["Телу", "нужен", "отдых", "."],
    enTokens: ["The", "body", "needs", "rest", "."],
    extraUaTokens: ["голова", "рука", "важливе"],
    extraRuTokens: ["голова", "рука", "важно"],
    extraEnTokens: ["head", "hand", "important"],
  },

  [phraseKey("hlava", "a0-14")]: {
    sk: "Bolie ma hlava.",
    ua: "У мене болить голова.",
    ru: "У меня болит голова.",
    en: "I have a headache.",
    uaTokens: ["У", "мене", "болить", "голова", "."],
    ruTokens: ["У", "меня", "болит", "голова", "."],
    enTokens: ["I", "have", "a", "headache", "."],
    extraUaTokens: ["око", "рука", "відпочинок"],
    extraRuTokens: ["глаз", "рука", "отдых"],
    extraEnTokens: ["eye", "hand", "rest"],
  },

  [phraseKey("oko", "a0-14")]: {
    sk: "Mám unavené oko.",
    ua: "У мене втомлене око.",
    ru: "У меня устал глаз.",
    en: "My eye is tired.",
    uaTokens: ["У", "мене", "втомлене", "око", "."],
    ruTokens: ["У", "меня", "устал", "глаз", "."],
    enTokens: ["My", "eye", "is", "tired", "."],
    extraUaTokens: ["голова", "ніс", "холодний"],
    extraRuTokens: ["голова", "нос", "холодный"],
    extraEnTokens: ["head", "nose", "cold"],
  },

  [phraseKey("nos", "a0-14")]: {
    sk: "Nos mám studený.",
    ua: "Ніс у мене холодний.",
    ru: "Нос у меня холодный.",
    en: "My nose is cold.",
    uaTokens: ["Ніс", "у", "мене", "холодний", "."],
    ruTokens: ["Нос", "у", "меня", "холодный", "."],
    enTokens: ["My", "nose", "is", "cold", "."],
    extraUaTokens: ["око", "рот", "сухий"],
    extraRuTokens: ["глаз", "рот", "сухой"],
    extraEnTokens: ["eye", "mouth", "dry"],
  },

  [phraseKey("ústa", "a0-14")]: {
    sk: "Ústa sú suché.",
    ua: "Рот сухий.",
    ru: "Рот сухой.",
    en: "My mouth is dry.",
    uaTokens: ["Рот", "сухий", "."],
    ruTokens: ["Рот", "сухой", "."],
    enTokens: ["My", "mouth", "is", "dry", "."],
    extraUaTokens: ["ніс", "холодний", "нога"],
    extraRuTokens: ["нос", "холодный", "нога"],
    extraEnTokens: ["nose", "cold", "leg"],
  },

  [phraseKey("ruka", "a0-14")]: {
    sk: "Ruka ma bolí.",
    ua: "Рука болить.",
    ru: "Рука болит.",
    en: "My hand hurts.",
    uaTokens: ["Рука", "болить", "."],
    ruTokens: ["Рука", "болит", "."],
    enTokens: ["My", "hand", "hurts", "."],
    extraUaTokens: ["голова", "спина", "живіт"],
    extraRuTokens: ["голова", "спина", "живот"],
    extraEnTokens: ["head", "back", "stomach"],
  },

  [phraseKey("noha", "a0-14")]: {
    sk: "Noha je unavená.",
    ua: "Нога втомлена.",
    ru: "Нога устала.",
    en: "My leg is tired.",
    uaTokens: ["Нога", "втомлена", "."],
    ruTokens: ["Нога", "устала", "."],
    enTokens: ["My", "leg", "is", "tired", "."],
    extraUaTokens: ["рука", "голова", "важливе"],
    extraRuTokens: ["рука", "голова", "важно"],
    extraEnTokens: ["hand", "head", "important"],
  },

  [phraseKey("chrbát", "a0-14")]: {
    sk: "Chrbát ma bolí.",
    ua: "Спина болить.",
    ru: "Спина болит.",
    en: "My back hurts.",
    uaTokens: ["Спина", "болить", "."],
    ruTokens: ["Спина", "болит", "."],
    enTokens: ["My", "back", "hurts", "."],
    extraUaTokens: ["рука", "нога", "око"],
    extraRuTokens: ["рука", "нога", "глаз"],
    extraEnTokens: ["hand", "leg", "eye"],
  },

  [phraseKey("brucho", "a0-14")]: {
    sk: "Brucho ma bolí.",
    ua: "Живіт болить.",
    ru: "Живот болит.",
    en: "My stomach hurts.",
    uaTokens: ["Живіт", "болить", "."],
    ruTokens: ["Живот", "болит", "."],
    enTokens: ["My", "stomach", "hurts", "."],
    extraUaTokens: ["спина", "рука", "голова"],
    extraRuTokens: ["спина", "рука", "голова"],
    extraEnTokens: ["back", "hand", "head"],
  },

  [phraseKey("srdce", "a0-14")]: {
    sk: "Srdce je dôležité.",
    ua: "Серце важливе.",
    ru: "Сердце важно.",
    en: "The heart is important.",
    uaTokens: ["Серце", "важливе", "."],
    ruTokens: ["Сердце", "важно", "."],
    enTokens: ["The", "heart", "is", "important", "."],
    extraUaTokens: ["тілу", "відпочинок", "голова"],
    extraRuTokens: ["телу", "отдых", "голова"],
    extraEnTokens: ["body", "rest", "head"],
  },

  // =========================
  // LESSON 15 — Здоров’я
  // =========================
  [phraseKey("zdravie", "a0-15")]: {
    sk: "Zdravie je dôležité.",
    ua: "Здоров’я важливе.",
    ru: "Здоровье важно.",
    en: "Health is important.",
    uaTokens: ["Здоров’я", "важливе", "."],
    ruTokens: ["Здоровье", "важно", "."],
    enTokens: ["Health", "is", "important", "."],
    extraUaTokens: ["лікар", "біль", "температура"],
    extraRuTokens: ["врач", "боль", "температура"],
    extraEnTokens: ["doctor", "pain", "temperature"],
  },

  [phraseKey("choroba", "a0-15")]: {
    sk: "Mám chorobu.",
    ua: "У мене хвороба.",
    ru: "У меня болезнь.",
    en: "I am sick.",
    uaTokens: ["У", "мене", "хвороба", "."],
    ruTokens: ["У", "меня", "болезнь", "."],
    enTokens: ["I", "am", "sick", "."],
    extraUaTokens: ["лікар", "біль", "застуда"],
    extraRuTokens: ["врач", "боль", "простуда"],
    extraEnTokens: ["doctor", "pain", "cold"],
  },

  [phraseKey("lekár", "a0-15")]: {
    sk: "Potrebujem lekára.",
    ua: "Мені потрібен лікар.",
    ru: "Мне нужен врач.",
    en: "I need a doctor.",
    uaTokens: ["Мені", "потрібен", "лікар", "."],
    ruTokens: ["Мне", "нужен", "врач", "."],
    enTokens: ["I", "need", "a", "doctor", "."],
    extraUaTokens: ["хвороба", "біль", "температура"],
    extraRuTokens: ["болезнь", "боль", "температура"],
    extraEnTokens: ["illness", "pain", "temperature"],
  },

  [phraseKey("nemocnica", "a0-15")]: {
    sk: "Idem do nemocnice.",
    ua: "Я йду до лікарні.",
    ru: "Я иду в больницу.",
    en: "I am going to the hospital.",
    uaTokens: ["Я", "йду", "до", "лікарні", "."],
    ruTokens: ["Я", "иду", "в", "больницу", "."],
    enTokens: ["I", "am", "going", "to", "the", "hospital", "."],
    extraUaTokens: ["лікар", "ліки", "біль"],
    extraRuTokens: ["врач", "лекарство", "боль"],
    extraEnTokens: ["doctor", "medicine", "pain"],
  },

  [phraseKey("liek", "a0-15")]: {
    sk: "Toto je liek.",
    ua: "Це ліки.",
    ru: "Это лекарство.",
    en: "This is medicine.",
    uaTokens: ["Це", "ліки", "."],
    ruTokens: ["Это", "лекарство", "."],
    enTokens: ["This", "is", "medicine", "."],
    extraUaTokens: ["лікар", "температура", "хвороба"],
    extraRuTokens: ["врач", "температура", "болезнь"],
    extraEnTokens: ["doctor", "temperature", "illness"],
  },

  [phraseKey("bolesť", "a0-15")]: {
    sk: "Mám bolesť.",
    ua: "У мене біль.",
    ru: "У меня боль.",
    en: "I am in pain.",
    uaTokens: ["У", "мене", "біль", "."],
    ruTokens: ["У", "меня", "боль", "."],
    enTokens: ["I", "am", "in", "pain", "."],
    extraUaTokens: ["лікар", "хвороба", "застуда"],
    extraRuTokens: ["врач", "болезнь", "простуда"],
    extraEnTokens: ["doctor", "illness", "cold"],
  },

  [phraseKey("teplota", "a0-15")]: {
    sk: "Mám teplotu.",
    ua: "У мене температура.",
    ru: "У меня температура.",
    en: "I have a fever.",
    uaTokens: ["У", "мене", "температура", "."],
    ruTokens: ["У", "меня", "температура", "."],
    enTokens: ["I", "have", "a", "fever", "."],
    extraUaTokens: ["біль", "кашель", "лікар"],
    extraRuTokens: ["боль", "кашель", "врач"],
    extraEnTokens: ["pain", "cough", "doctor"],
  },

  [phraseKey("kašeľ", "a0-15")]: {
    sk: "Mám kašeľ.",
    ua: "У мене кашель.",
    ru: "У меня кашель.",
    en: "I have a cough.",
    uaTokens: ["У", "мене", "кашель", "."],
    ruTokens: ["У", "меня", "кашель", "."],
    enTokens: ["I", "have", "a", "cough", "."],
    extraUaTokens: ["температура", "застуда", "ліки"],
    extraRuTokens: ["температура", "простуда", "лекарство"],
    extraEnTokens: ["temperature", "cold", "medicine"],
  },

  [phraseKey("prechladnutie", "a0-15")]: {
    sk: "Mám prechladnutie.",
    ua: "У мене застуда.",
    ru: "У меня простуда.",
    en: "I have a cold.",
    uaTokens: ["У", "мене", "застуда", "."],
    ruTokens: ["У", "меня", "простуда", "."],
    enTokens: ["I", "have", "a", "cold", "."],
    extraUaTokens: ["кашель", "температура", "лікар"],
    extraRuTokens: ["кашель", "температура", "врач"],
    extraEnTokens: ["cough", "temperature", "doctor"],
  },

  [phraseKey("uzdraviť sa", "a0-15")]: {
    sk: "Chcem sa uzdraviť.",
    ua: "Я хочу одужати.",
    ru: "Я хочу выздороветь.",
    en: "I want to get better.",
    uaTokens: ["Я", "хочу", "одужати", "."],
    ruTokens: ["Я", "хочу", "выздороветь", "."],
    enTokens: ["I", "want", "to", "get", "better", "."],
    extraUaTokens: ["лікар", "ліки", "застуда"],
    extraRuTokens: ["врач", "лекарство", "простуда"],
    extraEnTokens: ["doctor", "medicine", "cold"],
  },
};