import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A0_BUILD_UA_SENTENCES_4: BuildUaSentenceDict = { // =========================
    // LESSON 16 — Погода
    // =========================
    [phraseKey("počasie", "a0-16")]: {
        sk: "Aké je dnes počasie?",
        ua: "Яка сьогодні погода?",
        ru: "Какая сегодня погода?",
        en: "What is the weather like today?",
        uaTokens: ["Яка", "сьогодні", "погода", "?"],
        ruTokens: ["Какая", "сегодня", "погода", "?"],
        enTokens: ["What", "is", "the", "weather", "like", "today", "?"],
        extraUaTokens: ["дощ", "сонце", "вітер"],
        extraRuTokens: ["дождь", "солнце", "ветер"],
        extraEnTokens: ["rain", "sun", "wind"],
    },

    [phraseKey("slnko", "a0-16")]: {
        sk: "Slnko svieti.",
        ua: "Сонце світить.",
        ru: "Солнце светит.",
        en: "The sun is shining.",
        uaTokens: ["Сонце", "світить", "."],
        ruTokens: ["Солнце", "светит", "."],
        enTokens: ["The", "sun", "is", "shining", "."],
        extraUaTokens: ["погода", "дощ", "тепло"],
        extraRuTokens: ["погода", "дождь", "тепло"],
        extraEnTokens: ["weather", "rain", "warm"],
    },

    [phraseKey("dážď", "a0-16")]: {
        sk: "Dnes je dážď.",
        ua: "Сьогодні дощ.",
        ru: "Сегодня дождь.",
        en: "Today it is raining.",
        uaTokens: ["Сьогодні", "дощ", "."],
        ruTokens: ["Сегодня", "дождь", "."],
        enTokens: ["Today", "it", "is", "raining", "."],
        extraUaTokens: ["сонце", "погода", "холодно"],
        extraRuTokens: ["солнце", "погода", "холодно"],
        extraEnTokens: ["sun", "weather", "cold"],
    },

    [phraseKey("sneh", "a0-16")]: {
        sk: "Je sneh.",
        ua: "Є сніг.",
        ru: "Есть снег.",
        en: "There is snow.",
        uaTokens: ["Є", "сніг", "."],
        ruTokens: ["Есть", "снег", "."],
        enTokens: ["There", "is", "snow", "."],
        extraUaTokens: ["дощ", "буря", "температура"],
        extraRuTokens: ["дождь", "буря", "температура"],
        extraEnTokens: ["rain", "storm", "temperature"],
    },

    [phraseKey("vietor", "a0-16")]: {
        sk: "Fúka vietor.",
        ua: "Дме вітер.",
        ru: "Дует ветер.",
        en: "The wind is blowing.",
        uaTokens: ["Дме", "вітер", "."],
        ruTokens: ["Дует", "ветер", "."],
        enTokens: ["The", "wind", "is", "blowing", "."],
        extraUaTokens: ["дощ", "сніг", "хмара"],
        extraRuTokens: ["дождь", "снег", "облако"],
        extraEnTokens: ["rain", "snow", "cloud"],
    },

    [phraseKey("oblak", "a0-16")]: {
        sk: "Na nebi je oblak.",
        ua: "На небі хмара.",
        ru: "На небе облако.",
        en: "There is a cloud in the sky.",
        uaTokens: ["На", "небі", "хмара", "."],
        ruTokens: ["На", "небе", "облако", "."],
        enTokens: ["There", "is", "a", "cloud", "in", "the", "sky", "."],
        extraUaTokens: ["вітер", "сонце", "температура"],
        extraRuTokens: ["ветер", "солнце", "температура"],
        extraEnTokens: ["wind", "sun", "temperature"],
    },

    [phraseKey("teplo", "a0-16")]: {
        sk: "Dnes je teplo.",
        ua: "Сьогодні тепло.",
        ru: "Сегодня тепло.",
        en: "It is warm today.",
        uaTokens: ["Сьогодні", "тепло", "."],
        ruTokens: ["Сегодня", "тепло", "."],
        enTokens: ["It", "is", "warm", "today", "."],
        extraUaTokens: ["сонце", "погода", "дощ"],
        extraRuTokens: ["солнце", "погода", "дождь"],
        extraEnTokens: ["sun", "weather", "rain"],
    },

    [phraseKey("zima", "a0-16")]: {
        sk: "Dnes je zima.",
        ua: "Сьогодні холодно.",
        ru: "Сегодня холодно.",
        en: "It is cold today.",
        uaTokens: ["Сьогодні", "холодно", "."],
        ruTokens: ["Сегодня", "холодно", "."],
        enTokens: ["It", "is", "cold", "today", "."],
        extraUaTokens: ["сніг", "вітер", "сонце"],
        extraRuTokens: ["снег", "ветер", "солнце"],
        extraEnTokens: ["snow", "wind", "sun"],
    },

    [phraseKey("búrka", "a0-16")]: {
        sk: "Je búrka.",
        ua: "Буря.",
        ru: "Буря.",
        en: "There is a storm.",
        uaTokens: ["Буря", "."],
        ruTokens: ["Буря", "."],
        enTokens: ["There", "is", "a", "storm", "."],
        uaAltAnswers: [["Гроза", "."]],
        ruAltAnswers: [["Гроза", "."]],
        enAltAnswers: [["There", "is", "a", "thunderstorm", "."]],
        extraUaTokens: ["дощ", "вітер", "сніг"],
        extraRuTokens: ["дождь", "ветер", "снег"],
        extraEnTokens: ["rain", "wind", "snow"],
    },

    [phraseKey("teplota", "a0-16")]: {
        sk: "To je teplota.",
        ua: "Це температура.",
        ru: "Это температура.",
        en: "This is the temperature.",
        uaTokens: ["Це", "температура", "."],
        ruTokens: ["Это", "температура", "."],
        enTokens: ["This", "is", "the", "temperature", "."],
        extraUaTokens: ["погода", "дощ", "сонце"],
        extraRuTokens: ["погода", "дождь", "солнце"],
        extraEnTokens: ["weather", "rain", "sun"],
    },

    // =========================
    // LESSON 17 — Природа
    // =========================
    [phraseKey("príroda", "a0-17")]: {
        sk: "Mám rád prírodu.",
        ua: "Я люблю природу.",
        ru: "Я люблю природу.",
        en: "I love nature.",
        uaTokens: ["Я", "люблю", "природу", "."],
        ruTokens: ["Я", "люблю", "природу", "."],
        enTokens: ["I", "love", "nature", "."],
        extraUaTokens: ["дерево", "ліс", "річка"],
        extraRuTokens: ["дерево", "лес", "река"],
        extraEnTokens: ["tree", "forest", "river"],
    },

    [phraseKey("strom", "a0-17")]: {
        sk: "Tu je strom.",
        ua: "Тут дерево.",
        ru: "Здесь дерево.",
        en: "There is a tree here.",
        uaTokens: ["Тут", "дерево", "."],
        ruTokens: ["Здесь", "дерево", "."],
        enTokens: ["There", "is", "a", "tree", "here", "."],
        extraUaTokens: ["ліс", "гора", "зелена"],
        extraRuTokens: ["лес", "гора", "зелёная"],
        extraEnTokens: ["forest", "mountain", "green"],
    },

    [phraseKey("les", "a0-17")]: {
        sk: "Idem do lesa.",
        ua: "Я йду в ліс.",
        ru: "Я иду в лес.",
        en: "I am going to the forest.",
        uaTokens: ["Я", "йду", "в", "ліс", "."],
        ruTokens: ["Я", "иду", "в", "лес", "."],
        enTokens: ["I", "am", "going", "to", "the", "forest", "."],
        extraUaTokens: ["дерево", "річка", "висока"],
        extraRuTokens: ["дерево", "река", "высокая"],
        extraEnTokens: ["tree", "river", "high"],
    },

    [phraseKey("rieka", "a0-17")]: {
        sk: "Tu je rieka.",
        ua: "Тут річка.",
        ru: "Здесь река.",
        en: "There is a river here.",
        uaTokens: ["Тут", "річка", "."],
        ruTokens: ["Здесь", "река", "."],
        enTokens: ["There", "is", "a", "river", "here", "."],
        extraUaTokens: ["ліс", "озеро", "дерево"],
        extraRuTokens: ["лес", "озеро", "дерево"],
        extraEnTokens: ["forest", "lake", "tree"],
    },

    [phraseKey("jazero", "a0-17")]: {
        sk: "Tu je jazero.",
        ua: "Тут озеро.",
        ru: "Здесь озеро.",
        en: "There is a lake here.",
        uaTokens: ["Тут", "озеро", "."],
        ruTokens: ["Здесь", "озеро", "."],
        enTokens: ["There", "is", "a", "lake", "here", "."],
        extraUaTokens: ["річка", "гора", "квітка"],
        extraRuTokens: ["река", "гора", "цветок"],
        extraEnTokens: ["river", "mountain", "flower"],
    },

    [phraseKey("hora", "a0-17")]: {
        sk: "Tá hora je vysoká.",
        ua: "Та гора висока.",
        ru: "Та гора высокая.",
        en: "That mountain is high.",
        uaTokens: ["Та", "гора", "висока", "."],
        ruTokens: ["Та", "гора", "высокая", "."],
        enTokens: ["That", "mountain", "is", "high", "."],
        extraUaTokens: ["озеро", "ліс", "земля"],
        extraRuTokens: ["озеро", "лес", "земля"],
        extraEnTokens: ["lake", "forest", "earth"],
    },

    [phraseKey("kvet", "a0-17")]: {
        sk: "Toto je kvet.",
        ua: "Це квітка.",
        ru: "Это цветок.",
        en: "This is a flower.",
        uaTokens: ["Це", "квітка", "."],
        ruTokens: ["Это", "цветок", "."],
        enTokens: ["This", "is", "a", "flower", "."],
        extraUaTokens: ["трава", "зелена", "дерево"],
        extraRuTokens: ["трава", "зелёная", "дерево"],
        extraEnTokens: ["grass", "green", "tree"],
    },

    [phraseKey("tráva", "a0-17")]: {
        sk: "Tráva je zelená.",
        ua: "Трава зелена.",
        ru: "Трава зелёная.",
        en: "The grass is green.",
        uaTokens: ["Трава", "зелена", "."],
        ruTokens: ["Трава", "зелёная", "."],
        enTokens: ["The", "grass", "is", "green", "."],
        extraUaTokens: ["квітка", "дерево", "гора"],
        extraRuTokens: ["цветок", "дерево", "гора"],
        extraEnTokens: ["flower", "tree", "mountain"],
    },

    [phraseKey("zviera", "a0-17")]: {
        sk: "To zviera je tu.",
        ua: "Ця тварина тут.",
        ru: "Это животное здесь.",
        en: "This animal is here.",
        uaTokens: ["Ця", "тварина", "тут", "."],
        ruTokens: ["Это", "животное", "здесь", "."],
        enTokens: ["This", "animal", "is", "here", "."],
        extraUaTokens: ["природу", "трава", "земля"],
        extraRuTokens: ["природу", "трава", "земля"],
        extraEnTokens: ["nature", "grass", "earth"],
    },

    [phraseKey("zem", "a0-17")]: {
        sk: "Zem je veľká.",
        ua: "Земля велика.",
        ru: "Земля большая.",
        en: "The earth is big.",
        uaTokens: ["Земля", "велика", "."],
        ruTokens: ["Земля", "большая", "."],
        enTokens: ["The", "earth", "is", "big", "."],
        extraUaTokens: ["гора", "тварина", "природу"],
        extraRuTokens: ["гора", "животное", "природу"],
        extraEnTokens: ["mountain", "animal", "nature"],
    },

    // =========================
    // LESSON 18 — Побут
    // =========================
    [phraseKey("domácnosť", "a0-18")]: {
        sk: "Domácnosť je dôležitá.",
        ua: "Побут важливий.",
        ru: "Быт важен.",
        en: "Household life is important.",
        uaTokens: ["Побут", "важливий", "."],
        ruTokens: ["Быт", "важен", "."],
        enTokens: ["Household", "life", "is", "important", "."],
        extraUaTokens: ["дім", "квартира", "чиста"],
        extraRuTokens: ["дом", "квартира", "чистая"],
        extraEnTokens: ["house", "apartment", "clean"],
    },

    [phraseKey("dom", "a0-18")]: {
        sk: "Toto je dom.",
        ua: "Це дім.",
        ru: "Это дом.",
        en: "This is a house.",
        uaTokens: ["Це", "дім", "."],
        ruTokens: ["Это", "дом", "."],
        enTokens: ["This", "is", "a", "house", "."],
        extraUaTokens: ["квартира", "кімната", "важливий"],
        extraRuTokens: ["квартира", "комната", "важен"],
        extraEnTokens: ["apartment", "room", "important"],
    },

    [phraseKey("byt", "a0-18")]: {
        sk: "Mám byt.",
        ua: "У мене є квартира.",
        ru: "У меня есть квартира.",
        en: "I have an apartment.",
        uaTokens: ["У", "мене", "є", "квартира", "."],
        ruTokens: ["У", "меня", "есть", "квартира", "."],
        enTokens: ["I", "have", "an", "apartment", "."],
        extraUaTokens: ["дім", "кімната", "ліжко"],
        extraRuTokens: ["дом", "комната", "кровать"],
        extraEnTokens: ["house", "room", "bed"],
    },

    [phraseKey("izba", "a0-18")]: {
        sk: "Toto je izba.",
        ua: "Це кімната.",
        ru: "Это комната.",
        en: "This is a room.",
        uaTokens: ["Це", "кімната", "."],
        ruTokens: ["Это", "комната", "."],
        enTokens: ["This", "is", "a", "room", "."],
        extraUaTokens: ["квартира", "стіл", "стілець"],
        extraRuTokens: ["квартира", "стол", "стул"],
        extraEnTokens: ["apartment", "table", "chair"],
    },

    [phraseKey("posteľ", "a0-18")]: {
        sk: "Tu je posteľ.",
        ua: "Тут ліжко.",
        ru: "Здесь кровать.",
        en: "There is a bed here.",
        uaTokens: ["Тут", "ліжко", "."],
        ruTokens: ["Здесь", "кровать", "."],
        enTokens: ["There", "is", "a", "bed", "here", "."],
        extraUaTokens: ["кімната", "стіл", "чиста"],
        extraRuTokens: ["комната", "стол", "чистая"],
        extraEnTokens: ["room", "table", "clean"],
    },

    [phraseKey("stôl", "a0-18")]: {
        sk: "Stôl je veľký.",
        ua: "Стіл великий.",
        ru: "Стол большой.",
        en: "The table is big.",
        uaTokens: ["Стіл", "великий", "."],
        ruTokens: ["Стол", "большой", "."],
        enTokens: ["The", "table", "is", "big", "."],
        extraUaTokens: ["ліжко", "стілець", "кімната"],
        extraRuTokens: ["кровать", "стул", "комната"],
        extraEnTokens: ["bed", "chair", "room"],
    },

    [phraseKey("stolička", "a0-18")]: {
        sk: "Stolička je tu.",
        ua: "Стілець тут.",
        ru: "Стул здесь.",
        en: "The chair is here.",
        uaTokens: ["Стілець", "тут", "."],
        ruTokens: ["Стул", "здесь", "."],
        enTokens: ["The", "chair", "is", "here", "."],
        extraUaTokens: ["стіл", "кухня", "квартира"],
        extraRuTokens: ["стол", "кухня", "квартира"],
        extraEnTokens: ["table", "kitchen", "apartment"],
    },

    [phraseKey("kuchyňa", "a0-18")]: {
        sk: "Kuchyňa je čistá.",
        ua: "Кухня чиста.",
        ru: "Кухня чистая.",
        en: "The kitchen is clean.",
        uaTokens: ["Кухня", "чиста", "."],
        ruTokens: ["Кухня", "чистая", "."],
        enTokens: ["The", "kitchen", "is", "clean", "."],
        extraUaTokens: ["холодильник", "повний", "стіл"],
        extraRuTokens: ["холодильник", "полный", "стол"],
        extraEnTokens: ["fridge", "full", "table"],
    },

    [phraseKey("chladnička", "a0-18")]: {
        sk: "Chladnička je plná.",
        ua: "Холодильник повний.",
        ru: "Холодильник полный.",
        en: "The fridge is full.",
        uaTokens: ["Холодильник", "повний", "."],
        ruTokens: ["Холодильник", "полный", "."],
        enTokens: ["The", "fridge", "is", "full", "."],
        extraUaTokens: ["кухня", "чиста", "прибирати"],
        extraRuTokens: ["кухня", "чистая", "убирать"],
        extraEnTokens: ["kitchen", "clean", "cleaning"],
    },

    [phraseKey("upratovať", "a0-18")]: {
        sk: "Idem upratovať.",
        ua: "Я йду прибирати.",
        ru: "Я иду убирать.",
        en: "I am going to clean.",
        uaTokens: ["Я", "йду", "прибирати", "."],
        ruTokens: ["Я", "иду", "убирать", "."],
        enTokens: ["I", "am", "going", "to", "clean", "."],
        extraUaTokens: ["кухня", "кімната", "чиста"],
        extraRuTokens: ["кухня", "комната", "чистая"],
        extraEnTokens: ["kitchen", "room", "clean"],
    },

    // =========================
    // LESSON 19 — Дії та дієслова
    // =========================
    [phraseKey("robiť", "a0-19")]: {
        sk: "Čo robíš?",
        ua: "Що ти робиш?",
        ru: "Что ты делаешь?",
        en: "What are you doing?",
        uaTokens: ["Що", "ти", "робиш", "?"],
        ruTokens: ["Что", "ты", "делаешь", "?"],
        enTokens: ["What", "are", "you", "doing", "?"],
        extraUaTokens: ["йду", "бачу", "сьогодні"],
        extraRuTokens: ["иду", "вижу", "сегодня"],
        extraEnTokens: ["go", "see", "today"],
    },

    [phraseKey("ísť", "a0-19")]: {
        sk: "Idem domov.",
        ua: "Я йду додому.",
        ru: "Я иду домой.",
        en: "I am going home.",
        uaTokens: ["Я", "йду", "додому", "."],
        ruTokens: ["Я", "иду", "домой", "."],
        enTokens: ["I", "am", "going", "home", "."],
        extraUaTokens: ["робиш", "завтра", "бачу"],
        extraRuTokens: ["делаешь", "завтра", "вижу"],
        extraEnTokens: ["doing", "tomorrow", "see"],
    },

    [phraseKey("prísť", "a0-19")]: {
        sk: "Prídem zajtra.",
        ua: "Я прийду завтра.",
        ru: "Я приду завтра.",
        en: "I will come tomorrow.",
        uaTokens: ["Я", "прийду", "завтра", "."],
        ruTokens: ["Я", "приду", "завтра", "."],
        enTokens: ["I", "will", "come", "tomorrow", "."],
        extraUaTokens: ["додому", "бачу", "воду"],
        extraRuTokens: ["домой", "вижу", "воду"],
        extraEnTokens: ["home", "see", "water"],
    },

    [phraseKey("vidieť", "a0-19")]: {
        sk: "Vidím ťa.",
        ua: "Я бачу тебе.",
        ru: "Я вижу тебя.",
        en: "I see you.",
        uaTokens: ["Я", "бачу", "тебе", "."],
        ruTokens: ["Я", "вижу", "тебя", "."],
        enTokens: ["I", "see", "you", "."],
        extraUaTokens: ["завтра", "йду", "говорю"],
        extraRuTokens: ["завтра", "иду", "говорю"],
        extraEnTokens: ["tomorrow", "go", "speak"],
    },

    [phraseKey("hovoriť", "a0-19")]: {
        sk: "Hovorím po slovensky.",
        ua: "Я говорю словацькою.",
        ru: "Я говорю по-словацки.",
        en: "I speak Slovak.",
        uaTokens: ["Я", "говорю", "словацькою", "."],
        ruTokens: ["Я", "говорю", "по-словацки", "."],
        enTokens: ["I", "speak", "Slovak", "."],
        extraUaTokens: ["бачу", "воду", "вчуся"],
        extraRuTokens: ["вижу", "воду", "учусь"],
        extraEnTokens: ["see", "water", "study"],
    },

    [phraseKey("jesť", "a0-19")]: {
        sk: "Jem obed.",
        ua: "Я їм обід.",
        ru: "Я ем обед.",
        en: "I am eating lunch.",
        uaTokens: ["Я", "їм", "обід", "."],
        ruTokens: ["Я", "ем", "обед", "."],
        enTokens: ["I", "am", "eating", "lunch", "."],
        extraUaTokens: ["п’ю", "воду", "сьогодні"],
        extraRuTokens: ["пью", "воду", "сегодня"],
        extraEnTokens: ["drink", "water", "today"],
    },

    [phraseKey("piť", "a0-19")]: {
        sk: "Pijem vodu.",
        ua: "Я п’ю воду.",
        ru: "Я пью воду.",
        en: "I am drinking water.",
        uaTokens: ["Я", "п’ю", "воду", "."],
        ruTokens: ["Я", "пью", "воду", "."],
        enTokens: ["I", "am", "drinking", "water", "."],
        extraUaTokens: ["обід", "вночі", "сьогодні"],
        extraRuTokens: ["обед", "ночью", "сегодня"],
        extraEnTokens: ["lunch", "night", "today"],
    },

    [phraseKey("spať", "a0-19")]: {
        sk: "Spím v noci.",
        ua: "Я сплю вночі.",
        ru: "Я сплю ночью.",
        en: "I sleep at night.",
        uaTokens: ["Я", "сплю", "вночі", "."],
        ruTokens: ["Я", "сплю", "ночью", "."],
        enTokens: ["I", "sleep", "at", "night", "."],
        extraUaTokens: ["п’ю", "воду", "завтра"],
        extraRuTokens: ["пью", "воду", "завтра"],
        extraEnTokens: ["drink", "water", "tomorrow"],
    },

    [phraseKey("pracovať", "a0-19")]: {
        sk: "Pracujem dnes.",
        ua: "Я працюю сьогодні.",
        ru: "Я работаю сегодня.",
        en: "I am working today.",
        uaTokens: ["Я", "працюю", "сьогодні", "."],
        ruTokens: ["Я", "работаю", "сегодня", "."],
        enTokens: ["I", "am", "working", "today", "."],
        extraUaTokens: ["йду", "додому", "вчуся"],
        extraRuTokens: ["иду", "домой", "учусь"],
        extraEnTokens: ["go", "home", "study"],
    },

    [phraseKey("učiť sa", "a0-19")]: {
        sk: "Učím sa po slovensky.",
        ua: "Я вчуся словацькою.",
        ru: "Я учусь словацкому.",
        en: "I am learning Slovak.",
        uaTokens: ["Я", "вчуся", "словацькою", "."],
        ruTokens: ["Я", "учусь", "словацкому", "."],
        enTokens: ["I", "am", "learning", "Slovak", "."],
        extraUaTokens: ["говорю", "сьогодні", "бачу"],
        extraRuTokens: ["говорю", "сегодня", "вижу"],
        extraEnTokens: ["speak", "today", "see"],
    },

    // =========================
    // LESSON 20 — Питання і відповіді
    // =========================
    [phraseKey("kto", "a0-20")]: {
        sk: "Kto je to?",
        ua: "Хто це?",
        ru: "Кто это?",
        en: "Who is this?",
        uaTokens: ["Хто", "це", "?"],
        ruTokens: ["Кто", "это", "?"],
        enTokens: ["Who", "is", "this", "?"],
        extraUaTokens: ["що", "де", "ти"],
        extraRuTokens: ["что", "где", "ты"],
        extraEnTokens: ["what", "where", "you"],
    },

    [phraseKey("čo", "a0-20")]: {
        sk: "Čo je to?",
        ua: "Що це?",
        ru: "Что это?",
        en: "What is this?",
        uaTokens: ["Що", "це", "?"],
        ruTokens: ["Что", "это", "?"],
        enTokens: ["What", "is", "this", "?"],
        extraUaTokens: ["хто", "де", "коли"],
        extraRuTokens: ["кто", "где", "когда"],
        extraEnTokens: ["who", "where", "when"],
    },

    [phraseKey("kde", "a0-20")]: {
        sk: "Kde si?",
        ua: "Де ти?",
        ru: "Где ты?",
        en: "Where are you?",
        uaTokens: ["Де", "ти", "?"],
        ruTokens: ["Где", "ты", "?"],
        enTokens: ["Where", "are", "you", "?"],
        extraUaTokens: ["хто", "що", "тут"],
        extraRuTokens: ["кто", "что", "здесь"],
        extraEnTokens: ["who", "what", "here"],
    },

    [phraseKey("kedy", "a0-20")]: {
        sk: "Kedy prídeš?",
        ua: "Коли ти прийдеш?",
        ru: "Когда ты придёшь?",
        en: "When will you come?",
        uaTokens: ["Коли", "ти", "прийдеш", "?"],
        ruTokens: ["Когда", "ты", "придёшь", "?"],
        enTokens: ["When", "will", "you", "come", "?"],
        extraUaTokens: ["де", "завтра", "можливо"],
        extraRuTokens: ["где", "завтра", "возможно"],
        extraEnTokens: ["where", "tomorrow", "maybe"],
    },

    [phraseKey("prečo", "a0-20")]: {
        sk: "Prečo si tu?",
        ua: "Чому ти тут?",
        ru: "Почему ты здесь?",
        en: "Why are you here?",
        uaTokens: ["Чому", "ти", "тут", "?"],
        ruTokens: ["Почему", "ты", "здесь", "?"],
        enTokens: ["Why", "are", "you", "here", "?"],
        extraUaTokens: ["де", "хто", "можливо"],
        extraRuTokens: ["где", "кто", "возможно"],
        extraEnTokens: ["where", "who", "maybe"],
    },

    [phraseKey("ako", "a0-20")]: {
        sk: "Ako sa máš?",
        ua: "Як ти?",
        ru: "Как ты?",
        en: "How are you?",
        uaTokens: ["Як", "ти", "?"],
        ruTokens: ["Как", "ты", "?"],
        enTokens: ["How", "are", "you", "?"],
        extraUaTokens: ["дякую", "так", "ні"],
        extraRuTokens: ["спасибо", "да", "нет"],
        extraEnTokens: ["thanks", "yes", "no"],
    },

    [phraseKey("koľko", "a0-20")]: {
        sk: "Koľko to stojí?",
        ua: "Скільки це коштує?",
        ru: "Сколько это стоит?",
        en: "How much does it cost?",
        uaTokens: ["Скільки", "це", "коштує", "?"],
        ruTokens: ["Сколько", "это", "стоит", "?"],
        enTokens: ["How", "much", "does", "it", "cost", "?"],
        extraUaTokens: ["можливо", "завтра", "так"],
        extraRuTokens: ["возможно", "завтра", "да"],
        extraEnTokens: ["maybe", "tomorrow", "yes"],
    },

    [phraseKey("áno", "a0-20")]: {
        sk: "Áno, ďakujem.",
        ua: "Так, дякую.",
        ru: "Да, спасибо.",
        en: "Yes, thank you.",
        uaTokens: ["Так", ",", "дякую", "."],
        ruTokens: ["Да", ",", "спасибо", "."],
        enTokens: ["Yes", ",", "thank", "you", "."],
        extraUaTokens: ["ні", "можливо", "ти"],
        extraRuTokens: ["нет", "возможно", "ты"],
        extraEnTokens: ["no", "maybe", "you"],
    },

    [phraseKey("nie", "a0-20")]: {
        sk: "Nie, ďakujem.",
        ua: "Ні, дякую.",
        ru: "Нет, спасибо.",
        en: "No, thank you.",
        uaTokens: ["Ні", ",", "дякую", "."],
        ruTokens: ["Нет", ",", "спасибо", "."],
        enTokens: ["No", ",", "thank", "you", "."],
        extraUaTokens: ["так", "можливо", "хто"],
        extraRuTokens: ["да", "возможно", "кто"],
        extraEnTokens: ["yes", "maybe", "who"],
    },

    [phraseKey("možno", "a0-20")]: {
        sk: "Možno zajtra.",
        ua: "Можливо завтра.",
        ru: "Возможно завтра.",
        en: "Maybe tomorrow.",
        uaTokens: ["Можливо", "завтра", "."],
        ruTokens: ["Возможно", "завтра", "."],
        enTokens: ["Maybe", "tomorrow", "."],
        extraUaTokens: ["так", "ні", "коли"],
        extraRuTokens: ["да", "нет", "когда"],
        extraEnTokens: ["yes", "no", "when"],
    },
};