import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A0_BUILD_UA_SENTENCES_6: BuildUaSentenceDict = {
    // =========================
    // LESSON 26 — Hotel a reštaurácia
    // =========================
    [phraseKey("hotel", "a0-26")]: {
        sk: "Hotel je v centre.",
        ua: "Готель у центрі.",
        ru: "Отель в центре.",
        en: "The hotel is in the center.",
        uaTokens: ["Готель", "у", "центрі", "."],
        ruTokens: ["Отель", "в", "центре", "."],
        enTokens: ["The", "hotel", "is", "in", "the", "center", "."],
        extraUaTokens: ["кімната", "ресепшн", "меню"],
        extraRuTokens: ["комната", "ресепшн", "меню"],
        extraEnTokens: ["room", "reception", "menu"],
    },
    [phraseKey("izba", "a0-26")]: {
        sk: "Izba je čistá.",
        ua: "Кімната чиста.",
        ru: "Комната чистая.",
        en: "The room is clean.",
        uaTokens: ["Кімната", "чиста", "."],
        ruTokens: ["Комната", "чистая", "."],
        enTokens: ["The", "room", "is", "clean", "."],
        extraUaTokens: ["готель", "відкрита", "меню"],
        extraRuTokens: ["отель", "открыт", "меню"],
        extraEnTokens: ["hotel", "open", "menu"],
    },
    [phraseKey("recepcia", "a0-26")]: {
        sk: "Idem na recepciu.",
        ua: "Я йду на ресепшн.",
        ru: "Я иду на ресепшн.",
        en: "I am going to the reception.",
        uaTokens: ["Я", "йду", "на", "ресепшн", "."],
        ruTokens: ["Я", "иду", "на", "ресепшн", "."],
        enTokens: ["I", "am", "going", "to", "the", "reception", "."],
        extraUaTokens: ["готель", "кімната", "меню"],
        extraRuTokens: ["отель", "комната", "меню"],
        extraEnTokens: ["hotel", "room", "menu"],
    },
    [phraseKey("reštaurácia", "a0-26")]: {
        sk: "Reštaurácia je otvorená.",
        ua: "Ресторан відкритий.",
        ru: "Ресторан открыт.",
        en: "The restaurant is open.",
        uaTokens: ["Ресторан", "відкритий", "."],
        ruTokens: ["Ресторан", "открыт", "."],
        enTokens: ["The", "restaurant", "is", "open", "."],
        extraUaTokens: ["меню", "суп", "рахунок"],
        extraRuTokens: ["меню", "суп", "счёт"],
        extraEnTokens: ["menu", "soup", "bill"],
    },
    [phraseKey("menu", "a0-26")]: {
        sk: "Prosím si menu.",
        ua: "Будь ласка, меню.",
        ru: "Пожалуйста, меню.",
        en: "Menu, please.",
        uaTokens: ["Будь", "ласка", ",", "меню", "."],
        ruTokens: ["Пожалуйста", ",", "меню", "."],
        enTokens: ["Menu", ",", "please", "."],
        extraUaTokens: ["ресторан", "обід", "вечеря"],
        extraRuTokens: ["ресторан", "обед", "ужин"],
        extraEnTokens: ["restaurant", "lunch", "dinner"],
    },
    [phraseKey("objednať", "a0-26")]: {
        sk: "Chcem si objednať polievku.",
        ua: "Я хочу замовити суп.",
        ru: "Я хочу заказать суп.",
        en: "I want to order soup.",
        uaTokens: ["Я", "хочу", "замовити", "суп", "."],
        ruTokens: ["Я", "хочу", "заказать", "суп", "."],
        enTokens: ["I", "want", "to", "order", "soup", "."],
        extraUaTokens: ["меню", "обід", "рахунок"],
        extraRuTokens: ["меню", "обед", "счёт"],
        extraEnTokens: ["menu", "lunch", "bill"],
    },
    [phraseKey("raňajky", "a0-26")]: {
        sk: "Raňajky sú o siedmej.",
        ua: "Сніданок о сьомій.",
        ru: "Завтрак в семь.",
        en: "Breakfast is at seven.",
        uaTokens: ["Сніданок", "о", "сьомій", "."],
        ruTokens: ["Завтрак", "в", "семь", "."],
        enTokens: ["Breakfast", "is", "at", "seven", "."],
        extraUaTokens: ["обід", "вечеря", "меню"],
        extraRuTokens: ["обед", "ужин", "меню"],
        extraEnTokens: ["lunch", "dinner", "menu"],
    },
    [phraseKey("obed", "a0-26")]: {
        sk: "Dám si obed.",
        ua: "Я візьму обід.",
        ru: "Я возьму обед.",
        en: "I will have lunch.",
        uaTokens: ["Я", "візьму", "обід", "."],
        ruTokens: ["Я", "возьму", "обед", "."],
        enTokens: ["I", "will", "have", "lunch", "."],
        extraUaTokens: ["сніданок", "вечеря", "суп"],
        extraRuTokens: ["завтрак", "ужин", "суп"],
        extraEnTokens: ["breakfast", "dinner", "soup"],
    },
    [phraseKey("večera", "a0-26")]: {
        sk: "Večera je chutná.",
        ua: "Вечеря смачна.",
        ru: "Ужин вкусный.",
        en: "Dinner is tasty.",
        uaTokens: ["Вечеря", "смачна", "."],
        ruTokens: ["Ужин", "вкусный", "."],
        enTokens: ["Dinner", "is", "tasty", "."],
        extraUaTokens: ["обід", "меню", "суп"],
        extraRuTokens: ["обед", "меню", "суп"],
        extraEnTokens: ["lunch", "menu", "soup"],
    },
    [phraseKey("účet", "a0-26")]: {
        sk: "Prosím, účet.",
        ua: "Рахунок, будь ласка.",
        ru: "Счёт, пожалуйста.",
        en: "The bill, please.",
        uaTokens: ["Рахунок", ",", "будь", "ласка", "."],
        ruTokens: ["Счёт", ",", "пожалуйста", "."],
        enTokens: ["The", "bill", ",", "please", "."],
        extraUaTokens: ["меню", "вечеря", "обід"],
        extraRuTokens: ["меню", "ужин", "обед"],
        extraEnTokens: ["menu", "dinner", "lunch"],
    },

    // =========================
    // LESSON 27 — Hroši
    // =========================
    [phraseKey("peniaze", "a0-27")]: {
        sk: "Nemám teraz peniaze.",
        ua: "Я зараз не маю грошей.",
        ru: "У меня сейчас нет денег.",
        en: "I do not have money now.",
        uaTokens: ["Я", "зараз", "не", "маю", "грошей", "."],
        ruTokens: ["У", "меня", "сейчас", "нет", "денег", "."],
        enTokens: ["I", "do", "not", "have", "money", "now", "."],
        extraUaTokens: ["ціна", "банк", "картка"],
        extraRuTokens: ["цена", "банк", "карта"],
        extraEnTokens: ["price", "bank", "card"],
    },
    [phraseKey("euro", "a0-27")]: {
        sk: "Je to desať eur.",
        ua: "Це десять євро.",
        ru: "Это десять евро.",
        en: "It is ten euros.",
        uaTokens: ["Це", "десять", "євро", "."],
        ruTokens: ["Это", "десять", "евро", "."],
        enTokens: ["It", "is", "ten", "euros", "."],
        extraUaTokens: ["грошей", "ціна", "знижка"],
        extraRuTokens: ["денег", "цена", "скидка"],
        extraEnTokens: ["money", "price", "discount"],
    },
    [phraseKey("cena", "a0-27")]: {
        sk: "Aká je cena?",
        ua: "Яка ціна?",
        ru: "Какая цена?",
        en: "What is the price?",
        uaTokens: ["Яка", "ціна", "?"],
        ruTokens: ["Какая", "цена", "?"],
        enTokens: ["What", "is", "the", "price", "?"],
        extraUaTokens: ["євро", "знижка", "витрати"],
        extraRuTokens: ["евро", "скидка", "расходы"],
        extraEnTokens: ["euro", "discount", "expenses"],
    },
    [phraseKey("platba", "a0-27")]: {
        sk: "Platba je úspešná.",
        ua: "Платіж успішний.",
        ru: "Платёж успешный.",
        en: "The payment is successful.",
        uaTokens: ["Платіж", "успішний", "."],
        ruTokens: ["Платёж", "успешный", "."],
        enTokens: ["The", "payment", "is", "successful", "."],
        extraUaTokens: ["картка", "готівкою", "банк"],
        extraRuTokens: ["карта", "наличными", "банк"],
        extraEnTokens: ["card", "cash", "bank"],
    },
    [phraseKey("hotovosť", "a0-27")]: {
        sk: "Platím v hotovosti.",
        ua: "Я плачу готівкою.",
        ru: "Я плачу наличными.",
        en: "I pay in cash.",
        uaTokens: ["Я", "плачу", "готівкою", "."],
        ruTokens: ["Я", "плачу", "наличными", "."],
        enTokens: ["I", "pay", "in", "cash", "."],
        extraUaTokens: ["картка", "банк", "ціна"],
        extraRuTokens: ["карта", "банк", "цена"],
        extraEnTokens: ["card", "bank", "price"],
    },
    [phraseKey("karta", "a0-27")]: {
        sk: "Platím kartou.",
        ua: "Я плачу карткою.",
        ru: "Я плачу картой.",
        en: "I pay by card.",
        uaTokens: ["Я", "плачу", "карткою", "."],
        ruTokens: ["Я", "плачу", "картой", "."],
        enTokens: ["I", "pay", "by", "card", "."],
        extraUaTokens: ["готівкою", "платіж", "банк"],
        extraRuTokens: ["наличными", "платёж", "банк"],
        extraEnTokens: ["cash", "payment", "bank"],
    },
    [phraseKey("účet", "a0-27")]: {
        sk: "Účet je vysoký.",
        ua: "Рахунок великий.",
        ru: "Счёт большой.",
        en: "The bill is high.",
        uaTokens: ["Рахунок", "великий", "."],
        ruTokens: ["Счёт", "большой", "."],
        enTokens: ["The", "bill", "is", "high", "."],
        extraUaTokens: ["ціна", "витрати", "грошей"],
        extraRuTokens: ["цена", "расходы", "денег"],
        extraEnTokens: ["price", "expenses", "money"],
    },
    [phraseKey("banka", "a0-27")]: {
        sk: "Banka je blízko.",
        ua: "Банк близько.",
        ru: "Банк близко.",
        en: "The bank is nearby.",
        uaTokens: ["Банк", "близько", "."],
        ruTokens: ["Банк", "близко", "."],
        enTokens: ["The", "bank", "is", "nearby", "."],
        extraUaTokens: ["грошей", "картка", "платіж"],
        extraRuTokens: ["денег", "карта", "платёж"],
        extraEnTokens: ["money", "card", "payment"],
    },
    [phraseKey("zľava", "a0-27")]: {
        sk: "Dnes je zľava.",
        ua: "Сьогодні знижка.",
        ru: "Сегодня скидка.",
        en: "There is a discount today.",
        uaTokens: ["Сьогодні", "знижка", "."],
        ruTokens: ["Сегодня", "скидка", "."],
        enTokens: ["There", "is", "a", "discount", "today", "."],
        extraUaTokens: ["ціна", "євро", "витрати"],
        extraRuTokens: ["цена", "евро", "расходы"],
        extraEnTokens: ["price", "euro", "expenses"],
    },
    [phraseKey("výdavky", "a0-27")]: {
        sk: "Moje výdavky sú veľké.",
        ua: "Мої витрати великі.",
        ru: "Мои расходы большие.",
        en: "My expenses are big.",
        uaTokens: ["Мої", "витрати", "великі", "."],
        ruTokens: ["Мои", "расходы", "большие", "."],
        enTokens: ["My", "expenses", "are", "big", "."],
        extraUaTokens: ["грошей", "знижка", "ціна"],
        extraRuTokens: ["денег", "скидка", "цена"],
        extraEnTokens: ["money", "discount", "price"],
    },

    // =========================
    // LESSON 28 — Technológie
    // =========================
    [phraseKey("technológia", "a0-28")]: {
        sk: "Technológia sa rýchlo mení.",
        ua: "Технології швидко змінюються.",
        ru: "Технологии быстро меняются.",
        en: "Technology changes quickly.",
        uaTokens: ["Технології", "швидко", "змінюються", "."],
        ruTokens: ["Технологии", "быстро", "меняются", "."],
        enTokens: ["Technology", "changes", "quickly", "."],
        extraUaTokens: ["комп’ютер", "інтернет", "дані"],
        extraRuTokens: ["компьютер", "интернет", "данные"],
        extraEnTokens: ["computer", "internet", "data"],
    },
    [phraseKey("počítač", "a0-28")]: {
        sk: "Mám nový počítač.",
        ua: "У мене новий комп’ютер.",
        ru: "У меня новый компьютер.",
        en: "I have a new computer.",
        uaTokens: ["У", "мене", "новий", "комп’ютер", "."],
        ruTokens: ["У", "меня", "новый", "компьютер", "."],
        enTokens: ["I", "have", "a", "new", "computer", "."],
        extraUaTokens: ["телефон", "система", "пароль"],
        extraRuTokens: ["телефон", "система", "пароль"],
        extraEnTokens: ["phone", "system", "password"],
    },
    [phraseKey("telefón", "a0-28")]: {
        sk: "Telefón je na stole.",
        ua: "Телефон на столі.",
        ru: "Телефон на столе.",
        en: "The phone is on the table.",
        uaTokens: ["Телефон", "на", "столі", "."],
        ruTokens: ["Телефон", "на", "столе", "."],
        enTokens: ["The", "phone", "is", "on", "the", "table", "."],
        extraUaTokens: ["комп’ютер", "додаток", "пароль"],
        extraRuTokens: ["компьютер", "приложение", "пароль"],
        extraEnTokens: ["computer", "app", "password"],
    },
    [phraseKey("internet", "a0-28")]: {
        sk: "Nemám internet.",
        ua: "У мене немає інтернету.",
        ru: "У меня нет интернета.",
        en: "I do not have internet.",
        uaTokens: ["У", "мене", "немає", "інтернету", "."],
        ruTokens: ["У", "меня", "нет", "интернета", "."],
        enTokens: ["I", "do", "not", "have", "internet", "."],
        extraUaTokens: ["мережа", "дані", "система"],
        extraRuTokens: ["сеть", "данные", "система"],
        extraEnTokens: ["network", "data", "system"],
    },
    [phraseKey("aplikácia", "a0-28")]: {
        sk: "Používam túto aplikáciu.",
        ua: "Я використовую цей додаток.",
        ru: "Я использую это приложение.",
        en: "I use this app.",
        uaTokens: ["Я", "використовую", "цей", "додаток", "."],
        ruTokens: ["Я", "использую", "это", "приложение", "."],
        enTokens: ["I", "use", "this", "app", "."],
        extraUaTokens: ["телефон", "програма", "система"],
        extraRuTokens: ["телефон", "программа", "система"],
        extraEnTokens: ["phone", "program", "system"],
    },
    [phraseKey("program", "a0-28")]: {
        sk: "Program nefunguje.",
        ua: "Програма не працює.",
        ru: "Программа не работает.",
        en: "The program does not work.",
        uaTokens: ["Програма", "не", "працює", "."],
        ruTokens: ["Программа", "не", "работает", "."],
        enTokens: ["The", "program", "does", "not", "work", "."],
        extraUaTokens: ["додаток", "система", "пароль"],
        extraRuTokens: ["приложение", "система", "пароль"],
        extraEnTokens: ["app", "system", "password"],
    },
    [phraseKey("systém", "a0-28")]: {
        sk: "Systém je rýchly.",
        ua: "Система швидка.",
        ru: "Система быстрая.",
        en: "The system is fast.",
        uaTokens: ["Система", "швидка", "."],
        ruTokens: ["Система", "быстрая", "."],
        enTokens: ["The", "system", "is", "fast", "."],
        extraUaTokens: ["програма", "мережа", "дані"],
        extraRuTokens: ["программа", "сеть", "данные"],
        extraEnTokens: ["program", "network", "data"],
    },
    [phraseKey("sieť", "a0-28")]: {
        sk: "Sieť je slabá.",
        ua: "Мережа слабка.",
        ru: "Сеть слабая.",
        en: "The network is weak.",
        uaTokens: ["Мережа", "слабка", "."],
        ruTokens: ["Сеть", "слабая", "."],
        enTokens: ["The", "network", "is", "weak", "."],
        extraUaTokens: ["інтернет", "система", "дані"],
        extraRuTokens: ["интернет", "система", "данные"],
        extraEnTokens: ["internet", "system", "data"],
    },
    [phraseKey("dáta", "a0-28")]: {
        sk: "Ukladám dáta.",
        ua: "Я зберігаю дані.",
        ru: "Я сохраняю данные.",
        en: "I save data.",
        uaTokens: ["Я", "зберігаю", "дані", "."],
        ruTokens: ["Я", "сохраняю", "данные", "."],
        enTokens: ["I", "save", "data", "."],
        extraUaTokens: ["мережа", "пароль", "система"],
        extraRuTokens: ["сеть", "пароль", "система"],
        extraEnTokens: ["network", "password", "system"],
    },
    [phraseKey("heslo", "a0-28")]: {
        sk: "Zabudol som heslo.",
        ua: "Я забув пароль.",
        ru: "Я забыл пароль.",
        en: "I forgot the password.",
        uaTokens: ["Я", "забув", "пароль", "."],
        ruTokens: ["Я", "забыл", "пароль", "."],
        enTokens: ["I", "forgot", "the", "password", "."],
        extraUaTokens: ["комп’ютер", "дані", "інтернет"],
        extraRuTokens: ["компьютер", "данные", "интернет"],
        extraEnTokens: ["computer", "data", "internet"],
    },

    // =========================
    // LESSON 29 — Každodenné frázy
    // =========================
    [phraseKey("dobrý deň", "a0-29")]: {
        sk: "Dobrý deň, ako sa máte?",
        ua: "Добрий день, як ви?",
        ru: "Добрый день, как вы?",
        en: "Good afternoon, how are you?",
        uaTokens: ["Добрий", "день", ",", "як", "ви", "?"],
        ruTokens: ["Добрый", "день", ",", "как", "вы", "?"],
        enTokens: ["Good", "afternoon", ",", "how", "are", "you", "?"],
        extraUaTokens: ["привіт", "дякую", "вибач"],
        extraRuTokens: ["привет", "спасибо", "извини"],
        extraEnTokens: ["hello", "thank-you", "sorry"],
    },
    [phraseKey("ahoj", "a0-29")]: {
        sk: "Ahoj, čo robíš?",
        ua: "Привіт, що ти робиш?",
        ru: "Привет, что ты делаешь?",
        en: "Hi, what are you doing?",
        uaTokens: ["Привіт", ",", "що", "ти", "робиш", "?"],
        ruTokens: ["Привет", ",", "что", "ты", "делаешь", "?"],
        enTokens: ["Hi", ",", "what", "are", "you", "doing", "?"],
        extraUaTokens: ["дякую", "добре", "ясно"],
        extraRuTokens: ["спасибо", "хорошо", "ясно"],
        extraEnTokens: ["thank-you", "good", "clear"],
    },
    [phraseKey("ďakujem", "a0-29")]: {
        sk: "Ďakujem za pomoc.",
        ua: "Дякую за допомогу.",
        ru: "Спасибо за помощь.",
        en: "Thank you for the help.",
        uaTokens: ["Дякую", "за", "допомогу", "."],
        ruTokens: ["Спасибо", "за", "помощь", "."],
        enTokens: ["Thank", "you", "for", "the", "help", "."],
        extraUaTokens: ["будь", "ласка", "вибач"],
        extraRuTokens: ["пожалуйста", "извини", "помощь"],
        extraEnTokens: ["please", "sorry", "help"],
    },
    [phraseKey("prosím", "a0-29")]: {
        sk: "Prosím, sadnite si.",
        ua: "Будь ласка, сідайте.",
        ru: "Пожалуйста, садитесь.",
        en: "Please, sit down.",
        uaTokens: ["Будь", "ласка", ",", "сідайте", "."],
        ruTokens: ["Пожалуйста", ",", "садитесь", "."],
        enTokens: ["Please", ",", "sit", "down", "."],
        extraUaTokens: ["дякую", "добрий", "день"],
        extraRuTokens: ["спасибо", "добрый", "день"],
        extraEnTokens: ["thank-you", "good", "day"],
    },
    [phraseKey("prepáč", "a0-29")]: {
        sk: "Prepáč, meškám.",
        ua: "Вибач, я запізнився.",
        ru: "Извини, я опоздал.",
        en: "Sorry, I am late.",
        uaTokens: ["Вибач", ",", "я", "запізнився", "."],
        ruTokens: ["Извини", ",", "я", "опоздал", "."],
        enTokens: ["Sorry", ",", "I", "am", "late", "."],
        extraUaTokens: ["дякую", "допомогу", "ясно"],
        extraRuTokens: ["спасибо", "помощь", "ясно"],
        extraEnTokens: ["thank-you", "help", "clear"],
    },
    [phraseKey("rozumiem", "a0-29")]: {
        sk: "Rozumiem všetko.",
        ua: "Я все розумію.",
        ru: "Я всё понимаю.",
        en: "I understand everything.",
        uaTokens: ["Я", "все", "розумію", "."],
        ruTokens: ["Я", "всё", "понимаю", "."],
        enTokens: ["I", "understand", "everything", "."],
        extraUaTokens: ["питання", "вибач", "добре"],
        extraRuTokens: ["вопрос", "извини", "хорошо"],
        extraEnTokens: ["question", "sorry", "good"],
    },
    [phraseKey("nerozumiem", "a0-29")]: {
        sk: "Nerozumiem tej otázke.",
        ua: "Я не розумію цього питання.",
        ru: "Я не понимаю этот вопрос.",
        en: "I do not understand this question.",
        uaTokens: ["Я", "не", "розумію", "цього", "питання", "."],
        ruTokens: ["Я", "не", "понимаю", "этот", "вопрос", "."],
        enTokens: ["I", "do", "not", "understand", "this", "question", "."],
        extraUaTokens: ["допоможіть", "будь", "ласка"],
        extraRuTokens: ["помогите", "пожалуйста", "вопрос"],
        extraEnTokens: ["help", "please", "question"],
    },
    [phraseKey("pomôžte", "a0-29")]: {
        sk: "Pomôžte mi, prosím.",
        ua: "Допоможіть мені, будь ласка.",
        ru: "Помогите мне, пожалуйста.",
        en: "Help me, please.",
        uaTokens: ["Допоможіть", "мені", ",", "будь", "ласка", "."],
        ruTokens: ["Помогите", "мне", ",", "пожалуйста", "."],
        enTokens: ["Help", "me", ",", "please", "."],
        extraUaTokens: ["не", "розумію", "питання"],
        extraRuTokens: ["не", "понимаю", "вопрос"],
        extraEnTokens: ["not", "understand", "question"],
    },
    [phraseKey("jasné", "a0-29")]: {
        sk: "Jasné, súhlasím.",
        ua: "Ясно, я згоден.",
        ru: "Ясно, я согласен.",
        en: "Alright, I agree.",
        uaTokens: ["Ясно", ",", "я", "згоден", "."],
        ruTokens: ["Ясно", ",", "я", "согласен", "."],
        enTokens: ["Alright", ",", "I", "agree", "."],
        extraUaTokens: ["добре", "ходімо", "дякую"],
        extraRuTokens: ["хорошо", "пойдём", "спасибо"],
        extraEnTokens: ["good", "let's-go", "thank-you"],
    },
    [phraseKey("dobre", "a0-29")]: {
        sk: "Dobre, poďme.",
        ua: "Добре, ходімо.",
        ru: "Хорошо, пойдём.",
        en: "Okay, let's go.",
        uaTokens: ["Добре", ",", "ходімо", "."],
        ruTokens: ["Хорошо", ",", "пойдём", "."],
        enTokens: ["Okay", ",", "let's", "go", "."],
        extraUaTokens: ["ясно", "згоден", "привіт"],
        extraRuTokens: ["ясно", "согласен", "привет"],
        extraEnTokens: ["clear", "agree", "hello"],
    },

    // =========================
    // LESSON 30 — Základ
    // =========================
    [phraseKey("ja", "a0-30")]: {
        sk: "Ja som tu.",
        ua: "Я тут.",
        ru: "Я здесь.",
        en: "I am here.",
        uaTokens: ["Я", "тут", "."],
        ruTokens: ["Я", "здесь", "."],
        enTokens: ["I", "am", "here", "."],
        extraUaTokens: ["ти", "він", "ми"],
        extraRuTokens: ["ты", "он", "мы"],
        extraEnTokens: ["you", "he", "we"],
    },
    [phraseKey("ty", "a0-30")]: {
        sk: "Ty si môj priateľ.",
        ua: "Ти мій друг.",
        ru: "Ты мой друг.",
        en: "You are my friend.",
        uaTokens: ["Ти", "мій", "друг", "."],
        ruTokens: ["Ты", "мой", "друг", "."],
        enTokens: ["You", "are", "my", "friend", "."],
        extraUaTokens: ["я", "він", "вона"],
        extraRuTokens: ["я", "он", "она"],
        extraEnTokens: ["I", "he", "she"],
    },
    [phraseKey("on", "a0-30")]: {
        sk: "On pracuje dnes.",
        ua: "Він працює сьогодні.",
        ru: "Он работает сегодня.",
        en: "He is working today.",
        uaTokens: ["Він", "працює", "сьогодні", "."],
        ruTokens: ["Он", "работает", "сегодня", "."],
        enTokens: ["He", "is", "working", "today", "."],
        extraUaTokens: ["вона", "ми", "роботу"],
        extraRuTokens: ["она", "мы", "работу"],
        extraEnTokens: ["she", "we", "work"],
    },
    [phraseKey("ona", "a0-30")]: {
        sk: "Ona je doma.",
        ua: "Вона вдома.",
        ru: "Она дома.",
        en: "She is at home.",
        uaTokens: ["Вона", "вдома", "."],
        ruTokens: ["Она", "дома", "."],
        enTokens: ["She", "is", "at", "home", "."],
        extraUaTokens: ["він", "ми", "друг"],
        extraRuTokens: ["он", "мы", "друг"],
        extraEnTokens: ["he", "we", "friend"],
    },
    [phraseKey("my", "a0-30")]: {
        sk: "My ideme do mesta.",
        ua: "Ми йдемо до міста.",
        ru: "Мы идём в город.",
        en: "We are going to the city.",
        uaTokens: ["Ми", "йдемо", "до", "міста", "."],
        ruTokens: ["Мы", "идём", "в", "город", "."],
        enTokens: ["We", "are", "going", "to", "the", "city", "."],
        extraUaTokens: ["вони", "центр", "роботу"],
        extraRuTokens: ["они", "центр", "работу"],
        extraEnTokens: ["they", "center", "work"],
    },
    [phraseKey("vy", "a0-30")]: {
        sk: "Vy ste pripravení?",
        ua: "Ви готові?",
        ru: "Вы готовы?",
        en: "Are you ready?",
        uaTokens: ["Ви", "готові", "?"],
        ruTokens: ["Вы", "готовы", "?"],
        enTokens: ["Are", "you", "ready", "?"],
        extraUaTokens: ["ми", "вони", "друг"],
        extraRuTokens: ["мы", "они", "друг"],
        extraEnTokens: ["we", "they", "friend"],
    },
    [phraseKey("oni", "a0-30")]: {
        sk: "Oni bývajú blízko.",
        ua: "Вони живуть близько.",
        ru: "Они живут рядом.",
        en: "They live nearby.",
        uaTokens: ["Вони", "живуть", "близько", "."],
        ruTokens: ["Они", "живут", "рядом", "."],
        enTokens: ["They", "live", "nearby", "."],
        extraUaTokens: ["ми", "центр", "вдома"],
        extraRuTokens: ["мы", "центр", "дома"],
        extraEnTokens: ["we", "center", "home"],
    },
    [phraseKey("byť", "a0-30")]: {
        sk: "Chcem byť doma.",
        ua: "Я хочу бути вдома.",
        ru: "Я хочу быть дома.",
        en: "I want to be at home.",
        uaTokens: ["Я", "хочу", "бути", "вдома", "."],
        ruTokens: ["Я", "хочу", "быть", "дома", "."],
        enTokens: ["I", "want", "to", "be", "at", "home", "."],
        extraUaTokens: ["час", "роботу", "ми"],
        extraRuTokens: ["время", "работу", "мы"],
        extraEnTokens: ["time", "work", "we"],
    },
    [phraseKey("mať", "a0-30")]: {
        sk: "Mám čas.",
        ua: "Я маю час.",
        ru: "У меня есть время.",
        en: "I have time.",
        uaTokens: ["Я", "маю", "час", "."],
        ruTokens: ["У", "меня", "есть", "время", "."],
        enTokens: ["I", "have", "time", "."],
        extraUaTokens: ["бути", "роботу", "сьогодні"],
        extraRuTokens: ["быть", "работу", "сегодня"],
        extraEnTokens: ["be", "work", "today"],
    },
    [phraseKey("ísť", "a0-30")]: {
        sk: "Idem do práce.",
        ua: "Я йду на роботу.",
        ru: "Я иду на работу.",
        en: "I am going to work.",
        uaTokens: ["Я", "йду", "на", "роботу", "."],
        ruTokens: ["Я", "иду", "на", "работу", "."],
        enTokens: ["I", "am", "going", "to", "work", "."],
        extraUaTokens: ["час", "ми", "центр"],
        extraRuTokens: ["время", "мы", "центр"],
        extraEnTokens: ["time", "we", "center"],
    },
};