// app/learning/phrases/a0-2.ts
import type { Phrase } from "./a0";
import { phraseKey } from "./phraseKey";

export const A0_PHRASES_2: Record<string, Phrase> = {
  // =========================
  // LESSON 11 — Числа
  // =========================
  [phraseKey("nula", "a0-11")]: {
    sk: "Je to nula.",
    ua: "Це нуль.",
    ru: "Это ноль.",
    en: "It is zero.",
    tokens: ["Je", "to", "nula", "."],
  },
  [phraseKey("jeden", "a0-11")]: {
    sk: "Mám jeden telefón.",
    ua: "У мене один телефон.",
    ru: "У меня один телефон.",
    en: "I have one phone.",
    tokens: ["Mám", "jeden", "telefón", "."],
  },
  [phraseKey("dva", "a0-11")]: {
    sk: "Mám dva dni voľno.",
    ua: "У мене два дні вихідних.",
    ru: "У меня два дня выходных.",
    en: "I have two days off.",
    tokens: ["Mám", "dva", "dni", "voľno", "."],
  },
  [phraseKey("tri", "a0-11")]: {
    sk: "Sú tri hodiny.",
    ua: "Зараз три години.",
    ru: "Сейчас три часа.",
    en: "It is three o'clock.",
    tokens: ["Sú", "tri", "hodiny", "."],
  },
  [phraseKey("štyri", "a0-11")]: {
    sk: "Sú štyri stoličky.",
    ua: "Є чотири стільці.",
    ru: "Есть четыре стула.",
    en: "There are four chairs.",
    tokens: ["Sú", "štyri", "stoličky", "."],
  },
  [phraseKey("päť", "a0-11")]: {
    sk: "Je päť eur.",
    ua: "Це п’ять євро.",
    ru: "Это пять евро.",
    en: "It is five euros.",
    tokens: ["Je", "päť", "eur", "."],
  },
  [phraseKey("šesť", "a0-11")]: {
    sk: "Vstávam o šiestej.",
    ua: "Я встаю о шостій.",
    ru: "Я встаю в шесть.",
    en: "I get up at six.",
    tokens: ["Vstávam", "o", "šiestej", "."],

  },
  [phraseKey("sedem", "a0-11")]: {
    sk: "V týždni je sedem dní.",
    ua: "У тижні сім днів.",
    ru: "В неделе семь дней.",
    en: "There are seven days in a week.",
    tokens: ["V", "týždni", "je", "sedem", "dní", "."],
  },
  [phraseKey("osem", "a0-11")]: {
    sk: "Prídem o ôsmej.",
    ua: "Я прийду о восьмій.",
    ru: "Я приду в восемь.",
    en: "I will come at eight.",
    tokens: ["Prídem", "o", "ôsmej", "."],
  },
  [phraseKey("deväť", "a0-11")]: {
    sk: "Je deväť hodín.",
    ua: "Зараз дев’ята година.",
    ru: "Сейчас девять часов.",
    en: "It is nine o'clock.",
    tokens: ["Je", "deväť", "hodín", "."],
  },

  // =========================
  // LESSON 12 — Кольори
  // =========================
  [phraseKey("farba", "a0-12")]: {
    sk: "Aká je to farba?",
    ua: "Який це колір?",
    ru: "Какой это цвет?",
    en: "What color is it?",
    tokens: ["Aká", "je", "to", "farba", "?"],
  },
  [phraseKey("biely", "a0-12")]: {
    sk: "Toto je biely papier.",
    ua: "Це білий папір.",
    ru: "Это белая бумага.",
    en: "This is white paper.",
    tokens: ["Toto", "je", "biely", "papier", "."],
  },
  [phraseKey("čierny", "a0-12")]: {
    sk: "Mám čierny telefón.",
    ua: "У мене чорний телефон.",
    ru: "У меня чёрный телефон.",
    en: "I have a black phone.",
    tokens: ["Mám", "čierny", "telefón", "."],
  },
  [phraseKey("červený", "a0-12")]: {
    sk: "To je červený kabát.",
    ua: "Це червоне пальто.",
    ru: "Это красное пальто.",
    en: "That is a red coat.",
    tokens: ["To", "je", "červený", "kabát", "."],
  },
  [phraseKey("modrý", "a0-12")]: {
    sk: "Mám modrý sveter.",
    ua: "У мене синій светр.",
    ru: "У меня синий свитер.",
    en: "I have a blue sweater.",
    tokens: ["Mám", "modrý", "sveter", "."],
  },
  [phraseKey("zelený", "a0-12")]: {
    sk: "Zelený strom je veľký.",
    ua: "Зелене дерево велике.",
    ru: "Зелёное дерево большое.",
    en: "The green tree is big.",
    tokens: ["Zelený", "strom", "je", "veľký", "."],
  },
  [phraseKey("žltý", "a0-12")]: {
    sk: "Žlté slnko svieti.",
    ua: "Жовте сонце світить.",
    ru: "Жёлтое солнце светит.",
    en: "The yellow sun is shining.",
    tokens: ["Žlté", "slnko", "svieti", "."],
  },
  [phraseKey("oranžový", "a0-12")]: {
    sk: "Chcem oranžový džús.",
    ua: "Я хочу помаранчевий сік.",
    ru: "Я хочу оранжевый сок.",
    en: "I want orange juice.",
    tokens: ["Chcem", "oranžový", "džús", "."],
  },
  [phraseKey("ružový", "a0-12")]: {
    sk: "Ružové šaty sú pekné.",
    ua: "Рожева сукня гарна.",
    ru: "Розовое платье красивое.",
    en: "The pink dress is pretty.",
    tokens: ["Ružové", "šaty", "sú", "pekné", "."],
  },
  [phraseKey("hnedý", "a0-12")]: {
    sk: "Hnedé topánky sú nové.",
    ua: "Коричневе взуття нове.",
    ru: "Коричневая обувь новая.",
    en: "The brown shoes are new.",
    tokens: ["Hnedé", "topánky", "sú", "nové", "."],
  },

  // =========================
  // LESSON 13 — Одяг
  // =========================
  [phraseKey("oblečenie", "a0-13")]: {
    sk: "Toto je moje oblečenie.",
    ua: "Це мій одяг.",
    ru: "Это моя одежда.",
    en: "This is my clothing.",
    tokens: ["Toto", "je", "moje", "oblečenie", "."],
  },
  [phraseKey("tričko", "a0-13")]: {
    sk: "Mám nové tričko.",
    ua: "У мене нова футболка.",
    ru: "У меня новая футболка.",
    en: "I have a new T-shirt.",
    tokens: ["Mám", "nové", "tričko", "."],
  },
  [phraseKey("nohavice", "a0-13")]: {
    sk: "Tieto nohavice sú čisté.",
    ua: "Ці штани чисті.",
    ru: "Эти брюки чистые.",
    en: "These trousers are clean.",
    tokens: ["Tieto", "nohavice", "sú", "čisté", "."],
  },
  [phraseKey("bunda", "a0-13")]: {
    sk: "Je zima, dávam si bundu.",
    ua: "Холодно, я одягаю куртку.",
    ru: "Холодно, я надеваю куртку.",
    en: "It is cold, I am putting on a jacket.",
    tokens: ["Je", "zima", ",", "dávam", "si", "bundu", "."],
  },
  [phraseKey("topánky", "a0-13")]: {
    sk: "Kde sú moje topánky?",
    ua: "Де моє взуття?",
    ru: "Где моя обувь?",
    en: "Where are my shoes?",
    tokens: ["Kde", "sú", "moje", "topánky", "?"],
  },
  [phraseKey("kabát", "a0-13")]: {
    sk: "Kabát je v skrini.",
    ua: "Пальто в шафі.",
    ru: "Пальто в шкафу.",
    en: "The coat is in the wardrobe.",
    tokens: ["Kabát", "je", "v", "skrini", "."],
  },
  [phraseKey("šaty", "a0-13")]: {
    sk: "Šaty sú ružové.",
    ua: "Сукня рожева.",
    ru: "Платье розовое.",
    en: "The dress is pink.",
    tokens: ["Šaty", "sú", "ružové", "."],
  },
  [phraseKey("čiapka", "a0-13")]: {
    sk: "Potrebujem čiapku.",
    ua: "Мені потрібна шапка.",
    ru: "Мне нужна шапка.",
    en: "I need a hat.",
    tokens: ["Potrebujem", "čiapku", "."],
  },
  [phraseKey("ponožky", "a0-13")]: {
    sk: "Ponožky sú v taške.",
    ua: "Шкарпетки в сумці.",
    ru: "Носки в сумке.",
    en: "The socks are in the bag.",
    tokens: ["Ponožky", "sú", "v", "taške", "."],
  },
  [phraseKey("sveter", "a0-13")]: {
    sk: "Sveter je teplý.",
    ua: "Светр теплий.",
    ru: "Свитер тёплый.",
    en: "The sweater is warm.",
    tokens: ["Sveter", "je", "teplý", "."],
  },

  // =========================
  // LESSON 14 — Тіло людини
  // =========================
  [phraseKey("telo", "a0-14")]: {
    sk: "Telo potrebuje oddych.",
    ua: "Тілу потрібен відпочинок.",
    ru: "Телу нужен отдых.",
    en: "The body needs rest.",
    tokens: ["Telo", "potrebuje", "oddych", "."],
  },
  [phraseKey("hlava", "a0-14")]: {
    sk: "Bolie ma hlava.",
    ua: "У мене болить голова.",
    ru: "У меня болит голова.",
    en: "My head hurts.",
    tokens: ["Bolie", "ma", "hlava", "."],
  },
  [phraseKey("oko", "a0-14")]: {
    sk: "Mám unavené oko.",
    ua: "У мене втомлене око.",
    ru: "У меня устал глаз.",
    en: "My eye is tired.",
    tokens: ["Mám", "unavené", "oko", "."],
  },
  [phraseKey("nos", "a0-14")]: {
    sk: "Nos mám studený.",
    ua: "Ніс у мене холодний.",
    ru: "Нос у меня холодный.",
    en: "My nose is cold.",
    tokens: ["Nos", "mám", "studený", "."],
  },
  [phraseKey("ústa", "a0-14")]: {
    sk: "Ústa sú suché.",
    ua: "Рот сухий.",
    ru: "Рот сухой.",
    en: "My mouth is dry.",
    tokens: ["Ústa", "sú", "suché", "."],
  },
  [phraseKey("ruka", "a0-14")]: {
    sk: "Ruka ma bolí.",
    ua: "Рука болить.",
    ru: "Рука болит.",
    en: "My hand hurts.",
    tokens: ["Ruka", "ma", "bolí", "."],
  },
  [phraseKey("noha", "a0-14")]: {
    sk: "Noha je unavená.",
    ua: "Нога втомлена.",
    ru: "Нога устала.",
    en: "My leg is tired.",
    tokens: ["Noha", "je", "unavená", "."],
  },
  [phraseKey("chrbát", "a0-14")]: {
    sk: "Chrbát ma bolí.",
    ua: "Спина болить.",
    ru: "Спина болит.",
    en: "My back hurts.",
    tokens: ["Chrbát", "ma", "bolí", "."],
  },
  [phraseKey("brucho", "a0-14")]: {
    sk: "Brucho ma bolí.",
    ua: "Живіт болить.",
    ru: "Живот болит.",
    en: "My stomach hurts.",
    tokens: ["Brucho", "ma", "bolí", "."],
  },
  [phraseKey("srdce", "a0-14")]: {
    sk: "Srdce je dôležité.",
    ua: "Серце важливе.",
    ru: "Сердце важно.",
    en: "The heart is important.",
    tokens: ["Srdce", "je", "dôležité", "."],
  },

  // =========================
  // LESSON 15 — Здоров’я
  // =========================
  [phraseKey("zdravie", "a0-15")]: {
    sk: "Zdravie je dôležité.",
    ua: "Здоров’я важливе.",
    ru: "Здоровье важно.",
    en: "Health is important.",
    tokens: ["Zdravie", "je", "dôležité", "."],
  },
  [phraseKey("choroba", "a0-15")]: {
    sk: "Mám chorobu.",
    ua: "У мене хвороба.",
    ru: "У меня болезнь.",
    en: "I have an illness.",
    tokens: ["Mám", "chorobu", "."],
  },
  [phraseKey("lekár", "a0-15")]: {
    sk: "Potrebujem lekára.",
    ua: "Мені потрібен лікар.",
    ru: "Мне нужен врач.",
    en: "I need a doctor.",
    tokens: ["Potrebujem", "lekára", "."],
  },
  [phraseKey("nemocnica", "a0-15")]: {
    sk: "Idem do nemocnice.",
    ua: "Я йду до лікарні.",
    ru: "Я иду в больницу.",
    en: "I am going to the hospital.",
    tokens: ["Idem", "do", "nemocnice", "."],
  },
  [phraseKey("liek", "a0-15")]: {
    sk: "Toto je liek.",
    ua: "Це ліки.",
    ru: "Это лекарство.",
    en: "This is medicine.",
    tokens: ["Toto", "je", "liek", "."],
  },
  [phraseKey("bolesť", "a0-15")]: {
    sk: "Mám bolesť.",
    ua: "У мене біль.",
    ru: "У меня боль.",
    en: "I am in pain.",
    tokens: ["Mám", "bolesť", "."],
  },
  [phraseKey("teplota", "a0-15")]: {
    sk: "Mám teplotu.",
    ua: "У мене температура.",
    ru: "У меня температура.",
    en: "I have a fever.",
    tokens: ["Mám", "teplotu", "."],
  },
  [phraseKey("kašeľ", "a0-15")]: {
    sk: "Mám kašeľ.",
    ua: "У мене кашель.",
    ru: "У меня кашель.",
    en: "I have a cough.",
    tokens: ["Mám", "kašeľ", "."],
  },
  [phraseKey("prechladnutie", "a0-15")]: {
    sk: "Mám prechladnutie.",
    ua: "У мене застуда.",
    ru: "У мене застуда.",
    en: "I have a cold.",
    tokens: ["Mám", "prechladnutie", "."],
  },
  [phraseKey("uzdraviť sa", "a0-15")]: {
    sk: "Chcem sa uzdraviť.",
    ua: "Я хочу одужати.",
    ru: "Я хочу выздороветь.",
    en: "I want to recover.",
    tokens: ["Chcem", "sa", "uzdraviť", "."],
  },

  // =========================
  // LESSON 16 — Погода
  // =========================
  [phraseKey("počasie", "a0-16")]: {
    sk: "Aké je dnes počasie?",
    ua: "Яка сьогодні погода?",
    ru: "Какая сегодня погода?",
    en: "What is the weather like today?",
    tokens: ["Aké", "je", "dnes", "počasie", "?"],
  },
  [phraseKey("slnko", "a0-16")]: {
    sk: "Slnko svieti.",
    ua: "Сонце світить.",
    ru: "Солнце светит.",
    en: "The sun is shining.",
    tokens: ["Slnko", "svieti", "."],
  },
  [phraseKey("dážď", "a0-16")]: {
    sk: "Dnes je dážď.",
    ua: "Сьогодні дощ.",
    ru: "Сегодня дождь.",
    en: "It is raining today.",
    tokens: ["Dnes", "je", "dážď", "."],
  },
  [phraseKey("sneh", "a0-16")]: {
    sk: "Je sneh.",
    ua: "Є сніг.",
    ru: "Есть снег.",
    en: "There is snow.",
    tokens: ["Je", "sneh", "."],
  },
  [phraseKey("vietor", "a0-16")]: {
    sk: "Fúka vietor.",
    ua: "Дме вітер.",
    ru: "Дует ветер.",
    en: "The wind is blowing.",
    tokens: ["Fúka", "vietor", "."],
  },
  [phraseKey("oblak", "a0-16")]: {
    sk: "Na nebi je oblak.",
    ua: "На небі хмара.",
    ru: "На небе облако.",
    en: "There is a cloud in the sky.",
    tokens: ["Na", "nebi", "je", "oblak", "."],
  },
  [phraseKey("teplo", "a0-16")]: {
    sk: "Dnes je teplo.",
    ua: "Сьогодні тепло.",
    ru: "Сегодня тепло.",
    en: "It is warm today.",
    tokens: ["Dnes", "je", "teplo", "."],
  },
  [phraseKey("zima", "a0-16")]: {
    sk: "Dnes je zima.",
    ua: "Сьогодні холодно.",
    ru: "Сегодня холодно.",
    en: "It is cold today.",
    tokens: ["Dnes", "je", "zima", "."],
  },
  [phraseKey("búrka", "a0-16")]: {
    sk: "Je búrka.",
    ua: "Буря / гроза.",
    ru: "Буря / гроза.",
    en: "There is a storm.",
    tokens: ["Je", "búrka", "."]
  },
  [phraseKey("teplota", "a0-16")]: {
    sk: "To je teplota.",
    ua: "Це температура.",
    ru: "Это температура.",
    en: "This is the temperature.",
    tokens: ["To", "je", "teplota", "."],
  },
  // =========================
  // LESSON 17 — Природа
  // =========================
  [phraseKey("príroda", "a0-17")]: {
    sk: "Mám rád prírodu.",
    ua: "Я люблю природу.",
    ru: "Я люблю природу.",
    en: "I like nature.",
    tokens: ["Mám", "rád", "prírodu", "."],
  },
  [phraseKey("strom", "a0-17")]: {
    sk: "Tu je strom.",
    ua: "Тут дерево.",
    ru: "Здесь дерево.",
    en: "There is a tree here.",
    tokens: ["Tu", "je", "strom", "."],
  },
  [phraseKey("les", "a0-17")]: {
    sk: "Idem do lesa.",
    ua: "Я йду в ліс.",
    ru: "Я иду в лес.",
    en: "I am going to the forest.",
    tokens: ["Idem", "do", "lesa", "."],
  },
  [phraseKey("rieka", "a0-17")]: {
    sk: "Tu je rieka.",
    ua: "Тут річка.",
    ru: "Здесь река.",
    en: "There is a river here.",
    tokens: ["Tu", "je", "rieka", "."],
  },
  [phraseKey("jazero", "a0-17")]: {
    sk: "Tu je jazero.",
    ua: "Тут озеро.",
    ru: "Здесь озеро.",
    en: "There is a lake here.",
    tokens: ["Tu", "je", "jazero", "."],
  },
  [phraseKey("hora", "a0-17")]: {
    sk: "Tá hora je vysoká.",
    ua: "Та гора висока.",
    ru: "Та гора высокая.",
    en: "That mountain is high.",
    tokens: ["Tá", "hora", "je", "vysoká", "."],
  },
  [phraseKey("kvet", "a0-17")]: {
    sk: "Toto je kvet.",
    ua: "Це квітка.",
    ru: "Это цветок.",
    en: "This is a flower.",
    tokens: ["Toto", "je", "kvet", "."],
  },
  [phraseKey("tráva", "a0-17")]: {
    sk: "Tráva je zelená.",
    ua: "Трава зелена.",
    ru: "Трава зелёная.",
    en: "The grass is green.",
    tokens: ["Tráva", "je", "zelená", "."],
  },
  [phraseKey("zviera", "a0-17")]: {
    sk: "To zviera je tu.",
    ua: "Ця тварина тут.",
    ru: "Это животное здесь.",
    en: "That animal is here.",
    tokens: ["To", "zviera", "je", "tu", "."],
  },
  [phraseKey("zem", "a0-17")]: {
    sk: "Zem je veľká.",
    ua: "Земля велика.",
    ru: "Земля большая.",
    en: "The Earth is big.",
    tokens: ["Zem", "je", "veľká", "."],
  },

  // =========================
  // LESSON 18 — Побут
  // =========================
  [phraseKey("domácnosť", "a0-18")]: {
    sk: "Domácnosť je dôležitá.",
    ua: "Побут важливий.",
    ru: "Быт важен.",
    en: "Household life is important.",
    tokens: ["Domácnosť", "je", "dôležitá", "."],
  },
  [phraseKey("dom", "a0-18")]: {
    sk: "Toto je dom.",
    ua: "Це дім.",
    ru: "Это дом.",
    en: "This is a house.",
    tokens: ["Toto", "je", "dom", "."],
  },
  [phraseKey("byt", "a0-18")]: {
    sk: "Mám byt.",
    ua: "У мене є квартира.",
    ru: "У меня есть квартира.",
    en: "I have an apartment.",
    tokens: ["Mám", "byt", "."],
  },
  [phraseKey("izba", "a0-18")]: {
    sk: "Toto je izba.",
    ua: "Це кімната.",
    ru: "Это комната.",
    en: "This is a room.",
    tokens: ["Toto", "je", "izba", "."],
  },
  [phraseKey("posteľ", "a0-18")]: {
    sk: "Tu je posteľ.",
    ua: "Тут ліжко.",
    ru: "Здесь кровать.",
    en: "There is a bed here.",
    tokens: ["Tu", "je", "posteľ", "."],
  },
  [phraseKey("stôl", "a0-18")]: {
    sk: "Stôl je veľký.",
    ua: "Стіл великий.",
    ru: "Стол большой.",
    en: "The table is big.",
    tokens: ["Stôl", "je", "veľký", "."],
  },
  [phraseKey("stolička", "a0-18")]: {
    sk: "Stolička je tu.",
    ua: "Стілець тут.",
    ru: "Стул здесь.",
    en: "The chair is here.",
    tokens: ["Stolička", "je", "tu", "."],
  },
  [phraseKey("kuchyňa", "a0-18")]: {
    sk: "Kuchyňa je čistá.",
    ua: "Кухня чиста.",
    ru: "Кухня чистая.",
    en: "The kitchen is clean.",
    tokens: ["Kuchyňa", "je", "čistá", "."],
  },
  [phraseKey("chladnička", "a0-18")]: {
    sk: "Chladnička je plná.",
    ua: "Холодильник повний.",
    ru: "Холодильник полный.",
    en: "The fridge is full.",
    tokens: ["Chladnička", "je", "plná", "."],
  },
  [phraseKey("upratovať", "a0-18")]: {
    sk: "Idem upratovať.",
    ua: "Я йду прибирати.",
    ru: "Я иду убирать.",
    en: "I am going to clean.",
    tokens: ["Idem", "upratovať", "."],
  },

  // =========================
  // LESSON 19 — Дії та дієслова
  // =========================
  [phraseKey("robiť", "a0-19")]: {
    sk: "Čo robíš?",
    ua: "Що ти робиш?",
    ru: "Что ты делаешь?",
    en: "What are you doing?",
    tokens: ["Čo", "robíš", "?"],
  },
  [phraseKey("ísť", "a0-19")]: {
    sk: "Idem domov.",
    ua: "Я йду додому.",
    ru: "Я иду домой.",
    en: "I am going home.",
    tokens: ["Idem", "domov", "."],
  },
  [phraseKey("prísť", "a0-19")]: {
    sk: "Prídem zajtra.",
    ua: "Я прийду завтра.",
    ru: "Я приду завтра.",
    en: "I will come tomorrow.",
    tokens: ["Prídem", "zajtra", "."],
  },
  [phraseKey("vidieť", "a0-19")]: {
    sk: "Vidím ťa.",
    ua: "Я бачу тебе.",
    ru: "Я вижу тебя.",
    en: "I see you.",
    tokens: ["Vidím", "ťa", "."],
  },
  [phraseKey("hovoriť", "a0-19")]: {
    sk: "Hovorím po slovensky.",
    ua: "Я говорю словацькою.",
    ru: "Я говорю по-словацки.",
    en: "I speak Slovak.",
    tokens: ["Hovorím", "po", "slovensky", "."],
  },
  [phraseKey("jesť", "a0-19")]: {
    sk: "Jem obed.",
    ua: "Я їм обід.",
    ru: "Я ем обед.",
    en: "I am eating lunch.",
    tokens: ["Jem", "obed", "."],
  },
  [phraseKey("piť", "a0-19")]: {
    sk: "Pijem vodu.",
    ua: "Я п’ю воду.",
    ru: "Я пью воду.",
    en: "I am drinking water.",
    tokens: ["Pijem", "vodu", "."],
  },
  [phraseKey("spať", "a0-19")]: {
    sk: "Spím v noci.",
    ua: "Я сплю вночі.",
    ru: "Я сплю ночью.",
    en: "I sleep at night.",
    tokens: ["Spím", "v", "noci", "."],
  },
  [phraseKey("pracovať", "a0-19")]: {
    sk: "Pracujem dnes.",
    ua: "Я працюю сьогодні.",
    ru: "Я работаю сегодня.",
    en: "I am working today.",
    tokens: ["Pracujem", "dnes", "."],
  },
  [phraseKey("učiť sa", "a0-19")]: {
    sk: "Učím sa po slovensky.",
    ua: "Я вчуся словацькою.",
    ru: "Я учусь словацкому.",
    en: "I am learning Slovak.",
    tokens: ["Učím", "sa", "po", "slovensky", "."],
  },

  // =========================
  // LESSON 20 — Питання і відповіді
  // =========================
  [phraseKey("kto", "a0-20")]: {
    sk: "Kto je to?",
    ua: "Хто це?",
    ru: "Кто это?",
    en: "Who is it?",
    tokens: ["Kto", "je", "to", "?"],
  },
  [phraseKey("čo", "a0-20")]: {
    sk: "Čo je to?",
    ua: "Що це?",
    ru: "Что это?",
    en: "What is it?",
    tokens: ["Čo", "je", "to", "?"],
  },
  [phraseKey("kde", "a0-20")]: {
    sk: "Kde si?",
    ua: "Де ти?",
    ru: "Где ты?",
    en: "Where are you?",
    tokens: ["Kde", "si", "?"],
  },
  [phraseKey("kedy", "a0-20")]: {
    sk: "Kedy prídeš?",
    ua: "Коли ти прийдеш?",
    ru: "Когда ты придёшь?",
    en: "When will you come?",
    tokens: ["Kedy", "prídeš", "?"],
  },
  [phraseKey("prečo", "a0-20")]: {
    sk: "Prečo si tu?",
    ua: "Чому ти тут?",
    ru: "Почему ты здесь?",
    en: "Why are you here?",
    tokens: ["Prečo", "si", "tu", "?"],
  },
  [phraseKey("ako", "a0-20")]: {
    sk: "Ako sa máš?",
    ua: "Як ти?",
    ru: "Как ты?",
    en: "How are you?",
    tokens: ["Ako", "sa", "máš", "?"],
  },
  [phraseKey("koľko", "a0-20")]: {
    sk: "Koľko to stojí?",
    ua: "Скільки це коштує?",
    ru: "Сколько это стоит?",
    en: "How much does it cost?",
    tokens: ["Koľko", "to", "stojí", "?"],
  },
  [phraseKey("áno", "a0-20")]: {
    sk: "Áno, ďakujem.",
    ua: "Так, дякую.",
    ru: "Да, спасибо.",
    en: "Yes, thank you.",
    tokens: ["Áno", ",", "ďakujem", "."],
  },
  [phraseKey("nie", "a0-20")]: {
    sk: "Nie, ďakujem.",
    ua: "Ні, дякую.",
    ru: "Нет, спасибо.",
    en: "No, thank you.",
    tokens: ["Nie", ",", "ďakujem", "."],
  },
  [phraseKey("možno", "a0-20")]: {
    sk: "Možno zajtra.",
    ua: "Можливо завтра.",
    ru: "Возможно завтра.",
    en: "Maybe tomorrow.",
    tokens: ["Možno", "zajtra", "."],
  },
};