// app/learning/phrases/a0-3.ts
import type { Phrase } from "./a0";
import { phraseKey } from "./phraseKey";

export const A0_PHRASES_3: Record<string, Phrase> = {
  // =========================
  // LESSON 21 — Miesta
  // =========================
  [phraseKey("miesto", "a0-21")]: {
    sk: "To je pekné miesto.",
    ua: "Це гарне місце.",
    ru: "Это красивое место.",
    en: "This is a nice place.",
    tokens: ["To", "je", "pekné", "miesto", "."],
  },
  [phraseKey("centrum", "a0-21")]: {
    sk: "Som v centre mesta.",
    ua: "Я в центрі міста.",
    ru: "Я в центре города.",
    en: "I am in the city center.",
    tokens: ["Som", "v", "centre", "mesta", "."],
  },
  [phraseKey("obchod", "a0-21")]: {
    sk: "Idem do obchodu.",
    ua: "Я йду до магазину.",
    ru: "Я иду в магазин.",
    en: "I am going to the shop.",
    tokens: ["Idem", "do", "obchodu", "."],
  },
  [phraseKey("reštaurácia", "a0-21")]: {
    sk: "Večer ideme do reštaurácie.",
    ua: "Увечері ми йдемо до ресторану.",
    ru: "Вечером мы идём в ресторан.",
    en: "We are going to a restaurant in the evening.",
    tokens: ["Večer", "ideme", "do", "reštaurácie", "."],
  },
  [phraseKey("kaviareň", "a0-21")]: {
    sk: "Sedím v kaviarni s priateľom.",
    ua: "Я сиджу в кафе з другом.",
    ru: "Я сижу в кафе с другом.",
    en: "I am sitting in a café with a friend.",
    tokens: ["Sedím", "v", "kaviarni", "s", "priateľom", "."],
  },
  [phraseKey("park", "a0-21")]: {
    sk: "Prechádzam sa v parku.",
    ua: "Я гуляю в парку.",
    ru: "Я гуляю в парке.",
    en: "I am walking in the park.",
    tokens: ["Prechádzam", "sa", "v", "parku", "."],
  },
  [phraseKey("banka", "a0-21")]: {
    sk: "Musím ísť do banky.",
    ua: "Мені потрібно піти до банку.",
    ru: "Мне нужно идти в банк.",
    en: "I need to go to the bank.",
    tokens: ["Musím", "ísť", "do", "banky", "."],
  },
  [phraseKey("pošta", "a0-21")]: {
    sk: "Balík je na pošte.",
    ua: "Посилка на пошті.",
    ru: "Посылка на почте.",
    en: "The package is at the post office.",
    tokens: ["Balík", "je", "na", "pošte", "."],
  },
  [phraseKey("polícia", "a0-21")]: {
    sk: "Volám políciu.",
    ua: "Я викликаю поліцію.",
    ru: "Я вызываю полицию.",
    en: "I am calling the police.",
    tokens: ["Volám", "políciu", "."],
  },
  [phraseKey("stanica", "a0-21")]: {
    sk: "Čakám na stanici.",
    ua: "Я чекаю на вокзалі.",
    ru: "Я жду на вокзале.",
    en: "I am waiting at the station.",
    tokens: ["Čakám", "na", "stanici", "."],
  },

  // =========================
  // LESSON 22 — Emócie
  // =========================
  [phraseKey("radosť", "a0-22")]: {
    sk: "Cítim veľkú radosť.",
    ua: "Я відчуваю велику радість.",
    ru: "Я чувствую большую радость.",
    en: "I feel great joy.",
    tokens: ["Cítim", "veľkú", "radosť", "."],
  },
  [phraseKey("smútok", "a0-22")]: {
    sk: "Je to hlboký smútok.",
    ua: "Це глибокий смуток.",
    ru: "Это глубокая грусть.",
    en: "It is deep sadness.",
    tokens: ["Je", "to", "hlboký", "smútok", "."],
  },
  [phraseKey("strach", "a0-22")]: {
    sk: "Mám strach z tmy.",
    ua: "Я боюся темряви.",
    ru: "Я боюсь темноты.",
    en: "I am afraid of the dark.",
    tokens: ["Mám", "strach", "z", "tmy", "."],
  },
  [phraseKey("hnev", "a0-22")]: {
    sk: "Cítim hnev.",
    ua: "Я відчуваю злість.",
    ru: "Я чувствую гнев.",
    en: "I feel anger.",
    tokens: ["Cítim", "hnev", "."],
  },
  [phraseKey("láska", "a0-22")]: {
    sk: "Láska je krásna.",
    ua: "Любов прекрасна.",
    ru: "Любовь прекрасна.",
    en: "Love is beautiful.",
    tokens: ["Láska", "je", "krásna", "."],
  },
  [phraseKey("šťastie", "a0-22")]: {
    sk: "Cítim šťastie.",
    ua: "Я відчуваю щастя.",
    ru: "Я чувствую счастье.",
    en: "I feel happiness.",
    tokens: ["Cítim", "šťastie", "."],
  },
  [phraseKey("únava", "a0-22")]: {
    sk: "Som unavený.",
    ua: "Я втомлений.",
    ru: "Я устал.",
    en: "I am tired.",
    tokens: ["Som", "unavený", "."],
  },
  [phraseKey("stres", "a0-22")]: {
    sk: "Mám veľa stresu.",
    ua: "У мене багато стресу.",
    ru: "У меня много стресса.",
    en: "I have a lot of stress.",
    tokens: ["Mám", "veľa", "stresu", "."],
  },
  [phraseKey("pokoj", "a0-22")]: {
    sk: "Chcem pokoj.",
    ua: "Я хочу спокою.",
    ru: "Я хочу спокойствия.",
    en: "I want peace.",
    tokens: ["Chcem", "pokoj", "."],
  },
  [phraseKey("prekvapenie", "a0-22")]: {
    sk: "To je prekvapenie.",
    ua: "Це сюрприз.",
    ru: "Это сюрприз.",
    en: "That is a surprise.",
    tokens: ["To", "je", "prekvapenie", "."],
  },

  // =========================
  // LESSON 23 — Hobby
  // =========================
  [phraseKey("hobby", "a0-23")]: {
    sk: "Moje hobby je hudba.",
    ua: "Моє хобі — музика.",
    ru: "Моё хобби — музыка.",
    en: "My hobby is music.",
    tokens: ["Moje", "hobby", "je", "hudba", "."],
  },
  [phraseKey("šport", "a0-23")]: {
    sk: "Rád športujem.",
    ua: "Я люблю займатися спортом.",
    ru: "Я люблю заниматься спортом.",
    en: "I like sports.",
    tokens: ["Rád", "športujem", "."],
  },
  [phraseKey("futbal", "a0-23")]: {
    sk: "Hrám futbal.",
    ua: "Я граю у футбол.",
    ru: "Я играю в футбол.",
    en: "I play football.",
    tokens: ["Hrám", "futbal", "."],
  },
  [phraseKey("hudba", "a0-23")]: {
    sk: "Počúvam hudbu každý deň.",
    ua: "Я слухаю музику щодня.",
    ru: "Я слушаю музыку каждый день.",
    en: "I listen to music every day.",
    tokens: ["Počúvam", "hudbu", "každý", "deň", "."],
  },
  [phraseKey("film", "a0-23")]: {
    sk: "Pozerám film.",
    ua: "Я дивлюся фільм.",
    ru: "Я смотрю фильм.",
    en: "I watch a movie.",
    tokens: ["Pozerám", "film", "."],
  },
  [phraseKey("čítanie", "a0-23")]: {
    sk: "Mám rád čítanie.",
    ua: "Я люблю читання.",
    ru: "Я люблю чтение.",
    en: "I like reading.",
    tokens: ["Mám", "rád", "čítanie", "."],
  },
  [phraseKey("cestovanie", "a0-23")]: {
    sk: "Milujem cestovanie.",
    ua: "Я люблю подорожувати.",
    ru: "Я люблю путешествовать.",
    en: "I love traveling.",
    tokens: ["Milujem", "cestovanie", "."],
  },
  [phraseKey("hra", "a0-23")]: {
    sk: "Hrám hru.",
    ua: "Я граю в гру.",
    ru: "Я играю в игру.",
    en: "I play a game.",
    tokens: ["Hrám", "hru", "."],
  },
  [phraseKey("maľovanie", "a0-23")]: {
    sk: "Maľujem obraz.",
    ua: "Я малюю картину.",
    ru: "Я рисую картину.",
    en: "I paint a picture.",
    tokens: ["Maľujem", "obraz", "."],
  },
  [phraseKey("tanec", "a0-23")]: {
    sk: "Tancujem večer.",
    ua: "Я танцюю ввечері.",
    ru: "Я танцую вечером.",
    en: "I dance in the evening.",
    tokens: ["Tancujem", "večer", "."],
  },

  // =========================
  // LESSON 24 — Komunikácia
  // =========================
  [phraseKey("hovoriť", "a0-24")]: {
    sk: "Hovorím po slovensky.",
    ua: "Я говорю словацькою.",
    ru: "Я говорю по-словацки.",
    en: "I speak Slovak.",
    tokens: ["Hovorím", "po", "slovensky", "."],
  },
  [phraseKey("rozprávať", "a0-24")]: {
    sk: "Rozprávam ti príbeh.",
    ua: "Я розповідаю тобі історію.",
    ru: "Я рассказываю тебе историю.",
    en: "I tell you a story.",
    tokens: ["Rozprávam", "ti", "príbeh", "."],
  },
  [phraseKey("počúvať", "a0-24")]: {
    sk: "Počúvam ťa.",
    ua: "Я слухаю тебе.",
    ru: "Я слушаю тебя.",
    en: "I listen to you.",
    tokens: ["Počúvam", "ťa", "."],
  },
  [phraseKey("pýtať sa", "a0-24")]: {
    sk: "Pýtam sa na cenu.",
    ua: "Я питаю про ціну.",
    ru: "Я спрашиваю про цену.",
    en: "I ask about the price.",
    tokens: ["Pýtam", "sa", "na", "cenu", "."],
  },
  [phraseKey("odpovedať", "a0-24")]: {
    sk: "Odpovedám na otázku.",
    ua: "Я відповідаю на питання.",
    ru: "Я отвечаю на вопрос.",
    en: "I answer the question.",
    tokens: ["Odpovedám", "na", "otázku", "."],
  },
  [phraseKey("telefonovať", "a0-24")]: {
    sk: "Telefonujem mame.",
    ua: "Я телефоную мамі.",
    ru: "Я звоню маме.",
    en: "I call my mom.",
    tokens: ["Telefonujem", "mame", "."],
  },
  [phraseKey("správa", "a0-24")]: {
    sk: "Posielam správu.",
    ua: "Я надсилаю повідомлення.",
    ru: "Я отправляю сообщение.",
    en: "I send a message.",
    tokens: ["Posielam", "správu", "."],
  },
  [phraseKey("stretnutie", "a0-24")]: {
    sk: "Mám stretnutie o tretej.",
    ua: "У мене зустріч о третій.",
    ru: "У меня встреча в три.",
    en: "I have a meeting at three.",
    tokens: ["Mám", "stretnutie", "o", "tretej", "."],
  },
  [phraseKey("diskusia", "a0-24")]: {
    sk: "Máme diskusiu v práci.",
    ua: "У нас обговорення на роботі.",
    ru: "У нас обсуждение на работе.",
    en: "We have a discussion at work.",
    tokens: ["Máme", "diskusiu", "v", "práci", "."],
  },
  [phraseKey("pozdrav", "a0-24")]: {
    sk: "Dám ti pozdrav.",
    ua: "Передам тобі привітання.",
    ru: "Передам тебе привет.",
    en: "I will send you greetings.",
    tokens: ["Dám", "ti", "pozdrav", "."],
  },

  // =========================
  // LESSON 25 — Cestovanie
  // =========================
  [phraseKey("cesta", "a0-25")]: {
    sk: "Tá cesta je dlhá.",
    ua: "Ця подорож довга.",
    ru: "Это путешествие долгое.",
    en: "This journey is long.",
    tokens: ["Tá", "cesta", "je", "dlhá", "."],
  },
  [phraseKey("cestovať", "a0-25")]: {
    sk: "Chcem cestovať v lete.",
    ua: "Я хочу подорожувати влітку.",
    ru: "Я хочу путешествовать летом.",
    en: "I want to travel in summer.",
    tokens: ["Chcem", "cestovať", "v", "lete", "."],
  },
  [phraseKey("kufor", "a0-25")]: {
    sk: "Kufor je ťažký.",
    ua: "Валіза важка.",
    ru: "Чемодан тяжёлый.",
    en: "The suitcase is heavy.",
    tokens: ["Kufor", "je", "ťažký", "."],
  },
  [phraseKey("pas", "a0-25")]: {
    sk: "Kde je môj pas?",
    ua: "Де мій паспорт?",
    ru: "Где мой паспорт?",
    en: "Where is my passport?",
    tokens: ["Kde", "je", "môj", "pas", "?"],
  },
  [phraseKey("letenka", "a0-25")]: {
    sk: "Mám letenku do Viedne.",
    ua: "У мене є авіаквиток до Відня.",
    ru: "У меня есть авиабилет в Вену.",
    en: "I have a ticket to Vienna.",
    tokens: ["Mám", "letenku", "do", "Viedne", "."],
  },
  [phraseKey("vlak", "a0-25")]: {
    sk: "Vlak ide o šiestej.",
    ua: "Поїзд їде о шостій.",
    ru: "Поезд едет в шесть.",
    en: "The train leaves at six.",
    tokens: ["Vlak", "ide", "o", "šiestej", "."],
  },
  [phraseKey("autobus", "a0-25")]: {
    sk: "Autobus je už tu.",
    ua: "Автобус уже тут.",
    ru: "Автобус уже здесь.",
    en: "The bus is already here.",
    tokens: ["Autobus", "je", "už", "tu", "."],
  },
  [phraseKey("letisko", "a0-25")]: {
    sk: "Som na letisku.",
    ua: "Я в аеропорту.",
    ru: "Я в аэропорту.",
    en: "I am at the airport.",
    tokens: ["Som", "na", "letisku", "."],
  },
  [phraseKey("mapa", "a0-25")]: {
    sk: "Mám mapu mesta.",
    ua: "У мене є карта міста.",
    ru: "У меня есть карта города.",
    en: "I have a city map.",
    tokens: ["Mám", "mapu", "mesta", "."],
  },
  [phraseKey("rezervácia", "a0-25")]: {
    sk: "Mám rezerváciu v hoteli.",
    ua: "У мене є бронювання в готелі.",
    ru: "У меня есть бронь в отеле.",
    en: "I have a reservation at the hotel.",
    tokens: ["Mám", "rezerváciu", "v", "hoteli", "."],
  },

  // =========================
  // LESSON 26 — Hotel a reštaurácia
  // =========================
  [phraseKey("hotel", "a0-26")]: {
    sk: "Hotel je v centre.",
    ua: "Готель у центрі.",
    ru: "Отель в центре.",
    en: "The hotel is in the center.",
    tokens: ["Hotel", "je", "v", "centre", "."],
  },
  [phraseKey("izba", "a0-26")]: {
    sk: "Izba je čistá.",
    ua: "Кімната чиста.",
    ru: "Комната чистая.",
    en: "The room is clean.",
    tokens: ["Izba", "je", "čistá", "."],
  },
  [phraseKey("recepcia", "a0-26")]: {
    sk: "Idem na recepciu.",
    ua: "Я йду на ресепшн.",
    ru: "Я иду на ресепшн.",
    en: "I am going to the reception.",
    tokens: ["Idem", "na", "recepciu", "."],
  },
  [phraseKey("reštaurácia", "a0-26")]: {
    sk: "Reštaurácia je otvorená.",
    ua: "Ресторан відкритий.",
    ru: "Ресторан открыт.",
    en: "The restaurant is open.",
    tokens: ["Reštaurácia", "je", "otvorená", "."],
  },
  [phraseKey("menu", "a0-26")]: {
    sk: "Prosím si menu.",
    ua: "Будь ласка, меню.",
    ru: "Пожалуйста, меню.",
    en: "Menu, please.",
    tokens: ["Prosím", "si", "menu", "."],
  },
  [phraseKey("objednať", "a0-26")]: {
    sk: "Chcem si objednať polievku.",
    ua: "Я хочу замовити суп.",
    ru: "Я хочу заказать суп.",
    en: "I want to order soup.",
    tokens: ["Chcem", "si", "objednať", "polievku", "."],
  },
  [phraseKey("raňajky", "a0-26")]: {
    sk: "Raňajky sú o siedmej.",
    ua: "Сніданок о сьомій.",
    ru: "Завтрак в семь.",
    en: "Breakfast is at seven.",
    tokens: ["Raňajky", "sú", "o", "siedmej", "."],
  },
  [phraseKey("obed", "a0-26")]: {
    sk: "Dám si obed.",
    ua: "Я візьму обід.",
    ru: "Я возьму обед.",
    en: "I will have lunch.",
    tokens: ["Dám", "si", "obed", "."],
  },
  [phraseKey("večera", "a0-26")]: {
    sk: "Večera je chutná.",
    ua: "Вечеря смачна.",
    ru: "Ужин вкусный.",
    en: "Dinner is tasty.",
    tokens: ["Večera", "je", "chutná", "."],
  },
  [phraseKey("účet", "a0-26")]: {
    sk: "Prosím, účet.",
    ua: "Рахунок, будь ласка.",
    ru: "Счёт, пожалуйста.",
    en: "The bill, please.",
    tokens: ["Prosím", ",", "účet", "."],
  },

  // =========================
  // LESSON 27 — Peniaze
  // =========================
  [phraseKey("peniaze", "a0-27")]: {
    sk: "Nemám teraz peniaze.",
    ua: "Я зараз не маю грошей.",
    ru: "У меня сейчас нет денег.",
    en: "I do not have any money now.",
    tokens: ["Nemám", "teraz", "peniaze", "."],
  },
  [phraseKey("euro", "a0-27")]: {
    sk: "Je to desať eur.",
    ua: "Це десять євро.",
    ru: "Это десять евро.",
    en: "It is ten euros.",
    tokens: ["Je", "to", "desať", "eur", "."],
  },
  [phraseKey("cena", "a0-27")]: {
    sk: "Aká je cena?",
    ua: "Яка ціна?",
    ru: "Какая цена?",
    en: "What is the price?",
    tokens: ["Aká", "je", "cena", "?"],
  },
  [phraseKey("platba", "a0-27")]: {
    sk: "Platba je úspešná.",
    ua: "Платіж успішний.",
    ru: "Платёж успешный.",
    en: "The payment is successful.",
    tokens: ["Platba", "je", "úspešná", "."],
  },
  [phraseKey("hotovosť", "a0-27")]: {
    sk: "Platím v hotovosti.",
    ua: "Я плачу готівкою.",
    ru: "Я плачу наличными.",
    en: "I pay in cash.",
    tokens: ["Platím", "v", "hotovosti", "."],
  },
  [phraseKey("karta", "a0-27")]: {
    sk: "Platím kartou.",
    ua: "Я плачу карткою.",
    ru: "Я плачу картой.",
    en: "I pay by card.",
    tokens: ["Platím", "kartou", "."],
  },
  [phraseKey("účet", "a0-27")]: {
    sk: "Účet je vysoký.",
    ua: "Рахунок великий.",
    ru: "Счёт большой.",
    en: "The bill is high.",
    tokens: ["Účet", "je", "vysoký", "."],
  },
  [phraseKey("banka", "a0-27")]: {
    sk: "Banka je blízko.",
    ua: "Банк близько.",
    ru: "Банк близко.",
    en: "The bank is nearby.",
    tokens: ["Banka", "je", "blízko", "."],
  },
  [phraseKey("zľava", "a0-27")]: {
    sk: "Dnes je zľava.",
    ua: "Сьогодні знижка.",
    ru: "Сегодня скидка.",
    en: "There is a discount today.",
    tokens: ["Dnes", "je", "zľava", "."],
  },
  [phraseKey("výdavky", "a0-27")]: {
    sk: "Moje výdavky sú veľké.",
    ua: "Мої витрати великі.",
    ru: "Мои расходы большие.",
    en: "My expenses are high.",
    tokens: ["Moje", "výdavky", "sú", "veľké", "."],
  },

  // =========================
  // LESSON 28 — Technológie
  // =========================
  [phraseKey("technológia", "a0-28")]: {
    sk: "Technológia sa rýchlo mení.",
    ua: "Технології швидко змінюються.",
    ru: "Технологии быстро меняются.",
    en: "Technology changes quickly.",
    tokens: ["Technológia", "sa", "rýchlo", "mení", "."],
  },
  [phraseKey("počítač", "a0-28")]: {
    sk: "Mám nový počítač.",
    ua: "У мене новий комп’ютер.",
    ru: "У меня новый компьютер.",
    en: "I have a new computer.",
    tokens: ["Mám", "nový", "počítač", "."],
  },
  [phraseKey("telefón", "a0-28")]: {
    sk: "Telefón je na stole.",
    ua: "Телефон на столі.",
    ru: "Телефон на столе.",
    en: "The phone is on the table.",
    tokens: ["Telefón", "je", "na", "stole", "."],
  },
  [phraseKey("internet", "a0-28")]: {
    sk: "Nemám internet.",
    ua: "У мене немає інтернету.",
    ru: "У меня нет интернета.",
    en: "I don't have internet.",
    tokens: ["Nemám", "internet", "."],
  },
  [phraseKey("aplikácia", "a0-28")]: {
    sk: "Používam túto aplikáciu.",
    ua: "Я використовую цей додаток.",
    ru: "Я использую это приложение.",
    en: "I use this app.",
    tokens: ["Používam", "túto", "aplikáciu", "."],
  },
  [phraseKey("program", "a0-28")]: {
    sk: "Program nefunguje.",
    ua: "Програма не працює.",
    ru: "Программа не работает.",
    en: "The program does not work.",
    tokens: ["Program", "nefunguje", "."],
  },
  [phraseKey("systém", "a0-28")]: {
    sk: "Systém je rýchly.",
    ua: "Система швидка.",
    ru: "Система быстрая.",
    en: "The system is fast.",
    tokens: ["Systém", "je", "rýchly", "."],
  },
  [phraseKey("sieť", "a0-28")]: {
    sk: "Sieť je slabá.",
    ua: "Мережа слабка.",
    ru: "Сеть слабая.",
    en: "The network is weak.",
    tokens: ["Sieť", "je", "slabá", "."],
  },
  [phraseKey("dáta", "a0-28")]: {
    sk: "Ukladám dáta.",
    ua: "Я зберігаю дані.",
    ru: "Я сохраняю данные.",
    en: "I save data.",
    tokens: ["Ukladám", "dáta", "."],
  },
  [phraseKey("heslo", "a0-28")]: {
    sk: "Zabudol som heslo.",
    ua: "Я забув пароль.",
    ru: "Я забыл пароль.",
    en: "I forgot the password.",
    tokens: ["Zabudol", "som", "heslo", "."],
  },

  // =========================
  // LESSON 29 — Každodenné frázy
  // =========================
  [phraseKey("dobrý deň", "a0-29")]: {
    sk: "Dobrý deň, ako sa máte?",
    ua: "Добрий день, як ви?",
    ru: "Добрый день, как вы?",
    en: "Good day, how are you?",
    tokens: ["Dobrý", "deň", ",", "ako", "sa", "máte", "?"],
  },
  [phraseKey("ahoj", "a0-29")]: {
    sk: "Ahoj, čo robíš?",
    ua: "Привіт, що ти робиш?",
    ru: "Привет, что ты делаешь?",
    en: "Hi, what are you doing?",
    tokens: ["Ahoj", ",", "čo", "robíš", "?"],
  },
  [phraseKey("ďakujem", "a0-29")]: {
    sk: "Ďakujem za pomoc.",
    ua: "Дякую за допомогу.",
    ru: "Спасибо за помощь.",
    en: "Thank you for your help.",
    tokens: ["Ďakujem", "za", "pomoc", "."],
  },
  [phraseKey("prosím", "a0-29")]: {
    sk: "Prosím, sadnite si.",
    ua: "Будь ласка, сідайте.",
    ru: "Пожалуйста, садитесь.",
    en: "Please, sit down.",
    tokens: ["Prosím", ",", "sadnite", "si", "."],
  },
  [phraseKey("prepáč", "a0-29")]: {
    sk: "Prepáč, meškám.",
    ua: "Вибач, я запізнився.",
    ru: "Извини, я опоздал.",
    en: "Sorry, I am late.",
    tokens: ["Prepáč", ",", "meškám", "."],
  },
  [phraseKey("rozumiem", "a0-29")]: {
    sk: "Rozumiem všetko.",
    ua: "Я все розумію.",
    ru: "Я всё понимаю.",
    en: "I understand everything.",
    tokens: ["Rozumiem", "všetko", "."],
  },
  [phraseKey("nerozumiem", "a0-29")]: {
    sk: "Nerozumiem tej otázke.",
    ua: "Я не розумію цього питання.",
    ru: "Я не понимаю этот вопрос.",
    en: "I do not understand the question.",
    tokens: ["Nerozumiem", "tej", "otázke", "."],
  },
  [phraseKey("pomôžte", "a0-29")]: {
    sk: "Pomôžte mi, prosím.",
    ua: "Допоможіть мені, будь ласка.",
    ru: "Помогите мне, пожалуйста.",
    en: "Help me, please.",
    tokens: ["Pomôžte", "mi", ",", "prosím", "."],
  },
  [phraseKey("jasné", "a0-29")]: {
    sk: "Jasné, súhlasím.",
    ua: "Ясно, я згоден.",
    ru: "Ясно, я согласен.",
    en: "Sure, I agree.",
    tokens: ["Jasné", ",", "súhlasím", "."],
  },
  [phraseKey("dobre", "a0-29")]: {
    sk: "Dobre, poďme.",
    ua: "Добре, ходімо.",
    ru: "Хорошо, пойдём.",
    en: "Okay, let's go.",
    tokens: ["Dobre", ",", "poďme", "."],
  },

  // =========================
  // LESSON 30 — Základ
  // =========================
  [phraseKey("ja", "a0-30")]: {
    sk: "Ja som tu.",
    ua: "Я тут.",
    ru: "Я здесь.",
    en: "I am here.",
    tokens: ["Ja", "som", "tu", "."],
  },
  [phraseKey("ty", "a0-30")]: {
    sk: "Ty si môj priateľ.",
    ua: "Ти мій друг.",
    ru: "Ты мой друг.",
    en: "You are my friend.",
    tokens: ["Ty", "si", "môj", "priateľ", "."],
  },
  [phraseKey("on", "a0-30")]: {
    sk: "On pracuje dnes.",
    ua: "Він працює сьогодні.",
    ru: "Он работает сегодня.",
    en: "He works today.",
    tokens: ["On", "pracuje", "dnes", "."],
  },
  [phraseKey("ona", "a0-30")]: {
    sk: "Ona je doma.",
    ua: "Вона вдома.",
    ru: "Она дома.",
    en: "She is at home.",
    tokens: ["Ona", "je", "doma", "."],
  },
  [phraseKey("my", "a0-30")]: {
    sk: "My ideme do mesta.",
    ua: "Ми йдемо до міста.",
    ru: "Мы идём в город.",
    en: "We are going to the city.",
    tokens: ["My", "ideme", "do", "mesta", "."],
  },
  [phraseKey("vy", "a0-30")]: {
    sk: "Vy ste pripravení?",
    ua: "Ви готові?",
    ru: "Вы готовы?",
    en: "Are you ready?",
    tokens: ["Vy", "ste", "pripravení", "?"],
  },
  [phraseKey("oni", "a0-30")]: {
    sk: "Oni bývajú blízko.",
    ua: "Вони живуть близько.",
    ru: "Они живут рядом.",
    en: "They live nearby.",
    tokens: ["Oni", "bývajú", "blízko", "."],
  },
  [phraseKey("byť", "a0-30")]: {
    sk: "Chcem byť doma.",
    ua: "Я хочу бути вдома.",
    ru: "Я хочу быть дома.",
    en: "I want to be at home.",
    tokens: ["Chcem", "byť", "doma", "."],
  },
  [phraseKey("mať", "a0-30")]: {
    sk: "Mám čas.",
    ua: "Я маю час.",
    ru: "У меня есть время.",
    en: "I have time.",
    tokens: ["Mám", "čas", "."],
  },
  [phraseKey("ísť", "a0-30")]: {
    sk: "Idem do práce.",
    ua: "Я йду на роботу.",
    ru: "Я иду на работу.",
    en: "I am going to work.",
    tokens: ["Idem", "do", "práce", "."],
  },
};