import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const B2_BUILD_UA_SENTENCES_4: BuildUaSentenceDict = {
  // =========================
  // LESSON 16 — Ovocie
  // =========================
  [phraseKey("jablko", "b2-16")]: {
    sk: "Na desiatu som si vzal čerstvé jablko.",
    ua: "На перекус я взяв свіже яблуко.",
    ru: "На перекус я взял свежее яблоко.",
    en: "I took a fresh apple for a snack.",
    uaTokens: ["На", "перекус", "я", "взяв", "свіже", "яблуко", "."],
    ruTokens: ["На", "перекус", "я", "взял", "свежее", "яблоко", "."],
    enTokens: ["I", "took", "a", "fresh", "apple", "for", "a", "snack", "."],
    extraUaTokens: ["сьогодні", "вранці", "велике"],
    extraRuTokens: ["сегодня", "утром", "большое"],
    extraEnTokens: ["today", "morning", "big"],
  },

  [phraseKey("hruška", "b2-16")]: {
    sk: "Táto hruška je mäkká, sladká a veľmi chutná.",
    ua: "Ця груша м’яка, солодка і дуже смачна.",
    ru: "Эта груша мягкая, сладкая и очень вкусная.",
    en: "This pear is soft, sweet, and very tasty.",
    uaTokens: ["Ця", "груша", "м’яка", ",", "солодка", "і", "дуже", "смачна", "."],
    ruTokens: ["Эта", "груша", "мягкая", ",", "сладкая", "и", "очень", "вкусная", "."],
    enTokens: ["This", "pear", "is", "soft", ",", "sweet", ",", "and", "very", "tasty", "."],
    extraUaTokens: ["сьогодні", "справді", "жовта"],
    extraRuTokens: ["сегодня", "правда", "жёлтая"],
    extraEnTokens: ["today", "really", "yellow"],
  },

  [phraseKey("broskyňa", "b2-16")]: {
    sk: "Do koláča sme nakrájali aj zrelú broskyňu.",
    ua: "До пирога ми також нарізали стиглий персик.",
    ru: "В пирог мы также нарезали спелый персик.",
    en: "We also sliced a ripe peach into the pie.",
    uaTokens: ["До", "пирога", "ми", "також", "нарізали", "стиглий", "персик", "."],
    ruTokens: ["В", "пирог", "мы", "также", "нарезали", "спелый", "персик", "."],
    enTokens: ["We", "also", "sliced", "a", "ripe", "peach", "into", "the", "pie", "."],
    uaAltAnswers: [["До", "пирога", "ми", "нарізали", "також", "стиглий", "персик", "."]],
    ruAltAnswers: [["В", "пирог", "мы", "нарезали", "также", "спелый", "персик", "."]],
    extraUaTokens: ["солодкий", "сьогодні", "акуратно"],
    extraRuTokens: ["сладкий", "сегодня", "аккуратно"],
    extraEnTokens: ["sweet", "today", "carefully"],
  },

  [phraseKey("marhuľa", "b2-16")]: {
    sk: "Marhuľa chutí najlepšie, keď je čerstvo odtrhnutá.",
    ua: "Абрикос найкраще смакує, коли його щойно зірвали.",
    ru: "Абрикос вкуснее всего, когда он только что сорван.",
    en: "An apricot tastes best when it has just been picked.",
    uaTokens: ["Абрикос", "найкраще", "смакує", ",", "коли", "його", "щойно", "зірвали", "."],
    ruTokens: ["Абрикос", "вкуснее", "всего", ",", "когда", "он", "только", "что", "сорван", "."],
    enTokens: ["An", "apricot", "tastes", "best", ",", "when", "it", "has", "just", "been", "picked", "."],
    extraUaTokens: ["сьогодні", "вранці", "в саду"],
    extraRuTokens: ["сегодня", "утром", "саду"],
    extraEnTokens: ["today", "morning", "garden"],
  },

  [phraseKey("slivka", "b2-16")]: {
    sk: "Zo sliviek sa dá pripraviť výborný džem.",
    ua: "Із слив можна приготувати чудове варення.",
    ru: "Из слив можно приготовить отличный джем.",
    en: "Excellent jam can be made from plums.",
    uaTokens: ["Із", "слив", "можна", "приготувати", "чудове", "варення", "."],
    ruTokens: ["Из", "слив", "можно", "приготовить", "отличный", "джем", "."],
    enTokens: ["Excellent", "jam", "can", "be", "made", "from", "plums", "."],
    extraUaTokens: ["домашнє", "солодке", "легко"],
    extraRuTokens: ["домашний", "сладкий", "легко"],
    extraEnTokens: ["homemade", "sweet", "easily"],
  },

  [phraseKey("čučoriedka", "b2-16")]: {
    sk: "Čučoriedky sú bohaté na vitamíny a antioxidanty.",
    ua: "Чорниці багаті на вітаміни й антиоксиданти.",
    ru: "Черника богата витаминами и антиоксидантами.",
    en: "Blueberries are rich in vitamins and antioxidants.",
    uaTokens: ["Чорниці", "багаті", "на", "вітаміни", "й", "антиоксиданти", "."],
    ruTokens: ["Черника", "богата", "витаминами", "и", "антиоксидантами", "."],
    enTokens: ["Blueberries", "are", "rich", "in", "vitamins", "and", "antioxidants", "."],
    extraUaTokens: ["дуже", "корисні", "також"],
    extraRuTokens: ["очень", "полезна", "тоже"],
    extraEnTokens: ["very", "healthy", "also"],
  },

  [phraseKey("malina", "b2-16")]: {
    sk: "Maliny zbierame skoro ráno, kým sú ešte chladné.",
    ua: "Малину ми збираємо рано-вранці, поки вона ще прохолодна.",
    ru: "Малину мы собираем рано утром, пока она ещё прохладная.",
    en: "We pick raspberries early in the morning while they are still cool.",
    uaTokens: ["Малину", "ми", "збираємо", "рано-вранці", ",", "поки", "вона", "ще", "прохолодна", "."],
    ruTokens: ["Малину", "мы", "собираем", "рано", "утром", ",", "пока", "она", "ещё", "прохладная", "."],
    enTokens: ["We", "pick", "raspberries", "early", "in", "the", "morning", ",", "while", "they", "are", "still", "cool", "."],
    extraUaTokens: ["у", "саду", "завжди"],
    extraRuTokens: ["в", "саду", "всегда"],
    extraEnTokens: ["garden", "always", "there"],
  },

  [phraseKey("ananás", "b2-16")]: {
    sk: "Ananás dodáva nápojom sviežu tropickú chuť.",
    ua: "Ананас надає напоям свіжого тропічного смаку.",
    ru: "Ананас придаёт напиткам свежий тропический вкус.",
    en: "Pineapple gives drinks a fresh tropical taste.",
    uaTokens: ["Ананас", "надає", "напоям", "свіжого", "тропічного", "смаку", "."],
    ruTokens: ["Ананас", "придаёт", "напиткам", "свежий", "тропический", "вкус", "."],
    enTokens: ["Pineapple", "gives", "drinks", "a", "fresh", "tropical", "taste", "."],
    extraUaTokens: ["дуже", "приємного", "аромату"],
    extraRuTokens: ["очень", "приятного", "аромата"],
    extraEnTokens: ["very", "pleasant", "aroma"],
  },

  [phraseKey("mango", "b2-16")]: {
    sk: "Zrelé mango je sladké a príjemne voňavé.",
    ua: "Стигле манго солодке й приємно пахне.",
    ru: "Спелое манго сладкое и приятно пахнет.",
    en: "A ripe mango is sweet and smells pleasant.",
    uaTokens: ["Стигле", "манго", "солодке", "й", "приємно", "пахне", "."],
    ruTokens: ["Спелое", "манго", "сладкое", "и", "приятно", "пахнет", "."],
    enTokens: ["A", "ripe", "mango", "is", "sweet", "and", "smells", "pleasant", "."],
    extraUaTokens: ["дуже", "сьогодні", "свіже"],
    extraRuTokens: ["очень", "сегодня", "свежее"],
    extraEnTokens: ["very", "today", "fresh"],
  },

  [phraseKey("melón", "b2-16")]: {
    sk: "V horúčave najradšej jem studený melón.",
    ua: "У спеку я найбільше люблю їсти холодний кавун.",
    ru: "В жару я больше всего люблю есть холодный арбуз.",
    en: "In hot weather, I like eating cold watermelon most of all.",
    uaTokens: ["У", "спеку", "я", "найбільше", "люблю", "їсти", "холодний", "кавун", "."],
    ruTokens: ["В", "жару", "я", "больше", "всего", "люблю", "есть", "холодный", "арбуз", "."],
    enTokens: ["In", "hot", "weather", ",", "I", "like", "eating", "cold", "watermelon", "most", "of", "all", "."],
    extraUaTokens: ["влітку", "дуже", "часто"],
    extraRuTokens: ["летом", "очень", "часто"],
    extraEnTokens: ["summer", "very", "often"],
  },

  // =========================
  // LESSON 17 — Zelenina
  // =========================
  [phraseKey("mrkva", "b2-17")]: {
    sk: "Do polievky som nakrájal aj čerstvú mrkvu.",
    ua: "До супу я нарізав також свіжу моркву.",
    ru: "В суп я также нарезал свежую морковь.",
    en: "I also sliced fresh carrots into the soup.",
    uaTokens: ["До", "супу", "я", "нарізав", "також", "свіжу", "моркву", "."],
    ruTokens: ["В", "суп", "я", "также", "нарезал", "свежую", "морковь", "."],
    enTokens: ["I", "also", "sliced", "fresh", "carrots", "into", "the", "soup", "."],
    uaAltAnswers: [["До", "супу", "я", "також", "нарізав", "свіжу", "моркву", "."]],
    ruAltAnswers: [["В", "суп", "я", "нарезал", "также", "свежую", "морковь", "."]],
    extraUaTokens: ["сьогодні", "дрібно", "ще"],
    extraRuTokens: ["сегодня", "мелко", "ещё"],
    extraEnTokens: ["today", "finely", "more"],
  },

  [phraseKey("uhorka", "b2-17")]: {
    sk: "Uhorka je v lete výborná do šalátu.",
    ua: "Огірок улітку чудово підходить для салату.",
    ru: "Огурец летом отлично подходит для салата.",
    en: "Cucumber is excellent in salads in summer.",
    uaTokens: ["Огірок", "улітку", "чудово", "підходить", "для", "салату", "."],
    ruTokens: ["Огурец", "летом", "отлично", "подходит", "для", "салата", "."],
    enTokens: ["Cucumber", "is", "excellent", "in", "salads", "in", "summer", "."],
    extraUaTokens: ["свіжого", "дуже", "завжди"],
    extraRuTokens: ["свежего", "очень", "всегда"],
    extraEnTokens: ["fresh", "very", "always"],
  },

  [phraseKey("paradajka", "b2-17")]: {
    sk: "Záhradná paradajka chutí lepšie než tá z obchodu.",
    ua: "Домашній помідор смакує краще, ніж той із магазину.",
    ru: "Домашний помидор вкуснее, чем тот, что из магазина.",
    en: "A homegrown tomato tastes better than one from the store.",
    uaTokens: ["Домашній", "помідор", "смакує", "краще", ",", "ніж", "той", "із", "магазину", "."],
    ruTokens: ["Домашний", "помидор", "вкуснее", ",", "чем", "тот", "что", "из", "магазина", "."],
    enTokens: ["A", "homegrown", "tomato", "tastes", "better", "than", "one", "from", "the", "store", "."],
    extraUaTokens: ["набагато", "влітку", "свіжіше"],
    extraRuTokens: ["намного", "летом", "свежее"],
    extraEnTokens: ["much", "summer", "fresher"],
  },

  [phraseKey("paprika", "b2-17")]: {
    sk: "Červená paprika je sladšia než zelená.",
    ua: "Червоний перець солодший за зелений.",
    ru: "Красный перец слаще зелёного.",
    en: "Red pepper is sweeter than green pepper.",
    uaTokens: ["Червоний", "перець", "солодший", "за", "зелений", "."],
    ruTokens: ["Красный", "перец", "слаще", "зелёного", "."],
    enTokens: ["Red", "pepper", "is", "sweeter", "than", "green", "pepper", "."],
    extraUaTokens: ["набагато", "часто", "соковитіший"],
    extraRuTokens: ["намного", "часто", "сочнее"],
    extraEnTokens: ["much", "often", "juicier"],
  },

  [phraseKey("zemiak", "b2-17")]: {
    sk: "Pečený zemiak je jednoduchý, ale veľmi chutný.",
    ua: "Запечена картопля проста, але дуже смачна.",
    ru: "Запечённый картофель прост, но очень вкусен.",
    en: "A baked potato is simple but very tasty.",
    uaTokens: ["Запечена", "картопля", "проста", ",", "але", "дуже", "смачна", "."],
    ruTokens: ["Запечённый", "картофель", "прост", ",", "но", "очень", "вкусен", "."],
    enTokens: ["A", "baked", "potato", "is", "simple", "but", "very", "tasty", "."],
    extraUaTokens: ["вдома", "сьогодні", "гаряча"],
    extraRuTokens: ["дома", "сегодня", "горячая"],
    extraEnTokens: ["home", "today", "hot"],
  },

  [phraseKey("cibuľa", "b2-17")]: {
    sk: "Bez cibule si túto omáčku neviem predstaviť.",
    ua: "Без цибулі я не уявляю цього соусу.",
    ru: "Без лука я не представляю этот соус.",
    en: "I cannot imagine this sauce without onion.",
    uaTokens: ["Без", "цибулі", "я", "не", "уявляю", "цього", "соусу", "."],
    ruTokens: ["Без", "лука", "я", "не", "представляю", "этот", "соус", "."],
    enTokens: ["I", "cannot", "imagine", "this", "sauce", "without", "onion", "."],
    extraUaTokens: ["взагалі", "сьогодні", "смачний"],
    extraRuTokens: ["вообще", "сегодня", "вкусный"],
    extraEnTokens: ["at", "all", "tasty"],
  },

  [phraseKey("cesnak", "b2-17")]: {
    sk: "Cesnak dodáva jedlu silnú a typickú arómu.",
    ua: "Часник надає страві сильного й характерного аромату.",
    ru: "Чеснок придаёт блюду сильный и характерный аромат.",
    en: "Garlic gives the dish a strong and distinctive aroma.",
    uaTokens: ["Часник", "надає", "страві", "сильного", "й", "характерного", "аромату", "."],
    ruTokens: ["Чеснок", "придаёт", "блюду", "сильный", "и", "характерный", "аромат", "."],
    enTokens: ["Garlic", "gives", "the", "dish", "a", "strong", "and", "distinctive", "aroma", "."],
    extraUaTokens: ["дуже", "приємного", "сьогодні"],
    extraRuTokens: ["очень", "приятного", "сегодня"],
    extraEnTokens: ["very", "pleasant", "today"],
  },

  [phraseKey("baklažán", "b2-17")]: {
    sk: "Baklažán chutí výborne najmä grilovaný.",
    ua: "Баклажан особливо смачний на грилі.",
    ru: "Баклажан особенно вкусен на гриле.",
    en: "Eggplant tastes especially good when grilled.",
    uaTokens: ["Баклажан", "особливо", "смачний", "на", "грилі", "."],
    ruTokens: ["Баклажан", "особенно", "вкусен", "на", "гриле", "."],
    enTokens: ["Eggplant", "tastes", "especially", "good", "when", "grilled", "."],
    extraUaTokens: ["влітку", "дуже", "ароматний"],
    extraRuTokens: ["летом", "очень", "ароматный"],
    extraEnTokens: ["summer", "very", "aromatic"],
  },

  [phraseKey("cuketa", "b2-17")]: {
    sk: "Z cukety sa dajú pripraviť aj veľmi ľahké jedlá.",
    ua: "З кабачка можна приготувати також дуже легкі страви.",
    ru: "Из кабачка можно приготовить и очень лёгкие блюда.",
    en: "Very light dishes can also be prepared from zucchini.",
    uaTokens: ["З", "кабачка", "можна", "приготувати", "також", "дуже", "легкі", "страви", "."],
    ruTokens: ["Из", "кабачка", "можно", "приготовить", "и", "очень", "лёгкие", "блюда", "."],
    enTokens: ["Very", "light", "dishes", "can", "also", "be", "prepared", "from", "zucchini", "."],
    extraUaTokens: ["вдома", "швидко", "смачно"],
    extraRuTokens: ["дома", "быстро", "вкусно"],
    extraEnTokens: ["home", "quickly", "tastily"],
  },

  [phraseKey("kapusta", "b2-17")]: {
    sk: "Kapusta je dôležitou súčasťou mnohých tradičných jedál.",
    ua: "Капуста є важливою частиною багатьох традиційних страв.",
    ru: "Капуста — важная часть многих традиционных блюд.",
    en: "Cabbage is an important part of many traditional dishes.",
    uaTokens: ["Капуста", "є", "важливою", "частиною", "багатьох", "традиційних", "страв", "."],
    ruTokens: ["Капуста", "—", "важная", "часть", "многих", "традиционных", "блюд", "."],
    enTokens: ["Cabbage", "is", "an", "important", "part", "of", "many", "traditional", "dishes", "."],
    extraUaTokens: ["у", "нас", "завжди"],
    extraRuTokens: ["у", "нас", "всегда"],
    extraEnTokens: ["with", "us", "always"],
  },

  // =========================
  // LESSON 18 — Nápoje
  // =========================
  [phraseKey("minerálna voda", "b2-18")]: {
    sk: "K obedu si dám len minerálnu vodu.",
    ua: "На обід я візьму лише мінеральну воду.",
    ru: "К обеду я возьму только минеральную воду.",
    en: "For lunch, I will only have mineral water.",
    uaTokens: ["На", "обід", "я", "візьму", "лише", "мінеральну", "воду", "."],
    ruTokens: ["К", "обеду", "я", "возьму", "только", "минеральную", "воду", "."],
    enTokens: ["For", "lunch", ",", "I", "will", "only", "have", "mineral", "water", "."],
    extraUaTokens: ["сьогодні", "холодну", "свіжу"],
    extraRuTokens: ["сегодня", "холодную", "свежую"],
    extraEnTokens: ["today", "cold", "fresh"],
  },

  [phraseKey("džús", "b2-18")]: {
    sk: "Ráno si rád dám čerstvý pomarančový džús.",
    ua: "Вранці я люблю випити свіжий апельсиновий сік.",
    ru: "Утром я люблю выпить свежий апельсиновый сок.",
    en: "In the morning, I like to drink fresh orange juice.",
    uaTokens: ["Вранці", "я", "люблю", "випити", "свіжий", "апельсиновий", "сік", "."],
    ruTokens: ["Утром", "я", "люблю", "выпить", "свежий", "апельсиновый", "сок", "."],
    enTokens: ["In", "the", "morning", ",", "I", "like", "to", "drink", "fresh", "orange", "juice", "."],
    extraUaTokens: ["часто", "дуже", "солодкий"],
    extraRuTokens: ["часто", "очень", "сладкий"],
    extraEnTokens: ["often", "very", "sweet"],
  },

  [phraseKey("čaj", "b2-18")]: {
    sk: "Keď som chorý, najradšej pijem horúci čaj s medom.",
    ua: "Коли я хворий, найбільше люблю пити гарячий чай із медом.",
    ru: "Когда я болею, больше всего люблю пить горячий чай с мёдом.",
    en: "When I am sick, I like drinking hot tea with honey the most.",
    uaTokens: ["Коли", "я", "хворий", ",", "найбільше", "люблю", "пити", "гарячий", "чай", "із", "медом", "."],
    ruTokens: ["Когда", "я", "болею", ",", "больше", "всего", "люблю", "пить", "горячий", "чай", "с", "мёдом", "."],
    enTokens: ["When", "I", "am", "sick", ",", "I", "like", "drinking", "hot", "tea", "with", "honey", "the", "most", "."],
    extraUaTokens: ["взимку", "дуже", "часто"],
    extraRuTokens: ["зимой", "очень", "часто"],
    extraEnTokens: ["winter", "very", "often"],
  },

  [phraseKey("káva", "b2-18")]: {
    sk: "Bez rannej kávy sa mi ťažko začína deň.",
    ua: "Без ранкової кави мені важко почати день.",
    ru: "Без утреннего кофе мне трудно начать день.",
    en: "Without morning coffee, it is hard for me to start the day.",
    uaTokens: ["Без", "ранкової", "кави", "мені", "важко", "почати", "день", "."],
    ruTokens: ["Без", "утреннего", "кофе", "мне", "трудно", "начать", "день", "."],
    enTokens: ["Without", "morning", "coffee", ",", "it", "is", "hard", "for", "me", "to", "start", "the", "day", "."],
    extraUaTokens: ["сьогодні", "взагалі", "нормально"],
    extraRuTokens: ["сегодня", "вообще", "нормально"],
    extraEnTokens: ["today", "at", "all"],
  },

  [phraseKey("espresso", "b2-18")]: {
    sk: "Po obede si zvyknem objednať malé espresso.",
    ua: "Після обіду я зазвичай замовляю маленьке еспресо.",
    ru: "После обеда я обычно заказываю маленький эспрессо.",
    en: "After lunch, I usually order a small espresso.",
    uaTokens: ["Після", "обіду", "я", "зазвичай", "замовляю", "маленьке", "еспресо", "."],
    ruTokens: ["После", "обеда", "я", "обычно", "заказываю", "маленький", "эспрессо", "."],
    enTokens: ["After", "lunch", ",", "I", "usually", "order", "a", "small", "espresso", "."],
    extraUaTokens: ["у", "кафе", "часто"],
    extraRuTokens: ["в", "кафе", "часто"],
    extraEnTokens: ["in", "cafe", "often"],
  },

  [phraseKey("cappuccino", "b2-18")]: {
    sk: "V tejto kaviarni pripravujú výborné cappuccino.",
    ua: "У цій кав’ярні готують чудове капучино.",
    ru: "В этом кафе готовят отличное капучино.",
    en: "They make excellent cappuccino in this café.",
    uaTokens: ["У", "цій", "кав’ярні", "готують", "чудове", "капучино", "."],
    ruTokens: ["В", "этом", "кафе", "готовят", "отличное", "капучино", "."],
    enTokens: ["They", "make", "excellent", "cappuccino", "in", "this", "café", "."],
    extraUaTokens: ["дуже", "пінне", "сьогодні"],
    extraRuTokens: ["очень", "пенное", "сегодня"],
    extraEnTokens: ["very", "foamy", "today"],
  },

  [phraseKey("limonáda", "b2-18")]: {
    sk: "V horúcom počasí najlepšie osvieži domáca limonáda.",
    ua: "У спекотну погоду найкраще освіжає домашній лимонад.",
    ru: "В жаркую погоду лучше всего освежает домашний лимонад.",
    en: "In hot weather, homemade lemonade refreshes best.",
    uaTokens: ["У", "спекотну", "погоду", "найкраще", "освіжає", "домашній", "лимонад", "."],
    ruTokens: ["В", "жаркую", "погоду", "лучше", "всего", "освежает", "домашний", "лимонад", "."],
    enTokens: ["In", "hot", "weather", ",", "homemade", "lemonade", "refreshes", "best", "."],
    extraUaTokens: ["холодний", "з", "льодом"],
    extraRuTokens: ["холодный", "со", "льдом"],
    extraEnTokens: ["cold", "with", "ice"],
  },

  [phraseKey("pivo", "b2-18")]: {
    sk: "Večer si dal jedno malé pivo.",
    ua: "Увечері він випив одне маленьке пиво.",
    ru: "Вечером он выпил одно маленькое пиво.",
    en: "In the evening, he drank one small beer.",
    uaTokens: ["Увечері", "він", "випив", "одне", "маленьке", "пиво", "."],
    ruTokens: ["Вечером", "он", "выпил", "одно", "маленькое", "пиво", "."],
    enTokens: ["In", "the", "evening", ",", "he", "drank", "one", "small", "beer", "."],
    extraUaTokens: ["холодне", "після", "роботи"],
    extraRuTokens: ["холодное", "после", "работы"],
    extraEnTokens: ["cold", "after", "work"],
  },

  [phraseKey("víno", "b2-18")]: {
    sk: "K syru sa výborne hodí biele víno.",
    ua: "До сиру чудово пасує біле вино.",
    ru: "К сыру отлично подходит белое вино.",
    en: "White wine goes excellently with cheese.",
    uaTokens: ["До", "сиру", "чудово", "пасує", "біле", "вино", "."],
    ruTokens: ["К", "сыру", "отлично", "подходит", "белое", "вино", "."],
    enTokens: ["White", "wine", "goes", "excellently", "with", "cheese", "."],
    extraUaTokens: ["сухе", "легке", "сьогодні"],
    extraRuTokens: ["сухое", "лёгкое", "сегодня"],
    extraEnTokens: ["dry", "light", "today"],
  },

  [phraseKey("koktail", "b2-18")]: {
    sk: "Na oslave nám pripravili ovocný koktail bez alkoholu.",
    ua: "На святі нам приготували фруктовий коктейль без алкоголю.",
    ru: "На празднике нам приготовили фруктовый коктейль без алкоголя.",
    en: "At the celebration, they made us a fruit cocktail without alcohol.",
    uaTokens: ["На", "святі", "нам", "приготували", "фруктовий", "коктейль", "без", "алкоголю", "."],
    ruTokens: ["На", "празднике", "нам", "приготовили", "фруктовый", "коктейль", "без", "алкоголя", "."],
    enTokens: ["At", "the", "celebration", ",", "they", "made", "us", "a", "fruit", "cocktail", "without", "alcohol", "."],
    extraUaTokens: ["смачний", "дуже", "солодкий"],
    extraRuTokens: ["вкусный", "очень", "сладкий"],
    extraEnTokens: ["tasty", "very", "sweet"],
  },

  // =========================
  // LESSON 19 — Emócie a vnútorný stav
  // =========================
  [phraseKey("úzkosť", "b2-19")]: {
    sk: "Pred dôležitým vystúpením cítil silnú úzkosť.",
    ua: "Перед важливим виступом він відчував сильну тривогу.",
    ru: "Перед важным выступлением он чувствовал сильную тревогу.",
    en: "Before the important performance, he felt strong anxiety.",
    uaTokens: ["Перед", "важливим", "виступом", "він", "відчував", "сильну", "тривогу", "."],
    ruTokens: ["Перед", "важным", "выступлением", "он", "чувствовал", "сильную", "тревогу", "."],
    enTokens: ["Before", "the", "important", "performance", ",", "he", "felt", "strong", "anxiety", "."],
    extraUaTokens: ["дуже", "сьогодні", "вранці"],
    extraRuTokens: ["очень", "сегодня", "утром"],
    extraEnTokens: ["very", "today", "morning"],
  },

  [phraseKey("sklamanie", "b2-19")]: {
    sk: "Po neúspechu bolo na jej tvári vidieť veľké sklamanie.",
    ua: "Після невдачі на її обличчі було видно велике розчарування.",
    ru: "После неудачи на её лице было видно большое разочарование.",
    en: "After the failure, great disappointment could be seen on her face.",
    uaTokens: ["Після", "невдачі", "на", "її", "обличчі", "було", "видно", "велике", "розчарування", "."],
    ruTokens: ["После", "неудачи", "на", "её", "лице", "было", "видно", "большое", "разочарование", "."],
    enTokens: ["After", "the", "failure", ",", "great", "disappointment", "could", "be", "seen", "on", "her", "face", "."],
    extraUaTokens: ["одразу", "дуже", "сильно"],
    extraRuTokens: ["сразу", "очень", "сильно"],
    extraEnTokens: ["immediately", "very", "strongly"],
  },

  [phraseKey("dojatie", "b2-19")]: {
    sk: "Jeho príhovor v nej vyvolal silné dojatie.",
    ua: "Його промова викликала в неї сильне зворушення.",
    ru: "Его речь вызвала в ней сильное душевное волнение.",
    en: "His speech caused deep emotion in her.",
    uaTokens: ["Його", "промова", "викликала", "в", "неї", "сильне", "зворушення", "."],
    ruTokens: ["Его", "речь", "вызвала", "в", "ней", "сильное", "душевное", "волнение", "."],
    enTokens: ["His", "speech", "caused", "deep", "emotion", "in", "her", "."],
    extraUaTokens: ["майже", "одразу", "сльози"],
    extraRuTokens: ["почти", "сразу", "слёзы"],
    extraEnTokens: ["almost", "immediately", "tears"],
  },

  [phraseKey("odľahčenie", "b2-19")]: {
    sk: "Po vyriešení problému pocítil veľké odľahčenie.",
    ua: "Після вирішення проблеми він відчув велике полегшення.",
    ru: "После решения проблемы он почувствовал большое облегчение.",
    en: "After solving the problem, he felt great relief.",
    uaTokens: ["Після", "вирішення", "проблеми", "він", "відчув", "велике", "полегшення", "."],
    ruTokens: ["После", "решения", "проблемы", "он", "почувствовал", "большое", "облегчение", "."],
    enTokens: ["After", "solving", "the", "problem", ",", "he", "felt", "great", "relief", "."],
    extraUaTokens: ["нарешті", "дуже", "сильне"],
    extraRuTokens: ["наконец", "очень", "сильное"],
    extraEnTokens: ["finally", "very", "strong"],
  },

  [phraseKey("znechutenie", "b2-19")]: {
    sk: "Pri pohľade na tú nespravodlivosť cítila znechutenie.",
    ua: "Побачивши цю несправедливість, вона відчула відразу.",
    ru: "Увидев эту несправедливость, она почувствовала отвращение.",
    en: "Seeing that injustice, she felt disgust.",
    uaTokens: ["Побачивши", "цю", "несправедливість", ",", "вона", "відчула", "відразу", "."],
    ruTokens: ["Увидев", "эту", "несправедливость", ",", "она", "почувствовала", "отвращение", "."],
    enTokens: ["Seeing", "that", "injustice", ",", "she", "felt", "disgust", "."],
    extraUaTokens: ["сильну", "дуже", "одразу"],
    extraRuTokens: ["сильное", "очень", "сразу"],
    extraEnTokens: ["strong", "very", "immediately"],
  },

  [phraseKey("rozladený", "b2-19")]: {
    sk: "Po hádke bol celý večer rozladený.",
    ua: "Після сварки він увесь вечір був засмучений і роздратований.",
    ru: "После ссоры он весь вечер был расстроенным и раздражённым.",
    en: "After the argument, he was upset and irritated all evening.",
    uaTokens: ["Після", "сварки", "він", "увесь", "вечір", "був", "засмучений", "і", "роздратований", "."],
    ruTokens: ["После", "ссоры", "он", "весь", "вечер", "был", "расстроенным", "и", "раздражённым", "."],
    enTokens: ["After", "the", "argument", ",", "he", "was", "upset", "and", "irritated", "all", "evening", "."],
    extraUaTokens: ["дуже", "ще", "довго"],
    extraRuTokens: ["очень", "ещё", "долго"],
    extraEnTokens: ["very", "still", "long"],
  },

  [phraseKey("vyčerpanosť", "b2-19")]: {
    sk: "Na konci týždňa už cítila úplnú vyčerpanosť.",
    ua: "Наприкінці тижня вона вже відчувала повне виснаження.",
    ru: "В конце недели она уже чувствовала полное истощение.",
    en: "By the end of the week, she already felt complete exhaustion.",
    uaTokens: ["Наприкінці", "тижня", "вона", "вже", "відчувала", "повне", "виснаження", "."],
    ruTokens: ["В", "конце", "недели", "она", "уже", "чувствовала", "полное", "истощение", "."],
    enTokens: ["By", "the", "end", "of", "the", "week", ",", "she", "already", "felt", "complete", "exhaustion", "."],
    extraUaTokens: ["дуже", "сильне", "всередині"],
    extraRuTokens: ["очень", "сильное", "внутри"],
    extraEnTokens: ["very", "strong", "inside"],
  },

  [phraseKey("citová reakcia", "b2-19")]: {
    sk: "Jeho citová reakcia bola silnejšia, než sme čakali.",
    ua: "Його емоційна реакція була сильнішою, ніж ми очікували.",
    ru: "Его эмоциональная реакция была сильнее, чем мы ожидали.",
    en: "His emotional reaction was stronger than we expected.",
    uaTokens: ["Його", "емоційна", "реакція", "була", "сильнішою", ",", "ніж", "ми", "очікували", "."],
    ruTokens: ["Его", "эмоциональная", "реакция", "была", "сильнее", ",", "чем", "мы", "ожидали", "."],
    enTokens: ["His", "emotional", "reaction", "was", "stronger", "than", "we", "expected", "."],
    extraUaTokens: ["набагато", "справді", "того"],
    extraRuTokens: ["намного", "правда", "того"],
    extraEnTokens: ["much", "really", "that"],
  },

  [phraseKey("duševná pohoda", "b2-19")]: {
    sk: "Pre duševnú pohodu je dôležitý oddych aj rovnováha.",
    ua: "Для душевного спокою важливі і відпочинок, і рівновага.",
    ru: "Для душевного спокойствия важны и отдых, и равновесие.",
    en: "For mental well-being, both rest and balance are important.",
    uaTokens: ["Для", "душевного", "спокою", "важливі", "і", "відпочинок", ",", "і", "рівновага", "."],
    ruTokens: ["Для", "душевного", "спокойствия", "важны", "и", "отдых", ",", "и", "равновесие", "."],
    enTokens: ["For", "mental", "well-being", ",", "both", "rest", "and", "balance", "are", "important", "."],
    extraUaTokens: ["щодня", "дуже", "потрібні"],
    extraRuTokens: ["ежедневно", "очень", "нужны"],
    extraEnTokens: ["daily", "very", "necessary"],
  },

  [phraseKey("potlačiť emócie", "b2-19")]: {
    sk: "Nie je vždy dobré potláčať emócie príliš dlho.",
    ua: "Не завжди добре занадто довго пригнічувати емоції.",
    ru: "Не всегда хорошо слишком долго подавлять эмоции.",
    en: "It is not always good to suppress emotions for too long.",
    uaTokens: ["Не", "завжди", "добре", "занадто", "довго", "пригнічувати", "емоції", "."],
    ruTokens: ["Не", "всегда", "хорошо", "слишком", "долго", "подавлять", "эмоции", "."],
    enTokens: ["It", "is", "not", "always", "good", "to", "suppress", "emotions", "for", "too", "long", "."],
    extraUaTokens: ["в", "собі", "постійно"],
    extraRuTokens: ["в", "себе", "постоянно"],
    extraEnTokens: ["inside", "yourself", "constantly"],
  },

  // =========================
  // LESSON 20 — Kultúra a umenie
  // =========================
  [phraseKey("umenie", "b2-20")]: {
    sk: "Moderné umenie v ňom vyvoláva veľa otázok.",
    ua: "Сучасне мистецтво викликає в нього багато запитань.",
    ru: "Современное искусство вызывает у него много вопросов.",
    en: "Modern art raises many questions for him.",
    uaTokens: ["Сучасне", "мистецтво", "викликає", "в", "нього", "багато", "запитань", "."],
    ruTokens: ["Современное", "искусство", "вызывает", "у", "него", "много", "вопросов", "."],
    enTokens: ["Modern", "art", "raises", "many", "questions", "for", "him", "."],
    extraUaTokens: ["різних", "дуже", "глибоких"],
    extraRuTokens: ["разных", "очень", "глубоких"],
    extraEnTokens: ["different", "very", "deep"],
  },

  [phraseKey("umelecké dielo", "b2-20")]: {
    sk: "Toto umelecké dielo zaujme hneď na prvý pohľad.",
    ua: "Цей твір мистецтва привертає увагу з першого погляду.",
    ru: "Это произведение искусства привлекает внимание с первого взгляда.",
    en: "This work of art catches attention at first glance.",
    uaTokens: ["Цей", "твір", "мистецтва", "привертає", "увагу", "з", "першого", "погляду", "."],
    ruTokens: ["Это", "произведение", "искусства", "привлекает", "внимание", "с", "первого", "взгляда", "."],
    enTokens: ["This", "work", "of", "art", "catches", "attention", "at", "first", "glance", "."],
    extraUaTokens: ["одразу", "дуже", "сильно"],
    extraRuTokens: ["сразу", "очень", "сильно"],
    extraEnTokens: ["immediately", "very", "strongly"],
  },

  [phraseKey("výstava", "b2-20")]: {
    sk: "Na výstave sme strávili viac než dve hodiny.",
    ua: "На виставці ми провели більше двох годин.",
    ru: "На выставке мы провели больше двух часов.",
    en: "We spent more than two hours at the exhibition.",
    uaTokens: ["На", "виставці", "ми", "провели", "більше", "двох", "годин", "."],
    ruTokens: ["На", "выставке", "мы", "провели", "больше", "двух", "часов", "."],
    enTokens: ["We", "spent", "more", "than", "two", "hours", "at", "the", "exhibition", "."],
    extraUaTokens: ["сьогодні", "майже", "разом"],
    extraRuTokens: ["сегодня", "почти", "вместе"],
    extraEnTokens: ["today", "almost", "together"],
  },

  [phraseKey("galéria", "b2-20")]: {
    sk: "Táto galéria je známa svojou modernou architektúrou.",
    ua: "Ця галерея відома своєю сучасною архітектурою.",
    ru: "Эта галерея известна своей современной архитектурой.",
    en: "This gallery is known for its modern architecture.",
    uaTokens: ["Ця", "галерея", "відома", "своєю", "сучасною", "архітектурою", "."],
    ruTokens: ["Эта", "галерея", "известна", "своей", "современной", "архитектурой", "."],
    enTokens: ["This", "gallery", "is", "known", "for", "its", "modern", "architecture", "."],
    extraUaTokens: ["дуже", "красивою", "зовні"],
    extraRuTokens: ["очень", "красивой", "снаружи"],
    extraEnTokens: ["very", "beautiful", "outside"],
  },

  [phraseKey("divadlo", "b2-20")]: {
    sk: "Do divadla chodíme najmä na historické predstavenia.",
    ua: "До театру ми ходимо переважно на історичні вистави.",
    ru: "В театр мы ходим в основном на исторические постановки.",
    en: "We mostly go to the theater for historical performances.",
    uaTokens: ["До", "театру", "ми", "ходимо", "переважно", "на", "історичні", "вистави", "."],
    ruTokens: ["В", "театр", "мы", "ходим", "в", "основном", "на", "исторические", "постановки", "."],
    enTokens: ["We", "mostly", "go", "to", "the", "theater", "for", "historical", "performances", "."],
    uaAltAnswers: [["До", "театру", "ми", "переважно", "ходимо", "на", "історичні", "вистави", "."]],
    ruAltAnswers: [["В", "театр", "мы", "в", "основном", "ходим", "на", "исторические", "постановки", "."]],
    extraUaTokens: ["разом", "увечері", "часто"],
    extraRuTokens: ["вместе", "вечером", "часто"],
    extraEnTokens: ["together", "evening", "often"],
  },

  [phraseKey("predstavenie", "b2-20")]: {
    sk: "Včerajšie predstavenie malo veľký úspech u publika.",
    ua: "Учорашня вистава мала великий успіх у публіки.",
    ru: "Вчерашнее представление имело большой успех у публики.",
    en: "Yesterday’s performance was a great success with the audience.",
    uaTokens: ["Учорашня", "вистава", "мала", "великий", "успіх", "у", "публіки", "."],
    ruTokens: ["Вчерашнее", "представление", "имело", "большой", "успех", "у", "публики", "."],
    enTokens: ["Yesterday’s", "performance", "was", "a", "great", "success", "with", "the", "audience", "."],
    extraUaTokens: ["справді", "дуже", "великий"],
    extraRuTokens: ["правда", "очень", "большой"],
    extraEnTokens: ["really", "very", "big"],
  },

  [phraseKey("publikum", "b2-20")]: {
    sk: "Publikum odmenilo hercov dlhým potleskom.",
    ua: "Публіка нагородила акторів довгими оплесками.",
    ru: "Публика наградила актёров долгими аплодисментами.",
    en: "The audience rewarded the actors with long applause.",
    uaTokens: ["Публіка", "нагородила", "акторів", "довгими", "оплесками", "."],
    ruTokens: ["Публика", "наградила", "актёров", "долгими", "аплодисментами", "."],
    enTokens: ["The", "audience", "rewarded", "the", "actors", "with", "long", "applause", "."],
    extraUaTokens: ["після", "кінця", "вистави"],
    extraRuTokens: ["после", "конца", "спектакля"],
    extraEnTokens: ["after", "end", "performance"],
  },

  [phraseKey("umelecký štýl", "b2-20")]: {
    sk: "Jeho umelecký štýl sa nedá s nikým pomýliť.",
    ua: "Його художній стиль неможливо ні з ким сплутати.",
    ru: "Его художественный стиль невозможно ни с кем спутать.",
    en: "His artistic style cannot be confused with anyone else’s.",
    uaTokens: ["Його", "художній", "стиль", "неможливо", "ні", "з", "ким", "сплутати", "."],
    ruTokens: ["Его", "художественный", "стиль", "невозможно", "ни", "с", "кем", "спутать", "."],
    enTokens: ["His", "artistic", "style", "cannot", "be", "confused", "with", "anyone", "else’s", "."],
    extraUaTokens: ["зовсім", "сьогодні", "легко"],
    extraRuTokens: ["совсем", "сегодня", "легко"],
    extraEnTokens: ["at", "all", "easily"],
  },

  [phraseKey("interpretácia", "b2-20")]: {
    sk: "Každá interpretácia tohto diela môže byť iná.",
    ua: "Кожна інтерпретація цього твору може бути іншою.",
    ru: "Каждая интерпретация этого произведения может быть иной.",
    en: "Each interpretation of this work may be different.",
    uaTokens: ["Кожна", "інтерпретація", "цього", "твору", "може", "бути", "іншою", "."],
    ruTokens: ["Каждая", "интерпретация", "этого", "произведения", "может", "быть", "иной", "."],
    enTokens: ["Each", "interpretation", "of", "this", "work", "may", "be", "different", "."],
    extraUaTokens: ["зовсім", "трохи", "сьогодні"],
    extraRuTokens: ["совсем", "немного", "сегодня"],
    extraEnTokens: ["completely", "slightly", "today"],
  },

  [phraseKey("kultúrny zážitok", "b2-20")]: {
    sk: "Bol to silný kultúrny zážitok, ktorý v nás zostane dlho.",
    ua: "Це був сильний культурний досвід, який надовго залишиться з нами.",
    ru: "Это был сильный культурный опыт, который надолго останется с нами.",
    en: "It was a powerful cultural experience that will stay with us for a long time.",
    uaTokens: ["Це", "був", "сильний", "культурний", "досвід", ",", "який", "надовго", "залишиться", "з", "нами", "."],
    ruTokens: ["Это", "был", "сильный", "культурный", "опыт", ",", "который", "надолго", "останется", "с", "нами", "."],
    enTokens: ["It", "was", "a", "powerful", "cultural", "experience", "that", "will", "stay", "with", "us", "for", "a", "long", "time", "."],
    uaAltAnswers: [["Це", "був", "сильний", "культурний", "досвід", ",", "який", "з", "нами", "надовго", "залишиться", "."]],
    ruAltAnswers: [["Это", "был", "сильный", "культурный", "опыт", ",", "который", "с", "нами", "надолго", "останется", "."]],
    extraUaTokens: ["справді", "дуже", "особливий"],
    extraRuTokens: ["правда", "очень", "особенный"],
    extraEnTokens: ["really", "very", "special"],
  },
};