import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const B2_BUILD_UA_SENTENCES_6: BuildUaSentenceDict = {
  // =========================
  // LESSON 26 — Psychológia človeka
  // =========================
  [phraseKey("sebareflexia", "b2-26")]: {
    sk: "Sebareflexia mu pomohla lepšie pochopiť vlastné chyby.",
    ua: "Саморефлексія допомогла йому краще зрозуміти власні помилки.",
    ru: "Саморефлексия помогла ему лучше понять собственные ошибки.",
    en: "Self-reflection helped him better understand his own mistakes.",
    uaTokens: ["Саморефлексія", "допомогла", "йому", "краще", "зрозуміти", "власні", "помилки", "."],
    ruTokens: ["Саморефлексия", "помогла", "ему", "лучше", "понять", "собственные", "ошибки", "."],
    enTokens: ["Self-reflection", "helped", "him", "better", "understand", "his", "own", "mistakes", "."],
    extraUaTokens: ["сьогодні", "глибше", "себе"],
    extraRuTokens: ["сегодня", "глубже", "себя"],
    extraEnTokens: ["today", "deeper", "himself"],
  },

  [phraseKey("vnútorný konflikt", "b2-26")]: {
    sk: "Prežíval silný vnútorný konflikt medzi rozumom a citmi.",
    ua: "Він переживав сильний внутрішній конфлікт між розумом і почуттями.",
    ru: "Он переживал сильный внутренний конфликт между разумом и чувствами.",
    en: "He was going through a strong inner conflict between reason and feelings.",
    uaTokens: ["Він", "переживав", "сильний", "внутрішній", "конфлікт", "між", "розумом", "і", "почуттями", "."],
    ruTokens: ["Он", "переживал", "сильный", "внутренний", "конфликт", "между", "разумом", "и", "чувствами", "."],
    enTokens: ["He", "was", "going", "through", "a", "strong", "inner", "conflict", "between", "reason", "and", "feelings", "."],
    extraUaTokens: ["довго", "дуже", "важкий"],
    extraRuTokens: ["долго", "очень", "тяжёлый"],
    extraEnTokens: ["for", "long", "difficult"],
  },

  [phraseKey("sebakontrola", "b2-26")]: {
    sk: "V stresových situáciách je dôležitá sebakontrola.",
    ua: "У стресових ситуаціях важливий самоконтроль.",
    ru: "В стрессовых ситуациях важен самоконтроль.",
    en: "In stressful situations, self-control is important.",
    uaTokens: ["У", "стресових", "ситуаціях", "важливий", "самоконтроль", "."],
    ruTokens: ["В", "стрессовых", "ситуациях", "важен", "самоконтроль", "."],
    enTokens: ["In", "stressful", "situations", ",", "self-control", "is", "important", "."],
    extraUaTokens: ["дуже", "сильний", "завжди"],
    extraRuTokens: ["очень", "сильный", "всегда"],
    extraEnTokens: ["very", "strong", "always"],
  },

  [phraseKey("duševná rovnováha", "b2-26")]: {
    sk: "Na duševnú rovnováhu vplýva práca aj oddych.",
    ua: "На душевну рівновагу впливають і робота, і відпочинок.",
    ru: "На душевное равновесие влияют и работа, и отдых.",
    en: "Both work and rest affect mental balance.",
    uaTokens: ["На", "душевну", "рівновагу", "впливають", "і", "робота", ",", "і", "відпочинок", "."],
    ruTokens: ["На", "душевное", "равновесие", "влияют", "и", "работа", ",", "и", "отдых", "."],
    enTokens: ["Both", "work", "and", "rest", "affect", "mental", "balance", "."],
    extraUaTokens: ["також", "сон", "щодня"],
    extraRuTokens: ["также", "сон", "ежедневно"],
    extraEnTokens: ["also", "sleep", "daily"],
  },

  [phraseKey("podvedomie", "b2-26")]: {
    sk: "Niektoré reakcie vychádzajú z nášho podvedomia.",
    ua: "Деякі реакції походять із нашої підсвідомості.",
    ru: "Некоторые реакции исходят из нашего подсознания.",
    en: "Some reactions come from our subconscious.",
    uaTokens: ["Деякі", "реакції", "походять", "із", "нашої", "підсвідомості", "."],
    ruTokens: ["Некоторые", "реакции", "исходят", "из", "нашего", "подсознания", "."],
    enTokens: ["Some", "reactions", "come", "from", "our", "subconscious", "."],
    extraUaTokens: ["глибоко", "дуже", "всередині"],
    extraRuTokens: ["глубоко", "очень", "внутри"],
    extraEnTokens: ["deep", "very", "inside"],
  },

  [phraseKey("vnútorný tlak", "b2-26")]: {
    sk: "Dlhodobý vnútorný tlak môže viesť k vyčerpaniu.",
    ua: "Тривалий внутрішній тиск може призвести до виснаження.",
    ru: "Длительное внутреннее давление может привести к истощению.",
    en: "Long-term inner pressure can lead to exhaustion.",
    uaTokens: ["Тривалий", "внутрішній", "тиск", "може", "призвести", "до", "виснаження", "."],
    ruTokens: ["Длительное", "внутреннее", "давление", "может", "привести", "к", "истощению", "."],
    enTokens: ["Long-term", "inner", "pressure", "can", "lead", "to", "exhaustion", "."],
    extraUaTokens: ["сильного", "дуже", "сьогодні"],
    extraRuTokens: ["сильного", "очень", "сегодня"],
    extraEnTokens: ["strong", "very", "today"],
  },

  [phraseKey("osobná hranica", "b2-26")]: {
    sk: "Každý človek má právo chrániť svoju osobnú hranicu.",
    ua: "Кожна людина має право захищати свої особисті межі.",
    ru: "Каждый человек имеет право защищать свои личные границы.",
    en: "Every person has the right to protect their personal boundaries.",
    uaTokens: ["Кожна", "людина", "має", "право", "захищати", "свої", "особисті", "межі", "."],
    ruTokens: ["Каждый", "человек", "имеет", "право", "защищать", "свои", "личные", "границы", "."],
    enTokens: ["Every", "person", "has", "the", "right", "to", "protect", "their", "personal", "boundaries", "."],
    extraUaTokens: ["завжди", "чітко", "власні"],
    extraRuTokens: ["всегда", "чётко", "собственные"],
    extraEnTokens: ["always", "clearly", "own"],
  },

  [phraseKey("psychická odolnosť", "b2-26")]: {
    sk: "Psychická odolnosť sa buduje postupne a dlhodobo.",
    ua: "Психологічна стійкість формується поступово й упродовж тривалого часу.",
    ru: "Психологическая устойчивость формируется постепенно и в течение долгого времени.",
    en: "Psychological resilience is built gradually over a long period of time.",
    uaTokens: ["Психологічна", "стійкість", "формується", "поступово", "й", "упродовж", "тривалого", "часу", "."],
    ruTokens: ["Психологическая", "устойчивость", "формируется", "постепенно", "и", "в", "течение", "долгого", "времени", "."],
    enTokens: ["Psychological", "resilience", "is", "built", "gradually", "over", "a", "long", "period", "of", "time", "."],
    extraUaTokens: ["щодня", "дуже", "повільно"],
    extraRuTokens: ["ежедневно", "очень", "медленно"],
    extraEnTokens: ["daily", "very", "slowly"],
  },

  [phraseKey("duševný stav", "b2-26")]: {
    sk: "Jeho duševný stav sa po odpočinku zlepšil.",
    ua: "Його психічний стан покращився після відпочинку.",
    ru: "Его психическое состояние улучшилось после отдыха.",
    en: "His mental state improved after rest.",
    uaTokens: ["Його", "психічний", "стан", "покращився", "після", "відпочинку", "."],
    ruTokens: ["Его", "психическое", "состояние", "улучшилось", "после", "отдыха", "."],
    enTokens: ["His", "mental", "state", "improved", "after", "rest", "."],
    extraUaTokens: ["значно", "дуже", "вчора"],
    extraRuTokens: ["значительно", "очень", "вчера"],
    extraEnTokens: ["significantly", "very", "yesterday"],
  },

  [phraseKey("sebauvedomenie", "b2-26")]: {
    sk: "Sebauvedomenie mu pomáha robiť lepšie rozhodnutia.",
    ua: "Самоусвідомлення допомагає йому приймати кращі рішення.",
    ru: "Самоосознание помогает ему принимать лучшие решения.",
    en: "Self-awareness helps him make better decisions.",
    uaTokens: ["Самоусвідомлення", "допомагає", "йому", "приймати", "кращі", "рішення", "."],
    ruTokens: ["Самоосознание", "помогает", "ему", "принимать", "лучшие", "решения", "."],
    enTokens: ["Self-awareness", "helps", "him", "make", "better", "decisions", "."],
    extraUaTokens: ["щодня", "більш", "свідомо"],
    extraRuTokens: ["ежедневно", "более", "осознанно"],
    extraEnTokens: ["daily", "more", "consciously"],
  },

  // =========================
  // LESSON 27 — Diplomacia
  // =========================
  [phraseKey("vyjednávanie", "b2-27")]: {
    sk: "Vyjednávanie trvalo dlhšie, než všetci očakávali.",
    ua: "Переговори тривали довше, ніж усі очікували.",
    ru: "Переговоры длились дольше, чем все ожидали.",
    en: "The negotiations lasted longer than everyone expected.",
    uaTokens: ["Переговори", "тривали", "довше", ",", "ніж", "усі", "очікували", "."],
    ruTokens: ["Переговоры", "длились", "дольше", ",", "чем", "все", "ожидали", "."],
    enTokens: ["The", "negotiations", "lasted", "longer", "than", "everyone", "expected", "."],
    extraUaTokens: ["набагато", "вчора", "довго"],
    extraRuTokens: ["намного", "вчера", "долго"],
    extraEnTokens: ["much", "yesterday", "long"],
  },

  [phraseKey("ústretový postoj", "b2-27")]: {
    sk: "Jeho ústretový postoj pomohol zmierniť napätie.",
    ua: "Його конструктивна позиція допомогла зменшити напругу.",
    ru: "Его конструктивная позиция помогла снизить напряжение.",
    en: "His constructive attitude helped reduce the tension.",
    uaTokens: ["Його", "конструктивна", "позиція", "допомогла", "зменшити", "напругу", "."],
    ruTokens: ["Его", "конструктивная", "позиция", "помогла", "снизить", "напряжение", "."],
    enTokens: ["His", "constructive", "attitude", "helped", "reduce", "the", "tension", "."],
    extraUaTokens: ["суттєво", "дуже", "швидко"],
    extraRuTokens: ["существенно", "очень", "быстро"],
    extraEnTokens: ["significantly", "very", "quickly"],
  },

  [phraseKey("neutrálne stanovisko", "b2-27")]: {
    sk: "V tejto veci sa rozhodol zaujať neutrálne stanovisko.",
    ua: "У цій справі він вирішив зайняти нейтральну позицію.",
    ru: "В этом вопросе он решил занять нейтральную позицию.",
    en: "In this matter, he decided to take a neutral position.",
    uaTokens: ["У", "цій", "справі", "він", "вирішив", "зайняти", "нейтральну", "позицію", "."],
    ruTokens: ["В", "этом", "вопросе", "он", "решил", "занять", "нейтральную", "позицию", "."],
    enTokens: ["In", "this", "matter", ",", "he", "decided", "to", "take", "a", "neutral", "position", "."],
    extraUaTokens: ["спокійно", "зараз", "обережну"],
    extraRuTokens: ["спокойно", "сейчас", "осторожную"],
    extraEnTokens: ["calmly", "now", "careful"],
  },

  [phraseKey("vyvážené riešenie", "b2-27")]: {
    sk: "Hľadáme vyvážené riešenie prijateľné pre obe strany.",
    ua: "Ми шукаємо збалансоване рішення, прийнятне для обох сторін.",
    ru: "Мы ищем сбалансированное решение, приемлемое для обеих сторон.",
    en: "We are looking for a balanced solution acceptable to both sides.",
    uaTokens: ["Ми", "шукаємо", "збалансоване", "рішення", ",", "прийнятне", "для", "обох", "сторін", "."],
    ruTokens: ["Мы", "ищем", "сбалансированное", "решение", ",", "приемлемое", "для", "обеих", "сторон", "."],
    enTokens: ["We", "are", "looking", "for", "a", "balanced", "solution", "acceptable", "to", "both", "sides", "."],
    uaAltAnswers: [["Ми", "шукаємо", "прийнятне", "для", "обох", "сторін", "збалансоване", "рішення", "."]],
    ruAltAnswers: [["Мы", "ищем", "приемлемое", "для", "обеих", "сторон", "сбалансированное", "решение", "."]],
    enAltAnswers: [["We", "are", "looking", "for", "an", "acceptable", "balanced", "solution", "for", "both", "sides", "."]],
    extraUaTokens: ["сьогодні", "найкраще", "можливе"],
    extraRuTokens: ["сегодня", "лучшее", "возможное"],
    extraEnTokens: ["today", "best", "possible"],
  },

  [phraseKey("napätá situácia", "b2-27")]: {
    sk: "Aj v napätej situácii si zachoval pokoj.",
    ua: "Навіть у напруженій ситуації він зберіг спокій.",
    ru: "Даже в напряжённой ситуации он сохранил спокойствие.",
    en: "Even in a tense situation, he remained calm.",
    uaTokens: ["Навіть", "у", "напруженій", "ситуації", "він", "зберіг", "спокій", "."],
    ruTokens: ["Даже", "в", "напряжённой", "ситуации", "он", "сохранил", "спокойствие", "."],
    enTokens: ["Even", "in", "a", "tense", "situation", ",", "he", "remained", "calm", "."],
    extraUaTokens: ["повністю", "дуже", "впевнено"],
    extraRuTokens: ["полностью", "очень", "уверенно"],
    extraEnTokens: ["completely", "very", "confidently"],
  },

  [phraseKey("zmierlivý tón", "b2-27")]: {
    sk: "Rozprával zmierlivým tónom, aby predišiel konfliktu.",
    ua: "Він говорив примирливим тоном, щоб уникнути конфлікту.",
    ru: "Он говорил примирительным тоном, чтобы избежать конфликта.",
    en: "He spoke in a conciliatory tone to avoid conflict.",
    uaTokens: ["Він", "говорив", "примирливим", "тоном", ",", "щоб", "уникнути", "конфлікту", "."],
    ruTokens: ["Он", "говорил", "примирительным", "тоном", ",", "чтобы", "избежать", "конфликта", "."],
    enTokens: ["He", "spoke", "in", "a", "conciliatory", "tone", "to", "avoid", "conflict", "."],
    extraUaTokens: ["спокійно", "дуже", "м’яко"],
    extraRuTokens: ["спокойно", "очень", "мягко"],
    extraEnTokens: ["calmly", "very", "gently"],
  },

  [phraseKey("rokovacia stratégia", "b2-27")]: {
    sk: "Ich rokovacia stratégia bola veľmi dobre pripravená.",
    ua: "Їхня стратегія переговорів була дуже добре підготовлена.",
    ru: "Их переговорная стратегия была очень хорошо подготовлена.",
    en: "Their negotiation strategy was very well prepared.",
    uaTokens: ["Їхня", "стратегія", "переговорів", "була", "дуже", "добре", "підготовлена", "."],
    ruTokens: ["Их", "переговорная", "стратегия", "была", "очень", "хорошо", "подготовлена", "."],
    enTokens: ["Their", "negotiation", "strategy", "was", "very", "well", "prepared", "."],
    extraUaTokens: ["заздалегідь", "ретельно", "сьогодні"],
    extraRuTokens: ["заранее", "тщательно", "сегодня"],
    extraEnTokens: ["in", "advance", "carefully"],
  },

  [phraseKey("vzájomná dohoda", "b2-27")]: {
    sk: "Nakoniec sa podarilo dosiahnuť vzájomnú dohodu.",
    ua: "Зрештою вдалося досягти взаємної домовленості.",
    ru: "В итоге удалось достичь взаимного соглашения.",
    en: "In the end, they managed to reach a mutual agreement.",
    uaTokens: ["Зрештою", "вдалося", "досягти", "взаємної", "домовленості", "."],
    ruTokens: ["В", "итоге", "удалось", "достичь", "взаимного", "соглашения", "."],
    enTokens: ["In", "the", "end", ",", "they", "managed", "to", "reach", "a", "mutual", "agreement", "."],
    extraUaTokens: ["нарешті", "між", "усіма"],
    extraRuTokens: ["наконец", "между", "всеми"],
    extraEnTokens: ["finally", "between", "everyone"],
  },

  [phraseKey("kompromisné riešenie", "b2-27")]: {
    sk: "Kompromisné riešenie bolo v tej chvíli najlepšie.",
    ua: "Компромісне рішення в той момент було найкращим.",
    ru: "Компромиссное решение в тот момент было лучшим.",
    en: "At that moment, a compromise solution was the best one.",
    uaTokens: ["Компромісне", "рішення", "в", "той", "момент", "було", "найкращим", "."],
    ruTokens: ["Компромиссное", "решение", "в", "тот", "момент", "было", "лучшим", "."],
    enTokens: ["At", "that", "moment", ",", "a", "compromise", "solution", "was", "the", "best", "one", "."],
    extraUaTokens: ["єдиним", "можливим", "тоді"],
    extraRuTokens: ["единственным", "возможным", "тогда"],
    extraEnTokens: ["only", "possible", "then"],
  },

  [phraseKey("zachovať neutralitu", "b2-27")]: {
    sk: "Ako mediátor musí zachovať neutralitu.",
    ua: "Як посередник він має зберігати нейтралітет.",
    ru: "Как посредник он должен сохранять нейтралитет.",
    en: "As a mediator, he must remain neutral.",
    uaTokens: ["Як", "посередник", "він", "має", "зберігати", "нейтралітет", "."],
    ruTokens: ["Как", "посредник", "он", "должен", "сохранять", "нейтралитет", "."],
    enTokens: ["As", "a", "mediator", ",", "he", "must", "remain", "neutral", "."],
    extraUaTokens: ["завжди", "повний", "спокій"],
    extraRuTokens: ["всегда", "полный", "покой"],
    extraEnTokens: ["always", "complete", "calm"],
  },

  // =========================
  // LESSON 28 — Globálne problémy
  // =========================
  [phraseKey("globálna výzva", "b2-28")]: {
    sk: "Zmena klímy je vážna globálna výzva.",
    ua: "Зміна клімату — це серйозний глобальний виклик.",
    ru: "Изменение климата — это серьёзный глобальный вызов.",
    en: "Climate change is a serious global challenge.",
    uaTokens: ["Зміна", "клімату", "—", "це", "серйозний", "глобальний", "виклик", "."],
    ruTokens: ["Изменение", "климата", "—", "это", "серьёзный", "глобальный", "вызов", "."],
    enTokens: ["Climate", "change", "is", "a", "serious", "global", "challenge", "."],
    extraUaTokens: ["сьогодні", "для", "людства"],
    extraRuTokens: ["сегодня", "для", "человечества"],
    extraEnTokens: ["today", "for", "humanity"],
  },

  [phraseKey("humanitárna kríza", "b2-28")]: {
    sk: "Vojna často vedie k hlbokej humanitárnej kríze.",
    ua: "Війна часто призводить до глибокої гуманітарної кризи.",
    ru: "Война часто приводит к глубокой гуманитарной кризе.",
    en: "War often leads to a deep humanitarian crisis.",
    uaTokens: ["Війна", "часто", "призводить", "до", "глибокої", "гуманітарної", "кризи", "."],
    ruTokens: ["Война", "часто", "приводит", "к", "глубокой", "гуманитарной", "кризе", "."],
    enTokens: ["War", "often", "leads", "to", "a", "deep", "humanitarian", "crisis", "."],
    extraUaTokens: ["дуже", "важкої", "сьогодні"],
    extraRuTokens: ["очень", "тяжёлой", "сегодня"],
    extraEnTokens: ["very", "severe", "today"],
  },

  [phraseKey("nedostatok zdrojov", "b2-28")]: {
    sk: "V niektorých regiónoch je veľký nedostatok zdrojov.",
    ua: "У деяких регіонах є велика нестача ресурсів.",
    ru: "В некоторых регионах наблюдается большая нехватка ресурсов.",
    en: "In some regions, there is a major shortage of resources.",
    uaTokens: ["У", "деяких", "регіонах", "є", "велика", "нестача", "ресурсів", "."],
    ruTokens: ["В", "некоторых", "регионах", "наблюдается", "большая", "нехватка", "ресурсов", "."],
    enTokens: ["In", "some", "regions", ",", "there", "is", "a", "major", "shortage", "of", "resources", "."],
    extraUaTokens: ["води", "їжі", "часто"],
    extraRuTokens: ["воды", "еды", "часто"],
    extraEnTokens: ["water", "food", "often"],
  },

  [phraseKey("sociálna nerovnosť", "b2-28")]: {
    sk: "Sociálna nerovnosť zostáva vážnym problémom mnohých krajín.",
    ua: "Соціальна нерівність залишається серйозною проблемою багатьох країн.",
    ru: "Социальное неравенство остаётся серьёзной проблемой многих стран.",
    en: "Social inequality remains a serious problem in many countries.",
    uaTokens: ["Соціальна", "нерівність", "залишається", "серйозною", "проблемою", "багатьох", "країн", "."],
    ruTokens: ["Социальное", "неравенство", "остаётся", "серьёзной", "проблемой", "многих", "стран", "."],
    enTokens: ["Social", "inequality", "remains", "a", "serious", "problem", "in", "many", "countries", "."],
    extraUaTokens: ["і", "сьогодні", "досі"],
    extraRuTokens: ["и", "сегодня", "до сих пор"],
    extraEnTokens: ["and", "today", "still"],
  },

  [phraseKey("migračná vlna", "b2-28")]: {
    sk: "Migračná vlna ovplyvnila situáciu v celom regióne.",
    ua: "Міграційна хвиля вплинула на ситуацію в усьому регіоні.",
    ru: "Миграционная волна повлияла на ситуацию во всём регионе.",
    en: "The migration wave affected the situation across the entire region.",
    uaTokens: ["Міграційна", "хвиля", "вплинула", "на", "ситуацію", "в", "усьому", "регіоні", "."],
    ruTokens: ["Миграционная", "волна", "повлияла", "на", "ситуацию", "во", "всём", "регионе", "."],
    enTokens: ["The", "migration", "wave", "affected", "the", "situation", "across", "the", "entire", "region", "."],
    extraUaTokens: ["значно", "дуже", "сильно"],
    extraRuTokens: ["значительно", "очень", "сильно"],
    extraEnTokens: ["significantly", "very", "strongly"],
  },

  [phraseKey("medzinárodná spolupráca", "b2-28")]: {
    sk: "Bez medzinárodnej spolupráce sa tento problém nevyrieši.",
    ua: "Без міжнародної співпраці цю проблему не вирішити.",
    ru: "Без международного сотрудничества эту проблему не решить.",
    en: "Without international cooperation, this problem cannot be solved.",
    uaTokens: ["Без", "міжнародної", "співпраці", "цю", "проблему", "не", "вирішити", "."],
    ruTokens: ["Без", "международного", "сотрудничества", "эту", "проблему", "не", "решить", "."],
    enTokens: ["Without", "international", "cooperation", ",", "this", "problem", "cannot", "be", "solved", "."],
    extraUaTokens: ["сьогодні", "разом", "ніколи"],
    extraRuTokens: ["сегодня", "вместе", "никогда"],
    extraEnTokens: ["today", "together", "never"],
  },

  [phraseKey("dlhodobý problém", "b2-28")]: {
    sk: "Chudoba je dlhodobý problém, ktorý sa nedá odstrániť rýchlo.",
    ua: "Бідність — це довготривала проблема, яку неможливо швидко усунути.",
    ru: "Бедность — это долгосрочная проблема, которую нельзя быстро устранить.",
    en: "Poverty is a long-term problem that cannot be eliminated quickly.",
    uaTokens: ["Бідність", "—", "це", "довготривала", "проблема", ",", "яку", "неможливо", "швидко", "усунути", "."],
    ruTokens: ["Бедность", "—", "это", "долгосрочная", "проблема", ",", "которую", "нельзя", "быстро", "устранить", "."],
    enTokens: ["Poverty", "is", "a", "long-term", "problem", "that", "cannot", "be", "eliminated", "quickly", "."],
    extraUaTokens: ["просто", "сьогодні", "одразу"],
    extraRuTokens: ["просто", "сегодня", "сразу"],
    extraEnTokens: ["simply", "today", "immediately"],
  },

  [phraseKey("spoločná zodpovednosť", "b2-28")]: {
    sk: "Ochrana planéty je spoločná zodpovednosť nás všetkých.",
    ua: "Захист планети — це спільна відповідальність усіх нас.",
    ru: "Защита планеты — это общая ответственность всех нас.",
    en: "Protecting the planet is a shared responsibility of all of us.",
    uaTokens: ["Захист", "планети", "—", "це", "спільна", "відповідальність", "усіх", "нас", "."],
    ruTokens: ["Защита", "планеты", "—", "это", "общая", "ответственность", "всех", "нас", "."],
    enTokens: ["Protecting", "the", "planet", "is", "a", "shared", "responsibility", "of", "all", "of", "us", "."],
    extraUaTokens: ["сьогодні", "для", "людей"],
    extraRuTokens: ["сегодня", "для", "людей"],
    extraEnTokens: ["today", "for", "people"],
  },

  [phraseKey("celosvetový dopad", "b2-28")]: {
    sk: "Takéto rozhodnutie môže mať celosvetový dopad.",
    ua: "Таке рішення може мати глобальний вплив.",
    ru: "Такое решение может иметь глобальное влияние.",
    en: "Such a decision can have a global impact.",
    uaTokens: ["Таке", "рішення", "може", "мати", "глобальний", "вплив", "."],
    ruTokens: ["Такое", "решение", "может", "иметь", "глобальное", "влияние", "."],
    enTokens: ["Such", "a", "decision", "can", "have", "a", "global", "impact", "."],
    extraUaTokens: ["дуже", "серйозний", "сьогодні"],
    extraRuTokens: ["очень", "серьёзный", "сегодня"],
    extraEnTokens: ["very", "serious", "today"],
  },

  [phraseKey("udržateľné riešenie", "b2-28")]: {
    sk: "Potrebujeme nájsť udržateľné riešenie na dlhé roky.",
    ua: "Нам потрібно знайти стале рішення на довгі роки.",
    ru: "Нам нужно найти устойчивое решение на долгие годы.",
    en: "We need to find a sustainable solution for many years ahead.",
    uaTokens: ["Нам", "потрібно", "знайти", "стале", "рішення", "на", "довгі", "роки", "."],
    ruTokens: ["Нам", "нужно", "найти", "устойчивое", "решение", "на", "долгие", "годы", "."],
    enTokens: ["We", "need", "to", "find", "a", "sustainable", "solution", "for", "many", "years", "ahead", "."],
    extraUaTokens: ["справді", "дуже", "надійне"],
    extraRuTokens: ["действительно", "очень", "надёжное"],
    extraEnTokens: ["truly", "very", "reliable"],
  },

  // =========================
  // LESSON 29 — Medziľudské konflikty
  // =========================
  [phraseKey("napätý vzťah", "b2-29")]: {
    sk: "Ich napätý vzťah sa časom ešte viac zhoršil.",
    ua: "Їхні напружені стосунки з часом ще більше погіршилися.",
    ru: "Их напряжённые отношения со временем ещё больше ухудшились.",
    en: "Their tense relationship grew even worse over time.",
    uaTokens: ["Їхні", "напружені", "стосунки", "з", "часом", "ще", "більше", "погіршилися", "."],
    ruTokens: ["Их", "напряжённые", "отношения", "со", "временем", "ещё", "больше", "ухудшились", "."],
    enTokens: ["Their", "tense", "relationship", "grew", "even", "worse", "over", "time", "."],
    extraUaTokens: ["дуже", "сильно", "вчора"],
    extraRuTokens: ["очень", "сильно", "вчера"],
    extraEnTokens: ["very", "strongly", "yesterday"],
  },

  [phraseKey("nepochopenie", "b2-29")]: {
    sk: "Celý problém vznikol len z obyčajného nepochopenia.",
    ua: "Уся проблема виникла лише через звичайне непорозуміння.",
    ru: "Вся проблема возникла только из-за обычного недопонимания.",
    en: "The whole problem arose only from a simple misunderstanding.",
    uaTokens: ["Уся", "проблема", "виникла", "лише", "через", "звичайне", "непорозуміння", "."],
    ruTokens: ["Вся", "проблема", "возникла", "только", "из-за", "обычного", "недопонимания", "."],
    enTokens: ["The", "whole", "problem", "arose", "only", "from", "a", "simple", "misunderstanding", "."],
    extraUaTokens: ["просте", "дуже", "маленьке"],
    extraRuTokens: ["простое", "очень", "маленькое"],
    extraEnTokens: ["simple", "very", "small"],
  },

  [phraseKey("ospravedlnenie", "b2-29")]: {
    sk: "Úprimné ospravedlnenie môže veľa napraviť.",
    ua: "Щире вибачення може багато що виправити.",
    ru: "Искреннее извинение может многое исправить.",
    en: "A sincere apology can fix a lot.",
    uaTokens: ["Щире", "вибачення", "може", "багато", "що", "виправити", "."],
    ruTokens: ["Искреннее", "извинение", "может", "многое", "исправить", "."],
    enTokens: ["A", "sincere", "apology", "can", "fix", "a", "lot", "."],
    uaAltAnswers: [["Щире", "вибачення", "може", "виправити", "багато", "чого", "."]],
    ruAltAnswers: [["Искреннее", "извинение", "может", "исправить", "многое", "."]],
    enAltAnswers: [["A", "sincere", "apology", "can", "correct", "a", "lot", "."]],
    extraUaTokens: ["одразу", "дуже", "швидко"],
    extraRuTokens: ["сразу", "очень", "быстро"],
    extraEnTokens: ["immediately", "very", "quickly"],
  },

  [phraseKey("zmier", "b2-29")]: {
    sk: "Obe strany nakoniec pristúpili na zmier.",
    ua: "Обидві сторони зрештою погодилися на примирення.",
    ru: "Обе стороны в итоге согласились на примирение.",
    en: "In the end, both sides agreed to reconciliation.",
    uaTokens: ["Обидві", "сторони", "зрештою", "погодилися", "на", "примирення", "."],
    ruTokens: ["Обе", "стороны", "в", "итоге", "согласились", "на", "примирение", "."],
    enTokens: ["In", "the", "end", ",", "both", "sides", "agreed", "to", "reconciliation", "."],
    extraUaTokens: ["після", "довгих", "суперечок"],
    extraRuTokens: ["после", "долгих", "споров"],
    extraEnTokens: ["after", "long", "arguments"],
  },

  [phraseKey("napätá atmosféra", "b2-29")]: {
    sk: "V miestnosti panovala napätá atmosféra.",
    ua: "У кімнаті панувала напружена атмосфера.",
    ru: "В комнате царила напряжённая атмосфера.",
    en: "There was a tense atmosphere in the room.",
    uaTokens: ["У", "кімнаті", "панувала", "напружена", "атмосфера", "."],
    ruTokens: ["В", "комнате", "царила", "напряжённая", "атмосфера", "."],
    enTokens: ["There", "was", "a", "tense", "atmosphere", "in", "the", "room", "."],
    extraUaTokens: ["дуже", "важка", "сьогодні"],
    extraRuTokens: ["очень", "тяжёлая", "сегодня"],
    extraEnTokens: ["very", "heavy", "today"],
  },

  [phraseKey("vyriešiť konflikt", "b2-29")]: {
    sk: "Musíme sa porozprávať, ak chceme vyriešiť konflikt.",
    ua: "Ми повинні поговорити, якщо хочемо вирішити конфлікт.",
    ru: "Мы должны поговорить, если хотим решить конфликт.",
    en: "We need to talk if we want to resolve the conflict.",
    uaTokens: ["Ми", "повинні", "поговорити", ",", "якщо", "хочемо", "вирішити", "конфлікт", "."],
    ruTokens: ["Мы", "должны", "поговорить", ",", "если", "хотим", "решить", "конфликт", "."],
    enTokens: ["We", "need", "to", "talk", "if", "we", "want", "to", "resolve", "the", "conflict", "."],
    extraUaTokens: ["спокійно", "разом", "сьогодні"],
    extraRuTokens: ["спокойно", "вместе", "сегодня"],
    extraEnTokens: ["calmly", "together", "today"],
  },

  [phraseKey("vzájomné pochopenie", "b2-29")]: {
    sk: "Bez vzájomného pochopenia sa vzťah ťažko zlepší.",
    ua: "Без взаєморозуміння стосунки важко покращити.",
    ru: "Без взаимопонимания отношения трудно улучшить.",
    en: "Without mutual understanding, a relationship is hard to improve.",
    uaTokens: ["Без", "взаєморозуміння", "стосунки", "важко", "покращити", "."],
    ruTokens: ["Без", "взаимопонимания", "отношения", "трудно", "улучшить", "."],
    enTokens: ["Without", "mutual", "understanding", ",", "a", "relationship", "is", "hard", "to", "improve", "."],
    extraUaTokens: ["справді", "дуже", "швидко"],
    extraRuTokens: ["действительно", "очень", "быстро"],
    extraEnTokens: ["really", "very", "quickly"],
  },

  [phraseKey("napraviť chybu", "b2-29")]: {
    sk: "Snažil sa napraviť chybu skôr, než bude neskoro.",
    ua: "Він намагався виправити помилку, перш ніж стане запізно.",
    ru: "Он пытался исправить ошибку, прежде чем станет слишком поздно.",
    en: "He tried to correct the mistake before it became too late.",
    uaTokens: ["Він", "намагався", "виправити", "помилку", ",", "перш", "ніж", "стане", "запізно", "."],
    ruTokens: ["Он", "пытался", "исправить", "ошибку", ",", "прежде", "чем", "станет", "слишком", "поздно", "."],
    enTokens: ["He", "tried", "to", "correct", "the", "mistake", "before", "it", "became", "too", "late", "."],
    extraUaTokens: ["одразу", "швидко", "сьогодні"],
    extraRuTokens: ["сразу", "быстро", "сегодня"],
    extraEnTokens: ["immediately", "quickly", "today"],
  },

  [phraseKey("napätie medzi ľuďmi", "b2-29")]: {
    sk: "Napätie medzi ľuďmi bolo citeľné už od začiatku.",
    ua: "Напруга між людьми була відчутною вже від самого початку.",
    ru: "Напряжение между людьми ощущалось уже с самого начала.",
    en: "The tension between people was noticeable from the very beginning.",
    uaTokens: ["Напруга", "між", "людьми", "була", "відчутною", "вже", "від", "самого", "початку", "."],
    ruTokens: ["Напряжение", "между", "людьми", "ощущалось", "уже", "с", "самого", "начала", "."],
    enTokens: ["The", "tension", "between", "people", "was", "noticeable", "from", "the", "very", "beginning", "."],
    extraUaTokens: ["дуже", "сильно", "вчора"],
    extraRuTokens: ["очень", "сильно", "вчера"],
    extraEnTokens: ["very", "strongly", "yesterday"],
  },

  [phraseKey("vzťahová kríza", "b2-29")]: {
    sk: "Ich vzťahová kríza trvala niekoľko mesiacov.",
    ua: "Їхня криза у стосунках тривала кілька місяців.",
    ru: "Их кризис в отношениях длился несколько месяцев.",
    en: "Their relationship crisis lasted for several months.",
    uaTokens: ["Їхня", "криза", "у", "стосунках", "тривала", "кілька", "місяців", "."],
    ruTokens: ["Их", "кризис", "в", "отношениях", "длился", "несколько", "месяцев", "."],
    enTokens: ["Their", "relationship", "crisis", "lasted", "for", "several", "months", "."],
    extraUaTokens: ["майже", "дуже", "довго"],
    extraRuTokens: ["почти", "очень", "долго"],
    extraEnTokens: ["almost", "very", "long"],
  },

  // =========================
  // LESSON 30 — Kultúra a spoločenské javy
  // =========================
  [phraseKey("kultúrna identita", "b2-30")]: {
    sk: "Jazyk je dôležitou súčasťou kultúrnej identity.",
    ua: "Мова є важливою частиною культурної ідентичності.",
    ru: "Язык является важной частью культурной идентичности.",
    en: "Language is an important part of cultural identity.",
    uaTokens: ["Мова", "є", "важливою", "частиною", "культурної", "ідентичності", "."],
    ruTokens: ["Язык", "является", "важной", "частью", "культурной", "идентичности", "."],
    enTokens: ["Language", "is", "an", "important", "part", "of", "cultural", "identity", "."],
    extraUaTokens: ["кожного", "народу", "сьогодні"],
    extraRuTokens: ["каждого", "народа", "сегодня"],
    extraEnTokens: ["every", "nation", "today"],
  },

  [phraseKey("spoločenský trend", "b2-30")]: {
    sk: "Tento spoločenský trend je medzi mladými veľmi silný.",
    ua: "Цей соціальний тренд дуже сильний серед молоді.",
    ru: "Этот социальный тренд очень силён среди молодёжи.",
    en: "This social trend is very strong among young people.",
    uaTokens: ["Цей", "соціальний", "тренд", "дуже", "сильний", "серед", "молоді", "."],
    ruTokens: ["Этот", "социальный", "тренд", "очень", "силён", "среди", "молодёжи", "."],
    enTokens: ["This", "social", "trend", "is", "very", "strong", "among", "young", "people", "."],
    extraUaTokens: ["сьогодні", "особливо", "помітний"],
    extraRuTokens: ["сегодня", "особенно", "заметный"],
    extraEnTokens: ["today", "especially", "noticeable"],
  },

  [phraseKey("spoločenská norma", "b2-30")]: {
    sk: "Nie každá spoločenská norma je rovnaká v každej krajine.",
    ua: "Не кожна соціальна норма однакова в кожній країні.",
    ru: "Не каждая социальная норма одинакова в каждой стране.",
    en: "Not every social norm is the same in every country.",
    uaTokens: ["Не", "кожна", "соціальна", "норма", "однакова", "в", "кожній", "країні", "."],
    ruTokens: ["Не", "каждая", "социальная", "норма", "одинакова", "в", "каждой", "стране", "."],
    enTokens: ["Not", "every", "social", "norm", "is", "the", "same", "in", "every", "country", "."],
    extraUaTokens: ["завжди", "усюди", "повністю"],
    extraRuTokens: ["всегда", "везде", "полностью"],
    extraEnTokens: ["always", "everywhere", "completely"],
  },

  [phraseKey("kultúrne dedičstvo", "b2-30")]: {
    sk: "Mesto je hrdé na svoje kultúrne dedičstvo.",
    ua: "Місто пишається своєю культурною спадщиною.",
    ru: "Город гордится своим культурным наследием.",
    en: "The city is proud of its cultural heritage.",
    uaTokens: ["Місто", "пишається", "своєю", "культурною", "спадщиною", "."],
    ruTokens: ["Город", "гордится", "своим", "культурным", "наследием", "."],
    enTokens: ["The", "city", "is", "proud", "of", "its", "cultural", "heritage", "."],
    extraUaTokens: ["дуже", "сильно", "сьогодні"],
    extraRuTokens: ["очень", "сильно", "сегодня"],
    extraEnTokens: ["very", "strongly", "today"],
  },

  [phraseKey("umelecký smer", "b2-30")]: {
    sk: "Tento umelecký smer vznikol na začiatku minulého storočia.",
    ua: "Цей художній напрям виник на початку минулого століття.",
    ru: "Это художественное направление возникло в начале прошлого века.",
    en: "This artistic movement emerged at the beginning of the last century.",
    uaTokens: ["Цей", "художній", "напрям", "виник", "на", "початку", "минулого", "століття", "."],
    ruTokens: ["Это", "художественное", "направление", "возникло", "в", "начале", "прошлого", "века", "."],
    enTokens: ["This", "artistic", "movement", "emerged", "at", "the", "beginning", "of", "the", "last", "century", "."],
    extraUaTokens: ["дуже", "рано", "тоді"],
    extraRuTokens: ["очень", "рано", "тогда"],
    extraEnTokens: ["very", "early", "then"],
  },

  [phraseKey("spoločenský vplyv", "b2-30")]: {
    sk: "Médiá majú veľký spoločenský vplyv na verejnosť.",
    ua: "Медіа мають великий соціальний вплив на суспільство.",
    ru: "Медиа оказывают большое социальное влияние на общество.",
    en: "The media have a great influence on society.",
    uaTokens: ["Медіа", "мають", "великий", "соціальний", "вплив", "на", "суспільство", "."],
    ruTokens: ["Медиа", "оказывают", "большое", "социальное", "влияние", "на", "общество", "."],
    enTokens: ["The", "media", "have", "a", "great", "influence", "on", "society", "."],
    extraUaTokens: ["сьогодні", "дуже", "сильний"],
    extraRuTokens: ["сегодня", "очень", "сильное"],
    extraEnTokens: ["today", "very", "strong"],
  },

  [phraseKey("verejná diskusia", "b2-30")]: {
    sk: "Táto téma vyvolala širokú verejnú diskusiu.",
    ua: "Ця тема викликала широку публічну дискусію.",
    ru: "Эта тема вызвала широкую публичную дискуссию.",
    en: "This topic sparked a broad public discussion.",
    uaTokens: ["Ця", "тема", "викликала", "широку", "публічну", "дискусію", "."],
    ruTokens: ["Эта", "тема", "вызвала", "широкую", "публичную", "дискуссию", "."],
    enTokens: ["This", "topic", "sparked", "a", "broad", "public", "discussion", "."],
    extraUaTokens: ["сьогодні", "дуже", "активну"],
    extraRuTokens: ["сегодня", "очень", "активную"],
    extraEnTokens: ["today", "very", "active"],
  },

  [phraseKey("spoločenský kontext", "b2-30")]: {
    sk: "Tomuto dielu lepšie porozumieme v spoločenskom kontexte doby.",
    ua: "Цей твір краще розуміти в соціальному контексті епохи.",
    ru: "Это произведение лучше понимать в социальном контексте эпохи.",
    en: "This work is better understood in the social context of its era.",
    uaTokens: ["Цей", "твір", "краще", "розуміти", "в", "соціальному", "контексті", "епохи", "."],
    ruTokens: ["Это", "произведение", "лучше", "понимать", "в", "социальном", "контексте", "эпохи", "."],
    enTokens: ["This", "work", "is", "better", "understood", "in", "the", "social", "context", "of", "its", "era", "."],
    extraUaTokens: ["історичної", "саме", "тієї"],
    extraRuTokens: ["исторической", "именно", "той"],
    extraEnTokens: ["historical", "exactly", "that"],
  },

  [phraseKey("kultúrny rozdiel", "b2-30")]: {
    sk: "Malý kultúrny rozdiel môže viesť k nedorozumeniu.",
    ua: "Невелика культурна різниця може призвести до непорозуміння.",
    ru: "Небольшое культурное различие может привести к недопониманию.",
    en: "A small cultural difference can lead to a misunderstanding.",
    uaTokens: ["Невелика", "культурна", "різниця", "може", "призвести", "до", "непорозуміння", "."],
    ruTokens: ["Небольшое", "культурное", "различие", "может", "привести", "к", "недопониманию", "."],
    enTokens: ["A", "small", "cultural", "difference", "can", "lead", "to", "a", "misunderstanding", "."],
    extraUaTokens: ["іноді", "дуже", "легко"],
    extraRuTokens: ["иногда", "очень", "легко"],
    extraEnTokens: ["sometimes", "very", "easily"],
  },

  [phraseKey("spoločenská realita", "b2-30")]: {
    sk: "Film verne zobrazil spoločenskú realitu svojej doby.",
    ua: "Фільм правдиво показав соціальну реальність свого часу.",
    ru: "Фильм правдиво показал социальную реальность своего времени.",
    en: "The film truthfully portrayed the social reality of its time.",
    uaTokens: ["Фільм", "правдиво", "показав", "соціальну", "реальність", "свого", "часу", "."],
    ruTokens: ["Фильм", "правдиво", "показал", "социальную", "реальность", "своего", "времени", "."],
    enTokens: ["The", "film", "truthfully", "portrayed", "the", "social", "reality", "of", "its", "time", "."],
    extraUaTokens: ["дуже", "точно", "тоді"],
    extraRuTokens: ["очень", "точно", "тогда"],
    extraEnTokens: ["very", "accurately", "then"],
  },
};