export type Lang = "ua" | "ru" | "en";

export type LocalizedText = Partial<Record<Lang, string>>;

export type Word = {
    term?: string; // optional universal term
    sk: string;
    ua: string;
    ru?: string;
    en?: string;
    ipa?: string;
    img?: string;
    imgCredit?: string;
    phrase?: {
        sk: string;
        ua: string;
        ru?: string;
        en?: string;
        tokens: string[];
    };
};

export type LessonSource = {
    id: string;
    title: string | LocalizedText;
    words: Word[];
};

export const A0_REAL_SOURCE: LessonSource[] = [
    {
        id: "1",
        title: {
            ua: "Урок 1 — Базові слова",
            ru: "Урок 1 — Базовые слова",
            en: "Lesson 1 — Basic words",
        },
        words: [
            { sk: "dom", ua: "дім", ru: "дом", en: "house", img: "/words/dom.jpg" },
            { sk: "auto", ua: "авто", ru: "авто", en: "car", img: "/words/auto.jpg" },
            { sk: "voda", ua: "вода", ru: "вода", en: "water", img: "/words/voda.jpg" },
            { sk: "chlieb", ua: "хліб", ru: "хлеб", en: "bread", img: "/words/chlieb.jpg" },
            { sk: "škola", ua: "школа", ru: "школа", en: "school", img: "/words/škola.jpg" },
            { sk: "mesto", ua: "місто", ru: "город", en: "city", img: "/words/mesto.jpg" },
            { sk: "čas", ua: "час", ru: "время", en: "time", img: "/words/čas.jpg" },
            { sk: "deň", ua: "день", ru: "день", en: "day", img: "/words/deň.jpg" },
            { sk: "dobrý", ua: "добрий", ru: "хороший", en: "good", img: "/words/dobrý.jpg" },
            { sk: "peniaze", ua: "гроші", ru: "деньги", en: "money", img: "/words/peniaze.jpg" },
        ],
    },
    {
        id: "2",
        title: {
            ua: "Урок 2 — люди",
            ru: "Урок 2 — люди",
            en: "Lesson 2 — People",
        },
        words: [
            { sk: "človek", ua: "людина", ru: "человек", en: "person", img: "/words/human.jpg" },
            { sk: "muž", ua: "чоловік", ru: "мужчина", en: "man", img: "/words/man.jpg" },
            { sk: "žena", ua: "жінка", ru: "женщина", en: "woman", img: "/words/woman.jpg" },
            { sk: "dieťa", ua: "дитина", ru: "ребёнок", en: "child", img: "/words/child.jpg" },
            { sk: "priateľ", ua: "друг", ru: "друг", en: "friend", img: "/words/priateľ.jpg" },
            { sk: "priateľka", ua: "подруга", ru: "подруга", en: "female friend", img: "/words/priateľka.jpg" },
            { sk: "otec", ua: "батько", ru: "отец", en: "father", img: "/words/otec.jpg" },
            { sk: "matka", ua: "мати", ru: "мать", en: "mother", img: "/words/matka.jpg" },
            { sk: "brat", ua: "брат", ru: "брат", en: "brother", img: "/words/brat.jpg" },
            { sk: "sestra", ua: "сестра", ru: "сестра", en: "sister", img: "/words/sestra.jpg" },
        ],
    },
    {
        id: "3",
        title: {
            ua: "Урок 3 — дім",
            ru: "Урок 3 — дом",
            en: "Lesson 3 — Home",
        },
        words: [
            { sk: "byt", ua: "квартира", ru: "квартира", en: "apartment", img: "/words/byt.jpg" },
            { sk: "izba", ua: "кімната", ru: "комната", en: "room", img: "/words/izba.jpg" },
            { sk: "kuchyňa", ua: "кухня", ru: "кухня", en: "kitchen", img: "/words/kuchyňa.jpg" },
            { sk: "kúpeľňa", ua: "ванна кімната", ru: "ванная", en: "bathroom", img: "/words/kúpeľňa.jpg" },
            { sk: "dvere", ua: "двері", ru: "дверь", en: "door", img: "/words/dvere.jpg" },
            { sk: "okno", ua: "вікно", ru: "окно", en: "window", img: "/words/okno.jpg" },
            { sk: "stôl", ua: "стіл", ru: "стол", en: "table", img: "/words/stôl.jpg" },
            { sk: "stolička", ua: "стілець", ru: "стул", en: "chair", img: "/words/stolička.jpg" },
            { sk: "posteľ", ua: "ліжко", ru: "кровать", en: "bed", img: "/words/posteľ.jpg" },
            { sk: "skriňa", ua: "шафа", ru: "шкаф", en: "wardrobe", img: "/words/skriňa.jpg" },
        ],
    },
    {
        id: "4",
        title: {
            ua: "Урок 4 — магазин",
            ru: "Урок 4 — магазин",
            en: "Lesson 4 — Shop",
        },
        words: [
            { sk: "obchod", ua: "магазин", ru: "магазин", en: "shop", img: "/words/obchod.jpg" },
            { sk: "pokladňa", ua: "каса", ru: "касса", en: "cash register", img: "/words/pokladňa.jpg" },
            { sk: "cena", ua: "ціна", ru: "цена", en: "price", img: "/words/cena.jpg" },
            { sk: "zľava", ua: "знижка", ru: "скидка", en: "discount", img: "/words/zľava.jpg" },
            { sk: "taška", ua: "пакет/сумка", ru: "пакет/сумка", en: "bag", img: "/words/taška.jpg" },
            { sk: "blok", ua: "чек", ru: "чек", en: "receipt", img: "/words/blok.jpg" },
            { sk: "hotovosť", ua: "готівка", ru: "наличные", en: "cash", img: "/words/hotovosť.jpg" },
            { sk: "karta", ua: "картка", ru: "карта", en: "card", img: "/words/karta.jpg" },
            { sk: "kúpiť", ua: "купити", ru: "купить", en: "to buy", img: "/words/kupiť.jpg" },
            { sk: "platiť", ua: "платити", ru: "платить", en: "to pay", img: "/words/platiť.jpg" },
        ],
    },
    {
        id: "5",
        title: {
            ua: "Урок 5 — Їжа та напої",
            ru: "Урок 5 — Еда и напитки",
            en: "Lesson 5 — Food and drinks",
        },
        words: [
            { sk: "jedlo", ua: "їжа", ru: "еда", en: "food", img: "/words/jedlo.jpg" },
            { sk: "nápoj", ua: "напій", ru: "напиток", en: "drink", img: "/words/nápoj.jpg" },
            { sk: "chlieb", ua: "хліб", ru: "хлеб", en: "bread", img: "/words/chlieb.jpg" },
            { sk: "mäso", ua: "м'ясо", ru: "мясо", en: "meat", img: "/words/mäso.jpg" },
            { sk: "polievka", ua: "суп", ru: "суп", en: "soup", img: "/words/polievka.jpg" },
            { sk: "ovocie", ua: "фрукти", ru: "фрукты", en: "fruit", img: "/words/ovocie.jpg" },
            { sk: "zelenina", ua: "овочі", ru: "овощи", en: "vegetables", img: "/words/zelenina.jpg" },
            { sk: "voda", ua: "вода", ru: "вода", en: "water", img: "/words/voda.jpg" },
            { sk: "káva", ua: "кава", ru: "кофе", en: "coffee", img: "/words/káva.jpg" },
            { sk: "čaj", ua: "чай", ru: "чай", en: "tea", img: "/words/čaj.jpg" },
        ],
    },
    {
        id: "6",
        title: {
            ua: "Урок 6 — Місто",
            ru: "Урок 6 — Город",
            en: "Lesson 6 — City",
        },
        words: [
            { sk: "mesto", ua: "місто", ru: "город", en: "city", img: "/words/mesto.jpg" },
            { sk: "ulica", ua: "вулиця", ru: "улица", en: "street", img: "/words/ulica.jpg" },
            { sk: "námestie", ua: "площа", ru: "площадь", en: "square", img: "/words/námestie.jpg" },
            { sk: "dom", ua: "будинок", ru: "дом", en: "house", img: "/words/dom.jpg" },
            { sk: "byt", ua: "квартира", ru: "квартира", en: "apartment", img: "/words/bytt.jpg" },
            { sk: "škola", ua: "школа", ru: "школа", en: "school", img: "/words/school.jpg" },
            { sk: "nemocnica", ua: "лікарня", ru: "больница", en: "hospital", img: "/words/nemocnica.jpg" },
            { sk: "zastávka", ua: "зупинка", ru: "остановка", en: "stop", img: "/words/zastávka.jpg" },
            { sk: "park", ua: "парк", ru: "парк", en: "park", img: "/words/park.jpg" },
            { sk: "stanica", ua: "станція/вокзал", ru: "станция / вокзал", en: "station", img: "/words/stanica.jpg" },
        ],
    },
    {
        id: "7",
        title: {
            ua: "Урок 7 — Транспорт",
            ru: "Урок 7 — Транспорт",
            en: "Lesson 7 — Transport",
        },
        words: [
            { sk: "doprava", ua: "транспорт", ru: "транспорт", en: "transport", img: "/words/doprava.jpg" },
            { sk: "auto", ua: "авто", ru: "авто", en: "car", img: "/words/car.jpg" },
            { sk: "autobus", ua: "автобус", ru: "автобус", en: "bus", img: "/words/autobus.jpg" },
            { sk: "vlak", ua: "поїзд", ru: "поезд", en: "train", img: "/words/vlak.jpg" },
            { sk: "električka", ua: "трамвай", ru: "трамвай", en: "tram", img: "/words/električka.jpg" },
            { sk: "metro", ua: "метро", ru: "метро", en: "metro", img: "/words/stanica.jpg" },
            { sk: "taxík", ua: "таксі", ru: "такси", en: "taxi", img: "/words/taxík.jpg" },
            { sk: "zastávka", ua: "зупинка", ru: "остановка", en: "stop", img: "/words/zastávka.jpg" },
            { sk: "lístok", ua: "квиток", ru: "билет", en: "ticket", img: "/words/lístok.jpg" },
            { sk: "letisko", ua: "аеропорт", ru: "аэропорт", en: "airport", img: "/words/letisko.jpg" },
        ],
    },
    {
        id: "8",
        title: {
            ua: "Урок 8 — Час і дні",
            ru: "Урок 8 — Время и дни",
            en: "Lesson 8 — Time and days",
        },
        words: [
            { sk: "čas", ua: "час", ru: "время", en: "time", img: "/words/čas.jpg" },
            { sk: "deň", ua: "день", ru: "день", en: "day", img: "/words/day.jpg" },
            { sk: "noc", ua: "ніч", ru: "ночь", en: "night", img: "/words/noc.jpg" },
            { sk: "týždeň", ua: "тиждень", ru: "неделя", en: "week", img: "/words/týždeň.jpg" },
            { sk: "mesiac", ua: "місяць", ru: "месяц", en: "month", img: "/words/mesiac.jpg" },
            { sk: "rok", ua: "рік", ru: "год", en: "year", img: "/words/rok.jpg" },
            { sk: "dnes", ua: "сьогодні", ru: "сегодня", en: "today", img: "/words/dnes.jpg" },
            { sk: "zajtra", ua: "завтра", ru: "завтра", en: "tomorrow", img: "/words/zajtra.jpg" },
            { sk: "včera", ua: "вчора", ru: "вчера", en: "yesterday", img: "/words/včera.jpg" },
            { sk: "hodina", ua: "година", ru: "час / час (ед.)", en: "hour", img: "/words/hodina.jpg" },
        ],
    },
    {
        id: "9",
        title: {
            ua: "Урок 9 — Робота",
            ru: "Урок 9 — Работа",
            en: "Lesson 9 — Work",
        },
        words: [
            { sk: "práca", ua: "робота", ru: "работа", en: "work", img: "/words/práca.jpg" },
            { sk: "zamestnanie", ua: "зайнятість / робота", ru: "занятость / работа", en: "job / employment", img: "/words/zamestnanie.jpg" },
            { sk: "firma", ua: "фірма", ru: "фирма", en: "company", img: "/words/firma.jpg" },
            { sk: "šéf", ua: "начальник", ru: "начальник", en: "boss", img: "/words/šéf.jpg" },
            { sk: "kolega", ua: "колега", ru: "коллега", en: "colleague", img: "/words/kolega.jpg" },
            { sk: "mzda", ua: "зарплата", ru: "зарплата", en: "salary", img: "/words/hotovosť.jpg" },
            { sk: "zmluva", ua: "договір", ru: "договор", en: "contract", img: "/words/kolega.jpg" },
            { sk: "pracovať", ua: "працювати", ru: "работать", en: "to work", img: "/words/pracovať.jpg" },
            { sk: "brigáda", ua: "підробіток", ru: "подработка", en: "part-time job", img: "/words/brigáda.jpg" },
            { sk: "dovolenka", ua: "відпустка", ru: "отпуск", en: "vacation", img: "/words/dovolenka.jpg" },
        ],
    },
    {
        id: "10",
        title: {
            ua: "Урок 10 — Школа",
            ru: "Урок 10 — Школа",
            en: "Lesson 10 — School",
        },
        words: [
            { sk: "škola", ua: "школа", ru: "школа", en: "school", img: "/words/school.jpg" },
            { sk: "žiak", ua: "учень", ru: "ученик", en: "student", img: "/words/žiak.jpg" },
            { sk: "učiteľ", ua: "вчитель", ru: "учитель", en: "teacher", img: "/words/učiteľ.jpg" },
            { sk: "trieda", ua: "клас", ru: "класс", en: "classroom", img: "/words/trieda.jpg" },
            { sk: "predmet", ua: "предмет", ru: "предмет", en: "subject", img: "/words/predmet.jpg" },
            { sk: "hodina", ua: "урок", ru: "урок", en: "lesson", img: "/words/hodina.jpg" },
            { sk: "úloha", ua: "завдання / домашня робота", ru: "задание / домашняя работа", en: "task / homework", img: "/words/úloha.jpg" },
            { sk: "test", ua: "тест", ru: "тест", en: "test", img: "/words/test.jpg" },
            { sk: "zošit", ua: "зошит", ru: "тетрадь", en: "notebook", img: "/words/zošitt.jpg" },
            { sk: "učebnica", ua: "підручник", ru: "учебник", en: "textbook", img: "/words/učebnica.jpg" },
        ],
    },
    {
        id: "11",
        title: {
            ua: "Урок 11 — Числа",
            ru: "Урок 11 — Числа",
            en: "Lesson 11 — Numbers",
        },
        words: [
            { sk: "nula", ua: "нуль", ru: "ноль", en: "zero", img: "/words/nula.jpg" },
            { sk: "jeden", ua: "один", ru: "один", en: "one", img: "/words/jeden.jpg" },
            { sk: "dva", ua: "два", ru: "два", en: "two", img: "/words/dva.jpg" },
            { sk: "tri", ua: "три", ru: "три", en: "three", img: "/words/tri.jpg" },
            { sk: "štyri", ua: "чотири", ru: "четыре", en: "four", img: "/words/štyri.jpg" },
            { sk: "päť", ua: "п’ять", ru: "пять", en: "five", img: "/words/päť.jpg" },
            { sk: "šesť", ua: "шість", ru: "шесть", en: "six", img: "/words/šesť.jpg" },
            { sk: "sedem", ua: "сім", ru: "семь", en: "seven", img: "/words/sedem.jpg" },
            { sk: "osem", ua: "вісім", ru: "восемь", en: "eight", img: "/words/osem.jpg" },
            { sk: "deväť", ua: "дев’ять", ru: "девять", en: "nine", img: "/words/deväť.jpg" },
        ],
    },
    {
        id: "12",
        title: {
            ua: "Урок 12 — Кольори",
            ru: "Урок 12 — Цвета",
            en: "Lesson 12 — Colors",
        },
        words: [
            { sk: "farba", ua: "колір", ru: "цвет", en: "color", img: "/words/farba.jpg" },
            { sk: "biely", ua: "білий", ru: "белый", en: "white", img: "/words/biely.jpg" },
            { sk: "čierny", ua: "чорний", ru: "чёрный", en: "black", img: "/words/čierny.jpg" },
            { sk: "červený", ua: "червоний", ru: "красный", en: "red", img: "/words/červený.jpg" },
            { sk: "modrý", ua: "синій", ru: "синий", en: "blue", img: "/words/modrý.jpg" },
            { sk: "zelený", ua: "зелений", ru: "зелёный", en: "green", img: "/words/zelený.jpg" },
            { sk: "žltý", ua: "жовтий", ru: "жёлтый", en: "yellow", img: "/words/žltý.jpg" },
            { sk: "oranžový", ua: "помаранчевий", ru: "оранжевый", en: "orange", img: "/words/oranžový.jpg" },
            { sk: "ružový", ua: "рожевий", ru: "розовый", en: "pink", img: "/words/ružový.jpg" },
            { sk: "hnedý", ua: "коричневий", ru: "коричневый", en: "brown", img: "/words/hnedý.jpg" },
        ],
    },
    {
        id: "13",
        title: {
            ua: "Урок 13 — Одяг",
            ru: "Урок 13 — Одежда",
            en: "Lesson 13 — Clothes",
        },
        words: [
            { sk: "oblečenie", ua: "одяг", ru: "одежда", en: "clothes", img: "/words/oblečenie.jpg" },
            { sk: "tričko", ua: "футболка", ru: "футболка", en: "T-shirt", img: "/words/tričko.jpg" },
            { sk: "nohavice", ua: "штани", ru: "брюки", en: "trousers", img: "/words/nohavice.jpg" },
            { sk: "bunda", ua: "куртка", ru: "куртка", en: "jacket", img: "/words/bunda.jpg" },
            { sk: "topánky", ua: "взуття", ru: "обувь", en: "shoes", img: "/words/topánky.jpg" },
            { sk: "kabát", ua: "пальто", ru: "пальто", en: "coat", img: "/words/kabát.jpg" },
            { sk: "šaty", ua: "сукня", ru: "платье", en: "dress", img: "/words/šaty.jpg" },
            { sk: "čiapka", ua: "шапка", ru: "шапка", en: "hat", img: "/words/čiapka.jpg" },
            { sk: "ponožky", ua: "шкарпетки", ru: "носки", en: "socks", img: "/words/ponožky.jpg" },
            { sk: "sveter", ua: "светр", ru: "свитер", en: "sweater", img: "/words/sveter.jpg" },
        ],
    },
    {
        id: "14",
        title: {
            ua: "Урок 14 — Тіло людини",
            ru: "Урок 14 — Тело человека",
            en: "Lesson 14 — Body",
        },
        words: [
            { sk: "telo", ua: "тіло", ru: "тело", en: "body", img: "/words/telo.jpg" },
            { sk: "hlava", ua: "голова", ru: "голова", en: "head", img: "/words/hlava.jpg" },
            { sk: "oko", ua: "око", ru: "глаз", en: "eye", img: "/words/oko.jpg" },
            { sk: "nos", ua: "ніс", ru: "нос", en: "nose", img: "/words/nos.jpg" },
            { sk: "ústa", ua: "рот", ru: "рот", en: "mouth", img: "/words/ústa.jpg" },
            { sk: "ruka", ua: "рука", ru: "рука", en: "hand", img: "/words/ruka.jpg" },
            { sk: "noha", ua: "нога", ru: "нога", en: "leg", img: "/words/noha.jpg" },
            { sk: "chrbát", ua: "спина", ru: "спина", en: "back", img: "/words/chrbát.jpg" },
            { sk: "brucho", ua: "живіт", ru: "живот", en: "belly", img: "/words/brucho.jpg" },
            { sk: "srdce", ua: "серце", ru: "сердце", en: "heart", img: "/words/srdce.jpg" },
        ],
    },
    {
        id: "15",
        title: {
            ua: "Урок 15 — Здоров’я",
            ru: "Урок 15 — Здоровье",
            en: "Lesson 15 — Health",
        },
        words: [
            { sk: "zdravie", ua: "здоров’я", ru: "здоровье", en: "health", img: "/words_pl/zdrowie.jpg" },
            { sk: "choroba", ua: "хвороба", ru: "болезнь", en: "illness", img: "/words/choroba.jpg" },
            { sk: "lekár", ua: "лікар", ru: "врач", en: "doctor", img: "/words/lekár.jpg" },
            { sk: "nemocnica", ua: "лікарня", ru: "больница", en: "hospital", img: "/words/nemocnica.jpg" },
            { sk: "liek", ua: "ліки", ru: "лекарство / лекарства", en: "medicine", img: "/words_pl/lek.jpg" },
            { sk: "bolesť", ua: "біль", ru: "боль", en: "pain", img: "/words_pl/ból.jpg" },
            { sk: "teplota", ua: "температура", ru: "температура", en: "temperature", img: "/words_pl/temperatura.jpg" },
            { sk: "kašeľ", ua: "кашель", ru: "кашель", en: "cough", img: "/words_pl/kaszel.jpg" },
            { sk: "prechladnutie", ua: "застуда", ru: "простуда", en: "cold", img: "/words_pl/przeziębienie.jpg" },
            { sk: "uzdraviť sa", ua: "одужати", ru: "выздороветь", en: "to recover", img: "/words_pl/wyzdrowieć.jpg" },
        ],
    },
    {
        id: "16",
        title: {
            ua: "Урок 16 — Погода",
            ru: "Урок 16 — Погода",
            en: "Lesson 16 — Weather",
        },
        words: [
            { sk: "počasie", ua: "погода", ru: "погода", en: "weather", img: "/words_a0_cz/počasí.jpg" },
            { sk: "slnko", ua: "сонце", ru: "солнце", en: "sun", img: "/words_a0_cz/slunce.jpg" },
            { sk: "dážď", ua: "дощ", ru: "дождь", en: "rain", img: "/words_a0_cz/déšť.jpg" },
            { sk: "sneh", ua: "сніг", ru: "снег", en: "snow", img: "/words_a0_cz/sníh.jpg" },
            { sk: "vietor", ua: "вітер", ru: "ветер", en: "wind", img: "/words_a0_cz/vítr.jpg" },
            { sk: "oblak", ua: "хмара", ru: "облако", en: "cloud", img: "/words_a0_cz/mrak.jpg" },
            { sk: "teplo", ua: "тепло", ru: "тепло", en: "warmth", img: "/words_pl/ciepło.jpg" },
            { sk: "zima", ua: "холод", ru: "холод", en: "cold", img: "/words/zima.jpg" },
            { sk: "búrka", ua: "буря", ru: "буря / гроза", en: "storm", img: "/words_a0_cz/bouře.jpg" },
            { sk: "teplota", ua: "температура", ru: "температура", en: "temperature", img: "/words_pl/temperatura.jpg" },
        ],
    },
    {
        id: "17",
        title: {
            ua: "Урок 17 — Природа",
            ru: "Урок 17 — Природа",
            en: "Lesson 17 — Nature",
        },
        words: [
            { sk: "príroda", ua: "природа", ru: "природа", en: "nature", img: "/words_a0_cz/příroda.jpg" },
            { sk: "strom", ua: "дерево", ru: "дерево", en: "tree", img: "/words_pl/drzewo.jpg" },
            { sk: "les", ua: "ліс", ru: "лес", en: "forest", img: "/words_pl/las.jpg" },
            { sk: "rieka", ua: "річка", ru: "река", en: "river", img: "/words_a0_cz/řeka.jpg" },
            { sk: "jazero", ua: "озеро", ru: "озеро", en: "lake", img: "/words_pl/jezioro.jpg" },
            { sk: "hora", ua: "гора", ru: "гора", en: "mountain", img: "/words_pl/góra.jpg" },
            { sk: "kvet", ua: "квітка", ru: "цветок", en: "flower", img: "/words_a0_cz/květina.jpg" },
            { sk: "tráva", ua: "трава", ru: "трава", en: "grass", img: "/words_pl/trawa.jpg" },
            { sk: "zviera", ua: "тварина", ru: "животное", en: "animal", img: "/words_a0_cz/zvíře.jpg" },
            { sk: "zem", ua: "земля", ru: "земля", en: "earth", img: "/words_a0_cz/země.jpg" },
        ],
    },
    {
        id: "18",
        title: {
            ua: "Урок 18 — Побут",
            ru: "Урок 18 — Быт",
            en: "Lesson 18 — Household",
        },
        words: [
            { sk: "domácnosť", ua: "побут", ru: "быт", en: "household", img: "/words_pl/gospodarstwo domowe.jpg" },
            { sk: "dom", ua: "дім", ru: "дом", en: "house", img: "/words/dom.jpg" },
            { sk: "byt", ua: "квартира", ru: "квартира", en: "apartment", img: "/words/bytt.jpg" },
            { sk: "izba", ua: "кімната", ru: "комната", en: "room", img: "/words/izba.jpg" },
            { sk: "posteľ", ua: "ліжко", ru: "кровать", en: "bed", img: "/words/posteľ.jpg" },
            { sk: "stôl", ua: "стіл", ru: "стол", en: "table", img: "/words/stôl.jpg" },
            { sk: "stolička", ua: "стілець", ru: "стул", en: "chair", img: "/words/stolička.jpg" },
            { sk: "kuchyňa", ua: "кухня", ru: "кухня", en: "kitchen", img: "/words/kuchyňa.jpg" },
            { sk: "chladnička", ua: "холодильник", ru: "холодильник", en: "fridge", img: "/words_a0_cz/lednička.jpg" },
            { sk: "upratovať", ua: "прибирати", ru: "убирать / прибираться", en: "to clean", img: "/words_a0_cz/uklízet.jpg" },
        ],
    },
    {
        id: "19",
        title: {
            ua: "Урок 19 — Дії та дієслова",
            ru: "Урок 19 — Действия и глаголы",
            en: "Lesson 19 — Actions and verbs",
        },
        words: [
            { sk: "robiť", ua: "робити", ru: "делать", en: "to do", img: "/words_a0_cz/dělat.jpg" },
            { sk: "ísť", ua: "йти", ru: "идти", en: "to go", img: "/words_a0_cz/jít.jpg" },
            { sk: "prísť", ua: "прийти", ru: "прийти", en: "to come", img: "/words_a0_cz/přijít.jpg" },
            { sk: "vidieť", ua: "бачити", ru: "видеть", en: "to see", img: "/words_a0_cz/vidět.jpg" },
            { sk: "hovoriť", ua: "говорити", ru: "говорить", en: "to speak", img: "/words_a0_cz/mluvit.jpg" },
            { sk: "jesť", ua: "їсти", ru: "есть", en: "to eat", img: "/words_a0_cz/jíst.jpg" },
            { sk: "piť", ua: "пити", ru: "пить", en: "to drink", img: "/words/piť.jpg" },
            { sk: "spať", ua: "спати", ru: "спать", en: "to sleep", img: "/words_a0_cz/spát.jpg" },
            { sk: "pracovať", ua: "працювати", ru: "работать", en: "to work", img: "/words/pracovať.jpg" },
            { sk: "učiť sa", ua: "вчитися", ru: "учиться", en: "to study", img: "/words_a0_cz/učit se.jpg" },
        ],
    },
    {
        id: "20",
        title: {
            ua: "Урок 20 — Питання і відповіді",
            ru: "Урок 20 — Вопросы и ответы",
            en: "Lesson 20 — Questions and answers",
        },
        words: [
            { sk: "kto", ua: "хто", ru: "кто", en: "who", img: "/words_a0_cz/kdo.jpg" },
            { sk: "čo", ua: "що", ru: "что", en: "what", img: "/words_a0_cz/co.jpg" },
            { sk: "kde", ua: "де", ru: "где", en: "where", img: "/words_pl/gdzie.jpg" },
            { sk: "kedy", ua: "коли", ru: "когда", en: "when", img: "/words_a0_cz/kdy.jpg" },
            { sk: "prečo", ua: "чому", ru: "почему", en: "why", img: "/words_a0_cz/proč.jpg" },
            { sk: "ako", ua: "як", ru: "как", en: "how", img: "/words_a0_cz/jak.jpg" },
            { sk: "koľko", ua: "скільки", ru: "сколько", en: "how much / how many", img: "/words/koľko.jpg" },
            { sk: "áno", ua: "так", ru: "да", en: "yes", img: "/words_a0_cz/ano.jpg" },
            { sk: "nie", ua: "ні", ru: "нет", en: "no", img: "/words_a0_cz/ne.jpg" },
            { sk: "možno", ua: "можливо", ru: "возможно", en: "maybe", img: "/words_a0_cz/možná.jpg" },
        ],
    },
    {
        id: "21",
        title: {
            ua: "Урок 21 — Місця",
            ru: "Урок 21 — Места",
            en: "Lesson 21 — Places",
        },
        words: [
            { sk: "miesto", ua: "місце", ru: "место", en: "place", img: "/words/miesto.jpg" },
            { sk: "centrum", ua: "центр", ru: "центр", en: "center", img: "/words/centrum.jpg" },
            { sk: "obchod", ua: "магазин", ru: "магазин", en: "shop", img: "/words/obchod.jpg" },
            { sk: "reštaurácia", ua: "ресторан", ru: "ресторан", en: "restaurant", img: "/words_a0_cz/restaurace.jpg" },
            { sk: "kaviareň", ua: "кафе", ru: "кафе", en: "café", img: "/words_a0_cz/kavárna.jpg" },
            { sk: "park", ua: "парк", ru: "парк", en: "park", img: "/words/park.jpg" },
            { sk: "banka", ua: "банк", ru: "банк", en: "bank", img: "/words_pl/bank.jpg" },
            { sk: "pošta", ua: "пошта", ru: "почта", en: "post office", img: "/words_pl/poczta.jpg" },
            { sk: "polícia", ua: "поліція", ru: "полиция", en: "police", img: "/words_a0_cz/policie.jpg" },
            { sk: "stanica", ua: "станція / вокзал", ru: "станция / вокзал", en: "station", img: "/words/stanica.jpg" },
        ],
    },
    {
        id: "22",
        title: {
            ua: "Урок 22 — Емоції",
            ru: "Урок 22 — Эмоции",
            en: "Lesson 22 — Emotions",
        },
        words: [
            { sk: "radosť", ua: "радість", ru: "радость", en: "joy", img: "/words_a0_cz/radost.jpg" },
            { sk: "smútok", ua: "смуток", ru: "грусть / печаль", en: "sadness", img: "/words_a0_cz/smutek.jpg" },
            { sk: "strach", ua: "страх", ru: "страх", en: "fear", img: "/words/strach.jpg" },
            { sk: "hnev", ua: "злість", ru: "злость / гнев", en: "anger", img: "/words_a0_cz/hněv.jpg" },
            { sk: "láska", ua: "любов", ru: "любовь", en: "love", img: "/words_pl/miłość.jpg" },
            { sk: "šťastie", ua: "щастя", ru: "счастье", en: "happiness", img: "/words_a0_cz/štěstí.jpg" },
            { sk: "únava", ua: "втома", ru: "усталость", en: "tiredness", img: "/words_pl/zmęczenie.jpg" },
            { sk: "stres", ua: "стрес", ru: "стресс", en: "stress", img: "/words/stres.jpg" },
            { sk: "pokoj", ua: "спокій", ru: "покой / спокойствие", en: "calm", img: "/words_a0_cz/klid.jpg" },
            { sk: "prekvapenie", ua: "здивування", ru: "удивление", en: "surprise", img: "/words_a0_cz/překvapení.jpg" },
        ],
    },
    {
        id: "23",
        title: {
            ua: "Урок 23 — Хобі",
            ru: "Урок 23 — Хобби",
            en: "Lesson 23 — Hobbies",
        },
        words: [
            { sk: "hobby", ua: "хобі", ru: "хобби", en: "hobby", img: "/words/hobby.jpg" },
            { sk: "šport", ua: "спорт", ru: "спорт", en: "sport", img: "/words_a0_cz/sport.jpg" },
            { sk: "futbal", ua: "футбол", ru: "футбол", en: "football", img: "/words_a0_cz/fotbal.jpg" },
            { sk: "hudba", ua: "музика", ru: "музыка", en: "music", img: "/words_pl/muzyka.jpg" },
            { sk: "film", ua: "фільм", ru: "фильм", en: "film", img: "/words/film.jpg" },
            { sk: "čítanie", ua: "читання", ru: "чтение", en: "reading", img: "/words_a0_cz/čtení.jpg" },
            { sk: "cestovanie", ua: "подорожі", ru: "путешествия", en: "traveling", img: "/words_a0_cz/cestování.jpg" },
            { sk: "hra", ua: "гра", ru: "игра", en: "game", img: "/words_pl/gra.jpg" },
            { sk: "maľovanie", ua: "малювання", ru: "рисование", en: "painting", img: "/words_a0_cz/malování.jpg" },
            { sk: "tanec", ua: "танець", ru: "танец", en: "dance", img: "/words_pl/taniec.jpg" },
        ],
    },
    {
        id: "24",
        title: {
            ua: "Урок 24 — Спілкування",
            ru: "Урок 24 — Общение",
            en: "Lesson 24 — Communication",
        },
        words: [
            { sk: "hovoriť", ua: "говорити", ru: "говорить", en: "to speak", img: "/words_a0_cz/mluvit.jpg" },
            { sk: "rozprávať", ua: "розповідати", ru: "рассказывать", en: "to tell", img: "/words_a0_cz/vyprávět.jpg" },
            { sk: "počúvať", ua: "слухати", ru: "слушать", en: "to listen", img: "/words_a0_cz/poslouchat.jpg" },
            { sk: "pýtať sa", ua: "питати", ru: "спрашивать", en: "to ask", img: "/words_a0_cz/ptát se.jpg" },
            { sk: "odpovedať", ua: "відповідати", ru: "отвечать", en: "to answer", img: "/words_a0_cz/odpovědět.jpg" },
            { sk: "telefonovať", ua: "телефонувати", ru: "звонить / разговаривать по телефону", en: "to call", img: "/words_a0_cz/telefonovat.jpg" },
            { sk: "správa", ua: "повідомлення", ru: "сообщение", en: "message", img: "/words_a0_cz/zpráva.jpg" },
            { sk: "stretnutie", ua: "зустріч", ru: "встреча", en: "meeting", img: "/words_a0_cz/setkání.jpg" },
            { sk: "diskusia", ua: "обговорення", ru: "обсуждение / дискуссия", en: "discussion", img: "/words_a0_cz/diskuze.jpg" },
            { sk: "pozdrav", ua: "привітання", ru: "приветствие", en: "greeting", img: "/words_pl/pozdrowienie.jpg" },
        ],
    },
    {
        id: "25",
        title: {
            ua: "Урок 25 — Подорожі",
            ru: "Урок 25 — Путешествия",
            en: "Lesson 25 — Travel",
        },
        words: [
            { sk: "cesta", ua: "подорож", ru: "путешествие / дорога", en: "trip / journey", img: "/words_pl/droga.jpg" },
            { sk: "cestovať", ua: "подорожувати", ru: "путешествовать", en: "to travel", img: "/words_a0_cz/cestovat.jpg" },
            { sk: "kufor", ua: "валіза", ru: "чемодан", en: "suitcase", img: "/words_a0_cz/kufr.jpg" },
            { sk: "pas", ua: "паспорт", ru: "паспорт", en: "passport", img: "/words_pl/paszport.jpg" },
            { sk: "letenka", ua: "авіаквиток", ru: "авиабилет", en: "plane ticket", img: "/words_pl/bilet lotniczy.jpg" },
            { sk: "vlak", ua: "поїзд", ru: "поезд", en: "train", img: "/words/vlak.jpg" },
            { sk: "autobus", ua: "автобус", ru: "автобус", en: "bus", img: "/words/autobus.jpg" },
            { sk: "letisko", ua: "аеропорт", ru: "аэропорт", en: "airport", img: "/words/letisko.jpg" },
            { sk: "mapa", ua: "карта", ru: "карта", en: "map", img: "/words/mapa.jpg" },
            { sk: "rezervácia", ua: "бронювання", ru: "бронирование", en: "reservation", img: "/words_a0_cz/rezervace.jpg" },
        ],
    },
    {
        id: "26",
        title: {
            ua: "Урок 26 — Готель і ресторан",
            ru: "Урок 26 — Отель и ресторан",
            en: "Lesson 26 — Hotel and restaurant",
        },
        words: [
            { sk: "hotel", ua: "готель", ru: "отель", en: "hotel", img: "/words/hotel.jpg" },
            { sk: "izba", ua: "кімната", ru: "комната / номер", en: "room", img: "/words/izba.jpg" },
            { sk: "recepcia", ua: "ресепшн", ru: "ресепшн", en: "reception", img: "/words_a0_cz/recepce.jpg" },
            { sk: "reštaurácia", ua: "ресторан", ru: "ресторан", en: "restaurant", img: "/words_a0_cz/restaurace.jpg" },
            { sk: "menu", ua: "меню", ru: "меню", en: "menu", img: "/words/menu.jpg" },
            { sk: "objednať", ua: "замовити", ru: "заказать", en: "to order", img: "/words_a0_cz/objednat.jpg" },
            { sk: "raňajky", ua: "сніданок", ru: "завтрак", en: "breakfast", img: "/words_a0_cz/snídaně.jpg" },
            { sk: "obed", ua: "обід", ru: "обед", en: "lunch", img: "/words_a0_cz/oběd.jpg" },
            { sk: "večera", ua: "вечеря", ru: "ужин", en: "dinner", img: "/words_a0_cz/večeře.jpg" },
            { sk: "účet", ua: "рахунок", ru: "счёт", en: "bill", img: "/words_pl/rachunek.jpg" },
        ],
    },
    {
        id: "27",
        title: {
            ua: "Урок 27 — Гроші",
            ru: "Урок 27 — Деньги",
            en: "Lesson 27 — Money",
        },
        words: [
            { sk: "peniaze", ua: "гроші", ru: "деньги", en: "money", img: "/words_a0_cz/peníze.jpg" },
            { sk: "euro", ua: "євро", ru: "евро", en: "euro", img: "/words/euro.jpg" },
            { sk: "cena", ua: "ціна", ru: "цена", en: "price", img: "/words/cena.jpg" },
            { sk: "platba", ua: "платіж", ru: "платёж", en: "payment", img: "/words_pl/płatność.jpg" },
            { sk: "hotovosť", ua: "готівка", ru: "наличные", en: "cash", img: "/words/hotovosť.jpg" },
            { sk: "karta", ua: "картка", ru: "карта", en: "card", img: "/words/karta.jpg" },
            { sk: "účet", ua: "рахунок", ru: "счёт", en: "account / bill", img: "/words_pl/rachunek.jpg" },
            { sk: "banka", ua: "банк", ru: "банк", en: "bank", img: "/words_pl/bank.jpg" },
            { sk: "zľava", ua: "знижка", ru: "скидка", en: "discount", img: "/words/zľava.jpg" },
            { sk: "výdavky", ua: "витрати", ru: "расходы", en: "expenses", img: "/words_a0_cz/výdaje.jpg" },
        ],
    },
    {
        id: "28",
        title: {
            ua: "Урок 28 — Технології",
            ru: "Урок 28 — Технологии",
            en: "Lesson 28 — Technology",
        },
        words: [
            { sk: "technológia", ua: "технологія", ru: "технология", en: "technology", img: "/words_a0_cz/technologie.jpg" },
            { sk: "počítač", ua: "комп’ютер", ru: "компьютер", en: "computer", img: "/words_a0_cz/počítač.jpg" },
            { sk: "telefón", ua: "телефон", ru: "телефон", en: "phone", img: "/words_a0_cz/telefon.jpg" },
            { sk: "internet", ua: "інтернет", ru: "интернет", en: "internet", img: "/words/internet.jpg" },
            { sk: "aplikácia", ua: "додаток", ru: "приложение", en: "app", img: "/words_a0_cz/aplikace.jpg" },
            { sk: "program", ua: "програма", ru: "программа", en: "program", img: "/words/program.jpg" },
            { sk: "systém", ua: "система", ru: "система", en: "system", img: "/words/systém.jpg" },
            { sk: "sieť", ua: "мережа", ru: "сеть", en: "network", img: "/words_a0_cz/síť.jpg" },
            { sk: "dáta", ua: "дані", ru: "данные", en: "data", img: "/words_a0_cz/data.jpg" },
            { sk: "heslo", ua: "пароль", ru: "пароль", en: "password", img: "/words_pl/hasło.jpg" },
        ],
    },
    {
        id: "29",
        title: {
            ua: "Урок 29 — Повсякденні фрази",
            ru: "Урок 29 — Повседневные фразы",
            en: "Lesson 29 — Everyday phrases",
        },
        words: [
            { sk: "dobrý deň", ua: "добрий день", ru: "добрый день", en: "good afternoon", img: "/words_a0_cz/dobrý den.jpg" },
            { sk: "ahoj", ua: "привіт", ru: "привет", en: "hi", img: "/words_pl/cześć.jpg" },
            { sk: "ďakujem", ua: "дякую", ru: "спасибо", en: "thank you", img: "/words_a0_cz/děkuji.jpg" },
            { sk: "prosím", ua: "будь ласка", ru: "пожалуйста", en: "please", img: "/words_pl/proszę.jpg" },
            { sk: "prepáč", ua: "вибач", ru: "извини", en: "sorry", img: "/words_a0_cz/omlouvám se.jpg" },
            { sk: "rozumiem", ua: "розумію", ru: "понимаю", en: "I understand", img: "/words_a0_cz/rozumím.jpg" },
            { sk: "nerozumiem", ua: "не розумію", ru: "не понимаю", en: "I don't understand", img: "/words_a0_cz/nerozumím.jpg" },
            { sk: "pomôžte", ua: "допоможіть", ru: "помогите", en: "help", img: "/words_a0_cz/pomozte.jpg" },
            { sk: "jasné", ua: "ясно", ru: "ясно", en: "sure", img: "/words_a0_cz/jasné.jpg" },
            { sk: "dobre", ua: "добре", ru: "хорошо", en: "okay", img: "/words_a0_cz/dobře.jpg" },
        ],
    },
    {
        id: "30",
        title: {
            ua: "Урок 30 — Повторення бази",
            ru: "Урок 30 — Повторение базы",
            en: "Lesson 30 — Basic review",
        },
        words: [
            { sk: "ja", ua: "я", ru: "я", en: "I", img: "/words_a0_cz/já.jpg" },
            { sk: "ty", ua: "ти", ru: "ты", en: "you", img: "/words/ty.jpg" },
            { sk: "on", ua: "він", ru: "он", en: "he", img: "/words/on.jpg" },
            { sk: "ona", ua: "вона", ru: "она", en: "she", img: "/words/ona.jpg" },
            { sk: "my", ua: "ми", ru: "мы", en: "we", img: "/words/my.jpg" },
            { sk: "vy", ua: "ви", ru: "вы", en: "you (plural/formal)", img: "/words_pl/wy.jpg" },
            { sk: "oni", ua: "вони", ru: "они", en: "they", img: "/words/oni.jpg" },
            { sk: "byť", ua: "бути", ru: "быть", en: "to be", img: "/words_pl/być.jpg" },
            { sk: "mať", ua: "мати", ru: "иметь", en: "to have", img: "/words_pl/mieć.jpg" },
            { sk: "ísť", ua: "йти", ru: "идти", en: "to go", img: "/words_a0_cz/jít.jpg" },
        ],
    },]