import type { Lesson } from "../data";

export const A1_ALL: Lesson[] = [
  {
    id: "a1-1",
    title: { ua: "Урок 1 — Знайомство", ru: "Урок 1 — Знакомство", en: "Lesson 1 — Introduction" },
    words: [
      { sk: "volať sa", ua: "називатися", ru: "называться", en: "to be called", img: "/words_a1/volať sa.jpg" },
      { sk: "zoznámiť sa", ua: "познайомитися", ru: "познакомиться", en: "to get acquainted", img: "/words_a1/zoznámiť sa.jpg" },
      { sk: "meno", ua: "ім’я", ru: "имя", en: "name", img: "/words_a1/meno.jpg" },
      { sk: "priezvisko", ua: "прізвище", ru: "фамилия", en: "surname", img: "/words_a1/priezvisko.jpg" },
      { sk: "odkiaľ", ua: "звідки", ru: "откуда", en: "from where", img: "/words_a1/odkiaľ.jpg" },
      { sk: "bývať", ua: "жити (мешкати)", ru: "жить (проживать)", en: "to live", img: "/words_a1/bývať.jpg" },
      { sk: "pracovať", ua: "працювати", ru: "работать", en: "to work", img: "/words_a1/pracovať.jpg" },
      { sk: "teší ma", ua: "приємно познайомитись", ru: "приятно познакомиться", en: "nice to meet you", img: "/words_a1/teší ma.jpg" },
      { sk: "mať rád", ua: "подобатися", ru: "нравиться", en: "to like", img: "/words_a1/mať rád.jpg" },
      { sk: "ďakujem", ua: "дякую", ru: "спасибо", en: "thank you", img: "/words_a1/ďakujem.jpg" },
    ],
  },
  {
    id: "a1-2",
    title: { ua: "Урок 2 — Ввічливі фрази", ru: "Урок 2 — Вежливые фразы", en: "Lesson 2 — Polite phrases" },
    words: [
      { sk: "prosím", ua: "будь ласка", ru: "пожалуйста", en: "please", img: "/words_a1/prosím.jpg" },
      { sk: "prepáčte", ua: "вибачте", ru: "извините", en: "excuse me", img: "/words_a1/prepáčte.jpg" },
      { sk: "ďakujem pekne", ua: "дуже дякую", ru: "большое спасибо", en: "thank you very much", img: "/words_a1/ďakujem pekne.jpg" },
      { sk: "niet za čo", ua: "нема за що", ru: "не за что", en: "you're welcome", img: "/words_a1/niet za čo.jpg" },
      { sk: "môžem", ua: "можна", ru: "можно", en: "may I / can I", img: "/words_a1/môžem.jpg" },
      { sk: "môžete", ua: "можете", ru: "можете", en: "can you", img: "/words_a1/môžete.jpg" },
      { sk: "pomôžte mi", ua: "допоможіть мені", ru: "помогите мне", en: "help me", img: "/words_a1/pomôžte mi.jpg" },
      { sk: "nech sa páči", ua: "прошу / будь ласка (даючи щось)", ru: "пожалуйста (вот, когда даёте что-то)", en: "here you go", img: "/words_a1/nech sa páči.jpg" },
      { sk: "v poriadku", ua: "в порядку", ru: "в порядке", en: "all right", img: "/words_a1/v poriadku.jpg" },
      { sk: "jasné", ua: "ясно", ru: "ясно", en: "sure", img: "/words_a1/jasné.jpg" },
    ],
  },
  {
    id: "a1-3",
    title: { ua: "Урок 3 — Місто", ru: "Урок 3 — Город", en: "Lesson 3 — City" },
    words: [
      { sk: "križovatka", ua: "перехрестя", ru: "перекрёсток", en: "intersection", img: "/words_a1/križovatka.jpg" },
      { sk: "semafor", ua: "світлофор", ru: "светофор", en: "traffic light", img: "/words_a1/semafor.jpg" },
      { sk: "most", ua: "міст", ru: "мост", en: "bridge", img: "/words_a1/most.jpg" },
      { sk: "kino", ua: "кінотеатр", ru: "кинотеатр", en: "cinema", img: "/words_a1/kino.jpg" },
      { sk: "múzeum", ua: "музей", ru: "музей", en: "museum", img: "/words_a1/múzeum.jpg" },
      { sk: "lekáreň", ua: "аптека", ru: "аптека", en: "pharmacy", img: "/words_a1/lekáreň.jpg" },
      { sk: "knižnica", ua: "бібліотека", ru: "библиотека", en: "library", img: "/words_a1/knižnica.jpg" },
      { sk: "trh", ua: "ринок", ru: "рынок", en: "market", img: "/words_a1/trh.jpg" },
      { sk: "vstup", ua: "вхід", ru: "вход", en: "entrance", img: "/words_a1/vstup.jpg" },
      { sk: "východ", ua: "вихід", ru: "выход", en: "exit", img: "/words_a1/východ.jpg" },
    ],
  },
  {
    id: "a1-4",
    title: { ua: "Урок 4 — Магазин (розширено)", ru: "Урок 4 — Магазин (расширено)", en: "Lesson 4 — Shop (extended)" },
    words: [
      { sk: "pokladník", ua: "касир", ru: "кассир", en: "cashier", img: "/words_a1/pokladník.jpg" },
      { sk: "regál", ua: "стелаж/полиця", ru: "стеллаж/полка", en: "shelf", img: "/words_a1/regál.jpg" },
      { sk: "oddelenie", ua: "відділ", ru: "отдел", en: "department", img: "/words_a1/oddelenie.jpg" },
      { sk: "veľkosť", ua: "розмір", ru: "размер", en: "size", img: "/words_a1/veľkosť.jpg" },
      { sk: "skúsiť", ua: "приміряти/спробувати", ru: "примерить/попробовать", en: "to try", img: "/words_a1/skúsiť.jpg" },
      { sk: "vymeniť", ua: "обміняти", ru: "обменять", en: "to exchange", img: "/words_a1/vymeniť.jpg" },
      { sk: "vrátiť", ua: "повернути (товар)", ru: "вернуть (товар)", en: "to return", img: "/words_a1/vrátiť.jpg" },
      { sk: "záruka", ua: "гарантія", ru: "гарантия", en: "warranty", img: "/words_a1/záruka.jpg" },
      { sk: "balenie", ua: "упаковка", ru: "упаковка", en: "packaging", img: "/words_a1/balenie.jpg" },
      { sk: "účtovať", ua: "рахувати (на касі)", ru: "пробивать (на кассе) / считать", en: "to charge / bill", img: "/words_a1/účtovať.jpg" },
    ],
  },
  {
    id: "a1-5",
    title: { ua: "Урок 5 — Їжа (у ресторані)", ru: "Урок 5 — Еда (в ресторане)", en: "Lesson 5 — Food (in a restaurant)" },
    words: [
      { sk: "objednať", ua: "замовити", ru: "заказать", en: "to order", img: "/words_a1/objednať.jpg" },
      { sk: "porcia", ua: "порція", ru: "порция", en: "portion", img: "/words_a1/porcia.jpg" },
      { sk: "príloha", ua: "гарнір", ru: "гарнир", en: "side dish", img: "/words_a1/príloha.jpg" },
      { sk: "dezert", ua: "десерт", ru: "десерт", en: "dessert", img: "/words_a1/dezert.jpg" },
      { sk: "chutný", ua: "смачний", ru: "вкусный", en: "tasty", img: "/words_a1/chutný.jpg" },
      { sk: "hladný", ua: "голодний", ru: "голодный", en: "hungry", img: "/words_a1/hladný.jpg" },
      { sk: "smädný", ua: "спраглий", ru: "хотящий пить / испытывающий жажду", en: "thirsty", img: "/words_a1/smädný.jpg" },
      { sk: "účtovať", ua: "виставити рахунок", ru: "выставить счёт", en: "to bill", img: "/words_a1/účtovať.jpg" },
      { sk: "zaplatiť", ua: "заплатити", ru: "заплатить", en: "to pay", img: "/words_a1/zaplatiť.jpg" },
      { sk: "rezervácia", ua: "бронювання", ru: "бронирование", en: "reservation", img: "/words_a1/rezervácia.jpg" },
    ],
  },
  {
    id: "a1-6",
    title: { ua: "Урок 6 — Транспорт", ru: "Урок 6 — Транспорт", en: "Lesson 6 — Transport" },
    words: [
      { sk: "cestovný poriadok", ua: "розклад", ru: "расписание", en: "timetable", img: "/words_a1/cestovný poriadok.jpg" },
      { sk: "prestup", ua: "пересадка", ru: "пересадка", en: "transfer", img: "/words_a1/prestup.jpg" },
      { sk: "nástupište", ua: "платформа", ru: "платформа", en: "platform", img: "/words_a1/nástupište.jpg" },
      { sk: "meškať", ua: "запізнюватися", ru: "опаздывать", en: "to be late", img: "/words_a1/meškať.jpg" },
      { sk: "odchod", ua: "відправлення", ru: "отправление", en: "departure", img: "/words_a1/odchod.jpg" },
      { sk: "príchod", ua: "прибуття", ru: "прибытие", en: "arrival", img: "/words_a1/príchod.jpg" },
      { sk: "lístok", ua: "квиток", ru: "билет", en: "ticket", img: "/words_a1/lístok.jpg" },
      { sk: "kúpiť", ua: "купити", ru: "купить", en: "to buy", img: "/words_a1/kúpiť.jpg" },
      { sk: "vystúpiť", ua: "вийти (з транспорту)", ru: "выйти (из транспорта)", en: "to get off", img: "/words_a1/vystúpiť.jpg" },
      { sk: "nastúpiť", ua: "сісти (в транспорт)", ru: "сесть (в транспорт) / войти", en: "to get on", img: "/words_a1/nastúpiť.jpg" },
    ],
  },
  {
    id: "a1-7",
    title: { ua: "Урок 7 — Дім (побутові дії)", ru: "Урок 7 — Дом (бытовые действия)", en: "Lesson 7 — Home (household actions)" },
    words: [
      { sk: "variť", ua: "готувати", ru: "готовить", en: "to cook", img: "/words_a1/variť.jpg" },
      { sk: "upratovať", ua: "прибирати", ru: "убирать / прибираться", en: "to clean", img: "/words_a1/upratovať.jpg" },
      { sk: "umývať", ua: "мити", ru: "мыть", en: "to wash", img: "/words_a1/umývať.jpg" },
      { sk: "prať", ua: "прати", ru: "стирать", en: "to wash clothes", img: "/words_a1/prať.jpg" },
      { sk: "žehliť", ua: "прасувати", ru: "гладить", en: "to iron", img: "/words_a1/žehliť.jpg" },
      { sk: "otvoriť", ua: "відкрити", ru: "открыть", en: "to open", img: "/words_a1/otvoriť.jpg" },
      { sk: "zatvoriť", ua: "закрити", ru: "закрыть", en: "to close", img: "/words_a1/zatvoriť.jpg" },
      { sk: "zapnúť", ua: "увімкнути", ru: "включить", en: "to turn on", img: "/words_a1/zapnúť.jpg" },
      { sk: "vypnúť", ua: "вимкнути", ru: "выключить", en: "to turn off", img: "/words_a1/vypnúť.jpg" },
      { sk: "hľadať", ua: "шукати", ru: "искать", en: "to look for", img: "/words_a1/hľadať.jpg" },
    ],
  },
  {
    id: "a1-8",
    title: { ua: "Урок 8 — Робота (процеси)", ru: "Урок 8 — Работа (процессы)", en: "Lesson 8 — Work (processes)" },
    words: [
      { sk: "pracovisko", ua: "робоче місце", ru: "рабочее место", en: "workplace", img: "/words_a1/pracovisko.jpg" },
      { sk: "zmena", ua: "зміна", ru: "смена", en: "shift", img: "/words_a1/zmena.jpg" },
      { sk: "nadčas", ua: "надурочно", ru: "сверхурочно", en: "overtime", img: "/words_a1/nadčas.jpg" },
      { sk: "porada", ua: "нарада", ru: "совещание", en: "meeting", img: "/words_a1/porada.jpg" },
      { sk: "úloha", ua: "завдання", ru: "задание", en: "task", img: "/words_a1/úloha.jpg" },
      { sk: "hotovo", ua: "готово", ru: "готово", en: "done", img: "/words_a1/hotovo.jpg" },
      { sk: "skontrolovať", ua: "перевірити", ru: "проверить", en: "to check", img: "/words_a1/skontrolovať.jpg" },
      { sk: "opraviť", ua: "відремонтувати/виправити", ru: "отремонтировать/исправить", en: "to repair / fix", img: "/words_a1/opraviť.jpg" },
      { sk: "začať", ua: "почати", ru: "начать", en: "to start", img: "/words_a1/začať.jpg" },
      { sk: "skončiť", ua: "закінчити", ru: "закончить", en: "to finish", img: "/words_a1/skončiť.jpg" },
    ],
  },
  {
    id: "a1-9",
    title: { ua: "Урок 9 — Емоції і стани", ru: "Урок 9 — Эмоции и состояния", en: "Lesson 9 — Emotions and states" },
    words: [
      { sk: "unavený", ua: "втомлений", ru: "уставший", en: "tired", img: "/words_a1/unavený.jpg" },
      { sk: "šťastný", ua: "щасливий", ru: "счастливый", en: "happy", img: "/words_a1/šťastný.jpg" },
      { sk: "smutný", ua: "сумний", ru: "грустный", en: "sad", img: "/words_a1/smutný.jpg" },
      { sk: "nahnevaný", ua: "злий", ru: "злой / сердитый", en: "angry", img: "/words_a1/nahnevaný.jpg" },
      { sk: "nervózny", ua: "нервовий", ru: "нервный", en: "nervous", img: "/words_a1/nervózny.jpg" },
      { sk: "pokojný", ua: "спокійний", ru: "спокойный", en: "calm", img: "/words_a1/pokojný.jpg" },
      { sk: "prekvapený", ua: "здивований", ru: "удивлённый", en: "surprised", img: "/words_a1/prekvapený.jpg" },
      { sk: "báť sa", ua: "боятися", ru: "бояться", en: "to be afraid", img: "/words_a1/báť sa.jpg" },
      { sk: "tešiť sa", ua: "радіти/чекати з радістю", ru: "радоваться / ждать с радостью", en: "to look forward to / rejoice", img: "/words_a1/tešiť sa.jpg" },
      { sk: "mať chuť", ua: "мати бажання", ru: "хотеть / иметь желание", en: "to feel like", img: "/words_a1/mať chuť.jpg" },
    ],
  },
  {
    id: "a1-10",
    title: { ua: "Урок 10 — Запитання", ru: "Урок 10 — Вопросы", en: "Lesson 10 — Questions" },
    words: [
      { sk: "ktorý", ua: "який (котрий)", ru: "который", en: "which", img: "/words_a1/ktorý.jpg" },
      { sk: "aký", ua: "який (якої якості)", ru: "какой (какого качества)", en: "what kind of", img: "/words_a1/aký.jpg" },
      { sk: "čí", ua: "чий", ru: "чей", en: "whose", img: "/words_a1/čí.jpg" },
      { sk: "kde je", ua: "де є...?", ru: "где...?", en: "where is", img: "/words_a1/kde je....jpg" },
      { sk: "koľko to stojí", ua: "скільки це коштує?", ru: "сколько это стоит?", en: "how much does it cost", img: "/words_a1/koľko to stojí.jpg" },
      { sk: "môžete zopakovať", ua: "можете повторити?", ru: "можете повторить?", en: "can you repeat", img: "/words_a1/môžete zopakovať.jpg" },
      { sk: "čo to znamená", ua: "що це означає?", ru: "что это значит?", en: "what does it mean", img: "/words_a1/čo to znamená.jpg" },
      { sk: "rozumiete", ua: "розумієте?", ru: "понимаете?", en: "do you understand", img: "/words_a1/rozumiete.jpg" },
      { sk: "samozrejme", ua: "звісно", ru: "конечно", en: "of course", img: "/words_a1/samozrejme.jpg" },
      { sk: "neviem", ua: "не знаю", ru: "не знаю", en: "I don't know", img: "/words_a1/neviem.jpg" },
    ],
  },
  {
    id: "a1-11",
    title: { ua: "Урок 11 — Опис людини", ru: "Урок 11 — Описание человека", en: "Lesson 11 — Describing a person" },
    words: [
      { sk: "vysoký", ua: "високий", ru: "высокий", en: "tall", img: "/words_a1/vysoký.jpg" },
      { sk: "nízky", ua: "низький", ru: "низкий", en: "short", img: "/words_a1/nízky.jpg" },
      { sk: "mladý", ua: "молодий", ru: "молодой", en: "young", img: "/words_a1/mladý.jpg" },
      { sk: "starý", ua: "старий", ru: "старый", en: "old", img: "/words_a1/starý.jpg" },
      { sk: "silný", ua: "сильний", ru: "сильный", en: "strong", img: "/words_a1/silný.jpg" },
      { sk: "slabý", ua: "слабкий", ru: "слабый", en: "weak", img: "/words_a1/slabý.jpg" },
      { sk: "pekný", ua: "гарний", ru: "красивый", en: "nice / pretty", img: "/words_a1/pekný.jpg" },
      { sk: "škaredý", ua: "негарний", ru: "некрасивый / уродливый", en: "ugly", img: "/words_a1/škaredý.jpg" },
      { sk: "milý", ua: "милий", ru: "милый", en: "kind", img: "/words_a1/milý.jpg" },
      { sk: "vážny", ua: "серйозний", ru: "серьёзный", en: "serious", img: "/words_a1/vážny.jpg" },
    ],
  },
  {
    id: "a1-12",
    title: { ua: "Урок 12 — Час", ru: "Урок 12 — Время", en: "Lesson 12 — Time" },
    words: [
      { sk: "ráno", ua: "ранок", ru: "утро", en: "morning", img: "/words_a1/ráno.jpg" },
      { sk: "obed", ua: "обід", ru: "обед", en: "lunch", img: "/words_a1/obed.jpg" },
      { sk: "večer", ua: "вечір", ru: "вечер", en: "evening", img: "/words_a1/večer.jpg" },
      { sk: "polnoc", ua: "північ", ru: "полночь", en: "midnight", img: "/words_a1/polnoc.jpg" },
      { sk: "dnes", ua: "сьогодні", ru: "сегодня", en: "today", img: "/words_a1/dnes.jpg" },
      { sk: "zajtra", ua: "завтра", ru: "завтра", en: "tomorrow", img: "/words_a1/zajtra.jpg" },
      { sk: "pozajtra", ua: "післязавтра", ru: "послезавтра", en: "the day after tomorrow", img: "/words_a1/pozajtra.jpg" },
      { sk: "vždy", ua: "завжди", ru: "всегда", en: "always", img: "/words_a1/vždy.jpg" },
      { sk: "často", ua: "часто", ru: "часто", en: "often", img: "/words_a1/často.jpg" },
      { sk: "niekedy", ua: "інколи", ru: "иногда", en: "sometimes", img: "/words_a1/niekedy.jpg" },
    ],
  },
  {
    id: "a1-13",
    title: { ua: "Урок 13 — Дім", ru: "Урок 13 — Дом", en: "Lesson 13 — Home" },
    words: [
      { sk: "chodba", ua: "коридор", ru: "коридор", en: "hallway", img: "/words_a1/chodba.jpg" },
      { sk: "balkón", ua: "балкон", ru: "балкон", en: "balcony", img: "/words_a1/balkón.jpg" },
      { sk: "pivnica", ua: "підвал", ru: "подвал", en: "basement", img: "/words_a1/pivnica.jpg" },
      { sk: "výťah", ua: "ліфт", ru: "лифт", en: "elevator", img: "/words_a1/výťah.jpg" },
      { sk: "schody", ua: "сходи", ru: "лестница / ступени", en: "stairs", img: "/words_a1/schody.jpg" },
      { sk: "záhrada", ua: "сад", ru: "сад", en: "garden", img: "/words_a1/záhrada.jpg" },
      { sk: "garáž", ua: "гараж", ru: "гараж", en: "garage", img: "/words_a1/garáž.jpg" },
      { sk: "stena", ua: "стіна", ru: "стена", en: "wall", img: "/words_a1/stena.jpg" },
      { sk: "strop", ua: "стеля", ru: "потолок", en: "ceiling", img: "/words_a1/strop.jpg" },
      { sk: "podlaha", ua: "підлога", ru: "пол", en: "floor", img: "/words_a1/podlaha.jpg" },
    ],
  },
  {
    id: "a1-14",
    title: { ua: "Урок 14 — Покупки", ru: "Урок 14 — Покупки", en: "Lesson 14 — Shopping" },
    words: [
      { sk: "predávať", ua: "продавати", ru: "продавать", en: "to sell", img: "/words_a1/predávať.jpg" },
      { sk: "kupovať", ua: "купувати", ru: "покупать", en: "to buy", img: "/words_a1/kupovať.jpg" },
      { sk: "lacný", ua: "дешевий", ru: "дешёвый", en: "cheap", img: "/words_a1/lacný.jpg" },
      { sk: "drahý", ua: "дорогий", ru: "дорогой", en: "expensive", img: "/words_a1/drahý.jpg" },
      { sk: "kvalita", ua: "якість", ru: "качество", en: "quality", img: "/words_a1/kvalita.jpg" },
      { sk: "značka", ua: "бренд", ru: "бренд / марка", en: "brand", img: "/words_a1/značka.jpg" },
      { sk: "akcia", ua: "акція", ru: "акция", en: "sale / promotion", img: "/words_a1/akcia.jpg" },
      { sk: "zľavnený", ua: "зі знижкою", ru: "со скидкой", en: "discounted", img: "/words_a1/zľavnený.jpg" },
      { sk: "pokladňa", ua: "каса", ru: "касса", en: "cash desk", img: "/words_a1/pokladňa.jpg" },
      { sk: "blok", ua: "чек", ru: "чек", en: "receipt", img: "/words_a1/blok.jpg" },
    ],
  },
  {
    id: "a1-15",
    title: { ua: "Урок 15 — Подорожі", ru: "Урок 15 — Путешествия", en: "Lesson 15 — Travel" },
    words: [
      { sk: "hotel", ua: "готель", ru: "отель", en: "hotel", img: "/words_a1/hotel.jpg" },
      { sk: "ubytovanie", ua: "проживання", ru: "проживание", en: "accommodation", img: "/words_a1/ubytovanie.jpg" },
      { sk: "turista", ua: "турист", ru: "турист", en: "tourist", img: "/words_a1/turista.jpg" },
      { sk: "sprievodca", ua: "гід", ru: "гид", en: "guide", img: "/words_a1/sprievodca.jpg" },
      { sk: "výlet", ua: "екскурсія", ru: "экскурсия", en: "trip / excursion", img: "/words_a1/výlet.jpg" },
      { sk: "pláž", ua: "пляж", ru: "пляж", en: "beach", img: "/words_a1/pláž.jpg" },
      { sk: "hory", ua: "гори", ru: "горы", en: "mountains", img: "/words_a1/hory.jpg" },
      { sk: "more", ua: "море", ru: "море", en: "sea", img: "/words_a1/more.jpg" },
      { sk: "rezervovať", ua: "бронювати", ru: "бронировать", en: "to reserve", img: "/words_a1/rezervovať.jpg" },
      { sk: "dovolenka", ua: "відпустка", ru: "отпуск", en: "vacation", img: "/words_a1/dovolenka.jpg" },
    ],
  },
  {
    id: "a1-16",
    title: { ua: "Урок 16 — Здоровʼя", ru: "Урок 16 — Здоровье", en: "Lesson 16 — Health" },
    words: [
      { sk: "bolieť", ua: "боліти", ru: "болеть", en: "to hurt", img: "/words_a1/bolieť.jpg" },
      { sk: "hlava", ua: "голова", ru: "голова", en: "head", img: "/words_a1/hlava.jpg" },
      { sk: "zub", ua: "зуб", ru: "зуб", en: "tooth", img: "/words_a1/zub.jpg" },
      { sk: "žalúdok", ua: "шлунок", ru: "желудок", en: "stomach", img: "/words_a1/žalúdok.jpg" },
      { sk: "tabletka", ua: "таблетка", ru: "таблетка", en: "pill", img: "/words_a1/tabletka.jpg" },
      { sk: "sirup", ua: "сироп", ru: "сироп", en: "syrup", img: "/words_a1/sirup.jpg" },
      { sk: "odpočívať", ua: "відпочивати", ru: "отдыхать", en: "to rest", img: "/words_a1/odpočívať.jpg" },
      { sk: "zdravý", ua: "здоровий", ru: "здоровый", en: "healthy", img: "/words_a1/zdravý.jpg" },
      { sk: "chorý", ua: "хворий", ru: "больной", en: "ill", img: "/words_a1/chorý.jpg" },
      { sk: "liečiť", ua: "лікувати", ru: "лечить", en: "to treat", img: "/words_a1/liečiť.jpg" },
    ],
  },
  {
    id: "a1-17",
    title: { ua: "Урок 17 — Робота (словник)", ru: "Урок 17 — Работа (словарь)", en: "Lesson 17 — Work vocabulary" },
    words: [
      { sk: "zamestnanec", ua: "працівник", ru: "работник / сотрудник", en: "employee", img: "/words_a1/zamestnanec.jpg" },
      { sk: "zamestnávateľ", ua: "роботодавець", ru: "работодатель", en: "employer", img: "/words_a1/zamestnávateľ.jpg" },
      { sk: "plat", ua: "зарплата", ru: "зарплата", en: "salary", img: "/words_a1/plat.jpg" },
      { sk: "pracovná zmluva", ua: "трудовий договір", ru: "трудовой договор", en: "employment contract", img: "/words_a1/pracovná zmluva.jpg" },
      { sk: "prax", ua: "досвід роботи", ru: "опыт работы", en: "work experience", img: "/words_a1/prax.jpg" },
      { sk: "kariéra", ua: "карʼєра", ru: "карьера", en: "career", img: "/words_a1/kariéra.jpg" },
      { sk: "povýšenie", ua: "підвищення", ru: "повышение", en: "promotion", img: "/words_a1/povýšenie.jpg" },
      { sk: "výpoveď", ua: "звільнення", ru: "увольнение / заявление об увольнении", en: "dismissal / resignation notice", img: "/words_a1/výpoveď.jpg" },
      { sk: "povinnosť", ua: "обовʼязок", ru: "обязанность", en: "duty", img: "/words_a1/povinnosť.jpg" },
      { sk: "právo", ua: "право", ru: "право", en: "right", img: "/words_a1/právo.jpg" },
    ],
  },
  {
    id: "a1-18",
    title: { ua: "Урок 18 — Спілкування", ru: "Урок 18 — Общение", en: "Lesson 18 — Communication" },
    words: [
      { sk: "rozumieť", ua: "розуміти", ru: "понимать", en: "to understand", img: "/words_a1/rozumieť.jpg" },
      { sk: "vysvetliť", ua: "пояснити", ru: "объяснить", en: "to explain", img: "/words_a1/vysvetliť.jpg" },
      { sk: "opýtať sa", ua: "запитати", ru: "спросить", en: "to ask", img: "/words_a1/opýtať sa.jpg" },
      { sk: "odpoveď", ua: "відповідь", ru: "ответ", en: "answer", img: "/words_a1/odpoveď.jpg" },
      { sk: "názor", ua: "думка", ru: "мнение", en: "opinion", img: "/words_a1/názor.jpg" },
      { sk: "súhlasiť", ua: "погоджуватися", ru: "соглашаться", en: "to agree", img: "/words_a1/súhlasiť.jpg" },
      { sk: "nesúhlasiť", ua: "не погоджуватися", ru: "не соглашаться", en: "to disagree", img: "/words_a1/nesúhlasiť.jpg" },
      { sk: "diskutovať", ua: "обговорювати", ru: "обсуждать", en: "to discuss", img: "/words_a1/diskutovať.jpg" },
      { sk: "hovor", ua: "розмова", ru: "разговор", en: "conversation", img: "/words_a1/hovor.jpg" },
      { sk: "kontakt", ua: "контакт", ru: "контакт", en: "contact", img: "/words_a1/kontakt.jpg" },
    ],
  },
  {
    id: "a1-19",
    title: { ua: "Урок 19 — Технології", ru: "Урок 19 — Технологии", en: "Lesson 19 — Technology" },
    words: [
      { sk: "mobil", ua: "мобільний телефон", ru: "мобильный телефон", en: "mobile phone", img: "/words_a1/mobil.jpg" },
      { sk: "nabíjačka", ua: "зарядка", ru: "зарядка / зарядное устройство", en: "charger", img: "/words_a1/nabíjačka.jpg" },
      { sk: "správa", ua: "повідомлення", ru: "сообщение", en: "message", img: "/words_a1/správa.jpg" },
      { sk: "hovor", ua: "дзвінок", ru: "звонок", en: "call", img: "/words_a1/hovor1.jpg" },
      { sk: "internet", ua: "інтернет", ru: "интернет", en: "internet", img: "/words_a1/internet.jpg" },
      { sk: "wifi", ua: "вайфай", ru: "вай-фай", en: "Wi-Fi", img: "/words_a1/wifi.jpg" },
      { sk: "sociálne siete", ua: "соціальні мережі", ru: "социальные сети", en: "social networks", img: "/words_a1/sociálne siete.jpg" },
      { sk: "profil", ua: "профіль", ru: "профиль", en: "profile", img: "/words_a1/profil.jpg" },
      { sk: "heslo", ua: "пароль", ru: "пароль", en: "password", img: "/words_a1/heslo.jpg" },
      { sk: "stiahnuť", ua: "завантажити", ru: "скачать / загрузить", en: "to download", img: "/words_a1/stiahnuť.jpg" },
    ],
  },
  {
    id: "a1-20",
    title: { ua: "Урок 20 — Повсякденні дії", ru: "Урок 20 — Повседневные действия", en: "Lesson 20 — Everyday actions" },
    words: [
      { sk: "vstať", ua: "встати", ru: "встать", en: "to get up", img: "/words_a1/vstať.jpg" },
      { sk: "ísť do práce", ua: "йти на роботу", ru: "идти на работу", en: "to go to work", img: "/words_a1/ísť do práce.jpg" },
      { sk: "nakupovať", ua: "робити покупки", ru: "делать покупки", en: "to shop", img: "/words_a1/nakupovať.jpg" },
      { sk: "oddýchnuť si", ua: "відпочити", ru: "отдохнуть", en: "to rest", img: "/words_a1/oddýchnuť si.jpg" },
      { sk: "stretnúť sa", ua: "зустрітися", ru: "встретиться", en: "to meet", img: "/words_a1/stretnúť sa.jpg" },
      { sk: "telefonovať", ua: "телефонувати", ru: "звонить", en: "to call", img: "/words_a1/telefonovať.jpg" },
      { sk: "variť", ua: "готувати", ru: "готовить", en: "to cook", img: "/words_a1/variť.jpg" },
      { sk: "pozerať", ua: "дивитися", ru: "смотреть", en: "to watch", img: "/words_a1/pozerať.jpg" },
      { sk: "čítať", ua: "читати", ru: "читать", en: "to read", img: "/words_a1/čítať.jpg" },
      { sk: "spať", ua: "спати", ru: "спать", en: "to sleep", img: "/words_a1/spať.jpg" },
    ],
  },
  {
    id: "a1-21",
    title: { ua: "Урок 21 — Проблеми і ситуації", ru: "Урок 21 — Проблемы и ситуации", en: "Lesson 21 — Problems and situations" },
    words: [
      { sk: "problém", ua: "проблема", ru: "проблема", en: "problem", img: "/words_a1/problém.jpg" },
      { sk: "pokazený", ua: "зламаний", ru: "сломанный / неисправный", en: "broken", img: "/words_a1/pokazený.jpg" },
      { sk: "stratiť", ua: "загубити", ru: "потерять", en: "to lose", img: "/words_a1/stratiť.jpg" },
      { sk: "nájsť", ua: "знайти", ru: "найти", en: "to find", img: "/words_a1/nájsť.jpg" },
      { sk: "meškať", ua: "запізнюватися", ru: "опаздывать", en: "to be late", img: "/words_a1/meškať.jpg" },
      { sk: "zabudnúť", ua: "забути", ru: "забыть", en: "to forget", img: "/words_a1/zabudnúť.jpg" },
      { sk: "chyba", ua: "помилка", ru: "ошибка", en: "mistake", img: "/words_a1/chyba.jpg" },
      { sk: "oprava", ua: "ремонт", ru: "ремонт", en: "repair", img: "/words_a1/oprava.jpg" },
      { sk: "pomoc", ua: "допомога", ru: "помощь", en: "help", img: "/words_a1/pomoc.jpg" },
      { sk: "riešenie", ua: "рішення", ru: "решение", en: "solution", img: "/words_a1/riešenie.jpg" },
    ],
  },
  {
    id: "a1-22",
    title: { ua: "Урок 22 — Напрямки", ru: "Урок 22 — Направления", en: "Lesson 22 — Directions" },
    words: [
      { sk: "vpravo", ua: "праворуч", ru: "направо", en: "to the right", img: "/words_a1/vpravo.jpg" },
      { sk: "vľavo", ua: "ліворуч", ru: "налево", en: "to the left", img: "/words_a1/vľavo.jpg" },
      { sk: "rovno", ua: "прямо", ru: "прямо", en: "straight", img: "/words_a1/rovno.jpg" },
      { sk: "blízko", ua: "близько", ru: "близко", en: "near", img: "/words_a1/blízko.jpg" },
      { sk: "ďaleko", ua: "далеко", ru: "далеко", en: "far", img: "/words_a1/ďaleko.jpg" },
      { sk: "hore", ua: "вгору", ru: "вверх", en: "up", img: "/words_a1/hore.jpg" },
      { sk: "dole", ua: "вниз", ru: "вниз", en: "down", img: "/words_a1/dole.jpg" },
      { sk: "pred", ua: "перед", ru: "перед", en: "in front of", img: "/words_a1/pred.jpg" },
      { sk: "za", ua: "за", ru: "за", en: "behind", img: "/words_a1/za.jpg" },
      { sk: "medzi", ua: "між", ru: "между", en: "between", img: "/words_a1/medzi.jpg" },
    ]
  },
  {
    id: "a1-23",
    title: { ua: "Урок 23 — Характер", ru: "Урок 23 — Характер", en: "Lesson 23 — Character" },
    words: [
      { sk: "dobrý", ua: "добрий", ru: "добрый", en: "good", img: "/words_a1/dobrý.jpg" },
      { sk: "zlý", ua: "поганий", ru: "плохой", en: "bad", img: "/words_a1/zlý.jpg" },
      { sk: "trpezlivý", ua: "терплячий", ru: "терпеливый", en: "patient", img: "/words_a1/trpezlivý.jpg" },
      { sk: "lenivý", ua: "ледачий", ru: "ленивый", en: "lazy", img: "/words_a1/lenivý.jpg" },
      { sk: "pracovitý", ua: "працьовитий", ru: "трудолюбивый", en: "hard-working", img: "/words_a1/pracovitý.jpg" },
      { sk: "úprimný", ua: "щирий", ru: "искренний", en: "honest / sincere", img: "/words_a1/úprimný.jpg" },
      { sk: "priateľský", ua: "дружній", ru: "дружелюбный", en: "friendly", img: "/words_a1/priateľský.jpg" },
      { sk: "vážny", ua: "серйозний", ru: "серьёзный", en: "serious", img: "/words_a1/vážny.jpg" },
      { sk: "zábavný", ua: "веселий", ru: "весёлый", en: "funny / entertaining", img: "/words_a1/zábavný.jpg" },
      { sk: "tichý", ua: "тихий", ru: "тихий", en: "quiet", img: "/words_a1/tichý.jpg" },
    ],
  },
  {
    id: "a1-24",
    title: { ua: "Урок 24 — Погода (розширено)", ru: "Урок 24 — Погода (расширено)", en: "Lesson 24 — Weather (extended)" },
    words: [
      { sk: "teplo", ua: "тепло", ru: "тепло", en: "warm", img: "/words_a1/teplo.jpg" },
      { sk: "chladno", ua: "холодно", ru: "холодно", en: "cold", img: "/words_a1/chladno.jpg" },
      { sk: "zamračené", ua: "хмарно", ru: "пасмурно / облачно", en: "cloudy", img: "/words_a1/zamračené.jpg" },
      { sk: "jasno", ua: "ясно", ru: "ясно", en: "clear", img: "/words_a1/jasno.jpg" },
      { sk: "pršať", ua: "йти дощу", ru: "идти (о дожде) / идти дождю", en: "to rain", img: "/words_a1/pršať.jpg" },
      { sk: "snežiť", ua: "йти снігу", ru: "идти (о снеге) / идти снегу", en: "to snow", img: "/words_a1/snežiť.jpg" },
      { sk: "vietor", ua: "вітер", ru: "ветер", en: "wind", img: "/words_a1/vietor.jpg" },
      { sk: "mráz", ua: "мороз", ru: "мороз", en: "frost", img: "/words_a1/mráz.jpg" },
      { sk: "búrka", ua: "буря", ru: "буря / гроза", en: "storm", img: "/words_a1/búrka.jpg" },
      { sk: "predpoveď", ua: "прогноз", ru: "прогноз", en: "forecast", img: "/words_a1/predpoveď.jpg" },
    ],
  },
  {
    id: "a1-25",
    title: { ua: "Урок 25 — Їжа (розширено)", ru: "Урок 25 — Еда (расширено)", en: "Lesson 25 — Food (extended)" },
    words: [
      { sk: "raňajky", ua: "сніданок", ru: "завтрак", en: "breakfast", img: "/words_a1/raňajky.jpg" },
      { sk: "obed", ua: "обід", ru: "обед", en: "lunch", img: "/words_a1/obed.jpg" },
      { sk: "večera", ua: "вечеря", ru: "ужин", en: "dinner", img: "/words_a1/večera.jpg" },
      { sk: "sladký", ua: "солодкий", ru: "сладкий", en: "sweet", img: "/words_a1/sladký.jpg" },
      { sk: "slaný", ua: "солоний", ru: "солёный", en: "salty", img: "/words_a1/slaný.jpg" },
      { sk: "pikantný", ua: "гострий", ru: "острый / пикантный", en: "spicy", img: "/words_a1/pikantný.jpg" },
      { sk: "čerstvý", ua: "свіжий", ru: "свежий", en: "fresh", img: "/words_a1/čerstvý.jpg" },
      { sk: "hlad", ua: "голод", ru: "голод", en: "hunger", img: "/words_a1/hlad.jpg" },
      { sk: "smäd", ua: "спрага", ru: "жажда", en: "thirst", img: "/words_a1/smäd.jpg" },
      { sk: "chuť", ua: "смак / бажання", ru: "вкус / желание", en: "taste / desire", img: "/words_a1/chuť.jpg" },
    ],
  },
  {
    id: "a1-26",
    title: { ua: "Урок 26 — Гроші (розширено)", ru: "Урок 26 — Деньги (расширено)", en: "Lesson 26 — Money (extended)" },
    words: [
      { sk: "platiť", ua: "платити", ru: "платить", en: "to pay", img: "/words_a1/platiť.jpg"  },
      { sk: "ušetriť", ua: "зекономити", ru: "сэкономить", en: "to save", img: "/words_a1/ušetriť.jpg"  },
      { sk: "minúť", ua: "витратити", ru: "потратить", en: "to spend", img: "/words_a1/minúť.jpg" },
      { sk: "výplata", ua: "зарплата", ru: "зарплата", en: "paycheck / salary", img: "/words_a1/výplata.jpg" },
      { sk: "úver", ua: "кредит", ru: "кредит", en: "loan", img: "/words_a1/úver.jpg" },
      { sk: "dlh", ua: "борг", ru: "долг", en: "debt", img: "/words_a1/dlh.jpg"  },
      { sk: "bankomat", ua: "банкомат", ru: "банкомат", en: "ATM", img: "/words_a1/bankomat.jpg"  },
      { sk: "účet", ua: "рахунок", ru: "счёт", en: "bill / account", img: "/words_a1/účet.jpg"  },
      { sk: "príjem", ua: "дохід", ru: "доход", en: "income", img: "/words_a1/príjem.jpg"  },
      { sk: "výdavok", ua: "витрата", ru: "расход", en: "expense", img: "/words_a1/výdavok.jpg" },
    ],
  },
  {
    id: "a1-27",
    title: { ua: "Урок 27 — Технології (практика)", ru: "Урок 27 — Технологии (практика)", en: "Lesson 27 — Technology (practice)" },
    words: [
      { sk: "zapnúť", ua: "увімкнути", ru: "включить", en: "to turn on", img: "/words_a1/zapnúť.jpg"  },
      { sk: "vypnúť", ua: "вимкнути", ru: "выключить", en: "to turn off", img: "/words_a1/vypnúť.jpg"  },
      { sk: "nabíjať", ua: "заряджати", ru: "заряжать", en: "to charge", img: "/words_a1/nabíjať.jpg"  },
      { sk: "prihlásiť sa", ua: "увійти", ru: "войти", en: "to log in", img: "/words_a1/prihlásiť sa.jpg" },
      { sk: "odhlásiť sa", ua: "вийти", ru: "выйти", en: "to log out", img: "/words_a1/odhlásiť sa.jpg"  },
      { sk: "stiahnuť", ua: "завантажити", ru: "скачать / загрузить", en: "to download", img: "/words_a1/stiahnuť.jpg"  },
      { sk: "uložiť", ua: "зберегти", ru: "сохранить", en: "to save", img: "/words_a1/uložiť.jpg"  },
      { sk: "vymazať", ua: "видалити", ru: "удалить", en: "to delete", img: "/words_a1/vymazať.jpg" },
      { sk: "kliknúť", ua: "натиснути", ru: "нажать / кликнуть", en: "to click", img: "/words_a1/kliknúť.jpg"  },
      { sk: "nastavenia", ua: "налаштування", ru: "настройки", en: "settings", img: "/words_a1/nastavenia.jpg"  },
    ],
  },
  {
    id: "a1-28",
    title: { ua: "Урок 28 — Подорожі (ситуації)", ru: "Урок 28 — Путешествия (ситуации)", en: "Lesson 28 — Travel (situations)" },
    words: [
      { sk: "let", ua: "рейс", ru: "рейс", en: "flight", img: "/words_a1/let.jpg"  },
      { sk: "meškanie", ua: "затримка", ru: "задержка", en: "delay", img: "/words_a1/meškanie.jpg"  },
      { sk: "odlet", ua: "виліт", ru: "вылет", en: "departure", img: "/words_a1/odlet.jpg"  },
      { sk: "prílet", ua: "приліт", ru: "прилёт", en: "arrival", img: "/words_a1/prílet.jpg"  },
      { sk: "pasová kontrola", ua: "паспортний контроль", ru: "паспортный контроль", en: "passport control", img: "/words_a1/pasová kontrola.jpg"  },
      { sk: "batožina", ua: "багаж", ru: "багаж", en: "luggage", img: "/words_a1/batožina.jpg"  },
      { sk: "rezervácia", ua: "бронювання", ru: "бронирование", en: "reservation", img: "/words_a1/rezervácia.jpg"  },
      { sk: "sprievodca", ua: "гід", ru: "гид", en: "guide", img: "/words_a1/sprievodca.jpg"  },
      { sk: "mapa", ua: "карта", ru: "карта", en: "map", img: "/words_a1/mapa.jpg"  },
      { sk: "cieľ", ua: "ціль", ru: "цель", en: "goal / destination", img: "/words_a1/cieľ.jpg"  },
    ],
  },
  {
    id: "a1-29",
    title: { ua: "Урок 29 — Робочі фрази", ru: "Урок 29 — Рабочие фразы", en: "Lesson 29 — Work phrases" },
    words: [
      { sk: "rozumiem", ua: "розумію", ru: "понимаю", en: "I understand", img: "/words_a1/rozumiem.jpg"  },
      { sk: "nerozumiem", ua: "не розумію", ru: "не понимаю", en: "I don't understand", img: "/words_a1/nerozumiem.jpg"  },
      { sk: "hotovo", ua: "готово", ru: "готово", en: "done", img: "/words_a1/hotovo.jpg"  },
      { sk: "môžem", ua: "можна", ru: "можно", en: "may I / can I", img: "/words_a1/môžem.jpg"  },
      { sk: "potrebujem", ua: "потрібно", ru: "нужно / мне нужно", en: "I need", img: "/words_a1/potrebujem.jpg"  },
      { sk: "problém", ua: "проблема", ru: "проблема", en: "problem", img: "/words_a1/problém.jpg"  },
      { sk: "v poriadku", ua: "в порядку", ru: "в порядке", en: "all right", img: "/words_a1/v poriadku.jpg" },
      { sk: "hneď", ua: "зараз", ru: "сейчас / сразу", en: "right away", img: "/words_a1/hneď.jpg" },
      { sk: "neskôr", ua: "пізніше", ru: "позже", en: "later", img: "/words_a1/neskôr.jpg" },
      { sk: "dohodnúť sa", ua: "домовитись", ru: "договориться", en: "to agree / arrange", img: "/words_a1/dohodnúť sa.jpg"  },
    ],
  },
  {
    id: "a1-30",
    title: { ua: "Урок 30 — Часті дієслова", ru: "Урок 30 — Частые глаголы", en: "Lesson 30 — Common verbs" },
    words: [
      { sk: "mať", ua: "мати", ru: "иметь", en: "to have", img: "/words_a1/mať.jpg"  },
      { sk: "byť", ua: "бути", ru: "быть", en: "to be", img: "/words_a1/byť.jpg"  },
      { sk: "robiť", ua: "робити", ru: "делать", en: "to do", img: "/words_a1/robiť.jpg"  },
      { sk: "ísť", ua: "йти", ru: "идти", en: "to go", img: "/words_a1/ísť.jpg"  },
      { sk: "vidieť", ua: "бачити", ru: "видеть", en: "to see", img: "/words_a1/vidieť.jpg" },
      { sk: "počúvať", ua: "слухати", ru: "слушать", en: "to listen", img: "/words_a1/počúvať.jpg"  },
      { sk: "hovoriť", ua: "говорити", ru: "говорить", en: "to speak", img: "/words_a1/hovoriť.jpg"  },
      { sk: "myslieť", ua: "думати", ru: "думать", en: "to think", img: "/words_a1/myslieť.jpg"  },
      { sk: "chcieť", ua: "хотіти", ru: "хотеть", en: "to want", img: "/words_a1/chcieť.jpg"  },
      { sk: "môcť", ua: "могти", ru: "мочь", en: "to be able to", img: "/words_a1/môcť.jpg" },
    ],
  },
  {
    id: "a1-31",
    title: { ua: "Урок 31 — Почуття", ru: "Урок 31 — Чувства", en: "Lesson 31 — Feelings" },
    words: [
      { sk: "radosť", ua: "радість", ru: "радость", en: "joy", img: "/words_a1/radosť.jpg" },
      { sk: "smútok", ua: "смуток", ru: "грусть / печаль", en: "sadness", img: "/words_a1/smútok.jpg" },
      { sk: "strach", ua: "страх", ru: "страх", en: "fear", img: "/words_a1/strach.jpg" },
      { sk: "hnev", ua: "злість", ru: "злость / гнев", en: "anger", img: "/words_a1/hnev.jpg" },
      { sk: "láska", ua: "любов", ru: "любовь", en: "love", img: "/words_a1/láska.jpg" },
      { sk: "únava", ua: "втома", ru: "усталость", en: "tiredness", img: "/words_a1/únava.jpg" },
      { sk: "stres", ua: "стрес", ru: "стресс", en: "stress", img: "/words_a1/stres.jpg" },
      { sk: "pokoj", ua: "спокій", ru: "покой / спокойствие", en: "calm", img: "/words_a1/pokoj.jpg" },
      { sk: "prekvapenie", ua: "здивування", ru: "удивление", en: "surprise", img: "/words_a1/prekvapenie.jpg" },
      { sk: "nadšenie", ua: "захоплення", ru: "восторг / воодушевление", en: "enthusiasm", img: "/words_a1/nadšenie.jpg" },
    ],
  },
  {
    id: "a1-32",
    title: { ua: "Урок 32 — Опис речей", ru: "Урок 32 — Описание вещей", en: "Lesson 32 — Describing things" },
    words: [
      { sk: "nový", ua: "новий", ru: "новый", en: "new", img: "/words_a1/nový.jpg" },
      { sk: "starý", ua: "старий", ru: "старый", en: "old", img: "/words_a1/starý.jpg" },
      { sk: "veľký", ua: "великий", ru: "большой", en: "big", img: "/words_a1/veľký.jpg" },
      { sk: "malý", ua: "малий", ru: "маленький", en: "small", img: "/words_a1/malý.jpg" },
      { sk: "ťažký", ua: "важкий", ru: "тяжёлый", en: "heavy", img: "/words_a1/ťažký.jpg" },
      { sk: "ľahký", ua: "легкий", ru: "лёгкий", en: "light", img: "/words_a1/ľahký.jpg" },
      { sk: "rýchly", ua: "швидкий", ru: "быстрый", en: "fast", img: "/words_a1/rýchly.jpg" },
      { sk: "pomalý", ua: "повільний", ru: "медленный", en: "slow", img: "/words_a1/pomalý.jpg" },
      { sk: "drahý", ua: "дорогий", ru: "дорогой", en: "expensive", img: "/words_a1/drahý.jpg" },
      { sk: "lacný", ua: "дешевий", ru: "дешёвый", en: "cheap", img: "/words_a1/lacný.jpg" },
    ],
  },
  {
    id: "a1-33",
    title: { ua: "Урок 33 — Дім (дії)", ru: "Урок 33 — Дом (действия)", en: "Lesson 33 — Home (actions)" },
    words: [
      { sk: "variť", ua: "готувати", ru: "готовить", en: "to cook", img: "/words_a1/variť.jpg" },
      { sk: "vysávať", ua: "пилососити", ru: "пылесосить", en: "to vacuum", img: "/words_a1/vysávať.jpg" },
      { sk: "umyť", ua: "помити", ru: "помыть", en: "to wash", img: "/words_a1/umyť.jpg" },
      { sk: "zatvoriť", ua: "закрити", ru: "закрыть", en: "to close", img: "/words_a1/zatvoriť.jpg" },
      { sk: "opraviť", ua: "відремонтувати", ru: "отремонтировать", en: "to repair", img: "/words_a1/opraviť.jpg" },
      { sk: "postaviť", ua: "побудувати", ru: "построить", en: "to build", img: "/words_a1/postaviť.jpg" },
      { sk: "presťahovať sa", ua: "переїхати", ru: "переехать", en: "to move", img: "/words_a1/presťahovať sa.jpg" },
      { sk: "zavesiť", ua: "повісити", ru: "повесить", en: "to hang", img: "/words_a1/zavesiť.jpg" },
      { sk: "poskladať", ua: "скласти (речі)", ru: "сложить (вещи)", en: "to fold", img: "/words_a1/poskladať.jpg" },
      { sk: "zariadiť", ua: "облаштувати", ru: "обустроить", en: "to furnish / arrange", img: "/words_a1/zariadiť.jpg" },
    ],
  },
  {
    id: "a1-34",
    title: { ua: "Урок 34 — Комунікація", ru: "Урок 34 — Коммуникация", en: "Lesson 34 — Communication" },
    words: [
      { sk: "opísať", ua: "описати", ru: "описать", en: "to describe", img: "/words_a1/opísať.jpg" },
      { sk: "navrhnúť", ua: "запропонувати", ru: "предложить", en: "to suggest", img: "/words_a1/navrhnúť.jpg" },
      { sk: "rozprávať", ua: "розповідати", ru: "рассказывать", en: "to tell", img: "/words_a1/rozprávať.jpg" },
      { sk: "oznámiť", ua: "повідомити", ru: "сообщить", en: "to announce / inform", img: "/words_a1/oznámiť.jpg" },
      { sk: "požiadať", ua: "попросити", ru: "попросить", en: "to ask for", img: "/words_a1/požiadať.jpg" },
      { sk: "odpísať", ua: "відписати", ru: "ответить (на повідомлення)", en: "to reply", img: "/words_a1/odpísať.jpg" },
      { sk: "zavolať", ua: "подзвонити", ru: "позвонить", en: "to call", img: "/words_a1/zavolať.jpg" },
      { sk: "pozdraviť", ua: "привітати", ru: "поприветствовать", en: "to greet", img: "/words_a1/pozdraviť.jpg" },
      { sk: "spýtať sa", ua: "запитати", ru: "спросить", en: "to ask", img: "/words_a1/spýtať sa.jpg" },
      { sk: "dohodnúť sa", ua: "домовитися", ru: "договориться", en: "to agree / arrange", img: "/words_a1/dohodnúť sa.jpg" },
    ]
  },
  {
    id: "a1-35",
    title: { ua: "Урок 35 — Місто (ситуації)", ru: "Урок 35 — Город (ситуации)", en: "Lesson 35 — City (situations)" },
    words: [
      { sk: "úrad", ua: "установа", ru: "учреждение", en: "office / institution", img: "/words_a1/úrad.jpg" },
      { sk: "kaderníctvo", ua: "перукарня", ru: "парикмахерская", en: "hair salon", img: "/words_a1/kaderníctvo.jpg" },
      { sk: "pekáreň", ua: "пекарня", ru: "пекарня", en: "bakery", img: "/words_a1/pekáreň.jpg" },
      { sk: "cukráreň", ua: "кондитерська", ru: "кондитерская", en: "pastry shop", img: "/words_a1/cukráreň.jpg" },
      { sk: "čerpacia stanica", ua: "заправка", ru: "заправка", en: "gas station", img: "/words_a1/čerpacia stanica.jpg" },
      { sk: "autobusová stanica", ua: "автовокзал", ru: "автовокзал", en: "bus station", img: "/words_a1/autobusová stanica.jpg" },
      { sk: "železničná stanica", ua: "залізничний вокзал", ru: "железнодорожный вокзал", en: "railway station", img: "/words_a1/železničná stanica.jpg" },
      { sk: "križovatka", ua: "перехрестя", ru: "перекрёсток", en: "intersection", img: "/words_a1/križovatka.jpg" },
      { sk: "chodník", ua: "тротуар", ru: "тротуар", en: "sidewalk", img: "/words_a1/chodník.jpg" },
      { sk: "podchod", ua: "підземний перехід", ru: "подземный переход", en: "underpass", img: "/words_a1/podchod.jpg" },
    ],
  },
  {
    id: "a1-36",
    title: { ua: "Урок 36 — Транспорт (дії)", ru: "Урок 36 — Транспорт (действия)", en: "Lesson 36 — Transport (actions)" },
    words: [
      { sk: "nastúpiť", ua: "сісти", ru: "сесть / зайти (в транспорт)", en: "to get on", img: "/words_a1/nastúpiť.jpg" },
      { sk: "vystúpiť", ua: "вийти", ru: "выйти (из транспорта)", en: "to get off", img: "/words_a1/vystúpiť.jpg" },
      { sk: "prestúpiť", ua: "пересісти", ru: "пересесть / сделать пересадку", en: "to transfer", img: "/words_a1/prestúpiť.jpg" },
      { sk: "meškať", ua: "запізнюватися", ru: "опаздывать", en: "to be late", img: "/words_a1/meškať.jpg" },
      { sk: "čakať", ua: "чекати", ru: "ждать", en: "to wait", img: "/words_a1/čakať.jpg" },
      { sk: "odísť", ua: "піти", ru: "уйти", en: "to leave", img: "/words_a1/odísť.jpg" },
      { sk: "prísť", ua: "прийти", ru: "прийти", en: "to come", img: "/words_a1/prísť.jpg" },
      { sk: "riadiť", ua: "керувати", ru: "водить / управлять", en: "to drive", img: "/words_a1/riadiť.jpg" },
      { sk: "parkovať", ua: "паркувати", ru: "парковать(ся)", en: "to park", img: "/words_a1/parkovať.jpg" },
      { sk: "zastaviť", ua: "зупинити", ru: "остановить", en: "to stop", img: "/words_a1/zastaviť.jpg" },
    ],
  },
  {
    id: "a1-37",
    title: { ua: "Урок 37 — Плани", ru: "Урок 37 — Планы", en: "Lesson 37 — Plans" },
    words: [
      { sk: "plán", ua: "план", ru: "план", en: "plan", img: "/words_a1/plán.jpg" },
      { sk: "cieľ", ua: "ціль", ru: "цель", en: "goal", img: "/words_a1/cieľ.jpg" },
      { sk: "budúcnosť", ua: "майбутнє", ru: "будущее", en: "future", img: "/words_a1/budúcnosť.jpg" },
      { sk: "pripraviť", ua: "підготувати", ru: "подготовить", en: "to prepare", img: "/words_a1/pripraviť.jpg" },
      { sk: "budúci týždeň", ua: "наступного тижня", ru: "на следующей неделе", en: "next week", img: "/words_a1/budúci týždeň.jpg" },
      { sk: "dúfať", ua: "сподіватися", ru: "надеяться", en: "to hope", img: "/words_a1/dúfať.jpg" },
      { sk: "rozhodnúť sa", ua: "вирішити", ru: "решить", en: "to decide", img: "/words_a1/rozhodnúť sa.jpg" },
      { sk: "naplánovať", ua: "запланувати", ru: "запланировать", en: "to plan", img: "/words_a1/naplánovať.jpg" },
      { sk: "termín", ua: "термін", ru: "срок", en: "deadline / date", img: "/words_a1/termín.jpg" },
      { sk: "pokračovať", ua: "продовжити", ru: "продолжить", en: "to continue", img: "/words_a1/pokračovať.jpg" },
    ],
  },
  {
    id: "a1-38",
    title: { ua: "Урок 38 — Ситуації в магазині", ru: "Урок 38 — Ситуации в магазине", en: "Lesson 38 — Situations in a shop" },
    words: [
      { sk: "reklamácia", ua: "скарга / повернення", ru: "претензия / рекламация", en: "complaint / return", img: "/words_a1/reklamácia.jpg" },
      { sk: "tovar", ua: "товар", ru: "товар", en: "goods", img: "/words_a1/tovar.jpg" },
      { sk: "sklad", ua: "склад", ru: "склад", en: "warehouse", img: "/words_a1/sklad.jpg" },
      { sk: "účtenka", ua: "чек", ru: "чек", en: "receipt", img: "/words_a1/účtenka.jpg" },
      { sk: "záruka", ua: "гарантія", ru: "гарантия", en: "warranty", img: "/words_a1/záruka.jpg" },
      { sk: "poškodený", ua: "пошкоджений", ru: "повреждённый", en: "damaged", img: "/words_a1/poškodený.jpg" },
      { sk: "predavač", ua: "продавець", ru: "продавец", en: "salesperson", img: "/words_a1/predavač.jpg" },
      { sk: "zákazník", ua: "клієнт", ru: "клиент", en: "customer", img: "/words_a1/zákazník.jpg" },
      { sk: "reklamovať", ua: "рекламувати / подавати скаргу", ru: "подавать рекламацию", en: "to make a complaint / claim", img: "/words_a1/reklamovať.jpg" },
      { sk: "výmena", ua: "обмін", ru: "обмен", en: "exchange", img: "/words_a1/výmena.jpg" },
    ],
  },
  {
    id: "a1-39",
    title: { ua: "Урок 39 — Абстрактні слова", ru: "Урок 39 — Абстрактные слова", en: "Lesson 39 — Abstract words" },
    words: [
      { sk: "život", ua: "життя", ru: "жизнь", en: "life", img: "/words_a1/život.jpg" },
      { sk: "čas", ua: "час", ru: "время", en: "time", img: "/words_a1/čas.jpg" },
      { sk: "možnosť", ua: "можливість", ru: "возможность", en: "possibility", img: "/words_a1/možnosť.jpg" },
      { sk: "dôvod", ua: "причина", ru: "причина", en: "reason", img: "/words_a1/dôvod.jpg" },
      { sk: "význam", ua: "значення", ru: "значение", en: "meaning", img: "/words_a1/význam.jpg" },
      { sk: "pravda", ua: "правда", ru: "правда", en: "truth", img: "/words_a1/pravda.jpg" },
      { sk: "lož", ua: "брехня", ru: "ложь", en: "lie", img: "/words_a1/lož.jpg" },
      { sk: "úspech", ua: "успіх", ru: "успех", en: "success", img: "/words_a1/úspech.jpg" },
      { sk: "neúspech", ua: "невдача", ru: "неудача", en: "failure", img: "/words_a1/neúspech.jpg" },
      { sk: "skúsenosť", ua: "досвід", ru: "опыт", en: "experience", img: "/words_a1/skúsenosť.jpg" },
    ],
  },
  {
    id: "a1-40",
    title: { ua: "Урок 40 — Повторення A1", ru: "Урок 40 — Повторение A1", en: "Lesson 40 — A1 review" },
    words: [
      { sk: "učiť sa", ua: "вчитися", ru: "учиться", en: "to study", img: "/words_a1/učiť sa.jpg" },
      { sk: "cestovať", ua: "подорожувати", ru: "путешествовать", en: "to travel", img: "/words_a1/cestovať.jpg" },
      { sk: "pomôcť", ua: "допомогти", ru: "помочь", en: "to help", img: "/words_a1/pomôcť.jpg" },
      { sk: "písať", ua: "писати", ru: "писать", en: "to write", img: "/words_a1/písať.jpg" },
      { sk: "vrátiť sa", ua: "повернутися", ru: "вернуться", en: "to return", img: "/words_a1/vrátiť sa.jpg" },
      { sk: "zostať", ua: "залишитися", ru: "остаться", en: "to stay", img: "/words_a1/zostať.jpg" },
      { sk: "zmeniť", ua: "змінити", ru: "изменить", en: "to change", img: "/words_a1/zmeniť.jpg" },
      { sk: "ukázať", ua: "показати", ru: "показать", en: "to show", img: "/words_a1/ukázať.jpg" },
      { sk: "niesť", ua: "нести", ru: "нести", en: "to carry", img: "/words_a1/niesť.jpg" },
      { sk: "sedieť", ua: "сидіти", ru: "сидеть", en: "to sit", img: "/words_a1/sedieť.jpg" },
    ],
  }
];