import type { Lesson } from "../data";

export const A1_ALL: Lesson[] = [
  {
    id: "a1-1",
    title: { ua: "Урок 1 — Знайомство", ru: "Урок 1 — Знакомство" },
    words: [
      { sk: "volať sa", ua: "називатися", ru: "называться", img: "/words_a1/volať sa.jpg" },
      { sk: "zoznámiť sa", ua: "познайомитися", ru: "познакомиться", img: "/words_a1/zoznámiť sa.jpg" },
      { sk: "meno", ua: "ім’я", ru: "имя", img: "/words_a1/meno.jpg" },
      { sk: "priezvisko", ua: "прізвище", ru: "фамилия", img: "/words_a1/priezvisko.jpg" },
      { sk: "odkiaľ", ua: "звідки", ru: "откуда", img: "/words_a1/odkiaľ.jpg" },
      { sk: "bývať", ua: "жити (мешкати)", ru: "жить (проживать)", img: "/words_a1/bývať.jpg" },
      { sk: "pracovať", ua: "працювати", ru: "работать", img: "/words_a1/pracovať.jpg" },
      { sk: "teší ma", ua: "приємно познайомитись", ru: "приятно познакомиться", img: "/words_a1/teší ma.jpg" },
      { sk: "mať rád/rada", ua: "подобатися/любити", ru: "нравиться/любить", img: "/words_a1/mať rád/rada.jpg" },
      { sk: "ďakujem", ua: "дякую", ru: "спасибо", img: "/words_a1/ďakujem.jpg" },
    ],
  },
  {
    id: "a1-2",
    title: { ua: "Урок 2 — Ввічливі фрази", ru: "Урок 2 — Вежливые фразы" },
    words: [
      { sk: "prosím", ua: "будь ласка", ru: "пожалуйста", img: "/words_a1/prosím.jpg" },
      { sk: "prepáčte", ua: "вибачте", ru: "извините" , img: "/words_a1/prepáčte.jpg"},
      { sk: "ďakujem pekne", ua: "дуже дякую", ru: "большое спасибо", img: "/words_a1/ďakujem pekne.jpg" },
      { sk: "niet za čo", ua: "нема за що", ru: "не за что" , img: "/words_a1/niet za čo.jpg"},
      { sk: "môžem?", ua: "можна?", ru: "можно?" , img: "/words_a1/môžem.jpg"},
      { sk: "môžete?", ua: "можете?", ru: "можете?" , img: "/words_a1/môžete.jpg"},
      { sk: "pomôžte mi", ua: "допоможіть мені", ru: "помогите мне", img: "/words_a1/pomôžte mi.jpg" },
      { sk: "nech sa páči", ua: "прошу / будь ласка (даючи щось)", ru: "пожалуйста (вот, когда даёте что-то)" , img: "/words_a1/nech sa páči.jpg"},
      { sk: "v poriadku", ua: "в порядку", ru: "в порядке" , img: "/words_a1/v poriadku.jpg"},
      { sk: "jasné", ua: "ясно", ru: "ясно", img: "/words_a1/jasné.jpg" },
    ],
  },
  {
    id: "a1-3",
    title: { ua: "Урок 3 — Місто", ru: "Урок 3 — Город" },
    words: [
      { sk: "križovatka", ua: "перехрестя", ru: "перекрёсток", img: "/words_a1/križovatka.jpg" },
      { sk: "semafor", ua: "світлофор", ru: "светофор", img: "/words_a1/semafor.jpg" },
      { sk: "most", ua: "міст", ru: "мост" , img: "/words_a1/most.jpg"},
      { sk: "kino", ua: "кінотеатр", ru: "кинотеатр", img: "/words_a1/kino.jpg" },
      { sk: "múzeum", ua: "музей", ru: "музей", img: "/words_a1/múzeum.jpg" },
      { sk: "lekáreň", ua: "аптека", ru: "аптека" , img: "/words_a1/lekáreň.jpg"},
      { sk: "knižnica", ua: "бібліотека", ru: "библиотека" , img: "/words_a1/knižnica.jpg"},
      { sk: "trh", ua: "ринок", ru: "рынок", img: "/words_a1/trh.jpg" },
      { sk: "vstup", ua: "вхід", ru: "вход", img: "/words_a1/vstup.jpg" },
      { sk: "východ", ua: "вихід", ru: "выход", img: "/words_a1/východ.jpg" },
    ],
  },
  {
    id: "a1-4",
    title: { ua: "Урок 4 — Магазин (розширено)", ru: "Урок 4 — Магазин (расширено)" },
    words: [
      { sk: "pokladník", ua: "касир", ru: "кассир", img: "/words_a1/pokladník.jpg"},
      { sk: "regál", ua: "стелаж/полиця", ru: "стеллаж/полка" , img: "/words_a1/regál.jpg"},
      { sk: "oddelenie", ua: "відділ", ru: "отдел" , img: "/words_a1/oddelenie.jpg"},
      { sk: "veľkosť", ua: "розмір", ru: "размер", img: "/words_a1/veľkosť.jpg" },
      { sk: "skúsiť", ua: "приміряти/спробувати", ru: "примерить/попробовать" , img: "/words_a1/skúsiť.jpg"},
      { sk: "vymeniť", ua: "обміняти", ru: "обменять", img: "/words_a1/vymeniť.jpg" },
      { sk: "vrátiť", ua: "повернути (товар)", ru: "вернуть (товар)" , img: "/words_a1/vrátiť.jpg"},
      { sk: "záruka", ua: "гарантія", ru: "гарантия", img: "/words_a1/záruka.jpg" },
      { sk: "balenie", ua: "упаковка", ru: "упаковка" , img: "/words_a1/balenie.jpg"},
      { sk: "účtovať", ua: "рахувати (на касі)", ru: "пробивать (на кассе) / считать" , img: "/words_a1/účtovať.jpg"},
    ],
  },
  {
    id: "a1-5",
    title: { ua: "Урок 5 — Їжа (у ресторані)", ru: "Урок 5 — Еда (в ресторане)" },
    words: [
      { sk: "objednať", ua: "замовити", ru: "заказать", img: "/words_a1/objednať.jpg" },
      { sk: "porcia", ua: "порція", ru: "порция", img: "/words_a1/porcia.jpg" },
      { sk: "príloha", ua: "гарнір", ru: "гарнир" , img: "/words_a1/príloha.jpg"},
      { sk: "dezert", ua: "десерт", ru: "десерт", img: "/words_a1/dezert.jpg"},
      { sk: "chutný", ua: "смачний", ru: "вкусный", img: "/words_a1/chutný.jpg" },
      { sk: "hladný", ua: "голодний", ru: "голодный", img: "/words_a1/hladný.jpg" },
      { sk: "smädný", ua: "спраглий", ru: "хотящий пить / испытывающий жажду", img: "/words_a1/smädný.jpg" },
      { sk: "účtovať", ua: "виставити рахунок", ru: "выставить счёт" , img: "/words_a1/účtovať.jpg"},
      { sk: "zaplatiť", ua: "заплатити", ru: "заплатить" , img: "/words_a1/zaplatiť.jpg"},
      { sk: "rezervácia", ua: "бронювання", ru: "бронирование", img: "/words_a1/rezervácia.jpg" },
    ],
  },
  {
    id: "a1-6",
    title: { ua: "Урок 6 — Транспорт", ru: "Урок 6 — Транспорт" },
    words: [
      { sk: "cestovný poriadok", ua: "розклад", ru: "расписание" , img: "/words_a1/cestovný poriadok.jpg"},
      { sk: "prestup", ua: "пересадка", ru: "пересадка" , img: "/words_a1/prestup.jpg"},
      { sk: "nástupište", ua: "платформа", ru: "платформа", img: "/words_a1/nástupište.jpg" },
      { sk: "meškať", ua: "запізнюватися", ru: "опаздывать", img: "/words_a1/meškať.jpg" },
      { sk: "odchod", ua: "відправлення", ru: "отправление" , img: "/words_a1/odchod.jpg"},
      { sk: "príchod", ua: "прибуття", ru: "прибытие" , img: "/words_a1/príchod.jpg"},
      { sk: "lístok", ua: "квиток", ru: "билет" , img: "/words_a1/lístok.jpg"},
      { sk: "kúpiť", ua: "купити", ru: "купить", img: "/words_a1/kúpiť.jpg" },
      { sk: "vystúpiť", ua: "вийти (з транспорту)", ru: "выйти (из транспорта)" , img: "/words_a1/vystúpiť.jpg"},
      { sk: "nastúpiť", ua: "сісти (в транспорт)", ru: "сесть (в транспорт) / войти" , img: "/words_a1/nastúpiť.jpg"},
    ],
  },
  {
    id: "a1-7",
    title: { ua: "Урок 7 — Дім (побутові дії)", ru: "Урок 7 — Дом (бытовые действия)" },
    words: [
      { sk: "variť", ua: "готувати", ru: "готовить" , img: "/words_a1/variť.jpg"},
      { sk: "upratovať", ua: "прибирати", ru: "убирать / прибираться", img: "/words_a1/upratovať.jpg" },
      { sk: "umývať", ua: "мити", ru: "мыть" , img: "/words_a1/umývať.jpg"},
      { sk: "prať", ua: "прати", ru: "стирать", img: "/words_a1/prať.jpg" },
      { sk: "žehliť", ua: "прасувати", ru: "гладить", img: "/words_a1/žehliť.jpg" },
      { sk: "otvoriť", ua: "відкрити", ru: "открыть", img: "/words_a1/otvoriť.jpg" },
      { sk: "zatvoriť", ua: "закрити", ru: "закрыть" , img: "/words_a1/zatvoriť.jpg"},
      { sk: "zapnúť", ua: "увімкнути", ru: "включить", img: "/words_a1/zapnúť.jpg" },
      { sk: "vypnúť", ua: "вимкнути", ru: "выключить", img: "/words_a1/vypnúť.jpg" },
      { sk: "hľadať", ua: "шукати", ru: "искать", img: "/words_a1/hľadať.jpg" },
    ],
  },
  {
    id: "a1-8",
    title: { ua: "Урок 8 — Робота (процеси)", ru: "Урок 8 — Работа (процессы)" },
    words: [
      { sk: "pracovisko", ua: "робоче місце", ru: "рабочее место", img: "/words_a1/pracovisko.jpg" },
      { sk: "zmena", ua: "зміна", ru: "смена" , img: "/words_a1/zmena.jpg"},
      { sk: "nadčas", ua: "надурочно", ru: "сверхурочно", img: "/words_a1/nadčas.jpg" },
      { sk: "porada", ua: "нарада", ru: "совещание", img: "/words_a1/porada.jpg" },
      { sk: "úloha", ua: "завдання", ru: "задание", img: "/words_a1/úloha.jpg" },
      { sk: "hotovo", ua: "готово", ru: "готово", img: "/words_a1/hotovo.jpg" },
      { sk: "skontrolovať", ua: "перевірити", ru: "проверить", img: "/words_a1/skontrolovať.jpg" },
      { sk: "opraviť", ua: "відремонтувати/виправити", ru: "отремонтировать/исправить", img: "/words_a1/opraviť.jpg" },
      { sk: "začať", ua: "почати", ru: "начать" , img: "/words_a1/začať.jpg"},
      { sk: "skončiť", ua: "закінчити", ru: "закончить" , img: "/words_a1/skončiť.jpg"},
    ],
  },
  {
    id: "a1-9",
    title: { ua: "Урок 9 — Емоції і стани", ru: "Урок 9 — Эмоции и состояния" },
    words: [
      { sk: "unavený", ua: "втомлений", ru: "уставший", img: "/words_a1/unavený.jpg" },
      { sk: "šťastný", ua: "щасливий", ru: "счастливый", img: "/words_a1/šťastný.jpg" },
      { sk: "smutný", ua: "сумний", ru: "грустный" , img: "/words_a1/smutný.jpg"},
      { sk: "nahnevaný", ua: "злий", ru: "злой / сердитый", img: "/words_a1/nahnevaný.jpg" },
      { sk: "nervózny", ua: "нервовий", ru: "нервный", img: "/words_a1/nervózny.jpg" },
      { sk: "pokojný", ua: "спокійний", ru: "спокойный" , img: "/words_a1/pokojný.jpg"},
      { sk: "prekvapený", ua: "здивований", ru: "удивлённый" , img: "/words_a1/prekvapený.jpg"},
      { sk: "báť sa", ua: "боятися", ru: "бояться", img: "/words_a1/báť sa.jpg" },
      { sk: "tešiť sa", ua: "радіти/чекати з радістю", ru: "радоваться / ждать с радостью" , img: "/words_a1/tešiť sa.jpg"},
      { sk: "mať chuť", ua: "мати бажання", ru: "хотеть / иметь желание", img: "/words_a1/mať chuť.jpg" },
    ],
  },
  {
    id: "a1-10",
    title: { ua: "Урок 10 — Запитання", ru: "Урок 10 — Вопросы" },
    words: [
      { sk: "ktorý", ua: "який (котрий)", ru: "который" , img: "/words_a1/ktorý.jpg"},
      { sk: "aký", ua: "який (якої якості)", ru: "какой (какого качества)", img: "/words_a1/aký.jpg" },
      { sk: "čí", ua: "чий", ru: "чей", img: "/words_a1/čí.jpg" },
      { sk: "kde je...?", ua: "де є...?", ru: "где...?", img: "/words_a1/kde je....jpg" },
      { sk: "koľko to stojí?", ua: "скільки це коштує?", ru: "сколько это стоит?", img: "/words_a1/koľko to stojí.jpg" },
      { sk: "môžete zopakovať?", ua: "можете повторити?", ru: "можете повторить?" , img: "/words_a1/môžete zopakovať.jpg"},
      { sk: "čo to znamená?", ua: "що це означає?", ru: "что это значит?" , img: "/words_a1/čo to znamená.jpg"},
      { sk: "rozumiete?", ua: "розумієте?", ru: "понимаете?", img: "/words_a1/rozumiete.jpg" },
      { sk: "samozrejme", ua: "звісно", ru: "конечно", img: "/words_a1/samozrejme.jpg" },
      { sk: "neviem", ua: "не знаю", ru: "не знаю" , img: "/words_a1/neviem.jpg"},
    ],
  },

  {
    id: "a1-11",
    title: { ua: "Урок 11 — Опис людини", ru: "Урок 11 — Описание человека" },
    words: [
      { sk: "vysoký", ua: "високий", ru: "высокий", img: "/words_a1/vysoký.jpg" },
      { sk: "nízky", ua: "низький", ru: "низкий" , img: "/words_a1/nízky.jpg"},
      { sk: "mladý", ua: "молодий", ru: "молодой", img: "/words_a1/mladý.jpg" },
      { sk: "starý", ua: "старий", ru: "старый" , img: "/words_a1/starý.jpg"},
      { sk: "silný", ua: "сильний", ru: "сильный", img: "/words_a1/silný.jpg" },
      { sk: "slabý", ua: "слабкий", ru: "слабый", img: "/words_a1/slabý.jpg" },
      { sk: "pekný", ua: "гарний", ru: "красивый" , img: "/words_a1/pekný.jpg"},
      { sk: "škaredý", ua: "негарний", ru: "некрасивый / уродливый", img: "/words_a1/unavený.jpg" },
      { sk: "milý", ua: "милий", ru: "милый", img: "/words_a1/unavený.jpg" },
      { sk: "vážny", ua: "серйозний", ru: "серьёзный", img: "/words_a1/unavený.jpg" },
    ],
  },
  {
    id: "a1-12",
    title: { ua: "Урок 12 — Час", ru: "Урок 12 — Время" },
    words: [
      { sk: "ráno", ua: "ранок", ru: "утро" },
      { sk: "obed", ua: "обід", ru: "обед" },
      { sk: "večer", ua: "вечір", ru: "вечер" },
      { sk: "polnoc", ua: "північ", ru: "полночь" },
      { sk: "dnes", ua: "сьогодні", ru: "сегодня" },
      { sk: "zajtra", ua: "завтра", ru: "завтра" },
      { sk: "pozajtra", ua: "післязавтра", ru: "послезавтра" },
      { sk: "vždy", ua: "завжди", ru: "всегда" },
      { sk: "často", ua: "часто", ru: "часто" },
      { sk: "niekedy", ua: "інколи", ru: "иногда" },
    ],
  },
  {
    id: "a1-13",
    title: { ua: "Урок 13 — Дім", ru: "Урок 13 — Дом" },
    words: [
      { sk: "chodba", ua: "коридор", ru: "коридор" },
      { sk: "balkón", ua: "балкон", ru: "балкон" },
      { sk: "pivnica", ua: "підвал", ru: "подвал" },
      { sk: "výťah", ua: "ліфт", ru: "лифт" },
      { sk: "schody", ua: "сходи", ru: "лестница / ступени" },
      { sk: "záhrada", ua: "сад", ru: "сад" },
      { sk: "garáž", ua: "гараж", ru: "гараж" },
      { sk: "stena", ua: "стіна", ru: "стена" },
      { sk: "strop", ua: "стеля", ru: "потолок" },
      { sk: "podlaha", ua: "підлога", ru: "пол" },
    ],
  },
  {
    id: "a1-14",
    title: { ua: "Урок 14 — Покупки", ru: "Урок 14 — Покупки" },
    words: [
      { sk: "predávať", ua: "продавати", ru: "продавать" },
      { sk: "kupovať", ua: "купувати", ru: "покупать" },
      { sk: "lacný", ua: "дешевий", ru: "дешёвый" },
      { sk: "drahý", ua: "дорогий", ru: "дорогой" },
      { sk: "kvalita", ua: "якість", ru: "качество" },
      { sk: "značka", ua: "бренд", ru: "бренд / марка" },
      { sk: "akcia", ua: "акція", ru: "акция" },
      { sk: "zľavnený", ua: "зі знижкою", ru: "со скидкой" },
      { sk: "pokladňa", ua: "каса", ru: "касса" },
      { sk: "blok", ua: "чек", ru: "чек" },
    ],
  },
  {
    id: "a1-15",
    title: { ua: "Урок 15 — Подорожі", ru: "Урок 15 — Путешествия" },
    words: [
      { sk: "hotel", ua: "готель", ru: "отель" },
      { sk: "ubytovanie", ua: "проживання", ru: "проживание" },
      { sk: "turista", ua: "турист", ru: "турист" },
      { sk: "sprievodca", ua: "гід", ru: "гид" },
      { sk: "výlet", ua: "екскурсія", ru: "экскурсия" },
      { sk: "pláž", ua: "пляж", ru: "пляж" },
      { sk: "hory", ua: "гори", ru: "горы" },
      { sk: "more", ua: "море", ru: "море" },
      { sk: "rezervovať", ua: "бронювати", ru: "бронировать" },
      { sk: "dovolenka", ua: "відпустка", ru: "отпуск" },
    ],
  },
  {
    id: "a1-16",
    title: { ua: "Урок 16 — Здоровʼя", ru: "Урок 16 — Здоровье" },
    words: [
      { sk: "bolieť", ua: "боліти", ru: "болеть" },
      { sk: "hlava", ua: "голова", ru: "голова" },
      { sk: "zub", ua: "зуб", ru: "зуб" },
      { sk: "žalúdok", ua: "шлунок", ru: "желудок" },
      { sk: "tabletka", ua: "таблетка", ru: "таблетка" },
      { sk: "sirup", ua: "сироп", ru: "сироп" },
      { sk: "odpočívať", ua: "відпочивати", ru: "отдыхать" },
      { sk: "zdravý", ua: "здоровий", ru: "здоровый" },
      { sk: "chorý", ua: "хворий", ru: "больной" },
      { sk: "liečiť", ua: "лікувати", ru: "лечить" },
    ],
  },
  {
    id: "a1-17",
    title: { ua: "Урок 17 — Робота (словник)", ru: "Урок 17 — Работа (словарь)" },
    words: [
      { sk: "zamestnanec", ua: "працівник", ru: "работник / сотрудник" },
      { sk: "zamestnávateľ", ua: "роботодавець", ru: "работодатель" },
      { sk: "plat", ua: "зарплата", ru: "зарплата" },
      { sk: "pracovná zmluva", ua: "трудовий договір", ru: "трудовой договор" },
      { sk: "prax", ua: "досвід роботи", ru: "опыт работы" },
      { sk: "kariéra", ua: "карʼєра", ru: "карьера" },
      { sk: "povýšenie", ua: "підвищення", ru: "повышение" },
      { sk: "výpoveď", ua: "звільнення", ru: "увольнение / заявление об увольнении" },
      { sk: "povinnosť", ua: "обовʼязок", ru: "обязанность" },
      { sk: "právo", ua: "право", ru: "право" },
    ],
  },
  {
    id: "a1-18",
    title: { ua: "Урок 18 — Спілкування", ru: "Урок 18 — Общение" },
    words: [
      { sk: "rozumieť", ua: "розуміти", ru: "понимать" },
      { sk: "vysvetliť", ua: "пояснити", ru: "объяснить" },
      { sk: "opýtať sa", ua: "запитати", ru: "спросить" },
      { sk: "odpoveď", ua: "відповідь", ru: "ответ" },
      { sk: "názor", ua: "думка", ru: "мнение" },
      { sk: "súhlasiť", ua: "погоджуватися", ru: "соглашаться" },
      { sk: "nesúhlasiť", ua: "не погоджуватися", ru: "не соглашаться" },
      { sk: "diskutovať", ua: "обговорювати", ru: "обсуждать" },
      { sk: "hovor", ua: "розмова", ru: "разговор" },
      { sk: "kontakt", ua: "контакт", ru: "контакт" },
    ],
  },
  {
    id: "a1-19",
    title: { ua: "Урок 19 — Технології", ru: "Урок 19 — Технологии" },
    words: [
      { sk: "mobil", ua: "мобільний телефон", ru: "мобильный телефон" },
      { sk: "nabíjačka", ua: "зарядка", ru: "зарядка / зарядное устройство" },
      { sk: "správa", ua: "повідомлення", ru: "сообщение" },
      { sk: "hovor", ua: "дзвінок", ru: "звонок", img: "/words_a1/hovor1.jpg" },
      { sk: "internet", ua: "інтернет", ru: "интернет" },
      { sk: "wifi", ua: "вайфай", ru: "вай-фай" },
      { sk: "sociálne siete", ua: "соціальні мережі", ru: "социальные сети" },
      { sk: "profil", ua: "профіль", ru: "профиль" },
      { sk: "heslo", ua: "пароль", ru: "пароль" },
      { sk: "stiahnuť", ua: "завантажити", ru: "скачать / загрузить" },
    ],
  },
  {
    id: "a1-20",
    title: { ua: "Урок 20 — Повсякденні дії", ru: "Урок 20 — Повседневные действия" },
    words: [
      { sk: "vstať", ua: "встати", ru: "встать" },
      { sk: "ísť do práce", ua: "йти на роботу", ru: "идти на работу" },
      { sk: "nakupovať", ua: "робити покупки", ru: "делать покупки" },
      { sk: "oddýchnuť si", ua: "відпочити", ru: "отдохнуть" },
      { sk: "stretnúť sa", ua: "зустрітися", ru: "встретиться" },
      { sk: "telefonovať", ua: "телефонувати", ru: "звонить" },
      { sk: "variť", ua: "готувати", ru: "готовить" },
      { sk: "pozerať", ua: "дивитися", ru: "смотреть" },
      { sk: "čítať", ua: "читати", ru: "читать" },
      { sk: "spať", ua: "спати", ru: "спать" },
    ],
  },
  {
    id: "a1-21",
    title: { ua: "Урок 21 — Проблеми і ситуації", ru: "Урок 21 — Проблемы и ситуации" },
    words: [
      { sk: "problém", ua: "проблема", ru: "проблема" },
      { sk: "pokazený", ua: "зламаний", ru: "сломанный / неисправный" },
      { sk: "stratiť", ua: "загубити", ru: "потерять" },
      { sk: "nájsť", ua: "знайти", ru: "найти" },
      { sk: "meškať", ua: "запізнюватися", ru: "опаздывать" },
      { sk: "zabudnúť", ua: "забути", ru: "забыть" },
      { sk: "chyba", ua: "помилка", ru: "ошибка" },
      { sk: "oprava", ua: "ремонт", ru: "ремонт" },
      { sk: "pomoc", ua: "допомога", ru: "помощь" },
      { sk: "riešenie", ua: "рішення", ru: "решение" },
    ],
  },
  {
    id: "a1-22",
    title: { ua: "Урок 22 — Напрямки", ru: "Урок 22 — Направления" },
    words: [
      { sk: "vpravo", ua: "праворуч", ru: "направо" },
      { sk: "vľavo", ua: "ліворуч", ru: "налево" },
      { sk: "rovno", ua: "прямо", ru: "прямо" },
      { sk: "blízko", ua: "близько", ru: "близко" },
      { sk: "ďaleko", ua: "далеко", ru: "далеко" },
      { sk: "hore", ua: "вгору", ru: "вверх" },
      { sk: "dole", ua: "вниз", ru: "вниз" },
      { sk: "pred", ua: "перед", ru: "перед" },
      { sk: "za", ua: "за", ru: "за" },
      { sk: "medzi", ua: "між", ru: "между" },
    ],
  },
  {
    id: "a1-23",
    title: { ua: "Урок 23 — Характер", ru: "Урок 23 — Характер" },
    words: [
      { sk: "dobrý", ua: "добрий", ru: "добрый" },
      { sk: "zlý", ua: "поганий", ru: "плохой" },
      { sk: "trpezlivý", ua: "терплячий", ru: "терпеливый" },
      { sk: "lenivý", ua: "ледачий", ru: "ленивый" },
      { sk: "pracovitý", ua: "працьовитий", ru: "трудолюбивый" },
      { sk: "úprimný", ua: "щирий", ru: "искренний" },
      { sk: "priateľský", ua: "дружній", ru: "дружелюбный" },
      { sk: "vážny", ua: "серйозний", ru: "серьёзный" },
      { sk: "zábavný", ua: "веселий", ru: "весёлый" },
      { sk: "tichý", ua: "тихий", ru: "тихий" },
    ],
  },
  {
    id: "a1-24",
    title: { ua: "Урок 24 — Погода (розширено)", ru: "Урок 24 — Погода (расширено)" },
    words: [
      { sk: "teplo", ua: "тепло", ru: "тепло" },
      { sk: "chladno", ua: "холодно", ru: "холодно" },
      { sk: "zamračené", ua: "хмарно", ru: "пасмурно / облачно" },
      { sk: "jasno", ua: "ясно", ru: "ясно" },
      { sk: "pršať", ua: "йти дощу", ru: "идти (о дожде) / идти дождю" },
      { sk: "snežiť", ua: "йти снігу", ru: "идти (о снеге) / идти снегу" },
      { sk: "vietor", ua: "вітер", ru: "ветер" },
      { sk: "mráz", ua: "мороз", ru: "мороз" },
      { sk: "búrka", ua: "буря", ru: "буря / гроза" },
      { sk: "predpoveď", ua: "прогноз", ru: "прогноз" },
    ],
  },
  {
    id: "a1-25",
    title: { ua: "Урок 25 — Їжа (розширено)", ru: "Урок 25 — Еда (расширено)" },
    words: [
      { sk: "raňajky", ua: "сніданок", ru: "завтрак" },
      { sk: "obed", ua: "обід", ru: "обед" },
      { sk: "večera", ua: "вечеря", ru: "ужин" },
      { sk: "sladký", ua: "солодкий", ru: "сладкий" },
      { sk: "slaný", ua: "солоний", ru: "солёный" },
      { sk: "pikantný", ua: "гострий", ru: "острый / пикантный" },
      { sk: "čerstvý", ua: "свіжий", ru: "свежий" },
      { sk: "hlad", ua: "голод", ru: "голод" },
      { sk: "smäd", ua: "спрага", ru: "жажда" },
      { sk: "chuť", ua: "смак / бажання", ru: "вкус / желание" },
    ],
  },
  {
    id: "a1-26",
    title: { ua: "Урок 26 — Гроші (розширено)", ru: "Урок 26 — Деньги (расширено)" },
    words: [
      { sk: "platiť", ua: "платити", ru: "платить" },
      { sk: "ušetriť", ua: "зекономити", ru: "сэкономить" },
      { sk: "minúť", ua: "витратити", ru: "потратить" },
      { sk: "výplata", ua: "зарплата", ru: "зарплата" },
      { sk: "úver", ua: "кредит", ru: "кредит" },
      { sk: "dlh", ua: "борг", ru: "долг" },
      { sk: "bankomat", ua: "банкомат", ru: "банкомат" },
      { sk: "účet", ua: "рахунок", ru: "счёт" },
      { sk: "príjem", ua: "дохід", ru: "доход" },
      { sk: "výdavok", ua: "витрата", ru: "расход" },
    ],
  },
  {
    id: "a1-27",
    title: { ua: "Урок 27 — Технології (практика)", ru: "Урок 27 — Технологии (практика)" },
    words: [
      { sk: "zapnúť", ua: "увімкнути", ru: "включить" },
      { sk: "vypnúť", ua: "вимкнути", ru: "выключить" },
      { sk: "nabíjať", ua: "заряджати", ru: "заряжать" },
      { sk: "prihlásiť sa", ua: "увійти", ru: "войти" },
      { sk: "odhlásiť sa", ua: "вийти", ru: "выйти" },
      { sk: "stiahnuť", ua: "завантажити", ru: "скачать / загрузить" },
      { sk: "uložiť", ua: "зберегти", ru: "сохранить" },
      { sk: "vymazať", ua: "видалити", ru: "удалить" },
      { sk: "kliknúť", ua: "натиснути", ru: "нажать / кликнуть" },
      { sk: "nastavenia", ua: "налаштування", ru: "настройки" },
    ],
  },
  {
    id: "a1-28",
    title: { ua: "Урок 28 — Подорожі (ситуації)", ru: "Урок 28 — Путешествия (ситуации)" },
    words: [
      { sk: "let", ua: "рейс", ru: "рейс" },
      { sk: "meškanie", ua: "затримка", ru: "задержка" },
      { sk: "odlet", ua: "виліт", ru: "вылет" },
      { sk: "prílet", ua: "приліт", ru: "прилёт" },
      { sk: "pasová kontrola", ua: "паспортний контроль", ru: "паспортный контроль" },
      { sk: "batožina", ua: "багаж", ru: "багаж" },
      { sk: "rezervácia", ua: "бронювання", ru: "бронирование" },
      { sk: "sprievodca", ua: "гід", ru: "гид" },
      { sk: "mapa", ua: "карта", ru: "карта" },
      { sk: "cieľ", ua: "ціль", ru: "цель" },
    ],
  },
  {
    id: "a1-29",
    title: { ua: "Урок 29 — Робочі фрази", ru: "Урок 29 — Рабочие фразы" },
    words: [
      { sk: "rozumiem", ua: "розумію", ru: "понимаю" },
      { sk: "nerozumiem", ua: "не розумію", ru: "не понимаю" },
      { sk: "hotovo", ua: "готово", ru: "готово" },
      { sk: "môžem?", ua: "можна?", ru: "можно?" },
      { sk: "potrebujem", ua: "потрібно", ru: "нужно / мне нужно" },
      { sk: "problém", ua: "проблема", ru: "проблема" },
      { sk: "v poriadku", ua: "в порядку", ru: "в порядке" },
      { sk: "hneď", ua: "зараз", ru: "сейчас / сразу" },
      { sk: "neskôr", ua: "пізніше", ru: "позже" },
      { sk: "dohodnúť sa", ua: "домовитись", ru: "договориться" },
    ],
  },
  {
    id: "a1-30",
    title: { ua: "Урок 30 — Часті дієслова", ru: "Урок 30 — Частые глаголы" },
    words: [
      { sk: "mať", ua: "мати", ru: "иметь" },
      { sk: "byť", ua: "бути", ru: "быть" },
      { sk: "robiť", ua: "робити", ru: "делать" },
      { sk: "ísť", ua: "йти", ru: "идти" },
      { sk: "vidieť", ua: "бачити", ru: "видеть" },
      { sk: "počúvať", ua: "слухати", ru: "слушать" },
      { sk: "hovoriť", ua: "говорити", ru: "говорить" },
      { sk: "myslieť", ua: "думати", ru: "думать" },
      { sk: "chcieť", ua: "хотіти", ru: "хотеть" },
      { sk: "môcť", ua: "могти", ru: "мочь" },
    ],
  },
  {
    id: "a1-31",
    title: { ua: "Урок 31 — Почуття", ru: "Урок 31 — Чувства" },
    words: [
      { sk: "radosť", ua: "радість", ru: "радость" },
      { sk: "smútok", ua: "смуток", ru: "грусть / печаль" },
      { sk: "strach", ua: "страх", ru: "страх" },
      { sk: "hnev", ua: "злість", ru: "злость / гнев" },
      { sk: "láska", ua: "любов", ru: "любовь" },
      { sk: "únava", ua: "втома", ru: "усталость" },
      { sk: "stres", ua: "стрес", ru: "стресс" },
      { sk: "pokoj", ua: "спокій", ru: "покой / спокойствие" },
      { sk: "prekvapenie", ua: "здивування", ru: "удивление" },
      { sk: "nadšenie", ua: "захоплення", ru: "восторг / воодушевление" },
    ],
  },
  {
    id: "a1-32",
    title: { ua: "Урок 32 — Опис речей", ru: "Урок 32 — Описание вещей" },
    words: [
      { sk: "nový", ua: "новий", ru: "новый" },
      { sk: "starý", ua: "старий", ru: "старый" },
      { sk: "veľký", ua: "великий", ru: "большой" },
      { sk: "malý", ua: "малий", ru: "маленький" },
      { sk: "ťažký", ua: "важкий", ru: "тяжёлый" },
      { sk: "ľahký", ua: "легкий", ru: "лёгкий" },
      { sk: "rýchly", ua: "швидкий", ru: "быстрый" },
      { sk: "pomalý", ua: "повільний", ru: "медленный" },
      { sk: "drahý", ua: "дорогий", ru: "дорогой" },
      { sk: "lacný", ua: "дешевий", ru: "дешёвый" },
    ],
  },
  {
    id: "a1-33",
    title: { ua: "Урок 33 — Дім (дії)", ru: "Урок 33 — Дом (действия)" },
    words: [
      { sk: "variť", ua: "готувати", ru: "готовить" },
      { sk: "upratovať", ua: "прибирати", ru: "убирать / прибираться" },
      { sk: "otvoriť", ua: "відкрити", ru: "открыть" },
      { sk: "zatvoriť", ua: "закрити", ru: "закрыть" },
      { sk: "opraviť", ua: "відремонтувати", ru: "отремонтировать" },
      { sk: "postaviť", ua: "побудувати", ru: "построить" },
      { sk: "presťahovať sa", ua: "переїхати", ru: "переехать" },
      { sk: "zapnúť", ua: "увімкнути", ru: "включить" },
      { sk: "vypnúť", ua: "вимкнути", ru: "выключить" },
      { sk: "čistiť", ua: "чистити", ru: "чистить" },
    ],
  },
  {
    id: "a1-34",
    title: { ua: "Урок 34 — Комунікація", ru: "Урок 34 — Коммуникация" },
    words: [
      { sk: "hovoriť", ua: "говорити", ru: "говорить" },
      { sk: "počúvať", ua: "слухати", ru: "слушать" },
      { sk: "pýtať sa", ua: "питати", ru: "спрашивать" },
      { sk: "odpovedať", ua: "відповідати", ru: "отвечать" },
      { sk: "vysvetliť", ua: "пояснити", ru: "объяснить" },
      { sk: "opísať", ua: "описати", ru: "описать" },
      { sk: "súhlasiť", ua: "погоджуватись", ru: "соглашаться" },
      { sk: "nesúhlasiť", ua: "не погоджуватись", ru: "не соглашаться" },
      { sk: "navrhnúť", ua: "запропонувати", ru: "предложить" },
      { sk: "diskutovať", ua: "обговорювати", ru: "обсуждать" },
    ],
  },
  {
    id: "a1-35",
    title: { ua: "Урок 35 — Місто (ситуації)", ru: "Урок 35 — Город (ситуации)" },
    words: [
      { sk: "úrad", ua: "установа", ru: "учреждение" },
      { sk: "lekáreň", ua: "аптека", ru: "аптека" },
      { sk: "polícia", ua: "поліція", ru: "полиция" },
      { sk: "pošta", ua: "пошта", ru: "почта" },
      { sk: "banka", ua: "банк", ru: "банк" },
      { sk: "obchod", ua: "магазин", ru: "магазин" },
      { sk: "reštaurácia", ua: "ресторан", ru: "ресторан" },
      { sk: "kino", ua: "кінотеатр", ru: "кинотеатр" },
      { sk: "park", ua: "парк", ru: "парк" },
      { sk: "zastávka", ua: "зупинка", ru: "остановка" },
    ],
  },
  {
    id: "a1-36",
    title: { ua: "Урок 36 — Транспорт (дії)", ru: "Урок 36 — Транспорт (действия)" },
    words: [
      { sk: "nastúpiť", ua: "сісти", ru: "сесть / зайти (в транспорт)" },
      { sk: "vystúpiť", ua: "вийти", ru: "выйти (из транспорта)" },
      { sk: "prestúpiť", ua: "пересісти", ru: "пересесть / сделать пересадку" },
      { sk: "meškať", ua: "запізнюватися", ru: "опаздывать" },
      { sk: "čakať", ua: "чекати", ru: "ждать" },
      { sk: "odísť", ua: "піти", ru: "уйти" },
      { sk: "prísť", ua: "прийти", ru: "прийти" },
      { sk: "riadiť", ua: "керувати", ru: "водить / управлять" },
      { sk: "parkovať", ua: "паркувати", ru: "парковать(ся)" },
      { sk: "zastaviť", ua: "зупинити", ru: "остановить" },
    ],
  },
  {
    id: "a1-37",
    title: { ua: "Урок 37 — Плани", ru: "Урок 37 — Планы" },
    words: [
      { sk: "plán", ua: "план", ru: "план" },
      { sk: "cieľ", ua: "ціль", ru: "цель" },
      { sk: "budúcnosť", ua: "майбутнє", ru: "будущее" },
      { sk: "zajtra", ua: "завтра", ru: "завтра" },
      { sk: "budúci týždeň", ua: "наступного тижня", ru: "на следующей неделе" },
      { sk: "chcieť", ua: "хотіти", ru: "хотеть" },
      { sk: "rozhodnúť sa", ua: "вирішити", ru: "решить" },
      { sk: "skúsiť", ua: "спробувати", ru: "попробовать" },
      { sk: "začať", ua: "почати", ru: "начать" },
      { sk: "pokračovať", ua: "продовжити", ru: "продолжить" },
    ],
  },
  {
    id: "a1-38",
    title: { ua: "Урок 38 — Ситуації в магазині", ru: "Урок 38 — Ситуации в магазине" },
    words: [
      { sk: "hľadať", ua: "шукати", ru: "искать" },
      { sk: "nájsť", ua: "знайти", ru: "найти" },
      { sk: "vymeniť", ua: "обміняти", ru: "обменять" },
      { sk: "vrátiť", ua: "повернути", ru: "вернуть" },
      { sk: "zľava", ua: "знижка", ru: "скидка" },
      { sk: "blok", ua: "чек", ru: "чек" },
      { sk: "reklamácia", ua: "скарга/повернення", ru: "претензия / возврат (рекламация)" },
      { sk: "pokazený", ua: "зламаний", ru: "сломанный / неисправный" },
      { sk: "nový", ua: "новий", ru: "новый" },
      { sk: "fungovať", ua: "працювати", ru: "работать / функционировать" },
    ],
  },
  {
    id: "a1-39",
    title: { ua: "Урок 39 — Абстрактні слова", ru: "Урок 39 — Абстрактные слова" },
    words: [
      { sk: "život", ua: "життя", ru: "жизнь" },
      { sk: "čas", ua: "час", ru: "время" },
      { sk: "možnosť", ua: "можливість", ru: "возможность" },
      { sk: "dôvod", ua: "причина", ru: "причина" },
      { sk: "význam", ua: "значення", ru: "значение" },
      { sk: "pravda", ua: "правда", ru: "правда" },
      { sk: "lož", ua: "брехня", ru: "ложь" },
      { sk: "úspech", ua: "успіх", ru: "успех" },
      { sk: "neúspech", ua: "невдача", ru: "неудача" },
      { sk: "skúsenosť", ua: "досвід", ru: "опыт" },
    ],
  },
  {
    id: "a1-40",
    title: { ua: "Урок 40 — Повторення A1", ru: "Урок 40 — Повторение A1" },
    words: [
      { sk: "pracovať", ua: "працювати", ru: "работать" },
      { sk: "cestovať", ua: "подорожувати", ru: "путешествовать" },
      { sk: "nakupovať", ua: "купувати", ru: "покупать / ходить за покупками" },
      { sk: "hovoriť", ua: "говорити", ru: "говорить" },
      { sk: "rozumieť", ua: "розуміти", ru: "понимать" },
      { sk: "pomôcť", ua: "допомогти", ru: "помочь" },
      { sk: "žiť", ua: "жити", ru: "жить" },
      { sk: "učiť sa", ua: "вчитися", ru: "учиться" },
      { sk: "myslieť", ua: "думати", ru: "думать" },
      { sk: "tešiť sa", ua: "радіти", ru: "радоваться" },
    ],
  },]