import type { Lesson } from "../data";

export const B1_ALL: Lesson[] = [
  {
    id: "b1-1",
    title: { ua: "Урок 1 — Розмова (думки та аргументи)", ru: "Урок 1 — Разговор (мнения и аргументы)" },
    words: [
      { sk: "myslieť si", ua: "вважати/думати" },
      { sk: "podľa mňa", ua: "на мою думку" },
      { sk: "súhlasiť", ua: "погоджуватися" },
      { sk: "nesúhlasiť", ua: "не погоджуватися" },
      { sk: "argument", ua: "аргумент" },
      { sk: "dôkaz", ua: "доказ" },
      { sk: "presvedčiť", ua: "переконати" },
      { sk: "vysvetliť", ua: "пояснити" },
      { sk: "zhrnúť", ua: "підсумувати" },
      { sk: "dospieť k záveru", ua: "дійти висновку" },
    ],
  },
  {
    id: "b1-2",
    title: { ua: "Урок 2 — Дім (організація та правила)", ru: "Урок 2 — Дом (организация и правила)" },
    words: [
      { sk: "domácnosť", ua: "домогосподарство/побут" },
      { sk: "povinnosti", ua: "обовʼязки" },
      { sk: "dohodnúť sa", ua: "домовитися" },
      { sk: "rozvrh", ua: "розклад" },
      { sk: "poriadok", ua: "порядок" },
      { sk: "upratovanie", ua: "прибирання" },
      { sk: "zodpovednosť", ua: "відповідальність" },
      { sk: "rešpektovať", ua: "поважати/дотримуватись" },
      { sk: "pravidlo", ua: "правило" },
      { sk: "kompromis", ua: "компроміс" },
    ],
  },
  {
    id: "b1-3",
    title: { ua: "Урок 3 — Робота (план і дедлайни)", ru: "Урок 3 — Работа (план и дедлайны)" },
    words: [
      { sk: "termín", ua: "термін/дедлайн" },
      { sk: "deadline", ua: "дедлайн" },
      { sk: "priorita", ua: "пріоритет" },
      { sk: "zodpovedať", ua: "відповідати (за щось)" },
      { sk: "splniť", ua: "виконати" },
      { sk: "odovzdať", ua: "здати/передати" },
      { sk: "posunúť", ua: "перенести/зсунути" },
      { sk: "zdržanie", ua: "затримка" },
      { sk: "kontrolovať", ua: "контролювати/перевіряти" },
      { sk: "výsledok", ua: "результат" },
    ],
  },
  {
    id: "b1-4",
    title: { ua: "Урок 4 — Спілкування (ввічливо та чітко)", ru: "Урок 4 — Общение (вежливо и четко)" },
    words: [
      { sk: "prosím vás", ua: "будь ласка (ввічливо)" },
      { sk: "ospravedlňujem sa", ua: "перепрошую" },
      { sk: "mohli by ste...?", ua: "чи могли б ви...?" },
      { sk: "ďakujem za pomoc", ua: "дякую за допомогу" },
      { sk: "vážim si to", ua: "я це ціную" },
      { sk: "rozumiem vám", ua: "я вас розумію" },
      { sk: "skúsme to inak", ua: "спробуймо інакше" },
      { sk: "dajte mi vedieť", ua: "дайте знати" },
      { sk: "platí?", ua: "домовились?/ок?" },
      { sk: "dohodnuté", ua: "домовлено" },
    ],
  },
  {
    id: "b1-5",
    title: { ua: "Урок 5 — Подорожі (непередбачені ситуації)", ru: "Урок 5 — Путешествия (непредвиденные ситуации)" },
    words: [
      { sk: "meškanie", ua: "затримка" },
      { sk: "zrušený let", ua: "скасований рейс" },
      { sk: "náhradné spojenie", ua: "альтернативне сполучення" },
      { sk: "prebookovať", ua: "перебронювати" },
      { sk: "nárok", ua: "право/претензія" },
      { sk: "kompenzácia", ua: "компенсація" },
      { sk: "sťažnosť", ua: "скарга" },
      { sk: "stratená batožina", ua: "втрачений багаж" },
      { sk: "potvrdenie", ua: "підтвердження" },
      { sk: "poisťovňa", ua: "страхова" },
    ],
  },
  {
    id: "b1-6",
    title: { ua: "Урок 6 — Здоровʼя (лікар і симптоми)", ru: "Урок 6 — Здоровье (врач и симптомы)" },
    words: [
      { sk: "príznak", ua: "симптом" },
      { sk: "zhoršiť sa", ua: "погіршитися" },
      { sk: "zlepšiť sa", ua: "покращитися" },
      { sk: "vyšetrenie", ua: "обстеження" },
      { sk: "odporúčanie", ua: "рекомендація" },
      { sk: "liečba", ua: "лікування" },
      { sk: "vedľajšie účinky", ua: "побічні ефекти" },
      { sk: "dávkovanie", ua: "дозування" },
      { sk: "užívať lieky", ua: "приймати ліки" },
      { sk: "kontrola", ua: "контрольний огляд" },
    ],
  },
  {
    id: "b1-7",
    title: { ua: "Урок 7 — Гроші (бюджет і витрати)", ru: "Урок 7 — Деньги (бюджет и расходы)" },
    words: [
      { sk: "rozpočet", ua: "бюджет" },
      { sk: "výdavky", ua: "витрати" },
      { sk: "príjmy", ua: "доходи" },
      { sk: "ušetriť", ua: "зекономити" },
      { sk: "minúť", ua: "витратити" },
      { sk: "dlh", ua: "борг" },
      { sk: "splátka", ua: "платіж (в розстрочку)" },
      { sk: "poplatok", ua: "комісія/збір" },
      { sk: "zvýšiť", ua: "підвищити" },
      { sk: "znížiť", ua: "знизити" },
    ],
  },
  {
    id: "b1-8",
    title: { ua: "Урок 8 — Емоції (реакції і стани)", ru: "Урок 8 — Эмоции (реакции и состояния)" },
    words: [
      { sk: "byť pod stresom", ua: "бути в стресі" },
      { sk: "mať nervy", ua: "нервувати" },
      { sk: "mať obavy", ua: "мати побоювання" },
      { sk: "byť sklamaný", ua: "бути розчарованим" },
      { sk: "byť nadšený", ua: "бути в захваті" },
      { sk: "uľavilo sa mi", ua: "мені полегшало" },
      { sk: "rozčuľovať sa", ua: "злитись" },
      { sk: "upokojiť sa", ua: "заспокоїтись" },
      { sk: "cítiť sa", ua: "почуватися" },
      { sk: "prekvapiť", ua: "здивувати" },
    ],
  },
  {
    id: "b1-9",
    title: { ua: "Урок 9 — Технології (проблеми та підтримка)", ru: "Урок 9 — Технологии (проблемы и поддержка)" },
    words: [
      { sk: "zaseknúť sa", ua: "зависнути" },
      { sk: "chyba", ua: "помилка" },
      { sk: "aktualizácia", ua: "оновлення" },
      { sk: "nastavenia", ua: "налаштування" },
      { sk: "obnoviť", ua: "відновити" },
      { sk: "zálohovať", ua: "робити резервну копію" },
      { sk: "prihlásiť sa", ua: "увійти" },
      { sk: "odhlásiť sa", ua: "вийти" },
      { sk: "zablokovať", ua: "заблокувати" },
      { sk: "zákaznícka podpora", ua: "служба підтримки" },
    ],
  },
  {
    id: "b1-10",
    title: { ua: "Урок 10 — Повторення B1 (1–9)", ru: "Урок 10 — Повторение B1 (1–9)" },
    words: [
      { sk: "kompromis", ua: "компроміс" },
      { sk: "termín", ua: "дедлайн" },
      { sk: "dohodnuté", ua: "домовлено" },
      { sk: "kompenzácia", ua: "компенсація" },
      { sk: "vyšetrenie", ua: "обстеження" },
      { sk: "rozpočet", ua: "бюджет" },
      { sk: "uľavilo sa mi", ua: "полегшало" },
      { sk: "aktualizácia", ua: "оновлення" },
      { sk: "dôkaz", ua: "доказ" },
      { sk: "zdržanie", ua: "затримка" },
    ],
  },

  // ====== 11–20 ======
  {
    id: "b1-11",
    title: { ua: "Урок 11 — Новини та інформація", ru: "Урок 11 — Новости и информация" },
    words: [
      { sk: "správa", ua: "новина/повідомлення" },
      { sk: "zdroj", ua: "джерело" },
      { sk: "overiť", ua: "перевірити" },
      { sk: "pravdepodobne", ua: "ймовірно" },
      { sk: "určite", ua: "точно" },
      { sk: "dôveryhodný", ua: "надійний" },
      { sk: "zavádzať", ua: "вводити в оману" },
      { sk: "šíriť", ua: "поширювати" },
      { sk: "diskusia", ua: "дискусія" },
      { sk: "tvrdenie", ua: "твердження" },
    ],
  },
  {
    id: "b1-12",
    title: { ua: "Урок 12 — Відносини та межі", ru: "Урок 12 — Отношения и границы" },
    words: [
      { sk: "vzťah", ua: "стосунки" },
      { sk: "dôvera", ua: "довіра" },
      { sk: "rešpekt", ua: "повага" },
      { sk: "hranice", ua: "межі" },
      { sk: "úprimnosť", ua: "щирість" },
      { sk: "hádať sa", ua: "сваритися" },
      { sk: "zmieriť sa", ua: "помиритися" },
      { sk: "podporiť", ua: "підтримати" },
      { sk: "vyjasniť si", ua: "прояснити" },
      { sk: "nedorozumenie", ua: "непорозуміння" },
    ],
  },
  {
    id: "b1-13",
    title: { ua: "Урок 13 — Час (організація дня)", ru: "Урок 13 — Время (организация дня)" },
    words: [
      { sk: "stihnúť", ua: "встигнути" },
      { sk: "meškať", ua: "запізнюватися" },
      { sk: "ponáhľať sa", ua: "поспішати" },
      { sk: "odložiť", ua: "відкласти" },
      { sk: "presunúť", ua: "перенести" },
      { sk: "plán", ua: "план" },
      { sk: "zvyčajne", ua: "зазвичай" },
      { sk: "výnimka", ua: "виняток" },
      { sk: "rutina", ua: "рутина" },
      { sk: "zorganizovať", ua: "організувати" },
    ],
  },
  {
    id: "b1-14",
    title: { ua: "Урок 14 — В магазині (складніші покупки)", ru: "Урок 14 — В магазине (сложные покупки)" },
    words: [
      { sk: "reklamovať", ua: "рекламувати/повертати по гарантії" },
      { sk: "reklamácia", ua: "рекламація/претензія" },
      { sk: "poškodený", ua: "пошкоджений" },
      { sk: "záruka", ua: "гарантія" },
      { sk: "vrátenie", ua: "повернення" },
      { sk: "vymeniť", ua: "обміняти" },
      { sk: "doklad", ua: "документ/підтвердження" },
      { sk: "podmienky", ua: "умови" },
      { sk: "zľava", ua: "знижка" },
      { sk: "dostupnosť", ua: "наявність" },
    ],
  },
  {
    id: "b1-15",
    title: { ua: "Урок 15 — Природа (подорож і погода)", ru: "Урок 15 — Природа (путешествие и погода)" },
    words: [
      { sk: "predpoveď", ua: "прогноз" },
      { sk: "výstraha", ua: "попередження" },
      { sk: "búrka", ua: "буря" },
      { sk: "hmla", ua: "туман" },
      { sk: "poľadovica", ua: "ожеледиця" },
      { sk: "ochladenie", ua: "похолодання" },
      { sk: "oteplenie", ua: "потепління" },
      { sk: "vietor", ua: "вітер" },
      { sk: "zrážky", ua: "опади" },
      { sk: "počasie", ua: "погода" },
    ],
  },
  {
    id: "b1-16",
    title: { ua: "Урок 16 — Навчання (мотивація і прогрес)", ru: "Урок 16 — Учёба (мотивация и прогресс)" },
    words: [
      { sk: "cieľ", ua: "ціль" },
      { sk: "pokrok", ua: "прогрес" },
      { sk: "zlepšiť sa", ua: "покращитись" },
      { sk: "zvyknúť si", ua: "звикнути" },
      { sk: "disciplína", ua: "дисципліна" },
      { sk: "motivácia", ua: "мотивація" },
      { sk: "pravidelne", ua: "регулярно" },
      { sk: "opakovať", ua: "повторювати" },
      { sk: "učiť sa naspamäť", ua: "вчити напам’ять" },
      { sk: "zručnosť", ua: "навичка" },
    ],
  },
  {
    id: "b1-17",
    title: { ua: "Урок 17 — Культура (спілкування та манери)", ru: "Урок 17 — Культура (общение и манеры)" },
    words: [
      { sk: "zvyk", ua: "звичай" },
      { sk: "tradícia", ua: "традиція" },
      { sk: "správanie", ua: "поведінка" },
      { sk: "zdvorilosť", ua: "ввічливість" },
      { sk: "pozdraviť", ua: "привітатися" },
      { sk: "predstaviť sa", ua: "представитися" },
      { sk: "spoločnosť", ua: "суспільство/компанія" },
      { sk: "hostiteľ", ua: "господар" },
      { sk: "návšteva", ua: "візит" },
      { sk: "prispôsobiť sa", ua: "пристосуватися" },
    ],
  },
  {
    id: "b1-18",
    title: { ua: "Урок 18 — Візити та зустрічі", ru: "Урок 18 — Визиты и встречи" },
    words: [
      { sk: "stretnutie", ua: "зустріч" },
      { sk: "pozvánka", ua: "запрошення" },
      { sk: "potvrdiť", ua: "підтвердити" },
      { sk: "zrušiť", ua: "скасувати" },
      { sk: "presunúť", ua: "перенести" },
      { sk: "dohodnúť termín", ua: "узгодити дату" },
      { sk: "prísť načas", ua: "прийти вчасно" },
      { sk: "meškať", ua: "запізнюватися" },
      { sk: "ospravedlniť sa", ua: "перепросити" },
      { sk: "rozlúčiť sa", ua: "попрощатися" },
    ],
  },
  {
    id: "b1-19",
    title: { ua: "Урок 19 — Місто (установи та документи)", ru: "Урок 19 — Город (учреждения и документы)" },
    words: [
      { sk: "úrad", ua: "установа" },
      { sk: "žiadosť", ua: "заява" },
      { sk: "tlačivo", ua: "бланк" },
      { sk: "potvrdenie", ua: "довідка/підтвердження" },
      { sk: "podpis", ua: "підпис" },
      { sk: "pečiatka", ua: "печатка" },
      { sk: "termín", ua: "дата/термін" },
      { sk: "číslo", ua: "номер" },
      { sk: "doklad totožnosti", ua: "посвідчення особи" },
      { sk: "poplatok", ua: "збір/комісія" },
    ],
  },
  {
    id: "b1-20",
    title: { ua: "Урок 20 — Повторення B1 (11–19)", ru: "Урок 20 — Повторение B1 (11–19)" },
    words: [
      { sk: "dôveryhodný", ua: "надійний" },
      { sk: "nedorozumenie", ua: "непорозуміння" },
      { sk: "ponáhľať sa", ua: "поспішати" },
      { sk: "reklamácia", ua: "претензія" },
      { sk: "výstraha", ua: "попередження" },
      { sk: "disciplína", ua: "дисципліна" },
      { sk: "prispôsobiť sa", ua: "пристосуватися" },
      { sk: "pozvánka", ua: "запрошення" },
      { sk: "tlačivo", ua: "бланк" },
      { sk: "pečiatka", ua: "печатка" },
    ],
  },

  // ====== 21–30 ======
  {
    id: "b1-21",
    title: { ua: "Урок 21 — Робота (конфлікти та рішення)", ru: "Урок 21 — Работа (конфликты и решения)" },
    words: [
      { sk: "konflikt", ua: "конфлікт" },
      { sk: "riešiť", ua: "вирішувати" },
      { sk: "sťažovať sa", ua: "скаржитися" },
      { sk: "vysvetliť si", ua: "з’ясувати" },
      { sk: "dohoda", ua: "домовленість" },
      { sk: "pripomienka", ua: "зауваження" },
      { sk: "kritika", ua: "критика" },
      { sk: "zlepšenie", ua: "покращення" },
      { sk: "ponúknuť", ua: "запропонувати" },
      { sk: "prijať", ua: "прийняти" },
    ],
  },
  {
    id: "b1-22",
    title: { ua: "Урок 22 — Характер (як описати людей)", ru: "Урок 22 — Характер (как описывать людей)" },
    words: [
      { sk: "spoľahlivý", ua: "надійний" },
      { sk: "zodpovedný", ua: "відповідальний" },
      { sk: "trpezlivý", ua: "терплячий" },
      { sk: "tvrdohlavý", ua: "впертий" },
      { sk: "citlivý", ua: "чутливий" },
      { sk: "sebavedomý", ua: "впевнений у собі" },
      { sk: "skromný", ua: "скромний" },
      { sk: "príjemný", ua: "приємний" },
      { sk: "nepríjemný", ua: "неприємний" },
      { sk: "úprimný", ua: "щирий" },
    ],
  },
  {
    id: "b1-23",
    title: { ua: "Урок 23 — Плани (майбутнє і наміри)", ru: "Урок 23 — Планы (будущее и намерения)" },
    words: [
      { sk: "plánovať", ua: "планувати" },
      { sk: "rozhodnúť sa", ua: "вирішити" },
      { sk: "zvážiť", ua: "зважити" },
      { sk: "vyskúšať", ua: "спробувати" },
      { sk: "odhodlanie", ua: "рішучість" },
      { sk: "ambícia", ua: "амбіція" },
      { sk: "príležitosť", ua: "можливість" },
      { sk: "riziko", ua: "ризик" },
      { sk: "zmeniť", ua: "змінити" },
      { sk: "pokračovať", ua: "продовжити" },
    ],
  },
  {
    id: "b1-24",
    title: { ua: "Урок 24 — Їжа (звички та здорове харчування)", ru: "Урок 24 — Еда (привычки и здоровое питание)" },
    words: [
      { sk: "stravovanie", ua: "харчування" },
      { sk: "zdravý", ua: "здоровий" },
      { sk: "nezdravý", ua: "нездоровий" },
      { sk: "vyvážený", ua: "збалансований" },
      { sk: "porcia", ua: "порція" },
      { sk: "kalórie", ua: "калорії" },
      { sk: "cukor", ua: "цукор" },
      { sk: "soľ", ua: "сіль" },
      { sk: "tuk", ua: "жир" },
      { sk: "jedálniček", ua: "меню/раціон" },
    ],
  },
  {
    id: "b1-25",
    title: { ua: "Урок 25 — Спорт і здоровʼя", ru: "Урок 25 — Спорт и здоровье" },
    words: [
      { sk: "kondícia", ua: "фізична форма" },
      { sk: "vytrvalosť", ua: "витривалість" },
      { sk: "silový tréning", ua: "силове тренування" },
      { sk: "strečing", ua: "розтяжка" },
      { sk: "zahriať sa", ua: "розігрітися" },
      { sk: "zranenie", ua: "травма" },
      { sk: "regenerácia", ua: "відновлення" },
      { sk: "bolesť svalov", ua: "біль у мʼязах" },
      { sk: "cvičiť pravidelne", ua: "тренуватися регулярно" },
      { sk: "zdravotný stav", ua: "стан здоров’я" },
    ],
  },
  {
    id: "b1-26",
    title: { ua: "Урок 26 — Технології (соцмережі та звички)", ru: "Урок 26 — Технологии (соцсети и привычки)" },
    words: [
      { sk: "sociálne siete", ua: "соціальні мережі" },
      { sk: "návykový", ua: "звикання/залежність" },
      { sk: "závislosť", ua: "залежність" },
      { sk: "obmedziť", ua: "обмежити" },
      { sk: "súkromie", ua: "приватність" },
      { sk: "nastaviť", ua: "налаштувати" },
      { sk: "zdieľať", ua: "ділитися" },
      { sk: "komentár", ua: "коментар" },
      { sk: "sledovať", ua: "стежити/підписатися" },
      { sk: "zablokovať", ua: "заблокувати" },
    ],
  },
  {
    id: "b1-27",
    title: { ua: "Урок 27 — Відпочинок (плани на вихідні)", ru: "Урок 27 — Отдых (планы на выходные)" },
    words: [
      { sk: "oddýchnuť si", ua: "відпочити" },
      { sk: "výlet", ua: "поїздка/екскурсія" },
      { sk: "turistika", ua: "похід" },
      { sk: "rezervovať", ua: "забронювати" },
      { sk: "zrušiť", ua: "скасувати" },
      { sk: "spontánne", ua: "спонтанно" },
      { sk: "dopredu", ua: "заздалегідь" },
      { sk: "vopred", ua: "наперед" },
      { sk: "stretnúť sa", ua: "зустрітися" },
      { sk: "program", ua: "план/програма" },
    ],
  },
  {
    id: "b1-28",
    title: { ua: "Урок 28 — Опис місць (враження)", ru: "Урок 28 — Описание мест (впечатления)" },
    words: [
      { sk: "pôsobivý", ua: "вражаючий" },
      { sk: "útulný", ua: "затишний" },
      { sk: "hlučný", ua: "шумний" },
      { sk: "pokojný", ua: "спокійний" },
      { sk: "špinavý", ua: "брудний" },
      { sk: "čistý", ua: "чистий" },
      { sk: "moderný", ua: "сучасний" },
      { sk: "tradičný", ua: "традиційний" },
      { sk: "dostupný", ua: "доступний" },
      { sk: "vzdialený", ua: "віддалений" },
    ],
  },
  {
    id: "b1-29",
    title: { ua: "Урок 29 — Мова (фрази для розмови)", ru: "Урок 29 — Язык (фразы для разговора)" },
    words: [
      { sk: "ak tomu rozumiem správne", ua: "якщо я правильно розумію" },
      { sk: "inými slovami", ua: "іншими словами" },
      { sk: "na druhej strane", ua: "з іншого боку" },
      { sk: "v každom prípade", ua: "в будь-якому разі" },
      { sk: "záleží na tom", ua: "залежить від цього" },
      { sk: "mám pocit, že", ua: "мені здається, що" },
      { sk: "neviem presne", ua: "не знаю точно" },
      { sk: "to dáva zmysel", ua: "це має сенс" },
      { sk: "to je zaujímavé", ua: "це цікаво" },
      { sk: "poďme ďalej", ua: "йдемо далі" },
    ],
  },
  {
    id: "b1-30",
    title: { ua: "Урок 30 — Повторення B1 (21–29)", ru: "Урок 30 — Повторение B1 (21–29)" },
    words: [
      { sk: "konflikt", ua: "конфлікт" },
      { sk: "tvrdohlavý", ua: "впертий" },
      { sk: "ambícia", ua: "амбіція" },
      { sk: "vyvážený", ua: "збалансований" },
      { sk: "zranenie", ua: "травма" },
      { sk: "závislosť", ua: "залежність" },
      { sk: "spontánne", ua: "спонтанно" },
      { sk: "útulný", ua: "затишний" },
      { sk: "inými slovami", ua: "іншими словами" },
      { sk: "záleží na tom", ua: "залежить" },
    ],
  },

  // ====== 31–60 ======
  {
    id: "b1-31",
    title: { ua: "Урок 31 — Робота (зустрічі та задачі)", ru: "Урок 31 — Работа (встречи и задачи)" },
    words: [
      { sk: "porada", ua: "нарада" },
      { sk: "agenda", ua: "порядок денний" },
      { sk: "úloha", ua: "завдання" },
      { sk: "zodpovedný", ua: "відповідальний" },
      { sk: "prideliť", ua: "призначити/розподілити" },
      { sk: "prebrať", ua: "обговорити" },
      { sk: "navrhnúť", ua: "запропонувати" },
      { sk: "schváliť", ua: "затвердити" },
      { sk: "odmietnuť", ua: "відмовити" },
      { sk: "záznam", ua: "запис/протокол" },
    ],
  },
  {
    id: "b1-32",
    title: { ua: "Урок 32 — Фінанси (банк і рахунки)", ru: "Урок 32 — Финансы (банк и счета)" },
    words: [
      { sk: "bankový účet", ua: "банківський рахунок" },
      { sk: "prevod", ua: "переказ" },
      { sk: "trvalý príkaz", ua: "постійне доручення" },
      { sk: "inkaso", ua: "автосписання" },
      { sk: "výpis", ua: "виписка" },
      { sk: "zostatok", ua: "залишок" },
      { sk: "limit", ua: "ліміт" },
      { sk: "blokovať kartu", ua: "заблокувати картку" },
      { sk: "poplatky", ua: "комісії" },
      { sk: "overenie platby", ua: "підтвердження платежу" },
    ],
  },
  {
    id: "b1-33",
    title: { ua: "Урок 33 — Конфлікти (як говорити спокійно)", ru: "Урок 33 — Конфликты (как говорить спокойно)" },
    words: [
      { sk: "nepríjemné", ua: "неприємно" },
      { sk: "uraziť", ua: "образити" },
      { sk: "kritizovať", ua: "критикувати" },
      { sk: "upozorniť", ua: "звернути увагу" },
      { sk: "vysvetlenie", ua: "пояснення" },
      { sk: "ospravedlnenie", ua: "вибачення" },
      { sk: "pochopiť", ua: "зрозуміти" },
      { sk: "zachovať pokoj", ua: "зберігати спокій" },
      { sk: "dohodnúť sa", ua: "домовитися" },
      { sk: "urovnať", ua: "уладнати" },
    ],
  },
  {
    id: "b1-34",
    title: { ua: "Урок 34 — Житло (сусіди та правила)", ru: "Урок 34 — Жильё (соседи и правила)" },
    words: [
      { sk: "sused", ua: "сусід" },
      { sk: "hluk", ua: "шум" },
      { sk: "ticho", ua: "тиша" },
      { sk: "domový poriadok", ua: "правила будинку" },
      { sk: "sťažnosť", ua: "скарга" },
      { sk: "upozornenie", ua: "попередження" },
      { sk: "spoločné priestory", ua: "спільні приміщення" },
      { sk: "výťah", ua: "ліфт" },
      { sk: "pivnica", ua: "підвал" },
      { sk: "správca", ua: "управитель/адмін" },
    ],
  },
  {
    id: "b1-35",
    title: { ua: "Урок 35 — Відпустка (плани і бронювання)", ru: "Урок 35 — Отпуск (планы и бронирование)" },
    words: [
      { sk: "dovolenka", ua: "відпустка" },
      { sk: "ubytovanie", ua: "проживання" },
      { sk: "rezervácia", ua: "бронювання" },
      { sk: "potvrdenie", ua: "підтвердження" },
      { sk: "záloha", ua: "передоплата" },
      { sk: "storno", ua: "скасування" },
      { sk: "podmienky", ua: "умови" },
      { sk: "cestovné poistenie", ua: "страхування подорожі" },
      { sk: "program", ua: "програма" },
      { sk: "oddych", ua: "відпочинок" },
    ],
  },
  {
    id: "b1-36",
    title: { ua: "Урок 36 — Робота (безпека і правила)", ru: "Урок 36 — Работа (безопасность и правила)" },
    words: [
      { sk: "bezpečnosť práce", ua: "охорона праці" },
      { sk: "ochranné pomôcky", ua: "засоби захисту" },
      { sk: "povinné", ua: "обов’язкове" },
      { sk: "zakázané", ua: "заборонене" },
      { sk: "návod", ua: "інструкція" },
      { sk: "školenie", ua: "інструктаж" },
      { sk: "riziko", ua: "ризик" },
      { sk: "zranenie", ua: "травма" },
      { sk: "predpis", ua: "припис/норма" },
      { sk: "dodržiavať", ua: "дотримуватися" },
    ],
  },
  {
    id: "b1-37",
    title: { ua: "Урок 37 — Місто (сервіси і послуги)", ru: "Урок 37 — Город (сервисы и услуги)" },
    words: [
      { sk: "služba", ua: "послуга" },
      { sk: "objednať termín", ua: "записатися" },
      { sk: "čakacia doba", ua: "час очікування" },
      { sk: "otváracie hodiny", ua: "години роботи" },
      { sk: "rezervovať", ua: "забронювати" },
      { sk: "zrušiť", ua: "скасувати" },
      { sk: "potvrdiť", ua: "підтвердити" },
      { sk: "dostupnosť", ua: "доступність" },
      { sk: "informácie", ua: "інформація" },
      { sk: "kontakt", ua: "контакт" },
    ],
  },
  {
    id: "b1-38",
    title: { ua: "Урок 38 — Дім (ремонт і майстерня)", ru: "Урок 38 — Дом (ремонт и мастерская)" },
    words: [
      { sk: "porucha", ua: "поломка" },
      { sk: "oprava", ua: "ремонт" },
      { sk: "diagnostika", ua: "діагностика" },
      { sk: "náhradné diely", ua: "запасні частини" },
      { sk: "odhad ceny", ua: "оцінка вартості" },
      { sk: "záruka", ua: "гарантія" },
      { sk: "servis", ua: "сервіс" },
      { sk: "objednať", ua: "замовити" },
      { sk: "vymeniť", ua: "замінити" },
      { sk: "fungovať", ua: "працювати" },
    ],
  },
  {
    id: "b1-39",
    title: { ua: "Урок 39 — Поради (як радити)", ru: "Урок 39 — Советы (как советовать)" },
    words: [
      { sk: "odporúčať", ua: "рекомендувати" },
      { sk: "poradiť", ua: "порадити" },
      { sk: "najlepšie je", ua: "найкраще" },
      { sk: "mal by si", ua: "тобі варто" },
      { sk: "skús", ua: "спробуй" },
      { sk: "dávať pozor", ua: "бути обережним" },
      { sk: "vyhnúť sa", ua: "уникати" },
      { sk: "pomôže", ua: "допоможе" },
      { sk: "záleží", ua: "залежить" },
      { sk: "vhodné", ua: "доречне/підходяще" },
    ],
  },
  {
    id: "b1-40",
    title: { ua: "Урок 40 — Повторення B1 (31–39)", ru: "Урок 40 — Повторение B1 (31–39)" },
    words: [
      { sk: "agenda", ua: "порядок денний" },
      { sk: "trvalý príkaz", ua: "постійне доручення" },
      { sk: "urovnať", ua: "уладнати" },
      { sk: "domový poriadok", ua: "правила будинку" },
      { sk: "storno", ua: "скасування" },
      { sk: "ochranné pomôcky", ua: "засоби захисту" },
      { sk: "čakacia doba", ua: "час очікування" },
      { sk: "diagnostika", ua: "діагностика" },
      { sk: "vyhnúť sa", ua: "уникати" },
      { sk: "dostupnosť", ua: "доступність" },
    ],
  },

  {
    id: "b1-41",
    title: { ua: "Урок 41 — Опис подій (історія/досвід)", ru: "Урок 41 — Описание событий (история/опыт)" },
    words: [
      { sk: "udalosť", ua: "подія" },
      { sk: "zažiť", ua: "пережити" },
      { sk: "spomenúť si", ua: "згадати" },
      { sk: "spomienka", ua: "спогад" },
      { sk: "priebeh", ua: "перебіг" },
      { sk: "zrazu", ua: "раптом" },
      { sk: "nakoniec", ua: "зрештою" },
      { sk: "našťastie", ua: "на щастя" },
      { sk: "žiaľ", ua: "на жаль" },
      { sk: "poučenie", ua: "висновок/урок" },
    ],
  },
  {
    id: "b1-42",
    title: { ua: "Урок 42 — Мова (порівняння та нюанси)", ru: "Урок 42 — Язык (сравнения и нюансы)" },
    words: [
      { sk: "podobný", ua: "схожий" },
      { sk: "odlišný", ua: "відмінний" },
      { sk: "rozdiel", ua: "різниця" },
      { sk: "podobnosť", ua: "схожість" },
      { sk: "výraz", ua: "вираз/слово" },
      { sk: "význam", ua: "значення" },
      { sk: "nuansa", ua: "нюанс" },
      { sk: "presne", ua: "точно" },
      { sk: "približne", ua: "приблизно" },
      { sk: "záleží od kontextu", ua: "залежить від контексту" },
    ],
  },
  {
    id: "b1-43",
    title: { ua: "Урок 43 — Соціальне життя (плани й стосунки)", ru: "Урок 43 — Социальная жизнь (планы и отношения)" },
    words: [
      { sk: "stretnúť sa", ua: "зустрітися" },
      { sk: "dohodnúť sa", ua: "домовитися" },
      { sk: "spoločný", ua: "спільний" },
      { sk: "vzťahy", ua: "стосунки" },
      { sk: "priateľstvo", ua: "дружба" },
      { sk: "podpora", ua: "підтримка" },
      { sk: "dôvera", ua: "довіра" },
      { sk: "úprimnosť", ua: "щирість" },
      { sk: "sklamanie", ua: "розчарування" },
      { sk: "zmierenie", ua: "примирення" },
    ],
  },
  {
    id: "b1-44",
    title: { ua: "Урок 44 — Звички (корисні та шкідливі)", ru: "Урок 44 — Привычки (полезные и вредные)" },
    words: [
      { sk: "zvyk", ua: "звичка" },
      { sk: "návyk", ua: "звикання" },
      { sk: "závislosť", ua: "залежність" },
      { sk: "obmedziť", ua: "обмежити" },
      { sk: "zmeniť", ua: "змінити" },
      { sk: "zlepšiť", ua: "покращити" },
      { sk: "zhoršiť", ua: "погіршити" },
      { sk: "pravidelne", ua: "регулярно" },
      { sk: "disciplína", ua: "дисципліна" },
      { sk: "vytrvať", ua: "витримати/продовжувати" },
    ],
  },
  {
    id: "b1-45",
    title: { ua: "Урок 45 — Дім (покупки для дому)", ru: "Урок 45 — Дом (покупки для дома)" },
    words: [
      { sk: "náradie", ua: "інструменти" },
      { sk: "materiál", ua: "матеріал" },
      { sk: "návod", ua: "інструкція" },
      { sk: "montáž", ua: "монтаж" },
      { sk: "skrutka", ua: "гвинт" },
      { sk: "hmoždinka", ua: "дюбель" },
      { sk: "vŕtačka", ua: "дриль" },
      { sk: "kladivo", ua: "молоток" },
      { sk: "merať", ua: "вимірювати" },
      { sk: "opraviť", ua: "відремонтувати" },
    ],
  },
  {
    id: "b1-46",
    title: { ua: "Урок 46 — Робота (зміни та графік)", ru: "Урок 46 — Работа (смены и график)" },
    words: [
      { sk: "zmena", ua: "зміна" },
      { sk: "nočná", ua: "нічна зміна" },
      { sk: "denná", ua: "денна зміна" },
      { sk: "voľno", ua: "вихідний" },
      { sk: "nadčas", ua: "надурочні" },
      { sk: "prestávka", ua: "перерва" },
      { sk: "dochádzka", ua: "відвідуваність/прихід" },
      { sk: "zastúpiť", ua: "підмінити" },
      { sk: "vymeniť si zmenu", ua: "помінятися зміною" },
      { sk: "oznamiť", ua: "повідомити" },
    ],
  },
  {
    id: "b1-47",
    title: { ua: "Урок 47 — Послуги (телефон, інтернет, контракти)", ru: "Урок 47 — Услуги (телефон, интернет, контракты)" },
    words: [
      { sk: "zmluva", ua: "договір" },
      { sk: "viazanosť", ua: "контрактний термін" },
      { sk: "výpoveď", ua: "розірвання/звільнення" },
      { sk: "podmienky", ua: "умови" },
      { sk: "tarifa", ua: "тариф" },
      { sk: "poplatok", ua: "комісія/плата" },
      { sk: "zvýšiť cenu", ua: "підвищити ціну" },
      { sk: "znížiť cenu", ua: "знизити ціну" },
      { sk: "zrušiť službu", ua: "скасувати послугу" },
      { sk: "predĺžiť", ua: "продовжити" },
    ],
  },
  {
    id: "b1-48",
    title: { ua: "Урок 48 — Їжа (алергії та обмеження)", ru: "Урок 48 — Еда (аллергии и ограничения)" },
    words: [
      { sk: "alergia", ua: "алергія" },
      { sk: "intolerancia", ua: "непереносимість" },
      { sk: "bez lepku", ua: "без глютену" },
      { sk: "bez laktózy", ua: "без лактози" },
      { sk: "vegetarián", ua: "вегетаріанець" },
      { sk: "vegán", ua: "веган" },
      { sk: "zloženie", ua: "склад" },
      { sk: "obsahovať", ua: "містити" },
      { sk: "vynechať", ua: "прибрати/виключити" },
      { sk: "odporučiť", ua: "порадити" },
    ],
  },
  {
    id: "b1-49",
    title: { ua: "Урок 49 — Психологія (самопочуття)", ru: "Урок 49 — Психология (самочувствие)" },
    words: [
      { sk: "nálada", ua: "настрій" },
      { sk: "vyčerpaný", ua: "виснажений" },
      { sk: "oddych", ua: "відпочинок" },
      { sk: "rovnováha", ua: "баланс" },
      { sk: "zvládať stres", ua: "справлятися зі стресом" },
      { sk: "uvoľniť sa", ua: "розслабитися" },
      { sk: "napätie", ua: "напруга" },
      { sk: "podpora", ua: "підтримка" },
      { sk: "sebadôvera", ua: "впевненість у собі" },
      { sk: "pohoda", ua: "комфорт/псих.стан" },
    ],
  },
  {
    id: "b1-50",
    title: { ua: "Урок 50 — Повторення B1 (41–49)", ru: "Урок 50 — Повторение B1 (41–49)" },
    words: [
      { sk: "poučenie", ua: "висновок/урок" },
      { sk: "nuansa", ua: "нюанс" },
      { sk: "priateľstvo", ua: "дружба" },
      { sk: "vytrvať", ua: "витримати" },
      { sk: "náradie", ua: "інструменти" },
      { sk: "dochádzka", ua: "відвідуваність" },
      { sk: "viazanosť", ua: "контрактний термін" },
      { sk: "zloženie", ua: "склад" },
      { sk: "rovnováha", ua: "баланс" },
      { sk: "napätie", ua: "напруга" },
    ],
  },

  {
    id: "b1-51",
    title: { ua: "Урок 51 — Розповідь (послідовність)", ru: "Урок 51 — Рассказ (последовательность)" },
    words: [
      { sk: "najprv", ua: "спочатку" },
      { sk: "potom", ua: "потім" },
      { sk: "následne", ua: "далі" },
      { sk: "medzitým", ua: "тим часом" },
      { sk: "nakoniec", ua: "врешті" },
      { sk: "zrazu", ua: "раптом" },
      { sk: "napokon", ua: "зрештою" },
      { sk: "vtedy", ua: "тоді" },
      { sk: "odvtedy", ua: "відтоді" },
      { sk: "dovtedy", ua: "до того часу" },
    ],
  },
  {
    id: "b1-52",
    title: { ua: "Урок 52 — Умови (якщо/то)", ru: "Урок 52 — Условия (если/то)" },
    words: [
      { sk: "ak", ua: "якщо" },
      { sk: "keby", ua: "якби" },
      { sk: "inak", ua: "інакше" },
      { sk: "v prípade", ua: "у випадку" },
      { sk: "za podmienky", ua: "за умови" },
      { sk: "pokiaľ", ua: "поки/якщо" },
      { sk: "aj keď", ua: "навіть якщо" },
      { sk: "hoci", ua: "хоча" },
      { sk: "napriek tomu", ua: "попри це" },
      { sk: "v opačnom prípade", ua: "в іншому випадку" },
    ],
  },
  {
    id: "b1-53",
    title: { ua: "Урок 53 — Причина і наслідок", ru: "Урок 53 — Причина и следствие" },
    words: [
      { sk: "pretože", ua: "тому що" },
      { sk: "preto", ua: "тому" },
      { sk: "kvôli", ua: "через" },
      { sk: "vďaka", ua: "завдяки" },
      { sk: "dôvod", ua: "причина" },
      { sk: "dôsledok", ua: "наслідок" },
      { sk: "výsledok", ua: "результат" },
      { sk: "spôsobiť", ua: "спричинити" },
      { sk: "ovplyvniť", ua: "вплинути" },
      { sk: "zmeniť", ua: "змінити" },
    ],
  },
  {
    id: "b1-54",
    title: { ua: "Урок 54 — Робота (зворотній зв’язок)", ru: "Урок 54 — Работа (обратная связь)" },
    words: [
      { sk: "spätná väzba", ua: "зворотний зв’язок" },
      { sk: "pochvala", ua: "похвала" },
      { sk: "pripomienka", ua: "зауваження" },
      { sk: "zlepšenie", ua: "покращення" },
      { sk: "oceniť", ua: "оцінити" },
      { sk: "navrhnúť", ua: "запропонувати" },
      { sk: "zohľadniť", ua: "врахувати" },
      { sk: "súhlasiť", ua: "погодитися" },
      { sk: "nesúhlasiť", ua: "не погодитися" },
      { sk: "dohodnúť sa", ua: "домовитися" },
    ],
  },
  {
    id: "b1-55",
    title: { ua: "Урок 55 — Місто (транспорт і затримки)", ru: "Урок 55 — Город (транспорт и задержки)" },
    words: [
      { sk: "výluka", ua: "обмеження руху" },
      { sk: "obchádzka", ua: "об’їзд" },
      { sk: "zápcha", ua: "затори" },
      { sk: "nehoda", ua: "аварія" },
      { sk: "meškanie", ua: "запізнення" },
      { sk: "odklon", ua: "об’їзд/відхилення" },
      { sk: "spoj", ua: "сполучення" },
      { sk: "prestup", ua: "пересадка" },
      { sk: "nástupište", ua: "платформа" },
      { sk: "cestovný poriadok", ua: "розклад" },
    ],
  },
  {
    id: "b1-56",
    title: { ua: "Урок 56 — Дім (щоденні справи)", ru: "Урок 56 — Дом (ежедневные дела)" },
    words: [
      { sk: "vybaviť", ua: "вирішити/зробити (справи)" },
      { sk: "zariadiť", ua: "організувати/влаштувати" },
      { sk: "stihnúť", ua: "встигнути" },
      { sk: "odložiť", ua: "відкласти" },
      { sk: "upratať", ua: "прибрати" },
      { sk: "vyčistiť", ua: "почистити" },
      { sk: "nakúpiť", ua: "купити (продукти)" },
      { sk: "vyzdvihnúť", ua: "забрати/підхопити" },
      { sk: "zaniesť", ua: "віднести" },
      { sk: "doniesť", ua: "принести" },
    ],
  },
  {
    id: "b1-57",
    title: { ua: "Урок 57 — Комунікація (прохання і пропозиції)", ru: "Урок 57 — Общение (просьбы и предложения)" },
    words: [
      { sk: "mohol by si...?", ua: "міг би ти...?" },
      { sk: "vadilo by ti...?", ua: "не проти...?" },
      { sk: "pomôžeš mi?", ua: "допоможеш?" },
      { sk: "navrhujem", ua: "я пропоную" },
      { sk: "čo keby", ua: "що якби" },
      { sk: "dohodnime sa", ua: "домовимось" },
      { sk: "určite", ua: "звісно" },
      { sk: "bohužiaľ", ua: "на жаль" },
      { sk: "nemôžem", ua: "не можу" },
      { sk: "skúsim", ua: "спробую" },
    ],
  },
  {
    id: "b1-58",
    title: { ua: "Урок 58 — Думки (сумнів і впевненість)", ru: "Урок 58 — Мысли (сомнение и уверенность)" },
    words: [
      { sk: "som si istý", ua: "я впевнений" },
      { sk: "nie som si istý", ua: "я не впевнений" },
      { sk: "pochybovať", ua: "сумніватися" },
      { sk: "predpokladať", ua: "припускати" },
      { sk: "uvedomiť si", ua: "усвідомити" },
      { sk: "zistiť", ua: "з’ясувати" },
      { sk: "zdá sa mi", ua: "мені здається" },
      { sk: "pravdepodobne", ua: "ймовірно" },
      { sk: "určite", ua: "точно" },
      { sk: "možno", ua: "можливо" },
    ],
  },
  {
    id: "b1-59",
    title: { ua: "Урок 59 — Культура (фільми і музика)", ru: "Урок 59 — Культура (фильмы и музыка)" },
    words: [
      { sk: "žáner", ua: "жанр" },
      { sk: "dej", ua: "сюжет" },
      { sk: "postava", ua: "персонаж" },
      { sk: "herec", ua: "актор" },
      { sk: "režisér", ua: "режисер" },
      { sk: "recenzia", ua: "рецензія" },
      { sk: "odporučiť", ua: "порекомендувати" },
      { sk: "dojem", ua: "враження" },
      { sk: "nuda", ua: "нудьга" },
      { sk: "zaujímavý", ua: "цікавий" },
    ],
  },
  {
    id: "b1-60",
    title: { ua: "Урок 60 — Повторення B1 (51–59)", ru: "Урок 60 — Повторение B1 (51–59)" },
    words: [
      { sk: "medzitým", ua: "тим часом" },
      { sk: "v opačnom prípade", ua: "в іншому випадку" },
      { sk: "dôsledok", ua: "наслідок" },
      { sk: "spätná väzba", ua: "зворотний зв’язок" },
      { sk: "obchádzka", ua: "об’їзд" },
      { sk: "vyzdvihnúť", ua: "забрати" },
      { sk: "čo keby", ua: "що якби" },
      { sk: "predpokladať", ua: "припускати" },
      { sk: "recenzia", ua: "рецензія" },
      { sk: "nakoniec", ua: "врешті" },
    ],
  },
];