import type { Lesson } from "../data";

export const B1_ALL: Lesson[] = [
  {
    id: "b1-1",
    title: { ua: "Урок 1 — Робота та кар’єра", ru: "Урок 1 — Работа и карьера" },
    words: [
      { sk: "pracovná doba", ua: "робочий час", ru: "рабочее время", img: "/words_b1/pracovná doba.jpg" },
      { sk: "nástup", ua: "вихід на роботу (початок)", ru: "выход на работу (начало)", img: "/words_b1/nástup.jpg" },
      { sk: "skúšobná doba", ua: "випробувальний термін", ru: "испытательный срок", img: "/words_b1/skúšobná doba.jpg" },
      { sk: "pracovný pomer", ua: "трудові відносини", ru: "трудовые отношения", img: "/words_b1/pracovný pomer.jpg" },
      { sk: "výplata", ua: "виплата зарплати", ru: "выплата зарплаты", img: "/words_b1/výplata.jpg" },
      { sk: "príspevok", ua: "внесок/доплата", ru: "взнос/доплата", img: "/words_b1/príspevok.jpg" },
      { sk: "dochádzka", ua: "відвідуваність/табель", ru: "посещаемость/табель", img: "/words_b1/dochádzkaa.jpg" },
      { sk: "benefit", ua: "бонус / соціальна пільга", ru: "бонус / социальная льгота", img: "/words_b1/benefit.jpg" },
      { sk: "nadriadený", ua: "керівник / начальник", ru: "руководитель / начальник", img: "/words_b1/nadriadený.jpg" },
      { sk: "podriadený", ua: "підлеглий", ru: "подчинённый", img: "/words_b1/podriadený.jpg" },

    ],
  },
  {
    id: "b1-2",
    title: { ua: "Урок 2 — Комунікація в команді", ru: "Урок 2 — Коммуникация в команде" },
    words: [
      { sk: "nedorozumenie", ua: "непорозуміння", ru: "недоразумение", img: "/words_b1/nedorozumenie.jpg" },
      { sk: "spolupráca", ua: "співпраця", ru: "сотрудничество", img: "/words_b1/spolupráca.jpg" },
      { sk: "komunikácia", ua: "комунікація", ru: "коммуникация", img: "/words_b1/komunikácia.jpg" },
      { sk: "vyjadriť sa", ua: "висловитися", ru: "высказаться", img: "/words_b1/vyjadriť sa.jpg" },
      { sk: "navrhnúť", ua: "запропонувати", ru: "предложить", img: "/words_b1/navrhnúť.jpg" },
      { sk: "súhlas", ua: "згода", ru: "согласие", img: "/words_b1/súhlas.jpg" },
      { sk: "nesúhlas", ua: "незгода", ru: "несогласие", img: "/words_b1/nesúhlas.jpg" },
      { sk: "vysvetlenie", ua: "пояснення", ru: "объяснение", img: "/words_b1/vysvetlenie.jpg" },
      { sk: "upozorniť", ua: "попередити / звернути увагу", ru: "предупредить / обратить внимание", img: "/words_b1/upozorniť.jpg" },
      { sk: "reagovať", ua: "реагувати", ru: "реагировать", img: "/words_b1/reagovať.jpg" },
    ],
  },
  {
    id: "b1-3",
    title: { ua: "Урок 3 — Подорожі та транспорт", ru: "Урок 3 — Путешествия и транспорт" },
    words: [
      { sk: "príručná batožina", ua: "ручна поклажа", ru: "ручная кладь", img: "/words_b1/príručná batožina.jpg" },
      { sk: "nástup", ua: "посадка (на транспорт)", ru: "посадка", img: "/words_b1/nástup.jpg" },
      { sk: "cestujúci", ua: "пасажир", ru: "пассажир", img: "/words_b1/cestujúci.jpg" },
      { sk: "zrušenie", ua: "скасування", ru: "отмена", img: "/words_b1/zrušenie.jpg" },
      { sk: "prestupovať", ua: "робити пересадку", ru: "делать пересадку", img: "/words_b1/prestupovať.jpg" },
      { sk: "cestovný doklad", ua: "проїзний документ", ru: "проездной документ", img: "/words_b1/cestovný doklad.jpg" },
      { sk: "bezpečnostná kontrola", ua: "контроль безпеки", ru: "контроль безопасности", img: "/words_b1/bezpečnostná kontrola.jpg" },
      { sk: "palubný lístok", ua: "посадковий талон", ru: "посадочный талон", img: "/words_b1/palubný lístok.jpg" },
      { sk: "odovzdať batožinu", ua: "здати багаж", ru: "сдать багаж", img: "/words_b1/odovzdať batožinu.jpg" },
      { sk: "colná kontrola", ua: "митний контроль", ru: "таможенный контроль", img: "/words_b1/colná kontrola.jpg" },
    ],
  },
  {
    id: "b1-4",
    title: { ua: "Урок 4 — Здоров’я та лікар", ru: "Урок 4 — Здоровье и врач" },
    words: [
      { sk: "liečba", ua: "лікування", ru: "лечение", img: "/words_b1/liečba.jpg" },
      { sk: "vyšetriť", ua: "оглянути / обстежити", ru: "осмотреть / обследовать", img: "/words_b1/vyšetriť.jpg" },
      { sk: "predpísať", ua: "призначити (ліки)", ru: "назначить (лекарство)", img: "/words_b1/predpísať.jpg" },
      { sk: "zhoršiť sa", ua: "погіршитися", ru: "ухудшиться", img: "/words_b1/zhoršiť sa.jpg" },
      { sk: "zlepšiť sa", ua: "покращитися", ru: "улучшиться", img: "/words_b1/zlepšiť sa.jpg" },
      { sk: "hospitalizácia", ua: "госпіталізація", ru: "госпитализация", img: "/words_b1/hospitalizácia.jpg" },
      { sk: "príznak", ua: "симптом", ru: "симптом", img: "/words_b1/príznak.jpg" },
      { sk: "zdravotný stav", ua: "стан здоров’я", ru: "состояние здоровья", img: "/words_b1/zdravotný stav.jpg" },
      { sk: "zotavenie", ua: "одужання / відновлення", ru: "выздоровление / восстановление", img: "/words_b1/zotavenie.jpg" },
      { sk: "predpis", ua: "припис / медичне призначення", ru: "предписание / медицинское назначение", img: "/words_b1/predpis.jpg" },
    ],
  },
  {
    id: "b1-5",
    title: { ua: "Урок 5 — Емоції та стосунки", ru: "Урок 5 — Эмоции и отношения" },
    words: [
      { sk: "hádka", ua: "сварка", ru: "ссора", img: "/words_b1/hádka.jpg" },
      { sk: "zmierenie", ua: "примирення", ru: "примирение", img: "/words_b1/zmierenie.jpg" },
      { sk: "sklamať", ua: "розчарувати", ru: "разочаровать", img: "/words_b1/sklamať.jpg" },
      { sk: "oceniť", ua: "оцінити (позитивно)", ru: "оценить (положительно)", img: "/words_b1/oceniť.jpg" },
      { sk: "žiarlivosť", ua: "ревнощі", ru: "ревность", img: "/words_b1/žiarlivosť.jpg" },
      { sk: "odpustiť", ua: "пробачити", ru: "простить", img: "/words_b1/odpustiť.jpg" },
      { sk: "rešpekt", ua: "повага", ru: "уважение", img: "/words_b1/rešpekt.jpg" },
      { sk: "uraziť sa", ua: "образитися", ru: "обидеться", img: "/words_b1/uraziť sa.jpg" },
      { sk: "zblížiť sa", ua: "зблизитися", ru: "сблизиться", img: "/words_b1/zblížiť sa.jpg" },
      { sk: "vzťah", ua: "стосунки", ru: "отношения", img: "/words_b1/vzťah.jpg" },
    ],
  },
  {
    id: "b1-6",
    title: { ua: "Урок 6 — Освіта та навчання", ru: "Урок 6 — Образование и обучение" },
    words: [
      { sk: "seminár", ua: "семінар", ru: "семинар", img: "/words_b1/seminár.jpg" },
      { sk: "zadanie", ua: "завдання", ru: "задание", img: "/words_b1/zadanie.jpg" },
      { sk: "hodnotenie", ua: "оцінювання", ru: "оценивание", img: "/words_b1/hodnotenie.jpg" },
      { sk: "sústredenie", ua: "концентрація", ru: "концентрация", img: "/words_b1/sústredenie.jpg" },
      { sk: "zlepšenie", ua: "покращення", ru: "улучшение", img: "/words_b1/zlepšenie.jpg" },
      { sk: "známka", ua: "оцінка (бал)", ru: "оценка (балл)", img: "/words_b1/známka.jpg" },
      { sk: "ročník", ua: "курс (рік навчання)", ru: "курс (год обучения)", img: "/words_b1/ročník.jpg" },
      { sk: "prednášať", ua: "читати лекцію", ru: "читать лекцию", img: "/words_b1/prednášať.jpg" },
      { sk: "vypracovať", ua: "опрацювати / виконати (завдання)", ru: "выполнить (задание)", img: "/words_b1/vypracovať.jpg" },
      { sk: "termín odovzdania", ua: "термін здачі", ru: "срок сдачи", img: "/words_b1/termín odovzdania.jpg" },
    ],
  },
  {
    id: "b1-7",
    title: { ua: "Урок 7 — Технології та інтернет", ru: "Урок 7 — Технологии и интернет" },
    words: [
      { sk: "nastavenie", ua: "налаштування", ru: "настройка", img: "/words_b1/nastavenie.jpg" },
      { sk: "heslo", ua: "пароль", ru: "пароль", img: "/words_b1/heslo.jpg" },
      { sk: "prihlásenie", ua: "вхід (логін)", ru: "вход (логин)", img: "/words_b1/prihlásenie.jpg" },
      { sk: "súkromie", ua: "приватність", ru: "приватность", img: "/words_b1/súkromie.jpg" },
      { sk: "nahrať", ua: "завантажити (на сайт)", ru: "загрузить (на сайт)", img: "/words_b1/nahrať.jpg" },
      { sk: "zdieľať", ua: "ділитися", ru: "делиться", img: "/words_b1/zdieľať.jpg" },
      { sk: "prehliadač", ua: "браузер", ru: "браузер", img: "/words_b1/prehliadač.jpg" },
      { sk: "aplikácia", ua: "додаток", ru: "приложение", img: "/words_b1/aplikácia.jpg" },
      { sk: "vyhľadávať", ua: "шукати (в інтернеті)", ru: "искать (в интернете)", img: "/words_b1/vyhľadávať.jpg" },
      { sk: "ochrana údajov", ua: "захист даних", ru: "защита данных", img: "/words_b1/ochrana údajov.jpg" },
    ],
  },
  {
    id: "b1-8",
    title: { ua: "Урок 8 — Фінанси та покупки", ru: "Урок 8 — Финансы и покупки" },
    words: [
      { sk: "splátka", ua: "платіж частинами", ru: "взнос (рассрочка)", img: "/words_b1/splátka.jpg" },
      { sk: "pokladničný doklad", ua: "чек", ru: "чек", img: "/words_b1/pokladničný doklad.jpg" },
      { sk: "predajca", ua: "продавець", ru: "продавец", img: "/words_b1/predajca.jpg" },
      { sk: "pôžička", ua: "позика", ru: "заём", img: "/words_b1/pôžička.jpg" },
      { sk: "úrok", ua: "відсоток (по кредиту)", ru: "процент (по кредиту)", img: "/words_b1/úrok.jpg" },
      { sk: "dlh", ua: "борг", ru: "долг", img: "/words_b1/dlh.jpg" },
      { sk: "výpis z účtu", ua: "виписка з рахунку", ru: "выписка со счёта", img: "/words_b1/výpis z účtu.jpg" },
      { sk: "zostatok", ua: "залишок (на рахунку)", ru: "остаток (на счёте)", img: "/words_b1/zostatok.jpg" },
      { sk: "zamietnuť", ua: "відхилити (заявку / кредит)", ru: "отклонить (заявку / кредит)", img: "/words_b1/zamietnuť.jpg" },
      { sk: "splatnosť", ua: "термін погашення", ru: "срок погашения", img: "/words_b1/splatnosť.jpg" },
    ],
  },
  {
    id: "b1-9",
    title: { ua: "Урок 9 — Дім: ремонти та послуги", ru: "Урок 9 — Дом: ремонты и услуги" },
    words: [
      { sk: "montáž", ua: "монтаж", ru: "монтаж", img: "/words_b1/montáž.jpg" },
      { sk: "technická podpora", ua: "техпідтримка", ru: "техподдержка", img: "/words_b1/technická podpora.jpg" },
      { sk: "údržba", ua: "обслуговування / догляд", ru: "обслуживание / уход", img: "/words_b1/údržba.jpg" },
      { sk: "objednať servis", ua: "замовити сервіс", ru: "заказать сервис", img: "/words_b1/objednať servis.jpg" },
      { sk: "zmluvný servis", ua: "офіційний сервіс", ru: "официальный сервис", img: "/words_b1/zmluvný servis.jpg" },
      { sk: "porucha zariadenia", ua: "поломка пристрою", ru: "поломка устройства", img: "/words_b1/porucha zariadenia.jpg" },
      { sk: "oprava na mieste", ua: "ремонт на місці", ru: "ремонт на месте", img: "/words_b1/oprava na mieste.jpg" },
      { sk: "zásah technika", ua: "виїзд майстра", ru: "выезд техника", img: "/words_b1/zásah technika.jpg" },
      { sk: "pracovný postup", ua: "робоча процедура", ru: "рабочая процедура", img: "/words_b1/pracovný postup.jpg" },
      { sk: "odstrániť chybu", ua: "усунути несправність", ru: "устранить неисправность", img: "/words_b1/odstrániť chybu.jpg" },
    ],
  },
  {
    id: "b1-10",
    title: { ua: "Урок 10 — Комунікація та медіа", ru: "Урок 10 — Коммуникация и медиа" },
    words: [
      { sk: "rozhovor", ua: "інтерв’ю / розмова", ru: "интервью / разговор", img: "/words_b1/rozhovor.jpg" },
      { sk: "reportáž", ua: "репортаж", ru: "репортаж", img: "/words_b1/reportáž.jpg" },
      { sk: "tlačová správa", ua: "пресреліз", ru: "пресс-релиз", img: "/words_b1/tlačová správa.jpg" },
      { sk: "sledovať", ua: "стежити / слідкувати", ru: "следить", img: "/words_b1/sledovať.jpg" },
      { sk: "ovplyvniť", ua: "вплинути", ru: "повлиять", img: "/words_b1/ovplyvniť.jpg" },
      { sk: "uveriteľný", ua: "достовірний", ru: "достоверный", img: "/words_b1/uveriteľný.jpg" },
      { sk: "informovať", ua: "інформувати", ru: "информировать", img: "/words_b1/informovať.jpg" },
      { sk: "vyjadriť názor", ua: "висловити думку", ru: "выразить мнение", img: "/words_b1/vyjadriť názor.jpg" },
      { sk: "komentár", ua: "коментар", ru: "комментарий", img: "/words_b1/komentár.jpg" },
      { sk: "verejnosť", ua: "громадськість", ru: "общественность", img: "/words_b1/verejnosť.jpg" },
    ],
  },
  {
    id: "b1-11",
    title: { ua: "Урок 11 — Природа та погода", ru: "Урок 11 — Природа и погода" },
    words: [
      { sk: "sucho", ua: "посуха", ru: "засуха", img: "/words_b1/sucho.jpg" },
      { sk: "povodeň", ua: "повінь", ru: "наводнение", img: "/words_b1/povodeň.jpg" },
      { sk: "klíma", ua: "клімат", ru: "климат", img: "/words_b1/klíma.jpg" },
      { sk: "oblačnosť", ua: "хмарність", ru: "облачность", img: "/words_b1/oblačnosť.jpg" },
      { sk: "lavína", ua: "лавина", ru: "лавина", img: "/words_b1/lavína.jpg" },
      { sk: "zemetrasenie", ua: "землетрус", ru: "землетрясение", img: "/words_b1/zemetrasenie.jpg" },
      { sk: "vlhkosť", ua: "вологість", ru: "влажность", img: "/words_b1/vlhkosť.jpg" },
      { sk: "topenie", ua: "танення", ru: "таяние", img: "/words_b1/topenie.jpg" },
      { sk: "záplava", ua: "затоплення", ru: "затопление", img: "/words_b1/záplava.jpg" },
      { sk: "prírodná katastrofa", ua: "природна катастрофа", ru: "природная катастрофа", img: "/words_b1/prírodná katastrofa.jpg" },
    ],
  },
  {
    id: "b1-12",
    title: { ua: "Урок 12 — У місті: адміністрація", ru: "Урок 12 — В городе: администрация" },
    words: [
      { sk: "prechodný pobyt", ua: "тимчасове проживання", ru: "временное проживание", img: "/words_b1/prechodný pobyt.jpg" },
      { sk: "vyhlásenie", ua: "заява / декларація", ru: "заявление / декларация", img: "/words_b1/vyhlásenie.jpg" },
      { sk: "overenie totožnosti", ua: "перевірка особи", ru: "проверка личности", img: "/words_b1/overenie totožnosti.jpg" },
      { sk: "zákonný", ua: "законний", ru: "законный", img: "/words_b1/zákonný.jpg" },
      { sk: "občianstvo", ua: "громадянство", ru: "гражданство", img: "/words_b1/občianstvo.jpg" },
      { sk: "povinnosť", ua: "обов’язок", ru: "обязанность", img: "/words_b1/povinnosť.jpg" },
      { sk: "oprávnenie", ua: "право / повноваження", ru: "право / полномочие", img: "/words_b1/oprávnenie.jpg" },
      { sk: "zápis", ua: "запис / внесення до реєстру", ru: "запись / внесение в реестр", img: "/words_b1/zápis.jpg" },
      { sk: "odvolanie", ua: "апеляція / оскарження", ru: "апелляция / обжалование", img: "/words_b1/odvolanie.jpg" },
      { sk: "úradný dokument", ua: "офіційний документ", ru: "официальный документ", img: "/words_b1/úradný dokument.jpg" },
    ],
  },
  {
    id: "b1-13",
    title: { ua: "Урок 13 — Послуги та клієнт", ru: "Урок 13 — Услуги и клиент" },
    words: [
      { sk: "ochota", ua: "готовність допомогти", ru: "готовность помочь", img: "/words_b1/ochota.jpg" },
      { sk: "zákazník", ua: "клієнт", ru: "клиент", img: "/words_b1/zákazník.jpg" },
      { sk: "poskytovať služby", ua: "надавати послуги", ru: "предоставлять услуги", img: "/words_b1/poskytovať služby.jpg" },
      { sk: "vybavenie požiadavky", ua: "обробка запиту", ru: "обработка запроса", img: "/words_b1/vybavenie požiadavky.jpg" },
      { sk: "spokojnosť", ua: "задоволеність", ru: "удовлетворенность", img: "/words_b1/spokojnosť.jpg" },
      { sk: "nespokojný", ua: "незадоволений", ru: "недовольный", img: "/words_b1/nespokojný.jpg" },
      { sk: "zodpovedať za", ua: "нести відповідальність за", ru: "нести ответственность за", img: "/words_b1/zodpovedať za.jpg" },
      { sk: "vyhovieť", ua: "задовольнити (вимогу)", ru: "удовлетворить (требование)", img: "/words_b1/vyhovieť.jpg" },
      { sk: "podpora zákazníkov", ua: "служба підтримки клієнтів", ru: "служба поддержки клиентов", img: "/words_b1/podpora zákazníkov.jpg" },
      { sk: "požiadavka", ua: "вимога / запит", ru: "требование / запрос", img: "/words_b1/požiadavka.jpg" },
    ],
  },
  {
    id: "b1-14",
    title: { ua: "Урок 14 — Харчування та звички", ru: "Урок 14 — Питание и привычки" },
    words: [
      { sk: "stravovanie", ua: "харчування", ru: "питание", img: "/words_b1/stravovanie.jpg" },
      { sk: "zloženie", ua: "склад", ru: "состав", img: "/words_b1/zloženie.jpg" },
      { sk: "porcia", ua: "порція", ru: "порция", img: "/words_b1/porcia.jpg" },
      { sk: "intolerancia", ua: "непереносимість", ru: "непереносимость", img: "/words_b1/intolerancia.jpg" },
      { sk: "návyk", ua: "звичка", ru: "привычка", img: "/words_b1/návyk.jpg" },
      { sk: "obmedziť", ua: "обмежити", ru: "ограничить", img: "/words_b1/obmedziť.jpg" },
      { sk: "vyvážená strava", ua: "збалансоване харчування", ru: "сбалансированное питание", img: "/words_b1/vyvážená strava.jpg" },
      { sk: "výživový doplnok", ua: "харчова добавка", ru: "пищевая добавка", img: "/words_b1/výživový doplnok.jpg" },
      { sk: "pravidelnosť", ua: "регулярність", ru: "регулярность", img: "/words_b1/pravidelnosť.jpg" },
      { sk: "zdravý životný štýl", ua: "здоровий спосіб життя", ru: "здоровый образ жизни", img: "/words_b1/zdravý životný štýl.jpg" },
    ],
  },
  {
    id: "b1-15",
    title: { ua: "Урок 15 — Спорт і форма", ru: "Урок 15 — Спорт и форма" },
    words: [
      { sk: "výdrž", ua: "витривалість", ru: "выносливость", img: "/words_b1/výdrž.jpg" },
      { sk: "sval", ua: "м’яз", ru: "мышца", img: "/words_b1/sval.jpg" },
      { sk: "rozohriatie", ua: "розігрів", ru: "разминка", img: "/words_b1/rozohriatie.jpg" },
      { sk: "strečing", ua: "розтяжка", ru: "растяжка", img: "/words_b1/strečing.jpg" },
      { sk: "životospráva", ua: "здоровий спосіб життя", ru: "здоровый образ жизни", img: "/words_b1/životospráva.jpg" },
      { sk: "kondícia", ua: "фізична форма", ru: "физическая форма", img: "/words_b1/kondícia.jpg" },
      { sk: "výkon", ua: "результат / продуктивність", ru: "результат / производительность", img: "/words_b1/výkon.jpg" },
      { sk: "zlepšiť výkon", ua: "покращити результат", ru: "улучшить результат", img: "/words_b1/zlepšiť výkon.jpg" },
      { sk: "preťaženie", ua: "перевантаження", ru: "перегрузка", img: "/words_b1/preťaženie.jpg" },
      { sk: "oddych", ua: "відпочинок", ru: "отдых", img: "/words_b1/oddych.jpg" },
    ],
  },
  {
    id: "b1-16",
    title: { ua: "Урок 16 — Культура та дозвілля", ru: "Урок 16 — Культура и досуг" },
    words: [
      { sk: "vkus", ua: "смак (уподобання)", ru: "вкус (предпочтения)", img: "/words_b1/vkus.jpg" },
      { sk: "recenzia", ua: "рецензія", ru: "рецензия", img: "/words_b1/recenzia.jpg" },
      { sk: "zážitok", ua: "враження", ru: "впечатление", img: "/words_b1/zážitok.jpg" },
      { sk: "vystúpenie", ua: "виступ", ru: "выступление", img: "/words_b1/vystúpenie.jpg" },
      { sk: "voľný čas", ua: "вільний час", ru: "свободное время", img: "/words_b1/voľný čas.jpg" },
      { sk: "účinkovať", ua: "виступати (брати участь)", ru: "выступать (принимать участие)", img: "/words_b1/účinkovať.jpg" },
      { sk: "navštíviť", ua: "відвідати", ru: "посетить", img: "/words_b1/navštíviť.jpg" },
      { sk: "premiéra", ua: "прем’єра", ru: "премьера", img: "/words_b1/výstava.jpg" },
      { sk: "program podujatia", ua: "програма заходу", ru: "программа мероприятия", img: "/words_b1/program podujatia.jpg" },
      { sk: "rezervácia miesta", ua: "бронювання місця", ru: "бронирование места", img: "/words_b1/rezervácia miesta.jpg" },
    ],
  },
  {
    id: "b1-17",
    title: { ua: "Урок 17 — Спорт", ru: "Урок 17 — Спорт" },
    words: [
      { sk: "tréning", ua: "тренування", ru: "тренировка", img: "/words_b1/tréning.jpg" },
      { sk: "zápas", ua: "матч", ru: "матч", img: "/words_b1/zápas.jpg" },
      { sk: "výhra", ua: "перемога", ru: "победа", img: "/words_b1/výhra.jpg" },
      { sk: "prehra", ua: "поразка", ru: "поражение", img: "/words_b1/prehra.jpg" },
      { sk: "rozhodca", ua: "суддя", ru: "судья", img: "/words_b1/rozhodca.jpg" },
      { sk: "súťaž", ua: "змагання", ru: "соревнование", img: "/words_b1/súťaž.jpg" },
      { sk: "divák", ua: "глядач", ru: "зритель", img: "/words_b1/divák.jpg" },
      { sk: "tím", ua: "команда", ru: "команда", img: "/words_b1/tím.jpg" },
      { sk: "výkon", ua: "результат / виступ", ru: "результат / выступление", img: "/words_b1/výkon.jpg" },
      { sk: "zranenie", ua: "травма", ru: "травма", img: "/words_b1/zranenie.jpg" }
    ]
  },
  {
    id: "b1-18",
    title: { ua: "Урок 18 — Географія", ru: "Урок 18 — География" },
    words: [
      { sk: "kontinent", ua: "континент", ru: "континент", img: "/words_b1/kontinent.jpg" },
      { sk: "hranica", ua: "кордон", ru: "граница", img: "/words_b1/hranica.jpg" },
      { sk: "obyvateľstvo", ua: "населення", ru: "население", img: "/words_b1/obyvateľstvo.jpg" },
      { sk: "podnebie", ua: "клімат", ru: "климат", img: "/words_b1/podnebie.jpg" },
      { sk: "hlavné mesto", ua: "столиця", ru: "столица", img: "/words_b1/hlavné mesto.jpg" },
      { sk: "povrch", ua: "поверхня", ru: "поверхность", img: "/words_b1/povrch.jpg" },
      { sk: "pobrežie", ua: "узбережжя", ru: "побережье", img: "/words_b1/pobrežie.jpg" },
      { sk: "ostrov", ua: "острів", ru: "остров", img: "/words_b1/ostrov.jpg" },
      { sk: "vnútrozemie", ua: "внутрішня територія", ru: "внутренняя территория", img: "/words_b1/vnútrozemie.jpg" },
      { sk: "zemepis", ua: "географія", ru: "география", img: "/words_b1/zemepis.jpg" }
    ]
  },
  {
    id: "b1-19",
    title: { ua: "Урок 19 — Математика", ru: "Урок 19 — Математика" },
    words: [
      { sk: "rovnica", ua: "рівняння", ru: "уравнение", img: "/words_b1/rovnica.jpg" },
      { sk: "výsledok", ua: "результат", ru: "результат", img: "/words_b1/výsledok.jpg" },
      { sk: "násobiť", ua: "множити", ru: "умножать", img: "/words_b1/násobiť.jpg" },
      { sk: "deliť", ua: "ділити", ru: "делить", img: "/words_b1/deliť.jpg" },
      { sk: "odčítať", ua: "віднімати", ru: "вычитать", img: "/words_b1/odčítať.jpg" },
      { sk: "sčítať", ua: "додавати", ru: "складывать", img: "/words_b1/sčítať.jpg" },
      { sk: "zlomok", ua: "дріб", ru: "дробь", img: "/words_b1/zlomok.jpg" },
      { sk: "percento", ua: "відсоток", ru: "процент", img: "/words_b1/percento.jpg" },
      { sk: "graf", ua: "графік", ru: "график", img: "/words_b1/graf.jpg" },
      { sk: "vypočítať", ua: "обчислити", ru: "вычислить", img: "/words_b1/vypočítať.jpg" }
    ]
  },
  {
    id: "b1-20",
    title: { ua: "Урок 20 — Держава та суспільство", ru: "Урок 20 — Государство и общество" },
    words: [
      { sk: "zákon", ua: "закон", ru: "закон", img: "/words_b1/zákon.jpg" },
      { sk: "voľby", ua: "вибори", ru: "выборы", img: "/words_b1/voľby.jpg" },
      { sk: "vláda", ua: "уряд", ru: "правительство", img: "/words_b1/vláda.jpg" },
      { sk: "občan", ua: "громадянин", ru: "гражданин", img: "/words_b1/občan.jpg" },
      { sk: "parlament", ua: "парламент", ru: "парламент", img: "/words_b1/parlament.jpg" },
      { sk: "prezident", ua: "президент", ru: "президент", img: "/words_b1/prezident.jpg" },
      { sk: "ústava", ua: "конституція", ru: "конституция", img: "/words_b1/ústava.jpg" },
      { sk: "ministerstvo", ua: "міністерство", ru: "министерство", img: "/words_b1/ministerstvo.jpg" },
      { sk: "referendum", ua: "референдум", ru: "референдум", img: "/words_b1/referendum.jpg" },
      { sk: "štátna správa", ua: "державне управління", ru: "государственное управление", img: "/words_b1/štátna správa.jpg" }
    ]
  },
  {
    id: "b1-21",
    title: { ua: "Урок 21 — Країни", ru: "Урок 21 — Страны" },
    words: [
      { sk: "Slovensko", ua: "Словаччина", ru: "Словакия", img: "/words_b1/Slovensko.jpg" },
      { sk: "Česko", ua: "Чехія", ru: "Чехия", img: "/words_b1/Česko.jpg" },
      { sk: "Poľsko", ua: "Польща", ru: "Польша", img: "/words_b1/Poľsko.jpg" },
      { sk: "Nemecko", ua: "Німеччина", ru: "Германия", img: "/words_b1/Nemecko.jpg" },
      { sk: "Rakúsko", ua: "Австрія", ru: "Австрия", img: "/words_b1/Rakúsko.jpg" },
      { sk: "Maďarsko", ua: "Угорщина", ru: "Венгрия", img: "/words_b1/Maďarsko.jpg" },
      { sk: "Francúzsko", ua: "Франція", ru: "Франция", img: "/words_b1/Francúzsko.jpg" },
      { sk: "Taliansko", ua: "Італія", ru: "Италия", img: "/words_b1/Taliansko.jpg" },
      { sk: "Španielsko", ua: "Іспанія", ru: "Испания", img: "/words_b1/Španielsko.jpg" },
      { sk: "Ukrajina", ua: "Україна", ru: "Украина", img: "/words_b1/Ukrajina.jpg" }
    ]
  },
  {
    id: "b1-22",
    title: { ua: "Урок 22 — Медіа та інформація", ru: "Урок 22 — СМИ и информация" },
    words: [
      { sk: "tlač", ua: "преса", ru: "пресса", img: "/words_b1/tlač.jpg" },
      { sk: "noviny", ua: "газети", ru: "газеты", img: "/words_b1/noviny.jpg" },
      { sk: "televízia", ua: "телебачення", ru: "телевидение", img: "/words_b1/televízia.jpg" },
      { sk: "rozhlas", ua: "радіо (офіц.)", ru: "радио", img: "/words_b1/rozhlas.jpg" },
      { sk: "vysielanie", ua: "трансляція", ru: "вещание", img: "/words_b1/vysielanie.jpg" },
      { sk: "reklama", ua: "реклама", ru: "реклама", img: "/words_b1/reklama.jpg" },
      { sk: "redaktor", ua: "редактор / журналіст", ru: "редактор / журналист", img: "/words_b1/redaktor.jpg" },
      { sk: "titulok", ua: "заголовок", ru: "заголовок", img: "/words_b1/titulok.jpg" },
      { sk: "uveriť", ua: "повірити", ru: "поверить", img: "/words_b1/uveriť.jpg" },
      { sk: "verejná myšlienka", ua: "громадська думка", ru: "общественное мнение", img: "/words_b1/verejná myšlienka.jpg" }
    ]
  },
  {
    id: "b1-23",
    title: { ua: "Урок 23 — Інтернет та соцмережі", ru: "Урок 23 — Интернет и соцсети" },
    words: [
      { sk: "webová stránka", ua: "вебсайт", ru: "веб-сайт", img: "/words_b1/webová stránka.jpg" },
      { sk: "sledovateľ", ua: "підписник", ru: "подписчик", img: "/words_b1/sledovateľ.jpg" },
      { sk: "online", ua: "онлайн", ru: "онлайн", img: "/words_b1/online.jpg" },
      { sk: "offline", ua: "офлайн", ru: "офлайн", img: "/words_b1/offline.jpg" },
      { sk: "profil", ua: "профіль", ru: "профиль", img: "/words_b1/profil.jpg" },
      { sk: "komentovať", ua: "коментувати", ru: "комментировать", img: "/words_b1/komentovať.jpg" },
      { sk: "označiť", ua: "позначити / тегнути", ru: "отметить / тегнуть", img: "/words_b1/označiť.jpg" },
      { sk: "zdieľať", ua: "поширювати", ru: "делиться", img: "/words_b1/zdieľať.jpg" },
      { sk: "správa", ua: "повідомлення", ru: "сообщение", img: "/words_b1/správa.jpg" },
      { sk: "upozornenie", ua: "сповіщення", ru: "уведомление", img: "/words_b1/upozornenie.jpg" }
    ]
  },
  {
    id: "b1-24",
    title: { ua: "Урок 24 — У гостях", ru: "Урок 24 — В гостях" },
    words: [
      { sk: "pozvanie", ua: "запрошення", ru: "приглашение", img: "/words_b1/pozvanie.jpg" },
      { sk: "hostiteľ", ua: "господар", ru: "хозяин", img: "/words_b1/hostiteľ.jpg" },
      { sk: "hosť", ua: "гість", ru: "гость", img: "/words_b1/hosť.jpg" },
      { sk: "pohostenie", ua: "частування", ru: "угощение", img: "/words_b1/pohostenie.jpg" },
      { sk: "priniesť darček", ua: "принести подарунок", ru: "принести подарок", img: "/words_b1/priniesť darček.jpg" },
      { sk: "slušnosť", ua: "ввічливість", ru: "вежливость", img: "/words_b1/slušnosť.jpg" },
      { sk: "privítať", ua: "привітати (зустріти)", ru: "поприветствовать (встретить)", img: "/words_b1/privítať.jpg" },
      { sk: "ponúknuť", ua: "запропонувати (частування)", ru: "предложить (угощение)", img: "/words_b1/ponúknuť.jpg" },
      { sk: "poďakovať sa", ua: "подякувати", ru: "поблагодарить", img: "/words_b1/poďakovať sa.jpg" },
      { sk: "rozlúčiť sa", ua: "попрощатися", ru: "попрощаться", img: "/words_b1/rozlúčiť sa.jpg" },
    ],
  },
  {
    id: "b1-25",
    title: { ua: "Урок 25 — Емоції та внутрішній стан", ru: "Урок 25 — Эмоции и внутреннее состояние" },
    words: [
      { sk: "sklamanie", ua: "розчарування", ru: "разочарование", img: "/words_b1/sklamanie.jpg" },
      { sk: "hrdosť", ua: "гордість", ru: "гордость", img: "/words_b1/hrdosť.jpg" },
      { sk: "úľava", ua: "полегшення", ru: "облегчение", img: "/words_b1/úľava.jpg" },
      { sk: "neistota", ua: "невпевненість", ru: "неуверенность", img: "/words_b1/neistota.jpg" },
      { sk: "frustrácia", ua: "фрустрація", ru: "фрустрация", img: "/words_b1/frustrácia.jpg" },
      { sk: "pochybnosť", ua: "сумнів", ru: "сомнение", img: "/words_b1/pochybnosť.jpg" },
      { sk: "obava", ua: "побоювання", ru: "опасение", img: "/words_b1/obava.jpg" },
      { sk: "spokojnosť", ua: "задоволення", ru: "удовлетворение", img: "/words_b1/spokojnosť.jpg" },
      { sk: "bezmocnosť", ua: "безсилля", ru: "бессилие", img: "/words_b1/bezmocnosť.jpg" },
      { sk: "vyčerpanie", ua: "виснаження", ru: "истощение", img: "/words_b1/vyčerpanie.jpg" },
    ],
  },
  {
    id: "b1-26",
    title: { ua: "Урок 26 — Суспільство та взаємини", ru: "Урок 26 — Общество и взаимоотношения" },
    words: [
      { sk: "porozumenie", ua: "розуміння", ru: "понимание", img: "/words_b1/porozumenie.jpg" },
      { sk: "solidarita", ua: "солідарність", ru: "солидарность", img: "/words_b1/solidarita.jpg" },
      { sk: "konflikt", ua: "конфлікт", ru: "конфликт", img: "/words_b1/konflikt.jpg" },
      { sk: "predsudok", ua: "упередження", ru: "предрассудок", img: "/words_b1/predsudok.jpg" },
      { sk: "rovnosť", ua: "рівність", ru: "равенство", img: "/words_b1/rovnosť.jpg" },
      { sk: "tolerancia", ua: "толерантність", ru: "толерантность", img: "/words_b1/tolerancia.jpg" },
      { sk: "diskriminácia", ua: "дискримінація", ru: "дискриминация", img: "/words_b1/diskriminácia.jpg" },
      { sk: "spolužitie", ua: "співжиття", ru: "сосуществование", img: "/words_b1/spolužitie.jpg" },
      { sk: "dôvera", ua: "довіра", ru: "доверие", img: "/words_b1/dôvera.jpg" },
      { sk: "kompromis", ua: "компроміс", ru: "компромисс", img: "/words_b1/kompromis.jpg" },
    ],
  },
  {
    id: "b1-27",
    title: { ua: "Урок 27 — Робота (безпека і правила)", ru: "Урок 27 — Работа (безопасность и правила)" },
    words: [
      { sk: "bezpečnosť práce", ua: "охорона праці", ru: "охрана труда", img: "/words_b1/bezpečnosť práce.jpg" },
      { sk: "ochranné pomôcky", ua: "засоби захисту", ru: "средства защиты", img: "/words_b1/ochranné pomôcky.jpg" },
      { sk: "povinné", ua: "обов’язкове", ru: "обязательное", img: "/words_b1/povinné.jpg" },
      { sk: "zakázané", ua: "заборонене", ru: "запрещено", img: "/words_b1/zakázané.jpg" },
      { sk: "školenie", ua: "інструктаж", ru: "инструктаж", img: "/words_b1/školenie.jpg" },
      { sk: "dodržiavať", ua: "дотримуватися", ru: "соблюдать", img: "/words_b1/dodržiavať.jpg" },
      { sk: "pracovný úraz", ua: "виробнича травма", ru: "производственная травма", img: "/words_b1/pracovný úraz.jpg" },
      { sk: "bezpečnostné pravidlá", ua: "правила безпеки", ru: "правила безопасности", img: "/words_b1/bezpečnostné pravidlá.jpg" },
      { sk: "dohľad", ua: "нагляд", ru: "надзор", img: "/words_b1/dohľad.jpg" },
      { sk: "upozornenie", ua: "попередження", ru: "предупреждение", img: "/words_b1/upozorneniee.jpg" },
    ],
  },
  {
    id: "b1-28",
    title: { ua: "Урок 28 — Розповідь (послідовність)", ru: "Урок 28 — Рассказ (последовательность)" },
    words: [
      { sk: "najprv", ua: "спочатку", ru: "сначала", img: "/words_b1/najprv.jpg" },
      { sk: "potom", ua: "потім", ru: "потом", img: "/words_b1/potom.jpg" },
      { sk: "následne", ua: "далі", ru: "затем", img: "/words_b1/následne.jpg" },
      { sk: "medzitým", ua: "тим часом", ru: "тем временем", img: "/words_b1/medzitým.jpg" },
      { sk: "nakoniec", ua: "врешті", ru: "в конце", img: "/words_b1/nakoniec.jpg" },
      { sk: "zrazu", ua: "раптом", ru: "вдруг", img: "/words_b1/zrazu.jpg" },
      { sk: "napokon", ua: "зрештою", ru: "в итоге", img: "/words_b1/napokon.jpg" },
      { sk: "vtedy", ua: "тоді", ru: "тогда", img: "/words_b1/vtedy.jpg" },
      { sk: "odvtedy", ua: "відтоді", ru: "с тех пор", img: "/words_b1/odvtedy.jpg" },
      { sk: "dovtedy", ua: "до того времени", ru: "до того времени", img: "/words_b1/dovtedy.jpg" },
    ],
  },
  {
    id: "b1-29",
    title: { ua: "Урок 29 — Конфлікти (як говорити спокійно)", ru: "Урок 29 — Конфликты (как говорить спокойно)" },
    words: [
      { sk: "nepríjemné", ua: "неприємно", ru: "неприятно", img: "/words_b1/nepríjemné.jpg" },
      { sk: "uraziť", ua: "образити", ru: "обидеть", img: "/words_b1/uraziť.jpg" },
      { sk: "kritizovať", ua: "критикувати", ru: "критиковать", img: "/words_b1/kritizovať.jpg" },
      { sk: "vyjadriť sa", ua: "висловитися", ru: "высказаться", img: "/words_b1/vyjadriť sa.jpg" },
      { sk: "vysvetlenie", ua: "пояснення", ru: "объяснение", img: "/words_b1/vysvetlenie.jpg" },
      { sk: "ospravedlnenie", ua: "вибачення", ru: "извинение", img: "/words_b1/ospravedlnenie.jpg" },
      { sk: "pochopiť", ua: "зрозуміти", ru: "понять", img: "/words_b1/pochopiť.jpg" },
      { sk: "zachovať pokoj", ua: "зберігати спокій", ru: "сохранять спокойствие", img: "/words_b1/zachovať pokoj.jpg" },
      { sk: "ustúpiť", ua: "поступитися", ru: "уступить", img: "/words_b1/ustúpiť.jpg" },
      { sk: "urovnať", ua: "уладнати", ru: "уладить", img: "/words_b1/urovnať.jpg" },
    ],
  },
  {
    id: "b1-30",
    title: { ua: "Урок 30 — Мова (фрази для розмови)", ru: "Урок 30 — Язык (фразы для разговора)" },
    words: [
      { sk: "ak tomu rozumiem správne", ua: "якщо я правильно розумію", ru: "если я правильно понимаю", img: "/words_b1/ak tomu rozumiem správne.jpg" },
      { sk: "inými slovami", ua: "іншими словами", ru: "другими словами", img: "/words_b1/inými slovami.jpg" },
      { sk: "na druhej strane", ua: "з іншого боку", ru: "с другой стороны", img: "/words_b1/na druhej strane.jpg" },
      { sk: "v každom prípade", ua: "в будь-якому разі", ru: "в любом случае", img: "/words_b1/v každom prípade.jpg" },
      { sk: "záleží na tom", ua: "залежить від цього", ru: "это зависит", img: "/words_b1/záleží na tom.jpg" },
      { sk: "mám pocit, že", ua: "мені здається, що", ru: "мне кажется, что", img: "/words_b1/mám pocit, že.jpg" },
      { sk: "neviem presne", ua: "не знаю точно", ru: "не знаю точно", img: "/words_b1/neviem presne.jpg" },
      { sk: "to dáva zmysel", ua: "це має сенс", ru: "это имеет смысл", img: "/words_b1/to dáva zmysel.jpg" },
      { sk: "to je zaujímavé", ua: "це цікаво", ru: "это интересно", img: "/words_b1/to je zaujímavé.jpg" },
      { sk: "poďme ďalej", ua: "йдемо далі", ru: "пойдём дальше", img: "/words_b1/poďme ďalej.jpg" },
    ],
  },
  {
    id: "b1-31",
    title: { ua: "Урок 31 — Країни (світ)", ru: "Урок 31 — Страны (мир)" },
    words: [
      { sk: "Spojené štáty", ua: "США", ru: "США", img: "/words_b1/Spojené štáty.jpg" },
      { sk: "Veľká Británia", ua: "Велика Британія", ru: "Великобритания", img: "/words_b1/Veľká Británia.jpg" },
      { sk: "Kanada", ua: "Канада", ru: "Канада", img: "/words_b1/Kanada.jpg" },
      { sk: "Švajčiarsko", ua: "Швейцарія", ru: "Швейцария", img: "/words_b1/Švajčiarsko.jpg" },
      { sk: "Holandsko", ua: "Нідерланди", ru: "Нидерланды", img: "/words_b1/Holandsko.jpg" },
      { sk: "Belgicko", ua: "Бельгія", ru: "Бельгия", img: "/words_b1/Belgicko.jpg" },
      { sk: "Švédsko", ua: "Швеція", ru: "Швеция", img: "/words_b1/Švédsko.jpg" },
      { sk: "Rusko", ua: "Росія", ru: "Россия", img: "/words_b1/Rusko.jpg" },
      { sk: "Rumunsko", ua: "Румунія", ru: "Румыния", img: "/words_b1/Rumunsko.jpg" },
      { sk: "Bulharsko", ua: "Болгарія", ru: "Болгария", img: "/words_b1/Bulharsko.jpg" }
    ],
  },
  {
    id: "b1-32",
    title: { ua: "Урок 32 — Релігія (Християнство)", ru: "Урок 32 — Религия (Христианство)" },
    words: [
      { sk: "kresťanstvo", ua: "християнство", ru: "христианство", img: "/words_b1/kresťanstvo.jpg" },
      { sk: "Boh", ua: "Бог", ru: "Бог", img: "/words_b1/Boh.jpg" },
      { sk: "Ježiš Kristus", ua: "Ісус Христос", ru: "Иисус Христос", img: "/words_b1/Ježiš Kristus.jpg" },
      { sk: "Biblia", ua: "Біблія", ru: "Библия", img: "/words_b1/Biblia.jpg" },
      { sk: "cirkev", ua: "церква", ru: "церковь", img: "/words_b1/cirkev.jpg" },
      { sk: "modlitba", ua: "молитва", ru: "молитва", img: "/words_b1/modlitba.jpg" },
      { sk: "viera", ua: "віра", ru: "вера", img: "/words_b1/viera.jpg" },
      { sk: "hriech", ua: "гріх", ru: "грех", img: "/words_b1/hriech.jpg" },
      { sk: "odpustenie", ua: "прощення", ru: "прощение", img: "/words_b1/odpustenie.jpg" },
      { sk: "večný život", ua: "вічне життя", ru: "вечная жизнь", img: "/words_b1/večný život.jpg" }
    ],
  },
  {
    id: "b1-33",
    title: { ua: "Урок 33 — Мова (спілкування і думки)", ru: "Урок 33 — Язык (общение и мысли)" },
    words: [
      { sk: "dialóg", ua: "діалог", ru: "диалог", img: "/words_b1/dialóg.jpg" },
      { sk: "tvrdenie", ua: "твердження", ru: "утверждение", img: "/words_b1/tvrdenie.jpg" },
      { sk: "odsek", ua: "абзац", ru: "абзац", img: "/words_b1/odsek.jpg" },
      { sk: "nadpis", ua: "заголовок", ru: "заголовок", img: "/words_b1/nadpis.jpg" },
      { sk: "citát", ua: "цитата", ru: "цитата", img: "/words_b1/citát.jpg" },
      { sk: "poznámka", ua: "примітка", ru: "заметка", img: "/words_b1/poznámka.jpg" },
      { sk: "skratka", ua: "скорочення", ru: "сокращение", img: "/words_b1/skratka.jpg" },
      { sk: "pravopis", ua: "правопис", ru: "правописание", img: "/words_b1/pravopis.jpg" },
      { sk: "spojiť slová", ua: "поєднати слова", ru: "соединить слова", img: "/words_b1/spojiť slová.jpg" },
      { sk: "vysloviť", ua: "вимовити", ru: "произнести", img: "/words_b1/vysloviť.jpg" }
    ],
  },
  {
    id: "b1-34",
    title: { ua: "Урок 34 — Психологія та внутрішній стан", ru: "Урок 34 — Психология и внутреннее состояние" },
    words: [
      { sk: "sebavedomie", ua: "самовпевненість", ru: "уверенность в себе", img: "/words_b1/sebavedomie.jpg" },
      { sk: "motivácia", ua: "мотивація", ru: "мотивация", img: "/words_b1/motivácia.jpg" },
      { sk: "rozhodnosť", ua: "рішучість", ru: "решительность", img: "/words_b1/rozhodnosť.jpg" },
      { sk: "sklamať sa", ua: "розчаруватися", ru: "разочароваться", img: "/words_b1/sklamať sa.jpg" },
      { sk: "prekonať strach", ua: "подолати страх", ru: "преодолеть страх", img: "/words_b1/prekonať strach.jpg" },
      { sk: "sebarozvoj", ua: "саморозвиток", ru: "саморазвитие", img: "/words_b1/sebarozvoj.jpg" },
      { sk: "vnútorný pokoj", ua: "внутрішній спокій", ru: "внутреннее спокойствие", img: "/words_b1/vnútorný pokoj.jpg" },
      { sk: "sebadisciplína", ua: "самодисципліна", ru: "самодисциплина", img: "/words_b1/sebadisciplína.jpg" },
      { sk: "odolnosť", ua: "стійкість", ru: "устойчивость", img: "/words_b1/odolnosť.jpg" },
      { sk: "vyrovnať sa s problémom", ua: "впоратися з проблемою", ru: "справиться с проблемой", img: "/words_b1/vyrovnať sa s problémom.jpg" }
    ],
  },
  {
    id: "b1-35",
    title: { ua: "Урок 35 — Столиці", ru: "Урок 35 — Столицы" },
    words: [
      { sk: "Kyjev", ua: "Київ", ru: "Киев", img: "/words_b1/Kyjev.jpg" },
      { sk: "Londýn", ua: "Лондон", ru: "Лондон", img: "/words_b1/Londýn.jpg" },
      { sk: "Ottawa", ua: "Оттава", ru: "Оттава", img: "/words_b1/Ottawa.jpg" },
      { sk: "Bern", ua: "Берн", ru: "Берн", img: "/words_b1/Bern.jpg" },
      { sk: "Amsterdam", ua: "Амстердам", ru: "Амстердам", img: "/words_b1/Amsterdam.jpg" },
      { sk: "Brusel", ua: "Брюссель", ru: "Брюссель", img: "/words_b1/Brusel.jpg" },
      { sk: "Štokholm", ua: "Стокгольм", ru: "Стокгольм", img: "/words_b1/Štokholm.jpg" },
      { sk: "Moskva", ua: "Москва", ru: "Москва", img: "/words_b1/Moskva.jpg" },
      { sk: "Bukurešť", ua: "Бухарест", ru: "Бухарест", img: "/words_b1/Bukurešť.jpg" },
      { sk: "Sofia", ua: "Софія", ru: "София", img: "/words_b1/Sofia.jpg" }
    ],
  },
]