import type { Lesson } from "../data";

export const B2_ALL: Lesson[] = [
    {
        id: "b2-1",
        title: { ua: "Урок 1 — Переговори та домовленості", ru: "Урок 1 — Переговоры и договорённости" },
        words: [
            { sk: "rokovanie", ua: "переговори", ru: "переговоры", img: "/words_b2/rokovanie.jpg" },
            { sk: "dohoda", ua: "домовленість / угода", ru: "договорённость / соглашение", img: "/words_b2/dohoda.jpg" },
            { sk: "podmienka", ua: "умова", ru: "условие", img: "/words_b2/podmienka.jpg" },
            { sk: "ústupok", ua: "поступка / компромісний крок", ru: "уступка / компромиссный шаг", img: "/words_b2/ústupok.jpg" },
            { sk: "stanovisko", ua: "позиція / точка зору", ru: "позиция / точка зрения", img: "/words_b2/stanovisko.jpg" },
            { sk: "presadiť", ua: "просунути / відстояти", ru: "продвинуть / отстоять", img: "/words_b2/presadiť.jpg" },
            { sk: "namietať", ua: "заперечувати", ru: "возражать", img: "/words_b2/namietať.jpg" },
            { sk: "prijať návrh", ua: "прийняти пропозицію", ru: "принять предложение", img: "/words_b2/prijať návrh.jpg" },
            { sk: "odmietnuť návrh", ua: "відхилити пропозицію", ru: "отклонить предложение", img: "/words_b2/odmietnuť návrh.jpg" },
            { sk: "kompromis", ua: "компроміс", ru: "компромисс", img: "/words_b2/kompromis.jpg" },
        ],
    },
    {
        id: "b2-2",
        title: { ua: "Урок 2 — Відповідальність і рішення", ru: "Урок 2 — Ответственность и решения" },
        words: [
            { sk: "zodpovednosť", ua: "відповідальність", ru: "ответственность", img: "/words_b2/zodpovednosť.jpg" },
            { sk: "rozhodnutie", ua: "рішення", ru: "решение", img: "/words_b2/rozhodnutie.jpg" },
            { sk: "dôsledok", ua: "наслідок", ru: "последствие", img: "/words_b2/dôsledok.jpg" },
            { sk: "posúdiť", ua: "оцінити / розглянути", ru: "оценить / рассмотреть", img: "/words_b2/posúdiť.jpg" },
            { sk: "zvážiť", ua: "зважити / обдумати", ru: "взвесить / обдумать", img: "/words_b2/zvážiť.jpg" },
            { sk: "riziko", ua: "ризик", ru: "риск", img: "/words_b2/riziko.jpg" },
            { sk: "následne", ua: "згодом / унаслідок цього", ru: "впоследствии / вследствие этого", img: "/words_b2/následne.jpg" },
            { sk: "prevziať zodpovednosť", ua: "взяти відповідальність", ru: "взять ответственность", img: "/words_b2/prevziať zodpovednosť.jpg" },
            { sk: "dospieť k záveru", ua: "дійти висновку", ru: "прийти к выводу", img: "/words_b2/dospieť k záveru.jpg" },
            { sk: "jednoznačný", ua: "однозначний / чіткий", ru: "однозначный / чёткий", img: "/words_b2/jednoznačný.jpg" },
        ],
    },
    {
        id: "b2-3",
        title: { ua: "Урок 3 — Конфлікти та аргументація", ru: "Урок 3 — Конфликты и аргументация" },
        words: [
            { sk: "spor", ua: "суперечка / спір", ru: "спор / конфликт", img: "/words_b2/spor.jpg" },
            { sk: "napätie", ua: "напруга", ru: "напряжение", img: "/words_b2/napätie.jpg" },
            { sk: "zmierniť", ua: "пом’якшити", ru: "смягчить", img: "/words_b2/zmierniť.jpg" },
            { sk: "vyhrotiť sa", ua: "загостритися", ru: "обостриться", img: "/words_b2/vyhrotiť sa.jpg" },
            { sk: "obhájiť", ua: "захистити / обґрунтувати", ru: "защитить / обосновать", img: "/words_b2/obhájiť.jpg" },
            { sk: "tvrdenie", ua: "твердження", ru: "утверждение", img: "/words_b2/tvrdenie.jpg" },
            { sk: "dôkaz", ua: "доказ", ru: "доказательство", img: "/words_b2/dôkaz.jpg" },
            { sk: "protiargument", ua: "контраргумент", ru: "контраргумент", img: "/words_b2/protiargument.jpg" },
            { sk: "presvedčivý", ua: "переконливий", ru: "убедительный", img: "/words_b2/presvedčivý.jpg" },
            { sk: "nezhoda", ua: "розбіжність / незгода", ru: "разногласие / несогласие", img: "/words_b2/nezhoda.jpg" },
        ],
    },
    {
        id: "b2-4",
        title: { ua: "Урок 4 — Формальна комунікація", ru: "Урок 4 — Формальная коммуникация" },
        words: [
            { sk: "zdvorilý", ua: "ввічливий", ru: "вежливый", img: "/words_b2/zdvorilý.jpg" },
            { sk: "formulovať", ua: "формулювати", ru: "формулировать", img: "/words_b2/formulovať.jpg" },
            { sk: "zaujať stanovisko", ua: "зайняти позицію", ru: "занять позицию", img: "/words_b2/zaujať stanovisko.jpg" },
            { sk: "predložiť žiadosť", ua: "подати запит / заяву", ru: "подать запрос / заявление", img: "/words_b2/predložiť žiadosť.jpg" },
            { sk: "upresniť", ua: "уточнити", ru: "уточнить", img: "/words_b2/upresniť.jpg" },
            { sk: "zdôrazniť", ua: "підкреслити / наголосити", ru: "подчеркнуть", img: "/words_b2/zdôrazniť.jpg" },
            { sk: "doplniť informáciu", ua: "доповнити інформацію", ru: "дополнить информацию", img: "/words_b2/doplniť informáciu.jpg" },
            { sk: "uviesť príklad", ua: "навести приклад", ru: "привести пример", img: "/words_b2/uviesť príklad.jpg" },
            { sk: "stručný", ua: "короткий / стислий", ru: "краткий", img: "/words_b2/stručný.jpg" },
            { sk: "jasne formulovaný", ua: "чітко сформульований", ru: "чётко сформулированный", img: "/words_b2/jasne formulovaný.jpg" },
        ],
    },
    {
        id: "b2-5",
        title: { ua: "Урок 5 — Скарги та рекламації", ru: "Урок 5 — Жалобы и рекламации" },
        words: [
            { sk: "nedostatok", ua: "недолік / дефект", ru: "недостаток / дефект", img: "/words_b2/nedostatok.jpg" },
            { sk: "vada", ua: "вада / дефект", ru: "дефект", img: "/words_b2/vada.jpg" },
            { sk: "uplatniť reklamáciu", ua: "подати рекламацію", ru: "подать рекламацию", img: "/words_b2/uplatniť reklamáciu.jpg" },
            { sk: "vybaviť reklamáciu", ua: "розглянути рекламацію", ru: "рассмотреть рекламацию", img: "/words_b2/vybaviť reklamáciu.jpg" },
            { sk: "odstrániť chybu", ua: "усунути помилку / дефект", ru: "устранить дефект", img: "/words_b2/odstrániť chybu.jpg" },
            { sk: "nárok", ua: "право на вимогу", ru: "право требования", img: "/words_b2/nárok.jpg" },
            { sk: "oprávnený nárok", ua: "обґрунтована вимога", ru: "обоснованное требование", img: "/words_b2/oprávnený nárok.jpg" },
            { sk: "zodpovedná osoba", ua: "відповідальна особа", ru: "ответственное лицо", img: "/words_b2/zodpovedná osoba.jpg" },
            { sk: "vyjadrenie spoločnosti", ua: "позиція компанії", ru: "позиция компании", img: "/words_b2/vyjadrenie spoločnosti.jpg" },
            { sk: "opodstatnený", ua: "обґрунтований", ru: "обоснованный", img: "/words_b2/opodstatnený.jpg" },
        ],
    },
    {
        id: "b2-6",
        title: { ua: "Урок 6 — Контракти та умови", ru: "Урок 6 — Контракты и условия" },
        words: [
            { sk: "zmluva", ua: "договір", ru: "договор", img: "/words_b2/zmluva.jpg" },
            { sk: "ustanovenie", ua: "положення", ru: "положение", img: "/words_b2/ustanovenie.jpg" },
            { sk: "platnosť", ua: "дійсність / чинність", ru: "действительность", img: "/words_b2/platnosť.jpg" },
            { sk: "záväzok", ua: "зобов'язання", ru: "обязательство", img: "/words_b2/záväzok.jpg" },
            { sk: "porušiť zmluvu", ua: "порушити договір", ru: "нарушить договор", img: "/words_b2/porušiť zmluvu.jpg" },
            { sk: "podpísať zmluvu", ua: "підписати договір", ru: "подписать договор", img: "/words_b2/podpísať zmluvu.jpg" },
            { sk: "dohodnutý", ua: "узгоджений", ru: "согласованный", img: "/words_b2/dohodnutý.jpg" },
            { sk: "lehota", ua: "термін", ru: "срок", img: "/words_b2/lehota.jpg" },
            { sk: "splniť podmienky", ua: "виконати умови", ru: "выполнить условия", img: "/words_b2/splniť podmienky.jpg" },
            { sk: "zmluvná strana", ua: "сторона договору", ru: "сторона договора", img: "/words_b2/zmluvná strana.jpg" },
        ],
    },
    {
        id: "b2-7",
        title: { ua: "Урок 7 — Планування та стратегія", ru: "Урок 7 — Планирование и стратегия" },
        words: [
            { sk: "stratégia", ua: "стратегія", ru: "стратегия", img: "/words_b2/stratégia.jpg" },
            { sk: "plánovanie", ua: "планування", ru: "планирование", img: "/words_b2/plánovanie.jpg" },
            { sk: "stanoviť cieľ", ua: "поставити мету", ru: "поставить цель", img: "/words_b2/stanoviť cieľ.jpg" },
            { sk: "dlhodobý", ua: "довгостроковий", ru: "долгосрочный", img: "/words_b2/dlhodobý.jpg" },
            { sk: "krátkodobý", ua: "короткостроковий", ru: "краткосрочный", img: "/words_b2/krátkodobý.jpg" },
            { sk: "postup", ua: "процедура / хід", ru: "процедура", img: "/words_b2/postup.jpg" },
            { sk: "priorita", ua: "пріоритет", ru: "приоритет", img: "/words_b2/priorita.jpg" },
            { sk: "efektívny", ua: "ефективний", ru: "эффективный", img: "/words_b2/efektívny.jpg" },
            { sk: "optimalizovať", ua: "оптимізувати", ru: "оптимизировать", img: "/words_b2/optimalizovať.jpg" },
            { sk: "realizovať plán", ua: "реалізувати план", ru: "реализовать план", img: "/words_b2/realizovať plán.jpg" },
        ],
    },
    {
        id: "b2-8",
        title: { ua: "Урок 8 — Аналіз і оцінка", ru: "Урок 8 — Анализ и оценка" },
        words: [
            { sk: "analýza", ua: "аналіз", ru: "анализ", img: "/words_b2/analýza.jpg" },
            { sk: "hodnotenie", ua: "оцінка", ru: "оценка", img: "/words_b2/hodnotenie.jpg" },
            { sk: "porovnať", ua: "порівняти", ru: "сравнить", img: "/words_b2/porovnať.jpg" },
            { sk: "výsledok", ua: "результат", ru: "результат", img: "/words_b2/výsledok.jpg" },
            { sk: "ukazovateľ", ua: "показник", ru: "показатель", img: "/words_b2/ukazovateľ.jpg" },
            { sk: "trend", ua: "тенденція", ru: "тенденция", img: "/words_b2/trend.jpg" },
            { sk: "významný", ua: "значний", ru: "значительный", img: "/words_b2/významný.jpg" },
            { sk: "zanedbateľný", ua: "незначний", ru: "незначительный", img: "/words_b2/zanedbateľný.jpg" },
            { sk: "objektívny", ua: "об'єктивний", ru: "объективный", img: "/words_b2/objektívny.jpg" },
            { sk: "subjektívny", ua: "суб'єктивний", ru: "субъективный", img: "/words_b2/subjektívny.jpg" },
        ],
    },
    {
        id: "b2-9",
        title: { ua: "Урок 9 — Співпраця та команда", ru: "Урок 9 — Сотрудничество и команда" },
        words: [
            { sk: "spolupráca", ua: "співпраця", ru: "сотрудничество", img: "/words_b2/spolupráca.jpg" },
            { sk: "tím", ua: "команда", ru: "команда", img: "/words_b2/tím.jpg" },
            { sk: "delegovať", ua: "делегувати", ru: "делегировать", img: "/words_b2/delegovať.jpg" },
            { sk: "zodpovedná osoba", ua: "відповідальна особа", ru: "ответственное лицо", img: "/words_b2/zodpovedná osoba.jpg" },
            { sk: "spoločný cieľ", ua: "спільна мета", ru: "общая цель", img: "/words_b2/spoločný cieľ.jpg" },
            { sk: "dohodnúť sa", ua: "домовитися", ru: "договориться", img: "/words_b2/dohodnúť sa.jpg" },
            { sk: "koordinovať", ua: "координувати", ru: "координировать", img: "/words_b2/koordinovať.jpg" },
            { sk: "podpora", ua: "підтримка", ru: "поддержка", img: "/words_b2/podpora.jpg" },
            { sk: "prispieť", ua: "зробити внесок", ru: "внести вклад", img: "/words_b2/prispieť.jpg" },
            { sk: "spoločné rozhodnutie", ua: "спільне рішення", ru: "совместное решение", img: "/words_b2/spoločné rozhodnutie.jpg" },
        ],
    },
    {
        id: "b2-10",
        title: { ua: "Урок 10 — Професійний розвиток", ru: "Урок 10 — Профессиональное развитие" },
        words: [
            { sk: "rozvoj", ua: "розвиток", ru: "развитие", img: "/words_b2/rozvoj.jpg" },
            { sk: "zdokonaliť sa", ua: "вдосконалитися", ru: "усовершенствоваться", img: "/words_b2/zdokonaliť sa.jpg" },
            { sk: "pracovať na sebe", ua: "працювати над собою", ru: "работать над собой", img: "/words_b2/pracovať na sebe.jpg" },
            { sk: "odbornosť", ua: "професіоналізм / експертність", ru: "профессионализм", img: "/words_b2/odbornosť.jpg" },
            { sk: "skúsený", ua: "досвідчений", ru: "опытный", img: "/words_b2/skúsený.jpg" },
            { sk: "prehlbovať vedomosti", ua: "поглиблювати знання", ru: "углублять знания", img: "/words_b2/prehlbovať vedomosti.jpg" },
            { sk: "zlepšovať sa", ua: "покращуватися", ru: "улучшаться", img: "/words_b2/zlepšovať sa.jpg" },
            { sk: "dosahovať výsledky", ua: "досягати результатів", ru: "достигать результатов", img: "/words_b2/dosahovať výsledky.jpg" },
            { sk: "osobný rast", ua: "особистий розвиток", ru: "личностный рост", img: "/words_b2/osobný rast.jpg" },
            { sk: "profesijný rast", ua: "професійний розвиток", ru: "профессиональный рост", img: "/words_b2/profesijný rast.jpg" },
        ],
    },
    {
        id: "b2-11",
        title: { ua: "Урок 11 — Фрукти та смаки", ru: "Урок 11 — Фрукты и вкусы" },
        words: [
            { sk: "dozretý", ua: "стиглий", ru: "спелый", img: "/words_b2/dozretý.jpg" },
            { sk: "šťavnatý", ua: "соковитий", ru: "сочный", img: "/words_b2/šťavnatý.jpg" },
            { sk: "kyslastý", ua: "кислуватий", ru: "кисловатый", img: "/words_b2/kyslastý.jpg" },
            { sk: "sladkosť", ua: "солодкість", ru: "сладость", img: "/words_b2/sladkosť.jpg" },
            { sk: "sezónne ovocie", ua: "сезонні фрукти", ru: "сезонные фрукты", img: "/words_b2/sezónne ovocie.jpg" },
            { sk: "tropické ovocie", ua: "тропічні фрукти", ru: "тропические фрукты", img: "/words_b2/tropické ovocie.jpg" },
            { sk: "zrelosť", ua: "стиглість", ru: "зрелость", img: "/words_b2/zrelosť.jpg" },
            { sk: "úroda", ua: "урожай", ru: "урожай", img: "/words_b2/úroda.jpg" },
            { sk: "pestovanie", ua: "вирощування", ru: "выращивание", img: "/words_b2/pestovanie.jpg" },
            { sk: "vitamíny", ua: "вітаміни", ru: "витамины", img: "/words_b2/vitamíny.jpg" },
        ],
    },
    {
        id: "b2-12",
        title: { ua: "Урок 12 — Кулінарія та смак", ru: "Урок 12 — Кулинария и вкус" },
        words: [
            { sk: "korenistý", ua: "пряний", ru: "пряный", img: "/words_b2/korenistý.jpg" },
            { sk: "jemný", ua: "ніжний", ru: "нежный", img: "/words_b2/jemný.jpg" },
            { sk: "výrazná chuť", ua: "виразний смак", ru: "выраженный вкус", img: "/words_b2/výrazná chuť.jpg" },
            { sk: "dochutiť", ua: "приправити", ru: "приправить", img: "/words_b2/dochutiť.jpg" },
            { sk: "ochutnať", ua: "спробувати на смак", ru: "попробовать", img: "/words_b2/ochutnať.jpg" },
            { sk: "ingrediencia", ua: "інгредієнт", ru: "ингредиент", img: "/words_b2/ingrediencia.jpg" },
            { sk: "recept", ua: "рецепт", ru: "рецепт", img: "/words_b2/recept.jpg" },
            { sk: "pripraviť jedlo", ua: "приготувати їжу", ru: "приготовить еду", img: "/words_b2/pripraviť jedlo.jpg" },
            { sk: "podávať jedlo", ua: "подавати їжу", ru: "подавать еду", img: "/words_b2/podávať jedlo.jpg" },
            { sk: "kulinársky", ua: "кулінарний", ru: "кулинарный", img: "/words_b2/kulinársky.jpg" },
        ],
    },
    {
        id: "b2-13",
        title: { ua: "Урок 13 — Спорт та фізична форма", ru: "Урок 13 — Спорт и физическая форма" },
        words: [
            { sk: "vytrvalosť", ua: "витривалість", ru: "выносливость", img: "/words_b2/vytrvalosť.jpg" },
            { sk: "kondícia", ua: "фізична форма", ru: "физическая форма", img: "/words_b2/kondícia.jpg" },
            { sk: "tréning", ua: "тренування", ru: "тренировка", img: "/words_b2/tréning.jpg" },
            { sk: "súťaž", ua: "змагання", ru: "соревнование", img: "/words_b2/súťaž.jpg" },
            { sk: "športovec", ua: "спортсмен", ru: "спортсмен", img: "/words_b2/športovec.jpg" },
            { sk: "výkon", ua: "результат / виступ", ru: "результат", img: "/words_b2/výkon.jpg" },
            { sk: "zlepšiť výkon", ua: "покращити результат", ru: "улучшить результат", img: "/words_b2/zlepšiť výkon.jpg" },
            { sk: "víťazstvo", ua: "перемога", ru: "победа", img: "/words_b2/víťazstvo.jpg" },
            { sk: "prehra", ua: "поразка", ru: "поражение", img: "/words_b2/prehra.jpg" },
            { sk: "disciplína", ua: "дисципліна", ru: "дисциплина", img: "/words_b2/disciplína.jpg" },
        ],
    },
    {
        id: "b2-14",
        title: { ua: "Урок 14 — Гори та природа", ru: "Урок 14 — Горы и природа" },
        words: [
            { sk: "pohorie", ua: "гірський хребет", ru: "горный хребет", img: "/words_b2/pohorie.jpg" },
            { sk: "vrchol", ua: "вершина", ru: "вершина", img: "/words_b2/vrchol.jpg" },
            { sk: "údolie", ua: "долина", ru: "долина", img: "/words_b2/údolie.jpg" },
            { sk: "turistika", ua: "піший туризм", ru: "пеший туризм", img: "/words_b2/turistika.jpg" },
            { sk: "výstup", ua: "підйом", ru: "подъём", img: "/words_b2/výstup.jpg" },
            { sk: "výhľad", ua: "краєвид", ru: "вид", img: "/words_b2/výhľad.jpg" },
            { sk: "chodník", ua: "стежка", ru: "тропа", img: "/words_b2/chodník.jpg" },
            { sk: "horský", ua: "гірський", ru: "горный", img: "/words_b2/horský.jpg" },
            { sk: "divoká príroda", ua: "дика природа", ru: "дикая природа", img: "/words_b2/divoká príroda.jpg" },
            { sk: "chránené územie", ua: "заповідна територія", ru: "охраняемая территория", img: "/words_b2/chránené územie.jpg" },
        ],
    },
    {
        id: "b2-15",
        title: { ua: "Урок 15 — Подорожі", ru: "Урок 15 — Путешествия" },
        words: [
            { sk: "destinácia", ua: "місце призначення", ru: "место назначения", img: "/words_b2/destinácia.jpg" },
            { sk: "itinerár", ua: "маршрут подорожі", ru: "маршрут", img: "/words_b2/itinerár.jpg" },
            { sk: "ubytovanie", ua: "проживання / житло", ru: "проживание", img: "/words_b2/ubytovanie.jpg" },
            { sk: "cestovný ruch", ua: "туризм", ru: "туризм", img: "/words_b2/cestovný ruch.jpg" },
            { sk: "miestne zvyky", ua: "місцеві звичаї", ru: "местные обычаи", img: "/words_b2/miestne zvyky.jpg" },
            { sk: "historická pamiatka", ua: "історична пам’ятка", ru: "историческая достопримечательность", img: "/words_b2/historická pamiatka.jpg" },
            { sk: "cestovateľ", ua: "мандрівник", ru: "путешественник", img: "/words_b2/cestovateľ.jpg" },
            { sk: "objavovať", ua: "відкривати / досліджувати", ru: "открывать", img: "/words_b2/objavovať.jpg" },
            { sk: "miestna kultúra", ua: "місцева культура", ru: "местная культура", img: "/words_b2/miestna kultúra.jpg" },
            { sk: "cestovateľský zážitok", ua: "досвід подорожі", ru: "опыт путешествия", img: "/words_b2/cestovateľský zážitok.jpg" },
        ],
    },
    {
        id: "b2-16",
        title: { ua: "Урок 16 — Фрукти", ru: "Урок 16 — Фрукты" },
        words: [
            { sk: "jablko", ua: "яблуко", ru: "яблоко", img: "/words_b2/jablko.jpg" },
            { sk: "hruška", ua: "груша", ru: "груша", img: "/words_b2/hruška.jpg" },
            { sk: "broskyňa", ua: "персик", ru: "персик", img: "/words_b2/broskyňa.jpg" },
            { sk: "marhuľa", ua: "абрикос", ru: "абрикос", img: "/words_b2/marhuľa.jpg" },
            { sk: "slivka", ua: "слива", ru: "слива", img: "/words_b2/slivka.jpg" },
            { sk: "čučoriedka", ua: "чорниця / лохина", ru: "черника", img: "/words_b2/čučoriedka.jpg" },
            { sk: "malina", ua: "малина", ru: "малина", img: "/words_b2/malina.jpg" },
            { sk: "ananás", ua: "ананас", ru: "ананас", img: "/words_b2/ananás.jpg" },
            { sk: "mango", ua: "манго", ru: "манго", img: "/words_b2/mango.jpg" },
            { sk: "melón", ua: "диня / кавун", ru: "дыня / арбуз", img: "/words_b2/melón.jpg" },
        ],
    },
    {
        id: "b2-17",
        title: { ua: "Урок 17 — Овочі", ru: "Урок 17 — Овощи" },
        words: [
            { sk: "mrkva", ua: "морква", ru: "морковь", img: "/words_b2/mrkva.jpg" },
            { sk: "uhorka", ua: "огірок", ru: "огурец", img: "/words_b2/uhorka.jpg" },
            { sk: "paradajka", ua: "помідор", ru: "помидор", img: "/words_b2/paradajka.jpg" },
            { sk: "paprika", ua: "перець", ru: "перец", img: "/words_b2/paprika.jpg" },
            { sk: "zemiak", ua: "картопля", ru: "картофель", img: "/words_b2/zemiak.jpg" },
            { sk: "cibuľa", ua: "цибуля", ru: "лук", img: "/words_b2/cibuľa.jpg" },
            { sk: "cesnak", ua: "часник", ru: "чеснок", img: "/words_b2/cesnak.jpg" },
            { sk: "baklažán", ua: "баклажан", ru: "баклажан", img: "/words_b2/baklažán.jpg" },
            { sk: "cuketa", ua: "кабачок", ru: "кабачок", img: "/words_b2/cuketa.jpg" },
            { sk: "kapusta", ua: "капуста", ru: "капуста", img: "/words_b2/kapusta.jpg" },
        ],
    },
    {
        id: "b2-18",
        title: { ua: "Урок 18 — Напої", ru: "Урок 18 — Напитки" },
        words: [
            { sk: "minerálna voda", ua: "мінеральна вода", ru: "минеральная вода", img: "/words_b2/minerálna voda.jpg" },
            { sk: "džús", ua: "сік", ru: "сок", img: "/words_b2/džús.jpg" },
            { sk: "čaj", ua: "чай", ru: "чай", img: "/words_b2/čaj.jpg" },
            { sk: "káva", ua: "кава", ru: "кофе", img: "/words_b2/káva.jpg" },
            { sk: "espresso", ua: "еспресо", ru: "эспрессо", img: "/words_b2/espresso.jpg" },
            { sk: "cappuccino", ua: "капучино", ru: "капучино", img: "/words_b2/cappuccino.jpg" },
            { sk: "limonáda", ua: "лимонад", ru: "лимонад", img: "/words_b2/limonáda.jpg" },
            { sk: "pivo", ua: "пиво", ru: "пиво", img: "/words_b2/pivo.jpg" },
            { sk: "víno", ua: "вино", ru: "вино", img: "/words_b2/víno.jpg" },
            { sk: "koktail", ua: "коктейль", ru: "коктейль", img: "/words_b2/koktail.jpg" },
        ],
    },
    {
        id: "b2-19",
        title: { ua: "Урок 19 — Емоції та внутрішній стан", ru: "Урок 19 — Эмоции и внутреннее состояние" },
        words: [
            { sk: "úzkosť", ua: "тривога", ru: "тревога", img: "/words_b2/úzkosť.jpg" },
            { sk: "sklamanie", ua: "розчарування", ru: "разочарование", img: "/words_b2/sklamanie.jpg" },
            { sk: "dojatie", ua: "зворушення", ru: "умиление / растроганность", img: "/words_b2/dojatie.jpg" },
            { sk: "odľahčenie", ua: "полегшення", ru: "облегчение", img: "/words_b2/odľahčenie.jpg" },
            { sk: "znechutenie", ua: "огида / відраза", ru: "отвращение", img: "/words_b2/znechutenie.jpg" },
            { sk: "rozladený", ua: "засмучений / роздратований", ru: "расстроенный / раздражённый", img: "/words_b2/rozladený.jpg" },
            { sk: "vyčerpanosť", ua: "виснаження", ru: "истощение", img: "/words_b2/vyčerpanosť.jpg" },
            { sk: "citová reakcia", ua: "емоційна реакція", ru: "эмоциональная реакция", img: "/words_b2/citová reakcia.jpg" },
            { sk: "duševná pohoda", ua: "душевний спокій / психологічний комфорт", ru: "душевное спокойствие", img: "/words_b2/duševná pohoda.jpg" },
            { sk: "potlačiť emócie", ua: "пригнічувати емоції", ru: "подавлять эмоции", img: "/words_b2/potlačiť emócie.jpg" },
        ],
    },
    {
        id: "b2-20",
        title: { ua: "Урок 20 — Культура і мистецтво", ru: "Урок 20 — Культура и искусство" },
        words: [
            { sk: "umenie", ua: "мистецтво", ru: "искусство", img: "/words_b2/umenie.jpg" },
            { sk: "umelecké dielo", ua: "твір мистецтва", ru: "произведение искусства", img: "/words_b2/umelecké dielo.jpg" },
            { sk: "výstava", ua: "виставка", ru: "выставка", img: "/words_b2/výstava.jpg" },
            { sk: "galéria", ua: "галерея", ru: "галерея", img: "/words_b2/galéria.jpg" },
            { sk: "divadlo", ua: "театр", ru: "театр", img: "/words_b2/divadlo.jpg" },
            { sk: "predstavenie", ua: "вистава", ru: "представление", img: "/words_b2/predstavenie.jpg" },
            { sk: "publikum", ua: "публіка", ru: "публика", img: "/words_b2/publikum.jpg" },
            { sk: "umelecký štýl", ua: "художній стиль", ru: "художественный стиль", img: "/words_b2/umelecký štýl.jpg" },
            { sk: "interpretácia", ua: "інтерпретація", ru: "интерпретация", img: "/words_b2/interpretácia.jpg" },
            { sk: "kultúrny zážitok", ua: "культурний досвід", ru: "культурный опыт", img: "/words_b2/kultúrny zážitok.jpg" },
        ],
    },
    {
        id: "b2-21",
        title: { ua: "Урок 21 — Мислення та аналіз", ru: "Урок 21 — Мышление и анализ" },
        words: [
            { sk: "uvažovanie", ua: "роздумування", ru: "размышление", img: "/words_b2/uvažovanie.jpg" },
            { sk: "predpoklad", ua: "припущення", ru: "предположение", img: "/words_b2/predpoklad.jpg" },
            { sk: "posudzovať", ua: "оцінювати / судити", ru: "оценивать", img: "/words_b2/posudzovať.jpg" },
            { sk: "hľadisko", ua: "точка зору / аспект", ru: "точка зрения / аспект", img: "/words_b2/hľadisko.jpg" },
            { sk: "súvislosť", ua: "взаємозв'язок", ru: "взаимосвязь", img: "/words_b2/súvislosť.jpg" },
            { sk: "domnienka", ua: "здогад / припущення", ru: "догадка / предположение", img: "/words_b2/domnienka.jpg" },
            { sk: "logický", ua: "логічний", ru: "логический", img: "/words_b2/logický.jpg" },
            { sk: "analyzovať", ua: "аналізувати", ru: "анализировать", img: "/words_b2/analyzovať.jpg" },
            { sk: "vyhodnotiť", ua: "оцінити результат", ru: "оценить результат", img: "/words_b2/vyhodnotiť.jpg" },
            { sk: "odhad", ua: "оцінка / приблизний розрахунок", ru: "оценка / приблизительный расчёт", img: "/words_b2/odhad.jpg" },
        ],
    },
    {
        id: "b2-22",
        title: { ua: "Урок 22 — Суспільство", ru: "Урок 22 — Общество" },
        words: [
            { sk: "spoločnosť", ua: "суспільство", ru: "общество", img: "/words_b2/spoločnosť.jpg" },
            { sk: "hodnota", ua: "цінність", ru: "ценность", img: "/words_b2/hodnota.jpg" },
            { sk: "generácia", ua: "покоління", ru: "поколение", img: "/words_b2/generácia.jpg" },
            { sk: "životný štýl", ua: "стиль життя", ru: "образ жизни", img: "/words_b2/životný štýl.jpg" },
            { sk: "súčasnosť", ua: "сучасність", ru: "современность", img: "/words_b2/súčasnosť.jpg" },
            { sk: "spoločenský vývoj", ua: "суспільний розвиток", ru: "общественное развитие", img: "/words_b2/spoločenský vývoj.jpg" },
            { sk: "verejný život", ua: "громадське життя", ru: "общественная жизнь", img: "/words_b2/verejný život.jpg" },
            { sk: "spoločenský jav", ua: "суспільне явище", ru: "общественное явление", img: "/words_b2/spoločenský jav.jpg" },
            { sk: "spoločenská zmena", ua: "суспільна зміна", ru: "общественное изменение", img: "/words_b2/spoločenská zmena.jpg" },
            { sk: "spoločenské prostredie", ua: "соціальне середовище", ru: "социальная среда", img: "/words_b2/spoločenské prostredie.jpg" },
        ],
    },
    {
        id: "b2-23",
        title: { ua: "Урок 23 — Характер людини", ru: "Урок 23 — Характер человека" },
        words: [
            { sk: "spoľahlivý", ua: "надійний", ru: "надёжный", img: "/words_b2/spoľahlivý.jpg" },
            { sk: "zásadový", ua: "принциповий", ru: "принципиальный", img: "/words_b2/zásadový.jpg" },
            { sk: "sebaistý", ua: "впевнений у собі", ru: "уверенный в себе", img: "/words_b2/sebaistý.jpg" },
            { sk: "tolerantný", ua: "толерантний", ru: "толерантный", img: "/words_b2/tolerantný.jpg" },
            { sk: "cieľavedomý", ua: "цілеспрямований", ru: "целеустремлённый", img: "/words_b2/cieľavedomý.jpg" },
            { sk: "citlivý", ua: "чутливий", ru: "чувствительный", img: "/words_b2/citlivý.jpg" },
            { sk: "rozhodný", ua: "рішучий", ru: "решительный", img: "/words_b2/rozhodný.jpg" },
            { sk: "skromný", ua: "скромний", ru: "скромный", img: "/words_b2/skromný.jpg" },
            { sk: "otvorený", ua: "відкритий", ru: "открытый", img: "/words_b2/otvorený.jpg" },
            { sk: "vyrovnaný", ua: "врівноважений", ru: "уравновешенный", img: "/words_b2/vyrovnaný.jpg" },
        ],
    },
    {
        id: "b2-24",
        title: { ua: "Урок 24 — Технології", ru: "Урок 24 — Технологии" },
        words: [
            { sk: "používateľ", ua: "користувач", ru: "пользователь", img: "/words_b2/používateľ.jpg" },
            { sk: "zariadenie", ua: "пристрій", ru: "устройство", img: "/words_b2/zariadenie.jpg" },
            { sk: "údaje", ua: "дані", ru: "данные", img: "/words_b2/údaje.jpg" },
            { sk: "digitálne prostredie", ua: "цифрове середовище", ru: "цифровая среда", img: "/words_b2/digitálne prostredie.jpg" },
            { sk: "online služba", ua: "онлайн сервіс", ru: "онлайн сервис", img: "/words_b2/online služba.jpg" },
            { sk: "spracovanie údajov", ua: "обробка даних", ru: "обработка данных", img: "/words_b2/spracovanie údajov.jpg" },
            { sk: "technické riešenie", ua: "технічне рішення", ru: "техническое решение", img: "/words_b2/technické riešenie.jpg" },
            { sk: "funkčnosť", ua: "функціональність", ru: "функциональность", img: "/words_b2/funkčnosť.jpg" },
            { sk: "výkon systému", ua: "продуктивність системи", ru: "производительность системы", img: "/words_b2/výkon systému.jpg" },
            { sk: "digitálna technológia", ua: "цифрова технологія", ru: "цифровая технология", img: "/words_b2/digitálna technológia.jpg" },
        ],
    },
    {
        id: "b2-25",
        title: { ua: "Урок 25 — Аргументація і дискусія", ru: "Урок 25 — Аргументация и дискуссия" },
        words: [
            { sk: "zdôvodniť", ua: "обґрунтувати", ru: "обосновать", img: "/words_b2/zdôvodniť.jpg" },
            { sk: "reakcia", ua: "реакція", ru: "реакция", img: "/words_b2/reakcia.jpg" },
            { sk: "stanovisko", ua: "позиція / точка зору", ru: "позиция / точка зрения", img: "/words_b2/stanovisko.jpg" },
            { sk: "tvrdenie", ua: "твердження", ru: "утверждение", img: "/words_b2/tvrdenie.jpg" },
            { sk: "vysvetlenie", ua: "пояснення", ru: "объяснение", img: "/words_b2/vysvetlenie.jpg" },
            { sk: "námietka", ua: "заперечення", ru: "возражение", img: "/words_b2/námietka.jpg" },
            { sk: "protiargument", ua: "контраргумент", ru: "контраргумент", img: "/words_b2/protiargument.jpg" },
            { sk: "diskusia", ua: "дискусія", ru: "дискуссия", img: "/words_b2/diskusia.jpg" },
            { sk: "argumentovať", ua: "аргументувати", ru: "аргументировать", img: "/words_b2/argumentovať.jpg" },
            { sk: "obhájiť názor", ua: "захистити свою думку", ru: "защитить мнение", img: "/words_b2/obhájiť názor.jpg" },
        ],
    },
    {
        id: "b2-26",
        title: { ua: "Урок 26 — Психологія людини", ru: "Урок 26 — Психология человека" },
        words: [
            { sk: "sebareflexia", ua: "саморефлексія", ru: "саморефлексия", img: "/words_b2/sebareflexia.jpg" },
            { sk: "vnútorný konflikt", ua: "внутрішній конфлікт", ru: "внутренний конфликт", img: "/words_b2/vnútorný konflikt.jpg" },
            { sk: "sebakontrola", ua: "самоконтроль", ru: "самоконтроль", img: "/words_b2/sebakontrola.jpg" },
            { sk: "duševná rovnováha", ua: "психологічна рівновага", ru: "душевное равновесие", img: "/words_b2/duševná rovnováha.jpg" },
            { sk: "podvedomie", ua: "підсвідомість", ru: "подсознание", img: "/words_b2/podvedomie.jpg" },
            { sk: "vnútorný tlak", ua: "внутрішній тиск", ru: "внутреннее давление", img: "/words_b2/vnútorný tlak.jpg" },
            { sk: "osobná hranica", ua: "особиста межа", ru: "личная граница", img: "/words_b2/osobná hranica.jpg" },
            { sk: "psychická odolnosť", ua: "психологічна стійкість", ru: "психологическая устойчивость", img: "/words_b2/psychická odolnosť.jpg" },
            { sk: "duševný stav", ua: "психічний стан", ru: "психическое состояние", img: "/words_b2/duševný stav.jpg" },
            { sk: "sebauvedomenie", ua: "самоусвідомлення", ru: "самоосознание", img: "/words_b2/sebauvedomenie.jpg" },
        ],
    },
    {
        id: "b2-27",
        title: { ua: "Урок 27 — Дипломатія", ru: "Урок 27 — Дипломатия" },
        words: [
            { sk: "vyjednávanie", ua: "переговори", ru: "переговоры", img: "/words_b2/vyjednávanie.jpg" },
            { sk: "ústretový postoj", ua: "компромісна позиція", ru: "компромиссная позиция", img: "/words_b2/ústretový postoj.jpg" },
            { sk: "neutrálne stanovisko", ua: "нейтральна позиція", ru: "нейтральная позиция", img: "/words_b2/neutrálne stanovisko.jpg" },
            { sk: "vyvážené riešenie", ua: "збалансоване рішення", ru: "сбалансированное решение", img: "/words_b2/vyvážené riešenie.jpg" },
            { sk: "napätá situácia", ua: "напружена ситуація", ru: "напряжённая ситуация", img: "/words_b2/napätá situácia.jpg" },
            { sk: "zmierlivý tón", ua: "примирливий тон", ru: "примирительный тон", img: "/words_b2/zmierlivý tón.jpg" },
            { sk: "rokovacia stratégia", ua: "стратегія переговорів", ru: "стратегия переговоров", img: "/words_b2/rokovacia stratégia.jpg" },
            { sk: "vzájomná dohoda", ua: "взаємна домовленість", ru: "взаимное соглашение", img: "/words_b2/vzájomná dohoda.jpg" },
            { sk: "kompromisné riešenie", ua: "компромісне рішення", ru: "компромиссное решение", img: "/words_b2/kompromisné riešenie.jpg" },
            { sk: "zachovať neutralitu", ua: "зберігати нейтралітет", ru: "сохранять нейтралитет", img: "/words_b2/zachovať neutralitu.jpg" },
        ],
    },
    {
        id: "b2-28",
        title: { ua: "Урок 28 — Глобальні проблеми", ru: "Урок 28 — Глобальные проблемы" },
        words: [
            { sk: "globálna výzva", ua: "глобальний виклик", ru: "глобальный вызов", img: "/words_b2/globálna výzva.jpg" },
            { sk: "humanitárna kríza", ua: "гуманітарна криза", ru: "гуманитарный кризис", img: "/words_b2/humanitárna kríza.jpg" },
            { sk: "nedostatok zdrojov", ua: "нестача ресурсів", ru: "нехватка ресурсов", img: "/words_b2/nedostatok zdrojov.jpg" },
            { sk: "sociálna nerovnosť", ua: "соціальна нерівність", ru: "социальное неравенство", img: "/words_b2/sociálna nerovnosť.jpg" },
            { sk: "migračná vlna", ua: "міграційна хвиля", ru: "миграционная волна", img: "/words_b2/migračná vlna.jpg" },
            { sk: "medzinárodná spolupráca", ua: "міжнародна співпраця", ru: "международное сотрудничество", img: "/words_b2/medzinárodná spolupráca.jpg" },
            { sk: "dlhodobý problém", ua: "довготривала проблема", ru: "долгосрочная проблема", img: "/words_b2/dlhodobý problém.jpg" },
            { sk: "spoločná zodpovednosť", ua: "спільна відповідальність", ru: "общая ответственность", img: "/words_b2/spoločná zodpovednosť.jpg" },
            { sk: "celosvetový dopad", ua: "глобальний вплив", ru: "глобальное влияние", img: "/words_b2/celosvetový dopad.jpg" },
            { sk: "udržateľné riešenie", ua: "стале рішення", ru: "устойчивое решение", img: "/words_b2/udržateľné riešenie.jpg" },
        ],
    },
    {
        id: "b2-29",
        title: { ua: "Урок 29 — Міжособистісні конфлікти", ru: "Урок 29 — Межличностные конфликты" },
        words: [
            { sk: "napätý vzťah", ua: "напружені стосунки", ru: "напряжённые отношения", img: "/words_b2/napätý vzťah.jpg" },
            { sk: "nepochopenie", ua: "непорозуміння", ru: "недопонимание", img: "/words_b2/nepochopenie.jpg" },
            { sk: "ospravedlnenie", ua: "вибачення", ru: "извинение", img: "/words_b2/ospravedlnenie.jpg" },
            { sk: "zmier", ua: "примирення", ru: "примирение", img: "/words_b2/zmier.jpg" },
            { sk: "napätá atmosféra", ua: "напружена атмосфера", ru: "напряжённая атмосфера", img: "/words_b2/napätá atmosféra.jpg" },
            { sk: "vyriešiť konflikt", ua: "вирішити конфлікт", ru: "решить конфликт", img: "/words_b2/vyriešiť konflikt.jpg" },
            { sk: "vzájomné pochopenie", ua: "взаєморозуміння", ru: "взаимопонимание", img: "/words_b2/vzájomné pochopenie.jpg" },
            { sk: "napraviť chybu", ua: "виправити помилку", ru: "исправить ошибку", img: "/words_b2/napraviť chybu.jpg" },
            { sk: "napätie medzi ľuďmi", ua: "напруга між людьми", ru: "напряжение между людьми", img: "/words_b2/napätie medzi ľuďmi.jpg" },
            { sk: "vzťahová kríza", ua: "криза у відносинах", ru: "кризис в отношениях", img: "/words_b2/vzťahová kríza.jpg" },
        ],
    },
    {
        id: "b2-30",
        title: { ua: "Урок 30 — Культура і суспільні явища", ru: "Урок 30 — Культура и общественные явления" },
        words: [
            { sk: "kultúrna identita", ua: "культурна ідентичність", ru: "культурная идентичность", img: "/words_b2/kultúrna identita.jpg" },
            { sk: "spoločenský trend", ua: "соціальний тренд", ru: "социальный тренд", img: "/words_b2/spoločenský trend.jpg" },
            { sk: "spoločenská norma", ua: "соціальна норма", ru: "социальная норма", img: "/words_b2/spoločenská norma.jpg" },
            { sk: "kultúrne dedičstvo", ua: "культурна спадщина", ru: "культурное наследие", img: "/words_b2/kultúrne dedičstvo.jpg" },
            { sk: "umelecký smer", ua: "художній напрям", ru: "художественное направление", img: "/words_b2/umelecký smer.jpg" },
            { sk: "spoločenský vplyv", ua: "соціальний вплив", ru: "социальное влияние", img: "/words_b2/spoločenský vplyv.jpg" },
            { sk: "verejná diskusia", ua: "публічна дискусія", ru: "публичная дискуссия", img: "/words_b2/verejná diskusia.jpg" },
            { sk: "spoločenský kontext", ua: "соціальний контекст", ru: "социальный контекст", img: "/words_b2/spoločenský kontext.jpg" },
            { sk: "kultúrny rozdiel", ua: "культурна різниця", ru: "культурное различие", img: "/words_b2/kultúrny rozdiel.jpg" },
            { sk: "spoločenská realita", ua: "соціальна реальність", ru: "социальная реальность", img: "/words_b2/spoločenská realita.jpg" },
        ],
    },
    {
        id: "b2-31",
        title: { ua: "Урок 31 — Командні види спорту", ru: "Урок 31 — Командные виды спорта" },
        words: [
            { sk: "prihrávka", ua: "пас", ru: "пас", img: "/words_b2/prihrávka.jpg" },
            { sk: "rohový kop", ua: "кутовий", ru: "угловой удар", img: "/words_b2/rohový kop.jpg" },
            { sk: "pokutový kop", ua: "пенальті", ru: "пенальти", img: "/words_b2/pokutový kop.jpg" },
            { sk: "obranca", ua: "захисник", ru: "защитник", img: "/words_b2/obranca.jpg" },
            { sk: "útočník", ua: "нападник", ru: "нападающий", img: "/words_b2/útočník.jpg" },
            { sk: "rozhodca", ua: "суддя", ru: "судья", img: "/words_b2/rozhodca.jpg" },
            { sk: "strela", ua: "удар / кидок", ru: "удар / бросок", img: "/words_b2/strela.jpg" },
            { sk: "skórovať", ua: "забити / набрати очки", ru: "забить / набрать очки", img: "/words_b2/skórovať.jpg" },
            { sk: "basketbalový kôš", ua: "баскетбольне кільце", ru: "баскетбольное кольцо", img: "/words_b2/basketbalový kôš.jpg" },
            { sk: "zápas", ua: "матч", ru: "матч", img: "/words_b2/zápas.jpg" },
        ],
    },
    {
        id: "b2-32",
        title: { ua: "Урок 32 — Теніс", ru: "Урок 32 — Теннис" },
        words: [
            { sk: "tenisový kurt", ua: "тенісний корт", ru: "теннисный корт", img: "/words_b2/tenisový kurt.jpg" },
            { sk: "raketa", ua: "ракетка", ru: "ракетка", img: "/words_b2/raketa.jpg" },
            { sk: "loptička", ua: "м’яч", ru: "мяч", img: "/words_b2/loptička.jpg" },
            { sk: "podanie", ua: "подача", ru: "подача", img: "/words_b2/podanie.jpg" },
            { sk: "set", ua: "сет", ru: "сет", img: "/words_b2/set.jpg" },
            { sk: "turnaj", ua: "турнір", ru: "турнир", img: "/words_b2/turnaj.jpg" },
            { sk: "súper", ua: "суперник", ru: "соперник", img: "/words_b2/súper.jpg" },
            { sk: "rozhodujúci bod", ua: "вирішальний пункт", ru: "решающий очко", img: "/words_b2/rozhodujúci bod.jpg" },
            { sk: "silný úder", ua: "сильний удар", ru: "сильный удар", img: "/words_b2/silný úder.jpg" },
            { sk: "vyhrať zápas", ua: "виграти матч", ru: "выиграть матч", img: "/words_b2/vyhrať zápas.jpg" },
        ],
    },
    {
        id: "b2-33",
        title: { ua: "Урок 33 — Риболовля", ru: "Урок 33 — Рыбалка" },
        words: [
            { sk: "udica", ua: "вудка", ru: "удочка", img: "/words_b2/udica.jpg" },
            { sk: "navijak", ua: "котушка", ru: "катушка", img: "/words_b2/navijak.jpg" },
            { sk: "háčik", ua: "гачок", ru: "крючок", img: "/words_b2/háčik.jpg" },
            { sk: "návnada", ua: "наживка", ru: "наживка", img: "/words_b2/návnada.jpg" },
            { sk: "úlovok", ua: "улов", ru: "улов", img: "/words_b2/úlovok.jpg" },
            { sk: "rybár", ua: "рибалка", ru: "рыбак", img: "/words_b2/rybár.jpg" },
            { sk: "jazero", ua: "озеро", ru: "озеро", img: "/words_b2/jazero.jpg" },
            { sk: "breh", ua: "берег", ru: "берег", img: "/words_b2/breh.jpg" },
            { sk: "čln", ua: "човен", ru: "лодка", img: "/words_b2/čln.jpg" },
            { sk: "chytiť rybu", ua: "зловити рибу", ru: "поймать рыбу", img: "/words_b2/chytiť rybu.jpg" },
        ],
    },
    {
        id: "b2-34",
        title: { ua: "Урок 34 — Автомобілі", ru: "Урок 34 — Автомобили" },
        words: [
            { sk: "automobilová značka", ua: "марка автомобіля", ru: "марка автомобиля", img: "/words_b2/automobilová značka.jpg" },
            { sk: "osobné vozidlo", ua: "легковий автомобіль", ru: "легковой автомобиль", img: "/words_b2/osobné vozidlo.jpg" },
            { sk: "sedan", ua: "седан", ru: "седан", img: "/words_b2/sedan.jpg" },
            { sk: "SUV", ua: "позашляховик", ru: "внедорожник", img: "/words_b2/suv.jpg" },
            { sk: "hatchback", ua: "хетчбек", ru: "хэтчбек", img: "/words_b2/hatchback.jpg" },
            { sk: "Volkswagen", ua: "Фольксваген", ru: "Фольксваген", img: "/words_b2/volkswagen.jpg" },
            { sk: "BMW", ua: "БМВ", ru: "БМВ", img: "/words_b2/bmw.jpg" },
            { sk: "Mercedes", ua: "Мерседес", ru: "Мерседес", img: "/words_b2/mercedes.jpg" },
            { sk: "Toyota", ua: "Тойота", ru: "Тойота", img: "/words_b2/toyota.jpg" },
            { sk: "motor vozidla", ua: "двигун автомобіля", ru: "двигатель автомобиля", img: "/words_b2/motor vozidla.jpg" },
        ],
    },
    {
        id: "b2-35",
        title: { ua: "Урок 35 — Морський транспорт", ru: "Урок 35 — Морской транспорт" },
        words: [
            { sk: "loď", ua: "корабель", ru: "корабль", img: "/words_b2/loď.jpg" },
            { sk: "ponorka", ua: "субмарина", ru: "подводная лодка", img: "/words_b2/ponorka.jpg" },
            { sk: "prístav", ua: "порт", ru: "порт", img: "/words_b2/prístav.jpg" },
            { sk: "paluba", ua: "палуба", ru: "палуба", img: "/words_b2/paluba.jpg" },
            { sk: "kapitán", ua: "капітан", ru: "капитан", img: "/words_b2/kapitán.jpg" },
            { sk: "námorník", ua: "моряк", ru: "моряк", img: "/words_b2/námorník.jpg" },
            { sk: "plavidlo", ua: "судно", ru: "судно", img: "/words_b2/plavidlo.jpg" },
            { sk: "námorná trasa", ua: "морський маршрут", ru: "морской маршрут", img: "/words_b2/námorná trasa.jpg" },
            { sk: "ponoriť sa", ua: "зануритися", ru: "погрузиться", img: "/words_b2/ponoriť sa.jpg" },
            { sk: "námorná doprava", ua: "морський транспорт", ru: "морской транспорт", img: "/words_b2/námorná doprava.jpg" },
        ],
    },
    {
        id: "b2-36",
        title: { ua: "Урок 36 — Казино", ru: "Урок 36 — Казино" },
        words: [
            { sk: "kasíno", ua: "казино", ru: "казино", img: "/words_b2/kasíno.jpg" },
            { sk: "ruleta", ua: "рулетка", ru: "рулетка", img: "/words_b2/ruleta.jpg" },
            { sk: "žetón", ua: "фішка", ru: "жетон", img: "/words_b2/žetón.jpg" },
            { sk: "stávka", ua: "ставка", ru: "ставка", img: "/words_b2/stávka.jpg" },
            { sk: "vyhrať jackpot", ua: "виграти джекпот", ru: "выиграть джекпот", img: "/words_b2/vyhrať jackpot.jpg" },
            { sk: "prehrať peniaze", ua: "програти гроші", ru: "проиграть деньги", img: "/words_b2/prehrať peniaze.jpg" },
            { sk: "hrací automat", ua: "ігровий автомат", ru: "игровой автомат", img: "/words_b2/hrací automat.jpg" },
            { sk: "karta", ua: "карта", ru: "карта", img: "/words_b2/karta.jpg" },
            { sk: "krupiér", ua: "круп'є", ru: "крупье", img: "/words_b2/krupiér.jpg" },
            { sk: "hrať o peniaze", ua: "грати на гроші", ru: "играть на деньги", img: "/words_b2/hrať o peniaze.jpg" },
        ],
    },
    {
        id: "b2-37",
        title: { ua: "Урок 37 — Жанри", ru: "Урок 37 — Жанры" },
        words: [
            { sk: "žáner", ua: "жанр", ru: "жанр", img: "/words_b2/žáner.jpg" },
            { sk: "komédia", ua: "комедія", ru: "комедия", img: "/words_b2/komédia.jpg" },
            { sk: "dráma", ua: "драма", ru: "драма", img: "/words_b2/dráma.jpg" },
            { sk: "triler", ua: "трилер", ru: "триллер", img: "/words_b2/triler.jpg" },
            { sk: "fantasy", ua: "фентезі", ru: "фэнтези", img: "/words_b2/fantasy.jpg" },
            { sk: "sci-fi", ua: "наукова фантастика", ru: "научная фантастика", img: "/words_b2/scifi.jpg" },
            { sk: "dokumentárny film", ua: "документальний фільм", ru: "документальный фильм", img: "/words_b2/dokumentárny film.jpg" },
            { sk: "horor", ua: "жахи", ru: "ужасы", img: "/words_b2/horor.jpg" },
            { sk: "romantický film", ua: "романтичний фільм", ru: "романтический фильм", img: "/words_b2/romantický film.jpg" },
            { sk: "dobrodružný film", ua: "пригодницький фільм", ru: "приключенческий фильм", img: "/words_b2/dobrodružný film.jpg" },
        ],
    },
    {
        id: "b2-38",
        title: { ua: "Урок 38 — Рельєф", ru: "Урок 38 — Рельеф" },
        words: [
            { sk: "reliéf", ua: "рельєф", ru: "рельеф", img: "/words_b2/reliéf.jpg" },
            { sk: "vrch", ua: "пагорб", ru: "холм", img: "/words_b2/vrch.jpg" },
            { sk: "rovina", ua: "рівнина", ru: "равнина", img: "/words_b2/rovina.jpg" },
            { sk: "náhorná plošina", ua: "плато", ru: "плато", img: "/words_b2/náhorná plošina.jpg" },
            { sk: "kaňon", ua: "каньйон", ru: "каньон", img: "/words_b2/kaňon.jpg" },
            { sk: "údolie", ua: "долина", ru: "долина", img: "/words_b2/údolie.jpg" },
            { sk: "horský hrebeň", ua: "гірський хребет", ru: "горный хребет", img: "/words_b2/horský hrebeň.jpg" },
            { sk: "skalnatý terén", ua: "скелястий рельєф", ru: "скалистая местность", img: "/words_b2/skalnatý terén.jpg" },
            { sk: "povrch krajiny", ua: "поверхня місцевості", ru: "поверхность местности", img: "/words_b2/povrch krajiny.jpg" },
            { sk: "prírodná krajina", ua: "природний ландшафт", ru: "природный ландшафт", img: "/words_b2/prírodná krajina.jpg" },
        ],
    },
    {
        id: "b2-39",
        title: { ua: "Урок 39 — Музика", ru: "Урок 39 — Музыка" },
        words: [
            { sk: "melódia", ua: "мелодія", ru: "мелодия", img: "/words_b2/melódia.jpg" },
            { sk: "rytmus", ua: "ритм", ru: "ритм", img: "/words_b2/rytmus.jpg" },
            { sk: "hudobný nástroj", ua: "музичний інструмент", ru: "музыкальный инструмент", img: "/words_b2/hudobný nástroj.jpg" },
            { sk: "gitara", ua: "гітара", ru: "гитара", img: "/words_b2/gitara.jpg" },
            { sk: "klavír", ua: "піаніно", ru: "пианино", img: "/words_b2/klavír.jpg" },
            { sk: "koncert", ua: "концерт", ru: "концерт", img: "/words_b2/koncert.jpg" },
            { sk: "spevák", ua: "співак", ru: "певец", img: "/words_b2/spevák.jpg" },
            { sk: "hudobná skupina", ua: "музичний гурт", ru: "музыкальная группа", img: "/words_b2/hudobná skupina.jpg" },
            { sk: "nahrávka", ua: "запис", ru: "запись", img: "/words_b2/nahrávka.jpg" },
            { sk: "hudobný štýl", ua: "музичний стиль", ru: "музыкальный стиль", img: "/words_b2/hudobný štýl.jpg" },
        ],
    },
    {
        id: "b2-40",
        title: { ua: "Урок 40 — Електрика", ru: "Урок 40 — Электричество" },
        words: [
            { sk: "elektrina", ua: "електрика", ru: "электричество", img: "/words_b2/elektrina.jpg" },
            { sk: "elektrický prúd", ua: "електричний струм", ru: "электрический ток", img: "/words_b2/elektrický prúd.jpg" },
            { sk: "napätie", ua: "напруга", ru: "напряжение", img: "/words_b2/napätie.jpg" },
            { sk: "zásuvka", ua: "розетка", ru: "розетка", img: "/words_b2/zásuvka.jpg" },
            { sk: "kábel", ua: "кабель", ru: "кабель", img: "/words_b2/kábel.jpg" },
            { sk: "vypínač", ua: "вимикач", ru: "выключатель", img: "/words_b2/vypínač.jpg" },
            { sk: "elektrický obvod", ua: "електричне коло", ru: "электрическая цепь", img: "/words_b2/elektrický obvod.jpg" },
            { sk: "spotrebič", ua: "електроприлад", ru: "электроприбор", img: "/words_b2/spotrebič.jpg" },
            { sk: "energia", ua: "енергія", ru: "энергия", img: "/words_b2/energia.jpg" },
            { sk: "zapnúť prúd", ua: "увімкнути струм", ru: "включить ток", img: "/words_b2/zapnúť prúd.jpg" },
        ],
    },
    {
        id: "b2-41",
        title: { ua: "Урок 41 — Мистецтво", ru: "Урок 41 — Искусство" },
        words: [
            { sk: "umelecké dielo", ua: "твір мистецтва", ru: "произведение искусства", img: "/words_b2/umelecké dielo.jpg" },
            { sk: "maliar", ua: "художник", ru: "художник", img: "/words_b2/maliar.jpg" },
            { sk: "socha", ua: "скульптура", ru: "скульптура", img: "/words_b2/socha.jpg" },
            { sk: "plátno", ua: "полотно (для картини)", ru: "холст", img: "/words_b2/plátno.jpg" },
            { sk: "portrét", ua: "портрет", ru: "портрет", img: "/words_b2/portrét.jpg" },
            { sk: "umelecký štýl", ua: "художній стиль", ru: "художественный стиль", img: "/words_b2/umelecký štýl.jpg" },
            { sk: "abstraktné umenie", ua: "абстрактне мистецтво", ru: "абстрактное искусство", img: "/words_b2/abstraktné umenie.jpg" },
            { sk: "maľba", ua: "живопис", ru: "живопись", img: "/words_b2/maľba.jpg" },
            { sk: "umelecká technika", ua: "художня техніка", ru: "художественная техника", img: "/words_b2/umelecká technika.jpg" },
            { sk: "kritika", ua: "критика", ru: "критика", img: "/words_b2/kritika.jpg" },
        ],
    },
    {
        id: "b2-42",
        title: { ua: "Урок 42 — Архітектура", ru: "Урок 42 — Архитектура" },
        words: [
            { sk: "architektúra", ua: "архітектура", ru: "архитектура", img: "/words_b2/architektúra.jpg" },
            { sk: "stavba", ua: "будівля", ru: "здание", img: "/words_b2/stavba.jpg" },
            { sk: "mrakodrap", ua: "хмарочос", ru: "небоскрёб", img: "/words_b2/mrakodrap.jpg" },
            { sk: "most", ua: "міст", ru: "мост", img: "/words_b2/most.jpg" },
            { sk: "historická budova", ua: "історична будівля", ru: "историческое здание", img: "/words_b2/historická budova.jpg" },
            { sk: "moderná architektúra", ua: "сучасна архітектура", ru: "современная архитектура", img: "/words_b2/moderná architektúra.jpg" },
            { sk: "fasáda", ua: "фасад", ru: "фасад", img: "/words_b2/fasáda.jpg" },
            { sk: "veža", ua: "вежа", ru: "башня", img: "/words_b2/veža.jpg" },
            { sk: "projekt", ua: "проєкт", ru: "проект", img: "/words_b2/projekt.jpg" },
            { sk: "architekt", ua: "архітектор", ru: "архитектор", img: "/words_b2/architekt.jpg" },
        ],
    },
    {
        id: "b2-43",
        title: { ua: "Урок 43 — Атмосферні явища", ru: "Урок 43 — Атмосферные явления" },
        words: [
            { sk: "oblačnosť", ua: "хмарність", ru: "облачность", img: "/words_b2/oblačnosť.jpg" },
            { sk: "tlak vzduchu", ua: "атмосферний тиск", ru: "атмосферное давление", img: "/words_b2/tlak vzduchu.jpg" },
            { sk: "náhle oteplenie", ua: "раптове потепління", ru: "резкое потепление", img: "/words_b2/náhle oteplenie.jpg" },
            { sk: "oteplenie", ua: "потепління", ru: "потепление", img: "/words_b2/oteplenie.jpg" },
            { sk: "mrholenie", ua: "мряка", ru: "морось", img: "/words_b2/mrholenie.jpg" },
            { sk: "prívalový dážď", ua: "злива", ru: "ливень", img: "/words_b2/prívalový dážď.jpg" },
            { sk: "ľadová vrstva", ua: "крижана кірка", ru: "ледяная корка", img: "/words_b2/ľadová vrstva.jpg" },
            { sk: "snehová pokrývka", ua: "сніговий покрив", ru: "снежный покров", img: "/words_b2/snehová pokrývka.jpg" },
            { sk: "extrémne počasie", ua: "екстремальна погода", ru: "экстремальная погода", img: "/words_b2/extrémne počasie.jpg" },
            { sk: "prudké ochladenie", ua: "різке похолодання", ru: "резкое похолодание", img: "/words_b2/prudké ochladenie.jpg" },
        ],
    },
    {
        id: "b2-44",
        title: { ua: "Урок 44 — Право", ru: "Урок 44 — Право" },
        words: [
            { sk: "legislatíva", ua: "законодавство", ru: "законодательство", img: "/words_b2/legislatíva.jpg" },
            { sk: "trestný čin", ua: "кримінальний злочин", ru: "уголовное преступление", img: "/words_b2/trestný čin.jpg" },
            { sk: "vyšetrovateľ", ua: "слідчий", ru: "следователь", img: "/words_b2/vyšetrovateľ.jpg" },
            { sk: "súd", ua: "суд", ru: "суд", img: "/words_b2/súd.jpg" },
            { sk: "rozsudok", ua: "вирок", ru: "приговор", img: "/words_b2/rozsudok.jpg" },
            { sk: "obvinenie", ua: "обвинувачення", ru: "обвинение", img: "/words_b2/obvinenie.jpg" },
            { sk: "svedok", ua: "свідок", ru: "свидетель", img: "/words_b2/svedok.jpg" },
            { sk: "zločin", ua: "злочин", ru: "преступление", img: "/words_b2/zločin.jpg" },
            { sk: "pokuta", ua: "штраф", ru: "штраф", img: "/words_b2/pokuta.jpg" },
            { sk: "zadržať", ua: "затримати", ru: "задержать", img: "/words_b2/zadržať.jpg" },
        ],
    },
    {
        id: "b2-45",
        title: { ua: "Урок 45 — Навігація", ru: "Урок 45 — Навигация" },
        words: [
            { sk: "kompas", ua: "компас", ru: "компас", img: "/words_b2/kompas.jpg" },
            { sk: "mapa", ua: "карта", ru: "карта", img: "/words_b2/mapa.jpg" },
            { sk: "smer", ua: "напрямок", ru: "направление", img: "/words_b2/smer.jpg" },
            { sk: "sever", ua: "північ", ru: "север", img: "/words_b2/sever.jpg" },
            { sk: "juh", ua: "південь", ru: "юг", img: "/words_b2/juh.jpg" },
            { sk: "východ", ua: "схід", ru: "восток", img: "/words_b2/východ.jpg" },
            { sk: "západ", ua: "захід", ru: "запад", img: "/words_b2/západ.jpg" },
            { sk: "navigácia", ua: "навігація", ru: "навигация", img: "/words_b2/navigácia.jpg" },
            { sk: "určiť polohu", ua: "визначити місцезнаходження", ru: "определить местоположение", img: "/words_b2/určiť polohu.jpg" },
            { sk: "cestovná trasa", ua: "маршрут подорожі", ru: "маршрут путешествия", img: "/words_b2/cestovná trasa.jpg" },
        ],
    },
    {
        id: "b2-46",
        title: { ua: "Урок 46 — Відеоігри", ru: "Урок 46 — Видеоигры" },
        words: [
            { sk: "videohra", ua: "відеогра", ru: "видеоигра", img: "/words_b2/videohra.jpg" },
            { sk: "herná konzola", ua: "ігрова консоль", ru: "игровая консоль", img: "/words_b2/herná konzola.jpg" },
            { sk: "ovládač", ua: "контролер", ru: "контроллер", img: "/words_b2/ovládač.jpg" },
            { sk: "hráč", ua: "гравець", ru: "игрок", img: "/words_b2/hráč.jpg" },
            { sk: "úroveň", ua: "рівень", ru: "уровень", img: "/words_b2/úroveň.jpg" },
            { sk: "misia", ua: "місія", ru: "миссия", img: "/words_b2/misia.jpg" },
            { sk: "postava", ua: "персонаж", ru: "персонаж", img: "/words_b2/postava.jpg" },
            { sk: "herné prostredie", ua: "ігрове середовище", ru: "игровая среда", img: "/words_b2/herné prostredie.jpg" },
            { sk: "multiplayer", ua: "багатокористувацька гра", ru: "мультиплеер", img: "/words_b2/multiplayer.jpg" },
            { sk: "dosiahnuť víťazstvo", ua: "досягти перемоги", ru: "достичь победы", img: "/words_b2/dosiahnuť víťazstvo.jpg" },
        ],
    },
    {
        id: "b2-47",
        title: { ua: "Урок 47 — Космос", ru: "Урок 47 — Космос" },
        words: [
            { sk: "vesmír", ua: "космос", ru: "космос", img: "/words_b2/vesmír.jpg" },
            { sk: "planéta", ua: "планета", ru: "планета", img: "/words_b2/planéta.jpg" },
            { sk: "hviezda", ua: "зірка", ru: "звезда", img: "/words_b2/hviezda.jpg" },
            { sk: "galaxia", ua: "галактика", ru: "галактика", img: "/words_b2/galaxia.jpg" },
            { sk: "raketa", ua: "ракета", ru: "ракета", img: "/words_b2/raketa.jpg" },
            { sk: "astronaut", ua: "астронавт", ru: "астронавт", img: "/words_b2/astronaut.jpg" },
            { sk: "vesmírna stanica", ua: "космічна станція", ru: "космическая станция", img: "/words_b2/vesmírna stanica.jpg" },
            { sk: "orbitálna dráha", ua: "орбіта", ru: "орбита", img: "/words_b2/orbitálna dráha.jpg" },
            { sk: "kozmická misia", ua: "космічна місія", ru: "космическая миссия", img: "/words_b2/kozmická misia.jpg" },
            { sk: "nekonečný vesmír", ua: "безмежний космос", ru: "бесконечный космос", img: "/words_b2/nekonečný vesmír.jpg" },
        ],
    },
    {
        id: "b2-48",
        title: { ua: "Урок 48 — Хімія", ru: "Урок 48 — Химия" },
        words: [
            { sk: "chemický prvok", ua: "хімічний елемент", ru: "химический элемент", img: "/words_b2/chemický prvok.jpg" },
            { sk: "zlúčenina", ua: "сполука", ru: "соединение", img: "/words_b2/zlúčenina.jpg" },
            { sk: "reakcia", ua: "реакція", ru: "реакция", img: "/words_b2/reakcia.jpg" },
            { sk: "laboratórium", ua: "лабораторія", ru: "лаборатория", img: "/words_b2/laboratórium.jpg" },
            { sk: "experiment", ua: "експеримент", ru: "эксперимент", img: "/words_b2/experiment.jpg" },
            { sk: "kyselina", ua: "кислота", ru: "кислота", img: "/words_b2/kyselina.jpg" },
            { sk: "zásada", ua: "основа (хім.)", ru: "основание", img: "/words_b2/zásada.jpg" },
            { sk: "chemická látka", ua: "хімічна речовина", ru: "химическое вещество", img: "/words_b2/chemická látka.jpg" },
            { sk: "zmes", ua: "суміш", ru: "смесь", img: "/words_b2/zmes.jpg" },
            { sk: "chemická reakcia", ua: "хімічна реакція", ru: "химическая реакция", img: "/words_b2/chemická reakcia.jpg" },
        ],
    },
    {
        id: "b2-49",
        title: { ua: "Урок 49 — Будівництво", ru: "Урок 49 — Строительство" },
        words: [
            { sk: "stavba", ua: "будівництво", ru: "строительство", img: "/words_b2/stavba.jpg" },
            { sk: "stavenisko", ua: "будівельний майданчик", ru: "стройплощадка", img: "/words_b2/stavenisko.jpg" },
            { sk: "tehla", ua: "цегла", ru: "кирпич", img: "/words_b2/tehla.jpg" },
            { sk: "betón", ua: "бетон", ru: "бетон", img: "/words_b2/betón.jpg" },
            { sk: "žeriav", ua: "кран", ru: "кран", img: "/words_b2/žeriav.jpg" },
            { sk: "lešenie", ua: "риштування", ru: "строительные леса", img: "/words_b2/lešenie.jpg" },
            { sk: "stavebný materiál", ua: "будівельний матеріал", ru: "строительный материал", img: "/words_b2/stavebný materiál.jpg" },
            { sk: "základ stavby", ua: "фундамент", ru: "фундамент", img: "/words_b2/základ stavby.jpg" },
            { sk: "strecha", ua: "дах", ru: "крыша", img: "/words_b2/strecha.jpg" },
            { sk: "stavebný projekt", ua: "будівельний проєкт", ru: "строительный проект", img: "/words_b2/stavebný projekt.jpg" },
        ],
    },
    {
        id: "b2-50",
        title: { ua: "Урок 50 — Інструменти", ru: "Урок 50 — Инструменты" },
        words: [
            { sk: "náradie", ua: "інструменти", ru: "инструменты", img: "/words_b2/náradie.jpg" },
            { sk: "kladivo", ua: "молоток", ru: "молоток", img: "/words_b2/kladivo.jpg" },
            { sk: "skrutkovač", ua: "викрутка", ru: "отвёртка", img: "/words_b2/skrutkovač.jpg" },
            { sk: "kľúč", ua: "гайковий ключ", ru: "гаечный ключ", img: "/words_b2/kľúč.jpg" },
            { sk: "píla", ua: "пила", ru: "пила", img: "/words_b2/píla.jpg" },
            { sk: "vŕtačka", ua: "дриль", ru: "дрель", img: "/words_b2/vŕtačka.jpg" },
            { sk: "klince", ua: "цвяхи", ru: "гвозди", img: "/words_b2/klince.jpg" },
            { sk: "skrutky", ua: "гвинти", ru: "винты", img: "/words_b2/skrutky.jpg" },
            { sk: "merať", ua: "вимірювати", ru: "измерять", img: "/words_b2/merať.jpg" },
            { sk: "opraviť", ua: "полагодити", ru: "починить", img: "/words_b2/opraviť.jpg" },
        ],
    },
];