import type { Lesson } from "../data";

export const CS_A0_SOURCE: Lesson[] = [
  {
    id: "1",
    title: { ua: "Урок 1 — Базові слова", ru: "Урок 1 — Базовые слова", en: "Lesson 1 — Basic Words" },
    words: [
      { sk: "dům", ua: "дім", ru: "дом", en: "house", img: "/words/dom.jpg", imgCredit: "Wikimedia Commons (CC BY-SA)" },
      { sk: "auto", ua: "авто", ru: "авто", en: "car", img: "/words/car.jpg", imgCredit: "Photo: Richard Smith, CC BY 2.0 (Wikimedia Commons)" },
      { sk: "voda", ua: "вода", ru: "вода", en: "water", img: "/words/water.jpg", imgCredit: "Photo: Roger McLassus, CC BY-SA 3.0 (Wikimedia Commons)" },
      { sk: "chléb", ua: "хліб", ru: "хлеб", en: "bread", img: "/words/bread.jpg", imgCredit: "Photo: Dmitry Makeev, CC BY-SA 4.0 (Wikimedia Commons)" },
      { sk: "škola", ua: "школа", ru: "школа", en: "school", img: "/words/school.jpg", imgCredit: "Photo: G. Edward Johnson, CC BY 4.0 (Wikimedia Commons)" },
      { sk: "město", ua: "місто", ru: "город", en: "city", img: "/words/city.jpg", imgCredit: "Photo: Daniel Schwen, CC BY-SA 2.5 (Wikimedia Commons)" },
      { sk: "čas", ua: "час", ru: "время", en: "time", img: "/words/čas.jpg", imgCredit: "Public Domain (Wikimedia Commons)" },
      { sk: "den", ua: "день", ru: "день", en: "day", img: "/words/day.jpg", imgCredit: "Photo: Basile Morin, CC BY-SA 4.0 (Wikimedia Commons)" },
      { sk: "dobrý", ua: "добрий", ru: "хороший", en: "good", img: "/words/good.jpg", imgCredit: "Wikimedia Commons" },
      { sk: "peníze", ua: "гроші", ru: "деньги", en: "money", img: "/words_a0_cz/peníze.jpg" },
    ],
  },
  {
    id: "2",
    title: { ua: "Урок 2 — люди", ru: "Урок 2 — люди", en: "Lesson 2 — People" },
    words: [
      { sk: "člověk", ua: "людина", ru: "человек", en: "person", img: "/words_a0_cz/člověk.jpg" },
      { sk: "muž", ua: "чоловік", ru: "мужчина", en: "man", img: "/words_a0_cz/muž.jpg" },
      { sk: "žena", ua: "жінка", ru: "женщина", en: "woman", img: "/words/woman.jpg", imgCredit: "Wikimedia Commons" },
      { sk: "dítě", ua: "дитина", ru: "ребёнок", en: "child", img: "/words/child.jpg", imgCredit: "Photo: Arkady Zarubin, CC BY-SA 3.0 (Wikimedia Commons)" },
      { sk: "kamarád", ua: "друг", ru: "друг", en: "male friend", img: "/words/male-friend.jpg", imgCredit: "Photo: Random Institute (Unsplash License)" },
      { sk: "kamarádka", ua: "подруга", ru: "подруга", en: "female friend", img: "/words/female-friend.jpg", imgCredit: "Photo: John Doe, Unsplash" },
      { sk: "otec", ua: "батько", ru: "отец", en: "father", img: "/words/father.jpg", imgCredit: "Photo: Derek Thomson (Unsplash License)" },
      { sk: "matka", ua: "мати", ru: "мать", en: "mother", img: "/words/mother.jpg" },
      { sk: "bratr", ua: "брат", ru: "брат", en: "brother", img: "/words/brother.jpg" },
      { sk: "sestra", ua: "сестра", ru: "сестра", en: "sister", img: "/words/sister.jpg" },
    ],
  },
  {
    id: "3",
    title: { ua: "Урок 3 — дім", ru: "Урок 3 — дом", en: "Lesson 3 — Home" },
    words: [
      { sk: "byt", ua: "квартира", ru: "квартира", en: "apartment", img: "/words/bytt.jpg" },
      { sk: "pokoj", ua: "кімната", ru: "комната", en: "room", img: "/words/izba.jpg" },
      { sk: "kuchyně", ua: "кухня", ru: "кухня", en: "kitchen", img: "/words/kuchyňa.jpg" },
      { sk: "koupelna", ua: "ванна кімната", ru: "ванная", en: "bathroom", img: "/words/kúpeľňa.jpg" },
      { sk: "dveře", ua: "двері", ru: "дверь", en: "door", img: "/words/dvere.jpg" },
      { sk: "okno", ua: "вікно", ru: "окно", en: "window", img: "/words/okno.jpg" },
      { sk: "stůl", ua: "стіл", ru: "стол", en: "table", img: "/words/stôl.jpg" },
      { sk: "židle", ua: "стілець", ru: "стул", en: "chair", img: "/words/stolička.jpg" },
      { sk: "postel", ua: "ліжко", ru: "кровать", en: "bed", img: "/words/posteľ.jpg" },
      { sk: "skříň", ua: "шафа", ru: "шкаф", en: "wardrobe", img: "/words/skriňa.jpg" },
    ],
  },
  {
    id: "4",
    title: { ua: "Урок 4 — магазин", ru: "Урок 4 — магазин", en: "Lesson 4 — Shop" },
    words: [
      { sk: "obchod", ua: "магазин", ru: "магазин", en: "shop", img: "/words/obchod.jpg" },
      { sk: "kasa", ua: "каса", ru: "касса", en: "cash register", img: "/words/cena.jpg" },
      { sk: "cena", ua: "ціна", ru: "цена", en: "price", img: "/words_a0_cz/cena.jpg" },
      { sk: "sleva", ua: "знижка", ru: "скидка", en: "discount", img: "/words/zľava.jpg" },
      { sk: "taška", ua: "пакет/сумка", ru: "пакет/сумка", en: "bag", img: "/words/taška.jpg" },
      { sk: "účtenka", ua: "чек", ru: "чек", en: "receipt", img: "/words/blok.jpg" },
      { sk: "hotovost", ua: "готівка", ru: "наличные", en: "cash", img: "/words/hotovosť.jpg" },
      { sk: "karta", ua: "картка", ru: "карта", en: "card", img: "/words/karta.jpg" },
      { sk: "koupit", ua: "купити", ru: "купить", en: "buy", img: "/words/kupiť.jpg" },
      { sk: "platit", ua: "платити", ru: "платить", en: "pay", img: "/words_a0_cz/platit.jpg" },
    ],
  },
  {
    id: "5",
    title: { ua: "Урок 5 — Їжа та напої", ru: "Урок 5 — Еда и напитки", en: "Lesson 5 — Food and Drinks" },
    words: [
      { sk: "jídlo", ua: "їжа", ru: "еда", en: "food", img: "/words/jedlo.jpg" },
      { sk: "nápoj", ua: "напій", ru: "напиток", en: "drink", img: "/words/nápoj.jpg" },
      { sk: "chléb", ua: "хліб", ru: "хлеб", en: "bread", img: "/words/chlieb.jpg" },
      { sk: "maso", ua: "м'ясо", ru: "мясо", en: "meat", img: "/words/mäso.jpg" },
      { sk: "polévka", ua: "суп", ru: "суп", en: "soup", img: "/words/polievka.jpg" },
      { sk: "ovoce", ua: "фрукти", ru: "фрукты", en: "fruit", img: "/words_a0_cz/ovoce.jpg" },
      { sk: "zelenina", ua: "овочі", ru: "овощи", en: "vegetables", img: "/words/zelenina.jpg" },
      { sk: "voda", ua: "вода", ru: "вода", en: "water", img: "/words/water.jpg" },
      { sk: "káva", ua: "кава", ru: "кофе", en: "coffee", img: "/words/káva.jpg" },
      { sk: "čaj", ua: "чай", ru: "чай", en: "tea", img: "/words/čaj.jpg" },
    ],
  },
  {
    id: "6",
    title: { ua: "Місто", ru: "Місто", en: "City" },
    words: [
      { sk: "město", ua: "місто", ru: "город", en: "city", img: "/words/mesto.jpg" },
      { sk: "ulice", ua: "вулиця", ru: "улица", en: "street", img: "/words/ulica.jpg" },
      { sk: "náměstí", ua: "площа", ru: "площадь", en: "square", img: "/words/námestie.jpg" },
      { sk: "dům", ua: "будинок", ru: "дом", en: "house", img: "/words/dom.jpg" },
      { sk: "byt", ua: "квартира", ru: "квартира", en: "apartment", img: "/words/bytt.jpg" },
      { sk: "škola", ua: "школа", ru: "школа", en: "school", img: "/words/school.jpg" },
      { sk: "nemocnice", ua: "лікарня", ru: "больница", en: "hospital", img: "/words/nemocnica.jpg" },
      { sk: "zastávka", ua: "зупинка", ru: "остановка", en: "stop", img: "/words/zastávka.jpg" },
      { sk: "park", ua: "парк", ru: "парк", en: "park", img: "/words/park.jpg" },
      { sk: "nádraží", ua: "станція/вокзал", ru: "станция / вокзал", en: "station / railway station", img: "/words/stanica.jpg" },
    ],
  },
  {
    id: "7",
    title: { ua: "Транспорт", ru: "Транспорт", en: "Transport" },
    words: [
      { sk: "doprava", ua: "транспорт", ru: "транспорт", en: "transport", img: "/words/doprava.jpg" },
      { sk: "auto", ua: "авто", ru: "авто", en: "car", img: "/words/car.jpg" },
      { sk: "autobus", ua: "автобус", ru: "автобус", en: "bus", img: "/words/autobus.jpg" },
      { sk: "vlak", ua: "поїзд", ru: "поезд", en: "train", img: "/words/vlak.jpg" },
      { sk: "tramvaj", ua: "трамвай", ru: "трамвай", en: "tram", img: "/words/električka.jpg" },
      { sk: "metro", ua: "метро", ru: "метро", en: "metro", img: "/words_a0_cz/metro.jpg" },
      { sk: "taxi", ua: "таксі", ru: "такси", en: "taxi", img: "/words/taxík.jpg" },
      { sk: "zastávka", ua: "зупинка", ru: "остановка", en: "stop", img: "/words/zastávka.jpg" },
      { sk: "lístek", ua: "квиток", ru: "билет", en: "ticket", img: "/words/lístok.jpg" },
      { sk: "letiště", ua: "аеропорт", ru: "аэропорт", en: "airport", img: "/words/letisko.jpg" },
    ],
  },
  {
    id: "8",
    title: { ua: "Час і дні", ru: "Час і дні", en: "Time and Days" },
    words: [
      { sk: "čas", ua: "час", ru: "время", en: "time", img: "/words/čas.jpg" },
      { sk: "den", ua: "день", ru: "день", en: "day", img: "/words/day.jpg" },
      { sk: "noc", ua: "ніч", ru: "ночь", en: "night", img: "/words/noc.jpg" },
      { sk: "týden", ua: "тиждень", ru: "неделя", en: "week", img: "/words/týždeň.jpg" },
      { sk: "měsíc", ua: "місяць", ru: "месяц", en: "month", img: "/words/mesiac.jpg" },
      { sk: "rok", ua: "рік", ru: "год", en: "year", img: "/words/rok.jpg" },
      { sk: "dnes", ua: "сьогодні", ru: "сегодня", en: "today", img: "/words/dnes.jpg" },
      { sk: "zítra", ua: "завтра", ru: "завтра", en: "tomorrow", img: "/words_a0_cz/zítra.jpg" },
      { sk: "včera", ua: "вчора", ru: "вчера", en: "yesterday", img: "/words/včera.jpg" },
      { sk: "hodina", ua: "година", ru: "час / час (ед.)", en: "hour", img: "/words/hodina.jpg" },
    ],
  },
  {
    id: "9",
    title: { ua: "Робота", ru: "Робота", en: "Work" },
    words: [
      { sk: "práce", ua: "робота", ru: "работа", en: "work", img: "/words/práca.jpg" },
      { sk: "zaměstnání", ua: "зайнятість / робота", ru: "занятость / работа", en: "employment / job", img: "/words_a0_cz/zaměstnání.jpg" },
      { sk: "firma", ua: "фірма", ru: "фирма", en: "company", img: "/words/firma.jpg" },
      { sk: "šéf", ua: "начальник", ru: "начальник", en: "boss", img: "/words/šéf.jpg" },
      { sk: "kolega", ua: "колега", ru: "коллега", en: "colleague", img: "/words/kolega.jpg" },
      { sk: "mzda", ua: "зарплата", ru: "зарплата", en: "salary / wage", img: "/words/hotovosť.jpg" },
      { sk: "smlouva", ua: "договір", ru: "договор", en: "contract", img: "/words/kolega.jpg" },
      { sk: "pracovat", ua: "працювати", ru: "работать", en: "work", img: "/words/pracovať.jpg" },
      { sk: "brigáda", ua: "підробіток", ru: "подработка", en: "part-time job", img: "/words/brigáda.jpg" },
      { sk: "dovolená", ua: "відпустка", ru: "отпуск", en: "vacation / holiday", img: "/words/dovolenka.jpg" },
    ],
  },
  {
    id: "10",
    title: { ua: "Школа", ru: "Школа", en: "School" },
    words: [
      { sk: "škola", ua: "школа", ru: "школа", en: "school", img: "/words/school.jpg" },
      { sk: "žák", ua: "учень", ru: "ученик", en: "pupil", img: "/words/žiak.jpg" },
      { sk: "učitel", ua: "вчитель", ru: "учитель", en: "teacher", img: "/words/učiteľ.jpg" },
      { sk: "třída", ua: "клас", ru: "класс", en: "classroom / class", img: "/words/trieda.jpg" },
      { sk: "předmět", ua: "предмет", ru: "предмет", en: "subject", img: "/words/predmet.jpg" },
      { sk: "hodina", ua: "урок", ru: "урок", en: "lesson", img: "/words/hodina.jpg" },
      { sk: "úloha", ua: "завдання / домашня робота", ru: "задание / домашняя работа", en: "task / homework", img: "/words/úloha.jpg" },
      { sk: "test", ua: "тест", ru: "тест", en: "test", img: "/words/test.jpg" },
      { sk: "sešit", ua: "зошит", ru: "тетрадь", en: "notebook", img: "/words_a0_cz/sešit.jpg" },
      { sk: "učebnice", ua: "підручник", ru: "учебник", en: "textbook", img: "/words_a0_cz/učebnice.jpg" },
    ],
  },
  {
    id: "11",
    title: { ua: "Числа", ru: "Числа", en: "Numbers" },
    words: [
      { sk: "nula", ua: "нуль", ru: "ноль", en: "zero", img: "/words/nula.jpg" },
      { sk: "jeden", ua: "один", ru: "один", en: "one", img: "/words/jeden.jpg" },
      { sk: "dva", ua: "два", ru: "два", en: "two", img: "/words/dva.jpg" },
      { sk: "tři", ua: "три", ru: "три", en: "three", img: "/words/tri.jpg" },
      { sk: "čtyři", ua: "чотири", ru: "четыре", en: "four", img: "/words/štyri.jpg" },
      { sk: "pět", ua: "п’ять", ru: "пять", en: "five", img: "/words/päť.jpg" },
      { sk: "šest", ua: "шість", ru: "шесть", en: "six", img: "/words_a0_cz/šest.jpg" },
      { sk: "sedm", ua: "сім", ru: "семь", en: "seven", img: "/words/sedem.jpg" },
      { sk: "osm", ua: "вісім", ru: "восемь", en: "eight", img: "/words/osem.jpg" },
      { sk: "devět", ua: "дев’ять", ru: "девять", en: "nine", img: "/words/deväť.jpg" },
    ],
  },
  {
    id: "12",
    title: { ua: "Кольори", ru: "Кольори", en: "Colors" },
    words: [
      { sk: "barva", ua: "колір", ru: "цвет", en: "color", img: "/words_a0_cz/barva.jpg" },
      { sk: "bílý", ua: "білий", ru: "белый", en: "white", img: "/words/biely.jpg" },
      { sk: "černý", ua: "чорний", ru: "чёрный", en: "black", img: "/words_a0_cz/černý.jpg" },
      { sk: "červený", ua: "червоний", ru: "красный", en: "red", img: "/words/červený.jpg" },
      { sk: "modrý", ua: "синій", ru: "синий", en: "blue", img: "/words/modrý.jpg" },
      { sk: "zelený", ua: "зелений", ru: "зелёный", en: "green", img: "/words/zelený.jpg" },
      { sk: "žlutý", ua: "жовтий", ru: "жёлтый", en: "yellow", img: "/words_a0_cz/žlutý.jpg" },
      { sk: "oranžový", ua: "помаранчевий", ru: "оранжевый", en: "orange", img: "/words/oranžový.jpg" },
      { sk: "růžový", ua: "рожевий", ru: "розовый", en: "pink", img: "/words_a0_cz/růžový.jpg" },
      { sk: "hnědý", ua: "коричневий", ru: "коричневый", en: "brown", img: "/words_a0_cz/hnědý.jpg" },
    ],
  },
  {
    id: "13",
    title: { ua: "Одяг", ru: "Одяг", en: "Clothes" },
    words: [
      { sk: "oblečení", ua: "одяг", ru: "одежда", en: "clothes", img: "/words/oblečenie.jpg" },
      { sk: "triko", ua: "футболка", ru: "футболка", en: "T-shirt", img: "/words_a0_cz/triko.jpg" },
      { sk: "kalhoty", ua: "штани", ru: "брюки", en: "trousers", img: "/words/nohavice.jpg" },
      { sk: "bunda", ua: "куртка", ru: "куртка", en: "jacket", img: "/words/bunda.jpg" },
      { sk: "boty", ua: "взуття", ru: "обувь", en: "shoes / footwear", img: "/words/topánky.jpg" },
      { sk: "kabát", ua: "пальто", ru: "пальто", en: "coat", img: "/words/kabát.jpg" },
      { sk: "šaty", ua: "сукня", ru: "платье", en: "dress", img: "/words/šaty.jpg" },
      { sk: "čepice", ua: "шапка", ru: "шапка", en: "hat / cap", img: "/words_a0_cz/čepice.jpg" },
      { sk: "ponožky", ua: "шкарпетки", ru: "носки", en: "socks", img: "/words/ponožky.jpg" },
      { sk: "svetr", ua: "светр", ru: "свитер", en: "sweater", img: "/words_a0_cz/svetr.jpg" },
    ],
  },
  {
    id: "14",
    title: { ua: "Тіло людини", ru: "Тіло людини", en: "Human Body" },
    words: [
      { sk: "tělo", ua: "тіло", ru: "тело", en: "body", img: "/words_a0_cz/tělo.jpg" },
      { sk: "hlava", ua: "голова", ru: "голова", en: "head", img: "/words/hlava.jpg" },
      { sk: "oko", ua: "око", ru: "глаз", en: "eye", img: "/words/oko.jpg" },
      { sk: "nos", ua: "ніс", ru: "нос", en: "nose", img: "/words/nos.jpg" },
      { sk: "ústa", ua: "рот", ru: "рот", en: "mouth", img: "/words/ústa.jpg" },
      { sk: "ruka", ua: "рука", ru: "рука", en: "hand / arm", img: "/words/ruka.jpg" },
      { sk: "noha", ua: "нога", ru: "нога", en: "leg", img: "/words/noha.jpg" },
      { sk: "záda", ua: "спина", ru: "спина", en: "back", img: "/words_a0_cz/záda.jpg" },
      { sk: "břicho", ua: "живіт", ru: "живот", en: "belly / stomach", img: "/words_a0_cz/břicho.jpg" },
      { sk: "srdce", ua: "серце", ru: "сердце", en: "heart", img: "/words/srdce.jpg" },
    ],
  },
  {
    id: "15",
    title: { ua: "Здоров’я", ru: "Здоров’я", en: "Health" },
    words: [
      { sk: "zdraví", ua: "здоров’я", ru: "здоровье", en: "health", img: "/words_a0_cz/zdraví.jpg" },
      { sk: "choroba", ua: "хвороба", ru: "болезнь", en: "illness", img: "/words/choroba.jpg" },
      { sk: "lékař", ua: "лікар", ru: "врач", en: "doctor", img: "/words/lekár.jpg" },
      { sk: "nemocnice", ua: "лікарня", ru: "больница", en: "hospital", img: "/words/nemocnica.jpg" },
      { sk: "lék", ua: "ліки", ru: "лекарство / лекарства", en: "medicine", img: "/words_a0_cz/lék.jpg" },
      { sk: "bolest", ua: "біль", ru: "боль", en: "pain", img: "/words_a0_cz/bolest.jpg" },
      { sk: "teplota", ua: "температура", ru: "температура", en: "temperature", img: "/words/teplota.jpg" },
      { sk: "kašel", ua: "кашель", ru: "кашель", en: "cough", img: "/words_a0_cz/kašel.jpg" },
      { sk: "nachlazení", ua: "застуда", ru: "простуда", en: "cold", img: "/words_a0_cz/nachlazení.jpg" },
      { sk: "uzdravit se", ua: "одужати", ru: "выздороветь", en: "recover / get better", img: "/words_a0_cz/uzdravit se.jpg" },
    ],
  },
  {
    id: "16",
    title: { ua: "Погода", ru: "Погода", en: "Weather" },
    words: [
      { sk: "počasí", ua: "погода", ru: "погода", en: "weather", img: "/words_a0_cz/počasí.jpg" },
      { sk: "slunce", ua: "сонце", ru: "солнце", en: "sun", img: "/words_a0_cz/slunce.jpg" },
      { sk: "déšť", ua: "дощ", ru: "дождь", en: "rain", img: "/words_a0_cz/déšť.jpg" },
      { sk: "sníh", ua: "сніг", ru: "снег", en: "snow", img: "/words_a0_cz/sníh.jpg" },
      { sk: "vítr", ua: "вітер", ru: "ветер", en: "wind", img: "/words_a0_cz/vítr.jpg" },
      { sk: "mrak", ua: "хмара", ru: "облако", en: "cloud", img: "/words_a0_cz/mrak.jpg" },
      { sk: "teplo", ua: "тепло", ru: "тепло", en: "warmth", img: "/words/teplo.jpg" },
      { sk: "zima", ua: "холод", ru: "холод", en: "cold", img: "/words/zima.jpg" },
      { sk: "bouře", ua: "буря", ru: "буря / гроза", en: "storm", img: "/words_a0_cz/bouře.jpg" },
      { sk: "teplota", ua: "температура", ru: "температура", en: "temperature", img: "/words/teplota.jpg" },
    ],
  },
  {
    id: "17",
    title: { ua: "Природа", ru: "Природа", en: "Nature" },
    words: [
      { sk: "příroda", ua: "природа", ru: "природа", en: "nature", img: "/words_a0_cz/příroda.jpg" },
      { sk: "strom", ua: "дерево", ru: "дерево", en: "tree", img: "/words/strom.jpg" },
      { sk: "les", ua: "ліс", ru: "лес", en: "forest", img: "/words/les.jpg" },
      { sk: "řeka", ua: "річка", ru: "река", en: "river", img: "/words_a0_cz/řeka.jpg" },
      { sk: "jezero", ua: "озеро", ru: "озеро", en: "lake", img: "/words/jazero.jpg" },
      { sk: "hora", ua: "гора", ru: "гора", en: "mountain", img: "/words/hora.jpg" },
      { sk: "květina", ua: "квітка", ru: "цветок", en: "flower", img: "/words_a0_cz/květina.jpg" },
      { sk: "tráva", ua: "трава", ru: "трава", en: "grass", img: "/words/tráva.jpg" },
      { sk: "zvíře", ua: "тварина", ru: "животное", en: "animal", img: "/words_a0_cz/zvíře.jpg" },
      { sk: "země", ua: "земля", ru: "земля", en: "earth / ground", img: "/words_a0_cz/země.jpg" },
    ],
  },
  {
    id: "18",
    title: { ua: "Побут", ru: "Побут", en: "Household" },
    words: [
      { sk: "domácnost", ua: "побут", ru: "быт", en: "household", img: "/words/domácnosť.jpg" },
      { sk: "dům", ua: "дім", ru: "дом", en: "house", img: "/words/dom.jpg" },
      { sk: "byt", ua: "квартира", ru: "квартира", en: "apartment", img: "/words/bytt.jpg" },
      { sk: "pokoj", ua: "кімната", ru: "комната", en: "room", img: "/words/izba.jpg" },
      { sk: "postel", ua: "ліжко", ru: "кровать", en: "bed", img: "/words/posteľ.jpg" },
      { sk: "stůl", ua: "стіл", ru: "стол", en: "table", img: "/words/stôl.jpg" },
      { sk: "židle", ua: "стілець", ru: "стул", en: "chair", img: "/words/stolička.jpg" },
      { sk: "kuchyně", ua: "кухня", ru: "кухня", en: "kitchen", img: "/words/kuchyňa.jpg" },
      { sk: "lednička", ua: "холодильник", ru: "холодильник", en: "fridge", img: "/words_a0_cz/lednička.jpg" },
      { sk: "uklízet", ua: "прибирати", ru: "убирать / прибираться", en: "clean / tidy up", img: "/words_a0_cz/uklízet.jpg" },
    ],
  },
  {
    id: "19",
    title: { ua: "Дії та дієслова", ru: "Дії та дієслова", en: "Actions and Verbs" },
    words: [
      { sk: "dělat", ua: "робити", ru: "делать", en: "do / make", img: "/words_a0_cz/dělat.jpg" },
      { sk: "jít", ua: "йти", ru: "идти", en: "go / walk", img: "/words_a0_cz/jít.jpg" },
      { sk: "přijít", ua: "прийти", ru: "прийти", en: "come / arrive", img: "/words_a0_cz/přijít.jpg" },
      { sk: "vidět", ua: "бачити", ru: "видеть", en: "see", img: "/words_a0_cz/vidět.jpg" },
      { sk: "mluvit", ua: "говорити", ru: "говорить", en: "speak", img: "/words_a0_cz/mluvit.jpg" },
      { sk: "jíst", ua: "їсти", ru: "есть", en: "eat", img: "/words_a0_cz/jíst.jpg" },
      { sk: "pít", ua: "пити", ru: "пить", en: "drink", img: "/words/piť.jpg" },
      { sk: "spát", ua: "спати", ru: "спать", en: "sleep", img: "/words_a0_cz/spát.jpg" },
      { sk: "pracovat", ua: "працювати", ru: "работать", en: "work", img: "/words/pracovať.jpg" },
      { sk: "učit se", ua: "вчитися", ru: "учиться", en: "study / learn", img: "/words_a0_cz/učit se.jpg" },
    ],
  },
  {
    id: "20",
    title: { ua: "Питання і відповіді", ru: "Питання і відповіді", en: "Questions and Answers" },
    words: [
      { sk: "kdo", ua: "хто", ru: "кто", en: "who", img: "/words_a0_cz/kdo.jpg" },
      { sk: "co", ua: "що", ru: "что", en: "what", img: "/words_a0_cz/co.jpg" },
      { sk: "kde", ua: "де", ru: "где", en: "where", img: "/words/kde.jpg" },
      { sk: "kdy", ua: "коли", ru: "когда", en: "when", img: "/words_a0_cz/kdy.jpg" },
      { sk: "proč", ua: "чому", ru: "почему", en: "why", img: "/words_a0_cz/proč.jpg" },
      { sk: "jak", ua: "як", ru: "как", en: "how", img: "/words_a0_cz/jak.jpg" },
      { sk: "kolik", ua: "скільки", ru: "сколько", en: "how much / how many", img: "/words/koľko.jpg" },
      { sk: "ano", ua: "так", ru: "да", en: "yes", img: "/words_a0_cz/ano.jpg" },
      { sk: "ne", ua: "ні", ru: "нет", en: "no", img: "/words_a0_cz/ne.jpg" },
      { sk: "možná", ua: "можливо", ru: "возможно", en: "maybe", img: "/words_a0_cz/možná.jpg" },
    ],
  },
  {
    id: "21",
    title: { ua: "Місця", ru: "Місця", en: "Places" },
    words: [
      { sk: "místo", ua: "місце", ru: "место", en: "place", img: "/words/miesto.jpg" },
      { sk: "centrum", ua: "центр", ru: "центр", en: "center", img: "/words/centrum.jpg" },
      { sk: "obchod", ua: "магазин", ru: "магазин", en: "shop", img: "/words/obchod.jpg" },
      { sk: "restaurace", ua: "ресторан", ru: "ресторан", en: "restaurant", img: "/words_a0_cz/restaurace.jpg" },
      { sk: "kavárna", ua: "кафе", ru: "кафе", en: "café", img: "/words_a0_cz/kavárna.jpg" },
      { sk: "park", ua: "парк", ru: "парк", en: "park", img: "/words/park.jpg" },
      { sk: "banka", ua: "банк", ru: "банк", en: "bank", img: "/words/banka.jpg" },
      { sk: "pošta", ua: "пошта", ru: "почта", en: "post office", img: "/words/pošta.jpg" },
      { sk: "policie", ua: "поліція", ru: "полиция", en: "police", img: "/words_a0_cz/policie.jpg" },
      { sk: "nádraží", ua: "станція / вокзал", ru: "станция / вокзал", en: "station / railway station", img: "/words/stanica.jpg" },
    ],
  },
  {
    id: "22",
    title: { ua: "Емоції", ru: "Емоції", en: "Emotions" },
    words: [
      { sk: "radost", ua: "радість", ru: "радость", en: "joy", img: "/words_a0_cz/radost.jpg" },
      { sk: "smutek", ua: "смуток", ru: "грусть / печаль", en: "sadness", img: "/words_a0_cz/smutek.jpg" },
      { sk: "strach", ua: "страх", ru: "страх", en: "fear", img: "/words/strach.jpg" },
      { sk: "hněv", ua: "злість", ru: "злость / гнев", en: "anger", img: "/words_a0_cz/hněv.jpg" },
      { sk: "láska", ua: "любов", ru: "любовь", en: "love", img: "/words/láska.jpg" },
      { sk: "štěstí", ua: "щастя", ru: "счастье", en: "happiness", img: "/words_a0_cz/štěstí.jpg" },
      { sk: "únava", ua: "втома", ru: "усталость", en: "tiredness / fatigue", img: "/words/únava.jpg" },
      { sk: "stres", ua: "стрес", ru: "стресс", en: "stress", img: "/words/stres.jpg" },
      { sk: "klid", ua: "спокій", ru: "покой / спокойствие", en: "calm", img: "/words_a0_cz/klid.jpg" },
      { sk: "překvapení", ua: "здивування", ru: "удивление", en: "surprise", img: "/words_a0_cz/překvapení.jpg" },
    ],
  },
  {
    id: "23",
    title: { ua: "Хобі", ru: "Хобі", en: "Hobbies" },
    words: [
      { sk: "hobby", ua: "хобі", ru: "хобби", en: "hobby", img: "/words/hobby.jpg" },
      { sk: "sport", ua: "спорт", ru: "спорт", en: "sport", img: "/words_a0_cz/sport.jpg" },
      { sk: "fotbal", ua: "футбол", ru: "футбол", en: "football", img: "/words_a0_cz/fotbal.jpg" },
      { sk: "hudba", ua: "музика", ru: "музыка", en: "music", img: "/words/hudba.jpg" },
      { sk: "film", ua: "фільм", ru: "фильм", en: "film", img: "/words/film.jpg" },
      { sk: "čtení", ua: "читання", ru: "чтение", en: "reading", img: "/words_a0_cz/čtení.jpg" },
      { sk: "cestování", ua: "подорожі", ru: "путешествия", en: "traveling", img: "/words_a0_cz/cestování.jpg" },
      { sk: "hra", ua: "гра", ru: "игра", en: "game", img: "/words/hra.jpg" },
      { sk: "malování", ua: "малювання", ru: "рисование", en: "painting / drawing", img: "/words_a0_cz/malování.jpg" },
      { sk: "tanec", ua: "танець", ru: "танец", en: "dance", img: "/words/tanec.jpg" },
    ],
  },
  {
    id: "24",
    title: { ua: "Спілкування", ru: "Спілкування", en: "Communication" },
    words: [
      { sk: "mluvit", ua: "говорити", ru: "говорить", en: "speak", img: "/words_a0_cz/mluvit.jpg" },
      { sk: "vyprávět", ua: "розповідати", ru: "рассказывать", en: "tell / narrate", img: "/words_a0_cz/vyprávět.jpg" },
      { sk: "poslouchat", ua: "слухати", ru: "слушать", en: "listen", img: "/words_a0_cz/poslouchat.jpg" },
      { sk: "ptát se", ua: "питати", ru: "спрашивать", en: "ask", img: "/words_a0_cz/ptát se.jpg" },
      { sk: "odpovědět", ua: "відповідати", ru: "отвечать", en: "answer", img: "/words_a0_cz/odpovědět.jpg" },
      { sk: "telefonovat", ua: "телефонувати", ru: "звонить / разговаривать по телефону", en: "call / talk on the phone", img: "/words_a0_cz/telefonovat.jpg" },
      { sk: "zpráva", ua: "повідомлення", ru: "сообщение", en: "message", img: "/words_a0_cz/zpráva.jpg" },
      { sk: "setkání", ua: "зустріч", ru: "встреча", en: "meeting", img: "/words_a0_cz/setkání.jpg" },
      { sk: "diskuze", ua: "обговорення", ru: "обсуждение / дискуссия", en: "discussion", img: "/words_a0_cz/diskuze.jpg" },
      { sk: "pozdrav", ua: "привітання", ru: "приветствие", en: "greeting", img: "/words/pozdrav.jpg" },
    ],
  },
  {
    id: "25",
    title: { ua: "Подорожі", ru: "Подорожі", en: "Travel" },
    words: [
      { sk: "cesta", ua: "подорож", ru: "путешествие / дорога", en: "trip / journey", img: "/words/cesta.jpg" },
      { sk: "cestovat", ua: "подорожувати", ru: "путешествовать", en: "travel", img: "/words_a0_cz/cestovat.jpg" },
      { sk: "kufr", ua: "валіза", ru: "чемодан", en: "suitcase", img: "/words_a0_cz/kufr.jpg" },
      { sk: "pas", ua: "паспорт", ru: "паспорт", en: "passport", img: "/words/pas.jpg" },
      { sk: "letenka", ua: "авіаквиток", ru: "авиабилет", en: "plane ticket", img: "/words/letenka.jpg" },
      { sk: "vlak", ua: "поїзд", ru: "поезд", en: "train", img: "/words/vlak.jpg" },
      { sk: "autobus", ua: "автобус", ru: "автобус", en: "bus", img: "/words/autobus.jpg" },
      { sk: "letiště", ua: "аеропорт", ru: "аэропорт", en: "airport", img: "/words/letisko.jpg" },
      { sk: "mapa", ua: "карта", ru: "карта", en: "map", img: "/words/mapa.jpg" },
      { sk: "rezervace", ua: "бронювання", ru: "бронирование", en: "reservation", img: "/words_a0_cz/rezervace.jpg" },
    ],
  },
  {
    id: "26",
    title: { ua: "Готель і ресторан", ru: "Готель і ресторан", en: "Hotel and Restaurant" },
    words: [
      { sk: "hotel", ua: "готель", ru: "отель", en: "hotel", img: "/words/hotel.jpg" },
      { sk: "pokoj", ua: "кімната", ru: "комната / номер", en: "room", img: "/words/izba.jpg" },
      { sk: "recepce", ua: "ресепшн", ru: "ресепшн", en: "reception", img: "/words_a0_cz/recepce.jpg" },
      { sk: "restaurace", ua: "ресторан", ru: "ресторан", en: "restaurant", img: "/words_a0_cz/restaurace.jpg" },
      { sk: "menu", ua: "меню", ru: "меню", en: "menu", img: "/words/menu.jpg" },
      { sk: "objednat", ua: "замовити", ru: "заказать", en: "order", img: "/words_a0_cz/objednat.jpg" },
      { sk: "snídaně", ua: "сніданок", ru: "завтрак", en: "breakfast", img: "/words_a0_cz/snídaně.jpg" },
      { sk: "oběd", ua: "обід", ru: "обед", en: "lunch", img: "/words_a0_cz/oběd.jpg" },
      { sk: "večeře", ua: "вечеря", ru: "ужин", en: "dinner", img: "/words_a0_cz/večeře.jpg" },
      { sk: "účet", ua: "рахунок", ru: "счёт", en: "bill", img: "/words/účet.jpg" },
    ],
  },
  {
    id: "27",
    title: { ua: "Гроші", ru: "Гроші", en: "Money" },
    words: [
      { sk: "peníze", ua: "гроші", ru: "деньги", en: "money", img: "/words_a0_cz/peníze.jpg" },
      { sk: "euro", ua: "євро", ru: "евро", en: "euro", img: "/words/euro.jpg" },
      { sk: "cena", ua: "ціна", ru: "цена", en: "price", img: "/words/cena.jpg" },
      { sk: "platba", ua: "платіж", ru: "платёж", en: "payment", img: "/words/platba.jpg" },
      { sk: "hotovost", ua: "готівка", ru: "наличные", en: "cash", img: "/words/hotovosť.jpg" },
      { sk: "karta", ua: "картка", ru: "карта", en: "card", img: "/words/karta.jpg" },
      { sk: "účet", ua: "рахунок", ru: "счёт", en: "bill / account", img: "/words/účet.jpg" },
      { sk: "banka", ua: "банк", ru: "банк", en: "bank", img: "/words/banka.jpg" },
      { sk: "sleva", ua: "знижка", ru: "скидка", en: "discount", img: "/words/zľava.jpg" },
      { sk: "výdaje", ua: "витрати", ru: "расходы", en: "expenses", img: "/words_a0_cz/výdaje.jpg" },
    ],
  },
  {
    id: "28",
    title: { ua: "Технології", ru: "Технології", en: "Technology" },
    words: [
      { sk: "technologie", ua: "технологія", ru: "технология", en: "technology", img: "/words_a0_cz/technologie.jpg" },
      { sk: "počítač", ua: "комп’ютер", ru: "компьютер", en: "computer", img: "/words_a0_cz/počítač.jpg" },
      { sk: "telefon", ua: "телефон", ru: "телефон", en: "phone", img: "/words_a0_cz/telefon.jpg" },
      { sk: "internet", ua: "інтернет", ru: "интернет", en: "internet", img: "/words/internet.jpg" },
      { sk: "aplikace", ua: "додаток", ru: "приложение", en: "app / application", img: "/words_a0_cz/aplikace.jpg" },
      { sk: "program", ua: "програма", ru: "программа", en: "program", img: "/words/program.jpg" },
      { sk: "systém", ua: "система", ru: "система", en: "system", img: "/words/systém.jpg" },
      { sk: "síť", ua: "мережа", ru: "сеть", en: "network", img: "/words_a0_cz/síť.jpg" },
      { sk: "data", ua: "дані", ru: "данные", en: "data", img: "/words_a0_cz/data.jpg" },
      { sk: "heslo", ua: "пароль", ru: "пароль", en: "password", img: "/words/heslo.jpg" },
    ],
  },
  {
    id: "29",
    title: { ua: "Повсякденні фрази", ru: "Повсякденні фрази", en: "Everyday Phrases" },
    words: [
      { sk: "dobrý den", ua: "добрий день", ru: "добрый день", en: "good day / hello", img: "/words_a0_cz/dobrý den.jpg" },
      { sk: "ahoj", ua: "привіт", ru: "привет", en: "hi", img: "/words_a0_cz/ahoj.jpg" },
      { sk: "děkuji", ua: "дякую", ru: "спасибо", en: "thank you", img: "/words_a0_cz/děkuji.jpg" },
      { sk: "prosím", ua: "будь ласка", ru: "пожалуйста", en: "please / you're welcome", img: "/words/prosím.jpg" },
      { sk: "omlouvám se", ua: "перепрошую", ru: "извиняюсь", en: "sorry / excuse me", img: "/words_a0_cz/omlouvám se.jpg" },
      { sk: "rozumím", ua: "розумію", ru: "понимаю", en: "I understand", img: "/words_a0_cz/rozumím.jpg" },
      { sk: "nerozumím", ua: "не розумію", ru: "не понимаю", en: "I don't understand", img: "/words_a0_cz/nerozumím.jpg" },
      { sk: "pomozte", ua: "допоможіть", ru: "помогите", en: "help", img: "/words_a0_cz/pomozte.jpg" },
      { sk: "jasné", ua: "ясно", ru: "ясно", en: "clear / sure", img: "/words_a0_cz/jasné.jpg" },
      { sk: "dobře", ua: "добре", ru: "хорошо", en: "well / okay", img: "/words_a0_cz/dobře.jpg" },
    ],
  },
  {
    id: "30",
    title: { ua: "Повторення бази", ru: "Повторення бази", en: "Basic Review" },
    words: [
      { sk: "já", ua: "я", ru: "я", en: "I", img: "/words_a0_cz/já.jpg" },
      { sk: "ty", ua: "ти", ru: "ты", en: "you", img: "/words/ty.jpg" },
      { sk: "on", ua: "він", ru: "он", en: "he", img: "/words/on.jpg" },
      { sk: "ona", ua: "вона", ru: "она", en: "she", img: "/words/ona.jpg" },
      { sk: "my", ua: "ми", ru: "мы", en: "we", img: "/words/my.jpg" },
      { sk: "vy", ua: "ви", ru: "вы", en: "you (plural/formal)", img: "/words/vy.jpg" },
      { sk: "oni", ua: "вони", ru: "они", en: "they", img: "/words/oni.jpg" },
      { sk: "být", ua: "бути", ru: "быть", en: "to be", img: "/words_a0_cz/být.jpg" },
      { sk: "mít", ua: "мати", ru: "иметь", en: "to have", img: "/words_a0_cz/mít.jpg" },
      { sk: "jít", ua: "йти", ru: "идти", en: "to go", img: "/words_a0_cz/jít.jpg" },
    ],
  },
];