import type { Lesson } from "../data";

export const CS_A2_SOURCE: Lesson[] = [
  {
    id: "a2-1",
    title: { ua: "Урок 1 — Дім і побут (розширено)", ru: "Урок 1 — Дом и быт (расширено)", en: "Lesson 1 — Home and household (extended)" },
    words: [
      { sk: "nájem", ua: "оренда", ru: "аренда", en: "rent", img: "/words_a2_cz/nájem.jpg" },
      { sk: "nájemní smlouva", ua: "договір оренди", ru: "договор аренды", en: "rental agreement", img: "/words_a2_cz/nájemní smlouva.jpg" },
      { sk: "majitel", ua: "власник", ru: "владелец", en: "owner", img: "/words_a2_cz/majitel.jpg" },
      { sk: "podnájemník", ua: "орендар", ru: "арендатор (субарендатор)", en: "subtenant", img: "/words_a2_cz/podnájemník.jpg" },
      { sk: "účty", ua: "рахунки (комунальні)", ru: "счета (коммунальные)", en: "bills (utilities)", img: "/words_a2/účty.jpg" },
      { sk: "energie", ua: "комунальні послуги/енергія", ru: "коммунальные услуги / энергия", en: "utilities / energy", img: "/words_a2/energie.jpg" },
      { sk: "oprava", ua: "ремонт", ru: "ремонт", en: "repair", img: "/words_a2/oprava.jpg" },
      { sk: "pokazený", ua: "зламаний", ru: "сломанный / неисправный", en: "broken / faulty", img: "/words_a2/pokazený.jpg" },
      { sk: "soused", ua: "сусід", ru: "сосед", en: "neighbor", img: "/words_a2_cz/soused.jpg" },
      { sk: "stěhování", ua: "переїзд", ru: "переезд", en: "moving", img: "/words_a2_cz/stěhování.jpg" },
    ],
  },
  {
    id: "a2-2",
    title: { ua: "Урок 2 — У лікаря", ru: "Урок 2 — У врача", en: "Lesson 2 — At the doctor" },
    words: [
      { sk: "vyšetření", ua: "обстеження", ru: "обследование", en: "examination", img: "/words_a2_cz/vyšetření.jpg" },
      { sk: "diagnóza", ua: "діагноз", ru: "диагноз", en: "diagnosis", img: "/words_a2/diagnóza.jpg" },
      { sk: "příznak", ua: "симптом", ru: "симптом", en: "symptom", img: "/words_a2_cz/příznak.jpg" },
      { sk: "bolest v krku", ua: "біль у горлі", ru: "боль в горле", en: "sore throat", img: "/words_a2_cz/bolest v krku.jpg" },
      { sk: "teploměr", ua: "термометр", ru: "термометр", en: "thermometer", img: "/words_a2_cz/teploměr.jpg" },
      { sk: "krvní tlak", ua: "артеріальний тиск", ru: "артериальное давление", en: "blood pressure", img: "/words_a2_cz/krvní tlak.jpg" },
      { sk: "recept", ua: "рецепт (лікарський)", ru: "рецепт (врачебный)", en: "prescription", img: "/words_a2/recept.jpg" },
      { sk: "alergie", ua: "алергія", ru: "аллергия", en: "allergy", img: "/words_a2_cz/alergie.jpg" },
      { sk: "zánět", ua: "запалення", ru: "воспаление", en: "inflammation", img: "/words_a2_cz/zánět.jpg" },
      { sk: "doporučení", ua: "рекомендація", ru: "рекомендация", en: "recommendation", img: "/words_a2_cz/doporučení.jpg" },
    ],
  },
  {
    id: "a2-3",
    title: { ua: "Урок 3 — Місто та послуги", ru: "Урок 3 — Город и услуги", en: "Lesson 3 — City and services" },
    words: [
      { sk: "městský úřad", ua: "міська рада/мерія", ru: "городская администрация / мэрия", en: "city hall / municipal office", img: "/words_a2_cz/městský úřad.jpg" },
      { sk: "oddělení", ua: "відділення/відділ", ru: "отдел / отделение", en: "department / section", img: "/words_a2_cz/oddělení.jpg" },
      { sk: "žadatel", ua: "заявник", ru: "заявитель", en: "applicant", img: "/words_a2_cz/žadatel.jpg" },
      { sk: "žádost", ua: "заява", ru: "заявление", en: "application / request", img: "/words_a2_cz/žádost.jpg" },
      { sk: "doklad", ua: "документ", ru: "документ", en: "document", img: "/words_a2/doklad.jpg" },
      { sk: "potvrzení", ua: "підтвердження/довідка", ru: "подтверждение / справка", en: "confirmation / certificate", img: "/words_a2_cz/potvrzení.jpg" },
      { sk: "poplatek", ua: "збір/плата", ru: "сбор / плата", en: "fee / charge", img: "/words_a2_cz/poplatek.jpg" },
      { sk: "objednat se", ua: "записатися (на прийом)", ru: "записаться (на приём)", en: "make an appointment", img: "/words_a2_cz/objednat se.jpg" },
      { sk: "otevírací hodiny", ua: "години роботи", ru: "часы работы", en: "opening hours", img: "/words_a2_cz/otevírací hodiny.jpg" },
      { sk: "formulář", ua: "бланк/форма", ru: "бланк / форма", en: "form", img: "/words_a2_cz/formulář.jpg" },
    ],
  },
  {
    id: "a2-4",
    title: { ua: "Урок 4 — Робота та карʼєра", ru: "Урок 4 — Работа и карьера", en: "Lesson 4 — Work and career" },
    words: [
      { sk: "pohovor", ua: "співбесіда", ru: "собеседование", en: "job interview", img: "/words_a2/pohovor.jpg" },
      { sk: "životopis", ua: "резюме (CV)", ru: "резюме (CV)", en: "CV / résumé", img: "/words_a2/životopis.jpg" },
      { sk: "praxe", ua: "досвід роботи/практика", ru: "опыт работы / практика", en: "work experience / practice", img: "/words_a2_cz/praxe.jpg" },
      { sk: "zručnost", ua: "навичка", ru: "навык", en: "skill", img: "/words_a2_cz/zručnost.jpg" },
      { sk: "požadavek", ua: "вимога", ru: "требование", en: "requirement", img: "/words_a2_cz/požadavek.jpg" },
      { sk: "pracovní nabídka", ua: "вакансія", ru: "вакансия", en: "job offer / vacancy", img: "/words_a2_cz/pracovní nabídka.jpg" },
      { sk: "pracovní pozice", ua: "посада", ru: "должность", en: "job position", img: "/words_a2_cz/pracovní pozice.jpg" },
      { sk: "odpovědnost", ua: "відповідальність", ru: "ответственность", en: "responsibility", img: "/words_a2_cz/odpovědnost.jpg" },
      { sk: "výhody", ua: "переваги/бонуси", ru: "льготы / бонусы / преимущества", en: "benefits / perks", img: "/words_a2/výhody.jpg" },
      { sk: "zkoušební doba", ua: "випробувальний термін", ru: "испытательный срок", en: "probation period", img: "/words_a2_cz/zkoušební doba.jpg" },
    ],
  },
  {
    id: "a2-5",
    title: { ua: "Урок 5 — Подорожі (ситуації)", ru: "Урок 5 — Путешествия (ситуации)", en: "Lesson 5 — Travel (situations)" },
    words: [
      { sk: "rezervace", ua: "бронювання", ru: "бронирование", en: "reservation", img: "/words_a2_cz/rezervace.jpg" },
      { sk: "ubytování", ua: "проживання", ru: "проживание", en: "accommodation", img: "/words_a2_cz/ubytování.jpg" },
      { sk: "potvrdit", ua: "підтвердити", ru: "подтвердить", en: "confirm", img: "/words_a2_cz/potvrdit.jpg" },
      { sk: "zrušit", ua: "скасувати", ru: "отменить", en: "cancel", img: "/words_a2_cz/zrušit.jpg" },
      { sk: "zpoždění", ua: "затримка", ru: "задержка", en: "delay", img: "/words_a2_cz/zpoždění.jpg" },
      { sk: "přesun", ua: "переміщення/трансфер", ru: "перемещение / трансфер", en: "transfer / move", img: "/words_a2_cz/přesun.jpg" },
      { sk: "jednosměrný", ua: "в один бік", ru: "в одну сторону", en: "one-way", img: "/words_a2_cz/jednosměrný.jpg" },
      { sk: "zpáteční", ua: "туди-й-назад", ru: "туда-обратно", en: "round-trip / return", img: "/words_a2_cz/zpáteční.jpg" },
      { sk: "cestovní pojištění", ua: "туристична страховка", ru: "туристическая страховка", en: "travel insurance", img: "/words_a2_cz/cestovní pojištění.jpg" },
      { sk: "zavazadlo", ua: "багаж", ru: "багаж", en: "luggage", img: "/words_a2_cz/zavazadlo.jpg" },
    ],
  },
  {
    id: "a2-6",
    title: { ua: "Урок 6 — Гроші та фінанси", ru: "Урок 6 — Деньги и финансы", en: "Lesson 6 — Money and finances" },
    words: [
      { sk: "rozpočet", ua: "бюджет", ru: "бюджет", en: "budget", img: "/words_a2/rozpočet.jpg" },
      { sk: "příjem", ua: "дохід", ru: "доход", en: "income", img: "/words_a2_cz/příjem.jpg" },
      { sk: "výdaje", ua: "витрати", ru: "расходы", en: "expenses", img: "/words_a2_cz/výdaje.jpg" },
      { sk: "ušetřit", ua: "заощадити", ru: "сэкономить", en: "save", img: "/words_a2_cz/ušetřit.jpg" },
      { sk: "minout", ua: "витратити", ru: "потратить", en: "spend", img: "/words_a2_cz/minout.jpg" },
      { sk: "převod", ua: "переказ", ru: "перевод", en: "transfer", img: "/words_a2_cz/převod.jpg" },
      { sk: "bankovní účet", ua: "банківський рахунок", ru: "банковский счёт", en: "bank account", img: "/words_a2_cz/bankovní účet.jpg" },
      { sk: "trvalý příkaz", ua: "постійне доручення (автоплатіж)", ru: "постоянное поручение (автоплатёж)", en: "standing order", img: "/words_a2_cz/trvalý příkaz.jpg" },
      { sk: "úrok", ua: "відсоток (interest)", ru: "процент (ставка)", en: "interest", img: "/words_a2/úrok.jpg" },
      { sk: "poplatek", ua: "комісія/збір", ru: "комиссия / сбор", en: "fee / charge", img: "/words_a2/poplatok.jpg" },
    ],
  },
  {
    id: "a2-7",
    title: { ua: "Урок 7 — Комунікація та думки", ru: "Урок 7 — Общение и мысли", en: "Lesson 7 — Communication and opinions" },
    words: [
      { sk: "podle mě", ua: "на мою думку", ru: "по-моему", en: "in my opinion", img: "/words_a2_cz/podle mě.jpg" },
      { sk: "myslím si", ua: "я думаю", ru: "я думаю", en: "I think", img: "/words_a2/myslím si.jpg" },
      { sk: "zdá se mi", ua: "мені здається", ru: "мне кажется", en: "it seems to me", img: "/words_a2_cz/zdá se mi.jpg" },
      { sk: "navrhnout", ua: "запропонувати", ru: "предложить", en: "suggest", img: "/words_a2_cz/navrhnout.jpg" },
      { sk: "shrnout", ua: "підсумувати", ru: "подытожить", en: "summarize", img: "/words_a2_cz/shrnout.jpg" },
      { sk: "vyjádřit názor", ua: "висловити думку", ru: "выразить мнение", en: "express an opinion", img: "/words_a2_cz/vyjádřit názor.jpg" },
      { sk: "argumentovat", ua: "аргументувати", ru: "аргументировать", en: "argue", img: "/words_a2_cz/argumentovat.jpg" },
      { sk: "přesvědčit", ua: "переконати", ru: "убедить", en: "convince", img: "/words_a2_cz/přesvědčit.jpg" },
      { sk: "zmínit", ua: "згадати", ru: "упомянуть", en: "mention", img: "/words_a2_cz/zmínit.jpg" },
      { sk: "reagovat", ua: "реагувати", ru: "реагировать", en: "react", img: "/words_a2_cz/reagovat.jpg" },
    ],
  },
  {
    id: "a2-8",
    title: { ua: "Урок 8 — Час, плани, події", ru: "Урок 8 — Время, планы, события", en: "Lesson 8 — Time, plans, events" },
    words: [
      { sk: "posunout", ua: "перенести (дату/зустріч)", ru: "перенести (дату/встречу)", en: "reschedule / move", img: "/words_a2_cz/posunout.jpg" },
      { sk: "naplánovat", ua: "запланувати", ru: "запланировать", en: "plan", img: "/words_a2_cz/naplánovat.jpg" },
      { sk: "odložit", ua: "відкласти", ru: "отложить", en: "postpone", img: "/words_a2_cz/odložit.jpg" },
      { sk: "zúčastnit se", ua: "взяти участь", ru: "принять участие", en: "take part", img: "/words_a2_cz/zúčastnit se.jpg" },
      { sk: "změnit plán", ua: "змінити план", ru: "изменить план", en: "change the plan", img: "/words_a2_cz/změnit plán.jpg" },
      { sk: "konat se", ua: "відбуватися", ru: "проводиться / происходить", en: "take place", img: "/words_a2_cz/konat se.jpg" },
      { sk: "organizovat", ua: "організувати", ru: "организовать", en: "organize", img: "/words_a2_cz/organizovat.jpg" },
      { sk: "uskutečnit se", ua: "відбутися", ru: "состояться", en: "take place / happen", img: "/words_a2_cz/uskutečnit se.jpg" },
      { sk: "zpozdit se", ua: "запізнюватися", ru: "опаздывать", en: "be late", img: "/words_a2_cz/zpozdit se.jpg" },
      { sk: "stihnout", ua: "встигнути", ru: "успеть", en: "manage in time", img: "/words_a2_cz/stihnout.jpg" },
    ],
  },
  {
    id: "a2-9",
    title: { ua: "Урок 9 — Покупки та рекламації", ru: "Урок 9 — Покупки и рекламации", en: "Lesson 9 — Shopping and complaints" },
    words: [
      { sk: "podmínky", ua: "умови", ru: "условия", en: "conditions / terms", img: "/words_a2_cz/podmínky.jpg" },
      { sk: "stížnost", ua: "скарга", ru: "жалоба", en: "complaint", img: "/words_a2_cz/stížnost.jpg" },
      { sk: "peníze zpět", ua: "гроші назад", ru: "деньги обратно", en: "money back", img: "/words_a2_cz/peníze zpět.jpg" },
      { sk: "vrácení zboží", ua: "повернення товару", ru: "возврат товара", en: "return of goods", img: "/words_a2_cz/vrácení zboží.jpg" },
      { sk: "pokladní blok", ua: "касовий чек", ru: "кассовый чек", en: "receipt", img: "/words_a2_cz/pokladní blok.jpg" },
      { sk: "reklamovat", ua: "подати рекламацію", ru: "подать рекламацию", en: "file a complaint / claim", img: "/words_a2_cz/reklamovat.jpg" },
      { sk: "doklad", ua: "документ / підтвердження", ru: "документ / подтверждение", en: "document / proof", img: "/words_a2/doklad.jpg" },
      { sk: "výmena", ua: "обмін", ru: "обмен", en: "exchange", img: "/words_a2/výmena.jpg" },
      { sk: "lhůta", ua: "термін", ru: "срок", en: "deadline / period", img: "/words_a2_cz/lhůta.jpg" },
      { sk: "náhrada", ua: "компенсація / заміна", ru: "компенсация / замена", en: "compensation / replacement", img: "/words_a2_cz/náhrada.jpg" },
    ],
  },
  {
    id: "a2-10",
    title: { ua: "Урок 10 — Погода і природа (розширено)", ru: "Урок 10 — Погода и природа (расширено)", en: "Lesson 10 — Weather and nature (extended)" },
    words: [
      { sk: "předpověď", ua: "прогноз", ru: "прогноз", en: "forecast", img: "/words_a2_cz/předpověď.jpg" },
      { sk: "polooblačno", ua: "мінлива хмарність", ru: "переменная облачность", en: "partly cloudy", img: "/words_a2/polooblačno.jpg" },
      { sk: "přeháňka", ua: "злива/короткий дощ", ru: "ливень / кратковременный дождь", en: "shower", img: "/words_a2/prehánka.jpg" },
      { sk: "jasno", ua: "ясно", ru: "ясно", en: "clear", img: "/words_a2/jasno.jpg" },
      { sk: "náledí", ua: "ожеледиця", ru: "гололёд", en: "black ice", img: "/words_a2/poľadovica.jpg" },
      { sk: "vlhkost", ua: "вологість", ru: "влажность", en: "humidity", img: "/words_a2/vlhkosť.jpg" },
      { sk: "oblačno", ua: "хмарно", ru: "облачно", en: "cloudy", img: "/words_a2/oblačno.jpg" },
      { sk: "ochladit se", ua: "похолоднішати", ru: "похолодать", en: "get colder", img: "/words_a2/ochladiť sa.jpg" },
      { sk: "oteplit se", ua: "потеплішати", ru: "потеплеть", en: "get warmer", img: "/words_a2/otepliť sa.jpg" },
      { sk: "prudký vítr", ua: "сильний вітер", ru: "сильный ветер", en: "strong wind", img: "/words_a2/prudký vietor.jpg" },
    ],
  },
  {
    id: "a2-11",
    title: { ua: "Урок 11 — Харчування та здорові звички", ru: "Урок 11 — Питание и здоровые привычки", en: "Lesson 11 — Nutrition and healthy habits" },
    words: [
      { sk: "strava", ua: "харчування", ru: "питание", en: "nutrition / diet", img: "/words_a2/strava.jpg" },
      { sk: "zdravé jídlo", ua: "здорова їжа", ru: "здоровая еда", en: "healthy food", img: "/words_a2/zdravé jedlo.jpg" },
      { sk: "nezdravý", ua: "нездоровий", ru: "нездоровый", en: "unhealthy", img: "/words_a2/nezdravé.jpg" },
      { sk: "kalorie", ua: "калорії", ru: "калории", en: "calories", img: "/words_a2/kalórie.jpg" },
      { sk: "vitamíny", ua: "вітаміни", ru: "витамины", en: "vitamins", img: "/words_a2/vitamíny.jpg" },
      { sk: "bílkoviny", ua: "білки", ru: "белки", en: "proteins", img: "/words_a2/bielkoviny.jpg" },
      { sk: "tuky", ua: "жири", ru: "жиры", en: "fats", img: "/words_a2/tuky.jpg" },
      { sk: "cukr", ua: "цукор", ru: "сахар", en: "sugar", img: "/words_a2/cukor.jpg" },
      { sk: "sůl", ua: "сіль", ru: "соль", en: "salt", img: "/words_a2/soľ.jpg" },
      { sk: "hydratace", ua: "гідратація", ru: "гидратация", en: "hydration", img: "/words_a2/hydratácia.jpg" },
    ],
  },
  {
    id: "a2-12",
    title: { ua: "Урок 12 — Спорт і активність", ru: "Урок 12 — Спорт и активность", en: "Lesson 12 — Sports and activity" },
    words: [
      { sk: "trénink", ua: "тренування", ru: "тренировка", en: "training", img: "/words_a2/tréning.jpg" },
      { sk: "cvičit", ua: "тренуватися", ru: "тренироваться / заниматься", en: "exercise", img: "/words_a2/cvičiť.jpg" },
      { sk: "posilovna", ua: "спортзал", ru: "спортзал / тренажёрный зал", en: "gym", img: "/words_a2/posilňovňa.jpg" },
      { sk: "vytrvalost", ua: "витривалість", ru: "выносливость", en: "endurance", img: "/words_a2/vytrvalosť.jpg" },
      { sk: "síla", ua: "сила", ru: "сила", en: "strength", img: "/words_a2/sila.jpg" },
      { sk: "tempo", ua: "темп", ru: "темп", en: "pace", img: "/words_a2/tempo.jpg" },
      { sk: "zahřát se", ua: "розігрітися", ru: "разогреться", en: "warm up", img: "/words_a2/zahriať sa.jpg" },
      { sk: "protáhnout se", ua: "розтягнутися", ru: "растянуться", en: "stretch", img: "/words_a2/natiahnuť sa.jpg" },
      { sk: "zranění", ua: "травма", ru: "травма", en: "injury", img: "/words_a2/zranenie.jpg" },
      { sk: "regenerace", ua: "відновлення", ru: "восстановление", en: "recovery", img: "/words_a2/regenerácia.jpg" },
    ],
  },
  {
    id: "a2-13",
    title: { ua: "Урок 13 — Відносини та спілкування", ru: "Урок 13 — Отношения и общение", en: "Lesson 13 — Relationships and communication" },
    words: [
      { sk: "vztah", ua: "стосунки", ru: "отношения", en: "relationship", img: "/words_a2/vzťah.jpg" },
      { sk: "důvěra", ua: "довіра", ru: "доверие", en: "trust", img: "/words_a2/dôvera.jpg" },
      { sk: "respekt", ua: "повага", ru: "уважение", en: "respect", img: "/words_a2/rešpekt.jpg" },
      { sk: "podpora", ua: "підтримка", ru: "поддержка", en: "support", img: "/words_a2/podpora.jpg" },
      { sk: "hádat se", ua: "сваритися", ru: "ссориться", en: "argue / quarrel", img: "/words_a2/hádať sa.jpg" },
      { sk: "smířit se", ua: "помиритися", ru: "помириться", en: "make up / reconcile", img: "/words_a2/zmieriť sa.jpg" },
      { sk: "dohoda", ua: "домовленість", ru: "договорённость / соглашение", en: "agreement", img: "/words_a2/dohoda.jpg" },
      { sk: "kompromis", ua: "компроміс", ru: "компромисс", en: "compromise", img: "/words_a2/kompromis.jpg" },
      { sk: "upřímný", ua: "щирий", ru: "искренний", en: "sincere", img: "/words_a2/úprimný.jpg" },
      { sk: "trpělivost", ua: "терпіння", ru: "терпение", en: "patience", img: "/words_a2/trpezlivosť.jpg" },
    ],
  },
  {
    id: "a2-14",
    title: { ua: "Урок 14 — Покупки онлайн і доставка", ru: "Урок 14 — Онлайн-покупки и доставка", en: "Lesson 14 — Online shopping and delivery" },
    words: [
      { sk: "objednávka", ua: "замовлення", ru: "заказ", en: "order", img: "/words_a2/objednávka.jpg" },
      { sk: "doručení", ua: "доставка", ru: "доставка", en: "delivery", img: "/words_a2/doručenie.jpg" },
      { sk: "balík", ua: "посилка", ru: "посылка", en: "parcel", img: "/words_a2/balík.jpg" },
      { sk: "kurýr", ua: "кур’єр", ru: "курьер", en: "courier", img: "/words_a2/kuriér.jpg" },
      { sk: "sledování zásilky", ua: "відстеження посилки", ru: "отслеживание посылки", en: "parcel tracking", img: "/words_a2/sledovanie zásielky.jpg" },
      { sk: "doručovací adresa", ua: "адреса доставки", ru: "адрес доставки", en: "delivery address", img: "/words_a2/adresa doručenia.jpg" },
      { sk: "vrácení", ua: "повернення", ru: "возврат", en: "return", img: "/words_a2/vrátenie.jpg" },
      { sk: "výmena", ua: "обмін", ru: "обмен", en: "exchange", img: "/words_a2/výmena.jpg" },
      { sk: "poštovné", ua: "вартість доставки", ru: "стоимость доставки", en: "shipping cost", img: "/words_a2/poštovné.jpg" },
      { sk: "platba kartou", ua: "оплата карткою", ru: "оплата картой", en: "card payment", img: "/words_a2/platba kartou.jpg" },
    ],
  },
  {
    id: "a2-15",
    title: { ua: "Урок 15 — Технології (побутові ситуації)", ru: "Урок 15 — Технологии (бытовые ситуации)", en: "Lesson 15 — Technology (everyday situations)" },
    words: [
      { sk: "nastavit", ua: "налаштувати", ru: "настроить", en: "set up / adjust", img: "/words_a2/nastaviť.jpg" },
      { sk: "aktualizace", ua: "оновлення", ru: "обновление", en: "update", img: "/words_a2/aktualizácia.jpg" },
      { sk: "připojení", ua: "підключення", ru: "подключение", en: "connection", img: "/words_a2/pripojenie.jpg" },
      { sk: "signál", ua: "сигнал", ru: "сигнал", en: "signal", img: "/words_a2/signál.jpg" },
      { sk: "výpadek", ua: "збій/відключення", ru: "сбой / отключение", en: "outage / failure", img: "/words_a2/výpadok.jpg" },
      { sk: "zaseknout se", ua: "зависнути", ru: "зависнуть", en: "freeze", img: "/words_a2/zaseknúť sa.jpg" },
      { sk: "restartovat", ua: "перезавантажити", ru: "перезагрузить", en: "restart", img: "/words_a2/reštartovať.jpg" },
      { sk: "nainstalovat", ua: "встановити", ru: "установить", en: "install", img: "/words_a2/nainštalovať.jpg" },
      { sk: "vymazat", ua: "видалити", ru: "удалить", en: "delete", img: "/words_a2/vymazať.jpg" },
      { sk: "obnovit", ua: "відновити", ru: "восстановить", en: "restore", img: "/words_a2/obnoviť.jpg" },
    ],
  },
  {
    id: "a2-16",
    title: { ua: "Урок 16 — Освіта і навчання", ru: "Урок 16 — Образование и обучение", en: "Lesson 16 — Education and learning" },
    words: [
      { sk: "kurz", ua: "курс", ru: "курс", en: "course", img: "/words_a2/kurz.jpg" },
      { sk: "přednáška", ua: "лекція", ru: "лекция", en: "lecture", img: "/words_a2/prednáška.jpg" },
      { sk: "poznámky", ua: "конспект/нотатки", ru: "конспект / заметки", en: "notes", img: "/words_a2/poznámky.jpg" },
      { sk: "domácí úkol", ua: "домашнє завдання", ru: "домашнее задание", en: "homework", img: "/words_a2/domáca úloha.jpg" },
      { sk: "zkouška", ua: "іспит", ru: "экзамен", en: "exam", img: "/words_a2/skúška.jpg" },
      { sk: "certifikát", ua: "сертифікат", ru: "сертификат", en: "certificate", img: "/words_a2/certifikát.jpg" },
      { sk: "zručnost", ua: "навичка", ru: "навык", en: "skill", img: "/words_a2/zručnosť.jpg" },
      { sk: "zlepšit se", ua: "покращитися", ru: "улучшиться", en: "improve", img: "/words_a2/zlepšiť sa.jpg" },
      { sk: "opakovat", ua: "повторювати", ru: "повторять", en: "repeat / revise", img: "/words_a2/opakovať.jpg" },
      { sk: "učit se nazpaměť", ua: "вчити напам’ять", ru: "учить наизусть", en: "learn by heart", img: "/words_a2/učiť sa naspamäť.jpg" },
    ],
  },
  {
    id: "a2-17",
    title: { ua: "Урок 17 — На роботі (комунікація)", ru: "Урок 17 — На работе (общение)", en: "Lesson 17 — At work (communication)" },
    words: [
      { sk: "rozdělit úkoly", ua: "розподілити завдання", ru: "распределить задачи", en: "divide tasks", img: "/words_a2/rozdeliť úlohy.jpg" },
      { sk: "spolupracovat", ua: "співпрацювати", ru: "сотрудничать", en: "cooperate", img: "/words_a2/spolupracovať.jpg" },
      { sk: "priorita", ua: "пріоритет", ru: "приоритет", en: "priority", img: "/words_a2/priorita.jpg" },
      { sk: "zodpovídat", ua: "відповідати (бути відповідальним)", ru: "отвечать (быть ответственным)", en: "be responsible for", img: "/words_a2/zodpovedať.jpg" },
      { sk: "odvzdat", ua: "здати/передати", ru: "сдать / передать", en: "hand in / submit", img: "/words_a2/odovzdať.jpg" },
      { sk: "zkontrolovat", ua: "перевірити", ru: "проверить", en: "check", img: "/words_a2/skontrolovať.jpg" },
      { sk: "organizovat", ua: "організовувати", ru: "организовывать", en: "organize", img: "/words_a2_cz/organizovat.jpg" },
      { sk: "zpětná vazba", ua: "зворотний зв’язок", ru: "обратная связь", en: "feedback", img: "/words_a2/spätná väzba.jpg" },
      { sk: "navrhnout řešení", ua: "запропонувати рішення", ru: "предложить решение", en: "suggest a solution", img: "/words_a2/navrhnúť riešenie.jpg" },
      { sk: "dokončit", ua: "завершити", ru: "завершить", en: "complete", img: "/words_a2/dokončiť.jpg" },
    ],
  },
  {
    id: "a2-18",
    title: { ua: "Урок 18 — Банківські справи", ru: "Урок 18 — Банковские дела", en: "Lesson 18 — Banking matters" },
    words: [
      { sk: "založit účet", ua: "відкрити рахунок", ru: "открыть счёт", en: "open an account", img: "/words_a2/založiť účet.jpg" },
      { sk: "výběr", ua: "зняття (грошей)", ru: "снятие (денег)", en: "withdrawal", img: "/words_a2/výber.jpg" },
      { sk: "vklad", ua: "внесення (грошей)", ru: "внесение (денег) / вклад", en: "deposit", img: "/words_a2/vklad.jpg" },
      { sk: "převést", ua: "перевести (гроші)", ru: "перевести (деньги)", en: "transfer", img: "/words_a2/previesť.jpg" },
      { sk: "platební karta", ua: "платіжна картка", ru: "платёжная карта", en: "payment card", img: "/words_a2/platobná karta.jpg" },
      { sk: "PIN kód", ua: "пін-код", ru: "пин-код", en: "PIN code", img: "/words_a2/PIN kód.jpg" },
      { sk: "limit", ua: "ліміт", ru: "лимит", en: "limit", img: "/words_a2/limit.jpg" },
      { sk: "poplatek", ua: "комісія", ru: "комиссия", en: "fee", img: "/words_a2_cz/poplatek.jpg" },
      { sk: "výpis", ua: "виписка", ru: "выписка", en: "statement", img: "/words_a2/výpis.jpg" },
      { sk: "zablokovat kartu", ua: "заблокувати картку", ru: "заблокировать карту", en: "block a card", img: "/words_a2/blokovať kartu.jpg" },
    ],
  },
  {
    id: "a2-19",
    title: { ua: "Урок 19 — Державні документи", ru: "Урок 19 — Госдокументы", en: "Lesson 19 — Official documents" },
    words: [
      { sk: "povolení", ua: "дозвіл", ru: "разрешение", en: "permit", img: "/words_a2/povolenie.jpg" },
      { sk: "pobyt", ua: "дозвіл на проживання/побут", ru: "вид на жительство / пребывание", en: "residence / stay", img: "/words_a2/pobyt.jpg" },
      { sk: "občanský průkaz", ua: "ID-картка", ru: "ID-карта / удостоверение личности", en: "ID card", img: "/words_a2/občiansky preukaz.jpg" },
      { sk: "registrace", ua: "реєстрація", ru: "регистрация", en: "registration", img: "/words_a2/registrácia.jpg" },
      { sk: "podpis", ua: "підпис", ru: "подпись", en: "signature", img: "/words_a2/podpis.jpg" },
      { sk: "fotografie", ua: "фото", ru: "фото", en: "photo", img: "/words_a2/fotografia.jpg" },
      { sk: "ověřit", ua: "завірити/підтвердити", ru: "заверить / подтвердить", en: "verify / certify", img: "/words_a2/overiť.jpg" },
      { sk: "termín schůzky", ua: "дата прийому", ru: "дата приёма", en: "appointment date", img: "/words_a2/termín stretnutia.jpg" },
      { sk: "vyřídit", ua: "оформити/вирішити (справу)", ru: "оформить / решить (дело)", en: "arrange / deal with", img: "/words_a2/vybaviť.jpg" },
      { sk: "rodné číslo", ua: "ідентифікаційний номер", ru: "идентификационный номер", en: "personal identification number", img: "/words_a2/rodné číslo.jpg" },
    ],
  },
  {
    id: "a2-20",
    title: { ua: "Урок 20 — Повторення A2 (11–19)", ru: "Урок 20 — Повторение A2 (11–19)", en: "Lesson 20 — Review A2 (11–19)" },
    words: [
      { sk: "strava", ua: "харчування", ru: "питание", en: "nutrition / diet", img: "/words_a2/strava.jpg" },
      { sk: "trénink", ua: "тренування", ru: "тренировка", en: "training", img: "/words_a2/tréning.jpg" },
      { sk: "kompromis", ua: "компроміс", ru: "компромисс", en: "compromise", img: "/words_a2/kompromis.jpg" },
      { sk: "doručení", ua: "доставка", ru: "доставка", en: "delivery", img: "/words_a2/doručenie.jpg" },
      { sk: "aktualizace", ua: "оновлення", ru: "обновление", en: "update", img: "/words_a2/aktualizácia.jpg" },
      { sk: "přednáška", ua: "лекція", ru: "лекция", en: "lecture", img: "/words_a2/prednáška.jpg" },
      { sk: "zpětná vazba", ua: "зворотний зв’язок", ru: "обратная связь", en: "feedback", img: "/words_a2/spätná väzba.jpg" },
      { sk: "výpis", ua: "виписка", ru: "выписка", en: "statement", img: "/words_a2/výpis.jpg" },
      { sk: "povolení", ua: "дозвіл", ru: "разрешение", en: "permit", img: "/words_a2/povolenie.jpg" },
      { sk: "vyřídit", ua: "оформити/вирішити", ru: "оформить / решить", en: "arrange / deal with", img: "/words_a2/vybaviť.jpg" },
    ],
  },
  {
    id: "a2-21",
    title: { ua: "Урок 21 — Дім (проблеми та майстер)", ru: "Урок 21 — Дом (проблемы и мастер)", en: "Lesson 21 — Home (problems and repairman)" },
    words: [
      { sk: "porucha", ua: "поломка/несправність", ru: "поломка / неисправность", en: "fault / malfunction", img: "/words_a2/porucha.jpg" },
      { sk: "instalatér", ua: "сантехнік", ru: "сантехник", en: "plumber", img: "/words_a2/inštalatér.jpg" },
      { sk: "elektrikář", ua: "електрик", ru: "электрик", en: "electrician", img: "/words_a2/elektrikár.jpg" },
      { sk: "opravit", ua: "відремонтувати", ru: "отремонтировать", en: "repair / fix", img: "/words_a2_cz/opravit.jpg" },
      { sk: "vyměnit", ua: "замінити", ru: "заменить", en: "replace", img: "/words_a2_cz/vyměnit.jpg" },
      { sk: "protékání", ua: "протікання", ru: "протечка", en: "leakage", img: "/words_a2/prietok.jpg" },
      { sk: "upchání", ua: "засмічення", ru: "засор", en: "blockage", img: "/words_a2/upchatie.jpg" },
      { sk: "zatekat", ua: "протікати", ru: "протекать", en: "leak", img: "/words_a2/zatekať.jpg" },
      { sk: "poškození", ua: "пошкодження", ru: "повреждение", en: "damage", img: "/words_a2/poškodenie.jpg" },
      { sk: "náhradní díl", ua: "запасна частина", ru: "запасная часть", en: "spare part", img: "/words_a2/náhradný diel.jpg" },
    ],
  },
  {
    id: "a2-22",
    title: { ua: "Урок 22 — Здоровʼя (аптека та лікування)", ru: "Урок 22 — Здоровье (аптека и лечение)", en: "Lesson 22 — Health (pharmacy and treatment)" },
    words: [
      { sk: "vedlejší účinky", ua: "побічні ефекти", ru: "побочные эффекты", en: "side effects", img: "/words_a2/vedľajšie účinky.jpg" },
      { sk: "dávkování", ua: "дозування", ru: "дозировка", en: "dosage", img: "/words_a2/dávkovanie.jpg" },
      { sk: "návod", ua: "інструкція", ru: "инструкция", en: "instructions", img: "/words_a2/návod.jpg" },
      { sk: "lék proti bolesti", ua: "знеболювальне", ru: "обезболивающее", en: "painkiller", img: "/words_a2/liek proti bolesti.jpg" },
      { sk: "antibiotika", ua: "антибіотики", ru: "антибиотики", en: "antibiotics", img: "/words_a2/antibiotiká.jpg" },
      { sk: "očkování", ua: "вакцинація", ru: "вакцинация", en: "vaccination", img: "/words_a2/očkovanie.jpg" },
      { sk: "recept", ua: "рецепт", ru: "рецепт", en: "prescription", img: "/words_a2/recept.jpg" },
      { sk: "bez receptu", ua: "без рецепта", ru: "без рецепта", en: "without prescription / over the counter", img: "/words_a2/bez receptu.jpg" },
      { sk: "kontrola", ua: "контроль/огляд", ru: "контроль / осмотр", en: "check-up / inspection", img: "/words_a2/kontrola.jpg" },
      { sk: "uzdravovat se", ua: "одужувати", ru: "выздоравливать", en: "recover", img: "/words_a2/uzdravovať sa.jpg" },
    ],
  },
  {
    id: "a2-23",
    title: { ua: "Урок 23 — Місто (безпека та служби)", ru: "Урок 23 — Город (безопасность и службы)", en: "Lesson 23 — City (safety and services)" },
    words: [
      { sk: "nehoda", ua: "аварія/нещасний випадок", ru: "авария / несчастный случай", en: "accident", img: "/words_a2/nehoda.jpg" },
      { sk: "záchranka", ua: "швидка допомога", ru: "скорая помощь", en: "ambulance", img: "/words_a2/záchranka.jpg" },
      { sk: "hasiči", ua: "пожежники", ru: "пожарные", en: "firefighters", img: "/words_a2/hasiči.jpg" },
      { sk: "policejní stanice", ua: "відділок поліції", ru: "отделение полиции", en: "police station", img: "/words_a2/policajná stanica.jpg" },
      { sk: "svědek", ua: "свідок", ru: "свидетель", en: "witness", img: "/words_a2/svedok.jpg" },
      { sk: "krádež", ua: "крадіжка", ru: "кража", en: "theft", img: "/words_a2/krádež.jpg" },
      { sk: "nahlásit", ua: "повідомити/заявити", ru: "сообщить / заявить", en: "report", img: "/words_a2/nahlásiť.jpg" },
      { sk: "doklady", ua: "документи", ru: "документы", en: "documents", img: "/words_a2/doklady.jpg" },
      { sk: "ztratit", ua: "загубити", ru: "потерять", en: "lose", img: "/words_a2_cz/ztratit.jpg" },
      { sk: "najít", ua: "знайти", ru: "найти", en: "find", img: "/words_a2_cz/najít.jpg" },
    ],
  },
  {
    id: "a2-24",
    title: { ua: "Урок 24 — Їжа (покупки та приготування)", ru: "Урок 24 — Еда (покупки и готовка)", en: "Lesson 24 — Food (shopping and cooking)" },
    words: [
      { sk: "ingredience", ua: "інгредієнти", ru: "ингредиенты", en: "ingredients", img: "/words_a2/ingrediencie.jpg" },
      { sk: "recept (kuchařský)", ua: "рецепт (кулінарний)", ru: "рецепт (кулинарный)", en: "recipe", img: "/words_a2/recept (kuchársky).jpg" },
      { sk: "nakrájet", ua: "нарізати", ru: "нарезать", en: "slice / cut up", img: "/words_a2/nakrájať.jpg" },
      { sk: "smíchat", ua: "змішати", ru: "смешать", en: "mix", img: "/words_a2/zmiešať.jpg" },
      { sk: "osmažit", ua: "підсмажити", ru: "поджарить", en: "fry", img: "/words_a2/osmažiť.jpg" },
      { sk: "uvařit", ua: "зварити", ru: "сварить", en: "cook / boil", img: "/words_a2/uvariť.jpg" },
      { sk: "upéct", ua: "спекти", ru: "испечь", en: "bake", img: "/words_a2/upiecť.jpg" },
      { sk: "ochutit", ua: "приправити", ru: "приправить", en: "season", img: "/words_a2/ochutiť.jpg" },
      { sk: "porce", ua: "порція", ru: "порция", en: "portion", img: "/words_a2/porcia.jpg" },
      { sk: "zbytky", ua: "залишки їжі", ru: "остатки еды", en: "leftovers", img: "/words_a2/zvyšky.jpg" },
    ],
  },
  {
    id: "a2-25",
    title: { ua: "Урок 25 — Подорожі (планування маршруту)", ru: "Урок 25 — Путешествия (планирование маршрута)", en: "Lesson 25 — Travel (route planning)" },
    words: [
      { sk: "itinerář", ua: "маршрут/план подорожі", ru: "маршрут / план поездки", en: "itinerary / travel plan", img: "/words_a2/itinerár.jpg" },
      { sk: "přestup", ua: "пересадка", ru: "пересадка", en: "transfer", img: "/words_a2/prestup.jpg" },
      { sk: "spoj", ua: "рейс/сполучення", ru: "рейс / сообщение", en: "connection / service", img: "/words_a2/spoj.jpg" },
      { sk: "zpoždění", ua: "затримка", ru: "задержка", en: "delay", img: "/words_a2_cz/zpoždění.jpg" },
      { sk: "zrušený", ua: "скасований", ru: "отменённый", en: "cancelled", img: "/words_a2/zrušený.jpg" },
      { sk: "odbavení", ua: "реєстрація / оформлення", ru: "регистрация / оформление", en: "check-in / processing", img: "/words_a2/odbavenie.jpg" },
      { sk: "cestovní řád", ua: "розклад руху", ru: "расписание движения", en: "timetable", img: "/words_a2/cestovný poriadok.jpg" },
      { sk: "zpáteční lístek", ua: "квиток туди-назад", ru: "билет туда-обратно", en: "return ticket", img: "/words_a2/spiatočný lístok.jpg" },
      { sk: "jednosměrný lístek", ua: "квиток в один бік", ru: "билет в одну сторону", en: "one-way ticket", img: "/words_a2/jednosmerný lístok.jpg" },
      { sk: "cestovní lístek", ua: "квиток", ru: "билет", en: "ticket", img: "/words_a2/cestovný lístok.jpg" },
    ],
  },
  {
    id: "a2-26",
    title: { ua: "Урок 26 — Комунікація та інформація", ru: "Урок 26 — Коммуникация и информация", en: "Lesson 26 — Communication and information" },
    words: [
      { sk: "zpráva", ua: "повідомлення", ru: "сообщение", en: "message / news", img: "/words_a2_cz/zpráva.jpg" },
      { sk: "oznámení", ua: "оголошення", ru: "объявление", en: "announcement", img: "/words_a2_cz/oznámení.jpg" },
      { sk: "článek", ua: "стаття", ru: "статья", en: "article", img: "/words_a2_cz/článek.jpg" },
      { sk: "zdroj informací", ua: "джерело інформації", ru: "источник информации", en: "source of information", img: "/words_a2/zdroj informácií.jpg" },
      { sk: "uvést", ua: "опублікувати", ru: "опубликовать", en: "publish / state", img: "/words_a2_cz/uvedej.jpg" },
      { sk: "zveřejnit", ua: "оприлюднити", ru: "опубликовать / обнародовать", en: "publish / make public", img: "/words_a2_cz/zveřejnit.jpg" },
      { sk: "reagovat", ua: "реагувати", ru: "реагировать", en: "react", img: "/words_a2_cz/reagovat.jpg" },
      { sk: "diskuze", ua: "дискусія", ru: "дискуссия", en: "discussion", img: "/words_a2_cz/diskuze.jpg" },
      { sk: "názor", ua: "думка", ru: "мнение", en: "opinion", img: "/words_a2/názor.jpg" },
      { sk: "vliv", ua: "вплив", ru: "влияние", en: "influence", img: "/words_a2_cz/vliv.jpg" },
    ],
  },
  {
    id: "a2-27",
    title: { ua: "Урок 27 — Комунікація (заперечення та аргументи)", ru: "Урок 27 — Общение (возражения и аргументы)", en: "Lesson 27 — Communication (objections and arguments)" },
    words: [
      { sk: "naopak", ua: "навпаки", ru: "наоборот", en: "on the contrary", img: "/words_a2/naopak.jpg" },
      { sk: "ve skutečnosti", ua: "насправді", ru: "на самом деле", en: "in fact", img: "/words_a2/v skutočnosti.jpg" },
      { sk: "důkaz", ua: "доказ", ru: "доказательство", en: "proof / evidence", img: "/words_a2/dôkaz.jpg" },
      { sk: "argument", ua: "аргумент", ru: "аргумент", en: "argument", img: "/words_a2/argument.jpg" },
      { sk: "důvod", ua: "причина", ru: "причина", en: "reason", img: "/words_a2_cz/důvod.jpg" },
      { sk: "výhoda", ua: "перевага", ru: "преимущество", en: "advantage", img: "/words_a2/výhoda.jpg" },
      { sk: "nevýhoda", ua: "недолік", ru: "недостаток", en: "disadvantage", img: "/words_a2/nevýhoda.jpg" },
      { sk: "záleží", ua: "залежить", ru: "зависит", en: "it depends", img: "/words_a2/záleží.jpg" },
      { sk: "přesvědčit", ua: "переконати", ru: "убедить", en: "convince", img: "/words_a2_cz/přesvědčit.jpg" },
      { sk: "souhlasit s tím", ua: "погодитися з цим", ru: "согласиться с этим", en: "agree with that", img: "/words_a2/súhlasiť s tým.jpg" },
    ],
  },
  {
    id: "a2-28",
    title: { ua: "Урок 28 — Технології (інтернет та безпека)", ru: "Урок 28 — Технологии (интернет и безопасность)", en: "Lesson 28 — Technology (internet and security)" },
    words: [
      { sk: "soukromí", ua: "приватність", ru: "приватность", en: "privacy", img: "/words_a2/súkromie.jpg" },
      { sk: "bezpečnost", ua: "безпека", ru: "безопасность", en: "security / safety", img: "/words_a2/bezpečnosť.jpg" },
      { sk: "ověření", ua: "підтвердження/верифікація", ru: "подтверждение / верификация", en: "verification", img: "/words_a2/overenie.jpg" },
      { sk: "dvojfaktorové ověření", ua: "2FA (двофакторна перевірка)", ru: "2FA (двухфакторная проверка)", en: "two-factor authentication", img: "/words_a2/dvojfaktorové overenie.jpg" },
      { sk: "podvod", ua: "шахрайство", ru: "мошенничество", en: "fraud / scam", img: "/words_a2/podvod.jpg" },
      { sk: "odkaz", ua: "посилання", ru: "ссылка", en: "link", img: "/words_a2/odkaz.jpg" },
      { sk: "stáhnout soubor", ua: "завантажити файл", ru: "скачать файл", en: "download a file", img: "/words_a2/stiahnuť súbor.jpg" },
      { sk: "virus", ua: "вірус", ru: "вирус", en: "virus", img: "/words_a2/vírus.jpg" },
      { sk: "zablokovat", ua: "заблокувати", ru: "заблокировать", en: "block", img: "/words_a2/zablokovať.jpg" },
      { sk: "obnovit heslo", ua: "відновити пароль", ru: "восстановить пароль", en: "reset password", img: "/words_a2/obnoviť heslo.jpg" },
    ],
  },
  {
    id: "a2-29",
    title: { ua: "Урок 29 — Емоції (розширено)", ru: "Урок 29 — Эмоции (расширено)", en: "Lesson 29 — Emotions (extended)" },
    words: [
      { sk: "zklamaný", ua: "розчарований", ru: "разочарованный", en: "disappointed", img: "/words_a2/sklamaný.jpg" },
      { sk: "naštvaný", ua: "розлючений", ru: "разъярённый / злой", en: "angry", img: "/words_a2/nahnevaný.jpg" },
      { sk: "nadšený", ua: "захоплений", ru: "восторженный / воодушевлённый", en: "enthusiastic", img: "/words_a2/nadšený.jpg" },
      { sk: "zmatený", ua: "розгублений", ru: "растерянный", en: "confused", img: "/words_a2/zmätený.jpg" },
      { sk: "znepokojený", ua: "стурбований", ru: "обеспокоенный", en: "concerned", img: "/words_a2/znepokojený.jpg" },
      { sk: "hrdý", ua: "гордий", ru: "гордый", en: "proud", img: "/words_a2/hrdý.jpg" },
      { sk: "vděčný", ua: "вдячний", ru: "благодарный", en: "grateful", img: "/words_a2/vďačný.jpg" },
      { sk: "stydět se", ua: "соромитися", ru: "стыдиться", en: "be ashamed", img: "/words_a2/hanbiť sa.jpg" },
      { sk: "litovat", ua: "шкодувати", ru: "жалеть / сожалеть", en: "regret", img: "/words_a2/ľutovať.jpg" },
      { sk: "ulevit se", ua: "полегшало", ru: "полегчало", en: "feel relieved", img: "/words_a2/uľaviť sa.jpg" },
    ],
  },
  {
    id: "a2-30",
    title: { ua: "Урок 30 — Повторення A2 (21–29)", ru: "Урок 30 — Повторение A2 (21–29)", en: "Lesson 30 — Review A2 (21–29)" },
    words: [
      { sk: "náhradní díl", ua: "запасна частина", ru: "запасная часть", en: "spare part", img: "/words_a2/náhradný diel.jpg" },
      { sk: "dávkování", ua: "дозування", ru: "дозировка", en: "dosage", img: "/words_a2/dávkovanie.jpg" },
      { sk: "krádež", ua: "крадіжка", ru: "кража", en: "theft", img: "/words_a2/krádež.jpg" },
      { sk: "ingredience", ua: "інгредієнти", ru: "ингредиенты", en: "ingredients", img: "/words_a2/ingrediencie.jpg" },
      { sk: "itinerář", ua: "маршрут", ru: "маршрут / план поездки", en: "itinerary", img: "/words_a2/itinerár.jpg" },
      { sk: "výplatní páska", ua: "розрахунковий лист", ru: "расчётный листок", en: "payslip", img: "/words_a2_cz/výplatní páska.jpg" },
      { sk: "argument", ua: "аргумент", ru: "аргумент", en: "argument", img: "/words_a2/argument.jpg" },
      { sk: "podvod", ua: "шахрайство", ru: "мошенничество", en: "fraud / scam", img: "/words_a2/podvod.jpg" },
      { sk: "znepokojený", ua: "стурбований", ru: "обеспокоенный", en: "concerned", img: "/words_a2/znepokojený.jpg" },
      { sk: "záleží", ua: "залежить", ru: "зависит", en: "it depends", img: "/words_a2/záleží.jpg" },
    ],
  },
  {
    id: "a2-31",
    title: { ua: "Урок 31 — Житло (пошук і оренда)", ru: "Урок 31 — Жильё (поиск и аренда)", en: "Lesson 31 — Housing (search and rent)" },
    words: [
      { sk: "nabídka", ua: "пропозиція", ru: "предложение", en: "offer", img: "/words_a2/ponuka.jpg" },
      { sk: "poptávka", ua: "попит", ru: "спрос", en: "demand", img: "/words_a2/dopyt.jpg" },
      { sk: "prohlídka", ua: "огляд (квартири)", ru: "осмотр (квартиры)", en: "viewing", img: "/words_a2/obhliadka.jpg" },
      { sk: "záloha", ua: "застава/депозит", ru: "залог / депозит", en: "deposit / advance payment", img: "/words_a2/záloha.jpg" },
      { sk: "kauce", ua: "депозит (кауція)", ru: "депозит (кауция)", en: "security deposit", img: "/words_a2/kaucia.jpg" },
      { sk: "měsíční platba", ua: "щомісячна оплата", ru: "ежемесячная оплата", en: "monthly payment", img: "/words_a2/mesačné.jpg" },
      { sk: "energie v ceně", ua: "комунальні включені", ru: "коммунальные включены", en: "utilities included", img: "/words_a2/energie v cene.jpg" },
      { sk: "zařízený", ua: "мебльований", ru: "меблированный", en: "furnished", img: "/words_a2/zariadený.jpg" },
      { sk: "nezařízený", ua: "немебльований", ru: "немеблированный", en: "unfurnished", img: "/words_a2/nezariadený.jpg" },
      { sk: "spolubydlení", ua: "спільне проживання", ru: "совместное проживание", en: "shared accommodation", img: "/words_a2/spolubývanie.jpg" },
    ],
  },
  {
    id: "a2-32",
    title: { ua: "Урок 32 — Робота (професійні навички)", ru: "Урок 32 — Работа (профессиональные навыки)", en: "Lesson 32 — Work (professional skills)" },
    words: [
      { sk: "schopnost", ua: "здатність", ru: "способность", en: "ability", img: "/words_a2/schopnosť.jpg" },
      { sk: "zručnost", ua: "навичка", ru: "навык", en: "skill", img: "/words_a2_cz/zručnost.jpg" },
      { sk: "zkušenosti", ua: "досвід", ru: "опыт", en: "experience", img: "/words_a2/skúsenosti.jpg" },
      { sk: "odpovědný", ua: "відповідальний", ru: "ответственный", en: "responsible", img: "/words_a2/zodpovedný.jpg" },
      { sk: "samostatný", ua: "самостійний", ru: "самостоятельный", en: "independent", img: "/words_a2/samostatný.jpg" },
      { sk: "přesný", ua: "точний", ru: "точный", en: "accurate", img: "/words_a2/presný.jpg" },
      { sk: "spolehlivý", ua: "надійний", ru: "надёжный", en: "reliable", img: "/words_a2/spoľahlivý.jpg" },
      { sk: "komunikativní", ua: "комунікабельний", ru: "коммуникабельный", en: "communicative", img: "/words_a2/komunikatívny.jpg" },
      { sk: "flexibilní", ua: "гнучкий", ru: "гибкий", en: "flexible", img: "/words_a2/flexibilný.jpg" },
      { sk: "učit se rychle", ua: "швидко вчитися", ru: "быстро учиться", en: "learn quickly", img: "/words_a2/učiť sa rýchlo.jpg" },
    ],
  },
  {
    id: "a2-33",
    title: { ua: "Урок 33 — Відпочинок і дозвілля", ru: "Урок 33 — Отдых и досуг", en: "Lesson 33 — Rest and leisure" },
    words: [
      { sk: "volný čas", ua: "вільний час", ru: "свободное время", en: "free time", img: "/words_a2/voľný čas.jpg" },
      { sk: "odpočinout si", ua: "відпочити", ru: "отдохнуть", en: "rest", img: "/words_a2/oddýchnuť si.jpg" },
      { sk: "zábava", ua: "розвага", ru: "развлечение", en: "entertainment / fun", img: "/words_a2/zábava.jpg" },
      { sk: "událost", ua: "подія", ru: "мероприятие / событие", en: "event", img: "/words_a2/podujatie.jpg" },
      { sk: "festival", ua: "фестиваль", ru: "фестиваль", en: "festival", img: "/words_a2/festival.jpg" },
      { sk: "vstupenka", ua: "квиток", ru: "билет", en: "ticket", img: "/words_a2/vstupenka.jpg" },
      { sk: "představení", ua: "вистава", ru: "представление / спектакль", en: "performance / show", img: "/words_a2/predstavenie.jpg" },
      { sk: "koncert", ua: "концерт", ru: "концерт", en: "concert", img: "/words_a2/koncert.jpg" },
      { sk: "výstava", ua: "виставка", ru: "выставка", en: "exhibition", img: "/words_a2/výstava.jpg" },
      { sk: "rezervovat místo", ua: "забронювати місце", ru: "забронировать место", en: "reserve a place", img: "/words_a2/rezervovať miesto.jpg" },
    ],
  },
  {
    id: "a2-34",
    title: { ua: "Урок 34 — Сервіс (майстерня, ремонт)", ru: "Урок 34 — Сервис (мастерская, ремонт)", en: "Lesson 34 — Service (workshop, repair)" },
    words: [
      { sk: "servis", ua: "сервіс", ru: "сервис", en: "service", img: "/words_a2/servis.jpg" },
      { sk: "objednat termín", ua: "записатися на час", ru: "записаться на время", en: "book an appointment", img: "/words_a2/objednať termín.jpg" },
      { sk: "diagnostika", ua: "діагностика", ru: "диагностика", en: "diagnostics", img: "/words_a2/diagnostika.jpg" },
      { sk: "porucha", ua: "несправність", ru: "неисправность", en: "fault / malfunction", img: "/words_a2/porucha.jpg" },
      { sk: "oprava", ua: "ремонт", ru: "ремонт", en: "repair", img: "/words_a2/oprava.jpg" },
      { sk: "náhradní díly", ua: "запасні частини", ru: "запасные части", en: "spare parts", img: "/words_a2/náhradné diely.jpg" },
      { sk: "ceník", ua: "прайс", ru: "прайс-лист", en: "price list", img: "/words_a2/cenník.jpg" },
      { sk: "odhad ceny", ua: "оцінка вартості", ru: "оценка стоимости", en: "cost estimate", img: "/words_a2/odhad ceny.jpg" },
      { sk: "schválit", ua: "схвалити / затвердити", ru: "одобрить / утвердить", en: "approve", img: "/words_a2/schváliť.jpg" },
      { sk: "záruka", ua: "гарантія", ru: "гарантия", en: "warranty", img: "/words_a2/záruka.jpg" },
    ],
  },
  {
    id: "a2-35",
    title: { ua: "Урок 35 — В магазині (складніші ситуації)", ru: "Урок 35 — В магазине (более сложные ситуации)", en: "Lesson 35 — In the shop (more complex situations)" },
    words: [
      { sk: "dostupnost", ua: "наявність", ru: "наличие / доступность", en: "availability", img: "/words_a2/dostupnosť.jpg" },
      { sk: "skladem", ua: "в наявності", ru: "в наличии", en: "in stock", img: "/words_a2_cz/skladem.jpg" },
      { sk: "vyprodáno", ua: "розпродано", ru: "распродано", en: "sold out", img: "/words_a2/vypredané.jpg" },
      { sk: "objednat", ua: "замовити", ru: "заказать", en: "order", img: "/words_a2_cz/objednat.jpg" },
      { sk: "dodání", ua: "поставка", ru: "поставка / доставка", en: "delivery / supply", img: "/words_a2/dodanie.jpg" },
      { sk: "dodací lhůta", ua: "термін доставки", ru: "срок доставки", en: "delivery time", img: "/words_a2/dodacia lehota.jpg" },
      { sk: "poškozené zboží", ua: "пошкоджений товар", ru: "повреждённый товар", en: "damaged goods", img: "/words_a2/poškodený tovar.jpg" },
      { sk: "vyměnit zboží", ua: "обміняти товар", ru: "обменять товар", en: "exchange goods", img: "/words_a2/vymeniť tovar.jpg" },
      { sk: "vrátit peníze", ua: "повернути гроші", ru: "вернуть деньги", en: "refund money", img: "/words_a2/vrátiť peniaze.jpg" },
      { sk: "reklamační oddělení", ua: "відділ рекламацій", ru: "отдел рекламаций", en: "complaints department", img: "/words_a2_cz/reklamační oddělení.jpg" },
    ],
  },
  {
    id: "a2-36",
    title: { ua: "Урок 36 — Подорожі (готельні ситуації)", ru: "Урок 36 — Путешествия (отельные ситуации)", en: "Lesson 36 — Travel (hotel situations)" },
    words: [
      { sk: "recepce", ua: "ресепшн", ru: "ресепшен", en: "reception", img: "/words_a2_cz/recepce.jpg" },
      { sk: "ubytovat se", ua: "заселитися", ru: "заселиться", en: "check in", img: "/words_a2/ubytovať sa.jpg" },
      { sk: "odhlásit se", ua: "виселитися", ru: "выселиться", en: "check out", img: "/words_a2/odubytovať sa.jpg" },
      { sk: "pokoj", ua: "номер/кімната", ru: "номер / комната", en: "room", img: "/words_a2/izba.jpg" },
      { sk: "klíč/karta", ua: "ключ/картка", ru: "ключ / карта", en: "key / card", img: "/words_a2/kľúč-karta.jpg" },
      { sk: "snídaně v ceně", ua: "сніданок включено", ru: "завтрак включён", en: "breakfast included", img: "/words_a2/raňajky v cene.jpg" },
      { sk: "doplatek", ua: "доплата", ru: "доплата", en: "surcharge / extra payment", img: "/words_a2/doplatok.jpg" },
      { sk: "stížnost", ua: "скарга", ru: "жалоба", en: "complaint", img: "/words_a2_cz/stížnost.jpg" },
      { sk: "hluk", ua: "шум", ru: "шум", en: "noise", img: "/words_a2/hluk.jpg" },
      { sk: "úklid", ua: "прибирання", ru: "уборка", en: "cleaning", img: "/words_a2/upratovanie.jpg" },
    ],
  },
  {
    id: "a2-37",
    title: { ua: "Урок 37 — Ресторан (обслуговування)", ru: "Урок 37 — Ресторан (обслуживание)", en: "Lesson 37 — Restaurant (service)" },
    words: [
      { sk: "obsluha", ua: "обслуговування", ru: "обслуживание", en: "service", img: "/words_a2/obsluha.jpg" },
      { sk: "číšník/číšnice", ua: "офіціант/офіціантка", ru: "официант/официантка", en: "waiter / waitress", img: "/words_a2/čašník-čašníčka.jpg" },
      { sk: "doporučit", ua: "порадити", ru: "порекомендовать / посоветовать", en: "recommend", img: "/words_a2/odporučiť.jpg" },
      { sk: "předkrm", ua: "закуска", ru: "закуска", en: "starter / appetizer", img: "/words_a2/predjedlo.jpg" },
      { sk: "hlavní jídlo", ua: "основна страва", ru: "основное блюдо", en: "main course", img: "/words_a2/hlavné jedlo.jpg" },
      { sk: "bez masa", ua: "без мʼяса", ru: "без мяса", en: "without meat", img: "/words_a2/bez mäsa.jpg" },
      { sk: "bez lepku", ua: "без глютену", ru: "без глютена", en: "gluten-free", img: "/words_a2/bez lepku.jpg" },
      { sk: "účtovat", ua: "виставити рахунок", ru: "выставить счёт", en: "bill / charge", img: "/words_a2/účtovať.jpg" },
      { sk: "spropitné", ua: "чайові", ru: "чаевые", en: "tip", img: "/words_a2/prepitné.jpg" },
      { sk: "pochutnat si", ua: "смачно поїсти", ru: "вкусно поесть", en: "enjoy the meal", img: "/words_a2/pochutnať si.jpg" },
    ],
  },
  {
    id: "a2-38",
    title: { ua: "Урок 38 — Спілкування (телефон/листування)", ru: "Урок 38 — Общение (телефон/переписка)", en: "Lesson 38 — Communication (phone/correspondence)" },
    words: [
      { sk: "zavolat", ua: "подзвонити", ru: "позвонить", en: "call", img: "/words_a2_cz/zavolat.jpg" },
      { sk: "nedostupný", ua: "недоступний", ru: "недоступный", en: "unavailable", img: "/words_a2/nedostupný.jpg" },
      { sk: "zanechat zprávu", ua: "залишити повідомлення", ru: "оставить сообщение", en: "leave a message", img: "/words_a2/zanechať správu.jpg" },
      { sk: "ozvat se", ua: "відписати/дати знати", ru: "отписаться / дать знать", en: "get back / respond", img: "/words_a2/ozvať sa.jpg" },
      { sk: "upřesnit", ua: "уточнити", ru: "уточнить", en: "clarify / specify", img: "/words_a2/spresniť.jpg" },
      { sk: "potvrdit", ua: "підтвердити", ru: "подтвердить", en: "confirm", img: "/words_a2_cz/potvrdit.jpg" },
      { sk: "dohodnout termín", ua: "узгодити дату", ru: "согласовать дату", en: "arrange a date", img: "/words_a2/dohodnúť termín.jpg" },
      { sk: "poslat e-mail", ua: "надіслати email", ru: "отправить e-mail", en: "send an email", img: "/words_a2/poslať e-mail.jpg" },
      { sk: "příloha", ua: "вкладення", ru: "вложение", en: "attachment", img: "/words_a2/príloha.jpg" },
      { sk: "předmět zprávy", ua: "тема повідомлення", ru: "тема сообщения", en: "subject line", img: "/words_a2/predmet správy.jpg" },
    ],
  },
  {
    id: "a2-39",
    title: { ua: "Урок 39 — Навчання мови (корисні слова)", ru: "Урок 39 — Изучение языка (полезные слова)", en: "Lesson 39 — Language learning (useful words)" },
    words: [
      { sk: "slovní zásoba", ua: "словниковий запас", ru: "словарный запас", en: "vocabulary", img: "/words_a2/slovná zásoba.jpg" },
      { sk: "výslovnost", ua: "вимова", ru: "произношение", en: "pronunciation", img: "/words_a2/výslovnosť.jpg" },
      { sk: "gramatika", ua: "граматика", ru: "грамматика", en: "grammar", img: "/words_a2/gramatika.jpg" },
      { sk: "překlad", ua: "переклад", ru: "перевод", en: "translation", img: "/words_a2/preklad.jpg" },
      { sk: "význam", ua: "значення", ru: "значение", en: "meaning", img: "/words_a2/význam.jpg" },
      { sk: "příklad", ua: "приклад", ru: "пример", en: "example", img: "/words_a2/príklad.jpg" },
      { sk: "cvičení", ua: "вправа", ru: "упражнение", en: "exercise", img: "/words_a2/cvičenie.jpg" },
      { sk: "udělat chybu", ua: "зробити помилку", ru: "сделать ошибку", en: "make a mistake", img: "/words_a2/urobiť chybu.jpg" },
      { sk: "zopakovat", ua: "повторити", ru: "повторить", en: "repeat", img: "/words_a2_cz/zopakovat.jpg" },
      { sk: "zlepšit se", ua: "покращитися", ru: "улучшиться", en: "improve", img: "/words_a2/zlepšiť sa.jpg" },
    ],
  },
  {
    id: "a2-40",
    title: { ua: "Урок 40 — Повторення A2 (31–39)", ru: "Урок 40 — Повторение A2 (31–39)", en: "Lesson 40 — Review A2 (31–39)" },
    words: [
      { sk: "kauce", ua: "депозит", ru: "депозит (кауция)", en: "security deposit", img: "/words_a2/kaucia.jpg" },
      { sk: "spolehlivý", ua: "надійний", ru: "надёжный", en: "reliable", img: "/words_a2/spoľahlivý.jpg" },
      { sk: "událost", ua: "подія", ru: "мероприятие / событие", en: "event", img: "/words_a2/podujatie.jpg" },
      { sk: "diagnostika", ua: "діагностика", ru: "диагностика", en: "diagnostics", img: "/words_a2/diagnostika.jpg" },
      { sk: "dodací lhůta", ua: "термін доставки", ru: "срок доставки", en: "delivery time", img: "/words_a2/dodacia lehota.jpg" },
      { sk: "odhlásit se", ua: "виселитися", ru: "выселиться", en: "check out", img: "/words_a2/odubytovať sa.jpg" },
      { sk: "spropitné", ua: "чайові", ru: "чаевые", en: "tip", img: "/words_a2/prepitné.jpg" },
      { sk: "příloha", ua: "вкладення", ru: "вложение", en: "attachment", img: "/words_a2/príloha.jpg" },
      { sk: "slovní zásoba", ua: "словниковий запас", ru: "словарный запас", en: "vocabulary", img: "/words_a2/slovná zásoba.jpg" },
      { sk: "upřesnit", ua: "уточнити", ru: "уточнить", en: "clarify / specify", img: "/words_a2/spresniť.jpg" },
    ],
  },
  {
    id: "a2-41",
    title: { ua: "Урок 41 — Плани та цілі", ru: "Урок 41 — Планы и цели", en: "Lesson 41 — Plans and goals" },
    words: [
      { sk: "ambice", ua: "амбіція", ru: "амбиция", en: "ambition", img: "/words_a2/ambícia.jpg" },
      { sk: "strategie", ua: "стратегія", ru: "стратегия", en: "strategy", img: "/words_a2/stratégia.jpg" },
      { sk: "odhodlání", ua: "рішучість", ru: "решимость", en: "determination", img: "/words_a2/odhodlanie.jpg" },
      { sk: "zvážit", ua: "зважити/розглянути", ru: "взвесить / рассмотреть", en: "consider", img: "/words_a2/zvážiť.jpg" },
      { sk: "přizpůsobit se", ua: "пристосуватися", ru: "приспособиться", en: "adapt", img: "/words_a2/prispôsobiť sa.jpg" },
      { sk: "priorita", ua: "пріоритет", ru: "приоритет", en: "priority", img: "/words_a2/priorita.jpg" },
      { sk: "dosáhnout", ua: "досягти", ru: "достичь", en: "achieve", img: "/words_a2/dosiahnuť.jpg" },
      { sk: "pokrok", ua: "прогрес", ru: "прогресс", en: "progress", img: "/words_a2/pokrok.jpg" },
      { sk: "vytrvat", ua: "витримати / не здатися", ru: "выдержать / не сдаться", en: "persevere", img: "/words_a2/vytrvať.jpg" },
      { sk: "pokračovat", ua: "продовжити", ru: "продолжить", en: "continue", img: "/words_a2_cz/pokračovat.jpg" },
    ],
  },
  {
    id: "a2-42",
    title: { ua: "Урок 42 — У місті (орієнтація)", ru: "Урок 42 — В городе (ориентация)", en: "Lesson 42 — In the city (orientation)" },
    words: [
      { sk: "směr", ua: "напрямок", ru: "направление", en: "direction", img: "/words_a2/smer.jpg" },
      { sk: "odbočit", ua: "повернути", ru: "повернуть", en: "turn", img: "/words_a2/odbočiť.jpg" },
      { sk: "kruhový objezd", ua: "кільце", ru: "кольцевой перекрёсток", en: "roundabout", img: "/words_a2/kruhový objazd.jpg" },
      { sk: "přechod pro chodce", ua: "пішохідний перехід", ru: "пешеходный переход", en: "pedestrian crossing", img: "/words_a2/prechod pre chodcov.jpg" },
      { sk: "zákaz", ua: "заборона", ru: "запрет", en: "ban / prohibition", img: "/words_a2/zákaz.jpg" },
      { sk: "povoleno", ua: "дозволено", ru: "разрешено", en: "allowed", img: "/words_a2/povolené.jpg" },
      { sk: "objížďka", ua: "об’їзд", ru: "объезд", en: "detour", img: "/words_a2/obchádzka.jpg" },
      { sk: "zabloudit", ua: "заблукати", ru: "заблудиться", en: "get lost", img: "/words_a2/zablúdiť.jpg" },
      { sk: "následovat", ua: "слідувати", ru: "следовать", en: "follow", img: "/words_a2/nasledovať.jpg" },
      { sk: "orientovat se", ua: "орієнтуватися", ru: "ориентироваться", en: "find one’s way / orient oneself", img: "/words_a2/orientovať sa.jpg" },
    ],
  },
  {
    id: "a2-43",
    title: { ua: "Урок 43 — Звички та рутина", ru: "Урок 43 — Привычки и рутина", en: "Lesson 43 — Habits and routine" },
    words: [
      { sk: "zvyk", ua: "звичка", ru: "привычка", en: "habit", img: "/words_a2/zvyk.jpg" },
      { sk: "rutina", ua: "рутина", ru: "рутина", en: "routine", img: "/words_a2/rutina.jpg" },
      { sk: "zvyknout si", ua: "звикнути", ru: "привыкнуть", en: "get used to", img: "/words_a2/zvyknúť si.jpg" },
      { sk: "odvyknout si", ua: "відвикнути", ru: "отвыкнуть", en: "break a habit / get out of the habit", img: "/words_a2/odvyknúť si.jpg" },
      { sk: "pravidelně", ua: "регулярно", ru: "регулярно", en: "regularly", img: "/words_a2/pravidelne.jpg" },
      { sk: "výjimka", ua: "виняток", ru: "исключение", en: "exception", img: "/words_a2/výnimka.jpg" },
      { sk: "zlepšit", ua: "покращити", ru: "улучшить", en: "improve", img: "/words_a2/zlepšiť.jpg" },
      { sk: "zhoršit", ua: "погіршити", ru: "ухудшить", en: "worsen", img: "/words_a2/zhoršiť.jpg" },
      { sk: "zdravý styl", ua: "здоровий стиль життя", ru: "здоровый образ жизни", en: "healthy lifestyle", img: "/words_a2/zdravý štýl.jpg" },
      { sk: "disciplína", ua: "дисципліна", ru: "дисциплина", en: "discipline", img: "/words_a2/disciplína.jpg" },
    ],
  },
  {
    id: "a2-44",
    title: { ua: "Урок 44 — Характер і поведінка", ru: "Урок 44 — Характер и поведение", en: "Lesson 44 — Character and behavior" },
    words: [
      { sk: "chování", ua: "поведінка", ru: "поведение", en: "behavior", img: "/words_a2/správanie.jpg" },
      { sk: "zdvořilý", ua: "ввічливий", ru: "вежливый", en: "polite", img: "/words_a2/zdvorilý.jpg" },
      { sk: "drzý", ua: "зухвалий", ru: "дерзкий", en: "rude / cheeky", img: "/words_a2/drzý.jpg" },
      { sk: "trpělivý", ua: "терплячий", ru: "терпеливый", en: "patient", img: "/words_a2_cz/trpělivý.jpg" },
      { sk: "netrpělivý", ua: "нетерплячий", ru: "нетерпеливый", en: "impatient", img: "/words_a2/netrpezlivý.jpg" },
      { sk: "ochotný", ua: "готовий допомогти", ru: "готовый помочь", en: "helpful / willing", img: "/words_a2/ochotný.jpg" },
      { sk: "tvrdohlavý", ua: "впертий", ru: "упрямый", en: "stubborn", img: "/words_a2/tvrdohlavý.jpg" },
      { sk: "přátelský", ua: "дружній", ru: "дружелюбный", en: "friendly", img: "/words_a2_cz/přátelský.jpg" },
      { sk: "odpovědný", ua: "відповідальний", ru: "ответственный", en: "responsible", img: "/words_a2/zodpovedný.jpg" },
      { sk: "lenivý", ua: "ледачий", ru: "ленивый", en: "lazy", img: "/words_a2/lenivý.jpg" },
    ],
  },
  {
    id: "a2-45",
    title: { ua: "Урок 45 — Проблеми та рішення", ru: "Урок 45 — Проблемы и решения", en: "Lesson 45 — Problems and solutions" },
    words: [
      { sk: "situace", ua: "ситуація", ru: "ситуация", en: "situation", img: "/words_a2/situácia.jpg" },
      { sk: "problém", ua: "проблема", ru: "проблема", en: "problem", img: "/words_a2_cz/problém.jpg" },
      { sk: "řešení", ua: "рішення", ru: "решение", en: "solution", img: "/words_a2_cz/řešení.jpg" },
      { sk: "možnost", ua: "варіант", ru: "вариант", en: "option / possibility", img: "/words_a2/možnosť.jpg" },
      { sk: "riziko", ua: "ризик", ru: "риск", en: "risk", img: "/words_a2/riziko.jpg" },
      { sk: "důsledek", ua: "наслідок", ru: "последствие", en: "consequence", img: "/words_a2/dôsledok.jpg" },
      { sk: "výsledek", ua: "результат", ru: "результат", en: "result", img: "/words_a2_cz/výsledek.jpg" },
      { sk: "zvládnout", ua: "впоратися", ru: "справиться", en: "manage / cope", img: "/words_a2/zvládnuť.jpg" },
      { sk: "poradit si", ua: "дати собі раду", ru: "справиться / найти выход", en: "cope / figure it out", img: "/words_a2/poradiť si.jpg" },
      { sk: "pokus", ua: "спроба", ru: "попытка", en: "attempt", img: "/words_a2/pokus.jpg" },
    ],
  },
  {
    id: "a2-46",
    title: { ua: "Урок 46 — Думки та рішення", ru: "Урок 46 — Мысли и решения", en: "Lesson 46 — Thoughts and decisions" },
    words: [
      { sk: "rozhodnutí", ua: "рішення", ru: "решение", en: "decision", img: "/words_a2/rozhodnutie.jpg" },
      { sk: "zvolit", ua: "обрати", ru: "выбрать", en: "choose", img: "/words_a2/zvoliť.jpg" },
      { sk: "změnit názor", ua: "змінити думку", ru: "изменить мнение", en: "change one’s mind", img: "/words_a2/zmeniť názor.jpg" },
      { sk: "pochybovat", ua: "сумніватися", ru: "сомневаться", en: "doubt", img: "/words_a2/pochybovať.jpg" },
      { sk: "jistota", ua: "впевненість", ru: "уверенность", en: "certainty / confidence", img: "/words_a2/istota.jpg" },
      { sk: "nejistota", ua: "невпевненість", ru: "неуверенность", en: "uncertainty / insecurity", img: "/words_a2/neistota.jpg" },
      { sk: "uvědomit si", ua: "усвідомити", ru: "осознать", en: "realize", img: "/words_a2/uvedomiť si.jpg" },
      { sk: "předpokládat", ua: "припускати", ru: "предполагать", en: "assume", img: "/words_a2/predpokladať.jpg" },
      { sk: "zjistit", ua: "з’ясувати", ru: "выяснить", en: "find out", img: "/words_a2/zistiť.jpg" },
      { sk: "závěr", ua: "висновок", ru: "вывод", en: "conclusion", img: "/words_a2/záver.jpg" },
    ],
  },
  {
    id: "a2-47",
    title: { ua: "Урок 47 — Культура та медіа", ru: "Урок 47 — Культура и медиа", en: "Lesson 47 — Culture and media" },
    words: [
      { sk: "kultura", ua: "культура", ru: "культура", en: "culture", img: "/words_a2_cz/kultura.jpg" },
      { sk: "tradice", ua: "традиція", ru: "традиция", en: "tradition", img: "/words_a2_cz/tradice.jpg" },
      { sk: "zvyk", ua: "звичай", ru: "обычай", en: "custom", img: "/words_a2/zvyk.jpg" },
      { sk: "zprávy", ua: "новини", ru: "новости", en: "news", img: "/words_a2_cz/zprávy.jpg" },
      { sk: "článek", ua: "стаття", ru: "статья", en: "article", img: "/words_a2_cz/článek.jpg" },
      { sk: "diskuze", ua: "обговорення", ru: "обсуждение", en: "discussion", img: "/words_a2_cz/diskuze.jpg" },
      { sk: "názor", ua: "думка", ru: "мнение", en: "opinion", img: "/words_a2/názor.jpg" },
      { sk: "reklama", ua: "реклама", ru: "реклама", en: "advertisement", img: "/words_a2/reklama.jpg" },
      { sk: "vliv", ua: "вплив", ru: "влияние", en: "influence", img: "/words_a2/vplyv.jpg" },
      { sk: "zdroj", ua: "джерело", ru: "источник", en: "source", img: "/words_a2/zdroj.jpg" },
    ],
  },
  {
    id: "a2-48",
    title: { ua: "Урок 48 — Природа та подорожі (активності)", ru: "Урок 48 — Природа и путешествия (активности)", en: "Lesson 48 — Nature and travel (activities)" },
    words: [
      { sk: "turistika", ua: "похід/туризм", ru: "поход / туризм", en: "hiking / tourism", img: "/words_a2/turistika.jpg" },
      { sk: "trasa", ua: "маршрут", ru: "маршрут", en: "route", img: "/words_a2/trasa.jpg" },
      { sk: "výstup", ua: "підйом", ru: "подъём", en: "ascent", img: "/words_a2/výstup.jpg" },
      { sk: "sestup", ua: "спуск", ru: "спуск", en: "descent", img: "/words_a2_cz/sestup.jpg" },
      { sk: "výhled", ua: "краєвид", ru: "вид / панорама", en: "view / panorama", img: "/words_a2_cz/výhled.jpg" },
      { sk: "příroda", ua: "природа", ru: "природа", en: "nature", img: "/words_a2_cz/příroda.jpg" },
      { sk: "chráněná oblast", ua: "заповідна зона", ru: "заповедная зона / охраняемая территория", en: "protected area", img: "/words_a2_cz/chráněná oblast.jpg" },
      { sk: "tábor", ua: "табір", ru: "лагерь", en: "camp", img: "/words_a2/tábor.jpg" },
      { sk: "výbava", ua: "спорядження", ru: "снаряжение", en: "equipment", img: "/words_a2/výbava.jpg" },
      { sk: "bezpečnost", ua: "безпека", ru: "безопасность", en: "safety / security", img: "/words_a2/bezpečnosť.jpg" },
    ],
  },
  {
    id: "a2-49",
    title: { ua: "Урок 49 — Погода (умови та поради)", ru: "Урок 49 — Погода (условия и советы)", en: "Lesson 49 — Weather (conditions and advice)" },
    words: [
      { sk: "výstraha", ua: "попередження", ru: "предупреждение", en: "warning", img: "/words_a2/výstraha.jpg" },
      { sk: "silný vítr", ua: "сильний вітер", ru: "сильный ветер", en: "strong wind", img: "/words_a2_cz/silný vítr.jpg" },
      { sk: "mlha", ua: "туман", ru: "туман", en: "fog", img: "/words_a2_cz/mlha.jpg" },
      { sk: "náledí", ua: "ожеледиця", ru: "гололёд", en: "black ice", img: "/words_a2/poľadovica.jpg" },
      { sk: "srážky", ua: "опади", ru: "осадки", en: "precipitation", img: "/words_a2_cz/srážky.jpg" },
      { sk: "vlna veder", ua: "хвиля спеки", ru: "волна жары", en: "heat wave", img: "/words_a2_cz/vlna veder.jpg" },
      { sk: "ochlazení", ua: "похолодання", ru: "похолодание", en: "cooling / cold spell", img: "/words_a2_cz/ochlazení.jpg" },
      { sk: "doporučení", ua: "порада/рекомендація", ru: "совет / рекомендация", en: "advice / recommendation", img: "/words_a2_cz/doporučení.jpg" },
      { sk: "vzít si deštník", ua: "взяти парасолю", ru: "взять зонт", en: "take an umbrella", img: "/words_a2_cz/vzít si deštník.jpg" },
      { sk: "teple se obléknout", ua: "тепло одягтися", ru: "тепло одеться", en: "dress warmly", img: "/words_a2_cz/teple se obléknout.jpg" },
    ],
  },
  {
    id: "a2-50",
    title: { ua: "Урок 50 — Повторення A2 (41–49)", ru: "Урок 50 — Повторение A2 (41–49)", en: "Lesson 50 — Review A2 (41–49)" },
    words: [
      { sk: "dosáhnout", ua: "досягти", ru: "достичь", en: "achieve", img: "/words_a2/dosiahnuť.jpg" },
      { sk: "objížďka", ua: "об’їзд", ru: "объезд", en: "detour", img: "/words_a2/obchádzka.jpg" },
      { sk: "disciplína", ua: "дисципліна", ru: "дисциплина", en: "discipline", img: "/words_a2/disciplína.jpg" },
      { sk: "tvrdohlavý", ua: "впертий", ru: "упрямый", en: "stubborn", img: "/words_a2/tvrdohlavý.jpg" },
      { sk: "poradit si", ua: "дати собі раду", ru: "справиться / найти выход", en: "cope / figure it out", img: "/words_a2/poradiť si.jpg" },
      { sk: "pochybovat", ua: "сумніватися", ru: "сомневаться", en: "doubt", img: "/words_a2/pochybovať.jpg" },
      { sk: "zdroj", ua: "джерело", ru: "источник", en: "source", img: "/words_a2/zdroj.jpg" },
      { sk: "výbava", ua: "спорядження", ru: "снаряжение", en: "equipment", img: "/words_a2/výbava.jpg" },
      { sk: "výstraha", ua: "попередження", ru: "предупреждение", en: "warning", img: "/words_a2/výstraha.jpg" },
      { sk: "orientovat se", ua: "орієнтуватися", ru: "ориентироваться", en: "find one’s way / orient oneself", img: "/words_a2/orientovať sa.jpg" },
    ],
  },
];