import type { Lesson } from "../data";

export const CS_A2_SOURCE: Lesson[] = [
  {
    id: "a2-1",
    title: { ua: "Урок 1 — Дім і побут (розширено)", ru: "Урок 1 — Дом и быт (расширено)" },
    words: [
      { sk: "TODO:nájom", ua: "оренда", ru: "аренда", img: "/words_a2/nájom.jpg" },
      { sk: "TODO:nájomná zmluva", ua: "договір оренди", ru: "договор аренды", img: "/words_a2/nájomná zmluva.jpg" },
      { sk: "TODO:majiteľ", ua: "власник", ru: "владелец", img: "/words_a2/majiteľ.jpg" },
      { sk: "TODO:podnájomník", ua: "орендар", ru: "арендатор (субарендатор)", img: "/words_a2/podnájomník.jpg" },
      { sk: "TODO:účty", ua: "рахунки (комунальні)", ru: "счета (коммунальные)", img: "/words_a2/účty.jpg" },
      { sk: "TODO:energie", ua: "комунальні послуги/енергія", ru: "коммунальные услуги / энергия", img: "/words_a2/energie.jpg" },
      { sk: "TODO:oprava", ua: "ремонт", ru: "ремонт", img: "/words_a2/oprava.jpg" },
      { sk: "TODO:pokazený", ua: "зламаний", ru: "сломанный / неисправный", img: "/words_a2/pokazený.jpg" },
      { sk: "TODO:sused", ua: "сусід", ru: "сосед", img: "/words_a2/sused.jpg" },
      { sk: "TODO:sťahovanie", ua: "переїзд", ru: "переезд", img: "/words_a2/sťahovanie.jpg" },
    ],
  },
  {
    id: "a2-2",
    title: { ua: "Урок 2 — У лікаря", ru: "Урок 2 — У врача" },
    words: [
      { sk: "TODO:vyšetrenie", ua: "обстеження", ru: "обследование", img: "/words_a2/vyšetrenie.jpg" },
      { sk: "TODO:diagnóza", ua: "діагноз", ru: "диагноз", img: "/words_a2/diagnóza.jpg" },
      { sk: "TODO:príznak", ua: "симптом", ru: "симптом", img: "/words_a2/príznak.jpg" },
      { sk: "bolest v krku", ua: "біль у горлі", ru: "боль в горле", img: "/words_a2/bolesť hrdla.jpg" },
      { sk: "TODO:teplomer", ua: "термометр", ru: "термометр", img: "/words_a2/teplomer.jpg" },
      { sk: "TODO:krvný tlak", ua: "артеріальний тиск", ru: "артериальное давление", img: "/words_a2/krvný tlak.jpg" },
      { sk: "TODO:recept", ua: "рецепт (лікарський)", ru: "рецепт (врачебный)", img: "/words_a2/recept.jpg" },
      { sk: "alergie", ua: "алергія", ru: "аллергия", img: "/words_a2/alergia.jpg" },
      { sk: "TODO:zápal", ua: "запалення", ru: "воспаление", img: "/words_a2/zápal.jpg" },
      { sk: "TODO:odporúčanie", ua: "рекомендація", ru: "рекомендация", img: "/words_a2/odporúčanie.jpg" },
    ],
  },
  {
    id: "a2-3",
    title: { ua: "Урок 3 — Місто та послуги", ru: "Урок 3 — Город и услуги" },
    words: [
      { sk: "TODO:mestský úrad", ua: "міська рада/мерія", ru: "городская администрация / мэрия", img: "/words_a2/mestský úrad.jpg" },
      { sk: "TODO:oddelenie", ua: "відділення/відділ", ru: "отдел / отделение", img: "/words_a2/oddelenie.jpg" },
      { sk: "TODO:žiadateľ", ua: "заявник", ru: "заявитель", img: "/words_a2/žiadateľ.jpg" },
      { sk: "TODO:žiadosť", ua: "заява", ru: "заявление", img: "/words_a2/žiadosť.jpg" },
      { sk: "TODO:doklad", ua: "документ", ru: "документ", img: "/words_a2/doklad.jpg" },
      { sk: "TODO:potvrdenie", ua: "підтвердження/довідка", ru: "подтверждение / справка", img: "/words_a2/potvrdenie.jpg" },
      { sk: "TODO:poplatok", ua: "збір/плата", ru: "сбор / плата", img: "/words_a2/poplatok.jpg" },
      { sk: "TODO:objednať sa", ua: "записатися (на прийом)", ru: "записаться (на приём)", img: "/words_a2/objednať sa.jpg" },
      { sk: "TODO:otváracie hodiny", ua: "години роботи", ru: "часы работы", img: "/words_a2/otváracie hodiny.jpg" },
      { sk: "TODO:formulár", ua: "бланк/форма", ru: "бланк / форма", img: "/words_a2/formulár.jpg" },
    ],
  },
  {
    id: "a2-4",
    title: { ua: "Урок 4 — Робота та карʼєра", ru: "Урок 4 — Работа и карьера" },
    words: [
      { sk: "TODO:pohovor", ua: "співбесіда", ru: "собеседование", img: "/words_a2/pohovor.jpg" },
      { sk: "TODO:životopis", ua: "резюме (CV)", ru: "резюме (CV)", img: "/words_a2/životopis.jpg" },
      { sk: "TODO:prax", ua: "досвід роботи/практика", ru: "опыт работы / практика", img: "/words_a2/prax.jpg" },
      { sk: "TODO:zručnosť", ua: "навичка", ru: "навык", img: "/words_a2/zručnosť.jpg" },
      { sk: "TODO:požiadavka", ua: "вимога", ru: "требование", img: "/words_a2/požiadavka.jpg" },
      { sk: "TODO:pracovná ponuka", ua: "вакансія", ru: "вакансия", img: "/words_a2/pracovná ponuka.jpg" },
      { sk: "TODO:pracovná pozícia", ua: "посада", ru: "должность", img: "/words_a2/pracovná pozícia.jpg" },
      { sk: "TODO:zodpovednosť", ua: "відповідальність", ru: "ответственность", img: "/words_a2/zodpovednosť.jpg" },
      { sk: "TODO:výhody", ua: "переваги/бонуси", ru: "льготы / бонусы / преимущества", img: "/words_a2/výhody.jpg" },
      { sk: "TODO:skúšobná doba", ua: "випробувальний термін", ru: "испытательный срок", img: "/words_a2/skúšobná doba.jpg" },
    ],
  },
  {
    id: "a2-5",
    title: { ua: "Урок 5 — Подорожі (ситуації)", ru: "Урок 5 — Путешествия (ситуации)" },
    words: [
      { sk: "TODO:rezervácia", ua: "бронювання", ru: "бронирование", img: "/words_a2/rezervácia.jpg" },
      { sk: "TODO:ubytovanie", ua: "проживання", ru: "проживание", img: "/words_a2/ubytovanie.jpg" },
      { sk: "TODO:potvrdiť", ua: "підтвердити", ru: "подтвердить", img: "/words_a2/potvrdiť.jpg" },
      { sk: "TODO:zrušiť", ua: "скасувати", ru: "отменить", img: "/words_a2/zrušiť.jpg" },
      { sk: "TODO:meškanie", ua: "затримка", ru: "задержка", img: "/words_a2/meškanie.jpg" },
      { sk: "TODO:presun", ua: "переміщення/трансфер", ru: "перемещение / трансфер", img: "/words_a2/presun.jpg" },
      { sk: "TODO:jednosmerný", ua: "в один бік", ru: "в одну сторону", img: "/words_a2/jednosmerný.jpg" },
      { sk: "TODO:spiatočný", ua: "туди-й-назад", ru: "туда-обратно", img: "/words_a2/spiatočný.jpg" },
      { sk: "TODO:cestovné poistenie", ua: "туристична страховка", ru: "туристическая страховка", img: "/words_a2/cestovné poistenie.jpg" },
      { sk: "zavazadlo", ua: "багаж", ru: "багаж", img: "/words_a2/batožina.jpg" },
    ],
  },
  {
    id: "a2-6",
    title: { ua: "Урок 6 — Гроші та фінанси", ru: "Урок 6 — Деньги и финансы" },
    words: [
      { sk: "TODO:rozpočet", ua: "бюджет", ru: "бюджет", img: "/words_a2/rozpočet.jpg" },
      { sk: "TODO:príjem", ua: "дохід", ru: "доход", img: "/words_a2/príjem.jpg" },
      { sk: "TODO:výdavky", ua: "витрати", ru: "расходы", img: "/words_a2/výdavky.jpg" },
      { sk: "TODO:ušetriť", ua: "заощадити", ru: "сэкономить", img: "/words_a2/ušetriť.jpg" },
      { sk: "TODO:minúť", ua: "витратити", ru: "потратить", img: "/words_a2/minúť.jpg" },
      { sk: "TODO:prevod", ua: "переказ", ru: "перевод", img: "/words_a2/prevod.jpg" },
      { sk: "bankovní účet", ua: "банківський рахунок", ru: "банковский счёт", img: "/words_a2/bankový účet.jpg" },
      { sk: "TODO:trvalý príkaz", ua: "постійне доручення (автоплатіж)", ru: "постоянное поручение (автоплатёж)", img: "/words_a2/trvalý príkaz.jpg" },
      { sk: "TODO:úrok", ua: "відсоток (interest)", ru: "процент (ставка)", img: "/words_a2/úrok.jpg" },
      { sk: "TODO:poplatok", ua: "комісія/збір", ru: "комиссия / сбор", img: "/words_a2/poplatok.jpg" },
    ],
  },
  {
    id: "a2-7",
    title: { ua: "Урок 7 — Комунікація та думки", ru: "Урок 7 — Общение и мысли" },
    words: [
      { sk: "TODO:podľa mňa", ua: "на мою думку", ru: "по-моему", img: "/words_a2/podľa mňa.jpg" },
      { sk: "TODO:myslím si", ua: "я думаю", ru: "я думаю", img: "/words_a2/myslím si.jpg" },
      { sk: "TODO:zdá sa mi", ua: "мені здається", ru: "мне кажется", img: "/words_a2/zdá sa mi.jpg" },
      { sk: "TODO:navrhnúť", ua: "запропонувати", ru: "предложить", img: "/words_a2/navrhnúť.jpg" },
      { sk: "TODO:zhrnúť", ua: "підсумувати", ru: "подытожить", img: "/words_a2/zhrnúť.jpg" },
      { sk: "TODO:vyjadriť názor", ua: "висловити думку", ru: "выразить мнение", img: "/words_a2/vyjadriť názor.jpg" },
      { sk: "argumentovat", ua: "аргументувати", ru: "аргументировать", img: "/words_a2/argumentovať.jpg" },
      { sk: "TODO:presvedčiť", ua: "переконати", ru: "убедить", img: "/words_a2/presvedčiť.jpg" },
      { sk: "TODO:spomenúť", ua: "згадати", ru: "упомянуть", img: "/words_a2/spomenúť.jpg" },
      { sk: "TODO:reagovať", ua: "реагувати", ru: "реагировать", img: "/words_a2/reagovať.jpg" },
    ],
  },
  {
    id: "a2-8",
    title: { ua: "Урок 8 — Час, плани, події", ru: "Урок 8 — Время, планы, события" },
    words: [
      { sk: "TODO:posunúť", ua: "перенести (дату/зустріч)", ru: "перенести (дату/встречу)", img: "/words_a2/posunúť.jpg" },
      { sk: "TODO:naplánovať", ua: "запланувати", ru: "запланировать", img: "/words_a2/naplánovať.jpg" },
      { sk: "TODO:odložiť", ua: "відкласти", ru: "отложить", img: "/words_a2/odložiť.jpg" },
      { sk: "TODO:zúčastniť sa", ua: "взяти участь", ru: "принять участие", img: "/words_a2/zúčastniť sa.jpg" },
      { sk: "TODO:zmeniť plán", ua: "змінити план", ru: "изменить план", img: "/words_a2/zmeniť plán.jpg" },
      { sk: "TODO:konať sa", ua: "відбуватися", ru: "проводиться / происходить", img: "/words_a2/konať sa.jpg" },
      { sk: "TODO:organizovať", ua: "організувати", ru: "организовать", img: "/words_a2/organizovať.jpg" },
      { sk: "TODO:uskutočniť sa", ua: "відбутися", ru: "состояться", img: "/words_a2/uskutočniť sa.jpg" },
      { sk: "TODO:meškať", ua: "запізнюватися", ru: "опаздывать", img: "/words_a2/meškať.jpg" },
      { sk: "TODO:stihnúť", ua: "встигнути", ru: "успеть", img: "/words_a2/stihnúť.jpg" },
    ],
  },
  {
    id: "a2-9",
    title: { ua: "Урок 9 — Покупки та рекламації", ru: "Урок 9 — Покупки и рекламации" },
    words: [
      { sk: "TODO:podmienky", ua: "умови", ru: "условия", img: "/words_a2/podmienky.jpg" },
      { sk: "TODO:sťažnosť", ua: "скарга", ru: "жалоба", img: "/words_a2/sťažnosť.jpg" },
      { sk: "TODO:peniaze späť", ua: "гроші назад", ru: "деньги обратно", img: "/words_a2/peniaze späť.jpg" },
      { sk: "TODO:vrátenie tovaru", ua: "повернення товару", ru: "возврат товара", img: "/words_a2/vrátenie tovaru.jpg" },
      { sk: "TODO:pokladničný blok", ua: "касовий чек", ru: "кассовый чек", img: "/words_a2/pokladničný blok.jpg" },
      { sk: "TODO:reklamovať", ua: "подати рекламацію", ru: "подать рекламацию", img: "/words_a2/reklamovať.jpg" },
      { sk: "TODO:doklad", ua: "документ / підтвердження", ru: "документ / подтверждение", img: "/words_a2/doklad.jpg" },
      { sk: "TODO:výmena", ua: "обмін", ru: "обмен", img: "/words_a2/výmena.jpg" },
      { sk: "TODO:lehota", ua: "термін", ru: "срок", img: "/words_a2/lehota.jpg" },
      { sk: "TODO:náhrada", ua: "компенсація / заміна", ru: "компенсация / замена", img: "/words_a2/náhrada.jpg" },
    ],
  },
  {
    id: "a2-10",
    title: { ua: "Урок 10 — Погода і природа (розширено)", ru: "Урок 10 — Погода и природа (расширено)" },
    words: [
      { sk: "TODO:predpoveď", ua: "прогноз", ru: "прогноз", img: "/words_a2/predpoveď.jpg" },
      { sk: "TODO:polooblačno", ua: "мінлива хмарність", ru: "переменная облачность", img: "/words_a2/polooblačno.jpg" },
      { sk: "TODO:prehánka", ua: "злива/короткий дощ", ru: "ливень / кратковременный дождь", img: "/words_a2/prehánka.jpg" },
      { sk: "TODO:jasno", ua: "ясно", ru: "ясно", img: "/words_a2/jasno.jpg" },
      { sk: "TODO:poľadovica", ua: "ожеледиця", ru: "гололёд", img: "/words_a2/poľadovica.jpg" },
      { sk: "TODO:vlhkosť", ua: "вологість", ru: "влажность", img: "/words_a2/vlhkosť.jpg" },
      { sk: "TODO:oblačno", ua: "хмарно", ru: "облачно", img: "/words_a2/oblačno.jpg" },
      { sk: "TODO:ochladiť sa", ua: "похолоднішати", ru: "похолодать", img: "/words_a2/ochladiť sa.jpg" },
      { sk: "TODO:otepliť sa", ua: "потеплішати", ru: "потеплеть", img: "/words_a2/otepliť sa.jpg" },
      { sk: "TODO:prudký vietor", ua: "сильний вітер", ru: "сильный ветер", img: "/words_a2/prudký vietor.jpg" },
    ],
  },
  {
    id: "a2-11",
    title: { ua: "Урок 11 — Харчування та здорові звички", ru: "Урок 11 — Питание и здоровые привычки" },
    words: [
      { sk: "TODO:strava", ua: "харчування", ru: "питание", img: "/words_a2/strava.jpg" },
      { sk: "TODO:zdravé jedlo", ua: "здорова їжа", ru: "здоровая еда", img: "/words_a2/zdravé jedlo.jpg" },
      { sk: "TODO:nezdravé", ua: "нездоровий", ru: "нездоровый", img: "/words_a2/nezdravé.jpg" },
      { sk: "TODO:kalórie", ua: "калорії", ru: "калории", img: "/words_a2/kalórie.jpg" },
      { sk: "TODO:vitamíny", ua: "вітаміни", ru: "витамины", img: "/words_a2/vitamíny.jpg" },
      { sk: "bílkoviny", ua: "білки", ru: "белки", img: "/words_a2/bielkoviny.jpg" },
      { sk: "TODO:tuky", ua: "жири", ru: "жиры", img: "/words_a2/tuky.jpg" },
      { sk: "TODO:cukor", ua: "цукор", ru: "сахар", img: "/words_a2/cukor.jpg" },
      { sk: "TODO:soľ", ua: "сіль", ru: "соль", img: "/words_a2/soľ.jpg" },
      { sk: "TODO:hydratácia", ua: "гідратація", ru: "гидратация", img: "/words_a2/hydratácia.jpg" },
    ],
  },
  {
    id: "a2-12",
    title: { ua: "Урок 12 — Спорт і активність", ru: "Урок 12 — Спорт и активность" },
    words: [
      { sk: "TODO:tréning", ua: "тренування", ru: "тренировка", img: "/words_a2/tréning.jpg" },
      { sk: "TODO:cvičiť", ua: "тренуватися", ru: "тренироваться / заниматься", img: "/words_a2/cvičiť.jpg" },
      { sk: "TODO:posilňovňa", ua: "спортзал", ru: "спортзал / тренажёрный зал", img: "/words_a2/posilňovňa.jpg" },
      { sk: "TODO:vytrvalosť", ua: "витривалість", ru: "выносливость", img: "/words_a2/vytrvalosť.jpg" },
      { sk: "TODO:sila", ua: "сила", ru: "сила", img: "/words_a2/sila.jpg" },
      { sk: "TODO:tempo", ua: "темп", ru: "темп", img: "/words_a2/tempo.jpg" },
      { sk: "TODO:zahriať sa", ua: "розігрітися", ru: "разогреться", img: "/words_a2/zahriať sa.jpg" },
      { sk: "TODO:natiahnuť sa", ua: "розтягнутися", ru: "растянуться", img: "/words_a2/natiahnuť sa.jpg" },
      { sk: "TODO:zranenie", ua: "травма", ru: "травма", img: "/words_a2/zranenie.jpg" },
      { sk: "TODO:regenerácia", ua: "відновлення", ru: "восстановление", img: "/words_a2/regenerácia.jpg" },
    ],
  },
  {
    id: "a2-13",
    title: { ua: "Урок 13 — Відносини та спілкування", ru: "Урок 13 — Отношения и общение" },
    words: [
      { sk: "TODO:vzťah", ua: "стосунки", ru: "отношения", img: "/words_a2/vzťah.jpg" },
      { sk: "TODO:dôvera", ua: "довіра", ru: "доверие", img: "/words_a2/dôvera.jpg" },
      { sk: "TODO:rešpekt", ua: "повага", ru: "уважение", img: "/words_a2/rešpekt.jpg" },
      { sk: "TODO:podpora", ua: "підтримка", ru: "поддержка", img: "/words_a2/podpora.jpg" },
      { sk: "TODO:hádať sa", ua: "сваритися", ru: "ссориться", img: "/words_a2/hádať sa.jpg" },
      { sk: "TODO:zmieriť sa", ua: "помиритися", ru: "помириться", img: "/words_a2/zmieriť sa.jpg" },
      { sk: "TODO:dohoda", ua: "домовленість", ru: "договорённость / соглашение", img: "/words_a2/dohoda.jpg" },
      { sk: "TODO:kompromis", ua: "компроміс", ru: "компромисс", img: "/words_a2/kompromis.jpg" },
      { sk: "TODO:úprimný", ua: "щирий", ru: "искренний", img: "/words_a2/úprimný.jpg" },
      { sk: "TODO:trpezlivosť", ua: "терпіння", ru: "терпение", img: "/words_a2/trpezlivosť.jpg" },
    ],
  },
  {
    id: "a2-14",
    title: { ua: "Урок 14 — Покупки онлайн і доставка", ru: "Урок 14 — Онлайн-покупки и доставка" },
    words: [
      { sk: "TODO:objednávka", ua: "замовлення", ru: "заказ", img: "/words_a2/objednávka.jpg" },
      { sk: "TODO:doručenie", ua: "доставка", ru: "доставка", img: "/words_a2/doručenie.jpg" },
      { sk: "balík", ua: "посилка", ru: "посылка", img: "/words_a2/balík.jpg" },
      { sk: "TODO:kuriér", ua: "кур’єр", ru: "курьер", img: "/words_a2/kuriér.jpg" },
      { sk: "TODO:sledovanie zásielky", ua: "відстеження посилки", ru: "отслеживание посылки", img: "/words_a2/sledovanie zásielky.jpg" },
      { sk: "doručovací adresa", ua: "адреса доставки", ru: "адрес доставки", img: "/words_a2/adresa doručenia.jpg" },
      { sk: "TODO:vrátenie", ua: "повернення", ru: "возврат", img: "/words_a2/vrátenie.jpg" },
      { sk: "TODO:výmena", ua: "обмін", ru: "обмен", img: "/words_a2/výmena.jpg" },
      { sk: "TODO:poštovné", ua: "вартість доставки", ru: "стоимость доставки", img: "/words_a2/poštovné.jpg" },
      { sk: "TODO:platba kartou", ua: "оплата карткою", ru: "оплата картой", img: "/words_a2/platba kartou.jpg" },
    ],
  },
  {
    id: "a2-15",
    title: { ua: "Урок 15 — Технології (побутові ситуації)", ru: "Урок 15 — Технологии (бытовые ситуации)" },
    words: [
      { sk: "TODO:nastaviť", ua: "налаштувати", ru: "настроить", img: "/words_a2/nastaviť.jpg" },
      { sk: "aktualizace", ua: "оновлення", ru: "обновление", img: "/words_a2/aktualizácia.jpg" },
      { sk: "TODO:pripojenie", ua: "підключення", ru: "подключение", img: "/words_a2/pripojenie.jpg" },
      { sk: "TODO:signál", ua: "сигнал", ru: "сигнал", img: "/words_a2/signál.jpg" },
      { sk: "TODO:výpadok", ua: "збій/відключення", ru: "сбой / отключение", img: "/words_a2/výpadok.jpg" },
      { sk: "TODO:zaseknúť sa", ua: "зависнути", ru: "зависнуть", img: "/words_a2/zaseknúť sa.jpg" },
      { sk: "TODO:reštartovať", ua: "перезавантажити", ru: "перезагрузить", img: "/words_a2/reštartovať.jpg" },
      { sk: "TODO:nainštalovať", ua: "встановити", ru: "установить", img: "/words_a2/nainštalovať.jpg" },
      { sk: "TODO:vymazať", ua: "видалити", ru: "удалить", img: "/words_a2/vymazať.jpg" },
      { sk: "TODO:obnoviť", ua: "відновити", ru: "восстановить", img: "/words_a2/obnoviť.jpg" },
    ],
  },
  {
    id: "a2-16",
    title: { ua: "Урок 16 — Освіта і навчання", ru: "Урок 16 — Образование и обучение" },
    words: [
      { sk: "TODO:kurz", ua: "курс", ru: "курс", img: "/words_a2/kurz.jpg" },
      { sk: "TODO:prednáška", ua: "лекція", ru: "лекция", img: "/words_a2/prednáška.jpg" },
      { sk: "TODO:poznámky", ua: "конспект/нотатки", ru: "конспект / заметки", img: "/words_a2/poznámky.jpg" },
      { sk: "TODO:domáca úloha", ua: "домашнє завдання", ru: "домашнее задание", img: "/words_a2/domáca úloha.jpg" },
      { sk: "TODO:skúška", ua: "іспит", ru: "экзамен", img: "/words_a2/skúška.jpg" },
      { sk: "TODO:certifikát", ua: "сертифікат", ru: "сертификат", img: "/words_a2/certifikát.jpg" },
      { sk: "TODO:zručnosť", ua: "навичка", ru: "навык", img: "/words_a2/zručnosť.jpg" },
      { sk: "TODO:zlepšiť sa", ua: "покращитися", ru: "улучшиться", img: "/words_a2/zlepšiť sa.jpg" },
      { sk: "TODO:opakovať", ua: "повторювати", ru: "повторять", img: "/words_a2/opakovať.jpg" },
      { sk: "TODO:učiť sa naspamäť", ua: "вчити напам’ять", ru: "учить наизусть", img: "/words_a2/učiť sa naspamäť.jpg" },
    ],
  },
  {
    id: "a2-17",
    title: { ua: "Урок 17 — На роботі (комунікація)", ru: "Урок 17 — На работе (общение)" },
    words: [
      { sk: "TODO:rozdeliť úlohy", ua: "розподілити завдання", ru: "распределить задачи", img: "/words_a2/rozdeliť úlohy.jpg" },
      { sk: "TODO:spolupracovať", ua: "співпрацювати", ru: "сотрудничать", img: "/words_a2/spolupracovať.jpg" },
      { sk: "TODO:priorita", ua: "пріоритет", ru: "приоритет", img: "/words_a2/priorita.jpg" },
      { sk: "TODO:zodpovedať", ua: "відповідати (бути відповідальним)", ru: "отвечать (быть ответственным)", img: "/words_a2/zodpovedať.jpg" },
      { sk: "TODO:odovzdať", ua: "здати/передати", ru: "сдать / передать", img: "/words_a2/odovzdať.jpg" },
      { sk: "TODO:skontrolovať", ua: "перевірити", ru: "проверить", img: "/words_a2/skontrolovať.jpg" },
      { sk: "TODO:organizovať", ua: "організовувати", ru: "организовывать", img: "/words_a2/organizovať.jpg" },
      { sk: "TODO:spätná väzba", ua: "зворотний зв’язок", ru: "обратная связь", img: "/words_a2/spätná väzba.jpg" },
      { sk: "TODO:navrhnúť riešenie", ua: "запропонувати рішення", ru: "предложить решение", img: "/words_a2/navrhnúť riešenie.jpg" },
      { sk: "TODO:dokončiť", ua: "завершити", ru: "завершить", img: "/words_a2/dokončiť.jpg" },
    ],
  },
  {
    id: "a2-18",
    title: { ua: "Урок 18 — Банківські справи", ru: "Урок 18 — Банковские дела" },
    words: [
      { sk: "TODO:založiť účet", ua: "відкрити рахунок", ru: "открыть счёт", img: "/words_a2/založiť účet.jpg" },
      { sk: "TODO:výber", ua: "зняття (грошей)", ru: "снятие (денег)", img: "/words_a2/výber.jpg" },
      { sk: "TODO:vklad", ua: "внесення (грошей)", ru: "внесение (денег) / вклад", img: "/words_a2/vklad.jpg" },
      { sk: "TODO:previesť", ua: "перевести (гроші)", ru: "перевести (деньги)", img: "/words_a2/previesť.jpg" },
      { sk: "TODO:platobná karta", ua: "платіжна картка", ru: "платёжная карта", img: "/words_a2/platobná karta.jpg" },
      { sk: "TODO:PIN kód", ua: "пін-код", ru: "пин-код", img: "/words_a2/PIN kód.jpg" },
      { sk: "TODO:limit", ua: "ліміт", ru: "лимит", img: "/words_a2/limit.jpg" },
      { sk: "TODO:poplatok", ua: "комісія", ru: "комиссия", img: "/words_a2/poplatok.jpg" },
      { sk: "TODO:výpis", ua: "виписка", ru: "выписка", img: "/words_a2/výpis.jpg" },
      { sk: "zablokovat kartu", ua: "заблокувати картку", ru: "заблокировать карту", img: "/words_a2/blokovať kartu.jpg" },
    ],
  },
  {
    id: "a2-19",
    title: { ua: "Урок 19 — Державні документи", ru: "Урок 19 — Госдокументы" },
    words: [
      { sk: "TODO:povolenie", ua: "дозвіл", ru: "разрешение", img: "/words_a2/povolenie.jpg" },
      { sk: "TODO:pobyt", ua: "дозвіл на проживання/побут", ru: "вид на жительство / пребывание", img: "/words_a2/pobyt.jpg" },
      { sk: "TODO:občiansky preukaz", ua: "ID-картка", ru: "ID-карта / удостоверение личности", img: "/words_a2/občiansky preukaz.jpg" },
      { sk: "TODO:registrácia", ua: "реєстрація", ru: "регистрация", img: "/words_a2/registrácia.jpg" },
      { sk: "TODO:podpis", ua: "підпис", ru: "подпись", img: "/words_a2/podpis.jpg" },
      { sk: "TODO:fotografia", ua: "фото", ru: "фото", img: "/words_a2/fotografia.jpg" },
      { sk: "TODO:overiť", ua: "завірити/підтвердити", ru: "заверить / подтвердить", img: "/words_a2/overiť.jpg" },
      { sk: "TODO:termín stretnutia", ua: "дата прийому", ru: "дата приёма", img: "/words_a2/termín stretnutia.jpg" },
      { sk: "TODO:vybaviť", ua: "оформити/вирішити (справу)", ru: "оформить / решить (дело)", img: "/words_a2/vybaviť.jpg" },
      { sk: "TODO:rodné číslo", ua: "ідентифікаційний номер", ru: "идентификационный номер", img: "/words_a2/rodné číslo.jpg" },
    ],
  },
  {
    id: "a2-20",
    title: { ua: "Урок 20 — Повторення A2 (11–19)", ru: "Урок 20 — Повторение A2 (11–19)" },
    words: [
      { sk: "TODO:strava", ua: "харчування", ru: "питание", img: "/words_a2/strava.jpg" },
      { sk: "TODO:tréning", ua: "тренування", ru: "тренировка", img: "/words_a2/tréning.jpg" },
      { sk: "TODO:kompromis", ua: "компроміс", ru: "компромисс", img: "/words_a2/kompromis.jpg" },
      { sk: "TODO:doručenie", ua: "доставка", ru: "доставка", img: "/words_a2/doručenie.jpg" },
      { sk: "aktualizace", ua: "оновлення", ru: "обновление", img: "/words_a2/aktualizácia.jpg" },
      { sk: "TODO:prednáška", ua: "лекція", ru: "лекция", img: "/words_a2/prednáška.jpg" },
      { sk: "TODO:spätná väzba", ua: "зворотний зв’язок", ru: "обратная связь", img: "/words_a2/spätná väzba.jpg" },
      { sk: "TODO:výpis", ua: "виписка", ru: "выписка", img: "/words_a2/výpis.jpg" },
      { sk: "TODO:povolenie", ua: "дозвіл", ru: "разрешение", img: "/words_a2/povolenie.jpg" },
      { sk: "TODO:vybaviť", ua: "оформити/вирішити", ru: "оформить / решить", img: "/words_a2/vybaviť.jpg" },
    ],
  },
  {
    id: "a2-21",
    title: { ua: "Урок 21 — Дім (проблеми та майстер)", ru: "Урок 21 — Дом (проблемы и мастер)" },
    words: [
      { sk: "TODO:porucha", ua: "поломка/несправність", ru: "поломка / неисправность", img: "/words_a2/porucha.jpg" },
      { sk: "TODO:inštalatér", ua: "сантехнік", ru: "сантехник", img: "/words_a2/inštalatér.jpg" },
      { sk: "TODO:elektrikár", ua: "електрик", ru: "электрик", img: "/words_a2/elektrikár.jpg" },
      { sk: "TODO:opraviť", ua: "відремонтувати", ru: "отремонтировать", img: "/words_a2/opraviť.jpg" },
      { sk: "TODO:vymeniť", ua: "замінити", ru: "заменить", img: "/words_a2/vymeniť.jpg" },
      { sk: "TODO:prietok", ua: "протікання", ru: "протечка", img: "/words_a2/prietok.jpg" },
      { sk: "TODO:upchatie", ua: "засмічення", ru: "засор", img: "/words_a2/upchatie.jpg" },
      { sk: "TODO:zatekať", ua: "протікати", ru: "протекать", img: "/words_a2/zatekať.jpg" },
      { sk: "TODO:poškodenie", ua: "пошкодження", ru: "повреждение", img: "/words_a2/poškodenie.jpg" },
      { sk: "TODO:náhradný diel", ua: "запасна частина", ru: "запасная часть", img: "/words_a2/náhradný diel.jpg" },
    ],
  },
  {
    id: "a2-22",
    title: { ua: "Урок 22 — Здоровʼя (аптека та лікування)", ru: "Урок 22 — Здоровье (аптека и лечение)" },
    words: [
      { sk: "TODO:vedľajšie účinky", ua: "побічні ефекти", ru: "побочные эффекты", img: "/words_a2/vedľajšie účinky.jpg" },
      { sk: "TODO:dávkovanie", ua: "дозування", ru: "дозировка", img: "/words_a2/dávkovanie.jpg" },
      { sk: "TODO:návod", ua: "інструкція", ru: "инструкция", img: "/words_a2/návod.jpg" },
      { sk: "TODO:liek proti bolesti", ua: "знеболювальне", ru: "обезболивающее", img: "/words_a2/liek proti bolesti.jpg" },
      { sk: "antibiotika", ua: "антибіотики", ru: "антибиотики", img: "/words_a2/antibiotiká.jpg" },
      { sk: "TODO:očkovanie", ua: "вакцинація", ru: "вакцинация", img: "/words_a2/očkovanie.jpg" },
      { sk: "TODO:recept", ua: "рецепт", ru: "рецепт", img: "/words_a2/recept.jpg" },
      { sk: "bez receptu", ua: "без рецепта", ru: "без рецепта", img: "/words_a2/bez receptu.jpg" },
      { sk: "TODO:kontrola", ua: "контроль/огляд", ru: "контроль / осмотр", img: "/words_a2/kontrola.jpg" },
      { sk: "TODO:uzdravovať sa", ua: "одужувати", ru: "выздоравливать", img: "/words_a2/uzdravovať sa.jpg" },
    ],
  },
  {
    id: "a2-23",
    title: { ua: "Урок 23 — Місто (безпека та служби)", ru: "Урок 23 — Город (безопасность и службы)" },
    words: [
      { sk: "TODO:nehoda", ua: "аварія/нещасний випадок", ru: "авария / несчастный случай", img: "/words_a2/nehoda.jpg" },
      { sk: "TODO:záchranka", ua: "швидка допомога", ru: "скорая помощь", img: "/words_a2/záchranka.jpg" },
      { sk: "TODO:hasiči", ua: "пожежники", ru: "пожарные", img: "/words_a2/hasiči.jpg" },
      { sk: "TODO:policajná stanica", ua: "відділок поліції", ru: "отделение полиции", img: "/words_a2/policajná stanica.jpg" },
      { sk: "TODO:svedok", ua: "свідок", ru: "свидетель", img: "/words_a2/svedok.jpg" },
      { sk: "TODO:krádež", ua: "крадіжка", ru: "кража", img: "/words_a2/krádež.jpg" },
      { sk: "TODO:nahlásiť", ua: "повідомити/заявити", ru: "сообщить / заявить", img: "/words_a2/nahlásiť.jpg" },
      { sk: "TODO:doklady", ua: "документи", ru: "документы", img: "/words_a2/doklady.jpg" },
      { sk: "TODO:stratiť", ua: "загубити", ru: "потерять", img: "/words_a2/stratiť.jpg" },
      { sk: "TODO:nájsť", ua: "знайти", ru: "найти", img: "/words_a2/nájsť.jpg" },
    ],
  },
  {
    id: "a2-24",
    title: { ua: "Урок 24 — Їжа (покупки та приготування)", ru: "Урок 24 — Еда (покупки и готовка)" },
    words: [
      { sk: "TODO:ingrediencie", ua: "інгредієнти", ru: "ингредиенты", img: "/words_a2/ingrediencie.jpg" },
      { sk: "TODO:recept (kuchársky)", ua: "рецепт (кулінарний)", ru: "рецепт (кулинарный)", img: "/words_a2/recept (kuchársky).jpg" },
      { sk: "TODO:nakrájať", ua: "нарізати", ru: "нарезать", img: "/words_a2/nakrájať.jpg" },
      { sk: "TODO:zmiešať", ua: "змішати", ru: "смешать", img: "/words_a2/zmiešať.jpg" },
      { sk: "TODO:osmažiť", ua: "підсмажити", ru: "поджарить", img: "/words_a2/osmažiť.jpg" },
      { sk: "TODO:uvariť", ua: "зварити", ru: "сварить", img: "/words_a2/uvariť.jpg" },
      { sk: "TODO:upiecť", ua: "спекти", ru: "испечь", img: "/words_a2/upiecť.jpg" },
      { sk: "TODO:ochutiť", ua: "приправити", ru: "приправить", img: "/words_a2/ochutiť.jpg" },
      { sk: "TODO:porcia", ua: "порція", ru: "порция", img: "/words_a2/porcia.jpg" },
      { sk: "TODO:zvyšky", ua: "залишки їжі", ru: "остатки еды", img: "/words_a2/zvyšky.jpg" },
    ],
  },
  {
    id: "a2-25",
    title: { ua: "Урок 25 — Подорожі (планування маршруту)", ru: "Урок 25 — Путешествия (планирование маршрута)" },
    words: [
      { sk: "TODO:itinerár", ua: "маршрут/план подорожі", ru: "маршрут / план поездки", img: "/words_a2/itinerár.jpg" },
      { sk: "TODO:prestup", ua: "пересадка", ru: "пересадка", img: "/words_a2/prestup.jpg" },
      { sk: "TODO:spoj", ua: "рейс/сполучення", ru: "рейс / сообщение", img: "/words_a2/spoj.jpg" },
      { sk: "TODO:oneskorenie", ua: "затримка", ru: "задержка", img: "/words_a2/oneskorenie.jpg" },
      { sk: "TODO:zrušený", ua: "скасований", ru: "отменённый", img: "/words_a2/zrušený.jpg" },
      { sk: "TODO:odbavenie", ua: "реєстрація / оформлення", ru: "регистрация / оформление", img: "/words_a2/odbavenie.jpg" },
      { sk: "TODO:cestovný poriadok", ua: "розклад руху", ru: "расписание движения", img: "/words_a2/cestovný poriadok.jpg" },
      { sk: "TODO:spiatočný lístok", ua: "квиток туди-назад", ru: "билет туда-обратно", img: "/words_a2/spiatočný lístok.jpg" },
      { sk: "TODO:jednosmerný lístok", ua: "квиток в один бік", ru: "билет в одну сторону", img: "/words_a2/jednosmerný lístok.jpg" },
      { sk: "TODO:cestovný lístok", ua: "квиток", ru: "билет", img: "/words_a2/cestovný lístok.jpg" },
    ],
  },
  {
    id: "a2-26",
    title: { ua: "Урок 26 — Комунікація та інформація", ru: "Урок 26 — Коммуникация и информация" },
    words: [
      { sk: "TODO:správa", ua: "повідомлення", ru: "сообщение", img: "/words_a2/správa.jpg" },
      { sk: "TODO:oznámenie", ua: "оголошення", ru: "объявление", img: "/words_a2/oznámenie.jpg" },
      { sk: "TODO:článok", ua: "стаття", ru: "статья", img: "/words_a2/článok.jpg" },
      { sk: "TODO:zdroj informácií", ua: "джерело інформації", ru: "источник информации", img: "/words_a2/zdroj informácií.jpg" },
      { sk: "TODO:uverejniť", ua: "опублікувати", ru: "опубликовать", img: "/words_a2/uverejniť.jpg" },
      { sk: "TODO:zverejniť", ua: "оприлюднити", ru: "опубликовать / обнародовать", img: "/words_a2/zverejniť.jpg" },
      { sk: "TODO:reagovať", ua: "реагувати", ru: "реагировать", img: "/words_a2/reagovať.jpg" },
      { sk: "TODO:diskusia", ua: "дискусія", ru: "дискуссия", img: "/words_a2/diskusia.jpg" },
      { sk: "TODO:názor", ua: "думка", ru: "мнение", img: "/words_a2/názor.jpg" },
      { sk: "TODO:vplyv", ua: "вплив", ru: "влияние", img: "/words_a2/vplyv.jpg" },
    ],
  },
  {
    id: "a2-27",
    title: { ua: "Урок 27 — Комунікація (заперечення та аргументи)", ru: "Урок 27 — Общение (возражения и аргументы)" },
    words: [
      { sk: "TODO:naopak", ua: "навпаки", ru: "наоборот", img: "/words_a2/naopak.jpg" },
      { sk: "TODO:v skutočnosti", ua: "насправді", ru: "на самом деле", img: "/words_a2/v skutočnosti.jpg" },
      { sk: "TODO:dôkaz", ua: "доказ", ru: "доказательство", img: "/words_a2/dôkaz.jpg" },
      { sk: "argument", ua: "аргумент", ru: "аргумент", img: "/words_a2/argument.jpg" },
      { sk: "TODO:dôvod", ua: "причина", ru: "причина", img: "/words_a2/dôvod.jpg" },
      { sk: "TODO:výhoda", ua: "перевага", ru: "преимущество", img: "/words_a2/výhoda.jpg" },
      { sk: "TODO:nevýhoda", ua: "недолік", ru: "недостаток", img: "/words_a2/nevýhoda.jpg" },
      { sk: "TODO:záleží", ua: "залежить", ru: "зависит", img: "/words_a2/záleží.jpg" },
      { sk: "TODO:presvedčiť", ua: "переконати", ru: "убедить", img: "/words_a2/presvedčiť.jpg" },
      { sk: "TODO:súhlasiť s tým", ua: "погодитися з цим", ru: "согласиться с этим", img: "/words_a2/súhlasiť s tým.jpg" },
    ],
  },
  {
    id: "a2-28",
    title: { ua: "Урок 28 — Технології (інтернет та безпека)", ru: "Урок 28 — Технологии (интернет и безопасность)" },
    words: [
      { sk: "TODO:súkromie", ua: "приватність", ru: "приватность", img: "/words_a2/súkromie.jpg" },
      { sk: "bezpečnost", ua: "безпека", ru: "безопасность", img: "/words_a2/bezpečnosť.jpg" },
      { sk: "TODO:overenie", ua: "підтвердження/верифікація", ru: "подтверждение / верификация", img: "/words_a2/overenie.jpg" },
      { sk: "TODO:dvojfaktorové overenie", ua: "2FA (двофакторна перевірка)", ru: "2FA (двухфакторная проверка)", img: "/words_a2/dvojfaktorové overenie.jpg" },
      { sk: "TODO:podvod", ua: "шахрайство", ru: "мошенничество", img: "/words_a2/podvod.jpg" },
      { sk: "TODO:odkaz", ua: "посилання", ru: "ссылка", img: "/words_a2/odkaz.jpg" },
      { sk: "TODO:stiahnuť súbor", ua: "завантажити файл", ru: "скачать файл", img: "/words_a2/stiahnuť súbor.jpg" },
      { sk: "TODO:vírus", ua: "вірус", ru: "вирус", img: "/words_a2/vírus.jpg" },
      { sk: "TODO:zablokovať", ua: "заблокувати", ru: "заблокировать", img: "/words_a2/zablokovať.jpg" },
      { sk: "TODO:obnoviť heslo", ua: "відновити пароль", ru: "восстановить пароль", img: "/words_a2/obnoviť heslo.jpg" },
    ],
  },
  {
    id: "a2-29",
    title: { ua: "Урок 29 — Емоції (розширено)", ru: "Урок 29 — Эмоции (расширено)" },
    words: [
      { sk: "TODO:sklamaný", ua: "розчарований", ru: "разочарованный", img: "/words_a2/sklamaný.jpg" },
      { sk: "TODO:nahnevaný", ua: "розлючений", ru: "разъярённый / злой", img: "/words_a2/nahnevaný.jpg" },
      { sk: "TODO:nadšený", ua: "захоплений", ru: "восторженный / воодушевлённый", img: "/words_a2/nadšený.jpg" },
      { sk: "TODO:zmätený", ua: "розгублений", ru: "растерянный", img: "/words_a2/zmätený.jpg" },
      { sk: "TODO:znepokojený", ua: "стурбований", ru: "обеспокоенный", img: "/words_a2/znepokojený.jpg" },
      { sk: "TODO:hrdý", ua: "гордий", ru: "гордый", img: "/words_a2/hrdý.jpg" },
      { sk: "TODO:vďačný", ua: "вдячний", ru: "благодарный", img: "/words_a2/vďačný.jpg" },
      { sk: "TODO:hanbiť sa", ua: "соромитися", ru: "стыдиться", img: "/words_a2/hanbiť sa.jpg" },
      { sk: "TODO:ľutovať", ua: "шкодувати", ru: "жалеть / сожалеть", img: "/words_a2/ľutovať.jpg" },
      { sk: "TODO:uľaviť sa", ua: "полегшало", ru: "полегчало", img: "/words_a2/uľaviť sa.jpg" },
    ],
  },
  {
    id: "a2-30",
    title: { ua: "Урок 30 — Повторення A2 (21–29)", ru: "Урок 30 — Повторение A2 (21–29)" },
    words: [
      { sk: "TODO:náhradný diel", ua: "запасна частина", ru: "запасная часть", img: "/words_a2/náhradný diel.jpg" },
      { sk: "TODO:dávkovanie", ua: "дозування", ru: "дозировка", img: "/words_a2/dávkovanie.jpg" },
      { sk: "TODO:krádež", ua: "крадіжка", ru: "кража", img: "/words_a2/krádež.jpg" },
      { sk: "TODO:ingrediencie", ua: "інгредієнти", ru: "ингредиенты", img: "/words_a2/ingrediencie.jpg" },
      { sk: "TODO:itinerár", ua: "маршрут", ru: "маршрут / план поездки", img: "/words_a2/itinerár.jpg" },
      { sk: "TODO:výplatná páska", ua: "розрахунковий лист", ru: "расчётный листок", img: "/words_a2/výplatná páska.jpg" },
      { sk: "argument", ua: "аргумент", ru: "аргумент", img: "/words_a2/argument.jpg" },
      { sk: "TODO:podvod", ua: "шахрайство", ru: "мошенничество", img: "/words_a2/podvod.jpg" },
      { sk: "TODO:znepokojený", ua: "стурбований", ru: "обеспокоенный", img: "/words_a2/znepokojený.jpg" },
      { sk: "TODO:záleží", ua: "залежить", ru: "зависит", img: "/words_a2/záleží.jpg" },
    ],
  },
  {
    id: "a2-31",
    title: { ua: "Урок 31 — Житло (пошук і оренда)", ru: "Урок 31 — Жильё (поиск и аренда)" },
    words: [
      { sk: "TODO:ponuka", ua: "пропозиція", ru: "предложение", img: "/words_a2/ponuka.jpg" },
      { sk: "TODO:dopyt", ua: "попит", ru: "спрос", img: "/words_a2/dopyt.jpg" },
      { sk: "TODO:obhliadka", ua: "огляд (квартири)", ru: "осмотр (квартиры)", img: "/words_a2/obhliadka.jpg" },
      { sk: "TODO:záloha", ua: "застава/депозит", ru: "залог / депозит", img: "/words_a2/záloha.jpg" },
      { sk: "TODO:kaucia", ua: "депозит (кауція)", ru: "депозит (кауция)", img: "/words_a2/kaucia.jpg" },
      { sk: "TODO:mesačné", ua: "щомісячна оплата", ru: "ежемесячная оплата", img: "/words_a2/mesačné.jpg" },
      { sk: "TODO:energie v cene", ua: "комунальні включені", ru: "коммунальные включены", img: "/words_a2/energie v cene.jpg" },
      { sk: "TODO:zariadený", ua: "мебльований", ru: "меблированный", img: "/words_a2/zariadený.jpg" },
      { sk: "TODO:nezariadený", ua: "немебльований", ru: "немеблированный", img: "/words_a2/nezariadený.jpg" },
      { sk: "TODO:spolubývanie", ua: "спільне проживання", ru: "совместное проживание", img: "/words_a2/spolubývanie.jpg" },
    ],
  },
  {
    id: "a2-32",
    title: { ua: "Урок 32 — Робота (професійні навички)", ru: "Урок 32 — Работа (профессиональные навыки)" },
    words: [
      { sk: "TODO:schopnosť", ua: "здатність", ru: "способность", img: "/words_a2/schopnosť.jpg" },
      { sk: "TODO:zručnosť", ua: "навичка", ru: "навык", img: "/words_a2/zručnosť.jpg" },
      { sk: "TODO:skúsenosti", ua: "досвід", ru: "опыт", img: "/words_a2/skúsenosti.jpg" },
      { sk: "TODO:zodpovedný", ua: "відповідальний", ru: "ответственный", img: "/words_a2/zodpovedný.jpg" },
      { sk: "TODO:samostatný", ua: "самостійний", ru: "самостоятельный", img: "/words_a2/samostatný.jpg" },
      { sk: "TODO:presný", ua: "точний", ru: "точный", img: "/words_a2/presný.jpg" },
      { sk: "TODO:spoľahlivý", ua: "надійний", ru: "надёжный", img: "/words_a2/spoľahlivý.jpg" },
      { sk: "TODO:komunikatívny", ua: "комунікабельний", ru: "коммуникабельный", img: "/words_a2/komunikatívny.jpg" },
      { sk: "TODO:flexibilný", ua: "гнучкий", ru: "гибкий", img: "/words_a2/flexibilný.jpg" },
      { sk: "TODO:učiť sa rýchlo", ua: "швидко вчитися", ru: "быстро учиться", img: "/words_a2/učiť sa rýchlo.jpg" },
    ],
  },
  {
    id: "a2-33",
    title: { ua: "Урок 33 — Відпочинок і дозвілля", ru: "Урок 33 — Отдых и досуг" },
    words: [
      { sk: "TODO:voľný čas", ua: "вільний час", ru: "свободное время", img: "/words_a2/voľný čas.jpg" },
      { sk: "TODO:oddýchnuť si", ua: "відпочити", ru: "отдохнуть", img: "/words_a2/oddýchnuť si.jpg" },
      { sk: "TODO:zábava", ua: "розвага", ru: "развлечение", img: "/words_a2/zábava.jpg" },
      { sk: "TODO:podujatie", ua: "подія", ru: "мероприятие / событие", img: "/words_a2/podujatie.jpg" },
      { sk: "TODO:festival", ua: "фестиваль", ru: "фестиваль", img: "/words_a2/festival.jpg" },
      { sk: "TODO:vstupenka", ua: "квиток", ru: "билет", img: "/words_a2/vstupenka.jpg" },
      { sk: "TODO:predstavenie", ua: "вистава", ru: "представление / спектакль", img: "/words_a2/predstavenie.jpg" },
      { sk: "TODO:koncert", ua: "концерт", ru: "концерт", img: "/words_a2/koncert.jpg" },
      { sk: "TODO:výstava", ua: "виставка", ru: "выставка", img: "/words_a2/výstava.jpg" },
      { sk: "TODO:rezervovať miesto", ua: "забронювати місце", ru: "забронировать место", img: "/words_a2/rezervovať miesto.jpg" },
    ],
  },
  {
    id: "a2-34",
    title: { ua: "Урок 34 — Сервіс (майстерня, ремонт)", ru: "Урок 34 — Сервис (мастерская, ремонт)" },
    words: [
      { sk: "TODO:servis", ua: "сервіс", ru: "сервис", img: "/words_a2/servis.jpg" },
      { sk: "TODO:objednať termín", ua: "записатися на час", ru: "записаться на время", img: "/words_a2/objednať termín.jpg" },
      { sk: "TODO:diagnostika", ua: "діагностика", ru: "диагностика", img: "/words_a2/diagnostika.jpg" },
      { sk: "TODO:porucha", ua: "несправність", ru: "неисправность", img: "/words_a2/porucha.jpg" },
      { sk: "TODO:oprava", ua: "ремонт", ru: "ремонт", img: "/words_a2/oprava.jpg" },
      { sk: "TODO:náhradné diely", ua: "запасні частини", ru: "запасные части", img: "/words_a2/náhradné diely.jpg" },
      { sk: "TODO:cenník", ua: "прайс", ru: "прайс-лист", img: "/words_a2/cenník.jpg" },
      { sk: "TODO:odhad ceny", ua: "оцінка вартості", ru: "оценка стоимости", img: "/words_a2/odhad ceny.jpg" },
      { sk: "TODO:schváliť", ua: "схвалити / затвердити", ru: "одобрить / утвердить", img: "/words_a2/schváliť.jpg" },
      { sk: "TODO:záruka", ua: "гарантія", ru: "гарантия", img: "/words_a2/záruka.jpg" },
    ],
  },
  {
    id: "a2-35",
    title: { ua: "Урок 35 — В магазині (складніші ситуації)", ru: "Урок 35 — В магазине (более сложные ситуации)" },
    words: [
      { sk: "TODO:dostupnosť", ua: "наявність", ru: "наличие / доступность", img: "/words_a2/dostupnosť.jpg" },
      { sk: "TODO:skladom", ua: "в наявності", ru: "в наличии", img: "/words_a2/skladom.jpg" },
      { sk: "TODO:vypredané", ua: "розпродано", ru: "распродано", img: "/words_a2/vypredané.jpg" },
      { sk: "TODO:objednať", ua: "замовити", ru: "заказать", img: "/words_a2/objednať.jpg" },
      { sk: "TODO:dodanie", ua: "поставка", ru: "поставка / доставка", img: "/words_a2/dodanie.jpg" },
      { sk: "TODO:dodacia lehota", ua: "термін доставки", ru: "срок доставки", img: "/words_a2/dodacia lehota.jpg" },
      { sk: "TODO:poškodený tovar", ua: "пошкоджений товар", ru: "повреждённый товар", img: "/words_a2/poškodený tovar.jpg" },
      { sk: "TODO:vymeniť tovar", ua: "обміняти товар", ru: "обменять товар", img: "/words_a2/vymeniť tovar.jpg" },
      { sk: "TODO:vrátiť peniaze", ua: "повернути гроші", ru: "вернуть деньги", img: "/words_a2/vrátiť peniaze.jpg" },
      { sk: "TODO:reklamačné oddelenie", ua: "відділ рекламацій", ru: "отдел рекламаций", img: "/words_a2/reklamačné oddelenie.jpg" },
    ],
  },
  {
    id: "a2-36",
    title: { ua: "Урок 36 — Подорожі (готельні ситуації)", ru: "Урок 36 — Путешествия (отельные ситуации)" },
    words: [
      { sk: "TODO:recepcia", ua: "ресепшн", ru: "ресепшен", img: "/words_a2/recepcia.jpg" },
      { sk: "TODO:ubytovať sa", ua: "заселитися", ru: "заселиться", img: "/words_a2/ubytovať sa.jpg" },
      { sk: "TODO:odubytovať sa", ua: "виселитися", ru: "выселиться", img: "/words_a2/odubytovať sa.jpg" },
      { sk: "TODO:izba", ua: "номер/кімната", ru: "номер / комната", img: "/words_a2/izba.jpg" },
      { sk: "TODO:kľúč/karta", ua: "ключ/картка", ru: "ключ / карта", img: "/words_a2/kľúč-karta.jpg" },
      { sk: "TODO:raňajky v cene", ua: "сніданок включено", ru: "завтрак включён", img: "/words_a2/raňajky v cene.jpg" },
      { sk: "TODO:doplatok", ua: "доплата", ru: "доплата", img: "/words_a2/doplatok.jpg" },
      { sk: "TODO:sťažnosť", ua: "скарга", ru: "жалоба", img: "/words_a2/sťažnosť.jpg" },
      { sk: "TODO:hluk", ua: "шум", ru: "шум", img: "/words_a2/hluk.jpg" },
      { sk: "TODO:upratovanie", ua: "прибирання", ru: "уборка", img: "/words_a2/upratovanie.jpg" },
    ],
  },
  {
    id: "a2-37",
    title: { ua: "Урок 37 — Ресторан (обслуговування)", ru: "Урок 37 — Ресторан (обслуживание)" },
    words: [
      { sk: "TODO:obsluha", ua: "обслуговування", ru: "обслуживание", img: "/words_a2/obsluha.jpg" },
      { sk: "TODO:čašník/čašníčka", ua: "офіціант/офіціантка", ru: "официант/официантка", img: "/words_a2/čašník-čašníčka.jpg" },
      { sk: "TODO:odporučiť", ua: "порадити", ru: "порекомендовать / посоветовать", img: "/words_a2/odporučiť.jpg" },
      { sk: "TODO:predjedlo", ua: "закуска", ru: "закуска", img: "/words_a2/predjedlo.jpg" },
      { sk: "TODO:hlavné jedlo", ua: "основна страва", ru: "основное блюдо", img: "/words_a2/hlavné jedlo.jpg" },
      { sk: "bez masa", ua: "без мʼяса", ru: "без мяса", img: "/words_a2/bez mäsa.jpg" },
      { sk: "bez lepku", ua: "без глютену", ru: "без глютена", img: "/words_a2/bez lepku.jpg" },
      { sk: "TODO:účtovať", ua: "виставити рахунок", ru: "выставить счёт", img: "/words_a2/účtovať.jpg" },
      { sk: "TODO:prepitné", ua: "чайові", ru: "чаевые", img: "/words_a2/prepitné.jpg" },
      { sk: "TODO:pochutnať si", ua: "смачно поїсти", ru: "вкусно поесть", img: "/words_a2/pochutnať si.jpg" },
    ],
  },
  {
    id: "a2-38",
    title: { ua: "Урок 38 — Спілкування (телефон/листування)", ru: "Урок 38 — Общение (телефон/переписка)" },
    words: [
      { sk: "TODO:zavolať", ua: "подзвонити", ru: "позвонить", img: "/words_a2/zavolať.jpg" },
      { sk: "TODO:nedostupný", ua: "недоступний", ru: "недоступный", img: "/words_a2/nedostupný.jpg" },
      { sk: "TODO:zanechať správu", ua: "залишити повідомлення", ru: "оставить сообщение", img: "/words_a2/zanechať správu.jpg" },
      { sk: "TODO:ozvať sa", ua: "відписати/дати знати", ru: "отписаться / дать знать", img: "/words_a2/ozvať sa.jpg" },
      { sk: "TODO:spresniť", ua: "уточнити", ru: "уточнить", img: "/words_a2/spresniť.jpg" },
      { sk: "TODO:potvrdiť", ua: "підтвердити", ru: "подтвердить", img: "/words_a2/potvrdiť.jpg" },
      { sk: "TODO:dohodnúť termín", ua: "узгодити дату", ru: "согласовать дату", img: "/words_a2/dohodnúť termín.jpg" },
      { sk: "TODO:poslať e-mail", ua: "надіслати email", ru: "отправить e-mail", img: "/words_a2/poslať e-mail.jpg" },
      { sk: "TODO:príloha", ua: "вкладення", ru: "вложение", img: "/words_a2/príloha.jpg" },
      { sk: "TODO:predmet správy", ua: "тема повідомлення", ru: "тема сообщения", img: "/words_a2/predmet správy.jpg" },
    ],
  },
  {
    id: "a2-39",
    title: { ua: "Урок 39 — Навчання мови (корисні слова)", ru: "Урок 39 — Изучение языка (полезные слова)" },
    words: [
      { sk: "TODO:slovná zásoba", ua: "словниковий запас", ru: "словарный запас", img: "/words_a2/slovná zásoba.jpg" },
      { sk: "TODO:výslovnosť", ua: "вимова", ru: "произношение", img: "/words_a2/výslovnosť.jpg" },
      { sk: "TODO:gramatika", ua: "граматика", ru: "грамматика", img: "/words_a2/gramatika.jpg" },
      { sk: "TODO:preklad", ua: "переклад", ru: "перевод", img: "/words_a2/preklad.jpg" },
      { sk: "TODO:význam", ua: "значення", ru: "значение", img: "/words_a2/význam.jpg" },
      { sk: "TODO:príklad", ua: "приклад", ru: "пример", img: "/words_a2/príklad.jpg" },
      { sk: "TODO:cvičenie", ua: "вправа", ru: "упражнение", img: "/words_a2/cvičenie.jpg" },
      { sk: "TODO:urobiť chybu", ua: "зробити помилку", ru: "сделать ошибку", img: "/words_a2/urobiť chybu.jpg" },
      { sk: "TODO:zopakovať", ua: "повторити", ru: "повторить", img: "/words_a2/zopakovať.jpg" },
      { sk: "TODO:zlepšiť sa", ua: "покращитися", ru: "улучшиться", img: "/words_a2/zlepšiť sa.jpg" },
    ],
  },
  {
    id: "a2-40",
    title: { ua: "Урок 40 — Повторення A2 (31–39)", ru: "Урок 40 — Повторение A2 (31–39)" },
    words: [
      { sk: "TODO:kaucia", ua: "депозит", ru: "депозит (кауция)", img: "/words_a2/kaucia.jpg" },
      { sk: "TODO:spoľahlivý", ua: "надійний", ru: "надёжный", img: "/words_a2/spoľahlivý.jpg" },
      { sk: "TODO:podujatie", ua: "подія", ru: "мероприятие / событие", img: "/words_a2/podujatie.jpg" },
      { sk: "TODO:diagnostika", ua: "діагностика", ru: "диагностика", img: "/words_a2/diagnostika.jpg" },
      { sk: "TODO:dodacia lehota", ua: "термін доставки", ru: "срок доставки", img: "/words_a2/dodacia lehota.jpg" },
      { sk: "TODO:odubytovať sa", ua: "виселитися", ru: "выселиться", img: "/words_a2/odubytovať sa.jpg" },
      { sk: "TODO:prepitné", ua: "чайові", ru: "чаевые", img: "/words_a2/prepitné.jpg" },
      { sk: "TODO:príloha", ua: "вкладення", ru: "вложение", img: "/words_a2/príloha.jpg" },
      { sk: "TODO:slovná zásoba", ua: "словниковий запас", ru: "словарный запас", img: "/words_a2/slovná zásoba.jpg" },
      { sk: "TODO:spresniť", ua: "уточнити", ru: "уточнить", img: "/words_a2/spresniť.jpg" },
    ],
  },
  {
    id: "a2-41",
    title: { ua: "Урок 41 — Плани та цілі", ru: "Урок 41 — Планы и цели" },
    words: [
      { sk: "ambice", ua: "амбіція", ru: "амбиция", img: "/words_a2/ambícia.jpg" },
      { sk: "TODO:stratégia", ua: "стратегія", ru: "стратегия", img: "/words_a2/stratégia.jpg" },
      { sk: "TODO:odhodlanie", ua: "рішучість", ru: "решимость", img: "/words_a2/odhodlanie.jpg" },
      { sk: "TODO:zvážiť", ua: "зважити/розглянути", ru: "взвесить / рассмотреть", img: "/words_a2/zvážiť.jpg" },
      { sk: "TODO:prispôsobiť sa", ua: "пристосуватися", ru: "приспособиться", img: "/words_a2/prispôsobiť sa.jpg" },
      { sk: "TODO:priorita", ua: "пріоритет", ru: "приоритет", img: "/words_a2/priorita.jpg" },
      { sk: "TODO:dosiahnuť", ua: "досягти", ru: "достичь", img: "/words_a2/dosiahnuť.jpg" },
      { sk: "TODO:pokrok", ua: "прогрес", ru: "прогресс", img: "/words_a2/pokrok.jpg" },
      { sk: "TODO:vytrvať", ua: "витримати / не здатися", ru: "выдержать / не сдаться", img: "/words_a2/vytrvať.jpg" },
      { sk: "TODO:pokračovať", ua: "продовжити", ru: "продолжить", img: "/words_a2/pokračovať.jpg" },
    ],
  },
  {
    id: "a2-42",
    title: { ua: "Урок 42 — У місті (орієнтація)", ru: "Урок 42 — В городе (ориентация)" },
    words: [
      { sk: "TODO:smer", ua: "напрямок", ru: "направление", img: "/words_a2/smer.jpg" },
      { sk: "TODO:odbočiť", ua: "повернути", ru: "повернуть", img: "/words_a2/odbočiť.jpg" },
      { sk: "TODO:kruhový objazd", ua: "кільце", ru: "кольцевой перекрёсток", img: "/words_a2/kruhový objazd.jpg" },
      { sk: "TODO:prechod pre chodcov", ua: "пішохідний перехід", ru: "пешеходный переход", img: "/words_a2/prechod pre chodcov.jpg" },
      { sk: "TODO:zákaz", ua: "заборона", ru: "запрет", img: "/words_a2/zákaz.jpg" },
      { sk: "TODO:povolené", ua: "дозволено", ru: "разрешено", img: "/words_a2/povolené.jpg" },
      { sk: "TODO:obchádzka", ua: "об’їзд", ru: "объезд", img: "/words_a2/obchádzka.jpg" },
      { sk: "TODO:zablúdiť", ua: "заблукати", ru: "заблудиться", img: "/words_a2/zablúdiť.jpg" },
      { sk: "TODO:nasledovať", ua: "слідувати", ru: "следовать", img: "/words_a2/nasledovať.jpg" },
      { sk: "TODO:orientovať sa", ua: "орієнтуватися", ru: "ориентироваться", img: "/words_a2/orientovať sa.jpg" },
    ],
  },
  {
    id: "a2-43",
    title: { ua: "Урок 43 — Звички та рутина", ru: "Урок 43 — Привычки и рутина" },
    words: [
      { sk: "TODO:zvyk", ua: "звичка", ru: "привычка", img: "/words_a2/zvyk.jpg" },
      { sk: "TODO:rutina", ua: "рутина", ru: "рутина", img: "/words_a2/rutina.jpg" },
      { sk: "TODO:zvyknúť si", ua: "звикнути", ru: "привыкнуть", img: "/words_a2/zvyknúť si.jpg" },
      { sk: "TODO:odvyknúť si", ua: "відвикнути", ru: "отвыкнуть", img: "/words_a2/odvyknúť si.jpg" },
      { sk: "TODO:pravidelne", ua: "регулярно", ru: "регулярно", img: "/words_a2/pravidelne.jpg" },
      { sk: "TODO:výnimka", ua: "виняток", ru: "исключение", img: "/words_a2/výnimka.jpg" },
      { sk: "TODO:zlepšiť", ua: "покращити", ru: "улучшить", img: "/words_a2/zlepšiť.jpg" },
      { sk: "TODO:zhoršiť", ua: "погіршити", ru: "ухудшить", img: "/words_a2/zhoršiť.jpg" },
      { sk: "TODO:zdravý štýl", ua: "здоровий стиль життя", ru: "здоровый образ жизни", img: "/words_a2/zdravý štýl.jpg" },
      { sk: "TODO:disciplína", ua: "дисципліна", ru: "дисциплина", img: "/words_a2/disciplína.jpg" },
    ],
  },
  {
    id: "a2-44",
    title: { ua: "Урок 44 — Характер і поведінка", ru: "Урок 44 — Характер и поведение" },
    words: [
      { sk: "TODO:správanie", ua: "поведінка", ru: "поведение", img: "/words_a2/správanie.jpg" },
      { sk: "TODO:zdvorilý", ua: "ввічливий", ru: "вежливый", img: "/words_a2/zdvorilý.jpg" },
      { sk: "TODO:drzý", ua: "зухвалий", ru: "дерзкий", img: "/words_a2/drzý.jpg" },
      { sk: "TODO:trpezlivý", ua: "терплячий", ru: "терпеливый", img: "/words_a2/trpezlivý.jpg" },
      { sk: "TODO:netrpezlivý", ua: "нетерплячий", ru: "нетерпеливый", img: "/words_a2/netrpezlivý.jpg" },
      { sk: "TODO:ochotný", ua: "готовий допомогти", ru: "готовый помочь", img: "/words_a2/ochotný.jpg" },
      { sk: "TODO:tvrdohlavý", ua: "впертий", ru: "упрямый", img: "/words_a2/tvrdohlavý.jpg" },
      { sk: "TODO:priateľský", ua: "дружній", ru: "дружелюбный", img: "/words_a2/priateľský.jpg" },
      { sk: "TODO:zodpovedný", ua: "відповідальний", ru: "ответственный", img: "/words_a2/zodpovedný.jpg" },
      { sk: "TODO:lenivý", ua: "ледачий", ru: "ленивый", img: "/words_a2/lenivý.jpg" },
    ],
  },
  {
    id: "a2-45",
    title: { ua: "Урок 45 — Проблеми та рішення", ru: "Урок 45 — Проблемы и решения" },
    words: [
      { sk: "TODO:situácia", ua: "ситуація", ru: "ситуация", img: "/words_a2/situácia.jpg" },
      { sk: "TODO:problém", ua: "проблема", ru: "проблема", img: "/words_a2/problém.jpg" },
      { sk: "TODO:riešenie", ua: "рішення", ru: "решение", img: "/words_a2/riešenie.jpg" },
      { sk: "TODO:možnosť", ua: "варіант", ru: "вариант", img: "/words_a2/možnosť.jpg" },
      { sk: "TODO:riziko", ua: "ризик", ru: "риск", img: "/words_a2/riziko.jpg" },
      { sk: "TODO:dôsledok", ua: "наслідок", ru: "последствие", img: "/words_a2/dôsledok.jpg" },
      { sk: "TODO:výsledok", ua: "результат", ru: "результат", img: "/words_a2/výsledok.jpg" },
      { sk: "TODO:zvládnuť", ua: "впоратися", ru: "справиться", img: "/words_a2/zvládnuť.jpg" },
      { sk: "TODO:poradiť si", ua: "дати собі раду", ru: "справиться / найти выход", img: "/words_a2/poradiť si.jpg" },
      { sk: "TODO:pokus", ua: "спроба", ru: "попытка", img: "/words_a2/pokus.jpg" },
    ],
  },
  {
    id: "a2-46",
    title: { ua: "Урок 46 — Думки та рішення", ru: "Урок 46 — Мысли и решения" },
    words: [
      { sk: "TODO:rozhodnutie", ua: "рішення", ru: "решение", img: "/words_a2/rozhodnutie.jpg" },
      { sk: "TODO:zvoliť", ua: "обрати", ru: "выбрать", img: "/words_a2/zvoliť.jpg" },
      { sk: "TODO:zmeniť názor", ua: "змінити думку", ru: "изменить мнение", img: "/words_a2/zmeniť názor.jpg" },
      { sk: "TODO:pochybovať", ua: "сумніватися", ru: "сомневаться", img: "/words_a2/pochybovať.jpg" },
      { sk: "TODO:istota", ua: "впевненість", ru: "уверенность", img: "/words_a2/istota.jpg" },
      { sk: "TODO:neistota", ua: "невпевненість", ru: "неуверенность", img: "/words_a2/neistota.jpg" },
      { sk: "TODO:uvedomiť si", ua: "усвідомити", ru: "осознать", img: "/words_a2/uvedomiť si.jpg" },
      { sk: "TODO:predpokladať", ua: "припускати", ru: "предполагать", img: "/words_a2/predpokladať.jpg" },
      { sk: "TODO:zistiť", ua: "з’ясувати", ru: "выяснить", img: "/words_a2/zistiť.jpg" },
      { sk: "TODO:záver", ua: "висновок", ru: "вывод", img: "/words_a2/záver.jpg" },
    ],
  },
  {
    id: "a2-47",
    title: { ua: "Урок 47 — Культура та медіа", ru: "Урок 47 — Культура и медиа" },
    words: [
      { sk: "TODO:kultúra", ua: "культура", ru: "культура", img: "/words_a2/kultúra.jpg" },
      { sk: "TODO:tradícia", ua: "традиція", ru: "традиция", img: "/words_a2/tradícia.jpg" },
      { sk: "TODO:zvyk", ua: "звичай", ru: "обычай", img: "/words_a2/zvyk.jpg" },
      { sk: "TODO:správy", ua: "новини", ru: "новости", img: "/words_a2/správy.jpg" },
      { sk: "TODO:článok", ua: "стаття", ru: "статья", img: "/words_a2/článok.jpg" },
      { sk: "TODO:diskusia", ua: "обговорення", ru: "обсуждение", img: "/words_a2/diskusia.jpg" },
      { sk: "TODO:názor", ua: "думка", ru: "мнение", img: "/words_a2/názor.jpg" },
      { sk: "TODO:reklama", ua: "реклама", ru: "реклама", img: "/words_a2/reklama.jpg" },
      { sk: "TODO:vplyv", ua: "вплив", ru: "влияние", img: "/words_a2/vplyv.jpg" },
      { sk: "TODO:zdroj", ua: "джерело", ru: "источник", img: "/words_a2/zdroj.jpg" },
    ],
  },
  {
    id: "a2-48",
    title: { ua: "Урок 48 — Природа та подорожі (активності)", ru: "Урок 48 — Природа и путешествия (активности)" },
    words: [
      { sk: "TODO:turistika", ua: "похід/туризм", ru: "поход / туризм", img: "/words_a2/turistika.jpg" },
      { sk: "TODO:trasa", ua: "маршрут", ru: "маршрут", img: "/words_a2/trasa.jpg" },
      { sk: "TODO:výstup", ua: "підйом", ru: "подъём", img: "/words_a2/výstup.jpg" },
      { sk: "TODO:zostup", ua: "спуск", ru: "спуск", img: "/words_a2/zostup.jpg" },
      { sk: "TODO:výhľad", ua: "краєвид", ru: "вид / панорама", img: "/words_a2/výhľad.jpg" },
      { sk: "TODO:príroda", ua: "природа", ru: "природа", img: "/words_a2/príroda.jpg" },
      { sk: "TODO:chránená oblasť", ua: "заповідна зона", ru: "заповедная зона / охраняемая территория", img: "/words_a2/chránená oblasť.jpg" },
      { sk: "TODO:tábor", ua: "табір", ru: "лагерь", img: "/words_a2/tábor.jpg" },
      { sk: "TODO:výbava", ua: "спорядження", ru: "снаряжение", img: "/words_a2/výbava.jpg" },
      { sk: "bezpečnost", ua: "безпека", ru: "безопасность", img: "/words_a2/bezpečnosť.jpg" },
    ],
  },
  {
    id: "a2-49",
    title: { ua: "Урок 49 — Погода (умови та поради)", ru: "Урок 49 — Погода (условия и советы)" },
    words: [
      { sk: "TODO:výstraha", ua: "попередження", ru: "предупреждение", img: "/words_a2/výstraha.jpg" },
      { sk: "TODO:silný vietor", ua: "сильний вітер", ru: "сильный ветер", img: "/words_a2/silný vietor.jpg" },
      { sk: "TODO:hmla", ua: "туман", ru: "туман", img: "/words_a2/hmla.jpg" },
      { sk: "TODO:poľadovica", ua: "ожеледиця", ru: "гололёд", img: "/words_a2/poľadovica.jpg" },
      { sk: "TODO:zrážky", ua: "опади", ru: "осадки", img: "/words_a2/zrážky.jpg" },
      { sk: "TODO:vlna horúčav", ua: "хвиля спеки", ru: "волна жары", img: "/words_a2/vlna horúčav.jpg" },
      { sk: "TODO:ochladenie", ua: "похолодання", ru: "похолодание", img: "/words_a2/ochladenie.jpg" },
      { sk: "TODO:odporúčanie", ua: "порада/рекомендація", ru: "совет / рекомендация", img: "/words_a2/odporúčanie.jpg" },
      { sk: "TODO:zobrať si dáždnik", ua: "взяти парасолю", ru: "взять зонт", img: "/words_a2/zobrať si dáždnik.jpg" },
      { sk: "TODO:teplo sa obliecť", ua: "тепло одягтися", ru: "тепло одеться", img: "/words_a2/teplo sa obliecť.jpg" },
    ],
  },
  {
    id: "a2-50",
    title: { ua: "Урок 50 — Повторення A2 (41–49)", ru: "Урок 50 — Повторение A2 (41–49)" },
    words: [
      { sk: "TODO:dosiahnuť", ua: "досягти", ru: "достичь", img: "/words_a2/dosiahnuť.jpg" },
      { sk: "TODO:obchádzka", ua: "об’їзд", ru: "объезд", img: "/words_a2/obchádzka.jpg" },
      { sk: "TODO:disciplína", ua: "дисципліна", ru: "дисциплина", img: "/words_a2/disciplína.jpg" },
      { sk: "TODO:tvrdohlavý", ua: "впертий", ru: "упрямый", img: "/words_a2/tvrdohlavý.jpg" },
      { sk: "TODO:poradiť si", ua: "дати собі раду", ru: "справиться / найти выход", img: "/words_a2/poradiť si.jpg" },
      { sk: "TODO:pochybovať", ua: "сумніватися", ru: "сомневаться", img: "/words_a2/pochybovať.jpg" },
      { sk: "TODO:zdroj", ua: "джерело", ru: "источник", img: "/words_a2/zdroj.jpg" },
      { sk: "TODO:výbava", ua: "спорядження", ru: "снаряжение", img: "/words_a2/výbava.jpg" },
      { sk: "TODO:výstraha", ua: "попередження", ru: "предупреждение", img: "/words_a2/výstraha.jpg" },
      { sk: "TODO:orientovať sa", ua: "орієнтуватися", ru: "ориентироваться", img: "/words_a2/orientovať sa.jpg" },
    ],
  },
];
