import type { Lesson } from "../data";

export const CS_A1_SOURCE: Lesson[] = [
  {
    id: "a1-1",
    title: { ua: "Урок 1 — Знайомство", ru: "Урок 1 — Знакомство" },
    words: [
      { sk: "TODO:volať sa", ua: "називатися", ru: "называться", img: "/words_a1/volať sa.jpg" },
      { sk: "TODO:zoznámiť sa", ua: "познайомитися", ru: "познакомиться", img: "/words_a1/zoznámiť sa.jpg" },
      { sk: "TODO:meno", ua: "ім’я", ru: "имя", img: "/words_a1/meno.jpg" },
      { sk: "TODO:priezvisko", ua: "прізвище", ru: "фамилия", img: "/words_a1/priezvisko.jpg" },
      { sk: "TODO:odkiaľ", ua: "звідки", ru: "откуда", img: "/words_a1/odkiaľ.jpg" },
      { sk: "TODO:bývať", ua: "жити (мешкати)", ru: "жить (проживать)", img: "/words_a1/bývať.jpg" },
      { sk: "TODO:pracovať", ua: "працювати", ru: "работать", img: "/words_a1/pracovať.jpg" },
      { sk: "TODO:teší ma", ua: "приємно познайомитись", ru: "приятно познакомиться", img: "/words_a1/teší ma.jpg" },
      { sk: "TODO:mať rád", ua: "подобатися", ru: "нравиться", img: "/words_a1/mať rád.jpg" },
      { sk: "TODO:ďakujem", ua: "дякую", ru: "спасибо", img: "/words_a1/ďakujem.jpg" },
    ],
  },
  {
    id: "a1-2",
    title: { ua: "Урок 2 — Ввічливі фрази", ru: "Урок 2 — Вежливые фразы" },
    words: [
      { sk: "TODO:prosím", ua: "будь ласка", ru: "пожалуйста", img: "/words_a1/prosím.jpg" },
      { sk: "TODO:prepáčte", ua: "вибачте", ru: "извините", img: "/words_a1/prepáčte.jpg" },
      { sk: "TODO:ďakujem pekne", ua: "дуже дякую", ru: "большое спасибо", img: "/words_a1/ďakujem pekne.jpg" },
      { sk: "TODO:niet za čo", ua: "нема за що", ru: "не за что", img: "/words_a1/niet za čo.jpg" },
      { sk: "TODO:môžem", ua: "можна", ru: "можно", img: "/words_a1/môžem.jpg" },
      { sk: "TODO:môžete", ua: "можете", ru: "можете", img: "/words_a1/môžete.jpg" },
      { sk: "TODO:pomôžte mi", ua: "допоможіть мені", ru: "помогите мне", img: "/words_a1/pomôžte mi.jpg" },
      { sk: "TODO:nech sa páči", ua: "прошу / будь ласка (даючи щось)", ru: "пожалуйста (вот, когда даёте что-то)", img: "/words_a1/nech sa páči.jpg" },
      { sk: "TODO:v poriadku", ua: "в порядку", ru: "в порядке", img: "/words_a1/v poriadku.jpg" },
      { sk: "TODO:jasné", ua: "ясно", ru: "ясно", img: "/words_a1/jasné.jpg" },
    ],
  },
  {
    id: "a1-3",
    title: { ua: "Урок 3 — Місто", ru: "Урок 3 — Город" },
    words: [
      { sk: "TODO:križovatka", ua: "перехрестя", ru: "перекрёсток", img: "/words_a1/križovatka.jpg" },
      { sk: "TODO:semafor", ua: "світлофор", ru: "светофор", img: "/words_a1/semafor.jpg" },
      { sk: "TODO:most", ua: "міст", ru: "мост", img: "/words_a1/most.jpg" },
      { sk: "TODO:kino", ua: "кінотеатр", ru: "кинотеатр", img: "/words_a1/kino.jpg" },
      { sk: "TODO:múzeum", ua: "музей", ru: "музей", img: "/words_a1/múzeum.jpg" },
      { sk: "TODO:lekáreň", ua: "аптека", ru: "аптека", img: "/words_a1/lekáreň.jpg" },
      { sk: "TODO:knižnica", ua: "бібліотека", ru: "библиотека", img: "/words_a1/knižnica.jpg" },
      { sk: "TODO:trh", ua: "ринок", ru: "рынок", img: "/words_a1/trh.jpg" },
      { sk: "TODO:vstup", ua: "вхід", ru: "вход", img: "/words_a1/vstup.jpg" },
      { sk: "TODO:východ", ua: "вихід", ru: "выход", img: "/words_a1/východ.jpg" },
    ],
  },
  {
    id: "a1-4",
    title: { ua: "Урок 4 — Магазин (розширено)", ru: "Урок 4 — Магазин (расширено)" },
    words: [
      { sk: "TODO:pokladník", ua: "касир", ru: "кассир", img: "/words_a1/pokladník.jpg" },
      { sk: "TODO:regál", ua: "стелаж/полиця", ru: "стеллаж/полка", img: "/words_a1/regál.jpg" },
      { sk: "TODO:oddelenie", ua: "відділ", ru: "отдел", img: "/words_a1/oddelenie.jpg" },
      { sk: "TODO:veľkosť", ua: "розмір", ru: "размер", img: "/words_a1/veľkosť.jpg" },
      { sk: "TODO:skúsiť", ua: "приміряти/спробувати", ru: "примерить/попробовать", img: "/words_a1/skúsiť.jpg" },
      { sk: "TODO:vymeniť", ua: "обміняти", ru: "обменять", img: "/words_a1/vymeniť.jpg" },
      { sk: "TODO:vrátiť", ua: "повернути (товар)", ru: "вернуть (товар)", img: "/words_a1/vrátiť.jpg" },
      { sk: "TODO:záruka", ua: "гарантія", ru: "гарантия", img: "/words_a1/záruka.jpg" },
      { sk: "balení", ua: "упаковка", ru: "упаковка", img: "/words_a1/balenie.jpg" },
      { sk: "TODO:účtovať", ua: "рахувати (на касі)", ru: "пробивать (на кассе) / считать", img: "/words_a1/účtovať.jpg" },
    ],
  },
  {
    id: "a1-5",
    title: { ua: "Урок 5 — Їжа (у ресторані)", ru: "Урок 5 — Еда (в ресторане)" },
    words: [
      { sk: "TODO:objednať", ua: "замовити", ru: "заказать", img: "/words_a1/objednať.jpg" },
      { sk: "TODO:porcia", ua: "порція", ru: "порция", img: "/words_a1/porcia.jpg" },
      { sk: "TODO:príloha", ua: "гарнір", ru: "гарнир", img: "/words_a1/príloha.jpg" },
      { sk: "TODO:dezert", ua: "десерт", ru: "десерт", img: "/words_a1/dezert.jpg" },
      { sk: "TODO:chutný", ua: "смачний", ru: "вкусный", img: "/words_a1/chutný.jpg" },
      { sk: "TODO:hladný", ua: "голодний", ru: "голодный", img: "/words_a1/hladný.jpg" },
      { sk: "TODO:smädný", ua: "спраглий", ru: "хотящий пить / испытывающий жажду", img: "/words_a1/smädný.jpg" },
      { sk: "TODO:účtovať", ua: "виставити рахунок", ru: "выставить счёт", img: "/words_a1/účtovať.jpg" },
      { sk: "TODO:zaplatiť", ua: "заплатити", ru: "заплатить", img: "/words_a1/zaplatiť.jpg" },
      { sk: "TODO:rezervácia", ua: "бронювання", ru: "бронирование", img: "/words_a1/rezervácia.jpg" },
    ],
  },
  {
    id: "a1-6",
    title: { ua: "Урок 6 — Транспорт", ru: "Урок 6 — Транспорт" },
    words: [
      { sk: "TODO:cestovný poriadok", ua: "розклад", ru: "расписание", img: "/words_a1/cestovný poriadok.jpg" },
      { sk: "TODO:prestup", ua: "пересадка", ru: "пересадка", img: "/words_a1/prestup.jpg" },
      { sk: "TODO:nástupište", ua: "платформа", ru: "платформа", img: "/words_a1/nástupište.jpg" },
      { sk: "TODO:meškať", ua: "запізнюватися", ru: "опаздывать", img: "/words_a1/meškať.jpg" },
      { sk: "TODO:odchod", ua: "відправлення", ru: "отправление", img: "/words_a1/odchod.jpg" },
      { sk: "TODO:príchod", ua: "прибуття", ru: "прибытие", img: "/words_a1/príchod.jpg" },
      { sk: "TODO:lístok", ua: "квиток", ru: "билет", img: "/words_a1/lístok.jpg" },
      { sk: "TODO:kúpiť", ua: "купити", ru: "купить", img: "/words_a1/kúpiť.jpg" },
      { sk: "TODO:vystúpiť", ua: "вийти (з транспорту)", ru: "выйти (из транспорта)", img: "/words_a1/vystúpiť.jpg" },
      { sk: "TODO:nastúpiť", ua: "сісти (в транспорт)", ru: "сесть (в транспорт) / войти", img: "/words_a1/nastúpiť.jpg" },
    ],
  },
  {
    id: "a1-7",
    title: { ua: "Урок 7 — Дім (побутові дії)", ru: "Урок 7 — Дом (бытовые действия)" },
    words: [
      { sk: "TODO:variť", ua: "готувати", ru: "готовить", img: "/words_a1/variť.jpg" },
      { sk: "TODO:upratovať", ua: "прибирати", ru: "убирать / прибираться", img: "/words_a1/upratovať.jpg" },
      { sk: "TODO:umývať", ua: "мити", ru: "мыть", img: "/words_a1/umývať.jpg" },
      { sk: "TODO:prať", ua: "прати", ru: "стирать", img: "/words_a1/prať.jpg" },
      { sk: "TODO:žehliť", ua: "прасувати", ru: "гладить", img: "/words_a1/žehliť.jpg" },
      { sk: "TODO:otvoriť", ua: "відкрити", ru: "открыть", img: "/words_a1/otvoriť.jpg" },
      { sk: "TODO:zatvoriť", ua: "закрити", ru: "закрыть", img: "/words_a1/zatvoriť.jpg" },
      { sk: "TODO:zapnúť", ua: "увімкнути", ru: "включить", img: "/words_a1/zapnúť.jpg" },
      { sk: "TODO:vypnúť", ua: "вимкнути", ru: "выключить", img: "/words_a1/vypnúť.jpg" },
      { sk: "TODO:hľadať", ua: "шукати", ru: "искать", img: "/words_a1/hľadať.jpg" },
    ],
  },
  {
    id: "a1-8",
    title: { ua: "Урок 8 — Робота (процеси)", ru: "Урок 8 — Работа (процессы)" },
    words: [
      { sk: "TODO:pracovisko", ua: "робоче місце", ru: "рабочее место", img: "/words_a1/pracovisko.jpg" },
      { sk: "TODO:zmena", ua: "зміна", ru: "смена", img: "/words_a1/zmena.jpg" },
      { sk: "TODO:nadčas", ua: "надурочно", ru: "сверхурочно", img: "/words_a1/nadčas.jpg" },
      { sk: "TODO:porada", ua: "нарада", ru: "совещание", img: "/words_a1/porada.jpg" },
      { sk: "TODO:úloha", ua: "завдання", ru: "задание", img: "/words_a1/úloha.jpg" },
      { sk: "TODO:hotovo", ua: "готово", ru: "готово", img: "/words_a1/hotovo.jpg" },
      { sk: "TODO:skontrolovať", ua: "перевірити", ru: "проверить", img: "/words_a1/skontrolovať.jpg" },
      { sk: "TODO:opraviť", ua: "відремонтувати/виправити", ru: "отремонтировать/исправить", img: "/words_a1/opraviť.jpg" },
      { sk: "TODO:začať", ua: "почати", ru: "начать", img: "/words_a1/začať.jpg" },
      { sk: "TODO:skončiť", ua: "закінчити", ru: "закончить", img: "/words_a1/skončiť.jpg" },
    ],
  },
  {
    id: "a1-9",
    title: { ua: "Урок 9 — Емоції і стани", ru: "Урок 9 — Эмоции и состояния" },
    words: [
      { sk: "TODO:unavený", ua: "втомлений", ru: "уставший", img: "/words_a1/unavený.jpg" },
      { sk: "TODO:šťastný", ua: "щасливий", ru: "счастливый", img: "/words_a1/šťastný.jpg" },
      { sk: "TODO:smutný", ua: "сумний", ru: "грустный", img: "/words_a1/smutný.jpg" },
      { sk: "TODO:nahnevaný", ua: "злий", ru: "злой / сердитый", img: "/words_a1/nahnevaný.jpg" },
      { sk: "TODO:nervózny", ua: "нервовий", ru: "нервный", img: "/words_a1/nervózny.jpg" },
      { sk: "TODO:pokojný", ua: "спокійний", ru: "спокойный", img: "/words_a1/pokojný.jpg" },
      { sk: "TODO:prekvapený", ua: "здивований", ru: "удивлённый", img: "/words_a1/prekvapený.jpg" },
      { sk: "bát se", ua: "боятися", ru: "бояться", img: "/words_a1/báť sa.jpg" },
      { sk: "TODO:tešiť sa", ua: "радіти/чекати з радістю", ru: "радоваться / ждать с радостью", img: "/words_a1/tešiť sa.jpg" },
      { sk: "TODO:mať chuť", ua: "мати бажання", ru: "хотеть / иметь желание", img: "/words_a1/mať chuť.jpg" },
    ],
  },
  {
    id: "a1-10",
    title: { ua: "Урок 10 — Запитання", ru: "Урок 10 — Вопросы" },
    words: [
      { sk: "TODO:ktorý", ua: "який (котрий)", ru: "который", img: "/words_a1/ktorý.jpg" },
      { sk: "jaký", ua: "який (якої якості)", ru: "какой (какого качества)", img: "/words_a1/aký.jpg" },
      { sk: "TODO:čí", ua: "чий", ru: "чей", img: "/words_a1/čí.jpg" },
      { sk: "TODO:kde je", ua: "де є...?", ru: "где...?", img: "/words_a1/kde je....jpg" },
      { sk: "TODO:koľko to stojí", ua: "скільки це коштує?", ru: "сколько это стоит?", img: "/words_a1/koľko to stojí.jpg" },
      { sk: "TODO:môžete zopakovať", ua: "можете повторити?", ru: "можете повторить?", img: "/words_a1/môžete zopakovať.jpg" },
      { sk: "TODO:čo to znamená", ua: "що це означає?", ru: "что это значит?", img: "/words_a1/čo to znamená.jpg" },
      { sk: "TODO:rozumiete", ua: "розумієте?", ru: "понимаете?", img: "/words_a1/rozumiete.jpg" },
      { sk: "TODO:samozrejme", ua: "звісно", ru: "конечно", img: "/words_a1/samozrejme.jpg" },
      { sk: "TODO:neviem", ua: "не знаю", ru: "не знаю", img: "/words_a1/neviem.jpg" },
    ],
  },
  {
    id: "a1-11",
    title: { ua: "Урок 11 — Опис людини", ru: "Урок 11 — Описание человека" },
    words: [
      { sk: "TODO:vysoký", ua: "високий", ru: "высокий", img: "/words_a1/vysoký.jpg" },
      { sk: "TODO:nízky", ua: "низький", ru: "низкий", img: "/words_a1/nízky.jpg" },
      { sk: "TODO:mladý", ua: "молодий", ru: "молодой", img: "/words_a1/mladý.jpg" },
      { sk: "TODO:starý", ua: "старий", ru: "старый", img: "/words_a1/starý.jpg" },
      { sk: "TODO:silný", ua: "сильний", ru: "сильный", img: "/words_a1/silný.jpg" },
      { sk: "TODO:slabý", ua: "слабкий", ru: "слабый", img: "/words_a1/slabý.jpg" },
      { sk: "TODO:pekný", ua: "гарний", ru: "красивый", img: "/words_a1/pekný.jpg" },
      { sk: "TODO:škaredý", ua: "негарний", ru: "некрасивый / уродливый", img: "/words_a1/škaredý.jpg" },
      { sk: "TODO:milý", ua: "милий", ru: "милый", img: "/words_a1/milý.jpg" },
      { sk: "TODO:vážny", ua: "серйозний", ru: "серьёзный", img: "/words_a1/vážny.jpg" },
    ],
  },
  {
    id: "a1-12",
    title: { ua: "Урок 12 — Час", ru: "Урок 12 — Время" },
    words: [
      { sk: "TODO:ráno", ua: "ранок", ru: "утро", img: "/words_a1/ráno.jpg" },
      { sk: "TODO:obed", ua: "обід", ru: "обед", img: "/words_a1/obed.jpg" },
      { sk: "TODO:večer", ua: "вечір", ru: "вечер", img: "/words_a1/večer.jpg" },
      { sk: "TODO:polnoc", ua: "північ", ru: "полночь", img: "/words_a1/polnoc.jpg" },
      { sk: "TODO:dnes", ua: "сьогодні", ru: "сегодня", img: "/words_a1/dnes.jpg" },
      { sk: "TODO:zajtra", ua: "завтра", ru: "завтра", img: "/words_a1/zajtra.jpg" },
      { sk: "TODO:pozajtra", ua: "післязавтра", ru: "послезавтра", img: "/words_a1/pozajtra.jpg" },
      { sk: "TODO:vždy", ua: "завжди", ru: "всегда", img: "/words_a1/vždy.jpg" },
      { sk: "TODO:často", ua: "часто", ru: "часто", img: "/words_a1/často.jpg" },
      { sk: "TODO:niekedy", ua: "інколи", ru: "иногда", img: "/words_a1/niekedy.jpg" },
    ],
  },
  {
    id: "a1-13",
    title: { ua: "Урок 13 — Дім", ru: "Урок 13 — Дом" },
    words: [
      { sk: "TODO:chodba", ua: "коридор", ru: "коридор", img: "/words_a1/chodba.jpg" },
      { sk: "balkon", ua: "балкон", ru: "балкон", img: "/words_a1/balkón.jpg" },
      { sk: "TODO:pivnica", ua: "підвал", ru: "подвал", img: "/words_a1/pivnica.jpg" },
      { sk: "TODO:výťah", ua: "ліфт", ru: "лифт", img: "/words_a1/výťah.jpg" },
      { sk: "TODO:schody", ua: "сходи", ru: "лестница / ступени", img: "/words_a1/schody.jpg" },
      { sk: "TODO:záhrada", ua: "сад", ru: "сад", img: "/words_a1/záhrada.jpg" },
      { sk: "TODO:garáž", ua: "гараж", ru: "гараж", img: "/words_a1/garáž.jpg" },
      { sk: "TODO:stena", ua: "стіна", ru: "стена", img: "/words_a1/stena.jpg" },
      { sk: "TODO:strop", ua: "стеля", ru: "потолок", img: "/words_a1/strop.jpg" },
      { sk: "TODO:podlaha", ua: "підлога", ru: "пол", img: "/words_a1/podlaha.jpg" },
    ],
  },
  {
    id: "a1-14",
    title: { ua: "Урок 14 — Покупки", ru: "Урок 14 — Покупки" },
    words: [
      { sk: "TODO:predávať", ua: "продавати", ru: "продавать", img: "/words_a1/predávať.jpg" },
      { sk: "TODO:kupovať", ua: "купувати", ru: "покупать", img: "/words_a1/kupovať.jpg" },
      { sk: "TODO:lacný", ua: "дешевий", ru: "дешёвый", img: "/words_a1/lacný.jpg" },
      { sk: "TODO:drahý", ua: "дорогий", ru: "дорогой", img: "/words_a1/drahý.jpg" },
      { sk: "TODO:kvalita", ua: "якість", ru: "качество", img: "/words_a1/kvalita.jpg" },
      { sk: "TODO:značka", ua: "бренд", ru: "бренд / марка", img: "/words_a1/značka.jpg" },
      { sk: "akce", ua: "акція", ru: "акция", img: "/words_a1/akcia.jpg" },
      { sk: "TODO:zľavnený", ua: "зі знижкою", ru: "со скидкой", img: "/words_a1/zľavnený.jpg" },
      { sk: "TODO:pokladňa", ua: "каса", ru: "касса", img: "/words_a1/pokladňa.jpg" },
      { sk: "účtenka", ua: "чек", ru: "чек", img: "/words_a1/blok.jpg" },
    ],
  },
  {
    id: "a1-15",
    title: { ua: "Урок 15 — Подорожі", ru: "Урок 15 — Путешествия" },
    words: [
      { sk: "TODO:hotel", ua: "готель", ru: "отель", img: "/words_a1/hotel.jpg" },
      { sk: "TODO:ubytovanie", ua: "проживання", ru: "проживание", img: "/words_a1/ubytovanie.jpg" },
      { sk: "TODO:turista", ua: "турист", ru: "турист", img: "/words_a1/turista.jpg" },
      { sk: "TODO:sprievodca", ua: "гід", ru: "гид", img: "/words_a1/sprievodca.jpg" },
      { sk: "TODO:výlet", ua: "екскурсія", ru: "экскурсия", img: "/words_a1/výlet.jpg" },
      { sk: "TODO:pláž", ua: "пляж", ru: "пляж", img: "/words_a1/pláž.jpg" },
      { sk: "TODO:hory", ua: "гори", ru: "горы", img: "/words_a1/hory.jpg" },
      { sk: "TODO:more", ua: "море", ru: "море", img: "/words_a1/more.jpg" },
      { sk: "TODO:rezervovať", ua: "бронювати", ru: "бронировать", img: "/words_a1/rezervovať.jpg" },
      { sk: "TODO:dovolenka", ua: "відпустка", ru: "отпуск", img: "/words_a1/dovolenka.jpg" },
    ],
  },
  {
    id: "a1-16",
    title: { ua: "Урок 16 — Здоровʼя", ru: "Урок 16 — Здоровье" },
    words: [
      { sk: "bolet", ua: "боліти", ru: "болеть", img: "/words_a1/bolieť.jpg" },
      { sk: "TODO:hlava", ua: "голова", ru: "голова", img: "/words_a1/hlava.jpg" },
      { sk: "TODO:zub", ua: "зуб", ru: "зуб", img: "/words_a1/zub.jpg" },
      { sk: "TODO:žalúdok", ua: "шлунок", ru: "желудок", img: "/words_a1/žalúdok.jpg" },
      { sk: "TODO:tabletka", ua: "таблетка", ru: "таблетка", img: "/words_a1/tabletka.jpg" },
      { sk: "TODO:sirup", ua: "сироп", ru: "сироп", img: "/words_a1/sirup.jpg" },
      { sk: "TODO:odpočívať", ua: "відпочивати", ru: "отдыхать", img: "/words_a1/odpočívať.jpg" },
      { sk: "TODO:zdravý", ua: "здоровий", ru: "здоровый", img: "/words_a1/zdravý.jpg" },
      { sk: "TODO:chorý", ua: "хворий", ru: "больной", img: "/words_a1/chorý.jpg" },
      { sk: "TODO:liečiť", ua: "лікувати", ru: "лечить", img: "/words_a1/liečiť.jpg" },
    ],
  },
  {
    id: "a1-17",
    title: { ua: "Урок 17 — Робота (словник)", ru: "Урок 17 — Работа (словарь)" },
    words: [
      { sk: "TODO:zamestnanec", ua: "працівник", ru: "работник / сотрудник", img: "/words_a1/zamestnanec.jpg" },
      { sk: "TODO:zamestnávateľ", ua: "роботодавець", ru: "работодатель", img: "/words_a1/zamestnávateľ.jpg" },
      { sk: "TODO:plat", ua: "зарплата", ru: "зарплата", img: "/words_a1/plat.jpg" },
      { sk: "TODO:pracovná zmluva", ua: "трудовий договір", ru: "трудовой договор", img: "/words_a1/pracovná zmluva.jpg" },
      { sk: "TODO:prax", ua: "досвід роботи", ru: "опыт работы", img: "/words_a1/prax.jpg" },
      { sk: "TODO:kariéra", ua: "карʼєра", ru: "карьера", img: "/words_a1/kariéra.jpg" },
      { sk: "TODO:povýšenie", ua: "підвищення", ru: "повышение", img: "/words_a1/povýšenie.jpg" },
      { sk: "TODO:výpoveď", ua: "звільнення", ru: "увольнение / заявление об увольнении", img: "/words_a1/výpoveď.jpg" },
      { sk: "TODO:povinnosť", ua: "обовʼязок", ru: "обязанность", img: "/words_a1/povinnosť.jpg" },
      { sk: "TODO:právo", ua: "право", ru: "право", img: "/words_a1/právo.jpg" },
    ],
  },
  {
    id: "a1-18",
    title: { ua: "Урок 18 — Спілкування", ru: "Урок 18 — Общение" },
    words: [
      { sk: "TODO:rozumieť", ua: "розуміти", ru: "понимать", img: "/words_a1/rozumieť.jpg" },
      { sk: "TODO:vysvetliť", ua: "пояснити", ru: "объяснить", img: "/words_a1/vysvetliť.jpg" },
      { sk: "TODO:opýtať sa", ua: "запитати", ru: "спросить", img: "/words_a1/opýtať sa.jpg" },
      { sk: "TODO:odpoveď", ua: "відповідь", ru: "ответ", img: "/words_a1/odpoveď.jpg" },
      { sk: "TODO:názor", ua: "думка", ru: "мнение", img: "/words_a1/názor.jpg" },
      { sk: "TODO:súhlasiť", ua: "погоджуватися", ru: "соглашаться", img: "/words_a1/súhlasiť.jpg" },
      { sk: "TODO:nesúhlasiť", ua: "не погоджуватися", ru: "не соглашаться", img: "/words_a1/nesúhlasiť.jpg" },
      { sk: "TODO:diskutovať", ua: "обговорювати", ru: "обсуждать", img: "/words_a1/diskutovať.jpg" },
      { sk: "TODO:hovor", ua: "розмова", ru: "разговор", img: "/words_a1/hovor.jpg" },
      { sk: "TODO:kontakt", ua: "контакт", ru: "контакт", img: "/words_a1/kontakt.jpg" },
    ],
  },
  {
    id: "a1-19",
    title: { ua: "Урок 19 — Технології", ru: "Урок 19 — Технологии" },
    words: [
      { sk: "TODO:mobil", ua: "мобільний телефон", ru: "мобильный телефон", img: "/words_a1/mobil.jpg" },
      { sk: "TODO:nabíjačka", ua: "зарядка", ru: "зарядка / зарядное устройство", img: "/words_a1/nabíjačka.jpg" },
      { sk: "TODO:správa", ua: "повідомлення", ru: "сообщение", img: "/words_a1/správa.jpg" },
      { sk: "TODO:hovor", ua: "дзвінок", ru: "звонок", img: "/words_a1/hovor1.jpg" },
      { sk: "TODO:internet", ua: "інтернет", ru: "интернет", img: "/words_a1/internet.jpg" },
      { sk: "TODO:wifi", ua: "вайфай", ru: "вай-фай", img: "/words_a1/wifi.jpg" },
      { sk: "TODO:sociálne siete", ua: "соціальні мережі", ru: "социальные сети", img: "/words_a1/sociálne siete.jpg" },
      { sk: "TODO:profil", ua: "профіль", ru: "профиль", img: "/words_a1/profil.jpg" },
      { sk: "TODO:heslo", ua: "пароль", ru: "пароль", img: "/words_a1/heslo.jpg" },
      { sk: "TODO:stiahnuť", ua: "завантажити", ru: "скачать / загрузить", img: "/words_a1/stiahnuť.jpg" },
    ],
  },
  {
    id: "a1-20",
    title: { ua: "Урок 20 — Повсякденні дії", ru: "Урок 20 — Повседневные действия" },
    words: [
      { sk: "TODO:vstať", ua: "встати", ru: "встать", img: "/words_a1/vstať.jpg" },
      { sk: "TODO:ísť do práce", ua: "йти на роботу", ru: "идти на работу", img: "/words_a1/ísť do práce.jpg" },
      { sk: "TODO:nakupovať", ua: "робити покупки", ru: "делать покупки", img: "/words_a1/nakupovať.jpg" },
      { sk: "TODO:oddýchnuť si", ua: "відпочити", ru: "отдохнуть", img: "/words_a1/oddýchnuť si.jpg" },
      { sk: "TODO:stretnúť sa", ua: "зустрітися", ru: "встретиться", img: "/words_a1/stretnúť sa.jpg" },
      { sk: "TODO:telefonovať", ua: "телефонувати", ru: "звонить", img: "/words_a1/telefonovať.jpg" },
      { sk: "TODO:variť", ua: "готувати", ru: "готовить", img: "/words_a1/variť.jpg" },
      { sk: "TODO:pozerať", ua: "дивитися", ru: "смотреть", img: "/words_a1/pozerať.jpg" },
      { sk: "TODO:čítať", ua: "читати", ru: "читать", img: "/words_a1/čítať.jpg" },
      { sk: "TODO:spať", ua: "спати", ru: "спать", img: "/words_a1/spať.jpg" },
    ],
  },
  {
    id: "a1-21",
    title: { ua: "Урок 21 — Проблеми і ситуації", ru: "Урок 21 — Проблемы и ситуации" },
    words: [
      { sk: "TODO:problém", ua: "проблема", ru: "проблема", img: "/words_a1/problém.jpg" },
      { sk: "TODO:pokazený", ua: "зламаний", ru: "сломанный / неисправный", img: "/words_a1/pokazený.jpg" },
      { sk: "TODO:stratiť", ua: "загубити", ru: "потерять", img: "/words_a1/stratiť.jpg" },
      { sk: "TODO:nájsť", ua: "знайти", ru: "найти", img: "/words_a1/nájsť.jpg" },
      { sk: "TODO:meškať", ua: "запізнюватися", ru: "опаздывать", img: "/words_a1/meškať.jpg" },
      { sk: "TODO:zabudnúť", ua: "забути", ru: "забыть", img: "/words_a1/zabudnúť.jpg" },
      { sk: "TODO:chyba", ua: "помилка", ru: "ошибка", img: "/words_a1/chyba.jpg" },
      { sk: "TODO:oprava", ua: "ремонт", ru: "ремонт", img: "/words_a1/oprava.jpg" },
      { sk: "TODO:pomoc", ua: "допомога", ru: "помощь", img: "/words_a1/pomoc.jpg" },
      { sk: "TODO:riešenie", ua: "рішення", ru: "решение", img: "/words_a1/riešenie.jpg" },
    ],
  },
  {
    id: "a1-22",
    title: { ua: "Урок 22 — Напрямки", ru: "Урок 22 — Направления" },
    words: [
      { sk: "TODO:vpravo", ua: "праворуч", ru: "направо", img: "/words_a1/vpravo.jpg" },
      { sk: "TODO:vľavo", ua: "ліворуч", ru: "налево", img: "/words_a1/vľavo.jpg" },
      { sk: "TODO:rovno", ua: "прямо", ru: "прямо", img: "/words_a1/rovno.jpg" },
      { sk: "blízko", ua: "близько", ru: "близко", img: "/words_a1/blízko.jpg" },
      { sk: "TODO:ďaleko", ua: "далеко", ru: "далеко", img: "/words_a1/ďaleko.jpg" },
      { sk: "TODO:hore", ua: "вгору", ru: "вверх", img: "/words_a1/hore.jpg" },
      { sk: "TODO:dole", ua: "вниз", ru: "вниз", img: "/words_a1/dole.jpg" },
      { sk: "TODO:pred", ua: "перед", ru: "перед", img: "/words_a1/pred.jpg" },
      { sk: "TODO:za", ua: "за", ru: "за", img: "/words_a1/za.jpg" },
      { sk: "TODO:medzi", ua: "між", ru: "между", img: "/words_a1/medzi.jpg" },
    ],
  },
  {
    id: "a1-23",
    title: { ua: "Урок 23 — Характер", ru: "Урок 23 — Характер" },
    words: [
      { sk: "TODO:dobrý", ua: "добрий", ru: "добрый", img: "/words_a1/dobrý.jpg" },
      { sk: "TODO:zlý", ua: "поганий", ru: "плохой", img: "/words_a1/zlý.jpg" },
      { sk: "TODO:trpezlivý", ua: "терплячий", ru: "терпеливый", img: "/words_a1/trpezlivý.jpg" },
      { sk: "TODO:lenivý", ua: "ледачий", ru: "ленивый", img: "/words_a1/lenivý.jpg" },
      { sk: "TODO:pracovitý", ua: "працьовитий", ru: "трудолюбивый", img: "/words_a1/pracovitý.jpg" },
      { sk: "TODO:úprimný", ua: "щирий", ru: "искренний", img: "/words_a1/úprimný.jpg" },
      { sk: "TODO:priateľský", ua: "дружній", ru: "дружелюбный", img: "/words_a1/priateľský.jpg" },
      { sk: "TODO:vážny", ua: "серйозний", ru: "серьёзный", img: "/words_a1/vážny.jpg" },
      { sk: "TODO:zábavný", ua: "веселий", ru: "весёлый", img: "/words_a1/zábavný.jpg" },
      { sk: "TODO:tichý", ua: "тихий", ru: "тихий", img: "/words_a1/tichý.jpg" },
    ],
  },
  {
    id: "a1-24",
    title: { ua: "Урок 24 — Погода (розширено)", ru: "Урок 24 — Погода (расширено)" },
    words: [
      { sk: "TODO:teplo", ua: "тепло", ru: "тепло", img: "/words_a1/teplo.jpg" },
      { sk: "TODO:chladno", ua: "холодно", ru: "холодно", img: "/words_a1/chladno.jpg" },
      { sk: "TODO:zamračené", ua: "хмарно", ru: "пасмурно / облачно", img: "/words_a1/zamračené.jpg" },
      { sk: "TODO:jasno", ua: "ясно", ru: "ясно", img: "/words_a1/jasno.jpg" },
      { sk: "TODO:pršať", ua: "йти дощу", ru: "идти (о дожде) / идти дождю", img: "/words_a1/pršať.jpg" },
      { sk: "TODO:snežiť", ua: "йти снігу", ru: "идти (о снеге) / идти снегу", img: "/words_a1/snežiť.jpg" },
      { sk: "TODO:vietor", ua: "вітер", ru: "ветер", img: "/words_a1/vietor.jpg" },
      { sk: "TODO:mráz", ua: "мороз", ru: "мороз", img: "/words_a1/mráz.jpg" },
      { sk: "TODO:búrka", ua: "буря", ru: "буря / гроза", img: "/words_a1/búrka.jpg" },
      { sk: "TODO:predpoveď", ua: "прогноз", ru: "прогноз", img: "/words_a1/predpoveď.jpg" },
    ],
  },
  {
    id: "a1-25",
    title: { ua: "Урок 25 — Їжа (розширено)", ru: "Урок 25 — Еда (расширено)" },
    words: [
      { sk: "TODO:raňajky", ua: "сніданок", ru: "завтрак", img: "/words_a1/raňajky.jpg" },
      { sk: "TODO:obed", ua: "обід", ru: "обед", img: "/words_a1/obed.jpg" },
      { sk: "TODO:večera", ua: "вечеря", ru: "ужин", img: "/words_a1/večera.jpg" },
      { sk: "TODO:sladký", ua: "солодкий", ru: "сладкий", img: "/words_a1/sladký.jpg" },
      { sk: "TODO:slaný", ua: "солоний", ru: "солёный", img: "/words_a1/slaný.jpg" },
      { sk: "TODO:pikantný", ua: "гострий", ru: "острый / пикантный", img: "/words_a1/pikantný.jpg" },
      { sk: "TODO:čerstvý", ua: "свіжий", ru: "свежий", img: "/words_a1/čerstvý.jpg" },
      { sk: "TODO:hlad", ua: "голод", ru: "голод", img: "/words_a1/hlad.jpg" },
      { sk: "TODO:smäd", ua: "спрага", ru: "жажда", img: "/words_a1/smäd.jpg" },
      { sk: "TODO:chuť", ua: "смак / бажання", ru: "вкус / желание", img: "/words_a1/chuť.jpg" },
    ],
  },
  {
    id: "a1-26",
    title: { ua: "Урок 26 — Гроші (розширено)", ru: "Урок 26 — Деньги (расширено)" },
    words: [
      { sk: "TODO:platiť", ua: "платити", ru: "платить", img: "/words_a1/platiť.jpg" },
      { sk: "TODO:ušetriť", ua: "зекономити", ru: "сэкономить", img: "/words_a1/ušetriť.jpg" },
      { sk: "TODO:minúť", ua: "витратити", ru: "потратить", img: "/words_a1/minúť.jpg" },
      { sk: "TODO:výplata", ua: "зарплата", ru: "зарплата", img: "/words_a1/výplata.jpg" },
      { sk: "TODO:úver", ua: "кредит", ru: "кредит", img: "/words_a1/úver.jpg" },
      { sk: "TODO:dlh", ua: "борг", ru: "долг", img: "/words_a1/dlh.jpg" },
      { sk: "bankomat", ua: "банкомат", ru: "банкомат", img: "/words_a1/bankomat.jpg" },
      { sk: "TODO:účet", ua: "рахунок", ru: "счёт", img: "/words_a1/účet.jpg" },
      { sk: "TODO:príjem", ua: "дохід", ru: "доход", img: "/words_a1/príjem.jpg" },
      { sk: "TODO:výdavok", ua: "витрата", ru: "расход", img: "/words_a1/výdavok.jpg" },
    ],
  },
  {
    id: "a1-27",
    title: { ua: "Урок 27 — Технології (практика)", ru: "Урок 27 — Технологии (практика)" },
    words: [
      { sk: "TODO:zapnúť", ua: "увімкнути", ru: "включить", img: "/words_a1/zapnúť.jpg" },
      { sk: "TODO:vypnúť", ua: "вимкнути", ru: "выключить", img: "/words_a1/vypnúť.jpg" },
      { sk: "TODO:nabíjať", ua: "заряджати", ru: "заряжать", img: "/words_a1/nabíjať.jpg" },
      { sk: "TODO:prihlásiť sa", ua: "увійти", ru: "войти", img: "/words_a1/prihlásiť sa.jpg" },
      { sk: "TODO:odhlásiť sa", ua: "вийти", ru: "выйти", img: "/words_a1/odhlásiť sa.jpg" },
      { sk: "TODO:stiahnuť", ua: "завантажити", ru: "скачать / загрузить", img: "/words_a1/stiahnuť.jpg" },
      { sk: "TODO:uložiť", ua: "зберегти", ru: "сохранить", img: "/words_a1/uložiť.jpg" },
      { sk: "TODO:vymazať", ua: "видалити", ru: "удалить", img: "/words_a1/vymazať.jpg" },
      { sk: "TODO:kliknúť", ua: "натиснути", ru: "нажать / кликнуть", img: "/words_a1/kliknúť.jpg" },
      { sk: "TODO:nastavenia", ua: "налаштування", ru: "настройки", img: "/words_a1/nastavenia.jpg" },
    ],
  },
  {
    id: "a1-28",
    title: { ua: "Урок 28 — Подорожі (ситуації)", ru: "Урок 28 — Путешествия (ситуации)" },
    words: [
      { sk: "TODO:let", ua: "рейс", ru: "рейс", img: "/words_a1/let.jpg" },
      { sk: "TODO:meškanie", ua: "затримка", ru: "задержка", img: "/words_a1/meškanie.jpg" },
      { sk: "TODO:odlet", ua: "виліт", ru: "вылет", img: "/words_a1/odlet.jpg" },
      { sk: "TODO:prílet", ua: "приліт", ru: "прилёт", img: "/words_a1/prílet.jpg" },
      { sk: "TODO:pasová kontrola", ua: "паспортний контроль", ru: "паспортный контроль", img: "/words_a1/pasová kontrola.jpg" },
      { sk: "zavazadlo", ua: "багаж", ru: "багаж", img: "/words_a1/batožina.jpg" },
      { sk: "TODO:rezervácia", ua: "бронювання", ru: "бронирование", img: "/words_a1/rezervácia.jpg" },
      { sk: "TODO:sprievodca", ua: "гід", ru: "гид", img: "/words_a1/sprievodca.jpg" },
      { sk: "TODO:mapa", ua: "карта", ru: "карта", img: "/words_a1/mapa.jpg" },
      { sk: "TODO:cieľ", ua: "ціль", ru: "цель", img: "/words_a1/cieľ.jpg" },
    ],
  },
  {
    id: "a1-29",
    title: { ua: "Урок 29 — Робочі фрази", ru: "Урок 29 — Рабочие фразы" },
    words: [
      { sk: "TODO:rozumiem", ua: "розумію", ru: "понимаю", img: "/words_a1/rozumiem.jpg" },
      { sk: "TODO:nerozumiem", ua: "не розумію", ru: "не понимаю", img: "/words_a1/nerozumiem.jpg" },
      { sk: "TODO:hotovo", ua: "готово", ru: "готово", img: "/words_a1/hotovo.jpg" },
      { sk: "TODO:môžem", ua: "можна", ru: "можно", img: "/words_a1/môžem.jpg" },
      { sk: "TODO:potrebujem", ua: "потрібно", ru: "нужно / мне нужно", img: "/words_a1/potrebujem.jpg" },
      { sk: "TODO:problém", ua: "проблема", ru: "проблема", img: "/words_a1/problém.jpg" },
      { sk: "TODO:v poriadku", ua: "в порядку", ru: "в порядке", img: "/words_a1/v poriadku.jpg" },
      { sk: "TODO:hneď", ua: "зараз", ru: "сейчас / сразу", img: "/words_a1/hneď.jpg" },
      { sk: "TODO:neskôr", ua: "пізніше", ru: "позже", img: "/words_a1/neskôr.jpg" },
      { sk: "TODO:dohodnúť sa", ua: "домовитись", ru: "договориться", img: "/words_a1/dohodnúť sa.jpg" },
    ],
  },
  {
    id: "a1-30",
    title: { ua: "Урок 30 — Часті дієслова", ru: "Урок 30 — Частые глаголы" },
    words: [
      { sk: "TODO:mať", ua: "мати", ru: "иметь", img: "/words_a1/mať.jpg" },
      { sk: "TODO:byť", ua: "бути", ru: "быть", img: "/words_a1/byť.jpg" },
      { sk: "TODO:robiť", ua: "робити", ru: "делать", img: "/words_a1/robiť.jpg" },
      { sk: "TODO:ísť", ua: "йти", ru: "идти", img: "/words_a1/ísť.jpg" },
      { sk: "TODO:vidieť", ua: "бачити", ru: "видеть", img: "/words_a1/vidieť.jpg" },
      { sk: "TODO:počúvať", ua: "слухати", ru: "слушать", img: "/words_a1/počúvať.jpg" },
      { sk: "TODO:hovoriť", ua: "говорити", ru: "говорить", img: "/words_a1/hovoriť.jpg" },
      { sk: "TODO:myslieť", ua: "думати", ru: "думать", img: "/words_a1/myslieť.jpg" },
      { sk: "TODO:chcieť", ua: "хотіти", ru: "хотеть", img: "/words_a1/chcieť.jpg" },
      { sk: "TODO:môcť", ua: "могти", ru: "мочь", img: "/words_a1/môcť.jpg" },
    ],
  },
  {
    id: "a1-31",
    title: { ua: "Урок 31 — Почуття", ru: "Урок 31 — Чувства" },
    words: [
      { sk: "TODO:radosť", ua: "радість", ru: "радость", img: "/words_a1/radosť.jpg" },
      { sk: "TODO:smútok", ua: "смуток", ru: "грусть / печаль", img: "/words_a1/smútok.jpg" },
      { sk: "TODO:strach", ua: "страх", ru: "страх", img: "/words_a1/strach.jpg" },
      { sk: "TODO:hnev", ua: "злість", ru: "злость / гнев", img: "/words_a1/hnev.jpg" },
      { sk: "TODO:láska", ua: "любов", ru: "любовь", img: "/words_a1/láska.jpg" },
      { sk: "TODO:únava", ua: "втома", ru: "усталость", img: "/words_a1/únava.jpg" },
      { sk: "TODO:stres", ua: "стрес", ru: "стресс", img: "/words_a1/stres.jpg" },
      { sk: "TODO:pokoj", ua: "спокій", ru: "покой / спокойствие", img: "/words_a1/pokoj.jpg" },
      { sk: "TODO:prekvapenie", ua: "здивування", ru: "удивление", img: "/words_a1/prekvapenie.jpg" },
      { sk: "TODO:nadšenie", ua: "захоплення", ru: "восторг / воодушевление", img: "/words_a1/nadšenie.jpg" },
    ],
  },
  {
    id: "a1-32",
    title: { ua: "Урок 32 — Опис речей", ru: "Урок 32 — Описание вещей" },
    words: [
      { sk: "TODO:nový", ua: "новий", ru: "новый", img: "/words_a1/nový.jpg" },
      { sk: "TODO:starý", ua: "старий", ru: "старый", img: "/words_a1/starý.jpg" },
      { sk: "TODO:veľký", ua: "великий", ru: "большой", img: "/words_a1/veľký.jpg" },
      { sk: "TODO:malý", ua: "малий", ru: "маленький", img: "/words_a1/malý.jpg" },
      { sk: "TODO:ťažký", ua: "важкий", ru: "тяжёлый", img: "/words_a1/ťažký.jpg" },
      { sk: "TODO:ľahký", ua: "легкий", ru: "лёгкий", img: "/words_a1/ľahký.jpg" },
      { sk: "TODO:rýchly", ua: "швидкий", ru: "быстрый", img: "/words_a1/rýchly.jpg" },
      { sk: "TODO:pomalý", ua: "повільний", ru: "медленный", img: "/words_a1/pomalý.jpg" },
      { sk: "TODO:drahý", ua: "дорогий", ru: "дорогой", img: "/words_a1/drahý.jpg" },
      { sk: "TODO:lacný", ua: "дешевий", ru: "дешёвый", img: "/words_a1/lacný.jpg" },
    ],
  },
  {
    id: "a1-33",
    title: { ua: "Урок 33 — Дім (дії)", ru: "Урок 33 — Дом (действия)" },
    words: [
      { sk: "TODO:variť", ua: "готувати", ru: "готовить", img: "/words_a1/variť.jpg" },
      { sk: "TODO:vysávať", ua: "пилососити", ru: "пылесосить", img: "/words_a1/vysávať.jpg" },
      { sk: "TODO:umyť", ua: "помити", ru: "помыть", img: "/words_a1/umyť.jpg" },
      { sk: "TODO:zatvoriť", ua: "закрити", ru: "закрыть", img: "/words_a1/zatvoriť.jpg" },
      { sk: "TODO:opraviť", ua: "відремонтувати", ru: "отремонтировать", img: "/words_a1/opraviť.jpg" },
      { sk: "TODO:postaviť", ua: "побудувати", ru: "построить", img: "/words_a1/postaviť.jpg" },
      { sk: "TODO:presťahovať sa", ua: "переїхати", ru: "переехать", img: "/words_a1/presťahovať sa.jpg" },
      { sk: "TODO:zavesiť", ua: "повісити", ru: "повесить", img: "/words_a1/zavesiť.jpg" },
      { sk: "TODO:poskladať", ua: "скласти (речі)", ru: "сложить (вещи)", img: "/words_a1/poskladať.jpg" },
      { sk: "TODO:zariadiť", ua: "облаштувати", ru: "обустроить", img: "/words_a1/zariadiť.jpg" },
    ],
  },
  {
    id: "a1-34",
    title: { ua: "Урок 34 — Комунікація", ru: "Урок 34 — Коммуникация" },
    words: [
      { sk: "TODO:opísať", ua: "описати", ru: "описать", img: "/words_a1/opísať.jpg" },
      { sk: "TODO:navrhnúť", ua: "запропонувати", ru: "предложить", img: "/words_a1/navrhnúť.jpg" },
      { sk: "TODO:rozprávať", ua: "розповідати", ru: "рассказывать", img: "/words_a1/rozprávať.jpg" },
      { sk: "TODO:oznámiť", ua: "повідомити", ru: "сообщить", img: "/words_a1/oznámiť.jpg" },
      { sk: "TODO:požiadať", ua: "попросити", ru: "попросить", img: "/words_a1/požiadať.jpg" },
      { sk: "TODO:odpísať", ua: "відписати", ru: "ответить (на повідомлення)", img: "/words_a1/odpísať.jpg" },
      { sk: "TODO:zavolať", ua: "подзвонити", ru: "позвонить", img: "/words_a1/zavolať.jpg" },
      { sk: "TODO:pozdraviť", ua: "привітати", ru: "поприветствовать", img: "/words_a1/pozdraviť.jpg" },
      { sk: "TODO:spýtať sa", ua: "запитати", ru: "спросить", img: "/words_a1/spýtať sa.jpg" },
      { sk: "TODO:dohodnúť sa", ua: "домовитися", ru: "договориться", img: "/words_a1/dohodnúť sa.jpg" },
    ],
  },
  {
    id: "a1-35",
    title: { ua: "Урок 35 — Місто (ситуації)", ru: "Урок 35 — Город (ситуации)" },
    words: [
      { sk: "TODO:úrad", ua: "установа", ru: "учреждение", img: "/words_a1/úrad.jpg" },
      { sk: "TODO:kaderníctvo", ua: "перукарня", ru: "парикмахерская", img: "/words_a1/kaderníctvo.jpg" },
      { sk: "TODO:pekáreň", ua: "пекарня", ru: "пекарня", img: "/words_a1/pekáreň.jpg" },
      { sk: "TODO:cukráreň", ua: "кондитерська", ru: "кондитерская", img: "/words_a1/cukráreň.jpg" },
      { sk: "TODO:čerpacia stanica", ua: "заправка", ru: "заправка", img: "/words_a1/čerpacia stanica.jpg" },
      { sk: "autobusové nádraží", ua: "автовокзал", ru: "автовокзал", img: "/words_a1/autobusová stanica.jpg" },
      { sk: "TODO:železničná stanica", ua: "залізничний вокзал", ru: "железнодорожный вокзал", img: "/words_a1/železničná stanica.jpg" },
      { sk: "TODO:križovatka", ua: "перехрестя", ru: "перекрёсток", img: "/words_a1/križovatka.jpg" },
      { sk: "TODO:chodník", ua: "тротуар", ru: "тротуар", img: "/words_a1/chodník.jpg" },
      { sk: "TODO:podchod", ua: "підземний перехід", ru: "подземный переход", img: "/words_a1/podchod.jpg" },
    ],
  },
  {
    id: "a1-36",
    title: { ua: "Урок 36 — Транспорт (дії)", ru: "Урок 36 — Транспорт (действия)" },
    words: [
      { sk: "TODO:nastúpiť", ua: "сісти", ru: "сесть / зайти (в транспорт)", img: "/words_a1/nastúpiť.jpg" },
      { sk: "TODO:vystúpiť", ua: "вийти", ru: "выйти (из транспорта)", img: "/words_a1/vystúpiť.jpg" },
      { sk: "TODO:prestúpiť", ua: "пересісти", ru: "пересесть / сделать пересадку", img: "/words_a1/prestúpiť.jpg" },
      { sk: "TODO:meškať", ua: "запізнюватися", ru: "опаздывать", img: "/words_a1/meškať.jpg" },
      { sk: "TODO:čakať", ua: "чекати", ru: "ждать", img: "/words_a1/čakať.jpg" },
      { sk: "TODO:odísť", ua: "піти", ru: "уйти", img: "/words_a1/odísť.jpg" },
      { sk: "TODO:prísť", ua: "прийти", ru: "прийти", img: "/words_a1/prísť.jpg" },
      { sk: "TODO:riadiť", ua: "керувати", ru: "водить / управлять", img: "/words_a1/riadiť.jpg" },
      { sk: "TODO:parkovať", ua: "паркувати", ru: "парковать(ся)", img: "/words_a1/parkovať.jpg" },
      { sk: "TODO:zastaviť", ua: "зупинити", ru: "остановить", img: "/words_a1/zastaviť.jpg" },
    ],
  },
  {
    id: "a1-37",
    title: { ua: "Урок 37 — Плани", ru: "Урок 37 — Планы" },
    words: [
      { sk: "TODO:plán", ua: "план", ru: "план", img: "/words_a1/plán.jpg" },
      { sk: "TODO:cieľ", ua: "ціль", ru: "цель", img: "/words_a1/cieľ.jpg" },
      { sk: "TODO:budúcnosť", ua: "майбутнє", ru: "будущее", img: "/words_a1/budúcnosť.jpg" },
      { sk: "TODO:pripraviť", ua: "підготувати", ru: "подготовить", img: "/words_a1/pripraviť.jpg" },
      { sk: "TODO:budúci týždeň", ua: "наступного тижня", ru: "на следующей неделе", img: "/words_a1/budúci týždeň.jpg" },
      { sk: "TODO:dúfať", ua: "сподіватися", ru: "надеяться", img: "/words_a1/dúfať.jpg" },
      { sk: "TODO:rozhodnúť sa", ua: "вирішити", ru: "решить", img: "/words_a1/rozhodnúť sa.jpg" },
      { sk: "TODO:naplánovať", ua: "запланувати", ru: "запланировать", img: "/words_a1/naplánovať.jpg" },
      { sk: "TODO:termín", ua: "термін", ru: "срок", img: "/words_a1/termín.jpg" },
      { sk: "TODO:pokračovať", ua: "продовжити", ru: "продолжить", img: "/words_a1/pokračovať.jpg" },
    ],
  },
  {
    id: "a1-38",
    title: { ua: "Урок 38 — Ситуації в магазині", ru: "Урок 38 — Ситуации в магазине" },
    words: [
      { sk: "TODO:reklamácia", ua: "скарга / повернення", ru: "претензия / рекламация", img: "/words_a1/reklamácia.jpg" },
      { sk: "TODO:tovar", ua: "товар", ru: "товар", img: "/words_a1/tovar.jpg" },
      { sk: "TODO:sklad", ua: "склад", ru: "склад", img: "/words_a1/sklad.jpg" },
      { sk: "TODO:účtenka", ua: "чек", ru: "чек", img: "/words_a1/účtenka.jpg" },
      { sk: "TODO:záruka", ua: "гарантія", ru: "гарантия", img: "/words_a1/záruka.jpg" },
      { sk: "TODO:poškodený", ua: "пошкоджений", ru: "повреждённый", img: "/words_a1/poškodený.jpg" },
      { sk: "TODO:predavač", ua: "продавець", ru: "продавец", img: "/words_a1/predavač.jpg" },
      { sk: "TODO:zákazník", ua: "клієнт", ru: "клиент", img: "/words_a1/zákazník.jpg" },
      { sk: "TODO:reklamovať", ua: "рекламувати / подавати скаргу", ru: "подавать рекламацию", img: "/words_a1/reklamovať.jpg" },
      { sk: "TODO:výmena", ua: "обмін", ru: "обмен", img: "/words_a1/výmena.jpg" },
    ],
  },
  {
    id: "a1-39",
    title: { ua: "Урок 39 — Абстрактні слова", ru: "Урок 39 — Абстрактные слова" },
    words: [
      { sk: "TODO:život", ua: "життя", ru: "жизнь", img: "/words_a1/život.jpg" },
      { sk: "TODO:čas", ua: "час", ru: "время", img: "/words_a1/čas.jpg" },
      { sk: "TODO:možnosť", ua: "можливість", ru: "возможность", img: "/words_a1/možnosť.jpg" },
      { sk: "TODO:dôvod", ua: "причина", ru: "причина", img: "/words_a1/dôvod.jpg" },
      { sk: "TODO:význam", ua: "значення", ru: "значение", img: "/words_a1/význam.jpg" },
      { sk: "TODO:pravda", ua: "правда", ru: "правда", img: "/words_a1/pravda.jpg" },
      { sk: "TODO:lož", ua: "брехня", ru: "ложь", img: "/words_a1/lož.jpg" },
      { sk: "TODO:úspech", ua: "успіх", ru: "успех", img: "/words_a1/úspech.jpg" },
      { sk: "TODO:neúspech", ua: "невдача", ru: "неудача", img: "/words_a1/neúspech.jpg" },
      { sk: "TODO:skúsenosť", ua: "досвід", ru: "опыт", img: "/words_a1/skúsenosť.jpg" },
    ],
  },
  {
    id: "a1-40",
    title: { ua: "Урок 40 — Повторення A1", ru: "Урок 40 — Повторение A1" },
    words: [
      { sk: "TODO:učiť sa", ua: "вчитися", ru: "учиться", img: "/words_a1/učiť sa.jpg" },
      { sk: "TODO:cestovať", ua: "подорожувати", ru: "путешествовать", img: "/words_a1/cestovať.jpg" },
      { sk: "TODO:pomôcť", ua: "допомогти", ru: "помочь", img: "/words_a1/pomôcť.jpg" },
      { sk: "TODO:písať", ua: "писати", ru: "писать", img: "/words_a1/písať.jpg" },
      { sk: "TODO:vrátiť sa", ua: "повернутися", ru: "вернуться", img: "/words_a1/vrátiť sa.jpg" },
      { sk: "TODO:zostať", ua: "залишитися", ru: "остаться", img: "/words_a1/zostať.jpg" },
      { sk: "TODO:zmeniť", ua: "змінити", ru: "изменить", img: "/words_a1/zmeniť.jpg" },
      { sk: "TODO:ukázať", ua: "показати", ru: "показать", img: "/words_a1/ukázať.jpg" },
      { sk: "TODO:niesť", ua: "нести", ru: "нести", img: "/words_a1/niesť.jpg" },
      { sk: "TODO:sedieť", ua: "сидіти", ru: "сидеть", img: "/words_a1/sedieť.jpg" },
    ],
  },
];
