import type { Lesson } from "../data";

export const CS_B1_SOURCE: Lesson[] = [
  {
    id: "b1-1",
    title: { ua: "Урок 1 — Робота та кар’єра", ru: "Урок 1 — Работа и карьера" },
    words: [
      { sk: "pracovní doba", ua: "робочий час", ru: "рабочее время", img: "/words_b1/pracovná doba.jpg" },
      { sk: "nástup", ua: "вихід на роботу (початок)", ru: "выход на работу (начало)", img: "/words_b1/nástup.jpg" },
      { sk: "zkoušební doba", ua: "випробувальний термін", ru: "испытательный срок", img: "/words_b1_cz/zkoušební doba.jpg" },
      { sk: "pracovní poměr", ua: "трудові відносини", ru: "трудовые отношения", img: "/words_b1/pracovný pomer.jpg" },
      { sk: "výplata", ua: "виплата зарплати", ru: "выплата зарплаты", img: "/words_b1/výplata.jpg" },
      { sk: "příspěvek", ua: "внесок/доплата", ru: "взнос/доплата", img: "/words_b1/príspevok.jpg" },
      { sk: "docházka", ua: "відвідуваність/табель", ru: "посещаемость/табель", img: "/words_b1/dochádzkaa.jpg" },
      { sk: "benefit", ua: "бонус / соціальна пільга", ru: "бонус / социальная льгота", img: "/words_b1/benefit.jpg" },
      { sk: "nadřízený", ua: "керівник / начальник", ru: "руководитель / начальник", img: "/words_b1/nadriadený.jpg" },
      { sk: "podřízený", ua: "підлеглий", ru: "подчинённый", img: "/words_b1/podriadený.jpg" },
    ],
  },
  {
    id: "b1-2",
    title: { ua: "Урок 2 — Комунікація в команді", ru: "Урок 2 — Коммуникация в команде" },
    words: [
      { sk: "nedorozumění", ua: "непорозуміння", ru: "недоразумение", img: "/words_b1/nedorozumenie.jpg" },
      { sk: "spolupráce", ua: "співпраця", ru: "сотрудничество", img: "/words_b1/spolupráca.jpg" },
      { sk: "komunikace", ua: "комунікація", ru: "коммуникация", img: "/words_b1/komunikácia.jpg" },
      { sk: "vyjádřit se", ua: "висловитися", ru: "высказаться", img: "/words_b1_cz/vyjádřit se.jpg" },
      { sk: "navrhnout", ua: "запропонувати", ru: "предложить", img: "/words_b1_cz/navrhnout.jpg" },
      { sk: "souhlas", ua: "згода", ru: "согласие", img: "/words_b1/súhlas.jpg" },
      { sk: "nesouhlas", ua: "незгода", ru: "несогласие", img: "/words_b1/nesúhlas.jpg" },
      { sk: "vysvětlení", ua: "пояснення", ru: "объяснение", img: "/words_b1_cz/vysvětlení.jpg" },
      { sk: "upozornit", ua: "попередити / звернути увагу", ru: "предупредить / обратить внимание", img: "/words_b1/upozorniť.jpg" },
      { sk: "reagovat", ua: "реагувати", ru: "реагировать", img: "/words_b1_cz/reagovat.jpg" },
    ],
  },
  {
    id: "b1-3",
    title: { ua: "Урок 3 — Подорожі та транспорт", ru: "Урок 3 — Путешествия и транспорт" },
    words: [
      { sk: "příruční zavazadlo", ua: "ручна поклажа", ru: "ручная кладь", img: "/words_b1_cz/příruční zavazadlo.jpg" },
      { sk: "nástup", ua: "посадка (на транспорт)", ru: "посадка", img: "/words_b1/nástup.jpg" },
      { sk: "cestující", ua: "пасажир", ru: "пассажир", img: "/words_b1_cz/cestující.jpg" },
      { sk: "zrušení", ua: "скасування", ru: "отмена", img: "/words_b1_cz/zrušení.jpg" },
      { sk: "přestupovat", ua: "робити пересадку", ru: "делать пересадку", img: "/words_b1_cz/přestupovat.jpg" },
      { sk: "cestovní doklad", ua: "проїзний документ", ru: "проездной документ", img: "/words_b1_cz/cestovní doklad.jpg" },
      { sk: "bezpečnostní kontrola", ua: "контроль безпеки", ru: "контроль безопасности", img: "/words_b1_cz/bezpečnostní kontrola.jpg" },
      { sk: "palubní lístek", ua: "посадковий талон", ru: "посадочный талон", img: "/words_b1_cz/palubní lístek.jpg" },
      { sk: "odvzdat zavazadlo", ua: "здати багаж", ru: "сдать багаж", img: "/words_b1_cz/odvzdat zavazadlo.jpg" },
      { sk: "celní kontrola", ua: "митний контроль", ru: "таможенный контроль", img: "/words_b1_cz/celní kontrola.jpg" },
    ],
  },
  {
    id: "b1-4",
    title: { ua: "Урок 4 — Здоров’я та лікар", ru: "Урок 4 — Здоровье и врач" },
    words: [
      { sk: "léčba", ua: "лікування", ru: "лечение", img: "/words_b1/liečba.jpg" },
      { sk: "vyšetřit", ua: "оглянути / обстежити", ru: "осмотреть / обследовать", img: "/words_b1/vyšetriť.jpg" },
      { sk: "předepsat", ua: "призначити (ліки)", ru: "назначить (лекарство)", img: "/words_b1/predpísať.jpg" },
      { sk: "zhoršit se", ua: "погіршитися", ru: "ухудшиться", img: "/words_b1/zhoršiť sa.jpg" },
      { sk: "zlepšit se", ua: "покращитися", ru: "улучшиться", img: "/words_b1/zlepšiť sa.jpg" },
      { sk: "hospitalizace", ua: "госпіталізація", ru: "госпитализация", img: "/words_b1/hospitalizácia.jpg" },
      { sk: "příznak", ua: "симптом", ru: "симптом", img: "/words_b1_cz/příznak.jpg" },
      { sk: "zdravotní stav", ua: "стан здоров’я", ru: "состояние здоровья", img: "/words_b1/zdravotný stav.jpg" },
      { sk: "uzdravení", ua: "одужання / відновлення", ru: "выздоровление / восстановление", img: "/words_b1/zotavenie.jpg" },
      { sk: "předpis", ua: "припис / медичне призначення", ru: "предписание / медицинское назначение", img: "/words_b1/predpis.jpg" },
    ],
  },
  {
    id: "b1-5",
    title: { ua: "Урок 5 — Емоції та стосунки", ru: "Урок 5 — Эмоции и отношения" },
    words: [
      { sk: "hádka", ua: "сварка", ru: "ссора", img: "/words_b1/hádka.jpg" },
      { sk: "smíření", ua: "примирення", ru: "примирение", img: "/words_b1/zmierenie.jpg" },
      { sk: "zklamat", ua: "розчарувати", ru: "разочаровать", img: "/words_b1/sklamať.jpg" },
      { sk: "ocenit", ua: "оцінити (позитивно)", ru: "оценить (положительно)", img: "/words_b1/oceniť.jpg" },
      { sk: "žárlivost", ua: "ревнощі", ru: "ревность", img: "/words_b1/žiarlivosť.jpg" },
      { sk: "odpustit", ua: "пробачити", ru: "простить", img: "/words_b1/odpustiť.jpg" },
      { sk: "respekt", ua: "повага", ru: "уважение", img: "/words_b1/rešpekt.jpg" },
      { sk: "urazit se", ua: "образитися", ru: "обидеться", img: "/words_b1/uraziť sa.jpg" },
      { sk: "přiblížit se", ua: "зблизитися", ru: "сблизиться", img: "/words_b1/zblížiť sa.jpg" },
      { sk: "vztah", ua: "стосунки", ru: "отношения", img: "/words_b1/vzťah.jpg" },
    ],
  },
  {
    id: "b1-6",
    title: { ua: "Урок 6 — Освіта та навчання", ru: "Урок 6 — Образование и обучение" },
    words: [
      { sk: "seminář", ua: "семінар", ru: "семинар", img: "/words_b1/seminár.jpg" },
      { sk: "zadání", ua: "завдання", ru: "задание", img: "/words_b1/zadanie.jpg" },
      { sk: "hodnocení", ua: "оцінювання", ru: "оценивание", img: "/words_b1/hodnotenie.jpg" },
      { sk: "soustředění", ua: "концентрація", ru: "концентрация", img: "/words_b1/sústredenie.jpg" },
      { sk: "zlepšení", ua: "покращення", ru: "улучшение", img: "/words_b1/zlepšenie.jpg" },
      { sk: "známka", ua: "оцінка (бал)", ru: "оценка (балл)", img: "/words_b1/známka.jpg" },
      { sk: "ročník", ua: "курс (рік навчання)", ru: "курс (год обучения)", img: "/words_b1/ročník.jpg" },
      { sk: "přednášet", ua: "читати лекцію", ru: "читать лекцию", img: "/words_b1/prednášať.jpg" },
      { sk: "vypracovat", ua: "опрацювати / виконати (завдання)", ru: "выполнить (задание)", img: "/words_b1/vypracovať.jpg" },
      { sk: "termín odevzdání", ua: "термін здачі", ru: "срок сдачи", img: "/words_b1/termín odovzdania.jpg" },
    ],
  },
  {
    id: "b1-7",
    title: { ua: "Урок 7 — Технології та інтернет", ru: "Урок 7 — Технологии и интернет" },
    words: [
      { sk: "nastavení", ua: "налаштування", ru: "настройка", img: "/words_b1_cz/nastavení.jpg" },
      { sk: "heslo", ua: "пароль", ru: "пароль", img: "/words_b1/heslo.jpg" },
      { sk: "přihlášení", ua: "вхід (логін)", ru: "вход (логин)", img: "/words_b1/prihlásenie.jpg" },
      { sk: "soukromí", ua: "приватність", ru: "приватность", img: "/words_b1/súkromie.jpg" },
      { sk: "nahrát", ua: "завантажити (на сайт)", ru: "загрузить (на сайт)", img: "/words_b1/nahrať.jpg" },
      { sk: "sdílet", ua: "ділитися", ru: "делиться", img: "/words_b1_cz/sdílet.jpg" },
      { sk: "prohlížeč", ua: "браузер", ru: "браузер", img: "/words_b1/prehliadač.jpg" },
      { sk: "aplikace", ua: "додаток", ru: "приложение", img: "/words_b1_cz/aplikace.jpg" },
      { sk: "vyhledávat", ua: "шукати (в інтернеті)", ru: "искать (в интернете)", img: "/words_b1/vyhľadávať.jpg" },
      { sk: "ochrana údajů", ua: "захист даних", ru: "защита данных", img: "/words_b1/ochrana údajov.jpg" },
    ],
  },
  {
    id: "b1-8",
    title: { ua: "Урок 8 — Фінанси та покупки", ru: "Урок 8 — Финансы и покупки" },
    words: [
      { sk: "splátka", ua: "платіж частинами", ru: "взнос (рассрочка)", img: "/words_b1/splátka.jpg" },
      { sk: "pokladní doklad", ua: "чек", ru: "чек", img: "/words_b1/pokladničný doklad.jpg" },
      { sk: "prodejce", ua: "продавець", ru: "продавец", img: "/words_b1/predajca.jpg" },
      { sk: "půjčka", ua: "позика", ru: "заём", img: "/words_b1/pôžička.jpg" },
      { sk: "úrok", ua: "відсоток (по кредиту)", ru: "процент (по кредиту)", img: "/words_b1/úrok.jpg" },
      { sk: "dluh", ua: "борг", ru: "долг", img: "/words_b1_cz/dluh.jpg" },
      { sk: "výpis z účtu", ua: "виписка з рахунку", ru: "выписка со счёта", img: "/words_b1/výpis z účtu.jpg" },
      { sk: "zůstatek", ua: "залишок (на рахунку)", ru: "остаток (на счёте)", img: "/words_b1/zostatok.jpg" },
      { sk: "zamítnout", ua: "відхилити (заявку / кредит)", ru: "отклонить (заявку / кредит)", img: "/words_b1/zamietnuť.jpg" },
      { sk: "splatnost", ua: "термін погашення", ru: "срок погашения", img: "/words_b1/splatnosť.jpg" },
    ],
  },
  {
    id: "b1-9",
    title: { ua: "Урок 9 — Дім: ремонти та послуги", ru: "Урок 9 — Дом: ремонты и услуги" },
    words: [
      { sk: "montáž", ua: "монтаж", ru: "монтаж", img: "/words_b1/montáž.jpg" },
      { sk: "technická podpora", ua: "техпідтримка", ru: "техподдержка", img: "/words_b1/technická podpora.jpg" },
      { sk: "údržba", ua: "обслуговування / догляд", ru: "обслуживание / уход", img: "/words_b1/údržba.jpg" },
      { sk: "objednat servis", ua: "замовити сервіс", ru: "заказать сервис", img: "/words_b1/objednať servis.jpg" },
      { sk: "smluvní servis", ua: "офіційний сервіс", ru: "официальный сервис", img: "/words_b1/zmluvný servis.jpg" },
      { sk: "porucha zařízení", ua: "поломка пристрою", ru: "поломка устройства", img: "/words_b1/porucha zariadenia.jpg" },
      { sk: "oprava na místě", ua: "ремонт на місці", ru: "ремонт на месте", img: "/words_b1/oprava na mieste.jpg" },
      { sk: "zásah technika", ua: "виїзд майстра", ru: "выезд техника", img: "/words_b1/zásah technika.jpg" },
      { sk: "pracovní postup", ua: "робоча процедура", ru: "рабочая процедура", img: "/words_b1/pracovný postup.jpg" },
      { sk: "odstranit chybu", ua: "усунути несправність", ru: "устранить неисправность", img: "/words_b1/odstrániť chybu.jpg" },
    ],
  },
  {
    id: "b1-10",
    title: { ua: "Урок 10 — Комунікація та медіа", ru: "Урок 10 — Коммуникация и медиа" },
    words: [
      { sk: "rozhovor", ua: "інтерв’ю / розмова", ru: "интервью / разговор", img: "/words_b1/rozhovor.jpg" },
      { sk: "reportáž", ua: "репортаж", ru: "репортаж", img: "/words_b1/reportáž.jpg" },
      { sk: "tisková zpráva", ua: "пресреліз", ru: "пресс-релиз", img: "/words_b1/tlačová správa.jpg" },
      { sk: "sledovat", ua: "стежити / слідкувати", ru: "следить", img: "/words_b1/sledovať.jpg" },
      { sk: "ovlivnit", ua: "вплинути", ru: "повлиять", img: "/words_b1/ovplyvniť.jpg" },
      { sk: "uveritelný", ua: "достовірний", ru: "достоверный", img: "/words_b1/uveriteľný.jpg" },
      { sk: "informovat", ua: "інформувати", ru: "информировать", img: "/words_b1/informovať.jpg" },
      { sk: "vyjádřit názor", ua: "висловити думку", ru: "выразить мнение", img: "/words_b1_cz/vyjádřit názor.jpg" },
      { sk: "komentář", ua: "коментар", ru: "комментарий", img: "/words_b1/komentár.jpg" },
      { sk: "veřejnost", ua: "громадськість", ru: "общественность", img: "/words_b1/verejnosť.jpg" },
    ],
  },
  {
    id: "b1-11",
    title: { ua: "Урок 11 — Природа та погода", ru: "Урок 11 — Природа и погода" },
    words: [
      { sk: "sucho", ua: "посуха", ru: "засуха", img: "/words_b1/sucho.jpg" },
      { sk: "povodeň", ua: "повінь", ru: "наводнение", img: "/words_b1/povodeň.jpg" },
      { sk: "klima", ua: "клімат", ru: "климат", img: "/words_b1/klíma.jpg" },
      { sk: "oblačnost", ua: "хмарність", ru: "облачность", img: "/words_b1/oblačnosť.jpg" },
      { sk: "lavina", ua: "лавина", ru: "лавина", img: "/words_b1/lavína.jpg" },
      { sk: "zemětřesení", ua: "землетрус", ru: "землетрясение", img: "/words_b1/zemetrasenie.jpg" },
      { sk: "vlhkost", ua: "вологість", ru: "влажность", img: "/words_b1/vlhkosť.jpg" },
      { sk: "tání", ua: "танення", ru: "таяние", img: "/words_b1/topenie.jpg" },
      { sk: "záplava", ua: "затоплення", ru: "затопление", img: "/words_b1/záplava.jpg" },
      { sk: "přírodní katastrofa", ua: "природна катастрофа", ru: "природная катастрофа", img: "/words_b1/prírodná katastrofa.jpg" },
    ],
  },
  {
    id: "b1-12",
    title: { ua: "Урок 12 — У місті: адміністрація", ru: "Урок 12 — В городе: администрация" },
    words: [
      { sk: "přechodný pobyt", ua: "тимчасове проживання", ru: "временное проживание", img: "/words_b1/prechodný pobyt.jpg" },
      { sk: "prohlášení", ua: "заява / декларація", ru: "заявление / декларация", img: "/words_b1/vyhlásenie.jpg" },
      { sk: "ověření totožnosti", ua: "перевірка особи", ru: "проверка личности", img: "/words_b1/overenie totožnosti.jpg" },
      { sk: "zákonný", ua: "законний", ru: "законный", img: "/words_b1/zákonný.jpg" },
      { sk: "občanství", ua: "громадянство", ru: "гражданство", img: "/words_b1/občianstvo.jpg" },
      { sk: "povinnost", ua: "обов’язок", ru: "обязанность", img: "/words_b1_cz/povinnost.jpg" },
      { sk: "oprávnění", ua: "право / повноваження", ru: "право / полномочие", img: "/words_b1/oprávnenie.jpg" },
      { sk: "zápis", ua: "запис / внесення до реєстру", ru: "запись / внесение в реестр", img: "/words_b1/zápis.jpg" },
      { sk: "odvolání", ua: "апеляція / оскарження", ru: "апелляция / обжалование", img: "/words_b1/odvolanie.jpg" },
      { sk: "úřední dokument", ua: "офіційний документ", ru: "официальный документ", img: "/words_b1/úradný dokument.jpg" },
    ],
  },
  {
    id: "b1-13",
    title: { ua: "Урок 13 — Послуги та клієнт", ru: "Урок 13 — Услуги и клиент" },
    words: [
      { sk: "ochota", ua: "готовність допомогти", ru: "готовность помочь", img: "/words_b1/ochota.jpg" },
      { sk: "zákazník", ua: "клієнт", ru: "клиент", img: "/words_b1/zákazník.jpg" },
      { sk: "poskytovat služby", ua: "надавати послуги", ru: "предоставлять услуги", img: "/words_b1/poskytovať služby.jpg" },
      { sk: "vyřízení požadavku", ua: "обробка запиту", ru: "обработка запроса", img: "/words_b1/vybavenie požiadavky.jpg" },
      { sk: "spokojenost", ua: "задоволеність", ru: "удовлетворенность", img: "/words_b1_cz/spokojenost.jpg" },
      { sk: "nespokojený", ua: "незадоволений", ru: "недовольный", img: "/words_b1/nespokojný.jpg" },
      { sk: "odpovídat za", ua: "нести відповідальність за", ru: "нести ответственность за", img: "/words_b1/zodpovedať za.jpg" },
      { sk: "vyhovět", ua: "задовольнити (вимогу)", ru: "удовлетворить (требование)", img: "/words_b1/vyhovieť.jpg" },
      { sk: "podpora zákazníků", ua: "служба підтримки клієнтів", ru: "служба поддержки клиентов", img: "/words_b1/podpora zákazníkov.jpg" },
      { sk: "požadavek", ua: "вимога / запит", ru: "требование / запрос", img: "/words_b1_cz/požadavek.jpg" },
    ],
  },
  {
    id: "b1-14",
    title: { ua: "Урок 14 — Харчування та звички", ru: "Урок 14 — Питание и привычки" },
    words: [
      { sk: "stravování", ua: "харчування", ru: "питание", img: "/words_b1/stravovanie.jpg" },
      { sk: "složení", ua: "склад", ru: "состав", img: "/words_b1/zloženie.jpg" },
      { sk: "porce", ua: "порція", ru: "порция", img: "/words_b1_cz/porce.jpg" },
      { sk: "intolerance", ua: "непереносимість", ru: "непереносимость", img: "/words_b1/intolerancia.jpg" },
      { sk: "návyk", ua: "звичка", ru: "привычка", img: "/words_b1/návyk.jpg" },
      { sk: "omezit", ua: "обмежити", ru: "ограничить", img: "/words_b1/obmedziť.jpg" },
      { sk: "vyvážená strava", ua: "збалансоване харчування", ru: "сбалансированное питание", img: "/words_b1/vyvážená strava.jpg" },
      { sk: "výživový doplněk", ua: "харчова добавка", ru: "пищевая добавка", img: "/words_b1/výživový doplnok.jpg" },
      { sk: "pravidelnost", ua: "регулярність", ru: "регулярность", img: "/words_b1/pravidelnosť.jpg" },
      { sk: "zdravý životní styl", ua: "здоровий спосіб життя", ru: "здоровый образ жизни", img: "/words_b1/zdravý životný štýl.jpg" },
    ],
  },
  {
    id: "b1-15",
    title: { ua: "Урок 15 — Спорт і форма", ru: "Урок 15 — Спорт и форма" },
    words: [
      { sk: "výdrž", ua: "витривалість", ru: "выносливость", img: "/words_b1/výdrž.jpg" },
      { sk: "sval", ua: "м’яз", ru: "мышца", img: "/words_b1/sval.jpg" },
      { sk: "rozohřátí", ua: "розігрів", ru: "разминка", img: "/words_b1/rozohriatie.jpg" },
      { sk: "strečink", ua: "розтяжка", ru: "растяжка", img: "/words_b1/strečing.jpg" },
      { sk: "životospráva", ua: "здоровий спосіб життя", ru: "здоровый образ жизни", img: "/words_b1/životospráva.jpg" },
      { sk: "kondice", ua: "фізична форма", ru: "физическая форма", img: "/words_b1/kondícia.jpg" },
      { sk: "výkon", ua: "результат / продуктивність", ru: "результат / производительность", img: "/words_b1/výkon.jpg" },
      { sk: "zlepšit výkon", ua: "покращити результат", ru: "улучшить результат", img: "/words_b1/zlepšiť výkon.jpg" },
      { sk: "přetížení", ua: "перевантаження", ru: "перегрузка", img: "/words_b1/preťaženie.jpg" },
      { sk: "odpočinek", ua: "відпочинок", ru: "отдых", img: "/words_b1/oddych.jpg" },
    ],
  },
  {
    id: "b1-16",
    title: { ua: "Урок 16 — Культура та дозвілля", ru: "Урок 16 — Культура и досуг" },
    words: [
      { sk: "vkus", ua: "смак (уподобання)", ru: "вкус (предпочтения)", img: "/words_b1/vkus.jpg" },
      { sk: "recenze", ua: "рецензія", ru: "рецензия", img: "/words_b1/recenzia.jpg" },
      { sk: "zážitek", ua: "враження", ru: "впечатление", img: "/words_b1/zážitok.jpg" },
      { sk: "vystoupení", ua: "виступ", ru: "выступление", img: "/words_b1/vystúpenie.jpg" },
      { sk: "volný čas", ua: "вільний час", ru: "свободное время", img: "/words_b1_cz/volný čas.jpg" },
      { sk: "účinkovat", ua: "виступати (брати участь)", ru: "выступать (принимать участие)", img: "/words_b1/účinkovať.jpg" },
      { sk: "navštívit", ua: "відвідати", ru: "посетить", img: "/words_b1/navštíviť.jpg" },
      { sk: "premiéra", ua: "прем’єра", ru: "премьера", img: "/words_b1/výstava.jpg" },
      { sk: "program akce", ua: "програма заходу", ru: "программа мероприятия", img: "/words_b1/program podujatia.jpg" },
      { sk: "rezervace místa", ua: "бронювання місця", ru: "бронирование места", img: "/words_b1/rezervácia miesta.jpg" },
    ],
  },
  {
    id: "b1-17",
    title: { ua: "Урок 17 — Спорт", ru: "Урок 17 — Спорт" },
    words: [
      { sk: "trénink", ua: "тренування", ru: "тренировка", img: "/words_b1/tréning.jpg" },
      { sk: "zápas", ua: "матч", ru: "матч", img: "/words_b1/zápas.jpg" },
      { sk: "výhra", ua: "перемога", ru: "победа", img: "/words_b1/výhra.jpg" },
      { sk: "prohra", ua: "поразка", ru: "поражение", img: "/words_b1/prehra.jpg" },
      { sk: "rozhodčí", ua: "суддя", ru: "судья", img: "/words_b1/rozhodca.jpg" },
      { sk: "soutěž", ua: "змагання", ru: "соревнование", img: "/words_b1/súťaž.jpg" },
      { sk: "divák", ua: "глядач", ru: "зритель", img: "/words_b1/divák.jpg" },
      { sk: "tým", ua: "команда", ru: "команда", img: "/words_b1/tím.jpg" },
      { sk: "výkon", ua: "результат / виступ", ru: "результат / выступление", img: "/words_b1/výkon.jpg" },
      { sk: "zranění", ua: "травма", ru: "травма", img: "/words_b1/zranenie.jpg" },
    ],
  },
  {
    id: "b1-18",
    title: { ua: "Урок 18 — Географія", ru: "Урок 18 — География" },
    words: [
      { sk: "kontinent", ua: "континент", ru: "континент", img: "/words_b1/kontinent.jpg" },
      { sk: "hranice", ua: "кордон", ru: "граница", img: "/words_b1/hranica.jpg" },
      { sk: "obyvatelstvo", ua: "населення", ru: "население", img: "/words_b1/obyvateľstvo.jpg" },
      { sk: "podnebí", ua: "клімат", ru: "климат", img: "/words_b1/podnebie.jpg" },
      { sk: "hlavní město", ua: "столиця", ru: "столица", img: "/words_b1/hlavné mesto.jpg" },
      { sk: "povrch", ua: "поверхня", ru: "поверхность", img: "/words_b1/povrch.jpg" },
      { sk: "pobřeží", ua: "узбережжя", ru: "побережье", img: "/words_b1/pobrežie.jpg" },
      { sk: "ostrov", ua: "острів", ru: "остров", img: "/words_b1/ostrov.jpg" },
      { sk: "vnitrozemí", ua: "внутрішня територія", ru: "внутренняя территория", img: "/words_b1/vnútrozemie.jpg" },
      { sk: "zeměpis", ua: "географія", ru: "география", img: "/words_b1/zemepis.jpg" },
    ],
  },
  {
    id: "b1-19",
    title: { ua: "Урок 19 — Математика", ru: "Урок 19 — Математика" },
    words: [
      { sk: "rovnice", ua: "рівняння", ru: "уравнение", img: "/words_b1/rovnica.jpg" },
      { sk: "výsledek", ua: "результат", ru: "результат", img: "/words_b1_cz/výsledek.jpg" },
      { sk: "násobit", ua: "множити", ru: "умножать", img: "/words_b1/násobiť.jpg" },
      { sk: "dělit", ua: "ділити", ru: "делить", img: "/words_b1/deliť.jpg" },
      { sk: "odčíst", ua: "віднімати", ru: "вычитать", img: "/words_b1/odčítať.jpg" },
      { sk: "sečíst", ua: "додавати", ru: "складывать", img: "/words_b1/sčítať.jpg" },
      { sk: "zlomek", ua: "дріб", ru: "дробь", img: "/words_b1/zlomok.jpg" },
      { sk: "procento", ua: "відсоток", ru: "процент", img: "/words_b1/percento.jpg" },
      { sk: "graf", ua: "графік", ru: "график", img: "/words_b1/graf.jpg" },
      { sk: "vypočítat", ua: "обчислити", ru: "вычислить", img: "/words_b1/vypočítať.jpg" },
    ],
  },
  {
    id: "b1-20",
    title: { ua: "Урок 20 — Держава та суспільство", ru: "Урок 20 — Государство и общество" },
    words: [
      { sk: "zákon", ua: "закон", ru: "закон", img: "/words_b1/zákon.jpg" },
      { sk: "volby", ua: "вибори", ru: "выборы", img: "/words_b1/voľby.jpg" },
      { sk: "vláda", ua: "уряд", ru: "правительство", img: "/words_b1/vláda.jpg" },
      { sk: "občan", ua: "громадянин", ru: "гражданин", img: "/words_b1/občan.jpg" },
      { sk: "parlament", ua: "парламент", ru: "парламент", img: "/words_b1/parlament.jpg" },
      { sk: "prezident", ua: "президент", ru: "президент", img: "/words_b1/prezident.jpg" },
      { sk: "ústava", ua: "конституція", ru: "конституция", img: "/words_b1/ústava.jpg" },
      { sk: "ministerstvo", ua: "міністерство", ru: "министерство", img: "/words_b1/ministerstvo.jpg" },
      { sk: "referendum", ua: "референдум", ru: "референдум", img: "/words_b1/referendum.jpg" },
      { sk: "státní správa", ua: "державне управління", ru: "государственное управление", img: "/words_b1/štátna správa.jpg" },
    ],
  },
  {
    id: "b1-21",
    title: { ua: "Урок 21 — Країни", ru: "Урок 21 — Страны" },
    words: [
      { sk: "Slovensko", ua: "Словаччина", ru: "Словакия", img: "/words_b1/Slovensko.jpg" },
      { sk: "Česko", ua: "Чехія", ru: "Чехия", img: "/words_b1/Česko.jpg" },
      { sk: "Polsko", ua: "Польща", ru: "Польша", img: "/words_b1/Poľsko.jpg" },
      { sk: "Německo", ua: "Німеччина", ru: "Германия", img: "/words_b1/Nemecko.jpg" },
      { sk: "Rakousko", ua: "Австрія", ru: "Австрия", img: "/words_b1/Rakúsko.jpg" },
      { sk: "Maďarsko", ua: "Угорщина", ru: "Венгрия", img: "/words_b1/Maďarsko.jpg" },
      { sk: "Francie", ua: "Франція", ru: "Франция", img: "/words_b1/Francúzsko.jpg" },
      { sk: "Itálie", ua: "Італія", ru: "Италия", img: "/words_b1/Taliansko.jpg" },
      { sk: "Španělsko", ua: "Іспанія", ru: "Испания", img: "/words_b1/Španielsko.jpg" },
      { sk: "Ukrajina", ua: "Україна", ru: "Украина", img: "/words_b1/Ukrajina.jpg" },
    ],
  },
  {
    id: "b1-22",
    title: { ua: "Урок 22 — Медіа та інформація", ru: "Урок 22 — СМИ и информация" },
    words: [
      { sk: "tisk", ua: "преса", ru: "пресса", img: "/words_b1/tlač.jpg" },
      { sk: "noviny", ua: "газети", ru: "газеты", img: "/words_b1/noviny.jpg" },
      { sk: "televize", ua: "телебачення", ru: "телевидение", img: "/words_b1/televízia.jpg" },
      { sk: "rozhlas", ua: "радіо (офіц.)", ru: "радио", img: "/words_b1/rozhlas.jpg" },
      { sk: "vysílání", ua: "трансляція", ru: "вещание", img: "/words_b1/vysielanie.jpg" },
      { sk: "reklama", ua: "реклама", ru: "реклама", img: "/words_b1/reklama.jpg" },
      { sk: "redaktor", ua: "редактор / журналіст", ru: "редактор / журналист", img: "/words_b1/redaktor.jpg" },
      { sk: "titulek", ua: "заголовок", ru: "заголовок", img: "/words_b1/titulok.jpg" },
      { sk: "uvěřit", ua: "повірити", ru: "поверить", img: "/words_b1/uveriť.jpg" },
      { sk: "veřejné mínění", ua: "громадська думка", ru: "общественное мнение", img: "/words_b1/verejná myšlienka.jpg" },
    ],
  },
  {
    id: "b1-23",
    title: { ua: "Урок 23 — Інтернет та соцмережі", ru: "Урок 23 — Интернет и соцсети" },
    words: [
      { sk: "webová stránka", ua: "вебсайт", ru: "веб-сайт", img: "/words_b1/webová stránka.jpg" },
      { sk: "sledovatel", ua: "підписник", ru: "подписчик", img: "/words_b1/sledovateľ.jpg" },
      { sk: "online", ua: "онлайн", ru: "онлайн", img: "/words_b1/online.jpg" },
      { sk: "offline", ua: "офлайн", ru: "офлайн", img: "/words_b1/offline.jpg" },
      { sk: "profil", ua: "профіль", ru: "профиль", img: "/words_b1/profil.jpg" },
      { sk: "komentovat", ua: "коментувати", ru: "комментировать", img: "/words_b1/komentovať.jpg" },
      { sk: "označit", ua: "позначити / тегнути", ru: "отметить / тегнуть", img: "/words_b1/označiť.jpg" },
      { sk: "sdílet", ua: "поширювати", ru: "делиться", img: "/words_b1_cz/sdílet.jpg" },
      { sk: "zpráva", ua: "повідомлення", ru: "сообщение", img: "/words_b1_cz/zpráva.jpg" },
      { sk: "upozornění", ua: "сповіщення", ru: "уведомление", img: "/words_b1/upozornenie.jpg" },
    ],
  },
  {
    id: "b1-24",
    title: { ua: "Урок 24 — У гостях", ru: "Урок 24 — В гостях" },
    words: [
      { sk: "pozvání", ua: "запрошення", ru: "приглашение", img: "/words_b1/pozvanie.jpg" },
      { sk: "hostitel", ua: "господар", ru: "хозяин", img: "/words_b1/hostiteľ.jpg" },
      { sk: "host", ua: "гість", ru: "гость", img: "/words_b1/hosť.jpg" },
      { sk: "pohoštění ", ua: "частування", ru: "угощение", img: "/words_b1/pohostenie.jpg" },
      { sk: "přinést dárek", ua: "принести подарунок", ru: "принести подарок", img: "/words_b1/priniesť darček.jpg" },
      { sk: "slušnost", ua: "ввічливість", ru: "вежливость", img: "/words_b1/slušnosť.jpg" },
      { sk: "přivítat", ua: "привітати (зустріти)", ru: "поприветствовать (встретить)", img: "/words_b1/privítať.jpg" },
      { sk: "nabídnout", ua: "запропонувати (частування)", ru: "предложить (угощение)", img: "/words_b1/ponúknuť.jpg" },
      { sk: "poděkovat", ua: "подякувати", ru: "поблагодарить", img: "/words_b1/poďakovať sa.jpg" },
      { sk: "rozloučit se", ua: "попрощатися", ru: "попрощаться", img: "/words_b1/rozlúčiť sa.jpg" },
    ],
  },
  {
    id: "b1-25",
    title: { ua: "Урок 25 — Емоції та внутрішній стан", ru: "Урок 25 — Эмоции и внутреннее состояние" },
    words: [
      { sk: "zklamání", ua: "розчарування", ru: "разочарование", img: "/words_b1/sklamanie.jpg" },
      { sk: "hrdost", ua: "гордість", ru: "гордость", img: "/words_b1/hrdosť.jpg" },
      { sk: "úleva", ua: "полегшення", ru: "облегчение", img: "/words_b1/úľava.jpg" },
      { sk: "nejistota", ua: "невпевненість", ru: "неуверенность", img: "/words_b1/neistota.jpg" },
      { sk: "frustrace", ua: "фрустрація", ru: "фрустрация", img: "/words_b1/frustrácia.jpg" },
      { sk: "pochybnost", ua: "сумнів", ru: "сомнение", img: "/words_b1/pochybnosť.jpg" },
      { sk: "obava", ua: "побоювання", ru: "опасение", img: "/words_b1/obava.jpg" },
      { sk: "spokojenost", ua: "задоволення", ru: "удовлетворение", img: "/words_b1_cz/spokojenost.jpg" },
      { sk: "bezmocnost", ua: "безсилля", ru: "бессилие", img: "/words_b1/bezmocnosť.jpg" },
      { sk: "vyčerpání", ua: "виснаження", ru: "истощение", img: "/words_b1/vyčerpanie.jpg" },
    ],
  },
  {
    id: "b1-26",
    title: { ua: "Урок 26 — Суспільство та взаємини", ru: "Урок 26 — Общество и взаимоотношения" },
    words: [
      { sk: "porozumění", ua: "розуміння", ru: "понимание", img: "/words_b1/porozumenie.jpg" },
      { sk: "solidarita", ua: "солідарність", ru: "солидарность", img: "/words_b1/solidarita.jpg" },
      { sk: "konflikt", ua: "конфлікт", ru: "конфликт", img: "/words_b1/konflikt.jpg" },
      { sk: "předpojatost", ua: "упередження", ru: "предрассудок", img: "/words_b1/predsudok.jpg" },
      { sk: "rovnost", ua: "рівність", ru: "равенство", img: "/words_b1/rovnosť.jpg" },
      { sk: "tolerance", ua: "толерантність", ru: "толерантность", img: "/words_b1/tolerancia.jpg" },
      { sk: "diskriminace", ua: "дискримінація", ru: "дискриминация", img: "/words_b1/diskriminácia.jpg" },
      { sk: "spolužití", ua: "співжиття", ru: "сосуществование", img: "/words_b1/spolužitie.jpg" },
      { sk: "důvěra", ua: "довіра", ru: "доверие", img: "/words_b1/dôvera.jpg" },
      { sk: "kompromis", ua: "компроміс", ru: "компромисс", img: "/words_b1/kompromis.jpg" },
    ],
  },
  {
    id: "b1-27",
    title: { ua: "Урок 27 — Робота (безпека і правила)", ru: "Урок 27 — Работа (безопасность и правила)" },
    words: [
      { sk: "bezpečnost práce", ua: "охорона праці", ru: "охрана труда", img: "/words_b1/bezpečnosť práce.jpg" },
      { sk: "ochranné pomůcky", ua: "засоби захисту", ru: "средства защиты", img: "/words_b1/ochranné pomôcky.jpg" },
      { sk: "povinné", ua: "обов’язкове", ru: "обязательное", img: "/words_b1/povinné.jpg" },
      { sk: "zakázané", ua: "заборонене", ru: "запрещено", img: "/words_b1/zakázané.jpg" },
      { sk: "školení", ua: "інструктаж", ru: "инструктаж", img: "/words_b1/školenie.jpg" },
      { sk: "dodržovat", ua: "дотримуватися", ru: "соблюдать", img: "/words_b1/dodržiavať.jpg" },
      { sk: "pracovní úraz", ua: "виробнича травма", ru: "производственная травма", img: "/words_b1/pracovný úraz.jpg" },
      { sk: "bezpečnostní pravidla", ua: "правила безпеки", ru: "правила безопасности", img: "/words_b1/bezpečnostné pravidlá.jpg" },
      { sk: "dohled", ua: "нагляд", ru: "надзор", img: "/words_b1/dohľad.jpg" },
      { sk: "upozornění", ua: "попередження", ru: "предупреждение", img: "/words_b1_cz/upozornění.jpg" },
    ],
  },
  {
    id: "b1-28",
    title: { ua: "Урок 28 — Розповідь (послідовність)", ru: "Урок 28 — Рассказ (последовательность)" },
    words: [
      { sk: "nejprve", ua: "спочатку", ru: "сначала", img: "/words_b1/najprv.jpg" },
      { sk: "potom", ua: "потім", ru: "потом", img: "/words_b1/potom.jpg" },
      { sk: "následně", ua: "далі", ru: "затем", img: "/words_b1/následne.jpg" },
      { sk: "mezitím", ua: "тим часом", ru: "тем временем", img: "/words_b1/medzitým.jpg" },
      { sk: "nakonec", ua: "врешті", ru: "в конце", img: "/words_b1/nakoniec.jpg" },
      { sk: "najednou", ua: "раптом", ru: "вдруг", img: "/words_b1/zrazu.jpg" },
      { sk: "nakonec", ua: "зрештою", ru: "в итоге", img: "/words_b1/napokon.jpg" },
      { sk: "tehdy", ua: "тоді", ru: "тогда", img: "/words_b1/vtedy.jpg" },
      { sk: "od té doby", ua: "відтоді", ru: "с тех пор", img: "/words_b1/odvtedy.jpg" },
      { sk: "do té doby", ua: "до того времени", ru: "до того времени", img: "/words_b1/dovtedy.jpg" },
    ],
  },
  {
    id: "b1-29",
    title: { ua: "Урок 29 — Конфлікти (як говорити спокійно)", ru: "Урок 29 — Конфликты (как говорить спокойно)" },
    words: [
      { sk: "nepříjemné", ua: "неприємно", ru: "неприятно", img: "/words_b1/nepríjemné.jpg" },
      { sk: "urazit", ua: "образити", ru: "обидеть", img: "/words_b1/uraziť.jpg" },
      { sk: "kritizovat", ua: "критикувати", ru: "критиковать", img: "/words_b1/kritizovať.jpg" },
      { sk: "vyjádřit se", ua: "висловитися", ru: "высказаться", img: "/words_b1_cz/vyjádřit se.jpg" },
      { sk: "vysvětlení", ua: "пояснення", ru: "объяснение", img: "/words_b1_cz/vysvětlení.jpg" },
      { sk: "omluva", ua: "вибачення", ru: "извинение", img: "/words_b1/ospravedlnenie.jpg" },
      { sk: "pochopit", ua: "зрозуміти", ru: "понять", img: "/words_b1/pochopiť.jpg" },
      { sk: "zachovat klid", ua: "зберігати спокій", ru: "сохранять спокойствие", img: "/words_b1/zachovať pokoj.jpg" },
      { sk: "ustoupit", ua: "поступитися", ru: "уступить", img: "/words_b1/ustúpiť.jpg" },
      { sk: "urovnat", ua: "уладнати", ru: "уладить", img: "/words_b1/urovnať.jpg" },
    ],
  },
  {
    id: "b1-30",
    title: { ua: "Урок 30 — Мова (фрази для розмови)", ru: "Урок 30 — Язык (фразы для разговора)" },
    words: [
      { sk: "jestli tomu správně rozumím", ua: "якщо я правильно розумію", ru: "если я правильно понимаю", img: "/words_b1/ak tomu rozumiem správne.jpg" },
      { sk: "jinými slovy", ua: "іншими словами", ru: "другими словами", img: "/words_b1/inými slovami.jpg" },
      { sk: "na druhé straně", ua: "з іншого боку", ru: "с другой стороны", img: "/words_b1/na druhej strane.jpg" },
      { sk: "v každém případě", ua: "в будь-якому разі", ru: "в любом случае", img: "/words_b1/v každom prípade.jpg" },
      { sk: "záleží na tom", ua: "залежить від цього", ru: "это зависит", img: "/words_b1/záleží na tom.jpg" },
      { sk: "mám pocit, že", ua: "мені здається, що", ru: "мне кажется, что", img: "/words_b1/mám pocit, že.jpg" },
      { sk: "nevím přesně", ua: "не знаю точно", ru: "не знаю точно", img: "/words_b1/neviem presne.jpg" },
      { sk: "to dává smysl", ua: "це має сенс", ru: "это имеет смысл", img: "/words_b1/to dáva zmysel.jpg" },
      { sk: "to je zajímavé", ua: "це цікаво", ru: "это интересно", img: "/words_b1/to je zaujímavé.jpg" },
      { sk: "pojďme dál", ua: "йдемо далі", ru: "пойдём дальше", img: "/words_b1/poďme ďalej.jpg" },
    ],
  },
  {
    id: "b1-31",
    title: { ua: "Урок 31 — Країни (світ)", ru: "Урок 31 — Страны (мир)" },
    words: [
      { sk: "Spojené státy", ua: "США", ru: "США", img: "/words_b1/Spojené štáty.jpg" },
      { sk: "Velká Británie", ua: "Велика Британія", ru: "Великобритания", img: "/words_b1/Veľká Británia.jpg" },
      { sk: "Kanada", ua: "Канада", ru: "Канада", img: "/words_b1/Kanada.jpg" },
      { sk: "Švýcarsko", ua: "Швейцарія", ru: "Швейцария", img: "/words_b1/Švajčiarsko.jpg" },
      { sk: "Nizozemsko", ua: "Нідерланди", ru: "Нидерланды", img: "/words_b1/Holandsko.jpg" },
      { sk: "Belgie", ua: "Бельгія", ru: "Бельгия", img: "/words_b1/Belgicko.jpg" },
      { sk: "Švédsko", ua: "Швеція", ru: "Швеция", img: "/words_b1/Švédsko.jpg" },
      { sk: "Rusko", ua: "Росія", ru: "Россия", img: "/words_b1/Rusko.jpg" },
      { sk: "Rumunsko", ua: "Румунія", ru: "Румыния", img: "/words_b1/Rumunsko.jpg" },
      { sk: "Bulharsko", ua: "Болгарія", ru: "Болгария", img: "/words_b1/Bulharsko.jpg" },
    ],
  },
  {
    id: "b1-32",
    title: { ua: "Урок 32 — Релігія (Християнство)", ru: "Урок 32 — Религия (Христианство)" },
    words: [
      { sk: "křesťanství", ua: "християнство", ru: "христианство", img: "/words_b1/kresťanstvo.jpg" },
      { sk: "Bůh", ua: "Бог", ru: "Бог", img: "/words_b1/Boh.jpg" },
      { sk: "Ježíš Kristus", ua: "Ісус Христос", ru: "Иисус Христос", img: "/words_b1/Ježiš Kristus.jpg" },
      { sk: "Bible", ua: "Біблія", ru: "Библия", img: "/words_b1/Biblia.jpg" },
      { sk: "církev", ua: "церква", ru: "церковь", img: "/words_b1/cirkev.jpg" },
      { sk: "modlitba", ua: "молитва", ru: "молитва", img: "/words_b1/modlitba.jpg" },
      { sk: "víra", ua: "віра", ru: "вера", img: "/words_b1/viera.jpg" },
      { sk: "hřích", ua: "гріх", ru: "грех", img: "/words_b1/hriech.jpg" },
      { sk: "odpuštění", ua: "прощення", ru: "прощение", img: "/words_b1/odpustenie.jpg" },
      { sk: "věčný život", ua: "вічне життя", ru: "вечная жизнь", img: "/words_b1/večný život.jpg" },
    ],
  },
  {
    id: "b1-33",
    title: { ua: "Урок 33 — Мова (спілкування і думки)", ru: "Урок 33 — Язык (общение и мысли)" },
    words: [
      { sk: "dialog", ua: "діалог", ru: "диалог", img: "/words_b1/dialóg.jpg" },
      { sk: "tvrzení", ua: "твердження", ru: "утверждение", img: "/words_b1/tvrdenie.jpg" },
      { sk: "odstavec", ua: "абзац", ru: "абзац", img: "/words_b1/odsek.jpg" },
      { sk: "nadpis", ua: "заголовок", ru: "заголовок", img: "/words_b1/nadpis.jpg" },
      { sk: "citát", ua: "цитата", ru: "цитата", img: "/words_b1/citát.jpg" },
      { sk: "poznámka", ua: "примітка", ru: "заметка", img: "/words_b1/poznámka.jpg" },
      { sk: "zkratka", ua: "скорочення", ru: "сокращение", img: "/words_b1/skratka.jpg" },
      { sk: "pravopis", ua: "правопис", ru: "правописание", img: "/words_b1/pravopis.jpg" },
      { sk: "spojit slova", ua: "поєднати слова", ru: "соединить слова", img: "/words_b1/spojiť slová.jpg" },
      { sk: "vyslovit", ua: "вимовити", ru: "произнести", img: "/words_b1/vysloviť.jpg" },
    ],
  },
  {
    id: "b1-34",
    title: { ua: "Урок 34 — Психологія та внутрішній стан", ru: "Урок 34 — Психология и внутреннее состояние" },
    words: [
      { sk: "sebevědomí", ua: "самовпевненість", ru: "уверенность в себе", img: "/words_b1/sebavedomie.jpg" },
      { sk: "motivace", ua: "мотивація", ru: "мотивация", img: "/words_b1/motivácia.jpg" },
      { sk: "rozhodnost", ua: "рішучість", ru: "решительность", img: "/words_b1/rozhodnosť.jpg" },
      { sk: "být zklamaný", ua: "розчаруватися", ru: "разочароваться", img: "/words_b1/sklamať sa.jpg" },
      { sk: "překonat strach", ua: "подолати страх", ru: "преодолеть страх", img: "/words_b1/prekonať strach.jpg" },
      { sk: "seberozvoj", ua: "саморозвиток", ru: "саморазвитие", img: "/words_b1/sebarozvoj.jpg" },
      { sk: "vnitřní klid", ua: "внутрішній спокій", ru: "внутреннее спокойствие", img: "/words_b1/vnútorný pokoj.jpg" },
      { sk: "sebedisciplína", ua: "самодисципліна", ru: "самодисциплина", img: "/words_b1/sebadisciplína.jpg" },
      { sk: "odolnost", ua: "стійкість", ru: "устойчивость", img: "/words_b1/odolnosť.jpg" },
      { sk: "vyrovnat se s problémem", ua: "впоратися з проблемою", ru: "справиться с проблемой", img: "/words_b1/vyrovnať sa s problémom.jpg" },
    ],
  },
  {
    id: "b1-35",
    title: { ua: "Урок 35 — Столиці", ru: "Урок 35 — Столицы" },
    words: [
      { sk: "Kyjev", ua: "Київ", ru: "Киев", img: "/words_b1/Kyjev.jpg" },
      { sk: "Londýn", ua: "Лондон", ru: "Лондон", img: "/words_b1/Londýn.jpg" },
      { sk: "Ottawa", ua: "Оттава", ru: "Оттава", img: "/words_b1/Ottawa.jpg" },
      { sk: "Bern", ua: "Берн", ru: "Берн", img: "/words_b1/Bern.jpg" },
      { sk: "Amsterdam", ua: "Амстердам", ru: "Амстердам", img: "/words_b1/Amsterdam.jpg" },
      { sk: "Brusel", ua: "Брюссель", ru: "Брюссель", img: "/words_b1/Brusel.jpg" },
      { sk: "Štokholm", ua: "Стокгольм", ru: "Стокгольм", img: "/words_b1/Štokholm.jpg" },
      { sk: "Moskva", ua: "Москва", ru: "Москва", img: "/words_b1/Moskva.jpg" },
      { sk: "Bukurešť", ua: "Бухарест", ru: "Бухарест", img: "/words_b1/Bukurešť.jpg" },
      { sk: "Sofia", ua: "Софія", ru: "София", img: "/words_b1/Sofia.jpg" },
    ],
  },
];
