import type { Lesson } from "../data";

export const PL_A1_SOURCE: Lesson[] = [
  {
    id: "a1-1",
    title: { ua: "Урок 1 — Знайомство", ru: "Урок 1 — Знакомство", en: "Lesson 1 — Introduction" },
    words: [
      { sk: "nazywać się", ua: "називатися", ru: "называться", en: "to be called", hintUa: "називач шє", img: "/words_pl/nazywać się.jpg" },
      { sk: "poznać się", ua: "познайомитися", ru: "познакомиться", en: "to get acquainted", hintUa: "познач шє", img: "/words_a1/zoznámiť sa.jpg" },
      { sk: "imię", ua: "ім’я", ru: "имя", en: "name", hintUa: "ім’є", img: "/words_a1/meno.jpg" },
      { sk: "nazwisko", ua: "прізвище", ru: "фамилия", en: "surname", hintUa: "назвіско", img: "/words_pl/nazwisko.jpg" },
      { sk: "skąd", ua: "звідки", ru: "откуда", en: "from where", hintUa: "сконд", img: "/words_a1_cz/odkud.jpg" },
      { sk: "mieszkać", ua: "жити (мешкати)", ru: "жить (проживать)", en: "to live", hintUa: "мєшкач", img: "/words_a1_cz/bývat.jpg" },
      { sk: "pracować", ua: "працювати", ru: "работать", en: "to work", hintUa: "працовач", img: "/words_a1_cz/pracovat.jpg" },
      { sk: "miło mi", ua: "приємно познайомитись", ru: "приятно познакомиться", en: "nice to meet you", hintUa: "міво мі", img: "/words_pl/miło mi.jpg" },
      { sk: "lubić", ua: "подобатися", ru: "нравиться", en: "to like", hintUa: "любіч", img: "/words_pl/lubić.jpg" },
      { sk: "dziękuję", ua: "дякую", ru: "спасибо", en: "thank you", hintUa: "джєнькує", img: "/words_a1_cz/děkuji.jpg" },
    ],
  },
  {
    id: "a1-2",
    title: { ua: "Урок 2 — Ввічливі фрази", ru: "Урок 2 — Вежливые фразы", en: "Lesson 2 — Polite phrases" },
    words: [
      { sk: "proszę", ua: "будь ласка", ru: "пожалуйста", en: "please", hintUa: "проше", img: "/words_pl/proszę.jpg" },
      { sk: "przepraszam", ua: "вибачте", ru: "извините", en: "excuse me", hintUa: "пшепрашам", img: "/words_a1_cz/omlouvám se.jpg" },
      { sk: "dziękuję bardzo", ua: "дуже дякую", ru: "большое спасибо", en: "thank you very much", hintUa: "джєнькує бардзо", img: "/words_pl/dziękuję bardzo.jpg" },
      { sk: "nie ma za co", ua: "нема за що", ru: "не за что", en: "you're welcome", hintUa: "нє ма за цо", img: "/words_a1_cz/není zač.jpg" },
      { sk: "mogę", ua: "можна", ru: "можно", en: "may I", hintUa: "моге", img: "/words_a1_cz/mohu.jpg" },
      { sk: "możecie", ua: "можете", ru: "можете", en: "can you", hintUa: "можецє", img: "/words_a1_cz/můžete.jpg" },
      { sk: "proszę mi pomóc", ua: "допоможіть мені", ru: "помогите мне", en: "help me", hintUa: "проше мі помуц", img: "/words_a1_cz/pomozte mi.jpg" },
      { sk: "proszę bardzo", ua: "ось, тримай", ru: "вот, держите", en: "here you go", hintUa: "проше бардзо", img: "/words_a1_cz/tady máte.jpg" },
      { sk: "w porządku", ua: "в порядку", ru: "в порядке", en: "all right", hintUa: "в пожондку", img: "/words_a1_cz/v pořádku.jpg" },
      { sk: "jasne", ua: "ясно", ru: "ясно", en: "sure", hintUa: "ясне", img: "/words_a1/jasné.jpg" },
    ],
  },
  {
    id: "a1-3",
    title: { ua: "Урок 3 — Місто", ru: "Урок 3 — Город", en: "Lesson 3 — City" },
    words: [
      { sk: "skrzyżowanie", ua: "перехрестя", ru: "перекрёсток", en: "intersection", hintUa: "скшижованє", img: "/words_a1_cz/křižovatka.jpg" },
      { sk: "sygnalizacja świetlna", ua: "світлофор", ru: "светофор", en: "traffic light", hintUa: "сигналізація швєтльна", img: "/words_pl/sygnalizacja świetlna.jpg" },
      { sk: "most", ua: "міст", ru: "мост", en: "bridge", hintUa: "мост", img: "/words_a1/most.jpg" },
      { sk: "kino", ua: "кінотеатр", ru: "кинотеатр", en: "cinema", hintUa: "кіно", img: "/words_a1/kino.jpg" },
      { sk: "muzeum", ua: "музей", ru: "музей", en: "museum", hintUa: "музеум", img: "/words_a1_cz/muzeum.jpg" },
      { sk: "apteka", ua: "аптека", ru: "аптека", en: "pharmacy", hintUa: "аптека", img: "/words_pl/aptekaa.jpg" },
      { sk: "biblioteka", ua: "бібліотека", ru: "библиотека", en: "library", hintUa: "бібліотека", img: "/words_a1_cz/knihovna.jpg" },
      { sk: "rynek", ua: "ринок", ru: "рынок", en: "market", hintUa: "ринек", img: "/words_pl/rynek.jpg" },
      { sk: "wejście", ua: "вхід", ru: "вход", en: "entrance", hintUa: "вейшчє", img: "/words_pl/wejście.jpg" },
      { sk: "wyjście ewakuacyjne", ua: "аварійний вихід", ru: "аварийный выход", en: "emergency exit", hintUa: "вийшчє евакуацийне", img: "/words_pl/wyjście ewakuacyjne.jpg" },
    ],
  },
  {
    id: "a1-4",
    title: { ua: "Урок 4 — Магазин (розширено)", ru: "Урок 4 — Магазин (расширено)", en: "Lesson 4 — Shop (extended)" },
    words: [
      { sk: "kasjer", ua: "касир", ru: "кассир", en: "cashier", hintUa: "касєр", img: "/words_pl/kasjer.jpg" },
      { sk: "regał", ua: "стелаж", ru: "стеллаж", en: "shelf", hintUa: "реґау", img: "/words_a1/regál.jpg" },
      { sk: "dział", ua: "відділ", ru: "отдел", en: "department", hintUa: "джяу", img: "/words_pl/dział.jpg" },
      { sk: "rozmiar", ua: "розмір", ru: "размер", en: "size", hintUa: "розмяр", img: "/words_a1_cz/velikost.jpg" },
      { sk: "przymierzyć", ua: "приміряти", ru: "примерить", en: "to try", hintUa: "пшимєжич", img: "/words_a1_cz/zkusit.jpg" },
      { sk: "wymienić", ua: "обміняти", ru: "обменять", en: "to exchange", hintUa: "вимєніч", img: "/words_a1_cz/vyměnit.jpg" },
      { sk: "zwrócić", ua: "повернути (товар)", ru: "вернуть (товар)", en: "to return", hintUa: "звруціч", img: "/words_a1_cz/vrátit.jpg" },
      { sk: "gwarancja", ua: "гарантія", ru: "гарантия", en: "warranty", hintUa: "ґваранція", img: "/words_pl/gwarancja.jpg" },
      { sk: "opakowanie", ua: "упаковка", ru: "упаковка", en: "packaging", hintUa: "опакованє", img: "/words_a1_cz/balení.jpg" },
      { sk: "naliczać", ua: "рахувати (на касі)", ru: "пробивать (на кассе)", en: "to charge", hintUa: "налічач", img: "/words_pl/naliczać.jpg" },
    ],
  },
  {
    id: "a1-5",
    title: { ua: "Урок 5 — Їжа (у ресторані)", ru: "Урок 5 — Еда (в ресторане)", en: "Lesson 5 — Food (in a restaurant)" },
    words: [
      { sk: "zamówić", ua: "замовити", ru: "заказать", en: "to order", hintUa: "замувіч", img: "/words_a1_cz/objednat.jpg" },
      { sk: "porcja", ua: "порція", ru: "порция", en: "portion", hintUa: "порція", img: "/words_a1_cz/porce.jpg" },
      { sk: "dodatek", ua: "гарнір", ru: "гарнир", en: "side dish", hintUa: "додатек", img: "/words_a1_cz/příloha.jpg" },
      { sk: "deser", ua: "десерт", ru: "десерт", en: "dessert", hintUa: "десер", img: "/words_pl/deser.jpg" },
      { sk: "smaczny", ua: "смачний", ru: "вкусный", en: "tasty", hintUa: "смачни", img: "/words_pl/smaczny.jpg" },
      { sk: "głodny", ua: "голодний", ru: "голодный", en: "hungry", hintUa: "ґводни", img: "/words_a1_cz/hladový.jpg" },
      { sk: "spragniony", ua: "спраглий", ru: "жаждущий", en: "thirsty", hintUa: "спраґньони", img: "/words_a1_cz/žíznivý.jpg" },
      { sk: "naliczać", ua: "виставити рахунок", ru: "выставить счёт", en: "to bill", hintUa: "налічач", img: "/words_pl/naliczać.jpg" },
      { sk: "zapłacić", ua: "заплатити", ru: "заплатить", en: "to pay", hintUa: "запваціч", img: "/words_a1_cz/zaplatit.jpg" },
      { sk: "rezerwacja", ua: "бронювання", ru: "бронирование", en: "reservation", hintUa: "резервація", img: "/words_a1_cz/rezervace.jpg" },
    ],
  },
  {
    id: "a1-6",
    title: { ua: "Урок 6 — Транспорт", ru: "Урок 6 — Транспорт", en: "Lesson 6 — Transport" },
    words: [
      { sk: "rozkład jazdy", ua: "розклад", ru: "расписание", en: "timetable", hintUa: "розквад язди", img: "/words_pl/rozkład jazdy.jpg" },
      { sk: "przesiadka", ua: "пересадка", ru: "пересадка", en: "transfer", hintUa: "пшес’ядка", img: "/words_pl/przesiadka.jpg" },
      { sk: "peron", ua: "платформа", ru: "платформа", en: "platform", hintUa: "перон", img: "/words_pl/peron.jpg" },
      { sk: "spóźniać się", ua: "запізнюватися", ru: "опаздывать", en: "to be late", hintUa: "спузьняч шє", img: "/words_a1_cz/zpozdit se.jpg" },
      { sk: "wyjazd", ua: "відправлення", ru: "отправление", en: "departure", hintUa: "виязд", img: "/words_pl/wyjazd.jpg" },
      { sk: "przyjazd", ua: "прибуття", ru: "прибытие", en: "arrival", hintUa: "пшиязд", img: "/words_a1_cz/příchod.jpg" },
      { sk: "bilet", ua: "квиток", ru: "билет", en: "ticket", hintUa: "білет", img: "/words_a1_cz/lístek.jpg" },
      { sk: "kupić", ua: "купити", ru: "купить", en: "to buy", hintUa: "купіч", img: "/words_a1_cz/koupit.jpg" },
      { sk: "wysiąść", ua: "вийти (з транспорту)", ru: "выйти (из транспорта)", en: "to get off", hintUa: "висянсьць", img: "/words_a1_cz/vystoupit.jpg" },
      { sk: "wsiąść", ua: "сісти (в транспорт)", ru: "сесть (в транспорт)", en: "to get on", hintUa: "всянсьць", img: "/words_a1_cz/nastoupit.jpg" },
    ],
  },
  {
    id: "a1-7",
    title: { ua: "Урок 7 — Дім (побутові дії)", ru: "Урок 7 — Дом (бытовые действия)", en: "Lesson 7 — Home (household actions)" },
    words: [
      { sk: "gotować", ua: "готувати", ru: "готовить", en: "to cook", hintUa: "ґотовач", img: "/words_a1_cz/vařit.jpg" },
      { sk: "sprzątać", ua: "прибирати", ru: "прибираться", en: "to clean", hintUa: "спшонтач", img: "/words_a1_cz/uklízet.jpg" },
      { sk: "myć", ua: "мити", ru: "мыть", en: "to wash", hintUa: "мич", img: "/words_a1_cz/umývat.jpg" },
      { sk: "prać", ua: "прати", ru: "стирать", en: "to wash clothes", hintUa: "прач", img: "/words_a1_cz/prát.jpg" },
      { sk: "prasować", ua: "прасувати", ru: "гладить", en: "to iron", hintUa: "прасовач", img: "/words_a1_cz/žehlit.jpg" },
      { sk: "otworzyć", ua: "відкрити", ru: "открыть", en: "to open", hintUa: "отворжич", img: "/words_a1_cz/otevřít.jpg" },
      { sk: "zamknąć", ua: "закрити", ru: "закрыть", en: "to close", hintUa: "замкнонць", img: "/words_a1_cz/zavřít.jpg" },
      { sk: "włączyć", ua: "увімкнути", ru: "включить", en: "to turn on", hintUa: "ввоньчич", img: "/words_a1_cz/zapnout.jpg" },
      { sk: "wyłączyć", ua: "вимкнути", ru: "выключить", en: "to turn off", hintUa: "вивоньчич", img: "/words_a1_cz/vypnout.jpg" },
      { sk: "szukać", ua: "шукати", ru: "искать", en: "to look for", hintUa: "шукач", img: "/words_a1_cz/hledat.jpg" },
    ],
  },
  {
    id: "a1-8",
    title: { ua: "Урок 8 — Робота (процеси)", ru: "Урок 8 — Работа (процессы)", en: "Lesson 8 — Work (processes)" },
    words: [
      { sk: "miejsce pracy", ua: "робоче місце", ru: "рабочее место", en: "workplace", hintUa: "мєйсце праци", img: "/words_a1_cz/pracoviště.jpg" },
      { sk: "zmiana", ua: "зміна", ru: "смена", en: "shift", hintUa: "змяна", img: "/words_a1_cz/změna.jpg" },
      { sk: "nadgodziny", ua: "надурочно", ru: "сверхурочно", en: "overtime", hintUa: "надґоджини", img: "/words_a1_cz/přesčas.jpg" },
      { sk: "narada", ua: "нарада", ru: "совещание", en: "meeting", hintUa: "нарада", img: "/words_pl/narada.jpg" },
      { sk: "zadanie", ua: "завдання", ru: "задание", en: "task", hintUa: "заданє", img: "/words_pl/zadanie.jpg" },
      { sk: "gotowe", ua: "готово", ru: "готово", en: "done", hintUa: "ґотове", img: "/words_pl/gotowe.jpg" },
      { sk: "sprawdzić", ua: "перевірити", ru: "проверить", en: "to check", hintUa: "справджіч", img: "/words_a1_cz/zkontrolovat.jpg" },
      { sk: "naprawić", ua: "виправити", ru: "исправить", en: "fix", hintUa: "напправіч", img: "/words_a1_cz/opravit.jpg" },
      { sk: "zacząć", ua: "почати", ru: "начать", en: "to start", hintUa: "зачонць", img: "/words_a1_cz/začít.jpg" },
      { sk: "skończyć", ua: "закінчити", ru: "закончить", en: "to finish", hintUa: "сконьчич", img: "/words_a1_cz/skončit.jpg" },
    ],
  },
  {
    id: "a1-9",
    title: { ua: "Урок 9 — Емоції і стани", ru: "Урок 9 — Эмоции и состояния", en: "Lesson 9 — Emotions and states" },
    words: [
      { sk: "zmęczony", ua: "втомлений", ru: "уставший", en: "tired", hintUa: "зменчони", img: "/words_pl/zmęczony.jpg" },
      { sk: "szczęśliwy", ua: "щасливий", ru: "счастливый", en: "happy", hintUa: "щенсьліви", img: "/words_pl/szczęśliwy.jpg" },
      { sk: "smutny", ua: "сумний", ru: "грустный", en: "sad", hintUa: "смутни", img: "/words_a1/smutný.jpg" },
      { sk: "zdenerwowany", ua: "злий", ru: "злой", en: "angry", hintUa: "зденервовани", img: "/words_a1_cz/naštvaný.jpg" },
      { sk: "nerwowy", ua: "нервовий", ru: "нервный", en: "nervous", hintUa: "нервови", img: "/words_a1_cz/nervózní.jpg" },
      { sk: "spokojny", ua: "спокійний", ru: "спокойный", en: "calm", hintUa: "спокойни", img: "/words_pl/spokojny.jpg" },
      { sk: "zaskoczony", ua: "здивований", ru: "удивлённый", en: "surprised", hintUa: "заскочони", img: "/words_a1_cz/překvapený.jpg" },
      { sk: "bać się", ua: "боятися", ru: "бояться", en: "to be afraid", hintUa: "бач шє", img: "/words_a1_cz/bát se.jpg" },
      { sk: "cieszyć się", ua: "чекати з нетерпінням", ru: "ждать с нетерпением", en: "to look forward to", hintUa: "цєшич шє", img: "/words_a1_cz/těšit se.jpg" },
      { sk: "mieć ochotę", ua: "мати бажання", ru: "иметь желание", en: "to feel like", hintUa: "мєч охоте", img: "/words_a1_cz/mít chuť.jpg" },
    ],
  },
  {
    id: "a1-10",
    title: { ua: "Урок 10 — Запитання", ru: "Урок 10 — Вопросы", en: "Lesson 10 — Questions" },
    words: [
      { sk: "który", ua: "котрий", ru: "который", en: "which", hintUa: "ктури", img: "/words_a1_cz/který.jpg" },
      { sk: "jaki", ua: "який", ru: "какой", en: "what kind of", hintUa: "які", img: "/words_a1_cz/jaký.jpg" },
      { sk: "czyj", ua: "чий", ru: "чей", en: "whose", hintUa: "чий", img: "/words_pl/czyj.jpg" },
      { sk: "gdzie jest", ua: "де є...?", ru: "где...?", en: "where is", hintUa: "ґджє єст", img: "/words_pl/gdzie jest.jpg" },
      { sk: "ile to kosztuje", ua: "скільки це коштує?", ru: "сколько это стоит?", en: "how much does it cost", hintUa: "іле то коштує", img: "/words_pl/ile to kosztuje.jpg" },
      { sk: "czy możecie powtórzyć", ua: "можете повторити?", ru: "можете повторить?", en: "can you repeat", hintUa: "чи можецє повтуржич", img: "/words_a1_cz/můžete zopakovat.jpg" },
      { sk: "co to znaczy", ua: "що це означає?", ru: "что это значит?", en: "what does it mean", hintUa: "цо то значи", img: "/words_a1_cz/co to znamená.jpg" },
      { sk: "rozumiecie", ua: "розумієте?", ru: "понимаете?", en: "do you understand", hintUa: "розумєцє", img: "/words_pl/rozumiecie.jpg" },
      { sk: "oczywiście", ua: "звісно", ru: "конечно", en: "of course", hintUa: "очивісьцє", img: "/words_pl/oczywiście.jpg" },
      { sk: "nie wiem", ua: "не знаю", ru: "не знаю", en: "I don't know", hintUa: "нє вєм", img: "/words_a1_cz/nevím.jpg" },
    ],
  },
  {
    id: "a1-11",
    title: { ua: "Урок 11 — Опис людини", ru: "Урок 11 — Описание человека", en: "Lesson 11 — Describing a person" },
    words: [
      { sk: "wysoki", ua: "високий", ru: "высокий", en: "tall", hintUa: "високі", img: "/words_pl/wysoki.jpg" },
      { sk: "niski", ua: "низький", ru: "низкий", en: "short", hintUa: "ніскі", img: "/words_a1_cz/nízký.jpg" },
      { sk: "młody", ua: "молодий", ru: "молодой", en: "young", hintUa: "мводи", img: "/words_pl/młody.jpg" },
      { sk: "stary", ua: "старий", ru: "старый", en: "old", hintUa: "стари", img: "/words_a1/starý.jpg" },
      { sk: "silny", ua: "сильний", ru: "сильный", en: "strong", hintUa: "сільни", img: "/words_a1/silný.jpg" },
      { sk: "słaby", ua: "слабкий", ru: "слабый", en: "weak", hintUa: "сваби", img: "/words_pl/słaby.jpg" },
      { sk: "ładny", ua: "гарний", ru: "красивый", en: "pretty", hintUa: "вадни", img: "/words_a1_cz/hezký.jpg" },
      { sk: "brzydki", ua: "негарний", ru: "уродливый", en: "ugly", hintUa: "бжидкі", img: "/words_a1_cz/ošklivý.jpg" },
      { sk: "miły", ua: "милий", ru: "милый", en: "kind", hintUa: "міви", img: "/words_pl/miły.jpg" },
      { sk: "poważny", ua: "серйозний", ru: "серьёзный", en: "serious", hintUa: "поважни", img: "/words_a1_cz/vážný.jpg" },
    ],
  },
  {
    id: "a1-12",
    title: { ua: "Урок 12 — Час", ru: "Урок 12 — Время", en: "Lesson 12 — Time" },
    words: [
      { sk: "rano", ua: "ранок", ru: "утро", en: "morning", hintUa: "рано", img: "/words_a1/ráno.jpg" },
      { sk: "obiad", ua: "обід", ru: "обед", en: "lunch", hintUa: "об’яд", img: "/words_pl/obiad.jpg" },
      { sk: "wieczór", ua: "вечір", ru: "вечер", en: "evening", hintUa: "вєчур", img: "/words_pl/wieczór.jpg" },
      { sk: "północ", ua: "північ", ru: "полночь", en: "midnight", hintUa: "пувноц", img: "/words_a1_cz/půlnoc.jpg" },
      { sk: "dziś", ua: "сьогодні", ru: "сегодня", en: "today", hintUa: "джісь", img: "/words_pl/dziś.jpg" },
      { sk: "jutro", ua: "завтра", ru: "завтра", en: "tomorrow", hintUa: "ютро", img: "/words_a1_cz/zítra.jpg" },
      { sk: "pojutrze", ua: "післязавтра", ru: "послезавтра", en: "the day after tomorrow", hintUa: "поюче", img: "/words_a1_cz/pozítří.jpg" },
      { sk: "zawsze", ua: "завжди", ru: "всегда", en: "always", hintUa: "завше", img: "/words_pl/zawsze.jpg" },
      { sk: "często", ua: "часто", ru: "часто", en: "often", hintUa: "ченсто", img: "/words_pl/często.jpg" },
      { sk: "czasami", ua: "інколи", ru: "иногда", en: "sometimes", hintUa: "часамі", img: "/words_a1_cz/někdy.jpg" },
    ],
  },
  {
    id: "a1-13",
    title: { ua: "Урок 13 — Дім", ru: "Урок 13 — Дом", en: "Lesson 13 — Home" },
    words: [
      { sk: "korytarz", ua: "коридор", ru: "коридор", en: "hallway", hintUa: "коритаж", img: "/words_pl/korytarz.jpg" },
      { sk: "balkon", ua: "балкон", ru: "балкон", en: "balcony", hintUa: "балкон", img: "/words_a1/balkón.jpg" },
      { sk: "piwnica", ua: "підвал", ru: "подвал", en: "basement", hintUa: "півніца", img: "/words_a1_cz/sklep.jpg" },
      { sk: "winda", ua: "ліфт", ru: "лифт", en: "elevator", hintUa: "вінда", img: "/words_pl/winda.jpg" },
      { sk: "schody", ua: "сходи", ru: "лестница", en: "stairs", hintUa: "сходи", img: "/words_a1/schody.jpg" },
      { sk: "ogród", ua: "сад", ru: "сад", en: "garden", hintUa: "оґруд", img: "/words_a1_cz/zahrada.jpg" },
      { sk: "garaż", ua: "гараж", ru: "гараж", en: "garage", hintUa: "ґараж", img: "/words_a1/garáž.jpg" },
      { sk: "ściana", ua: "стіна", ru: "стена", en: "wall", hintUa: "сьцяна", img: "/words_a1_cz/zeď.jpg" },
      { sk: "sufit", ua: "стеля", ru: "потолок", en: "ceiling", hintUa: "суфіт", img: "/words_pl/sufit.jpg" },
      { sk: "podłoga", ua: "підлога", ru: "пол", en: "floor", hintUa: "подвоґа", img: "/words_pl/podłoga.jpg" },
    ],
  },
  {
    id: "a1-14",
    title: { ua: "Урок 14 — Покупки", ru: "Урок 14 — Покупки", en: "Lesson 14 — Shopping" },
    words: [
      { sk: "sprzedawać", ua: "продавати", ru: "продавать", en: "to sell", hintUa: "спшедавач", img: "/words_a1_cz/prodávat.jpg" },
      { sk: "kupować", ua: "купувати", ru: "покупать", en: "to buy", hintUa: "куповач", img: "/words_pl/kupować.jpg" },
      { sk: "tani", ua: "дешевий", ru: "дешёвый", en: "cheap", hintUa: "тані", img: "/words_a1_cz/levný.jpg" },
      { sk: "drogi", ua: "дорогий", ru: "дорогой", en: "expensive", hintUa: "дроґі", img: "/words_pl/drogi.jpg" },
      { sk: "jakość", ua: "якість", ru: "качество", en: "quality", hintUa: "якощч", img: "/words_pl/jakość.jpg" },
      { sk: "marka", ua: "бренд", ru: "бренд", en: "brand", hintUa: "марка", img: "/words_pl/marka.jpg" },
      { sk: "promocja", ua: "акція", ru: "акция", en: "sale", hintUa: "промоція", img: "/words_a1_cz/akce.jpg" },
      { sk: "przeceniony", ua: "зі знижкою", ru: "со скидкой", en: "discounted", hintUa: "пшеценьони", img: "/words_a1_cz/zlevněný.jpg" },
      { sk: "kasa", ua: "каса", ru: "касса", en: "cash desk", hintUa: "каса", img: "/words_a1_cz/pokladna.jpg" },
      { sk: "paragon", ua: "чек", ru: "чек", en: "receipt", hintUa: "параґон", img: "/words_a1_cz/účtenka.jpg" },
    ],
  },
  {
    id: "a1-15",
    title: { ua: "Урок 15 — Подорожі", ru: "Урок 15 — Путешествия", en: "Lesson 15 — Travel" },
    words: [
      { sk: "hotel", ua: "готель", ru: "отель", en: "hotel", hintUa: "хотел", img: "/words_a1/hotel.jpg" },
      { sk: "zakwaterowanie", ua: "проживання", ru: "проживание", en: "accommodation", hintUa: "закватерованє", img: "/words_a1_cz/ubytování.jpg" },
      { sk: "turysta", ua: "турист", ru: "турист", en: "tourist", hintUa: "туриста", img: "/words_pl/turysta.jpg" },
      { sk: "przewodnik", ua: "гід", ru: "гид", en: "guide", hintUa: "пшеводнік", img: "/words_a1_cz/průvodce.jpg" },
      { sk: "wycieczka", ua: "екскурсія", ru: "экскурсия", en: "excursion", hintUa: "вичєчка", img: "/words_a1_cz/exkurze.jpg" },
      { sk: "plaża", ua: "пляж", ru: "пляж", en: "beach", hintUa: "пляжа", img: "/words_pl/plaża.jpg" },
      { sk: "góry", ua: "гори", ru: "горы", en: "mountains", hintUa: "ґури", img: "/words_a1/hory.jpg" },
      { sk: "morze", ua: "море", ru: "море", en: "sea", hintUa: "може", img: "/words_a1_cz/moře.jpg" },
      { sk: "zarezerwować", ua: "бронювати", ru: "бронировать", en: "to reserve", hintUa: "зарезервовач", img: "/words_a1_cz/rezervovat.jpg" },
      { sk: "urlop", ua: "відпустка", ru: "отпуск", en: "vacation", hintUa: "урльоп", img: "/words_a1_cz/dovolená.jpg" },
    ],
  },
  {
    id: "a1-16",
    title: { ua: "Урок 16 — Здоровʼя", ru: "Урок 16 — Здоровье", en: "Lesson 16 — Health" },
    words: [
      { sk: "boleć", ua: "боліти", ru: "болеть", en: "to hurt", hintUa: "болеч", img: "/words_a1_cz/bolet.jpg" },
      { sk: "głowa", ua: "голова", ru: "голова", en: "head", hintUa: "ґвова", img: "/words_pl/głowa.jpg" },
      { sk: "ząb", ua: "зуб", ru: "зуб", en: "tooth", hintUa: "зомб", img: "/words_pl/ząb.jpg" },
      { sk: "żołądek", ua: "шлунок", ru: "желудок", en: "stomach", hintUa: "жовондек", img: "/words_a1_cz/žaludek.jpg" },
      { sk: "tabletka", ua: "таблетка", ru: "таблетка", en: "pill", hintUa: "таблетка", img: "/words_a1/tabletka.jpg" },
      { sk: "syrop", ua: "сироп", ru: "сироп", en: "syrup", hintUa: "сироп", img: "/words_pl/syrop.jpg" },
      { sk: "odpoczywać", ua: "відпочивати", ru: "отдыхать", en: "to rest", hintUa: "одпочивач", img: "/words_a1_cz/odpočívat.jpg" },
      { sk: "zdrowy", ua: "здоровий", ru: "здоровый", en: "healthy", hintUa: "здрови", img: "/words_pl/zdrowy.jpg" },
      { sk: "chory", ua: "хворий", ru: "больной", en: "ill", hintUa: "хори", img: "/words_a1/chorý.jpg" },
      { sk: "leczyć", ua: "лікувати", ru: "лечить", en: "to treat", hintUa: "лечич", img: "/words_a1_cz/léčit.jpg" },
    ],
  },
  {
    id: "a1-17",
    title: { ua: "Урок 17 — Робота (словник)", ru: "Урок 17 — Работа (словарь)", en: "Lesson 17 — Work vocabulary" },
    words: [
      { sk: "pracownik", ua: "працівник", ru: "сотрудник", en: "employee", hintUa: "працовнік", img: "/words_a1_cz/zaměstnanec.jpg" },
      { sk: "pracodawca", ua: "роботодавець", ru: "работодатель", en: "employer", hintUa: "працодавца", img: "/words_a1_cz/zaměstnavatel.jpg" },
      { sk: "wynagrodzenie", ua: "зарплата", ru: "зарплата", en: "salary", hintUa: "винаґродзенє", img: "/words_pl/wynagrodzenie.jpg" },
      { sk: "umowa o pracę", ua: "трудовий договір", ru: "трудовой договор", en: "employment contract", hintUa: "умова о праце", img: "/words_a1_cz/pracovní smlouva.jpg" },
      { sk: "praktyka", ua: "досвід роботи", ru: "опыт работы", en: "work experience", hintUa: "практика", img: "/words_a1_cz/praxe.jpg" },
      { sk: "kariera", ua: "карʼєра", ru: "карьера", en: "career", hintUa: "кар’єра", img: "/words_a1/kariéra.jpg" },
      { sk: "awans", ua: "підвищення", ru: "повышение", en: "promotion", hintUa: "аванс", img: "/words_a1_cz/povýšení.jpg" },
      { sk: "wypowiedzenie", ua: "звільнення", ru: "увольнение", en: "dismissal", hintUa: "виповєдзенє", img: "/words_a1_cz/výpověď.jpg" },
      { sk: "obowiązek", ua: "обовʼязок", ru: "обязанность", en: "duty", hintUa: "обовьонзек", img: "/words_a1_cz/povinnost.jpg" },
      { sk: "prawo", ua: "право", ru: "право", en: "right", hintUa: "право", img: "/words_pl/prawo.jpg" },
    ],
  },
  {
    id: "a1-18",
    title: { ua: "Урок 18 — Спілкування", ru: "Урок 18 — Общение", en: "Lesson 18 — Communication" },
    words: [
      { sk: "rozumieć", ua: "розуміти", ru: "понимать", en: "to understand", hintUa: "розумєч", img: "/words_a1_cz/rozumět.jpg" },
      { sk: "wyjaśnić", ua: "пояснити", ru: "объяснить", en: "to explain", hintUa: "виясьніч", img: "/words_a1_cz/vysvětlit.jpg" },
      { sk: "zapytać", ua: "запитати", ru: "спросить", en: "to ask", hintUa: "запитач", img: "/words_a1_cz/zeptat se.jpg" },
      { sk: "odpowiedź", ua: "відповідь", ru: "ответ", en: "answer", hintUa: "одповєдж", img: "/words_a1_cz/odpověď.jpg" },
      { sk: "opinia", ua: "думка", ru: "мнение", en: "opinion", hintUa: "опіня", img: "/words_pl/opinia.jpg" },
      { sk: "zgadzać się", ua: "погоджуватися", ru: "соглашаться", en: "to agree", hintUa: "зґадзач шє", img: "/words_a1_cz/souhlasit.jpg" },
      { sk: "nie zgadzać się", ua: "не погоджуватися", ru: "не соглашаться", en: "to disagree", hintUa: "нє зґадзач шє", img: "/words_a1_cz/nesouhlasit.jpg" },
      { sk: "dyskutować", ua: "обговорювати", ru: "обсуждать", en: "to discuss", hintUa: "дискутовач", img: "/words_a1_cz/diskutovat.jpg" },
      { sk: "rozmowa", ua: "розмова", ru: "разговор", en: "conversation", hintUa: "розмова", img: "/words_a1_cz/rozhovor.jpg" },
      { sk: "kontakt", ua: "контакт", ru: "контакт", en: "contact", hintUa: "контакт", img: "/words_a1/kontakt.jpg" },
    ],
  },
  {
    id: "a1-19",
    title: { ua: "Урок 19 — Технології", ru: "Урок 19 — Технологии", en: "Lesson 19 — Technology" },
    words: [
      { sk: "telefon komórkowy", ua: "мобільний телефон", ru: "мобильный телефон", en: "mobile phone", hintUa: "телефон комуркови", img: "/words_a1/mobil.jpg" },
      { sk: "ładowarka", ua: "зарядка", ru: "зарядное устройство", en: "charger", hintUa: "вадоварка", img: "/words_a1_cz/nabíječka.jpg" },
      { sk: "wiadomość", ua: "повідомлення", ru: "сообщение", en: "message", hintUa: "вядомощч", img: "/words_a1_cz/zpráva.jpg" },
      { sk: "rozmowa", ua: "дзвінок", ru: "звонок", en: "call", hintUa: "розмова", img: "/words_a1_cz/telefonát.jpg" },
      { sk: "internet", ua: "інтернет", ru: "интернет", en: "internet", hintUa: "інтернет", img: "/words_a1/internet.jpg" },
      { sk: "wifi", ua: "вайфай", ru: "вай-фай", en: "Wi-Fi", hintUa: "вайфай", img: "/words_a1/wifi.jpg" },
      { sk: "media społecznościowe", ua: "соціальні мережі", ru: "социальные сети", en: "social networks", hintUa: "медіа сповечносцьове", img: "/words_a1_cz/sociální sítě.jpg" },
      { sk: "profil", ua: "профіль", ru: "профиль", en: "profile", hintUa: "профіл", img: "/words_a1/profil.jpg" },
      { sk: "hasło", ua: "пароль", ru: "пароль", en: "password", hintUa: "хасво", img: "/words_pl/hasło.jpg" },
      { sk: "pobrać", ua: "завантажити", ru: "скачать", en: "to download", hintUa: "побрач", img: "/words_a1_cz/stáhnout.jpg" },
    ],
  },
  {
    id: "a1-20",
    title: { ua: "Урок 20 — Повсякденні дії", ru: "Урок 20 — Повседневные действия", en: "Lesson 20 — Everyday actions" },
    words: [
      { sk: "wstać", ua: "встати", ru: "встать", en: "to get up", hintUa: "встач", img: "/words_a1_cz/vstát.jpg" },
      { sk: "iść do pracy", ua: "йти на роботу", ru: "идти на работу", en: "to go to work", hintUa: "іщч до праци", img: "/words_a1_cz/jít do práce.jpg" },
      { sk: "robić zakupy", ua: "робити покупки", ru: "делать покупки", en: "to shop", hintUa: "робіч закупи", img: "/words_a1_cz/nakupovat.jpg" },
      { sk: "odpocząć", ua: "відпочити", ru: "отдохнуть", en: "to rest", hintUa: "одпочонць", img: "/words_a1_cz/odpočinout si.jpg" },
      { sk: "spotkać się", ua: "зустрітися", ru: "встретиться", en: "to meet", hintUa: "споткач шє", img: "/words_a1_cz/setkat se.jpg" },
      { sk: "telefonować", ua: "телефонувати", ru: "звонить", en: "to call", hintUa: "телефоноваць", img: "/words_a1_cz/telefonovat.jpg" },
      { sk: "gotować", ua: "готувати", ru: "готовить", en: "to cook", hintUa: "ґотовач", img: "/words_a1_cz/vařit.jpg" },
      { sk: "oglądać", ua: "дивитися", ru: "смотреть", en: "to watch", hintUa: "оґльондач", img: "/words_a1_cz/dívat se.jpg" },
      { sk: "czytać", ua: "читати", ru: "читать", en: "to read", hintUa: "читач", img: "/words_a1_cz/číst.jpg" },
      { sk: "spać", ua: "спати", ru: "спать", en: "to sleep", hintUa: "спач", img: "/words_a1_cz/spát.jpg" },
    ],
  },
  {
    id: "a1-21",
    title: { ua: "Урок 21 — Проблеми і ситуації", ru: "Урок 21 — Проблемы и ситуации", en: "Lesson 21 — Problems and situations" },
    words: [
      { sk: "problem", ua: "проблема", ru: "проблема", en: "problem", hintUa: "проблем", img: "/words_a1/problém.jpg" },
      { sk: "zepsuty", ua: "зламаний", ru: "сломанный", en: "broken", hintUa: "зепсути", img: "/words_pl/zepsuty.jpg" },
      { sk: "stracić", ua: "загубити", ru: "потерять", en: "to lose", hintUa: "страціч", img: "/words_a1_cz/ztratit.jpg" },
      { sk: "znaleźć", ua: "знайти", ru: "найти", en: "to find", hintUa: "зналєщч", img: "/words_a1_cz/najít.jpg" },
      { sk: "spóźniać się", ua: "запізнюватися", ru: "опаздывать", en: "to be late", hintUa: "спузьняч шє", img: "/words_a1_cz/zpozdit se.jpg" },
      { sk: "zapomnieć", ua: "забути", ru: "забыть", en: "to forget", hintUa: "запомнєч", img: "/words_a1_cz/zapomenout.jpg" },
      { sk: "błąd", ua: "помилка", ru: "ошибка", en: "mistake", hintUa: "бвонд", img: "/words_pl/błąd.jpg" },
      { sk: "naprawa", ua: "ремонт", ru: "ремонт", en: "repair", hintUa: "направа", img: "/words_pl/naprawa.jpg" },
      { sk: "pomoc", ua: "допомога", ru: "помощь", en: "help", hintUa: "помоц", img: "/words_a1/pomoc.jpg" },
      { sk: "rozwiązanie", ua: "рішення", ru: "решение", en: "solution", hintUa: "розвьонзанє", img: "/words_a1_cz/řešení.jpg" },
    ],
  },
  {
    id: "a1-22",
    title: { ua: "Урок 22 — Напрямки", ru: "Урок 22 — Направления", en: "Lesson 22 — Directions" },
    words: [
      { sk: "w prawo", ua: "праворуч", ru: "направо", en: "to the right", hintUa: "в право", img: "/words_pl/w prawo.jpg" },
      { sk: "w lewo", ua: "ліворуч", ru: "налево", en: "to the left", hintUa: "в лєво", img: "/words_a1_cz/vlevo.jpg" },
      { sk: "prosto", ua: "прямо", ru: "прямо", en: "straight", hintUa: "просто", img: "/words_pl/prosto.jpg" },
      { sk: "blisko", ua: "близько", ru: "близко", en: "near", hintUa: "бліско", img: "/words_pl/blisko.jpg" },
      { sk: "daleko", ua: "далеко", ru: "далеко", en: "far", hintUa: "далеко", img: "/words_a1_cz/daleko.jpg" },
      { sk: "na górze", ua: "вгору", ru: "вверх", en: "up", hintUa: "на ґуже", img: "/words_a1_cz/nahoru.jpg" },
      { sk: "na dole", ua: "вниз", ru: "вниз", en: "down", hintUa: "на долє", img: "/words_a1/dole.jpg" },
      { sk: "przed", ua: "перед", ru: "перед", en: "in front of", hintUa: "пшед", img: "/words_a1_cz/před.jpg" },
      { sk: "za", ua: "за", ru: "за", en: "behind", hintUa: "за", img: "/words_a1/za.jpg" },
      { sk: "między", ua: "між", ru: "между", en: "between", hintUa: "мєндзи", img: "/words_a1_cz/mezi.jpg" },
    ],
  },
  {
    id: "a1-23",
    title: { ua: "Урок 23 — Характер", ru: "Урок 23 — Характер", en: "Lesson 23 — Character" },
    words: [
      { sk: "dobry", ua: "добрий", ru: "добрый", en: "good", hintUa: "добри", img: "/words_a1/dobrý.jpg" },
      { sk: "zły", ua: "поганий", ru: "плохой", en: "bad", hintUa: "зви", img: "/words_a1_cz/špatný.jpg" },
      { sk: "cierpliwy", ua: "терплячий", ru: "терпеливый", en: "patient", hintUa: "цєрпліви", img: "/words_a1_cz/trpělivý.jpg" },
      { sk: "leniwy", ua: "ледачий", ru: "ленивый", en: "lazy", hintUa: "лєніви", img: "/words_pl/leniwy.jpg" },
      { sk: "pracowity", ua: "працьовитий", ru: "трудолюбивый", en: "hard-working", hintUa: "працовіти", img: "/words_pl/pracowity.jpg" },
      { sk: "szczery", ua: "щирий", ru: "искренний", en: "sincere", hintUa: "щери", img: "/words_a1_cz/upřímný.jpg" },
      { sk: "przyjazny", ua: "дружній", ru: "дружелюбный", en: "friendly", hintUa: "пшиязни", img: "/words_a1_cz/přátelský.jpg" },
      { sk: "poważny", ua: "серйозний", ru: "серьёзный", en: "serious", hintUa: "поважни", img: "/words_a1_cz/vážný.jpg" },
      { sk: "zabawny", ua: "веселий", ru: "весёлый", en: "funny", hintUa: "забавни", img: "/words_pl/zabawny.jpg" },
      { sk: "cichy", ua: "тихий", ru: "тихий", en: "quiet", hintUa: "чіхи", img: "/words_pl/cichy.jpg" },
    ],
  },
  {
    id: "a1-24",
    title: { ua: "Урок 24 — Погода (розширено)", ru: "Урок 24 — Погода (расширено)", en: "Lesson 24 — Weather (extended)" },
    words: [
      { sk: "ciepło", ua: "тепло", ru: "тепло", en: "warm", hintUa: "цєпво", img: "/words_pl/ciepło.jpg" },
      { sk: "zimno", ua: "холодно", ru: "холодно", en: "cold", hintUa: "зімно", img: "/words_pl/zimno.jpg" },
      { sk: "pochmurno", ua: "хмарно", ru: "облачно", en: "cloudy", hintUa: "похмурно", img: "/words_pl/pochmurno.jpg" },
      { sk: "jasno", ua: "ясно", ru: "ясно", en: "clear", hintUa: "ясно", img: "/words_a1/jasno.jpg" },
      { sk: "padać deszcz", ua: "йде дощ", ru: "идёт дождь", en: "to rain", hintUa: "падач дешч", img: "/words_a1_cz/pršet.jpg" },
      { sk: "padać śnieg", ua: "йде сніг", ru: "идёт снег", en: "to snow", hintUa: "падач сьнєґ", img: "/words_a1_cz/sněžit.jpg" },
      { sk: "wiatr", ua: "вітер", ru: "ветер", en: "wind", hintUa: "вятр", img: "/words_a1_cz/vítr.jpg" },
      { sk: "mróz", ua: "мороз", ru: "мороз", en: "frost", hintUa: "мруз", img: "/words_pl/mróz.jpg" },
      { sk: "burza", ua: "буря", ru: "буря", en: "storm", hintUa: "бужа", img: "/words_a1_cz/bouře.jpg" },
      { sk: "prognoza", ua: "прогноз", ru: "прогноз", en: "forecast", hintUa: "проґноза", img: "/words_a1_cz/předpověď.jpg" },
    ],
  },
  {
    id: "a1-25",
    title: { ua: "Урок 25 — Їжа (розширено)", ru: "Урок 25 — Еда (расширено)", en: "Lesson 25 — Food (extended)" },
    words: [
      { sk: "śniadanie", ua: "сніданок", ru: "завтрак", en: "breakfast", hintUa: "сьняданє", img: "/words_a1_cz/snídaně.jpg" },
      { sk: "obiad", ua: "обід", ru: "обед", en: "lunch", hintUa: "об’яд", img: "/words_a1_cz/oběd.jpg" },
      { sk: "kolacja", ua: "вечеря", ru: "ужин", en: "dinner", hintUa: "колація", img: "/words_a1_cz/večeře.jpg" },
      { sk: "słodki", ua: "солодкий", ru: "сладкий", en: "sweet", hintUa: "сводкі", img: "/words_pl/słodki.jpg" },
      { sk: "słony", ua: "солоний", ru: "солёный", en: "salty", hintUa: "свони", img: "/words_pl/słony.jpg" },
      { sk: "pikantny", ua: "гострий", ru: "острый", en: "spicy", hintUa: "пікантни", img: "/words_a1_cz/pikantní.jpg" },
      { sk: "świeży", ua: "свіжий", ru: "свежий", en: "fresh", hintUa: "швєжи", img: "/words_pl/świeży.jpg" },
      { sk: "głód", ua: "голод", ru: "голод", en: "hunger", hintUa: "ґвуд", img: "/words_pl/głód.jpg" },
      { sk: "pragnienie", ua: "спрага", ru: "жажда", en: "thirst", hintUa: "праґнєнє", img: "/words_a1_cz/žízeň.jpg" },
      { sk: "smak", ua: "смак", ru: "вкус", en: "taste", hintUa: "смак", img: "/words_pl/smak.jpg" },
    ],
  },
  {
    id: "a1-26",
    title: { ua: "Урок 26 — Гроші (розширено)", ru: "Урок 26 — Деньги (расширено)", en: "Lesson 26 — Money (extended)" },
    words: [
      { sk: "płacić", ua: "платити", ru: "платить", en: "to pay", hintUa: "пваціч", img: "/words_a1_cz/platit.jpg" },
      { sk: "zaoszczędzić", ua: "зекономити", ru: "сэкономить", en: "to save", hintUa: "заощенджіч", img: "/words_a1_cz/ušetřit.jpg" },
      { sk: "wydać", ua: "витратити", ru: "потратить", en: "to spend", hintUa: "видач", img: "/words_a1_cz/minout.jpg" },
      { sk: "wypłata", ua: "зарплата", ru: "зарплата", en: "salary", hintUa: "випвата", img: "/words_pl/wypłata.jpg" },
      { sk: "kredyt", ua: "кредит", ru: "кредит", en: "loan", hintUa: "кредит", img: "/words_a1_cz/úvěr.jpg" },
      { sk: "dług", ua: "борг", ru: "долг", en: "debt", hintUa: "двуґ", img: "/words_a1_cz/dluh.jpg" },
      { sk: "bankomat", ua: "банкомат", ru: "банкомат", en: "ATM", hintUa: "банкомат", img: "/words_a1/bankomat.jpg" },
      { sk: "konto", ua: "рахунок", ru: "счёт", en: "account", hintUa: "конто", img: "/words_pl/rachunek.jpg" },
      { sk: "dochód", ua: "дохід", ru: "доход", en: "income", hintUa: "доход", img: "/words_a1_cz/příjem.jpg" },
      { sk: "wydatek", ua: "витрата", ru: "расход", en: "expense", hintUa: "видатек", img: "/words_a1_cz/výdaje.jpg" },
    ],
  },
  {
    id: "a1-27",
    title: { ua: "Урок 27 — Технології (практика)", ru: "Урок 27 — Технологии (практика)", en: "Lesson 27 — Technology (practice)" },
    words: [
      { sk: "włączyć", ua: "увімкнути", ru: "включить", en: "to turn on", hintUa: "ввоньчич", img: "/words_a1_cz/zapnout.jpg" },
      { sk: "wyłączyć", ua: "вимкнути", ru: "выключить", en: "to turn off", hintUa: "вивоньчич", img: "/words_a1_cz/vypnout.jpg" },
      { sk: "ładować", ua: "заряджати", ru: "заряжать", en: "to charge", hintUa: "вадовач", img: "/words_a1_cz/nabíjet.jpg" },
      { sk: "zalogować się", ua: "увійти", ru: "войти", en: "to log in", hintUa: "залоґовач шє", img: "/words_a1_cz/přihlásit se.jpg" },
      { sk: "wylogować się", ua: "вийти", ru: "выйти", en: "to log out", hintUa: "вилоґовач шє", img: "/words_a1_cz/odhlásit se.jpg" },
      { sk: "pobrać", ua: "завантажити", ru: "скачать", en: "to download", hintUa: "побрач", img: "/words_a1_cz/stáhnout.jpg" },
      { sk: "zapisać", ua: "зберегти", ru: "сохранить", en: "to save", hintUa: "запісач", img: "/words_a1/uložiť.jpg" },
      { sk: "usunąć", ua: "видалити", ru: "удалить", en: "to delete", hintUa: "усунȯнч", img: "/words_a1_cz/vymazat.jpg" },
      { sk: "kliknąć", ua: "натиснути", ru: "кликнуть", en: "to click", hintUa: "клікнонч", img: "/words_a1_cz/kliknout.jpg" },
      { sk: "ustawienia", ua: "налаштування", ru: "настройки", en: "settings", hintUa: "уставєня", img: "/words_a1_cz/nastavení.jpg" },
    ],
  },
  {
    id: "a1-28",
    title: { ua: "Урок 28 — Подорожі (ситуації)", ru: "Урок 28 — Путешествия (ситуации)", en: "Lesson 28 — Travel (situations)" },
    words: [
      { sk: "lot", ua: "рейс", ru: "рейс", en: "flight", hintUa: "лот", img: "/words_pl/lot.jpg" },
      { sk: "spóźnienie", ua: "затримка", ru: "задержка", en: "delay", hintUa: "спузьнєнє", img: "/words_a1_cz/zpoždění.jpg" },
      { sk: "odlot", ua: "виліт", ru: "вылет", en: "departure", hintUa: "одлот", img: "/words_pl/odlot.jpg" },
      { sk: "przylot", ua: "приліт", ru: "прилёт", en: "arrival", hintUa: "пшилот", img: "/words_a1_cz/přílet.jpg" },
      { sk: "kontrola paszportowa", ua: "паспортний контроль", ru: "паспортный контроль", en: "passport control", hintUa: "контрола пашпортова", img: "/words_pl/kontrola paszportowa.jpg" },
      { sk: "bagaż", ua: "багаж", ru: "багаж", en: "luggage", hintUa: "баґаж", img: "/words_a1_cz/zavazadlo.jpg" },
      { sk: "rezerwacja", ua: "бронювання", ru: "бронирование", en: "reservation", hintUa: "резервація", img: "/words_a1_cz/rezervace.jpg" },
      { sk: "przewodnik", ua: "гід", ru: "гид", en: "guide", hintUa: "пшеводнік", img: "/words_a1_cz/průvodce.jpg" },
      { sk: "mapa", ua: "карта", ru: "карта", en: "map", hintUa: "мапа", img: "/words_a1/mapa.jpg" },
      { sk: "cel", ua: "ціль", ru: "цель", en: "goal", hintUa: "цель", img: "/words_a1_cz/cíl.jpg" },
    ],
  },
  {
    id: "a1-29",
    title: { ua: "Урок 29 — Робочі фрази", ru: "Урок 29 — Рабочие фразы", en: "Lesson 29 — Work phrases" },
    words: [
      { sk: "rozumiem", ua: "розумію", ru: "понимаю", en: "I understand", hintUa: "розумєм", img: "/words_a1_cz/rozumím.jpg" },
      { sk: "nie rozumiem", ua: "не розумію", ru: "не понимаю", en: "I don't understand", hintUa: "нє розумєм", img: "/words_a1_cz/nerozumím.jpg" },
      { sk: "gotowe", ua: "готово", ru: "готово", en: "done", hintUa: "ґотове", img: "/words_pl/gotowe.jpg" },
      { sk: "mogę", ua: "можна", ru: "можно", en: "may I", hintUa: "моґе", img: "/words_a1_cz/mohu.jpg" },
      { sk: "potrzebuję", ua: "потрібно", ru: "мне нужно", en: "I need", hintUa: "потшебує", img: "/words_a1_cz/potřebuji.jpg" },
      { sk: "problem", ua: "проблема", ru: "проблема", en: "problem", hintUa: "проблем", img: "/words_a1/problém.jpg" },
      { sk: "w porządku", ua: "в порядку", ru: "в порядке", en: "all right", hintUa: "в пожондку", img: "/words_a1_cz/v pořádku.jpg" },
      { sk: "od razu", ua: "зараз", ru: "сразу", en: "right away", hintUa: "од разу", img: "/words_a1_cz/hned.jpg" },
      { sk: "później", ua: "пізніше", ru: "позже", en: "later", hintUa: "пузьнєй", img: "/words_a1_cz/později.jpg" },
      { sk: "umówić się", ua: "домовитись", ru: "договориться", en: "arrange", hintUa: "умувіч шє", img: "/words_a1_cz/dohodnout se.jpg" },
    ],
  },
  {
    id: "a1-30",
    title: { ua: "Урок 30 — Часті дієслова", ru: "Урок 30 — Частые глаголы", en: "Lesson 30 — Common verbs" },
    words: [
      { sk: "mieć", ua: "мати", ru: "иметь", en: "to have", hintUa: "мєч", img: "/words_a1_cz/mít.jpg" },
      { sk: "być", ua: "бути", ru: "быть", en: "to be", hintUa: "бич", img: "/words_pl/być.jpg" },
      { sk: "robić", ua: "робити", ru: "делать", en: "to do", hintUa: "робіч", img: "/words_a1_cz/dělat.jpg" },
      { sk: "iść", ua: "йти", ru: "идти", en: "to go", hintUa: "іщч", img: "/words_a1_cz/jít.jpg" },
      { sk: "widzieć", ua: "бачити", ru: "видеть", en: "to see", hintUa: "відзєч", img: "/words_a1_cz/vidět.jpg" },
      { sk: "słuchać", ua: "слухати", ru: "слушать", en: "to listen", hintUa: "свухач", img: "/words_a1_cz/poslouchat.jpg" },
      { sk: "mówić", ua: "говорити", ru: "говорить", en: "to speak", hintUa: "мувіч", img: "/words_a1_cz/mluvit.jpg" },
      { sk: "myśleć", ua: "думати", ru: "думать", en: "to think", hintUa: "мишлєч", img: "/words_a1_cz/myslet.jpg" },
      { sk: "chcieć", ua: "хотіти", ru: "хотеть", en: "to want", hintUa: "хцєч", img: "/words_a1_cz/chtít.jpg" },
      { sk: "móc", ua: "могти", ru: "мочь", en: "to be able to", hintUa: "муц", img: "/words_a1_cz/moci.jpg" },
    ],
  },
  {
    id: "a1-31",
    title: { ua: "Урок 31 — Почуття", ru: "Урок 31 — Чувства", en: "Lesson 31 — Feelings" },
    words: [
      { sk: "radość", ua: "радість", ru: "радость", en: "joy", hintUa: "радощч", img: "/words_a1_cz/radost.jpg" },
      { sk: "smutek", ua: "смуток", ru: "грусть", en: "sadness", hintUa: "смутек", img: "/words_a1_cz/smutek.jpg" },
      { sk: "strach", ua: "страх", ru: "страх", en: "fear", hintUa: "страх", img: "/words_a1/strach.jpg" },
      { sk: "gniew", ua: "злість", ru: "злость", en: "anger", hintUa: "ґнєв", img: "/words_a1_cz/hněv.jpg" },
      { sk: "miłość", ua: "любов", ru: "любовь", en: "love", hintUa: "мівощч", img: "/words_pl/miłość.jpg" },
      { sk: "zmęczenie", ua: "втома", ru: "усталость", en: "tiredness", hintUa: "зменченє", img: "/words_pl/zmęczenie.jpg" },
      { sk: "stres", ua: "стрес", ru: "стресс", en: "stress", hintUa: "стрес", img: "/words_a1/stres.jpg" },
      { sk: "spokój", ua: "спокій", ru: "спокойствие", en: "calm", hintUa: "спокуй", img: "/words_pl/spokój.jpg" },
      { sk: "zaskoczenie", ua: "здивування", ru: "удивление", en: "surprise", hintUa: "заскоченє", img: "/words_a1_cz/překvapení.jpg" },
      { sk: "entuzjazm", ua: "захоплення", ru: "воодушевление", en: "enthusiasm", hintUa: "ентузязм", img: "/words_a1_cz/nadšení.jpg" },
    ],
  },
  {
    id: "a1-32",
    title: { ua: "Урок 32 — Опис речей", ru: "Урок 32 — Описание вещей", en: "Lesson 32 — Describing things" },
    words: [
      { sk: "nowy", ua: "новий", ru: "новый", en: "new", hintUa: "нови", img: "/words_pl/nowy.jpg" },
      { sk: "stary", ua: "старий", ru: "старый", en: "old", hintUa: "стари", img: "/words_a1/starý.jpg" },
      { sk: "duży", ua: "великий", ru: "большой", en: "big", hintUa: "дужи", img: "/words_pl/duży.jpg" },
      { sk: "mały", ua: "малий", ru: "маленький", en: "small", hintUa: "мави", img: "/words_a1/malý.jpg" },
      { sk: "ciężki", ua: "важкий", ru: "тяжёлый", en: "heavy", hintUa: "цєнжкі", img: "/words_a1_cz/těžký.jpg" },
      { sk: "lekki", ua: "легкий", ru: "лёгкий", en: "light", hintUa: "леккі", img: "/words_a1/ľahký.jpg" },
      { sk: "szybki", ua: "швидкий", ru: "быстрый", en: "fast", hintUa: "шибкі", img: "/words_a1_cz/rychlý.jpg" },
      { sk: "wolny", ua: "повільний", ru: "медленный", en: "slow", hintUa: "вольни", img: "/words_pl/wolny.jpg" },
      { sk: "drogi", ua: "дорогий", ru: "дорогой", en: "expensive", hintUa: "дроґі", img: "/words_pl/drogi.jpg" },
      { sk: "tani", ua: "дешевий", ru: "дешёвый", en: "cheap", hintUa: "тані", img: "/words_a1_cz/levný.jpg" },
    ],
  },
  {
    id: "a1-33",
    title: { ua: "Урок 33 — Дім (дії)", ru: "Урок 33 — Дом (действия)", en: "Lesson 33 — Home (actions)" },
    words: [
      { sk: "gotować", ua: "готувати", ru: "готовить", en: "to cook", hintUa: "ґотовач", img: "/words_a1_cz/vařit.jpg" },
      { sk: "odkurzać", ua: "пилососити", ru: "пылесосить", en: "to vacuum", hintUa: "одкужач", img: "/words_a1_cz/vysávat.jpg" },
      { sk: "umyć", ua: "помити", ru: "помыть", en: "to wash", hintUa: "умич", img: "/words_pl/umyć.jpg" },
      { sk: "zamknąć", ua: "закрити", ru: "закрыть", en: "to close", hintUa: "замкнонч", img: "/words_a1_cz/zavřít.jpg" },
      { sk: "naprawić", ua: "відремонтувати", ru: "отремонтировать", en: "to repair", hintUa: "напправіч", img: "/words_a1_cz/opravit.jpg" },
      { sk: "zbudować", ua: "побудувати", ru: "построить", en: "to build", hintUa: "збудовач", img: "/words_a1_cz/postavit.jpg" },
      { sk: "przeprowadzić się", ua: "переїхати", ru: "переехать", en: "to move", hintUa: "пшепроваджіч шє", img: "/words_a1_cz/přestěhovat se.jpg" },
      { sk: "powiesić", ua: "повісити", ru: "повесить", en: "to hang", hintUa: "повєсіч", img: "/words_a1_cz/zavěsit.jpg" },
      { sk: "złożyć", ua: "скласти", ru: "сложить", en: "to fold", hintUa: "звожич", img: "/words_a1_cz/poskládat.jpg" },
      { sk: "urządzić", ua: "облаштувати", ru: "обустроить", en: "to furnish", hintUa: "ужонджіч", img: "/words_a1_cz/zařídit.jpg" },
    ],
  },
  {
    id: "a1-34",
    title: { ua: "Урок 34 — Комунікація", ru: "Урок 34 — Коммуникация", en: "Lesson 34 — Communication" },
    words: [
      { sk: "opisać", ua: "описати", ru: "описать", en: "to describe", hintUa: "опісач", img: "/words_a1_cz/opsat.jpg" },
      { sk: "zaproponować", ua: "запропонувати", ru: "предложить", en: "to suggest", hintUa: "запропоновач", img: "/words_a1_cz/navrhnout.jpg" },
      { sk: "opowiadać", ua: "розповідати", ru: "рассказывать", en: "to tell", hintUa: "оповядач", img: "/words_a1_cz/vyprávět.jpg" },
      { sk: "ogłosić", ua: "повідомити", ru: "сообщить", en: "to announce", hintUa: "оґвосіч", img: "/words_a1_cz/oznámit.jpg" },
      { sk: "poprosić", ua: "попросити", ru: "попросить", en: "to ask for", hintUa: "попросіч", img: "/words_a1_cz/požádat.jpg" },
      { sk: "odpisać", ua: "відписати", ru: "ответить", en: "to reply", hintUa: "одпісач", img: "/words_a1_cz/odpovědět.jpg" },
      { sk: "zadzwonić", ua: "подзвонити", ru: "позвонить", en: "to call", hintUa: "задзвоніч", img: "/words_a1_cz/zavolat.jpg" },
      { sk: "pozdrowić", ua: "привітати", ru: "поприветствовать", en: "to greet", hintUa: "поздровіч", img: "/words_a1_cz/pozdravit.jpg" },
      { sk: "zapytać", ua: "запитати", ru: "спросить", en: "to ask", hintUa: "запитач", img: "/words_a1_cz/zeptat se.jpg" },
      { sk: "umówić się", ua: "домовитися", ru: "договориться", en: "to agree / arrange", hintUa: "умувіч шє", img: "/words_a1_cz/dohodnout se.jpg" },
    ],
  },
  {
    id: "a1-35",
    title: { ua: "Урок 35 — Місто (ситуації)", ru: "Урок 35 — Город (ситуации)", en: "Lesson 35 — City (situations)" },
    words: [
      { sk: "urząd", ua: "установа", ru: "учреждение", en: "institution", hintUa: "ужонд", img: "/words_a1_cz/úřad.jpg" },
      { sk: "fryzjer", ua: "перукарня", ru: "парикмахерская", en: "hair salon", hintUa: "фризєр", img: "/words_a1_cz/kadeřnictví.jpg" },
      { sk: "piekarnia", ua: "пекарня", ru: "пекарня", en: "bakery", hintUa: "пєкарня", img: "/words_a1_cz/pekárna.jpg" },
      { sk: "cukiernia", ua: "кондитерська", ru: "кондитерская", en: "pastry shop", hintUa: "цукєрня", img: "/words_a1_cz/cukrárna.jpg" },
      { sk: "stacja benzynowa", ua: "заправка", ru: "заправка", en: "gas station", hintUa: "стація бензинова", img: "/words_a1_cz/čerpací stanice.jpg" },
      { sk: "dworzec autobusowy", ua: "автовокзал", ru: "автовокзал", en: "bus station", hintUa: "дво́жец автобусови", img: "/words_a1_cz/autobusové nádraží.jpg" },
      { sk: "dworzec kolejowy", ua: "залізничний вокзал", ru: "железнодорожный вокзал", en: "railway station", hintUa: "дво́жец колейови", img: "/words_a1_cz/železniční stanice.jpg" },
      { sk: "skrzyżowanie", ua: "перехрестя", ru: "перекрёсток", en: "intersection", hintUa: "скшижованє", img: "/words_a1_cz/křižovatka.jpg" },
      { sk: "chodnik", ua: "тротуар", ru: "тротуар", en: "sidewalk", hintUa: "ходнік", img: "/words_a1/chodník.jpg" },
      { sk: "przejście podziemne", ua: "підземний перехід", ru: "подземный переход", en: "underpass", hintUa: "пшейшчє подзємне", img: "/words_pl/przejście podziemne.jpg" },
    ],
  },
  {
    id: "a1-36",
    title: { ua: "Урок 36 — Транспорт (дії)", ru: "Урок 36 — Транспорт (действия)", en: "Lesson 36 — Transport (actions)" },
    words: [
      { sk: "wsiąść", ua: "сісти", ru: "сесть(в транспорт)", en: "to get on", hintUa: "всянсць", img: "/words_a1_cz/nastoupit.jpg" },
      { sk: "wysiąść", ua: "вийти", ru: "выйти (из транспорта)", en: "to get off", hintUa: "висянсць", img: "/words_a1_cz/vystoupit.jpg" },
      { sk: "przesiąść się", ua: "пересісти", ru: "пересесть", en: "to transfer", hintUa: "пшесянсць шє", img: "/words_a1_cz/přestoupit.jpg" },
      { sk: "spóźniać się", ua: "запізнюватися", ru: "опаздывать", en: "to be late", hintUa: "спузьняч шє", img: "/words_a1_cz/zpozdit se.jpg" },
      { sk: "czekać", ua: "чекати", ru: "ждать", en: "to wait", hintUa: "чекач", img: "/words_a1_cz/čekat.jpg" },
      { sk: "odejść", ua: "піти", ru: "уйти", en: "to leave", hintUa: "одейшч", img: "/words_a1_cz/odejít.jpg" },
      { sk: "przyjść", ua: "прийти", ru: "прийти", en: "to come", hintUa: "пшийшч", img: "/words_a1_cz/přijít.jpg" },
      { sk: "kierować", ua: "керувати", ru: "водить", en: "to drive", hintUa: "кєровач", img: "/words_a1_cz/řídit.jpg" },
      { sk: "parkować", ua: "паркувати", ru: "парковаться", en: "to park", hintUa: "парковач", img: "/words_a1_cz/parkovat.jpg" },
      { sk: "zatrzymać", ua: "зупинити", ru: "остановить", en: "to stop", hintUa: "затшимаць", img: "/words_a1_cz/zastavit.jpg" },
    ],
  },
  {
    id: "a1-37",
    title: { ua: "Урок 37 — Плани", ru: "Урок 37 — Планы", en: "Lesson 37 — Plans" },
    words: [
      { sk: "plan", ua: "план", ru: "план", en: "plan", hintUa: "план", img: "/words_a1/plán.jpg" },
      { sk: "cel", ua: "ціль", ru: "цель", en: "goal", hintUa: "цель", img: "/words_a1_cz/cíl.jpg" },
      { sk: "przyszłość", ua: "майбутнє", ru: "будущее", en: "future", hintUa: "пшишвощч", img: "/words_a1_cz/budoucnost.jpg" },
      { sk: "przygotować", ua: "підготувати", ru: "подготовить", en: "to prepare", hintUa: "пшиготовач", img: "/words_pl/przygotować.jpg" },
      { sk: "przyszły tydzień", ua: "наступного тижня", ru: "на следующей неделе", en: "next week", hintUa: "пшишви тиджень", img: "/words_pl/przyszły tydzień.jpg" },
      { sk: "mieć nadzieję", ua: "сподіватися", ru: "надеяться", en: "to hope", hintUa: "мєч надзєє", img: "/words_pl/mieć nadzieję.jpg" },
      { sk: "zdecydować się", ua: "вирішити", ru: "решить", en: "to decide", hintUa: "здецидовач шє", img: "/words_pl/zdecydować się.jpg" },
      { sk: "zaplanować", ua: "запланувати", ru: "запланировать", en: "to plan", hintUa: "заплановач", img: "/words_a1_cz/naplánovat.jpg" },
      { sk: "termin", ua: "термін", ru: "срок", en: "deadline", hintUa: "термін", img: "/words_a1/termín.jpg" },
      { sk: "kontynuować", ua: "продовжити", ru: "продолжить", en: "to continue", hintUa: "континуовач", img: "/words_a1_cz/pokračovat.jpg" },
    ],
  },
  {
    id: "a1-38",
    title: { ua: "Урок 38 — Ситуації в магазині", ru: "Урок 38 — Ситуации в магазине", en: "Lesson 38 — Situations in a shop" },
    words: [
      { sk: "reklamacja", ua: "скарга", ru: "рекламация", en: "complaint", hintUa: "рекламація", img: "/words_a1_cz/reklamace.jpg" },
      { sk: "towar", ua: "товар", ru: "товар", en: "goods", hintUa: "товар", img: "/words_a1_cz/zboží.jpg" },
      { sk: "magazyn", ua: "склад", ru: "склад", en: "warehouse", hintUa: "маґазин", img: "/words_pl/magazyn.jpg" },
      { sk: "paragon", ua: "чек", ru: "чек", en: "receipt", hintUa: "параґон", img: "/words_a1_cz/účtenka.jpg" },
      { sk: "gwarancja", ua: "гарантія", ru: "гарантия", en: "warranty", hintUa: "ґваранція", img: "/words_pl/gwarancja.jpg" },
      { sk: "uszkodzony", ua: "пошкоджений", ru: "повреждённый", en: "damaged", hintUa: "ушкодзони", img: "/words_a1_cz/poškozený.jpg" },
      { sk: "sprzedawca", ua: "продавець", ru: "продавец", en: "salesperson", hintUa: "спшедавца", img: "/words_a1/predavač.jpg" },
      { sk: "klient", ua: "клієнт", ru: "клиент", en: "customer", hintUa: "клієнт", img: "/words_pl/klient.jpg" },
      { sk: "reklamować", ua: "подавати скаргу", ru: "подавать рекламацию", en: "to make a complaint", hintUa: "рекламовач", img: "/words_a1_cz/reklamovat.jpg" },
      { sk: "wymiana", ua: "обмін", ru: "обмен", en: "exchange", hintUa: "вимяна", img: "/words_a1_cz/výměna.jpg" },
    ],
  },
  {
    id: "a1-39",
    title: { ua: "Урок 39 — Абстрактні слова", ru: "Урок 39 — Абстрактные слова", en: "Lesson 39 — Abstract words" },
    words: [
      { sk: "życie", ua: "життя", ru: "жизнь", en: "life", hintUa: "жицє", img: "/words_pl/życie.jpg" },
      { sk: "czas", ua: "час", ru: "время", en: "time", hintUa: "час", img: "/words_pl/czas.jpg" },
      { sk: "możliwość", ua: "можливість", ru: "возможность", en: "possibility", hintUa: "можлівощч", img: "/words_pl/możliwość.jpg" },
      { sk: "powód", ua: "причина", ru: "причина", en: "reason", hintUa: "повуд", img: "/words_a1_cz/důvod.jpg" },
      { sk: "znaczenie", ua: "значення", ru: "значение", en: "meaning", hintUa: "значенє", img: "/words_pl/znaczenie.jpg" },
      { sk: "prawda", ua: "правда", ru: "правда", en: "truth", hintUa: "правда", img: "/words_pl/prawda.jpg" },
      { sk: "kłamstwo", ua: "брехня", ru: "ложь", en: "lie", hintUa: "квамство", img: "/words_pl/kłamstwo.jpg" },
      { sk: "sukces", ua: "успіх", ru: "успех", en: "success", hintUa: "сукцес", img: "/words_pl/sukces.jpg" },
      { sk: "niepowodzenie", ua: "невдача", ru: "неудача", en: "failure", hintUa: "нєповодзенє", img: "/words_a1_cz/neúspěch.jpg" },
      { sk: "doświadczenie", ua: "досвід", ru: "опыт", en: "experience", hintUa: "досьвядченє", img: "/words_a1_cz/zkušenost.jpg" },
    ],
  },
  {
    id: "a1-40",
    title: { ua: "Урок 40 — Повторення A1", ru: "Урок 40 — Повторение A1", en: "Lesson 40 — A1 review" },
    words: [
      { sk: "uczyć się", ua: "вчитися", ru: "учиться", en: "to study", hintUa: "учич шє", img: "/words_a1_cz/učit se.jpg" },
      { sk: "podróżować", ua: "подорожувати", ru: "путешествовать", en: "to travel", hintUa: "подружовач", img: "/words_a1_cz/cestovat.jpg" },
      { sk: "pomóc", ua: "допомогти", ru: "помочь", en: "to help", hintUa: "помуц", img: "/words_a1_cz/pomoct.jpg" },
      { sk: "pisać", ua: "писати", ru: "писать", en: "to write", hintUa: "пісач", img: "/words_a1_cz/psát.jpg" },
      { sk: "wrócić", ua: "повернутися", ru: "вернуться", en: "to return", hintUa: "вруціч", img: "/words_a1_cz/vrátit se.jpg" },
      { sk: "zostać", ua: "залишитися", ru: "остаться", en: "to stay", hintUa: "зостач", img: "/words_a1_cz/zůstat.jpg" },
      { sk: "zmienić", ua: "змінити", ru: "изменить", en: "to change", hintUa: "змєніч", img: "/words_a1_cz/změnit.jpg" },
      { sk: "pokazać", ua: "показати", ru: "показать", en: "to show", hintUa: "показач", img: "/words_a1_cz/ukázat.jpg" },
      { sk: "nieść", ua: "нести", ru: "нести", en: "to carry", hintUa: "нєщч", img: "/words_a1_cz/nést.jpg" },
      { sk: "siedzieć", ua: "сидіти", ru: "сидеть", en: "to sit", hintUa: "сєдзєч", img: "/words_a1_cz/sedět.jpg" },
    ],
  },
]