import type { Lesson } from "../data";

export const PL_A0_SOURCE: Lesson[] = [
  {
    id: "1",
    title: { ua: "Урок 1 — Базові слова", ru: "Урок 1 — Базовые слова", en: "Lesson 1 — Basic words" },
    words: [
      { sk: "dom", ua: "дім", ru: "дом", en: "house", img: "/words/dom.jpg" },
      { sk: "samochód", ua: "авто", ru: "авто", en: "car", img: "/words/car.jpg" },
      { sk: "woda", ua: "вода", ru: "вода", en: "water", img: "/words/water.jpg" },
      { sk: "chleb", ua: "хліб", ru: "хлеб", en: "bread", img: "/words/bread.jpg" },
      { sk: "szkoła", ua: "школа", ru: "школа", en: "school", img: "/words/school.jpg" },
      { sk: "miasto", ua: "місто", ru: "город", en: "city", img: "/words/city.jpg" },
      { sk: "czas", ua: "час", ru: "время", en: "time", img: "/words/čas.jpg" },
      { sk: "dzień", ua: "день", ru: "день", en: "day", img: "/words/day.jpg" },
      { sk: "dobry", ua: "добрий", ru: "хороший", en: "good", img: "/words/good.jpg" },
      { sk: "pieniądze", ua: "гроші", ru: "деньги", en: "money", img: "/words_a0_cz/peníze.jpg" },
    ],
  },
  {
    id: "2",
    title: { ua: "Урок 2 — люди", ru: "Урок 2 — люди", en: "Lesson 2 — People" },
    words: [
      { sk: "człowiek", ua: "людина", ru: "человек", en: "person", img: "/words_a0_cz/člověk.jpg" },
      { sk: "mężczyzna", ua: "чоловік", ru: "мужчина", en: "man", img: "/words_a0_cz/muž.jpg" },
      { sk: "kobieta", ua: "жінка", ru: "женщина", en: "woman", img: "/words/woman.jpg" },
      { sk: "dziecko", ua: "дитина", ru: "ребёнок", en: "child", img: "/words/child.jpg" },
      { sk: "przyjaciel", ua: "друг", ru: "друг", en: "friend", img: "/words/male-friend.jpg" },
      { sk: "przyjaciółka", ua: "подруга", ru: "подруга", en: "female friend", img: "/words/female-friend.jpg" },
      { sk: "ojciec", ua: "батько", ru: "отец", en: "father", img: "/words/father.jpg" },
      { sk: "matka", ua: "мати", ru: "мать", en: "mother", img: "/words/mother.jpg" },
      { sk: "brat", ua: "брат", ru: "брат", en: "brother", img: "/words/brother.jpg" },
      { sk: "siostra", ua: "сестра", ru: "сестра", en: "sister", img: "/words/sister.jpg" },
    ],
  },
  {
    id: "3",
    title: { ua: "Урок 3 — дім", ru: "Урок 3 — дом", en: "Lesson 3 — Home" },
    words: [
      { sk: "mieszkanie", ua: "квартира", ru: "квартира", en: "apartment", img: "/words/bytt.jpg" },
      { sk: "pokój", ua: "кімната", ru: "комната", en: "room", img: "/words/izba.jpg" },
      { sk: "kuchnia", ua: "кухня", ru: "кухня", en: "kitchen", img: "/words/kuchyňa.jpg" },
      { sk: "łazienka", ua: "ванна кімната", ru: "ванная", en: "bathroom", img: "/words/kúpeľňa.jpg" },
      { sk: "drzwi", ua: "двері", ru: "дверь", en: "door", img: "/words/dvere.jpg" },
      { sk: "okno", ua: "вікно", ru: "окно", en: "window", img: "/words/okno.jpg" },
      { sk: "stół", ua: "стіл", ru: "стол", en: "table", img: "/words/stôl.jpg" },
      { sk: "krzesło", ua: "стілець", ru: "стул", en: "chair", img: "/words/stolička.jpg" },
      { sk: "łóżko", ua: "ліжко", ru: "кровать", en: "bed", img: "/words/posteľ.jpg" },
      { sk: "szafa", ua: "шафа", ru: "шкаф", en: "wardrobe", img: "/words/skriňa.jpg" },
    ],
  },
  {
    id: "4",
    title: { ua: "Урок 4 — магазин", ru: "Урок 4 — магазин", en: "Lesson 4 — Shop" },
    words: [
      { sk: "sklep", ua: "магазин", ru: "магазин", en: "shop", img: "/words/obchod.jpg" },
      { sk: "kasa", ua: "каса", ru: "касса", en: "cash register", img: "/words/cena.jpg" },
      { sk: "cena", ua: "ціна", ru: "цена", en: "price", img: "/words_a0_cz/cena.jpg" },
      { sk: "zniżka", ua: "знижка", ru: "скидка", en: "discount", img: "/words/zľava.jpg" },
      { sk: "torba", ua: "пакет/сумка", ru: "пакет/сумка", en: "bag", img: "/words/taška.jpg" },
      { sk: "blok", ua: "чек", ru: "чек", en: "receipt", img: "/words/blok.jpg" },
      { sk: "gotówka", ua: "готівка", ru: "наличные", en: "cash", img: "/words/hotovosť.jpg" },
      { sk: "karta", ua: "картка", ru: "карта", en: "card", img: "/words/karta.jpg" },
      { sk: "kupić", ua: "купити", ru: "купить", en: "to buy", img: "/words/kupiť.jpg" },
      { sk: "płacić", ua: "платити", ru: "платить", en: "to pay", img: "/words_a0_cz/platit.jpg" },
    ],
  },
  {
    id: "5",
    title: { ua: "Урок 5 — Їжа та напої", ru: "Урок 5 — Еда и напитки", en: "Lesson 5 — Food and drinks" },
    words: [
      { sk: "jedzenie", ua: "їжа", ru: "еда", en: "food", img: "/words/jedlo.jpg" },
      { sk: "napój", ua: "напій", ru: "напиток", en: "drink", img: "/words/nápoj.jpg" },
      { sk: "chleb", ua: "хліб", ru: "хлеб", en: "bread", img: "/words/chlieb.jpg" },
      { sk: "mięso", ua: "м'ясо", ru: "мясо", en: "meat", img: "/words/mäso.jpg" },
      { sk: "zupa", ua: "суп", ru: "суп", en: "soup", img: "/words/polievka.jpg" },
      { sk: "owoce", ua: "фрукти", ru: "фрукты", en: "fruit", img: "/words_a0_cz/ovoce.jpg" },
      { sk: "warzywa", ua: "овочі", ru: "овощи", en: "vegetables", img: "/words/zelenina.jpg" },
      { sk: "woda", ua: "вода", ru: "вода", en: "water", img: "/words/water.jpg" },
      { sk: "kawa", ua: "кава", ru: "кофе", en: "coffee", img: "/words/káva.jpg" },
      { sk: "herbata", ua: "чай", ru: "чай", en: "tea", img: "/words/čaj.jpg" },
    ],
  },
  {
    id: "6",
    title: { ua: "Урок 6 — Місто", ru: "Урок 6 — Город", en: "Lesson 6 — City" },
    words: [
      { sk: "miasto", ua: "місто", ru: "город", en: "city", img: "/words/mesto.jpg" },
      { sk: "ulica", ua: "вулиця", ru: "улица", en: "street", img: "/words/ulica.jpg" },
      { sk: "plac", ua: "площа", ru: "площадь", en: "square", img: "/words/námestie.jpg" },
      { sk: "dom", ua: "будинок", ru: "дом", en: "house", img: "/words/dom.jpg" },
      { sk: "mieszkanie", ua: "квартира", ru: "квартира", en: "apartment", img: "/words/bytt.jpg" },
      { sk: "szkoła", ua: "школа", ru: "школа", en: "school", img: "/words/school.jpg" },
      { sk: "szpital", ua: "лікарня", ru: "больница", en: "hospital", img: "/words/nemocnica.jpg" },
      { sk: "przystanek", ua: "зупинка", ru: "остановка", en: "stop", img: "/words/zastávka.jpg" },
      { sk: "park", ua: "парк", ru: "парк", en: "park", img: "/words/park.jpg" },
      { sk: "stacja", ua: "станція/вокзал", ru: "станция / вокзал", en: "station", img: "/words/stanica.jpg" },
    ],
  },
  {
    id: "7",
    title: { ua: "Урок 7 — Транспорт", ru: "Урок 7 — Транспорт", en: "Lesson 7 — Transport" },
    words: [
      { sk: "transport", ua: "транспорт", ru: "транспорт", en: "transport", img: "/words/doprava.jpg" },
      { sk: "samochód", ua: "авто", ru: "авто", en: "car", img: "/words/car.jpg" },
      { sk: "autobus", ua: "автобус", ru: "автобус", en: "bus", img: "/words/autobus.jpg" },
      { sk: "pociąg", ua: "поїзд", ru: "поезд", en: "train", img: "/words/vlak.jpg" },
      { sk: "tramwaj", ua: "трамвай", ru: "трамвай", en: "tram", img: "/words/električka.jpg" },
      { sk: "metro", ua: "метро", ru: "метро", en: "metro", img: "/words_a0_cz/metro.jpg" },
      { sk: "taksówka", ua: "таксі", ru: "такси", en: "taxi", img: "/words/taxík.jpg" },
      { sk: "przystanek", ua: "зупинка", ru: "остановка", en: "stop", img: "/words/zastávka.jpg" },
      { sk: "bilet", ua: "квиток", ru: "билет", en: "ticket", img: "/words/lístok.jpg" },
      { sk: "lotnisko", ua: "аеропорт", ru: "аэропорт", en: "airport", img: "/words/letisko.jpg" },
    ],
  },
  {
    id: "8",
    title: { ua: "Урок 8 — Час і дні", ru: "Урок 8 — Время и дни", en: "Lesson 8 — Time and days" },
    words: [
      { sk: "czas", ua: "час", ru: "время", en: "time", img: "/words/čas.jpg" },
      { sk: "dzień", ua: "день", ru: "день", en: "day", img: "/words/day.jpg" },
      { sk: "noc", ua: "ніч", ru: "ночь", en: "night", img: "/words/noc.jpg" },
      { sk: "tydzień", ua: "тиждень", ru: "неделя", en: "week", img: "/words/týždeň.jpg" },
      { sk: "miesiąc", ua: "місяць", ru: "месяц", en: "month", img: "/words/mesiac.jpg" },
      { sk: "rok", ua: "рік", ru: "год", en: "year", img: "/words/rok.jpg" },
      { sk: "dziś", ua: "сьогодні", ru: "сегодня", en: "today", img: "/words/dnes.jpg" },
      { sk: "jutro", ua: "завтра", ru: "завтра", en: "tomorrow", img: "/words_a0_cz/zítra.jpg" },
      { sk: "wczoraj", ua: "вчора", ru: "вчера", en: "yesterday", img: "/words/včera.jpg" },
      { sk: "godzina", ua: "година", ru: "час / час (ед.)", en: "hour", img: "/words/hodina.jpg" },
    ],
  },
  {
    id: "9",
    title: { ua: "Урок 9 — Робота", ru: "Урок 9 — Работа", en: "Lesson 9 — Work" },
    words: [
      { sk: "praca", ua: "робота", ru: "работа", en: "work", img: "/words/práca.jpg" },
      { sk: "zatrudnienie", ua: "зайнятість / робота", ru: "занятость / работа", en: "job / employment", img: "/words_a0_cz/zaměstnání.jpg" },
      { sk: "firma", ua: "фірма", ru: "фирма", en: "company", img: "/words/firma.jpg" },
      { sk: "szef", ua: "начальник", ru: "начальник", en: "boss", img: "/words/šéf.jpg" },
      { sk: "kolega", ua: "колега", ru: "коллега", en: "colleague", img: "/words/kolega.jpg" },
      { sk: "wynagrodzenie", ua: "зарплата", ru: "зарплата", en: "salary", img: "/words/hotovosť.jpg" },
      { sk: "umowa", ua: "договір", ru: "договор", en: "contract", img: "/words/kolega.jpg" },
      { sk: "pracować", ua: "працювати", ru: "работать", en: "to work", img: "/words/pracovať.jpg" },
      { sk: "praca dorywcza", ua: "підробіток", ru: "подработка", en: "part-time job", img: "/words/brigáda.jpg" },
      { sk: "urlop", ua: "відпустка", ru: "отпуск", en: "vacation", img: "/words/dovolenka.jpg" },
    ],
  },
  {
    id: "10",
    title: { ua: "Урок 10 — Школа", ru: "Урок 10 — Школа", en: "Lesson 10 — School" },
    words: [
      { sk: "szkoła", ua: "школа", ru: "школа", en: "school", img: "/words/school.jpg" },
      { sk: "uczeń", ua: "учень", ru: "ученик", en: "student", img: "/words/žiak.jpg" },
      { sk: "nauczyciel", ua: "вчитель", ru: "учитель", en: "teacher", img: "/words/učiteľ.jpg" },
      { sk: "klasa", ua: "клас", ru: "класс", en: "classroom", img: "/words/trieda.jpg" },
      { sk: "przedmiot", ua: "предмет", ru: "предмет", en: "subject", img: "/words/predmet.jpg" },
      { sk: "godzina", ua: "урок", ru: "урок", en: "lesson", img: "/words/hodina.jpg" },
      { sk: "zadanie", ua: "завдання / домашня робота", ru: "задание / домашняя работа", en: "task / homework", img: "/words/úloha.jpg" },
      { sk: "test", ua: "тест", ru: "тест", en: "test", img: "/words/test.jpg" },
      { sk: "zeszyt", ua: "зошит", ru: "тетрадь", en: "notebook", img: "/words_a0_cz/sešit.jpg" },
      { sk: "podręcznik", ua: "підручник", ru: "учебник", en: "textbook", img: "/words_a0_cz/učebnice.jpg" },
    ],
  },
  {
    id: "11",
    title: { ua: "Урок 11 — Числа", ru: "Урок 11 — Числа", en: "Lesson 11 — Numbers" },
    words: [
      { sk: "zero", ua: "нуль", ru: "ноль", en: "zero", img: "/words/nula.jpg" },
      { sk: "jeden", ua: "один", ru: "один", en: "one", img: "/words/jeden.jpg" },
      { sk: "dwa", ua: "два", ru: "два", en: "two", img: "/words/dva.jpg" },
      { sk: "trzy", ua: "три", ru: "три", en: "three", img: "/words/tri.jpg" },
      { sk: "cztery", ua: "чотири", ru: "четыре", en: "four", img: "/words/štyri.jpg" },
      { sk: "pięć", ua: "п’ять", ru: "пять", en: "five", img: "/words/päť.jpg" },
      { sk: "sześć", ua: "шість", ru: "шесть", en: "six", img: "/words/šesť.jpg" },
      { sk: "siedem", ua: "сім", ru: "семь", en: "seven", img: "/words/sedem.jpg" },
      { sk: "osiem", ua: "вісім", ru: "восемь", en: "eight", img: "/words/osem.jpg" },
      { sk: "dziewięć", ua: "дев’ять", ru: "девять", en: "nine", img: "/words/deväť.jpg" },
    ],
  },
  {
    id: "12",
    title: { ua: "Урок 12 — Кольори", ru: "Урок 12 — Цвета", en: "Lesson 12 — Colors" },
    words: [
      { sk: "kolor", ua: "колір", ru: "цвет", en: "color", img: "/words/farba.jpg" },
      { sk: "biały", ua: "білий", ru: "белый", en: "white", img: "/words/biely.jpg" },
      { sk: "czarny", ua: "чорний", ru: "чёрный", en: "black", img: "/words/čierny.jpg" },
      { sk: "czerwony", ua: "червоний", ru: "красный", en: "red", img: "/words/červený.jpg" },
      { sk: "niebieski", ua: "синій", ru: "синий", en: "blue", img: "/words/modrý.jpg" },
      { sk: "zielony", ua: "зелений", ru: "зелёный", en: "green", img: "/words/zelený.jpg" },
      { sk: "żółty", ua: "жовтий", ru: "жёлтый", en: "yellow", img: "/words/žltý.jpg" },
      { sk: "pomarańczowy", ua: "помаранчевий", ru: "оранжевый", en: "orange", img: "/words/oranžový.jpg" },
      { sk: "różowy", ua: "рожевий", ru: "розовый", en: "pink", img: "/words/ružový.jpg" },
      { sk: "brązowy", ua: "коричневий", ru: "коричневый", en: "brown", img: "/words/hnedý.jpg" },
    ],
  },
  {
    id: "13",
    title: { ua: "Урок 13 — Одяг", ru: "Урок 13 — Одежда", en: "Lesson 13 — Clothes" },
    words: [
      { sk: "ubranie", ua: "одяг", ru: "одежда", en: "clothes", img: "/words/oblečenie.jpg" },
      { sk: "koszulka", ua: "футболка", ru: "футболка", en: "T-shirt", img: "/words/tričko.jpg" },
      { sk: "spodnie", ua: "штани", ru: "брюки", en: "trousers", img: "/words/nohavice.jpg" },
      { sk: "kurtka", ua: "куртка", ru: "куртка", en: "jacket", img: "/words/bunda.jpg" },
      { sk: "buty", ua: "взуття", ru: "обувь", en: "shoes", img: "/words/topánky.jpg" },
      { sk: "płaszcz", ua: "пальто", ru: "пальто", en: "coat", img: "/words/kabát.jpg" },
      { sk: "sukienka", ua: "сукня", ru: "платье", en: "dress", img: "/words/šaty.jpg" },
      { sk: "czapka", ua: "шапка", ru: "шапка", en: "hat", img: "/words/čiapka.jpg" },
      { sk: "skarpetki", ua: "шкарпетки", ru: "носки", en: "socks", img: "/words/ponožky.jpg" },
      { sk: "sweter", ua: "светр", ru: "свитер", en: "sweater", img: "/words/sveter.jpg" },
    ],
  },
  {
    id: "14",
    title: { ua: "Урок 14 — Тіло людини", ru: "Урок 14 — Тело человека", en: "Lesson 14 — Body" },
    words: [
      { sk: "ciało", ua: "тіло", ru: "тело", en: "body", img: "/words/telo.jpg" },
      { sk: "głowa", ua: "голова", ru: "голова", en: "head", img: "/words/hlava.jpg" },
      { sk: "oko", ua: "око", ru: "глаз", en: "eye", img: "/words/oko.jpg" },
      { sk: "nos", ua: "ніс", ru: "нос", en: "nose", img: "/words/nos.jpg" },
      { sk: "usta", ua: "рот", ru: "рот", en: "mouth", img: "/words/ústa.jpg" },
      { sk: "ręka", ua: "рука", ru: "рука", en: "hand", img: "/words/ruka.jpg" },
      { sk: "noga", ua: "нога", ru: "нога", en: "leg", img: "/words/noha.jpg" },
      { sk: "plecy", ua: "спина", ru: "спина", en: "back", img: "/words/chrbát.jpg" },
      { sk: "brzuch", ua: "живіт", ru: "живот", en: "belly", img: "/words/brucho.jpg" },
      { sk: "serce", ua: "серце", ru: "сердце", en: "heart", img: "/words/srdce.jpg" },
    ],
  },
  {
    id: "15",
    title: { ua: "Урок 15 — Здоров’я", ru: "Урок 15 — Здоровье", en: "Lesson 15 — Health" },
    words: [
      { sk: "zdrowie", ua: "здоров’я", ru: "здоровье", en: "health", img: "/words/zdravie.jpg" },
      { sk: "choroba", ua: "хвороба", ru: "болезнь", en: "illness", img: "/words/choroba.jpg" },
      { sk: "lekarz", ua: "лікар", ru: "врач", en: "doctor", img: "/words/lekár.jpg" },
      { sk: "szpital", ua: "лікарня", ru: "больница", en: "hospital", img: "/words/nemocnica.jpg" },
      { sk: "lek", ua: "ліки", ru: "лекарство / лекарства", en: "medicine", img: "/words/liek.jpg" },
      { sk: "ból", ua: "біль", ru: "боль", en: "pain", img: "/words/bolesť.jpg" },
      { sk: "temperatura", ua: "температура", ru: "температура", en: "temperature", img: "/words/teplota.jpg" },
      { sk: "kaszel", ua: "кашель", ru: "кашель", en: "cough", img: "/words/kašeľ.jpg" },
      { sk: "przeziębienie", ua: "застуда", ru: "простуда", en: "cold", img: "/words/prechladnutie.jpg" },
      { sk: "wyzdrowieć", ua: "одужати", ru: "выздороветь", en: "to recover", img: "/words/uzdraviť sa.jpg" },
    ],
  },
  {
    id: "16",
    title: { ua: "Урок 16 — Погода", ru: "Урок 16 — Погода", en: "Lesson 16 — Weather" },
    words: [
      { sk: "pogoda", ua: "погода", ru: "погода", en: "weather", img: "/words_a0_cz/počasí.jpg" },
      { sk: "słońce", ua: "сонце", ru: "солнце", en: "sun", img: "/words_a0_cz/slunce.jpg" },
      { sk: "deszcz", ua: "дощ", ru: "дождь", en: "rain", img: "/words_a0_cz/déšť.jpg" },
      { sk: "śnieg", ua: "сніг", ru: "снег", en: "snow", img: "/words_a0_cz/sníh.jpg" },
      { sk: "wiatr", ua: "вітер", ru: "ветер", en: "wind", img: "/words_a0_cz/vítr.jpg" },
      { sk: "chmura", ua: "хмара", ru: "облако", en: "cloud", img: "/words_a0_cz/mrak.jpg" },
      { sk: "ciepło", ua: "тепло", ru: "тепло", en: "warmth", img: "/words/teplo.jpg" },
      { sk: "zima", ua: "холод", ru: "холод", en: "cold", img: "/words/zima.jpg" },
      { sk: "burza", ua: "буря", ru: "буря / гроза", en: "storm", img: "/words_a0_cz/bouře.jpg" },
      { sk: "temperatura", ua: "температура", ru: "температура", en: "temperature", img: "/words/teplota.jpg" },
    ],
  },
  {
    id: "17",
    title: { ua: "Урок 17 — Природа", ru: "Урок 17 — Природа", en: "Lesson 17 — Nature" },
    words: [
      { sk: "natura", ua: "природа", ru: "природа", en: "nature", img: "/words_a0_cz/příroda.jpg" },
      { sk: "drzewo", ua: "дерево", ru: "дерево", en: "tree", img: "/words/strom.jpg" },
      { sk: "las", ua: "ліс", ru: "лес", en: "forest", img: "/words/les.jpg" },
      { sk: "rzeka", ua: "річка", ru: "река", en: "river", img: "/words_a0_cz/řeka.jpg" },
      { sk: "jezioro", ua: "озеро", ru: "озеро", en: "lake", img: "/words/jazero.jpg" },
      { sk: "góra", ua: "гора", ru: "гора", en: "mountain", img: "/words/hora.jpg" },
      { sk: "kwiat", ua: "квітка", ru: "цветок", en: "flower", img: "/words_a0_cz/květina.jpg" },
      { sk: "trawa", ua: "трава", ru: "трава", en: "grass", img: "/words/tráva.jpg" },
      { sk: "zwierzę", ua: "тварина", ru: "животное", en: "animal", img: "/words_a0_cz/zvíře.jpg" },
      { sk: "ziemia", ua: "земля", ru: "земля", en: "earth", img: "/words_a0_cz/země.jpg" },
    ],
  },
  {
    id: "18",
    title: { ua: "Урок 18 — Побут", ru: "Урок 18 — Быт", en: "Lesson 18 — Household" },
    words: [
      { sk: "gospodarstwo domowe", ua: "побут", ru: "быт", en: "household", img: "/words/domácnosť.jpg" },
      { sk: "dom", ua: "дім", ru: "дом", en: "house", img: "/words/dom.jpg" },
      { sk: "mieszkanie", ua: "квартира", ru: "квартира", en: "apartment", img: "/words/bytt.jpg" },
      { sk: "pokój", ua: "кімната", ru: "комната", en: "room", img: "/words/izba.jpg" },
      { sk: "łóżko", ua: "ліжко", ru: "кровать", en: "bed", img: "/words/posteľ.jpg" },
      { sk: "stół", ua: "стіл", ru: "стол", en: "table", img: "/words/stôl.jpg" },
      { sk: "krzesło", ua: "стілець", ru: "стул", en: "chair", img: "/words/stolička.jpg" },
      { sk: "kuchnia", ua: "кухня", ru: "кухня", en: "kitchen", img: "/words/kuchyňa.jpg" },
      { sk: "lodówka", ua: "холодильник", ru: "холодильник", en: "fridge", img: "/words_a0_cz/lednička.jpg" },
      { sk: "sprzątać", ua: "прибирати", ru: "убирать / прибираться", en: "to clean", img: "/words_a0_cz/uklízet.jpg" },
    ],
  },
  {
    id: "19",
    title: { ua: "Урок 19 — Дії та дієслова", ru: "Урок 19 — Действия и глаголы", en: "Lesson 19 — Actions and verbs" },
    words: [
      { sk: "robić", ua: "робити", ru: "делать", en: "to do", img: "/words_a0_cz/dělat.jpg" },
      { sk: "iść", ua: "йти", ru: "идти", en: "to go", img: "/words_a0_cz/jít.jpg" },
      { sk: "przyjść", ua: "прийти", ru: "прийти", en: "to come", img: "/words_a0_cz/přijít.jpg" },
      { sk: "widzieć", ua: "бачити", ru: "видеть", en: "to see", img: "/words_a0_cz/vidět.jpg" },
      { sk: "mówić", ua: "говорити", ru: "говорить", en: "to speak", img: "/words_a0_cz/mluvit.jpg" },
      { sk: "jeść", ua: "їсти", ru: "есть", en: "to eat", img: "/words_a0_cz/jíst.jpg" },
      { sk: "pić", ua: "пити", ru: "пить", en: "to drink", img: "/words/piť.jpg" },
      { sk: "spać", ua: "спати", ru: "спать", en: "to sleep", img: "/words_a0_cz/spát.jpg" },
      { sk: "pracować", ua: "працювати", ru: "работать", en: "to work", img: "/words/pracovať.jpg" },
      { sk: "uczyć się", ua: "вчитися", ru: "учиться", en: "to study", img: "/words_a0_cz/učit se.jpg" },
    ],
  },
  {
    id: "20",
    title: { ua: "Урок 20 — Питання і відповіді", ru: "Урок 20 — Вопросы и ответы", en: "Lesson 20 — Questions and answers" },
    words: [
      { sk: "kto", ua: "хто", ru: "кто", en: "who", img: "/words_a0_cz/kdo.jpg" },
      { sk: "co", ua: "що", ru: "что", en: "what", img: "/words_a0_cz/co.jpg" },
      { sk: "gdzie", ua: "де", ru: "где", en: "where", img: "/words/kde.jpg" },
      { sk: "kiedy", ua: "коли", ru: "когда", en: "when", img: "/words_a0_cz/kdy.jpg" },
      { sk: "dlaczego", ua: "чому", ru: "почему", en: "why", img: "/words_a0_cz/proč.jpg" },
      { sk: "jak", ua: "як", ru: "как", en: "how", img: "/words_a0_cz/jak.jpg" },
      { sk: "ile", ua: "скільки", ru: "сколько", en: "how much / how many", img: "/words/koľko.jpg" },
      { sk: "tak", ua: "так", ru: "да", en: "yes", img: "/words_a0_cz/ano.jpg" },
      { sk: "nie", ua: "ні", ru: "нет", en: "no", img: "/words_a0_cz/ne.jpg" },
      { sk: "może", ua: "можливо", ru: "возможно", en: "maybe", img: "/words_a0_cz/možná.jpg" },
    ],
  },
  {
    id: "21",
    title: { ua: "Урок 21 — Місця", ru: "Урок 21 — Места", en: "Lesson 21 — Places" },
    words: [
      { sk: "miejsce", ua: "місце", ru: "место", en: "place", img: "/words/miesto.jpg" },
      { sk: "centrum", ua: "центр", ru: "центр", en: "center", img: "/words/centrum.jpg" },
      { sk: "sklep", ua: "магазин", ru: "магазин", en: "shop", img: "/words/obchod.jpg" },
      { sk: "restauracja", ua: "ресторан", ru: "ресторан", en: "restaurant", img: "/words_a0_cz/restaurace.jpg" },
      { sk: "kawiarnia", ua: "кафе", ru: "кафе", en: "café", img: "/words_a0_cz/kavárna.jpg" },
      { sk: "park", ua: "парк", ru: "парк", en: "park", img: "/words/park.jpg" },
      { sk: "bank", ua: "банк", ru: "банк", en: "bank", img: "/words/banka.jpg" },
      { sk: "poczta", ua: "пошта", ru: "почта", en: "post office", img: "/words/pošta.jpg" },
      { sk: "policja", ua: "поліція", ru: "полиция", en: "police", img: "/words_a0_cz/policie.jpg" },
      { sk: "stacja", ua: "станція / вокзал", ru: "станция / вокзал", en: "station", img: "/words/stanica.jpg" },
    ],
  },
  {
    id: "22",
    title: { ua: "Урок 22 — Емоції", ru: "Урок 22 — Эмоции", en: "Lesson 22 — Emotions" },
    words: [
      { sk: "radość", ua: "радість", ru: "радость", en: "joy", img: "/words_a0_cz/radost.jpg" },
      { sk: "smutek", ua: "смуток", ru: "грусть / печаль", en: "sadness", img: "/words_a0_cz/smutek.jpg" },
      { sk: "strach", ua: "страх", ru: "страх", en: "fear", img: "/words/strach.jpg" },
      { sk: "gniew", ua: "злість", ru: "злость / гнев", en: "anger", img: "/words_a0_cz/hněv.jpg" },
      { sk: "miłość", ua: "любов", ru: "любовь", en: "love", img: "/words/láska.jpg" },
      { sk: "szczęście", ua: "щастя", ru: "счастье", en: "happiness", img: "/words_a0_cz/štěstí.jpg" },
      { sk: "zmęczenie", ua: "втома", ru: "усталость", en: "tiredness", img: "/words/únava.jpg" },
      { sk: "stres", ua: "стрес", ru: "стресс", en: "stress", img: "/words/stres.jpg" },
      { sk: "spokój", ua: "спокій", ru: "покой / спокойствие", en: "calm", img: "/words_a0_cz/klid.jpg" },
      { sk: "zaskoczenie", ua: "здивування", ru: "удивление", en: "surprise", img: "/words_a0_cz/překvapení.jpg" },
    ],
  },
  {
    id: "23",
    title: { ua: "Урок 23 — Хобі", ru: "Урок 23 — Хобби", en: "Lesson 23 — Hobbies" },
    words: [
      { sk: "hobby", ua: "хобі", ru: "хобби", en: "hobby", img: "/words/hobby.jpg" },
      { sk: "sport", ua: "спорт", ru: "спорт", en: "sport", img: "/words_a0_cz/sport.jpg" },
      { sk: "piłka nożna", ua: "футбол", ru: "футбол", en: "football", img: "/words_a0_cz/fotbal.jpg" },
      { sk: "muzyka", ua: "музика", ru: "музыка", en: "music", img: "/words/hudba.jpg" },
      { sk: "film", ua: "фільм", ru: "фильм", en: "film", img: "/words/film.jpg" },
      { sk: "czytanie", ua: "читання", ru: "чтение", en: "reading", img: "/words_a0_cz/čtení.jpg" },
      { sk: "podróżowanie", ua: "подорожі", ru: "путешествия", en: "traveling", img: "/words_a0_cz/cestování.jpg" },
      { sk: "gra", ua: "гра", ru: "игра", en: "game", img: "/words/hra.jpg" },
      { sk: "malowanie", ua: "малювання", ru: "рисование", en: "painting", img: "/words_a0_cz/malování.jpg" },
      { sk: "taniec", ua: "танець", ru: "танец", en: "dance", img: "/words/tanec.jpg" },
    ],
  },
  {
    id: "24",
    title: { ua: "Урок 24 — Спілкування", ru: "Урок 24 — Общение", en: "Lesson 24 — Communication" },
    words: [
      { sk: "mówić", ua: "говорити", ru: "говорить", en: "to speak", img: "/words_a0_cz/mluvit.jpg" },
      { sk: "opowiadać", ua: "розповідати", ru: "рассказывать", en: "to tell", img: "/words_a0_cz/vyprávět.jpg" },
      { sk: "słuchać", ua: "слухати", ru: "слушать", en: "to listen", img: "/words_a0_cz/poslouchat.jpg" },
      { sk: "pytać", ua: "питати", ru: "спрашивать", en: "to ask", img: "/words_a0_cz/ptát se.jpg" },
      { sk: "odpowiadać", ua: "відповідати", ru: "отвечать", en: "to answer", img: "/words_a0_cz/odpovědět.jpg" },
      { sk: "telefonować", ua: "телефонувати", ru: "звонить / разговаривать по телефону", en: "to call", img: "/words_a0_cz/telefonovat.jpg" },
      { sk: "wiadomość", ua: "повідомлення", ru: "сообщение", en: "message", img: "/words_a0_cz/zpráva.jpg" },
      { sk: "spotkanie", ua: "зустріч", ru: "встреча", en: "meeting", img: "/words_a0_cz/setkání.jpg" },
      { sk: "dyskusja", ua: "обговорення", ru: "обсуждение / дискуссия", en: "discussion", img: "/words_a0_cz/diskuze.jpg" },
      { sk: "pozdrowienie", ua: "привітання", ru: "приветствие", en: "greeting", img: "/words/pozdrav.jpg" },
    ],
  },
  {
    id: "25",
    title: { ua: "Урок 25 — Подорожі", ru: "Урок 25 — Путешествия", en: "Lesson 25 — Travel" },
    words: [
      { sk: "droga", ua: "подорож", ru: "путешествие / дорога", en: "trip / journey", img: "/words/cesta.jpg" },
      { sk: "podróżować", ua: "подорожувати", ru: "путешествовать", en: "to travel", img: "/words_a0_cz/cestovat.jpg" },
      { sk: "walizka", ua: "валіза", ru: "чемодан", en: "suitcase", img: "/words_a0_cz/kufr.jpg" },
      { sk: "paszport", ua: "паспорт", ru: "паспорт", en: "passport", img: "/words/pas.jpg" },
      { sk: "bilet lotniczy", ua: "авіаквиток", ru: "авиабилет", en: "plane ticket", img: "/words/letenka.jpg" },
      { sk: "pociąg", ua: "поїзд", ru: "поезд", en: "train", img: "/words/vlak.jpg" },
      { sk: "autobus", ua: "автобус", ru: "автобус", en: "bus", img: "/words/autobus.jpg" },
      { sk: "lotnisko", ua: "аеропорт", ru: "аэропорт", en: "airport", img: "/words/letisko.jpg" },
      { sk: "mapa", ua: "карта", ru: "карта", en: "map", img: "/words/mapa.jpg" },
      { sk: "rezerwacja", ua: "бронювання", ru: "бронирование", en: "reservation", img: "/words_a0_cz/rezervace.jpg" },
    ],
  },
  {
    id: "26",
    title: { ua: "Урок 26 — Готель і ресторан", ru: "Урок 26 — Отель и ресторан", en: "Lesson 26 — Hotel and restaurant" },
    words: [
      { sk: "hotel", ua: "готель", ru: "отель", en: "hotel", img: "/words/hotel.jpg" },
      { sk: "pokój", ua: "кімната", ru: "комната / номер", en: "room", img: "/words/izba.jpg" },
      { sk: "recepcja", ua: "ресепшн", ru: "ресепшн", en: "reception", img: "/words_a0_cz/recepce.jpg" },
      { sk: "restauracja", ua: "ресторан", ru: "ресторан", en: "restaurant", img: "/words_a0_cz/restaurace.jpg" },
      { sk: "menu", ua: "меню", ru: "меню", en: "menu", img: "/words/menu.jpg" },
      { sk: "zamówić", ua: "замовити", ru: "заказать", en: "to order", img: "/words_a0_cz/objednat.jpg" },
      { sk: "śniadanie", ua: "сніданок", ru: "завтрак", en: "breakfast", img: "/words_a0_cz/snídaně.jpg" },
      { sk: "obiad", ua: "обід", ru: "обед", en: "lunch", img: "/words_a0_cz/oběd.jpg" },
      { sk: "kolacja", ua: "вечеря", ru: "ужин", en: "dinner", img: "/words_a0_cz/večeře.jpg" },
      { sk: "konto", ua: "рахунок", ru: "счёт", en: "bill", img: "/words/účet.jpg" },
    ],
  },
  {
    id: "27",
    title: { ua: "Урок 27 — Гроші", ru: "Урок 27 — Деньги", en: "Lesson 27 — Money" },
    words: [
      { sk: "pieniądze", ua: "гроші", ru: "деньги", en: "money", img: "/words_a0_cz/peníze.jpg" },
      { sk: "euro", ua: "євро", ru: "евро", en: "euro", img: "/words/euro.jpg" },
      { sk: "cena", ua: "ціна", ru: "цена", en: "price", img: "/words/cena.jpg" },
      { sk: "płatność", ua: "платіж", ru: "платёж", en: "payment", img: "/words/platba.jpg" },
      { sk: "gotówka", ua: "готівка", ru: "наличные", en: "cash", img: "/words/hotovosť.jpg" },
      { sk: "karta", ua: "картка", ru: "карта", en: "card", img: "/words/karta.jpg" },
      { sk: "konto", ua: "рахунок", ru: "счёт", en: "account / bill", img: "/words/účet.jpg" },
      { sk: "bank", ua: "банк", ru: "банк", en: "bank", img: "/words/banka.jpg" },
      { sk: "zniżka", ua: "знижка", ru: "скидка", en: "discount", img: "/words/zľava.jpg" },
      { sk: "wydatki", ua: "витрати", ru: "расходы", en: "expenses", img: "/words_a0_cz/výdaje.jpg" },
    ],
  },
  {
    id: "28",
    title: { ua: "Урок 28 — Технології", ru: "Урок 28 — Технологии", en: "Lesson 28 — Technology" },
    words: [
      { sk: "technologia", ua: "технологія", ru: "технология", en: "technology", img: "/words_a0_cz/technologie.jpg" },
      { sk: "komputer", ua: "комп’ютер", ru: "компьютер", en: "computer", img: "/words_a0_cz/počítač.jpg" },
      { sk: "telefon", ua: "телефон", ru: "телефон", en: "phone", img: "/words_a0_cz/telefon.jpg" },
      { sk: "internet", ua: "інтернет", ru: "интернет", en: "internet", img: "/words/internet.jpg" },
      { sk: "aplikacja", ua: "додаток", ru: "приложение", en: "app", img: "/words_a0_cz/aplikace.jpg" },
      { sk: "program", ua: "програма", ru: "программа", en: "program", img: "/words/program.jpg" },
      { sk: "system", ua: "система", ru: "система", en: "system", img: "/words/systém.jpg" },
      { sk: "sieć", ua: "мережа", ru: "сеть", en: "network", img: "/words_a0_cz/síť.jpg" },
      { sk: "dane", ua: "дані", ru: "данные", en: "data", img: "/words_a0_cz/data.jpg" },
      { sk: "hasło", ua: "пароль", ru: "пароль", en: "password", img: "/words/heslo.jpg" },
    ],
  },
  {
    id: "29",
    title: { ua: "Урок 29 — Повсякденні фрази", ru: "Урок 29 — Повседневные фразы", en: "Lesson 29 — Everyday phrases" },
    words: [
      { sk: "dzień dobry", ua: "добрий день", ru: "добрый день", en: "good afternoon", img: "/words_a0_cz/dobrý den.jpg" },
      { sk: "cześć", ua: "привіт", ru: "привет", en: "hi", img: "/words_a0_cz/ahoj.jpg" },
      { sk: "dziękuję", ua: "дякую", ru: "спасибо", en: "thank you", img: "/words_a0_cz/děkuji.jpg" },
      { sk: "proszę", ua: "будь ласка", ru: "пожалуйста", en: "please", img: "/words/prosím.jpg" },
      { sk: "przepraszam", ua: "вибач", ru: "извини", en: "sorry", img: "/words_a0_cz/omlouvám se.jpg" },
      { sk: "rozumiem", ua: "розумію", ru: "понимаю", en: "I understand", img: "/words_a0_cz/rozumím.jpg" },
      { sk: "nie rozumiem", ua: "не розумію", ru: "не понимаю", en: "I don't understand", img: "/words_a0_cz/nerozumím.jpg" },
      { sk: "proszę pomóc", ua: "допоможіть", ru: "помогите", en: "help", img: "/words_a0_cz/pomozte.jpg" },
      { sk: "jasne", ua: "ясно", ru: "ясно", en: "sure", img: "/words_a0_cz/jasné.jpg" },
      { sk: "dobrze", ua: "добре", ru: "хорошо", en: "okay", img: "/words_a0_cz/dobře.jpg" },
    ],
  },
  {
    id: "30",
    title: { ua: "Урок 30 — Повторення бази", ru: "Урок 30 — Повторение базы", en: "Lesson 30 — Basic review" },
    words: [
      { sk: "ja", ua: "я", ru: "я", en: "I", img: "/words_a0_cz/já.jpg" },
      { sk: "ty", ua: "ти", ru: "ты", en: "you", img: "/words/ty.jpg" },
      { sk: "on", ua: "він", ru: "он", en: "he", img: "/words/on.jpg" },
      { sk: "ona", ua: "вона", ru: "она", en: "she", img: "/words/ona.jpg" },
      { sk: "my", ua: "ми", ru: "мы", en: "we", img: "/words/my.jpg" },
      { sk: "wy", ua: "ви", ru: "вы", en: "you (plural/formal)", img: "/words/vy.jpg" },
      { sk: "oni", ua: "вони", ru: "они", en: "they", img: "/words/oni.jpg" },
      { sk: "być", ua: "бути", ru: "быть", en: "to be", img: "/words_a0_cz/být.jpg" },
      { sk: "mieć", ua: "мати", ru: "иметь", en: "to have", img: "/words_a0_cz/mít.jpg" },
      { sk: "iść", ua: "йти", ru: "идти", en: "to go", img: "/words_a0_cz/jít.jpg" },
    ],
  },]