import type { Lesson } from "../data";

export const PL_B2_SOURCE: Lesson[] = [
  {
    id: "b2-1",
    title: { ua: "Урок 1 — Переговори та домовленості", ru: "Урок 1 — Переговоры и договорённости", en: "Lesson 1 — Negotiations and Agreements" },
    words: [
      { sk: "negocjacje", ua: "переговори", ru: "переговоры", en: "negotiation", img: "/words_b2/rokovanie.jpg" },
      { sk: "umowa", ua: "домовленість / угода", ru: "договорённость / соглашение", en: "agreement / deal", img: "/words_b2/dohoda.jpg" },
      { sk: "warunek", ua: "умова", ru: "условие", en: "condition", img: "/words_b2/podmienka.jpg" },
      { sk: "ustępstwo", ua: "поступка / компромісний крок", ru: "уступка / компромиссный шаг", en: "concession / compromise move", img: "/words_b2/ústupok.jpg" },
      { sk: "stanowisko", ua: "позиція / точка зору", ru: "позиция / точка зрения", en: "position / point of view", img: "/words_b2/stanovisko.jpg" },
      { sk: "przeforsować", ua: "просунути / відстояти", ru: "продвинуть / отстоять", en: "push through / defend", img: "/words_b2/presadiť.jpg" },
      { sk: "sprzeciwiać się", ua: "заперечувати", ru: "возражать", en: "object", img: "/words_b2/namietať.jpg" },
      { sk: "przyjąć propozycję", ua: "прийняти пропозицію", ru: "принять предложение", en: "accept a proposal", img: "/words_b2/prijať návrh.jpg" },
      { sk: "odrzucić propozycję", ua: "відхилити пропозицію", ru: "отклонить предложение", en: "reject a proposal", img: "/words_b2/odmietnuť návrh.jpg" },
      { sk: "kompromis", ua: "компроміс", ru: "компромисс", en: "compromise", img: "/words_b2/kompromis.jpg" },
    ],
  },
  {
    id: "b2-2",
    title: { ua: "Урок 2 — Відповідальність і рішення", ru: "Урок 2 — Ответственность и решения", en: "Lesson 2 — Responsibility and Decisions" },
    words: [
      { sk: "zobowiązanie", ua: "зобов’язання", ru: "обязательство", en: "obligation", img: "/words_b2/záväzok.jpg" },
      { sk: "werdykt", ua: "вердикт", ru: "вердикт", en: "verdict", img: "/words_b2/verdikt.jpg" },
      { sk: "wpływ", ua: "вплив", ru: "влияние / последствия", en: "impact / consequences", img: "/words_b2/dopad.jpg" },
      { sk: "ocenić", ua: "оцінити / розглянути", ru: "оценить / рассмотреть", en: "assess / consider", img: "/words_b2/posúdiť.jpg" },
      { sk: "przemyśleć", ua: "продумати", ru: "обдумать / продумать", en: "think through", img: "/words_b2/premyslieť.jpg" },
      { sk: "zagrożenie", ua: "загроза", ru: "угроза", en: "threat", img: "/words_b2/ohrozenie.jpg" },
      { sk: "dalej", ua: "далі", ru: "далее / дальше", en: "further / next", img: "/words_b2/ďalej.jpg" },
      { sk: "wziąć odpowiedzialność", ua: "взяти відповідальність", ru: "взять ответственность", en: "take responsibility", img: "/words_b2/prevziať zodpovednosť.jpg" },
      { sk: "dojść do wniosku", ua: "дійти висновку", ru: "прийти к выводу", en: "come to a conclusion", img: "/words_b2/dospieť k záveru.jpg" },
      { sk: "jednoznaczny", ua: "однозначний / чіткий", ru: "однозначный / чёткий", en: "clear / unambiguous", img: "/words_b2/jednoznačný.jpg" },
    ],
  },
  {
    id: "b2-3",
    title: { ua: "Урок 3 — Конфлікти та аргументація", ru: "Урок 3 — Конфликты и аргументация", en: "Lesson 3 — Conflicts and Argumentation" },
    words: [
      { sk: "spór", ua: "суперечка / спір", ru: "спор / конфликт", en: "dispute / conflict", img: "/words_b2/spor.jpg" },
      { sk: "napięcie", ua: "напруга", ru: "напряжение", en: "tension", img: "/words_b2/napätie.jpg" },
      { sk: "złagodzić", ua: "пом’якшити", ru: "смягчить", en: "ease / soften", img: "/words_b2/zmierniť.jpg" },
      { sk: "zaostrzyć się", ua: "загостритися", ru: "обостриться", en: "escalate", img: "/words_b2/vyhrotiť sa.jpg" },
      { sk: "obronić", ua: "захистити / обґрунтувати", ru: "защитить / обосновать", en: "defend / justify", img: "/words_b2/obhájiť.jpg" },
      { sk: "twierdzenie", ua: "твердження", ru: "утверждение", en: "statement", img: "/words_b2/tvrdenie.jpg" },
      { sk: "dowód", ua: "доказ", ru: "доказательство", en: "evidence / proof", img: "/words_b2/dôkaz.jpg" },
      { sk: "kontrargument", ua: "контраргумент", ru: "контраргумент", en: "counterargument", img: "/words_b2/protiargument.jpg" },
      { sk: "przekonujący", ua: "переконливий", ru: "убедительный", en: "convincing", img: "/words_b2/presvedčivý.jpg" },
      { sk: "niezgoda", ua: "розбіжність / незгода", ru: "разногласие / несогласие", en: "disagreement", img: "/words_b2/nezhoda.jpg" },
    ],
  },
  {
    id: "b2-4",
    title: { ua: "Урок 4 — Формальна комунікація", ru: "Урок 4 — Формальная коммуникация", en: "Lesson 4 — Formal Communication" },
    words: [
      { sk: "uprzejmy", ua: "ввічливий", ru: "вежливый", en: "polite", img: "/words_b2/zdvorilý.jpg" },
      { sk: "formułować", ua: "формулювати", ru: "формулировать", en: "formulate", img: "/words_b2/formulovať.jpg" },
      { sk: "zająć stanowisko", ua: "зайняти позицію", ru: "занять позицию", en: "take a position", img: "/words_b2/zaujať stanovisko.jpg" },
      { sk: "złożyć wniosek", ua: "подати запит / заяву", ru: "подать запрос / заявление", en: "submit a request / application", img: "/words_b2/predložiť žiadosť.jpg" },
      { sk: "doprecyzować", ua: "уточнити", ru: "уточнить", en: "clarify / specify", img: "/words_b2/upresniť.jpg" },
      { sk: "podkreślić", ua: "підкреслити / наголосити", ru: "подчеркнуть", en: "emphasize", img: "/words_b2/zdôrazniť.jpg" },
      { sk: "uzupełnić informację", ua: "доповнити інформацію", ru: "дополнить информацию", en: "add information", img: "/words_b2/doplniť informáciu.jpg" },
      { sk: "podać przykład", ua: "навести приклад", ru: "привести пример", en: "give an example", img: "/words_b2/uviesť príklad.jpg" },
      { sk: "zwięzły", ua: "короткий / стислий", ru: "краткий", en: "brief / concise", img: "/words_b2/stručný.jpg" },
      { sk: "jasno sformułowany", ua: "чітко сформульований", ru: "чётко сформулированный", en: "clearly formulated", img: "/words_b2/jasne formulovaný.jpg" },
    ],
  },
  {
    id: "b2-5",
    title: { ua: "Урок 5 — Скарги та рекламації", ru: "Урок 5 — Жалобы и рекламации", en: "Lesson 5 — Complaints and Claims" },
    words: [
      { sk: "brak", ua: "недолік / дефект", ru: "недостаток / дефект", en: "defect / shortcoming", img: "/words_b2/nedostatok.jpg" },
      { sk: "wada", ua: "вада / дефект", ru: "дефект", en: "defect / fault", img: "/words_b2/vada.jpg" },
      { sk: "złożyć reklamację", ua: "подати рекламацію", ru: "подать рекламацию", en: "file a complaint / claim", img: "/words_b2/uplatniť reklamáciu.jpg" },
      { sk: "rozpatrzyć reklamację", ua: "розглянути рекламацію", ru: "рассмотреть рекламацию", en: "process a complaint / claim", img: "/words_b2/vybaviť reklamáciu.jpg" },
      { sk: "usunąć błąd", ua: "усунути помилку / дефект", ru: "устранить дефект", en: "fix a defect / error", img: "/words_b2/odstrániť chybu.jpg" },
      { sk: "roszczenie", ua: "право на вимогу", ru: "право требования", en: "claim / entitlement", img: "/words_b2/nárok.jpg" },
      { sk: "uzasadnione roszczenie", ua: "обґрунтована вимога", ru: "обоснованное требование", en: "valid claim", img: "/words_b2/oprávnený nárok.jpg" },
      { sk: "osoba odpowiedzialna", ua: "відповідальна особа", ru: "ответственное лицо", en: "responsible person", img: "/words_b2/zodpovedná osoba.jpg" },
      { sk: "oświadczenie firmy", ua: "позиція компанії", ru: "позиция компании", en: "company statement", img: "/words_b2/vyjadrenie spoločnosti.jpg" },
      { sk: "uzasadniony", ua: "обґрунтований", ru: "обоснованный", en: "justified / well-founded", img: "/words_b2/opodstatnený.jpg" },
    ],
  },
  {
    id: "b2-6",
    title: { ua: "Урок 6 — Контракти та умови", ru: "Урок 6 — Контракты и условия", en: "Lesson 6 — Contracts and Conditions" },
    words: [
      { sk: "umowa", ua: "договір", ru: "договор", en: "contract", img: "/words_b2/zmluva.jpg" },
      { sk: "postanowienie", ua: "положення", ru: "положение", en: "provision", img: "/words_b2/ustanovenie.jpg" },
      { sk: "ważność", ua: "дійсність / чинність", ru: "действительность", en: "validity", img: "/words_b2/platnosť.jpg" },
      { sk: "zobowiązanie", ua: "зобов'язання", ru: "обязательство", en: "obligation", img: "/words_b2/záväzok.jpg" },
      { sk: "naruszyć umowę", ua: "порушити договір", ru: "нарушить договор", en: "breach a contract", img: "/words_b2/porušiť zmluvu.jpg" },
      { sk: "podpisać umowę", ua: "підписати договір", ru: "подписать договор", en: "sign a contract", img: "/words_b2/podpísať zmluvu.jpg" },
      { sk: "uzgodniony", ua: "узгоджений", ru: "согласованный", en: "agreed", img: "/words_b2/dohodnutý.jpg" },
      { sk: "termin", ua: "термін", ru: "срок", en: "deadline / time limit", img: "/words_b2/lehota.jpg" },
      { sk: "spełnić warunki", ua: "виконати умови", ru: "выполнить условия", en: "meet the conditions", img: "/words_b2/splniť podmienky.jpg" },
      { sk: "strona umowy", ua: "сторона договору", ru: "сторона договора", en: "contracting party", img: "/words_b2/zmluvná strana.jpg" },
    ],
  },
  {
    id: "b2-7",
    title: { ua: "Урок 7 — Планування та стратегія", ru: "Урок 7 — Планирование и стратегия", en: "Lesson 7 — Planning and Strategy" },
    words: [
      { sk: "strategia", ua: "стратегія", ru: "стратегия", en: "strategy", img: "/words_b2/stratégia.jpg" },
      { sk: "planowanie", ua: "планування", ru: "планирование", en: "planning", img: "/words_b2/plánovanie.jpg" },
      { sk: "wyznaczyć cel", ua: "поставити мету", ru: "поставить цель", en: "set a goal", img: "/words_b2/stanoviť cieľ.jpg" },
      { sk: "długoterminowy", ua: "довгостроковий", ru: "долгосрочный", en: "long-term", img: "/words_b2/dlhodobý.jpg" },
      { sk: "krótkoterminowy", ua: "короткостроковий", ru: "краткосрочный", en: "short-term", img: "/words_b2/krátkodobý.jpg" },
      { sk: "procedura", ua: "процедура / хід", ru: "процедура", en: "procedure / process", img: "/words_b2/postup.jpg" },
      { sk: "priorytet", ua: "пріоритет", ru: "приоритет", en: "priority", img: "/words_b2/priorita.jpg" },
      { sk: "efektywny", ua: "ефективний", ru: "эффективный", en: "effective", img: "/words_b2/efektívny.jpg" },
      { sk: "optymalizować", ua: "оптимізувати", ru: "оптимизировать", en: "optimize", img: "/words_b2/optimalizovať.jpg" },
      { sk: "realizować plan", ua: "реалізувати план", ru: "реализовать план", en: "carry out a plan", img: "/words_b2/realizovať plán.jpg" },
    ],
  },
  {
    id: "b2-8",
    title: { ua: "Урок 8 — Аналіз і оцінка", ru: "Урок 8 — Анализ и оценка", en: "Lesson 8 — Analysis and Evaluation" },
    words: [
      { sk: "analiza", ua: "аналіз", ru: "анализ", en: "analysis", img: "/words_b2/analýza.jpg" },
      { sk: "ocena", ua: "оцінка", ru: "оценка", en: "evaluation", img: "/words_b2/hodnotenie.jpg" },
      { sk: "porównać", ua: "порівняти", ru: "сравнить", en: "compare", img: "/words_b2/porovnať.jpg" },
      { sk: "wynik", ua: "результат", ru: "результат", en: "result", img: "/words_b2/výsledok.jpg" },
      { sk: "wskaźnik", ua: "показник", ru: "показатель", en: "indicator", img: "/words_b2/ukazovateľ.jpg" },
      { sk: "trend", ua: "тенденція", ru: "тенденция", en: "trend", img: "/words_b2/trend.jpg" },
      { sk: "ważny", ua: "значний", ru: "значительный", en: "significant", img: "/words_b2/významný.jpg" },
      { sk: "nieistotny", ua: "незначний", ru: "незначительный", en: "negligible", img: "/words_b2/zanedbateľný.jpg" },
      { sk: "obiektywny", ua: "об'єктивний", ru: "объективный", en: "objective", img: "/words_b2/objektívny.jpg" },
      { sk: "subiektywny", ua: "суб'єктивний", ru: "субъективный", en: "subjective", img: "/words_b2/subjektívny.jpg" },
    ],
  },
  {
    id: "b2-9",
    title: { ua: "Урок 9 — Співпраця та команда", ru: "Урок 9 — Сотрудничество и команда", en: "Lesson 9 — Cooperation and Teamwork" },
    words: [
      { sk: "współpraca", ua: "співпраця", ru: "сотрудничество", en: "cooperation", img: "/words_b2/spolupráca.jpg" },
      { sk: "zespół", ua: "команда", ru: "команда", en: "team", img: "/words_b2/tím.jpg" },
      { sk: "delegować", ua: "делегувати", ru: "делегировать", en: "delegate", img: "/words_b2/delegovať.jpg" },
      { sk: "osoba odpowiedzialna", ua: "відповідальна особа", ru: "ответственное лицо", en: "responsible person", img: "/words_b2/zodpovedná osoba.jpg" },
      { sk: "wspólny cel", ua: "спільна мета", ru: "общая цель", en: "shared goal", img: "/words_b2/spoločný cieľ.jpg" },
      { sk: "umówić się", ua: "домовитися", ru: "договориться", en: "come to an agreement", img: "/words_b2/dohodnúť sa.jpg" },
      { sk: "koordynować", ua: "координувати", ru: "координировать", en: "coordinate", img: "/words_b2/koordinovať.jpg" },
      { sk: "wsparcie", ua: "підтримка", ru: "поддержка", en: "support", img: "/words_b2/podpora.jpg" },
      { sk: "przyczynić się", ua: "зробити внесок", ru: "внести вклад", en: "contribute", img: "/words_b2/prispieť.jpg" },
      { sk: "wspólna decyzja", ua: "спільне рішення", ru: "совместное решение", en: "joint decision", img: "/words_b2/spoločné rozhodnutie.jpg" },
    ],
  },
  {
    id: "b2-10",
    title: { ua: "Урок 10 — Професійний розвиток", ru: "Урок 10 — Профессиональное развитие", en: "Lesson 10 — Professional Development" },
    words: [
      { sk: "rozwój", ua: "розвиток", ru: "развитие", en: "development", img: "/words_b2/rozvoj.jpg" },
      { sk: "udoskonalić się", ua: "вдосконалитися", ru: "усовершенствоваться", en: "improve oneself", img: "/words_b2/zdokonaliť sa.jpg" },
      { sk: "pracować nad sobą", ua: "працювати над собою", ru: "работать над собой", en: "work on oneself", img: "/words_b2/pracovať na sebe.jpg" },
      { sk: "kompetencja", ua: "професіоналізм / експертність", ru: "профессионализм", en: "expertise / professionalism", img: "/words_b2/odbornosť.jpg" },
      { sk: "doświadczony", ua: "досвідчений", ru: "опытный", en: "experienced", img: "/words_b2/skúsený.jpg" },
      { sk: "pogłębiać wiedzę", ua: "поглиблювати знання", ru: "углублять знания", en: "deepen knowledge", img: "/words_b2/prehlbovať vedomosti.jpg" },
      { sk: "poprawiać się", ua: "покращуватися", ru: "улучшаться", en: "improve", img: "/words_b2/zlepšovať sa.jpg" },
      { sk: "osiągać wyniki", ua: "досягати результатів", ru: "достигать результатов", en: "achieve results", img: "/words_b2/dosahovať výsledky.jpg" },
      { sk: "rozwój osobisty", ua: "особистий розвиток", ru: "личностный рост", en: "personal growth", img: "/words_b2/osobný rast.jpg" },
      { sk: "rozwój zawodowy", ua: "професійний розвиток", ru: "профессиональный рост", en: "professional growth", img: "/words_b2/profesijný rast.jpg" },
    ],
  },
  {
    id: "b2-11",
    title: { ua: "Урок 11 — Фрукти та смаки", ru: "Урок 11 — Фрукты и вкусы", en: "Lesson 11 — Fruits and Flavors" },
    words: [
      { sk: "dojrzały", ua: "стиглий", ru: "спелый", en: "ripe", img: "/words_b2/dozretý.jpg" },
      { sk: "soczysty", ua: "соковитий", ru: "сочный", en: "juicy", img: "/words_b2/šťavnatý.jpg" },
      { sk: "kwaśnawy", ua: "кислуватий", ru: "кисловатый", en: "slightly sour", img: "/words_b2/kyslastý.jpg" },
      { sk: "słodycz", ua: "солодкість", ru: "сладость", en: "sweetness", img: "/words_b2/sladkosť.jpg" },
      { sk: "owoce sezonowe", ua: "сезонні фрукти", ru: "сезонные фрукты", en: "seasonal fruit", img: "/words_b2/sezónne ovocie.jpg" },
      { sk: "owoce tropikalne", ua: "тропічні фрукти", ru: "тропические фрукты", en: "tropical fruit", img: "/words_b2/tropické ovocie.jpg" },
      { sk: "dojrzałość", ua: "стиглість", ru: "зрелость", en: "ripeness", img: "/words_b2/zrelosť.jpg" },
      { sk: "plony", ua: "урожай", ru: "урожай", en: "harvest", img: "/words_b2/úroda.jpg" },
      { sk: "uprawa", ua: "вирощування", ru: "выращивание", en: "cultivation / growing", img: "/words_b2/pestovanie.jpg" },
      { sk: "witaminy", ua: "вітаміни", ru: "витамины", en: "vitamins", img: "/words_b2/vitamíny.jpg" },
    ],
  },
  {
    id: "b2-12",
    title: { ua: "Урок 12 — Кулінарія та смак", ru: "Урок 12 — Кулинария и вкус", en: "Lesson 12 — Cooking and Taste" },
    words: [
      { sk: "pikantny", ua: "пряний", ru: "пряный", en: "spicy / aromatic", img: "/words_b2/korenistý.jpg" },
      { sk: "delikatny", ua: "ніжний", ru: "нежный", en: "delicate / mild", img: "/words_b2/jemný.jpg" },
      { sk: "intensywny smak", ua: "виразний смак", ru: "выраженный вкус", en: "strong flavor", img: "/words_b2/výrazná chuť.jpg" },
      { sk: "doprawić", ua: "приправити", ru: "приправить", en: "season / flavor", img: "/words_b2/dochutiť.jpg" },
      { sk: "spróbować", ua: "спробувати на смак", ru: "попробовать", en: "taste / try", img: "/words_b2/ochutnať.jpg" },
      { sk: "składnik", ua: "інгредієнт", ru: "ингредиент", en: "ingredient", img: "/words_b2/ingrediencia.jpg" },
      { sk: "recepta", ua: "рецепт", ru: "рецепт", en: "recipe", img: "/words_b2/receptt.jpg" },
      { sk: "przygotować jedzenie", ua: "приготувати їжу", ru: "приготовить еду", en: "prepare food", img: "/words_b2/pripraviť jedlo.jpg" },
      { sk: "serwować jedzenie", ua: "подавати їжу", ru: "подавать еду", en: "serve food", img: "/words_b2/podávať jedlo.jpg" },
      { sk: "kulinarny", ua: "кулінарний", ru: "кулинарный", en: "culinary", img: "/words_b2/kulinársky.jpg" },
    ],
  },
  {
    id: "b2-13",
    title: { ua: "Урок 13 — Спорт та фізична форма", ru: "Урок 13 — Спорт и физическая форма", en: "Lesson 13 — Sports and Physical Fitness" },
    words: [
      { sk: "wytrwałość", ua: "витривалість", ru: "выносливость", en: "endurance", img: "/words_b2/vytrvalosť.jpg" },
      { sk: "kondycja", ua: "фізична форма", ru: "физическая форма", en: "fitness / condition", img: "/words_b2/kondícia.jpg" },
      { sk: "trening", ua: "тренування", ru: "тренировка", en: "training", img: "/words_b2/tréning.jpg" },
      { sk: "konkurs", ua: "змагання", ru: "соревнование", en: "competition", img: "/words_b2/súťaž.jpg" },
      { sk: "sportowiec", ua: "спортсмен", ru: "спортсмен", en: "athlete", img: "/words_b2/športovec.jpg" },
      { sk: "wydajność", ua: "результат / виступ", ru: "результат", en: "performance / result", img: "/words_b2/výkon.jpg" },
      { sk: "poprawić wydajność", ua: "покращити результат", ru: "улучшить результат", en: "improve performance", img: "/words_b2/zlepšiť výkon.jpg" },
      { sk: "zwycięstwo", ua: "перемога", ru: "победа", en: "victory", img: "/words_b2/víťazstvo.jpg" },
      { sk: "porażka", ua: "поразка", ru: "поражение", en: "defeat / loss", img: "/words_b2/prehra.jpg" },
      { sk: "dyscyplina", ua: "дисципліна", ru: "дисциплина", en: "discipline", img: "/words_b2/disciplína.jpg" },
    ],
  },
  {
    id: "b2-14",
    title: { ua: "Урок 14 — Гори та природа", ru: "Урок 14 — Горы и природа", en: "Lesson 14 — Mountains and Nature" },
    words: [
      { sk: "pasmo górskie", ua: "гірський хребет", ru: "горный хребет", en: "mountain range", img: "/words_b2/pohorie.jpg" },
      { sk: "szczyt", ua: "вершина", ru: "вершина", en: "peak / summit", img: "/words_b2/vrchol.jpg" },
      { sk: "dolina", ua: "долина", ru: "долина", en: "valley", img: "/words_b2/údolie.jpg" },
      { sk: "turystyka", ua: "піший туризм", ru: "пеший туризм", en: "hiking", img: "/words_b2/turistika.jpg" },
      { sk: "wyjście", ua: "підйом", ru: "подъём", en: "ascent / climb", img: "/words_b2/výstup.jpg" },
      { sk: "widok", ua: "краєвид", ru: "вид", en: "view", img: "/words_b2/výhľad.jpg" },
      { sk: "chodnik", ua: "стежка", ru: "тропа", en: "path / trail", img: "/words_b2/chodník.jpg" },
      { sk: "górski", ua: "гірський", ru: "горный", en: "mountain", img: "/words_b2/horský.jpg" },
      { sk: "dzika przyroda", ua: "дика природа", ru: "дикая природа", en: "wild nature", img: "/words_b2/divoká príroda.jpg" },
      { sk: "teren chroniony", ua: "заповідна територія", ru: "охраняемая территория", en: "protected area", img: "/words_b2/chránené územie.jpg" },
    ],
  },
  {
    id: "b2-15",
    title: { ua: "Урок 15 — Подорожі", ru: "Урок 15 — Путешествия", en: "Lesson 15 — Travel" },
    words: [
      { sk: "miejsce docelowe", ua: "місце призначення", ru: "место назначения", en: "destination", img: "/words_b2/destinácia.jpg" },
      { sk: "plan podróży", ua: "маршрут подорожі", ru: "маршрут", en: "itinerary", img: "/words_b2/itinerár.jpg" },
      { sk: "zakwaterowanie", ua: "проживання / житло", ru: "проживание", en: "accommodation", img: "/words_b2/ubytovanie.jpg" },
      { sk: "turystyka", ua: "туризм", ru: "туризм", en: "tourism", img: "/words_b2/cestovný ruch.jpg" },
      { sk: "lokalne zwyczaje", ua: "місцеві звичаї", ru: "местные обычаи", en: "local customs", img: "/words_b2/miestne zvyky.jpg" },
      { sk: "zabytek historyczny", ua: "історична пам’ятка", ru: "историческая достопримечательность", en: "historical landmark", img: "/words_b2/historická pamiatka.jpg" },
      { sk: "podróżnik", ua: "мандрівник", ru: "путешественник", en: "traveler", img: "/words_b2/cestovateľ.jpg" },
      { sk: "odkrywać", ua: "відкривати / досліджувати", ru: "открывать", en: "discover / explore", img: "/words_b2/objavovať.jpg" },
      { sk: "lokalna kultura", ua: "місцева культура", ru: "местная культура", en: "local culture", img: "/words_b2/miestna kultúra.jpg" },
      { sk: "doświadczenie podróżnicze", ua: "досвід подорожі", ru: "опыт путешествия", en: "travel experience", img: "/words_b2/cestovateľský zážitok.jpg" },
    ],
  },
  {
    id: "b2-16",
    title: { ua: "Урок 16 — Фрукти", ru: "Урок 16 — Фрукты", en: "Lesson 16 — Fruits" },
    words: [
      { sk: "jabłko", ua: "яблуко", ru: "яблоко", en: "apple", img: "/words_b2/jablko.jpg" },
      { sk: "gruszka", ua: "груша", ru: "груша", en: "pear", img: "/words_b2/hruška.jpg" },
      { sk: "brzoskwinia", ua: "персик", ru: "персик", en: "peach", img: "/words_b2/broskyňa.jpg" },
      { sk: "morela", ua: "абрикос", ru: "абрикос", en: "apricot", img: "/words_b2/marhuľa.jpg" },
      { sk: "śliwka", ua: "слива", ru: "слива", en: "plum", img: "/words_b2/slivka.jpg" },
      { sk: "borówka", ua: "чорниця / лохина", ru: "черника", en: "blueberry / bilberry", img: "/words_b2/čučoriedka.jpg" },
      { sk: "malina", ua: "малина", ru: "малина", en: "raspberry", img: "/words_b2/malina.jpg" },
      { sk: "ananas", ua: "ананас", ru: "ананас", en: "pineapple", img: "/words_b2/ananás.jpg" },
      { sk: "mango", ua: "манго", ru: "манго", en: "mango", img: "/words_b2/mango.jpg" },
      { sk: "melon", ua: "диня / кавун", ru: "дыня / арбуз", en: "melon / watermelon", img: "/words_b2/melón.jpg" },
    ],
  },
  {
    id: "b2-17",
    title: { ua: "Урок 17 — Овочі", ru: "Урок 17 — Овощи", en: "Lesson 17 — Vegetables" },
    words: [
      { sk: "marchew", ua: "морква", ru: "морковь", en: "carrot", img: "/words_b2/mrkva.jpg" },
      { sk: "ogórek", ua: "огірок", ru: "огурец", en: "cucumber", img: "/words_b2/uhorka.jpg" },
      { sk: "pomidor", ua: "помідор", ru: "помидор", en: "tomato", img: "/words_b2/paradajka.jpg" },
      { sk: "papryka", ua: "перець", ru: "перец", en: "pepper", img: "/words_b2/paprika.jpg" },
      { sk: "ziemniak", ua: "картопля", ru: "картофель", en: "potato", img: "/words_b2/zemiak.jpg" },
      { sk: "cebula", ua: "цибуля", ru: "лук", en: "onion", img: "/words_b2/cibuľa.jpg" },
      { sk: "czosnek", ua: "часник", ru: "чеснок", en: "garlic", img: "/words_b2/cesnak.jpg" },
      { sk: "bakłażan", ua: "баклажан", ru: "баклажан", en: "eggplant", img: "/words_b2/baklažán.jpg" },
      { sk: "cukinia", ua: "кабачок", ru: "кабачок", en: "zucchini", img: "/words_b2/cuketa.jpg" },
      { sk: "kapusta", ua: "капуста", ru: "капуста", en: "cabbage", img: "/words_b2/kapusta.jpg" },
    ],
  },
  {
    id: "b2-18",
    title: { ua: "Урок 18 — Напої", ru: "Урок 18 — Напитки", en: "Lesson 18 — Drinks" },
    words: [
      { sk: "woda mineralna", ua: "мінеральна вода", ru: "минеральная вода", en: "mineral water", img: "/words_b2/minerálna voda.jpg" },
      { sk: "sok", ua: "сік", ru: "сок", en: "juice", img: "/words_b2/džús.jpg" },
      { sk: "herbata", ua: "чай", ru: "чай", en: "tea", img: "/words_b2/čaj.jpg" },
      { sk: "kawa", ua: "кава", ru: "кофе", en: "coffee", img: "/words_b2/káva.jpg" },
      { sk: "espresso", ua: "еспресо", ru: "эспрессо", en: "espresso", img: "/words_b2/espresso.jpg" },
      { sk: "cappuccino", ua: "капучино", ru: "капучино", en: "cappuccino", img: "/words_b2/cappuccino.jpg" },
      { sk: "lemoniada", ua: "лимонад", ru: "лимонад", en: "lemonade", img: "/words_b2/limonáda.jpg" },
      { sk: "piwo", ua: "пиво", ru: "пиво", en: "beer", img: "/words_b2/pivo.jpg" },
      { sk: "wino", ua: "вино", ru: "вино", en: "wine", img: "/words_b2/víno.jpg" },
      { sk: "koktajl", ua: "коктейль", ru: "коктейль", en: "cocktail", img: "/words_b2/koktail.jpg" },
    ],
  },
  {
    id: "b2-19",
    title: { ua: "Урок 19 — Емоції та внутрішній стан", ru: "Урок 19 — Эмоции и внутреннее состояние", en: "Lesson 19 — Emotions and Inner State" },
    words: [
      { sk: "lęk", ua: "тривога", ru: "тревога", en: "anxiety", img: "/words_b2/úzkosť.jpg" },
      { sk: "rozczarowanie", ua: "розчарування", ru: "разочарование", en: "disappointment", img: "/words_b2/sklamanie.jpg" },
      { sk: "wzruszenie", ua: "зворушення", ru: "умиление / растроганность", en: "emotion / being moved", img: "/words_b2/dojatie.jpg" },
      { sk: "ulga", ua: "полегшення", ru: "облегчение", en: "relief", img: "/words_b2/odľahčenie.jpg" },
      { sk: "obrzydzenie", ua: "огида / відраза", ru: "отвращение", en: "disgust", img: "/words_b2/znechutenie.jpg" },
      { sk: "rozdrażniony", ua: "засмучений / роздратований", ru: "расстроенный / раздражённый", en: "upset / irritated", img: "/words_b2/rozladený.jpg" },
      { sk: "wyczerpanie", ua: "виснаження", ru: "истощение", en: "exhaustion", img: "/words_b2/vyčerpanosť.jpg" },
      { sk: "reakcja emocjonalna", ua: "емоційна реакція", ru: "эмоциональная реакция", en: "emotional reaction", img: "/words_b2/citová reakcia.jpg" },
      { sk: "dobre samopoczucie psychiczne", ua: "душевний спокій / психологічний комфорт", ru: "душевное спокойствие", en: "mental well-being / peace of mind", img: "/words_b2/duševná pohoda.jpg" },
      { sk: "tłumić emocje", ua: "пригнічувати емоції", ru: "подавлять эмоции", en: "suppress emotions", img: "/words_b2/potlačiť emócie.jpg" },
    ],
  },
  {
    id: "b2-20",
    title: { ua: "Урок 20 — Культура і мистецтво", ru: "Урок 20 — Культура и искусство", en: "Lesson 20 — Culture and Art" },
    words: [
      { sk: "sztuka", ua: "мистецтво", ru: "искусство", en: "art", img: "/words_b2/umenie.jpg" },
      { sk: "dzieło sztuki", ua: "твір мистецтва", ru: "произведение искусства", en: "work of art", img: "/words_b2/umelecké dielo.jpg" },
      { sk: "wystawa", ua: "виставка", ru: "выставка", en: "exhibition", img: "/words_b2/výstava.jpg" },
      { sk: "galeria", ua: "галерея", ru: "галерея", en: "gallery", img: "/words_b2/galéria.jpg" },
      { sk: "teatr", ua: "театр", ru: "театр", en: "theater", img: "/words_b2/divadlo.jpg" },
      { sk: "przedstawienie", ua: "вистава", ru: "представление", en: "performance", img: "/words_b2/predstavenie.jpg" },
      { sk: "publiczność", ua: "публіка", ru: "публика", en: "audience", img: "/words_b2/publikum.jpg" },
      { sk: "styl artystyczny", ua: "художній стиль", ru: "художественный стиль", en: "artistic style", img: "/words_b2/umelecký štýl.jpg" },
      { sk: "interpretacja", ua: "інтерпретація", ru: "интерпретация", en: "interpretation", img: "/words_b2/interpretácia.jpg" },
      { sk: "doświadczenie kulturowe", ua: "культурний досвід", ru: "культурный опыт", en: "cultural experience", img: "/words_b2/kultúrny zážitok.jpg" },
    ],
  },
  {
    id: "b2-21",
    title: { ua: "Урок 21 — Мислення та аналіз", ru: "Урок 21 — Мышление и анализ", en: "Lesson 21 — Thinking and Analysis" },
    words: [
      { sk: "rozumowanie", ua: "роздумування", ru: "размышление", en: "reasoning / reflection", img: "/words_b2/uvažovanie.jpg" },
      { sk: "założenie", ua: "припущення", ru: "предположение", en: "assumption", img: "/words_b2/predpokladať.jpg" },
      { sk: "oceniać", ua: "оцінювати / судити", ru: "оценивать", en: "assess / judge", img: "/words_b2/posudzovať.jpg" },
      { sk: "punkt widzenia", ua: "точка зору / аспект", ru: "точка зрения / аспект", en: "point of view / aspect", img: "/words_b2/hľadisko.jpg" },
      { sk: "związek", ua: "взаємозв'язок", ru: "взаимосвязь", en: "connection / relationship", img: "/words_b2/súvislosť.jpg" },
      { sk: "przypuszczenie", ua: "здогад / припущення", ru: "догадка / предположение", en: "guess / assumption", img: "/words_b2/domnienka.jpg" },
      { sk: "logiczny", ua: "логічний", ru: "логический", en: "logical", img: "/words_b2/logický.jpg" },
      { sk: "analizować", ua: "аналізувати", ru: "анализировать", en: "analyze", img: "/words_b2/analyzovať.jpg" },
      { sk: "ocenić", ua: "оцінити результат", ru: "оценить результат", en: "evaluate the result", img: "/words_b2/vyhodnotiť.jpg" },
      { sk: "szacunek", ua: "оцінка / приблизний розрахунок", ru: "оценка / приблизительный расчёт", en: "estimate", img: "/words_b2/odhad.jpg" },
    ],
  },
  {
    id: "b2-22",
    title: { ua: "Урок 22 — Суспільство", ru: "Урок 22 — Общество", en: "Lesson 22 — Society" },
    words: [
      { sk: "społeczeństwo", ua: "суспільство", ru: "общество", en: "society", img: "/words_b2/spoločnosť.jpg" },
      { sk: "wartość", ua: "цінність", ru: "ценность", en: "value", img: "/words_b2/hodnota.jpg" },
      { sk: "pokolenie", ua: "покоління", ru: "поколение", en: "generation", img: "/words_b2/generácia.jpg" },
      { sk: "styl życia", ua: "стиль життя", ru: "образ жизни", en: "lifestyle", img: "/words_b2/životný štýl.jpg" },
      { sk: "teraźniejszość", ua: "сучасність", ru: "современность", en: "the present / modern times", img: "/words_b2/súčasnosť.jpg" },
      { sk: "rozwój społeczny", ua: "суспільний розвиток", ru: "общественное развитие", en: "social development", img: "/words_b2/spoločenský vývoj.jpg" },
      { sk: "życie publiczne", ua: "громадське життя", ru: "общественная жизнь", en: "public life", img: "/words_b2/verejný život.jpg" },
      { sk: "zjawisko społeczne", ua: "суспільне явище", ru: "общественное явление", en: "social phenomenon", img: "/words_b2/spoločenský jav.jpg" },
      { sk: "zmiana społeczna", ua: "суспільна зміна", ru: "общественное изменение", en: "social change", img: "/words_b2/spoločenská zmena.jpg" },
      { sk: "środowisko społeczne", ua: "соціальне середовище", ru: "социальная среда", en: "social environment", img: "/words_b2/spoločenské prostredie.jpg" },
    ],
  },
  {
    id: "b2-23",
    title: { ua: "Урок 23 — Характер людини", ru: "Урок 23 — Характер человека", en: "Lesson 23 — Human Character" },
    words: [
      { sk: "niezawodny", ua: "надійний", ru: "надёжный", en: "reliable", img: "/words_b2/spoľahlivý.jpg" },
      { sk: "zasadniczy", ua: "принциповий", ru: "принципиальный", en: "principled", img: "/words_b2/zásadový.jpg" },
      { sk: "pewny siebie", ua: "впевнений у собі", ru: "уверенный в себе", en: "self-confident", img: "/words_b2/sebaistý.jpg" },
      { sk: "tolerancyjny", ua: "толерантний", ru: "толерантный", en: "tolerant", img: "/words_b2/tolerantný.jpg" },
      { sk: "zdeterminowany", ua: "цілеспрямований", ru: "целеустремлённый", en: "goal-oriented / determined", img: "/words_b2/cieľavedomý.jpg" },
      { sk: "wrażliwy", ua: "чутливий", ru: "чувствительный", en: "sensitive", img: "/words_b2/citlivý.jpg" },
      { sk: "zdecydowany", ua: "рішучий", ru: "решительный", en: "decisive", img: "/words_b2/rozhodný.jpg" },
      { sk: "skromny", ua: "скромний", ru: "скромный", en: "modest", img: "/words_b2/skromný.jpg" },
      { sk: "otwarty", ua: "відкритий", ru: "открытый", en: "open", img: "/words_b2/otvorený.jpg" },
      { sk: "zrównoważony", ua: "врівноважений", ru: "уравновешенный", en: "balanced / composed", img: "/words_b2/vyrovnaný.jpg" },
    ],
  },
  {
    id: "b2-24",
    title: { ua: "Урок 24 — Технології", ru: "Урок 24 — Технологии", en: "Lesson 24 — Technology" },
    words: [
      { sk: "użytkownik", ua: "користувач", ru: "пользователь", en: "user", img: "/words_b2/používateľ.jpg" },
      { sk: "urządzenie", ua: "пристрій", ru: "устройство", en: "device", img: "/words_b2/zariadenie.jpg" },
      { sk: "dane", ua: "дані", ru: "данные", en: "data", img: "/words_b2/údaje.jpg" },
      { sk: "środowisko cyfrowe", ua: "цифрове середовище", ru: "цифровая среда", en: "digital environment", img: "/words_b2/digitálne prostredie.jpg" },
      { sk: "usługa online", ua: "онлайн сервіс", ru: "онлайн сервис", en: "online service", img: "/words_b2/online služba.jpg" },
      { sk: "przetwarzanie danych", ua: "обробка даних", ru: "обработка данных", en: "data processing", img: "/words_b2/spracovanie údajov.jpg" },
      { sk: "rozwiązanie techniczne", ua: "технічне рішення", ru: "техническое решение", en: "technical solution", img: "/words_b2/technické riešenie.jpg" },
      { sk: "funkcjonalność", ua: "функціональність", ru: "функциональность", en: "functionality", img: "/words_b2/funkčnosť.jpg" },
      { sk: "wydajność systemu", ua: "продуктивність системи", ru: "производительность системы", en: "system performance", img: "/words_b2/výkon systému.jpg" },
      { sk: "technologia cyfrowa", ua: "цифрова технологія", ru: "цифровая технология", en: "digital technology", img: "/words_b2/digitálna technológia.jpg" },
    ],
  },
  {
    id: "b2-25",
    title: { ua: "Урок 25 — Аргументація і дискусія", ru: "Урок 25 — Аргументация и дискуссия", en: "Lesson 25 — Argumentation and Discussion" },
    words: [
      { sk: "uzasadnić", ua: "обґрунтувати", ru: "обосновать", en: "justify", img: "/words_b2/zdôvodniť.jpg" },
      { sk: "reakcja", ua: "реакція", ru: "реакция", en: "reaction", img: "/words_b2/reakcia.jpg" },
      { sk: "stanowisko", ua: "позиція / точка зору", ru: "позиция / точка зрения", en: "position / point of view", img: "/words_b2/stanovisko.jpg" },
      { sk: "twierdzenie", ua: "твердження", ru: "утверждение", en: "statement", img: "/words_b2/tvrdenie.jpg" },
      { sk: "wyjaśnienie", ua: "пояснення", ru: "объяснение", en: "explanation", img: "/words_b2/vysvetlenie.jpg" },
      { sk: "sprzeciw", ua: "заперечення", ru: "возражение", en: "objection", img: "/words_b2/námietka.jpg" },
      { sk: "kontrargument", ua: "контраргумент", ru: "контраргумент", en: "counterargument", img: "/words_b2/protiargument.jpg" },
      { sk: "dyskusja", ua: "дискусія", ru: "дискуссия", en: "discussion", img: "/words_b2/diskusia.jpg" },
      { sk: "argumentować", ua: "аргументувати", ru: "аргументировать", en: "argue", img: "/words_b2/argumentovať.jpg" },
      { sk: "obronić opinię", ua: "захистити свою думку", ru: "защитить мнение", en: "defend an opinion", img: "/words_b2/obhájiť názor.jpg" },
    ],
  },
  {
    id: "b2-26",
    title: { ua: "Урок 26 — Психологія людини", ru: "Урок 26 — Психология человека", en: "Lesson 26 — Human Psychology" },
    words: [
      { sk: "autorefleksja", ua: "саморефлексія", ru: "саморефлексия", en: "self-reflection", img: "/words_b2/sebareflexia.jpg" },
      { sk: "konflikt wewnętrzny", ua: "внутрішній конфлікт", ru: "внутренний конфликт", en: "inner conflict", img: "/words_b2/vnútorný konflikt.jpg" },
      { sk: "samokontrola", ua: "самоконтроль", ru: "самоконтроль", en: "self-control", img: "/words_b2/sebakontrola.jpg" },
      { sk: "równowaga psychiczna", ua: "психологічна рівновага", ru: "душевное равновесие", en: "mental balance", img: "/words_b2/duševná rovnováha.jpg" },
      { sk: "podświadomość", ua: "підсвідомість", ru: "подсознание", en: "subconscious", img: "/words_b2/podvedomie.jpg" },
      { sk: "wewnętrzna presja", ua: "внутрішній тиск", ru: "внутреннее давление", en: "inner pressure", img: "/words_b2/vnútorný tlak.jpg" },
      { sk: "granica osobista", ua: "особиста межа", ru: "личная граница", en: "personal boundary", img: "/words_b2/osobná hranica.jpg" },
      { sk: "odporność psychiczna", ua: "психологічна стійкість", ru: "психологическая устойчивость", en: "mental resilience", img: "/words_b2/psychická odolnosť.jpg" },
      { sk: "stan psychiczny", ua: "психічний стан", ru: "психическое состояние", en: "mental state", img: "/words_b2/duševný stav.jpg" },
      { sk: "samoświadomość", ua: "самоусвідомлення", ru: "самоосознание", en: "self-awareness", img: "/words_b2/sebauvedomenie.jpg" },
    ],
  },
  {
    id: "b2-27",
    title: { ua: "Урок 27 — Дипломатія", ru: "Урок 27 — Дипломатия", en: "Lesson 27 — Diplomacy" },
    words: [
      { sk: "negocjacje", ua: "переговори", ru: "переговоры", en: "negotiation", img: "/words_b2/vyjednávanie.jpg" },
      { sk: "przychylne nastawienie", ua: "компромісна позиція", ru: "компромиссная позиция", en: "cooperative attitude", img: "/words_b2/ústretový postoj.jpg" },
      { sk: "neutralne stanowisko", ua: "нейтральна позиція", ru: "нейтральная позиция", en: "neutral position", img: "/words_b2/neutrálne stanovisko.jpg" },
      { sk: "zrównoważone rozwiązanie", ua: "збалансоване рішення", ru: "сбалансированное решение", en: "balanced solution", img: "/words_b2/vyvážené riešenie.jpg" },
      { sk: "napięta sytuacja", ua: "напружена ситуація", ru: "напряжённая ситуация", en: "tense situation", img: "/words_b2/napätá situácia.jpg" },
      { sk: "pojednawczy ton", ua: "примирливий тон", ru: "примирительный тон", en: "conciliatory tone", img: "/words_b2/zmierlivý tón.jpg" },
      { sk: "strategia negocjacyjna", ua: "стратегія переговорів", ru: "стратегия переговоров", en: "negotiation strategy", img: "/words_b2/rokovacia stratégia.jpg" },
      { sk: "wzajemne porozumienie", ua: "взаємна домовленість", ru: "взаимное соглашение", en: "mutual agreement", img: "/words_b2/vzájomná dohoda.jpg" },
      { sk: "kompromisowe rozwiązanie", ua: "компромісне рішення", ru: "компромиссное решение", en: "compromise solution", img: "/words_b2/kompromisné riešenie.jpg" },
      { sk: "zachować neutralność", ua: "зберігати нейтралітет", ru: "сохранять нейтралитет", en: "maintain neutrality", img: "/words_b2/zachovať neutralitu.jpg" },
    ],
  },
  {
    id: "b2-28",
    title: { ua: "Урок 28 — Глобальні проблеми", ru: "Урок 28 — Глобальные проблемы", en: "Lesson 28 — Global Problems" },
    words: [
      { sk: "globalne wyzwanie", ua: "глобальний виклик", ru: "глобальный вызов", en: "global challenge", img: "/words_b2/globálna výzva.jpg" },
      { sk: "kryzys humanitarny", ua: "гуманітарна криза", ru: "гуманитарный кризис", en: "humanitarian crisis", img: "/words_b2/humanitárna kríza.jpg" },
      { sk: "brak zasobów", ua: "нестача ресурсів", ru: "нехватка ресурсов", en: "lack of resources", img: "/words_b2/nedostatok zdrojov.jpg" },
      { sk: "nierówność społeczna", ua: "соціальна нерівність", ru: "социальное неравенство", en: "social inequality", img: "/words_b2/sociálna nerovnosť.jpg" },
      { sk: "fala migracyjna", ua: "міграційна хвиля", ru: "миграционная волна", en: "migration wave", img: "/words_b2/migračná vlna.jpg" },
      { sk: "współpraca międzynarodowa", ua: "міжнародна співпраця", ru: "международное сотрудничество", en: "international cooperation", img: "/words_b2/medzinárodná spolupráca.jpg" },
      { sk: "długoterminowy problem", ua: "довготривала проблема", ru: "долгосрочная проблема", en: "long-term problem", img: "/words_b2/dlhodobý problém.jpg" },
      { sk: "wspólna odpowiedzialność", ua: "спільна відповідальність", ru: "общая ответственность", en: "shared responsibility", img: "/words_b2/spoločná zodpovednosť.jpg" },
      { sk: "globalny wpływ", ua: "глобальний вплив", ru: "глобальное влияние", en: "worldwide impact", img: "/words_b2/celosvetový dopad.jpg" },
      { sk: "zrównoważone rozwiązanie", ua: "стале рішення", ru: "устойчивое решение", en: "sustainable solution", img: "/words_b2/udržateľné riešenie.jpg" },
    ],
  },
  {
    id: "b2-29",
    title: { ua: "Урок 29 — Міжособистісні конфлікти", ru: "Урок 29 — Межличностные конфликты", en: "Lesson 29 — Interpersonal Conflicts" },
    words: [
      { sk: "napięta relacja", ua: "напружені стосунки", ru: "напряжённые отношения", en: "strained relationship", img: "/words_b2/napätý vzťah.jpg" },
      { sk: "niezrozumienie", ua: "непорозуміння", ru: "недопонимание", en: "misunderstanding", img: "/words_b2/nepochopenie.jpg" },
      { sk: "przeprosiny", ua: "вибачення", ru: "извинение", en: "apology", img: "/words_b2/ospravedlnenie.jpg" },
      { sk: "rozejm", ua: "примирення", ru: "примирение", en: "reconciliation", img: "/words_b2/zmier.jpg" },
      { sk: "napięta atmosfera", ua: "напружена атмосфера", ru: "напряжённая атмосфера", en: "tense atmosphere", img: "/words_b2/napätá atmosféra.jpg" },
      { sk: "rozwiązać konflikt", ua: "вирішити конфлікт", ru: "решить конфликт", en: "resolve a conflict", img: "/words_b2/vyriešiť konflikt.jpg" },
      { sk: "wzajemne zrozumienie", ua: "взаєморозуміння", ru: "взаимопонимание", en: "mutual understanding", img: "/words_b2/vzájomné pochopenie.jpg" },
      { sk: "naprawić błąd", ua: "виправити помилку", ru: "исправить ошибку", en: "correct a mistake", img: "/words_b2/napraviť chybu.jpg" },
      { sk: "napięcie między ludźmi", ua: "напруга між людьми", ru: "напряжение между людьми", en: "tension between people", img: "/words_b2/napätie medzi ľuďmi.jpg" },
      { sk: "kryzys w związku", ua: "криза у відносинах", ru: "кризис в отношениях", en: "relationship crisis", img: "/words_b2/vzťahová kríza.jpg" },
    ],
  },
  {
    id: "b2-30",
    title: { ua: "Урок 30 — Культура і суспільні явища", ru: "Урок 30 — Культура и общественные явления", en: "Lesson 30 — Culture and Social Phenomena" },
    words: [
      { sk: "tożsamość kulturowa", ua: "культурна ідентичність", ru: "культурная идентичность", en: "cultural identity", img: "/words_b2/kultúrna identita.jpg" },
      { sk: "trend społeczny", ua: "соціальний тренд", ru: "социальный тренд", en: "social trend", img: "/words_b2/spoločenský trend.jpg" },
      { sk: "norma społeczna", ua: "соціальна норма", ru: "социальная норма", en: "social norm", img: "/words_b2/spoločenská norma.jpg" },
      { sk: "dziedzictwo kulturowe", ua: "культурна спадщина", ru: "культурное наследие", en: "cultural heritage", img: "/words_b2/kultúrne dedičstvo.jpg" },
      { sk: "kierunek artystyczny", ua: "художній напрям", ru: "художественное направление", en: "artistic movement", img: "/words_b2/umelecký smer.jpg" },
      { sk: "wpływ społeczny", ua: "соціальний вплив", ru: "социальное влияние", en: "social influence", img: "/words_b2/spoločenský vplyv.jpg" },
      { sk: "debata publiczna", ua: "публічна дискусія", ru: "публичная дискуссия", en: "public discussion", img: "/words_b2/verejná diskusia.jpg" },
      { sk: "kontekst społeczny", ua: "соціальний контекст", ru: "социальный контекст", en: "social context", img: "/words_b2/spoločenský kontext.jpg" },
      { sk: "różnica kulturowa", ua: "культурна різниця", ru: "культурное различие", en: "cultural difference", img: "/words_b2/kultúrny rozdiel.jpg" },
      { sk: "rzeczywistość społeczna", ua: "соціальна реальність", ru: "социальная реальность", en: "social reality", img: "/words_b2/spoločenská realita.jpg" },
    ],
  },
  {
    id: "b2-31",
    title: { ua: "Урок 31 — Командні види спорту", ru: "Урок 31 — Командные виды спорта", en: "Lesson 31 — Team Sports" },
    words: [
      { sk: "podanie", ua: "пас", ru: "пас", en: "pass", img: "/words_b2/prihrávka.jpg" },
      { sk: "rzut rożny", ua: "кутовий", ru: "угловой удар", en: "corner kick", img: "/words_b2/rohový kop.jpg" },
      { sk: "rzut karny", ua: "пенальті", ru: "пенальти", en: "penalty kick", img: "/words_b2/pokutový kop.jpg" },
      { sk: "obrońca", ua: "захисник", ru: "защитник", en: "defender", img: "/words_b2/obranca.jpg" },
      { sk: "napastnik", ua: "нападник", ru: "нападающий", en: "attacker / forward", img: "/words_b2/útočník.jpg" },
      { sk: "sędzia", ua: "суддя", ru: "судья", en: "referee", img: "/words_b2/rozhodca.jpg" },
      { sk: "strzał", ua: "удар / кидок", ru: "удар / бросок", en: "shot / throw", img: "/words_b2/strela.jpg" },
      { sk: "strzelić gola", ua: "забити / набрати очки", ru: "забить / набрать очки", en: "score", img: "/words_b2/skórovať.jpg" },
      { sk: "kosz do koszykówki", ua: "баскетбольне кільце", ru: "баскетбольное кольцо", en: "basketball hoop", img: "/words_b2/basketbalový kôš.jpg" },
      { sk: "mecz", ua: "матч", ru: "матч", en: "match", img: "/words_b2/zápas.jpg" },
    ],
  },
  {
    id: "b2-32",
    title: { ua: "Урок 32 — Теніс", ru: "Урок 32 — Теннис", en: "Lesson 32 — Tennis" },
    words: [
      { sk: "kort tenisowy", ua: "тенісний корт", ru: "теннисный корт", en: "tennis court", img: "/words_b2/tenisový kurt.jpg" },
      { sk: "rakieta", ua: "ракетка", ru: "ракетка", en: "racket", img: "/words_b2/raketa.jpg" },
      { sk: "piłka", ua: "м’яч", ru: "мяч", en: "ball", img: "/words_b2/loptička.jpg" },
      { sk: "serwis", ua: "подача", ru: "подача", en: "serve", img: "/words_b2/podanie.jpg" },
      { sk: "set", ua: "сет", ru: "сет", en: "set", img: "/words_b2/set.jpg" },
      { sk: "turniej", ua: "турнір", ru: "турнир", en: "tournament", img: "/words_b2/turnaj.jpg" },
      { sk: "przeciwnik", ua: "суперник", ru: "соперник", en: "opponent", img: "/words_b2/súper.jpg" },
      { sk: "punkt decydujący", ua: "вирішальний пункт", ru: "решающий очко", en: "decisive point", img: "/words_b2/rozhodujúci bod.jpg" },
      { sk: "mocne uderzenie", ua: "сильний удар", ru: "сильный удар", en: "powerful shot", img: "/words_b2/silný úder.jpg" },
      { sk: "wygrać mecz", ua: "виграти матч", ru: "выиграть матч", en: "win a match", img: "/words_b2/vyhrať zápas.jpg" },
    ],
  },
  {
    id: "b2-33",
    title: { ua: "Урок 33 — Риболовля", ru: "Урок 33 — Рыбалка", en: "Lesson 33 — Fishing" },
    words: [
      { sk: "wędka", ua: "вудка", ru: "удочка", en: "fishing rod", img: "/words_b2/udica.jpg" },
      { sk: "wyciągarka", ua: "котушка", ru: "катушка", en: "reel", img: "/words_b2/navijak.jpg" },
      { sk: "haczyk", ua: "гачок", ru: "крючок", en: "hook", img: "/words_b2/háčik.jpg" },
      { sk: "przynęta", ua: "наживка", ru: "наживка", en: "bait", img: "/words_b2/návnada.jpg" },
      { sk: "połów", ua: "улов", ru: "улов", en: "catch", img: "/words_b2/úlovok.jpg" },
      { sk: "rybak", ua: "рибалка", ru: "рыбак", en: "fisherman / angler", img: "/words_b2/rybár.jpg" },
      { sk: "jezioro", ua: "озеро", ru: "озеро", en: "lake", img: "/words_b2/jazero.jpg" },
      { sk: "brzeg", ua: "берег", ru: "берег", en: "shore / bank", img: "/words_b2/breh.jpg" },
      { sk: "łódź", ua: "човен", ru: "лодка", en: "boat", img: "/words_b2/čln.jpg" },
      { sk: "złowić rybę", ua: "зловити рибу", ru: "поймать рыбу", en: "catch a fish", img: "/words_b2/chytiť rybu.jpg" },
    ],
  },
  {
    id: "b2-34",
    title: { ua: "Урок 34 — Автомобілі", ru: "Урок 34 — Автомобили", en: "Lesson 34 — Cars" },
    words: [
      { sk: "marka samochodu", ua: "марка автомобіля", ru: "марка автомобиля", en: "car brand", img: "/words_b2/automobilová značka.jpg" },
      { sk: "samochód osobowy", ua: "легковий автомобіль", ru: "легковой автомобиль", en: "passenger car", img: "/words_b2/osobné vozidlo.jpg" },
      { sk: "sedan", ua: "седан", ru: "седан", en: "sedan", img: "/words_b2/sedan.jpg" },
      { sk: "SUV", ua: "позашляховик", ru: "внедорожник", en: "SUV", img: "/words_b2/suv.jpg" },
      { sk: "hatchback", ua: "хетчбек", ru: "хэтчбек", en: "hatchback", img: "/words_b2/hatchback.jpg" },
      { sk: "Volkswagen", ua: "Фольксваген", ru: "Фольксваген", en: "Volkswagen", img: "/words_b2/volkswagen.jpg" },
      { sk: "BMW", ua: "БМВ", ru: "БМВ", en: "BMW", img: "/words_b2/bmw.jpg" },
      { sk: "Mercedes", ua: "Мерседес", ru: "Мерседес", en: "Mercedes", img: "/words_b2/mercedes.jpg" },
      { sk: "Toyota", ua: "Тойота", ru: "Тойота", en: "Toyota", img: "/words_b2/toyota.jpg" },
      { sk: "silnik pojazdu", ua: "двигун автомобіля", ru: "двигатель автомобиля", en: "car engine", img: "/words_b2/motor vozidla.jpg" },
    ],
  },
  {
    id: "b2-35",
    title: { ua: "Урок 35 — Морський транспорт", ru: "Урок 35 — Морской транспорт", en: "Lesson 35 — Maritime Transport" },
    words: [
      { sk: "łódź", ua: "корабель", ru: "корабль", en: "ship", img: "/words_b2/loď.jpg" },
      { sk: "łódź podwodna", ua: "субмарина", ru: "подводная лодка", en: "submarine", img: "/words_b2/ponorka.jpg" },
      { sk: "port", ua: "порт", ru: "порт", en: "port", img: "/words_b2/prístav.jpg" },
      { sk: "pokład", ua: "палуба", ru: "палуба", en: "deck", img: "/words_b2/paluba.jpg" },
      { sk: "kapitan", ua: "капітан", ru: "капитан", en: "captain", img: "/words_b2/kapitán.jpg" },
      { sk: "marynarz", ua: "моряк", ru: "моряк", en: "sailor", img: "/words_b2/námorník.jpg" },
      { sk: "statek", ua: "судно", ru: "судно", en: "vessel", img: "/words_b2/plavidlo.jpg" },
      { sk: "trasa morska", ua: "морський маршрут", ru: "морской маршрут", en: "sea route", img: "/words_b2/námorná trasa.jpg" },
      { sk: "zanurzyć się", ua: "зануритися", ru: "погрузиться", en: "dive / submerge", img: "/words_b2/ponoriť sa.jpg" },
      { sk: "transport morski", ua: "морський транспорт", ru: "морской транспорт", en: "maritime transport", img: "/words_b2/námorná doprava.jpg" },
    ],
  },
  {
    id: "b2-36",
    title: { ua: "Урок 36 — Казино", ru: "Урок 36 — Казино", en: "Lesson 36 — Casino" },
    words: [
      { sk: "kasyno", ua: "казино", ru: "казино", en: "casino", img: "/words_b2/kasíno.jpg" },
      { sk: "ruletka", ua: "рулетка", ru: "рулетка", en: "roulette", img: "/words_b2/ruleta.jpg" },
      { sk: "żeton", ua: "фішка", ru: "жетон", en: "chip / token", img: "/words_b2/žetón.jpg" },
      { sk: "zakład", ua: "ставка", ru: "ставка", en: "bet", img: "/words_b2/stávka.jpg" },
      { sk: "wygrać jackpot", ua: "виграти джекпот", ru: "выиграть джекпот", en: "win the jackpot", img: "/words_b2/vyhrať jackpot.jpg" },
      { sk: "przegrać pieniądze", ua: "програти гроші", ru: "проиграть деньги", en: "lose money", img: "/words_b2/prehrať peniaze.jpg" },
      { sk: "automat do gier", ua: "ігровий автомат", ru: "игровой автомат", en: "slot machine", img: "/words_b2/hrací automat.jpg" },
      { sk: "karta", ua: "карта", ru: "карта", en: "card", img: "/words_b2/karta.jpg" },
      { sk: "krupier", ua: "круп'є", ru: "крупье", en: "croupier / dealer", img: "/words_b2/krupiér.jpg" },
      { sk: "grać o pieniądze", ua: "грати на гроші", ru: "играть на деньги", en: "gamble / play for money", img: "/words_b2/hrať o peniaze.jpg" },
    ],
  },
  {
    id: "b2-37",
    title: { ua: "Урок 37 — Жанри", ru: "Урок 37 — Жанры", en: "Lesson 37 — Genres" },
    words: [
      { sk: "gatunek", ua: "жанр", ru: "жанр", en: "genre", img: "/words_b2/žáner.jpg" },
      { sk: "komedia", ua: "комедія", ru: "комедия", en: "comedy", img: "/words_b2/komédia.jpg" },
      { sk: "dramat", ua: "драма", ru: "драма", en: "drama", img: "/words_b2/dráma.jpg" },
      { sk: "thriller", ua: "трилер", ru: "триллер", en: "thriller", img: "/words_b2/triler.jpg" },
      { sk: "fantasy", ua: "фентезі", ru: "фэнтези", en: "fantasy", img: "/words_b2/fantasy.jpg" },
      { sk: "science fiction", ua: "наукова фантастика", ru: "научная фантастика", en: "science fiction", img: "/words_b2/sci-fi.jpg" },
      { sk: "film dokumentalny", ua: "документальний фільм", ru: "документальный фильм", en: "documentary film", img: "/words_b2/dokumentárny film.jpg" },
      { sk: "horror", ua: "жахи", ru: "ужасы", en: "horror", img: "/words_b2/horor.jpg" },
      { sk: "film romantyczny", ua: "романтичний фільм", ru: "романтический фильм", en: "romantic film", img: "/words_b2/romantický film.jpg" },
      { sk: "film przygodowy", ua: "пригодницький фільм", ru: "приключенческий фильм", en: "adventure film", img: "/words_b2/dobrodružný film.jpg" },
    ],
  },
  {
    id: "b2-38",
    title: { ua: "Урок 38 — Рельєф", ru: "Урок 38 — Рельеф", en: "Lesson 38 — Relief / Terrain" },
    words: [
      { sk: "rzeźba terenu", ua: "рельєф", ru: "рельеф", en: "relief / terrain", img: "/words_b2/reliéf.jpg" },
      { sk: "szczyt", ua: "пагорб", ru: "холм", en: "hill", img: "/words_b2/vrch.jpg" },
      { sk: "równina", ua: "рівнина", ru: "равнина", en: "plain", img: "/words_b2/rovina.jpg" },
      { sk: "płaskowyż", ua: "плато", ru: "плато", en: "plateau", img: "/words_b2/náhorná plošina.jpg" },
      { sk: "kanion", ua: "каньйон", ru: "каньон", en: "canyon", img: "/words_b2/kaňon.jpg" },
      { sk: "dolina", ua: "долина", ru: "долина", en: "valley", img: "/words_b2/údolie.jpg" },
      { sk: "grzbiet górski", ua: "гірський хребет", ru: "горный хребет", en: "mountain ridge", img: "/words_b2/horský hrebeň.jpg" },
      { sk: "skalisty teren", ua: "скелястий рельєф", ru: "скалистая местность", en: "rocky terrain", img: "/words_b2/skalnatý terén.jpg" },
      { sk: "powierzchnia terenu", ua: "поверхня місцевості", ru: "поверхность местности", en: "land surface", img: "/words_b2/povrch krajiny.jpg" },
      { sk: "krajobraz naturalny", ua: "природний ландшафт", ru: "природный ландшафт", en: "natural landscape", img: "/words_b2/prírodná krajina.jpg" },
    ],
  },
  {
    id: "b2-39",
    title: { ua: "Урок 39 — Музика", ru: "Урок 39 — Музыка", en: "Lesson 39 — Music" },
    words: [
      { sk: "melodia", ua: "мелодія", ru: "мелодия", en: "melody", img: "/words_b2/melódia.jpg" },
      { sk: "rytm", ua: "ритм", ru: "ритм", en: "rhythm", img: "/words_b2/rytmus.jpg" },
      { sk: "instrument muzyczny", ua: "музичний інструмент", ru: "музыкальный инструмент", en: "musical instrument", img: "/words_b2/hudobný nástroj.jpg" },
      { sk: "gitara", ua: "гітара", ru: "гитара", en: "guitar", img: "/words_b2/gitara.jpg" },
      { sk: "fortepian", ua: "піаніно", ru: "пианино", en: "piano", img: "/words_b2/klavír.jpg" },
      { sk: "koncert", ua: "концерт", ru: "концерт", en: "concert", img: "/words_b2/koncert.jpg" },
      { sk: "piosenkarz", ua: "співак", ru: "певец", en: "singer", img: "/words_b2/spevák.jpg" },
      { sk: "zespół muzyczny", ua: "музичний гурт", ru: "музыкальная группа", en: "music band", img: "/words_b2/hudobná skupina.jpg" },
      { sk: "nagranie", ua: "запис", ru: "запись", en: "recording", img: "/words_b2/nahrávka.jpg" },
      { sk: "styl muzyczny", ua: "музичний стиль", ru: "музыкальный стиль", en: "music style", img: "/words_b2/hudobný štýl.jpg" },
    ],
  },
  {
    id: "b2-40",
    title: { ua: "Урок 40 — Електрика", ru: "Урок 40 — Электричество", en: "Lesson 40 — Electricity" },
    words: [
      { sk: "prąd", ua: "електрика", ru: "электричество", en: "electricity", img: "/words_b2/elektrina.jpg" },
      { sk: "prąd elektryczny", ua: "електричний струм", ru: "электрический ток", en: "electric current", img: "/words_b2/elektrický prúd.jpg" },
      { sk: "napięcie", ua: "напруга", ru: "напряжение", en: "voltage", img: "/words_b2/napätie.jpg" },
      { sk: "gniazdko", ua: "розетка", ru: "розетка", en: "socket / outlet", img: "/words_b2/zásuvka.jpg" },
      { sk: "kabel", ua: "кабель", ru: "кабель", en: "cable", img: "/words_b2/kábel.jpg" },
      { sk: "wyłącznik", ua: "вимикач", ru: "выключатель", en: "switch", img: "/words_b2/vypínač.jpg" },
      { sk: "obwód elektryczny", ua: "електричне коло", ru: "электрическая цепь", en: "electrical circuit", img: "/words_b2/elektrický obvod.jpg" },
      { sk: "urządzenie", ua: "електроприлад", ru: "электроприбор", en: "electrical appliance", img: "/words_b2/spotrebič.jpg" },
      { sk: "energia", ua: "енергія", ru: "энергия", en: "energy", img: "/words_b2/energia.jpg" },
      { sk: "włączyć prąd", ua: "увімкнути струм", ru: "включить ток", en: "turn on the power", img: "/words_b2/zapnúť prúd.jpg" },
    ],
  },
  {
    id: "b2-41",
    title: { ua: "Урок 41 — Мистецтво", ru: "Урок 41 — Искусство", en: "Lesson 41 — Art" },
    words: [
      { sk: "dzieło sztuki", ua: "твір мистецтва", ru: "произведение искусства", en: "work of art", img: "/words_b2/umelecké dielo.jpg" },
      { sk: "malarz", ua: "художник", ru: "художник", en: "painter", img: "/words_b2/maliar.jpg" },
      { sk: "pomnik", ua: "скульптура", ru: "скульптура", en: "sculpture", img: "/words_b2/socha.jpg" },
      { sk: "płótno", ua: "полотно", ru: "холст", en: "canvas", img: "/words_b2/plátno.jpg" },
      { sk: "portret", ua: "портрет", ru: "портрет", en: "portrait", img: "/words_b2/portrét.jpg" },
      { sk: "styl artystyczny", ua: "художній стиль", ru: "художественный стиль", en: "artistic style", img: "/words_b2/umelecký štýl.jpg" },
      { sk: "sztuka abstrakcyjna", ua: "абстрактне мистецтво", ru: "абстрактное искусство", en: "abstract art", img: "/words_b2/abstraktné umenie.jpg" },
      { sk: "obraz", ua: "живопис", ru: "живопись", en: "painting", img: "/words_b2/maľba.jpg" },
      { sk: "technika artystyczna", ua: "художня техніка", ru: "художественная техника", en: "art technique", img: "/words_b2/umelecká technika.jpg" },
      { sk: "krytyka", ua: "критика", ru: "критика", en: "criticism / critique", img: "/words_b2/kritika.jpg" },
    ],
  },
  {
    id: "b2-42",
    title: { ua: "Урок 42 — Архітектура", ru: "Урок 42 — Архитектура", en: "Lesson 42 — Architecture" },
    words: [
      { sk: "architektura", ua: "архітектура", ru: "архитектура", en: "architecture", img: "/words_b2/architektúra.jpg" },
      { sk: "budowa", ua: "будівля", ru: "здание", en: "building", img: "/words_b2/stavba.jpg" },
      { sk: "wieżowiec", ua: "хмарочос", ru: "небоскрёб", en: "skyscraper", img: "/words_b2/mrakodrap.jpg" },
      { sk: "most", ua: "міст", ru: "мост", en: "bridge", img: "/words_b2/most.jpg" },
      { sk: "historyczny budynek", ua: "історична будівля", ru: "историческое здание", en: "historic building", img: "/words_b2/historická budova.jpg" },
      { sk: "nowoczesna architektura", ua: "сучасна архітектура", ru: "современная архитектура", en: "modern architecture", img: "/words_b2/moderná architektúra.jpg" },
      { sk: "fasada", ua: "фасад", ru: "фасад", en: "facade", img: "/words_b2/fasáda.jpg" },
      { sk: "wieża", ua: "вежа", ru: "башня", en: "tower", img: "/words_b2/veža.jpg" },
      { sk: "projekt", ua: "проєкт", ru: "проект", en: "project", img: "/words_b2/projekt.jpg" },
      { sk: "architekt", ua: "архітектор", ru: "архитектор", en: "architect", img: "/words_b2/architekt.jpg" },
    ],
  },
  {
    id: "b2-43",
    title: { ua: "Урок 43 — Атмосферні явища", ru: "Урок 43 — Атмосферные явления", en: "Lesson 43 — Atmospheric Phenomena" },
    words: [
      { sk: "zachmurzenie", ua: "хмарність", ru: "облачность", en: "cloudiness", img: "/words_b2/oblačnosť.jpg" },
      { sk: "ciśnienie powietrza", ua: "атмосферний тиск", ru: "атмосферное давление", en: "air pressure", img: "/words_b2/tlak vzduchu.jpg" },
      { sk: "nagłe ocieplenie", ua: "раптове потепління", ru: "резкое потепление", en: "sudden warming", img: "/words_b2/náhle oteplenie.jpg" },
      { sk: "ocieplenie", ua: "потепління", ru: "потепление", en: "warming", img: "/words_b2/oteplenie.jpg" },
      { sk: "mżawka", ua: "мряка", ru: "морось", en: "drizzle", img: "/words_b2/mrholenie.jpg" },
      { sk: "ulewny deszcz", ua: "злива", ru: "ливень", en: "torrential rain", img: "/words_b2/prívalový dážď.jpg" },
      { sk: "warstwa lodu", ua: "крижана кірка", ru: "ледяная корка", en: "ice layer", img: "/words_b2/ľadová vrstva.jpg" },
      { sk: "pokrywa śnieżna", ua: "сніговий покрив", ru: "снежный покров", en: "snow cover", img: "/words_b2/snehová pokrývka.jpg" },
      { sk: "ekstremalna pogoda", ua: "екстремальна погода", ru: "экстремальная погода", en: "extreme weather", img: "/words_b2/extrémne počasie.jpg" },
      { sk: "gwałtowne ochłodzenie", ua: "різке похолодання", ru: "резкое похолодание", en: "sharp cooling", img: "/words_b2/prudké ochladenie.jpg" },
    ],
  },
  {
    id: "b2-44",
    title: { ua: "Урок 44 — Право", ru: "Урок 44 — Право", en: "Lesson 44 — Law" },
    words: [
      { sk: "ustawodawstwo", ua: "законодавство", ru: "законодательство", en: "legislation", img: "/words_b2/legislatíva.jpg" },
      { sk: "czyn karalny", ua: "кримінальний злочин", ru: "уголовное преступление", en: "criminal offense", img: "/words_b2/trestný čin.jpg" },
      { sk: "śledczy", ua: "слідчий", ru: "следователь", en: "investigator", img: "/words_b2/vyšetrovateľ.jpg" },
      { sk: "sąd", ua: "суд", ru: "суд", en: "court", img: "/words_b2/súd.jpg" },
      { sk: "wyrok", ua: "вирок", ru: "приговор", en: "sentence / judgment", img: "/words_b2/rozsudok.jpg" },
      { sk: "oskarżenie", ua: "обвинувачення", ru: "обвинение", en: "accusation / charge", img: "/words_b2/obvinenie.jpg" },
      { sk: "świadek", ua: "свідок", ru: "свидетель", en: "witness", img: "/words_b2/svedok.jpg" },
      { sk: "przestępstwo", ua: "злочин", ru: "преступление", en: "crime", img: "/words_b2/zločin.jpg" },
      { sk: "mandat", ua: "штраф", ru: "штраф", en: "fine", img: "/words_b2/pokuta.jpg" },
      { sk: "zatrzymać", ua: "затримати", ru: "задержать", en: "detain / arrest", img: "/words_b2/zadržať.jpg" },
    ],
  },
  {
    id: "b2-45",
    title: { ua: "Урок 45 — Навігація", ru: "Урок 45 — Навигация", en: "Lesson 45 — Navigation" },
    words: [
      { sk: "kompas", ua: "компас", ru: "компас", en: "compass", img: "/words_b2/kompas.jpg" },
      { sk: "mapa", ua: "карта", ru: "карта", en: "map", img: "/words_b2/mapa.jpg" },
      { sk: "kierunek", ua: "напрямок", ru: "направление", en: "direction", img: "/words_b2/smer.jpg" },
      { sk: "północ", ua: "північ", ru: "север", en: "north", img: "/words_b2/sever.jpg" },
      { sk: "południe", ua: "південь", ru: "юг", en: "south", img: "/words_b2/juh.jpg" },
      { sk: "wschód", ua: "схід", ru: "восток", en: "east", img: "/words_b2/východ.jpg" },
      { sk: "zachód", ua: "захід", ru: "запад", en: "west", img: "/words_b2/západ.jpg" },
      { sk: "nawigacja", ua: "навігація", ru: "навигация", en: "navigation", img: "/words_b2/navigácia.jpg" },
      { sk: "określić położenie", ua: "визначити місцезнаходження", ru: "определить местоположение", en: "determine location", img: "/words_b2/určiť polohu.jpg" },
      { sk: "trasa podróży", ua: "маршрут подорожі", ru: "маршрут путешествия", en: "travel route", img: "/words_b2/cestovná trasa.jpg" },
    ],
  },
  {
    id: "b2-46",
    title: { ua: "Урок 46 — Відеоігри", ru: "Урок 46 — Видеоигры", en: "Lesson 46 — Video Games" },
    words: [
      { sk: "gra wideo", ua: "відеогра", ru: "видеоигра", en: "video game", img: "/words_b2/videohra.jpg" },
      { sk: "konsola do gier", ua: "ігрова консоль", ru: "игровая консоль", en: "game console", img: "/words_b2/herná konzola.jpg" },
      { sk: "pilot", ua: "контролер", ru: "контроллер", en: "controller", img: "/words_b2/ovládač.jpg" },
      { sk: "gracz", ua: "гравець", ru: "игрок", en: "player", img: "/words_b2/hráč.jpg" },
      { sk: "poziom", ua: "рівень", ru: "уровень", en: "level", img: "/words_b2/úroveň.jpg" },
      { sk: "misja", ua: "місія", ru: "миссия", en: "mission", img: "/words_b2/misia.jpg" },
      { sk: "postać", ua: "персонаж", ru: "персонаж", en: "character", img: "/words_b2/postava.jpg" },
      { sk: "środowisko gry", ua: "ігрове середовище", ru: "игровая среда", en: "game environment", img: "/words_b2/herné prostredie.jpg" },
      { sk: "multiplayer", ua: "багатокористувацька гра", ru: "мультиплеер", en: "multiplayer", img: "/words_b2/multiplayer.jpg" },
      { sk: "odnieść zwycięstwo", ua: "досягти перемоги", ru: "достичь победы", en: "achieve victory", img: "/words_b2/dosiahnuť víťazstvo.jpg" },
    ],
  },
  {
    id: "b2-47",
    title: { ua: "Урок 47 — Космос", ru: "Урок 47 — Космос", en: "Lesson 47 — Space" },
    words: [
      { sk: "kosmos", ua: "космос", ru: "космос", en: "space / universe", img: "/words_b2/vesmír.jpg" },
      { sk: "planeta", ua: "планета", ru: "планета", en: "planet", img: "/words_b2/planéta.jpg" },
      { sk: "gwiazda", ua: "зірка", ru: "звезда", en: "star", img: "/words_b2/hviezda.jpg" },
      { sk: "galaktyka", ua: "галактика", ru: "галактика", en: "galaxy", img: "/words_b2/galaxia.jpg" },
      { sk: "rakieta", ua: "ракета", ru: "ракета", en: "rocket", img: "/words_b2/raketa.jpg" },
      { sk: "astronauta", ua: "астронавт", ru: "астронавт", en: "astronaut", img: "/words_b2/astronaut.jpg" },
      { sk: "stacja kosmiczna", ua: "космічна станція", ru: "космическая станция", en: "space station", img: "/words_b2/vesmírna stanica.jpg" },
      { sk: "orbita", ua: "орбіта", ru: "орбита", en: "orbital path / orbit", img: "/words_b2/orbitálna dráha.jpg" },
      { sk: "misja kosmiczna", ua: "космічна місія", ru: "космическая миссия", en: "space mission", img: "/words_b2/kozmická misia.jpg" },
      { sk: "nieskończony wszechświat", ua: "безмежний космос", ru: "бесконечный космос", en: "endless universe", img: "/words_b2/nekonečný vesmír.jpg" },
    ],
  },
  {
    id: "b2-48",
    title: { ua: "Урок 48 — Хімія", ru: "Урок 48 — Химия", en: "Lesson 48 — Chemistry" },
    words: [
      { sk: "pierwiastek chemiczny", ua: "хімічний елемент", ru: "химический элемент", en: "chemical element", img: "/words_b2/chemický prvok.jpg" },
      { sk: "związek", ua: "сполука", ru: "соединение", en: "compound", img: "/words_b2/zlúčenina.jpg" },
      { sk: "reakcja", ua: "реакція", ru: "реакция", en: "reaction", img: "/words_b2/reakcia.jpg" },
      { sk: "laboratorium", ua: "лабораторія", ru: "лаборатория", en: "laboratory", img: "/words_b2/laboratórium.jpg" },
      { sk: "eksperyment", ua: "експеримент", ru: "эксперимент", en: "experiment", img: "/words_b2/experiment.jpg" },
      { sk: "kwas", ua: "кислота", ru: "кислота", en: "acid", img: "/words_b2/kyselina.jpg" },
      { sk: "zasada", ua: "основа (хім.)", ru: "основание", en: "base / alkali", img: "/words_b2/zásada.jpg" },
      { sk: "substancja chemiczna", ua: "хімічна речовина", ru: "химическое вещество", en: "chemical substance", img: "/words_b2/chemická látka.jpg" },
      { sk: "mieszanka", ua: "суміш", ru: "смесь", en: "mixture", img: "/words_b2/zmes.jpg" },
      { sk: "reakcja chemiczna", ua: "хімічна реакція", ru: "химическая реакция", en: "chemical reaction", img: "/words_b2/chemická reakcia.jpg" },
    ],
  },
  {
    id: "b2-49",
    title: { ua: "Урок 49 — Будівництво", ru: "Урок 49 — Строительство", en: "Lesson 49 — Construction" },
    words: [
      { sk: "budowa", ua: "будівництво", ru: "строительство", en: "construction", img: "/words_b2/stavba.jpg" },
      { sk: "plac budowy", ua: "будівельний майданчик", ru: "стройплощадка", en: "construction site", img: "/words_b2/stavenisko.jpg" },
      { sk: "cegła", ua: "цегла", ru: "кирпич", en: "brick", img: "/words_b2/tehla.jpg" },
      { sk: "beton", ua: "бетон", ru: "бетон", en: "concrete", img: "/words_b2/betón.jpg" },
      { sk: "dźwig", ua: "кран", ru: "кран", en: "crane", img: "/words_b2/žeriav.jpg" },
      { sk: "rusztowanie", ua: "риштування", ru: "строительные леса", en: "scaffolding", img: "/words_b2/lešenie.jpg" },
      { sk: "materiał budowlany", ua: "будівельний матеріал", ru: "строительный материал", en: "building material", img: "/words_b2/stavebný materiál.jpg" },
      { sk: "fundament budowy", ua: "фундамент", ru: "фундамент", en: "foundation", img: "/words_b2/základ stavby.jpg" },
      { sk: "dach", ua: "дах", ru: "крыша", en: "roof", img: "/words_b2/strecha.jpg" },
      { sk: "projekt budowlany", ua: "будівельний проєкт", ru: "строительный проект", en: "construction project", img: "/words_b2/stavebný projekt.jpg" },
    ],
  },
  {
    id: "b2-50",
    title: { ua: "Урок 50 — Інструменти", ru: "Урок 50 — Инструменты", en: "Lesson 50 — Tools" },
    words: [
      { sk: "narzędzia", ua: "інструменти", ru: "инструменты", en: "tools", img: "/words_b2/náradie.jpg" },
      { sk: "młotek", ua: "молоток", ru: "молоток", en: "hammer", img: "/words_b2/kladivo.jpg" },
      { sk: "śrubokręt", ua: "викрутка", ru: "отвёртка", en: "screwdriver", img: "/words_b2/skrutkovač.jpg" },
      { sk: "klucz", ua: "гайковий ключ", ru: "гаечный ключ", en: "wrench / spanner", img: "/words_b2/kľúč.jpg" },
      { sk: "piła", ua: "пила", ru: "пила", en: "saw", img: "/words_b2/píla.jpg" },
      { sk: "wiertarka", ua: "дриль", ru: "дрель", en: "drill", img: "/words_b2/vŕtačka.jpg" },
      { sk: "gwoździe", ua: "цвяхи", ru: "гвозди", en: "nails", img: "/words_b2/klince.jpg" },
      { sk: "śruby", ua: "гвинти", ru: "винты", en: "screws", img: "/words_b2/skrutky.jpg" },
      { sk: "mierzyć", ua: "вимірювати", ru: "измерять", en: "measure", img: "/words_b2/merať.jpg" },
      { sk: "naprawić", ua: "полагодити", ru: "починить", en: "repair / fix", img: "/words_b2/opraviť.jpg" },
    ],
  },
];
