import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A1_BUILD_UA_SENTENCES_1: BuildUaSentenceDict = {
    // =========================
    // LESSON 1 — Знайомство
    // =========================
    [phraseKey("nazywać się", "a1-1")]: {
        sk: "Jak się nazywasz?",
        ua: "Як тебе звати?",
        ru: "Как тебя зовут?",
        en: "What is your name?",
        uaTokens: ["Як", "тебе", "звати", "?"],
        ruTokens: ["Как", "тебя", "зовут", "?"],
        enTokens: ["What", "is", "your", "name", "?"],
        extraUaTokens: ["мене", "приємно", "живу"],
        extraRuTokens: ["меня", "приятно", "живу"],
        extraEnTokens: ["live", "nice", "city"],
    },

    [phraseKey("poznać się", "a1-1")]: {
        sk: "Miło cię poznać.",
        ua: "Приємно познайомитися.",
        ru: "Приятно познакомиться.",
        en: "Nice to meet you.",
        uaTokens: ["Приємно", "познайомитися", "."],
        ruTokens: ["Приятно", "познакомиться", "."],
        enTokens: ["Nice", "to", "meet", "you", "."],
        extraUaTokens: ["тебе", "звати", "офісі"],
        extraRuTokens: ["тебя", "зовут", "офисе"],
        extraEnTokens: ["name", "office", "help"],
    },

    [phraseKey("imię", "a1-1")]: {
        sk: "Moje imię to Anna.",
        ua: "Мене звати Анна.",
        ru: "Меня зовут Анна.",
        en: "My name is Anna.",
        uaTokens: ["Мене", "звати", "Анна", "."],
        ruTokens: ["Меня", "зовут", "Анна", "."],
        enTokens: ["My", "name", "is", "Anna", "."],
        extraUaTokens: ["живу", "каву", "дякую"],
        extraRuTokens: ["живу", "кофе", "спасибо"],
        extraEnTokens: ["live", "coffee", "thanks"],
    },

    [phraseKey("nazwisko", "a1-1")]: {
        sk: "Moje nazwisko to Kowalski.",
        ua: "Моє прізвище Ковальський.",
        ru: "Моя фамилия Ковальский.",
        en: "My surname is Kowalski.",
        uaTokens: ["Моє", "прізвище", "Ковальський", "."],
        ruTokens: ["Моя", "фамилия", "Ковальский", "."],
        enTokens: ["My", "surname", "is", "Kowalski", "."],
        extraUaTokens: ["Анна", "офісі", "допомогу"],
        extraRuTokens: ["Анна", "офисе", "помощь"],
        extraEnTokens: ["Anna", "office", "help"],
    },

    [phraseKey("skąd", "a1-1")]: {
        sk: "Skąd jesteś?",
        ua: "Звідки ти?",
        ru: "Ты откуда?",
        en: "Where are you from?",
        uaTokens: ["Звідки", "ти", "?"],
        ruTokens: ["Ты", "откуда", "?"],
        enTokens: ["Where", "are", "you", "from", "?"],
        extraUaTokens: ["живу", "працюю", "каву"],
        extraRuTokens: ["живу", "работаю", "кофе"],
        extraEnTokens: ["live", "work", "coffee"],
    },

    [phraseKey("mieszkać", "a1-1")]: {
        sk: "Mieszkam w Warszawie.",
        ua: "Я живу у Варшаві.",
        ru: "Я живу в Варшаве.",
        en: "I live in Warsaw.",
        uaTokens: ["Я", "живу", "у", "Варшаві", "."],
        ruTokens: ["Я", "живу", "в", "Варшаве", "."],
        enTokens: ["I", "live", "in", "Warsaw", "."],
        extraUaTokens: ["офісі", "дякую", "звати"],
        extraRuTokens: ["офисе", "спасибо", "зовут"],
        extraEnTokens: ["office", "thanks", "name"],
    },

    [phraseKey("pracować", "a1-1")]: {
        sk: "Pracuję w biurze.",
        ua: "Я працюю в офісі.",
        ru: "Я работаю в офисе.",
        en: "I work in an office.",
        uaTokens: ["Я", "працюю", "в", "офісі", "."],
        ruTokens: ["Я", "работаю", "в", "офисе", "."],
        enTokens: ["I", "work", "in", "an", "office", "."],
        extraUaTokens: ["Варшаві", "каву", "допомогу"],
        extraRuTokens: ["Варшаве", "кофе", "помощь"],
        extraEnTokens: ["Warsaw", "coffee", "help"],
    },

    [phraseKey("miło mi", "a1-1")]: {
        sk: "Miło mi cię poznać.",
        ua: "Мені приємно познайомитися.",
        ru: "Мне приятно познакомиться.",
        en: "Nice to meet you.",
        uaTokens: ["Мені", "приємно", "познайомитися", "."],
        ruTokens: ["Мне", "приятно", "познакомиться", "."],
        enTokens: ["Nice", "to", "meet", "you", "."],
        extraUaTokens: ["дякую", "живу", "Анна"],
        extraRuTokens: ["спасибо", "живу", "Анна"],
        extraEnTokens: ["thanks", "live", "Anna"],
    },

    [phraseKey("lubić", "a1-1")]: {
        sk: "Lubię kawę.",
        ua: "Я люблю каву.",
        ru: "Я люблю кофе.",
        en: "I like coffee.",
        uaTokens: ["Я", "люблю", "каву", "."],
        ruTokens: ["Я", "люблю", "кофе", "."],
        enTokens: ["I", "like", "coffee", "."],
        extraUaTokens: ["живу", "офісі", "допомогу"],
        extraRuTokens: ["живу", "офисе", "помощь"],
        extraEnTokens: ["live", "office", "help"],
    },

    [phraseKey("dziękuję", "a1-1")]: {
        sk: "Dziękuję za pomoc.",
        ua: "Дякую за допомогу.",
        ru: "Спасибо за помощь.",
        en: "Thank you for the help.",
        uaTokens: ["Дякую", "за", "допомогу", "."],
        ruTokens: ["Спасибо", "за", "помощь", "."],
        enTokens: ["Thank", "you", "for", "the", "help", "."],
        extraUaTokens: ["каву", "живу", "приємно"],
        extraRuTokens: ["кофе", "живу", "приятно"],
        extraEnTokens: ["coffee", "live", "nice"],
    },

    // =========================
    // LESSON 2 — Ввічливі фрази
    // =========================
    [phraseKey("proszę", "a1-2")]: {
        sk: "Proszę usiąść.",
        ua: "Будь ласка, сідайте.",
        ru: "Пожалуйста, садитесь.",
        en: "Please, sit down.",
        uaTokens: ["Будь", "ласка", ",", "сідайте", "."],
        ruTokens: ["Пожалуйста", ",", "садитесь", "."],
        enTokens: ["Please", ",", "sit", "down", "."],
        extraUaTokens: ["допомогу", "увійти", "зроблю"],
        extraRuTokens: ["помощь", "войти", "сделаю"],
        extraEnTokens: ["help", "enter", "do"],
    },

    [phraseKey("przepraszam", "a1-2")]: {
        sk: "Przepraszam za spóźnienie.",
        ua: "Вибачте за запізнення.",
        ru: "Извините за опоздание.",
        en: "Sorry for being late.",
        uaTokens: ["Вибачте", "за", "запізнення", "."],
        ruTokens: ["Извините", "за", "опоздание", "."],
        enTokens: ["Sorry", "for", "being", "late", "."],
        extraUaTokens: ["допомогу", "сідайте", "все"],
        extraRuTokens: ["помощь", "садитесь", "всё"],
        extraEnTokens: ["help", "down", "everything"],
    },

    [phraseKey("dziękuję bardzo", "a1-2")]: {
        sk: "Dziękuję bardzo za wszystko.",
        ua: "Дуже дякую за все.",
        ru: "Большое спасибо за всё.",
        en: "Thank you very much for everything.",
        uaTokens: ["Дуже", "дякую", "за", "все", "."],
        ruTokens: ["Большое", "спасибо", "за", "всё", "."],
        enTokens: ["Thank", "you", "very", "much", "for", "everything", "."],
        extraUaTokens: ["зроблю", "допомогти", "увійти"],
        extraRuTokens: ["сделаю", "помочь", "войти"],
        extraEnTokens: ["do", "help", "enter"],
    },

    [phraseKey("nie ma za co", "a1-2")]: {
        sk: "Nie ma za co.",
        ua: "Нема за що.",
        ru: "Не за что.",
        en: "You're welcome.",
        uaTokens: ["Нема", "за", "що", "."],
        ruTokens: ["Не", "за", "что", "."],
        enTokens: ["You", "are", "welcome", "."],
        extraUaTokens: ["все", "дякую", "ясно"],
        extraRuTokens: ["всё", "спасибо", "ясно"],
        extraEnTokens: ["everything", "thanks", "sure"],
    },

    [phraseKey("mogę", "a1-2")]: {
        sk: "Mogę wejść?",
        ua: "Можна увійти?",
        ru: "Можно войти?",
        en: "May I come in?",
        uaTokens: ["Можна", "увійти", "?"],
        ruTokens: ["Можно", "войти", "?"],
        enTokens: ["May", "I", "come", "in", "?"],
        extraUaTokens: ["допомогу", "зроблю", "валізою"],
        extraRuTokens: ["помощь", "сделаю", "чемоданом"],
        extraEnTokens: ["help", "do", "suitcase"],
    },

    [phraseKey("możecie", "a1-2")]: {
        sk: "Możecie mi pomóc?",
        ua: "Можете мені допомогти?",
        ru: "Можете мне помочь?",
        en: "Can you help me?",
        uaTokens: ["Можете", "мені", "допомогти", "?"],
        ruTokens: ["Можете", "мне", "помочь", "?"],
        enTokens: ["Can", "you", "help", "me", "?"],
        uaAltAnswers: [["Можете", "допомогти", "мені", "?"]],
        ruAltAnswers: [["Можете", "помочь", "мне", "?"]],
        enAltAnswers: [["Can", "you", "help", "me", "?"]],
        extraUaTokens: ["увійти", "все", "зроблю"],
        extraRuTokens: ["войти", "всё", "сделаю"],
        extraEnTokens: ["enter", "everything", "do"],
    },

    [phraseKey("proszę mi pomóc", "a1-2")]: {
        sk: "Proszę mi pomóc z walizką.",
        ua: "Допоможіть мені з валізою.",
        ru: "Помогите мне с чемоданом.",
        en: "Please help me with the suitcase.",
        uaTokens: ["Допоможіть", "мені", "з", "валізою", "."],
        ruTokens: ["Помогите", "мне", "с", "чемоданом", "."],
        enTokens: ["Please", "help", "me", "with", "the", "suitcase", "."],
        extraUaTokens: ["увійти", "все", "ясно"],
        extraRuTokens: ["войти", "всё", "ясно"],
        extraEnTokens: ["enter", "everything", "sure"],
    },

    [phraseKey("proszę bardzo", "a1-2")]: {
        sk: "Proszę bardzo, to dla ciebie.",
        ua: "Прошу, це для тебе.",
        ru: "Пожалуйста, это для тебя.",
        en: "Here you go, this is for you.",
        uaTokens: ["Прошу", ",", "це", "для", "тебе", "."],
        ruTokens: ["Пожалуйста", ",", "это", "для", "тебя", "."],
        enTokens: ["Here", "you", "go", ",", "this", "is", "for", "you", "."],
        extraUaTokens: ["допомогу", "увійти", "все"],
        extraRuTokens: ["помощь", "войти", "всё"],
        extraEnTokens: ["help", "enter", "everything"],
    },

    [phraseKey("w porządku", "a1-2")]: {
        sk: "Wszystko jest w porządku.",
        ua: "Все в порядку.",
        ru: "Всё в порядке.",
        en: "Everything is all right.",
        uaTokens: ["Все", "в", "порядку", "."],
        ruTokens: ["Всё", "в", "порядке", "."],
        enTokens: ["Everything", "is", "all", "right", "."],
        extraUaTokens: ["дякую", "зроблю", "валізою"],
        extraRuTokens: ["спасибо", "сделаю", "чемоданом"],
        extraEnTokens: ["thanks", "do", "suitcase"],
    },

    [phraseKey("jasne", "a1-2")]: {
        sk: "Jasne, zrobię to.",
        ua: "Ясно, я це зроблю.",
        ru: "Конечно, я это сделаю.",
        en: "Sure, I will do it.",
        uaTokens: ["Ясно", ",", "я", "це", "зроблю", "."],
        ruTokens: ["Конечно", ",", "я", "это", "сделаю", "."],
        enTokens: ["Sure", ",", "I", "will", "do", "it", "."],
        extraUaTokens: ["допомогу", "порядку", "увійти"],
        extraRuTokens: ["помощь", "порядке", "войти"],
        extraEnTokens: ["help", "right", "enter"],
    },

    // =========================
    // LESSON 3 — Місто
    // =========================
    [phraseKey("skrzyżowanie", "a1-3")]: {
        sk: "Skrzyżowanie jest niedaleko.",
        ua: "Перехрестя недалеко.",
        ru: "Перекрёсток недалеко.",
        en: "The intersection is nearby.",
        uaTokens: ["Перехрестя", "недалеко", "."],
        ruTokens: ["Перекрёсток", "недалеко", "."],
        enTokens: ["The", "intersection", "is", "nearby", "."],
        extraUaTokens: ["міст", "музей", "вхід"],
        extraRuTokens: ["мост", "музей", "вход"],
        extraEnTokens: ["bridge", "museum", "entrance"],
    },

    [phraseKey("sygnalizacja świetlna", "a1-3")]: {
        sk: "Czekam przy sygnalizacji świetlnej.",
        ua: "Я чекаю біля світлофора.",
        ru: "Я жду у светофора.",
        en: "I am waiting at the traffic light.",
        uaTokens: ["Я", "чекаю", "біля", "світлофора", "."],
        ruTokens: ["Я", "жду", "у", "светофора", "."],
        enTokens: ["I", "am", "waiting", "at", "the", "traffic", "light", "."],
        extraUaTokens: ["міст", "увечері", "цікавий"],
        extraRuTokens: ["мост", "вечером", "интересный"],
        extraEnTokens: ["bridge", "evening", "interesting"],
    },

    [phraseKey("most", "a1-3")]: {
        sk: "Idziemy przez most.",
        ua: "Ми йдемо через міст.",
        ru: "Мы идём через мост.",
        en: "We are walking across the bridge.",
        uaTokens: ["Ми", "йдемо", "через", "міст", "."],
        ruTokens: ["Мы", "идём", "через", "мост", "."],
        enTokens: ["We", "are", "walking", "across", "the", "bridge", "."],
        extraUaTokens: ["світлофора", "аптека", "зліва"],
        extraRuTokens: ["светофора", "аптека", "слева"],
        extraEnTokens: ["traffic", "pharmacy", "left"],
    },

    [phraseKey("kino", "a1-3")]: {
        sk: "Wieczorem idę do kina.",
        ua: "Увечері я йду в кінотеатр.",
        ru: "Вечером я иду в кинотеатр.",
        en: "I am going to the cinema in the evening.",
        uaTokens: ["Увечері", "я", "йду", "в", "кінотеатр", "."],
        ruTokens: ["Вечером", "я", "иду", "в", "кинотеатр", "."],
        enTokens: ["I", "am", "going", "to", "the", "cinema", "in", "the", "evening", "."],
        extraUaTokens: ["міст", "аптека", "ринку"],
        extraRuTokens: ["мост", "аптека", "рынке"],
        extraEnTokens: ["bridge", "pharmacy", "market"],
    },

    [phraseKey("muzeum", "a1-3")]: {
        sk: "To muzeum jest bardzo ciekawe.",
        ua: "Цей музей дуже цікавий.",
        ru: "Этот музей очень интересный.",
        en: "This museum is very interesting.",
        uaTokens: ["Цей", "музей", "дуже", "цікавий", "."],
        ruTokens: ["Этот", "музей", "очень", "интересный", "."],
        enTokens: ["This", "museum", "is", "very", "interesting", "."],
        extraUaTokens: ["ринку", "вхід", "ззаду"],
        extraRuTokens: ["рынке", "вход", "сзади"],
        extraEnTokens: ["market", "entrance", "back"],
    },

    [phraseKey("apteka", "a1-3")]: {
        sk: "Apteka jest obok sklepu.",
        ua: "Аптека біля магазину.",
        ru: "Аптека рядом с магазином.",
        en: "The pharmacy is next to the shop.",
        uaTokens: ["Аптека", "біля", "магазину", "."],
        ruTokens: ["Аптека", "рядом", "с", "магазином", "."],
        enTokens: ["The", "pharmacy", "is", "next", "to", "the", "shop", "."],
        extraUaTokens: ["музей", "зліва", "ринку"],
        extraRuTokens: ["музей", "слева", "рынке"],
        extraEnTokens: ["museum", "left", "market"],
    },

    [phraseKey("biblioteka", "a1-3")]: {
        sk: "Uczę się w bibliotece.",
        ua: "Я вчуся в бібліотеці.",
        ru: "Я занимаюсь в библиотеке.",
        en: "I study in the library.",
        uaTokens: ["Я", "вчуся", "в", "бібліотеці", "."],
        ruTokens: ["Я", "занимаюсь", "в", "библиотеке", "."],
        enTokens: ["I", "study", "in", "the", "library", "."],
        extraUaTokens: ["кінотеатр", "аптека", "міст"],
        extraRuTokens: ["кинотеатр", "аптека", "мост"],
        extraEnTokens: ["cinema", "pharmacy", "bridge"],
    },

    [phraseKey("rynek", "a1-3")]: {
        sk: "Spotkamy się na rynku.",
        ua: "Зустрінемося на ринку.",
        ru: "Встретимся на рынке.",
        en: "We will meet at the market square.",
        uaTokens: ["Зустрінемося", "на", "ринку", "."],
        ruTokens: ["Встретимся", "на", "рынке", "."],
        enTokens: ["We", "will", "meet", "at", "the", "market", "square", "."],
        extraUaTokens: ["музей", "вхід", "недалеко"],
        extraRuTokens: ["музей", "вход", "недалеко"],
        extraEnTokens: ["museum", "entrance", "nearby"],
    },

    [phraseKey("wejście", "a1-3")]: {
        sk: "Wejście jest z lewej strony.",
        ua: "Вхід з лівого боку.",
        ru: "Вход с левой стороны.",
        en: "The entrance is on the left side.",
        uaTokens: ["Вхід", "з", "лівого", "боку", "."],
        ruTokens: ["Вход", "с", "левой", "стороны", "."],
        enTokens: ["The", "entrance", "is", "on", "the", "left", "side", "."],
        extraUaTokens: ["музей", "ринку", "ззаду"],
        extraRuTokens: ["музей", "рынке", "сзади"],
        extraEnTokens: ["museum", "market", "back"],
    },

    [phraseKey("wyjście ewakuacyjne", "a1-3")]: {
        sk: "Wyjście ewakuacyjne jest z tyłu.",
        ua: "Аварійний вихід знаходиться ззаду.",
        ru: "Аварийный выход находится сзади.",
        en: "The emergency exit is at the back.",
        uaTokens: ["Аварійний", "вихід", "знаходиться", "ззаду", "."],
        ruTokens: ["Аварийный", "выход", "находится", "сзади", "."],
        enTokens: ["The", "emergency", "exit", "is", "at", "the", "back", "."],
        extraUaTokens: ["вхід", "музей", "ринку"],
        extraRuTokens: ["вход", "музей", "рынке"],
        extraEnTokens: ["entrance", "museum", "market"],
    },

    // =========================
    // LESSON 4 — Магазин (розширено)
    // =========================
    [phraseKey("kasjer", "a1-4")]: {
        sk: "Kasjer jest przy kasie.",
        ua: "Касир біля каси.",
        ru: "Кассир у кассы.",
        en: "The cashier is at the checkout.",
        uaTokens: ["Касир", "біля", "каси", "."],
        ruTokens: ["Кассир", "у", "кассы", "."],
        enTokens: ["The", "cashier", "is", "at", "the", "checkout", "."],
        extraUaTokens: ["полиці", "товар", "гарантію"],
        extraRuTokens: ["полке", "товар", "гарантия"],
        extraEnTokens: ["shelf", "product", "warranty"],
    },

    [phraseKey("regał", "a1-4")]: {
        sk: "Mleko stoi na regale.",
        ua: "Молоко стоїть на полиці.",
        ru: "Молоко стоит на полке.",
        en: "The milk is on the shelf.",
        uaTokens: ["Молоко", "стоїть", "на", "полиці", "."],
        ruTokens: ["Молоко", "стоит", "на", "полке", "."],
        enTokens: ["The", "milk", "is", "on", "the", "shelf", "."],
        extraUaTokens: ["касир", "розмір", "телефон"],
        extraRuTokens: ["кассир", "размер", "телефон"],
        extraEnTokens: ["cashier", "size", "phone"],
    },

    [phraseKey("oddział", "a1-4")]: {
        sk: "Szukam oddziału z ubraniami.",
        ua: "Я шукаю відділ з одягом.",
        ru: "Я ищу отдел с одеждой.",
        en: "I am looking for the clothing department.",
        uaTokens: ["Я", "шукаю", "відділ", "з", "одягом", "."],
        ruTokens: ["Я", "ищу", "отдел", "с", "одеждой", "."],
        enTokens: ["I", "am", "looking", "for", "the", "clothing", "department", "."],
        extraUaTokens: ["полиці", "куртку", "ціна"],
        extraRuTokens: ["полке", "куртку", "цена"],
        extraEnTokens: ["shelf", "jacket", "price"],
    },

    [phraseKey("rozmiar", "a1-4")]: {
        sk: "Jaki to rozmiar?",
        ua: "Який це розмір?",
        ru: "Какой это размер?",
        en: "What size is this?",
        uaTokens: ["Який", "це", "розмір", "?"],
        ruTokens: ["Какой", "это", "размер", "?"],
        enTokens: ["What", "size", "is", "this", "?"],
        extraUaTokens: ["куртку", "товар", "ціна"],
        extraRuTokens: ["куртку", "товар", "цена"],
        extraEnTokens: ["jacket", "product", "price"],
    },

    [phraseKey("spróbować", "a1-4")]: {
        sk: "Chcę spróbować tę kurtkę.",
        ua: "Я хочу приміряти цю куртку.",
        ru: "Я хочу примерить эту куртку.",
        en: "I want to try this jacket on.",
        uaTokens: ["Я", "хочу", "приміряти", "цю", "куртку", "."],
        ruTokens: ["Я", "хочу", "примерить", "эту", "куртку", "."],
        enTokens: ["I", "want", "to", "try", "this", "jacket", "on", "."],
        uaAltAnswers: [["Я", "хочу", "цю", "куртку", "приміряти", "."]],
        ruAltAnswers: [["Я", "хочу", "эту", "куртку", "примерить", "."]],
        enAltAnswers: [["I", "want", "to", "try", "on", "this", "jacket", "."]],
        extraUaTokens: ["розмір", "товар", "гарантію"],
        extraRuTokens: ["размер", "товар", "гарантия"],
        extraEnTokens: ["size", "product", "warranty"],
    },

    [phraseKey("wymienić", "a1-4")]: {
        sk: "Chcę wymienić ten produkt.",
        ua: "Я хочу обміняти цей товар.",
        ru: "Я хочу обменять этот товар.",
        en: "I want to exchange this product.",
        uaTokens: ["Я", "хочу", "обміняти", "цей", "товар", "."],
        ruTokens: ["Я", "хочу", "обменять", "этот", "товар", "."],
        enTokens: ["I", "want", "to", "exchange", "this", "product", "."],
        uaAltAnswers: [["Я", "хочу", "цей", "товар", "обміняти", "."]],
        ruAltAnswers: [["Я", "хочу", "этот", "товар", "обменять", "."]],
        enAltAnswers: [["I", "want", "to", "exchange", "this", "product", "."]],
        extraUaTokens: ["куртку", "взуття", "касир"],
        extraRuTokens: ["куртку", "обувь", "кассир"],
        extraEnTokens: ["jacket", "shoes", "cashier"],
    },

    [phraseKey("zwrócić", "a1-4")]: {
        sk: "Chcę zwrócić buty.",
        ua: "Я хочу повернути взуття.",
        ru: "Я хочу вернуть обувь.",
        en: "I want to return the shoes.",
        uaTokens: ["Я", "хочу", "повернути", "взуття", "."],
        ruTokens: ["Я", "хочу", "вернуть", "обувь", "."],
        enTokens: ["I", "want", "to", "return", "the", "shoes", "."],
        uaAltAnswers: [["Я", "хочу", "взуття", "повернути", "."]],
        ruAltAnswers: [["Я", "хочу", "обувь", "вернуть", "."]],
        extraUaTokens: ["товар", "гарантію", "полиці"],
        extraRuTokens: ["товар", "гарантия", "полке"],
        extraEnTokens: ["product", "warranty", "shelf"],
    },

    [phraseKey("gwarancja", "a1-4")]: {
        sk: "Ten telefon ma gwarancję.",
        ua: "Цей телефон має гарантію.",
        ru: "У этого телефона есть гарантия.",
        en: "This phone has a warranty.",
        uaTokens: ["Цей", "телефон", "має", "гарантію", "."],
        ruTokens: ["У", "этого", "телефона", "есть", "гарантия", "."],
        enTokens: ["This", "phone", "has", "a", "warranty", "."],
        extraUaTokens: ["товар", "касир", "розмір"],
        extraRuTokens: ["товар", "кассир", "размер"],
        extraEnTokens: ["product", "cashier", "size"],
    },

    [phraseKey("opakowanie", "a1-4")]: {
        sk: "Opakowanie jest uszkodzone.",
        ua: "Упаковка пошкоджена.",
        ru: "Упаковка повреждена.",
        en: "The packaging is damaged.",
        uaTokens: ["Упаковка", "пошкоджена", "."],
        ruTokens: ["Упаковка", "повреждена", "."],
        enTokens: ["The", "packaging", "is", "damaged", "."],
        extraUaTokens: ["товар", "касир", "ціна"],
        extraRuTokens: ["товар", "кассир", "цена"],
        extraEnTokens: ["product", "cashier", "price"],
    },

    [phraseKey("naliczać", "a1-4")]: {
        sk: "Kasjer nalicza cenę.",
        ua: "Касир рахує ціну.",
        ru: "Кассир считает сумму.",
        en: "The cashier is charging the price.",
        uaTokens: ["Касир", "рахує", "ціну", "."],
        ruTokens: ["Кассир", "считает", "сумму", "."],
        enTokens: ["The", "cashier", "is", "charging", "the", "price", "."],
        extraUaTokens: ["товар", "полиці", "телефон"],
        extraRuTokens: ["товар", "полке", "телефон"],
        extraEnTokens: ["product", "shelf", "phone"],
    },

    // =========================
    // LESSON 5 — Їжа (у ресторані)
    // =========================
    [phraseKey("zamówić", "a1-5")]: {
        sk: "Chcę zamówić zupę.",
        ua: "Я хочу замовити суп.",
        ru: "Я хочу заказать суп.",
        en: "I want to order soup.",
        uaTokens: ["Я", "хочу", "замовити", "суп", "."],
        ruTokens: ["Я", "хочу", "заказать", "суп", "."],
        enTokens: ["I", "want", "to", "order", "soup", "."],
        uaAltAnswers: [["Я", "хочу", "суп", "замовити", "."]],
        ruAltAnswers: [["Я", "хочу", "суп", "заказать", "."]],
        extraUaTokens: ["десерт", "рахунок", "голодний"],
        extraRuTokens: ["десерт", "счёт", "голодный"],
        extraEnTokens: ["dessert", "bill", "hungry"],
    },

    [phraseKey("porcja", "a1-5")]: {
        sk: "To jest duża porcja.",
        ua: "Це велика порція.",
        ru: "Это большая порция.",
        en: "This is a big portion.",
        uaTokens: ["Це", "велика", "порція", "."],
        ruTokens: ["Это", "большая", "порция", "."],
        enTokens: ["This", "is", "a", "big", "portion", "."],
        extraUaTokens: ["суп", "десерт", "вечір"],
        extraRuTokens: ["суп", "десерт", "вечер"],
        extraEnTokens: ["soup", "dessert", "evening"],
    },

    [phraseKey("załącznik", "a1-5")]: {
        sk: "Jaki załącznik chcecie?",
        ua: "Який гарнір ви хочете?",
        ru: "Какой гарнир вы хотите?",
        en: "Which side dish do you want?",
        uaTokens: ["Який", "гарнір", "ви", "хочете", "?"],
        ruTokens: ["Какой", "гарнир", "вы", "хотите", "?"],
        enTokens: ["Which", "side", "dish", "do", "you", "want", "?"],
        extraUaTokens: ["суп", "десерт", "рахунок"],
        extraRuTokens: ["суп", "десерт", "счёт"],
        extraEnTokens: ["soup", "dessert", "bill"],
    },

    [phraseKey("deser", "a1-5")]: {
        sk: "Na koniec chcę deser.",
        ua: "На кінець я хочу десерт.",
        ru: "В конце я хочу десерт.",
        en: "At the end I want dessert.",
        uaTokens: ["На", "кінець", "я", "хочу", "десерт", "."],
        ruTokens: ["В", "конце", "я", "хочу", "десерт", "."],
        enTokens: ["At", "the", "end", "I", "want", "dessert", "."],
        extraUaTokens: ["суп", "голодний", "вечір"],
        extraRuTokens: ["суп", "голодный", "вечер"],
        extraEnTokens: ["soup", "hungry", "evening"],
    },

    [phraseKey("smaczny", "a1-5")]: {
        sk: "Obiad był bardzo smaczny.",
        ua: "Обід був дуже смачний.",
        ru: "Обед был очень вкусный.",
        en: "The lunch was very tasty.",
        uaTokens: ["Обід", "був", "дуже", "смачний", "."],
        ruTokens: ["Обед", "был", "очень", "вкусный", "."],
        enTokens: ["The", "lunch", "was", "very", "tasty", "."],
        extraUaTokens: ["суп", "десерт", "рахунок"],
        extraRuTokens: ["суп", "десерт", "счёт"],
        extraEnTokens: ["soup", "dessert", "bill"],
    },

    [phraseKey("głodny", "a1-5")]: {
        sk: "Jestem bardzo głodny.",
        ua: "Я дуже голодний.",
        ru: "Я очень голодный.",
        en: "I am very hungry.",
        uaTokens: ["Я", "дуже", "голодний", "."],
        ruTokens: ["Я", "очень", "голодный", "."],
        enTokens: ["I", "am", "very", "hungry", "."],
        extraUaTokens: ["суп", "рахунок", "вечір"],
        extraRuTokens: ["суп", "счёт", "вечер"],
        extraEnTokens: ["soup", "bill", "evening"],
    },

    [phraseKey("spragniony", "a1-5")]: {
        sk: "Jestem spragniony.",
        ua: "Я хочу пити.",
        ru: "Я хочу пить.",
        en: "I am thirsty.",
        uaTokens: ["Я", "хочу", "пити", "."],
        ruTokens: ["Я", "хочу", "пить", "."],
        enTokens: ["I", "am", "thirsty", "."],
        extraUaTokens: ["суп", "десерт", "дуже"],
        extraRuTokens: ["суп", "десерт", "очень"],
        extraEnTokens: ["soup", "dessert", "very"],
    },

    [phraseKey("naliczać", "a1-5")]: {
        sk: "Proszę naliczyć rachunek.",
        ua: "Будь ласка, виставте рахунок.",
        ru: "Пожалуйста, выставьте счёт.",
        en: "Please bring the bill.",
        uaTokens: ["Будь", "ласка", ",", "виставте", "рахунок", "."],
        ruTokens: ["Пожалуйста", ",", "выставьте", "счёт", "."],
        enTokens: ["Please", "bring", "the", "bill", "."],
        extraUaTokens: ["суп", "десерт", "карткою"],
        extraRuTokens: ["суп", "десерт", "картой"],
        extraEnTokens: ["soup", "dessert", "card"],
    },

    [phraseKey("zapłacić", "a1-5")]: {
        sk: "Chcę zapłacić kartą.",
        ua: "Я хочу заплатити карткою.",
        ru: "Я хочу заплатить картой.",
        en: "I want to pay by card.",
        uaTokens: ["Я", "хочу", "заплатити", "карткою", "."],
        ruTokens: ["Я", "хочу", "заплатить", "картой", "."],
        enTokens: ["I", "want", "to", "pay", "by", "card", "."],
        uaAltAnswers: [["Я", "хочу", "карткою", "заплатити", "."]],
        ruAltAnswers: [["Я", "хочу", "картой", "заплатить", "."]],
        extraUaTokens: ["рахунок", "вечір", "суп"],
        extraRuTokens: ["счёт", "вечер", "суп"],
        extraEnTokens: ["bill", "evening", "soup"],
    },

    [phraseKey("rezerwacja", "a1-5")]: {
        sk: "Mam rezerwację na wieczór.",
        ua: "У мене бронювання на вечір.",
        ru: "У меня бронь на вечер.",
        en: "I have a reservation for the evening.",
        uaTokens: ["У", "мене", "бронювання", "на", "вечір", "."],
        ruTokens: ["У", "меня", "бронь", "на", "вечер", "."],
        enTokens: ["I", "have", "a", "reservation", "for", "the", "evening", "."],
        extraUaTokens: ["суп", "десерт", "карткою"],
        extraRuTokens: ["суп", "десерт", "картой"],
        extraEnTokens: ["soup", "dessert", "card"],
    },
};