import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A1_BUILD_UA_SENTENCES_2: BuildUaSentenceDict = {
    // =========================
    // LESSON 6 — Транспорт
    // =========================
    [phraseKey("rozkład jazdy", "a1-6")]: {
        sk: "Sprawdzam rozkład jazdy.",
        ua: "Я перевіряю розклад.",
        ru: "Я проверяю расписание.",
        en: "I check the timetable.",
        uaTokens: ["Я", "перевіряю", "розклад", "."],
        ruTokens: ["Я", "проверяю", "расписание", "."],
        enTokens: ["I", "check", "the", "timetable", "."],
        extraUaTokens: ["квиток", "ввечері", "платформи"],
        extraRuTokens: ["билет", "вечером", "платформы"],
        extraEnTokens: ["ticket", "evening", "platform"],
    },

    [phraseKey("przesiadka", "a1-6")]: {
        sk: "Mam jedną przesiadkę.",
        ua: "У мене одна пересадка.",
        ru: "У меня одна пересадка.",
        en: "I have one transfer.",
        uaTokens: ["У", "мене", "одна", "пересадка", "."],
        ruTokens: ["У", "меня", "одна", "пересадка", "."],
        enTokens: ["I", "have", "one", "transfer", "."],
        extraUaTokens: ["розклад", "автобус", "вже"],
        extraRuTokens: ["расписание", "автобус", "уже"],
        extraEnTokens: ["timetable", "bus", "already"],
    },

    [phraseKey("peron", "a1-6")]: {
        sk: "Pociąg stoi przy peronie.",
        ua: "Потяг стоїть біля платформи.",
        ru: "Поезд стоит у платформы.",
        en: "The train is at the platform.",
        uaTokens: ["Потяг", "стоїть", "біля", "платформи", "."],
        ruTokens: ["Поезд", "стоит", "у", "платформы", "."],
        enTokens: ["The", "train", "is", "at", "the", "platform", "."],
        extraUaTokens: ["розклад", "восьмій", "квиток"],
        extraRuTokens: ["расписание", "восемь", "билет"],
        extraEnTokens: ["timetable", "eight", "ticket"],
    },

    [phraseKey("spóźniać się", "a1-6")]: {
        sk: "Autobus często się spóźnia.",
        ua: "Автобус часто запізнюється.",
        ru: "Автобус часто опаздывает.",
        en: "The bus is often late.",
        uaTokens: ["Автобус", "часто", "запізнюється", "."],
        ruTokens: ["Автобус", "часто", "опаздывает", "."],
        enTokens: ["The", "bus", "is", "often", "late", "."],
        extraUaTokens: ["потяг", "стоїть", "ввечері"],
        extraRuTokens: ["поезд", "стоит", "вечером"],
        extraEnTokens: ["train", "stands", "evening"],
    },

    [phraseKey("wyjazd", "a1-6")]: {
        sk: "Wyjazd jest o ósmej.",
        ua: "Відправлення о восьмій.",
        ru: "Отправление в восемь.",
        en: "The departure is at eight.",
        uaTokens: ["Відправлення", "о", "восьмій", "."],
        ruTokens: ["Отправление", "в", "восемь", "."],
        enTokens: ["The", "departure", "is", "at", "eight", "."],
        extraUaTokens: ["пересадка", "тут", "вже"],
        extraRuTokens: ["пересадка", "здесь", "уже"],
        extraEnTokens: ["transfer", "here", "already"],
    },

    [phraseKey("przyjazd", "a1-6")]: {
        sk: "Przyjazd będzie wieczorem.",
        ua: "Прибуття буде ввечері.",
        ru: "Прибытие будет вечером.",
        en: "The arrival will be in the evening.",
        uaTokens: ["Прибуття", "буде", "ввечері", "."],
        ruTokens: ["Прибытие", "будет", "вечером", "."],
        enTokens: ["The", "arrival", "will", "be", "in", "the", "evening", "."],
        extraUaTokens: ["восьмій", "розклад", "платформи"],
        extraRuTokens: ["восемь", "расписание", "платформы"],
        extraEnTokens: ["eight", "timetable", "platform"],
    },

    [phraseKey("bilet", "a1-6")]: {
        sk: "Mam już bilet.",
        ua: "У мене вже є квиток.",
        ru: "У меня уже есть билет.",
        en: "I already have a ticket.",
        uaTokens: ["У", "мене", "вже", "є", "квиток", "."],
        ruTokens: ["У", "меня", "уже", "есть", "билет", "."],
        enTokens: ["I", "already", "have", "a", "ticket", "."],
        uaAltAnswers: [["У", "мене", "є", "вже", "квиток", "."]],
        enAltAnswers: [["I", "have", "a", "ticket", "already", "."]],
        extraUaTokens: ["розклад", "пересадка", "тут"],
        extraRuTokens: ["расписание", "пересадка", "здесь"],
        extraEnTokens: ["timetable", "transfer", "here"],
    },

    [phraseKey("kupić", "a1-6")]: {
        sk: "Chcę kupić bilet.",
        ua: "Я хочу купити квиток.",
        ru: "Я хочу купить билет.",
        en: "I want to buy a ticket.",
        uaTokens: ["Я", "хочу", "купити", "квиток", "."],
        ruTokens: ["Я", "хочу", "купить", "билет", "."],
        enTokens: ["I", "want", "to", "buy", "a", "ticket", "."],
        extraUaTokens: ["вже", "автобус", "платформи"],
        extraRuTokens: ["уже", "автобус", "платформы"],
        extraEnTokens: ["already", "bus", "platform"],
    },

    [phraseKey("wysiąść", "a1-6")]: {
        sk: "Muszę wysiąść tutaj.",
        ua: "Мені треба вийти тут.",
        ru: "Мне нужно выйти здесь.",
        en: "I need to get off here.",
        uaTokens: ["Мені", "треба", "вийти", "тут", "."],
        ruTokens: ["Мне", "нужно", "выйти", "здесь", "."],
        enTokens: ["I", "need", "to", "get", "off", "here", "."],
        extraUaTokens: ["квиток", "вечором", "пересадка"],
        extraRuTokens: ["билет", "вечером", "пересадка"],
        extraEnTokens: ["ticket", "evening", "transfer"],
    },

    [phraseKey("wsiąść", "a1-6")]: {
        sk: "Musimy wsiąść do autobusu.",
        ua: "Нам треба сісти в автобус.",
        ru: "Нам нужно сесть в автобус.",
        en: "We need to get on the bus.",
        uaTokens: ["Нам", "треба", "сісти", "в", "автобус", "."],
        ruTokens: ["Нам", "нужно", "сесть", "в", "автобус", "."],
        enTokens: ["We", "need", "to", "get", "on", "the", "bus", "."],
        extraUaTokens: ["тут", "квиток", "потяг"],
        extraRuTokens: ["здесь", "билет", "поезд"],
        extraEnTokens: ["here", "ticket", "train"],
    },

    // =========================
    // LESSON 7 — Дім (побутові дії)
    // =========================
    [phraseKey("gotować", "a1-7")]: {
        sk: "Lubię gotować w domu.",
        ua: "Я люблю готувати вдома.",
        ru: "Я люблю готовить дома.",
        en: "I like cooking at home.",
        uaTokens: ["Я", "люблю", "готувати", "вдома", "."],
        ruTokens: ["Я", "люблю", "готовить", "дома", "."],
        enTokens: ["I", "like", "cooking", "at", "home", "."],
        extraUaTokens: ["сьогодні", "вікно", "одяг"],
        extraRuTokens: ["сегодня", "окно", "одежду"],
        extraEnTokens: ["today", "window", "clothes"],
    },

    [phraseKey("sprzątać", "a1-7")]: {
        sk: "Muszę dziś sprzątać.",
        ua: "Мені треба сьогодні прибирати.",
        ru: "Мне нужно сегодня убирать.",
        en: "I need to clean today.",
        uaTokens: ["Мені", "треба", "сьогодні", "прибирати", "."],
        ruTokens: ["Мне", "нужно", "сегодня", "убирать", "."],
        enTokens: ["I", "need", "to", "clean", "today", "."],
        uaAltAnswers: [["Мені", "сьогодні", "треба", "прибирати", "."]],
        ruAltAnswers: [["Мне", "сегодня", "нужно", "убирать", "."]],
        extraUaTokens: ["двері", "руки", "вдома"],
        extraRuTokens: ["дверь", "руки", "дома"],
        extraEnTokens: ["door", "hands", "home"],
    },

    [phraseKey("myć", "a1-7")]: {
        sk: "Myję ręce przed obiadem.",
        ua: "Я мию руки перед обідом.",
        ru: "Я мою руки перед обедом.",
        en: "I wash my hands before lunch.",
        uaTokens: ["Я", "мию", "руки", "перед", "обідом", "."],
        ruTokens: ["Я", "мою", "руки", "перед", "обедом", "."],
        enTokens: ["I", "wash", "my", "hands", "before", "lunch", "."],
        extraUaTokens: ["ключі", "сьогодні", "світло"],
        extraRuTokens: ["ключи", "сегодня", "свет"],
        extraEnTokens: ["keys", "today", "light"],
    },

    [phraseKey("prać", "a1-7")]: {
        sk: "Muszę prać ubrania.",
        ua: "Мені треба прати одяг.",
        ru: "Мне нужно стирать одежду.",
        en: "I need to wash clothes.",
        uaTokens: ["Мені", "треба", "прати", "одяг", "."],
        ruTokens: ["Мне", "нужно", "стирать", "одежду", "."],
        enTokens: ["I", "need", "to", "wash", "clothes", "."],
        extraUaTokens: ["сьогодні", "вікно", "руки"],
        extraRuTokens: ["сегодня", "окно", "руки"],
        extraEnTokens: ["today", "window", "hands"],
    },

    [phraseKey("prasować", "a1-7")]: {
        sk: "Nie lubię prasować koszul.",
        ua: "Я не люблю прасувати сорочки.",
        ru: "Я не люблю гладить рубашки.",
        en: "I do not like ironing shirts.",
        uaTokens: ["Я", "не", "люблю", "прасувати", "сорочки", "."],
        ruTokens: ["Я", "не", "люблю", "гладить", "рубашки", "."],
        enTokens: ["I", "do", "not", "like", "ironing", "shirts", "."],
        extraUaTokens: ["одяг", "вдома", "перед"],
        extraRuTokens: ["одежду", "дома", "перед"],
        extraEnTokens: ["clothes", "home", "before"],
    },

    [phraseKey("otworzyć", "a1-7")]: {
        sk: "Możesz otworzyć okno?",
        ua: "Можеш відкрити вікно?",
        ru: "Можешь открыть окно?",
        en: "Can you open the window?",
        uaTokens: ["Можеш", "відкрити", "вікно", "?"],
        ruTokens: ["Можешь", "открыть", "окно", "?"],
        enTokens: ["Can", "you", "open", "the", "window", "?"],
        extraUaTokens: ["двері", "світло", "сьогодні"],
        extraRuTokens: ["дверь", "свет", "сегодня"],
        extraEnTokens: ["door", "light", "today"],
    },

    [phraseKey("zamknąć", "a1-7")]: {
        sk: "Proszę zamknąć drzwi.",
        ua: "Будь ласка, закрий двері.",
        ru: "Пожалуйста, закрой дверь.",
        en: "Please close the door.",
        uaTokens: ["Будь", "ласка", ",", "закрий", "двері", "."],
        ruTokens: ["Пожалуйста", ",", "закрой", "дверь", "."],
        enTokens: ["Please", "close", "the", "door", "."],
        extraUaTokens: ["вікно", "ключі", "світло"],
        extraRuTokens: ["окно", "ключи", "свет"],
        extraEnTokens: ["window", "keys", "light"],
    },

    [phraseKey("włączyć", "a1-7")]: {
        sk: "Włącz światło, proszę.",
        ua: "Увімкни світло, будь ласка.",
        ru: "Включи свет, пожалуйста.",
        en: "Turn on the light, please.",
        uaTokens: ["Увімкни", "світло", ",", "будь", "ласка", "."],
        ruTokens: ["Включи", "свет", ",", "пожалуйста", "."],
        enTokens: ["Turn", "on", "the", "light", ",", "please", "."],
        extraUaTokens: ["телевізор", "двері", "вікно"],
        extraRuTokens: ["телевизор", "дверь", "окно"],
        extraEnTokens: ["TV", "door", "window"],
    },

    [phraseKey("wyłączyć", "a1-7")]: {
        sk: "Wyłącz telewizor.",
        ua: "Вимкни телевізор.",
        ru: "Выключи телевизор.",
        en: "Turn off the TV.",
        uaTokens: ["Вимкни", "телевізор", "."],
        ruTokens: ["Выключи", "телевизор", "."],
        enTokens: ["Turn", "off", "the", "TV", "."],
        extraUaTokens: ["світло", "ключі", "вікно"],
        extraRuTokens: ["свет", "ключи", "окно"],
        extraEnTokens: ["light", "keys", "window"],
    },

    [phraseKey("szukać", "a1-7")]: {
        sk: "Szukam kluczy.",
        ua: "Я шукаю ключі.",
        ru: "Я ищу ключи.",
        en: "I am looking for the keys.",
        uaTokens: ["Я", "шукаю", "ключі", "."],
        ruTokens: ["Я", "ищу", "ключи", "."],
        enTokens: ["I", "am", "looking", "for", "the", "keys", "."],
        extraUaTokens: ["двері", "сьогодні", "світло"],
        extraRuTokens: ["дверь", "сегодня", "свет"],
        extraEnTokens: ["door", "today", "light"],
    },

    // =========================
    // LESSON 8 — Робота (процеси)
    // =========================
    [phraseKey("miejsce pracy", "a1-8")]: {
        sk: "Moje miejsce pracy jest daleko.",
        ua: "Моє робоче місце далеко.",
        ru: "Моё рабочее место далеко.",
        en: "My workplace is far away.",
        uaTokens: ["Моє", "робоче", "місце", "далеко", "."],
        ruTokens: ["Моё", "рабочее", "место", "далеко", "."],
        enTokens: ["My", "workplace", "is", "far", "away", "."],
        extraUaTokens: ["зміна", "ранку", "нове"],
        extraRuTokens: ["смена", "утро", "новое"],
        extraEnTokens: ["shift", "morning", "new"],
    },

    [phraseKey("zmiana", "a1-8")]: {
        sk: "Dziś mam nocną zmianę.",
        ua: "Сьогодні у мене нічна зміна.",
        ru: "Сегодня у меня ночная смена.",
        en: "Today I have a night shift.",
        uaTokens: ["Сьогодні", "у", "мене", "нічна", "зміна", "."],
        ruTokens: ["Сегодня", "у", "меня", "ночная", "смена", "."],
        enTokens: ["Today", "I", "have", "a", "night", "shift", "."],
        extraUaTokens: ["робота", "далеко", "завдання"],
        extraRuTokens: ["работа", "далеко", "задание"],
        extraEnTokens: ["work", "far", "task"],
    },

    [phraseKey("nadgodziny", "a1-8")]: {
        sk: "Dziś pracuję w nadgodzinach.",
        ua: "Сьогодні я працюю понаднормово.",
        ru: "Сегодня я работаю сверхурочно.",
        en: "Today I am working overtime.",
        uaTokens: ["Сьогодні", "я", "працюю", "понаднормово", "."],
        ruTokens: ["Сегодня", "я", "работаю", "сверхурочно", "."],
        enTokens: ["Today", "I", "am", "working", "overtime", "."],
        extraUaTokens: ["зміна", "вранці", "завдання"],
        extraRuTokens: ["смена", "утром", "задание"],
        extraEnTokens: ["shift", "morning", "task"],
    },

    [phraseKey("narada", "a1-8")]: {
        sk: "Rano mamy naradę.",
        ua: "Вранці у нас нарада.",
        ru: "Утром у нас совещание.",
        en: "We have a meeting in the morning.",
        uaTokens: ["Вранці", "у", "нас", "нарада", "."],
        ruTokens: ["Утром", "у", "нас", "совещание", "."],
        enTokens: ["We", "have", "a", "meeting", "in", "the", "morning", "."],
        extraUaTokens: ["нічна", "далеко", "завдання"],
        extraRuTokens: ["ночная", "далеко", "задание"],
        extraEnTokens: ["night", "far", "task"],
    },

    [phraseKey("zadanie", "a1-8")]: {
        sk: "Mam nowe zadanie.",
        ua: "У мене нове завдання.",
        ru: "У меня новое задание.",
        en: "I have a new task.",
        uaTokens: ["У", "мене", "нове", "завдання", "."],
        ruTokens: ["У", "меня", "новое", "задание", "."],
        enTokens: ["I", "have", "a", "new", "task", "."],
        extraUaTokens: ["робота", "раніше", "готово"],
        extraRuTokens: ["работа", "раньше", "готово"],
        extraEnTokens: ["work", "earlier", "done"],
    },

    [phraseKey("gotowe", "a1-8")]: {
        sk: "To już gotowe.",
        ua: "Це вже готово.",
        ru: "Это уже готово.",
        en: "It is already done.",
        uaTokens: ["Це", "вже", "готово", "."],
        ruTokens: ["Это", "уже", "готово", "."],
        enTokens: ["It", "is", "already", "done", "."],
        extraUaTokens: ["завдання", "нове", "починати"],
        extraRuTokens: ["задание", "новое", "начинать"],
        extraEnTokens: ["task", "new", "start"],
    },

    [phraseKey("sprawdzić", "a1-8")]: {
        sk: "Muszę to sprawdzić.",
        ua: "Мені треба це перевірити.",
        ru: "Мне нужно это проверить.",
        en: "I need to check it.",
        uaTokens: ["Мені", "треба", "це", "перевірити", "."],
        ruTokens: ["Мне", "нужно", "это", "проверить", "."],
        enTokens: ["I", "need", "to", "check", "it", "."],
        uaAltAnswers: [["Мені", "це", "треба", "перевірити", "."]],
        ruAltAnswers: [["Мне", "это", "нужно", "проверить", "."]],
        extraUaTokens: ["завдання", "готово", "раніше"],
        extraRuTokens: ["задание", "готово", "раньше"],
        extraEnTokens: ["task", "done", "earlier"],
    },

    [phraseKey("naprawić", "a1-8")]: {
        sk: "Trzeba to naprawić.",
        ua: "Це треба полагодити.",
        ru: "Это нужно починить.",
        en: "It needs to be fixed.",
        uaTokens: ["Це", "треба", "полагодити", "."],
        ruTokens: ["Это", "нужно", "починить", "."],
        enTokens: ["It", "needs", "to", "be", "fixed", "."],
        extraUaTokens: ["перевірити", "завдання", "роботу"],
        extraRuTokens: ["проверить", "задание", "работу"],
        extraEnTokens: ["check", "task", "work"],
    },

    [phraseKey("zacząć", "a1-8")]: {
        sk: "Czas zacząć pracę.",
        ua: "Час починати роботу.",
        ru: "Пора начинать работу.",
        en: "It is time to start work.",
        uaTokens: ["Час", "починати", "роботу", "."],
        ruTokens: ["Пора", "начинать", "работу", "."],
        enTokens: ["It", "is", "time", "to", "start", "work", "."],
        extraUaTokens: ["завдання", "раніше", "нове"],
        extraRuTokens: ["задание", "раньше", "новое"],
        extraEnTokens: ["task", "earlier", "new"],
    },

    [phraseKey("skończyć", "a1-8")]: {
        sk: "Chcę skończyć wcześniej.",
        ua: "Я хочу закінчити раніше.",
        ru: "Я хочу закончить раньше.",
        en: "I want to finish earlier.",
        uaTokens: ["Я", "хочу", "закінчити", "раніше", "."],
        ruTokens: ["Я", "хочу", "закончить", "раньше", "."],
        enTokens: ["I", "want", "to", "finish", "earlier", "."],
        extraUaTokens: ["роботу", "час", "сьогодні"],
        extraRuTokens: ["работу", "время", "сегодня"],
        extraEnTokens: ["work", "time", "today"],
    },

    // =========================
    // LESSON 9 — Емоції і стани
    // =========================
    [phraseKey("zmęczony", "a1-9")]: {
        sk: "Jestem dziś bardzo zmęczony.",
        ua: "Я сьогодні дуже втомлений.",
        ru: "Я сегодня очень уставший.",
        en: "I am very tired today.",
        uaTokens: ["Я", "сьогодні", "дуже", "втомлений", "."],
        ruTokens: ["Я", "сегодня", "очень", "уставший", "."],
        enTokens: ["I", "am", "very", "tired", "today", "."],
        uaAltAnswers: [["Я", "дуже", "втомлений", "сьогодні", "."]],
        ruAltAnswers: [["Я", "очень", "уставший", "сегодня", "."]],
        extraUaTokens: ["спокійний", "новиною", "іспитом"],
        extraRuTokens: ["спокойный", "новостью", "экзаменом"],
        extraEnTokens: ["calm", "news", "exam"],
    },

    [phraseKey("szczęśliwy", "a1-9")]: {
        sk: "Jestem szczęśliwy.",
        ua: "Я щасливий.",
        ru: "Я счастлив.",
        en: "I am happy.",
        uaTokens: ["Я", "щасливий", "."],
        ruTokens: ["Я", "счастлив", "."],
        enTokens: ["I", "am", "happy", "."],
        extraUaTokens: ["дуже", "сьогодні", "новиною"],
        extraRuTokens: ["очень", "сегодня", "новостью"],
        extraEnTokens: ["very", "today", "news"],
    },

    [phraseKey("smutny", "a1-9")]: {
        sk: "On wygląda na smutnego.",
        ua: "Він виглядає сумним.",
        ru: "Он выглядит грустным.",
        en: "He looks sad.",
        uaTokens: ["Він", "виглядає", "сумним", "."],
        ruTokens: ["Он", "выглядит", "грустным", "."],
        enTokens: ["He", "looks", "sad", "."],
        extraUaTokens: ["сьогодні", "дуже", "спокійний"],
        extraRuTokens: ["сегодня", "очень", "спокойный"],
        extraEnTokens: ["today", "very", "calm"],
    },

    [phraseKey("zdenerwowany", "a1-9")]: {
        sk: "Jestem zdenerwowany.",
        ua: "Я роздратований.",
        ru: "Я сердитый.",
        en: "I am angry.",
        uaTokens: ["Я", "роздратований", "."],
        ruTokens: ["Я", "сердитый", "."],
        enTokens: ["I", "am", "angry", "."],
        extraUaTokens: ["дуже", "сьогодні", "новиною"],
        extraRuTokens: ["очень", "сегодня", "новостью"],
        extraEnTokens: ["very", "today", "news"],
    },

    [phraseKey("nerwowy", "a1-9")]: {
        sk: "Przed egzaminem jestem nerwowy.",
        ua: "Перед іспитом я нервуюся.",
        ru: "Перед экзаменом я нервничаю.",
        en: "I am nervous before the exam.",
        uaTokens: ["Перед", "іспитом", "я", "нервуюся", "."],
        ruTokens: ["Перед", "экзаменом", "я", "нервничаю", "."],
        enTokens: ["I", "am", "nervous", "before", "the", "exam", "."],
        extraUaTokens: ["сьогодні", "дуже", "спокійний"],
        extraRuTokens: ["сегодня", "очень", "спокойный"],
        extraEnTokens: ["today", "very", "calm"],
    },

    [phraseKey("spokojny", "a1-9")]: {
        sk: "Dziś jestem spokojny.",
        ua: "Сьогодні я спокійний.",
        ru: "Сегодня я спокойный.",
        en: "Today I am calm.",
        uaTokens: ["Сьогодні", "я", "спокійний", "."],
        ruTokens: ["Сегодня", "я", "спокойный", "."],
        enTokens: ["Today", "I", "am", "calm", "."],
        extraUaTokens: ["іспитом", "сумним", "новиною"],
        extraRuTokens: ["экзаменом", "грустным", "новостью"],
        extraEnTokens: ["exam", "sad", "news"],
    },

    [phraseKey("zaskoczony", "a1-9")]: {
        sk: "Jestem zaskoczony tą wiadomością.",
        ua: "Я здивований цією новиною.",
        ru: "Я удивлён этой новостью.",
        en: "I am surprised by this news.",
        uaTokens: ["Я", "здивований", "цією", "новиною", "."],
        ruTokens: ["Я", "удивлён", "этой", "новостью", "."],
        enTokens: ["I", "am", "surprised", "by", "this", "news", "."],
        extraUaTokens: ["дуже", "спокійний", "сьогодні"],
        extraRuTokens: ["очень", "спокойный", "сегодня"],
        extraEnTokens: ["very", "calm", "today"],
    },

    [phraseKey("bać się", "a1-9")]: {
        sk: "Nie boję się psa.",
        ua: "Я не боюся собаки.",
        ru: "Я не боюсь собаки.",
        en: "I am not afraid of the dog.",
        uaTokens: ["Я", "не", "боюся", "собаки", "."],
        ruTokens: ["Я", "не", "боюсь", "собаки", "."],
        enTokens: ["I", "am", "not", "afraid", "of", "the", "dog", "."],
        extraUaTokens: ["новиною", "щасливий", "дуже"],
        extraRuTokens: ["новостью", "счастливый", "очень"],
        extraEnTokens: ["news", "happy", "very"],
    },

    [phraseKey("cieszyć się", "a1-9")]: {
        sk: "Cieszę się na weekend.",
        ua: "Я з радістю чекаю вихідних.",
        ru: "Я с радостью жду выходных.",
        en: "I am looking forward to the weekend.",
        uaTokens: ["Я", "з", "радістю", "чекаю", "вихідних", "."],
        ruTokens: ["Я", "с", "радостью", "жду", "выходных", "."],
        enTokens: ["I", "am", "looking", "forward", "to", "the", "weekend", "."],
        extraUaTokens: ["кави", "новиною", "сьогодні"],
        extraRuTokens: ["кофе", "новостью", "сегодня"],
        extraEnTokens: ["coffee", "news", "today"],
    },

    [phraseKey("mieć ochotę", "a1-9")]: {
        sk: "Mam ochotę na kawę.",
        ua: "Я хочу кави.",
        ru: "Мне хочется кофе.",
        en: "I feel like having coffee.",
        uaTokens: ["Я", "хочу", "кави", "."],
        ruTokens: ["Мне", "хочется", "кофе", "."],
        enTokens: ["I", "feel", "like", "having", "coffee", "."],
        extraUaTokens: ["вихідних", "дуже", "сьогодні"],
        extraRuTokens: ["выходных", "очень", "сегодня"],
        extraEnTokens: ["weekend", "very", "today"],
    },

    // =========================
    // LESSON 10 — Запитання
    // =========================
    [phraseKey("który", "a1-10")]: {
        sk: "Który autobus jedzie do centrum?",
        ua: "Який автобус їде в центр?",
        ru: "Какой автобус едет в центр?",
        en: "Which bus goes to the center?",
        uaTokens: ["Який", "автобус", "їде", "в", "центр", "?"],
        ruTokens: ["Какой", "автобус", "едет", "в", "центр", "?"],
        enTokens: ["Which", "bus", "goes", "to", "the", "center", "?"],
        extraUaTokens: ["аптека", "телефон", "це"],
        extraRuTokens: ["аптека", "телефон", "это"],
        extraEnTokens: ["pharmacy", "phone", "it"],
    },

    [phraseKey("jaki", "a1-10")]: {
        sk: "Jaki to kolor?",
        ua: "Який це колір?",
        ru: "Какой это цвет?",
        en: "What color is it?",
        uaTokens: ["Який", "це", "колір", "?"],
        ruTokens: ["Какой", "это", "цвет", "?"],
        enTokens: ["What", "color", "is", "it", "?"],
        extraUaTokens: ["телефон", "аптека", "центр"],
        extraRuTokens: ["телефон", "аптека", "центр"],
        extraEnTokens: ["phone", "pharmacy", "center"],
    },

    [phraseKey("czyj", "a1-10")]: {
        sk: "Czyj to telefon?",
        ua: "Чий це телефон?",
        ru: "Чей это телефон?",
        en: "Whose phone is this?",
        uaTokens: ["Чий", "це", "телефон", "?"],
        ruTokens: ["Чей", "это", "телефон", "?"],
        enTokens: ["Whose", "phone", "is", "this", "?"],
        extraUaTokens: ["колір", "аптека", "центр"],
        extraRuTokens: ["цвет", "аптека", "центр"],
        extraEnTokens: ["color", "pharmacy", "center"],
    },

    [phraseKey("gdzie jest", "a1-10")]: {
        sk: "Gdzie jest apteka?",
        ua: "Де аптека?",
        ru: "Где аптека?",
        en: "Where is the pharmacy?",
        uaTokens: ["Де", "аптека", "?"],
        ruTokens: ["Где", "аптека", "?"],
        enTokens: ["Where", "is", "the", "pharmacy", "?"],
        extraUaTokens: ["центр", "телефон", "колір"],
        extraRuTokens: ["центр", "телефон", "цвет"],
        extraEnTokens: ["center", "phone", "color"],
    },

    [phraseKey("ile to kosztuje", "a1-10")]: {
        sk: "Ile to kosztuje?",
        ua: "Скільки це коштує?",
        ru: "Сколько это стоит?",
        en: "How much does it cost?",
        uaTokens: ["Скільки", "це", "коштує", "?"],
        ruTokens: ["Сколько", "это", "стоит", "?"],
        enTokens: ["How", "much", "does", "it", "cost", "?"],
        extraUaTokens: ["аптека", "телефон", "повторити"],
        extraRuTokens: ["аптека", "телефон", "повторить"],
        extraEnTokens: ["pharmacy", "phone", "repeat"],
    },

    [phraseKey("czy możecie powtórzyć", "a1-10")]: {
        sk: "Czy możecie powtórzyć?",
        ua: "Можете повторити?",
        ru: "Можете повторить?",
        en: "Can you repeat?",
        uaTokens: ["Можете", "повторити", "?"],
        ruTokens: ["Можете", "повторить", "?"],
        enTokens: ["Can", "you", "repeat", "?"],
        extraUaTokens: ["це", "скільки", "означає"],
        extraRuTokens: ["это", "сколько", "значит"],
        extraEnTokens: ["it", "how", "means"],
    },

    [phraseKey("co to znaczy", "a1-10")]: {
        sk: "Co to znaczy?",
        ua: "Що це означає?",
        ru: "Что это значит?",
        en: "What does it mean?",
        uaTokens: ["Що", "це", "означає", "?"],
        ruTokens: ["Что", "это", "значит", "?"],
        enTokens: ["What", "does", "it", "mean", "?"],
        extraUaTokens: ["телефон", "скільки", "повторити"],
        extraRuTokens: ["телефон", "сколько", "повторить"],
        extraEnTokens: ["phone", "how", "repeat"],
    },

    [phraseKey("rozumiecie", "a1-10")]: {
        sk: "Rozumiecie mnie?",
        ua: "Ви мене розумієте?",
        ru: "Вы меня понимаете?",
        en: "Do you understand me?",
        uaTokens: ["Ви", "мене", "розумієте", "?"],
        ruTokens: ["Вы", "меня", "понимаете", "?"],
        enTokens: ["Do", "you", "understand", "me", "?"],
        extraUaTokens: ["це", "аптека", "телефон"],
        extraRuTokens: ["это", "аптека", "телефон"],
        extraEnTokens: ["it", "pharmacy", "phone"],
    },

    [phraseKey("oczywiście", "a1-10")]: {
        sk: "Oczywiście, że tak.",
        ua: "Звісно, що так.",
        ru: "Конечно, да.",
        en: "Of course.",
        uaTokens: ["Звісно", ",", "що", "так", "."],
        ruTokens: ["Конечно", ",", "да", "."],
        enTokens: ["Of", "course", "."],
        extraUaTokens: ["не", "це", "означає"],
        extraRuTokens: ["не", "это", "значит"],
        extraEnTokens: ["not", "it", "mean"],
    },

    [phraseKey("nie wiem", "a1-10")]: {
        sk: "Nie wiem.",
        ua: "Я не знаю.",
        ru: "Я не знаю.",
        en: "I do not know.",
        uaTokens: ["Я", "не", "знаю", "."],
        ruTokens: ["Я", "не", "знаю", "."],
        enTokens: ["I", "do", "not", "know", "."],
        extraUaTokens: ["це", "скільки", "телефон"],
        extraRuTokens: ["это", "сколько", "телефон"],
        extraEnTokens: ["it", "how", "phone"],
    },
};