import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A1_BUILD_UA_SENTENCES_4: BuildUaSentenceDict = {
    // =========================
    // LESSON 16 — Здоровʼя
    // =========================
    [phraseKey("boleć", "a1-16")]: {
        sk: "Boli mnie głowa.",
        ua: "У мене болить голова.",
        ru: "У меня болит голова.",
        en: "My head hurts.",
        uaTokens: ["У", "мене", "болить", "голова", "."],
        ruTokens: ["У", "меня", "болит", "голова", "."],
        enTokens: ["My", "head", "hurts", "."],
        extraUaTokens: ["таблетку", "сьогодні", "лікар"],
        extraRuTokens: ["таблетку", "сегодня", "врач"],
        extraEnTokens: ["pill", "today", "doctor"],
    },

    [phraseKey("głowa", "a1-16")]: {
        sk: "Moja głowa bardzo boli.",
        ua: "Моя голова дуже болить.",
        ru: "Моя голова очень болит.",
        en: "My head hurts a lot.",
        uaTokens: ["Моя", "голова", "дуже", "болить", "."],
        ruTokens: ["Моя", "голова", "очень", "болит", "."],
        enTokens: ["My", "head", "hurts", "a", "lot", "."],
        extraUaTokens: ["лікар", "пацієнтів", "здоровим"],
        extraRuTokens: ["врач", "пациентов", "здоровым"],
        extraEnTokens: ["doctor", "patients", "healthy"],
    },

    [phraseKey("ząb", "a1-16")]: {
        sk: "Boli mnie ząb.",
        ua: "У мене болить зуб.",
        ru: "У меня болит зуб.",
        en: "My tooth hurts.",
        uaTokens: ["У", "мене", "болить", "зуб", "."],
        ruTokens: ["У", "меня", "болит", "зуб", "."],
        enTokens: ["My", "tooth", "hurts", "."],
        extraUaTokens: ["шлунок", "таблетку", "кашлю"],
        extraRuTokens: ["желудок", "таблетку", "кашля"],
        extraEnTokens: ["stomach", "pill", "cough"],
    },

    [phraseKey("żołądek", "a1-16")]: {
        sk: "Boli mnie żołądek.",
        ua: "У мене болить шлунок.",
        ru: "У меня болит желудок.",
        en: "My stomach hurts.",
        uaTokens: ["У", "мене", "болить", "шлунок", "."],
        ruTokens: ["У", "меня", "болит", "желудок", "."],
        enTokens: ["My", "stomach", "hurts", "."],
        extraUaTokens: ["зуб", "сироп", "лікує"],
        extraRuTokens: ["зуб", "сироп", "лечит"],
        extraEnTokens: ["tooth", "syrup", "treats"],
    },

    [phraseKey("tabletka", "a1-16")]: {
        sk: "Biorę tabletkę.",
        ua: "Я приймаю таблетку.",
        ru: "Я принимаю таблетку.",
        en: "I take a pill.",
        uaTokens: ["Я", "приймаю", "таблетку", "."],
        ruTokens: ["Я", "принимаю", "таблетку", "."],
        enTokens: ["I", "take", "a", "pill", "."],
        extraUaTokens: ["шлунок", "відпочивати", "пацієнтів"],
        extraRuTokens: ["желудок", "отдыхать", "пациентов"],
        extraEnTokens: ["stomach", "rest", "patients"],
    },

    [phraseKey("syrop", "a1-16")]: {
        sk: "Piję syrop na kaszel.",
        ua: "Я п’ю сироп від кашлю.",
        ru: "Я пью сироп от кашля.",
        en: "I drink cough syrup.",
        uaTokens: ["Я", "п’ю", "сироп", "від", "кашлю", "."],
        ruTokens: ["Я", "пью", "сироп", "от", "кашля", "."],
        enTokens: ["I", "drink", "cough", "syrup", "."],
        extraUaTokens: ["таблетку", "зуб", "сьогодні"],
        extraRuTokens: ["таблетку", "зуб", "сегодня"],
        extraEnTokens: ["pill", "tooth", "today"],
    },

    [phraseKey("odpoczywać", "a1-16")]: {
        sk: "Muszę odpoczywać.",
        ua: "Мені треба відпочивати.",
        ru: "Мне нужно отдыхать.",
        en: "I need to rest.",
        uaTokens: ["Мені", "треба", "відпочивати", "."],
        ruTokens: ["Мне", "нужно", "отдыхать", "."],
        enTokens: ["I", "need", "to", "rest", "."],
        extraUaTokens: ["сьогодні", "лікар", "здоровим"],
        extraRuTokens: ["сегодня", "врач", "здоровым"],
        extraEnTokens: ["today", "doctor", "healthy"],
    },

    [phraseKey("zdrowy", "a1-16")]: {
        sk: "Chcę być zdrowy.",
        ua: "Я хочу бути здоровим.",
        ru: "Я хочу быть здоровым.",
        en: "I want to be healthy.",
        uaTokens: ["Я", "хочу", "бути", "здоровим", "."],
        ruTokens: ["Я", "хочу", "быть", "здоровым", "."],
        enTokens: ["I", "want", "to", "be", "healthy", "."],
        extraUaTokens: ["сьогодні", "таблетку", "лікує"],
        extraRuTokens: ["сегодня", "таблетку", "лечит"],
        extraEnTokens: ["today", "pill", "treats"],
    },

    [phraseKey("chory", "a1-16")]: {
        sk: "Dziś jestem chory.",
        ua: "Сьогодні я хворий.",
        ru: "Сегодня я болен.",
        en: "I am ill today.",
        uaTokens: ["Сьогодні", "я", "хворий", "."],
        ruTokens: ["Сегодня", "я", "болен", "."],
        enTokens: ["I", "am", "ill", "today", "."],
        extraUaTokens: ["голова", "лікар", "відпочивати"],
        extraRuTokens: ["голова", "врач", "отдыхать"],
        extraEnTokens: ["head", "doctor", "rest"],
    },

    [phraseKey("leczyć", "a1-16")]: {
        sk: "Lekarz leczy pacjentów.",
        ua: "Лікар лікує пацієнтів.",
        ru: "Врач лечит пациентов.",
        en: "The doctor treats patients.",
        uaTokens: ["Лікар", "лікує", "пацієнтів", "."],
        ruTokens: ["Врач", "лечит", "пациентов", "."],
        enTokens: ["The", "doctor", "treats", "patients", "."],
        extraUaTokens: ["сьогодні", "таблетку", "шлунок"],
        extraRuTokens: ["сегодня", "таблетку", "желудок"],
        extraEnTokens: ["today", "pill", "stomach"],
    },

    // =========================
    // LESSON 17 — Робота (словник)
    // =========================
    [phraseKey("pracownik", "a1-17")]: {
        sk: "Jestem nowym pracownikiem.",
        ua: "Я новий працівник.",
        ru: "Я новый сотрудник.",
        en: "I am a new employee.",
        uaTokens: ["Я", "новий", "працівник", "."],
        ruTokens: ["Я", "новый", "сотрудник", "."],
        enTokens: ["I", "am", "a", "new", "employee", "."],
        extraUaTokens: ["зарплата", "роботодавець", "обов’язок"],
        extraRuTokens: ["зарплата", "работодатель", "обязанность"],
        extraEnTokens: ["salary", "employer", "duty"],
    },

    [phraseKey("pracodawca", "a1-17")]: {
        sk: "Mój pracodawca jest wymagający.",
        ua: "Мій роботодавець вимогливий.",
        ru: "Мой работодатель требовательный.",
        en: "My employer is demanding.",
        uaTokens: ["Мій", "роботодавець", "вимогливий", "."],
        ruTokens: ["Мой", "работодатель", "требовательный", "."],
        enTokens: ["My", "employer", "is", "demanding", "."],
        extraUaTokens: ["зарплата", "кар’єру", "право"],
        extraRuTokens: ["зарплата", "карьеру", "право"],
        extraEnTokens: ["salary", "career", "right"],
    },

    [phraseKey("wynagrodzenie", "a1-17")]: {
        sk: "Moje wynagrodzenie jest dobre.",
        ua: "Моя зарплата хороша.",
        ru: "Моя зарплата хорошая.",
        en: "My salary is good.",
        uaTokens: ["Моя", "зарплата", "хороша", "."],
        ruTokens: ["Моя", "зарплата", "хорошая", "."],
        enTokens: ["My", "salary", "is", "good", "."],
        extraUaTokens: ["роботодавець", "договір", "кар’єру"],
        extraRuTokens: ["работодатель", "договор", "карьеру"],
        extraEnTokens: ["employer", "contract", "career"],
    },

    [phraseKey("umowa o pracę", "a1-17")]: {
        sk: "Mam umowę o pracę.",
        ua: "У мене є трудовий договір.",
        ru: "У меня есть трудовой договор.",
        en: "I have an employment contract.",
        uaTokens: ["У", "мене", "є", "трудовий", "договір", "."],
        ruTokens: ["У", "меня", "есть", "трудовой", "договор", "."],
        enTokens: ["I", "have", "an", "employment", "contract", "."],
        extraUaTokens: ["зарплата", "обов’язок", "кар’єру"],
        extraRuTokens: ["зарплата", "обязанность", "карьеру"],
        extraEnTokens: ["salary", "duty", "career"],
    },

    [phraseKey("praktyka", "a1-17")]: {
        sk: "Mam już praktykę w tej pracy.",
        ua: "У мене вже є досвід у цій роботі.",
        ru: "У меня уже есть опыт в этой работе.",
        en: "I already have experience in this job.",
        uaTokens: ["У", "мене", "вже", "є", "досвід", "у", "цій", "роботі", "."],
        ruTokens: ["У", "меня", "уже", "есть", "опыт", "в", "этой", "работе", "."],
        enTokens: ["I", "already", "have", "experience", "in", "this", "job", "."],
        extraUaTokens: ["зарплата", "кар’єру", "право"],
        extraRuTokens: ["зарплата", "карьеру", "право"],
        extraEnTokens: ["salary", "career", "right"],
    },

    [phraseKey("kariera", "a1-17")]: {
        sk: "Chcę rozwijać swoją karierę.",
        ua: "Я хочу розвивати свою кар’єру.",
        ru: "Я хочу развивать свою карьеру.",
        en: "I want to develop my career.",
        uaTokens: ["Я", "хочу", "розвивати", "свою", "кар’єру", "."],
        ruTokens: ["Я", "хочу", "развивать", "свою", "карьеру", "."],
        enTokens: ["I", "want", "to", "develop", "my", "career", "."],
        extraUaTokens: ["роботодавець", "підвищення", "обов’язок"],
        extraRuTokens: ["работодатель", "повышение", "обязанность"],
        extraEnTokens: ["employer", "promotion", "duty"],
    },

    [phraseKey("awans", "a1-17")]: {
        sk: "Dostał awans w pracy.",
        ua: "Він отримав підвищення на роботі.",
        ru: "Он получил повышение на работе.",
        en: "He got a promotion at work.",
        uaTokens: ["Він", "отримав", "підвищення", "на", "роботі", "."],
        ruTokens: ["Он", "получил", "повышение", "на", "работе", "."],
        enTokens: ["He", "got", "a", "promotion", "at", "work", "."],
        extraUaTokens: ["зарплата", "кар’єру", "договір"],
        extraRuTokens: ["зарплата", "карьеру", "договор"],
        extraEnTokens: ["salary", "career", "contract"],
    },

    [phraseKey("wypowiedzenie", "a1-17")]: {
        sk: "Złożył wypowiedzenie.",
        ua: "Він подав заяву на звільнення.",
        ru: "Он подал заявление об увольнении.",
        en: "He handed in his resignation notice.",
        uaTokens: ["Він", "подав", "заяву", "на", "звільнення", "."],
        ruTokens: ["Он", "подал", "заявление", "об", "увольнении", "."],
        enTokens: ["He", "handed", "in", "his", "resignation", "notice", "."],
        extraUaTokens: ["роботодавець", "підвищення", "обов’язок"],
        extraRuTokens: ["работодатель", "повышение", "обязанность"],
        extraEnTokens: ["employer", "promotion", "duty"],
    },

    [phraseKey("obowiązek", "a1-17")]: {
        sk: "To jest mój obowiązek.",
        ua: "Це мій обов’язок.",
        ru: "Это моя обязанность.",
        en: "This is my duty.",
        uaTokens: ["Це", "мій", "обов’язок", "."],
        ruTokens: ["Это", "моя", "обязанность", "."],
        enTokens: ["This", "is", "my", "duty", "."],
        extraUaTokens: ["зарплата", "договір", "право"],
        extraRuTokens: ["зарплата", "договор", "право"],
        extraEnTokens: ["salary", "contract", "right"],
    },

    [phraseKey("prawo", "a1-17")]: {
        sk: "Masz do tego prawo.",
        ua: "Ти маєш на це право.",
        ru: "Ты имеешь на это право.",
        en: "You have the right to do that.",
        uaTokens: ["Ти", "маєш", "на", "це", "право", "."],
        ruTokens: ["Ты", "имеешь", "на", "это", "право", "."],
        enTokens: ["You", "have", "the", "right", "to", "do", "that", "."],
        extraUaTokens: ["обов’язок", "роботодавець", "договір"],
        extraRuTokens: ["обязанность", "работодатель", "договор"],
        extraEnTokens: ["duty", "employer", "contract"],
    },

    // =========================
    // LESSON 18 — Спілкування
    // =========================
    [phraseKey("rozumieć", "a1-18")]: {
        sk: "Nie rozumiem tego zdania.",
        ua: "Я не розумію цього речення.",
        ru: "Я не понимаю этого предложения.",
        en: "I do not understand this sentence.",
        uaTokens: ["Я", "не", "розумію", "цього", "речення", "."],
        ruTokens: ["Я", "не", "понимаю", "этого", "предложения", "."],
        enTokens: ["I", "do", "not", "understand", "this", "sentence", "."],
        extraUaTokens: ["пояснити", "думка", "зв’язку"],
        extraRuTokens: ["объяснить", "мнение", "связи"],
        extraEnTokens: ["explain", "opinion", "contact"],
    },

    [phraseKey("wyjaśnić", "a1-18")]: {
        sk: "Możesz mi to wyjaśnić?",
        ua: "Можеш мені це пояснити?",
        ru: "Можешь мне это объяснить?",
        en: "Can you explain it to me?",
        uaTokens: ["Можеш", "мені", "це", "пояснити", "?"],
        ruTokens: ["Можешь", "мне", "это", "объяснить", "?"],
        enTokens: ["Can", "you", "explain", "it", "to", "me", "?"],
        uaAltAnswers: [["Можеш", "це", "мені", "пояснити", "?"]],
        ruAltAnswers: [["Можешь", "это", "мне", "объяснить", "?"]],
        extraUaTokens: ["речення", "думка", "розмова"],
        extraRuTokens: ["предложение", "мнение", "разговор"],
        extraEnTokens: ["sentence", "opinion", "conversation"],
    },

    [phraseKey("zapytać", "a1-34")]: {
        sk: "Chcę cię o coś zapytać.",
        ua: "Я хочу дещо тебе запитати.",
        ru: "Я хочу тебя кое о чём спросить.",
        en: "I want to ask you something.",
        uaTokens: ["Я", "хочу", "дещо", "тебе", "запитати", "."],
        ruTokens: ["Я", "хочу", "тебя", "кое", "о", "чём", "спросить", "."],
        enTokens: ["I", "want", "to", "ask", "you", "something", "."],
        uaAltAnswers: [["Я", "хочу", "тебе", "дещо", "запитати", "."]],
        extraUaTokens: ["допомогу", "родину", "рішення"],
        extraRuTokens: ["помощи", "семью", "решение"],
        extraEnTokens: ["help", "family", "solution"],
    },

    [phraseKey("odpowiedź", "a1-18")]: {
        sk: "Nie znam odpowiedzi.",
        ua: "Я не знаю відповіді.",
        ru: "Я не знаю ответа.",
        en: "I do not know the answer.",
        uaTokens: ["Я", "не", "знаю", "відповіді", "."],
        ruTokens: ["Я", "не", "знаю", "ответа", "."],
        enTokens: ["I", "do", "not", "know", "the", "answer", "."],
        extraUaTokens: ["речення", "розмова", "думка"],
        extraRuTokens: ["предложение", "разговор", "мнение"],
        extraEnTokens: ["sentence", "conversation", "opinion"],
    },

    [phraseKey("opinia", "a1-18")]: {
        sk: "To jest moja opinia.",
        ua: "Це моя думка.",
        ru: "Это моё мнение.",
        en: "This is my opinion.",
        uaTokens: ["Це", "моя", "думка", "."],
        ruTokens: ["Это", "моё", "мнение", "."],
        enTokens: ["This", "is", "my", "opinion", "."],
        extraUaTokens: ["відповіді", "розмова", "зв’язку"],
        extraRuTokens: ["ответа", "разговор", "связи"],
        extraEnTokens: ["answer", "conversation", "contact"],
    },

    [phraseKey("zgadzać się", "a1-18")]: {
        sk: "Zgadzam się z tobą.",
        ua: "Я з тобою погоджуюся.",
        ru: "Я с тобой согласен.",
        en: "I agree with you.",
        uaTokens: ["Я", "з", "тобою", "погоджуюся", "."],
        ruTokens: ["Я", "с", "тобой", "согласен", "."],
        enTokens: ["I", "agree", "with", "you", "."],
        extraUaTokens: ["думка", "розмова", "цим"],
        extraRuTokens: ["мнение", "разговор", "этим"],
        extraEnTokens: ["opinion", "conversation", "that"],
    },

    [phraseKey("nie zgadzać się", "a1-18")]: {
        sk: "Nie zgadzam się z tym.",
        ua: "Я з цим не погоджуюся.",
        ru: "Я с этим не согласен.",
        en: "I do not agree with that.",
        uaTokens: ["Я", "з", "цим", "не", "погоджуюся", "."],
        ruTokens: ["Я", "с", "этим", "не", "согласен", "."],
        enTokens: ["I", "do", "not", "agree", "with", "that", "."],
        uaAltAnswers: [["Я", "не", "погоджуюся", "з", "цим", "."]],
        ruAltAnswers: [["Я", "не", "согласен", "с", "этим", "."]],
        extraUaTokens: ["думка", "тобою", "розмова"],
        extraRuTokens: ["мнение", "тобой", "разговор"],
        extraEnTokens: ["opinion", "you", "conversation"],
    },

    [phraseKey("dyskutować", "a1-18")]: {
        sk: "Lubimy dyskutować o filmach.",
        ua: "Ми любимо обговорювати фільми.",
        ru: "Мы любим обсуждать фильмы.",
        en: "We like discussing films.",
        uaTokens: ["Ми", "любимо", "обговорювати", "фільми", "."],
        ruTokens: ["Мы", "любим", "обсуждать", "фильмы", "."],
        enTokens: ["We", "like", "discussing", "films", "."],
        extraUaTokens: ["думка", "відповіді", "зв’язку"],
        extraRuTokens: ["мнение", "ответа", "связи"],
        extraEnTokens: ["opinion", "answer", "contact"],
    },

    [phraseKey("rozmowa", "a1-18")]: {
        sk: "To była ciekawa rozmowa.",
        ua: "Це була цікава розмова.",
        ru: "Это был интересный разговор.",
        en: "It was an interesting conversation.",
        uaTokens: ["Це", "була", "цікава", "розмова", "."],
        ruTokens: ["Это", "был", "интересный", "разговор", "."],
        enTokens: ["It", "was", "an", "interesting", "conversation", "."],
        extraUaTokens: ["думка", "відповіді", "контакті"],
        extraRuTokens: ["мнение", "ответа", "контакте"],
        extraEnTokens: ["opinion", "answer", "contact"],
    },

    [phraseKey("kontakt", "a1-18")]: {
        sk: "Zostańmy w kontakcie.",
        ua: "Залишаймося на зв’язку.",
        ru: "Давай останемся на связи.",
        en: "Let's stay in touch.",
        uaTokens: ["Залишаймося", "на", "зв’язку", "."],
        ruTokens: ["Давай", "останемся", "на", "связи", "."],
        enTokens: ["Let's", "stay", "in", "touch", "."],
        extraUaTokens: ["думка", "розмова", "пояснити"],
        extraRuTokens: ["мнение", "разговор", "объяснить"],
        extraEnTokens: ["opinion", "conversation", "explain"],
    },

    // =========================
    // LESSON 19 — Технології
    // =========================
    [phraseKey("telefon komórkowy", "a1-19")]: {
        sk: "Mam nowy telefon komórkowy.",
        ua: "У мене новий мобільний телефон.",
        ru: "У меня новый мобильный телефон.",
        en: "I have a new mobile phone.",
        uaTokens: ["У", "мене", "новий", "мобільний", "телефон", "."],
        ruTokens: ["У", "меня", "новый", "мобильный", "телефон", "."],
        enTokens: ["I", "have", "a", "new", "mobile", "phone", "."],
        extraUaTokens: ["зарядка", "пароль", "додаток"],
        extraRuTokens: ["зарядка", "пароль", "приложение"],
        extraEnTokens: ["charger", "password", "app"],
    },

    [phraseKey("ładowarka", "a1-19")]: {
        sk: "Gdzie jest moja ładowarka?",
        ua: "Де моя зарядка?",
        ru: "Где моя зарядка?",
        en: "Where is my charger?",
        uaTokens: ["Де", "моя", "зарядка", "?"],
        ruTokens: ["Где", "моя", "зарядка", "?"],
        enTokens: ["Where", "is", "my", "charger", "?"],
        extraUaTokens: ["телефон", "пароль", "профіль"],
        extraRuTokens: ["телефон", "пароль", "профиль"],
        extraEnTokens: ["phone", "password", "profile"],
    },

    [phraseKey("wiadomość", "a1-19")]: {
        sk: "Wysłałem ci wiadomość.",
        ua: "Я надіслав тобі повідомлення.",
        ru: "Я отправил тебе сообщение.",
        en: "I sent you a message.",
        uaTokens: ["Я", "надіслав", "тобі", "повідомлення", "."],
        ruTokens: ["Я", "отправил", "тебе", "сообщение", "."],
        enTokens: ["I", "sent", "you", "a", "message", "."],
        extraUaTokens: ["зарядка", "пароль", "інтернет"],
        extraRuTokens: ["зарядка", "пароль", "интернет"],
        extraEnTokens: ["charger", "password", "internet"],
    },

    [phraseKey("rozmowa", "a1-19")]: {
        sk: "Mam ważną rozmowę telefoniczną.",
        ua: "У мене важливий телефонний дзвінок.",
        ru: "У меня важный телефонный звонок.",
        en: "I have an important phone call.",
        uaTokens: ["У", "мене", "важливий", "телефонний", "дзвінок", "."],
        ruTokens: ["У", "меня", "важный", "телефонный", "звонок", "."],
        enTokens: ["I", "have", "an", "important", "phone", "call", "."],
        extraUaTokens: ["повідомлення", "зарядка", "профіль"],
        extraRuTokens: ["сообщение", "зарядка", "профиль"],
        extraEnTokens: ["message", "charger", "profile"],
    },

    [phraseKey("internet", "a1-19")]: {
        sk: "Internet działa bardzo wolno.",
        ua: "Інтернет працює дуже повільно.",
        ru: "Интернет работает очень медленно.",
        en: "The internet works very slowly.",
        uaTokens: ["Інтернет", "працює", "дуже", "повільно", "."],
        ruTokens: ["Интернет", "работает", "очень", "медленно", "."],
        enTokens: ["The", "internet", "works", "very", "slowly", "."],
        extraUaTokens: ["зарядка", "пароль", "додаток"],
        extraRuTokens: ["зарядка", "пароль", "приложение"],
        extraEnTokens: ["charger", "password", "app"],
    },

    [phraseKey("wifi", "a1-19")]: {
        sk: "Jakie jest hasło do wifi?",
        ua: "Який пароль до вайфаю?",
        ru: "Какой пароль от вайфая?",
        en: "What is the Wi-Fi password?",
        uaTokens: ["Який", "пароль", "до", "вайфаю", "?"],
        ruTokens: ["Какой", "пароль", "от", "вайфая", "?"],
        enTokens: ["What", "is", "the", "Wi-Fi", "password", "?"],
        extraUaTokens: ["зарядка", "телефон", "профіль"],
        extraRuTokens: ["зарядка", "телефон", "профиль"],
        extraEnTokens: ["charger", "phone", "profile"],
    },

    [phraseKey("media społecznościowe", "a1-19")]: {
        sk: "Spędzam dużo czasu w mediach społecznościowych.",
        ua: "Я проводжу багато часу в соціальних мережах.",
        ru: "Я провожу много времени в социальных сетях.",
        en: "I spend a lot of time on social networks.",
        uaTokens: ["Я", "проводжу", "багато", "часу", "в", "соціальних", "мережах", "."],
        ruTokens: ["Я", "провожу", "много", "времени", "в", "социальных", "сетях", "."],
        enTokens: ["I", "spend", "a", "lot", "of", "time", "on", "social", "networks", "."],
        extraUaTokens: ["пароль", "профіль", "додаток"],
        extraRuTokens: ["пароль", "профиль", "приложение"],
        extraEnTokens: ["password", "profile", "app"],
    },

    [phraseKey("profil", "a1-19")]: {
        sk: "Mam nowy profil.",
        ua: "У мене новий профіль.",
        ru: "У меня новый профиль.",
        en: "I have a new profile.",
        uaTokens: ["У", "мене", "новий", "профіль", "."],
        ruTokens: ["У", "меня", "новый", "профиль", "."],
        enTokens: ["I", "have", "a", "new", "profile", "."],
        extraUaTokens: ["пароль", "телефон", "повідомлення"],
        extraRuTokens: ["пароль", "телефон", "сообщение"],
        extraEnTokens: ["password", "phone", "message"],
    },

    [phraseKey("hasło", "a1-19")]: {
        sk: "Zapomniałem hasła.",
        ua: "Я забув пароль.",
        ru: "Я забыл пароль.",
        en: "I forgot the password.",
        uaTokens: ["Я", "забув", "пароль", "."],
        ruTokens: ["Я", "забыл", "пароль", "."],
        enTokens: ["I", "forgot", "the", "password", "."],
        extraUaTokens: ["зарядка", "профіль", "повідомлення"],
        extraRuTokens: ["зарядка", "профиль", "сообщение"],
        extraEnTokens: ["charger", "profile", "message"],
    },

    [phraseKey("pobrać", "a1-19")]: {
        sk: "Chcę pobrać tę aplikację.",
        ua: "Я хочу завантажити цей додаток.",
        ru: "Я хочу скачать это приложение.",
        en: "I want to download this app.",
        uaTokens: ["Я", "хочу", "завантажити", "цей", "додаток", "."],
        ruTokens: ["Я", "хочу", "скачать", "это", "приложение", "."],
        enTokens: ["I", "want", "to", "download", "this", "app", "."],
        uaAltAnswers: [["Я", "хочу", "цей", "додаток", "завантажити", "."]],
        ruAltAnswers: [["Я", "хочу", "это", "приложение", "скачать", "."]],
        extraUaTokens: ["пароль", "профіль", "телефон"],
        extraRuTokens: ["пароль", "профиль", "телефон"],
        extraEnTokens: ["password", "profile", "phone"],
    },

    // =========================
    // LESSON 20 — Повсякденні дії
    // =========================
    [phraseKey("wstać", "a1-20")]: {
        sk: "Muszę wcześnie wstać.",
        ua: "Мені треба рано встати.",
        ru: "Мне нужно рано встать.",
        en: "I need to get up early.",
        uaTokens: ["Мені", "треба", "рано", "встати", "."],
        ruTokens: ["Мне", "нужно", "рано", "встать", "."],
        enTokens: ["I", "need", "to", "get", "up", "early", "."],
        extraUaTokens: ["роботу", "увечері", "мамі"],
        extraRuTokens: ["работу", "вечером", "маме"],
        extraEnTokens: ["work", "evening", "mom"],
    },

    [phraseKey("iść do pracy", "a1-20")]: {
        sk: "Codziennie idę do pracy o siódmej.",
        ua: "Щодня я йду на роботу о сьомій.",
        ru: "Каждый день я иду на работу в семь.",
        en: "Every day I go to work at seven.",
        uaTokens: ["Щодня", "я", "йду", "на", "роботу", "о", "сьомій", "."],
        ruTokens: ["Каждый", "день", "я", "иду", "на", "работу", "в", "семь", "."],
        enTokens: ["Every", "day", "I", "go", "to", "work", "at", "seven", "."],
        extraUaTokens: ["увечері", "покупки", "мамі"],
        extraRuTokens: ["вечером", "покупки", "маме"],
        extraEnTokens: ["evening", "shopping", "mom"],
    },

    [phraseKey("robić zakupy", "a1-20")]: {
        sk: "Wieczorem robię zakupy.",
        ua: "Увечері я роблю покупки.",
        ru: "Вечером я делаю покупки.",
        en: "I go shopping in the evening.",
        uaTokens: ["Увечері", "я", "роблю", "покупки", "."],
        ruTokens: ["Вечером", "я", "делаю", "покупки", "."],
        enTokens: ["I", "go", "shopping", "in", "the", "evening", "."],
        extraUaTokens: ["роботу", "мамі", "серіали"],
        extraRuTokens: ["работу", "маме", "сериалы"],
        extraEnTokens: ["work", "mom", "series"],
    },

    [phraseKey("odpocząć", "a1-20")]: {
        sk: "Po pracy chcę odpocząć.",
        ua: "Після роботи я хочу відпочити.",
        ru: "После работы я хочу отдохнуть.",
        en: "After work I want to rest.",
        uaTokens: ["Після", "роботи", "я", "хочу", "відпочити", "."],
        ruTokens: ["После", "работы", "я", "хочу", "отдохнуть", "."],
        enTokens: ["After", "work", "I", "want", "to", "rest", "."],
        extraUaTokens: ["покупки", "мамі", "серіали"],
        extraRuTokens: ["покупки", "маме", "сериалы"],
        extraEnTokens: ["shopping", "mom", "series"],
    },

    [phraseKey("spotkać się", "a1-20")]: {
        sk: "Chcę się spotkać z przyjacielem.",
        ua: "Я хочу зустрітися з другом.",
        ru: "Я хочу встретиться с другом.",
        en: "I want to meet my friend.",
        uaTokens: ["Я", "хочу", "зустрітися", "з", "другом", "."],
        ruTokens: ["Я", "хочу", "встретиться", "с", "другом", "."],
        enTokens: ["I", "want", "to", "meet", "my", "friend", "."],
        extraUaTokens: ["роботу", "мамі", "відпочити"],
        extraRuTokens: ["работу", "маме", "отдохнуть"],
        extraEnTokens: ["work", "mom", "rest"],
    },

    [phraseKey("telefonować", "a1-20")]: {
        sk: "Muszę telefonować do mamy.",
        ua: "Мені треба подзвонити мамі.",
        ru: "Мне нужно позвонить маме.",
        en: "I need to call my mom.",
        uaTokens: ["Мені", "треба", "подзвонити", "мамі", "."],
        ruTokens: ["Мне", "нужно", "позвонить", "маме", "."],
        enTokens: ["I", "need", "to", "call", "my", "mom", "."],
        extraUaTokens: ["роботу", "покупки", "серіали"],
        extraRuTokens: ["работу", "покупки", "сериалы"],
        extraEnTokens: ["work", "shopping", "series"],
    },

    [phraseKey("gotować", "a1-20")]: {
        sk: "Wieczorem lubię gotować.",
        ua: "Увечері я люблю готувати.",
        ru: "Вечером я люблю готовить.",
        en: "I like cooking in the evening.",
        uaTokens: ["Увечері", "я", "люблю", "готувати", "."],
        ruTokens: ["Вечером", "я", "люблю", "готовить", "."],
        enTokens: ["I", "like", "cooking", "in", "the", "evening", "."],
        extraUaTokens: ["роботу", "мамі", "серіали"],
        extraRuTokens: ["работу", "маме", "сериалы"],
        extraEnTokens: ["work", "mom", "series"],
    },

    [phraseKey("oglądać", "a1-20")]: {
        sk: "Lubię oglądać seriale.",
        ua: "Я люблю дивитися серіали.",
        ru: "Я люблю смотреть сериалы.",
        en: "I like watching TV series.",
        uaTokens: ["Я", "люблю", "дивитися", "серіали", "."],
        ruTokens: ["Я", "люблю", "смотреть", "сериалы", "."],
        enTokens: ["I", "like", "watching", "TV", "series", "."],
        extraUaTokens: ["роботу", "покупки", "мамі"],
        extraRuTokens: ["работу", "покупки", "маме"],
        extraEnTokens: ["work", "shopping", "mom"],
    },

    [phraseKey("czytać", "a1-20")]: {
        sk: "Przed snem lubię czytać.",
        ua: "Перед сном я люблю читати.",
        ru: "Перед сном я люблю читать.",
        en: "I like reading before sleep.",
        uaTokens: ["Перед", "сном", "я", "люблю", "читати", "."],
        ruTokens: ["Перед", "сном", "я", "люблю", "читать", "."],
        enTokens: ["I", "like", "reading", "before", "sleep", "."],
        extraUaTokens: ["роботу", "мамі", "серіали"],
        extraRuTokens: ["работу", "маме", "сериалы"],
        extraEnTokens: ["work", "mom", "series"],
    },

    [phraseKey("spać", "a1-20")]: {
        sk: "Idę spać o jedenastej.",
        ua: "Я йду спати об одинадцятій.",
        ru: "Я ложусь спать в одиннадцать.",
        en: "I go to sleep at eleven.",
        uaTokens: ["Я", "йду", "спати", "об", "одинадцятій", "."],
        ruTokens: ["Я", "ложусь", "спать", "в", "одиннадцать", "."],
        enTokens: ["I", "go", "to", "sleep", "at", "eleven", "."],
        extraUaTokens: ["роботу", "увечері", "читати"],
        extraRuTokens: ["работу", "вечером", "читать"],
        extraEnTokens: ["work", "evening", "read"],
    },
};