import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A1_BUILD_UA_SENTENCES_5: BuildUaSentenceDict = {
  // =========================
  // LESSON 21 — Проблеми і ситуації
  // =========================
  [phraseKey("problem", "a1-21")]: {
    sk: "Mam mały problem.",
    ua: "У мене маленька проблема.",
    ru: "У меня маленькая проблема.",
    en: "I have a small problem.",
    uaTokens: ["У", "мене", "маленька", "проблема", "."],
    ruTokens: ["У", "меня", "маленькая", "проблема", "."],
    enTokens: ["I", "have", "a", "small", "problem", "."],
    extraUaTokens: ["телефон", "документи", "рішення"],
    extraRuTokens: ["телефон", "документы", "решение"],
    extraEnTokens: ["phone", "documents", "solution"],
  },

  [phraseKey("zepsuty", "a1-21")]: {
    sk: "Mój telefon jest zepsuty.",
    ua: "Мій телефон зламаний.",
    ru: "Мой телефон сломан.",
    en: "My phone is broken.",
    uaTokens: ["Мій", "телефон", "зламаний", "."],
    ruTokens: ["Мой", "телефон", "сломан", "."],
    enTokens: ["My", "phone", "is", "broken", "."],
    extraUaTokens: ["проблема", "ключі", "помилка"],
    extraRuTokens: ["проблема", "ключи", "ошибка"],
    extraEnTokens: ["problem", "keys", "mistake"],
  },

  [phraseKey("stracić", "a1-21")]: {
    sk: "Nie chcę stracić dokumentów.",
    ua: "Я не хочу загубити документи.",
    ru: "Я не хочу потерять документы.",
    en: "I do not want to lose the documents.",
    uaTokens: ["Я", "не", "хочу", "загубити", "документи", "."],
    ruTokens: ["Я", "не", "хочу", "потерять", "документы", "."],
    enTokens: ["I", "do", "not", "want", "to", "lose", "the", "documents", "."],
    extraUaTokens: ["телефон", "знайти", "зустріч"],
    extraRuTokens: ["телефон", "найти", "встреча"],
    extraEnTokens: ["phone", "find", "meeting"],
  },

  [phraseKey("znaleźć", "a1-21")]: {
    sk: "Muszę znaleźć klucze.",
    ua: "Мені треба знайти ключі.",
    ru: "Мне нужно найти ключи.",
    en: "I need to find the keys.",
    uaTokens: ["Мені", "треба", "знайти", "ключі", "."],
    ruTokens: ["Мне", "нужно", "найти", "ключи", "."],
    enTokens: ["I", "need", "to", "find", "the", "keys", "."],
    extraUaTokens: ["документи", "телефон", "рішення"],
    extraRuTokens: ["документы", "телефон", "решение"],
    extraEnTokens: ["documents", "phone", "solution"],
  },

  [phraseKey("spóźniać się", "a1-21")]: {
    sk: "Nie lubię się spóźniać.",
    ua: "Я не люблю запізнюватися.",
    ru: "Я не люблю опаздывать.",
    en: "I do not like being late.",
    uaTokens: ["Я", "не", "люблю", "запізнюватися", "."],
    ruTokens: ["Я", "не", "люблю", "опаздывать", "."],
    enTokens: ["I", "do", "not", "like", "being", "late", "."],
    extraUaTokens: ["зустріч", "документи", "знайти"],
    extraRuTokens: ["встреча", "документы", "найти"],
    extraEnTokens: ["meeting", "documents", "find"],
  },

  [phraseKey("zapomnieć", "a1-21")]: {
    sk: "Nie mogę zapomnieć o spotkaniu.",
    ua: "Я не можу забути про зустріч.",
    ru: "Я не могу забыть о встрече.",
    en: "I cannot forget about the meeting.",
    uaTokens: ["Я", "не", "можу", "забути", "про", "зустріч", "."],
    ruTokens: ["Я", "не", "могу", "забыть", "о", "встрече", "."],
    enTokens: ["I", "cannot", "forget", "about", "the", "meeting", "."],
    extraUaTokens: ["документи", "ключі", "проблема"],
    extraRuTokens: ["документы", "ключи", "проблема"],
    extraEnTokens: ["documents", "keys", "problem"],
  },

  [phraseKey("błąd", "a1-21")]: {
    sk: "To był mój błąd.",
    ua: "Це була моя помилка.",
    ru: "Это была моя ошибка.",
    en: "It was my mistake.",
    uaTokens: ["Це", "була", "моя", "помилка", "."],
    ruTokens: ["Это", "была", "моя", "ошибка", "."],
    enTokens: ["It", "was", "my", "mistake", "."],
    extraUaTokens: ["рішення", "ремонт", "допомогу"],
    extraRuTokens: ["решение", "ремонт", "помощь"],
    extraEnTokens: ["solution", "repair", "help"],
  },

  [phraseKey("naprawa", "a1-21")]: {
    sk: "Naprawa zajmie dużo czasu.",
    ua: "Ремонт займе багато часу.",
    ru: "Ремонт займет много времени.",
    en: "The repair will take a lot of time.",
    uaTokens: ["Ремонт", "займе", "багато", "часу", "."],
    ruTokens: ["Ремонт", "займет", "много", "времени", "."],
    enTokens: ["The", "repair", "will", "take", "a", "lot", "of", "time", "."],
    extraUaTokens: ["проблема", "помилка", "допомогу"],
    extraRuTokens: ["проблема", "ошибка", "помощь"],
    extraEnTokens: ["problem", "mistake", "help"],
  },

  [phraseKey("pomoc", "a1-21")]: {
    sk: "Dziękuję za pomoc.",
    ua: "Дякую за допомогу.",
    ru: "Спасибо за помощь.",
    en: "Thank you for the help.",
    uaTokens: ["Дякую", "за", "допомогу", "."],
    ruTokens: ["Спасибо", "за", "помощь", "."],
    enTokens: ["Thank", "you", "for", "the", "help", "."],
    extraUaTokens: ["рішення", "ремонт", "часу"],
    extraRuTokens: ["решение", "ремонт", "времени"],
    extraEnTokens: ["solution", "repair", "time"],
  },

  [phraseKey("rozwiązanie", "a1-21")]: {
    sk: "Szukamy dobrego rozwiązania.",
    ua: "Ми шукаємо хороше рішення.",
    ru: "Мы ищем хорошее решение.",
    en: "We are looking for a good solution.",
    uaTokens: ["Ми", "шукаємо", "хороше", "рішення", "."],
    ruTokens: ["Мы", "ищем", "хорошее", "решение", "."],
    enTokens: ["We", "are", "looking", "for", "a", "good", "solution", "."],
    extraUaTokens: ["проблема", "помилка", "допомогу"],
    extraRuTokens: ["проблема", "ошибка", "помощь"],
    extraEnTokens: ["problem", "mistake", "help"],
  },

  // =========================
  // LESSON 22 — Напрямки
  // =========================
  [phraseKey("w prawo", "a1-22")]: {
    sk: "Skręć w prawo.",
    ua: "Поверни праворуч.",
    ru: "Поверни направо.",
    en: "Turn right.",
    uaTokens: ["Поверни", "праворуч", "."],
    ruTokens: ["Поверни", "направо", "."],
    enTokens: ["Turn", "right", "."],
    extraUaTokens: ["ліворуч", "прямо", "вокзал"],
    extraRuTokens: ["налево", "прямо", "вокзал"],
    extraEnTokens: ["left", "straight", "station"],
  },

  [phraseKey("w lewo", "a1-22")]: {
    sk: "Potem idź w lewo.",
    ua: "Потім іди ліворуч.",
    ru: "Потом иди налево.",
    en: "Then go left.",
    uaTokens: ["Потім", "іди", "ліворуч", "."],
    ruTokens: ["Потом", "иди", "налево", "."],
    enTokens: ["Then", "go", "left", "."],
    extraUaTokens: ["праворуч", "прямо", "магазин"],
    extraRuTokens: ["направо", "прямо", "магазин"],
    extraEnTokens: ["right", "straight", "shop"],
  },

  [phraseKey("prosto", "a1-22")]: {
    sk: "Idź prosto przez pięć minut.",
    ua: "Іди прямо п’ять хвилин.",
    ru: "Иди прямо пять минут.",
    en: "Go straight for five minutes.",
    uaTokens: ["Іди", "прямо", "п’ять", "хвилин", "."],
    ruTokens: ["Иди", "прямо", "пять", "минут", "."],
    enTokens: ["Go", "straight", "for", "five", "minutes", "."],
    extraUaTokens: ["праворуч", "ліворуч", "вокзал"],
    extraRuTokens: ["направо", "налево", "вокзал"],
    extraEnTokens: ["right", "left", "station"],
  },

  [phraseKey("blisko", "a1-22")]: {
    sk: "Sklep jest bardzo blisko.",
    ua: "Магазин дуже близько.",
    ru: "Магазин очень близко.",
    en: "The shop is very near.",
    uaTokens: ["Магазин", "дуже", "близько", "."],
    ruTokens: ["Магазин", "очень", "близко", "."],
    enTokens: ["The", "shop", "is", "very", "near", "."],
    extraUaTokens: ["вокзал", "праворуч", "школою"],
    extraRuTokens: ["вокзал", "направо", "школой"],
    extraEnTokens: ["station", "right", "school"],
  },

  [phraseKey("daleko", "a1-22")]: {
    sk: "Dworzec jest daleko.",
    ua: "Вокзал далеко.",
    ru: "Вокзал далеко.",
    en: "The station is far away.",
    uaTokens: ["Вокзал", "далеко", "."],
    ruTokens: ["Вокзал", "далеко", "."],
    enTokens: ["The", "station", "is", "far", "away", "."],
    extraUaTokens: ["магазин", "близько", "праворуч"],
    extraRuTokens: ["магазин", "близко", "направо"],
    extraEnTokens: ["shop", "near", "right"],
  },

  [phraseKey("na górze", "a1-22")]: {
    sk: "To jest na górze.",
    ua: "Це вгорі.",
    ru: "Это наверху.",
    en: "It is upstairs.",
    uaTokens: ["Це", "вгорі", "."],
    ruTokens: ["Это", "наверху", "."],
    enTokens: ["It", "is", "upstairs", "."],
    extraUaTokens: ["внизу", "рецепція", "магазин"],
    extraRuTokens: ["внизу", "ресепшн", "магазин"],
    extraEnTokens: ["downstairs", "reception", "shop"],
  },

  [phraseKey("na dole", "a1-22")]: {
    sk: "Recepcja jest na dole.",
    ua: "Ресепшн внизу.",
    ru: "Ресепшн внизу.",
    en: "The reception is downstairs.",
    uaTokens: ["Ресепшн", "внизу", "."],
    ruTokens: ["Ресепшн", "внизу", "."],
    enTokens: ["The", "reception", "is", "downstairs", "."],
    extraUaTokens: ["вгорі", "магазин", "банк"],
    extraRuTokens: ["наверху", "магазин", "банк"],
    extraEnTokens: ["upstairs", "shop", "bank"],
  },

  [phraseKey("przed", "a1-22")]: {
    sk: "Samochód stoi przed domem.",
    ua: "Машина стоїть перед будинком.",
    ru: "Машина стоит перед домом.",
    en: "The car is in front of the house.",
    uaTokens: ["Машина", "стоїть", "перед", "будинком", "."],
    ruTokens: ["Машина", "стоит", "перед", "домом", "."],
    enTokens: ["The", "car", "is", "in", "front", "of", "the", "house", "."],
    extraUaTokens: ["парк", "школою", "вокзал"],
    extraRuTokens: ["парк", "школой", "вокзал"],
    extraEnTokens: ["park", "school", "station"],
  },

  [phraseKey("za", "a1-22")]: {
    sk: "Park jest za szkołą.",
    ua: "Парк за школою.",
    ru: "Парк за школой.",
    en: "The park is behind the school.",
    uaTokens: ["Парк", "за", "школою", "."],
    ruTokens: ["Парк", "за", "школой", "."],
    enTokens: ["The", "park", "is", "behind", "the", "school", "."],
    extraUaTokens: ["магазин", "будинком", "між"],
    extraRuTokens: ["магазин", "домом", "между"],
    extraEnTokens: ["shop", "house", "between"],
  },

  [phraseKey("między", "a1-22")]: {
    sk: "Bank jest między sklepem a kawiarnią.",
    ua: "Банк між магазином і кафе.",
    ru: "Банк между магазином и кафе.",
    en: "The bank is between the shop and the café.",
    uaTokens: ["Банк", "між", "магазином", "і", "кафе", "."],
    ruTokens: ["Банк", "между", "магазином", "и", "кафе", "."],
    enTokens: ["The", "bank", "is", "between", "the", "shop", "and", "the", "café", "."],
    extraUaTokens: ["парк", "школою", "внизу"],
    extraRuTokens: ["парк", "школой", "внизу"],
    extraEnTokens: ["park", "school", "downstairs"],
  },

  // =========================
  // LESSON 23 — Характер
  // =========================
  [phraseKey("dobry", "a1-23")]: {
    sk: "On jest dobrym człowiekiem.",
    ua: "Він добра людина.",
    ru: "Он хороший человек.",
    en: "He is a good person.",
    uaTokens: ["Він", "добра", "людина", "."],
    ruTokens: ["Он", "хороший", "человек", "."],
    enTokens: ["He", "is", "a", "good", "person", "."],
    extraUaTokens: ["терплячий", "серйозний", "колега"],
    extraRuTokens: ["терпеливый", "серьёзный", "коллега"],
    extraEnTokens: ["patient", "serious", "colleague"],
  },

  [phraseKey("zły", "a1-23")]: {
    sk: "Dziś mam zły humor.",
    ua: "Сьогодні в мене поганий настрій.",
    ru: "Сегодня у меня плохое настроение.",
    en: "I am in a bad mood today.",
    uaTokens: ["Сьогодні", "в", "мене", "поганий", "настрій", "."],
    ruTokens: ["Сегодня", "у", "меня", "плохое", "настроение", "."],
    enTokens: ["I", "am", "in", "a", "bad", "mood", "today", "."],
    extraUaTokens: ["дуже", "вчитель", "щирих"],
    extraRuTokens: ["очень", "учитель", "искренних"],
    extraEnTokens: ["very", "teacher", "honest"],
  },

  [phraseKey("cierpliwy", "a1-23")]: {
    sk: "Nauczyciel jest bardzo cierpliwy.",
    ua: "Вчитель дуже терплячий.",
    ru: "Учитель очень терпеливый.",
    en: "The teacher is very patient.",
    uaTokens: ["Вчитель", "дуже", "терплячий", "."],
    ruTokens: ["Учитель", "очень", "терпеливый", "."],
    enTokens: ["The", "teacher", "is", "very", "patient", "."],
    extraUaTokens: ["серйозний", "дружній", "людей"],
    extraRuTokens: ["серьёзный", "дружелюбный", "людей"],
    extraEnTokens: ["serious", "friendly", "people"],
  },

  [phraseKey("leniwy", "a1-23")]: {
    sk: "Nie chcę być leniwy.",
    ua: "Я не хочу бути ледачим.",
    ru: "Я не хочу быть ленивым.",
    en: "I do not want to be lazy.",
    uaTokens: ["Я", "не", "хочу", "бути", "ледачим", "."],
    ruTokens: ["Я", "не", "хочу", "быть", "ленивым", "."],
    enTokens: ["I", "do", "not", "want", "to", "be", "lazy", "."],
    extraUaTokens: ["працьовита", "щирих", "веселий"],
    extraRuTokens: ["трудолюбивая", "искренних", "забавный"],
    extraEnTokens: ["hard-working", "honest", "funny"],
  },

  [phraseKey("pracowity", "a1-23")]: {
    sk: "Ona jest bardzo pracowita.",
    ua: "Вона дуже працьовита.",
    ru: "Она очень трудолюбивая.",
    en: "She is very hard-working.",
    uaTokens: ["Вона", "дуже", "працьовита", "."],
    ruTokens: ["Она", "очень", "трудолюбивая", "."],
    enTokens: ["She", "is", "very", "hard-working", "."],
    extraUaTokens: ["ледачим", "серйозний", "людина"],
    extraRuTokens: ["ленивым", "серьёзный", "человек"],
    extraEnTokens: ["lazy", "serious", "person"],
  },

  [phraseKey("szczery", "a1-23")]: {
    sk: "Lubię szczerych ludzi.",
    ua: "Я люблю щирих людей.",
    ru: "Я люблю искренних людей.",
    en: "I like honest people.",
    uaTokens: ["Я", "люблю", "щирих", "людей", "."],
    ruTokens: ["Я", "люблю", "искренних", "людей", "."],
    enTokens: ["I", "like", "honest", "people", "."],
    extraUaTokens: ["дружній", "серйозний", "вчитель"],
    extraRuTokens: ["дружелюбный", "серьёзный", "учитель"],
    extraEnTokens: ["friendly", "serious", "teacher"],
  },

  [phraseKey("przyjazny", "a1-23")]: {
    sk: "Nowy kolega jest przyjazny.",
    ua: "Новий колега дружній.",
    ru: "Новый коллега дружелюбный.",
    en: "The new colleague is friendly.",
    uaTokens: ["Новий", "колега", "дружній", "."],
    ruTokens: ["Новый", "коллега", "дружелюбный", "."],
    enTokens: ["The", "new", "colleague", "is", "friendly", "."],
    extraUaTokens: ["щирих", "серйозний", "веселий"],
    extraRuTokens: ["искренних", "серьёзный", "забавный"],
    extraEnTokens: ["honest", "serious", "funny"],
  },

  [phraseKey("poważny", "a1-23")]: {
    sk: "On zawsze jest poważny.",
    ua: "Він завжди серйозний.",
    ru: "Он всегда серьёзный.",
    en: "He is always serious.",
    uaTokens: ["Він", "завжди", "серйозний", "."],
    ruTokens: ["Он", "всегда", "серьёзный", "."],
    enTokens: ["He", "is", "always", "serious", "."],
    extraUaTokens: ["дуже", "дружній", "брат"],
    extraRuTokens: ["очень", "дружелюбный", "брат"],
    extraEnTokens: ["very", "friendly", "brother"],
  },

  [phraseKey("zabawny", "a1-23")]: {
    sk: "Twój brat jest bardzo zabawny.",
    ua: "Твій брат дуже веселий.",
    ru: "Твой брат очень забавный.",
    en: "Your brother is very funny.",
    uaTokens: ["Твій", "брат", "дуже", "веселий", "."],
    ruTokens: ["Твой", "брат", "очень", "забавный", "."],
    enTokens: ["Your", "brother", "is", "very", "funny", "."],
    extraUaTokens: ["серйозний", "тихий", "колега"],
    extraRuTokens: ["серьёзный", "тихий", "коллега"],
    extraEnTokens: ["serious", "quiet", "colleague"],
  },

  [phraseKey("cichy", "a1-23")]: {
    sk: "To jest cichy chłopak.",
    ua: "Це тихий хлопець.",
    ru: "Это тихий парень.",
    en: "This is a quiet boy.",
    uaTokens: ["Це", "тихий", "хлопець", "."],
    ruTokens: ["Это", "тихий", "парень", "."],
    enTokens: ["This", "is", "a", "quiet", "boy", "."],
    extraUaTokens: ["веселий", "серйозний", "людина"],
    extraRuTokens: ["забавный", "серьёзный", "человек"],
    extraEnTokens: ["funny", "serious", "person"],
  },

  // =========================
  // LESSON 24 — Погода (розширено)
  // =========================
  [phraseKey("ciepło", "a1-24")]: {
    sk: "Dziś jest ciepło.",
    ua: "Сьогодні тепло.",
    ru: "Сегодня тепло.",
    en: "It is warm today.",
    uaTokens: ["Сьогодні", "тепло", "."],
    ruTokens: ["Сегодня", "тепло", "."],
    enTokens: ["It", "is", "warm", "today", "."],
    extraUaTokens: ["хмарно", "вітер", "прогноз"],
    extraRuTokens: ["пасмурно", "ветер", "прогноз"],
    extraEnTokens: ["cloudy", "wind", "forecast"],
  },

  [phraseKey("zimno", "a1-24")]: {
    sk: "Rano było bardzo zimno.",
    ua: "Вранці було дуже холодно.",
    ru: "Утром было очень холодно.",
    en: "It was very cold in the morning.",
    uaTokens: ["Вранці", "було", "дуже", "холодно", "."],
    ruTokens: ["Утром", "было", "очень", "холодно", "."],
    enTokens: ["It", "was", "very", "cold", "in", "the", "morning", "."],
    extraUaTokens: ["тепло", "вітер", "мороз"],
    extraRuTokens: ["тепло", "ветер", "мороз"],
    extraEnTokens: ["warm", "wind", "frost"],
  },

  [phraseKey("pochmurno", "a1-24")]: {
    sk: "Dziś jest pochmurno.",
    ua: "Сьогодні хмарно.",
    ru: "Сегодня пасмурно.",
    en: "It is cloudy today.",
    uaTokens: ["Сьогодні", "хмарно", "."],
    ruTokens: ["Сегодня", "пасмурно", "."],
    enTokens: ["It", "is", "cloudy", "today", "."],
    extraUaTokens: ["тепло", "ясно", "дощ"],
    extraRuTokens: ["тепло", "светло", "дождь"],
    extraEnTokens: ["warm", "clear", "rain"],
  },

  [phraseKey("jasno", "a1-24")]: {
    sk: "Rano jest już jasno.",
    ua: "Вранці вже ясно.",
    ru: "Утром уже светло.",
    en: "It is already light in the morning.",
    uaTokens: ["Вранці", "вже", "ясно", "."],
    ruTokens: ["Утром", "уже", "светло", "."],
    enTokens: ["It", "is", "already", "light", "in", "the", "morning", "."],
    extraUaTokens: ["хмарно", "тепло", "вітер"],
    extraRuTokens: ["пасмурно", "тепло", "ветер"],
    extraEnTokens: ["cloudy", "warm", "wind"],
  },

  [phraseKey("padać deszcz", "a1-24")]: {
    sk: "Dziś będzie padać deszcz.",
    ua: "Сьогодні буде йти дощ.",
    ru: "Сегодня будет идти дождь.",
    en: "It will rain today.",
    uaTokens: ["Сьогодні", "буде", "йти", "дощ", "."],
    ruTokens: ["Сегодня", "будет", "идти", "дождь", "."],
    enTokens: ["It", "will", "rain", "today", "."],
    extraUaTokens: ["сніг", "вітер", "прогноз"],
    extraRuTokens: ["снег", "ветер", "прогноз"],
    extraEnTokens: ["snow", "wind", "forecast"],
  },

  [phraseKey("padać śnieg", "a1-24")]: {
    sk: "Zimą często pada śnieg.",
    ua: "Взимку часто йде сніг.",
    ru: "Зимой часто идёт снег.",
    en: "It often snows in winter.",
    uaTokens: ["Взимку", "часто", "йде", "сніг", "."],
    ruTokens: ["Зимой", "часто", "идёт", "снег", "."],
    enTokens: ["It", "often", "snows", "in", "winter", "."],
    extraUaTokens: ["дощ", "вітер", "мороз"],
    extraRuTokens: ["дождь", "ветер", "мороз"],
    extraEnTokens: ["rain", "wind", "frost"],
  },

  [phraseKey("wiatr", "a1-24")]: {
    sk: "Dziś wieje silny wiatr.",
    ua: "Сьогодні дме сильний вітер.",
    ru: "Сегодня дует сильный ветер.",
    en: "A strong wind is blowing today.",
    uaTokens: ["Сьогодні", "дме", "сильний", "вітер", "."],
    ruTokens: ["Сегодня", "дует", "сильный", "ветер", "."],
    enTokens: ["A", "strong", "wind", "is", "blowing", "today", "."],
    extraUaTokens: ["дощ", "сніг", "ясно"],
    extraRuTokens: ["дождь", "снег", "светло"],
    extraEnTokens: ["rain", "snow", "clear"],
  },

  [phraseKey("mróz", "a1-24")]: {
    sk: "W nocy był duży mróz.",
    ua: "Вночі був сильний мороз.",
    ru: "Ночью был сильный мороз.",
    en: "There was heavy frost at night.",
    uaTokens: ["Вночі", "був", "сильний", "мороз", "."],
    ruTokens: ["Ночью", "был", "сильный", "мороз", "."],
    enTokens: ["There", "was", "heavy", "frost", "at", "night", "."],
    extraUaTokens: ["вітер", "сніг", "холодно"],
    extraRuTokens: ["ветер", "снег", "холодно"],
    extraEnTokens: ["wind", "snow", "cold"],
  },

  [phraseKey("burza", "a1-24")]: {
    sk: "Wieczorem przyszła burza.",
    ua: "Увечері прийшла буря.",
    ru: "Вечером началась буря.",
    en: "A storm started in the evening.",
    uaTokens: ["Увечері", "прийшла", "буря", "."],
    ruTokens: ["Вечером", "началась", "буря", "."],
    enTokens: ["A", "storm", "started", "in", "the", "evening", "."],
    extraUaTokens: ["вітер", "дощ", "прогноз"],
    extraRuTokens: ["ветер", "дождь", "прогноз"],
    extraEnTokens: ["wind", "rain", "forecast"],
  },

  [phraseKey("prognoza", "a1-24")]: {
    sk: "Sprawdzam prognozę pogody.",
    ua: "Я перевіряю прогноз погоди.",
    ru: "Я проверяю прогноз погоды.",
    en: "I check the weather forecast.",
    uaTokens: ["Я", "перевіряю", "прогноз", "погоди", "."],
    ruTokens: ["Я", "проверяю", "прогноз", "погоды", "."],
    enTokens: ["I", "check", "the", "weather", "forecast", "."],
    extraUaTokens: ["вітер", "дощ", "сніг"],
    extraRuTokens: ["ветер", "дождь", "снег"],
    extraEnTokens: ["wind", "rain", "snow"],
  },

  // =========================
  // LESSON 25 — Їжа (розширено)
  // =========================
  [phraseKey("śniadanie", "a1-25")]: {
    sk: "Na śniadanie jem jajka.",
    ua: "На сніданок я їм яйця.",
    ru: "На завтрак я ем яйца.",
    en: "I eat eggs for breakfast.",
    uaTokens: ["На", "сніданок", "я", "їм", "яйця", "."],
    ruTokens: ["На", "завтрак", "я", "ем", "яйца", "."],
    enTokens: ["I", "eat", "eggs", "for", "breakfast", "."],
    extraUaTokens: ["обід", "родиною", "торт"],
    extraRuTokens: ["обед", "семьёй", "торт"],
    extraEnTokens: ["lunch", "family", "cake"],
  },

  [phraseKey("obiad", "a1-25")]: {
    sk: "Obiad jest już gotowy.",
    ua: "Обід уже готовий.",
    ru: "Обед уже готов.",
    en: "Lunch is already ready.",
    uaTokens: ["Обід", "уже", "готовий", "."],
    ruTokens: ["Обед", "уже", "готов", "."],
    enTokens: ["Lunch", "is", "already", "ready", "."],
    extraUaTokens: ["сніданок", "родиною", "смак"],
    extraRuTokens: ["завтрак", "семьёй", "вкус"],
    extraEnTokens: ["breakfast", "family", "taste"],
  },

  [phraseKey("kolacja", "a1-25")]: {
    sk: "Kolację jem z rodziną.",
    ua: "Я вечеряю з родиною.",
    ru: "Я ужинаю с семьёй.",
    en: "I eat dinner with my family.",
    uaTokens: ["Я", "вечеряю", "з", "родиною", "."],
    ruTokens: ["Я", "ужинаю", "с", "семьёй", "."],
    enTokens: ["I", "eat", "dinner", "with", "my", "family", "."],
    extraUaTokens: ["обід", "яйця", "смак"],
    extraRuTokens: ["обед", "яйца", "вкус"],
    extraEnTokens: ["lunch", "eggs", "taste"],
  },

  [phraseKey("słodki", "a1-25")]: {
    sk: "To ciasto jest bardzo słodkie.",
    ua: "Цей торт дуже солодкий.",
    ru: "Этот торт очень сладкий.",
    en: "This cake is very sweet.",
    uaTokens: ["Цей", "торт", "дуже", "солодкий", "."],
    ruTokens: ["Этот", "торт", "очень", "сладкий", "."],
    enTokens: ["This", "cake", "is", "very", "sweet", "."],
    extraUaTokens: ["суп", "гостру", "смак"],
    extraRuTokens: ["суп", "острую", "вкус"],
    extraEnTokens: ["soup", "spicy", "taste"],
  },

  [phraseKey("słony", "a1-25")]: {
    sk: "Ta zupa jest za słona.",
    ua: "Цей суп занадто солоний.",
    ru: "Этот суп слишком солёный.",
    en: "This soup is too salty.",
    uaTokens: ["Цей", "суп", "занадто", "солоний", "."],
    ruTokens: ["Этот", "суп", "слишком", "солёный", "."],
    enTokens: ["This", "soup", "is", "too", "salty", "."],
    extraUaTokens: ["торт", "солодкий", "їжу"],
    extraRuTokens: ["торт", "сладкий", "еду"],
    extraEnTokens: ["cake", "sweet", "food"],
  },

  [phraseKey("pikantny", "a1-25")]: {
    sk: "Nie lubię pikantnego jedzenia.",
    ua: "Я не люблю гостру їжу.",
    ru: "Я не люблю острую еду.",
    en: "I do not like spicy food.",
    uaTokens: ["Я", "не", "люблю", "гостру", "їжу", "."],
    ruTokens: ["Я", "не", "люблю", "острую", "еду", "."],
    enTokens: ["I", "do", "not", "like", "spicy", "food", "."],
    extraUaTokens: ["торт", "суп", "смак"],
    extraRuTokens: ["торт", "суп", "вкус"],
    extraEnTokens: ["cake", "soup", "taste"],
  },

  [phraseKey("świeży", "a1-25")]: {
    sk: "Kupuję świeży chleb.",
    ua: "Я купую свіжий хліб.",
    ru: "Я покупаю свежий хлеб.",
    en: "I buy fresh bread.",
    uaTokens: ["Я", "купую", "свіжий", "хліб", "."],
    ruTokens: ["Я", "покупаю", "свежий", "хлеб", "."],
    enTokens: ["I", "buy", "fresh", "bread", "."],
    extraUaTokens: ["торт", "суп", "голод"],
    extraRuTokens: ["торт", "суп", "голод"],
    extraEnTokens: ["cake", "soup", "hunger"],
  },

  [phraseKey("głód", "a1-25")]: {
    sk: "Czuję duży głód.",
    ua: "Я відчуваю сильний голод.",
    ru: "Я чувствую сильный голод.",
    en: "I feel very hungry.",
    uaTokens: ["Я", "відчуваю", "сильний", "голод", "."],
    ruTokens: ["Я", "чувствую", "сильный", "голод", "."],
    enTokens: ["I", "feel", "very", "hungry", "."],
    extraUaTokens: ["спрагу", "смак", "суп"],
    extraRuTokens: ["жажду", "вкус", "суп"],
    extraEnTokens: ["thirst", "taste", "soup"],
  },

  [phraseKey("pragnienie", "a1-25")]: {
    sk: "Po biegu czuję pragnienie.",
    ua: "Після бігу я відчуваю спрагу.",
    ru: "После бега я чувствую жажду.",
    en: "I feel thirsty after running.",
    uaTokens: ["Після", "бігу", "я", "відчуваю", "спрагу", "."],
    ruTokens: ["После", "бега", "я", "чувствую", "жажду", "."],
    enTokens: ["I", "feel", "thirsty", "after", "running", "."],
    extraUaTokens: ["голод", "сік", "смак"],
    extraRuTokens: ["голод", "сок", "вкус"],
    extraEnTokens: ["hunger", "juice", "taste"],
  },

  [phraseKey("smak", "a1-25")]: {
    sk: "Ten sok ma dobry smak.",
    ua: "Цей сік має добрий смак.",
    ru: "У этого сока хороший вкус.",
    en: "This juice has a good taste.",
    uaTokens: ["Цей", "сік", "має", "добрий", "смак", "."],
    ruTokens: ["У", "этого", "сока", "хороший", "вкус", "."],
    enTokens: ["This", "juice", "has", "a", "good", "taste", "."],
    extraUaTokens: ["торт", "суп", "спрагу"],
    extraRuTokens: ["торт", "суп", "жажду"],
    extraEnTokens: ["cake", "soup", "thirst"],
  },
};