import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A1_BUILD_UA_SENTENCES_6: BuildUaSentenceDict = {
    // =========================
    // LESSON 26 — Гроші (розширено)
    // =========================
    [phraseKey("płacić", "a1-26")]: {
        sk: "Wolę płacić kartą.",
        ua: "Я віддаю перевагу платити карткою.",
        ru: "Я предпочитаю платить картой.",
        en: "I prefer to pay by card.",
        uaTokens: ["Я", "віддаю", "перевагу", "платити", "карткою", "."],
        ruTokens: ["Я", "предпочитаю", "платить", "картой", "."],
        enTokens: ["I", "prefer", "to", "pay", "by", "card", "."],
        extraUaTokens: ["готівкою", "вчора", "магазин"],
        extraRuTokens: ["наличными", "вчера", "магазин"],
        extraEnTokens: ["cash", "yesterday", "shop"],
    },

    [phraseKey("zaoszczędzić", "a1-26")]: {
        sk: "Chcę zaoszczędzić trochę pieniędzy.",
        ua: "Я хочу зекономити трохи грошей.",
        ru: "Я хочу сэкономить немного денег.",
        en: "I want to save some money.",
        uaTokens: ["Я", "хочу", "зекономити", "трохи", "грошей", "."],
        ruTokens: ["Я", "хочу", "сэкономить", "немного", "денег", "."],
        enTokens: ["I", "want", "to", "save", "some", "money", "."],
        extraUaTokens: ["витратити", "багато", "сьогодні"],
        extraRuTokens: ["потратить", "много", "сегодня"],
        extraEnTokens: ["spend", "a lot", "today"],
    },

    [phraseKey("wydać", "a1-26")]: {
        sk: "Nie chcę wydać za dużo.",
        ua: "Я не хочу витратити занадто багато.",
        ru: "Я не хочу потратить слишком много.",
        en: "I do not want to spend too much.",
        uaTokens: ["Я", "не", "хочу", "витратити", "занадто", "багато", "."],
        ruTokens: ["Я", "не", "хочу", "потратить", "слишком", "много", "."],
        enTokens: ["I", "do", "not", "want", "to", "spend", "too", "much", "."],
        extraUaTokens: ["зекономити", "гроші", "завтра"],
        extraRuTokens: ["сэкономить", "деньги", "завтра"],
        extraEnTokens: ["save", "money", "tomorrow"],
    },

    [phraseKey("wypłata", "a1-26")]: {
        sk: "Dziś dostałem wypłatę.",
        ua: "Сьогодні я отримав зарплату.",
        ru: "Сегодня я получил зарплату.",
        en: "I got my paycheck today.",
        uaTokens: ["Сьогодні", "я", "отримав", "зарплату", "."],
        ruTokens: ["Сегодня", "я", "получил", "зарплату", "."],
        enTokens: ["I", "got", "my", "paycheck", "today", "."],
        extraUaTokens: ["вчора", "борг", "банк"],
        extraRuTokens: ["вчера", "долг", "банк"],
        extraEnTokens: ["yesterday", "debt", "bank"],
    },

    [phraseKey("kredyt", "a1-26")]: {
        sk: "Nie chcę brać kredytu.",
        ua: "Я не хочу брати кредит.",
        ru: "Я не хочу брать кредит.",
        en: "I do not want to take a loan.",
        uaTokens: ["Я", "не", "хочу", "брати", "кредит", "."],
        ruTokens: ["Я", "не", "хочу", "брать", "кредит", "."],
        enTokens: ["I", "do", "not", "want", "to", "take", "a", "loan", "."],
        extraUaTokens: ["банк", "великий", "сьогодні"],
        extraRuTokens: ["банк", "большой", "сегодня"],
        extraEnTokens: ["bank", "big", "today"],
    },

    [phraseKey("dług", "a1-26")]: {
        sk: "On ma duży dług.",
        ua: "У нього великий борг.",
        ru: "У него большой долг.",
        en: "He has a big debt.",
        uaTokens: ["У", "нього", "великий", "борг", "."],
        ruTokens: ["У", "него", "большой", "долг", "."],
        enTokens: ["He", "has", "a", "big", "debt", "."],
        extraUaTokens: ["малий", "дохід", "банк"],
        extraRuTokens: ["маленький", "доход", "банк"],
        extraEnTokens: ["small", "income", "bank"],
    },

    [phraseKey("bankomat", "a1-26")]: {
        sk: "Szukam bankomatu.",
        ua: "Я шукаю банкомат.",
        ru: "Я ищу банкомат.",
        en: "I am looking for an ATM.",
        uaTokens: ["Я", "шукаю", "банкомат", "."],
        ruTokens: ["Я", "ищу", "банкомат", "."],
        enTokens: ["I", "am", "looking", "for", "an", "ATM", "."],
        extraUaTokens: ["банк", "карта", "вчора"],
        extraRuTokens: ["банк", "карта", "вчера"],
        extraEnTokens: ["bank", "card", "yesterday"],
    },

    [phraseKey("konto", "a1-26")]: {
        sk: "Mam konto w tym banku.",
        ua: "У мене є рахунок у цьому банку.",
        ru: "У меня есть счёт в этом банке.",
        en: "I have an account in this bank.",
        uaTokens: ["У", "мене", "є", "рахунок", "у", "цьому", "банку", "."],
        ruTokens: ["У", "меня", "есть", "счёт", "в", "этом", "банке", "."],
        enTokens: ["I", "have", "an", "account", "in", "this", "bank", "."],
        extraUaTokens: ["інший", "магазин", "гроші"],
        extraRuTokens: ["другой", "магазин", "деньги"],
        extraEnTokens: ["other", "shop", "money"],
    },

    [phraseKey("dochód", "a1-26")]: {
        sk: "Mój dochód jest stabilny.",
        ua: "Мій дохід стабільний.",
        ru: "Мой доход стабильный.",
        en: "My income is stable.",
        uaTokens: ["Мій", "дохід", "стабільний", "."],
        ruTokens: ["Мой", "доход", "стабильный", "."],
        enTokens: ["My", "income", "is", "stable", "."],
        extraUaTokens: ["витрати", "великі", "зараз"],
        extraRuTokens: ["расходы", "большие", "сейчас"],
        extraEnTokens: ["expenses", "big", "now"],
    },

    [phraseKey("wydatek", "a1-26")]: {
        sk: "To był duży wydatek.",
        ua: "Це була велика витрата.",
        ru: "Это был большой расход.",
        en: "It was a big expense.",
        uaTokens: ["Це", "була", "велика", "витрата", "."],
        ruTokens: ["Это", "был", "большой", "расход", "."],
        enTokens: ["It", "was", "a", "big", "expense", "."],
        extraUaTokens: ["малий", "дохід", "учора"],
        extraRuTokens: ["маленький", "доход", "вчера"],
        extraEnTokens: ["small", "income", "yesterday"],
    },

    // =========================
    // LESSON 27 — Технології (практика)
    // =========================
    [phraseKey("włączyć", "a1-27")]: {
        sk: "Możesz włączyć komputer?",
        ua: "Можеш увімкнути комп’ютер?",
        ru: "Можешь включить компьютер?",
        en: "Can you turn on the computer?",
        uaTokens: ["Можеш", "увімкнути", "комп’ютер", "?"],
        ruTokens: ["Можешь", "включить", "компьютер", "?"],
        enTokens: ["Can", "you", "turn", "on", "the", "computer", "?"],
        extraUaTokens: ["телефон", "вимкнути", "зараз"],
        extraRuTokens: ["телефон", "выключить", "сейчас"],
        extraEnTokens: ["phone", "turn", "off"],
    },

    [phraseKey("wyłączyć", "a1-27")]: {
        sk: "Proszę wyłączyć światło.",
        ua: "Будь ласка, вимкни світло.",
        ru: "Пожалуйста, выключи свет.",
        en: "Please turn off the light.",
        uaTokens: ["Будь", "ласка", ",", "вимкни", "світло", "."],
        ruTokens: ["Пожалуйста", ",", "выключи", "свет", "."],
        enTokens: ["Please", "turn", "off", "the", "light", "."],
        extraUaTokens: ["увімкни", "лампу", "тут"],
        extraRuTokens: ["включи", "лампу", "здесь"],
        extraEnTokens: ["turn", "on", "lamp"],
    },

    [phraseKey("ładować", "a1-27")]: {
        sk: "Muszę ładować telefon.",
        ua: "Мені треба зарядити телефон.",
        ru: "Мне нужно зарядить телефон.",
        en: "I need to charge the phone.",
        uaTokens: ["Мені", "треба", "зарядити", "телефон", "."],
        ruTokens: ["Мне", "нужно", "зарядить", "телефон", "."],
        enTokens: ["I", "need", "to", "charge", "the", "phone", "."],
        extraUaTokens: ["ноутбук", "розряджений", "зараз"],
        extraRuTokens: ["ноутбук", "разряжен", "сейчас"],
        extraEnTokens: ["laptop", "dead", "now"],
    },

    [phraseKey("zalogować się", "a1-27")]: {
        sk: "Nie mogę się zalogować.",
        ua: "Я не можу увійти.",
        ru: "Я не могу войти.",
        en: "I cannot log in.",
        uaTokens: ["Я", "не", "можу", "увійти", "."],
        ruTokens: ["Я", "не", "могу", "войти", "."],
        enTokens: ["I", "cannot", "log", "in", "."],
        extraUaTokens: ["акаунт", "пароль", "зараз"],
        extraRuTokens: ["аккаунт", "пароль", "сейчас"],
        extraEnTokens: ["account", "password", "now"],
    },

    [phraseKey("wylogować się", "a1-27")]: {
        sk: "Pamiętaj, żeby się wylogować.",
        ua: "Пам’ятай, що треба вийти з акаунта.",
        ru: "Помни, что нужно выйти из аккаунта.",
        en: "Remember to log out.",
        uaTokens: ["Пам’ятай", ",", "що", "треба", "вийти", "з", "акаунта", "."],
        ruTokens: ["Помни", ",", "что", "нужно", "выйти", "из", "аккаунта", "."],
        enTokens: ["Remember", "to", "log", "out", "."],
        extraUaTokens: ["увійти", "пароль", "потім"],
        extraRuTokens: ["войти", "пароль", "потом"],
        extraEnTokens: ["log", "in", "later"],
    },

    [phraseKey("pobrać", "a1-27")]: {
        sk: "Chcę pobrać ten plik.",
        ua: "Я хочу завантажити цей файл.",
        ru: "Я хочу скачать этот файл.",
        en: "I want to download this file.",
        uaTokens: ["Я", "хочу", "завантажити", "цей", "файл", "."],
        ruTokens: ["Я", "хочу", "скачать", "этот", "файл", "."],
        enTokens: ["I", "want", "to", "download", "this", "file", "."],
        extraUaTokens: ["видалити", "документ", "завтра"],
        extraRuTokens: ["удалить", "документ", "завтра"],
        extraEnTokens: ["delete", "document", "tomorrow"],
    },

    [phraseKey("zapisać", "a1-27")]: {
        sk: "Muszę zapisać ten dokument.",
        ua: "Мені треба зберегти цей документ.",
        ru: "Мне нужно сохранить этот документ.",
        en: "I need to save this document.",
        uaTokens: ["Мені", "треба", "зберегти", "цей", "документ", "."],
        ruTokens: ["Мне", "нужно", "сохранить", "этот", "документ", "."],
        enTokens: ["I", "need", "to", "save", "this", "document", "."],
        extraUaTokens: ["файл", "видалити", "пізніше"],
        extraRuTokens: ["файл", "удалить", "позже"],
        extraEnTokens: ["file", "delete", "later"],
    },

    [phraseKey("usunąć", "a1-27")]: {
        sk: "Chcę usunąć to zdjęcie.",
        ua: "Я хочу видалити це фото.",
        ru: "Я хочу удалить это фото.",
        en: "I want to delete this photo.",
        uaTokens: ["Я", "хочу", "видалити", "це", "фото", "."],
        ruTokens: ["Я", "хочу", "удалить", "это", "фото", "."],
        enTokens: ["I", "want", "to", "delete", "this", "photo", "."],
        extraUaTokens: ["зберегти", "файл", "нове"],
        extraRuTokens: ["сохранить", "файл", "новое"],
        extraEnTokens: ["save", "file", "new"],
    },

    [phraseKey("kliknąć", "a1-27")]: {
        sk: "Musisz kliknąć tutaj.",
        ua: "Тобі треба натиснути тут.",
        ru: "Тебе нужно нажать здесь.",
        en: "You need to click here.",
        uaTokens: ["Тобі", "треба", "натиснути", "тут", "."],
        ruTokens: ["Тебе", "нужно", "нажать", "здесь", "."],
        enTokens: ["You", "need", "to", "click", "here", "."],
        extraUaTokens: ["там", "посилання", "зараз"],
        extraRuTokens: ["там", "ссылка", "сейчас"],
        extraEnTokens: ["there", "link", "now"],
    },

    [phraseKey("ustawienia", "a1-27")]: {
        sk: "Szukam ustawień w telefonie.",
        ua: "Я шукаю налаштування в телефоні.",
        ru: "Я ищу настройки в телефоне.",
        en: "I am looking for the settings on the phone.",
        uaTokens: ["Я", "шукаю", "налаштування", "в", "телефоні", "."],
        ruTokens: ["Я", "ищу", "настройки", "в", "телефоне", "."],
        enTokens: ["I", "am", "looking", "for", "the", "settings", "on", "the", "phone", "."],
        extraUaTokens: ["комп’ютер", "пароль", "нові"],
        extraRuTokens: ["компьютер", "пароль", "новые"],
        extraEnTokens: ["computer", "password", "new"],
    },

    // =========================
    // LESSON 28 — Подорожі (ситуації)
    // =========================
    [phraseKey("lot", "a1-28")]: {
        sk: "Mój lot jest wieczorem.",
        ua: "Мій рейс увечері.",
        ru: "Мой рейс вечером.",
        en: "My flight is in the evening.",
        uaTokens: ["Мій", "рейс", "увечері", "."],
        ruTokens: ["Мой", "рейс", "вечером", "."],
        enTokens: ["My", "flight", "is", "in", "the", "evening", "."],
        extraUaTokens: ["вранці", "затримка", "завтра"],
        extraRuTokens: ["утром", "задержка", "завтра"],
        extraEnTokens: ["morning", "delay", "tomorrow"],
    },

    [phraseKey("spóźnienie", "a1-28")]: {
        sk: "Lot ma spóźnienie.",
        ua: "Рейс має затримку.",
        ru: "Рейс задерживается.",
        en: "The flight is delayed.",
        uaTokens: ["Рейс", "має", "затримку", "."],
        ruTokens: ["Рейс", "задерживается", "."],
        enTokens: ["The", "flight", "is", "delayed", "."],
        extraUaTokens: ["вчасно", "приліт", "сьогодні"],
        extraRuTokens: ["вовремя", "прилёт", "сегодня"],
        extraEnTokens: ["on", "time", "arrival"],
    },

    [phraseKey("odlot", "a1-28")]: {
        sk: "Odlot jest o szóstej rano.",
        ua: "Виліт о шостій ранку.",
        ru: "Вылет в шесть утра.",
        en: "The departure is at six in the morning.",
        uaTokens: ["Виліт", "о", "шостій", "ранку", "."],
        ruTokens: ["Вылет", "в", "шесть", "утра", "."],
        enTokens: ["The", "departure", "is", "at", "six", "in", "the", "morning", "."],
        extraUaTokens: ["приліт", "увечері", "сьогодні"],
        extraRuTokens: ["прилёт", "вечером", "сегодня"],
        extraEnTokens: ["arrival", "evening", "today"],
    },

    [phraseKey("przylot", "a1-28")]: {
        sk: "Przylot będzie o dziewiątej.",
        ua: "Приліт буде о дев’ятій.",
        ru: "Прилёт будет в девять.",
        en: "The arrival will be at nine.",
        uaTokens: ["Приліт", "буде", "о", "дев’ятій", "."],
        ruTokens: ["Прилёт", "будет", "в", "девять", "."],
        enTokens: ["The", "arrival", "will", "be", "at", "nine", "."],
        extraUaTokens: ["виліт", "ранку", "завтра"],
        extraRuTokens: ["вылет", "утра", "завтра"],
        extraEnTokens: ["departure", "morning", "tomorrow"],
    },

    [phraseKey("kontrola paszportowa", "a1-28")]: {
        sk: "Teraz idziemy na kontrolę paszportową.",
        ua: "Зараз ми йдемо на паспортний контроль.",
        ru: "Сейчас мы идём на паспортный контроль.",
        en: "Now we are going to passport control.",
        uaTokens: ["Зараз", "ми", "йдемо", "на", "паспортний", "контроль", "."],
        ruTokens: ["Сейчас", "мы", "идём", "на", "паспортный", "контроль", "."],
        enTokens: ["Now", "we", "are", "going", "to", "passport", "control", "."],
        extraUaTokens: ["багаж", "потім", "квиток"],
        extraRuTokens: ["багаж", "потом", "билет"],
        extraEnTokens: ["luggage", "later", "ticket"],
    },

    [phraseKey("bagaż", "a1-28")]: {
        sk: "Mój bagaż jest ciężki.",
        ua: "Мій багаж важкий.",
        ru: "Мой багаж тяжёлый.",
        en: "My luggage is heavy.",
        uaTokens: ["Мій", "багаж", "важкий", "."],
        ruTokens: ["Мой", "багаж", "тяжёлый", "."],
        enTokens: ["My", "luggage", "is", "heavy", "."],
        extraUaTokens: ["легкий", "валіза", "сьогодні"],
        extraRuTokens: ["лёгкий", "чемодан", "сегодня"],
        extraEnTokens: ["light", "suitcase", "today"],
    },

    [phraseKey("rezerwacja", "a1-28")]: {
        sk: "Mam rezerwację w hotelu.",
        ua: "У мене є бронювання в готелі.",
        ru: "У меня есть бронь в отеле.",
        en: "I have a reservation at the hotel.",
        uaTokens: ["У", "мене", "є", "бронювання", "в", "готелі", "."],
        ruTokens: ["У", "меня", "есть", "бронь", "в", "отеле", "."],
        enTokens: ["I", "have", "a", "reservation", "at", "the", "hotel", "."],
        extraUaTokens: ["кімната", "скасувати", "завтра"],
        extraRuTokens: ["комната", "отменить", "завтра"],
        extraEnTokens: ["room", "cancel", "tomorrow"],
    },

    [phraseKey("przewodnik", "a1-28")]: {
        sk: "Przewodnik mówi po angielsku.",
        ua: "Гід говорить англійською.",
        ru: "Гид говорит по-английски.",
        en: "The guide speaks English.",
        uaTokens: ["Гід", "говорить", "англійською", "."],
        ruTokens: ["Гид", "говорит", "по-английски", "."],
        enTokens: ["The", "guide", "speaks", "English", "."],
        extraUaTokens: ["польською", "турист", "сьогодні"],
        extraRuTokens: ["по-польски", "турист", "сегодня"],
        extraEnTokens: ["Polish", "tourist", "today"],
    },

    [phraseKey("mapa", "a1-28")]: {
        sk: "Potrzebuję mapy miasta.",
        ua: "Мені потрібна карта міста.",
        ru: "Мне нужна карта города.",
        en: "I need a city map.",
        uaTokens: ["Мені", "потрібна", "карта", "міста", "."],
        ruTokens: ["Мне", "нужна", "карта", "города", "."],
        enTokens: ["I", "need", "a", "city", "map", "."],
        extraUaTokens: ["вулиця", "путівник", "завтра"],
        extraRuTokens: ["улица", "путеводитель", "завтра"],
        extraEnTokens: ["street", "guidebook", "tomorrow"],
    },

    [phraseKey("cel", "a1-28")]: {
        sk: "To jest mój cel podróży.",
        ua: "Це моя ціль подорожі.",
        ru: "Это моя цель поездки.",
        en: "This is my travel destination.",
        uaTokens: ["Це", "моя", "ціль", "подорожі", "."],
        ruTokens: ["Это", "моя", "цель", "поездки", "."],
        enTokens: ["This", "is", "my", "travel", "destination", "."],
        extraUaTokens: ["початок", "маршрут", "сьогодні"],
        extraRuTokens: ["начало", "маршрут", "сегодня"],
        extraEnTokens: ["start", "route", "today"],
    },

    // =========================
    // LESSON 29 — Робочі фрази
    // =========================
    [phraseKey("rozumiem", "a1-29")]: {
        sk: "Tak, rozumiem.",
        ua: "Так, я розумію.",
        ru: "Да, я понимаю.",
        en: "Yes, I understand.",
        uaTokens: ["Так", ",", "я", "розумію", "."],
        ruTokens: ["Да", ",", "я", "понимаю", "."],
        enTokens: ["Yes", ",", "I", "understand", "."],
        extraUaTokens: ["ні", "питання", "зараз"],
        extraRuTokens: ["нет", "вопрос", "сейчас"],
        extraEnTokens: ["no", "question", "now"],
    },

    [phraseKey("nie rozumiem", "a1-29")]: {
        sk: "Przepraszam, nie rozumiem.",
        ua: "Вибачте, я не розумію.",
        ru: "Извините, я не понимаю.",
        en: "Sorry, I do not understand.",
        uaTokens: ["Вибачте", ",", "я", "не", "розумію", "."],
        ruTokens: ["Извините", ",", "я", "не", "понимаю", "."],
        enTokens: ["Sorry", ",", "I", "do", "not", "understand", "."],
        extraUaTokens: ["допомога", "поясніть", "ще"],
        extraRuTokens: ["помощь", "объясните", "ещё"],
        extraEnTokens: ["help", "explain", "again"],
    },

    [phraseKey("gotowe", "a1-29")]: {
        sk: "To już gotowe.",
        ua: "Це вже готово.",
        ru: "Это уже готово.",
        en: "It is already done.",
        uaTokens: ["Це", "вже", "готово", "."],
        ruTokens: ["Это", "уже", "готово", "."],
        enTokens: ["It", "is", "already", "done", "."],
        extraUaTokens: ["ще", "не", "робота"],
        extraRuTokens: ["ещё", "не", "работа"],
        extraEnTokens: ["not", "yet", "work"],
    },

    [phraseKey("mogę", "a1-29")]: {
        sk: "Mogę zacząć teraz?",
        ua: "Можна почати зараз?",
        ru: "Можно начать сейчас?",
        en: "May I start now?",
        uaTokens: ["Можна", "почати", "зараз", "?"],
        ruTokens: ["Можно", "начать", "сейчас", "?"],
        enTokens: ["May", "I", "start", "now", "?"],
        extraUaTokens: ["пізніше", "роботу", "сьогодні"],
        extraRuTokens: ["позже", "работу", "сегодня"],
        extraEnTokens: ["later", "work", "today"],
    },

    [phraseKey("potrzebuję", "a1-29")]: {
        sk: "Potrzebuję twojej pomocy.",
        ua: "Мені потрібна твоя допомога.",
        ru: "Мне нужна твоя помощь.",
        en: "I need your help.",
        uaTokens: ["Мені", "потрібна", "твоя", "допомога", "."],
        ruTokens: ["Мне", "нужна", "твоя", "помощь", "."],
        enTokens: ["I", "need", "your", "help", "."],
        extraUaTokens: ["порада", "зараз", "робота"],
        extraRuTokens: ["совет", "сейчас", "работа"],
        extraEnTokens: ["advice", "now", "work"],
    },

    [phraseKey("problem", "a1-29")]: {
        sk: "Mamy problem z komputerem.",
        ua: "У нас проблема з комп’ютером.",
        ru: "У нас проблема с компьютером.",
        en: "We have a problem with the computer.",
        uaTokens: ["У", "нас", "проблема", "з", "комп’ютером", "."],
        ruTokens: ["У", "нас", "проблема", "с", "компьютером", "."],
        enTokens: ["We", "have", "a", "problem", "with", "the", "computer", "."],
        extraUaTokens: ["телефон", "маленька", "сьогодні"],
        extraRuTokens: ["телефон", "маленькая", "сегодня"],
        extraEnTokens: ["phone", "small", "today"],
    },

    [phraseKey("w porządku", "a1-29")]: {
        sk: "Wszystko jest w porządku.",
        ua: "Все в порядку.",
        ru: "Всё в порядке.",
        en: "Everything is all right.",
        uaTokens: ["Все", "в", "порядку", "."],
        ruTokens: ["Всё", "в", "порядке", "."],
        enTokens: ["Everything", "is", "all", "right", "."],
        extraUaTokens: ["проблема", "велика", "зараз"],
        extraRuTokens: ["проблема", "большая", "сейчас"],
        extraEnTokens: ["problem", "big", "now"],
    },

    [phraseKey("od razu", "a1-29")]: {
        sk: "Zrobię to od razu.",
        ua: "Я зроблю це одразу.",
        ru: "Я сделаю это сразу.",
        en: "I will do it right away.",
        uaTokens: ["Я", "зроблю", "це", "одразу", "."],
        ruTokens: ["Я", "сделаю", "это", "сразу", "."],
        enTokens: ["I", "will", "do", "it", "right", "away", "."],
        extraUaTokens: ["пізніше", "робота", "завтра"],
        extraRuTokens: ["позже", "работа", "завтра"],
        extraEnTokens: ["later", "work", "tomorrow"],
    },

    [phraseKey("później", "a1-29")]: {
        sk: "Porozmawiamy o tym później.",
        ua: "Ми поговоримо про це пізніше.",
        ru: "Мы поговорим об этом позже.",
        en: "We will talk about it later.",
        uaTokens: ["Ми", "поговоримо", "про", "це", "пізніше", "."],
        ruTokens: ["Мы", "поговорим", "об", "этом", "позже", "."],
        enTokens: ["We", "will", "talk", "about", "it", "later", "."],
        extraUaTokens: ["зараз", "проблема", "разом"],
        extraRuTokens: ["сейчас", "проблема", "вместе"],
        extraEnTokens: ["now", "problem", "together"],
    },

    [phraseKey("umówić się", "a1-29")]: {
        sk: "Musimy się umówić na jutro.",
        ua: "Нам треба домовитися на завтра.",
        ru: "Нам нужно договориться на завтра.",
        en: "We need to arrange it for tomorrow.",
        uaTokens: ["Нам", "треба", "домовитися", "на", "завтра", "."],
        ruTokens: ["Нам", "нужно", "договориться", "на", "завтра", "."],
        enTokens: ["We", "need", "to", "arrange", "it", "for", "tomorrow", "."],
        extraUaTokens: ["сьогодні", "зустріч", "пізніше"],
        extraRuTokens: ["сегодня", "встреча", "позже"],
        extraEnTokens: ["today", "meeting", "later"],
    },

    // =========================
    // LESSON 30 — Часті дієслова
    // =========================
    [phraseKey("mieć", "a1-30")]: {
        sk: "Muszę mieć więcej czasu.",
        ua: "Мені треба мати більше часу.",
        ru: "Мне нужно иметь больше времени.",
        en: "I need to have more time.",
        uaTokens: ["Мені", "треба", "мати", "більше", "часу", "."],
        ruTokens: ["Мне", "нужно", "иметь", "больше", "времени", "."],
        enTokens: ["I", "need", "to", "have", "more", "time", "."],
        extraUaTokens: ["менше", "роботи", "сьогодні"],
        extraRuTokens: ["меньше", "работы", "сегодня"],
        extraEnTokens: ["less", "work", "today"],
    },

    [phraseKey("być", "a1-30")]: {
        sk: "Chcę być spokojny.",
        ua: "Я хочу бути спокійним.",
        ru: "Я хочу быть спокойным.",
        en: "I want to be calm.",
        uaTokens: ["Я", "хочу", "бути", "спокійним", "."],
        ruTokens: ["Я", "хочу", "быть", "спокойным", "."],
        enTokens: ["I", "want", "to", "be", "calm", "."],
        extraUaTokens: ["нервовим", "завтра", "вдома"],
        extraRuTokens: ["нервным", "завтра", "дома"],
        extraEnTokens: ["nervous", "tomorrow", "home"],
    },

    [phraseKey("robić", "a1-30")]: {
        sk: "Lubię robić zakupy.",
        ua: "Я люблю робити покупки.",
        ru: "Я люблю делать покупки.",
        en: "I like shopping.",
        uaTokens: ["Я", "люблю", "робити", "покупки", "."],
        ruTokens: ["Я", "люблю", "делать", "покупки", "."],
        enTokens: ["I", "like", "shopping", "."],
        extraUaTokens: ["працювати", "вранці", "разом"],
        extraRuTokens: ["работать", "утром", "вместе"],
        extraEnTokens: ["work", "morning", "together"],
    },

    [phraseKey("iść", "a1-30")]: {
        sk: "Muszę iść do pracy.",
        ua: "Мені треба йти на роботу.",
        ru: "Мне нужно идти на работу.",
        en: "I need to go to work.",
        uaTokens: ["Мені", "треба", "йти", "на", "роботу", "."],
        ruTokens: ["Мне", "нужно", "идти", "на", "работу", "."],
        enTokens: ["I", "need", "to", "go", "to", "work", "."],
        extraUaTokens: ["додому", "завтра", "пішки"],
        extraRuTokens: ["домой", "завтра", "пешком"],
        extraEnTokens: ["home", "tomorrow", "walking"],
    },

    [phraseKey("widzieć", "a1-30")]: {
        sk: "Widzę cię dobrze.",
        ua: "Я тебе добре бачу.",
        ru: "Я хорошо тебя вижу.",
        en: "I can see you well.",
        uaTokens: ["Я", "тебе", "добре", "бачу", "."],
        ruTokens: ["Я", "хорошо", "тебя", "вижу", "."],
        enTokens: ["I", "can", "see", "you", "well", "."],
        extraUaTokens: ["погано", "чути", "зараз"],
        extraRuTokens: ["плохо", "слышать", "сейчас"],
        extraEnTokens: ["badly", "hear", "now"],
    },

    [phraseKey("słuchać", "a1-30")]: {
        sk: "Lubię słuchać muzyki.",
        ua: "Я люблю слухати музику.",
        ru: "Я люблю слушать музыку.",
        en: "I like listening to music.",
        uaTokens: ["Я", "люблю", "слухати", "музику", "."],
        ruTokens: ["Я", "люблю", "слушать", "музыку", "."],
        enTokens: ["I", "like", "listening", "to", "music", "."],
        extraUaTokens: ["новини", "читати", "ввечері"],
        extraRuTokens: ["новости", "читать", "вечером"],
        extraEnTokens: ["news", "read", "evening"],
    },

    [phraseKey("mówić", "a1-30")]: {
        sk: "Chcę mówić po polsku.",
        ua: "Я хочу говорити польською.",
        ru: "Я хочу говорить по-польски.",
        en: "I want to speak Polish.",
        uaTokens: ["Я", "хочу", "говорити", "польською", "."],
        ruTokens: ["Я", "хочу", "говорить", "по-польски", "."],
        enTokens: ["I", "want", "to", "speak", "Polish", "."],
        extraUaTokens: ["англійською", "вільно", "скоро"],
        extraRuTokens: ["по-английски", "свободно", "скоро"],
        extraEnTokens: ["English", "fluently", "soon"],
    },

    [phraseKey("myśleć", "a1-30")]: {
        sk: "Często myślę o przyszłości.",
        ua: "Я часто думаю про майбутнє.",
        ru: "Я часто думаю о будущем.",
        en: "I often think about the future.",
        uaTokens: ["Я", "часто", "думаю", "про", "майбутнє", "."],
        ruTokens: ["Я", "часто", "думаю", "о", "будущем", "."],
        enTokens: ["I", "often", "think", "about", "the", "future", "."],
        extraUaTokens: ["минуле", "рідко", "зараз"],
        extraRuTokens: ["прошлое", "редко", "сейчас"],
        extraEnTokens: ["past", "rarely", "now"],
    },

    [phraseKey("chcieć", "a1-30")]: {
        sk: "Chcę odpocząć.",
        ua: "Я хочу відпочити.",
        ru: "Я хочу отдохнуть.",
        en: "I want to rest.",
        uaTokens: ["Я", "хочу", "відпочити", "."],
        ruTokens: ["Я", "хочу", "отдохнуть", "."],
        enTokens: ["I", "want", "to", "rest", "."],
        extraUaTokens: ["працювати", "сьогодні", "довше"],
        extraRuTokens: ["работать", "сегодня", "дольше"],
        extraEnTokens: ["work", "today", "longer"],
    },

    [phraseKey("móc", "a1-30")]: {
        sk: "Nie mogę dziś przyjść.",
        ua: "Я не можу сьогодні прийти.",
        ru: "Я не могу сегодня прийти.",
        en: "I cannot come today.",
        uaTokens: ["Я", "не", "можу", "сьогодні", "прийти", "."],
        ruTokens: ["Я", "не", "могу", "сегодня", "прийти", "."],
        enTokens: ["I", "cannot", "come", "today", "."],
        extraUaTokens: ["завтра", "піти", "раніше"],
        extraRuTokens: ["завтра", "пойти", "раньше"],
        extraEnTokens: ["tomorrow", "go", "earlier"],
    },
};