import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A1_BUILD_UA_SENTENCES_8: BuildUaSentenceDict = {
    // =========================
    // LESSON 36 — Транспорт (дії)
    // =========================
    [phraseKey("wsiąść", "a1-36")]: {
        sk: "Musimy wsiąść do autobusu.",
        ua: "Нам треба сісти в автобус.",
        ru: "Нам нужно сесть в автобус.",
        en: "We need to get on the bus.",
        uaTokens: ["Нам", "треба", "сісти", "в", "автобус", "."],
        ruTokens: ["Нам", "нужно", "сесть", "в", "автобус", "."],
        enTokens: ["We", "need", "to", "get", "on", "the", "bus", "."],
        extraUaTokens: ["вийти", "трамвай", "зупинці"],
        extraRuTokens: ["выйти", "трамвай", "остановке"],
        extraEnTokens: ["get", "tram", "stop"],
    },

    [phraseKey("wysiąść", "a1-36")]: {
        sk: "Muszę wysiąść na następnym przystanku.",
        ua: "Мені треба вийти на наступній зупинці.",
        ru: "Мне нужно выйти на следующей остановке.",
        en: "I need to get off at the next stop.",
        uaTokens: ["Мені", "треба", "вийти", "на", "наступній", "зупинці", "."],
        ruTokens: ["Мне", "нужно", "выйти", "на", "следующей", "остановке", "."],
        enTokens: ["I", "need", "to", "get", "off", "at", "the", "next", "stop", "."],
        extraUaTokens: ["автобус", "пересісти", "завтра"],
        extraRuTokens: ["автобус", "пересесть", "завтра"],
        extraEnTokens: ["bus", "transfer", "tomorrow"],
    },

    [phraseKey("przesiąść się", "a1-36")]: {
        sk: "Muszę się przesiąść na tramwaj.",
        ua: "Мені треба пересісти на трамвай.",
        ru: "Мне нужно пересесть на трамвай.",
        en: "I need to transfer to the tram.",
        uaTokens: ["Мені", "треба", "пересісти", "на", "трамвай", "."],
        ruTokens: ["Мне", "нужно", "пересесть", "на", "трамвай", "."],
        enTokens: ["I", "need", "to", "transfer", "to", "the", "tram", "."],
        extraUaTokens: ["автобус", "зупинці", "часто"],
        extraRuTokens: ["автобус", "остановке", "часто"],
        extraEnTokens: ["bus", "stop", "often"],
    },

    [phraseKey("spóźniać się", "a1-36")]: {
        sk: "Ten pociąg często się spóźnia.",
        ua: "Цей поїзд часто запізнюється.",
        ru: "Этот поезд часто опаздывает.",
        en: "This train is often late.",
        uaTokens: ["Цей", "поїзд", "часто", "запізнюється", "."],
        ruTokens: ["Этот", "поезд", "часто", "опаздывает", "."],
        enTokens: ["This", "train", "is", "often", "late", "."],
        extraUaTokens: ["трамвай", "автобус", "вранці"],
        extraRuTokens: ["трамвай", "автобус", "утром"],
        extraEnTokens: ["tram", "bus", "morning"],
    },

    [phraseKey("czekać", "a1-36")]: {
        sk: "Czekam na autobus.",
        ua: "Я чекаю на автобус.",
        ru: "Я жду автобус.",
        en: "I am waiting for the bus.",
        uaTokens: ["Я", "чекаю", "на", "автобус", "."],
        ruTokens: ["Я", "жду", "автобус", "."],
        enTokens: ["I", "am", "waiting", "for", "the", "bus", "."],
        extraUaTokens: ["трамвай", "зупинці", "завтра"],
        extraRuTokens: ["трамвай", "остановке", "завтра"],
        extraEnTokens: ["tram", "stop", "tomorrow"],
    },

    [phraseKey("odejść", "a1-36")]: {
        sk: "Muszę już odejść.",
        ua: "Мені вже треба йти.",
        ru: "Мне уже нужно уходить.",
        en: "I need to leave now.",
        uaTokens: ["Мені", "вже", "треба", "йти", "."],
        ruTokens: ["Мне", "уже", "нужно", "уходить", "."],
        enTokens: ["I", "need", "to", "leave", "now", "."],
        uaAltAnswers: [["Мені", "треба", "вже", "йти", "."]],
        ruAltAnswers: [["Мне", "нужно", "уже", "уходить", "."]],
        extraUaTokens: ["прийти", "завтра", "вранці"],
        extraRuTokens: ["прийти", "завтра", "утром"],
        extraEnTokens: ["come", "tomorrow", "morning"],
    },

    [phraseKey("przyjść", "a1-36")]: {
        sk: "Mogę przyjść jutro rano.",
        ua: "Я можу прийти завтра вранці.",
        ru: "Я могу прийти завтра утром.",
        en: "I can come tomorrow morning.",
        uaTokens: ["Я", "можу", "прийти", "завтра", "вранці", "."],
        ruTokens: ["Я", "могу", "прийти", "завтра", "утром", "."],
        enTokens: ["I", "can", "come", "tomorrow", "morning", "."],
        extraUaTokens: ["сьогодні", "йти", "автобус"],
        extraRuTokens: ["сегодня", "уходить", "автобус"],
        extraEnTokens: ["today", "leave", "bus"],
    },

    [phraseKey("kierować", "a1-36")]: {
        sk: "On umie kierować samochodem.",
        ua: "Він уміє керувати автомобілем.",
        ru: "Он умеет водить машину.",
        en: "He can drive a car.",
        uaTokens: ["Він", "уміє", "керувати", "автомобілем", "."],
        ruTokens: ["Он", "умеет", "водить", "машину", "."],
        enTokens: ["He", "can", "drive", "a", "car", "."],
        extraUaTokens: ["паркуватися", "машину", "тут"],
        extraRuTokens: ["парковаться", "машину", "здесь"],
        extraEnTokens: ["park", "car", "here"],
    },

    [phraseKey("parkować", "a1-36")]: {
        sk: "Nie wolno tu parkować.",
        ua: "Тут не можна паркуватися.",
        ru: "Здесь нельзя парковаться.",
        en: "You cannot park here.",
        uaTokens: ["Тут", "не", "можна", "паркуватися", "."],
        ruTokens: ["Здесь", "нельзя", "парковаться", "."],
        enTokens: ["You", "cannot", "park", "here", "."],
        extraUaTokens: ["автомобілем", "зупинити", "автобус"],
        extraRuTokens: ["машину", "остановить", "автобус"],
        extraEnTokens: ["car", "stop", "bus"],
    },

    [phraseKey("zatrzymać", "a1-36")]: {
        sk: "Muszę zatrzymać samochód.",
        ua: "Мені треба зупинити машину.",
        ru: "Мне нужно остановить машину.",
        en: "I need to stop the car.",
        uaTokens: ["Мені", "треба", "зупинити", "машину", "."],
        ruTokens: ["Мне", "нужно", "остановить", "машину", "."],
        enTokens: ["I", "need", "to", "stop", "the", "car", "."],
        extraUaTokens: ["паркуватися", "вийти", "тут"],
        extraRuTokens: ["парковаться", "выйти", "здесь"],
        extraEnTokens: ["park", "get", "here"],
    },

    // =========================
    // LESSON 37 — Плани
    // =========================
    [phraseKey("plan", "a1-37")]: {
        sk: "Mam plan na weekend.",
        ua: "У мене є план на вихідні.",
        ru: "У меня есть план на выходные.",
        en: "I have a plan for the weekend.",
        uaTokens: ["У", "мене", "є", "план", "на", "вихідні", "."],
        ruTokens: ["У", "меня", "есть", "план", "на", "выходные", "."],
        enTokens: ["I", "have", "a", "plan", "for", "the", "weekend", "."],
        extraUaTokens: ["ціль", "майбутнє", "відпустку"],
        extraRuTokens: ["цель", "будущее", "отпуск"],
        extraEnTokens: ["goal", "future", "vacation"],
    },

    [phraseKey("cel", "a1-37")]: {
        sk: "To jest mój najważniejszy cel.",
        ua: "Це моя найважливіша ціль.",
        ru: "Это моя самая важная цель.",
        en: "This is my most important goal.",
        uaTokens: ["Це", "моя", "найважливіша", "ціль", "."],
        ruTokens: ["Это", "моя", "самая", "важная", "цель", "."],
        enTokens: ["This", "is", "my", "most", "important", "goal", "."],
        extraUaTokens: ["план", "документи", "роботи"],
        extraRuTokens: ["план", "документы", "работы"],
        extraEnTokens: ["plan", "documents", "work"],
    },

    [phraseKey("przyszłość", "a1-37")]: {
        sk: "Często myślę o przyszłości.",
        ua: "Я часто думаю про майбутнє.",
        ru: "Я часто думаю о будущем.",
        en: "I often think about the future.",
        uaTokens: ["Я", "часто", "думаю", "про", "майбутнє", "."],
        ruTokens: ["Я", "часто", "думаю", "о", "будущем", "."],
        enTokens: ["I", "often", "think", "about", "the", "future", "."],
        extraUaTokens: ["план", "тижня", "сьогодні"],
        extraRuTokens: ["план", "неделе", "сегодня"],
        extraEnTokens: ["plan", "week", "today"],
    },

    [phraseKey("przygotować", "a1-37")]: {
        sk: "Muszę przygotować dokumenty.",
        ua: "Мені треба підготувати документи.",
        ru: "Мне нужно подготовить документы.",
        en: "I need to prepare the documents.",
        uaTokens: ["Мені", "треба", "підготувати", "документи", "."],
        ruTokens: ["Мне", "нужно", "подготовить", "документы", "."],
        enTokens: ["I", "need", "to", "prepare", "the", "documents", "."],
        extraUaTokens: ["вирішити", "зустрічі", "відпустку"],
        extraRuTokens: ["решить", "встречи", "отпуск"],
        extraEnTokens: ["decide", "meeting", "vacation"],
    },

    [phraseKey("przyszły tydzień", "a1-37")]: {
        sk: "W przyszłym tygodniu mam dużo pracy.",
        ua: "Наступного тижня в мене багато роботи.",
        ru: "На следующей неделе у меня много работы.",
        en: "I have a lot of work next week.",
        uaTokens: ["Наступного", "тижня", "в", "мене", "багато", "роботи", "."],
        ruTokens: ["На", "следующей", "неделе", "у", "меня", "много", "работы", "."],
        enTokens: ["I", "have", "a", "lot", "of", "work", "next", "week", "."],
        extraUaTokens: ["план", "документи", "сьогодні"],
        extraRuTokens: ["план", "документы", "сегодня"],
        extraEnTokens: ["plan", "documents", "today"],
    },

    [phraseKey("mieć nadzieję", "a1-37")]: {
        sk: "Mam nadzieję, że wszystko będzie dobrze.",
        ua: "Я сподіваюся, що все буде добре.",
        ru: "Я надеюсь, что всё будет хорошо.",
        en: "I hope everything will be fine.",
        uaTokens: ["Я", "сподіваюся", ",", "що", "все", "буде", "добре", "."],
        ruTokens: ["Я", "надеюсь", ",", "что", "всё", "будет", "хорошо", "."],
        enTokens: ["I", "hope", "everything", "will", "be", "fine", "."],
        extraUaTokens: ["сьогодні", "план", "майбутнє"],
        extraRuTokens: ["сегодня", "план", "будущее"],
        extraEnTokens: ["today", "plan", "future"],
    },

    [phraseKey("zdecydować się", "a1-37")]: {
        sk: "Muszę się zdecydować dzisiaj.",
        ua: "Мені треба вирішити сьогодні.",
        ru: "Мне нужно решить сегодня.",
        en: "I need to decide today.",
        uaTokens: ["Мені", "треба", "вирішити", "сьогодні", "."],
        ruTokens: ["Мне", "нужно", "решить", "сегодня", "."],
        enTokens: ["I", "need", "to", "decide", "today", "."],
        uaAltAnswers: [["Мені", "сьогодні", "треба", "вирішити", "."]],
        ruAltAnswers: [["Мне", "сегодня", "нужно", "решить", "."]],
        extraUaTokens: ["план", "документи", "майбутнє"],
        extraRuTokens: ["план", "документы", "будущее"],
        extraEnTokens: ["plan", "documents", "future"],
    },

    [phraseKey("zaplanować", "a1-37")]: {
        sk: "Chcę zaplanować urlop.",
        ua: "Я хочу запланувати відпустку.",
        ru: "Я хочу запланировать отпуск.",
        en: "I want to plan my vacation.",
        uaTokens: ["Я", "хочу", "запланувати", "відпустку", "."],
        ruTokens: ["Я", "хочу", "запланировать", "отпуск", "."],
        enTokens: ["I", "want", "to", "plan", "my", "vacation", "."],
        extraUaTokens: ["документи", "ціль", "роботи"],
        extraRuTokens: ["документы", "цель", "работы"],
        extraEnTokens: ["documents", "goal", "work"],
    },

    [phraseKey("termin", "a1-37")]: {
        sk: "Jaki jest termin spotkania?",
        ua: "Який термін зустрічі?",
        ru: "Какой срок встречи?",
        en: "What is the deadline for the meeting?",
        uaTokens: ["Який", "термін", "зустрічі", "?"],
        ruTokens: ["Какой", "срок", "встречи", "?"],
        enTokens: ["What", "is", "the", "deadline", "for", "the", "meeting", "?"],
        extraUaTokens: ["план", "документи", "сьогодні"],
        extraRuTokens: ["план", "документы", "сегодня"],
        extraEnTokens: ["plan", "documents", "today"],
    },

    [phraseKey("kontynuować", "a1-37")]: {
        sk: "Chcę kontynuować naukę.",
        ua: "Я хочу продовжити навчання.",
        ru: "Я хочу продолжить учёбу.",
        en: "I want to continue studying.",
        uaTokens: ["Я", "хочу", "продовжити", "навчання", "."],
        ruTokens: ["Я", "хочу", "продолжить", "учёбу", "."],
        enTokens: ["I", "want", "to", "continue", "studying", "."],
        extraUaTokens: ["план", "ціль", "майбутнє"],
        extraRuTokens: ["план", "цель", "будущее"],
        extraEnTokens: ["plan", "goal", "future"],
    },

    // =========================
    // LESSON 38 — Ситуації в магазині
    // =========================
    [phraseKey("reklamacja", "a1-38")]: {
        sk: "Chcę złożyć reklamację.",
        ua: "Я хочу подати скаргу.",
        ru: "Я хочу подать рекламацию.",
        en: "I want to make a complaint.",
        uaTokens: ["Я", "хочу", "подати", "скаргу", "."],
        ruTokens: ["Я", "хочу", "подать", "рекламацию", "."],
        enTokens: ["I", "want", "to", "make", "a", "complaint", "."],
        extraUaTokens: ["товар", "чек", "гарантію"],
        extraRuTokens: ["товар", "чек", "гарантию"],
        extraEnTokens: ["product", "receipt", "warranty"],
    },

    [phraseKey("towar", "a1-38")]: {
        sk: "Ten towar jest uszkodzony.",
        ua: "Цей товар пошкоджений.",
        ru: "Этот товар повреждён.",
        en: "This product is damaged.",
        uaTokens: ["Цей", "товар", "пошкоджений", "."],
        ruTokens: ["Этот", "товар", "повреждён", "."],
        enTokens: ["This", "product", "is", "damaged", "."],
        extraUaTokens: ["гарантію", "складі", "чек"],
        extraRuTokens: ["гарантию", "складе", "чек"],
        extraEnTokens: ["warranty", "warehouse", "receipt"],
    },

    [phraseKey("magazyn", "a1-38")]: {
        sk: "Towar jest jeszcze w magazynie.",
        ua: "Товар ще на складі.",
        ru: "Товар ещё на складе.",
        en: "The goods are still in the warehouse.",
        uaTokens: ["Товар", "ще", "на", "складі", "."],
        ruTokens: ["Товар", "ещё", "на", "складе", "."],
        enTokens: ["The", "goods", "are", "still", "in", "the", "warehouse", "."],
        extraUaTokens: ["пошкоджений", "чек", "клієнт"],
        extraRuTokens: ["повреждён", "чек", "клиент"],
        extraEnTokens: ["damaged", "receipt", "customer"],
    },

    [phraseKey("paragon", "a1-38")]: {
        sk: "Proszę pokazać paragon.",
        ua: "Будь ласка, покажіть чек.",
        ru: "Пожалуйста, покажите чек.",
        en: "Please show the receipt.",
        uaTokens: ["Будь", "ласка", ",", "покажіть", "чек", "."],
        ruTokens: ["Пожалуйста", ",", "покажите", "чек", "."],
        enTokens: ["Please", "show", "the", "receipt", "."],
        extraUaTokens: ["товар", "скаргу", "обмін"],
        extraRuTokens: ["товар", "рекламацию", "обмен"],
        extraEnTokens: ["product", "complaint", "exchange"],
    },

    [phraseKey("gwarancja", "a1-38")]: {
        sk: "Ten produkt ma gwarancję.",
        ua: "Цей товар має гарантію.",
        ru: "У этого товара есть гарантия.",
        en: "This product has a warranty.",
        uaTokens: ["Цей", "товар", "має", "гарантію", "."],
        ruTokens: ["У", "этого", "товара", "есть", "гарантия", "."],
        enTokens: ["This", "product", "has", "a", "warranty", "."],
        extraUaTokens: ["чек", "пошкоджений", "обмін"],
        extraRuTokens: ["чек", "повреждён", "обмен"],
        extraEnTokens: ["receipt", "damaged", "exchange"],
    },

    [phraseKey("uszkodzony", "a1-38")]: {
        sk: "Telefon przyszedł uszkodzony.",
        ua: "Телефон прийшов пошкодженим.",
        ru: "Телефон пришёл повреждённым.",
        en: "The phone arrived damaged.",
        uaTokens: ["Телефон", "прийшов", "пошкодженим", "."],
        ruTokens: ["Телефон", "пришёл", "повреждённым", "."],
        enTokens: ["The", "phone", "arrived", "damaged", "."],
        extraUaTokens: ["товар", "чек", "гарантію"],
        extraRuTokens: ["товар", "чек", "гарантию"],
        extraEnTokens: ["product", "receipt", "warranty"],
    },

    [phraseKey("sprzedawca", "a1-38")]: {
        sk: "Sprzedawca był bardzo uprzejmy.",
        ua: "Продавець був дуже ввічливий.",
        ru: "Продавец был очень вежливый.",
        en: "The salesperson was very polite.",
        uaTokens: ["Продавець", "був", "дуже", "ввічливий", "."],
        ruTokens: ["Продавец", "был", "очень", "вежливый", "."],
        enTokens: ["The", "salesperson", "was", "very", "polite", "."],
        extraUaTokens: ["клієнт", "чек", "товар"],
        extraRuTokens: ["клиент", "чек", "товар"],
        extraEnTokens: ["customer", "receipt", "product"],
    },

    [phraseKey("klient", "a1-38")]: {
        sk: "Klient czeka przy kasie.",
        ua: "Клієнт чекає біля каси.",
        ru: "Клиент ждёт у кассы.",
        en: "The customer is waiting at the checkout.",
        uaTokens: ["Клієнт", "чекає", "біля", "каси", "."],
        ruTokens: ["Клиент", "ждёт", "у", "кассы", "."],
        enTokens: ["The", "customer", "is", "waiting", "at", "the", "checkout", "."],
        extraUaTokens: ["продавець", "товар", "чек"],
        extraRuTokens: ["продавец", "товар", "чек"],
        extraEnTokens: ["salesperson", "product", "receipt"],
    },

    [phraseKey("reklamować", "a1-38")]: {
        sk: "Chcę reklamować ten produkt.",
        ua: "Я хочу подати скаргу на цей товар.",
        ru: "Я хочу подать рекламацию на этот товар.",
        en: "I want to make a complaint about this product.",
        uaTokens: ["Я", "хочу", "подати", "скаргу", "на", "цей", "товар", "."],
        ruTokens: ["Я", "хочу", "подать", "рекламацию", "на", "этот", "товар", "."],
        enTokens: ["I", "want", "to", "make", "a", "complaint", "about", "this", "product", "."],
        extraUaTokens: ["гарантію", "чек", "обмін"],
        extraRuTokens: ["гарантию", "чек", "обмен"],
        extraEnTokens: ["warranty", "receipt", "exchange"],
    },

    [phraseKey("wymiana", "a1-38")]: {
        sk: "Czy wymiana jest możliwa?",
        ua: "Чи можливий обмін?",
        ru: "Возможен ли обмен?",
        en: "Is an exchange possible?",
        uaTokens: ["Чи", "можливий", "обмін", "?"],
        ruTokens: ["Возможен", "ли", "обмен", "?"],
        enTokens: ["Is", "an", "exchange", "possible", "?"],
        extraUaTokens: ["товар", "чек", "гарантію"],
        extraRuTokens: ["товар", "чек", "гарантию"],
        extraEnTokens: ["product", "receipt", "warranty"],
    },

    // =========================
    // LESSON 39 — Абстрактні слова
    // =========================
    [phraseKey("życie", "a1-39")]: {
        sk: "Życie bywa trudne.",
        ua: "Життя буває важким.",
        ru: "Жизнь бывает трудной.",
        en: "Life can be difficult.",
        uaTokens: ["Життя", "буває", "важким", "."],
        ruTokens: ["Жизнь", "бывает", "трудной", "."],
        enTokens: ["Life", "can", "be", "difficult", "."],
        extraUaTokens: ["правда", "успіх", "досвід"],
        extraRuTokens: ["правда", "успех", "опыт"],
        extraEnTokens: ["truth", "success", "experience"],
    },

    [phraseKey("czas", "a1-39")]: {
        sk: "Nie mam teraz czasu.",
        ua: "Я зараз не маю часу.",
        ru: "У меня сейчас нет времени.",
        en: "I do not have time now.",
        uaTokens: ["Я", "зараз", "не", "маю", "часу", "."],
        ruTokens: ["У", "меня", "сейчас", "нет", "времени", "."],
        enTokens: ["I", "do", "not", "have", "time", "now", "."],
        extraUaTokens: ["можливість", "досвід", "рішення"],
        extraRuTokens: ["возможность", "опыт", "решение"],
        extraEnTokens: ["possibility", "experience", "decision"],
    },

    [phraseKey("możliwość", "a1-39")]: {
        sk: "Mam jeszcze jedną możliwość.",
        ua: "У мене є ще одна можливість.",
        ru: "У меня есть ещё одна возможность.",
        en: "I still have one more option.",
        uaTokens: ["У", "мене", "є", "ще", "одна", "можливість", "."],
        ruTokens: ["У", "меня", "есть", "ещё", "одна", "возможность", "."],
        enTokens: ["I", "still", "have", "one", "more", "option", "."],
        uaAltAnswers: [["У", "мене", "ще", "є", "одна", "можливість", "."]],
        ruAltAnswers: [["У", "меня", "ещё", "есть", "одна", "возможность", "."]],
        extraUaTokens: ["часу", "причина", "слова"],
        extraRuTokens: ["времени", "причина", "слова"],
        extraEnTokens: ["time", "reason", "word"],
    },

    [phraseKey("powód", "a1-39")]: {
        sk: "Jaki jest powód tej decyzji?",
        ua: "Яка причина цього рішення?",
        ru: "Какова причина этого решения?",
        en: "What is the reason for this decision?",
        uaTokens: ["Яка", "причина", "цього", "рішення", "?"],
        ruTokens: ["Какова", "причина", "этого", "решения", "?"],
        enTokens: ["What", "is", "the", "reason", "for", "this", "decision", "?"],
        extraUaTokens: ["правда", "значення", "успіх"],
        extraRuTokens: ["правда", "значение", "успех"],
        extraEnTokens: ["truth", "meaning", "success"],
    },

    [phraseKey("znaczenie", "a1-39")]: {
        sk: "Nie znam znaczenia tego słowa.",
        ua: "Я не знаю значення цього слова.",
        ru: "Я не знаю значения этого слова.",
        en: "I do not know the meaning of this word.",
        uaTokens: ["Я", "не", "знаю", "значення", "цього", "слова", "."],
        ruTokens: ["Я", "не", "знаю", "значения", "этого", "слова", "."],
        enTokens: ["I", "do", "not", "know", "the", "meaning", "of", "this", "word", "."],
        extraUaTokens: ["правда", "рішення", "досвід"],
        extraRuTokens: ["правда", "решение", "опыт"],
        extraEnTokens: ["truth", "decision", "experience"],
    },

    [phraseKey("prawda", "a1-39")]: {
        sk: "To jest prawda.",
        ua: "Це правда.",
        ru: "Это правда.",
        en: "This is the truth.",
        uaTokens: ["Це", "правда", "."],
        ruTokens: ["Это", "правда", "."],
        enTokens: ["This", "is", "the", "truth", "."],
        extraUaTokens: ["брехня", "успіх", "досвід"],
        extraRuTokens: ["ложь", "успех", "опыт"],
        extraEnTokens: ["lie", "success", "experience"],
    },

    [phraseKey("kłamstwo", "a1-39")]: {
        sk: "To było kłamstwo.",
        ua: "Це була брехня.",
        ru: "Это была ложь.",
        en: "It was a lie.",
        uaTokens: ["Це", "була", "брехня", "."],
        ruTokens: ["Это", "была", "ложь", "."],
        enTokens: ["It", "was", "a", "lie", "."],
        extraUaTokens: ["правда", "рішення", "успіх"],
        extraRuTokens: ["правда", "решение", "успех"],
        extraEnTokens: ["truth", "decision", "success"],
    },

    [phraseKey("sukces", "a1-39")]: {
        sk: "To był duży sukces.",
        ua: "Це був великий успіх.",
        ru: "Это был большой успех.",
        en: "It was a big success.",
        uaTokens: ["Це", "був", "великий", "успіх", "."],
        ruTokens: ["Это", "был", "большой", "успех", "."],
        enTokens: ["It", "was", "a", "big", "success", "."],
        extraUaTokens: ["брехня", "правда", "досвід"],
        extraRuTokens: ["ложь", "правда", "опыт"],
        extraEnTokens: ["lie", "truth", "experience"],
    },

    [phraseKey("niepowodzenie", "a1-39")]: {
        sk: "To niepowodzenie dużo mnie nauczyło.",
        ua: "Ця невдача багато мене навчила.",
        ru: "Эта неудача многому меня научила.",
        en: "This failure taught me a lot.",
        uaTokens: ["Ця", "невдача", "багато", "мене", "навчила", "."],
        ruTokens: ["Эта", "неудача", "многому", "меня", "научила", "."],
        enTokens: ["This", "failure", "taught", "me", "a", "lot", "."],
        extraUaTokens: ["успіх", "досвід", "правда"],
        extraRuTokens: ["успех", "опыт", "правда"],
        extraEnTokens: ["success", "experience", "truth"],
    },

    [phraseKey("doświadczenie", "a1-39")]: {
        sk: "Mam już duże doświadczenie.",
        ua: "У мене вже великий досвід.",
        ru: "У меня уже большой опыт.",
        en: "I already have a lot of experience.",
        uaTokens: ["У", "мене", "вже", "великий", "досвід", "."],
        ruTokens: ["У", "меня", "уже", "большой", "опыт", "."],
        enTokens: ["I", "already", "have", "a", "lot", "of", "experience", "."],
        uaAltAnswers: [["У", "мене", "великий", "досвід", "вже", "."]],
        extraUaTokens: ["успіх", "можливість", "часу"],
        extraRuTokens: ["успех", "возможность", "времени"],
        extraEnTokens: ["success", "possibility", "time"],
    },

    // =========================
    // LESSON 40 — Повторення A1
    // =========================
    [phraseKey("uczyć się", "a1-40")]: {
        sk: "Chcę uczyć się polskiego.",
        ua: "Я хочу вчити польську.",
        ru: "Я хочу учить польский.",
        en: "I want to study Polish.",
        uaTokens: ["Я", "хочу", "вчити", "польську", "."],
        ruTokens: ["Я", "хочу", "учить", "польский", "."],
        enTokens: ["I", "want", "to", "study", "Polish", "."],
        extraUaTokens: ["подорожувати", "повідомлення", "роботу"],
        extraRuTokens: ["путешествовать", "сообщения", "работу"],
        extraEnTokens: ["travel", "messages", "job"],
    },

    [phraseKey("podróżować", "a1-40")]: {
        sk: "Lubię podróżować po Europie.",
        ua: "Я люблю подорожувати Європою.",
        ru: "Я люблю путешествовать по Европе.",
        en: "I like traveling around Europe.",
        uaTokens: ["Я", "люблю", "подорожувати", "Європою", "."],
        ruTokens: ["Я", "люблю", "путешествовать", "по", "Европе", "."],
        enTokens: ["I", "like", "traveling", "around", "Europe", "."],
        extraUaTokens: ["польську", "роботу", "сумку"],
        extraRuTokens: ["польский", "работу", "сумку"],
        extraEnTokens: ["Polish", "job", "bag"],
    },

    [phraseKey("pomóc", "a1-40")]: {
        sk: "Chcę ci pomóc.",
        ua: "Я хочу тобі допомогти.",
        ru: "Я хочу помочь тебе.",
        en: "I want to help you.",
        uaTokens: ["Я", "хочу", "тобі", "допомогти", "."],
        ruTokens: ["Я", "хочу", "помочь", "тебе", "."],
        enTokens: ["I", "want", "to", "help", "you", "."],
        extraUaTokens: ["показати", "сумку", "повідомлення"],
        extraRuTokens: ["показать", "сумку", "сообщения"],
        extraEnTokens: ["show", "bag", "messages"],
    },

    [phraseKey("pisać", "a1-40")]: {
        sk: "Lubię pisać wiadomości.",
        ua: "Я люблю писати повідомлення.",
        ru: "Я люблю писать сообщения.",
        en: "I like writing messages.",
        uaTokens: ["Я", "люблю", "писати", "повідомлення", "."],
        ruTokens: ["Я", "люблю", "писать", "сообщения", "."],
        enTokens: ["I", "like", "writing", "messages", "."],
        extraUaTokens: ["показати", "роботу", "Європою"],
        extraRuTokens: ["показать", "работу", "Европе"],
        extraEnTokens: ["show", "job", "Europe"],
    },

    [phraseKey("wrócić", "a1-40")]: {
        sk: "Chcę wrócić do domu.",
        ua: "Я хочу повернутися додому.",
        ru: "Я хочу вернуться домой.",
        en: "I want to return home.",
        uaTokens: ["Я", "хочу", "повернутися", "додому", "."],
        ruTokens: ["Я", "хочу", "вернуться", "домой", "."],
        enTokens: ["I", "want", "to", "return", "home", "."],
        extraUaTokens: ["залишитися", "тут", "довше"],
        extraRuTokens: ["остаться", "здесь", "дольше"],
        extraEnTokens: ["stay", "here", "longer"],
    },

    [phraseKey("zostać", "a1-40")]: {
        sk: "Chcę zostać tutaj dłużej.",
        ua: "Я хочу залишитися тут довше.",
        ru: "Я хочу остаться здесь дольше.",
        en: "I want to stay here longer.",
        uaTokens: ["Я", "хочу", "залишитися", "тут", "довше", "."],
        ruTokens: ["Я", "хочу", "остаться", "здесь", "дольше", "."],
        enTokens: ["I", "want", "to", "stay", "here", "longer", "."],
        extraUaTokens: ["додому", "роботу", "показати"],
        extraRuTokens: ["домой", "работу", "показать"],
        extraEnTokens: ["home", "job", "show"],
    },

    [phraseKey("zmienić", "a1-40")]: {
        sk: "Chcę zmienić pracę.",
        ua: "Я хочу змінити роботу.",
        ru: "Я хочу изменить работу.",
        en: "I want to change my job.",
        uaTokens: ["Я", "хочу", "змінити", "роботу", "."],
        ruTokens: ["Я", "хочу", "изменить", "работу", "."],
        enTokens: ["I", "want", "to", "change", "my", "job", "."],
        extraUaTokens: ["повідомлення", "додому", "навчання"],
        extraRuTokens: ["сообщения", "домой", "учёбу"],
        extraEnTokens: ["messages", "home", "studying"],
    },

    [phraseKey("pokazać", "a1-40")]: {
        sk: "Mogę ci to pokazać.",
        ua: "Я можу тобі це показати.",
        ru: "Я могу тебе это показать.",
        en: "I can show it to you.",
        uaTokens: ["Я", "можу", "тобі", "це", "показати", "."],
        ruTokens: ["Я", "могу", "тебе", "это", "показать", "."],
        enTokens: ["I", "can", "show", "it", "to", "you", "."],
        uaAltAnswers: [["Я", "можу", "це", "тобі", "показати", "."]],
        ruAltAnswers: [["Я", "могу", "это", "тебе", "показать", "."]],
        extraUaTokens: ["допомогти", "сумку", "роботу"],
        extraRuTokens: ["помочь", "сумку", "работу"],
        extraEnTokens: ["help", "bag", "job"],
    },

    [phraseKey("nieść", "a1-40")]: {
        sk: "Pomogę ci nieść torbę.",
        ua: "Я допоможу тобі нести сумку.",
        ru: "Я помогу тебе нести сумку.",
        en: "I will help you carry the bag.",
        uaTokens: ["Я", "допоможу", "тобі", "нести", "сумку", "."],
        ruTokens: ["Я", "помогу", "тебе", "нести", "сумку", "."],
        enTokens: ["I", "will", "help", "you", "carry", "the", "bag", "."],
        extraUaTokens: ["показати", "вікна", "роботу"],
        extraRuTokens: ["показать", "окна", "работу"],
        extraEnTokens: ["show", "window", "job"],
    },

    [phraseKey("siedzieć", "a1-40")]: {
        sk: "Lubię siedzieć przy oknie.",
        ua: "Я люблю сидіти біля вікна.",
        ru: "Я люблю сидеть у окна.",
        en: "I like sitting by the window.",
        uaTokens: ["Я", "люблю", "сидіти", "біля", "вікна", "."],
        ruTokens: ["Я", "люблю", "сидеть", "у", "окна", "."],
        enTokens: ["I", "like", "sitting", "by", "the", "window", "."],
        extraUaTokens: ["сумку", "повідомлення", "додому"],
        extraRuTokens: ["сумку", "сообщения", "домой"],
        extraEnTokens: ["bag", "messages", "home"],
    },
};