import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A1_BUILD_UA_SENTENCES_2: BuildUaSentenceDict = {
  // =========================
  // LESSON 6 — Doprava
  // =========================
  [phraseKey("cestovný poriadok", "a1-6")]: {
    sk: "Pozriem si cestovný poriadok.",
    ua: "Я подивлюся розклад.",
    ru: "Я посмотрю расписание.",
    en: "I will check the timetable.",
    uaTokens: ["Я", "подивлюся", "розклад", "."],
    ruTokens: ["Я", "посмотрю", "расписание", "."],
    enTokens: ["I", "will", "check", "the", "timetable", "."],
    extraUaTokens: ["автобус", "платформа", "зупинці"],
    extraRuTokens: ["автобус", "платформа", "остановке"],
    extraEnTokens: ["bus", "platform", "stop"],
  },

  [phraseKey("prestup", "a1-6")]: {
    sk: "Tu je prestup na autobus.",
    ua: "Тут пересадка на автобус.",
    ru: "Тут пересадка на автобус.",
    en: "Here is the transfer to the bus.",
    uaTokens: ["Тут", "пересадка", "на", "автобус", "."],
    ruTokens: ["Тут", "пересадка", "на", "автобус", "."],
    enTokens: ["Here", "is", "the", "transfer", "to", "the", "bus", "."],
    extraUaTokens: ["розклад", "платформа", "квиток"],
    extraRuTokens: ["расписание", "платформа", "билет"],
    extraEnTokens: ["timetable", "platform", "ticket"],
  },

  [phraseKey("nástupište", "a1-6")]: {
    sk: "Ktoré je nástupište číslo tri?",
    ua: "Де платформа номер три?",
    ru: "Где платформа номер три?",
    en: "Where is platform number three?",
    uaTokens: ["Де", "платформа", "номер", "три", "?"],
    ruTokens: ["Где", "платформа", "номер", "три", "?"],
    enTokens: ["Where", "is", "platform", "number", "three", "?"],
    extraUaTokens: ["автобус", "квиток", "відправлення"],
    extraRuTokens: ["автобус", "билет", "отправление"],
    extraEnTokens: ["bus", "ticket", "departure"],
  },

  [phraseKey("meškať", "a1-6")]: {
    sk: "Vlak dnes mešká.",
    ua: "Потяг сьогодні запізнюється.",
    ru: "Поезд сегодня опаздывает.",
    en: "The train is late today.",
    uaTokens: ["Потяг", "сьогодні", "запізнюється", "."],
    ruTokens: ["Поезд", "сегодня", "опаздывает", "."],
    enTokens: ["The", "train", "is", "late", "today", "."],
    extraUaTokens: ["відправлення", "прибуття", "квиток"],
    extraRuTokens: ["отправление", "прибытие", "билет"],
    extraEnTokens: ["departure", "arrival", "ticket"],
  },

  [phraseKey("odchod", "a1-6")]: {
    sk: "Odchod je o desať minút.",
    ua: "Відправлення за десять хвилин.",
    ru: "Отправление через десять минут.",
    en: "Departure is in ten minutes.",
    uaTokens: ["Відправлення", "за", "десять", "хвилин", "."],
    ruTokens: ["Отправление", "через", "десять", "минут", "."],
    enTokens: ["Departure", "is", "in", "ten", "minutes", "."],
    extraUaTokens: ["прибуття", "потяг", "платформа"],
    extraRuTokens: ["прибытие", "поезд", "платформа"],
    extraEnTokens: ["arrival", "train", "platform"],
  },

  [phraseKey("príchod", "a1-6")]: {
    sk: "Príchod je o piatej.",
    ua: "Прибуття о п’ятій.",
    ru: "Прибытие в пять.",
    en: "Arrival is at five.",
    uaTokens: ["Прибуття", "о", "п’ятій", "."],
    ruTokens: ["Прибытие", "в", "пять", "."],
    enTokens: ["Arrival", "is", "at", "five", "."],
    extraUaTokens: ["відправлення", "квиток", "автобус"],
    extraRuTokens: ["отправление", "билет", "автобус"],
    extraEnTokens: ["departure", "ticket", "bus"],
  },

  [phraseKey("lístok", "a1-6")]: {
    sk: "Potrebujem lístok do Košíc.",
    ua: "Мені потрібен квиток до Кошиць.",
    ru: "Мне нужен билет до Кошице.",
    en: "I need a ticket to Košice.",
    uaTokens: ["Мені", "потрібен", "квиток", "до", "Кошиць", "."],
    ruTokens: ["Мне", "нужен", "билет", "до", "Кошице", "."],
    enTokens: ["I", "need", "a", "ticket", "to", "Košice", "."],
    extraUaTokens: ["платформа", "відправлення", "зупинці"],
    extraRuTokens: ["платформа", "отправление", "остановке"],
    extraEnTokens: ["platform", "departure", "stop"],
  },

  [phraseKey("kúpiť", "a1-6")]: {
    sk: "Kde si môžem kúpiť lístok?",
    ua: "Де я можу купити квиток?",
    ru: "Где я могу купить билет?",
    en: "Where can I buy a ticket?",
    uaTokens: ["Де", "я", "можу", "купити", "квиток", "?"],
    ruTokens: ["Где", "я", "могу", "купить", "билет", "?"],
    enTokens: ["Where", "can", "I", "buy", "a", "ticket", "?"],
    extraUaTokens: ["Кошиць", "платформа", "потяг"],
    extraRuTokens: ["Кошице", "платформа", "поезд"],
    extraEnTokens: ["Košice", "platform", "train"],
  },

  [phraseKey("vystúpiť", "a1-6")]: {
    sk: "Musím vystúpiť na ďalšej zastávke.",
    ua: "Мені треба вийти на наступній зупинці.",
    ru: "Мне нужно выйти на следующей остановке.",
    en: "I need to get off at the next stop.",
    uaTokens: ["Мені", "треба", "вийти", "на", "наступній", "зупинці", "."],
    ruTokens: ["Мне", "нужно", "выйти", "на", "следующей", "остановке", "."],
    enTokens: ["I", "need", "to", "get", "off", "at", "the", "next", "stop", "."],
    extraUaTokens: ["трамвай", "квиток", "автобус"],
    extraRuTokens: ["трамвай", "билет", "автобус"],
    extraEnTokens: ["tram", "ticket", "bus"],
  },

  [phraseKey("nastúpiť", "a1-6")]: {
    sk: "Nastúpime do električky.",
    ua: "Сядемо в трамвай.",
    ru: "Сядем в трамвай.",
    en: "We will get on the tram.",
    uaTokens: ["Сядемо", "в", "трамвай", "."],
    ruTokens: ["Сядем", "в", "трамвай", "."],
    enTokens: ["We", "will", "get", "on", "the", "tram", "."],
    extraUaTokens: ["зупинці", "вийти", "квиток"],
    extraRuTokens: ["остановке", "выйти", "билет"],
    extraEnTokens: ["stop", "get", "off"],
  },

  // =========================
  // LESSON 7 — Domáce činnosti
  // =========================
  [phraseKey("variť", "a1-7")]: {
    sk: "Dnes budem variť večeru.",
    ua: "Сьогодні я буду готувати вечерю.",
    ru: "Сегодня я буду готовить ужин.",
    en: "Today I will cook dinner.",
    uaTokens: ["Сьогодні", "я", "буду", "готувати", "вечерю", "."],
    ruTokens: ["Сегодня", "я", "буду", "готовить", "ужин", "."],
    enTokens: ["Today", "I", "will", "cook", "dinner", "."],
    extraUaTokens: ["посуд", "одяг", "вікно"],
    extraRuTokens: ["посуду", "одежду", "окно"],
    extraEnTokens: ["dishes", "clothes", "window"],
  },

  [phraseKey("upratovať", "a1-7")]: {
    sk: "V sobotu upratujem byt.",
    ua: "У суботу прибираю квартиру.",
    ru: "В субботу убираю квартиру.",
    en: "On Saturday I clean the apartment.",
    uaTokens: ["У", "суботу", "прибираю", "квартиру", "."],
    ruTokens: ["В", "субботу", "убираю", "квартиру", "."],
    enTokens: ["On", "Saturday", "I", "clean", "the", "apartment", "."],
    extraUaTokens: ["готувати", "посуд", "ключі"],
    extraRuTokens: ["готовить", "посуду", "ключи"],
    extraEnTokens: ["cook", "dishes", "keys"],
  },

  [phraseKey("umývať", "a1-7")]: {
    sk: "Umývam riad.",
    ua: "Я мию посуд.",
    ru: "Я мою посуду.",
    en: "I wash the dishes.",
    uaTokens: ["Я", "мию", "посуд", "."],
    ruTokens: ["Я", "мою", "посуду", "."],
    enTokens: ["I", "wash", "the", "dishes", "."],
    extraUaTokens: ["квартиру", "одяг", "світло"],
    extraRuTokens: ["квартиру", "одежду", "свет"],
    extraEnTokens: ["apartment", "clothes", "light"],
  },

  [phraseKey("prať", "a1-7")]: {
    sk: "Musím oprať oblečenie.",
    ua: "Мені треба попрати одяг.",
    ru: "Мне нужно постирать одежду.",
    en: "I need to wash the clothes.",
    uaTokens: ["Мені", "треба", "попрати", "одяг", "."],
    ruTokens: ["Мне", "нужно", "постирать", "одежду", "."],
    enTokens: ["I", "need", "to", "wash", "the", "clothes", "."],
    extraUaTokens: ["посуд", "сорочки", "вікно"],
    extraRuTokens: ["посуду", "рубашки", "окно"],
    extraEnTokens: ["dishes", "shirts", "window"],
  },

  [phraseKey("žehliť", "a1-7")]: {
    sk: "Neznášam žehliť košele.",
    ua: "Я не люблю прасувати сорочки.",
    ru: "Я не люблю гладить рубашки.",
    en: "I do not like ironing shirts.",
    uaTokens: ["Я", "не", "люблю", "прасувати", "сорочки", "."],
    ruTokens: ["Я", "не", "люблю", "гладить", "рубашки", "."],
    enTokens: ["I", "do", "not", "like", "ironing", "shirts", "."],
    extraUaTokens: ["одяг", "вікно", "ключі"],
    extraRuTokens: ["одежду", "окно", "ключи"],
    extraEnTokens: ["clothes", "window", "keys"],
  },

  [phraseKey("otvoriť", "a1-7")]: {
    sk: "Otvor okno, prosím.",
    ua: "Відкрий вікно, будь ласка.",
    ru: "Открой окно, пожалуйста.",
    en: "Open the window, please.",
    uaTokens: ["Відкрий", "вікно", ",", "будь", "ласка", "."],
    ruTokens: ["Открой", "окно", ",", "пожалуйста", "."],
    enTokens: ["Open", "the", "window", ",", "please", "."],
    extraUaTokens: ["двері", "світло", "телевізор"],
    extraRuTokens: ["дверь", "свет", "телевизор"],
    extraEnTokens: ["door", "light", "television"],
  },

  [phraseKey("zatvoriť", "a1-7")]: {
    sk: "Zatvor dvere.",
    ua: "Закрий двері.",
    ru: "Закрой дверь.",
    en: "Close the door.",
    uaTokens: ["Закрий", "двері", "."],
    ruTokens: ["Закрой", "дверь", "."],
    enTokens: ["Close", "the", "door", "."],
    extraUaTokens: ["вікно", "світло", "ключі"],
    extraRuTokens: ["окно", "свет", "ключи"],
    extraEnTokens: ["window", "light", "keys"],
  },

  [phraseKey("zapnúť", "a1-7")]: {
    sk: "Zapni svetlo.",
    ua: "Увімкни світло.",
    ru: "Включи свет.",
    en: "Turn on the light.",
    uaTokens: ["Увімкни", "світло", "."],
    ruTokens: ["Включи", "свет", "."],
    enTokens: ["Turn", "on", "the", "light", "."],
    extraUaTokens: ["телевізор", "двері", "вікно"],
    extraRuTokens: ["телевизор", "дверь", "окно"],
    extraEnTokens: ["television", "door", "window"],
  },

  [phraseKey("vypnúť", "a1-7")]: {
    sk: "Vypni televízor.",
    ua: "Вимкни телевізор.",
    ru: "Выключи телевизор.",
    en: "Turn off the television.",
    uaTokens: ["Вимкни", "телевізор", "."],
    ruTokens: ["Выключи", "телевизор", "."],
    enTokens: ["Turn", "off", "the", "television", "."],
    extraUaTokens: ["світло", "вікно", "ключі"],
    extraRuTokens: ["свет", "окно", "ключи"],
    extraEnTokens: ["light", "window", "keys"],
  },

  [phraseKey("hľadať", "a1-7")]: {
    sk: "Hľadám kľúče.",
    ua: "Я шукаю ключі.",
    ru: "Я ищу ключи.",
    en: "I am looking for the keys.",
    uaTokens: ["Я", "шукаю", "ключі", "."],
    ruTokens: ["Я", "ищу", "ключи", "."],
    enTokens: ["I", "am", "looking", "for", "the", "keys", "."],
    extraUaTokens: ["двері", "вікно", "телевізор"],
    extraRuTokens: ["дверь", "окно", "телевизор"],
    extraEnTokens: ["door", "window", "television"],
  },

  // =========================
  // LESSON 8 — Práca (procesy)
  // =========================
  [phraseKey("pracovisko", "a1-8")]: {
    sk: "Som už na pracovisku.",
    ua: "Я вже на робочому місці.",
    ru: "Я уже на рабочем месте.",
    en: "I am already at the workplace.",
    uaTokens: ["Я", "вже", "на", "робочому", "місці", "."],
    ruTokens: ["Я", "уже", "на", "рабочем", "месте", "."],
    enTokens: ["I", "am", "already", "at", "the", "workplace", "."],
    extraUaTokens: ["зміна", "нарада", "завдання"],
    extraRuTokens: ["смена", "совещание", "задание"],
    extraEnTokens: ["shift", "meeting", "task"],
  },

  [phraseKey("zmena", "a1-8")]: {
    sk: "Mám rannú zmenu.",
    ua: "У мене ранкова зміна.",
    ru: "У меня утренняя смена.",
    en: "I have a morning shift.",
    uaTokens: ["У", "мене", "ранкова", "зміна", "."],
    ruTokens: ["У", "меня", "утренняя", "смена", "."],
    enTokens: ["I", "have", "a", "morning", "shift", "."],
    extraUaTokens: ["робочому", "місці", "нарада"],
    extraRuTokens: ["рабочем", "месте", "совещание"],
    extraEnTokens: ["workplace", "meeting", "task"],
  },

  [phraseKey("nadčas", "a1-8")]: {
    sk: "Dnes robím nadčas.",
    ua: "Сьогодні працюю понаднормово.",
    ru: "Сегодня работаю сверхурочно.",
    en: "Today I am working overtime.",
    uaTokens: ["Сьогодні", "працюю", "понаднормово", "."],
    ruTokens: ["Сегодня", "работаю", "сверхурочно", "."],
    enTokens: ["Today", "I", "am", "working", "overtime", "."],
    extraUaTokens: ["зміна", "завдання", "нарада"],
    extraRuTokens: ["смена", "задание", "совещание"],
    extraEnTokens: ["shift", "task", "meeting"],
  },

  [phraseKey("porada", "a1-8")]: {
    sk: "O deviatej máme poradu.",
    ua: "О дев’ятій у нас нарада.",
    ru: "В девять у нас совещание.",
    en: "We have a meeting at nine.",
    uaTokens: ["О", "дев’ятій", "у", "нас", "нарада", "."],
    ruTokens: ["В", "девять", "у", "нас", "совещание", "."],
    enTokens: ["We", "have", "a", "meeting", "at", "nine", "."],
    extraUaTokens: ["зміна", "завдання", "готово"],
    extraRuTokens: ["смена", "задание", "готово"],
    extraEnTokens: ["shift", "task", "done"],
  },

  [phraseKey("úloha", "a1-8")]: {
    sk: "Toto je moja úloha.",
    ua: "Це моє завдання.",
    ru: "Это моё задание.",
    en: "This is my task.",
    uaTokens: ["Це", "моє", "завдання", "."],
    ruTokens: ["Это", "моё", "задание", "."],
    enTokens: ["This", "is", "my", "task", "."],
    extraUaTokens: ["нарада", "перевірити", "виправити"],
    extraRuTokens: ["совещание", "проверить", "исправить"],
    extraEnTokens: ["meeting", "check", "fix"],
  },

  [phraseKey("hotovo", "a1-8")]: {
    sk: "Hotovo, môžeme ísť.",
    ua: "Готово, можемо йти.",
    ru: "Готово, можем идти.",
    en: "Done, we can go.",
    uaTokens: ["Готово", ",", "можемо", "йти", "."],
    ruTokens: ["Готово", ",", "можем", "идти", "."],
    enTokens: ["Done", ",", "we", "can", "go", "."],
    extraUaTokens: ["почати", "закінчимо", "завдання"],
    extraRuTokens: ["начать", "закончим", "задание"],
    extraEnTokens: ["start", "finish", "task"],
  },

  [phraseKey("skontrolovať", "a1-8")]: {
    sk: "Musím to skontrolovať.",
    ua: "Мені треба це перевірити.",
    ru: "Мне нужно это проверить.",
    en: "I need to check it.",
    uaTokens: ["Мені", "треба", "це", "перевірити", "."],
    ruTokens: ["Мне", "нужно", "это", "проверить", "."],
    enTokens: ["I", "need", "to", "check", "it", "."],
    extraUaTokens: ["виправити", "завдання", "готово"],
    extraRuTokens: ["исправить", "задание", "готово"],
    extraEnTokens: ["fix", "task", "done"],
  },

  [phraseKey("opraviť", "a1-8")]: {
    sk: "Skúsim to opraviť.",
    ua: "Спробую це виправити.",
    ru: "Попробую это исправить.",
    en: "I will try to fix it.",
    uaTokens: ["Спробую", "це", "виправити", "."],
    ruTokens: ["Попробую", "это", "исправить", "."],
    enTokens: ["I", "will", "try", "to", "fix", "it", "."],
    extraUaTokens: ["перевірити", "почати", "завдання"],
    extraRuTokens: ["проверить", "начать", "задание"],
    extraEnTokens: ["check", "start", "task"],
  },

  [phraseKey("začať", "a1-8")]: {
    sk: "Môžeme začať?",
    ua: "Можемо почати?",
    ru: "Можем начать?",
    en: "Can we start?",
    uaTokens: ["Можемо", "почати", "?"],
    ruTokens: ["Можем", "начать", "?"],
    enTokens: ["Can", "we", "start", "?"],
    extraUaTokens: ["готово", "закінчимо", "нарада"],
    extraRuTokens: ["готово", "закончим", "совещание"],
    extraEnTokens: ["done", "finish", "meeting"],
  },

  [phraseKey("skončiť", "a1-8")]: {
    sk: "Kedy skončíme?",
    ua: "Коли ми закінчимо?",
    ru: "Когда мы закончим?",
    en: "When will we finish?",
    uaTokens: ["Коли", "ми", "закінчимо", "?"],
    ruTokens: ["Когда", "мы", "закончим", "?"],
    enTokens: ["When", "will", "we", "finish", "?"],
    extraUaTokens: ["почати", "готово", "зміна"],
    extraRuTokens: ["начать", "готово", "смена"],
    extraEnTokens: ["start", "done", "shift"],
  },

  // =========================
  // LESSON 9 — Emócie a stavy
  // =========================
  [phraseKey("unavený", "a1-9")]: {
    sk: "Som unavený.",
    ua: "Я втомлений.",
    ru: "Я устал.",
    en: "I am tired.",
    uaTokens: ["Я", "втомлений", "."],
    ruTokens: ["Я", "устал", "."],
    enTokens: ["I", "am", "tired", "."],
    extraUaTokens: ["щасливий", "спокійно", "темряви"],
    extraRuTokens: ["счастлив", "спокойно", "темноты"],
    extraEnTokens: ["happy", "calm", "darkness"],
  },

  [phraseKey("šťastný", "a1-9")]: {
    sk: "Som veľmi šťastný.",
    ua: "Я дуже щасливий.",
    ru: "Я очень счастлив.",
    en: "I am very happy.",
    uaTokens: ["Я", "дуже", "щасливий", "."],
    ruTokens: ["Я", "очень", "счастлив", "."],
    enTokens: ["I", "am", "very", "happy", "."],
    extraUaTokens: ["втомлений", "злий", "солодкого"],
    extraRuTokens: ["устал", "злой", "сладкого"],
    extraEnTokens: ["tired", "angry", "sweet"],
  },

  [phraseKey("smutný", "a1-9")]: {
    sk: "Dnes som smutný.",
    ua: "Сьогодні мені сумно.",
    ru: "Сегодня мне грустно.",
    en: "I am sad today.",
    uaTokens: ["Сьогодні", "мені", "сумно", "."],
    ruTokens: ["Сегодня", "мне", "грустно", "."],
    enTokens: ["I", "am", "sad", "today", "."],
    extraUaTokens: ["щасливий", "злий", "темряви"],
    extraRuTokens: ["счастлив", "злой", "темноты"],
    extraEnTokens: ["happy", "angry", "darkness"],
  },

  [phraseKey("nahnevaný", "a1-9")]: {
    sk: "Som nahnevaný.",
    ua: "Я злий.",
    ru: "Я злой.",
    en: "I am angry.",
    uaTokens: ["Я", "злий", "."],
    ruTokens: ["Я", "злой", "."],
    enTokens: ["I", "am", "angry", "."],
    extraUaTokens: ["сумно", "щасливий", "спокійно"],
    extraRuTokens: ["грустно", "счастлив", "спокойно"],
    extraEnTokens: ["sad", "happy", "calm"],
  },

  [phraseKey("nervózny", "a1-9")]: {
    sk: "Som trochu nervózny.",
    ua: "Я трохи нервовий.",
    ru: "Я немного нервничаю.",
    en: "I am a little nervous.",
    uaTokens: ["Я", "трохи", "нервовий", "."],
    ruTokens: ["Я", "немного", "нервничаю", "."],
    enTokens: ["I", "am", "a", "little", "nervous", "."],
    extraUaTokens: ["спокійно", "злий", "солодкого"],
    extraRuTokens: ["спокойно", "злой", "сладкого"],
    extraEnTokens: ["calm", "angry", "sweet"],
  },

  [phraseKey("pokojný", "a1-9")]: {
    sk: "Cítim sa pokojný.",
    ua: "Я почуваюся спокійно.",
    ru: "Я чувствую себя спокойно.",
    en: "I feel calm.",
    uaTokens: ["Я", "почуваюся", "спокійно", "."],
    ruTokens: ["Я", "чувствую", "себя", "спокойно", "."],
    enTokens: ["I", "feel", "calm", "."],
    extraUaTokens: ["нервовий", "втомлений", "радістю"],
    extraRuTokens: ["нервничаю", "устал", "радостью"],
    extraEnTokens: ["nervous", "tired", "joy"],
  },

  [phraseKey("prekvapený", "a1-9")]: {
    sk: "Som prekvapený.",
    ua: "Я здивований.",
    ru: "Я удивлён.",
    en: "I am surprised.",
    uaTokens: ["Я", "здивований", "."],
    ruTokens: ["Я", "удивлён", "."],
    enTokens: ["I", "am", "surprised", "."],
    extraUaTokens: ["щасливий", "сумно", "спокійно"],
    extraRuTokens: ["счастлив", "грустно", "спокойно"],
    extraEnTokens: ["happy", "sad", "calm"],
  },

  [phraseKey("báť sa", "a1-9")]: {
    sk: "Bojím sa tmy.",
    ua: "Я боюся темряви.",
    ru: "Я боюсь темноты.",
    en: "I am afraid of the dark.",
    uaTokens: ["Я", "боюся", "темряви", "."],
    ruTokens: ["Я", "боюсь", "темноты", "."],
    enTokens: ["I", "am", "afraid", "of", "the", "dark", "."],
    extraUaTokens: ["здивований", "втомлений", "радістю"],
    extraRuTokens: ["удивлён", "устал", "радостью"],
    extraEnTokens: ["surprised", "tired", "joy"],
  },

  [phraseKey("tešiť sa", "a1-9")]: {
    sk: "Teším sa na víkend.",
    ua: "Я чекаю вихідних із радістю.",
    ru: "Я жду выходных с радостью.",
    en: "I am looking forward to the weekend.",
    uaTokens: ["Я", "чекаю", "вихідних", "із", "радістю", "."],
    ruTokens: ["Я", "жду", "выходных", "с", "радостью", "."],
    enTokens: ["I", "am", "looking", "forward", "to", "the", "weekend", "."],
    extraUaTokens: ["солодкого", "щасливий", "сумно"],
    extraRuTokens: ["сладкого", "счастлив", "грустно"],
    extraEnTokens: ["sweet", "happy", "sad"],
  },

  [phraseKey("mať chuť", "a1-9")]: {
    sk: "Mám chuť na niečo sladké.",
    ua: "Мені хочеться чогось солодкого.",
    ru: "Мне хочется чего-то сладкого.",
    en: "I want something sweet.",
    uaTokens: ["Мені", "хочеться", "чогось", "солодкого", "."],
    ruTokens: ["Мне", "хочется", "чего-то", "сладкого", "."],
    enTokens: ["I", "want", "something", "sweet", "."],
    extraUaTokens: ["вихідних", "радістю", "щасливий"],
    extraRuTokens: ["выходных", "радостью", "счастлив"],
    extraEnTokens: ["weekend", "joy", "happy"],
  },

  // =========================
  // LESSON 10 — Otázky
  // =========================
  [phraseKey("ktorý", "a1-10")]: {
    sk: "Ktorý autobus ide do centra?",
    ua: "Який автобус їде в центр?",
    ru: "Какой автобус едет в центр?",
    en: "Which bus goes to the center?",
    uaTokens: ["Який", "автобус", "їде", "в", "центр", "?"],
    ruTokens: ["Какой", "автобус", "едет", "в", "центр", "?"],
    enTokens: ["Which", "bus", "goes", "to", "the", "center", "?"],
    extraUaTokens: ["проблема", "телефон", "банкомат"],
    extraRuTokens: ["проблема", "телефон", "банкомат"],
    extraEnTokens: ["problem", "phone", "ATM"],
  },

  [phraseKey("aký", "a1-10")]: {
    sk: "Aký je to problém?",
    ua: "Яка це проблема?",
    ru: "Какая это проблема?",
    en: "What kind of problem is it?",
    uaTokens: ["Яка", "це", "проблема", "?"],
    ruTokens: ["Какая", "это", "проблема", "?"],
    enTokens: ["What", "kind", "of", "problem", "is", "it", "?"],
    extraUaTokens: ["автобус", "центр", "телефон"],
    extraRuTokens: ["автобус", "центр", "телефон"],
    extraEnTokens: ["bus", "center", "phone"],
  },

  [phraseKey("čí", "a1-10")]: {
    sk: "Čí je tento telefón?",
    ua: "Чий це телефон?",
    ru: "Чей это телефон?",
    en: "Whose phone is this?",
    uaTokens: ["Чий", "це", "телефон", "?"],
    ruTokens: ["Чей", "это", "телефон", "?"],
    enTokens: ["Whose", "phone", "is", "this", "?"],
    extraUaTokens: ["банкомат", "проблема", "центр"],
    extraRuTokens: ["банкомат", "проблема", "центр"],
    extraEnTokens: ["ATM", "problem", "center"],
  },

  [phraseKey("kde je", "a1-10")]: {
    sk: "Kde je najbližší bankomat?",
    ua: "Де найближчий банкомат?",
    ru: "Где ближайший банкомат?",
    en: "Where is the nearest ATM?",
    uaTokens: ["Де", "найближчий", "банкомат", "?"],
    ruTokens: ["Где", "ближайший", "банкомат", "?"],
    enTokens: ["Where", "is", "the", "nearest", "ATM", "?"],
    extraUaTokens: ["телефон", "автобус", "центр"],
    extraRuTokens: ["телефон", "автобус", "центр"],
    extraEnTokens: ["phone", "bus", "center"],
  },

  [phraseKey("koľko to stojí", "a1-10")]: {
    sk: "Koľko to stojí?",
    ua: "Скільки це коштує?",
    ru: "Сколько это стоит?",
    en: "How much does it cost?",
    uaTokens: ["Скільки", "це", "коштує", "?"],
    ruTokens: ["Сколько", "это", "стоит", "?"],
    enTokens: ["How", "much", "does", "it", "cost", "?"],
    extraUaTokens: ["банкомат", "проблема", "телефон"],
    extraRuTokens: ["банкомат", "проблема", "телефон"],
    extraEnTokens: ["ATM", "problem", "phone"],
  },

  [phraseKey("môžete zopakovať", "a1-10")]: {
    sk: "Môžete to zopakovať, prosím?",
    ua: "Можете повторити, будь ласка?",
    ru: "Можете повторить, пожалуйста?",
    en: "Can you repeat it, please?",
    uaTokens: ["Можете", "повторити", ",", "будь", "ласка", "?"],
    ruTokens: ["Можете", "повторить", ",", "пожалуйста", "?"],
    enTokens: ["Can", "you", "repeat", "it", ",", "please", "?"],
    extraUaTokens: ["розумієте", "банкомат", "телефон"],
    extraRuTokens: ["понимаете", "банкомат", "телефон"],
    extraEnTokens: ["understand", "ATM", "phone"],
  },

  [phraseKey("čo to znamená", "a1-10")]: {
    sk: "Čo to znamená?",
    ua: "Що це означає?",
    ru: "Что это значит?",
    en: "What does it mean?",
    uaTokens: ["Що", "це", "означає", "?"],
    ruTokens: ["Что", "это", "значит", "?"],
    enTokens: ["What", "does", "it", "mean", "?"],
    extraUaTokens: ["проблема", "телефон", "банкомат"],
    extraRuTokens: ["проблема", "телефон", "банкомат"],
    extraEnTokens: ["problem", "phone", "ATM"],
  },

  [phraseKey("rozumiete", "a1-10")]: {
    sk: "Rozumiete mi?",
    ua: "Ви мене розумієте?",
    ru: "Вы меня понимаете?",
    en: "Do you understand me?",
    uaTokens: ["Ви", "мене", "розумієте", "?"],
    ruTokens: ["Вы", "меня", "понимаете", "?"],
    enTokens: ["Do", "you", "understand", "me", "?"],
    extraUaTokens: ["повторити", "банкомат", "можу"],
    extraRuTokens: ["повторить", "банкомат", "могу"],
    extraEnTokens: ["repeat", "ATM", "can"],
  },

  [phraseKey("samozrejme", "a1-10")]: {
    sk: "Samozrejme, môžem.",
    ua: "Звісно, можу.",
    ru: "Конечно, могу.",
    en: "Of course, I can.",
    uaTokens: ["Звісно", ",", "можу", "."],
    ruTokens: ["Конечно", ",", "могу", "."],
    enTokens: ["Of", "course", ",", "I", "can", "."],
    extraUaTokens: ["не", "знаю", "вибачте"],
    extraRuTokens: ["не", "знаю", "извините"],
    extraEnTokens: ["do", "not", "sorry"],
  },

  [phraseKey("neviem", "a1-10")]: {
    sk: "Neviem, prepáčte.",
    ua: "Не знаю, вибачте.",
    ru: "Не знаю, извините.",
    en: "I do not know, sorry.",
    uaTokens: ["Не", "знаю", ",", "вибачте", "."],
    ruTokens: ["Не", "знаю", ",", "извините", "."],
    enTokens: ["I", "do", "not", "know", ",", "sorry", "."],
    extraUaTokens: ["звісно", "можу", "банкомат"],
    extraRuTokens: ["конечно", "могу", "банкомат"],
    extraEnTokens: ["of", "course", "ATM"],
  },
};