import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A1_BUILD_UA_SENTENCES_3: BuildUaSentenceDict = {
  // =========================
  // A1-11 — Опис людини
  // =========================

  [phraseKey("vysoký", "a1-11")]: {
    sk: "On je veľmi vysoký.",
    ua: "Він дуже високий.",
    ru: "Он очень высокий.",
    en: "He is very tall.",
    uaTokens: ["Він", "дуже", "високий", "."],
    ruTokens: ["Он", "очень", "высокий", "."],
    enTokens: ["He", "is", "very", "tall", "."],
    extraUaTokens: ["низький", "будинок", "сьогодні"],
    extraRuTokens: ["низкий", "дом", "сегодня"],
    extraEnTokens: ["short", "house", "today"],
  },

  [phraseKey("nízky", "a1-11")]: {
    sk: "Môj brat je nízky.",
    ua: "Мій брат низький.",
    ru: "Мой брат низкий.",
    en: "My brother is short.",
    uaTokens: ["Мій", "брат", "низький", "."],
    ruTokens: ["Мой", "брат", "низкий", "."],
    enTokens: ["My", "brother", "is", "short", "."],
    extraUaTokens: ["високий", "дуже", "сестра"],
    extraRuTokens: ["высокий", "очень", "сестра"],
    extraEnTokens: ["tall", "very", "sister"],
  },

  [phraseKey("mladý", "a1-11")]: {
    sk: "Je ešte mladý.",
    ua: "Він ще молодий.",
    ru: "Он ещё молодой.",
    en: "He is still young.",
    uaTokens: ["Він", "ще", "молодий", "."],
    ruTokens: ["Он", "ещё", "молодой", "."],
    enTokens: ["He", "is", "still", "young", "."],
    extraUaTokens: ["старий", "вона", "дуже"],
    extraRuTokens: ["старый", "она", "очень"],
    extraEnTokens: ["old", "she", "very"],
  },

  [phraseKey("starý", "a1-11")]: {
    sk: "Ten dom je starý.",
    ua: "Той будинок старий.",
    ru: "Тот дом старый.",
    en: "That house is old.",
    uaTokens: ["Той", "будинок", "старий", "."],
    ruTokens: ["Тот", "дом", "старый", "."],
    enTokens: ["That", "house", "is", "old", "."],
    extraUaTokens: ["новий", "дуже", "парк"],
    extraRuTokens: ["новый", "очень", "парк"],
    extraEnTokens: ["new", "very", "park"],
  },

  [phraseKey("silný", "a1-11")]: {
    sk: "Je silný a zdravý.",
    ua: "Він сильний і здоровий.",
    ru: "Он сильный и здоровый.",
    en: "He is strong and healthy.",
    uaTokens: ["Він", "сильний", "і", "здоровий", "."],
    ruTokens: ["Он", "сильный", "и", "здоровый", "."],
    enTokens: ["He", "is", "strong", "and", "healthy", "."],
    extraUaTokens: ["слабкий", "але", "хворий"],
    extraRuTokens: ["слабый", "но", "больной"],
    extraEnTokens: ["weak", "but", "ill"],
  },

  [phraseKey("slabý", "a1-11")]: {
    sk: "Som dnes slabý.",
    ua: "Я сьогодні слабкий.",
    ru: "Я сегодня слабый.",
    en: "I am weak today.",
    uaTokens: ["Я", "сьогодні", "слабкий", "."],
    ruTokens: ["Я", "сегодня", "слабый", "."],
    enTokens: ["I", "am", "weak", "today", "."],
    extraUaTokens: ["сильний", "дуже", "вчора"],
    extraRuTokens: ["сильный", "очень", "вчера"],
    extraEnTokens: ["strong", "very", "yesterday"],
  },

  [phraseKey("pekný", "a1-11")]: {
    sk: "To je pekný park.",
    ua: "Це гарний парк.",
    ru: "Это красивый парк.",
    en: "This is a beautiful park.",
    uaTokens: ["Це", "гарний", "парк", "."],
    ruTokens: ["Это", "красивый", "парк", "."],
    enTokens: ["This", "is", "a", "beautiful", "park", "."],
    extraUaTokens: ["великий", "будинок", "не"],
    extraRuTokens: ["большой", "дом", "не"],
    extraEnTokens: ["big", "house", "not"],
  },

  [phraseKey("škaredý", "a1-11")]: {
    sk: "To nie je škaredý obraz.",
    ua: "Це не потворна картина.",
    ru: "Это не уродливая картина.",
    en: "This is not an ugly picture.",
    uaTokens: ["Це", "не", "негарна", "картина", "."],
    ruTokens: ["Это", "не", "уродливая", "картина", "."],
    enTokens: ["This", "is", "not", "an", "ugly", "picture", "."],
    extraUaTokens: ["гарна", "стіна", "дуже"],
    extraRuTokens: ["красивая", "стена", "очень"],
    extraEnTokens: ["beautiful", "wall", "very"],
  },

  [phraseKey("milý", "a1-11")]: {
    sk: "Je veľmi milý.",
    ua: "Він дуже милий.",
    ru: "Он очень милый.",
    en: "He is very kind.",
    uaTokens: ["Він", "дуже", "милий", "."],
    ruTokens: ["Он", "очень", "милый", "."],
    enTokens: ["He", "is", "very", "kind", "."],
    extraUaTokens: ["серйозний", "сьогодні", "чоловік"],
    extraRuTokens: ["серьёзный", "сегодня", "человек"],
    extraEnTokens: ["serious", "today", "man"],
  },

  [phraseKey("vážny", "a1-11")]: {
    sk: "Je vážny človek.",
    ua: "Він серйозна людина.",
    ru: "Он серьёзный человек.",
    en: "He is a serious person.",
    uaTokens: ["Він", "серйозна", "людина", "."],
    ruTokens: ["Он", "серьёзный", "человек", "."],
    enTokens: ["He", "is", "a", "serious", "person", "."],
    extraUaTokens: ["милий", "дуже", "жінка"],
    extraRuTokens: ["милый", "очень", "женщина"],
    extraEnTokens: ["kind", "very", "woman"],
  },

  // =========================
  // A1-12 — Час
  // =========================

  [phraseKey("ráno", "a1-12")]: {
    sk: "Ráno vstávam o siedmej.",
    ua: "Вранці я встаю о сьомій.",
    ru: "Утром я встаю в семь.",
    en: "In the morning I get up at seven.",
    uaTokens: ["Вранці", "я", "встаю", "о", "сьомій", "."],
    ruTokens: ["Утром", "я", "встаю", "в", "семь", "."],
    enTokens: ["In", "the", "morning", "I", "get", "up", "at", "seven", "."],
    extraUaTokens: ["ввечері", "лягаю", "вдома"],
    extraRuTokens: ["вечером", "ложусь", "дома"],
    extraEnTokens: ["evening", "go", "to", "bed"],
  },

  [phraseKey("obed", "a1-12")]: {
    sk: "Obed máme o dvanástej.",
    ua: "Обід у нас о дванадцятій.",
    ru: "Обед у нас в двенадцать.",
    en: "We have lunch at twelve.",
    uaTokens: ["Обід", "у", "нас", "о", "дванадцятій", "."],
    ruTokens: ["Обед", "у", "нас", "в", "двенадцать", "."],
    enTokens: ["We", "have", "lunch", "at", "twelve", "."],
    extraUaTokens: ["вечеря", "сьомій", "сьогодні"],
    extraRuTokens: ["ужин", "семь", "сегодня"],
    extraEnTokens: ["dinner", "seven", "today"],
  },

  [phraseKey("večer", "a1-12")]: {
    sk: "Večer pozerám film.",
    ua: "Ввечері я дивлюся фільм.",
    ru: "Вечером я смотрю фильм.",
    en: "In the evening I watch a film.",
    uaTokens: ["Ввечері", "я", "дивлюся", "фільм", "."],
    ruTokens: ["Вечером", "я", "смотрю", "фильм", "."],
    enTokens: ["In", "the", "evening", "I", "watch", "a", "film", "."],
    extraUaTokens: ["вранці", "читаю", "книгу"],
    extraRuTokens: ["утром", "читаю", "книгу"],
    extraEnTokens: ["morning", "read", "book"],
  },

  [phraseKey("polnoc", "a1-12")]: {
    sk: "Je už polnoc.",
    ua: "Вже північ.",
    ru: "Уже полночь.",
    en: "It is already midnight.",
    uaTokens: ["Вже", "північ", "."],
    ruTokens: ["Уже", "полночь", "."],
    enTokens: ["It", "is", "already", "midnight", "."],
    extraUaTokens: ["ранок", "ще", "зараз"],
    extraRuTokens: ["утро", "ещё", "сейчас"],
    extraEnTokens: ["morning", "still", "now"],
  },

  [phraseKey("dnes", "a1-12")]: {
    sk: "Dnes pracujem doma.",
    ua: "Сьогодні я працюю вдома.",
    ru: "Сегодня я работаю дома.",
    en: "Today I work from home.",
    uaTokens: ["Сьогодні", "я", "працюю", "вдома", "."],
    ruTokens: ["Сегодня", "я", "работаю", "дома", "."],
    enTokens: ["Today", "I", "work", "from", "home", "."],
    extraUaTokens: ["завтра", "відпочиваю", "офісі"],
    extraRuTokens: ["завтра", "отдыхаю", "офисе"],
    extraEnTokens: ["tomorrow", "rest", "office"],
  },

  [phraseKey("zajtra", "a1-12")]: {
    sk: "Zajtra idem do práce.",
    ua: "Завтра я йду на роботу.",
    ru: "Завтра я иду на работу.",
    en: "Tomorrow I am going to work.",
    uaTokens: ["Завтра", "я", "йду", "на", "роботу", "."],
    ruTokens: ["Завтра", "я", "иду", "на", "работу", "."],
    enTokens: ["Tomorrow", "I", "am", "going", "to", "work", "."],
    extraUaTokens: ["сьогодні", "школу", "їду"],
    extraRuTokens: ["сегодня", "школу", "еду"],
    extraEnTokens: ["today", "school", "go"],
  },

  [phraseKey("pozajtra", "a1-12")]: {
    sk: "Pozajtra máme stretnutie.",
    ua: "Післязавтра у нас зустріч.",
    ru: "Послезавтра у нас встреча.",
    en: "The day after tomorrow we have a meeting.",
    uaTokens: ["Післязавтра", "у", "нас", "зустріч", "."],
    ruTokens: ["Послезавтра", "у", "нас", "встреча", "."],
    enTokens: ["The", "day", "after", "tomorrow", "we", "have", "a", "meeting", "."],
    extraUaTokens: ["завтра", "робота", "буде"],
    extraRuTokens: ["завтра", "работа", "будет"],
    extraEnTokens: ["tomorrow", "work", "will", "be"],
  },

  [phraseKey("vždy", "a1-12")]: {
    sk: "Vždy vstávam skoro.",
    ua: "Я завжди встаю рано.",
    ru: "Я всегда встаю рано.",
    en: "I always get up early.",
    uaTokens: ["Я", "завжди", "встаю", "рано", "."],
    ruTokens: ["Я", "всегда", "встаю", "рано", "."],
    enTokens: ["I", "always", "get", "up", "early", "."],
    extraUaTokens: ["інколи", "пізно", "лягаю"],
    extraRuTokens: ["иногда", "поздно", "ложусь"],
    extraEnTokens: ["sometimes", "late", "go", "to", "bed"],
  },

  [phraseKey("často", "a1-12")]: {
    sk: "Často chodím do kina.",
    ua: "Я часто ходжу в кіно.",
    ru: "Я часто хожу в кино.",
    en: "I often go to the cinema.",
    uaTokens: ["Я", "часто", "ходжу", "в", "кіно", "."],
    ruTokens: ["Я", "часто", "хожу", "в", "кино", "."],
    enTokens: ["I", "often", "go", "to", "the", "cinema", "."],
    extraUaTokens: ["рідко", "театр", "їжджу"],
    extraRuTokens: ["редко", "театр", "езжу"],
    extraEnTokens: ["rarely", "theatre", "go"],
  },

  [phraseKey("niekedy", "a1-12")]: {
    sk: "Niekedy som unavený.",
    ua: "Інколи я втомлений.",
    ru: "Иногда я уставший.",
    en: "Sometimes I am tired.",
    uaTokens: ["Інколи", "я", "втомлений", "."],
    ruTokens: ["Иногда", "я", "уставший", "."],
    enTokens: ["Sometimes", "I", "am", "tired", "."],
    extraUaTokens: ["завжди", "веселий", "сьогодні"],
    extraRuTokens: ["всегда", "весёлый", "сегодня"],
    extraEnTokens: ["always", "happy", "today"],
  },

  // =========================
  // A1-13 — Дім
  // =========================

  [phraseKey("chodba", "a1-13")]: {
    sk: "V chodbe je skriňa.",
    ua: "У коридорі є шафа.",
    ru: "В коридоре есть шкаф.",
    en: "There is a wardrobe in the hallway.",
    uaTokens: ["У", "коридорі", "є", "шафа", "."],
    ruTokens: ["В", "коридоре", "есть", "шкаф", "."],
    enTokens: ["There", "is", "a", "wardrobe", "in", "the", "hallway", "."],
    extraUaTokens: ["кухні", "стілець", "велика"],
    extraRuTokens: ["кухне", "стул", "большой"],
    extraEnTokens: ["kitchen", "chair", "big"],
  },

  [phraseKey("balkón", "a1-13")]: {
    sk: "Máme balkón s výhľadom.",
    ua: "У нас є балкон з видом.",
    ru: "У нас есть балкон с видом.",
    en: "We have a balcony with a view.",
    uaTokens: ["У", "нас", "є", "балкон", "з", "видом", "."],
    ruTokens: ["У", "нас", "есть", "балкон", "с", "видом", "."],
    enTokens: ["We", "have", "a", "balcony", "with", "a", "view", "."],
    extraUaTokens: ["тераса", "гарним", "квартира"],
    extraRuTokens: ["терраса", "красивым", "квартира"],
    extraEnTokens: ["terrace", "beautiful", "apartment"],
  },

  [phraseKey("pivnica", "a1-13")]: {
    sk: "V pivnici je bicykel.",
    ua: "У підвалі є велосипед.",
    ru: "В подвале есть велосипед.",
    en: "There is a bicycle in the basement.",
    uaTokens: ["У", "підвалі", "є", "велосипед", "."],
    ruTokens: ["В", "подвале", "есть", "велосипед", "."],
    enTokens: ["There", "is", "a", "bicycle", "in", "the", "basement", "."],
    extraUaTokens: ["гаражі", "авто", "старий"],
    extraRuTokens: ["гараже", "машина", "старый"],
    extraEnTokens: ["garage", "car", "old"],
  },

  [phraseKey("výťah", "a1-13")]: {
    sk: "Idem výťahom na tretie poschodie.",
    ua: "Я їду ліфтом на третій поверх.",
    ru: "Я еду на лифте на третий этаж.",
    en: "I am taking the lift to the third floor.",
    uaTokens: ["Я", "їду", "ліфтом", "на", "третій", "поверх", "."],
    ruTokens: ["Я", "еду", "на", "лифте", "на", "третий", "этаж", "."],
    enTokens: ["I", "am", "taking", "the", "lift", "to", "the", "third", "floor", "."],
    extraUaTokens: ["сходами", "другий", "будинок"],
    extraRuTokens: ["лестнице", "второй", "дом"],
    extraEnTokens: ["stairs", "second", "house"],
  },

  [phraseKey("schody", "a1-13")]: {
    sk: "Po schodoch je to rýchlejšie.",
    ua: "Сходами це швидше.",
    ru: "По лестнице это быстрее.",
    en: "It is faster by the stairs.",
    uaTokens: ["Сходами", "це", "швидше", "."],
    ruTokens: ["По", "лестнице", "это", "быстрее", "."],
    enTokens: ["It", "is", "faster", "by", "the", "stairs", "."],
    extraUaTokens: ["ліфтом", "повільніше", "зручно"],
    extraRuTokens: ["лифтом", "медленнее", "удобно"],
    extraEnTokens: ["lift", "slower", "comfortable"],
  },

  [phraseKey("záhrada", "a1-13")]: {
    sk: "V záhrade je veľa kvetov.",
    ua: "У саду багато квітів.",
    ru: "В саду много цветов.",
    en: "There are many flowers in the garden.",
    uaTokens: ["У", "саду", "багато", "квітів", "."],
    ruTokens: ["В", "саду", "много", "цветов", "."],
    enTokens: ["There", "are", "many", "flowers", "in", "the", "garden", "."],
    extraUaTokens: ["дерев", "будинку", "гарних"],
    extraRuTokens: ["деревьев", "дома", "красивых"],
    extraEnTokens: ["trees", "house", "beautiful"],
  },

  [phraseKey("garáž", "a1-13")]: {
    sk: "Auto je v garáži.",
    ua: "Авто в гаражі.",
    ru: "Машина в гараже.",
    en: "The car is in the garage.",
    uaTokens: ["Авто", "в", "гаражі", "."],
    ruTokens: ["Машина", "в", "гараже", "."],
    enTokens: ["The", "car", "is", "in", "the", "garage", "."],
    extraUaTokens: ["підвалі", "велосипед", "стоїть"],
    extraRuTokens: ["подвале", "велосипед", "стоит"],
    extraEnTokens: ["basement", "bicycle", "stands"],
  },

  [phraseKey("stena", "a1-13")]: {
    sk: "Na stene visí obraz.",
    ua: "На стіні висить картина.",
    ru: "На стене висит картина.",
    en: "A picture is hanging on the wall.",
    uaTokens: ["На", "стіні", "висить", "картина", "."],
    ruTokens: ["На", "стене", "висит", "картина", "."],
    enTokens: ["A", "picture", "is", "hanging", "on", "the", "wall", "."],
    extraUaTokens: ["фото", "лежить", "столі"],
    extraRuTokens: ["фото", "лежит", "столе"],
    extraEnTokens: ["photo", "lies", "table"],
  },

  [phraseKey("strop", "a1-13")]: {
    sk: "Strop je veľmi vysoký.",
    ua: "Стеля дуже висока.",
    ru: "Потолок очень высокий.",
    en: "The ceiling is very high.",
    uaTokens: ["Стеля", "дуже", "висока", "."],
    ruTokens: ["Потолок", "очень", "высокий", "."],
    enTokens: ["The", "ceiling", "is", "very", "high", "."],
    extraUaTokens: ["низька", "стіна", "кімната"],
    extraRuTokens: ["низкий", "стена", "комната"],
    extraEnTokens: ["low", "wall", "room"],
  },

  [phraseKey("podlaha", "a1-13")]: {
    sk: "Podlaha je čistá.",
    ua: "Підлога чиста.",
    ru: "Пол чистый.",
    en: "The floor is clean.",
    uaTokens: ["Підлога", "чиста", "."],
    ruTokens: ["Пол", "чистый", "."],
    enTokens: ["The", "floor", "is", "clean", "."],
    extraUaTokens: ["брудна", "стіна", "сьогодні"],
    extraRuTokens: ["грязный", "стена", "сегодня"],
    extraEnTokens: ["dirty", "wall", "today"],
  },

  // =========================
  // A1-14 — Покупки
  // =========================

  [phraseKey("predávať", "a1-14")]: {
    sk: "V tomto obchode predávajú oblečenie.",
    ua: "У цьому магазині продають одяг.",
    ru: "В этом магазине продают одежду.",
    en: "They sell clothes in this shop.",
    uaTokens: ["У", "цьому", "магазині", "продають", "одяг", "."],
    ruTokens: ["В", "этом", "магазине", "продают", "одежду", "."],
    enTokens: ["They", "sell", "clothes", "in", "this", "shop", "."],
    extraUaTokens: ["купують", "взуття", "ринку"],
    extraRuTokens: ["покупают", "обувь", "рынке"],
    extraEnTokens: ["buy", "shoes", "market"],
  },

  [phraseKey("kupovať", "a1-14")]: {
    sk: "Rád kupujem čerstvé ovocie.",
    ua: "Я люблю купувати свіжі фрукти.",
    ru: "Я люблю покупать свежие фрукты.",
    en: "I like buying fresh fruit.",
    uaTokens: ["Я", "люблю", "купувати", "свіжі", "фрукти", "."],
    ruTokens: ["Я", "люблю", "покупать", "свежие", "фрукты", "."],
    enTokens: ["I", "like", "buying", "fresh", "fruit", "."],
    extraUaTokens: ["овочі", "дорогі", "продавати"],
    extraRuTokens: ["овощи", "дорогие", "продавать"],
    extraEnTokens: ["vegetables", "expensive", "sell"],
  },

  [phraseKey("lacný", "a1-14")]: {
    sk: "Toto je lacný výrobok.",
    ua: "Це дешевий товар.",
    ru: "Это дешёвый товар.",
    en: "This is a cheap product.",
    uaTokens: ["Це", "дешевий", "товар", "."],
    ruTokens: ["Это", "дешёвый", "товар", "."],
    enTokens: ["This", "is", "a", "cheap", "product", "."],
    extraUaTokens: ["дорогий", "магазин", "новий"],
    extraRuTokens: ["дорогой", "магазин", "новый"],
    extraEnTokens: ["expensive", "shop", "new"],
  },

  [phraseKey("drahý", "a1-14")]: {
    sk: "Táto bunda je drahá.",
    ua: "Ця куртка дорога.",
    ru: "Эта куртка дорогая.",
    en: "This jacket is expensive.",
    uaTokens: ["Ця", "куртка", "дорога", "."],
    ruTokens: ["Эта", "куртка", "дорогая", "."],
    enTokens: ["This", "jacket", "is", "expensive", "."],
    extraUaTokens: ["дешева", "сорочка", "дуже"],
    extraRuTokens: ["дешёвая", "рубашка", "очень"],
    extraEnTokens: ["cheap", "shirt", "very"],
  },

  [phraseKey("kvalita", "a1-14")]: {
    sk: "Kvalita je veľmi dobrá.",
    ua: "Якість дуже добра.",
    ru: "Качество очень хорошее.",
    en: "The quality is very good.",
    uaTokens: ["Якість", "дуже", "добра", "."],
    ruTokens: ["Качество", "очень", "хорошее", "."],
    enTokens: ["The", "quality", "is", "very", "good", "."],
    extraUaTokens: ["погана", "ціна", "цього"],
    extraRuTokens: ["плохое", "цена", "этого"],
    extraEnTokens: ["bad", "price", "this"],
  },

  [phraseKey("značka", "a1-14")]: {
    sk: "Je to známa značka.",
    ua: "Це відомий бренд.",
    ru: "Это известный бренд.",
    en: "It is a well-known brand.",
    uaTokens: ["Це", "відомий", "бренд", "."],
    ruTokens: ["Это", "известный", "бренд", "."],
    enTokens: ["It", "is", "a", "well-known", "brand", "."],
    extraUaTokens: ["новий", "магазин", "товар"],
    extraRuTokens: ["новый", "магазин", "товар"],
    extraEnTokens: ["new", "shop", "product"],
  },

  [phraseKey("akcia", "a1-14")]: {
    sk: "Dnes je akcia na topánky.",
    ua: "Сьогодні акція на взуття.",
    ru: "Сегодня акция на обувь.",
    en: "There is a sale on shoes today.",
    uaTokens: ["Сьогодні", "акція", "на", "взуття", "."],
    ruTokens: ["Сегодня", "акция", "на", "обувь", "."],
    enTokens: ["There", "is", "a", "sale", "on", "shoes", "today", "."],
    extraUaTokens: ["знижка", "сукні", "буде"],
    extraRuTokens: ["скидка", "платья", "будет"],
    extraEnTokens: ["discount", "dresses", "will", "be"],
  },

  [phraseKey("zľavnený", "a1-14")]: {
    sk: "Tento tovar je zľavnený.",
    ua: "Цей товар зі знижкою.",
    ru: "Этот товар со скидкой.",
    en: "This product is discounted.",
    uaTokens: ["Цей", "товар", "зі", "знижкою", "."],
    ruTokens: ["Этот", "товар", "со", "скидкой", "."],
    enTokens: ["This", "product", "is", "discounted", "."],
    extraUaTokens: ["дорогий", "магазин", "сьогодні"],
    extraRuTokens: ["дорогой", "магазин", "сегодня"],
    extraEnTokens: ["expensive", "shop", "today"],
  },

  [phraseKey("pokladňa", "a1-14")]: {
    sk: "Pokladňa je vpravo.",
    ua: "Каса праворуч.",
    ru: "Касса справа.",
    en: "The checkout is on the right.",
    uaTokens: ["Каса", "праворуч", "."],
    ruTokens: ["Касса", "справа", "."],
    enTokens: ["The", "checkout", "is", "on", "the", "right", "."],
    extraUaTokens: ["ліворуч", "вхід", "магазин"],
    extraRuTokens: ["слева", "вход", "магазин"],
    extraEnTokens: ["left", "entrance", "shop"],
  },

  [phraseKey("blok", "a1-14")]: {
    sk: "Prosím, dajte mi blok.",
    ua: "Будь ласка, дайте мені чек.",
    ru: "Пожалуйста, дайте мне чек.",
    en: "Please give me the receipt.",
    uaTokens: ["Будь", "ласка", ",", "дайте", "мені", "чек", "."],
    ruTokens: ["Пожалуйста", ",", "дайте", "мне", "чек", "."],
    enTokens: ["Please", "give", "me", "the", "receipt", "."],
    extraUaTokens: ["товар", "рахунок", "пакет"],
    extraRuTokens: ["товар", "счёт", "пакет"],
    extraEnTokens: ["product", "bill", "bag"],
  },

  // =========================
  // A1-15 — Подорожі
  // =========================

  [phraseKey("hotel", "a1-15")]: {
    sk: "Bývame v hoteli v centre.",
    ua: "Ми живемо в готелі в центрі.",
    ru: "Мы живём в отеле в центре.",
    en: "We are staying in a hotel in the center.",
    uaTokens: ["Ми", "живемо", "в", "готелі", "в", "центрі", "."],
    ruTokens: ["Мы", "живём", "в", "отеле", "в", "центре", "."],
    enTokens: ["We", "are", "staying", "in", "a", "hotel", "in", "the", "center", "."],
    extraUaTokens: ["квартирі", "далеко", "міста"],
    extraRuTokens: ["квартире", "далеко", "города"],
    extraEnTokens: ["apartment", "far", "city"],
  },

  [phraseKey("ubytovanie", "a1-15")]: {
    sk: "Hľadám lacné ubytovanie.",
    ua: "Я шукаю дешеве проживання.",
    ru: "Я ищу недорогое жильё.",
    en: "I am looking for cheap accommodation.",
    uaTokens: ["Я", "шукаю", "дешеве", "проживання", "."],
    ruTokens: ["Я", "ищу", "недорогое", "жильё", "."],
    enTokens: ["I", "am", "looking", "for", "cheap", "accommodation", "."],
    extraUaTokens: ["готель", "дороге", "сьогодні"],
    extraRuTokens: ["отель", "дорогое", "сегодня"],
    extraEnTokens: ["hotel", "expensive", "today"],
  },

  [phraseKey("turista", "a1-15")]: {
    sk: "V lete je tu veľa turistov.",
    ua: "Влітку тут багато туристів.",
    ru: "Летом здесь много туристов.",
    en: "There are many tourists here in summer.",
    uaTokens: ["Влітку", "тут", "багато", "туристів", "."],
    ruTokens: ["Летом", "здесь", "много", "туристов", "."],
    enTokens: ["There", "are", "many", "tourists", "here", "in", "summer", "."],
    extraUaTokens: ["взимку", "мало", "людей"],
    extraRuTokens: ["зимой", "мало", "людей"],
    extraEnTokens: ["winter", "few", "people"],
  },

  [phraseKey("sprievodca", "a1-15")]: {
    sk: "Sprievodca nám všetko vysvetlí.",
    ua: "Гід нам усе пояснить.",
    ru: "Гид нам всё объяснит.",
    en: "The guide will explain everything to us.",
    uaTokens: ["Гід", "нам", "усе", "пояснить", "."],
    ruTokens: ["Гид", "нам", "всё", "объяснит", "."],
    enTokens: ["The", "guide", "will", "explain", "everything", "to", "us", "."],
    extraUaTokens: ["турист", "покаже", "місто"],
    extraRuTokens: ["турист", "покажет", "город"],
    extraEnTokens: ["tourist", "show", "city"],
  },

  [phraseKey("výlet", "a1-15")]: {
    sk: "Zajtra ideme na výlet.",
    ua: "Завтра ми йдемо на екскурсію.",
    ru: "Завтра мы идём на экскурсию.",
    en: "Tomorrow we are going on an excursion.",
    uaTokens: ["Завтра", "ми", "йдемо", "на", "екскурсію", "."],
    ruTokens: ["Завтра", "мы", "идём", "на", "экскурсию", "."],
    enTokens: ["Tomorrow", "we", "are", "going", "on", "an", "excursion", "."],
    extraUaTokens: ["сьогодні", "роботу", "їдемо"],
    extraRuTokens: ["сегодня", "работу", "едем"],
    extraEnTokens: ["today", "work", "go"],
  },

  [phraseKey("pláž", "a1-15")]: {
    sk: "Na pláži je dnes teplo.",
    ua: "На пляжі сьогодні тепло.",
    ru: "На пляже сегодня тепло.",
    en: "It is warm on the beach today.",
    uaTokens: ["На", "пляжі", "сьогодні", "тепло", "."],
    ruTokens: ["На", "пляже", "сегодня", "тепло", "."],
    enTokens: ["It", "is", "warm", "on", "the", "beach", "today", "."],
    extraUaTokens: ["море", "холодно", "вчора"],
    extraRuTokens: ["море", "холодно", "вчера"],
    extraEnTokens: ["sea", "cold", "yesterday"],
  },

  [phraseKey("hory", "a1-15")]: {
    sk: "V zime chodíme do hôr.",
    ua: "Взимку ми їздимо в гори.",
    ru: "Зимой мы ездим в горы.",
    en: "In winter we go to the mountains.",
    uaTokens: ["Взимку", "ми", "їздимо", "в", "гори", "."],
    ruTokens: ["Зимой", "мы", "ездим", "в", "горы", "."],
    enTokens: ["In", "winter", "we", "go", "to", "the", "mountains", "."],
    extraUaTokens: ["влітку", "море", "часто"],
    extraRuTokens: ["летом", "море", "часто"],
    extraEnTokens: ["summer", "sea", "often"],
  },

  [phraseKey("more", "a1-15")]: {
    sk: "More je veľmi studené.",
    ua: "Море дуже холодне.",
    ru: "Море очень холодное.",
    en: "The sea is very cold.",
    uaTokens: ["Море", "дуже", "холодне", "."],
    ruTokens: ["Море", "очень", "холодное", "."],
    enTokens: ["The", "sea", "is", "very", "cold", "."],
    extraUaTokens: ["тепле", "сьогодні", "озеро"],
    extraRuTokens: ["тёплое", "сегодня", "озеро"],
    extraEnTokens: ["warm", "today", "lake"],
  },

  [phraseKey("rezervovať", "a1-15")]: {
    sk: "Chcem rezervovať izbu.",
    ua: "Я хочу забронювати кімнату.",
    ru: "Я хочу забронировать номер.",
    en: "I want to book a room.",
    uaTokens: ["Я", "хочу", "забронювати", "кімнату", "."],
    ruTokens: ["Я", "хочу", "забронировать", "номер", "."],
    enTokens: ["I", "want", "to", "book", "a", "room", "."],
    extraUaTokens: ["готель", "купити", "квиток"],
    extraRuTokens: ["отель", "купить", "билет"],
    extraEnTokens: ["hotel", "buy", "ticket"],
  },

  [phraseKey("dovolenka", "a1-15")]: {
    sk: "V auguste mám dovolenku.",
    ua: "У серпні в мене відпустка.",
    ru: "В августе у меня отпуск.",
    en: "I have a holiday in August.",
    uaTokens: ["У", "серпні", "в", "мене", "відпустка", "."],
    ruTokens: ["В", "августе", "у", "меня", "отпуск", "."],
    enTokens: ["I", "have", "a", "holiday", "in", "August", "."],
    extraUaTokens: ["липні", "робота", "буде"],
    extraRuTokens: ["июле", "работа", "будет"],
    extraEnTokens: ["July", "work", "will", "be"],
  },
};