import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A1_BUILD_UA_SENTENCES_5: BuildUaSentenceDict = {
  // =========================
  // A1-21 — Проблеми і ситуації
  // =========================

  [phraseKey("problém", "a1-21")]: {
    sk: "Mám problém.",
    ua: "У мене проблема.",
    ru: "У меня проблема.",
    en: "I have a problem.",
    uaTokens: ["У", "мене", "проблема", "."],
    ruTokens: ["У", "меня", "проблема", "."],
    enTokens: ["I", "have", "a", "problem", "."],
    extraUaTokens: ["рішення", "є", "сьогодні"],
    extraRuTokens: ["решение", "есть", "сегодня"],
    extraEnTokens: ["solution", "is", "today"],
  },

  [phraseKey("pokazený", "a1-21")]: {
    sk: "Telefón je pokazený.",
    ua: "Телефон зламаний.",
    ru: "Телефон сломан.",
    en: "The phone is broken.",
    uaTokens: ["Телефон", "зламаний", "."],
    ruTokens: ["Телефон", "сломан", "."],
    enTokens: ["The", "phone", "is", "broken", "."],
    extraUaTokens: ["новий", "працює", "сьогодні"],
    extraRuTokens: ["новый", "работает", "сегодня"],
    extraEnTokens: ["new", "works", "today"],
  },

  [phraseKey("stratiť", "a1-21")]: {
    sk: "Stratil som kľúče.",
    ua: "Я загубив ключі.",
    ru: "Я потерял ключи.",
    en: "I lost the keys.",
    uaTokens: ["Я", "загубив", "ключі", "."],
    ruTokens: ["Я", "потерял", "ключи", "."],
    enTokens: ["I", "lost", "the", "keys", "."],
    extraUaTokens: ["знайшов", "телефон", "вчора"],
    extraRuTokens: ["нашёл", "телефон", "вчера"],
    extraEnTokens: ["found", "phone", "yesterday"],
  },

  [phraseKey("nájsť", "a1-21")]: {
    sk: "Nemôžem nájsť mobil.",
    ua: "Я не можу знайти телефон.",
    ru: "Я не могу найти телефон.",
    en: "I cannot find the phone.",
    uaTokens: ["Я", "не", "можу", "знайти", "телефон", "."],
    ruTokens: ["Я", "не", "могу", "найти", "телефон", "."],
    enTokens: ["I", "cannot", "find", "the", "phone", "."],
    extraUaTokens: ["ключі", "загубив", "вдома"],
    extraRuTokens: ["ключи", "потерял", "дома"],
    extraEnTokens: ["keys", "lost", "at", "home"],
  },

  [phraseKey("meškať", "a1-21")]: {
    sk: "Prepáčte, meškám.",
    ua: "Вибачте, я запізнююся.",
    ru: "Извините, я опаздываю.",
    en: "Sorry, I am late.",
    uaTokens: ["Вибачте", ",", "я", "запізнююся", "."],
    ruTokens: ["Извините", ",", "я", "опаздываю", "."],
    enTokens: ["Sorry", ",", "I", "am", "late", "."],
    extraUaTokens: ["вже", "прийшов", "сьогодні"],
    extraRuTokens: ["уже", "пришёл", "сегодня"],
    extraEnTokens: ["already", "came", "today"],
  },

  [phraseKey("zabudnúť", "a1-21")]: {
    sk: "Zabudol som heslo.",
    ua: "Я забув пароль.",
    ru: "Я забыл пароль.",
    en: "I forgot the password.",
    uaTokens: ["Я", "забув", "пароль", "."],
    ruTokens: ["Я", "забыл", "пароль", "."],
    enTokens: ["I", "forgot", "the", "password", "."],
    extraUaTokens: ["логін", "пам’ятаю", "новий"],
    extraRuTokens: ["логин", "помню", "новый"],
    extraEnTokens: ["login", "remember", "new"],
  },

  [phraseKey("chyba", "a1-21")]: {
    sk: "Je tu chyba.",
    ua: "Тут є помилка.",
    ru: "Тут ошибка.",
    en: "There is a mistake here.",
    uaTokens: ["Тут", "є", "помилка", "."],
    ruTokens: ["Тут", "есть", "ошибка", "."],
    enTokens: ["There", "is", "a", "mistake", "here", "."],
    extraUaTokens: ["рішення", "нема", "сьогодні"],
    extraRuTokens: ["решение", "нет", "сегодня"],
    extraEnTokens: ["solution", "none", "today"],
  },

  [phraseKey("oprava", "a1-21")]: {
    sk: "Potrebujem opravu.",
    ua: "Мені потрібен ремонт.",
    ru: "Мне нужен ремонт.",
    en: "I need a repair.",
    uaTokens: ["Мені", "потрібен", "ремонт", "."],
    ruTokens: ["Мне", "нужен", "ремонт", "."],
    enTokens: ["I", "need", "a", "repair", "."],
    extraUaTokens: ["допомога", "швидкий", "вже"],
    extraRuTokens: ["помощь", "быстрый", "уже"],
    extraEnTokens: ["help", "quick", "already"],
  },

  [phraseKey("pomoc", "a1-21")]: {
    sk: "Potrebujem pomoc.",
    ua: "Мені потрібна допомога.",
    ru: "Мне нужна помощь.",
    en: "I need help.",
    uaTokens: ["Мені", "потрібна", "допомога", "."],
    ruTokens: ["Мне", "нужна", "помощь", "."],
    enTokens: ["I", "need", "help", "."],
    extraUaTokens: ["ремонт", "терміново", "сьогодні"],
    extraRuTokens: ["ремонт", "срочно", "сегодня"],
    extraEnTokens: ["repair", "urgently", "today"],
  },

  [phraseKey("riešenie", "a1-21")]: {
    sk: "Máme riešenie.",
    ua: "У нас є рішення.",
    ru: "У нас есть решение.",
    en: "We have a solution.",
    uaTokens: ["У", "нас", "є", "рішення", "."],
    ruTokens: ["У", "нас", "есть", "решение", "."],
    enTokens: ["We", "have", "a", "solution", "."],
    extraUaTokens: ["проблема", "нова", "тепер"],
    extraRuTokens: ["проблема", "новая", "теперь"],
    extraEnTokens: ["problem", "new", "now"],
  },

  // =========================
  // A1-22 — Напрямки
  // =========================

  [phraseKey("vpravo", "a1-22")]: {
    sk: "Odbočte vpravo.",
    ua: "Поверніть праворуч.",
    ru: "Поверните направо.",
    en: "Turn right.",
    uaTokens: ["Поверніть", "праворуч", "."],
    ruTokens: ["Поверните", "направо", "."],
    enTokens: ["Turn", "right", "."],
    extraUaTokens: ["ліворуч", "йдіть", "прямо"],
    extraRuTokens: ["налево", "идите", "прямо"],
    extraEnTokens: ["left", "go", "straight"],
  },

  [phraseKey("vľavo", "a1-22")]: {
    sk: "Odbočte vľavo.",
    ua: "Поверніть ліворуч.",
    ru: "Поверните налево.",
    en: "Turn left.",
    uaTokens: ["Поверніть", "ліворуч", "."],
    ruTokens: ["Поверните", "налево", "."],
    enTokens: ["Turn", "left", "."],
    extraUaTokens: ["праворуч", "йдіть", "далі"],
    extraRuTokens: ["направо", "идите", "дальше"],
    extraEnTokens: ["right", "go", "further"],
  },

  [phraseKey("rovno", "a1-22")]: {
    sk: "Choďte rovno.",
    ua: "Ідіть прямо.",
    ru: "Идите прямо.",
    en: "Go straight.",
    uaTokens: ["Ідіть", "прямо", "."],
    ruTokens: ["Идите", "прямо", "."],
    enTokens: ["Go", "straight", "."],
    extraUaTokens: ["ліворуч", "поверніть", "зараз"],
    extraRuTokens: ["налево", "поверните", "сейчас"],
    extraEnTokens: ["left", "turn", "now"],
  },

  [phraseKey("blízko", "a1-22")]: {
    sk: "Je to blízko.",
    ua: "Це близько.",
    ru: "Это близко.",
    en: "It is close.",
    uaTokens: ["Це", "близько", "."],
    ruTokens: ["Это", "близко", "."],
    enTokens: ["It", "is", "close", "."],
    extraUaTokens: ["далеко", "дуже", "звідси"],
    extraRuTokens: ["далеко", "очень", "отсюда"],
    extraEnTokens: ["far", "very", "from", "here"],
  },

  [phraseKey("ďaleko", "a1-22")]: {
    sk: "Nie je to ďaleko.",
    ua: "Це недалеко.",
    ru: "Это недалеко.",
    en: "It is not far.",
    uaTokens: ["Це", "недалеко", "."],
    ruTokens: ["Это", "недалеко", "."],
    enTokens: ["It", "is", "not", "far", "."],
    extraUaTokens: ["близько", "дуже", "вже"],
    extraRuTokens: ["близко", "очень", "уже"],
    extraEnTokens: ["close", "very", "already"],
  },

  [phraseKey("hore", "a1-22")]: {
    sk: "Choďte hore po schodoch.",
    ua: "Підійдіть вгору по сходах.",
    ru: "Поднимитесь вверх по лестнице.",
    en: "Go up the stairs.",
    uaTokens: ["Підійдіть", "вгору", "по", "сходах", "."],
    ruTokens: ["Поднимитесь", "вверх", "по", "лестнице", "."],
    enTokens: ["Go", "up", "the", "stairs", "."],
    extraUaTokens: ["вниз", "ліфтом", "повільно"],
    extraRuTokens: ["вниз", "лифтом", "медленно"],
    extraEnTokens: ["down", "lift", "slowly"],
  },

  [phraseKey("dole", "a1-22")]: {
    sk: "Choďte dole.",
    ua: "Ідіть вниз.",
    ru: "Идите вниз.",
    en: "Go down.",
    uaTokens: ["Ідіть", "вниз", "."],
    ruTokens: ["Идите", "вниз", "."],
    enTokens: ["Go", "down", "."],
    extraUaTokens: ["вгору", "зараз", "праворуч"],
    extraRuTokens: ["вверх", "сейчас", "направо"],
    extraEnTokens: ["up", "now", "right"],
  },

  [phraseKey("pred", "a1-22")]: {
    sk: "Zastávka je pred obchodom.",
    ua: "Зупинка перед магазином.",
    ru: "Остановка перед магазином.",
    en: "The stop is in front of the shop.",
    uaTokens: ["Зупинка", "перед", "магазином", "."],
    ruTokens: ["Остановка", "перед", "магазином", "."],
    enTokens: ["The", "stop", "is", "in", "front", "of", "the", "shop", "."],
    extraUaTokens: ["за", "банком", "пошта"],
    extraRuTokens: ["за", "банком", "почта"],
    extraEnTokens: ["behind", "bank", "post", "office"],
  },

  [phraseKey("za", "a1-22")]: {
    sk: "Park je za domom.",
    ua: "Парк за будинком.",
    ru: "Парк за домом.",
    en: "The park is behind the house.",
    uaTokens: ["Парк", "за", "будинком", "."],
    ruTokens: ["Парк", "за", "домом", "."],
    enTokens: ["The", "park", "is", "behind", "the", "house", "."],
    extraUaTokens: ["перед", "школою", "магазин"],
    extraRuTokens: ["перед", "школой", "магазин"],
    extraEnTokens: ["in", "front", "of", "school", "shop"],
  },

  [phraseKey("medzi", "a1-22")]: {
    sk: "Je to medzi bankou a poštou.",
    ua: "Це між банком і поштою.",
    ru: "Это между банком и почтой.",
    en: "It is between the bank and the post office.",
    uaTokens: ["Це", "між", "банком", "і", "поштою", "."],
    ruTokens: ["Это", "между", "банком", "и", "почтой", "."],
    enTokens: ["It", "is", "between", "the", "bank", "and", "the", "post", "office", "."],
    extraUaTokens: ["перед", "магазином", "ліворуч"],
    extraRuTokens: ["перед", "магазином", "налево"],
    extraEnTokens: ["in", "front", "of", "shop", "left"],
  },

  // =========================
  // A1-23 — Характер
  // =========================

  [phraseKey("dobrý", "a1-23")]: {
    sk: "Je to dobrý človek.",
    ua: "Це добра людина.",
    ru: "Это хороший человек.",
    en: "This is a good person.",
    uaTokens: ["Це", "добра", "людина", "."],
    ruTokens: ["Это", "хороший", "человек", "."],
    enTokens: ["This", "is", "a", "good", "person", "."],
    extraUaTokens: ["погана", "ідея", "сьогодні"],
    extraRuTokens: ["плохая", "идея", "сегодня"],
    extraEnTokens: ["bad", "idea", "today"],
  },

  [phraseKey("zlý", "a1-23")]: {
    sk: "To nie je zlý nápad.",
    ua: "Це не погана ідея.",
    ru: "Это не плохая идея.",
    en: "This is not a bad idea.",
    uaTokens: ["Це", "не", "погана", "ідея", "."],
    ruTokens: ["Это", "не", "плохая", "идея", "."],
    enTokens: ["This", "is", "not", "a", "bad", "idea", "."],
    extraUaTokens: ["добра", "людина", "дуже"],
    extraRuTokens: ["хороший", "человек", "очень"],
    extraEnTokens: ["good", "person", "very"],
  },

  [phraseKey("trpezlivý", "a1-23")]: {
    sk: "Buďte trpezlivý, prosím.",
    ua: "Будьте терплячі, будь ласка.",
    ru: "Будьте терпеливы, пожалуйста.",
    en: "Please be patient.",
    uaTokens: ["Будьте", "терплячі", ",", "будь", "ласка", "."],
    ruTokens: ["Будьте", "терпеливы", ",", "пожалуйста", "."],
    enTokens: ["Please", "be", "patient", "."],
    extraUaTokens: ["швидкі", "дуже", "сьогодні"],
    extraRuTokens: ["быстры", "очень", "сегодня"],
    extraEnTokens: ["fast", "very", "today"],
  },

  [phraseKey("lenivý", "a1-23")]: {
    sk: "Dnes som trochu lenivý.",
    ua: "Сьогодні я трохи ледачий.",
    ru: "Сегодня я немного ленивый.",
    en: "Today I am a little lazy.",
    uaTokens: ["Сьогодні", "я", "трохи", "ледачий", "."],
    ruTokens: ["Сегодня", "я", "немного", "ленивый", "."],
    enTokens: ["Today", "I", "am", "a", "little", "lazy", "."],
    extraUaTokens: ["працьовитий", "дуже", "вчора"],
    extraRuTokens: ["трудолюбивый", "очень", "вчера"],
    extraEnTokens: ["hardworking", "very", "yesterday"],
  },

  [phraseKey("pracovitý", "a1-23")]: {
    sk: "Je veľmi pracovitý.",
    ua: "Він дуже працьовитий.",
    ru: "Он очень трудолюбивый.",
    en: "He is very hardworking.",
    uaTokens: ["Він", "дуже", "працьовитий", "."],
    ruTokens: ["Он", "очень", "трудолюбивый", "."],
    enTokens: ["He", "is", "very", "hardworking", "."],
    extraUaTokens: ["ледачий", "сьогодні", "чоловік"],
    extraRuTokens: ["ленивый", "сегодня", "человек"],
    extraEnTokens: ["lazy", "today", "man"],
  },

  [phraseKey("úprimný", "a1-23")]: {
    sk: "Buď úprimný.",
    ua: "Будь щирим.",
    ru: "Будь искренним.",
    en: "Be sincere.",
    uaTokens: ["Будь", "щирим", "."],
    ruTokens: ["Будь", "искренним", "."],
    enTokens: ["Be", "sincere", "."],
    extraUaTokens: ["спокійним", "зараз", "дуже"],
    extraRuTokens: ["спокойным", "сейчас", "очень"],
    extraEnTokens: ["calm", "now", "very"],
  },

  [phraseKey("priateľský", "a1-23")]: {
    sk: "Je priateľský a milý.",
    ua: "Він дружній і милий.",
    ru: "Он дружелюбный и милый.",
    en: "He is friendly and kind.",
    uaTokens: ["Він", "дружній", "і", "милий", "."],
    ruTokens: ["Он", "дружелюбный", "и", "милый", "."],
    enTokens: ["He", "is", "friendly", "and", "kind", "."],
    extraUaTokens: ["серйозний", "але", "сьогодні"],
    extraRuTokens: ["серьёзный", "но", "сегодня"],
    extraEnTokens: ["serious", "but", "today"],
  },

  [phraseKey("vážny", "a1-23")]: {
    sk: "Dnes som vážny.",
    ua: "Сьогодні я серйозний.",
    ru: "Сегодня я серьёзный.",
    en: "Today I am serious.",
    uaTokens: ["Сьогодні", "я", "серйозний", "."],
    ruTokens: ["Сегодня", "я", "серьёзный", "."],
    enTokens: ["Today", "I", "am", "serious", "."],
    extraUaTokens: ["веселий", "дуже", "зараз"],
    extraRuTokens: ["весёлый", "очень", "сейчас"],
    extraEnTokens: ["funny", "very", "now"],
  },

  [phraseKey("zábavný", "a1-23")]: {
    sk: "Je to zábavný človek.",
    ua: "Це весела людина.",
    ru: "Это весёлый человек.",
    en: "This is a funny person.",
    uaTokens: ["Це", "весела", "людина", "."],
    ruTokens: ["Это", "весёлый", "человек", "."],
    enTokens: ["This", "is", "a", "funny", "person", "."],
    extraUaTokens: ["серйозна", "жінка", "сьогодні"],
    extraRuTokens: ["серьёзная", "женщина", "сегодня"],
    extraEnTokens: ["serious", "woman", "today"],
  },

  [phraseKey("tichý", "a1-23")]: {
    sk: "Je tichý a pokojný.",
    ua: "Він тихий і спокійний.",
    ru: "Он тихий и спокойный.",
    en: "He is quiet and calm.",
    uaTokens: ["Він", "тихий", "і", "спокійний", "."],
    ruTokens: ["Он", "тихий", "и", "спокойный", "."],
    enTokens: ["He", "is", "quiet", "and", "calm", "."],
    extraUaTokens: ["гучний", "дуже", "сьогодні"],
    extraRuTokens: ["громкий", "очень", "сегодня"],
    extraEnTokens: ["loud", "very", "today"],
  },

  // =========================
  // A1-24 — Погода (розширено)
  // =========================

  [phraseKey("teplo", "a1-24")]: {
    sk: "Dnes je teplo.",
    ua: "Сьогодні тепло.",
    ru: "Сегодня тепло.",
    en: "It is warm today.",
    uaTokens: ["Сьогодні", "тепло", "."],
    ruTokens: ["Сегодня", "тепло", "."],
    enTokens: ["It", "is", "warm", "today", "."],
    extraUaTokens: ["холодно", "дуже", "вчора"],
    extraRuTokens: ["холодно", "очень", "вчера"],
    extraEnTokens: ["cold", "very", "yesterday"],
  },

  [phraseKey("chladno", "a1-24")]: {
    sk: "Vonku je chladno.",
    ua: "Надворі холодно.",
    ru: "На улице холодно.",
    en: "It is cold outside.",
    uaTokens: ["Надворі", "холодно", "."],
    ruTokens: ["На", "улице", "холодно", "."],
    enTokens: ["It", "is", "cold", "outside", "."],
    extraUaTokens: ["тепло", "сьогодні", "вдома"],
    extraRuTokens: ["тепло", "сегодня", "дома"],
    extraEnTokens: ["warm", "today", "at", "home"],
  },

  [phraseKey("zamračené", "a1-24")]: {
    sk: "Dnes je zamračené.",
    ua: "Сьогодні хмарно.",
    ru: "Сегодня пасмурно.",
    en: "It is cloudy today.",
    uaTokens: ["Сьогодні", "хмарно", "."],
    ruTokens: ["Сегодня", "пасмурно", "."],
    enTokens: ["It", "is", "cloudy", "today", "."],
    extraUaTokens: ["сонячно", "було", "вчора"],
    extraRuTokens: ["солнечно", "было", "вчера"],
    extraEnTokens: ["sunny", "was", "yesterday"],
  },

  [phraseKey("jasno", "a1-24")]: {
    sk: "Zajtra bude jasno.",
    ua: "Завтра буде ясно.",
    ru: "Завтра будет ясно.",
    en: "It will be clear tomorrow.",
    uaTokens: ["Завтра", "буде", "ясно", "."],
    ruTokens: ["Завтра", "будет", "ясно", "."],
    enTokens: ["It", "will", "be", "clear", "tomorrow", "."],
    extraUaTokens: ["хмарно", "сьогодні", "дуже"],
    extraRuTokens: ["пасмурно", "сегодня", "очень"],
    extraEnTokens: ["cloudy", "today", "very"],
  },

  [phraseKey("pršať", "a1-24")]: {
    sk: "Dnes prší.",
    ua: "Сьогодні йде дощ.",
    ru: "Сегодня идёт дождь.",
    en: "It is raining today.",
    uaTokens: ["Сьогодні", "йде", "дощ", "."],
    ruTokens: ["Сегодня", "идёт", "дождь", "."],
    enTokens: ["It", "is", "raining", "today", "."],
    extraUaTokens: ["сніг", "завтра", "буде"],
    extraRuTokens: ["снег", "завтра", "будет"],
    extraEnTokens: ["snow", "tomorrow", "will", "be"],
  },

  [phraseKey("snežiť", "a1-24")]: {
    sk: "V zime často sneží.",
    ua: "Взимку часто йде сніг.",
    ru: "Зимой часто идёт снег.",
    en: "It often snows in winter.",
    uaTokens: ["Взимку", "часто", "йде", "сніг", "."],
    ruTokens: ["Зимой", "часто", "идёт", "снег", "."],
    enTokens: ["It", "often", "snows", "in", "winter", "."],
    extraUaTokens: ["дощ", "влітку", "інколи"],
    extraRuTokens: ["дождь", "летом", "иногда"],
    extraEnTokens: ["rain", "summer", "sometimes"],
  },

  [phraseKey("vietor", "a1-24")]: {
    sk: "Fúka silný vietor.",
    ua: "Дме сильний вітер.",
    ru: "Дует сильный ветер.",
    en: "A strong wind is blowing.",
    uaTokens: ["Дме", "сильний", "вітер", "."],
    ruTokens: ["Дует", "сильный", "ветер", "."],
    enTokens: ["A", "strong", "wind", "is", "blowing", "."],
    extraUaTokens: ["дощ", "тепло", "сьогодні"],
    extraRuTokens: ["дождь", "тепло", "сегодня"],
    extraEnTokens: ["rain", "warm", "today"],
  },

  [phraseKey("mráz", "a1-24")]: {
    sk: "Ráno bol mráz.",
    ua: "Вранці був мороз.",
    ru: "Утром был мороз.",
    en: "There was frost in the morning.",
    uaTokens: ["Вранці", "був", "мороз", "."],
    ruTokens: ["Утром", "был", "мороз", "."],
    enTokens: ["There", "was", "frost", "in", "the", "morning", "."],
    extraUaTokens: ["вітер", "сильний", "вчора"],
    extraRuTokens: ["ветер", "сильный", "вчера"],
    extraEnTokens: ["wind", "strong", "yesterday"],
  },

  [phraseKey("búrka", "a1-24")]: {
    sk: "Prichádza búrka.",
    ua: "Наближається буря.",
    ru: "Приближается гроза.",
    en: "A storm is coming.",
    uaTokens: ["Наближається", "буря", "."],
    ruTokens: ["Приближается", "гроза", "."],
    enTokens: ["A", "storm", "is", "coming", "."],
    extraUaTokens: ["дощ", "сильна", "завтра"],
    extraRuTokens: ["дождь", "сильная", "завтра"],
    extraEnTokens: ["rain", "strong", "tomorrow"],
  },

  [phraseKey("predpoveď", "a1-24")]: {
    sk: "Pozerám predpoveď počasia.",
    ua: "Я дивлюся прогноз погоди.",
    ru: "Я смотрю прогноз погоды.",
    en: "I am watching the weather forecast.",
    uaTokens: ["Я", "дивлюся", "прогноз", "погоди", "."],
    ruTokens: ["Я", "смотрю", "прогноз", "погоды", "."],
    enTokens: ["I", "am", "watching", "the", "weather", "forecast", "."],
    extraUaTokens: ["новини", "сьогодні", "уважно"],
    extraRuTokens: ["новости", "сегодня", "внимательно"],
    extraEnTokens: ["news", "today", "carefully"],
  },

  // =========================
  // A1-25 — Їжа (розширено)
  // =========================

  [phraseKey("raňajky", "a1-25")]: {
    sk: "Na raňajky jem chlieb.",
    ua: "На сніданок я їм хліб.",
    ru: "На завтрак я ем хлеб.",
    en: "I eat bread for breakfast.",
    uaTokens: ["На", "сніданок", "я", "їм", "хліб", "."],
    ruTokens: ["На", "завтрак", "я", "ем", "хлеб", "."],
    enTokens: ["I", "eat", "bread", "for", "breakfast", "."],
    extraUaTokens: ["вечерю", "п’ю", "каву"],
    extraRuTokens: ["ужин", "пью", "кофе"],
    extraEnTokens: ["dinner", "drink", "coffee"],
  },

  [phraseKey("obed", "a1-25")]: {
    sk: "Obed mám o dvanástej.",
    ua: "Обід у мене о дванадцятій.",
    ru: "Обед у меня в двенадцать.",
    en: "I have lunch at twelve.",
    uaTokens: ["Обід", "у", "мене", "о", "дванадцятій", "."],
    ruTokens: ["Обед", "у", "меня", "в", "двенадцать", "."],
    enTokens: ["I", "have", "lunch", "at", "twelve", "."],
    extraUaTokens: ["сніданок", "сьомій", "сьогодні"],
    extraRuTokens: ["завтрак", "семь", "сегодня"],
    extraEnTokens: ["breakfast", "seven", "today"],
  },

  [phraseKey("večera", "a1-25")]: {
    sk: "Večeru jeme doma.",
    ua: "Вечерю ми їмо вдома.",
    ru: "Ужин мы едим дома.",
    en: "We eat dinner at home.",
    uaTokens: ["Вечерю", "ми", "їмо", "вдома", "."],
    ruTokens: ["Ужин", "мы", "едим", "дома", "."],
    enTokens: ["We", "eat", "dinner", "at", "home", "."],
    extraUaTokens: ["обід", "ресторані", "сьогодні"],
    extraRuTokens: ["обед", "ресторане", "сегодня"],
    extraEnTokens: ["lunch", "restaurant", "today"],
  },

  [phraseKey("sladký", "a1-25")]: {
    sk: "Tento čaj je sladký.",
    ua: "Цей чай солодкий.",
    ru: "Этот чай сладкий.",
    en: "This tea is sweet.",
    uaTokens: ["Цей", "чай", "солодкий", "."],
    ruTokens: ["Этот", "чай", "сладкий", "."],
    enTokens: ["This", "tea", "is", "sweet", "."],
    extraUaTokens: ["солоний", "суп", "дуже"],
    extraRuTokens: ["солёный", "суп", "очень"],
    extraEnTokens: ["salty", "soup", "very"],
  },

  [phraseKey("slaný", "a1-25")]: {
    sk: "Polievka je slaná.",
    ua: "Суп солоний.",
    ru: "Суп солёный.",
    en: "The soup is salty.",
    uaTokens: ["Суп", "солоний", "."],
    ruTokens: ["Суп", "солёный", "."],
    enTokens: ["The", "soup", "is", "salty", "."],
    extraUaTokens: ["солодкий", "чай", "сьогодні"],
    extraRuTokens: ["сладкий", "чай", "сегодня"],
    extraEnTokens: ["sweet", "tea", "today"],
  },

  [phraseKey("pikantný", "a1-25")]: {
    sk: "Toto jedlo je pikantné.",
    ua: "Ця їжа гостра.",
    ru: "Эта еда острая.",
    en: "This food is spicy.",
    uaTokens: ["Ця", "їжа", "гостра", "."],
    ruTokens: ["Эта", "еда", "острая", "."],
    enTokens: ["This", "food", "is", "spicy", "."],
    extraUaTokens: ["смачна", "солодка", "дуже"],
    extraRuTokens: ["вкусная", "сладкая", "очень"],
    extraEnTokens: ["tasty", "sweet", "very"],
  },

  [phraseKey("čerstvý", "a1-25")]: {
    sk: "Chlieb je čerstvý.",
    ua: "Хліб свіжий.",
    ru: "Хлеб свежий.",
    en: "The bread is fresh.",
    uaTokens: ["Хліб", "свіжий", "."],
    ruTokens: ["Хлеб", "свежий", "."],
    enTokens: ["The", "bread", "is", "fresh", "."],
    extraUaTokens: ["старий", "гарячий", "сьогодні"],
    extraRuTokens: ["старый", "горячий", "сегодня"],
    extraEnTokens: ["old", "hot", "today"],
  },

  [phraseKey("hlad", "a1-25")]: {
    sk: "Mám hlad.",
    ua: "Я голодний.",
    ru: "Я голодный.",
    en: "I am hungry.",
    uaTokens: ["Я", "голодний", "."],
    ruTokens: ["Я", "голодный", "."],
    enTokens: ["I", "am", "hungry", "."],
    extraUaTokens: ["спраглий", "дуже", "сьогодні"],
    extraRuTokens: ["голоден", "очень", "сегодня"],
    extraEnTokens: ["thirsty", "very", "today"],
  },

  [phraseKey("smäd", "a1-25")]: {
    sk: "Mám smäd.",
    ua: "Я хочу пити.",
    ru: "Я хочу пить.",
    en: "I am thirsty.",
    uaTokens: ["Я", "хочу", "пити", "."],
    ruTokens: ["Я", "хочу", "пить", "."],
    enTokens: ["I", "am", "thirsty", "."],
    extraUaTokens: ["їсти", "дуже", "зараз"],
    extraRuTokens: ["есть", "очень", "сейчас"],
    extraEnTokens: ["eat", "very", "now"],
  },

  [phraseKey("chuť", "a1-25")]: {
    sk: "Mám chuť na kávu.",
    ua: "Мені хочеться кави.",
    ru: "Мне хочется кофе.",
    en: "I feel like having coffee.",
    uaTokens: ["Мені", "хочеться", "кави", "."],
    ruTokens: ["Мне", "хочется", "кофе", "."],
    enTokens: ["I", "feel", "like", "having", "coffee", "."],
    extraUaTokens: ["чаю", "зараз", "дуже"],
    extraRuTokens: ["чая", "сейчас", "очень"],
    extraEnTokens: ["tea", "now", "very"],
  },
};