import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A1_BUILD_UA_SENTENCES_8: BuildUaSentenceDict = {
  // =========================
  // A1-36 — Транспорт (дії)
  // =========================

  [phraseKey("nastúpiť", "a1-36")]: {
    sk: "Nastúpim do autobusu.",
    ua: "Я сяду в автобус.",
    ru: "Я сяду в автобус.",
    en: "I will get on the bus.",
    uaTokens: ["Я", "сяду", "в", "автобус", "."],
    ruTokens: ["Я", "сяду", "в", "автобус", "."],
    enTokens: ["I", "will", "get", "on", "the", "bus", "."],
    extraUaTokens: ["вийду", "поїзд", "зараз"],
    extraRuTokens: ["выйду", "поезд", "сейчас"],
    extraEnTokens: ["get", "off", "train"],
  },

  [phraseKey("vystúpiť", "a1-36")]: {
    sk: "Vystúpim na ďalšej zastávke.",
    ua: "Я вийду на наступній зупинці.",
    ru: "Я выйду на следующей остановке.",
    en: "I will get off at the next stop.",
    uaTokens: ["Я", "вийду", "на", "наступній", "зупинці", "."],
    ruTokens: ["Я", "выйду", "на", "следующей", "остановке", "."],
    enTokens: ["I", "will", "get", "off", "at", "the", "next", "stop", "."],
    extraUaTokens: ["сяду", "автобус", "зараз"],
    extraRuTokens: ["сяду", "автобус", "сейчас"],
    extraEnTokens: ["get", "on", "bus"],
  },

  [phraseKey("prestúpiť", "a1-36")]: {
    sk: "Musím prestúpiť.",
    ua: "Мені треба пересісти.",
    ru: "Мне нужно пересесть.",
    en: "I need to change.",
    uaTokens: ["Мені", "треба", "пересісти", "."],
    ruTokens: ["Мне", "нужно", "пересесть", "."],
    enTokens: ["I", "need", "to", "change", "."],
    extraUaTokens: ["почекати", "ще", "зараз"],
    extraRuTokens: ["подождать", "ещё", "сейчас"],
    extraEnTokens: ["wait", "more", "now"],
  },

  [phraseKey("meškať", "a1-36")]: {
    sk: "Autobus mešká.",
    ua: "Автобус запізнюється.",
    ru: "Автобус опаздывает.",
    en: "The bus is late.",
    uaTokens: ["Автобус", "запізнюється", "."],
    ruTokens: ["Автобус", "опаздывает", "."],
    enTokens: ["The", "bus", "is", "late", "."],
    extraUaTokens: ["приїхав", "вчасно", "сьогодні"],
    extraRuTokens: ["приехал", "вовремя", "сегодня"],
    extraEnTokens: ["arrived", "on", "time"],
  },

  [phraseKey("čakať", "a1-36")]: {
    sk: "Čakám na vlak.",
    ua: "Я чекаю на поїзд.",
    ru: "Я жду поезд.",
    en: "I am waiting for the train.",
    uaTokens: ["Я", "чекаю", "на", "поїзд", "."],
    ruTokens: ["Я", "жду", "поезд", "."],
    enTokens: ["I", "am", "waiting", "for", "the", "train", "."],
    extraUaTokens: ["автобус", "сьогодні", "їду"],
    extraRuTokens: ["автобус", "сегодня", "еду"],
    extraEnTokens: ["bus", "today", "go"],
  },

  [phraseKey("odísť", "a1-36")]: {
    sk: "Musím odísť.",
    ua: "Мені треба піти.",
    ru: "Мне нужно уйти.",
    en: "I need to leave.",
    uaTokens: ["Мені", "треба", "піти", "."],
    ruTokens: ["Мне", "нужно", "уйти", "."],
    enTokens: ["I", "need", "to", "leave", "."],
    extraUaTokens: ["прийти", "пізніше", "сьогодні"],
    extraRuTokens: ["прийти", "позже", "сегодня"],
    extraEnTokens: ["come", "later", "today"],
  },

  [phraseKey("prísť", "a1-36")]: {
    sk: "Prídem o piatej.",
    ua: "Я прийду о п’ятій.",
    ru: "Я приду в пять.",
    en: "I will come at five.",
    uaTokens: ["Я", "прийду", "о", "п’ятій", "."],
    ruTokens: ["Я", "приду", "в", "пять", "."],
    enTokens: ["I", "will", "come", "at", "five", "."],
    extraUaTokens: ["шостій", "піду", "сьогодні"],
    extraRuTokens: ["шесть", "уйду", "сегодня"],
    extraEnTokens: ["six", "leave", "today"],
  },

  [phraseKey("riadiť", "a1-36")]: {
    sk: "Neviem riadiť auto.",
    ua: "Я не вмію керувати авто.",
    ru: "Я не умею водить машину.",
    en: "I cannot drive a car.",
    uaTokens: ["Я", "не", "вмію", "керувати", "авто", "."],
    ruTokens: ["Я", "не", "умею", "водить", "машину", "."],
    enTokens: ["I", "cannot", "drive", "a", "car", "."],
    extraUaTokens: ["велосипед", "зараз", "їздити"],
    extraRuTokens: ["велосипед", "сейчас", "ездить"],
    extraEnTokens: ["bicycle", "now", "ride"],
  },

  [phraseKey("parkovať", "a1-36")]: {
    sk: "Parkujem tu.",
    ua: "Я паркуюсь тут.",
    ru: "Я паркуюсь здесь.",
    en: "I am parking here.",
    uaTokens: ["Я", "паркуюсь", "тут", "."],
    ruTokens: ["Я", "паркуюсь", "здесь", "."],
    enTokens: ["I", "am", "parking", "here", "."],
    extraUaTokens: ["там", "їду", "зараз"],
    extraRuTokens: ["там", "еду", "сейчас"],
    extraEnTokens: ["there", "go", "now"],
  },

  [phraseKey("zastaviť", "a1-36")]: {
    sk: "Zastavte, prosím.",
    ua: "Зупиніться, будь ласка.",
    ru: "Остановитесь, пожалуйста.",
    en: "Stop, please.",
    uaTokens: ["Зупиніться", ",", "будь", "ласка", "."],
    ruTokens: ["Остановитесь", ",", "пожалуйста", "."],
    enTokens: ["Stop", ",", "please", "."],
    extraUaTokens: ["їдьте", "далі", "зараз"],
    extraRuTokens: ["езжайте", "дальше", "сейчас"],
    extraEnTokens: ["go", "further", "now"],
  },

  // =========================
  // A1-37 — Плани
  // =========================

  [phraseKey("plán", "a1-37")]: {
    sk: "Mám plán.",
    ua: "У мене є план.",
    ru: "У меня есть план.",
    en: "I have a plan.",
    uaTokens: ["У", "мене", "є", "план", "."],
    ruTokens: ["У", "меня", "есть", "план", "."],
    enTokens: ["I", "have", "a", "plan", "."],
    extraUaTokens: ["ціль", "нова", "сьогодні"],
    extraRuTokens: ["цель", "новая", "сегодня"],
    extraEnTokens: ["goal", "new", "today"],
  },

  [phraseKey("cieľ", "a1-37")]: {
    sk: "Môj cieľ je jasný.",
    ua: "Моя ціль ясна.",
    ru: "Моя цель ясна.",
    en: "My goal is clear.",
    uaTokens: ["Моя", "ціль", "ясна", "."],
    ruTokens: ["Моя", "цель", "ясна", "."],
    enTokens: ["My", "goal", "is", "clear", "."],
    extraUaTokens: ["план", "великий", "сьогодні"],
    extraRuTokens: ["план", "большой", "сегодня"],
    extraEnTokens: ["plan", "big", "today"],
  },

  [phraseKey("budúcnosť", "a1-37")]: {
    sk: "Myslím na budúcnosť.",
    ua: "Я думаю про майбутнє.",
    ru: "Я думаю о будущем.",
    en: "I think about the future.",
    uaTokens: ["Я", "думаю", "про", "майбутнє", "."],
    ruTokens: ["Я", "думаю", "о", "будущем", "."],
    enTokens: ["I", "think", "about", "the", "future", "."],
    extraUaTokens: ["минуле", "часто", "сьогодні"],
    extraRuTokens: ["прошлом", "часто", "сегодня"],
    extraEnTokens: ["past", "often", "today"],
  },

  [phraseKey("pripraviť", "a1-37")]: {
    sk: "Musím sa pripraviť.",
    ua: "Мені треба підготуватися.",
    ru: "Мне нужно подготовиться.",
    en: "I need to prepare.",
    uaTokens: ["Мені", "треба", "підготуватися", "."],
    ruTokens: ["Мне", "нужно", "подготовиться", "."],
    enTokens: ["I", "need", "to", "prepare", "."],
    extraUaTokens: ["почекати", "ще", "трохи"],
    extraRuTokens: ["подождать", "ещё", "немного"],
    extraEnTokens: ["wait", "a", "little", "more"],
  },

  [phraseKey("budúci týždeň", "a1-37")]: {
    sk: "Uvidíme sa budúci týždeň.",
    ua: "Побачимось наступного тижня.",
    ru: "Увидимся на следующей неделе.",
    en: "See you next week.",
    uaTokens: ["Побачимось", "наступного", "тижня", "."],
    ruTokens: ["Увидимся", "на", "следующей", "неделе", "."],
    enTokens: ["See", "you", "next", "week", "."],
    extraUaTokens: ["завтра", "зараз", "може"],
    extraRuTokens: ["завтра", "сейчас", "может"],
    extraEnTokens: ["tomorrow", "now", "maybe"],
  },

  [phraseKey("dúfať", "a1-37")]: {
    sk: "Dúfam, že to vyjde.",
    ua: "Сподіваюсь, що вийде.",
    ru: "Надеюсь, что получится.",
    en: "I hope it works out.",
    uaTokens: ["Сподіваюсь", ",", "що", "вийде", "."],
    ruTokens: ["Надеюсь", ",", "что", "получится", "."],
    enTokens: ["I", "hope", "it", "works", "out", "."],
    extraUaTokens: ["не", "сьогодні", "може"],
    extraRuTokens: ["не", "сегодня", "может"],
    extraEnTokens: ["not", "today", "maybe"],
  },

  [phraseKey("rozhodnúť sa", "a1-37")]: {
    sk: "Rozhodol som sa.",
    ua: "Я вирішив.",
    ru: "Я решил.",
    en: "I decided.",
    uaTokens: ["Я", "вирішив", "."],
    ruTokens: ["Я", "решил", "."],
    enTokens: ["I", "decided", "."],
    extraUaTokens: ["передумав", "зараз", "може"],
    extraRuTokens: ["передумал", "сейчас", "может"],
    extraEnTokens: ["changed", "my", "mind"],
  },

  [phraseKey("naplánovať", "a1-37")]: {
    sk: "Chcem to naplánovať.",
    ua: "Я хочу це запланувати.",
    ru: "Я хочу это запланировать.",
    en: "I want to plan it.",
    uaTokens: ["Я", "хочу", "це", "запланувати", "."],
    ruTokens: ["Я", "хочу", "это", "запланировать", "."],
    enTokens: ["I", "want", "to", "plan", "it", "."],
    extraUaTokens: ["змінити", "сьогодні", "план"],
    extraRuTokens: ["изменить", "сегодня", "план"],
    extraEnTokens: ["change", "today", "plan"],
  },

  [phraseKey("termín", "a1-37")]: {
    sk: "Aký je termín?",
    ua: "Який термін?",
    ru: "Какой срок?",
    en: "What is the deadline?",
    uaTokens: ["Який", "термін", "?"],
    ruTokens: ["Какой", "срок", "?"],
    enTokens: ["What", "is", "the", "deadline", "?"],
    extraUaTokens: ["план", "новий", "зараз"],
    extraRuTokens: ["план", "новый", "сейчас"],
    extraEnTokens: ["plan", "new", "now"],
  },

  [phraseKey("pokračovať", "a1-37")]: {
    sk: "Môžeme pokračovať.",
    ua: "Можемо продовжити.",
    ru: "Можем продолжить.",
    en: "We can continue.",
    uaTokens: ["Можемо", "продовжити", "."],
    ruTokens: ["Можем", "продолжить", "."],
    enTokens: ["We", "can", "continue", "."],
    extraUaTokens: ["зупинитися", "зараз", "ще"],
    extraRuTokens: ["остановиться", "сейчас", "ещё"],
    extraEnTokens: ["stop", "now", "more"],
  },

  // =========================
  // A1-38 — Ситуації в магазині
  // =========================

  [phraseKey("reklamácia", "a1-38")]: {
    sk: "Chcem urobiť reklamáciu.",
    ua: "Я хочу подати  рекламацію.",
    ru: "Я хочу подать  рекламацию.",
    en: "I want to make a complaint.",
    uaTokens: ["Я", "хочу", "подати ", "рекламацію", "."],
    ruTokens: ["Я", "хочу", "подать ", "рекламацию", "."],
    enTokens: ["I", "want", "to", "make", "a", "complaint", "."],
    extraUaTokens: ["обмін", "зараз", "товару"],
    extraRuTokens: ["обмен", "сейчас", "товара"],
    extraEnTokens: ["exchange", "now", "goods"],
  },

  [phraseKey("tovar", "a1-38")]: {
    sk: "Tento tovar je poškodený.",
    ua: "Цей товар пошкоджений.",
    ru: "Этот товар повреждён.",
    en: "This product is damaged.",
    uaTokens: ["Цей", "товар", "пошкоджений", "."],
    ruTokens: ["Этот", "товар", "повреждён", "."],
    enTokens: ["This", "product", "is", "damaged", "."],
    extraUaTokens: ["новий", "добрий", "сьогодні"],
    extraRuTokens: ["новый", "хороший", "сегодня"],
    extraEnTokens: ["new", "good", "today"],
  },

  [phraseKey("sklad", "a1-38")]: {
    sk: "Je to na sklade.",
    ua: "Це є на складі.",
    ru: "Это  на складе.",
    en: "It is in stock.",
    uaTokens: ["Це", "є", "на", "складі", "."],
    ruTokens: ["Это", "на", "складе", "."],
    enTokens: ["It", "is", "in", "stock", "."],
    extraUaTokens: ["магазині", "зараз", "нема"],
    extraRuTokens: ["магазине", "сейчас", "нет"],
    extraEnTokens: ["shop", "now", "none"],
  },

  [phraseKey("účtenka", "a1-38")]: {
    sk: "Máte účtenku?",
    ua: "У вас є чек?",
    ru: "У вас есть чек?",
    en: "Do you have the receipt?",
    uaTokens: ["У", "вас", "є", "чек", "?"],
    ruTokens: ["У", "вас", "есть", "чек", "?"],
    enTokens: ["Do", "you", "have", "the", "receipt", "?"],
    extraUaTokens: ["товар", "новий", "сьогодні"],
    extraRuTokens: ["товар", "новый", "сегодня"],
    extraEnTokens: ["product", "new", "today"],
  },

  [phraseKey("záruka", "a1-38")]: {
    sk: "Je na to záruka.",
    ua: "На це є гарантія.",
    ru: "На это есть гарантия.",
    en: "There is a warranty for it.",
    uaTokens: ["На", "це", "є", "гарантія", "."],
    ruTokens: ["На", "это", "есть", "гарантия", "."],
    enTokens: ["There", "is", "a", "warranty", "for", "it", "."],
    extraUaTokens: ["чек", "сьогодні", "новий"],
    extraRuTokens: ["чек", "сегодня", "новый"],
    extraEnTokens: ["receipt", "today", "new"],
  },

  [phraseKey("poškodený", "a1-38")]: {
    sk: "Je to poškodené.",
    ua: "Це пошкоджене.",
    ru: "Это повреждено.",
    en: "It is damaged.",
    uaTokens: ["Це", "пошкоджене", "."],
    ruTokens: ["Это", "повреждено", "."],
    enTokens: ["It", "is", "damaged", "."],
    extraUaTokens: ["нове", "добре", "сьогодні"],
    extraRuTokens: ["новое", "хорошо", "сегодня"],
    extraEnTokens: ["new", "good", "today"],
  },

  [phraseKey("predavač", "a1-38")]: {
    sk: "Predavač mi pomohol.",
    ua: "Продавець мені допоміг.",
    ru: "Продавец мне помог.",
    en: "The shop assistant helped me.",
    uaTokens: ["Продавець", "мені", "допоміг", "."],
    ruTokens: ["Продавец", "мне", "помог", "."],
    enTokens: ["The", "shop", "assistant", "helped", "me", "."],
    extraUaTokens: ["клієнт", "чекав", "сьогодні"],
    extraRuTokens: ["клиент", "ждал", "сегодня"],
    extraEnTokens: ["customer", "waited", "today"],
  },

  [phraseKey("zákazník", "a1-38")]: {
    sk: "Zákazník čaká pri pokladni.",
    ua: "Клієнт чекає біля каси.",
    ru: "Клиент ждёт у кассы.",
    en: "The customer is waiting at the checkout.",
    uaTokens: ["Клієнт", "чекає", "біля", "каси", "."],
    ruTokens: ["Клиент", "ждёт", "у", "кассы", "."],
    enTokens: ["The", "customer", "is", "waiting", "at", "the", "checkout", "."],
    extraUaTokens: ["продавець", "поруч", "зараз"],
    extraRuTokens: ["продавец", "рядом", "сейчас"],
    extraEnTokens: ["assistant", "near", "now"],
  },

  [phraseKey("reklamovať", "a1-38")]: {
    sk: "Chcem reklamovať tento tovar.",
    ua: "Я хочу поскаржитися на цей товар.",
    ru: "Я хочу подать рекламацию на этот товар.",
    en: "I want to complain about this product.",
    uaTokens: ["Я", "хочу", "поскаржитися", "на", "цей", "товар", "."],
    ruTokens: ["Я", "хочу", "подать", "рекламацию", "на", "этот", "товар", "."],
    enTokens: ["I", "want", "to", "complain", "about", "this", "product", "."],
    extraUaTokens: ["обміняти", "його", "сьогодні"],
    extraRuTokens: ["обменять", "его", "сегодня"],
    extraEnTokens: ["exchange", "it", "today"],
  },

  [phraseKey("výmena", "a1-38")]: {
    sk: "Chcem výmenu.",
    ua: "Я хочу обмін.",
    ru: "Я хочу обмен.",
    en: "I want an exchange.",
    uaTokens: ["Я", "хочу", "обмін", "."],
    ruTokens: ["Я", "хочу", "обмен", "."],
    enTokens: ["I", "want", "an", "exchange", "."],
    extraUaTokens: ["повернення", "коштів", "зараз"],
    extraRuTokens: ["возврат", "денег", "сейчас"],
    extraEnTokens: ["return", "money", "now"],
  },

  // =========================
  // A1-39 — Абстрактні слова
  // =========================

  [phraseKey("život", "a1-39")]: {
    sk: "Život je krátky.",
    ua: "Життя коротке.",
    ru: "Жизнь короткая.",
    en: "Life is short.",
    uaTokens: ["Життя", "коротке", "."],
    ruTokens: ["Жизнь", "короткая", "."],
    enTokens: ["Life", "is", "short", "."],
    extraUaTokens: ["довге", "сьогодні", "дуже"],
    extraRuTokens: ["длинная", "сегодня", "очень"],
    extraEnTokens: ["long", "today", "very"],
  },

  [phraseKey("čas", "a1-39")]: {
    sk: "Nemám čas.",
    ua: "У мене немає часу.",
    ru: "У меня нет времени.",
    en: "I do not have time.",
    uaTokens: ["У", "мене", "немає", "часу", "."],
    ruTokens: ["У", "меня", "нет", "времени", "."],
    enTokens: ["I", "do", "not", "have", "time", "."],
    extraUaTokens: ["багато", "сьогодні", "роботи"],
    extraRuTokens: ["много", "сегодня", "работы"],
    extraEnTokens: ["a", "lot", "today", "work"],
  },

  [phraseKey("možnosť", "a1-39")]: {
    sk: "Mám možnosť vybrať si.",
    ua: "У мене є можливість вибрати.",
    ru: "У меня есть возможность выбрать.",
    en: "I have the option to choose.",
    uaTokens: ["У", "мене", "є", "можливість", "вибрати", "."],
    ruTokens: ["У", "меня", "есть", "возможность", "выбрать", "."],
    enTokens: ["I", "have", "the", "option", "to", "choose", "."],
    extraUaTokens: ["змінити", "сьогодні", "ще"],
    extraRuTokens: ["изменить", "сегодня", "ещё"],
    extraEnTokens: ["change", "today", "more"],
  },

  [phraseKey("dôvod", "a1-39")]: {
    sk: "Aký je dôvod?",
    ua: "Яка причина?",
    ru: "Какая причина?",
    en: "What is the reason?",
    uaTokens: ["Яка", "причина", "?"],
    ruTokens: ["Какая", "причина", "?"],
    enTokens: ["What", "is", "the", "reason", "?"],
    extraUaTokens: ["відповідь", "правильна", "сьогодні"],
    extraRuTokens: ["ответ", "правильный", "сегодня"],
    extraEnTokens: ["answer", "correct", "today"],
  },

  [phraseKey("význam", "a1-39")]: {
    sk: "Aký to má význam?",
    ua: "Яке це має значення?",
    ru: "Какое это имеет значение?",
    en: "What does it mean?",
    uaTokens: ["Яке", "це", "має", "значення", "?"],
    ruTokens: ["Какое", "это", "имеет", "значение", "?"],
    enTokens: ["What", "does", "it", "mean", "?"],
    extraUaTokens: ["сенс", "новий", "сьогодні"],
    extraRuTokens: ["смысл", "новый", "сегодня"],
    extraEnTokens: ["sense", "new", "today"],
  },

  [phraseKey("pravda", "a1-39")]: {
    sk: "To je pravda.",
    ua: "Це правда.",
    ru: "Это правда.",
    en: "That is true.",
    uaTokens: ["Це", "правда", "."],
    ruTokens: ["Это", "правда", "."],
    enTokens: ["That", "is", "true", "."],
    extraUaTokens: ["брехня", "сьогодні", "може"],
    extraRuTokens: ["ложь", "сегодня", "может"],
    extraEnTokens: ["lie", "today", "maybe"],
  },

  [phraseKey("lož", "a1-39")]: {
    sk: "To nie je pravda, je to lož.",
    ua: "Це не правда, це брехня.",
    ru: "Это не правда, это ложь.",
    en: "That is not true, it is a lie.",
    uaTokens: ["Це", "не", "правда", ",", "це", "брехня", "."],
    ruTokens: ["Это", "не", "правда", ",", "это", "ложь", "."],
    enTokens: ["That", "is", "not", "true", ",", "it", "is", "a", "lie", "."],
    extraUaTokens: ["істина", "сьогодні", "дуже"],
    extraRuTokens: ["истина", "сегодня", "очень"],
    extraEnTokens: ["truth", "today", "very"],
  },

  [phraseKey("úspech", "a1-39")]: {
    sk: "To je úspech.",
    ua: "Це успіх.",
    ru: "Это успех.",
    en: "That is a success.",
    uaTokens: ["Це", "успіх", "."],
    ruTokens: ["Это", "успех", "."],
    enTokens: ["That", "is", "a", "success", "."],
    extraUaTokens: ["невдача", "сьогодні", "велика"],
    extraRuTokens: ["неудача", "сегодня", "большая"],
    extraEnTokens: ["failure", "today", "big"],
  },

  [phraseKey("neúspech", "a1-39")]: {
    sk: "To bol neúspech.",
    ua: "Це була невдача.",
    ru: "Это была неудача.",
    en: "That was a failure.",
    uaTokens: ["Це", "була", "невдача", "."],
    ruTokens: ["Это", "была", "неудача", "."],
    enTokens: ["That", "was", "a", "failure", "."],
    extraUaTokens: ["успіх", "сьогодні", "великий"],
    extraRuTokens: ["успех", "сегодня", "большой"],
    extraEnTokens: ["success", "today", "big"],
  },

  [phraseKey("skúsenosť", "a1-39")]: {
    sk: "Mám skúsenosť.",
    ua: "У мене є досвід.",
    ru: "У меня есть опыт.",
    en: "I have experience.",
    uaTokens: ["У", "мене", "є", "досвід", "."],
    ruTokens: ["У", "меня", "есть", "опыт", "."],
    enTokens: ["I", "have", "experience", "."],
    extraUaTokens: ["знання", "сьогодні", "нове"],
    extraRuTokens: ["знание", "сегодня", "новое"],
    extraEnTokens: ["knowledge", "today", "new"],
  },

  // =========================
  // A1-40 — Повторення A1
  // =========================

  [phraseKey("učiť sa", "a1-40")]: {
    sk: "Učím sa po slovensky.",
    ua: "Я вчу словацьку.",
    ru: "Я учу словацкий.",
    en: "I am learning Slovak.",
    uaTokens: ["Я", "вчу", "словацьку", "."],
    ruTokens: ["Я", "учу", "словацкий", "."],
    enTokens: ["I", "am", "learning", "Slovak", "."],
    extraUaTokens: ["чеської", "сьогодні", "трохи"],
    extraRuTokens: ["чешский", "сегодня", "немного"],
    extraEnTokens: ["Czech", "today", "a", "little"],
  },

  [phraseKey("cestovať", "a1-40")]: {
    sk: "Rád cestujem.",
    ua: "Я люблю подорожувати.",
    ru: "Я люблю путешествовать.",
    en: "I like traveling.",
    uaTokens: ["Я", "люблю", "подорожувати", "."],
    ruTokens: ["Я", "люблю", "путешествовать", "."],
    enTokens: ["I", "like", "traveling", "."],
    extraUaTokens: ["працювати", "зараз", "багато"],
    extraRuTokens: ["работать", "сейчас", "много"],
    extraEnTokens: ["work", "now", "a", "lot"],
  },

  [phraseKey("pomôcť", "a1-40")]: {
    sk: "Môžem vám pomôcť?",
    ua: "Можу вам допомогти?",
    ru: "Могу вам помочь?",
    en: "Can I help you?",
    uaTokens: ["Можу", "вам", "допомогти", "?"],
    ruTokens: ["Могу", "вам", "помочь", "?"],
    enTokens: ["Can", "I", "help", "you", "?"],
    extraUaTokens: ["пояснити", "трохи", "зараз"],
    extraRuTokens: ["объяснить", "немного", "сейчас"],
    extraEnTokens: ["explain", "a", "little", "now"],
  },

  [phraseKey("písať", "a1-40")]: {
    sk: "Píšem správu.",
    ua: "Я пишу повідомлення.",
    ru: "Я пишу сообщение.",
    en: "I am writing a message.",
    uaTokens: ["Я", "пишу", "повідомлення", "."],
    ruTokens: ["Я", "пишу", "сообщение", "."],
    enTokens: ["I", "am", "writing", "a", "message", "."],
    extraUaTokens: ["лист", "читаю", "зараз"],
    extraRuTokens: ["письмо", "читаю", "сейчас"],
    extraEnTokens: ["letter", "read", "now"],
  },

  [phraseKey("vrátiť sa", "a1-40")]: {
    sk: "Vrátim sa domov.",
    ua: "Я повернуся додому.",
    ru: "Я вернусь домой.",
    en: "I will return home.",
    uaTokens: ["Я", "повернуся", "додому", "."],
    ruTokens: ["Я", "вернусь", "домой", "."],
    enTokens: ["I", "will", "return", "home", "."],
    extraUaTokens: ["залишуся", "тут", "сьогодні"],
    extraRuTokens: ["останусь", "здесь", "сегодня"],
    extraEnTokens: ["stay", "here", "today"],
  },

  [phraseKey("zostať", "a1-40")]: {
    sk: "Zostanem tu.",
    ua: "Я залишуся тут.",
    ru: "Я останусь здесь.",
    en: "I will stay here.",
    uaTokens: ["Я", "залишуся", "тут", "."],
    ruTokens: ["Я", "останусь", "здесь", "."],
    enTokens: ["I", "will", "stay", "here", "."],
    extraUaTokens: ["піду", "додому", "зараз"],
    extraRuTokens: ["уйду", "домой", "сейчас"],
    extraEnTokens: ["leave", "home", "now"],
  },

  [phraseKey("zmeniť", "a1-40")]: {
    sk: "Chcem to zmeniť.",
    ua: "Я хочу це змінити.",
    ru: "Я хочу это изменить.",
    en: "I want to change it.",
    uaTokens: ["Я", "хочу", "це", "змінити", "."],
    ruTokens: ["Я", "хочу", "это", "изменить", "."],
    enTokens: ["I", "want", "to", "change", "it", "."],
    extraUaTokens: ["залишити", "так", "сьогодні"],
    extraRuTokens: ["оставить", "так", "сегодня"],
    extraEnTokens: ["leave", "it", "today"],
  },

  [phraseKey("ukázať", "a1-40")]: {
    sk: "Ukážem vám to.",
    ua: "Я покажу вам це.",
    ru: "Я покажу вам это.",
    en: "I will show it to you.",
    uaTokens: ["Я", "покажу", "вам", "це", "."],
    ruTokens: ["Я", "покажу", "вам", "это", "."],
    enTokens: ["I", "will", "show", "it", "to", "you", "."],
    extraUaTokens: ["поясню", "пізніше", "зараз"],
    extraRuTokens: ["объясню", "позже", "сейчас"],
    extraEnTokens: ["explain", "later", "now"],
  },

  [phraseKey("niesť", "a1-40")]: {
    sk: "Nesiem tašku.",
    ua: "Я несу сумку.",
    ru: "Я несу сумку.",
    en: "I am carrying a bag.",
    uaTokens: ["Я", "несу", "сумку", "."],
    ruTokens: ["Я", "несу", "сумку", "."],
    enTokens: ["I", "am", "carrying", "a", "bag", "."],
    extraUaTokens: ["валізу", "сьогодні", "важку"],
    extraRuTokens: ["чемодан", "сегодня", "тяжёлый"],
    extraEnTokens: ["suitcase", "today", "heavy"],
  },

  [phraseKey("sedieť", "a1-40")]: {
    sk: "Sedím na stoličke.",
    ua: "Я сиджу на стільці.",
    ru: "Я сижу на стуле.",
    en: "I am sitting on a chair.",
    uaTokens: ["Я", "сиджу", "на", "стільці", "."],
    ruTokens: ["Я", "сижу", "на", "стуле", "."],
    enTokens: ["I", "am", "sitting", "on", "a", "chair", "."],
    extraUaTokens: ["дивані", "лежу", "зараз"],
    extraRuTokens: ["диване", "лежу", "сейчас"],
    extraEnTokens: ["sofa", "lie", "now"],
  },
};