import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_B2_BUILD_UA_SENTENCES_2: BuildUaSentenceDict = {
    // =========================
    // LESSON 6 — Контракти та умови
    // =========================
    [phraseKey("umowa", "b2-6")]: {
        sk: "Umowa została podpisana po długich negocjacjach.",
        ua: "Договір був підписаний після довгих переговорів.",
        ru: "Договор был подписан после долгих переговоров.",
        en: "The contract was signed after long negotiations.",
        uaTokens: ["Договір", "був", "підписаний", "після", "довгих", "переговорів", "."],
        ruTokens: ["Договор", "был", "подписан", "после", "долгих", "переговоров", "."],
        enTokens: ["The", "contract", "was", "signed", "after", "long", "negotiations", "."],
        extraUaTokens: ["сторони", "умови", "проєкт"],
        extraRuTokens: ["стороны", "условия", "проект"],
        extraEnTokens: ["parties", "conditions", "project"],
    },

    [phraseKey("postanowienie", "b2-6")]: {
        sk: "Każde postanowienie umowy musi być dokładnie przeanalizowane.",
        ua: "Кожне положення договору має бути ретельно проаналізоване.",
        ru: "Каждое положение договора должно быть тщательно проанализировано.",
        en: "Each provision of the contract must be carefully analyzed.",
        uaTokens: ["Кожне", "положення", "договору", "має", "бути", "ретельно", "проаналізоване", "."],
        ruTokens: ["Каждое", "положение", "договора", "должно", "быть", "тщательно", "проанализировано", "."],
        enTokens: ["Each", "provision", "of", "the", "contract", "must", "be", "carefully", "analyzed", "."],
        extraUaTokens: ["строки", "проєкт", "пропозицію"],
        extraRuTokens: ["сроки", "проект", "предложение"],
        extraEnTokens: ["deadline", "project", "offer"],
    },

    [phraseKey("ważność", "b2-6")]: {
        sk: "Ważność umowy wygasa po upływie określonego czasu.",
        ua: "Чинність договору закінчується після певного часу.",
        ru: "Срок действия договора истекает по истечении определённого времени.",
        en: "The validity of the contract expires after a certain period.",
        uaTokens: ["Чинність", "договору", "закінчується", "після", "певного", "часу", "."],
        ruTokens: ["Срок", "действия", "договора", "истекает", "по", "истечении", "определённого", "времени", "."],
        enTokens: ["The", "validity", "of", "the", "contract", "expires", "after", "a", "certain", "period", "."],
        extraUaTokens: ["умови", "строки", "сторони"],
        extraRuTokens: ["условия", "сроки", "стороны"],
        extraEnTokens: ["conditions", "deadline", "parties"],
    },

    [phraseKey("zobowiązanie", "b2-6")]: {
        sk: "Zobowiązanie musi być wykonane zgodnie z warunkami umowy.",
        ua: "Зобов’язання має бути виконане відповідно до умов договору.",
        ru: "Обязательство должно быть выполнено в соответствии с условиями договора.",
        en: "The obligation must be fulfilled according to the contract terms.",
        uaTokens: ["Зобов’язання", "має", "бути", "виконане", "відповідно", "до", "умов", "договору", "."],
        ruTokens: ["Обязательство", "должно", "быть", "выполнено", "в", "соответствии", "с", "условиями", "договора", "."],
        enTokens: ["The", "obligation", "must", "be", "fulfilled", "according", "to", "the", "contract", "terms", "."],
        extraUaTokens: ["переговорів", "проєкт", "рішення"],
        extraRuTokens: ["переговоров", "проект", "решение"],
        extraEnTokens: ["negotiations", "project", "decision"],
    },

    [phraseKey("naruszyć umowę", "b2-6")]: {
        sk: "Jeśli naruszysz umowę, możesz ponieść konsekwencje prawne.",
        ua: "Якщо ти порушиш договір, можеш понести юридичні наслідки.",
        ru: "Если ты нарушишь договор, можешь понести юридические последствия.",
        en: "If you breach the contract, you may face legal consequences.",
        uaTokens: ["Якщо", "ти", "порушиш", "договір", ",", "можеш", "понести", "юридичні", "наслідки", "."],
        ruTokens: ["Если", "ты", "нарушишь", "договор", ",", "можешь", "понести", "юридические", "последствия", "."],
        enTokens: ["If", "you", "breach", "the", "contract", ",", "you", "may", "face", "legal", "consequences", "."],
        extraUaTokens: ["сторони", "умови", "термін"],
        extraRuTokens: ["стороны", "условия", "срок"],
        extraEnTokens: ["parties", "conditions", "deadline"],
    },

    [phraseKey("podpisać umowę", "b2-6")]: {
        sk: "Obie strony muszą podpisać umowę, aby była ważna.",
        ua: "Обидві сторони повинні підписати договір, щоб він був дійсним.",
        ru: "Обе стороны должны подписать договор, чтобы он был действительным.",
        en: "Both parties must sign the contract for it to be valid.",
        uaTokens: ["Обидві", "сторони", "повинні", "підписати", "договір", ",", "щоб", "він", "був", "дійсним", "."],
        ruTokens: ["Обе", "стороны", "должны", "подписать", "договор", ",", "чтобы", "он", "был", "действительным", "."],
        enTokens: ["Both", "parties", "must", "sign", "the", "contract", "for", "it", "to", "be", "valid", "."],
        extraUaTokens: ["умови", "строки", "проєкт"],
        extraRuTokens: ["условия", "сроки", "проект"],
        extraEnTokens: ["conditions", "deadline", "project"],
    },

    [phraseKey("uzgodniony", "b2-6")]: {
        sk: "Termin został wcześniej uzgodniony przez obie strony.",
        ua: "Термін був попередньо узгоджений обома сторонами.",
        ru: "Срок был заранее согласован обеими сторонами.",
        en: "The deadline was agreed upon earlier by both parties.",
        uaTokens: ["Термін", "був", "попередньо", "узгоджений", "обома", "сторонами", "."],
        ruTokens: ["Срок", "был", "заранее", "согласован", "обеими", "сторонами", "."],
        enTokens: ["The", "deadline", "was", "agreed", "upon", "earlier", "by", "both", "parties", "."],
        uaAltAnswers: [["Термін", "був", "узгоджений", "попередньо", "обома", "сторонами", "."]],
        ruAltAnswers: [["Срок", "был", "согласован", "заранее", "обеими", "сторонами", "."]],
        extraUaTokens: ["договір", "умови", "проєкт"],
        extraRuTokens: ["договор", "условия", "проект"],
        extraEnTokens: ["contract", "conditions", "project"],
    },

    [phraseKey("termin", "b2-6")]: {
        sk: "Musimy dotrzymać terminu, inaczej projekt się opóźni.",
        ua: "Ми повинні дотриматися терміну, інакше проєкт затримається.",
        ru: "Мы должны уложиться в срок, иначе проект задержится.",
        en: "We must meet the deadline, otherwise the project will be delayed.",
        uaTokens: ["Ми", "повинні", "дотриматися", "терміну", ",", "інакше", "проєкт", "затримається", "."],
        ruTokens: ["Мы", "должны", "уложиться", "в", "срок", ",", "иначе", "проект", "задержится", "."],
        enTokens: ["We", "must", "meet", "the", "deadline", ",", "otherwise", "the", "project", "will", "be", "delayed", "."],
        extraUaTokens: ["сторони", "умови", "пропозицію"],
        extraRuTokens: ["стороны", "условия", "предложение"],
        extraEnTokens: ["parties", "conditions", "offer"],
    },

    [phraseKey("spełnić warunki", "b2-6")]: {
        sk: "Aby otrzymać ofertę, musisz spełnić wszystkie warunki.",
        ua: "Щоб отримати пропозицію, ти повинен виконати всі умови.",
        ru: "Чтобы получить предложение, ты должен выполнить все условия.",
        en: "To receive the offer, you must meet all the conditions.",
        uaTokens: ["Щоб", "отримати", "пропозицію", ",", "ти", "повинен", "виконати", "всі", "умови", "."],
        ruTokens: ["Чтобы", "получить", "предложение", ",", "ты", "должен", "выполнить", "все", "условия", "."],
        enTokens: ["To", "receive", "the", "offer", ",", "you", "must", "meet", "all", "the", "conditions", "."],
        extraUaTokens: ["термін", "проєкт", "сторони"],
        extraRuTokens: ["срок", "проект", "стороны"],
        extraEnTokens: ["deadline", "project", "parties"],
    },

    [phraseKey("strona umowy", "b2-6")]: {
        sk: "Każda strona umowy ma swoje prawa i obowiązki.",
        ua: "Кожна сторона договору має свої права та обов’язки.",
        ru: "Каждая сторона договора имеет свои права и обязанности.",
        en: "Each contracting party has its rights and obligations.",
        uaTokens: ["Кожна", "сторона", "договору", "має", "свої", "права", "та", "обов’язки", "."],
        ruTokens: ["Каждая", "сторона", "договора", "имеет", "свои", "права", "и", "обязанности", "."],
        enTokens: ["Each", "contracting", "party", "has", "its", "rights", "and", "obligations", "."],
        extraUaTokens: ["умови", "термін", "проєкт"],
        extraRuTokens: ["условия", "срок", "проект"],
        extraEnTokens: ["conditions", "deadline", "project"],
    },

    // =========================
    // LESSON 7 — Планування та стратегія
    // =========================
    [phraseKey("strategia", "b2-7")]: {
        sk: "Dobra strategia pozwala osiągnąć długoterminowe cele.",
        ua: "Хороша стратегія дозволяє досягати довгострокових цілей.",
        ru: "Хорошая стратегия позволяет достигать долгосрочных целей.",
        en: "A good strategy allows achieving long-term goals.",
        uaTokens: ["Хороша", "стратегія", "дозволяє", "досягати", "довгострокових", "цілей", "."],
        ruTokens: ["Хорошая", "стратегия", "позволяет", "достигать", "долгосрочных", "целей", "."],
        enTokens: ["A", "good", "strategy", "allows", "achieving", "long-term", "goals", "."],
        extraUaTokens: ["планування", "процедура", "команда"],
        extraRuTokens: ["планирование", "процедура", "команда"],
        extraEnTokens: ["planning", "procedure", "team"],
    },

    [phraseKey("planowanie", "b2-7")]: {
        sk: "Planowanie jest kluczowe dla sukcesu projektu.",
        ua: "Планування є ключовим для успіху проєкту.",
        ru: "Планирование является ключевым для успеха проекта.",
        en: "Planning is crucial for project success.",
        uaTokens: ["Планування", "є", "ключовим", "для", "успіху", "проєкту", "."],
        ruTokens: ["Планирование", "является", "ключевым", "для", "успеха", "проекта", "."],
        enTokens: ["Planning", "is", "crucial", "for", "project", "success", "."],
        extraUaTokens: ["стратегія", "мету", "процедура"],
        extraRuTokens: ["стратегия", "цель", "процедура"],
        extraEnTokens: ["strategy", "goal", "procedure"],
    },

    [phraseKey("wyznaczyć cel", "b2-7")]: {
        sk: "Najpierw musimy wyznaczyć cel, a potem działać.",
        ua: "Спочатку потрібно поставити мету, а потім діяти.",
        ru: "Сначала нужно поставить цель, а потом действовать.",
        en: "First we need to set a goal, then act.",
        uaTokens: ["Спочатку", "потрібно", "поставити", "мету", ",", "а", "потім", "діяти", "."],
        ruTokens: ["Сначала", "нужно", "поставить", "цель", ",", "а", "потом", "действовать", "."],
        enTokens: ["First", "we", "need", "to", "set", "a", "goal", ",", "then", "act", "."],
        extraUaTokens: ["стратегія", "проєкту", "команда"],
        extraRuTokens: ["стратегия", "проекта", "команда"],
        extraEnTokens: ["strategy", "project", "team"],
    },

    [phraseKey("długoterminowy", "b2-7")]: {
        sk: "To jest długoterminowy projekt wymagający cierpliwości.",
        ua: "Це довгостроковий проєкт, що вимагає терпіння.",
        ru: "Это долгосрочный проект, требующий терпения.",
        en: "This is a long-term project requiring patience.",
        uaTokens: ["Це", "довгостроковий", "проєкт", ",", "що", "вимагає", "терпіння", "."],
        ruTokens: ["Это", "долгосрочный", "проект", ",", "требующий", "терпения", "."],
        enTokens: ["This", "is", "a", "long-term", "project", "requiring", "patience", "."],
        extraUaTokens: ["стратегія", "рішення", "процедура"],
        extraRuTokens: ["стратегия", "решения", "процедура"],
        extraEnTokens: ["strategy", "solution", "procedure"],
    },

    [phraseKey("krótkoterminowy", "b2-7")]: {
        sk: "Potrzebujemy krótkoterminowych rozwiązań tego problemu.",
        ua: "Нам потрібні короткострокові рішення цієї проблеми.",
        ru: "Нам нужны краткосрочные решения этой проблемы.",
        en: "We need short-term solutions to this problem.",
        uaTokens: ["Нам", "потрібні", "короткострокові", "рішення", "цієї", "проблеми", "."],
        ruTokens: ["Нам", "нужны", "краткосрочные", "решения", "этой", "проблемы", "."],
        enTokens: ["We", "need", "short-term", "solutions", "to", "this", "problem", "."],
        extraUaTokens: ["стратегія", "проєкту", "команда"],
        extraRuTokens: ["стратегия", "проекта", "команда"],
        extraEnTokens: ["strategy", "project", "team"],
    },

    [phraseKey("procedura", "b2-7")]: {
        sk: "Procedura musi być przestrzegana przez wszystkich pracowników.",
        ua: "Процедура повинна виконуватися всіма працівниками.",
        ru: "Процедура должна соблюдаться всеми сотрудниками.",
        en: "The procedure must be followed by all employees.",
        uaTokens: ["Процедура", "повинна", "виконуватися", "всіма", "працівниками", "."],
        ruTokens: ["Процедура", "должна", "соблюдаться", "всеми", "сотрудниками", "."],
        enTokens: ["The", "procedure", "must", "be", "followed", "by", "all", "employees", "."],
        extraUaTokens: ["стратегія", "пріоритетом", "команда"],
        extraRuTokens: ["стратегия", "приоритетом", "команда"],
        extraEnTokens: ["strategy", "priority", "team"],
    },

    [phraseKey("priorytet", "b2-7")]: {
        sk: "Bezpieczeństwo powinno być naszym najwyższym priorytetem.",
        ua: "Безпека повинна бути нашим найвищим пріоритетом.",
        ru: "Безопасность должна быть нашим главным приоритетом.",
        en: "Safety should be our top priority.",
        uaTokens: ["Безпека", "повинна", "бути", "нашим", "найвищим", "пріоритетом", "."],
        ruTokens: ["Безопасность", "должна", "быть", "нашим", "главным", "приоритетом", "."],
        enTokens: ["Safety", "should", "be", "our", "top", "priority", "."],
        extraUaTokens: ["процедура", "стратегія", "команда"],
        extraRuTokens: ["процедура", "стратегия", "команда"],
        extraEnTokens: ["procedure", "strategy", "team"],
    },

    [phraseKey("efektywny", "b2-7")]: {
        sk: "Musimy znaleźć bardziej efektywny sposób pracy.",
        ua: "Ми повинні знайти більш ефективний спосіб роботи.",
        ru: "Мы должны найти более эффективный способ работы.",
        en: "We need to find a more effective way of working.",
        uaTokens: ["Ми", "повинні", "знайти", "більш", "ефективний", "спосіб", "роботи", "."],
        ruTokens: ["Мы", "должны", "найти", "более", "эффективный", "способ", "работы", "."],
        enTokens: ["We", "need", "to", "find", "a", "more", "effective", "way", "of", "working", "."],
        extraUaTokens: ["процедура", "план", "процеси"],
        extraRuTokens: ["процедура", "план", "процессы"],
        extraEnTokens: ["procedure", "plan", "processes"],
    },

    [phraseKey("optymalizować", "b2-7")]: {
        sk: "Firma stara się optymalizować procesy produkcyjne.",
        ua: "Компанія намагається оптимізувати виробничі процеси.",
        ru: "Компания старается оптимизировать производственные процессы.",
        en: "The company tries to optimize production processes.",
        uaTokens: ["Компанія", "намагається", "оптимізувати", "виробничі", "процеси", "."],
        ruTokens: ["Компания", "старается", "оптимизировать", "производственные", "процессы", "."],
        enTokens: ["The", "company", "tries", "to", "optimize", "production", "processes", "."],
        extraUaTokens: ["роботи", "план", "пріоритетом"],
        extraRuTokens: ["работы", "план", "приоритетом"],
        extraEnTokens: ["work", "plan", "priority"],
    },

    [phraseKey("realizować plan", "b2-7")]: {
        sk: "Zespół konsekwentnie realizuje plan działania.",
        ua: "Команда послідовно реалізує план дій.",
        ru: "Команда последовательно реализует план действий.",
        en: "The team consistently carries out the plan.",
        uaTokens: ["Команда", "послідовно", "реалізує", "план", "дій", "."],
        ruTokens: ["Команда", "последовательно", "реализует", "план", "действий", "."],
        enTokens: ["The", "team", "consistently", "carries", "out", "the", "plan", "."],
        uaAltAnswers: [["Команда", "реалізує", "план", "дій", "послідовно", "."]],
        ruAltAnswers: [["Команда", "реализует", "план", "действий", "последовательно", "."]],
        extraUaTokens: ["стратегія", "процедура", "цілей"],
        extraRuTokens: ["стратегия", "процедура", "целей"],
        extraEnTokens: ["strategy", "procedure", "goals"],
    },

    // =========================
    // LESSON 8 — Аналіз і оцінка
    // =========================
    [phraseKey("analiza", "b2-8")]: {
        sk: "Analiza danych pomogła nam podjąć właściwą decyzję.",
        ua: "Аналіз даних допоміг нам прийняти правильне рішення.",
        ru: "Анализ данных помог нам принять правильное решение.",
        en: "Data analysis helped us make the right decision.",
        uaTokens: ["Аналіз", "даних", "допоміг", "нам", "прийняти", "правильне", "рішення", "."],
        ruTokens: ["Анализ", "данных", "помог", "нам", "принять", "правильное", "решение", "."],
        enTokens: ["Data", "analysis", "helped", "us", "make", "the", "right", "decision", "."],
        extraUaTokens: ["результати", "думка", "команда"],
        extraRuTokens: ["результаты", "мнение", "команда"],
        extraEnTokens: ["results", "opinion", "team"],
    },

    [phraseKey("ocena", "b2-8")]: {
        sk: "Ocena sytuacji była trudna, ale konieczna.",
        ua: "Оцінка ситуації була складною, але необхідною.",
        ru: "Оценка ситуации была сложной, но необходимой.",
        en: "The evaluation of the situation was difficult but necessary.",
        uaTokens: ["Оцінка", "ситуації", "була", "складною", ",", "але", "необхідною", "."],
        ruTokens: ["Оценка", "ситуации", "была", "сложной", ",", "но", "необходимой", "."],
        enTokens: ["The", "evaluation", "of", "the", "situation", "was", "difficult", "but", "necessary", "."],
        extraUaTokens: ["аналіз", "результати", "думка"],
        extraRuTokens: ["анализ", "результаты", "мнение"],
        extraEnTokens: ["analysis", "results", "opinion"],
    },

    [phraseKey("porównać", "b2-8")]: {
        sk: "Musimy porównać wyniki z poprzednimi latami.",
        ua: "Ми повинні порівняти результати з попередніми роками.",
        ru: "Мы должны сравнить результаты с предыдущими годами.",
        en: "We need to compare the results with previous years.",
        uaTokens: ["Ми", "повинні", "порівняти", "результати", "з", "попередніми", "роками", "."],
        ruTokens: ["Мы", "должны", "сравнить", "результаты", "с", "предыдущими", "годами", "."],
        enTokens: ["We", "need", "to", "compare", "the", "results", "with", "previous", "years", "."],
        extraUaTokens: ["аналіз", "показник", "компанії"],
        extraRuTokens: ["анализ", "показатель", "компании"],
        extraEnTokens: ["analysis", "indicator", "company"],
    },

    [phraseKey("wynik", "b2-8")]: {
        sk: "Wynik okazał się lepszy, niż się spodziewaliśmy.",
        ua: "Результат виявився кращим, ніж ми очікували.",
        ru: "Результат оказался лучше, чем мы ожидали.",
        en: "The result turned out better than expected.",
        uaTokens: ["Результат", "виявився", "кращим", ",", "ніж", "ми", "очікували", "."],
        ruTokens: ["Результат", "оказался", "лучше", ",", "чем", "мы", "ожидали", "."],
        enTokens: ["The", "result", "turned", "out", "better", "than", "expected", "."],
        extraUaTokens: ["аналіз", "ситуації", "компанії"],
        extraRuTokens: ["анализ", "ситуации", "компании"],
        extraEnTokens: ["analysis", "situation", "company"],
    },

    [phraseKey("wskaźnik", "b2-8")]: {
        sk: "Ten wskaźnik pokazuje rozwój firmy.",
        ua: "Цей показник показує розвиток компанії.",
        ru: "Этот показатель показывает развитие компании.",
        en: "This indicator shows the company's growth.",
        uaTokens: ["Цей", "показник", "показує", "розвиток", "компанії", "."],
        ruTokens: ["Этот", "показатель", "показывает", "развитие", "компании", "."],
        enTokens: ["This", "indicator", "shows", "the", "company's", "growth", "."],
        extraUaTokens: ["тенденція", "аналіз", "результати"],
        extraRuTokens: ["тенденция", "анализ", "результаты"],
        extraEnTokens: ["trend", "analysis", "results"],
    },

    [phraseKey("trend", "b2-8")]: {
        sk: "Trend wzrostowy utrzymuje się już od kilku miesięcy.",
        ua: "Тенденція зростання триває вже кілька місяців.",
        ru: "Тенденция роста сохраняется уже несколько месяцев.",
        en: "The upward trend has continued for several months.",
        uaTokens: ["Тенденція", "зростання", "триває", "вже", "кілька", "місяців", "."],
        ruTokens: ["Тенденция", "роста", "сохраняется", "уже", "несколько", "месяцев", "."],
        enTokens: ["The", "upward", "trend", "has", "continued", "for", "several", "months", "."],
        extraUaTokens: ["показник", "аналіз", "компанії"],
        extraRuTokens: ["показатель", "анализ", "компании"],
        extraEnTokens: ["indicator", "analysis", "company"],
    },

    [phraseKey("ważny", "b2-8")]: {
        sk: "To był bardzo ważny moment dla całego zespołu.",
        ua: "Це був дуже важливий момент для всієї команди.",
        ru: "Это был очень важный момент для всей команды.",
        en: "It was a very important moment for the whole team.",
        uaTokens: ["Це", "був", "дуже", "важливий", "момент", "для", "всієї", "команди", "."],
        ruTokens: ["Это", "был", "очень", "важный", "момент", "для", "всей", "команды", "."],
        enTokens: ["It", "was", "a", "very", "important", "moment", "for", "the", "whole", "team", "."],
        extraUaTokens: ["результат", "аналіз", "думка"],
        extraRuTokens: ["результат", "анализ", "мнение"],
        extraEnTokens: ["result", "analysis", "opinion"],
    },

    [phraseKey("nieistotny", "b2-8")]: {
        sk: "Ten szczegół okazał się całkowicie nieistotny.",
        ua: "Ця деталь виявилася повністю незначною.",
        ru: "Эта деталь оказалась совершенно незначительной.",
        en: "This detail turned out to be completely insignificant.",
        uaTokens: ["Ця", "деталь", "виявилася", "повністю", "незначною", "."],
        ruTokens: ["Эта", "деталь", "оказалась", "совершенно", "незначительной", "."],
        enTokens: ["This", "detail", "turned", "out", "to", "be", "completely", "insignificant", "."],
        extraUaTokens: ["думка", "аналіз", "результати"],
        extraRuTokens: ["мнение", "анализ", "результаты"],
        extraEnTokens: ["opinion", "analysis", "results"],
    },

    [phraseKey("obiektywny", "b2-8")]: {
        sk: "Musimy podejść do tego problemu w sposób obiektywny.",
        ua: "Ми повинні підійти до цієї проблеми об'єктивно.",
        ru: "Мы должны подойти к этой проблеме объективно.",
        en: "We must approach this problem objectively.",
        uaTokens: ["Ми", "повинні", "підійти", "до", "цієї", "проблеми", "об'єктивно", "."],
        ruTokens: ["Мы", "должны", "подойти", "к", "этой", "проблеме", "объективно", "."],
        enTokens: ["We", "must", "approach", "this", "problem", "objectively", "."],
        extraUaTokens: ["думка", "аналіз", "ситуації"],
        extraRuTokens: ["мнение", "анализ", "ситуации"],
        extraEnTokens: ["opinion", "analysis", "situation"],
    },

    [phraseKey("subiektywny", "b2-8")]: {
        sk: "Jego opinia była zbyt subiektywna, aby ją uwzględnić.",
        ua: "Його думка була надто суб'єктивною, щоб її врахувати.",
        ru: "Его мнение было слишком субъективным, чтобы его учитывать.",
        en: "His opinion was too subjective to be considered.",
        uaTokens: ["Його", "думка", "була", "надто", "суб'єктивною", ",", "щоб", "її", "врахувати", "."],
        ruTokens: ["Его", "мнение", "было", "слишком", "субъективным", ",", "чтобы", "его", "учитывать", "."],
        enTokens: ["His", "opinion", "was", "too", "subjective", "to", "be", "considered", "."],
        extraUaTokens: ["об'єктивно", "аналіз", "результати"],
        extraRuTokens: ["объективно", "анализ", "результаты"],
        extraEnTokens: ["objectively", "analysis", "results"],
    },

    // =========================
    // LESSON 9 — Співпраця та команда
    // =========================
    [phraseKey("współpraca", "b2-9")]: {
        sk: "Dobra współpraca jest podstawą sukcesu każdego projektu.",
        ua: "Хороша співпраця є основою успіху кожного проєкту.",
        ru: "Хорошее сотрудничество — основа успеха любого проекта.",
        en: "Good cooperation is the foundation of every project's success.",
        uaTokens: ["Хороша", "співпраця", "є", "основою", "успіху", "кожного", "проєкту", "."],
        ruTokens: ["Хорошее", "сотрудничество", "—", "основа", "успеха", "любого", "проекта", "."],
        enTokens: ["Good", "cooperation", "is", "the", "foundation", "of", "every", "project's", "success", "."],
        extraUaTokens: ["команда", "завдання", "зустріч"],
        extraRuTokens: ["команда", "задачи", "встреча"],
        extraEnTokens: ["team", "tasks", "meeting"],
    },

    [phraseKey("zespół", "b2-9")]: {
        sk: "Zespół pracował razem, aby osiągnąć wspólny cel.",
        ua: "Команда працювала разом, щоб досягти спільної мети.",
        ru: "Команда работала вместе, чтобы достичь общей цели.",
        en: "The team worked together to achieve a common goal.",
        uaTokens: ["Команда", "працювала", "разом", ",", "щоб", "досягти", "спільної", "мети", "."],
        ruTokens: ["Команда", "работала", "вместе", ",", "чтобы", "достичь", "общей", "цели", "."],
        enTokens: ["The", "team", "worked", "together", "to", "achieve", "a", "common", "goal", "."],
        extraUaTokens: ["співпраця", "завдання", "рішення"],
        extraRuTokens: ["сотрудничество", "задачи", "решение"],
        extraEnTokens: ["cooperation", "tasks", "decision"],
    },

    [phraseKey("delegować", "b2-9")]: {
        sk: "Dobry lider potrafi delegować zadania.",
        ua: "Хороший лідер вміє делегувати завдання.",
        ru: "Хороший лидер умеет делегировать задачи.",
        en: "A good leader knows how to delegate tasks.",
        uaTokens: ["Хороший", "лідер", "вміє", "делегувати", "завдання", "."],
        ruTokens: ["Хороший", "лидер", "умеет", "делегировать", "задачи", "."],
        enTokens: ["A", "good", "leader", "knows", "how", "to", "delegate", "tasks", "."],
        extraUaTokens: ["команда", "зустріч", "підтримка"],
        extraRuTokens: ["команда", "встреча", "поддержка"],
        extraEnTokens: ["team", "meeting", "support"],
    },

    [phraseKey("osoba odpowiedzialna", "b2-9")]: {
        sk: "Każde zadanie ma przypisaną osobę odpowiedzialną.",
        ua: "Кожне завдання має відповідальну особу.",
        ru: "У каждой задачи есть ответственное лицо.",
        en: "Each task has a responsible person assigned.",
        uaTokens: ["Кожне", "завдання", "має", "відповідальну", "особу", "."],
        ruTokens: ["У", "каждой", "задачи", "есть", "ответственное", "лицо", "."],
        enTokens: ["Each", "task", "has", "a", "responsible", "person", "assigned", "."],
        extraUaTokens: ["команда", "рішення", "зустріч"],
        extraRuTokens: ["команда", "решение", "встреча"],
        extraEnTokens: ["team", "decision", "meeting"],
    },

    [phraseKey("wspólny cel", "b2-9")]: {
        sk: "Wspólny cel motywuje zespół do działania.",
        ua: "Спільна мета мотивує команду діяти.",
        ru: "Общая цель мотивирует команду действовать.",
        en: "A shared goal motivates the team to act.",
        uaTokens: ["Спільна", "мета", "мотивує", "команду", "діяти", "."],
        ruTokens: ["Общая", "цель", "мотивирует", "команду", "действовать", "."],
        enTokens: ["A", "shared", "goal", "motivates", "the", "team", "to", "act", "."],
        extraUaTokens: ["співпраця", "підтримка", "зустріч"],
        extraRuTokens: ["сотрудничество", "поддержка", "встреча"],
        extraEnTokens: ["cooperation", "support", "meeting"],
    },

    [phraseKey("umówić się", "b2-9")]: {
        sk: "Musimy się umówić na kolejne spotkanie.",
        ua: "Ми повинні домовитися про наступну зустріч.",
        ru: "Мы должны договориться о следующей встрече.",
        en: "We need to arrange the next meeting.",
        uaTokens: ["Ми", "повинні", "домовитися", "про", "наступну", "зустріч", "."],
        ruTokens: ["Мы", "должны", "договориться", "о", "следующей", "встрече", "."],
        enTokens: ["We", "need", "to", "arrange", "the", "next", "meeting", "."],
        extraUaTokens: ["команда", "підтримка", "мета"],
        extraRuTokens: ["команда", "поддержка", "цель"],
        extraEnTokens: ["team", "support", "goal"],
    },

    [phraseKey("koordynować", "b2-9")]: {
        sk: "Ktoś musi koordynować pracę całego zespołu.",
        ua: "Хтось повинен координувати роботу всієї команди.",
        ru: "Кто-то должен координировать работу всей команды.",
        en: "Someone must coordinate the work of the whole team.",
        uaTokens: ["Хтось", "повинен", "координувати", "роботу", "всієї", "команди", "."],
        ruTokens: ["Кто-то", "должен", "координировать", "работу", "всей", "команды", "."],
        enTokens: ["Someone", "must", "coordinate", "the", "work", "of", "the", "whole", "team", "."],
        extraUaTokens: ["співпраця", "підтримка", "завдання"],
        extraRuTokens: ["сотрудничество", "поддержка", "задачи"],
        extraEnTokens: ["cooperation", "support", "tasks"],
    },

    [phraseKey("wsparcie", "b2-9")]: {
        sk: "Wsparcie zespołu było kluczowe w trudnej sytuacji.",
        ua: "Підтримка команди була ключовою у складній ситуації.",
        ru: "Поддержка команды была ключевой в сложной ситуации.",
        en: "Team support was crucial in a difficult situation.",
        uaTokens: ["Підтримка", "команди", "була", "ключовою", "у", "складній", "ситуації", "."],
        ruTokens: ["Поддержка", "команды", "была", "ключевой", "в", "сложной", "ситуации", "."],
        enTokens: ["Team", "support", "was", "crucial", "in", "a", "difficult", "situation", "."],
        extraUaTokens: ["співпраця", "рішення", "зустріч"],
        extraRuTokens: ["сотрудничество", "решение", "встреча"],
        extraEnTokens: ["cooperation", "decision", "meeting"],
    },

    [phraseKey("przyczynić się", "b2-9")]: {
        sk: "Każdy przyczynił się do sukcesu projektu.",
        ua: "Кожен зробив свій внесок у успіх проєкту.",
        ru: "Каждый внёс вклад в успех проекта.",
        en: "Everyone contributed to the success of the project.",
        uaTokens: ["Кожен", "зробив", "свій", "внесок", "у", "успіх", "проєкту", "."],
        ruTokens: ["Каждый", "внёс", "вклад", "в", "успех", "проекта", "."],
        enTokens: ["Everyone", "contributed", "to", "the", "success", "of", "the", "project", "."],
        extraUaTokens: ["команда", "підтримка", "мета"],
        extraRuTokens: ["команда", "поддержка", "цель"],
        extraEnTokens: ["team", "support", "goal"],
    },

    [phraseKey("wspólna decyzja", "b2-9")]: {
        sk: "To była wspólna decyzja całego zespołu.",
        ua: "Це було спільне рішення всієї команди.",
        ru: "Это было совместное решение всей команды.",
        en: "It was a joint decision of the whole team.",
        uaTokens: ["Це", "було", "спільне", "рішення", "всієї", "команди", "."],
        ruTokens: ["Это", "было", "совместное", "решение", "всей", "команды", "."],
        enTokens: ["It", "was", "a", "joint", "decision", "of", "the", "whole", "team", "."],
        extraUaTokens: ["підтримка", "мета", "зустріч"],
        extraRuTokens: ["поддержка", "цель", "встреча"],
        extraEnTokens: ["support", "goal", "meeting"],
    },

    // =========================
    // LESSON 10 — Професійний розвиток
    // =========================
    [phraseKey("rozwój", "b2-10")]: {
        sk: "Rozwój zawodowy wymaga ciągłego uczenia się.",
        ua: "Професійний розвиток вимагає постійного навчання.",
        ru: "Профессиональное развитие требует постоянного обучения.",
        en: "Professional development requires continuous learning.",
        uaTokens: ["Професійний", "розвиток", "вимагає", "постійного", "навчання", "."],
        ruTokens: ["Профессиональное", "развитие", "требует", "постоянного", "обучения", "."],
        enTokens: ["Professional", "development", "requires", "continuous", "learning", "."],
        extraUaTokens: ["знання", "успіху", "результатів"],
        extraRuTokens: ["знания", "успеха", "результатов"],
        extraEnTokens: ["knowledge", "success", "results"],
    },

    [phraseKey("udoskonalić się", "b2-10")]: {
        sk: "Chcę się udoskonalić w swojej pracy.",
        ua: "Я хочу вдосконалитися у своїй роботі.",
        ru: "Я хочу усовершенствоваться в своей работе.",
        en: "I want to improve myself in my work.",
        uaTokens: ["Я", "хочу", "вдосконалитися", "у", "своїй", "роботі", "."],
        ruTokens: ["Я", "хочу", "усовершенствоваться", "в", "своей", "работе", "."],
        enTokens: ["I", "want", "to", "improve", "myself", "in", "my", "work", "."],
        extraUaTokens: ["знання", "успіху", "результатів"],
        extraRuTokens: ["знания", "успеха", "результатов"],
        extraEnTokens: ["knowledge", "success", "results"],
    },

    [phraseKey("pracować nad sobą", "b2-10")]: {
        sk: "Musisz pracować nad sobą, aby osiągnąć sukces.",
        ua: "Ти повинен працювати над собою, щоб досягти успіху.",
        ru: "Ты должен работать над собой, чтобы добиться успеха.",
        en: "You must work on yourself to achieve success.",
        uaTokens: ["Ти", "повинен", "працювати", "над", "собою", ",", "щоб", "досягти", "успіху", "."],
        ruTokens: ["Ты", "должен", "работать", "над", "собой", ",", "чтобы", "добиться", "успеха", "."],
        enTokens: ["You", "must", "work", "on", "yourself", "to", "achieve", "success", "."],
        extraUaTokens: ["розвиток", "знання", "результатів"],
        extraRuTokens: ["развитие", "знания", "результатов"],
        extraEnTokens: ["development", "knowledge", "results"],
    },

    [phraseKey("kompetencja", "b2-10")]: {
        sk: "Kompetencja jest bardzo ważna w tej branży.",
        ua: "Компетентність дуже важлива у цій сфері.",
        ru: "Компетентность очень важна в этой сфере.",
        en: "Competence is very important in this field.",
        uaTokens: ["Компетентність", "дуже", "важлива", "у", "цій", "сфері", "."],
        ruTokens: ["Компетентность", "очень", "важна", "в", "этой", "сфере", "."],
        enTokens: ["Competence", "is", "very", "important", "in", "this", "field", "."],
        extraUaTokens: ["розвиток", "знання", "спеціаліст"],
        extraRuTokens: ["развитие", "знания", "специалист"],
        extraEnTokens: ["development", "knowledge", "specialist"],
    },

    [phraseKey("doświadczony", "b2-10")]: {
        sk: "On jest bardzo doświadczonym specjalistą.",
        ua: "Він дуже досвідчений спеціаліст.",
        ru: "Он очень опытный специалист.",
        en: "He is a very experienced specialist.",
        uaTokens: ["Він", "дуже", "досвідчений", "спеціаліст", "."],
        ruTokens: ["Он", "очень", "опытный", "специалист", "."],
        enTokens: ["He", "is", "a", "very", "experienced", "specialist", "."],
        extraUaTokens: ["знання", "сфері", "розвиток"],
        extraRuTokens: ["знания", "сфере", "развитие"],
        extraEnTokens: ["knowledge", "field", "development"],
    },

    [phraseKey("pogłębiać wiedzę", "b2-10")]: {
        sk: "Chcę pogłębiać swoją wiedzę w tej dziedzinie.",
        ua: "Я хочу поглиблювати свої знання у цій сфері.",
        ru: "Я хочу углублять свои знания в этой области.",
        en: "I want to deepen my knowledge in this field.",
        uaTokens: ["Я", "хочу", "поглиблювати", "свої", "знання", "у", "цій", "сфері", "."],
        ruTokens: ["Я", "хочу", "углублять", "свои", "знания", "в", "этой", "области", "."],
        enTokens: ["I", "want", "to", "deepen", "my", "knowledge", "in", "this", "field", "."],
        extraUaTokens: ["розвиток", "успіху", "результатів"],
        extraRuTokens: ["развитие", "успеха", "результатов"],
        extraEnTokens: ["development", "success", "results"],
    },

    [phraseKey("poprawiać się", "b2-10")]: {
        sk: "Z czasem wszystko będzie się poprawiać.",
        ua: "З часом усе буде покращуватися.",
        ru: "Со временем всё будет улучшаться.",
        en: "Everything will improve over time.",
        uaTokens: ["З", "часом", "усе", "буде", "покращуватися", "."],
        ruTokens: ["Со", "временем", "всё", "будет", "улучшаться", "."],
        enTokens: ["Everything", "will", "improve", "over", "time", "."],
        extraUaTokens: ["розвиток", "результатів", "знання"],
        extraRuTokens: ["развитие", "результатов", "знания"],
        extraEnTokens: ["development", "results", "knowledge"],
    },

    [phraseKey("osiągać wyniki", "b2-10")]: {
        sk: "Firma zaczęła osiągać coraz lepsze wyniki.",
        ua: "Компанія почала досягати дедалі кращих результатів.",
        ru: "Компания начала достигать всё лучших результатов.",
        en: "The company started achieving better and better results.",
        uaTokens: ["Компанія", "почала", "досягати", "дедалі", "кращих", "результатів", "."],
        ruTokens: ["Компания", "начала", "достигать", "всё", "лучших", "результатов", "."],
        enTokens: ["The", "company", "started", "achieving", "better", "and", "better", "results", "."],
        extraUaTokens: ["розвиток", "знання", "успіху"],
        extraRuTokens: ["развитие", "знания", "успеха"],
        extraEnTokens: ["development", "knowledge", "success"],
    },

    [phraseKey("rozwój osobisty", "b2-10")]: {
        sk: "Rozwój osobisty jest ważny dla każdego człowieka.",
        ua: "Особистий розвиток важливий для кожної людини.",
        ru: "Личностный рост важен для каждого человека.",
        en: "Personal growth is important for everyone.",
        uaTokens: ["Особистий", "розвиток", "важливий", "для", "кожної", "людини", "."],
        ruTokens: ["Личностный", "рост", "важен", "для", "каждого", "человека", "."],
        enTokens: ["Personal", "growth", "is", "important", "for", "everyone", "."],
        extraUaTokens: ["розвиток", "знання", "успіху"],
        extraRuTokens: ["развитие", "знания", "успеха"],
        extraEnTokens: ["development", "knowledge", "success"],
    },

    [phraseKey("rozwój zawodowy", "b2-10")]: {
        sk: "Rozwój zawodowy otwiera nowe możliwości.",
        ua: "Професійний розвиток відкриває нові можливості.",
        ru: "Профессиональное развитие открывает новые возможности.",
        en: "Professional growth opens new opportunities.",
        uaTokens: ["Професійний", "розвиток", "відкриває", "нові", "можливості", "."],
        ruTokens: ["Профессиональное", "развитие", "открывает", "новые", "возможности", "."],
        enTokens: ["Professional", "growth", "opens", "new", "opportunities", "."],
        extraUaTokens: ["знання", "успіху", "результатів"],
        extraRuTokens: ["знания", "успеха", "результатов"],
        extraEnTokens: ["knowledge", "success", "results"],
    },
}