import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_B2_BUILD_UA_SENTENCES_4: BuildUaSentenceDict = {
    // =========================
    // LESSON 16 — Фрукти
    // =========================
    [phraseKey("jabłko", "b2-16")]: {
        sk: "To jabłko jest bardzo soczyste i ma przyjemny smak.",
        ua: "Це яблуко дуже соковите і має приємний смак.",
        ru: "Это яблоко очень сочное и имеет приятный вкус.",
        en: "This apple is very juicy and has a pleasant taste.",
        uaTokens: ["Це", "яблуко", "дуже", "соковите", "і", "має", "приємний", "смак", "."],
        ruTokens: ["Это", "яблоко", "очень", "сочное", "и", "имеет", "приятный", "вкус", "."],
        enTokens: ["This", "apple", "is", "very", "juicy", "and", "has", "a", "pleasant", "taste", "."],
        extraUaTokens: ["десерту", "вітамінів", "спрагу"],
        extraRuTokens: ["десерта", "витаминов", "жажду"],
        extraEnTokens: ["dessert", "vitamins", "thirst"],
    },

    [phraseKey("gruszka", "b2-16")]: {
        sk: "Gruszka była dojrzała i idealna do deseru.",
        ua: "Груша була стиглою і ідеальною для десерту.",
        ru: "Груша была спелой и идеальной для десерта.",
        en: "The pear was ripe and perfect for dessert.",
        uaTokens: ["Груша", "була", "стиглою", "і", "ідеальною", "для", "десерту", "."],
        ruTokens: ["Груша", "была", "спелой", "и", "идеальной", "для", "десерта", "."],
        enTokens: ["The", "pear", "was", "ripe", "and", "perfect", "for", "dessert", "."],
        extraUaTokens: ["смак", "джемів", "освіжає"],
        extraRuTokens: ["вкус", "джемов", "освежает"],
        extraEnTokens: ["taste", "jams", "refreshes"],
    },

    [phraseKey("brzoskwinia", "b2-16")]: {
        sk: "Brzoskwinia miała delikatny i słodki smak.",
        ua: "Персик мав ніжний і солодкий смак.",
        ru: "Персик имел нежный и сладкий вкус.",
        en: "The peach had a delicate and sweet flavor.",
        uaTokens: ["Персик", "мав", "ніжний", "і", "солодкий", "смак", "."],
        ruTokens: ["Персик", "имел", "нежный", "и", "сладкий", "вкус", "."],
        enTokens: ["The", "peach", "had", "a", "delicate", "and", "sweet", "flavor", "."],
        extraUaTokens: ["яблуко", "ароматне", "десертів"],
        extraRuTokens: ["яблоко", "ароматное", "десертов"],
        extraEnTokens: ["apple", "aromatic", "desserts"],
    },

    [phraseKey("morela", "b2-16")]: {
        sk: "Morele są często używane do przygotowywania dżemów.",
        ua: "Абрикоси часто використовують для приготування джемів.",
        ru: "Абрикосы часто используют для приготовления джемов.",
        en: "Apricots are often used to make jams.",
        uaTokens: ["Абрикоси", "часто", "використовують", "для", "приготування", "джемів", "."],
        ruTokens: ["Абрикосы", "часто", "используют", "для", "приготовления", "джемов", "."],
        enTokens: ["Apricots", "are", "often", "used", "to", "make", "jams", "."],
        extraUaTokens: ["сливи", "вітамінів", "фрукт"],
        extraRuTokens: ["сливы", "витаминов", "фрукт"],
        extraEnTokens: ["plums", "vitamins", "fruit"],
    },

    [phraseKey("śliwka", "b2-16")]: {
        sk: "Śliwki są idealne do wypieków i deserów.",
        ua: "Сливи ідеально підходять для випічки та десертів.",
        ru: "Сливы идеально подходят для выпечки и десертов.",
        en: "Plums are perfect for baking and desserts.",
        uaTokens: ["Сливи", "ідеально", "підходять", "для", "випічки", "та", "десертів", "."],
        ruTokens: ["Сливы", "идеально", "подходят", "для", "выпечки", "и", "десертов", "."],
        enTokens: ["Plums", "are", "perfect", "for", "baking", "and", "desserts", "."],
        extraUaTokens: ["джемів", "солодкий", "освіжає"],
        extraRuTokens: ["джемов", "сладкий", "освежает"],
        extraEnTokens: ["jams", "sweet", "refreshes"],
    },

    [phraseKey("borówka", "b2-16")]: {
        sk: "Borówki zawierają wiele witamin i są bardzo zdrowe.",
        ua: "Чорниця містить багато вітамінів і дуже корисна.",
        ru: "Черника содержит много витаминов и очень полезна.",
        en: "Blueberries contain many vitamins and are very healthy.",
        uaTokens: ["Чорниця", "містить", "багато", "вітамінів", "і", "дуже", "корисна", "."],
        ruTokens: ["Черника", "содержит", "много", "витаминов", "и", "очень", "полезна", "."],
        enTokens: ["Blueberries", "contain", "many", "vitamins", "and", "are", "very", "healthy", "."],
        extraUaTokens: ["джемів", "соковите", "спрагу"],
        extraRuTokens: ["джемов", "сочное", "жажду"],
        extraEnTokens: ["jams", "juicy", "thirst"],
    },

    [phraseKey("malina", "b2-16")]: {
        sk: "Maliny mają lekko kwaśny, ale przyjemny smak.",
        ua: "Малина має трохи кислий, але приємний смак.",
        ru: "Малина имеет слегка кислый, но приятный вкус.",
        en: "Raspberries have a slightly sour but pleasant taste.",
        uaTokens: ["Малина", "має", "трохи", "кислий", ",", "але", "приємний", "смак", "."],
        ruTokens: ["Малина", "имеет", "слегка", "кислый", ",", "но", "приятный", "вкус", "."],
        enTokens: ["Raspberries", "have", "a", "slightly", "sour", "but", "pleasant", "taste", "."],
        extraUaTokens: ["солодкий", "вітамінів", "ароматне"],
        extraRuTokens: ["сладкий", "витаминов", "ароматное"],
        extraEnTokens: ["sweet", "vitamins", "aromatic"],
    },

    [phraseKey("ananas", "b2-16")]: {
        sk: "Ananas jest egzotycznym owocem o intensywnym smaku.",
        ua: "Ананас — це екзотичний фрукт з інтенсивним смаком.",
        ru: "Ананас — это экзотический фрукт с насыщенным вкусом.",
        en: "Pineapple is an exotic fruit with a strong flavor.",
        uaTokens: ["Ананас", "—", "це", "екзотичний", "фрукт", "з", "інтенсивним", "смаком", "."],
        ruTokens: ["Ананас", "—", "это", "экзотический", "фрукт", "с", "насыщенным", "вкусом", "."],
        enTokens: ["Pineapple", "is", "an", "exotic", "fruit", "with", "a", "strong", "flavor", "."],
        extraUaTokens: ["солодке", "спекотні", "джемів"],
        extraRuTokens: ["сладкое", "жаркие", "джемов"],
        extraEnTokens: ["sweet", "hot", "jams"],
    },

    [phraseKey("mango", "b2-16")]: {
        sk: "Mango jest bardzo słodkie i aromatyczne.",
        ua: "Манго дуже солодке і ароматне.",
        ru: "Манго очень сладкое и ароматное.",
        en: "Mango is very sweet and aromatic.",
        uaTokens: ["Манго", "дуже", "солодке", "і", "ароматне", "."],
        ruTokens: ["Манго", "очень", "сладкое", "и", "ароматное", "."],
        enTokens: ["Mango", "is", "very", "sweet", "and", "aromatic", "."],
        extraUaTokens: ["соковите", "десерту", "освіжає"],
        extraRuTokens: ["сочное", "десерта", "освежает"],
        extraEnTokens: ["juicy", "dessert", "refreshes"],
    },

    [phraseKey("melon", "b2-16")]: {
        sk: "Melon doskonale orzeźwia w upalne dni.",
        ua: "Диня чудово освіжає у спекотні дні.",
        ru: "Дыня отлично освежает в жаркие дни.",
        en: "Melon refreshes perfectly on hot days.",
        uaTokens: ["Диня", "чудово", "освіжає", "у", "спекотні", "дні", "."],
        ruTokens: ["Дыня", "отлично", "освежает", "в", "жаркие", "дни", "."],
        enTokens: ["Melon", "refreshes", "perfectly", "on", "hot", "days", "."],
        extraUaTokens: ["вітамінів", "солодке", "екзотичний"],
        extraRuTokens: ["витаминов", "сладкое", "экзотический"],
        extraEnTokens: ["vitamins", "sweet", "exotic"],
    },

    // =========================
    // LESSON 17 — Овочі
    // =========================
    [phraseKey("marchew", "b2-17")]: {
        sk: "Marchew jest bogata w witaminy i często używana w kuchni.",
        ua: "Морква багата на вітаміни і часто використовується в кухні.",
        ru: "Морковь богата витаминами и часто используется в кухне.",
        en: "Carrots are rich in vitamins and often used in cooking.",
        uaTokens: ["Морква", "багата", "на", "вітаміни", "і", "часто", "використовується", "в", "кухні", "."],
        ruTokens: ["Морковь", "богата", "витаминами", "и", "часто", "используется", "в", "кухне", "."],
        enTokens: ["Carrots", "are", "rich", "in", "vitamins", "and", "often", "used", "in", "cooking", "."],
        extraUaTokens: ["салатів", "страв", "корисний"],
        extraRuTokens: ["салатов", "блюд", "полезен"],
        extraEnTokens: ["salads", "dishes", "healthy"],
    },

    [phraseKey("ogórek", "b2-17")]: {
        sk: "Ogórek jest świeży i idealny do sałatek.",
        ua: "Огірок свіжий і ідеально підходить для салатів.",
        ru: "Огурец свежий и идеально подходит для салатов.",
        en: "Cucumber is fresh and perfect for salads.",
        uaTokens: ["Огірок", "свіжий", "і", "ідеально", "підходить", "для", "салатів", "."],
        ruTokens: ["Огурец", "свежий", "и", "идеально", "подходит", "для", "салатов", "."],
        enTokens: ["Cucumber", "is", "fresh", "and", "perfect", "for", "salads", "."],
        extraUaTokens: ["вітаміни", "кольору", "традиційних"],
        extraRuTokens: ["витамины", "цвета", "традиционных"],
        extraEnTokens: ["vitamins", "color", "traditional"],
    },

    [phraseKey("pomidor", "b2-17")]: {
        sk: "Pomidory są podstawą wielu potraw.",
        ua: "Помідори є основою багатьох страв.",
        ru: "Помидоры являются основой многих блюд.",
        en: "Tomatoes are the base of many dishes.",
        uaTokens: ["Помідори", "є", "основою", "багатьох", "страв", "."],
        ruTokens: ["Помидоры", "являются", "основой", "многих", "блюд", "."],
        enTokens: ["Tomatoes", "are", "the", "base", "of", "many", "dishes", "."],
        extraUaTokens: ["салатів", "інгредієнтом", "смаку"],
        extraRuTokens: ["салатов", "ингредиентом", "вкуса"],
        extraEnTokens: ["salads", "ingredient", "flavor"],
    },

    [phraseKey("papryka", "b2-17")]: {
        sk: "Papryka nadaje potrawom intensywny smak i kolor.",
        ua: "Перець додає стравам інтенсивного смаку та кольору.",
        ru: "Перец придаёт блюдам насыщенный вкус и цвет.",
        en: "Pepper gives dishes a strong flavor and color.",
        uaTokens: ["Перець", "додає", "стравам", "інтенсивного", "смаку", "та", "кольору", "."],
        ruTokens: ["Перец", "придаёт", "блюдам", "насыщенный", "вкус", "и", "цвет", "."],
        enTokens: ["Pepper", "gives", "dishes", "a", "strong", "flavor", "and", "color", "."],
        extraUaTokens: ["салатів", "способами", "традиційних"],
        extraRuTokens: ["салатов", "способами", "традиционных"],
        extraEnTokens: ["salads", "ways", "traditional"],
    },

    [phraseKey("ziemniak", "b2-17")]: {
        sk: "Ziemniaki można przygotować na wiele sposobów.",
        ua: "Картоплю можна приготувати багатьма способами.",
        ru: "Картофель можно приготовить разными способами.",
        en: "Potatoes can be prepared in many ways.",
        uaTokens: ["Картоплю", "можна", "приготувати", "багатьма", "способами", "."],
        ruTokens: ["Картофель", "можно", "приготовить", "разными", "способами", "."],
        enTokens: ["Potatoes", "can", "be", "prepared", "in", "many", "ways", "."],
        extraUaTokens: ["страв", "смаку", "корисний"],
        extraRuTokens: ["блюд", "вкуса", "полезен"],
        extraEnTokens: ["dishes", "flavor", "healthy"],
    },

    [phraseKey("cebula", "b2-17")]: {
        sk: "Cebula jest podstawowym składnikiem wielu potraw.",
        ua: "Цибуля є базовим інгредієнтом багатьох страв.",
        ru: "Лук является основным ингредиентом многих блюд.",
        en: "Onion is a basic ingredient in many dishes.",
        uaTokens: ["Цибуля", "є", "базовим", "інгредієнтом", "багатьох", "страв", "."],
        ruTokens: ["Лук", "является", "основным", "ингредиентом", "многих", "блюд", "."],
        enTokens: ["Onion", "is", "a", "basic", "ingredient", "in", "many", "dishes", "."],
        extraUaTokens: ["способами", "салатів", "здорова"],
        extraRuTokens: ["способами", "салатов", "полезна"],
        extraEnTokens: ["ways", "salads", "healthy"],
    },

    [phraseKey("czosnek", "b2-17")]: {
        sk: "Czosnek nadaje potrawom wyrazisty smak.",
        ua: "Часник надає стравам виразного смаку.",
        ru: "Чеснок придаёт блюдам яркий вкус.",
        en: "Garlic gives dishes a strong flavor.",
        uaTokens: ["Часник", "надає", "стравам", "виразного", "смаку", "."],
        ruTokens: ["Чеснок", "придаёт", "блюдам", "яркий", "вкус", "."],
        enTokens: ["Garlic", "gives", "dishes", "a", "strong", "flavor", "."],
        extraUaTokens: ["інгредієнтом", "кольору", "підходить"],
        extraRuTokens: ["ингредиентом", "цвета", "подходит"],
        extraEnTokens: ["ingredient", "color", "perfect"],
    },

    [phraseKey("bakłażan", "b2-17")]: {
        sk: "Bakłażan jest popularny w kuchni śródziemnomorskiej.",
        ua: "Баклажан популярний у середземноморській кухні.",
        ru: "Баклажан популярен в средиземноморской кухне.",
        en: "Eggplant is popular in Mediterranean cuisine.",
        uaTokens: ["Баклажан", "популярний", "у", "середземноморській", "кухні", "."],
        ruTokens: ["Баклажан", "популярен", "в", "средиземноморской", "кухне", "."],
        enTokens: ["Eggplant", "is", "popular", "in", "Mediterranean", "cuisine", "."],
        extraUaTokens: ["вітаміни", "стравам", "традиційних"],
        extraRuTokens: ["витамины", "блюдам", "традиционных"],
        extraEnTokens: ["vitamins", "dishes", "traditional"],
    },

    [phraseKey("cukinia", "b2-17")]: {
        sk: "Cukinia jest lekkostrawna i zdrowa.",
        ua: "Кабачок легко засвоюється і корисний.",
        ru: "Кабачок легко усваивается и полезен.",
        en: "Zucchini is easy to digest and healthy.",
        uaTokens: ["Кабачок", "легко", "засвоюється", "і", "корисний", "."],
        ruTokens: ["Кабачок", "легко", "усваивается", "и", "полезен", "."],
        enTokens: ["Zucchini", "is", "easy", "to", "digest", "and", "healthy", "."],
        extraUaTokens: ["вітаміни", "смаку", "інгредієнтом"],
        extraRuTokens: ["витамины", "вкуса", "ингредиентом"],
        extraEnTokens: ["vitamins", "flavor", "ingredient"],
    },

    [phraseKey("kapusta", "b2-17")]: {
        sk: "Kapusta jest ważnym składnikiem tradycyjnych potraw.",
        ua: "Капуста є важливим інгредієнтом традиційних страв.",
        ru: "Капуста является важным ингредиентом традиционных блюд.",
        en: "Cabbage is an important ingredient in traditional dishes.",
        uaTokens: ["Капуста", "є", "важливим", "інгредієнтом", "традиційних", "страв", "."],
        ruTokens: ["Капуста", "является", "важным", "ингредиентом", "традиционных", "блюд", "."],
        enTokens: ["Cabbage", "is", "an", "important", "ingredient", "in", "traditional", "dishes", "."],
        extraUaTokens: ["смаку", "способами", "салатів"],
        extraRuTokens: ["вкуса", "способами", "салатов"],
        extraEnTokens: ["flavor", "ways", "salads"],
    },

    // =========================
    // LESSON 18 — Напої
    // =========================
    [phraseKey("woda mineralna", "b2-18")]: {
        sk: "Woda mineralna jest najlepszym wyborem w upalne dni.",
        ua: "Мінеральна вода — найкращий вибір у спекотні дні.",
        ru: "Минеральная вода — лучший выбор в жаркие дни.",
        en: "Mineral water is the best choice on hot days.",
        uaTokens: ["Мінеральна", "вода", "—", "найкращий", "вибір", "у", "спекотні", "дні", "."],
        ruTokens: ["Минеральная", "вода", "—", "лучший", "выбор", "в", "жаркие", "дни", "."],
        enTokens: ["Mineral", "water", "is", "the", "best", "choice", "on", "hot", "days", "."],
        extraUaTokens: ["вітамінів", "чай", "спрагу"],
        extraRuTokens: ["витаминов", "чай", "жажду"],
        extraEnTokens: ["vitamins", "tea", "thirst"],
    },

    [phraseKey("sok", "b2-18")]: {
        sk: "Świeży sok zawiera dużo witamin.",
        ua: "Свіжий сік містить багато вітамінів.",
        ru: "Свежий сок содержит много витаминов.",
        en: "Fresh juice contains many vitamins.",
        uaTokens: ["Свіжий", "сік", "містить", "багато", "вітамінів", "."],
        ruTokens: ["Свежий", "сок", "содержит", "много", "витаминов", "."],
        enTokens: ["Fresh", "juice", "contains", "many", "vitamins", "."],
        extraUaTokens: ["спекотні", "чай", "смак"],
        extraRuTokens: ["жаркие", "чай", "вкус"],
        extraEnTokens: ["hot", "tea", "taste"],
    },

    [phraseKey("herbata", "b2-18")]: {
        sk: "Wieczorem lubię pić herbatę, aby się zrelaksować.",
        ua: "Ввечері я люблю пити чай, щоб розслабитися.",
        ru: "Вечером я люблю пить чай, чтобы расслабиться.",
        en: "In the evening I like to drink tea to relax.",
        uaTokens: ["Ввечері", "я", "люблю", "пити", "чай", ",", "щоб", "розслабитися", "."],
        ruTokens: ["Вечером", "я", "люблю", "пить", "чай", ",", "чтобы", "расслабиться", "."],
        enTokens: ["In", "the", "evening", "I", "like", "to", "drink", "tea", "to", "relax", "."],
        extraUaTokens: ["каву", "вітамінів", "вибір"],
        extraRuTokens: ["кофе", "витаминов", "выбор"],
        extraEnTokens: ["coffee", "vitamins", "choice"],
    },

    [phraseKey("kawa", "b2-18")]: {
        sk: "Rano zawsze piję kawę, aby się obudzić.",
        ua: "Вранці я завжди п’ю каву, щоб прокинутися.",
        ru: "Утром я всегда пью кофе, чтобы проснуться.",
        en: "I always drink coffee in the morning to wake up.",
        uaTokens: ["Вранці", "я", "завжди", "п’ю", "каву", ",", "щоб", "прокинутися", "."],
        ruTokens: ["Утром", "я", "всегда", "пью", "кофе", ",", "чтобы", "проснуться", "."],
        enTokens: ["I", "always", "drink", "coffee", "in", "the", "morning", "to", "wake", "up", "."],
        extraUaTokens: ["чай", "ароматне", "вечері"],
        extraRuTokens: ["чай", "ароматный", "ужину"],
        extraEnTokens: ["tea", "aromatic", "dinner"],
    },

    [phraseKey("espresso", "b2-18")]: {
        sk: "Espresso jest mocne i aromatyczne.",
        ua: "Еспресо міцне і ароматне.",
        ru: "Эспрессо крепкий и ароматный.",
        en: "Espresso is strong and aromatic.",
        uaTokens: ["Еспресо", "міцне", "і", "ароматне", "."],
        ruTokens: ["Эспрессо", "крепкий", "и", "ароматный", "."],
        enTokens: ["Espresso", "is", "strong", "and", "aromatic", "."],
        extraUaTokens: ["каву", "пінку", "смак"],
        extraRuTokens: ["кофе", "пенку", "вкус"],
        extraEnTokens: ["coffee", "foam", "taste"],
    },

    [phraseKey("cappuccino", "b2-18")]: {
        sk: "Cappuccino ma delikatną piankę i łagodny smak.",
        ua: "Капучино має ніжну пінку і м’який смак.",
        ru: "Капучино имеет нежную пенку и мягкий вкус.",
        en: "Cappuccino has delicate foam and a mild taste.",
        uaTokens: ["Капучино", "має", "ніжну", "пінку", "і", "м’який", "смак", "."],
        ruTokens: ["Капучино", "имеет", "нежную", "пенку", "и", "мягкий", "вкус", "."],
        enTokens: ["Cappuccino", "has", "delicate", "foam", "and", "a", "mild", "taste", "."],
        extraUaTokens: ["каву", "ароматне", "спрагу"],
        extraRuTokens: ["кофе", "ароматный", "жажду"],
        extraEnTokens: ["coffee", "aromatic", "thirst"],
    },

    [phraseKey("lemoniada", "b2-18")]: {
        sk: "Lemoniada doskonale gasi pragnienie.",
        ua: "Лимонад чудово втамовує спрагу.",
        ru: "Лимонад отлично утоляет жажду.",
        en: "Lemonade quenches thirst perfectly.",
        uaTokens: ["Лимонад", "чудово", "втамовує", "спрагу", "."],
        ruTokens: ["Лимонад", "отлично", "утоляет", "жажду", "."],
        enTokens: ["Lemonade", "quenches", "thirst", "perfectly", "."],
        extraUaTokens: ["вода", "спекотні", "смак"],
        extraRuTokens: ["вода", "жаркие", "вкус"],
        extraEnTokens: ["water", "hot", "taste"],
    },

    [phraseKey("piwo", "b2-18")]: {
        sk: "Piwo jest popularnym napojem w wielu krajach.",
        ua: "Пиво є популярним напоєм у багатьох країнах.",
        ru: "Пиво является популярным напитком во многих странах.",
        en: "Beer is a popular drink in many countries.",
        uaTokens: ["Пиво", "є", "популярним", "напоєм", "у", "багатьох", "країнах", "."],
        ruTokens: ["Пиво", "является", "популярным", "напитком", "во", "многих", "странах", "."],
        enTokens: ["Beer", "is", "a", "popular", "drink", "in", "many", "countries", "."],
        extraUaTokens: ["вода", "вечері", "коктейль"],
        extraRuTokens: ["вода", "ужину", "коктейль"],
        extraEnTokens: ["water", "dinner", "cocktail"],
    },

    [phraseKey("wino", "b2-18")]: {
        sk: "Wino często podaje się do kolacji.",
        ua: "Вино часто подають до вечері.",
        ru: "Вино часто подают к ужину.",
        en: "Wine is often served with dinner.",
        uaTokens: ["Вино", "часто", "подають", "до", "вечері", "."],
        ruTokens: ["Вино", "часто", "подают", "к", "ужину", "."],
        enTokens: ["Wine", "is", "often", "served", "with", "dinner", "."],
        extraUaTokens: ["пиво", "каву", "спрагу"],
        extraRuTokens: ["пиво", "кофе", "жажду"],
        extraEnTokens: ["beer", "coffee", "thirst"],
    },

    [phraseKey("koktajl", "b2-18")]: {
        sk: "Koktajl owocowy jest zdrowy i smaczny.",
        ua: "Фруктовий коктейль корисний і смачний.",
        ru: "Фруктовый коктейль полезный и вкусный.",
        en: "A fruit cocktail is healthy and tasty.",
        uaTokens: ["Фруктовий", "коктейль", "корисний", "і", "смачний", "."],
        ruTokens: ["Фруктовый", "коктейль", "полезный", "и", "вкусный", "."],
        enTokens: ["A", "fruit", "cocktail", "is", "healthy", "and", "tasty", "."],
        extraUaTokens: ["вітамінів", "вода", "вечері"],
        extraRuTokens: ["витаминов", "вода", "ужину"],
        extraEnTokens: ["vitamins", "water", "dinner"],
    },

    // =========================
    // LESSON 19 — Емоції
    // =========================
    [phraseKey("lęk", "b2-19")]: {
        sk: "Lęk może wpływać na nasze decyzje.",
        ua: "Тривога може впливати на наші рішення.",
        ru: "Тревога может влиять на наши решения.",
        en: "Anxiety can affect our decisions.",
        uaTokens: ["Тривога", "може", "впливати", "на", "наші", "рішення", "."],
        ruTokens: ["Тревога", "может", "влиять", "на", "наши", "решения", "."],
        enTokens: ["Anxiety", "can", "affect", "our", "decisions", "."],
        extraUaTokens: ["розчарування", "полегшення", "емоції"],
        extraRuTokens: ["разочарование", "облегчение", "эмоции"],
        extraEnTokens: ["disappointment", "relief", "emotions"],
    },

    [phraseKey("rozczarowanie", "b2-19")]: {
        sk: "Czułem rozczarowanie po tej decyzji.",
        ua: "Я відчував розчарування після цього рішення.",
        ru: "Я чувствовал разочарование после этого решения.",
        en: "I felt disappointment after that decision.",
        uaTokens: ["Я", "відчував", "розчарування", "після", "цього", "рішення", "."],
        ruTokens: ["Я", "чувствовал", "разочарование", "после", "этого", "решения", "."],
        enTokens: ["I", "felt", "disappointment", "after", "that", "decision", "."],
        extraUaTokens: ["тривога", "полегшення", "реакція"],
        extraRuTokens: ["тревога", "облегчение", "реакция"],
        extraEnTokens: ["anxiety", "relief", "reaction"],
    },

    [phraseKey("wzruszenie", "b2-19")]: {
        sk: "Film wywołał u mnie silne wzruszenie.",
        ua: "Фільм викликав у мене сильне зворушення.",
        ru: "Фильм вызвал у меня сильное волнение.",
        en: "The film moved me deeply.",
        uaTokens: ["Фільм", "викликав", "у", "мене", "сильне", "зворушення", "."],
        ruTokens: ["Фильм", "вызвал", "у", "меня", "сильное", "волнение", "."],
        enTokens: ["The", "film", "moved", "me", "deeply", "."],
        extraUaTokens: ["реакція", "розчарування", "комфорт"],
        extraRuTokens: ["реакция", "разочарование", "благополучие"],
        extraEnTokens: ["reaction", "disappointment", "well-being"],
    },

    [phraseKey("ulga", "b2-19")]: {
        sk: "Poczułem ulgę, gdy problem został rozwiązany.",
        ua: "Я відчув полегшення, коли проблему вирішили.",
        ru: "Я почувствовал облегчение, когда проблему решили.",
        en: "I felt relief when the problem was solved.",
        uaTokens: ["Я", "відчув", "полегшення", ",", "коли", "проблему", "вирішили", "."],
        ruTokens: ["Я", "почувствовал", "облегчение", ",", "когда", "проблему", "решили", "."],
        enTokens: ["I", "felt", "relief", "when", "the", "problem", "was", "solved", "."],
        extraUaTokens: ["тривога", "розчарування", "виснаження"],
        extraRuTokens: ["тревога", "разочарование", "истощение"],
        extraEnTokens: ["anxiety", "disappointment", "exhaustion"],
    },

    [phraseKey("obrzydzenie", "b2-19")]: {
        sk: "To wywołało u niego obrzydzenie.",
        ua: "Це викликало у нього відразу.",
        ru: "Это вызвало у него отвращение.",
        en: "It caused him disgust.",
        uaTokens: ["Це", "викликало", "у", "нього", "відразу", "."],
        ruTokens: ["Это", "вызвало", "у", "него", "отвращение", "."],
        enTokens: ["It", "caused", "him", "disgust", "."],
        extraUaTokens: ["зворушення", "реакція", "емоції"],
        extraRuTokens: ["волнение", "реакция", "эмоции"],
        extraEnTokens: ["emotion", "reaction", "emotions"],
    },

    [phraseKey("rozdrażniony", "b2-19")]: {
        sk: "Był rozdrażniony po ciężkim dniu pracy.",
        ua: "Він був роздратований після важкого робочого дня.",
        ru: "Он был раздражён после тяжёлого рабочего дня.",
        en: "He was irritated after a long day at work.",
        uaTokens: ["Він", "був", "роздратований", "після", "важкого", "робочого", "дня", "."],
        ruTokens: ["Он", "был", "раздражён", "после", "тяжёлого", "рабочего", "дня", "."],
        enTokens: ["He", "was", "irritated", "after", "a", "long", "day", "at", "work", "."],
        extraUaTokens: ["виснаження", "тривога", "полегшення"],
        extraRuTokens: ["истощение", "тревога", "облегчение"],
        extraEnTokens: ["exhaustion", "anxiety", "relief"],
    },

    [phraseKey("wyczerpanie", "b2-19")]: {
        sk: "Czułem wyczerpanie po intensywnym treningu.",
        ua: "Я відчував виснаження після інтенсивного тренування.",
        ru: "Я чувствовал истощение после интенсивной тренировки.",
        en: "I felt exhausted after intense training.",
        uaTokens: ["Я", "відчував", "виснаження", "після", "інтенсивного", "тренування", "."],
        ruTokens: ["Я", "чувствовал", "истощение", "после", "интенсивной", "тренировки", "."],
        enTokens: ["I", "felt", "exhausted", "after", "intense", "training", "."],
        extraUaTokens: ["роздратований", "полегшення", "емоції"],
        extraRuTokens: ["раздражён", "облегчение", "эмоции"],
        extraEnTokens: ["irritated", "relief", "emotions"],
    },

    [phraseKey("reakcja emocjonalna", "b2-19")]: {
        sk: "To była silna reakcja emocjonalna.",
        ua: "Це була сильна емоційна реакція.",
        ru: "Это была сильная эмоциональная реакция.",
        en: "It was a strong emotional reaction.",
        uaTokens: ["Це", "була", "сильна", "емоційна", "реакція", "."],
        ruTokens: ["Это", "была", "сильная", "эмоциональная", "реакция", "."],
        enTokens: ["It", "was", "a", "strong", "emotional", "reaction", "."],
        extraUaTokens: ["зворушення", "відразу", "емоції"],
        extraRuTokens: ["волнение", "отвращение", "эмоции"],
        extraEnTokens: ["emotion", "disgust", "emotions"],
    },

    [phraseKey("dobre samopoczucie psychiczne", "b2-19")]: {
        sk: "Dobre samopoczucie psychiczne jest bardzo ważne.",
        ua: "Психологічний комфорт дуже важливий.",
        ru: "Психологическое благополучие очень важно.",
        en: "Mental well-being is very important.",
        uaTokens: ["Психологічний", "комфорт", "дуже", "важливий", "."],
        ruTokens: ["Психологическое", "благополучие", "очень", "важно", "."],
        enTokens: ["Mental", "well-being", "is", "very", "important", "."],
        extraUaTokens: ["емоції", "тривога", "реакція"],
        extraRuTokens: ["эмоции", "тревога", "реакция"],
        extraEnTokens: ["emotions", "anxiety", "reaction"],
    },

    [phraseKey("tłumić emocje", "b2-19")]: {
        sk: "Nie powinieneś tłumić emocji.",
        ua: "Ти не повинен пригнічувати емоції.",
        ru: "Ты не должен подавлять эмоции.",
        en: "You should not suppress emotions.",
        uaTokens: ["Ти", "не", "повинен", "пригнічувати", "емоції", "."],
        ruTokens: ["Ты", "не", "должен", "подавлять", "эмоции", "."],
        enTokens: ["You", "should", "not", "suppress", "emotions", "."],
        extraUaTokens: ["комфорт", "реакція", "розчарування"],
        extraRuTokens: ["благополучие", "реакция", "разочарование"],
        extraEnTokens: ["well-being", "reaction", "disappointment"],
    },

    // =========================
    // LESSON 20 — Культура
    // =========================
    [phraseKey("sztuka", "b2-20")]: {
        sk: "Sztuka pozwala wyrażać emocje i idee.",
        ua: "Мистецтво дозволяє виражати емоції та ідеї.",
        ru: "Искусство позволяет выражать эмоции и идеи.",
        en: "Art allows expressing emotions and ideas.",
        uaTokens: ["Мистецтво", "дозволяє", "виражати", "емоції", "та", "ідеї", "."],
        ruTokens: ["Искусство", "позволяет", "выражать", "эмоции", "и", "идеи", "."],
        enTokens: ["Art", "allows", "expressing", "emotions", "and", "ideas", "."],
        extraUaTokens: ["виставка", "театр", "стиль"],
        extraRuTokens: ["выставка", "театр", "стиль"],
        extraEnTokens: ["exhibition", "theater", "style"],
    },

    [phraseKey("dzieło sztuki", "b2-20")]: {
        sk: "To dzieło sztuki jest bardzo znane.",
        ua: "Цей твір мистецтва дуже відомий.",
        ru: "Это произведение искусства очень известно.",
        en: "This work of art is very famous.",
        uaTokens: ["Цей", "твір", "мистецтва", "дуже", "відомий", "."],
        ruTokens: ["Это", "произведение", "искусства", "очень", "известно", "."],
        enTokens: ["This", "work", "of", "art", "is", "very", "famous", "."],
        extraUaTokens: ["галерея", "інтерпретацію", "публіка"],
        extraRuTokens: ["галерея", "интерпретацию", "публика"],
        extraEnTokens: ["gallery", "interpretation", "audience"],
    },

    [phraseKey("wystawa", "b2-20")]: {
        sk: "Wystawa przyciągnęła wielu zwiedzających.",
        ua: "Виставка привабила багато відвідувачів.",
        ru: "Выставка привлекла много посетителей.",
        en: "The exhibition attracted many visitors.",
        uaTokens: ["Виставка", "привабила", "багато", "відвідувачів", "."],
        ruTokens: ["Выставка", "привлекла", "много", "посетителей", "."],
        enTokens: ["The", "exhibition", "attracted", "many", "visitors", "."],
        extraUaTokens: ["галерея", "твори", "досвід"],
        extraRuTokens: ["галерея", "произведения", "опыт"],
        extraEnTokens: ["gallery", "works", "experience"],
    },

    [phraseKey("galeria", "b2-20")]: {
        sk: "Galeria prezentuje nowoczesne dzieła sztuki.",
        ua: "Галерея представляє сучасні твори мистецтва.",
        ru: "Галерея представляет современные произведения искусства.",
        en: "The gallery presents modern works of art.",
        uaTokens: ["Галерея", "представляє", "сучасні", "твори", "мистецтва", "."],
        ruTokens: ["Галерея", "представляет", "современные", "произведения", "искусства", "."],
        enTokens: ["The", "gallery", "presents", "modern", "works", "of", "art", "."],
        extraUaTokens: ["виставка", "стиль", "інтерпретацію"],
        extraRuTokens: ["выставка", "стиль", "интерпретацию"],
        extraEnTokens: ["exhibition", "style", "interpretation"],
    },

    [phraseKey("teatr", "b2-20")]: {
        sk: "Teatr oferuje różnorodne przedstawienia.",
        ua: "Театр пропонує різноманітні вистави.",
        ru: "Театр предлагает разнообразные представления.",
        en: "The theater offers various performances.",
        uaTokens: ["Театр", "пропонує", "різноманітні", "вистави", "."],
        ruTokens: ["Театр", "предлагает", "разнообразные", "представления", "."],
        enTokens: ["The", "theater", "offers", "various", "performances", "."],
        extraUaTokens: ["публіка", "емоційною", "стиль"],
        extraRuTokens: ["публика", "эмоциональным", "стиль"],
        extraEnTokens: ["audience", "emotional", "style"],
    },

    [phraseKey("przedstawienie", "b2-20")]: {
        sk: "Przedstawienie było bardzo emocjonujące.",
        ua: "Вистава була дуже емоційною.",
        ru: "Представление было очень эмоциональным.",
        en: "The performance was very emotional.",
        uaTokens: ["Вистава", "була", "дуже", "емоційною", "."],
        ruTokens: ["Представление", "было", "очень", "эмоциональным", "."],
        enTokens: ["The", "performance", "was", "very", "emotional", "."],
        extraUaTokens: ["театр", "оплесками", "досвід"],
        extraRuTokens: ["театр", "аплодисментами", "опыт"],
        extraEnTokens: ["theater", "applause", "experience"],
    },

    [phraseKey("publiczność", "b2-20")]: {
        sk: "Publiczność nagrodziła artystów oklaskami.",
        ua: "Публіка нагородила артистів оплесками.",
        ru: "Публика наградила артистов аплодисментами.",
        en: "The audience rewarded the artists with applause.",
        uaTokens: ["Публіка", "нагородила", "артистів", "оплесками", "."],
        ruTokens: ["Публика", "наградила", "артистов", "аплодисментами", "."],
        enTokens: ["The", "audience", "rewarded", "the", "artists", "with", "applause", "."],
        extraUaTokens: ["вистава", "галерея", "стиль"],
        extraRuTokens: ["представление", "галерея", "стиль"],
        extraEnTokens: ["performance", "gallery", "style"],
    },

    [phraseKey("styl artystyczny", "b2-20")]: {
        sk: "Ten styl artystyczny jest bardzo charakterystyczny.",
        ua: "Цей художній стиль дуже характерний.",
        ru: "Этот художественный стиль очень характерный.",
        en: "This artistic style is very distinctive.",
        uaTokens: ["Цей", "художній", "стиль", "дуже", "характерний", "."],
        ruTokens: ["Этот", "художественный", "стиль", "очень", "характерный", "."],
        enTokens: ["This", "artistic", "style", "is", "very", "distinctive", "."],
        extraUaTokens: ["твір", "галерея", "інтерпретацію"],
        extraRuTokens: ["произведение", "галерея", "интерпретацию"],
        extraEnTokens: ["work", "gallery", "interpretation"],
    },

    [phraseKey("interpretacja", "b2-20")]: {
        sk: "Każdy może mieć własną interpretację tego dzieła.",
        ua: "Кожен може мати власну інтерпретацію цього твору.",
        ru: "Каждый может иметь свою интерпретацию этого произведения.",
        en: "Everyone can have their own interpretation of this work.",
        uaTokens: ["Кожен", "може", "мати", "власну", "інтерпретацію", "цього", "твору", "."],
        ruTokens: ["Каждый", "может", "иметь", "свою", "интерпретацию", "этого", "произведения", "."],
        enTokens: ["Everyone", "can", "have", "their", "own", "interpretation", "of", "this", "work", "."],
        extraUaTokens: ["стиль", "мистецтва", "відвідувачів"],
        extraRuTokens: ["стиль", "искусства", "посетителей"],
        extraEnTokens: ["style", "art", "visitors"],
    },

    [phraseKey("doświadczenie kulturowe", "b2-20")]: {
        sk: "To było niezapomniane doświadczenie kulturowe.",
        ua: "Це був незабутній культурний досвід.",
        ru: "Это был незабываемый культурный опыт.",
        en: "It was an unforgettable cultural experience.",
        uaTokens: ["Це", "був", "незабутній", "культурний", "досвід", "."],
        ruTokens: ["Это", "был", "незабываемый", "культурный", "опыт", "."],
        enTokens: ["It", "was", "an", "unforgettable", "cultural", "experience", "."],
        extraUaTokens: ["виставка", "театр", "твір"],
        extraRuTokens: ["выставка", "театр", "произведение"],
        extraEnTokens: ["exhibition", "theater", "work"],
    },
};