import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_B2_BUILD_UA_SENTENCES_6: BuildUaSentenceDict = {
    // =========================
    // LESSON 26 — Психологія людини
    // =========================
    [phraseKey("autorefleksja", "b2-26")]: {
        sk: "Autorefleksja pomaga lepiej zrozumieć własne zachowanie i emocje.",
        ua: "Саморефлексія допомагає краще зрозуміти власну поведінку та емоції.",
        ru: "Саморефлексия помогает лучше понять собственное поведение и эмоции.",
        en: "Self-reflection helps to better understand one's behavior and emotions.",
        uaTokens: ["Саморефлексія", "допомагає", "краще", "зрозуміти", "власну", "поведінку", "та", "емоції", "."],
        ruTokens: ["Саморефлексия", "помогает", "лучше", "понять", "собственное", "поведение", "и", "эмоции", "."],
        enTokens: ["Self-reflection", "helps", "to", "better", "understand", "one's", "behavior", "and", "emotions", "."],
        extraUaTokens: ["людини", "характер", "реакцію"],
        extraRuTokens: ["человека", "характер", "реакцию"],
        extraEnTokens: ["person", "character", "reaction"],
    },

    [phraseKey("konflikt wewnętrzny", "b2-26")]: {
        sk: "Przez długi czas odczuwał konflikt wewnętrzny i nie potrafił podjąć decyzji.",
        ua: "Довгий час він відчував внутрішній конфлікт і не міг ухвалити рішення.",
        ru: "Долгое время он ощущал внутренний конфликт и не мог принять решение.",
        en: "For a long time he felt an inner conflict and could not make a decision.",
        uaTokens: ["Довгий", "час", "він", "відчував", "внутрішній", "конфлікт", "і", "не", "міг", "ухвалити", "рішення", "."],
        ruTokens: ["Долгое", "время", "он", "ощущал", "внутренний", "конфликт", "и", "не", "мог", "принять", "решение", "."],
        enTokens: ["For", "a", "long", "time", "he", "felt", "an", "inner", "conflict", "and", "could", "not", "make", "a", "decision", "."],
        extraUaTokens: ["тиск", "емоції", "сумніви"],
        extraRuTokens: ["давление", "эмоции", "сомнения"],
        extraEnTokens: ["pressure", "emotions", "doubts"],
    },

    [phraseKey("samokontrola", "b2-26")]: {
        sk: "W trudnych sytuacjach samokontrola jest ważniejsza niż impulsywna reakcja.",
        ua: "У складних ситуаціях самоконтроль важливіший за імпульсивну реакцію.",
        ru: "В трудных ситуациях самоконтроль важнее импульсивной реакции.",
        en: "In difficult situations, self-control is more important than an impulsive reaction.",
        uaTokens: ["У", "складних", "ситуаціях", "самоконтроль", "важливіший", "за", "імпульсивну", "реакцію", "."],
        ruTokens: ["В", "трудных", "ситуациях", "самоконтроль", "важнее", "импульсивной", "реакции", "."],
        enTokens: ["In", "difficult", "situations", ",", "self-control", "is", "more", "important", "than", "an", "impulsive", "reaction", "."],
        extraUaTokens: ["поведінка", "рішення", "емоції"],
        extraRuTokens: ["поведение", "решение", "эмоции"],
        extraEnTokens: ["behavior", "decision", "emotions"],
    },

    [phraseKey("równowaga psychiczna", "b2-26")]: {
        sk: "Równowaga psychiczna jest niezbędna, aby radzić sobie ze stresem.",
        ua: "Психологічна рівновага необхідна, щоб справлятися зі стресом.",
        ru: "Душевное равновесие необходимо, чтобы справляться со стрессом.",
        en: "Mental balance is essential to cope with stress.",
        uaTokens: ["Психологічна", "рівновага", "необхідна", ",", "щоб", "справлятися", "зі", "стресом", "."],
        ruTokens: ["Душевное", "равновесие", "необходимо", ",", "чтобы", "справляться", "со", "стрессом", "."],
        enTokens: ["Mental", "balance", "is", "essential", "to", "cope", "with", "stress", "."],
        extraUaTokens: ["спокій", "емоції", "напругу"],
        extraRuTokens: ["спокойствие", "эмоции", "напряжение"],
        extraEnTokens: ["calm", "emotions", "tension"],
    },

    [phraseKey("podświadomość", "b2-26")]: {
        sk: "Niektóre decyzje podejmujemy pod wpływem podświadomości, nawet jeśli tego nie zauważamy.",
        ua: "Деякі рішення ми ухвалюємо під впливом підсвідомості, навіть якщо цього не помічаємо.",
        ru: "Некоторые решения мы принимаем под влиянием подсознания, даже если этого не замечаем.",
        en: "Some decisions are made under the influence of the subconscious, even if we do not notice it.",
        uaTokens: ["Деякі", "рішення", "ми", "ухвалюємо", "під", "впливом", "підсвідомості", ",", "навіть", "якщо", "цього", "не", "помічаємо", "."],
        ruTokens: ["Некоторые", "решения", "мы", "принимаем", "под", "влиянием", "подсознания", ",", "даже", "если", "этого", "не", "замечаем", "."],
        enTokens: ["Some", "decisions", "are", "made", "under", "the", "influence", "of", "the", "subconscious", ",", "even", "if", "we", "do", "not", "notice", "it", "."],
        extraUaTokens: ["думки", "мозку", "вибору"],
        extraRuTokens: ["мысли", "мозга", "выбора"],
        extraEnTokens: ["thoughts", "brain", "choice"],
    },

    [phraseKey("wewnętrzna presja", "b2-26")]: {
        sk: "Wewnętrzna presja sprawiała, że ciągle czuł się niewystarczająco dobry.",
        ua: "Внутрішній тиск змушував його постійно почуватися недостатньо хорошим.",
        ru: "Внутреннее давление заставляло его постоянно чувствовать себя недостаточно хорошим.",
        en: "Inner pressure made him constantly feel not good enough.",
        uaTokens: ["Внутрішній", "тиск", "змушував", "його", "постійно", "почуватися", "недостатньо", "хорошим", "."],
        ruTokens: ["Внутреннее", "давление", "заставляло", "его", "постоянно", "чувствовать", "себя", "недостаточно", "хорошим", "."],
        enTokens: ["Inner", "pressure", "made", "him", "constantly", "feel", "not", "good", "enough", "."],
        extraUaTokens: ["стрес", "самооцінку", "сумніви"],
        extraRuTokens: ["стресс", "самооценку", "сомнения"],
        extraEnTokens: ["stress", "self-esteem", "doubts"],
    },

    [phraseKey("granica osobista", "b2-26")]: {
        sk: "Każdy ma prawo wyznaczać własną granicę osobistą i oczekiwać jej szacunku.",
        ua: "Кожен має право встановлювати власні особисті межі й очікувати поваги до них.",
        ru: "Каждый имеет право устанавливать личные границы и ожидать уважения к ним.",
        en: "Everyone has the right to set a personal boundary and expect it to be respected.",
        uaTokens: ["Кожен", "має", "право", "встановлювати", "власні", "особисті", "межі", "й", "очікувати", "поваги", "до", "них", "."],
        ruTokens: ["Каждый", "имеет", "право", "устанавливать", "личные", "границы", "и", "ожидать", "уважения", "к", "ним", "."],
        enTokens: ["Everyone", "has", "the", "right", "to", "set", "a", "personal", "boundary", "and", "expect", "it", "to", "be", "respected", "."],
        extraUaTokens: ["людей", "відносинах", "простір"],
        extraRuTokens: ["людей", "отношениях", "пространство"],
        extraEnTokens: ["people", "relationships", "space"],
    },

    [phraseKey("odporność psychiczna", "b2-26")]: {
        sk: "Odporność psychiczna pomaga przetrwać kryzysy i nie poddawać się zbyt łatwo.",
        ua: "Психологічна стійкість допомагає пережити кризи й не здаватися надто легко.",
        ru: "Психологическая устойчивость помогает пережить кризисы и не сдаваться слишком легко.",
        en: "Mental resilience helps to survive crises and not give up too easily.",
        uaTokens: ["Психологічна", "стійкість", "допомагає", "пережити", "кризи", "й", "не", "здаватися", "надто", "легко", "."],
        ruTokens: ["Психологическая", "устойчивость", "помогает", "пережить", "кризисы", "и", "не", "сдаваться", "слишком", "легко", "."],
        enTokens: ["Mental", "resilience", "helps", "to", "survive", "crises", "and", "not", "give", "up", "too", "easily", "."],
        extraUaTokens: ["стрес", "сила", "характер"],
        extraRuTokens: ["стресс", "сила", "характер"],
        extraEnTokens: ["stress", "strength", "character"],
    },

    [phraseKey("stan psychiczny", "b2-26")]: {
        sk: "Jego stan psychiczny poprawił się, gdy zaczął regularnie odpoczywać.",
        ua: "Його психічний стан покращився, коли він почав регулярно відпочивати.",
        ru: "Его психическое состояние улучшилось, когда он начал регулярно отдыхать.",
        en: "His mental state improved when he started resting regularly.",
        uaTokens: ["Його", "психічний", "стан", "покращився", ",", "коли", "він", "почав", "регулярно", "відпочивати", "."],
        ruTokens: ["Его", "психическое", "состояние", "улучшилось", ",", "когда", "он", "начал", "регулярно", "отдыхать", "."],
        enTokens: ["His", "mental", "state", "improved", "when", "he", "started", "resting", "regularly", "."],
        extraUaTokens: ["здоров’я", "сон", "стрес"],
        extraRuTokens: ["здоровье", "сон", "стресс"],
        extraEnTokens: ["health", "sleep", "stress"],
    },

    [phraseKey("samoświadomość", "b2-26")]: {
        sk: "Samoświadomość pozwala zauważyć własne słabości i świadomie nad nimi pracować.",
        ua: "Самоусвідомлення дозволяє помічати власні слабкості й свідомо над ними працювати.",
        ru: "Самоосознание позволяет замечать собственные слабости и сознательно над ними работать.",
        en: "Self-awareness allows you to notice your weaknesses and work on them consciously.",
        uaTokens: ["Самоусвідомлення", "дозволяє", "помічати", "власні", "слабкості", "й", "свідомо", "над", "ними", "працювати", "."],
        ruTokens: ["Самоосознание", "позволяет", "замечать", "собственные", "слабости", "и", "сознательно", "над", "ними", "работать", "."],
        enTokens: ["Self-awareness", "allows", "you", "to", "notice", "your", "weaknesses", "and", "work", "on", "them", "consciously", "."],
        extraUaTokens: ["характер", "розвиток", "поведінку"],
        extraRuTokens: ["характер", "развитие", "поведение"],
        extraEnTokens: ["character", "development", "behavior"],
    },

    // =========================
    // LESSON 27 — Дипломатія
    // =========================
    [phraseKey("negocjacje", "b2-27")]: {
        sk: "Negocjacje trwały wiele godzin, zanim obie strony osiągnęły porozumienie.",
        ua: "Переговори тривали багато годин, перш ніж обидві сторони досягли згоди.",
        ru: "Переговоры длились много часов, прежде чем обе стороны достигли соглашения.",
        en: "The negotiations lasted many hours before both sides reached an agreement.",
        uaTokens: ["Переговори", "тривали", "багато", "годин", ",", "перш", "ніж", "обидві", "сторони", "досягли", "згоди", "."],
        ruTokens: ["Переговоры", "длились", "много", "часов", ",", "прежде", "чем", "обе", "стороны", "достигли", "соглашения", "."],
        enTokens: ["The", "negotiations", "lasted", "many", "hours", "before", "both", "sides", "reached", "an", "agreement", "."],
        extraUaTokens: ["компроміс", "діалог", "спір"],
        extraRuTokens: ["компромисс", "диалог", "спор"],
        extraEnTokens: ["compromise", "dialogue", "dispute"],
    },

    [phraseKey("przychylne nastawienie", "b2-27")]: {
        sk: "Przychylne nastawienie ułatwia dialog i zwiększa szansę na kompromis.",
        ua: "Прихильна позиція полегшує діалог і збільшує шанс на компроміс.",
        ru: "Благожелательный настрой облегчает диалог и повышает шанс на компромисс.",
        en: "A cooperative attitude makes dialogue easier and increases the chance of compromise.",
        uaTokens: ["Прихильна", "позиція", "полегшує", "діалог", "і", "збільшує", "шанс", "на", "компроміс", "."],
        ruTokens: ["Благожелательный", "настрой", "облегчает", "диалог", "и", "повышает", "шанс", "на", "компромисс", "."],
        enTokens: ["A", "cooperative", "attitude", "makes", "dialogue", "easier", "and", "increases", "the", "chance", "of", "compromise", "."],
        extraUaTokens: ["згоду", "сторін", "розмову"],
        extraRuTokens: ["согласие", "сторон", "разговор"],
        extraEnTokens: ["agreement", "sides", "conversation"],
    },

    [phraseKey("neutralne stanowisko", "b2-27")]: {
        sk: "W tej sprawie postanowiliśmy zająć neutralne stanowisko, aby nikogo nie faworyzować.",
        ua: "У цій справі ми вирішили зайняти нейтральну позицію, щоб нікого не підтримувати більше за інших.",
        ru: "В этом вопросе мы решили занять нейтральную позицию, чтобы никого не выделять.",
        en: "In this matter, we decided to take a neutral position so as not to favor anyone.",
        uaTokens: ["У", "цій", "справі", "ми", "вирішили", "зайняти", "нейтральну", "позицію", ",", "щоб", "нікого", "не", "підтримувати", "більше", "за", "інших", "."],
        ruTokens: ["В", "этом", "вопросе", "мы", "решили", "занять", "нейтральную", "позицию", ",", "чтобы", "никого", "не", "выделять", "."],
        enTokens: ["In", "this", "matter", ",", "we", "decided", "to", "take", "a", "neutral", "position", "so", "as", "not", "to", "favor", "anyone", "."],
        extraUaTokens: ["рішення", "сторони", "компроміс"],
        extraRuTokens: ["решение", "стороны", "компромисс"],
        extraEnTokens: ["decision", "sides", "compromise"],
    },

    [phraseKey("zrównoważone rozwiązanie", "b2-27")]: {
        sk: "Potrzebujemy zrównoważonego rozwiązania, które będzie korzystne dla obu stron.",
        ua: "Нам потрібне збалансоване рішення, яке буде вигідним для обох сторін.",
        ru: "Нам нужно сбалансированное решение, которое будет выгодным для обеих сторон.",
        en: "We need a balanced solution that will be beneficial for both sides.",
        uaTokens: ["Нам", "потрібне", "збалансоване", "рішення", ",", "яке", "буде", "вигідним", "для", "обох", "сторін", "."],
        ruTokens: ["Нам", "нужно", "сбалансированное", "решение", ",", "которое", "будет", "выгодным", "для", "обеих", "сторон", "."],
        enTokens: ["We", "need", "a", "balanced", "solution", "that", "will", "be", "beneficial", "for", "both", "sides", "."],
        extraUaTokens: ["компроміс", "переговори", "угоду"],
        extraRuTokens: ["компромисс", "переговоры", "соглашение"],
        extraEnTokens: ["compromise", "negotiations", "agreement"],
    },

    [phraseKey("napięta sytuacja", "b2-27")]: {
        sk: "Napięta sytuacja wymagała spokojnego tonu i bardzo ostrożnych słów.",
        ua: "Напружена ситуація вимагала спокійного тону й дуже обережних слів.",
        ru: "Напряжённая ситуация требовала спокойного тона и очень осторожных слов.",
        en: "The tense situation required a calm tone and very careful words.",
        uaTokens: ["Напружена", "ситуація", "вимагала", "спокійного", "тону", "й", "дуже", "обережних", "слів", "."],
        ruTokens: ["Напряжённая", "ситуация", "требовала", "спокойного", "тона", "и", "очень", "осторожных", "слов", "."],
        enTokens: ["The", "tense", "situation", "required", "a", "calm", "tone", "and", "very", "careful", "words", "."],
        extraUaTokens: ["розмови", "спору", "атмосфери"],
        extraRuTokens: ["разговора", "спора", "атмосферы"],
        extraEnTokens: ["conversation", "dispute", "atmosphere"],
    },

    [phraseKey("pojednawczy ton", "b2-27")]: {
        sk: "Jego pojednawczy ton pomógł uspokoić atmosferę podczas spotkania.",
        ua: "Його примирливий тон допоміг заспокоїти атмосферу під час зустрічі.",
        ru: "Его примирительный тон помог успокоить атмосферу во время встречи.",
        en: "His conciliatory tone helped calm the atmosphere during the meeting.",
        uaTokens: ["Його", "примирливий", "тон", "допоміг", "заспокоїти", "атмосферу", "під", "час", "зустрічі", "."],
        ruTokens: ["Его", "примирительный", "тон", "помог", "успокоить", "атмосферу", "во", "время", "встречи", "."],
        enTokens: ["His", "conciliatory", "tone", "helped", "calm", "the", "atmosphere", "during", "the", "meeting", "."],
        extraUaTokens: ["спокій", "діалог", "компроміс"],
        extraRuTokens: ["спокойствие", "диалог", "компромисс"],
        extraEnTokens: ["calm", "dialogue", "compromise"],
    },

    [phraseKey("strategia negocjacyjna", "b2-27")]: {
        sk: "Dobrze przygotowana strategia negocjacyjna zwiększa szansę na osiągnięcie celu.",
        ua: "Добре підготовлена стратегія переговорів збільшує шанс досягти мети.",
        ru: "Хорошо подготовленная стратегия переговоров повышает шанс достичь цели.",
        en: "A well-prepared negotiation strategy increases the chance of achieving the goal.",
        uaTokens: ["Добре", "підготовлена", "стратегія", "переговорів", "збільшує", "шанс", "досягти", "мети", "."],
        ruTokens: ["Хорошо", "подготовленная", "стратегия", "переговоров", "повышает", "шанс", "достичь", "цели", "."],
        enTokens: ["A", "well-prepared", "negotiation", "strategy", "increases", "the", "chance", "of", "achieving", "the", "goal", "."],
        extraUaTokens: ["план", "успіх", "угоду"],
        extraRuTokens: ["план", "успех", "соглашение"],
        extraEnTokens: ["plan", "success", "agreement"],
    },

    [phraseKey("wzajemne porozumienie", "b2-27")]: {
        sk: "Wzajemne porozumienie było możliwe tylko dzięki cierpliwości i gotowości do ustępstw.",
        ua: "Взаємна домовленість стала можливою лише завдяки терпінню й готовності до поступок.",
        ru: "Взаимное соглашение стало возможным только благодаря терпению и готовности к уступкам.",
        en: "Mutual agreement was possible only thanks to patience and willingness to make concessions.",
        uaTokens: ["Взаємна", "домовленість", "стала", "можливою", "лише", "завдяки", "терпінню", "й", "готовності", "до", "поступок", "."],
        ruTokens: ["Взаимное", "соглашение", "стало", "возможным", "только", "благодаря", "терпению", "и", "готовности", "к", "уступкам", "."],
        enTokens: ["Mutual", "agreement", "was", "possible", "only", "thanks", "to", "patience", "and", "willingness", "to", "make", "concessions", "."],
        extraUaTokens: ["сторін", "компроміс", "переговори"],
        extraRuTokens: ["сторон", "компромисс", "переговоры"],
        extraEnTokens: ["sides", "compromise", "negotiations"],
    },

    [phraseKey("kompromisowe rozwiązanie", "b2-27")]: {
        sk: "Kompromisowe rozwiązanie nie było idealne, ale pozwoliło zakończyć spór.",
        ua: "Компромісне рішення не було ідеальним, але дозволило завершити суперечку.",
        ru: "Компромиссное решение не было идеальным, но позволило завершить спор.",
        en: "The compromise solution was not ideal, but it made it possible to end the dispute.",
        uaTokens: ["Компромісне", "рішення", "не", "було", "ідеальним", ",", "але", "дозволило", "завершити", "суперечку", "."],
        ruTokens: ["Компромиссное", "решение", "не", "было", "идеальным", ",", "но", "позволило", "завершить", "спор", "."],
        enTokens: ["The", "compromise", "solution", "was", "not", "ideal", ",", "but", "it", "made", "it", "possible", "to", "end", "the", "dispute", "."],
        extraUaTokens: ["угоду", "сторони", "мир"],
        extraRuTokens: ["соглашение", "стороны", "мир"],
        extraEnTokens: ["agreement", "sides", "peace"],
    },

    [phraseKey("zachować neutralność", "b2-27")]: {
        sk: "W tak delikatnej sprawie trudno było zachować neutralność przez cały czas.",
        ua: "У такій делікатній справі було важко зберігати нейтралітет увесь час.",
        ru: "В таком деликатном вопросе было трудно сохранять нейтралитет всё время.",
        en: "In such a delicate matter, it was difficult to maintain neutrality all the time.",
        uaTokens: ["У", "такій", "делікатній", "справі", "було", "важко", "зберігати", "нейтралітет", "увесь", "час", "."],
        ruTokens: ["В", "таком", "деликатном", "вопросе", "было", "трудно", "сохранять", "нейтралитет", "всё", "время", "."],
        enTokens: ["In", "such", "a", "delicate", "matter", ",", "it", "was", "difficult", "to", "maintain", "neutrality", "all", "the", "time", "."],
        extraUaTokens: ["позицію", "сторін", "конфлікт"],
        extraRuTokens: ["позицию", "сторон", "конфликт"],
        extraEnTokens: ["position", "sides", "conflict"],
    },

    // =========================
    // LESSON 28 — Глобальні проблеми
    // =========================
    [phraseKey("globalne wyzwanie", "b2-28")]: {
        sk: "Zmiany klimatyczne są dziś jednym z największych globalnych wyzwań.",
        ua: "Зміни клімату сьогодні є одним із найбільших глобальних викликів.",
        ru: "Изменение климата сегодня является одним из крупнейших глобальных вызовов.",
        en: "Climate change is one of the greatest global challenges today.",
        uaTokens: ["Зміни", "клімату", "сьогодні", "є", "одним", "із", "найбільших", "глобальних", "викликів", "."],
        ruTokens: ["Изменение", "климата", "сегодня", "является", "одним", "из", "крупнейших", "глобальных", "вызовов", "."],
        enTokens: ["Climate", "change", "is", "one", "of", "the", "greatest", "global", "challenges", "today", "."],
        extraUaTokens: ["довкілля", "світу", "проблем"],
        extraRuTokens: ["окружающей", "среды", "мира"],
        extraEnTokens: ["environment", "world", "problems"],
    },

    [phraseKey("kryzys humanitarny", "b2-28")]: {
        sk: "Kryzys humanitarny wymaga szybkiej reakcji i realnego wsparcia ze strony innych państw.",
        ua: "Гуманітарна криза потребує швидкої реакції та реальної підтримки з боку інших держав.",
        ru: "Гуманитарный кризис требует быстрой реакции и реальной поддержки со стороны других государств.",
        en: "A humanitarian crisis requires a quick response and real support from other countries.",
        uaTokens: ["Гуманітарна", "криза", "потребує", "швидкої", "реакції", "та", "реальної", "підтримки", "з", "боку", "інших", "держав", "."],
        ruTokens: ["Гуманитарный", "кризис", "требует", "быстрой", "реакции", "и", "реальной", "поддержки", "со", "стороны", "других", "государств", "."],
        enTokens: ["A", "humanitarian", "crisis", "requires", "a", "quick", "response", "and", "real", "support", "from", "other", "countries", "."],
        extraUaTokens: ["допомоги", "світу", "людей"],
        extraRuTokens: ["помощи", "мира", "людей"],
        extraEnTokens: ["aid", "world", "people"],
    },

    [phraseKey("brak zasobów", "b2-28")]: {
        sk: "Brak zasobów utrudnia rozwój regionów, które już wcześniej zmagały się z problemami.",
        ua: "Нестача ресурсів ускладнює розвиток регіонів, які й раніше боролися з проблемами.",
        ru: "Нехватка ресурсов затрудняет развитие регионов, которые и раньше сталкивались с проблемами.",
        en: "Lack of resources hinders the development of regions that were already struggling with problems.",
        uaTokens: ["Нестача", "ресурсів", "ускладнює", "розвиток", "регіонів", ",", "які", "й", "раніше", "боролися", "з", "проблемами", "."],
        ruTokens: ["Нехватка", "ресурсов", "затрудняет", "развитие", "регионов", ",", "которые", "и", "раньше", "сталкивались", "с", "проблемами", "."],
        enTokens: ["Lack", "of", "resources", "hinders", "the", "development", "of", "regions", "that", "were", "already", "struggling", "with", "problems", "."],
        extraUaTokens: ["економіку", "допомогу", "кризу"],
        extraRuTokens: ["экономику", "помощь", "кризис"],
        extraEnTokens: ["economy", "aid", "crisis"],
    },

    [phraseKey("nierówność społeczna", "b2-28")]: {
        sk: "Nierówność społeczna prowadzi do napięć i osłabia poczucie sprawiedliwości.",
        ua: "Соціальна нерівність призводить до напруження й послаблює відчуття справедливості.",
        ru: "Социальное неравенство приводит к напряжению и ослабляет чувство справедливости.",
        en: "Social inequality leads to tension and weakens the sense of justice.",
        uaTokens: ["Соціальна", "нерівність", "призводить", "до", "напруження", "й", "послаблює", "відчуття", "справедливості", "."],
        ruTokens: ["Социальное", "неравенство", "приводит", "к", "напряжению", "и", "ослабляет", "чувство", "справедливости", "."],
        enTokens: ["Social", "inequality", "leads", "to", "tension", "and", "weakens", "the", "sense", "of", "justice", "."],
        extraUaTokens: ["суспільство", "людей", "конфліктів"],
        extraRuTokens: ["общество", "людей", "конфликтов"],
        extraEnTokens: ["society", "people", "conflicts"],
    },

    [phraseKey("fala migracyjna", "b2-28")]: {
        sk: "Nowa fala migracyjna zmusiła wiele krajów do zmiany swojej polityki.",
        ua: "Нова міграційна хвиля змусила багато країн змінити свою політику.",
        ru: "Новая миграционная волна заставила многие страны изменить свою политику.",
        en: "A new migration wave forced many countries to change their policy.",
        uaTokens: ["Нова", "міграційна", "хвиля", "змусила", "багато", "країн", "змінити", "свою", "політику", "."],
        ruTokens: ["Новая", "миграционная", "волна", "заставила", "многие", "страны", "изменить", "свою", "политику", "."],
        enTokens: ["A", "new", "migration", "wave", "forced", "many", "countries", "to", "change", "their", "policy", "."],
        extraUaTokens: ["кордони", "держав", "кризу"],
        extraRuTokens: ["границы", "государств", "кризис"],
        extraEnTokens: ["borders", "states", "crisis"],
    },

    [phraseKey("współpraca międzynarodowa", "b2-28")]: {
        sk: "Bez współpracy międzynarodowej trudno znaleźć skuteczne rozwiązania globalnych problemów.",
        ua: "Без міжнародної співпраці важко знайти ефективні рішення глобальних проблем.",
        ru: "Без международного сотрудничества трудно найти эффективные решения глобальных проблем.",
        en: "Without international cooperation, it is hard to find effective solutions to global problems.",
        uaTokens: ["Без", "міжнародної", "співпраці", "важко", "знайти", "ефективні", "рішення", "глобальних", "проблем", "."],
        ruTokens: ["Без", "международного", "сотрудничества", "трудно", "найти", "эффективные", "решения", "глобальных", "проблем", "."],
        enTokens: ["Without", "international", "cooperation", ",", "it", "is", "hard", "to", "find", "effective", "solutions", "to", "global", "problems", "."],
        extraUaTokens: ["держав", "світу", "кризи"],
        extraRuTokens: ["государств", "мира", "кризиса"],
        extraEnTokens: ["states", "world", "crisis"],
    },

    [phraseKey("długoterminowy problem", "b2-28")]: {
        sk: "To nie jest chwilowy kryzys, lecz długoterminowy problem wymagający systemowych działań.",
        ua: "Це не тимчасова криза, а довготривала проблема, що потребує системних дій.",
        ru: "Это не временный кризис, а долгосрочная проблема, требующая системных действий.",
        en: "This is not a temporary crisis, but a long-term problem requiring systemic action.",
        uaTokens: ["Це", "не", "тимчасова", "криза", ",", "а", "довготривала", "проблема", ",", "що", "потребує", "системних", "дій", "."],
        ruTokens: ["Это", "не", "временный", "кризис", ",", "а", "долгосрочная", "проблема", ",", "требующая", "системных", "действий", "."],
        enTokens: ["This", "is", "not", "a", "temporary", "crisis", ",", "but", "a", "long-term", "problem", "requiring", "systemic", "action", "."],
        extraUaTokens: ["реформ", "майбутнього", "змін"],
        extraRuTokens: ["реформ", "будущего", "изменений"],
        extraEnTokens: ["reforms", "future", "changes"],
    },

    [phraseKey("wspólna odpowiedzialność", "b2-28")]: {
        sk: "Ochrona środowiska to wspólna odpowiedzialność wszystkich państw i społeczeństw.",
        ua: "Захист довкілля — це спільна відповідальність усіх держав і суспільств.",
        ru: "Защита окружающей среды — это общая ответственность всех государств и обществ.",
        en: "Environmental protection is the shared responsibility of all countries and societies.",
        uaTokens: ["Захист", "довкілля", "—", "це", "спільна", "відповідальність", "усіх", "держав", "і", "суспільств", "."],
        ruTokens: ["Защита", "окружающей", "среды", "—", "это", "общая", "ответственность", "всех", "государств", "и", "обществ", "."],
        enTokens: ["Environmental", "protection", "is", "the", "shared", "responsibility", "of", "all", "countries", "and", "societies", "."],
        extraUaTokens: ["природи", "світу", "обов’язок"],
        extraRuTokens: ["природы", "мира", "обязанность"],
        extraEnTokens: ["nature", "world", "duty"],
    },

    [phraseKey("globalny wpływ", "b2-28")]: {
        sk: "Ta decyzja gospodarcza może mieć globalny wpływ na ceny i rynki finansowe.",
        ua: "Це економічне рішення може мати глобальний вплив на ціни та фінансові ринки.",
        ru: "Это экономическое решение может оказать глобальное влияние на цены и финансовые рынки.",
        en: "This economic decision may have a global impact on prices and financial markets.",
        uaTokens: ["Це", "економічне", "рішення", "може", "мати", "глобальний", "вплив", "на", "ціни", "та", "фінансові", "ринки", "."],
        ruTokens: ["Это", "экономическое", "решение", "может", "оказать", "глобальное", "влияние", "на", "цены", "и", "финансовые", "рынки", "."],
        enTokens: ["This", "economic", "decision", "may", "have", "a", "global", "impact", "on", "prices", "and", "financial", "markets", "."],
        extraUaTokens: ["економіку", "гроші", "світ"],
        extraRuTokens: ["экономику", "деньги", "мир"],
        extraEnTokens: ["economy", "money", "world"],
    },

    [phraseKey("zrównoważone rozwiązanie", "b2-28")]: {
        sk: "Potrzebujemy zrównoważonego rozwiązania, które będzie skuteczne także w przyszłości.",
        ua: "Нам потрібне стале рішення, яке буде ефективним і в майбутньому.",
        ru: "Нам нужно устойчивое решение, которое будет эффективным и в будущем.",
        en: "We need a sustainable solution that will also be effective in the future.",
        uaTokens: ["Нам", "потрібне", "стале", "рішення", ",", "яке", "буде", "ефективним", "і", "в", "майбутньому", "."],
        ruTokens: ["Нам", "нужно", "устойчивое", "решение", ",", "которое", "будет", "эффективным", "и", "в", "будущем", "."],
        enTokens: ["We", "need", "a", "sustainable", "solution", "that", "will", "also", "be", "effective", "in", "the", "future", "."],
        extraUaTokens: ["реформу", "проблем", "екології"],
        extraRuTokens: ["реформу", "проблем", "экологии"],
        extraEnTokens: ["reform", "problems", "ecology"],
    },

    // =========================
    // LESSON 29 — Міжособистісні конфлікти
    // =========================
    [phraseKey("napięta relacja", "b2-29")]: {
        sk: "Ich napięta relacja była widoczna nawet wtedy, gdy próbowali zachować spokój.",
        ua: "Їхній напружений зв’язок був помітний навіть тоді, коли вони намагалися зберігати спокій.",
        ru: "Их напряжённая связь была заметна даже тогда, когда они пытались сохранять спокойствие.",
        en: "Their strained relationship was visible even when they tried to stay calm.",
        uaTokens: ["Їхній", "напружений", "зв’язок", "був", "помітний", "навіть", "тоді", ",", "коли", "вони", "намагалися", "зберігати", "спокій", "."],
        ruTokens: ["Их", "напряжённая", "связь", "была", "заметна", "даже", "тогда", ",", "когда", "они", "пытались", "сохранять", "спокойствие", "."],
        enTokens: ["Their", "strained", "relationship", "was", "visible", "even", "when", "they", "tried", "to", "stay", "calm", "."],
        extraUaTokens: ["конфлікт", "емоції", "розмову"],
        extraRuTokens: ["конфликт", "эмоции", "разговор"],
        extraEnTokens: ["conflict", "emotions", "conversation"],
    },

    [phraseKey("niezrozumienie", "b2-29")]: {
        sk: "Cały konflikt zaczął się od zwykłego niezrozumienia i braku rozmowy.",
        ua: "Увесь конфлікт почався зі звичайного непорозуміння та відсутності розмови.",
        ru: "Весь конфликт начался с обычного недопонимания и отсутствия разговора.",
        en: "The whole conflict started with a simple misunderstanding and lack of communication.",
        uaTokens: ["Увесь", "конфлікт", "почався", "зі", "звичайного", "непорозуміння", "та", "відсутності", "розмови", "."],
        ruTokens: ["Весь", "конфликт", "начался", "с", "обычного", "недопонимания", "и", "отсутствия", "разговора", "."],
        enTokens: ["The", "whole", "conflict", "started", "with", "a", "simple", "misunderstanding", "and", "lack", "of", "communication", "."],
        extraUaTokens: ["слів", "стосунків", "пояснення"],
        extraRuTokens: ["слов", "отношений", "объяснения"],
        extraEnTokens: ["words", "relationships", "explanation"],
    },

    [phraseKey("przeprosiny", "b2-29")]: {
        sk: "Szczere przeprosiny mogą czasem naprawić więcej niż długie wyjaśnienia.",
        ua: "Щирі вибачення іноді можуть виправити більше, ніж довгі пояснення.",
        ru: "Искренние извинения иногда могут исправить больше, чем долгие объяснения.",
        en: "A sincere apology can sometimes fix more than a long explanation.",
        uaTokens: ["Щирі", "вибачення", "іноді", "можуть", "виправити", "більше", ",", "ніж", "довгі", "пояснення", "."],
        ruTokens: ["Искренние", "извинения", "иногда", "могут", "исправить", "больше", ",", "чем", "долгие", "объяснения", "."],
        enTokens: ["A", "sincere", "apology", "can", "sometimes", "fix", "more", "than", "a", "long", "explanation", "."],
        extraUaTokens: ["конфлікт", "помилку", "розмову"],
        extraRuTokens: ["конфликт", "ошибку", "разговор"],
        extraEnTokens: ["conflict", "mistake", "conversation"],
    },

    [phraseKey("rozejm", "b2-29")]: {
        sk: "Po wielu tygodniach kłótni w końcu udało im się zawrzeć rozejm.",
        ua: "Після багатьох тижнів сварок їм нарешті вдалося досягти примирення.",
        ru: "После многих недель ссор им наконец удалось заключить перемирие.",
        en: "After many weeks of arguments, they finally managed to reach a truce.",
        uaTokens: ["Після", "багатьох", "тижнів", "сварок", "їм", "нарешті", "вдалося", "досягти", "примирення", "."],
        ruTokens: ["После", "многих", "недель", "ссор", "им", "наконец", "удалось", "заключить", "перемирие", "."],
        enTokens: ["After", "many", "weeks", "of", "arguments", ",", "they", "finally", "managed", "to", "reach", "a", "truce", "."],
        extraUaTokens: ["миру", "розмови", "стосунків"],
        extraRuTokens: ["мира", "разговора", "отношений"],
        extraEnTokens: ["peace", "conversation", "relationships"],
    },

    [phraseKey("napięta atmosfera", "b2-29")]: {
        sk: "Napięta atmosfera w biurze utrudniała współpracę i obniżała motywację zespołu.",
        ua: "Напружена атмосфера в офісі ускладнювала співпрацю й знижувала мотивацію команди.",
        ru: "Напряжённая атмосфера в офисе затрудняла сотрудничество и снижала мотивацию команды.",
        en: "The tense atmosphere in the office made cooperation difficult and lowered the team's motivation.",
        uaTokens: ["Напружена", "атмосфера", "в", "офісі", "ускладнювала", "співпрацю", "й", "знижувала", "мотивацію", "команди", "."],
        ruTokens: ["Напряжённая", "атмосфера", "в", "офисе", "затрудняла", "сотрудничество", "и", "снижала", "мотивацию", "команды", "."],
        enTokens: ["The", "tense", "atmosphere", "in", "the", "office", "made", "cooperation", "difficult", "and", "lowered", "the", "team's", "motivation", "."],
        extraUaTokens: ["роботу", "конфлікт", "емоції"],
        extraRuTokens: ["работу", "конфликт", "эмоции"],
        extraEnTokens: ["work", "conflict", "emotions"],
    },

    [phraseKey("rozwiązać konflikt", "b2-29")]: {
        sk: "Aby rozwiązać konflikt, trzeba najpierw uważnie wysłuchać obu stron.",
        ua: "Щоб вирішити конфлікт, спочатку треба уважно вислухати обидві сторони.",
        ru: "Чтобы решить конфликт, сначала нужно внимательно выслушать обе стороны.",
        en: "To resolve a conflict, you first need to listen carefully to both sides.",
        uaTokens: ["Щоб", "вирішити", "конфлікт", ",", "спочатку", "треба", "уважно", "вислухати", "обидві", "сторони", "."],
        ruTokens: ["Чтобы", "решить", "конфликт", ",", "сначала", "нужно", "внимательно", "выслушать", "обе", "стороны", "."],
        enTokens: ["To", "resolve", "a", "conflict", ",", "you", "first", "need", "to", "listen", "carefully", "to", "both", "sides", "."],
        extraUaTokens: ["розмову", "згоду", "суперечку"],
        extraRuTokens: ["разговор", "согласие", "спор"],
        extraEnTokens: ["conversation", "agreement", "dispute"],
    },

    [phraseKey("wzajemne zrozumienie", "b2-29")]: {
        sk: "Bez wzajemnego zrozumienia trudno zbudować trwałą i zdrową relację.",
        ua: "Без взаєморозуміння важко побудувати міцні й здорові стосунки.",
        ru: "Без взаимопонимания трудно построить прочные и здоровые отношения.",
        en: "Without mutual understanding, it is difficult to build a lasting and healthy relationship.",
        uaTokens: ["Без", "взаєморозуміння", "важко", "побудувати", "міцні", "й", "здорові", "стосунки", "."],
        ruTokens: ["Без", "взаимопонимания", "трудно", "построить", "прочные", "и", "здоровые", "отношения", "."],
        enTokens: ["Without", "mutual", "understanding", ",", "it", "is", "difficult", "to", "build", "a", "lasting", "and", "healthy", "relationship", "."],
        extraUaTokens: ["довіру", "повагу", "любов"],
        extraRuTokens: ["доверие", "уважение", "любовь"],
        extraEnTokens: ["trust", "respect", "love"],
    },

    [phraseKey("naprawić błąd", "b2-29")]: {
        sk: "Najważniejsze było to, że próbował naprawić błąd, zamiast szukać wymówek.",
        ua: "Найважливішим було те, що він намагався виправити помилку, а не шукати виправдань.",
        ru: "Самым важным было то, что он пытался исправить ошибку, а не искать оправдания.",
        en: "The most important thing was that he tried to correct the mistake instead of making excuses.",
        uaTokens: ["Найважливішим", "було", "те", ",", "що", "він", "намагався", "виправити", "помилку", ",", "а", "не", "шукати", "виправдань", "."],
        ruTokens: ["Самым", "важным", "было", "то", ",", "что", "он", "пытался", "исправить", "ошибку", ",", "а", "не", "искать", "оправдания", "."],
        enTokens: ["The", "most", "important", "thing", "was", "that", "he", "tried", "to", "correct", "the", "mistake", "instead", "of", "making", "excuses", "."],
        extraUaTokens: ["провину", "відповідальність", "чесність"],
        extraRuTokens: ["вину", "ответственность", "честность"],
        extraEnTokens: ["guilt", "responsibility", "honesty"],
    },

    [phraseKey("napięcie między ludźmi", "b2-29")]: {
        sk: "Napięcie między ludźmi często rośnie wtedy, gdy nikt nie chce ustąpić.",
        ua: "Напруга між людьми часто зростає тоді, коли ніхто не хоче поступатися.",
        ru: "Напряжение между людьми часто растёт тогда, когда никто не хочет уступать.",
        en: "Tension between people often grows when no one wants to give in.",
        uaTokens: ["Напруга", "між", "людьми", "часто", "зростає", "тоді", ",", "коли", "ніхто", "не", "хоче", "поступатися", "."],
        ruTokens: ["Напряжение", "между", "людьми", "часто", "растёт", "тогда", ",", "когда", "никто", "не", "хочет", "уступать", "."],
        enTokens: ["Tension", "between", "people", "often", "grows", "when", "no", "one", "wants", "to", "give", "in", "."],
        extraUaTokens: ["конфлікт", "сварку", "его"],
        extraRuTokens: ["конфликт", "ссору", "эго"],
        extraEnTokens: ["conflict", "argument", "ego"],
    },

    [phraseKey("kryzys w związku", "b2-29")]: {
        sk: "Kryzys w związku nie zawsze oznacza koniec, ale wymaga szczerej rozmowy i pracy.",
        ua: "Криза у стосунках не завжди означає кінець, але вимагає щирої розмови та роботи над собою.",
        ru: "Кризис в отношениях не всегда означает конец, но требует честного разговора и работы.",
        en: "A relationship crisis does not always mean the end, but it requires honest conversation and effort.",
        uaTokens: ["Криза", "у", "стосунках", "не", "завжди", "означає", "кінець", ",", "але", "вимагає", "щирої", "розмови", "та", "роботи", "над", "собою", "."],
        ruTokens: ["Кризис", "в", "отношениях", "не", "всегда", "означает", "конец", ",", "но", "требует", "честного", "разговора", "и", "работы", "."],
        enTokens: ["A", "relationship", "crisis", "does", "not", "always", "mean", "the", "end", ",", "but", "it", "requires", "honest", "conversation", "and", "effort", "."],
        extraUaTokens: ["довіри", "любові", "пари"],
        extraRuTokens: ["доверия", "любви", "пары"],
        extraEnTokens: ["trust", "love", "couple"],
    },

    // =========================
    // LESSON 30 — Культура і суспільні явища
    // =========================
    [phraseKey("tożsamość kulturowa", "b2-30")]: {
        sk: "Tożsamość kulturowa kształtuje się przez język, tradycję i wspólne doświadczenia.",
        ua: "Культурна ідентичність формується через мову, традицію та спільний досвід.",
        ru: "Культурная идентичность формируется через язык, традиции и общий опыт.",
        en: "Cultural identity is shaped by language, tradition, and shared experience.",
        uaTokens: ["Культурна", "ідентичність", "формується", "через", "мову", ",", "традицію", "та", "спільний", "досвід", "."],
        ruTokens: ["Культурная", "идентичность", "формируется", "через", "язык", ",", "традиции", "и", "общий", "опыт", "."],
        enTokens: ["Cultural", "identity", "is", "shaped", "by", "language", ",", "tradition", ",", "and", "shared", "experience", "."],
        extraUaTokens: ["народу", "історію", "культуру"],
        extraRuTokens: ["народа", "историю", "культуру"],
        extraEnTokens: ["people", "history", "culture"],
    },

    [phraseKey("trend społeczny", "b2-30")]: {
        sk: "Ten trend społeczny stał się szczególnie widoczny w ostatnich latach.",
        ua: "Цей соціальний тренд став особливо помітним в останні роки.",
        ru: "Этот социальный тренд стал особенно заметен в последние годы.",
        en: "This social trend has become especially visible in recent years.",
        uaTokens: ["Цей", "соціальний", "тренд", "став", "особливо", "помітним", "в", "останні", "роки", "."],
        ruTokens: ["Этот", "социальный", "тренд", "стал", "особенно", "заметен", "в", "последние", "годы", "."],
        enTokens: ["This", "social", "trend", "has", "become", "especially", "visible", "in", "recent", "years", "."],
        extraUaTokens: ["суспільстві", "зміни", "людей"],
        extraRuTokens: ["обществе", "изменения", "людей"],
        extraEnTokens: ["society", "changes", "people"],
    },

    [phraseKey("norma społeczna", "b2-30")]: {
        sk: "To, co w jednym kraju jest normą społeczną, w innym może budzić zdziwienie.",
        ua: "Те, що в одній країні є соціальною нормою, в іншій може викликати подив.",
        ru: "То, что в одной стране является социальной нормой, в другой может вызывать удивление.",
        en: "What is a social norm in one country may be surprising in another.",
        uaTokens: ["Те", ",", "що", "в", "одній", "країні", "є", "соціальною", "нормою", ",", "в", "іншій", "може", "викликати", "подив", "."],
        ruTokens: ["То", ",", "что", "в", "одной", "стране", "является", "социальной", "нормой", ",", "в", "другой", "может", "вызывать", "удивление", "."],
        enTokens: ["What", "is", "a", "social", "norm", "in", "one", "country", "may", "be", "surprising", "in", "another", "."],
        extraUaTokens: ["традицію", "культуру", "звичай"],
        extraRuTokens: ["традицию", "культуру", "обычай"],
        extraEnTokens: ["tradition", "culture", "custom"],
    },

    [phraseKey("dziedzictwo kulturowe", "b2-30")]: {
        sk: "Dziedzictwo kulturowe powinno być chronione, ponieważ łączy przeszłość z teraźniejszością.",
        ua: "Культурну спадщину слід берегти, адже вона поєднує минуле із сучасністю.",
        ru: "Культурное наследие следует сохранять, потому что оно соединяет прошлое с настоящим.",
        en: "Cultural heritage should be protected because it connects the past with the present.",
        uaTokens: ["Культурну", "спадщину", "слід", "берегти", ",", "адже", "вона", "поєднує", "минуле", "із", "сучасністю", "."],
        ruTokens: ["Культурное", "наследие", "следует", "сохранять", ",", "потому", "что", "оно", "соединяет", "прошлое", "с", "настоящим", "."],
        enTokens: ["Cultural", "heritage", "should", "be", "protected", "because", "it", "connects", "the", "past", "with", "the", "present", "."],
        extraUaTokens: ["історію", "пам’ять", "культури"],
        extraRuTokens: ["историю", "память", "культуры"],
        extraEnTokens: ["history", "memory", "culture"],
    },

    [phraseKey("kierunek artystyczny", "b2-30")]: {
        sk: "Ten kierunek artystyczny odrzucał tradycyjne formy i szukał nowych środków wyrazu.",
        ua: "Цей художній напрям відкидав традиційні форми й шукав нові засоби вираження.",
        ru: "Это художественное направление отвергало традиционные формы и искало новые средства выражения.",
        en: "This artistic movement rejected traditional forms and searched for new means of expression.",
        uaTokens: ["Цей", "художній", "напрям", "відкидав", "традиційні", "форми", "й", "шукав", "нові", "засоби", "вираження", "."],
        ruTokens: ["Это", "художественное", "направление", "отвергало", "традиционные", "формы", "и", "искало", "новые", "средства", "выражения", "."],
        enTokens: ["This", "artistic", "movement", "rejected", "traditional", "forms", "and", "searched", "for", "new", "means", "of", "expression", "."],
        extraUaTokens: ["мистецтва", "стилі", "форми"],
        extraRuTokens: ["искусства", "стили", "формы"],
        extraEnTokens: ["art", "styles", "forms"],
    },

    [phraseKey("wpływ społeczny", "b2-30")]: {
        sk: "Media mają ogromny wpływ społeczny, dlatego powinny działać odpowiedzialnie.",
        ua: "Медіа мають величезний соціальний вплив, тому повинні діяти відповідально.",
        ru: "СМИ оказывают огромное социальное влияние, поэтому должны действовать ответственно.",
        en: "The media have a huge social influence, so they should act responsibly.",
        uaTokens: ["Медіа", "мають", "величезний", "соціальний", "вплив", ",", "тому", "повинні", "діяти", "відповідально", "."],
        ruTokens: ["СМИ", "оказывают", "огромное", "социальное", "влияние", ",", "поэтому", "должны", "действовать", "ответственно", "."],
        enTokens: ["The", "media", "have", "a", "huge", "social", "influence", ",", "so", "they", "should", "act", "responsibly", "."],
        extraUaTokens: ["суспільство", "інформацію", "людей"],
        extraRuTokens: ["общество", "информацию", "людей"],
        extraEnTokens: ["society", "information", "people"],
    },

    [phraseKey("debata publiczna", "b2-30")]: {
        sk: "Debata publiczna była potrzebna, ponieważ temat dotyczył całego społeczeństwa.",
        ua: "Публічна дискусія була необхідною, оскільки тема стосувалася всього суспільства.",
        ru: "Публичная дискуссия была необходима, поскольку тема касалась всего общества.",
        en: "A public discussion was necessary because the topic concerned the whole society.",
        uaTokens: ["Публічна", "дискусія", "була", "необхідною", ",", "оскільки", "тема", "стосувалася", "всього", "суспільства", "."],
        ruTokens: ["Публичная", "дискуссия", "была", "необходима", ",", "поскольку", "тема", "касалась", "всего", "общества", "."],
        enTokens: ["A", "public", "discussion", "was", "necessary", "because", "the", "topic", "concerned", "the", "whole", "society", "."],
        extraUaTokens: ["теми", "людей", "проблеми"],
        extraRuTokens: ["темы", "людей", "проблемы"],
        extraEnTokens: ["topic", "people", "problem"],
    },

    [phraseKey("kontekst społeczny", "b2-30")]: {
        sk: "Nie można oceniać tego zjawiska bez uwzględnienia jego kontekstu społecznego.",
        ua: "Не можна оцінювати це явище без урахування його соціального контексту.",
        ru: "Нельзя оценивать это явление без учёта его социального контекста.",
        en: "This phenomenon cannot be judged without taking its social context into account.",
        uaTokens: ["Не", "можна", "оцінювати", "це", "явище", "без", "урахування", "його", "соціального", "контексту", "."],
        ruTokens: ["Нельзя", "оценивать", "это", "явление", "без", "учёта", "его", "социального", "контекста", "."],
        enTokens: ["This", "phenomenon", "cannot", "be", "judged", "without", "taking", "its", "social", "context", "into", "account", "."],
        extraUaTokens: ["суспільства", "аналізу", "теми"],
        extraRuTokens: ["общества", "анализа", "темы"],
        extraEnTokens: ["society", "analysis", "topic"],
    },

    [phraseKey("różnica kulturowa", "b2-30")]: {
        sk: "Różnica kulturowa nie musi dzielić ludzi, jeśli towarzyszy jej wzajemny szacunek.",
        ua: "Культурна різниця не обов’язково роз’єднує людей, якщо її супроводжує взаємна повага.",
        ru: "Культурное различие не обязательно разъединяет людей, если ему сопутствует взаимное уважение.",
        en: "A cultural difference does not have to divide people if it is accompanied by mutual respect.",
        uaTokens: ["Культурна", "різниця", "не", "обов’язково", "роз’єднує", "людей", ",", "якщо", "її", "супроводжує", "взаємна", "повага", "."],
        ruTokens: ["Культурное", "различие", "не", "обязательно", "разъединяет", "людей", ",", "если", "ему", "сопутствует", "взаимное", "уважение", "."],
        enTokens: ["A", "cultural", "difference", "does", "not", "have", "to", "divide", "people", "if", "it", "is", "accompanied", "by", "mutual", "respect", "."],
        extraUaTokens: ["традиції", "культури", "звичаї"],
        extraRuTokens: ["традиции", "культуры", "обычаи"],
        extraEnTokens: ["traditions", "cultures", "customs"],
    },

    [phraseKey("rzeczywistość społeczna", "b2-30")]: {
        sk: "Sztuka często odzwierciedla rzeczywistość społeczną bardziej szczerze niż oficjalne raporty.",
        ua: "Мистецтво часто відображає соціальну реальність щиріше, ніж офіційні звіти.",
        ru: "Искусство часто отражает социальную реальность честнее, чем официальные отчёты.",
        en: "Art often reflects social reality more honestly than official reports.",
        uaTokens: ["Мистецтво", "часто", "відображає", "соціальну", "реальність", "щиріше", ",", "ніж", "офіційні", "звіти", "."],
        ruTokens: ["Искусство", "часто", "отражает", "социальную", "реальность", "честнее", ",", "чем", "официальные", "отчёты", "."],
        enTokens: ["Art", "often", "reflects", "social", "reality", "more", "honestly", "than", "official", "reports", "."],
        extraUaTokens: ["суспільство", "правду", "культуру"],
        extraRuTokens: ["общество", "правду", "культуру"],
        extraEnTokens: ["society", "truth", "culture"],
    },
};