import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_B2_BUILD_UA_SENTENCES_7: BuildUaSentenceDict = {
    // =========================
    // LESSON 31 — Командні види спорту
    // =========================
    [phraseKey("podanie", "b2-31")]: {
        sk: "Szybkie podanie całkowicie zaskoczyło obrońców przeciwnej drużyny.",
        ua: "Швидкий пас повністю заскочив захисників команди суперника зненацька.",
        ru: "Быстрый пас полностью застал врасплох защитников команды соперника.",
        en: "A quick pass completely surprised the opposing team's defenders.",
        uaTokens: ["Швидкий", "пас", "повністю", "заскочив", "захисників", "команди", "суперника", "зненацька", "."],
        ruTokens: ["Быстрый", "пас", "полностью", "застал", "врасплох", "защитников", "команды", "соперника", "."],
        enTokens: ["A", "quick", "pass", "completely", "surprised", "the", "opposing", "team's", "defenders", "."],
        extraUaTokens: ["гол", "гра", "м’яч"],
        extraRuTokens: ["гол", "игра", "мяч"],
        extraEnTokens: ["goal", "game", "ball"],
    },
    [phraseKey("rzut rożny", "b2-31")]: {
        sk: "Po rzucie rożnym piłka trafiła idealnie pod nogi napastnika.",
        ua: "Після кутового м’яч ідеально потрапив під ноги нападника.",
        ru: "После углового мяч идеально попал под ноги нападающего.",
        en: "After the corner kick, the ball landed perfectly at the striker's feet.",
        uaTokens: ["Після", "кутового", "м’яч", "ідеально", "потрапив", "під", "ноги", "нападника", "."],
        ruTokens: ["После", "углового", "мяч", "идеально", "попал", "под", "ноги", "нападающего", "."],
        enTokens: ["After", "the", "corner", "kick", ",", "the", "ball", "landed", "perfectly", "at", "the", "striker's", "feet", "."],
        extraUaTokens: ["удар", "захисник", "гра"],
        extraRuTokens: ["удар", "защитник", "игра"],
        extraEnTokens: ["shot", "defender", "game"],
    },

    [phraseKey("rzut karny", "b2-31")]: {
        sk: "Rzut karny w ostatniej minucie zdecydował o wyniku całego meczu.",
        ua: "Пенальті на останній хвилині вирішило результат усього матчу.",
        ru: "Пенальти на последней минуте решило исход всего матча.",
        en: "The penalty kick in the last minute decided the outcome of the whole match.",
        uaTokens: ["Пенальті", "на", "останній", "хвилині", "вирішило", "результат", "усього", "матчу", "."],
        ruTokens: ["Пенальти", "на", "последней", "минуте", "решило", "исход", "всего", "матча", "."],
        enTokens: ["The", "penalty", "kick", "in", "the", "last", "minute", "decided", "the", "outcome", "of", "the", "whole", "match", "."],
        extraUaTokens: ["гол", "команда", "суддя"],
        extraRuTokens: ["гол", "команда", "судья"],
        extraEnTokens: ["goal", "team", "referee"],
    },

    [phraseKey("obrońca", "b2-31")]: {
        sk: "Doświadczony obrońca potrafił przewidzieć niemal każdy ruch przeciwnika.",
        ua: "Досвідчений захисник умів передбачити майже кожен рух суперника.",
        ru: "Опытный защитник умел предвидеть почти каждое движение соперника.",
        en: "The experienced defender could predict almost every move of the opponent.",
        uaTokens: ["Досвідчений", "захисник", "умів", "передбачити", "майже", "кожен", "рух", "суперника", "."],
        ruTokens: ["Опытный", "защитник", "умел", "предвидеть", "почти", "каждое", "движение", "соперника", "."],
        enTokens: ["The", "experienced", "defender", "could", "predict", "almost", "every", "move", "of", "the", "opponent", "."],
        extraUaTokens: ["пас", "удар", "гра"],
        extraRuTokens: ["пас", "удар", "игра"],
        extraEnTokens: ["pass", "shot", "game"],
    },

    [phraseKey("napastnik", "b2-31")]: {
        sk: "Napastnik wykorzystał błąd bramkarza i bez problemu strzelił gola.",
        ua: "Нападник скористався помилкою воротаря і без проблем забив гол.",
        ru: "Нападающий воспользовался ошибкой вратаря и без проблем забил гол.",
        en: "The forward took advantage of the goalkeeper's mistake and scored easily.",
        uaTokens: ["Нападник", "скористався", "помилкою", "воротаря", "і", "без", "проблем", "забив", "гол", "."],
        ruTokens: ["Нападающий", "воспользовался", "ошибкой", "вратаря", "и", "без", "проблем", "забил", "гол", "."],
        enTokens: ["The", "forward", "took", "advantage", "of", "the", "goalkeeper's", "mistake", "and", "scored", "easily", "."],
        extraUaTokens: ["пас", "гра", "команда"],
        extraRuTokens: ["пас", "игра", "команда"],
        extraEnTokens: ["pass", "game", "team"],
    },

    [phraseKey("sędzia", "b2-31")]: {
        sk: "Sędzia przerwał grę, ponieważ zawodnik doznał kontuzji.",
        ua: "Суддя зупинив гру, оскільки гравець отримав травму.",
        ru: "Судья остановил игру, поскольку игрок получил травму.",
        en: "The referee stopped the game because a player got injured.",
        uaTokens: ["Суддя", "зупинив", "гру", ",", "оскільки", "гравець", "отримав", "травму", "."],
        ruTokens: ["Судья", "остановил", "игру", ",", "поскольку", "игрок", "получил", "травму", "."],
        enTokens: ["The", "referee", "stopped", "the", "game", "because", "a", "player", "got", "injured", "."],
        extraUaTokens: ["гол", "матч", "удар"],
        extraRuTokens: ["гол", "матч", "удар"],
        extraEnTokens: ["goal", "match", "shot"],
    },

    [phraseKey("strzał", "b2-31")]: {
        sk: "Jego strzał był tak silny, że bramkarz nie miał żadnych szans.",
        ua: "Його удар був настільки сильним, що воротар не мав жодних шансів.",
        ru: "Его удар был настолько сильным, что у вратаря не было никаких шансов.",
        en: "His shot was so powerful that the goalkeeper had no chance.",
        uaTokens: ["Його", "удар", "був", "настільки", "сильним", ",", "що", "воротар", "не", "мав", "жодних", "шансів", "."],
        ruTokens: ["Его", "удар", "был", "настолько", "сильным", ",", "что", "у", "вратаря", "не", "было", "никаких", "шансов", "."],
        enTokens: ["His", "shot", "was", "so", "powerful", "that", "the", "goalkeeper", "had", "no", "chance", "."],
        extraUaTokens: ["пас", "команда", "гра"],
        extraRuTokens: ["пас", "команда", "игра"],
        extraEnTokens: ["pass", "team", "game"],
    },

    [phraseKey("strzelić gola", "b2-31")]: {
        sk: "Marzył o tym, aby strzelić gola w najważniejszym meczu sezonu.",
        ua: "Він мріяв забити гол у найважливішому матчі сезону.",
        ru: "Он мечтал забить гол в самом важном матче сезона.",
        en: "He dreamed of scoring a goal in the most important match of the season.",
        uaTokens: ["Він", "мріяв", "забити", "гол", "у", "найважливішому", "матчі", "сезону", "."],
        ruTokens: ["Он", "мечтал", "забить", "гол", "в", "самом", "важном", "матче", "сезона", "."],
        enTokens: ["He", "dreamed", "of", "scoring", "a", "goal", "in", "the", "most", "important", "match", "of", "the", "season", "."],
        extraUaTokens: ["пас", "удар", "суддя"],
        extraRuTokens: ["пас", "удар", "судья"],
        extraEnTokens: ["pass", "shot", "referee"],
    },

    [phraseKey("kosz do koszykówki", "b2-31")]: {
        sk: "Piłka odbiła się od tablicy i wpadła prosto do kosza do koszykówki.",
        ua: "М’яч відскочив від щита і залетів просто в баскетбольне кільце.",
        ru: "Мяч отскочил от щита и попал прямо в баскетбольное кольцо.",
        en: "The ball bounced off the backboard and went straight into the basketball hoop.",
        uaTokens: ["М’яч", "відскочив", "від", "щита", "і", "залетів", "просто", "в", "баскетбольне", "кільце", "."],
        ruTokens: ["Мяч", "отскочил", "от", "щита", "и", "попал", "прямо", "в", "баскетбольное", "кольцо", "."],
        enTokens: ["The", "ball", "bounced", "off", "the", "backboard", "and", "went", "straight", "into", "the", "basketball", "hoop", "."],
        extraUaTokens: ["удар", "матч", "нападника"],
        extraRuTokens: ["удар", "матч", "нападающего"],
        extraEnTokens: ["shot", "match", "striker"],
    },

    [phraseKey("mecz", "b2-31")]: {
        sk: "Cały mecz był bardzo wyrównany, ale końcówka należała do naszej drużyny.",
        ua: "Увесь матч був дуже рівним, але кінцівка належала нашій команді.",
        ru: "Весь матч был очень равным, но концовка осталась за нашей командой.",
        en: "The whole match was very even, but the final moments belonged to our team.",
        uaTokens: ["Увесь", "матч", "був", "дуже", "рівним", ",", "але", "кінцівка", "належала", "нашій", "команді", "."],
        ruTokens: ["Весь", "матч", "был", "очень", "равным", ",", "но", "концовка", "осталась", "за", "нашей", "командой", "."],
        enTokens: ["The", "whole", "match", "was", "very", "even", ",", "but", "the", "final", "moments", "belonged", "to", "our", "team", "."],
        extraUaTokens: ["гол", "пас", "суддя"],
        extraRuTokens: ["гол", "пас", "судья"],
        extraEnTokens: ["goal", "pass", "referee"],
    },

    // =========================
    // LESSON 32 — Теніс
    // =========================
    [phraseKey("kort tenisowy", "b2-32")]: {
        sk: "Kort tenisowy był mokry po deszczu, więc mecz rozpoczął się z opóźnieniem.",
        ua: "Тенісний корт був мокрий після дощу, тому матч почався із запізненням.",
        ru: "Теннисный корт был мокрым после дождя, поэтому матч начался с задержкой.",
        en: "The tennis court was wet after the rain, so the match started late.",
        uaTokens: ["Тенісний", "корт", "був", "мокрий", "після", "дощу", ",", "тому", "матч", "почався", "із", "запізненням", "."],
        ruTokens: ["Теннисный", "корт", "был", "мокрым", "после", "дождя", ",", "поэтому", "матч", "начался", "с", "задержкой", "."],
        enTokens: ["The", "tennis", "court", "was", "wet", "after", "the", "rain", ",", "so", "the", "match", "started", "late", "."],
        extraUaTokens: ["гравець", "м’яч", "суперник"],
        extraRuTokens: ["игрок", "мяч", "соперник"],
        extraEnTokens: ["player", "ball", "opponent"],
    },

    [phraseKey("rakieta", "b2-32")]: {
        sk: "Nowa rakieta była lżejsza, dzięki czemu mógł grać szybciej i dokładniej.",
        ua: "Нова ракетка була легшою, завдяки чому він міг грати швидше й точніше.",
        ru: "Новая ракетка была легче, благодаря чему он мог играть быстрее и точнее.",
        en: "The new racket was lighter, which allowed him to play faster and more accurately.",
        uaTokens: ["Нова", "ракетка", "була", "легшою", ",", "завдяки", "чому", "він", "міг", "грати", "швидше", "й", "точніше", "."],
        ruTokens: ["Новая", "ракетка", "была", "легче", ",", "благодаря", "чему", "он", "мог", "играть", "быстрее", "и", "точнее", "."],
        enTokens: ["The", "new", "racket", "was", "lighter", ",", "which", "allowed", "him", "to", "play", "faster", "and", "more", "accurately", "."],
        extraUaTokens: ["м’яч", "удар", "гра"],
        extraRuTokens: ["мяч", "удар", "игра"],
        extraEnTokens: ["ball", "shot", "game"],
    },

    [phraseKey("piłka", "b2-32")]: {
        sk: "Piłka odbiła się tuż przy linii i zaskoczyła przeciwnika.",
        ua: "М’яч відскочив просто біля лінії й здивував суперника.",
        ru: "Мяч отскочил прямо у линии и удивил соперника.",
        en: "The ball bounced right near the line and surprised the opponent.",
        uaTokens: ["М’яч", "відскочив", "просто", "біля", "лінії", "й", "здивував", "суперника", "."],
        ruTokens: ["Мяч", "отскочил", "прямо", "у", "линии", "и", "удивил", "соперника", "."],
        enTokens: ["The", "ball", "bounced", "right", "near", "the", "line", "and", "surprised", "the", "opponent", "."],
        extraUaTokens: ["ракетка", "сет", "подача"],
        extraRuTokens: ["ракетка", "сет", "подача"],
        extraEnTokens: ["racket", "set", "serve"],
    },

    [phraseKey("serwis", "b2-32")]: {
        sk: "Jego serwis był tak precyzyjny i mocny, że przeciwnik nie miał żadnych szans na skuteczną odpowiedź.",
        ua: "Його подача була настільки точною і сильною, що суперник не мав жодних шансів на вдалу відповідь.",
        ru: "Его подача была настолько точной и сильной, что соперник не имел никаких шансов на ответ.",
        en: "His serve was so precise and powerful that the opponent had no chance to respond effectively.",
        uaTokens: ["Його", "подача", "була", "настільки", "точною", "і", "сильною", ",", "що", "суперник", "не", "мав", "жодних", "шансів", "на", "вдалу", "відповідь", "."],
        ruTokens: ["Его", "подача", "была", "настолько", "точной", "и", "сильной", ",", "что", "соперник", "не", "имел", "никаких", "шансов", "на", "ответ", "."],
        enTokens: ["His", "serve", "was", "so", "precise", "and", "powerful", "that", "the", "opponent", "had", "no", "chance", "to", "respond", "effectively", "."],
        extraUaTokens: ["м’яч", "турнір", "лінії"],
        extraRuTokens: ["мяч", "турнир", "линии"],
        extraEnTokens: ["ball", "tournament", "line"],
    },
    [phraseKey("set", "b2-32")]: {
        sk: "Drugi set był najbardziej wyrównany i trwał prawie godzinę.",
        ua: "Другий сет був найрівнішим і тривав майже годину.",
        ru: "Второй сет был самым равным и длился почти час.",
        en: "The second set was the most even and lasted almost an hour.",
        uaTokens: ["Другий", "сет", "був", "найрівнішим", "і", "тривав", "майже", "годину", "."],
        ruTokens: ["Второй", "сет", "был", "самым", "равным", "и", "длился", "почти", "час", "."],
        enTokens: ["The", "second", "set", "was", "the", "most", "even", "and", "lasted", "almost", "an", "hour", "."],
        extraUaTokens: ["турнір", "гравців", "м’яч"],
        extraRuTokens: ["турнир", "игроков", "мяч"],
        extraEnTokens: ["tournament", "players", "ball"],
    },

    [phraseKey("turniej", "b2-32")]: {
        sk: "Ten turniej przyciągnął najlepszych zawodników z całego świata.",
        ua: "Цей турнір зібрав найкращих гравців з усього світу.",
        ru: "Этот турнир собрал лучших игроков со всего мира.",
        en: "This tournament attracted the best players from all over the world.",
        uaTokens: ["Цей", "турнір", "зібрав", "найкращих", "гравців", "з", "усього", "світу", "."],
        ruTokens: ["Этот", "турнир", "собрал", "лучших", "игроков", "со", "всего", "мира", "."],
        enTokens: ["This", "tournament", "attracted", "the", "best", "players", "from", "all", "over", "the", "world", "."],
        extraUaTokens: ["сет", "суперник", "удар"],
        extraRuTokens: ["сет", "соперник", "удар"],
        extraEnTokens: ["set", "opponent", "shot"],
    },

    [phraseKey("przeciwnik", "b2-32")]: {
        sk: "Jego przeciwnik był świetnie przygotowany fizycznie i taktycznie.",
        ua: "Його суперник був чудово підготовлений фізично й тактично.",
        ru: "Его соперник был отлично подготовлен физически и тактически.",
        en: "His opponent was excellently prepared physically and tactically.",
        uaTokens: ["Його", "суперник", "був", "чудово", "підготовлений", "фізично", "й", "тактично", "."],
        ruTokens: ["Его", "соперник", "был", "отлично", "подготовлен", "физически", "и", "тактически", "."],
        enTokens: ["His", "opponent", "was", "excellently", "prepared", "physically", "and", "tactically", "."],
        extraUaTokens: ["турнір", "подача", "лінії"],
        extraRuTokens: ["турнир", "подача", "линии"],
        extraEnTokens: ["tournament", "serve", "line"],
    },

    [phraseKey("punkt decydujący", "b2-32")]: {
        sk: "Punkt decydujący wymagał maksymalnego skupienia i zimnej krwi.",
        ua: "Вирішальне очко вимагало максимального зосередження та холоднокровності.",
        ru: "Решающее очко требовало максимальной концентрации и хладнокровия.",
        en: "The decisive point required maximum concentration and composure.",
        uaTokens: ["Вирішальне", "очко", "вимагало", "максимального", "зосередження", "та", "холоднокровності", "."],
        ruTokens: ["Решающее", "очко", "требовало", "максимальной", "концентрации", "и", "хладнокровия", "."],
        enTokens: ["The", "decisive", "point", "required", "maximum", "concentration", "and", "composure", "."],
        extraUaTokens: ["турнір", "гравців", "подача"],
        extraRuTokens: ["турнир", "игроков", "подача"],
        extraEnTokens: ["tournament", "players", "serve"],
    },

    [phraseKey("mocne uderzenie", "b2-32")]: {
        sk: "Mocne uderzenie zakończyło wymianę i dało mu przewagę psychiczną.",
        ua: "Сильний удар завершив розіграш і дав йому психологічну перевагу.",
        ru: "Сильный удар завершил розыгрыш и дал ему психологическое преимущество.",
        en: "A powerful shot ended the rally and gave him a mental advantage.",
        uaTokens: ["Сильний", "удар", "завершив", "розіграш", "і", "дав", "йому", "психологічну", "перевагу", "."],
        ruTokens: ["Сильный", "удар", "завершил", "розыгрыш", "и", "дал", "ему", "психологическое", "преимущество", "."],
        enTokens: ["A", "powerful", "shot", "ended", "the", "rally", "and", "gave", "him", "a", "mental", "advantage", "."],
        extraUaTokens: ["очко", "спокій", "суперник"],
        extraRuTokens: ["очко", "спокойствие", "соперник"],
        extraEnTokens: ["point", "calm", "opponent"],
    },

    [phraseKey("wygrać mecz", "b2-32")]: {
        sk: "Aby wygrać mecz, musiał zachować spokój do ostatniej piłki.",
        ua: "Щоб виграти матч, йому потрібно було зберігати спокій до останнього м’яча.",
        ru: "Чтобы выиграть матч, ему нужно было сохранять спокойствие до последнего мяча.",
        en: "To win the match, he had to stay calm until the very last ball.",
        uaTokens: ["Щоб", "виграти", "матч", ",", "йому", "потрібно", "було", "зберігати", "спокій", "до", "останнього", "м’яча", "."],
        ruTokens: ["Чтобы", "выиграть", "матч", ",", "ему", "нужно", "было", "сохранять", "спокойствие", "до", "последнего", "мяча", "."],
        enTokens: ["To", "win", "the", "match", ",", "he", "had", "to", "stay", "calm", "until", "the", "very", "last", "ball", "."],
        extraUaTokens: ["турнір", "очко", "лінії"],
        extraRuTokens: ["турнир", "очко", "линии"],
        extraEnTokens: ["tournament", "point", "line"],
    },

    // =========================
    // LESSON 33 — Риболовля
    // =========================
    [phraseKey("wędka", "b2-33")]: {
        sk: "Nowa wędka była znacznie lżejsza i wygodniejsza podczas długiego łowienia.",
        ua: "Нова вудка була значно легшою й зручнішою під час довгого рибалення.",
        ru: "Новая удочка была значительно легче и удобнее во время долгой рыбалки.",
        en: "The new fishing rod was much lighter and more comfortable during long fishing sessions.",
        uaTokens: ["Нова", "вудка", "була", "значно", "легшою", "й", "зручнішою", "під", "час", "довгого", "рибалення", "."],
        ruTokens: ["Новая", "удочка", "была", "значительно", "легче", "и", "удобнее", "во", "время", "долгой", "рыбалки", "."],
        enTokens: ["The", "new", "fishing", "rod", "was", "much", "lighter", "and", "more", "comfortable", "during", "long", "fishing", "sessions", "."],
        extraUaTokens: ["риба", "озеро", "гачок"],
        extraRuTokens: ["рыба", "озеро", "крючок"],
        extraEnTokens: ["fish", "lake", "hook"],
    },

    [phraseKey("kołowrotek", "b2-33")]: {
        sk: "Kołowrotek działał płynnie, dzięki czemu mógł szybko nawijać żyłkę.",
        ua: "Котушка працювала плавно, завдяки чому він міг швидко намотувати волосінь.",
        ru: "Катушка работала плавно, благодаря чему он мог быстро наматывать леску.",
        en: "The reel worked smoothly, allowing him to wind the line quickly.",
        uaTokens: ["Котушка", "працювала", "плавно", ",", "завдяки", "чому", "він", "міг", "швидко", "намотувати", "волосінь", "."],
        ruTokens: ["Катушка", "работала", "плавно", ",", "благодаря", "чему", "он", "мог", "быстро", "наматывать", "леску", "."],
        enTokens: ["The", "reel", "worked", "smoothly", ",", "allowing", "him", "to", "wind", "the", "line", "quickly", "."],
        extraUaTokens: ["вудка", "озеро", "улов"],
        extraRuTokens: ["удочка", "озеро", "улов"],
        extraEnTokens: ["rod", "lake", "catch"],
    },

    [phraseKey("haczyk", "b2-33")]: {
        sk: "Mały haczyk okazał się skuteczniejszy niż większy, którego używał wcześniej.",
        ua: "Маленький гачок виявився ефективнішим за більший, який він використовував раніше.",
        ru: "Маленький крючок оказался эффективнее большого, которым он пользовался раньше.",
        en: "The small hook turned out to be more effective than the larger one he used before.",
        uaTokens: ["Маленький", "гачок", "виявився", "ефективнішим", "за", "більший", ",", "який", "він", "використовував", "раніше", "."],
        ruTokens: ["Маленький", "крючок", "оказался", "эффективнее", "большого", ",", "которым", "он", "пользовался", "раньше", "."],
        enTokens: ["The", "small", "hook", "turned", "out", "to", "be", "more", "effective", "than", "the", "larger", "one", "he", "used", "before", "."],
        extraUaTokens: ["наживка", "рибалення", "човен"],
        extraRuTokens: ["наживка", "рыбалка", "лодка"],
        extraEnTokens: ["bait", "fishing", "boat"],
    },

    [phraseKey("przynęta", "b2-33")]: {
        sk: "Dobrze dobrana przynęta zwiększa szansę na udany połów.",
        ua: "Правильно підібрана наживка збільшує шанс на вдалий улов.",
        ru: "Правильно подобранная наживка увеличивает шанс на удачный улов.",
        en: "Well-chosen bait increases the chance of a successful catch.",
        uaTokens: ["Правильно", "підібрана", "наживка", "збільшує", "шанс", "на", "вдалий", "улов", "."],
        ruTokens: ["Правильно", "подобранная", "наживка", "увеличивает", "шанс", "на", "удачный", "улов", "."],
        enTokens: ["Well-chosen", "bait", "increases", "the", "chance", "of", "a", "successful", "catch", "."],
        extraUaTokens: ["гачок", "озеро", "вода"],
        extraRuTokens: ["крючок", "озеро", "вода"],
        extraEnTokens: ["hook", "lake", "water"],
    },

    [phraseKey("połów", "b2-33")]: {
        sk: "Dzisiejszy połów był wyjątkowo udany, mimo że pogoda nie sprzyjała.",
        ua: "Сьогоднішній улов був надзвичайно вдалим, хоча погода не сприяла.",
        ru: "Сегодняшний улов был исключительно удачным, хотя погода не способствовала.",
        en: "Today's catch was exceptionally successful, even though the weather was not favorable.",
        uaTokens: ["Сьогоднішній", "улов", "був", "надзвичайно", "вдалим", ",", "хоча", "погода", "не", "сприяла", "."],
        ruTokens: ["Сегодняшний", "улов", "был", "исключительно", "удачным", ",", "хотя", "погода", "не", "способствовала", "."],
        enTokens: ["Today's", "catch", "was", "exceptionally", "successful", ",", "even", "though", "the", "weather", "was", "not", "favorable", "."],
        extraUaTokens: ["наживка", "гачок", "озеро"],
        extraRuTokens: ["наживка", "крючок", "озеро"],
        extraEnTokens: ["bait", "hook", "lake"],
    },

    [phraseKey("rybak", "b2-33")]: {
        sk: "Doświadczony rybak znał to jezioro lepiej niż ktokolwiek inny.",
        ua: "Досвідчений рибалка знав це озеро краще за будь-кого іншого.",
        ru: "Опытный рыбак знал это озеро лучше, чем кто-либо другой.",
        en: "The experienced fisherman knew this lake better than anyone else.",
        uaTokens: ["Досвідчений", "рибалка", "знав", "це", "озеро", "краще", "за", "будь-кого", "іншого", "."],
        ruTokens: ["Опытный", "рыбак", "знал", "это", "озеро", "лучше", ",", "чем", "кто-либо", "другой", "."],
        enTokens: ["The", "experienced", "fisherman", "knew", "this", "lake", "better", "than", "anyone", "else", "."],
        extraUaTokens: ["вудка", "човен", "вода"],
        extraRuTokens: ["удочка", "лодка", "вода"],
        extraEnTokens: ["rod", "boat", "water"],
    },

    [phraseKey("jezioro", "b2-33")]: {
        sk: "To jezioro jest spokojne o poranku i idealne do łowienia ryb.",
        ua: "Це озеро спокійне вранці й ідеальне для ловлі риби.",
        ru: "Это озеро спокойное по утрам и идеально подходит для рыбалки.",
        en: "This lake is calm in the morning and perfect for fishing.",
        uaTokens: ["Це", "озеро", "спокійне", "вранці", "й", "ідеальне", "для", "ловлі", "риби", "."],
        ruTokens: ["Это", "озеро", "спокойное", "по", "утрам", "и", "идеально", "подходит", "для", "рыбалки", "."],
        enTokens: ["This", "lake", "is", "calm", "in", "the", "morning", "and", "perfect", "for", "fishing", "."],
        extraUaTokens: ["човен", "берег", "улов"],
        extraRuTokens: ["лодка", "берег", "улов"],
        extraEnTokens: ["boat", "shore", "catch"],
    },

    [phraseKey("brzeg", "b2-33")]: {
        sk: "Usiedliśmy na brzegu i przez długi czas obserwowaliśmy wodę.",
        ua: "Ми сіли на березі й довго спостерігали за водою.",
        ru: "Мы сели на берегу и долго наблюдали за водой.",
        en: "We sat on the shore and watched the water for a long time.",
        uaTokens: ["Ми", "сіли", "на", "березі", "й", "довго", "спостерігали", "за", "водою", "."],
        ruTokens: ["Мы", "сели", "на", "берегу", "и", "долго", "наблюдали", "за", "водой", "."],
        enTokens: ["We", "sat", "on", "the", "shore", "and", "watched", "the", "water", "for", "a", "long", "time", "."],
        extraUaTokens: ["озеро", "човен", "рибу"],
        extraRuTokens: ["озеро", "лодка", "рыбу"],
        extraEnTokens: ["lake", "boat", "fish"],
    },

    [phraseKey("łódź", "b2-33")]: {
        sk: "Mała łódź pozwoliła nam dopłynąć do miejsc, gdzie było więcej ryb.",
        ua: "Маленький човен дозволив нам дістатися до місць, де було більше риби.",
        ru: "Маленькая лодка позволила нам добраться до мест, где было больше рыбы.",
        en: "The small boat allowed us to reach places where there were more fish.",
        uaTokens: ["Маленький", "човен", "дозволив", "нам", "дістатися", "до", "місць", ",", "де", "було", "більше", "риби", "."],
        ruTokens: ["Маленькая", "лодка", "позволила", "нам", "добраться", "до", "мест", ",", "где", "было", "больше", "рыбы", "."],
        enTokens: ["The", "small", "boat", "allowed", "us", "to", "reach", "places", "where", "there", "were", "more", "fish", "."],
        extraUaTokens: ["озеро", "берег", "улов"],
        extraRuTokens: ["озеро", "берег", "улов"],
        extraEnTokens: ["lake", "shore", "catch"],
    },

    [phraseKey("złowić rybę", "b2-33")]: {
        sk: "Nie było łatwo złowić rybę, bo woda była dziś wyjątkowo przejrzysta.",
        ua: "Було нелегко зловити рибу, бо вода сьогодні була надзвичайно прозорою.",
        ru: "Было нелегко поймать рыбу, потому что вода сегодня была необычайно прозрачной.",
        en: "It was not easy to catch a fish because the water was exceptionally clear today.",
        uaTokens: ["Було", "нелегко", "зловити", "рибу", ",", "бо", "вода", "сьогодні", "була", "надзвичайно", "прозорою", "."],
        ruTokens: ["Было", "нелегко", "поймать", "рыбу", ",", "потому", "что", "вода", "сегодня", "была", "необычайно", "прозрачной", "."],
        enTokens: ["It", "was", "not", "easy", "to", "catch", "a", "fish", "because", "the", "water", "was", "exceptionally", "clear", "today", "."],
        extraUaTokens: ["човен", "озеро", "наживка"],
        extraRuTokens: ["лодка", "озеро", "наживка"],
        extraEnTokens: ["boat", "lake", "bait"],
    },

    // =========================
    // LESSON 34 — Автомобілі
    // =========================
    [phraseKey("marka samochodu", "b2-34")]: {
        sk: "Dla niego marka samochodu była mniej ważna niż niezawodność i wygoda jazdy.",
        ua: "Для нього марка автомобіля була менш важливою, ніж надійність і комфорт їзди.",
        ru: "Для него марка автомобиля была менее важна, чем надёжность и комфорт езды.",
        en: "For him, the car brand was less important than reliability and driving comfort.",
        uaTokens: ["Для", "нього", "марка", "автомобіля", "була", "менш", "важливою", ",", "ніж", "надійність", "і", "комфорт", "їзди", "."],
        ruTokens: ["Для", "него", "марка", "автомобиля", "была", "менее", "важна", ",", "чем", "надёжность", "и", "комфорт", "езды", "."],
        enTokens: ["For", "him", ",", "the", "car", "brand", "was", "less", "important", "than", "reliability", "and", "driving", "comfort", "."],
        extraUaTokens: ["двигун", "дорога", "швидкість"],
        extraRuTokens: ["двигатель", "дорога", "скорость"],
        extraEnTokens: ["engine", "road", "speed"],
    },

    [phraseKey("samochód osobowy", "b2-34")]: {
        sk: "Ten samochód osobowy świetnie sprawdza się zarówno w mieście, jak i w trasie.",
        ua: "Цей легковий автомобіль чудово підходить як для міста, так і для далеких поїздок.",
        ru: "Этот легковой автомобиль отлично подходит как для города, так и для дальних поездок.",
        en: "This passenger car works great both in the city and on longer trips.",
        uaTokens: ["Цей", "легковий", "автомобіль", "чудово", "підходить", "як", "для", "міста", ",", "так", "і", "для", "далеких", "поїздок", "."],
        ruTokens: ["Этот", "легковой", "автомобиль", "отлично", "подходит", "как", "для", "города", ",", "так", "и", "для", "дальних", "поездок", "."],
        enTokens: ["This", "passenger", "car", "works", "great", "both", "in", "the", "city", "and", "on", "longer", "trips", "."],
        extraUaTokens: ["марка", "двигун", "паркування"],
        extraRuTokens: ["марка", "двигатель", "парковка"],
        extraEnTokens: ["brand", "engine", "parking"],
    },

    [phraseKey("sedan", "b2-34")]: {
        sk: "Sedan wygląda elegancko i zwykle oferuje wysoki komfort podróżowania.",
        ua: "Седан виглядає елегантно й зазвичай пропонує високий комфорт подорожі.",
        ru: "Седан выглядит элегантно и обычно обеспечивает высокий комфорт поездки.",
        en: "A sedan looks elegant and usually offers a high level of travel comfort.",
        uaTokens: ["Седан", "виглядає", "елегантно", "й", "зазвичай", "пропонує", "високий", "комфорт", "подорожі", "."],
        ruTokens: ["Седан", "выглядит", "элегантно", "и", "обычно", "обеспечивает", "высокий", "комфорт", "поездки", "."],
        enTokens: ["A", "sedan", "looks", "elegant", "and", "usually", "offers", "a", "high", "level", "of", "travel", "comfort", "."],
        extraUaTokens: ["автомобіль", "двигун", "міста"],
        extraRuTokens: ["автомобиль", "двигатель", "города"],
        extraEnTokens: ["car", "engine", "city"],
    },

    [phraseKey("SUV", "b2-34")]: {
        sk: "SUV jest popularny wśród kierowców, którzy cenią wyższą pozycję za kierownicą.",
        ua: "Позашляховик популярний серед водіїв, які цінують вищу посадку за кермом.",
        ru: "Внедорожник популярен среди водителей, которые ценят более высокую посадку за рулём.",
        en: "An SUV is popular among drivers who value a higher driving position.",
        uaTokens: ["Позашляховик", "популярний", "серед", "водіїв", ",", "які", "цінують", "вищу", "посадку", "за", "кермом", "."],
        ruTokens: ["Внедорожник", "популярен", "среди", "водителей", ",", "которые", "ценят", "более", "высокую", "посадку", "за", "рулём", "."],
        enTokens: ["An", "SUV", "is", "popular", "among", "drivers", "who", "value", "a", "higher", "driving", "position", "."],
        extraUaTokens: ["седан", "паркування", "двигун"],
        extraRuTokens: ["седан", "парковка", "двигатель"],
        extraEnTokens: ["sedan", "parking", "engine"],
    },

    [phraseKey("hatchback", "b2-34")]: {
        sk: "Hatchback jest praktyczny, kompaktowy i łatwy do parkowania w mieście.",
        ua: "Хетчбек практичний, компактний і легкий для паркування в місті.",
        ru: "Хэтчбек практичный, компактный и удобный для парковки в городе.",
        en: "A hatchback is practical, compact, and easy to park in the city.",
        uaTokens: ["Хетчбек", "практичний", ",", "компактний", "і", "легкий", "для", "паркування", "в", "місті", "."],
        ruTokens: ["Хэтчбек", "практичный", ",", "компактный", "и", "удобный", "для", "парковки", "в", "городе", "."],
        enTokens: ["A", "hatchback", "is", "practical", ",", "compact", ",", "and", "easy", "to", "park", "in", "the", "city", "."],
        extraUaTokens: ["водіїв", "комфорт", "перевірки"],
        extraRuTokens: ["водителей", "комфорт", "проверки"],
        extraEnTokens: ["drivers", "comfort", "inspection"],
    },

    [phraseKey("Volkswagen", "b2-34")]: {
        sk: "Volkswagen od lat kojarzy się z solidnością i rozsądnymi kosztami eksploatacji.",
        ua: "Volkswagen багато років асоціюється з надійністю та розумними витратами на експлуатацію.",
        ru: "Volkswagen уже много лет ассоциируется с надёжностью и разумными расходами на эксплуатацию.",
        en: "Volkswagen has long been associated with reliability and reasonable running costs.",
        uaTokens: ["Volkswagen", "багато", "років", "асоціюється", "з", "надійністю", "та", "розумними", "витратами", "на", "експлуатацію", "."],
        ruTokens: ["Volkswagen", "уже", "много", "лет", "ассоциируется", "с", "надёжностью", "и", "разумными", "расходами", "на", "эксплуатацию", "."],
        enTokens: ["Volkswagen", "has", "long", "been", "associated", "with", "reliability", "and", "reasonable", "running", "costs", "."],
        extraUaTokens: ["Toyota", "BMW", "двигун"],
        extraRuTokens: ["Toyota", "BMW", "двигатель"],
        extraEnTokens: ["Toyota", "BMW", "engine"],
    },

    [phraseKey("BMW", "b2-34")]: {
        sk: "BMW często wybierają kierowcy, którzy lubią dynamiczną jazdę i mocny silnik.",
        ua: "BMW часто обирають водії, які люблять динамічну їзду та потужний двигун.",
        ru: "BMW часто выбирают водители, которые любят динамичную езду и мощный двигатель.",
        en: "BMW is often chosen by drivers who enjoy dynamic driving and a powerful engine.",
        uaTokens: ["BMW", "часто", "обирають", "водії", ",", "які", "люблять", "динамічну", "їзду", "та", "потужний", "двигун", "."],
        ruTokens: ["BMW", "часто", "выбирают", "водители", ",", "которые", "любят", "динамичную", "езду", "и", "мощный", "двигатель", "."],
        enTokens: ["BMW", "is", "often", "chosen", "by", "drivers", "who", "enjoy", "dynamic", "driving", "and", "a", "powerful", "engine", "."],
        extraUaTokens: ["Mercedes", "Volkswagen", "комфорт"],
        extraRuTokens: ["Mercedes", "Volkswagen", "комфорт"],
        extraEnTokens: ["Mercedes", "Volkswagen", "comfort"],
    },

    [phraseKey("Mercedes", "b2-34")]: {
        sk: "Mercedes kojarzy się wielu osobom z prestiżem, wygodą i nowoczesnymi technologiami.",
        ua: "Mercedes у багатьох асоціюється з престижем, комфортом і сучасними технологіями.",
        ru: "Mercedes у многих ассоциируется с престижем, комфортом и современными технологиями.",
        en: "Mercedes is associated by many people with prestige, comfort, and modern technology.",
        uaTokens: ["Mercedes", "у", "багатьох", "асоціюється", "з", "престижем", ",", "комфортом", "і", "сучасними", "технологіями", "."],
        ruTokens: ["Mercedes", "у", "многих", "ассоциируется", "с", "престижем", ",", "комфортом", "и", "современными", "технологиями", "."],
        enTokens: ["Mercedes", "is", "associated", "by", "many", "people", "with", "prestige", ",", "comfort", ",", "and", "modern", "technology", "."],
        extraUaTokens: ["Toyota", "BMW", "міста"],
        extraRuTokens: ["Toyota", "BMW", "города"],
        extraEnTokens: ["Toyota", "BMW", "city"],
    },

    [phraseKey("Toyota", "b2-34")]: {
        sk: "Toyota słynie z trwałości, dlatego wiele osób ufa tej marce od lat.",
        ua: "Toyota славиться довговічністю, тому багато людей довіряють цій марці роками.",
        ru: "Toyota славится долговечностью, поэтому многие люди доверяют этой марке годами.",
        en: "Toyota is known for durability, which is why many people have trusted this brand for years.",
        uaTokens: ["Toyota", "славиться", "довговічністю", ",", "тому", "багато", "людей", "довіряють", "цій", "марці", "роками", "."],
        ruTokens: ["Toyota", "славится", "долговечностью", ",", "поэтому", "многие", "люди", "доверяют", "этой", "марке", "годами", "."],
        enTokens: ["Toyota", "is", "known", "for", "durability", ",", "which", "is", "why", "many", "people", "have", "trusted", "this", "brand", "for", "years", "."],
        extraUaTokens: ["Volkswagen", "Mercedes", "двигун"],
        extraRuTokens: ["Volkswagen", "Mercedes", "двигатель"],
        extraEnTokens: ["Volkswagen", "Mercedes", "engine"],
    },

    [phraseKey("silnik pojazdu", "b2-34")]: {
        sk: "Silnik pojazdu wymaga regularnej kontroli, jeśli ma działać bezawaryjnie.",
        ua: "Двигун автомобіля потребує регулярної перевірки, якщо має працювати безвідмовно.",
        ru: "Двигатель автомобиля требует регулярной проверки, если он должен работать безотказно.",
        en: "A car engine requires regular inspection if it is to run reliably.",
        uaTokens: ["Двигун", "автомобіля", "потребує", "регулярної", "перевірки", ",", "якщо", "має", "працювати", "безвідмовно", "."],
        ruTokens: ["Двигатель", "автомобиля", "требует", "регулярной", "проверки", ",", "если", "он", "должен", "работать", "безотказно", "."],
        enTokens: ["A", "car", "engine", "requires", "regular", "inspection", "if", "it", "is", "to", "run", "reliably", "."],
        extraUaTokens: ["марка", "водії", "паркування"],
        extraRuTokens: ["марка", "водители", "парковка"],
        extraEnTokens: ["brand", "drivers", "parking"],
    },

    // =========================
    // LESSON 35 — Морський транспорт
    // =========================
    [phraseKey("łódź", "b2-35")]: {
        sk: "Ta łódź była wystarczająco duża, aby bezpiecznie przewieźć cały sprzęt.",
        ua: "Цей човен був достатньо великий, щоб безпечно перевезти все обладнання.",
        ru: "Эта лодка была достаточно большой, чтобы безопасно перевезти всё оборудование.",
        en: "This boat was large enough to safely carry all the equipment.",
        uaTokens: ["Цей", "човен", "був", "достатньо", "великий", ",", "щоб", "безпечно", "перевезти", "все", "обладнання", "."],
        ruTokens: ["Эта", "лодка", "была", "достаточно", "большой", ",", "чтобы", "безопасно", "перевезти", "всё", "оборудование", "."],
        enTokens: ["This", "boat", "was", "large", "enough", "to", "safely", "carry", "all", "the", "equipment", "."],
        extraUaTokens: ["порт", "вода", "море"],
        extraRuTokens: ["порт", "вода", "море"],
        extraEnTokens: ["port", "water", "sea"],
    },

    [phraseKey("łódź podwodna", "b2-35")]: {
        sk: "Łódź podwodna może przez długi czas poruszać się pod powierzchnią wody.",
        ua: "Субмарина може довгий час рухатися під поверхнею води.",
        ru: "Подводная лодка может долго двигаться под поверхностью воды.",
        en: "A submarine can move under the surface of the water for a long time.",
        uaTokens: ["Субмарина", "може", "довгий", "час", "рухатися", "під", "поверхнею", "води", "."],
        ruTokens: ["Подводная", "лодка", "может", "долго", "двигаться", "под", "поверхностью", "воды", "."],
        enTokens: ["A", "submarine", "can", "move", "under", "the", "surface", "of", "the", "water", "for", "a", "long", "time", "."],
        extraUaTokens: ["порт", "палуби", "маршрут"],
        extraRuTokens: ["порт", "палубы", "маршрут"],
        extraEnTokens: ["port", "deck", "route"],
    },

    [phraseKey("port", "b2-35")]: {
        sk: "Port był bardzo zatłoczony, ponieważ jednocześnie przypłynęło kilka statków.",
        ua: "Порт був дуже завантажений, оскільки одночасно прибуло кілька суден.",
        ru: "Порт был очень загружен, потому что одновременно прибыло несколько судов.",
        en: "The port was very crowded because several ships arrived at the same time.",
        uaTokens: ["Порт", "був", "дуже", "завантажений", ",", "оскільки", "одночасно", "прибуло", "кілька", "суден", "."],
        ruTokens: ["Порт", "был", "очень", "загружен", ",", "потому", "что", "одновременно", "прибыло", "несколько", "судов", "."],
        enTokens: ["The", "port", "was", "very", "crowded", "because", "several", "ships", "arrived", "at", "the", "same", "time", "."],
        extraUaTokens: ["корабель", "палуби", "капітан"],
        extraRuTokens: ["корабль", "палубы", "капитан"],
        extraEnTokens: ["ship", "deck", "captain"],
    },

    [phraseKey("pokład", "b2-35")]: {
        sk: "Z pokładu rozciągał się wspaniały widok na całe wybrzeże.",
        ua: "З палуби відкривався чудовий краєвид на все узбережжя.",
        ru: "С палубы открывался прекрасный вид на всё побережье.",
        en: "From the deck, there was a wonderful view of the entire coast.",
        uaTokens: ["З", "палуби", "відкривався", "чудовий", "краєвид", "на", "все", "узбережжя", "."],
        ruTokens: ["С", "палубы", "открывался", "прекрасный", "вид", "на", "всё", "побережье", "."],
        enTokens: ["From", "the", "deck", ",", "there", "was", "a", "wonderful", "view", "of", "the", "entire", "coast", "."],
        extraUaTokens: ["порт", "корабель", "моряк"],
        extraRuTokens: ["порт", "корабль", "моряк"],
        extraEnTokens: ["port", "ship", "sailor"],
    },

    [phraseKey("kapitan", "b2-35")]: {
        sk: "Kapitan zachował spokój nawet wtedy, gdy pogoda nagle się pogorszyła.",
        ua: "Капітан зберіг спокій навіть тоді, коли погода раптово погіршилася.",
        ru: "Капитан сохранил спокойствие даже тогда, когда погода внезапно ухудшилась.",
        en: "The captain remained calm even when the weather suddenly worsened.",
        uaTokens: ["Капітан", "зберіг", "спокій", "навіть", "тоді", ",", "коли", "погода", "раптово", "погіршилася", "."],
        ruTokens: ["Капитан", "сохранил", "спокойствие", "даже", "тогда", ",", "когда", "погода", "внезапно", "ухудшилась", "."],
        enTokens: ["The", "captain", "remained", "calm", "even", "when", "the", "weather", "suddenly", "worsened", "."],
        extraUaTokens: ["порт", "моряк", "вода"],
        extraRuTokens: ["порт", "моряк", "вода"],
        extraEnTokens: ["port", "sailor", "water"],
    },

    [phraseKey("marynarz", "b2-35")]: {
        sk: "Doświadczony marynarz potrafił szybko reagować na zmieniające się warunki na morzu.",
        ua: "Досвідчений моряк умів швидко реагувати на змінні умови на морі.",
        ru: "Опытный моряк умел быстро реагировать на меняющиеся условия в море.",
        en: "An experienced sailor could quickly react to changing sea conditions.",
        uaTokens: ["Досвідчений", "моряк", "умів", "швидко", "реагувати", "на", "змінні", "умови", "на", "морі", "."],
        ruTokens: ["Опытный", "моряк", "умел", "быстро", "реагировать", "на", "меняющиеся", "условия", "в", "море", "."],
        enTokens: ["An", "experienced", "sailor", "could", "quickly", "react", "to", "changing", "sea", "conditions", "."],
        extraUaTokens: ["капітан", "корабель", "палуби"],
        extraRuTokens: ["капитан", "корабль", "палубы"],
        extraEnTokens: ["captain", "ship", "deck"],
    },

    [phraseKey("statek", "b2-35")]: {
        sk: "Nowoczesny statek przewozi ogromne ilości towarów między kontynentami.",
        ua: "Сучасне судно перевозить величезні обсяги товарів між континентами.",
        ru: "Современное судно перевозит огромные объёмы товаров между континентами.",
        en: "A modern vessel transports huge amounts of goods between continents.",
        uaTokens: ["Сучасне", "судно", "перевозить", "величезні", "обсяги", "товарів", "між", "континентами", "."],
        ruTokens: ["Современное", "судно", "перевозит", "огромные", "объёмы", "товаров", "между", "континентами", "."],
        enTokens: ["A", "modern", "vessel", "transports", "huge", "amounts", "of", "goods", "between", "continents", "."],
        extraUaTokens: ["порт", "маршрут", "економіки"],
        extraRuTokens: ["порт", "маршрут", "экономики"],
        extraEnTokens: ["port", "route", "economy"],
    },

    [phraseKey("trasa morska", "b2-35")]: {
        sk: "Ta trasa morska jest jedną z najważniejszych dróg handlowych na świecie.",
        ua: "Цей морський маршрут є одним із найважливіших торговельних шляхів у світі.",
        ru: "Этот морской маршрут является одним из важнейших торговых путей в мире.",
        en: "This sea route is one of the most important trade routes in the world.",
        uaTokens: ["Цей", "морський", "маршрут", "є", "одним", "із", "найважливіших", "торговельних", "шляхів", "у", "світі", "."],
        ruTokens: ["Этот", "морской", "маршрут", "является", "одним", "из", "важнейших", "торговых", "путей", "в", "мире", "."],
        enTokens: ["This", "sea", "route", "is", "one", "of", "the", "most", "important", "trade", "routes", "in", "the", "world", "."],
        extraUaTokens: ["судно", "порт", "моряк"],
        extraRuTokens: ["судно", "порт", "моряк"],
        extraEnTokens: ["vessel", "port", "sailor"],
    },

    [phraseKey("zanurzyć się", "b2-35")]: {
        sk: "Łódź podwodna musiała zanurzyć się głębiej, aby uniknąć wykrycia.",
        ua: "Субмарина мусила зануритися глибше, щоб уникнути виявлення.",
        ru: "Подводная лодка должна была погрузиться глубже, чтобы избежать обнаружения.",
        en: "The submarine had to dive deeper to avoid detection.",
        uaTokens: ["Субмарина", "мусила", "зануритися", "глибше", ",", "щоб", "уникнути", "виявлення", "."],
        ruTokens: ["Подводная", "лодка", "должна", "была", "погрузиться", "глубже", ",", "чтобы", "избежать", "обнаружения", "."],
        enTokens: ["The", "submarine", "had", "to", "dive", "deeper", "to", "avoid", "detection", "."],
        extraUaTokens: ["маршрут", "порт", "вода"],
        extraRuTokens: ["маршрут", "порт", "вода"],
        extraEnTokens: ["route", "port", "water"],
    },

    [phraseKey("transport morski", "b2-35")]: {
        sk: "Transport morski pozostaje kluczowy dla światowej gospodarki i wymiany handlowej.",
        ua: "Морський транспорт залишається ключовим для світової економіки та торгівлі.",
        ru: "Морской транспорт остаётся ключевым для мировой экономики и торговли.",
        en: "Maritime transport remains crucial for the global economy and trade.",
        uaTokens: ["Морський", "транспорт", "залишається", "ключовим", "для", "світової", "економіки", "та", "торгівлі", "."],
        ruTokens: ["Морской", "транспорт", "остаётся", "ключевым", "для", "мировой", "экономики", "и", "торговли", "."],
        enTokens: ["Maritime", "transport", "remains", "crucial", "for", "the", "global", "economy", "and", "trade", "."],
        extraUaTokens: ["маршрут", "судно", "порт"],
        extraRuTokens: ["маршрут", "судно", "порт"],
        extraEnTokens: ["route", "vessel", "port"],
    },
};