import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_B2_BUILD_UA_SENTENCES_9: BuildUaSentenceDict = {
    // =========================
    // LESSON 41 — Мистецтво
    // =========================
    [phraseKey("dzieło sztuki", "b2-41")]: {
        sk: "To dzieło sztuki wywołuje silne emocje i skłania do refleksji.",
        ua: "Цей твір мистецтва викликає сильні емоції та спонукає до роздумів.",
        ru: "Это произведение искусства вызывает сильные эмоции и побуждает к размышлению.",
        en: "This work of art evokes strong emotions and encourages reflection.",
        uaTokens: ["Цей", "твір", "мистецтва", "викликає", "сильні", "емоції", "та", "спонукає", "до", "роздумів", "."],
        ruTokens: ["Это", "произведение", "искусства", "вызывает", "сильные", "эмоции", "и", "побуждает", "к", "размышлению", "."],
        enTokens: ["This", "work", "of", "art", "evokes", "strong", "emotions", "and", "encourages", "reflection", "."],
        extraUaTokens: ["картиною", "критика", "міста"],
        extraRuTokens: ["картиной", "критика", "города"],
        extraEnTokens: ["painting", "criticism", "city"],
    },

    [phraseKey("malarz", "b2-41")]: {
        sk: "Malarz pracował nad tym obrazem przez kilka miesięcy, zanim uznał go za skończony.",
        ua: "Художник працював над цією картиною кілька місяців, перш ніж визнав її завершеною.",
        ru: "Художник работал над этой картиной несколько месяцев, прежде чем признал её завершённой.",
        en: "The painter worked on this painting for several months before considering it finished.",
        uaTokens: ["Художник", "працював", "над", "цією", "картиною", "кілька", "місяців", ",", "перш", "ніж", "визнав", "її", "завершеною", "."],
        ruTokens: ["Художник", "работал", "над", "этой", "картиной", "несколько", "месяцев", ",", "прежде", "чем", "признал", "её", "завершённой", "."],
        enTokens: ["The", "painter", "worked", "on", "this", "painting", "for", "several", "months", "before", "considering", "it", "finished", "."],
        extraUaTokens: ["полотна", "портрет", "критика"],
        extraRuTokens: ["холста", "портрет", "критика"],
        extraEnTokens: ["canvas", "portrait", "criticism"],
    },

    [phraseKey("pomnik", "b2-41")]: {
        sk: "Ten pomnik upamiętnia ważne wydarzenie, które odegrało dużą rolę w historii miasta.",
        ua: "Ця скульптура вшановує важливу подію, яка відіграла велику роль в історії міста.",
        ru: "Эта скульптура посвящена важному событию, сыгравшему большую роль в истории города.",
        en: "This sculpture commemorates an important event that played a major role in the city's history.",
        uaTokens: ["Ця", "скульптура", "вшановує", "важливу", "подію", ",", "яка", "відіграла", "велику", "роль", "в", "історії", "міста", "."],
        ruTokens: ["Эта", "скульптура", "посвящена", "важному", "событию", ",", "сыгравшему", "большую", "роль", "в", "истории", "города", "."],
        enTokens: ["This", "sculpture", "commemorates", "an", "important", "event", "that", "played", "a", "major", "role", "in", "the", "city's", "history", "."],
        extraUaTokens: ["твір", "архітектура", "фасад"],
        extraRuTokens: ["произведение", "архитектура", "фасад"],
        extraEnTokens: ["artwork", "architecture", "facade"],
    },

    [phraseKey("płótno", "b2-41")]: {
        sk: "Artysta zaczął od pustego płótna, ale już po kilku godzinach kompozycja była wyraźna.",
        ua: "Художник почав із порожнього полотна, але вже за кілька годин композиція стала чіткою.",
        ru: "Художник начал с пустого холста, но уже через несколько часов композиция стала чёткой.",
        en: "The artist started with a blank canvas, but after just a few hours the composition was clear.",
        uaTokens: ["Художник", "почав", "із", "порожнього", "полотна", ",", "але", "вже", "за", "кілька", "годин", "композиція", "стала", "чіткою", "."],
        ruTokens: ["Художник", "начал", "с", "пустого", "холста", ",", "но", "уже", "через", "несколько", "часов", "композиция", "стала", "чёткой", "."],
        enTokens: ["The", "artist", "started", "with", "a", "blank", "canvas", ",", "but", "after", "just", "a", "few", "hours", "the", "composition", "was", "clear", "."],
        extraUaTokens: ["картиною", "техніка", "критика"],
        extraRuTokens: ["картиной", "техника", "критика"],
        extraEnTokens: ["painting", "technique", "criticism"],
    },

    [phraseKey("portret", "b2-41")]: {
        sk: "Ten portret oddaje nie tylko wygląd modela, ale także jego nastrój i charakter.",
        ua: "Цей портрет передає не лише зовнішність моделі, а й її настрій і характер.",
        ru: "Этот портрет передаёт не только внешность модели, но и её настроение и характер.",
        en: "This portrait captures not only the model's appearance but also their mood and character.",
        uaTokens: ["Цей", "портрет", "передає", "не", "лише", "зовнішність", "моделі", ",", "а", "й", "її", "настрій", "і", "характер", "."],
        ruTokens: ["Этот", "портрет", "передаёт", "не", "только", "внешность", "модели", ",", "но", "и", "её", "настроение", "и", "характер", "."],
        enTokens: ["This", "portrait", "captures", "not", "only", "the", "model's", "appearance", "but", "also", "their", "mood", "and", "character", "."],
        extraUaTokens: ["картиною", "полотна", "стиль"],
        extraRuTokens: ["картиной", "холста", "стиль"],
        extraEnTokens: ["painting", "canvas", "style"],
    },

    [phraseKey("styl artystyczny", "b2-41")]: {
        sk: "Jego styl artystyczny jest tak charakterystyczny, że trudno pomylić go z innym twórcą.",
        ua: "Його художній стиль настільки характерний, що його важко сплутати з іншим митцем.",
        ru: "Его художественный стиль настолько характерен, что его трудно спутать с другим автором.",
        en: "His artistic style is so distinctive that it is hard to confuse him with another artist.",
        uaTokens: ["Його", "художній", "стиль", "настільки", "характерний", ",", "що", "його", "важко", "сплутати", "з", "іншим", "митцем", "."],
        ruTokens: ["Его", "художественный", "стиль", "настолько", "характерен", ",", "что", "его", "трудно", "спутать", "с", "другим", "автором", "."],
        enTokens: ["His", "artistic", "style", "is", "so", "distinctive", "that", "it", "is", "hard", "to", "confuse", "him", "with", "another", "artist", "."],
        extraUaTokens: ["портрет", "техніка", "архітектура"],
        extraRuTokens: ["портрет", "техника", "архитектура"],
        extraEnTokens: ["portrait", "technique", "architecture"],
    },

    [phraseKey("sztuka abstrakcyjna", "b2-41")]: {
        sk: "Sztuka abstrakcyjna nie przedstawia rzeczywistości dosłownie, lecz działa formą i kolorem.",
        ua: "Абстрактне мистецтво не зображає реальність буквально, а працює формою і кольором.",
        ru: "Абстрактное искусство не изображает реальность буквально, а работает формой и цветом.",
        en: "Abstract art does not depict reality literally, but works through form and color.",
        uaTokens: ["Абстрактне", "мистецтво", "не", "зображає", "реальність", "буквально", ",", "а", "працює", "формою", "і", "кольором", "."],
        ruTokens: ["Абстрактное", "искусство", "не", "изображает", "реальность", "буквально", ",", "а", "работает", "формой", "и", "цветом", "."],
        enTokens: ["Abstract", "art", "does", "not", "depict", "reality", "literally", ",", "but", "works", "through", "form", "and", "color", "."],
        extraUaTokens: ["портрет", "картина", "критика"],
        extraRuTokens: ["портрет", "картина", "критика"],
        extraEnTokens: ["portrait", "painting", "criticism"],
    },

    [phraseKey("obraz", "b2-41")]: {
        sk: "Ten obraz przyciąga uwagę swoją kompozycją, a jednocześnie pozostawia miejsce na własną interpretację.",
        ua: "Ця картина привертає увагу своєю композицією і водночас залишає простір для власної інтерпретації.",
        ru: "Эта картина привлекает внимание своей композицией и в то же время оставляет место для собственной интерпретации.",
        en: "This painting attracts attention with its composition while still leaving room for personal interpretation.",
        uaTokens: ["Ця", "картина", "привертає", "увагу", "своєю", "композицією", "і", "водночас", "залишає", "простір", "для", "власної", "інтерпретації", "."],
        ruTokens: ["Эта", "картина", "привлекает", "внимание", "своей", "композицией", "и", "в", "то", "же", "время", "оставляет", "место", "для", "собственной", "интерпретации", "."],
        enTokens: ["This", "painting", "attracts", "attention", "with", "its", "composition", "while", "still", "leaving", "room", "for", "personal", "interpretation", "."],
        extraUaTokens: ["полотно", "критика", "стиль"],
        extraRuTokens: ["холст", "критика", "стиль"],
        extraEnTokens: ["canvas", "criticism", "style"],
    },

    [phraseKey("technika artystyczna", "b2-41")]: {
        sk: "Wybrana technika artystyczna miała ogromny wpływ na końcowy efekt całego dzieła.",
        ua: "Обрана художня техніка мала величезний вплив на кінцевий результат усього твору.",
        ru: "Выбранная художественная техника оказала огромное влияние на конечный результат всего произведения.",
        en: "The chosen art technique had a huge impact on the final effect of the whole work.",
        uaTokens: ["Обрана", "художня", "техніка", "мала", "величезний", "вплив", "на", "кінцевий", "результат", "усього", "твору", "."],
        ruTokens: ["Выбранная", "художественная", "техника", "оказала", "огромное", "влияние", "на", "конечный", "результат", "всего", "произведения", "."],
        enTokens: ["The", "chosen", "art", "technique", "had", "a", "huge", "impact", "on", "the", "final", "effect", "of", "the", "whole", "work", "."],
        extraUaTokens: ["картина", "стиль", "критика"],
        extraRuTokens: ["картина", "стиль", "критика"],
        extraEnTokens: ["painting", "style", "criticism"],
    },

    [phraseKey("krytyka", "b2-41")]: {
        sk: "Krytyka była surowa, ale zawierała wiele trafnych uwag, które pomogły mu się rozwinąć.",
        ua: "Критика була суворою, але містила багато влучних зауважень, які допомогли йому розвиватися.",
        ru: "Критика была жёсткой, но содержала много точных замечаний, которые помогли ему развиваться.",
        en: "The criticism was harsh, but it contained many accurate remarks that helped him improve.",
        uaTokens: ["Критика", "була", "суворою", ",", "але", "містила", "багато", "влучних", "зауважень", ",", "які", "допомогли", "йому", "розвиватися", "."],
        ruTokens: ["Критика", "была", "жёсткой", ",", "но", "содержала", "много", "точных", "замечаний", ",", "которые", "помогли", "ему", "развиваться", "."],
        enTokens: ["The", "criticism", "was", "harsh", ",", "but", "it", "contained", "many", "accurate", "remarks", "that", "helped", "him", "improve", "."],
        extraUaTokens: ["мистецтва", "техніка", "портрет"],
        extraRuTokens: ["искусства", "техника", "портрет"],
        extraEnTokens: ["art", "technique", "portrait"],
    },

    // =========================
    // LESSON 42 — Архітектура
    // =========================
    [phraseKey("architektura", "b2-42")]: {
        sk: "Nowoczesna architektura coraz częściej łączy funkcjonalność, ekologię i odważne rozwiązania estetyczne.",
        ua: "Сучасна архітектура дедалі частіше поєднує функціональність, екологічність і сміливі естетичні рішення.",
        ru: "Современная архитектура всё чаще сочетает функциональность, экологичность и смелые эстетические решения.",
        en: "Modern architecture increasingly combines functionality, sustainability, and bold aesthetic solutions.",
        uaTokens: ["Сучасна", "архітектура", "дедалі", "частіше", "поєднує", "функціональність", ",", "екологічність", "і", "сміливі", "естетичні", "рішення", "."],
        ruTokens: ["Современная", "архитектура", "всё", "чаще", "сочетает", "функциональность", ",", "экологичность", "и", "смелые", "эстетические", "решения", "."],
        enTokens: ["Modern", "architecture", "increasingly", "combines", "functionality", ",", "sustainability", ",", "and", "bold", "aesthetic", "solutions", "."],
        extraUaTokens: ["фасад", "будівлю", "вежі"],
        extraRuTokens: ["фасад", "здание", "башни"],
        extraEnTokens: ["facade", "building", "tower"],
    },

    [phraseKey("budowa", "b2-42")]: {
        sk: "Budowa tego obiektu trwała dłużej niż planowano z powodu problemów technicznych i finansowych.",
        ua: "Будівництво цього об’єкта тривало довше, ніж планувалося, через технічні та фінансові проблеми.",
        ru: "Строительство этого объекта длилось дольше, чем планировалось, из-за технических и финансовых проблем.",
        en: "The construction of this building lasted longer than planned due to technical and financial problems.",
        uaTokens: ["Будівництво", "цього", "об’єкта", "тривало", "довше", ",", "ніж", "планувалося", ",", "через", "технічні", "та", "фінансові", "проблеми", "."],
        ruTokens: ["Строительство", "этого", "объекта", "длилось", "дольше", ",", "чем", "планировалось", ",", "из-за", "технических", "и", "финансовых", "проблем", "."],
        enTokens: ["The", "construction", "of", "this", "building", "lasted", "longer", "than", "planned", "due", "to", "technical", "and", "financial", "problems", "."],
        extraUaTokens: ["архітектору", "проєкт", "фасад"],
        extraRuTokens: ["архитектору", "проект", "фасад"],
        extraEnTokens: ["architect", "project", "facade"],
    },

    [phraseKey("wieżowiec", "b2-42")]: {
        sk: "Nowy wieżowiec zmienił panoramę miasta i stał się jednym z jego najbardziej rozpoznawalnych punktów.",
        ua: "Новий хмарочос змінив панораму міста і став однією з його найупізнаваніших точок.",
        ru: "Новый небоскрёб изменил панораму города и стал одной из его самых узнаваемых точек.",
        en: "The new skyscraper changed the city's skyline and became one of its most recognizable landmarks.",
        uaTokens: ["Новий", "хмарочос", "змінив", "панораму", "міста", "і", "став", "однією", "з", "його", "найупізнаваніших", "точок", "."],
        ruTokens: ["Новый", "небоскрёб", "изменил", "панораму", "города", "и", "стал", "одной", "из", "его", "самых", "узнаваемых", "точек", "."],
        enTokens: ["The", "new", "skyscraper", "changed", "the", "city's", "skyline", "and", "became", "one", "of", "its", "most", "recognizable", "landmarks", "."],
        extraUaTokens: ["архітектура", "вежі", "проєкт"],
        extraRuTokens: ["архитектура", "башни", "проект"],
        extraEnTokens: ["architecture", "tower", "project"],
    },

    [phraseKey("most", "b2-42")]: {
        sk: "Ten most nie tylko łączy dwa brzegi rzeki, ale również jest ważnym symbolem miasta.",
        ua: "Цей міст не лише з’єднує два береги річки, а й є важливим символом міста.",
        ru: "Этот мост не только соединяет два берега реки, но и является важным символом города.",
        en: "This bridge not only connects the two banks of the river, but is also an important symbol of the city.",
        uaTokens: ["Цей", "міст", "не", "лише", "з’єднує", "два", "береги", "річки", ",", "а", "й", "є", "важливим", "символом", "міста", "."],
        ruTokens: ["Этот", "мост", "не", "только", "соединяет", "два", "берега", "реки", ",", "но", "и", "является", "важным", "символом", "города", "."],
        enTokens: ["This", "bridge", "not", "only", "connects", "the", "two", "banks", "of", "the", "river", ",", "but", "is", "also", "an", "important", "symbol", "of", "the", "city", "."],
        extraUaTokens: ["будівлю", "вежі", "фасад"],
        extraRuTokens: ["здание", "башни", "фасад"],
        extraEnTokens: ["building", "tower", "facade"],
    },

    [phraseKey("historyczny budynek", "b2-42")]: {
        sk: "Ten historyczny budynek został starannie odrestaurowany, aby zachować jego pierwotny charakter.",
        ua: "Цю історичну будівлю ретельно відреставрували, щоб зберегти її первісний характер.",
        ru: "Это историческое здание было тщательно отреставрировано, чтобы сохранить его первоначальный характер.",
        en: "This historic building was carefully restored to preserve its original character.",
        uaTokens: ["Цю", "історичну", "будівлю", "ретельно", "відреставрували", ",", "щоб", "зберегти", "її", "первісний", "характер", "."],
        ruTokens: ["Это", "историческое", "здание", "было", "тщательно", "отреставрировано", ",", "чтобы", "сохранить", "его", "первоначальный", "характер", "."],
        enTokens: ["This", "historic", "building", "was", "carefully", "restored", "to", "preserve", "its", "original", "character", "."],
        extraUaTokens: ["фасад", "архітектору", "проєкт"],
        extraRuTokens: ["фасад", "архитектору", "проект"],
        extraEnTokens: ["facade", "architect", "project"],
    },

    [phraseKey("nowoczesna architektura", "b2-42")]: {
        sk: "Nowoczesna architektura często wykorzystuje szkło, stal i proste linie, aby podkreślić przestrzeń.",
        ua: "Сучасна архітектура часто використовує скло, сталь і прості лінії, щоб підкреслити простір.",
        ru: "Современная архитектура часто использует стекло, сталь и простые линии, чтобы подчеркнуть пространство.",
        en: "Modern architecture often uses glass, steel, and simple lines to emphasize space.",
        uaTokens: ["Сучасна", "архітектура", "часто", "використовує", "скло", ",", "сталь", "і", "прості", "лінії", ",", "щоб", "підкреслити", "простір", "."],
        ruTokens: ["Современная", "архитектура", "часто", "использует", "стекло", ",", "сталь", "и", "простые", "линии", ",", "чтобы", "подчеркнуть", "пространство", "."],
        enTokens: ["Modern", "architecture", "often", "uses", "glass", ",", "steel", ",", "and", "simple", "lines", "to", "emphasize", "space", "."],
        extraUaTokens: ["фасад", "будівництво", "вежі"],
        extraRuTokens: ["фасад", "строительство", "башни"],
        extraEnTokens: ["facade", "construction", "tower"],
    },

    [phraseKey("fasada", "b2-42")]: {
        sk: "Fasada budynku została zaprojektowana tak, aby harmonijnie współgrała z otoczeniem.",
        ua: "Фасад будівлі було спроєктовано так, щоб він гармонійно поєднувався з оточенням.",
        ru: "Фасад здания был спроектирован так, чтобы гармонично сочетаться с окружением.",
        en: "The facade of the building was designed to harmonize with its surroundings.",
        uaTokens: ["Фасад", "будівлі", "було", "спроєктовано", "так", ",", "щоб", "він", "гармонійно", "поєднувався", "з", "оточенням", "."],
        ruTokens: ["Фасад", "здания", "был", "спроектирован", "так", ",", "чтобы", "гармонично", "сочетаться", "с", "окружением", "."],
        enTokens: ["The", "facade", "of", "the", "building", "was", "designed", "to", "harmonize", "with", "its", "surroundings", "."],
        extraUaTokens: ["архітектура", "будівлю", "міст"],
        extraRuTokens: ["архитектура", "здание", "мост"],
        extraEnTokens: ["architecture", "building", "bridge"],
    },

    [phraseKey("wieża", "b2-42")]: {
        sk: "Ze szczytu wieży rozciągał się widok, który przyciągał turystów przez cały rok.",
        ua: "З вершини вежі відкривався краєвид, який приваблював туристів упродовж усього року.",
        ru: "С вершины башни открывался вид, который привлекал туристов круглый год.",
        en: "From the top of the tower, there was a view that attracted tourists all year round.",
        uaTokens: ["З", "вершини", "вежі", "відкривався", "краєвид", ",", "який", "приваблював", "туристів", "упродовж", "усього", "року", "."],
        ruTokens: ["С", "вершины", "башни", "открывался", "вид", ",", "который", "привлекал", "туристов", "круглый", "год", "."],
        enTokens: ["From", "the", "top", "of", "the", "tower", ",", "there", "was", "a", "view", "that", "attracted", "tourists", "all", "year", "round", "."],
        extraUaTokens: ["будівлі", "міст", "архітектору"],
        extraRuTokens: ["здания", "мост", "архитектору"],
        extraEnTokens: ["building", "bridge", "architect"],
    },

    [phraseKey("projekt", "b2-42")]: {
        sk: "Projekt został wielokrotnie zmieniony, zanim inwestor zaakceptował jego ostateczną wersję.",
        ua: "Проєкт багато разів змінювали, перш ніж інвестор схвалив його остаточну версію.",
        ru: "Проект многократно изменяли, прежде чем инвестор утвердил его окончательную версию.",
        en: "The project was revised many times before the investor approved its final version.",
        uaTokens: ["Проєкт", "багато", "разів", "змінювали", ",", "перш", "ніж", "інвестор", "схвалив", "його", "остаточну", "версію", "."],
        ruTokens: ["Проект", "многократно", "изменяли", ",", "прежде", "чем", "инвестор", "утвердил", "его", "окончательную", "версию", "."],
        enTokens: ["The", "project", "was", "revised", "many", "times", "before", "the", "investor", "approved", "its", "final", "version", "."],
        extraUaTokens: ["архітектору", "фасад", "будівництво"],
        extraRuTokens: ["архитектору", "фасад", "строительство"],
        extraEnTokens: ["architect", "facade", "construction"],
    },

    [phraseKey("architekt", "b2-42")]: {
        sk: "Architekt musiał połączyć oczekiwania klienta z ograniczeniami technicznymi i budżetowymi.",
        ua: "Архітектору довелося поєднати очікування клієнта з технічними та бюджетними обмеженнями.",
        ru: "Архитектору пришлось совместить ожидания клиента с техническими и бюджетными ограничениями.",
        en: "The architect had to combine the client's expectations with technical and budget constraints.",
        uaTokens: ["Архітектору", "довелося", "поєднати", "очікування", "клієнта", "з", "технічними", "та", "бюджетними", "обмеженнями", "."],
        ruTokens: ["Архитектору", "пришлось", "совместить", "ожидания", "клиента", "с", "техническими", "и", "бюджетными", "ограничениями", "."],
        enTokens: ["The", "architect", "had", "to", "combine", "the", "client's", "expectations", "with", "technical", "and", "budget", "constraints", "."],
        extraUaTokens: ["проєкт", "будівництво", "вежі"],
        extraRuTokens: ["проект", "строительство", "башни"],
        extraEnTokens: ["project", "construction", "tower"],
    },

    // =========================
    // LESSON 43 — Атмосферні явища
    // =========================
    [phraseKey("zachmurzenie", "b2-43")]: {
        sk: "Duże zachmurzenie utrzymywało się przez cały dzień, przez co temperatura była niższa niż zwykle.",
        ua: "Велика хмарність трималася весь день, через що температура була нижчою, ніж зазвичай.",
        ru: "Сильная облачность держалась весь день, из-за чего температура была ниже обычной.",
        en: "Heavy cloudiness lasted all day, which made the temperature lower than usual.",
        uaTokens: ["Велика", "хмарність", "трималася", "весь", "день", ",", "через", "що", "температура", "була", "нижчою", ",", "ніж", "зазвичай", "."],
        ruTokens: ["Сильная", "облачность", "держалась", "весь", "день", ",", "из-за", "чего", "температура", "была", "ниже", "обычной", "."],
        enTokens: ["Heavy", "cloudiness", "lasted", "all", "day", ",", "which", "made", "the", "temperature", "lower", "than", "usual", "."],
        extraUaTokens: ["тиску", "дощ", "погода"],
        extraRuTokens: ["давления", "дождь", "погода"],
        extraEnTokens: ["pressure", "rain", "weather"],
    },

    [phraseKey("ciśnienie powietrza", "b2-43")]: {
        sk: "Nagły spadek ciśnienia powietrza często zapowiada pogorszenie warunków pogodowych.",
        ua: "Раптове падіння атмосферного тиску часто передвіщає погіршення погодних умов.",
        ru: "Резкое падение атмосферного давления часто предвещает ухудшение погодных условий.",
        en: "A sudden drop in air pressure often signals worsening weather conditions.",
        uaTokens: ["Раптове", "падіння", "атмосферного", "тиску", "часто", "передвіщає", "погіршення", "погодних", "умов", "."],
        ruTokens: ["Резкое", "падение", "атмосферного", "давления", "часто", "предвещает", "ухудшение", "погодных", "условий", "."],
        enTokens: ["A", "sudden", "drop", "in", "air", "pressure", "often", "signals", "worsening", "weather", "conditions", "."],
        extraUaTokens: ["хмарність", "мряка", "потепління"],
        extraRuTokens: ["облачность", "морось", "потепление"],
        extraEnTokens: ["cloudiness", "drizzle", "warming"],
    },

    [phraseKey("nagłe ocieplenie", "b2-43")]: {
        sk: "Nagłe ocieplenie sprawiło, że śnieg zaczął topnieć znacznie szybciej niż przewidywano.",
        ua: "Раптове потепління призвело до того, що сніг почав танути значно швидше, ніж очікували.",
        ru: "Резкое потепление привело к тому, что снег начал таять намного быстрее, чем ожидалось.",
        en: "A sudden warming caused the snow to melt much faster than expected.",
        uaTokens: ["Раптове", "потепління", "призвело", "до", "того", ",", "що", "сніг", "почав", "танути", "значно", "швидше", ",", "ніж", "очікували", "."],
        ruTokens: ["Резкое", "потепление", "привело", "к", "тому", ",", "что", "снег", "начал", "таять", "намного", "быстрее", ",", "чем", "ожидалось", "."],
        enTokens: ["A", "sudden", "warming", "caused", "the", "snow", "to", "melt", "much", "faster", "than", "expected", "."],
        extraUaTokens: ["покрив", "льоду", "дощ"],
        extraRuTokens: ["покров", "льда", "дождь"],
        extraEnTokens: ["cover", "ice", "rain"],
    },

    [phraseKey("ocieplenie", "b2-43")]: {
        sk: "Ocieplenie klimatu ma wpływ nie tylko na pogodę, ale także na rolnictwo i gospodarkę wodną.",
        ua: "Потепління клімату впливає не лише на погоду, а й на сільське господарство та водні ресурси.",
        ru: "Потепление климата влияет не только на погоду, но и на сельское хозяйство и водные ресурсы.",
        en: "Climate warming affects not only the weather but also agriculture and water resources.",
        uaTokens: ["Потепління", "клімату", "впливає", "не", "лише", "на", "погоду", ",", "а", "й", "на", "сільське", "господарство", "та", "водні", "ресурси", "."],
        ruTokens: ["Потепление", "климата", "влияет", "не", "только", "на", "погоду", ",", "но", "и", "на", "сельское", "хозяйство", "и", "водные", "ресурсы", "."],
        enTokens: ["Climate", "warming", "affects", "not", "only", "the", "weather", "but", "also", "agriculture", "and", "water", "resources", "."],
        extraUaTokens: ["тиску", "мряка", "інфраструктуру"],
        extraRuTokens: ["давления", "морось", "инфраструктуру"],
        extraEnTokens: ["pressure", "drizzle", "infrastructure"],
    },

    [phraseKey("mżawka", "b2-43")]: {
        sk: "Choć to była tylko mżawka, wilgoć przenikała ubranie i szybko powodowała dyskomfort.",
        ua: "Хоч це була лише мряка, волога проникала крізь одяг і швидко спричиняла дискомфорт.",
        ru: "Хотя это была всего лишь морось, влага проникала через одежду и быстро вызывала дискомфорт.",
        en: "Although it was only drizzle, the moisture soaked through clothes and quickly caused discomfort.",
        uaTokens: ["Хоч", "це", "була", "лише", "мряка", ",", "волога", "проникала", "крізь", "одяг", "і", "швидко", "спричиняла", "дискомфорт", "."],
        ruTokens: ["Хотя", "это", "была", "всего", "лишь", "морось", ",", "влага", "проникала", "через", "одежду", "и", "быстро", "вызывала", "дискомфорт", "."],
        enTokens: ["Although", "it", "was", "only", "drizzle", ",", "the", "moisture", "soaked", "through", "clothes", "and", "quickly", "caused", "discomfort", "."],
        extraUaTokens: ["хмарність", "злива", "льоду"],
        extraRuTokens: ["облачность", "ливень", "льда"],
        extraEnTokens: ["cloudiness", "rain", "ice"],
    },

    [phraseKey("ulewny deszcz", "b2-43")]: {
        sk: "Ulewny deszcz sparaliżował ruch w mieście i doprowadził do lokalnych podtopień.",
        ua: "Злива паралізувала рух у місті та призвела до локальних підтоплень.",
        ru: "Ливень парализовал движение в городе и привёл к локальным подтоплениям.",
        en: "Torrential rain paralyzed traffic in the city and caused local flooding.",
        uaTokens: ["Злива", "паралізувала", "рух", "у", "місті", "та", "призвела", "до", "локальних", "підтоплень", "."],
        ruTokens: ["Ливень", "парализовал", "движение", "в", "городе", "и", "привёл", "к", "локальным", "подтоплениям", "."],
        enTokens: ["Torrential", "rain", "paralyzed", "traffic", "in", "the", "city", "and", "caused", "local", "flooding", "."],
        extraUaTokens: ["мряка", "погода", "інфраструктуру"],
        extraRuTokens: ["морось", "погода", "инфраструктуру"],
        extraEnTokens: ["drizzle", "weather", "infrastructure"],
    },

    [phraseKey("warstwa lodu", "b2-43")]: {
        sk: "Na drogach utworzyła się cienka warstwa lodu, która była niemal niewidoczna dla kierowców.",
        ua: "На дорогах утворився тонкий шар льоду, який був майже непомітний для водіїв.",
        ru: "На дорогах образовался тонкий слой льда, который был почти незаметен для водителей.",
        en: "A thin layer of ice formed on the roads, almost invisible to drivers.",
        uaTokens: ["На", "дорогах", "утворився", "тонкий", "шар", "льоду", ",", "який", "був", "майже", "непомітний", "для", "водіїв", "."],
        ruTokens: ["На", "дорогах", "образовался", "тонкий", "слой", "льда", ",", "который", "был", "почти", "незаметен", "для", "водителей", "."],
        enTokens: ["A", "thin", "layer", "of", "ice", "formed", "on", "the", "roads", ",", "almost", "invisible", "to", "drivers", "."],
        extraUaTokens: ["сніг", "злива", "похолодання"],
        extraRuTokens: ["снег", "ливень", "похолодание"],
        extraEnTokens: ["snow", "rain", "cooling"],
    },

    [phraseKey("pokrywa śnieżna", "b2-43")]: {
        sk: "Pokrywa śnieżna była tak gruba, że wiele dróg pozostawało nieprzejezdnych przez kilka dni.",
        ua: "Сніговий покрив був настільки товстим, що багато доріг залишалися непроїзними кілька днів.",
        ru: "Снежный покров был настолько толстым, что многие дороги оставались непроходимыми несколько дней.",
        en: "The snow cover was so thick that many roads remained impassable for several days.",
        uaTokens: ["Сніговий", "покрив", "був", "настільки", "товстим", ",", "що", "багато", "доріг", "залишалися", "непроїзними", "кілька", "днів", "."],
        ruTokens: ["Снежный", "покров", "был", "настолько", "толстым", ",", "что", "многие", "дороги", "оставались", "непроходимыми", "несколько", "дней", "."],
        enTokens: ["The", "snow", "cover", "was", "so", "thick", "that", "many", "roads", "remained", "impassable", "for", "several", "days", "."],
        extraUaTokens: ["льоду", "потепління", "температура"],
        extraRuTokens: ["льда", "потепление", "температура"],
        extraEnTokens: ["ice", "warming", "temperature"],
    },

    [phraseKey("ekstremalna pogoda", "b2-43")]: {
        sk: "Ekstremalna pogoda staje się coraz częstsza, dlatego miasta muszą lepiej przygotować infrastrukturę.",
        ua: "Екстремальна погода стає дедалі частішою, тому міста мають краще готувати інфраструктуру.",
        ru: "Экстремальная погода становится всё более частой, поэтому города должны лучше готовить инфраструктуру.",
        en: "Extreme weather is becoming more frequent, so cities must prepare their infrastructure better.",
        uaTokens: ["Екстремальна", "погода", "стає", "дедалі", "частішою", ",", "тому", "міста", "мають", "краще", "готувати", "інфраструктуру", "."],
        ruTokens: ["Экстремальная", "погода", "становится", "всё", "более", "частой", ",", "поэтому", "города", "должны", "лучше", "готовить", "инфраструктуру", "."],
        enTokens: ["Extreme", "weather", "is", "becoming", "more", "frequent", ",", "so", "cities", "must", "prepare", "their", "infrastructure", "better", "."],
        extraUaTokens: ["злива", "тиску", "потепління"],
        extraRuTokens: ["ливень", "давления", "потепление"],
        extraEnTokens: ["rain", "pressure", "warming"],
    },

    [phraseKey("gwałtowne ochłodzenie", "b2-43")]: {
        sk: "Gwałtowne ochłodzenie nastąpiło w nocy i całkowicie zaskoczyło mieszkańców regionu.",
        ua: "Різке похолодання настало вночі й повністю застало зненацька мешканців регіону.",
        ru: "Резкое похолодание наступило ночью и полностью застало жителей региона врасплох.",
        en: "A sharp cooling came during the night and completely caught the region's residents by surprise.",
        uaTokens: ["Різке", "похолодання", "настало", "вночі", "й", "повністю", "застало", "зненацька", "мешканців", "регіону", "."],
        ruTokens: ["Резкое", "похолодание", "наступило", "ночью", "и", "полностью", "застало", "жителей", "региона", "врасплох", "."],
        enTokens: ["A", "sharp", "cooling", "came", "during", "the", "night", "and", "completely", "caught", "the", "region's", "residents", "by", "surprise", "."],
        extraUaTokens: ["хмарність", "льоду", "сніг"],
        extraRuTokens: ["облачность", "льда", "снег"],
        extraEnTokens: ["cloudiness", "ice", "snow"],
    },

    // =========================
    // LESSON 44 — Право
    // =========================
    [phraseKey("ustawodawstwo", "b2-44")]: {
        sk: "Ustawodawstwo musi nadążać za zmianami społecznymi, technologicznymi i gospodarczymi.",
        ua: "Законодавство має встигати за соціальними, технологічними та економічними змінами.",
        ru: "Законодательство должно успевать за социальными, технологическими и экономическими изменениями.",
        en: "Legislation must keep pace with social, technological, and economic changes.",
        uaTokens: ["Законодавство", "має", "встигати", "за", "соціальними", ",", "технологічними", "та", "економічними", "змінами", "."],
        ruTokens: ["Законодательство", "должно", "успевать", "за", "социальными", ",", "технологическими", "и", "экономическими", "изменениями", "."],
        enTokens: ["Legislation", "must", "keep", "pace", "with", "social", ",", "technological", ",", "and", "economic", "changes", "."],
        extraUaTokens: ["суду", "вирок", "штраф"],
        extraRuTokens: ["суда", "приговор", "штраф"],
        extraEnTokens: ["court", "judgment", "fine"],
    },

    [phraseKey("przestępstwo", "b2-44")]: {
        sk: "To przestępstwo zostało starannie zaplanowane, dlatego śledztwo trwało znacznie dłużej niż zwykle.",
        ua: "Цей кримінальний злочин був ретельно спланований, тому розслідування тривало значно довше, ніж зазвичай.",
        ru: "Это уголовное преступление было тщательно спланировано, поэтому расследование длилось значительно дольше обычного.",
        en: "This criminal offense was carefully planned, so the investigation lasted much longer than usual.",
        uaTokens: ["Цей", "кримінальний", "злочин", "був", "ретельно", "спланований", ",", "тому", "розслідування", "тривало", "значно", "довше", ",", "ніж", "зазвичай", "."],
        ruTokens: ["Это", "уголовное", "преступление", "было", "тщательно", "спланировано", ",", "поэтому", "расследование", "длилось", "значительно", "дольше", "обычного", "."],
        enTokens: ["This", "criminal", "offense", "was", "carefully", "planned", ",", "so", "the", "investigation", "lasted", "much", "longer", "than", "usual", "."],
        extraUaTokens: ["слідчий", "суду", "свідків"],
        extraRuTokens: ["следователь", "суда", "свидетелей"],
        extraEnTokens: ["investigator", "court", "witnesses"],
    },

    [phraseKey("śledczy", "b2-44")]: {
        sk: "Śledczy zebrał wystarczająco dużo dowodów, aby skierować sprawę do sądu.",
        ua: "Слідчий зібрав достатньо доказів, щоб передати справу до суду.",
        ru: "Следователь собрал достаточно доказательств, чтобы передать дело в суд.",
        en: "The investigator gathered enough evidence to bring the case to court.",
        uaTokens: ["Слідчий", "зібрав", "достатньо", "доказів", ",", "щоб", "передати", "справу", "до", "суду", "."],
        ruTokens: ["Следователь", "собрал", "достаточно", "доказательств", ",", "чтобы", "передать", "дело", "в", "суд", "."],
        enTokens: ["The", "investigator", "gathered", "enough", "evidence", "to", "bring", "the", "case", "to", "court", "."],
        extraUaTokens: ["злочин", "вирок", "штраф"],
        extraRuTokens: ["преступление", "приговор", "штраф"],
        extraEnTokens: ["crime", "judgment", "fine"],
    },

    [phraseKey("sąd", "b2-44")]: {
        sk: "Sąd odroczył rozprawę, ponieważ obrona poprosiła o dodatkowy czas na przygotowanie.",
        ua: "Суд відклав засідання, оскільки захист попросив додатковий час на підготовку.",
        ru: "Суд отложил заседание, потому что защита попросила дополнительное время на подготовку.",
        en: "The court postponed the hearing because the defense asked for additional time to prepare.",
        uaTokens: ["Суд", "відклав", "засідання", ",", "оскільки", "захист", "попросив", "додатковий", "час", "на", "підготовку", "."],
        ruTokens: ["Суд", "отложил", "заседание", ",", "потому", "что", "защита", "попросила", "дополнительное", "время", "на", "подготовку", "."],
        enTokens: ["The", "court", "postponed", "the", "hearing", "because", "the", "defense", "asked", "for", "additional", "time", "to", "prepare", "."],
        extraUaTokens: ["слідчий", "свідок", "мандат"],
        extraRuTokens: ["следователь", "свидетель", "штраф"],
        extraEnTokens: ["investigator", "witness", "fine"],
    },

    [phraseKey("wyrok", "b2-44")]: {
        sk: "Wyrok został ogłoszony po wielogodzinnej naradzie i wywołał mieszane reakcje opinii publicznej.",
        ua: "Вирок було оголошено після багатогодинної наради, і він викликав змішані реакції громадськості.",
        ru: "Приговор был оглашён после многочасового совещания и вызвал смешанную реакцию общественности.",
        en: "The judgment was announced after hours of deliberation and provoked mixed public reactions.",
        uaTokens: ["Вирок", "було", "оголошено", "після", "багатогодинної", "наради", ",", "і", "він", "викликав", "змішані", "реакції", "громадськості", "."],
        ruTokens: ["Приговор", "был", "оглашён", "после", "многочасового", "совещания", "и", "вызвал", "смешанную", "реакцию", "общественности", "."],
        enTokens: ["The", "judgment", "was", "announced", "after", "hours", "of", "deliberation", "and", "provoked", "mixed", "public", "reactions", "."],
        extraUaTokens: ["суду", "обвинувачення", "свідок"],
        extraRuTokens: ["суда", "обвинение", "свидетель"],
        extraEnTokens: ["court", "accusation", "witness"],
    },

    [phraseKey("oskarżenie", "b2-44")]: {
        sk: "Oskarżenie opierało się na dokumentach, zeznaniach świadków i wynikach ekspertyzy.",
        ua: "Обвинувачення ґрунтувалося на документах, свідченнях свідків і результатах експертизи.",
        ru: "Обвинение основывалось на документах, показаниях свидетелей и результатах экспертизы.",
        en: "The accusation was based on documents, witness testimony, and expert findings.",
        uaTokens: ["Обвинувачення", "ґрунтувалося", "на", "документах", ",", "свідченнях", "свідків", "і", "результатах", "експертизи", "."],
        ruTokens: ["Обвинение", "основывалось", "на", "документах", ",", "показаниях", "свидетелей", "и", "результатах", "экспертизы", "."],
        enTokens: ["The", "accusation", "was", "based", "on", "documents", ",", "witness", "testimony", ",", "and", "expert", "findings", "."],
        extraUaTokens: ["вирок", "суду", "штраф"],
        extraRuTokens: ["приговор", "суда", "штраф"],
        extraEnTokens: ["judgment", "court", "fine"],
    },

    [phraseKey("świadek", "b2-44")]: {
        sk: "Świadek zmienił swoje zeznania, co skomplikowało przebieg całego postępowania.",
        ua: "Свідок змінив свої показання, що ускладнило хід усього провадження.",
        ru: "Свидетель изменил свои показания, что усложнило ход всего разбирательства.",
        en: "The witness changed their testimony, which complicated the entire proceedings.",
        uaTokens: ["Свідок", "змінив", "свої", "показання", ",", "що", "ускладнило", "хід", "усього", "провадження", "."],
        ruTokens: ["Свидетель", "изменил", "свои", "показания", ",", "что", "усложнило", "ход", "всего", "разбирательства", "."],
        enTokens: ["The", "witness", "changed", "their", "testimony", ",", "which", "complicated", "the", "entire", "proceedings", "."],
        extraUaTokens: ["обвинувачення", "суду", "злочин"],
        extraRuTokens: ["обвинение", "суда", "преступление"],
        extraEnTokens: ["accusation", "court", "crime"],
    },

    [phraseKey("czyn karalny", "b2-44")]: {
        sk: "Każdy czyn karalny powinien zostać dokładnie zbadany, zanim sprawa trafi do sądu.",
        ua: "Кожен кримінальний злочин має бути ретельно розслідуваний, перш ніж справа потрапить до суду.",
        ru: "Каждое уголовное преступление должно быть тщательно расследовано, прежде чем дело попадёт в суд.",
        en: "Every criminal offense should be thoroughly investigated before the case goes to court.",
        uaTokens: ["Кожен", "кримінальний", "злочин", "має", "бути", "ретельно", "розслідуваний", ",", "перш", "ніж", "справа", "потрапить", "до", "суду", "."],
        ruTokens: ["Каждое", "уголовное", "преступление", "должно", "быть", "тщательно", "расследовано", ",", "прежде", "чем", "дело", "попадёт", "в", "суд", "."],
        enTokens: ["Every", "criminal", "offense", "should", "be", "thoroughly", "investigated", "before", "the", "case", "goes", "to", "court", "."],
        extraUaTokens: ["слідчий", "свідок", "вирок"],
        extraRuTokens: ["следователь", "свидетель", "приговор"],
        extraEnTokens: ["investigator", "witness", "judgment"],
    },

    [phraseKey("mandat", "b2-44")]: {
        sk: "Otrzymał mandat za przekroczenie prędkości, choć twierdził, że znak był słabo widoczny.",
        ua: "Він отримав штраф за перевищення швидкості, хоча стверджував, що знак було погано видно.",
        ru: "Он получил штраф за превышение скорости, хотя утверждал, что знак был плохо виден.",
        en: "He received a fine for speeding, although he claimed the sign was hard to see.",
        uaTokens: ["Він", "отримав", "штраф", "за", "перевищення", "швидкості", ",", "хоча", "стверджував", ",", "що", "знак", "було", "погано", "видно", "."],
        ruTokens: ["Он", "получил", "штраф", "за", "превышение", "скорости", ",", "хотя", "утверждал", ",", "что", "знак", "был", "плохо", "виден", "."],
        enTokens: ["He", "received", "a", "fine", "for", "speeding", ",", "although", "he", "claimed", "the", "sign", "was", "hard", "to", "see", "."],
        extraUaTokens: ["суду", "підозрюваного", "законодавство"],
        extraRuTokens: ["суда", "подозреваемого", "законодательство"],
        extraEnTokens: ["court", "suspect", "legislation"],
    },

    [phraseKey("zatrzymać", "b2-44")]: {
        sk: "Policja musiała zatrzymać podejrzanego natychmiast, aby zapobiec jego ucieczce za granicę.",
        ua: "Поліція мусила негайно затримати підозрюваного, щоб запобігти його втечі за кордон.",
        ru: "Полиция должна была немедленно задержать подозреваемого, чтобы предотвратить его побег за границу.",
        en: "The police had to detain the suspect immediately to prevent him from fleeing abroad.",
        uaTokens: ["Поліція", "мусила", "негайно", "затримати", "підозрюваного", ",", "щоб", "запобігти", "його", "втечі", "за", "кордон", "."],
        ruTokens: ["Полиция", "должна", "была", "немедленно", "задержать", "подозреваемого", ",", "чтобы", "предотвратить", "его", "побег", "за", "границу", "."],
        enTokens: ["The", "police", "had", "to", "detain", "the", "suspect", "immediately", "to", "prevent", "him", "from", "fleeing", "abroad", "."],
        extraUaTokens: ["штраф", "суду", "свідок"],
        extraRuTokens: ["штраф", "суда", "свидетель"],
        extraEnTokens: ["fine", "court", "witness"],
    },

    // =========================
    // LESSON 45 — Навігація
    // =========================
    [phraseKey("kompas", "b2-45")]: {
        sk: "Kompas okazał się niezbędny, gdy telefon stracił zasięg i przestał działać GPS.",
        ua: "Компас виявився незамінним, коли телефон втратив зв’язок і GPS перестав працювати.",
        ru: "Компас оказался незаменимым, когда телефон потерял связь и GPS перестал работать.",
        en: "The compass proved essential when the phone lost signal and the GPS stopped working.",
        uaTokens: ["Компас", "виявився", "незамінним", ",", "коли", "телефон", "втратив", "зв’язок", "і", "GPS", "перестав", "працювати", "."],
        ruTokens: ["Компас", "оказался", "незаменимым", ",", "когда", "телефон", "потерял", "связь", "и", "GPS", "перестал", "работать", "."],
        enTokens: ["The", "compass", "proved", "essential", "when", "the", "phone", "lost", "signal", "and", "the", "GPS", "stopped", "working", "."],
        extraUaTokens: ["карта", "маршрут", "північ"],
        extraRuTokens: ["карта", "маршрут", "север"],
        extraEnTokens: ["map", "route", "north"],
    },

    [phraseKey("mapa", "b2-45")]: {
        sk: "Papierowa mapa była bardziej przydatna niż aplikacja, ponieważ nie wymagała dostępu do internetu.",
        ua: "Паперова карта була кориснішою за застосунок, оскільки не потребувала доступу до інтернету.",
        ru: "Бумажная карта оказалась полезнее приложения, потому что не требовала доступа к интернету.",
        en: "The paper map was more useful than the app because it did not require internet access.",
        uaTokens: ["Паперова", "карта", "була", "кориснішою", "за", "застосунок", ",", "оскільки", "не", "потребувала", "доступу", "до", "інтернету", "."],
        ruTokens: ["Бумажная", "карта", "оказалась", "полезнее", "приложения", ",", "потому", "что", "не", "требовала", "доступа", "к", "интернету", "."],
        enTokens: ["The", "paper", "map", "was", "more", "useful", "than", "the", "app", "because", "it", "did", "not", "require", "internet", "access", "."],
        extraUaTokens: ["компас", "навігація", "захід"],
        extraRuTokens: ["компас", "навигация", "запад"],
        extraEnTokens: ["compass", "navigation", "west"],
    },

    [phraseKey("kierunek", "b2-45")]: {
        sk: "Musieliśmy zmienić kierunek marszu, ponieważ szlak został częściowo zamknięty po burzy.",
        ua: "Нам довелося змінити напрямок руху, оскільки стежку частково закрили після бурі.",
        ru: "Нам пришлось изменить направление движения, потому что тропу частично закрыли после шторма.",
        en: "We had to change direction because the trail was partially closed after the storm.",
        uaTokens: ["Нам", "довелося", "змінити", "напрямок", "руху", ",", "оскільки", "стежку", "частково", "закрили", "після", "бурі", "."],
        ruTokens: ["Нам", "пришлось", "изменить", "направление", "движения", ",", "потому", "что", "тропу", "частично", "закрыли", "после", "шторма", "."],
        enTokens: ["We", "had", "to", "change", "direction", "because", "the", "trail", "was", "partially", "closed", "after", "the", "storm", "."],
        extraUaTokens: ["карта", "компас", "схід"],
        extraRuTokens: ["карта", "компас", "восток"],
        extraEnTokens: ["map", "compass", "east"],
    },

    [phraseKey("północ", "b2-45")]: {
        sk: "Na północ od jeziora teren stawał się bardziej stromy i trudniejszy do przejścia.",
        ua: "На північ від озера місцевість ставала крутішою і важчою для проходу.",
        ru: "К северу от озера местность становилась более крутой и трудной для прохода.",
        en: "North of the lake, the terrain became steeper and harder to cross.",
        uaTokens: ["На", "північ", "від", "озера", "місцевість", "ставала", "крутішою", "і", "важчою", "для", "проходу", "."],
        ruTokens: ["К", "северу", "от", "озера", "местность", "становилась", "более", "крутой", "и", "трудной", "для", "прохода", "."],
        enTokens: ["North", "of", "the", "lake", ",", "the", "terrain", "became", "steeper", "and", "harder", "to", "cross", "."],
        extraUaTokens: ["південь", "схід", "захід"],
        extraRuTokens: ["юг", "восток", "запад"],
        extraEnTokens: ["south", "east", "west"],
    },

    [phraseKey("południe", "b2-45")]: {
        sk: "Na południe od miasta rozciągają się równiny, które latem szybko się nagrzewają.",
        ua: "На південь від міста простягаються рівнини, які влітку швидко нагріваються.",
        ru: "К югу от города простираются равнины, которые летом быстро нагреваются.",
        en: "South of the city there are plains that heat up quickly in summer.",
        uaTokens: ["На", "південь", "від", "міста", "простягаються", "рівнини", ",", "які", "влітку", "швидко", "нагріваються", "."],
        ruTokens: ["К", "югу", "от", "города", "простираются", "равнины", ",", "которые", "летом", "быстро", "нагреваются", "."],
        enTokens: ["South", "of", "the", "city", "there", "are", "plains", "that", "heat", "up", "quickly", "in", "summer", "."],
        extraUaTokens: ["північ", "схід", "карта"],
        extraRuTokens: ["север", "восток", "карта"],
        extraEnTokens: ["north", "east", "map"],
    },

    [phraseKey("wschód", "b2-45")]: {
        sk: "Wyruszyliśmy o świcie na wschód, licząc na to, że przed południem dotrzemy do celu.",
        ua: "Ми вирушили на світанку на схід, сподіваючись дістатися до мети до полудня.",
        ru: "Мы отправились на рассвете на восток, рассчитывая добраться до цели до полудня.",
        en: "We set off east at dawn, hoping to reach our destination before noon.",
        uaTokens: ["Ми", "вирушили", "на", "світанку", "на", "схід", ",", "сподіваючись", "дістатися", "до", "мети", "до", "полудня", "."],
        ruTokens: ["Мы", "отправились", "на", "рассвете", "на", "восток", ",", "рассчитывая", "добраться", "до", "цели", "до", "полудня", "."],
        enTokens: ["We", "set", "off", "east", "at", "dawn", ",", "hoping", "to", "reach", "our", "destination", "before", "noon", "."],
        extraUaTokens: ["захід", "компас", "маршрут"],
        extraRuTokens: ["запад", "компас", "маршрут"],
        extraEnTokens: ["west", "compass", "route"],
    },

    [phraseKey("zachód", "b2-45")]: {
        sk: "Po kilku godzinach marszu skręciliśmy na zachód, aby ominąć podmokły teren.",
        ua: "Після кількох годин ходи ми повернули на захід, щоб оминути заболочену місцевість.",
        ru: "После нескольких часов пути мы свернули на запад, чтобы обойти заболоченную местность.",
        en: "After several hours of walking, we turned west to avoid the marshy terrain.",
        uaTokens: ["Після", "кількох", "годин", "ходи", "ми", "повернули", "на", "захід", ",", "щоб", "оминути", "заболочену", "місцевість", "."],
        ruTokens: ["После", "нескольких", "часов", "пути", "мы", "свернули", "на", "запад", ",", "чтобы", "обойти", "заболоченную", "местность", "."],
        enTokens: ["After", "several", "hours", "of", "walking", ",", "we", "turned", "west", "to", "avoid", "the", "marshy", "terrain", "."],
        extraUaTokens: ["схід", "північ", "карта"],
        extraRuTokens: ["восток", "север", "карта"],
        extraEnTokens: ["east", "north", "map"],
    },

    [phraseKey("nawigacja", "b2-45")]: {
        sk: "Nowoczesna nawigacja bardzo ułatwia podróżowanie, ale nie zawsze można na niej całkowicie polegać.",
        ua: "Сучасна навігація дуже полегшує подорожі, але на неї не завжди можна повністю покладатися.",
        ru: "Современная навигация сильно облегчает путешествия, но на неё не всегда можно полностью полагаться.",
        en: "Modern navigation makes traveling much easier, but it cannot always be relied on completely.",
        uaTokens: ["Сучасна", "навігація", "дуже", "полегшує", "подорожі", ",", "але", "на", "неї", "не", "завжди", "можна", "повністю", "покладатися", "."],
        ruTokens: ["Современная", "навигация", "сильно", "облегчает", "путешествия", ",", "но", "на", "неё", "не", "всегда", "можно", "полностью", "полагаться", "."],
        enTokens: ["Modern", "navigation", "makes", "traveling", "much", "easier", ",", "but", "it", "cannot", "always", "be", "relied", "on", "completely", "."],
        extraUaTokens: ["компас", "карта", "маршрут"],
        extraRuTokens: ["компас", "карта", "маршрут"],
        extraEnTokens: ["compass", "map", "route"],
    },

    [phraseKey("określić położenie", "b2-45")]: {
        sk: "Bez widocznych punktów orientacyjnych trudno było dokładnie określić położenie całej grupy.",
        ua: "Без видимих орієнтирів було важко точно визначити місцезнаходження всієї групи.",
        ru: "Без видимых ориентиров было трудно точно определить местоположение всей группы.",
        en: "Without visible landmarks, it was difficult to determine the exact location of the whole group.",
        uaTokens: ["Без", "видимих", "орієнтирів", "було", "важко", "точно", "визначити", "місцезнаходження", "всієї", "групи", "."],
        ruTokens: ["Без", "видимых", "ориентиров", "было", "трудно", "точно", "определить", "местоположение", "всей", "группы", "."],
        enTokens: ["Without", "visible", "landmarks", ",", "it", "was", "difficult", "to", "determine", "the", "exact", "location", "of", "the", "whole", "group", "."],
        extraUaTokens: ["компас", "карта", "північ"],
        extraRuTokens: ["компас", "карта", "север"],
        extraEnTokens: ["compass", "map", "north"],
    },

    [phraseKey("trasa podróży", "b2-45")]: {
        sk: "Trasa podróży została zaplanowana tak, aby połączyć bezpieczeństwo, wygodę i ciekawe miejsca po drodze.",
        ua: "Маршрут подорожі був спланований так, щоб поєднати безпеку, зручність і цікаві місця дорогою.",
        ru: "Маршрут путешествия был спланирован так, чтобы сочетать безопасность, удобство и интересные места по пути.",
        en: "The travel route was planned to combine safety, comfort, and interesting places along the way.",
        uaTokens: ["Маршрут", "подорожі", "був", "спланований", "так", ",", "щоб", "поєднати", "безпеку", ",", "зручність", "і", "цікаві", "місця", "дорогою", "."],
        ruTokens: ["Маршрут", "путешествия", "был", "спланирован", "так", ",", "чтобы", "сочетать", "безопасность", ",", "удобство", "и", "интересные", "места", "по", "пути", "."],
        enTokens: ["The", "travel", "route", "was", "planned", "to", "combine", "safety", ",", "comfort", ",", "and", "interesting", "places", "along", "the", "way", "."],
        extraUaTokens: ["навігація", "карта", "схід"],
        extraRuTokens: ["навигация", "карта", "восток"],
        extraEnTokens: ["navigation", "map", "east"],
    },
};