import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_B1_BUILD_UA_SENTENCES_4: BuildUaSentenceDict = {
    // =========================
    // LESSON 16 — Культура та дозвілля
    // =========================
    [phraseKey("gust", "b1-16")]: {
        sk: "Każdy ma inny gust, dlatego nie wszystkim podoba się to samo.",
        ua: "У кожного інший смак, тому не всім подобається одне й те саме.",
        ru: "У каждого свой вкус, поэтому не всем нравится одно и то же.",
        en: "Everyone has different tastes, so not everyone likes the same thing.",
        uaTokens: ["У", "кожного", "інший", "смак", ",", "тому", "не", "всім", "подобається", "одне", "й", "те", "саме", "."],
        ruTokens: ["У", "каждого", "свой", "вкус", ",", "поэтому", "не", "всем", "нравится", "одно", "и", "то", "же", "."],
        enTokens: ["Everyone", "has", "different", "tastes", ",", "so", "not", "everyone", "likes", "the", "same", "thing", "."],
        extraUaTokens: ["фільм", "музей", "концерт"],
        extraRuTokens: ["фильм", "музей", "концерт"],
        extraEnTokens: ["film", "museum", "concert"],
    },

    [phraseKey("recenzja", "b1-16")]: {
        sk: "Przeczytałem recenzję filmu, zanim zdecydowałem się go obejrzeć.",
        ua: "Я прочитав рецензію на фільм, перш ніж вирішив його подивитися.",
        ru: "Я прочитал рецензию на фильм, прежде чем решил его посмотреть.",
        en: "I read a review of the film before deciding to watch it.",
        uaTokens: ["Я", "прочитав", "рецензію", "на", "фільм", ",", "перш", "ніж", "вирішив", "його", "подивитися", "."],
        ruTokens: ["Я", "прочитал", "рецензию", "на", "фильм", ",", "прежде", "чем", "решил", "его", "посмотреть", "."],
        enTokens: ["I", "read", "a", "review", "of", "the", "film", "before", "deciding", "to", "watch", "it", "."],
        extraUaTokens: ["виставу", "квиток", "музей"],
        extraRuTokens: ["спектакль", "билет", "музей"],
        extraEnTokens: ["play", "ticket", "museum"],
    },

    [phraseKey("doświadczenie", "b1-16")]: {
        sk: "To było niezapomniane doświadczenie, do którego chętnie wrócę.",
        ua: "Це був незабутній досвід, до якого я охоче повернуся.",
        ru: "Это был незабываемый опыт, к которому я с удовольствием вернусь.",
        en: "It was an unforgettable experience that I would gladly return to.",
        uaTokens: ["Це", "був", "незабутній", "досвід", ",", "до", "якого", "я", "охоче", "повернуся", "."],
        ruTokens: ["Это", "был", "незабываемый", "опыт", ",", "к", "которому", "я", "с", "удовольствием", "вернусь", "."],
        enTokens: ["It", "was", "an", "unforgettable", "experience", "that", "I", "would", "gladly", "return", "to", "."],
        extraUaTokens: ["концерт", "книга", "сцена"],
        extraRuTokens: ["концерт", "книга", "сцена"],
        extraEnTokens: ["concert", "book", "stage"],
    },

    [phraseKey("występ", "b1-16")]: {
        sk: "Występ artysty zrobił na publiczności ogromne wrażenie.",
        ua: "Виступ артиста справив на публіку величезне враження.",
        ru: "Выступление артиста произвело на публику огромное впечатление.",
        en: "The artist's performance made a huge impression on the audience.",
        uaTokens: ["Виступ", "артиста", "справив", "на", "публіку", "величезне", "враження", "."],
        ruTokens: ["Выступление", "артиста", "произвело", "на", "публику", "огромное", "впечатление", "."],
        enTokens: ["The", "artist's", "performance", "made", "a", "huge", "impression", "on", "the", "audience", "."],
        extraUaTokens: ["музей", "квиток", "смак"],
        extraRuTokens: ["музей", "билет", "вкус"],
        extraEnTokens: ["museum", "ticket", "taste"],
    },

    [phraseKey("czas wolny", "b1-16")]: {
        sk: "W czasie wolnym lubię czytać książki albo chodzić do kina.",
        ua: "У вільний час я люблю читати книжки або ходити в кіно.",
        ru: "В свободное время я люблю читать книги или ходить в кино.",
        en: "In my free time I like reading books or going to the cinema.",
        uaTokens: ["У", "вільний", "час", "я", "люблю", "читати", "книжки", "або", "ходити", "в", "кіно", "."],
        ruTokens: ["В", "свободное", "время", "я", "люблю", "читать", "книги", "или", "ходить", "в", "кино", "."],
        enTokens: ["In", "my", "free", "time", "I", "like", "reading", "books", "or", "going", "to", "the", "cinema", "."],
        extraUaTokens: ["музей", "концерт", "сестра"],
        extraRuTokens: ["музей", "концерт", "сестра"],
        extraEnTokens: ["museum", "concert", "sister"],
    },

    [phraseKey("występować", "b1-16")]: {
        sk: "Moja siostra będzie występować na scenie podczas koncertu.",
        ua: "Моя сестра буде виступати на сцені під час концерту.",
        ru: "Моя сестра будет выступать на сцене во время концерта.",
        en: "My sister will perform on stage during the concert.",
        uaTokens: ["Моя", "сестра", "буде", "виступати", "на", "сцені", "під", "час", "концерту", "."],
        ruTokens: ["Моя", "сестра", "будет", "выступать", "на", "сцене", "во", "время", "концерта", "."],
        enTokens: ["My", "sister", "will", "perform", "on", "stage", "during", "the", "concert", "."],
        extraUaTokens: ["музеї", "прем’єри", "квитки"],
        extraRuTokens: ["музее", "премьеры", "билеты"],
        extraEnTokens: ["museum", "premiere", "tickets"],
    },

    [phraseKey("odwiedzić", "b1-16")]: {
        sk: "Chcemy odwiedzić muzeum, ponieważ słyszeliśmy o nim wiele dobrego.",
        ua: "Ми хочемо відвідати музей, оскільки чули про нього багато хорошого.",
        ru: "Мы хотим посетить музей, потому что слышали о нём много хорошего.",
        en: "We want to visit the museum because we have heard many good things about it.",
        uaTokens: ["Ми", "хочемо", "відвідати", "музей", ",", "оскільки", "чули", "про", "нього", "багато", "хорошого", "."],
        ruTokens: ["Мы", "хотим", "посетить", "музей", ",", "потому", "что", "слышали", "о", "нём", "много", "хорошего", "."],
        enTokens: ["We", "want", "to", "visit", "the", "museum", "because", "we", "have", "heard", "many", "good", "things", "about", "it", "."],
        extraUaTokens: ["концерт", "сцена", "виступ"],
        extraRuTokens: ["концерт", "сцена", "выступление"],
        extraEnTokens: ["concert", "stage", "performance"],
    },

    [phraseKey("premiera", "b1-16")]: {
        sk: "Na premierę nowego spektaklu bilety sprzedały się bardzo szybko.",
        ua: "На прем’єру нової вистави квитки продалися дуже швидко.",
        ru: "На премьеру нового спектакля билеты продались очень быстро.",
        en: "Tickets for the premiere of the new play sold out very quickly.",
        uaTokens: ["На", "прем’єру", "нової", "вистави", "квитки", "продалися", "дуже", "швидко", "."],
        ruTokens: ["На", "премьеру", "нового", "спектакля", "билеты", "продались", "очень", "быстро", "."],
        enTokens: ["Tickets", "for", "the", "premiere", "of", "the", "new", "play", "sold", "out", "very", "quickly", "."],
        extraUaTokens: ["музей", "сцена", "програма"],
        extraRuTokens: ["музей", "сцена", "программа"],
        extraEnTokens: ["museum", "stage", "program"],
    },

    [phraseKey("program wydarzenia", "b1-16")]: {
        sk: "Program wydarzenia został zmieniony z powodu pogody.",
        ua: "Програму заходу змінили через погоду.",
        ru: "Программу мероприятия изменили из-за погоды.",
        en: "The event program was changed because of the weather.",
        uaTokens: ["Програму", "заходу", "змінили", "через", "погоду", "."],
        ruTokens: ["Программу", "мероприятия", "изменили", "из-за", "погоды", "."],
        enTokens: ["The", "event", "program", "was", "changed", "because", "of", "the", "weather", "."],
        extraUaTokens: ["квитки", "сцена", "зал"],
        extraRuTokens: ["билеты", "сцена", "зал"],
        extraEnTokens: ["tickets", "stage", "hall"],
    },

    [phraseKey("rezerwacja miejsca", "b1-16")]: {
        sk: "Rezerwacja miejsca jest konieczna, jeśli chcesz siedzieć blisko sceny.",
        ua: "Бронювання місця необхідне, якщо ти хочеш сидіти близько до сцени.",
        ru: "Бронирование места необходимо, если ты хочешь сидеть близко к сцене.",
        en: "Seat reservation is necessary if you want to sit close to the stage.",
        uaTokens: ["Бронювання", "місця", "необхідне", ",", "якщо", "ти", "хочеш", "сидіти", "близько", "до", "сцени", "."],
        ruTokens: ["Бронирование", "места", "необходимо", ",", "если", "ты", "хочешь", "сидеть", "близко", "к", "сцене", "."],
        enTokens: ["Seat", "reservation", "is", "necessary", "if", "you", "want", "to", "sit", "close", "to", "the", "stage", "."],
        extraUaTokens: ["квитки", "концерт", "виступ"],
        extraRuTokens: ["билеты", "концерт", "выступление"],
        extraEnTokens: ["tickets", "concert", "performance"],
    },

    // =========================
    // LESSON 17 — Спорт
    // =========================
    [phraseKey("trening", "b1-17")]: {
        sk: "Dzisiejszy trening był bardzo intensywny, ale dużo mi dał.",
        ua: "Сьогоднішнє тренування було дуже інтенсивним, але багато мені дало.",
        ru: "Сегодняшняя тренировка была очень интенсивной, но многое мне дала.",
        en: "Today's training was very intense, but it gave me a lot.",
        uaTokens: ["Сьогоднішнє", "тренування", "було", "дуже", "інтенсивним", ",", "але", "багато", "мені", "дало", "."],
        ruTokens: ["Сегодняшняя", "тренировка", "была", "очень", "интенсивной", ",", "но", "многое", "мне", "дала", "."],
        enTokens: ["Today's", "training", "was", "very", "intense", ",", "but", "it", "gave", "me", "a", "lot", "."],
        extraUaTokens: ["матч", "суддя", "гравець"],
        extraRuTokens: ["матч", "судья", "игрок"],
        extraEnTokens: ["match", "referee", "player"],
    },

    [phraseKey("mecz", "b1-17")]: {
        sk: "Wczorajszy mecz był bardzo emocjonujący i trwał do ostatniej minuty.",
        ua: "Учорашній матч був дуже напруженим і тривав до останньої хвилини.",
        ru: "Вчерашний матч был очень напряжённым и длился до последней минуты.",
        en: "Yesterday's match was very exciting and lasted until the final minute.",
        uaTokens: ["Учорашній", "матч", "був", "дуже", "напруженим", "і", "тривав", "до", "останньої", "хвилини", "."],
        ruTokens: ["Вчерашний", "матч", "был", "очень", "напряжённым", "и", "длился", "до", "последней", "минуты", "."],
        enTokens: ["Yesterday's", "match", "was", "very", "exciting", "and", "lasted", "until", "the", "final", "minute", "."],
        extraUaTokens: ["суддя", "команда", "глядач"],
        extraRuTokens: ["судья", "команда", "зритель"],
        extraEnTokens: ["referee", "team", "spectator"],
    },

    [phraseKey("wygrana", "b1-17")]: {
        sk: "Ta wygrana była dla nas ważna, ponieważ długo na nią pracowaliśmy.",
        ua: "Ця перемога була для нас важливою, оскільки ми довго на неї працювали.",
        ru: "Эта победа была для нас важной, потому что мы долго к ней шли.",
        en: "This victory was important for us because we had worked for it for a long time.",
        uaTokens: ["Ця", "перемога", "була", "для", "нас", "важливою", ",", "оскільки", "ми", "довго", "на", "неї", "працювали", "."],
        ruTokens: ["Эта", "победа", "была", "для", "нас", "важной", ",", "потому", "что", "мы", "долго", "к", "ней", "шли", "."],
        enTokens: ["This", "victory", "was", "important", "for", "us", "because", "we", "had", "worked", "for", "it", "for", "a", "long", "time", "."],
        extraUaTokens: ["поразка", "матч", "тренер"],
        extraRuTokens: ["поражение", "матч", "тренер"],
        extraEnTokens: ["defeat", "match", "coach"],
    },

    [phraseKey("porażka", "b1-17")]: {
        sk: "Porażka była bolesna, ale wiele nas nauczyła.",
        ua: "Поразка була болючою, але багато нас навчила.",
        ru: "Поражение было болезненным, но многому нас научило.",
        en: "The defeat was painful, but it taught us a lot.",
        uaTokens: ["Поразка", "була", "болючою", ",", "але", "багато", "нас", "навчила", "."],
        ruTokens: ["Поражение", "было", "болезненным", ",", "но", "многому", "нас", "научило", "."],
        enTokens: ["The", "defeat", "was", "painful", ",", "but", "it", "taught", "us", "a", "lot", "."],
        extraUaTokens: ["перемога", "матч", "досвід"],
        extraRuTokens: ["победа", "матч", "опыт"],
        extraEnTokens: ["victory", "match", "experience"],
    },

    [phraseKey("sędzia", "b1-17")]: {
        sk: "Sędzia przerwał grę, ponieważ jeden z zawodników był kontuzjowany.",
        ua: "Суддя зупинив гру, оскільки один із гравців був травмований.",
        ru: "Судья остановил игру, потому что один из игроков был травмирован.",
        en: "The referee stopped the game because one of the players was injured.",
        uaTokens: ["Суддя", "зупинив", "гру", ",", "оскільки", "один", "із", "гравців", "був", "травмований", "."],
        ruTokens: ["Судья", "остановил", "игру", ",", "потому", "что", "один", "из", "игроков", "был", "травмирован", "."],
        enTokens: ["The", "referee", "stopped", "the", "game", "because", "one", "of", "the", "players", "was", "injured", "."],
        extraUaTokens: ["матч", "команда", "перерва"],
        extraRuTokens: ["матч", "команда", "перерыв"],
        extraEnTokens: ["match", "team", "break"],
    },

    [phraseKey("konkurs", "b1-17")]: {
        sk: "W konkursie wzięło udział więcej osób, niż się spodziewaliśmy.",
        ua: "У змаганні взяло участь більше людей, ніж ми очікували.",
        ru: "В соревновании приняло участие больше людей, чем мы ожидали.",
        en: "More people took part in the competition than we expected.",
        uaTokens: ["У", "змаганні", "взяло", "участь", "більше", "людей", ",", "ніж", "ми", "очікували", "."],
        ruTokens: ["В", "соревновании", "приняло", "участие", "больше", "людей", ",", "чем", "мы", "ожидали", "."],
        enTokens: ["More", "people", "took", "part", "in", "the", "competition", "than", "we", "expected", "."],
        extraUaTokens: ["глядач", "матч", "результат"],
        extraRuTokens: ["зритель", "матч", "результат"],
        extraEnTokens: ["spectator", "match", "result"],
    },

    [phraseKey("widz", "b1-17")]: {
        sk: "Każdy widz reagował bardzo emocjonalnie na przebieg meczu.",
        ua: "Кожен глядач дуже емоційно реагував на хід матчу.",
        ru: "Каждый зритель очень эмоционально реагировал на ход матча.",
        en: "Every spectator reacted very emotionally to the course of the match.",
        uaTokens: ["Кожен", "глядач", "дуже", "емоційно", "реагував", "на", "хід", "матчу", "."],
        ruTokens: ["Каждый", "зритель", "очень", "эмоционально", "реагировал", "на", "ход", "матча", "."],
        enTokens: ["Every", "spectator", "reacted", "very", "emotionally", "to", "the", "course", "of", "the", "match", "."],
        uaAltAnswers: [["Кожен", "глядач", "реагував", "дуже", "емоційно", "на", "хід", "матчу", "."]],
        ruAltAnswers: [["Каждый", "зритель", "реагировал", "очень", "эмоционально", "на", "ход", "матча", "."]],
        extraUaTokens: ["суддя", "команда", "тренування"],
        extraRuTokens: ["судья", "команда", "тренировка"],
        extraEnTokens: ["referee", "team", "training"],
    },

    [phraseKey("zespół", "b1-17")]: {
        sk: "Nasz zespół grał dobrze, ponieważ byliśmy świetnie przygotowani.",
        ua: "Наша команда грала добре, оскільки ми були чудово підготовлені.",
        ru: "Наша команда играла хорошо, потому что мы были отлично подготовлены.",
        en: "Our team played well because we were very well prepared.",
        uaTokens: ["Наша", "команда", "грала", "добре", ",", "оскільки", "ми", "були", "чудово", "підготовлені", "."],
        ruTokens: ["Наша", "команда", "играла", "хорошо", ",", "потому", "что", "мы", "были", "отлично", "подготовлены", "."],
        enTokens: ["Our", "team", "played", "well", "because", "we", "were", "very", "well", "prepared", "."],
        extraUaTokens: ["глядач", "суддя", "перемога"],
        extraRuTokens: ["зритель", "судья", "победа"],
        extraEnTokens: ["spectator", "referee", "victory"],
    },

    [phraseKey("wydajność", "b1-17")]: {
        sk: "Jego wydajność spadła, gdy zaczął odczuwać zmęczenie.",
        ua: "Його результативність знизилася, коли він почав відчувати втому.",
        ru: "Его результативность снизилась, когда он начал чувствовать усталость.",
        en: "His performance dropped when he started to feel tired.",
        uaTokens: ["Його", "результативність", "знизилася", ",", "коли", "він", "почав", "відчувати", "втому", "."],
        ruTokens: ["Его", "результативность", "снизилась", ",", "когда", "он", "начал", "чувствовать", "усталость", "."],
        enTokens: ["His", "performance", "dropped", "when", "he", "started", "to", "feel", "tired", "."],
        extraUaTokens: ["тренування", "перерва", "матч"],
        extraRuTokens: ["тренировка", "перерыв", "матч"],
        extraEnTokens: ["training", "break", "match"],
    },

    [phraseKey("uraz", "b1-17")]: {
        sk: "Po urazie kolana musiał zrobić sobie dłuższą przerwę od sportu.",
        ua: "Після травми коліна йому довелося зробити довшу перерву у спорті.",
        ru: "После травмы колена ему пришлось сделать более длительный перерыв в спорте.",
        en: "After a knee injury, he had to take a longer break from sport.",
        uaTokens: ["Після", "травми", "коліна", "йому", "довелося", "зробити", "довшу", "перерву", "у", "спорті", "."],
        ruTokens: ["После", "травмы", "колена", "ему", "пришлось", "сделать", "более", "длительный", "перерыв", "в", "спорте", "."],
        enTokens: ["After", "a", "knee", "injury", ",", "he", "had", "to", "take", "a", "longer", "break", "from", "sport", "."],
        extraUaTokens: ["тренування", "втома", "команда"],
        extraRuTokens: ["тренировка", "усталость", "команда"],
        extraEnTokens: ["training", "fatigue", "team"],
    },

    // =========================
    // LESSON 18 — Географія
    // =========================
    [phraseKey("kontynent", "b1-18")]: {
        sk: "Australia jest najmniejszym kontynentem na świecie.",
        ua: "Австралія є найменшим континентом у світі.",
        ru: "Австралия является самым маленьким континентом в мире.",
        en: "Australia is the smallest continent in the world.",
        uaTokens: ["Австралія", "є", "найменшим", "континентом", "у", "світі", "."],
        ruTokens: ["Австралия", "является", "самым", "маленьким", "континентом", "в", "мире", "."],
        enTokens: ["Australia", "is", "the", "smallest", "continent", "in", "the", "world", "."],
        extraUaTokens: ["кордон", "клімат", "острів"],
        extraRuTokens: ["граница", "климат", "остров"],
        extraEnTokens: ["border", "climate", "island"],
    },

    [phraseKey("granica", "b1-18")]: {
        sk: "Przekroczyliśmy granicę bez problemów, ponieważ mieliśmy wszystkie dokumenty.",
        ua: "Ми перетнули кордон без проблем, оскільки мали всі документи.",
        ru: "Мы пересекли границу без проблем, потому что у нас были все документы.",
        en: "We crossed the border without problems because we had all the documents.",
        uaTokens: ["Ми", "перетнули", "кордон", "без", "проблем", ",", "оскільки", "мали", "всі", "документи", "."],
        ruTokens: ["Мы", "пересекли", "границу", "без", "проблем", ",", "потому", "что", "у", "нас", "были", "все", "документы", "."],
        enTokens: ["We", "crossed", "the", "border", "without", "problems", "because", "we", "had", "all", "the", "documents", "."],
        extraUaTokens: ["паспорт", "країна", "столиця"],
        extraRuTokens: ["паспорт", "страна", "столица"],
        extraEnTokens: ["passport", "country", "capital"],
    },

    [phraseKey("ludność", "b1-18")]: {
        sk: "Ludność tego miasta stale rośnie z roku na rok.",
        ua: "Населення цього міста постійно зростає з року в рік.",
        ru: "Население этого города постоянно растёт из года в год.",
        en: "The population of this city keeps growing year by year.",
        uaTokens: ["Населення", "цього", "міста", "постійно", "зростає", "з", "року", "в", "рік", "."],
        ruTokens: ["Население", "этого", "города", "постоянно", "растёт", "из", "года", "в", "год", "."],
        enTokens: ["The", "population", "of", "this", "city", "keeps", "growing", "year", "by", "year", "."],
        uaAltAnswers: [["Населення", "цього", "міста", "зростає", "постійно", "з", "року", "в", "рік", "."]],
        ruAltAnswers: [["Население", "этого", "города", "растёт", "постоянно", "из", "года", "в", "год", "."]],
        extraUaTokens: ["клімат", "столиця", "географія"],
        extraRuTokens: ["климат", "столица", "география"],
        extraEnTokens: ["climate", "capital", "geography"],
    },

    [phraseKey("klimat", "b1-18")]: {
        sk: "Klimat w tym regionie jest łagodny, dlatego żyje się tu wygodnie.",
        ua: "Клімат у цьому регіоні м’який, тому тут комфортно жити.",
        ru: "Климат в этом регионе мягкий, поэтому здесь комфортно жить.",
        en: "The climate in this region is mild, so it is comfortable to live here.",
        uaTokens: ["Клімат", "у", "цьому", "регіоні", "м’який", ",", "тому", "тут", "комфортно", "жити", "."],
        ruTokens: ["Климат", "в", "этом", "регионе", "мягкий", ",", "поэтому", "здесь", "комфортно", "жить", "."],
        enTokens: ["The", "climate", "in", "this", "region", "is", "mild", ",", "so", "it", "is", "comfortable", "to", "live", "here", "."],
        uaAltAnswers: [["Клімат", "у", "цьому", "регіоні", "м’який", ",", "тому", "жити", "тут", "комфортно", "."]],
        ruAltAnswers: [["Климат", "в", "этом", "регионе", "мягкий", ",", "поэтому", "жить", "здесь", "комфортно", "."]],
        extraUaTokens: ["населення", "море", "столиця"],
        extraRuTokens: ["население", "море", "столица"],
        extraEnTokens: ["population", "sea", "capital"],
    },

    [phraseKey("stolica", "b1-18")]: {
        sk: "Warszawa jest stolicą Polski i największym miastem kraju.",
        ua: "Варшава є столицею Польщі та найбільшим містом країни.",
        ru: "Варшава является столицей Польши и крупнейшим городом страны.",
        en: "Warsaw is the capital of Poland and the country's largest city.",
        uaTokens: ["Варшава", "є", "столицею", "Польщі", "та", "найбільшим", "містом", "країни", "."],
        ruTokens: ["Варшава", "является", "столицей", "Польши", "и", "крупнейшим", "городом", "страны", "."],
        enTokens: ["Warsaw", "is", "the", "capital", "of", "Poland", "and", "the", "country's", "largest", "city", "."],
        extraUaTokens: ["кордон", "клімат", "населення"],
        extraRuTokens: ["граница", "климат", "население"],
        extraEnTokens: ["border", "climate", "population"],
    },

    [phraseKey("powierzchnia", "b1-18")]: {
        sk: "Powierzchnia tego jeziora jest znacznie większa, niż myślałem.",
        ua: "Площа цього озера значно більша, ніж я думав.",
        ru: "Площадь этого озера значительно больше, чем я думал.",
        en: "The surface area of this lake is much larger than I thought.",
        uaTokens: ["Площа", "цього", "озера", "значно", "більша", ",", "ніж", "я", "думав", "."],
        ruTokens: ["Площадь", "этого", "озера", "значительно", "больше", ",", "чем", "я", "думал", "."],
        enTokens: ["The", "surface", "area", "of", "this", "lake", "is", "much", "larger", "than", "I", "thought", "."],
        extraUaTokens: ["карта", "острів", "регіон"],
        extraRuTokens: ["карта", "остров", "регион"],
        extraEnTokens: ["map", "island", "region"],
    },

    [phraseKey("wybrzeże", "b1-18")]: {
        sk: "Latem wiele osób jedzie nad wybrzeże, żeby odpocząć nad morzem.",
        ua: "Влітку багато людей їдуть на узбережжя, щоб відпочити біля моря.",
        ru: "Летом многие едут на побережье, чтобы отдохнуть у моря.",
        en: "In summer many people go to the coast to relax by the sea.",
        uaTokens: ["Влітку", "багато", "людей", "їдуть", "на", "узбережжя", ",", "щоб", "відпочити", "біля", "моря", "."],
        ruTokens: ["Летом", "многие", "едут", "на", "побережье", ",", "чтобы", "отдохнуть", "у", "моря", "."],
        enTokens: ["In", "summer", "many", "people", "go", "to", "the", "coast", "to", "relax", "by", "the", "sea", "."],
        extraUaTokens: ["острів", "клімат", "регіон"],
        extraRuTokens: ["остров", "климат", "регион"],
        extraEnTokens: ["island", "climate", "region"],
    },

    [phraseKey("wyspa", "b1-18")]: {
        sk: "Ta wyspa jest mała, ale bardzo popularna wśród turystów.",
        ua: "Цей острів невеликий, але дуже популярний серед туристів.",
        ru: "Этот остров небольшой, но очень популярный среди туристов.",
        en: "This island is small but very popular among tourists.",
        uaTokens: ["Цей", "острів", "невеликий", ",", "але", "дуже", "популярний", "серед", "туристів", "."],
        ruTokens: ["Этот", "остров", "небольшой", ",", "но", "очень", "популярный", "среди", "туристов", "."],
        enTokens: ["This", "island", "is", "small", "but", "very", "popular", "among", "tourists", "."],
        extraUaTokens: ["узбережжя", "клімат", "море"],
        extraRuTokens: ["побережье", "климат", "море"],
        extraEnTokens: ["coast", "climate", "sea"],
    },

    [phraseKey("wnętrze kraju", "b1-18")]: {
        sk: "Wnętrze kraju ma inny klimat niż regiony nadmorskie.",
        ua: "Внутрішня частина країни має інший клімат, ніж приморські регіони.",
        ru: "Внутренняя часть страны имеет другой климат, чем прибрежные регионы.",
        en: "The inland part of the country has a different climate than the coastal regions.",
        uaTokens: ["Внутрішня", "частина", "країни", "має", "інший", "клімат", ",", "ніж", "приморські", "регіони", "."],
        ruTokens: ["Внутренняя", "часть", "страны", "имеет", "другой", "климат", ",", "чем", "прибрежные", "регионы", "."],
        enTokens: ["The", "inland", "part", "of", "the", "country", "has", "a", "different", "climate", "than", "the", "coastal", "regions", "."],
        extraUaTokens: ["узбережжя", "острів", "столиця"],
        extraRuTokens: ["побережье", "остров", "столица"],
        extraEnTokens: ["coast", "island", "capital"],
    },

    [phraseKey("geografia", "b1-18")]: {
        sk: "Geografia była moim ulubionym przedmiotem w szkole.",
        ua: "Географія була моїм улюбленим предметом у школі.",
        ru: "География была моим любимым предметом в школе.",
        en: "Geography was my favorite subject at school.",
        uaTokens: ["Географія", "була", "моїм", "улюбленим", "предметом", "у", "школі", "."],
        ruTokens: ["География", "была", "моим", "любимым", "предметом", "в", "школе", "."],
        enTokens: ["Geography", "was", "my", "favorite", "subject", "at", "school", "."],
        extraUaTokens: ["карта", "столиця", "клімат"],
        extraRuTokens: ["карта", "столица", "климат"],
        extraEnTokens: ["map", "capital", "climate"],
    },

    // =========================
    // LESSON 19 — Математика
    // =========================
    [phraseKey("równanie", "b1-19")]: {
        sk: "To równanie wydaje się trudne, ale da się je rozwiązać krok po kroku.",
        ua: "Це рівняння виглядає складним, але його можна розв’язати крок за кроком.",
        ru: "Это уравнение выглядит сложным, но его можно решить шаг за шагом.",
        en: "This equation looks difficult, but it can be solved step by step.",
        uaTokens: ["Це", "рівняння", "виглядає", "складним", ",", "але", "його", "можна", "розв’язати", "крок", "за", "кроком", "."],
        ruTokens: ["Это", "уравнение", "выглядит", "сложным", ",", "но", "его", "можно", "решить", "шаг", "за", "шагом", "."],
        enTokens: ["This", "equation", "looks", "difficult", ",", "but", "it", "can", "be", "solved", "step", "by", "step", "."],
        extraUaTokens: ["число", "графік", "значення"],
        extraRuTokens: ["число", "график", "значение"],
        extraEnTokens: ["number", "graph", "value"],
    },

    [phraseKey("wynik", "b1-19")]: {
        sk: "Jeśli popełnisz błąd na początku, końcowy wynik będzie nieprawidłowy.",
        ua: "Якщо ти зробиш помилку на початку, кінцевий результат буде неправильним.",
        ru: "Если ты допустишь ошибку в начале, конечный результат будет неправильным.",
        en: "If you make a mistake at the beginning, the final result will be incorrect.",
        uaTokens: ["Якщо", "ти", "зробиш", "помилку", "на", "початку", ",", "кінцевий", "результат", "буде", "неправильним", "."],
        ruTokens: ["Если", "ты", "допустишь", "ошибку", "в", "начале", ",", "конечный", "результат", "будет", "неправильным", "."],
        enTokens: ["If", "you", "make", "a", "mistake", "at", "the", "beginning", ",", "the", "final", "result", "will", "be", "incorrect", "."],
        extraUaTokens: ["рівняння", "число", "графік"],
        extraRuTokens: ["уравнение", "число", "график"],
        extraEnTokens: ["equation", "number", "graph"],
    },

    [phraseKey("mnożyć", "b1-19")]: {
        sk: "Najpierw trzeba mnożyć, a dopiero potem dodawać.",
        ua: "Спочатку треба множити, а вже потім додавати.",
        ru: "Сначала нужно умножать, а уже потом складывать.",
        en: "First you have to multiply and only then add.",
        uaTokens: ["Спочатку", "треба", "множити", ",", "а", "вже", "потім", "додавати", "."],
        ruTokens: ["Сначала", "нужно", "умножать", ",", "а", "уже", "потом", "складывать", "."],
        enTokens: ["First", "you", "have", "to", "multiply", "and", "only", "then", "add", "."],
        extraUaTokens: ["ділити", "число", "відсоток"],
        extraRuTokens: ["делить", "число", "процент"],
        extraEnTokens: ["divide", "number", "percent"],
    },

    [phraseKey("dzielić", "b1-19")]: {
        sk: "Nie można dzielić przez zero, ponieważ to nie ma sensu matematycznego.",
        ua: "Не можна ділити на нуль, оскільки це не має математичного сенсу.",
        ru: "Нельзя делить на ноль, потому что это не имеет математического смысла.",
        en: "You cannot divide by zero because it makes no mathematical sense.",
        uaTokens: ["Не", "можна", "ділити", "на", "нуль", ",", "оскільки", "це", "не", "має", "математичного", "сенсу", "."],
        ruTokens: ["Нельзя", "делить", "на", "ноль", ",", "потому", "что", "это", "не", "имеет", "математического", "смысла", "."],
        enTokens: ["You", "cannot", "divide", "by", "zero", "because", "it", "makes", "no", "mathematical", "sense", "."],
        extraUaTokens: ["рівняння", "число", "дроби"],
        extraRuTokens: ["уравнение", "число", "дроби"],
        extraEnTokens: ["equation", "number", "fractions"],
    },

    [phraseKey("odczytać", "b1-19")]: {
        sk: "Żeby rozwiązać to zadanie, musisz najpierw odczytać właściwą wartość.",
        ua: "Щоб розв’язати це завдання, ти повинен спочатку зчитати правильне значення.",
        ru: "Чтобы решить это задание, тебе нужно сначала считать правильное значение.",
        en: "To solve this task, you first need to read the correct value.",
        uaTokens: ["Щоб", "розв’язати", "це", "завдання", ",", "ти", "повинен", "спочатку", "зчитати", "правильне", "значення", "."],
        ruTokens: ["Чтобы", "решить", "это", "задание", ",", "тебе", "нужно", "сначала", "считать", "правильное", "значение", "."],
        enTokens: ["To", "solve", "this", "task", ",", "you", "first", "need", "to", "read", "the", "correct", "value", "."],
        extraUaTokens: ["рівняння", "графік", "число"],
        extraRuTokens: ["уравнение", "график", "число"],
        extraEnTokens: ["equation", "graph", "number"],
    },

    [phraseKey("dodawać", "b1-19")]: {
        sk: "Dzieci najpierw uczą się dodawać, a dopiero później mnożyć.",
        ua: "Діти спочатку вчаться додавати, а вже потім множити.",
        ru: "Дети сначала учатся складывать, а потом умножать.",
        en: "Children first learn to add and only later to multiply.",
        uaTokens: ["Діти", "спочатку", "вчаться", "додавати", ",", "а", "вже", "потім", "множити", "."],
        ruTokens: ["Дети", "сначала", "учатся", "складывать", ",", "а", "потом", "умножать", "."],
        enTokens: ["Children", "first", "learn", "to", "add", "and", "only", "later", "to", "multiply", "."],
        extraUaTokens: ["ділити", "дроби", "число"],
        extraRuTokens: ["делить", "дроби", "число"],
        extraEnTokens: ["divide", "fractions", "number"],
    },

    [phraseKey("ułamek", "b1-19")]: {
        sk: "Ten ułamek jest dla mnie trudny, dlatego muszę go jeszcze przećwiczyć.",
        ua: "Цей дріб для мене складний, тому мені потрібно ще його потренувати.",
        ru: "Эта дробь для меня сложная, поэтому мне нужно ещё её потренировать.",
        en: "This fraction is difficult for me, so I need to practice it more.",
        uaTokens: ["Цей", "дріб", "для", "мене", "складний", ",", "тому", "мені", "потрібно", "ще", "його", "потренувати", "."],
        ruTokens: ["Эта", "дробь", "для", "меня", "сложная", ",", "поэтому", "мне", "нужно", "ещё", "её", "потренировать", "."],
        enTokens: ["This", "fraction", "is", "difficult", "for", "me", ",", "so", "I", "need", "to", "practice", "it", "more", "."],
        uaAltAnswers: [["Цей", "дріб", "для", "мене", "складний", ",", "тому", "мені", "потрібно", "його", "ще", "потренувати", "."]],
        ruAltAnswers: [["Эта", "дробь", "для", "меня", "сложная", ",", "поэтому", "мне", "нужно", "её", "ещё", "потренировать", "."]],
        extraUaTokens: ["відсоток", "число", "значення"],
        extraRuTokens: ["процент", "число", "значение"],
        extraEnTokens: ["percent", "number", "value"],
    },

    [phraseKey("procent", "b1-19")]: {
        sk: "Obliczyliśmy procent zniżki podczas zakupów.",
        ua: "Ми порахували відсоток знижки під час покупок.",
        ru: "Мы посчитали процент скидки во время покупок.",
        en: "We calculated the discount percentage while shopping.",
        uaTokens: ["Ми", "порахували", "відсоток", "знижки", "під", "час", "покупок", "."],
        ruTokens: ["Мы", "посчитали", "процент", "скидки", "во", "время", "покупок", "."],
        enTokens: ["We", "calculated", "the", "discount", "percentage", "while", "shopping", "."],
        extraUaTokens: ["графік", "число", "рівняння"],
        extraRuTokens: ["график", "число", "уравнение"],
        extraEnTokens: ["graph", "number", "equation"],
    },

    [phraseKey("wykres", "b1-19")]: {
        sk: "Na wykresie widać wyraźny wzrost sprzedaży.",
        ua: "На графіку видно явне зростання продажів.",
        ru: "На графике видно явный рост продаж.",
        en: "The graph shows a clear increase in sales.",
        uaTokens: ["На", "графіку", "видно", "явне", "зростання", "продажів", "."],
        ruTokens: ["На", "графике", "видно", "явный", "рост", "продаж", "."],
        enTokens: ["The", "graph", "shows", "a", "clear", "increase", "in", "sales", "."],
        extraUaTokens: ["відсоток", "число", "результат"],
        extraRuTokens: ["процент", "число", "результат"],
        extraEnTokens: ["percent", "number", "result"],
    },

    [phraseKey("obliczyć", "b1-19")]: {
        sk: "Muszę obliczyć wynik, zanim oddam zadanie.",
        ua: "Мені потрібно обчислити результат, перш ніж здати завдання.",
        ru: "Мне нужно вычислить результат, прежде чем сдать задание.",
        en: "I need to calculate the result before submitting the task.",
        uaTokens: ["Мені", "потрібно", "обчислити", "результат", ",", "перш", "ніж", "здати", "завдання", "."],
        ruTokens: ["Мне", "нужно", "вычислить", "результат", ",", "прежде", "чем", "сдать", "задание", "."],
        enTokens: ["I", "need", "to", "calculate", "the", "result", "before", "submitting", "the", "task", "."],
        extraUaTokens: ["число", "рівняння", "графік"],
        extraRuTokens: ["число", "уравнение", "график"],
        extraEnTokens: ["number", "equation", "graph"],
    },

    // =========================
    // LESSON 20 — Держава та суспільство
    // =========================
    [phraseKey("prawo", "b1-20")]: {
        sk: "Prawo musi być przestrzegane przez wszystkich obywateli.",
        ua: "Закон повинен дотримуватися всіма громадянами.",
        ru: "Закон должен соблюдаться всеми гражданами.",
        en: "The law must be followed by all citizens.",
        uaTokens: ["Закон", "повинен", "дотримуватися", "всіма", "громадянами", "."],
        ruTokens: ["Закон", "должен", "соблюдаться", "всеми", "гражданами", "."],
        enTokens: ["The", "law", "must", "be", "followed", "by", "all", "citizens", "."],
        extraUaTokens: ["уряд", "вибори", "парламент"],
        extraRuTokens: ["правительство", "выборы", "парламент"],
        extraEnTokens: ["government", "elections", "parliament"],
    },

    [phraseKey("wybory", "b1-20")]: {
        sk: "Wybory odbędą się w przyszłym miesiącu.",
        ua: "Вибори відбудуться наступного місяця.",
        ru: "Выборы состоятся в следующем месяце.",
        en: "The elections will take place next month.",
        uaTokens: ["Вибори", "відбудуться", "наступного", "місяця", "."],
        ruTokens: ["Выборы", "состоятся", "в", "следующем", "месяце", "."],
        enTokens: ["The", "elections", "will", "take", "place", "next", "month", "."],
        extraUaTokens: ["уряд", "закон", "президент"],
        extraRuTokens: ["правительство", "закон", "президент"],
        extraEnTokens: ["government", "law", "president"],
    },

    [phraseKey("rząd", "b1-20")]: {
        sk: "Rząd wprowadził nowe przepisy dotyczące pracy.",
        ua: "Уряд запровадив нові правила щодо роботи.",
        ru: "Правительство ввело новые правила, касающиеся работы.",
        en: "The government introduced new work regulations.",
        uaTokens: ["Уряд", "запровадив", "нові", "правила", "щодо", "роботи", "."],
        ruTokens: ["Правительство", "ввело", "новые", "правила", ",", "касающиеся", "работы", "."],
        enTokens: ["The", "government", "introduced", "new", "work", "regulations", "."],
        extraUaTokens: ["закон", "парламент", "реформи"],
        extraRuTokens: ["закон", "парламент", "реформы"],
        extraEnTokens: ["law", "parliament", "reforms"],
    },

    [phraseKey("obywatel", "b1-20")]: {
        sk: "Każdy obywatel ma swoje prawa i obowiązki.",
        ua: "Кожен громадянин має свої права та обов’язки.",
        ru: "Каждый гражданин имеет свои права и обязанности.",
        en: "Every citizen has their rights and obligations.",
        uaTokens: ["Кожен", "громадянин", "має", "свої", "права", "та", "обов’язки", "."],
        ruTokens: ["Каждый", "гражданин", "имеет", "свои", "права", "и", "обязанности", "."],
        enTokens: ["Every", "citizen", "has", "their", "rights", "and", "obligations", "."],
        extraUaTokens: ["закон", "держава", "референдум"],
        extraRuTokens: ["закон", "государство", "референдум"],
        extraEnTokens: ["law", "state", "referendum"],
    },

    [phraseKey("parlament", "b1-20")]: {
        sk: "Parlament uchwalił nową ustawę.",
        ua: "Парламент ухвалив новий закон.",
        ru: "Парламент принял новый закон.",
        en: "The parliament passed a new law.",
        uaTokens: ["Парламент", "ухвалив", "новий", "закон", "."],
        ruTokens: ["Парламент", "принял", "новый", "закон", "."],
        enTokens: ["The", "parliament", "passed", "a", "new", "law", "."],
        extraUaTokens: ["уряд", "президент", "реформи"],
        extraRuTokens: ["правительство", "президент", "реформы"],
        extraEnTokens: ["government", "president", "reforms"],
    },

    [phraseKey("prezydent", "b1-20")]: {
        sk: "Prezydent wygłosił przemówienie do narodu.",
        ua: "Президент виголосив промову до народу.",
        ru: "Президент выступил с речью перед народом.",
        en: "The president delivered a speech to the nation.",
        uaTokens: ["Президент", "виголосив", "промову", "до", "народу", "."],
        ruTokens: ["Президент", "выступил", "с", "речью", "перед", "народом", "."],
        enTokens: ["The", "president", "delivered", "a", "speech", "to", "the", "nation", "."],
        extraUaTokens: ["парламент", "уряд", "вибори"],
        extraRuTokens: ["парламент", "правительство", "выборы"],
        extraEnTokens: ["parliament", "government", "elections"],
    },

    [phraseKey("konstytucja", "b1-20")]: {
        sk: "Konstytucja gwarantuje podstawowe prawa obywateli.",
        ua: "Конституція гарантує основні права громадян.",
        ru: "Конституция гарантирует основные права граждан.",
        en: "The constitution guarantees basic rights of citizens.",
        uaTokens: ["Конституція", "гарантує", "основні", "права", "громадян", "."],
        ruTokens: ["Конституция", "гарантирует", "основные", "права", "граждан", "."],
        enTokens: ["The", "constitution", "guarantees", "basic", "rights", "of", "citizens", "."],
        extraUaTokens: ["закон", "парламент", "держава"],
        extraRuTokens: ["закон", "парламент", "государство"],
        extraEnTokens: ["law", "parliament", "state"],
    },

    [phraseKey("ministerstwo", "b1-20")]: {
        sk: "Ministerstwo ogłosiło nowe reformy.",
        ua: "Міністерство оголосило нові реформи.",
        ru: "Министерство объявило новые реформы.",
        en: "The ministry announced new reforms.",
        uaTokens: ["Міністерство", "оголосило", "нові", "реформи", "."],
        ruTokens: ["Министерство", "объявило", "новые", "реформы", "."],
        enTokens: ["The", "ministry", "announced", "new", "reforms", "."],
        extraUaTokens: ["уряд", "закон", "громадяни"],
        extraRuTokens: ["правительство", "закон", "граждане"],
        extraEnTokens: ["government", "law", "citizens"],
    },

    [phraseKey("referendum", "b1-20")]: {
        sk: "Referendum pozwala obywatelom wyrazić swoją opinię.",
        ua: "Референдум дозволяє громадянам висловити свою думку.",
        ru: "Референдум позволяет гражданам выразить своё мнение.",
        en: "A referendum allows citizens to express their opinion.",
        uaTokens: ["Референдум", "дозволяє", "громадянам", "висловити", "свою", "думку", "."],
        ruTokens: ["Референдум", "позволяет", "гражданам", "выразить", "своё", "мнение", "."],
        enTokens: ["A", "referendum", "allows", "citizens", "to", "express", "their", "opinion", "."],
        extraUaTokens: ["вибори", "закон", "уряд"],
        extraRuTokens: ["выборы", "закон", "правительство"],
        extraEnTokens: ["elections", "law", "government"],
    },

    [phraseKey("administracja państwowa", "b1-20")]: {
        sk: "Administracja państwowa odpowiada za funkcjonowanie kraju.",
        ua: "Державне управління відповідає за функціонування країни.",
        ru: "Государственное управление отвечает за функционирование страны.",
        en: "Public administration is responsible for the functioning of the country.",
        uaTokens: ["Державне", "управління", "відповідає", "за", "функціонування", "країни", "."],
        ruTokens: ["Государственное", "управление", "отвечает", "за", "функционирование", "страны", "."],
        enTokens: ["Public", "administration", "is", "responsible", "for", "the", "functioning", "of", "the", "country", "."],
        extraUaTokens: ["уряд", "міністерство", "закон"],
        extraRuTokens: ["правительство", "министерство", "закон"],
        extraEnTokens: ["government", "ministry", "law"],
    },
}