import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_B1_BUILD_UA_SENTENCES_5: BuildUaSentenceDict = {
    // =========================
    // LESSON 21 — Країни
    // =========================
    [phraseKey("Słowacja", "b1-21")]: {
        sk: "Słowacja jest małym krajem, ale bardzo mi się tu podoba.",
        ua: "Словаччина — невелика країна, але мені тут дуже подобається.",
        ru: "Словакия — небольшая страна, но мне здесь очень нравится.",
        en: "Slovakia is a small country, but I like it here very much.",
        uaTokens: ["Словаччина", "—", "невелика", "країна", ",", "але", "мені", "тут", "дуже", "подобається", "."],
        ruTokens: ["Словакия", "—", "небольшая", "страна", ",", "но", "мне", "здесь", "очень", "нравится", "."],
        enTokens: ["Slovakia", "is", "a", "small", "country", ",", "but", "I", "like", "it", "here", "very", "much", "."],
        extraUaTokens: ["архітектурою", "Будапешт", "відпочинку"],
        extraRuTokens: ["архитектурой", "Будапешт", "отдыха"],
        extraEnTokens: ["architecture", "Budapest", "vacation"],
    },

    [phraseKey("Czechy", "b1-21")]: {
        sk: "Czechy odwiedziłem kilka razy, ponieważ mam tam znajomych.",
        ua: "Чехію я відвідував кілька разів, бо маю там знайомих.",
        ru: "Чехию я посещал несколько раз, потому что у меня там есть знакомые.",
        en: "I have visited Czechia several times because I have friends there.",
        uaTokens: ["Чехію", "я", "відвідував", "кілька", "разів", ",", "бо", "маю", "там", "знайомих", "."],
        ruTokens: ["Чехию", "я", "посещал", "несколько", "раз", ",", "потому", "что", "у", "меня", "там", "есть", "знакомые", "."],
        enTokens: ["I", "have", "visited", "Czechia", "several", "times", "because", "I", "have", "friends", "there", "."],
        extraUaTokens: ["країна", "кухнею", "лижах"],
        extraRuTokens: ["страна", "кухней", "лыжах"],
        extraEnTokens: ["country", "cuisine", "skiing"],
    },

    [phraseKey("Polska", "b1-21")]: {
        sk: "Polska jest dla mnie ważna, ponieważ uczę się polskiego.",
        ua: "Польща важлива для мене, бо я вчу польську.",
        ru: "Польша важна для меня, потому что я учу польский.",
        en: "Poland is important to me because I am learning Polish.",
        uaTokens: ["Польща", "важлива", "для", "мене", ",", "бо", "я", "вчу", "польську", "."],
        ruTokens: ["Польша", "важна", "для", "меня", ",", "потому", "что", "я", "учу", "польский", "."],
        enTokens: ["Poland", "is", "important", "to", "me", "because", "I", "am", "learning", "Polish", "."],
        extraUaTokens: ["країна", "іноземців", "пам’ятати"],
        extraRuTokens: ["страна", "иностранцев", "помнить"],
        extraEnTokens: ["country", "foreigners", "remember"],
    },

    [phraseKey("Niemcy", "b1-21")]: {
        sk: "W Niemczech pracuje wielu obcokrajowców, dlatego kraj ten jest bardzo międzynarodowy.",
        ua: "У Німеччині працює багато іноземців, тому ця країна дуже міжнародна.",
        ru: "В Германии работает много иностранцев, поэтому эта страна очень международная.",
        en: "Many foreigners work in Germany, so this country is very international.",
        uaTokens: ["У", "Німеччині", "працює", "багато", "іноземців", ",", "тому", "ця", "країна", "дуже", "міжнародна", "."],
        ruTokens: ["В", "Германии", "работает", "много", "иностранцев", ",", "поэтому", "эта", "страна", "очень", "международная", "."],
        enTokens: ["Many", "foreigners", "work", "in", "Germany", ",", "so", "this", "country", "is", "very", "international", "."],
        extraUaTokens: ["знайомих", "архітектурою", "батьківщина"],
        extraRuTokens: ["знакомые", "архитектурой", "родина"],
        extraEnTokens: ["friends", "architecture", "homeland"],
    },

    [phraseKey("Austria", "b1-21")]: {
        sk: "Austria słynie z pięknych gór i dobrych warunków do jazdy na nartach.",
        ua: "Австрія славиться красивими горами та хорошими умовами для катання на лижах.",
        ru: "Австрия славится красивыми горами и хорошими условиями для катания на лыжах.",
        en: "Austria is famous for its beautiful mountains and good skiing conditions.",
        uaTokens: ["Австрія", "славиться", "красивими", "горами", "та", "хорошими", "умовами", "для", "катання", "на", "лижах", "."],
        ruTokens: ["Австрия", "славится", "красивыми", "горами", "и", "хорошими", "условиями", "для", "катания", "на", "лыжах", "."],
        enTokens: ["Austria", "is", "famous", "for", "its", "beautiful", "mountains", "and", "good", "skiing", "conditions", "."],
        extraUaTokens: ["міжнародна", "кухнею", "спекотно"],
        extraRuTokens: ["международная", "кухней", "жарко"],
        extraEnTokens: ["international", "cuisine", "hot"],
    },

    [phraseKey("Węgry", "b1-21")]: {
        sk: "Na Węgrzech chciałbym zobaczyć Budapeszt, ponieważ wiele o nim słyszałem.",
        ua: "В Угорщині я хотів би побачити Будапешт, бо багато про нього чув.",
        ru: "В Венгрии я хотел бы увидеть Будапешт, потому что много о нём слышал.",
        en: "In Hungary, I would like to see Budapest because I have heard a lot about it.",
        uaTokens: ["В", "Угорщині", "я", "хотів", "би", "побачити", "Будапешт", ",", "бо", "багато", "про", "нього", "чув", "."],
        ruTokens: ["В", "Венгрии", "я", "хотел", "бы", "увидеть", "Будапешт", ",", "потому", "что", "много", "о", "нём", "слышал", "."],
        enTokens: ["In", "Hungary", ",", "I", "would", "like", "to", "see", "Budapest", "because", "I", "have", "heard", "a", "lot", "about", "it", "."],
        extraUaTokens: ["горами", "знайомих", "архітектурою"],
        extraRuTokens: ["горами", "знакомые", "архитектурой"],
        extraEnTokens: ["mountains", "friends", "architecture"],
    },

    [phraseKey("Francja", "b1-21")]: {
        sk: "Francja kojarzy mi się z dobrą kuchnią i piękną architekturą.",
        ua: "Франція асоціюється в мене з доброю кухнею та гарною архітектурою.",
        ru: "Франция ассоциируется у меня с хорошей кухней и красивой архитектурой.",
        en: "France is associated in my mind with good cuisine and beautiful architecture.",
        uaTokens: ["Франція", "асоціюється", "в", "мене", "з", "доброю", "кухнею", "та", "гарною", "архітектурою", "."],
        ruTokens: ["Франция", "ассоциируется", "у", "меня", "с", "хорошей", "кухней", "и", "красивой", "архитектурой", "."],
        enTokens: ["France", "is", "associated", "in", "my", "mind", "with", "good", "cuisine", "and", "beautiful", "architecture", "."],
        extraUaTokens: ["Будапешт", "лижах", "батьківщина"],
        extraRuTokens: ["Будапешт", "лыжах", "родина"],
        extraEnTokens: ["Budapest", "skiing", "homeland"],
    },

    [phraseKey("Włochy", "b1-21")]: {
        sk: "Włochy chciałbym odwiedzić latem, chociaż wtedy jest tam bardzo gorąco.",
        ua: "Італію я хотів би відвідати влітку, хоча тоді там дуже спекотно.",
        ru: "Италию я хотел бы посетить летом, хотя тогда там очень жарко.",
        en: "I would like to visit Italy in summer, although it is very hot there then.",
        uaTokens: ["Італію", "я", "хотів", "би", "відвідати", "влітку", ",", "хоча", "тоді", "там", "дуже", "спекотно", "."],
        ruTokens: ["Италию", "я", "хотел", "бы", "посетить", "летом", ",", "хотя", "тогда", "там", "очень", "жарко", "."],
        enTokens: ["I", "would", "like", "to", "visit", "Italy", "in", "summer", ",", "although", "it", "is", "very", "hot", "there", "then", "."],
        extraUaTokens: ["архітектурою", "міжнародна", "відпочинку"],
        extraRuTokens: ["архитектурой", "международная", "отдыха"],
        extraEnTokens: ["architecture", "international", "vacation"],
    },

    [phraseKey("Hiszpania", "b1-21")]: {
        sk: "Hiszpania jest popularnym kierunkiem wakacyjnym, dlatego wiele osób tam wyjeżdża.",
        ua: "Іспанія є популярним напрямком для відпочинку, тому багато людей туди їздять.",
        ru: "Испания — популярное направление для отдыха, поэтому многие туда ездят.",
        en: "Spain is a popular holiday destination, so many people go there.",
        uaTokens: ["Іспанія", "є", "популярним", "напрямком", "для", "відпочинку", ",", "тому", "багато", "людей", "туди", "їздять", "."],
        ruTokens: ["Испания", "—", "популярное", "направление", "для", "отдыха", ",", "поэтому", "многие", "туда", "ездят", "."],
        enTokens: ["Spain", "is", "a", "popular", "holiday", "destination", ",", "so", "many", "people", "go", "there", "."],
        extraUaTokens: ["влітку", "архітектурою", "пам’ятати"],
        extraRuTokens: ["летом", "архитектурой", "помнить"],
        extraEnTokens: ["summer", "architecture", "remember"],
    },

    [phraseKey("Ukraina", "b1-21")]: {
        sk: "Ukraina jest moją ojczyzną, dlatego zawsze będę o niej pamiętać.",
        ua: "Україна — моя батьківщина, тому я завжди буду про неї пам’ятати.",
        ru: "Украина — моя родина, поэтому я всегда буду о ней помнить.",
        en: "Ukraine is my homeland, so I will always remember it.",
        uaTokens: ["Україна", "—", "моя", "батьківщина", ",", "тому", "я", "завжди", "буду", "про", "неї", "пам’ятати", "."],
        ruTokens: ["Украина", "—", "моя", "родина", ",", "поэтому", "я", "всегда", "буду", "о", "ней", "помнить", "."],
        enTokens: ["Ukraine", "is", "my", "homeland", ",", "so", "I", "will", "always", "remember", "it", "."],
        extraUaTokens: ["Польща", "знайомих", "горами"],
        extraRuTokens: ["Польша", "знакомые", "горами"],
        extraEnTokens: ["Poland", "friends", "mountains"],
    },

    // =========================
    // LESSON 22 — Медіа та інформація
    // =========================
    [phraseKey("druk", "b1-22")]: {
        sk: "Druk ma dziś mniejsze znaczenie niż internet, ale wciąż ma swoich odbiorców.",
        ua: "Преса сьогодні має менше значення, ніж інтернет, але все ще має своїх читачів.",
        ru: "Печать сегодня имеет меньшее значение, чем интернет, но всё ещё имеет свою аудиторию.",
        en: "The press is less important today than the internet, but it still has its audience.",
        uaTokens: ["Преса", "сьогодні", "має", "менше", "значення", ",", "ніж", "інтернет", ",", "але", "все", "ще", "має", "своїх", "читачів", "."],
        ruTokens: ["Печать", "сегодня", "имеет", "меньшее", "значение", ",", "чем", "интернет", ",", "но", "всё", "ещё", "имеет", "свою", "аудиторию", "."],
        enTokens: ["The", "press", "is", "less", "important", "today", "than", "the", "internet", ",", "but", "it", "still", "has", "its", "audience", "."],
        extraUaTokens: ["газету", "заголовок", "політиків"],
        extraRuTokens: ["газету", "заголовок", "политиков"],
        extraEnTokens: ["newspaper", "headline", "politicians"],
    },

    [phraseKey("gazeta", "b1-22")]: {
        sk: "Mój dziadek codziennie rano czyta gazetę przy kawie.",
        ua: "Мій дідусь щодня зранку читає газету за кавою.",
        ru: "Мой дедушка каждое утро читает газету за чашкой кофе.",
        en: "My grandfather reads the newspaper every morning with coffee.",
        uaTokens: ["Мій", "дідусь", "щодня", "зранку", "читає", "газету", "за", "кавою", "."],
        ruTokens: ["Мой", "дедушка", "каждое", "утро", "читает", "газету", "за", "чашкой", "кофе", "."],
        enTokens: ["My", "grandfather", "reads", "the", "newspaper", "every", "morning", "with", "coffee", "."],
        extraUaTokens: ["реклама", "статтю", "медіа"],
        extraRuTokens: ["реклама", "статью", "медиа"],
        extraEnTokens: ["advertising", "article", "media"],
    },

    [phraseKey("telewizja", "b1-22")]: {
        sk: "Telewizja nadal wpływa na ludzi, chociaż młodzi częściej wybierają internet.",
        ua: "Телебачення досі впливає на людей, хоча молодь частіше обирає інтернет.",
        ru: "Телевидение всё ещё влияет на людей, хотя молодёжь чаще выбирает интернет.",
        en: "Television still influences people, although young people more often choose the internet.",
        uaTokens: ["Телебачення", "досі", "впливає", "на", "людей", ",", "хоча", "молодь", "частіше", "обирає", "інтернет", "."],
        ruTokens: ["Телевидение", "всё", "ещё", "влияет", "на", "людей", ",", "хотя", "молодёжь", "чаще", "выбирает", "интернет", "."],
        enTokens: ["Television", "still", "influences", "people", ",", "although", "young", "people", "more", "often", "choose", "the", "internet", "."],
        extraUaTokens: ["газету", "реклама", "читачів"],
        extraRuTokens: ["газету", "реклама", "аудиторию"],
        extraEnTokens: ["newspaper", "advertising", "audience"],
    },

    [phraseKey("radio", "b1-22")]: {
        sk: "Radio włączam w samochodzie, ponieważ lubię słuchać wiadomości w drodze do pracy.",
        ua: "Радіо я вмикаю в машині, бо люблю слухати новини дорогою на роботу.",
        ru: "Радио я включаю в машине, потому что люблю слушать новости по дороге на работу.",
        en: "I turn on the radio in the car because I like listening to the news on the way to work.",
        uaTokens: ["Радіо", "я", "вмикаю", "в", "машині", ",", "бо", "люблю", "слухати", "новини", "дорогою", "на", "роботу", "."],
        ruTokens: ["Радио", "я", "включаю", "в", "машине", ",", "потому", "что", "люблю", "слушать", "новости", "по", "дороге", "на", "работу", "."],
        enTokens: ["I", "turn", "on", "the", "radio", "in", "the", "car", "because", "I", "like", "listening", "to", "the", "news", "on", "the", "way", "to", "work", "."],
        extraUaTokens: ["газету", "трансляція", "статтю"],
        extraRuTokens: ["газету", "трансляция", "статью"],
        extraEnTokens: ["newspaper", "broadcast", "article"],
    },

    [phraseKey("nadawanie", "b1-22")]: {
        sk: "Nadawanie programu rozpoczęło się z opóźnieniem z powodów technicznych.",
        ua: "Трансляція програми почалася із запізненням через технічні причини.",
        ru: "Трансляция программы началась с опозданием по техническим причинам.",
        en: "The broadcast of the program started late for technical reasons.",
        uaTokens: ["Трансляція", "програми", "почалася", "із", "запізненням", "через", "технічні", "причини", "."],
        ruTokens: ["Трансляция", "программы", "началась", "с", "опозданием", "по", "техническим", "причинам", "."],
        enTokens: ["The", "broadcast", "of", "the", "program", "started", "late", "for", "technical", "reasons", "."],
        extraUaTokens: ["заголовок", "реклама", "людей"],
        extraRuTokens: ["заголовок", "реклама", "людей"],
        extraEnTokens: ["headline", "advertising", "people"],
    },

    [phraseKey("reklama", "b1-22")]: {
        sk: "Dobra reklama może przyciągnąć klientów, ale nie powinna wprowadzać w błąd.",
        ua: "Хороша реклама може привернути клієнтів, але не повинна вводити в оману.",
        ru: "Хорошая реклама может привлечь клиентов, но не должна вводить в заблуждение.",
        en: "Good advertising can attract customers, but it should not mislead them.",
        uaTokens: ["Хороша", "реклама", "може", "привернути", "клієнтів", ",", "але", "не", "повинна", "вводити", "в", "оману", "."],
        ruTokens: ["Хорошая", "реклама", "может", "привлечь", "клиентов", ",", "но", "не", "должна", "вводить", "в", "заблуждение", "."],
        enTokens: ["Good", "advertising", "can", "attract", "customers", ",", "but", "it", "should", "not", "mislead", "them", "."],
        extraUaTokens: ["газету", "програми", "медіа"],
        extraRuTokens: ["газету", "программы", "медиа"],
        extraEnTokens: ["newspaper", "program", "media"],
    },

    [phraseKey("redaktor", "b1-22")]: {
        sk: "Redaktor poprawił tekst, zanim artykuł został opublikowany.",
        ua: "Редактор виправив текст, перш ніж статтю опублікували.",
        ru: "Редактор исправил текст, прежде чем статью опубликовали.",
        en: "The editor corrected the text before the article was published.",
        uaTokens: ["Редактор", "виправив", "текст", ",", "перш", "ніж", "статтю", "опублікували", "."],
        ruTokens: ["Редактор", "исправил", "текст", ",", "прежде", "чем", "статью", "опубликовали", "."],
        enTokens: ["The", "editor", "corrected", "the", "text", "before", "the", "article", "was", "published", "."],
        extraUaTokens: ["заголовок", "клієнтів", "політиків"],
        extraRuTokens: ["заголовок", "клиентов", "политиков"],
        extraEnTokens: ["headline", "customers", "politicians"],
    },

    [phraseKey("nagłówek", "b1-22")]: {
        sk: "Nagłówek był tak ciekawy, że od razu przeczytałem cały artykuł.",
        ua: "Заголовок був настільки цікавий, що я одразу прочитав усю статтю.",
        ru: "Заголовок был настолько интересным, что я сразу прочитал всю статью.",
        en: "The headline was so interesting that I immediately read the whole article.",
        uaTokens: ["Заголовок", "був", "настільки", "цікавий", ",", "що", "я", "одразу", "прочитав", "усю", "статтю", "."],
        ruTokens: ["Заголовок", "был", "настолько", "интересным", ",", "что", "я", "сразу", "прочитал", "всю", "статью", "."],
        enTokens: ["The", "headline", "was", "so", "interesting", "that", "I", "immediately", "read", "the", "whole", "article", "."],
        extraUaTokens: ["реклама", "читачів", "трансляція"],
        extraRuTokens: ["реклама", "аудиторию", "трансляция"],
        extraEnTokens: ["advertising", "audience", "broadcast"],
    },

    [phraseKey("uwierzyć", "b1-22")]: {
        sk: "Nie warto od razu uwierzyć we wszystko, co pojawia się w mediach.",
        ua: "Не варто одразу вірити в усе, що з’являється в медіа.",
        ru: "Не стоит сразу верить всему, что появляется в медиа.",
        en: "It is not worth believing everything that appears in the media right away.",
        uaTokens: ["Не", "варто", "одразу", "вірити", "в", "усе", ",", "що", "з’являється", "в", "медіа", "."],
        ruTokens: ["Не", "стоит", "сразу", "верить", "всему", ",", "что", "появляется", "в", "медиа", "."],
        enTokens: ["It", "is", "not", "worth", "believing", "everything", "that", "appears", "in", "the", "media", "right", "away", "."],
        extraUaTokens: ["заголовок", "редактор", "думка"],
        extraRuTokens: ["заголовок", "редактор", "мнение"],
        extraEnTokens: ["headline", "editor", "opinion"],
    },

    [phraseKey("idea publiczna", "b1-22")]: {
        sk: "Idea publiczna może wpływać na decyzje polityków i działania mediów.",
        ua: "Громадська думка може впливати на рішення політиків і дії медіа.",
        ru: "Общественное мнение может влиять на решения политиков и действия медиа.",
        en: "Public opinion can influence politicians' decisions and the actions of the media.",
        uaTokens: ["Громадська", "думка", "може", "впливати", "на", "рішення", "політиків", "і", "дії", "медіа", "."],
        ruTokens: ["Общественное", "мнение", "может", "влиять", "на", "решения", "политиков", "и", "действия", "медиа", "."],
        enTokens: ["Public", "opinion", "can", "influence", "politicians'", "decisions", "and", "the", "actions", "of", "the", "media", "."],
        extraUaTokens: ["вірити", "статтю", "читачів"],
        extraRuTokens: ["верить", "статью", "аудиторию"],
        extraEnTokens: ["believe", "article", "audience"],
    },

    // =========================
    // LESSON 23 — Інтернет та соцмережі
    // =========================
    [phraseKey("strona internetowa", "b1-23")]: {
        sk: "Ta strona internetowa działa bardzo szybko i jest łatwa w obsłudze.",
        ua: "Цей вебсайт працює дуже швидко і ним легко користуватися.",
        ru: "Этот веб-сайт работает очень быстро и им легко пользоваться.",
        en: "This website works very fast and is easy to use.",
        uaTokens: ["Цей", "вебсайт", "працює", "дуже", "швидко", "і", "ним", "легко", "користуватися", "."],
        ruTokens: ["Этот", "веб-сайт", "работает", "очень", "быстро", "и", "им", "легко", "пользоваться", "."],
        enTokens: ["This", "website", "works", "very", "fast", "and", "is", "easy", "to", "use", "."],
        extraUaTokens: ["профіль", "контент", "коментар"],
        extraRuTokens: ["профиль", "контент", "комментарий"],
        extraEnTokens: ["profile", "content", "comment"],
    },

    [phraseKey("obserwujący", "b1-23")]: {
        sk: "Mam coraz więcej obserwujących, ponieważ regularnie publikuję ciekawe treści.",
        ua: "У мене дедалі більше підписників, бо я регулярно публікую цікавий контент.",
        ru: "У меня всё больше подписчиков, потому что я регулярно публикую интересный контент.",
        en: "I have more and more followers because I regularly publish interesting content.",
        uaTokens: ["У", "мене", "дедалі", "більше", "підписників", ",", "бо", "я", "регулярно", "публікую", "цікавий", "контент", "."],
        ruTokens: ["У", "меня", "всё", "больше", "подписчиков", ",", "потому", "что", "я", "регулярно", "публикую", "интересный", "контент", "."],
        enTokens: ["I", "have", "more", "and", "more", "followers", "because", "I", "regularly", "publish", "interesting", "content", "."],
        extraUaTokens: ["вебсайт", "офіс", "сповіщення"],
        extraRuTokens: ["веб-сайт", "офис", "уведомление"],
        extraEnTokens: ["website", "office", "notification"],
    },

    [phraseKey("online", "b1-23")]: {
        sk: "Pracuję dziś online, dlatego nie muszę jechać do biura.",
        ua: "Сьогодні я працюю онлайн, тому не мушу їхати в офіс.",
        ru: "Сегодня я работаю онлайн, поэтому мне не нужно ехать в офис.",
        en: "I am working online today, so I don't have to go to the office.",
        uaTokens: ["Сьогодні", "я", "працюю", "онлайн", ",", "тому", "не", "мушу", "їхати", "в", "офіс", "."],
        ruTokens: ["Сегодня", "я", "работаю", "онлайн", ",", "поэтому", "мне", "не", "нужно", "ехать", "в", "офис", "."],
        enTokens: ["I", "am", "working", "online", "today", ",", "so", "I", "don't", "have", "to", "go", "to", "the", "office", "."],
        extraUaTokens: ["офлайн", "профіль", "контент"],
        extraRuTokens: ["офлайн", "профиль", "контент"],
        extraEnTokens: ["offline", "profile", "content"],
    },

    [phraseKey("offline", "b1-23")]: {
        sk: "W weekend wolę być offline, żeby naprawdę odpocząć.",
        ua: "На вихідних я волію бути офлайн, щоб справді відпочити.",
        ru: "На выходных я предпочитаю быть офлайн, чтобы действительно отдохнуть.",
        en: "At weekends I prefer to be offline to really rest.",
        uaTokens: ["На", "вихідних", "я", "волію", "бути", "офлайн", ",", "щоб", "справді", "відпочити", "."],
        ruTokens: ["На", "выходных", "я", "предпочитаю", "быть", "офлайн", ",", "чтобы", "действительно", "отдохнуть", "."],
        enTokens: ["At", "weekends", "I", "prefer", "to", "be", "offline", "to", "really", "rest", "."],
        extraUaTokens: ["онлайн", "офіс", "повідомлення"],
        extraRuTokens: ["онлайн", "офис", "сообщение"],
        extraEnTokens: ["online", "office", "message"],
    },

    [phraseKey("profil", "b1-23")]: {
        sk: "Muszę zaktualizować profil, ponieważ niektóre informacje są już nieaktualne.",
        ua: "Мені потрібно оновити профіль, бо деякі дані вже неактуальні.",
        ru: "Мне нужно обновить профиль, потому что некоторые данные уже неактуальны.",
        en: "I need to update my profile because some information is already outdated.",
        uaTokens: ["Мені", "потрібно", "оновити", "профіль", ",", "бо", "деякі", "дані", "вже", "неактуальні", "."],
        ruTokens: ["Мне", "нужно", "обновить", "профиль", ",", "потому", "что", "некоторые", "данные", "уже", "неактуальны", "."],
        enTokens: ["I", "need", "to", "update", "my", "profile", "because", "some", "information", "is", "already", "outdated", "."],
        extraUaTokens: ["вебсайт", "контент", "сповіщення"],
        extraRuTokens: ["веб-сайт", "контент", "уведомление"],
        extraEnTokens: ["website", "content", "notification"],
    },

    [phraseKey("komentować", "b1-23")]: {
        sk: "Nie lubię komentować wszystkiego w internecie, bo wolę najpierw się zastanowić.",
        ua: "Я не люблю все коментувати в інтернеті, бо спершу волію подумати.",
        ru: "Я не люблю всё комментировать в интернете, потому что сначала предпочитаю подумать.",
        en: "I don't like commenting on everything online because I prefer to think first.",
        uaTokens: ["Я", "не", "люблю", "все", "коментувати", "в", "інтернеті", ",", "бо", "спершу", "волію", "подумати", "."],
        ruTokens: ["Я", "не", "люблю", "всё", "комментировать", "в", "интернете", ",", "потому", "что", "сначала", "предпочитаю", "подумать", "."],
        enTokens: ["I", "don't", "like", "commenting", "on", "everything", "online", "because", "I", "prefer", "to", "think", "first", "."],
        extraUaTokens: ["позначити", "контент", "профіль"],
        extraRuTokens: ["отметить", "контент", "профиль"],
        extraEnTokens: ["tag", "content", "profile"],
    },

    [phraseKey("oznaczyć", "b1-23")]: {
        sk: "Możesz mnie oznaczyć na zdjęciu, jeśli chcesz.",
        ua: "Можеш мене позначити на фото, якщо хочеш.",
        ru: "Можешь отметить меня на фото, если хочешь.",
        en: "You can tag me in the photo if you want.",
        uaTokens: ["Можеш", "мене", "позначити", "на", "фото", ",", "якщо", "хочеш", "."],
        ruTokens: ["Можешь", "отметить", "меня", "на", "фото", ",", "если", "хочешь", "."],
        enTokens: ["You", "can", "tag", "me", "in", "the", "photo", "if", "you", "want", "."],
        extraUaTokens: ["коментар", "профіль", "контент"],
        extraRuTokens: ["комментарий", "профиль", "контент"],
        extraEnTokens: ["comment", "profile", "content"],
    },

    [phraseKey("dzielić się", "b1-23")]: {
        sk: "Warto dzielić się ważnymi informacjami, ale tylko z zaufanych źródeł.",
        ua: "Варто ділитися важливою інформацією, але лише з надійних джерел.",
        ru: "Стоит делиться важной информацией, но только из надёжных источников.",
        en: "It is worth sharing important information, but only from trusted sources.",
        uaTokens: ["Варто", "ділитися", "важливою", "інформацією", ",", "але", "лише", "з", "надійних", "джерел", "."],
        ruTokens: ["Стоит", "делиться", "важной", "информацией", ",", "но", "только", "из", "надёжных", "источников", "."],
        enTokens: ["It", "is", "worth", "sharing", "important", "information", ",", "but", "only", "from", "trusted", "sources", "."],
        extraUaTokens: ["коментувати", "сповіщення", "вебсайт"],
        extraRuTokens: ["комментировать", "уведомление", "веб-сайт"],
        extraEnTokens: ["commenting", "notification", "website"],
    },

    [phraseKey("wiadomość", "b1-23")]: {
        sk: "Wysłałem ci wiadomość rano, ale chyba jej nie zauważyłeś.",
        ua: "Я надіслав тобі повідомлення зранку, але ти, мабуть, його не помітив.",
        ru: "Я отправил тебе сообщение утром, но ты, кажется, его не заметил.",
        en: "I sent you a message in the morning, but you probably didn't notice it.",
        uaTokens: ["Я", "надіслав", "тобі", "повідомлення", "зранку", ",", "але", "ти", ",", "мабуть", ",", "його", "не", "помітив", "."],
        ruTokens: ["Я", "отправил", "тебе", "сообщение", "утром", ",", "но", "ты", ",", "кажется", ",", "его", "не", "заметил", "."],
        enTokens: ["I", "sent", "you", "a", "message", "in", "the", "morning", ",", "but", "you", "probably", "didn't", "notice", "it", "."],
        extraUaTokens: ["сповіщення", "коментар", "офлайн"],
        extraRuTokens: ["уведомление", "комментарий", "офлайн"],
        extraEnTokens: ["notification", "comment", "offline"],
    },

    [phraseKey("powiadomienie", "b1-23")]: {
        sk: "Dostałem powiadomienie, że ktoś odpowiedział na mój komentarz.",
        ua: "Я отримав сповіщення, що хтось відповів на мій коментар.",
        ru: "Я получил уведомление, что кто-то ответил на мой комментарий.",
        en: "I got a notification that someone replied to my comment.",
        uaTokens: ["Я", "отримав", "сповіщення", ",", "що", "хтось", "відповів", "на", "мій", "коментар", "."],
        ruTokens: ["Я", "получил", "уведомление", ",", "что", "кто-то", "ответил", "на", "мой", "комментарий", "."],
        enTokens: ["I", "got", "a", "notification", "that", "someone", "replied", "to", "my", "comment", "."],
        extraUaTokens: ["повідомлення", "профіль", "позначити"],
        extraRuTokens: ["сообщение", "профиль", "отметить"],
        extraEnTokens: ["message", "profile", "tag"],
    },

    // =========================
    // LESSON 24 — У гостях
    // =========================
    [phraseKey("zaproszenie", "b1-24")]: {
        sk: "Dziękuję za zaproszenie, chętnie przyjdę na twoje przyjęcie.",
        ua: "Дякую за запрошення, я із задоволенням прийду на твоє свято.",
        ru: "Спасибо за приглашение, я с удовольствием приду на твою вечеринку.",
        en: "Thank you for the invitation, I will gladly come to your party.",
        uaTokens: ["Дякую", "за", "запрошення", ",", "я", "із", "задоволенням", "прийду", "на", "твоє", "свято", "."],
        ruTokens: ["Спасибо", "за", "приглашение", ",", "я", "с", "удовольствием", "приду", "на", "твою", "вечеринку", "."],
        enTokens: ["Thank", "you", "for", "the", "invitation", ",", "I", "will", "gladly", "come", "to", "your", "party", "."],
        extraUaTokens: ["гостей", "гостинність", "торт"],
        extraRuTokens: ["гостей", "гостеприимство", "торт"],
        extraEnTokens: ["guests", "hospitality", "cake"],
    },

    [phraseKey("gospodarz", "b1-24")]: {
        sk: "Gospodarz powitał wszystkich gości z uśmiechem.",
        ua: "Господар привітав усіх гостей з усмішкою.",
        ru: "Хозяин приветствовал всех гостей с улыбкой.",
        en: "The host welcomed all the guests with a smile.",
        uaTokens: ["Господар", "привітав", "усіх", "гостей", "з", "усмішкою", "."],
        ruTokens: ["Хозяин", "приветствовал", "всех", "гостей", "с", "улыбкой", "."],
        enTokens: ["The", "host", "welcomed", "all", "the", "guests", "with", "a", "smile", "."],
        extraUaTokens: ["запрошення", "подарунок", "гостинність"],
        extraRuTokens: ["приглашение", "подарок", "гостеприимство"],
        extraEnTokens: ["invitation", "gift", "hospitality"],
    },

    [phraseKey("gość", "b1-24")]: {
        sk: "Każdy gość powinien zachowywać się uprzejmie i z szacunkiem.",
        ua: "Кожен гість повинен поводитися ввічливо і з повагою.",
        ru: "Каждый гость должен вести себя вежливо и с уважением.",
        en: "Every guest should behave politely and respectfully.",
        uaTokens: ["Кожен", "гість", "повинен", "поводитися", "ввічливо", "і", "з", "повагою", "."],
        ruTokens: ["Каждый", "гость", "должен", "вести", "себя", "вежливо", "и", "с", "уважением", "."],
        enTokens: ["Every", "guest", "should", "behave", "politely", "and", "respectfully", "."],
        extraUaTokens: ["господар", "запрошення", "каву"],
        extraRuTokens: ["хозяин", "приглашение", "кофе"],
        extraEnTokens: ["host", "invitation", "coffee"],
    },

    [phraseKey("poczęstunek", "b1-24")]: {
        sk: "Poczęstunek był bardzo smaczny, dlatego wszyscy byli zadowoleni.",
        ua: "Частування було дуже смачним, тому всі були задоволені.",
        ru: "Угощение было очень вкусным, поэтому все были довольны.",
        en: "The refreshments were very tasty, so everyone was satisfied.",
        uaTokens: ["Частування", "було", "дуже", "смачним", ",", "тому", "всі", "були", "задоволені", "."],
        ruTokens: ["Угощение", "было", "очень", "вкусным", ",", "поэтому", "все", "были", "довольны", "."],
        enTokens: ["The", "refreshments", "were", "very", "tasty", ",", "so", "everyone", "was", "satisfied", "."],
        extraUaTokens: ["торт", "гостей", "усмішкою"],
        extraRuTokens: ["торт", "гостей", "улыбкой"],
        extraEnTokens: ["cake", "guests", "smile"],
    },

    [phraseKey("przynieść prezent", "b1-24")]: {
        sk: "Wypada przynieść prezent, kiedy idzie się do kogoś w gości.",
        ua: "Прийнято приносити подарунок, коли йдеш до когось у гості.",
        ru: "Принято приносить подарок, когда идёшь к кому-то в гости.",
        en: "It is appropriate to bring a gift when visiting someone.",
        uaTokens: ["Прийнято", "приносити", "подарунок", ",", "коли", "йдеш", "до", "когось", "у", "гості", "."],
        ruTokens: ["Принято", "приносить", "подарок", ",", "когда", "идёшь", "к", "кому-то", "в", "гости", "."],
        enTokens: ["It", "is", "appropriate", "to", "bring", "a", "gift", "when", "visiting", "someone", "."],
        extraUaTokens: ["запрошення", "гостинність", "каву"],
        extraRuTokens: ["приглашение", "гостеприимство", "кофе"],
        extraEnTokens: ["invitation", "hospitality", "coffee"],
    },

    [phraseKey("uprzejmość", "b1-24")]: {
        sk: "Uprzejmość w takich sytuacjach jest bardzo ważna.",
        ua: "Ввічливість у таких ситуаціях дуже важлива.",
        ru: "Вежливость в таких ситуациях очень важна.",
        en: "Politeness is very important in such situations.",
        uaTokens: ["Ввічливість", "у", "таких", "ситуаціях", "дуже", "важлива", "."],
        ruTokens: ["Вежливость", "в", "таких", "ситуациях", "очень", "важна", "."],
        enTokens: ["Politeness", "is", "very", "important", "in", "such", "situations", "."],
        extraUaTokens: ["гість", "подарунок", "усмішкою"],
        extraRuTokens: ["гость", "подарок", "улыбкой"],
        extraEnTokens: ["guest", "gift", "smile"],
    },

    [phraseKey("powitać", "b1-24")]: {
        sk: "Wyszedłem do drzwi, żeby powitać gości osobiście.",
        ua: "Я вийшов до дверей, щоб особисто привітати гостей.",
        ru: "Я вышел к двери, чтобы лично поприветствовать гостей.",
        en: "I went to the door to welcome the guests personally.",
        uaTokens: ["Я", "вийшов", "до", "дверей", ",", "щоб", "особисто", "привітати", "гостей", "."],
        ruTokens: ["Я", "вышел", "к", "двери", ",", "чтобы", "лично", "поприветствовать", "гостей", "."],
        enTokens: ["I", "went", "to", "the", "door", "to", "welcome", "the", "guests", "personally", "."],
        extraUaTokens: ["господар", "подарунок", "гостинність"],
        extraRuTokens: ["хозяин", "подарок", "гостеприимство"],
        extraEnTokens: ["host", "gift", "hospitality"],
    },

    [phraseKey("zaoferować", "b1-24")]: {
        sk: "Gospodyni od razu zaoferowała nam kawę i ciasto.",
        ua: "Господиня одразу запропонувала нам каву і торт.",
        ru: "Хозяйка сразу предложила нам кофе и торт.",
        en: "The hostess immediately offered us coffee and cake.",
        uaTokens: ["Господиня", "одразу", "запропонувала", "нам", "каву", "і", "торт", "."],
        ruTokens: ["Хозяйка", "сразу", "предложила", "нам", "кофе", "и", "торт", "."],
        enTokens: ["The", "hostess", "immediately", "offered", "us", "coffee", "and", "cake", "."],
        extraUaTokens: ["гостей", "запрошення", "гостинність"],
        extraRuTokens: ["гостей", "приглашение", "гостеприимство"],
        extraEnTokens: ["guests", "invitation", "hospitality"],
    },

    [phraseKey("podziękować", "b1-24")]: {
        sk: "Po spotkaniu zadzwoniłem, żeby jeszcze raz podziękować za gościnność.",
        ua: "Після зустрічі я зателефонував, щоб ще раз подякувати за гостинність.",
        ru: "После встречи я позвонил, чтобы ещё раз поблагодарить за гостеприимство.",
        en: "After the meeting, I called to thank them again for their hospitality.",
        uaTokens: ["Після", "зустрічі", "я", "зателефонував", ",", "щоб", "ще", "раз", "подякувати", "за", "гостинність", "."],
        ruTokens: ["После", "встречи", "я", "позвонил", ",", "чтобы", "ещё", "раз", "поблагодарить", "за", "гостеприимство", "."],
        enTokens: ["After", "the", "meeting", ",", "I", "called", "to", "thank", "them", "again", "for", "their", "hospitality", "."],
        extraUaTokens: ["господар", "гостей", "торт"],
        extraRuTokens: ["хозяин", "гостей", "торт"],
        extraEnTokens: ["host", "guests", "cake"],
    },

    [phraseKey("pożegnać się", "b1-24")]: {
        sk: "Musieliśmy pożegnać się wcześniej, ponieważ rano mieliśmy pracę.",
        ua: "Нам довелося попрощатися раніше, бо зранку ми мали роботу.",
        ru: "Нам пришлось попрощаться раньше, потому что утром у нас была работа.",
        en: "We had to say goodbye earlier because we had work in the morning.",
        uaTokens: ["Нам", "довелося", "попрощатися", "раніше", ",", "бо", "зранку", "ми", "мали", "роботу", "."],
        ruTokens: ["Нам", "пришлось", "попрощаться", "раньше", ",", "потому", "что", "утром", "у", "нас", "была", "работа", "."],
        enTokens: ["We", "had", "to", "say", "goodbye", "earlier", "because", "we", "had", "work", "in", "the", "morning", "."],
        extraUaTokens: ["гостинність", "запрошення", "торт"],
        extraRuTokens: ["гостеприимство", "приглашение", "торт"],
        extraEnTokens: ["hospitality", "invitation", "cake"],
    },

    // =========================
    // LESSON 25 — Емоції та внутрішній стан
    // =========================
    [phraseKey("rozczarowanie", "b1-25")]: {
        sk: "Poczułem duże rozczarowanie, kiedy dowiedziałem się o wyniku.",
        ua: "Я відчув велике розчарування, коли дізнався про результат.",
        ru: "Я почувствовал большое разочарование, когда узнал о результате.",
        en: "I felt great disappointment when I found out about the result.",
        uaTokens: ["Я", "відчув", "велике", "розчарування", ",", "коли", "дізнався", "про", "результат", "."],
        ruTokens: ["Я", "почувствовал", "большое", "разочарование", ",", "когда", "узнал", "о", "результате", "."],
        enTokens: ["I", "felt", "great", "disappointment", "when", "I", "found", "out", "about", "the", "result", "."],
        extraUaTokens: ["гордість", "полегшення", "рішення"],
        extraRuTokens: ["гордость", "облегчение", "решение"],
        extraEnTokens: ["pride", "relief", "decision"],
    },

    [phraseKey("duma", "b1-25")]: {
        sk: "Czułem dumę, ponieważ udało mi się osiągnąć ważny cel.",
        ua: "Я відчував гордість, бо мені вдалося досягти важливої мети.",
        ru: "Я чувствовал гордость, потому что мне удалось достичь важной цели.",
        en: "I felt pride because I managed to achieve an important goal.",
        uaTokens: ["Я", "відчував", "гордість", ",", "бо", "мені", "вдалося", "досягти", "важливої", "мети", "."],
        ruTokens: ["Я", "чувствовал", "гордость", ",", "потому", "что", "мне", "удалось", "достичь", "важной", "цели", "."],
        enTokens: ["I", "felt", "pride", "because", "I", "managed", "to", "achieve", "an", "important", "goal", "."],
        extraUaTokens: ["розчарування", "сумніви", "безсилля"],
        extraRuTokens: ["разочарование", "сомнения", "бессилие"],
        extraEnTokens: ["disappointment", "doubts", "helplessness"],
    },

    [phraseKey("ulga", "b1-25")]: {
        sk: "Poczułem ulgę, gdy usłyszałem, że wszystko będzie dobrze.",
        ua: "Я відчув полегшення, коли почув, що все буде добре.",
        ru: "Я почувствовал облегчение, когда услышал, что всё будет хорошо.",
        en: "I felt relief when I heard that everything would be fine.",
        uaTokens: ["Я", "відчув", "полегшення", ",", "коли", "почув", ",", "що", "все", "буде", "добре", "."],
        ruTokens: ["Я", "почувствовал", "облегчение", ",", "когда", "услышал", ",", "что", "всё", "будет", "хорошо", "."],
        enTokens: ["I", "felt", "relief", "when", "I", "heard", "that", "everything", "would", "be", "fine", "."],
        extraUaTokens: ["розчарування", "сумніви", "результат"],
        extraRuTokens: ["разочарование", "сомнения", "результат"],
        extraEnTokens: ["disappointment", "doubts", "result"],
    },

    [phraseKey("niepewność", "b1-25")]: {
        sk: "Na początku czułem niepewność, ale z czasem nabrałem odwagi.",
        ua: "Спочатку я відчував невпевненість, але з часом набрався сміливості.",
        ru: "Сначала я чувствовал неуверенность, но со временем набрался смелости.",
        en: "At first I felt uncertainty, but over time I gained courage.",
        uaTokens: ["Спочатку", "я", "відчував", "невпевненість", ",", "але", "з", "часом", "набрався", "сміливості", "."],
        ruTokens: ["Сначала", "я", "чувствовал", "неуверенность", ",", "но", "со", "временем", "набрался", "смелости", "."],
        enTokens: ["At", "first", "I", "felt", "uncertainty", ",", "but", "over", "time", "I", "gained", "courage", "."],
        extraUaTokens: ["гордість", "безсилля", "рішення"],
        extraRuTokens: ["гордость", "бессилие", "решение"],
        extraEnTokens: ["pride", "helplessness", "decision"],
    },

    [phraseKey("frustracja", "b1-25")]: {
        sk: "Frustracja rosła, ponieważ mimo wysiłku nic się nie zmieniało.",
        ua: "Фрустрація зростала, бо попри зусилля нічого не змінювалося.",
        ru: "Фрустрация росла, потому что несмотря на усилия ничего не менялось.",
        en: "Frustration was growing because despite the effort nothing was changing.",
        uaTokens: ["Фрустрація", "зростала", ",", "бо", "попри", "зусилля", "нічого", "не", "змінювалося", "."],
        ruTokens: ["Фрустрация", "росла", ",", "потому", "что", "несмотря", "на", "усилия", "ничего", "не", "менялось", "."],
        enTokens: ["Frustration", "was", "growing", "because", "despite", "the", "effort", "nothing", "was", "changing", "."],
        extraUaTokens: ["сумніви", "полегшення", "сміливості"],
        extraRuTokens: ["сомнения", "облегчение", "смелости"],
        extraEnTokens: ["doubts", "relief", "courage"],
    },

    [phraseKey("wątpliwość", "b1-25")]: {
        sk: "Miałem wątpliwości, czy to na pewno była dobra decyzja.",
        ua: "Я мав сумніви, чи це точно було правильне рішення.",
        ru: "У меня были сомнения, было ли это действительно хорошим решением.",
        en: "I had doubts whether it was really a good decision.",
        uaTokens: ["Я", "мав", "сумніви", ",", "чи", "це", "точно", "було", "правильне", "рішення", "."],
        ruTokens: ["У", "меня", "были", "сомнения", ",", "было", "ли", "это", "действительно", "хорошим", "решением", "."],
        enTokens: ["I", "had", "doubts", "whether", "it", "was", "really", "a", "good", "decision", "."],
        extraUaTokens: ["розчарування", "гордість", "результат"],
        extraRuTokens: ["разочарование", "гордость", "результат"],
        extraEnTokens: ["disappointment", "pride", "result"],
    },

    [phraseKey("obawa", "b1-25")]: {
        sk: "Miałem obawy przed rozmową, chociaż dobrze się przygotowałem.",
        ua: "Я мав побоювання перед розмовою, хоча добре підготувався.",
        ru: "У меня были опасения перед разговором, хотя я хорошо подготовился.",
        en: "I had concerns before the conversation, although I prepared well.",
        uaTokens: ["Я", "мав", "побоювання", "перед", "розмовою", ",", "хоча", "добре", "підготувався", "."],
        ruTokens: ["У", "меня", "были", "опасения", "перед", "разговором", ",", "хотя", "я", "хорошо", "подготовился", "."],
        enTokens: ["I", "had", "concerns", "before", "the", "conversation", ",", "although", "I", "prepared", "well", "."],
        extraUaTokens: ["сумніви", "результат", "мети"],
        extraRuTokens: ["сомнения", "результат", "цели"],
        extraEnTokens: ["doubts", "result", "goal"],
    },

    [phraseKey("satysfakcja", "b1-25")]: {
        sk: "Największą satysfakcję daje mi praca, w której widzę sens.",
        ua: "Найбільше задоволення мені дає робота, в якій я бачу сенс.",
        ru: "Наибольшее удовлетворение мне даёт работа, в которой я вижу смысл.",
        en: "Work in which I see meaning gives me the greatest satisfaction.",
        uaTokens: ["Найбільше", "задоволення", "мені", "дає", "робота", ",", "в", "якій", "я", "бачу", "сенс", "."],
        ruTokens: ["Наибольшее", "удовлетворение", "мне", "даёт", "работа", ",", "в", "которой", "я", "вижу", "смысл", "."],
        enTokens: ["Work", "in", "which", "I", "see", "meaning", "gives", "me", "the", "greatest", "satisfaction", "."],
        extraUaTokens: ["безсилля", "зусилля", "розчарування"],
        extraRuTokens: ["бессилие", "усилия", "разочарование"],
        extraEnTokens: ["helplessness", "effort", "disappointment"],
    },

    [phraseKey("bezsilność", "b1-25")]: {
        sk: "Czasem czułem bezsilność, bo nie mogłem niczego zmienić.",
        ua: "Іноді я відчував безсилля, бо не міг нічого змінити.",
        ru: "Иногда я чувствовал бессилие, потому что не мог ничего изменить.",
        en: "Sometimes I felt helplessness because I could not change anything.",
        uaTokens: ["Іноді", "я", "відчував", "безсилля", ",", "бо", "не", "міг", "нічого", "змінити", "."],
        ruTokens: ["Иногда", "я", "чувствовал", "бессилие", ",", "потому", "что", "не", "мог", "ничего", "изменить", "."],
        enTokens: ["Sometimes", "I", "felt", "helplessness", "because", "I", "could", "not", "change", "anything", "."],
        extraUaTokens: ["гордість", "сумніви", "полегшення"],
        extraRuTokens: ["гордость", "сомнения", "облегчение"],
        extraEnTokens: ["pride", "doubts", "relief"],
    },

    [phraseKey("wyczerpanie", "b1-25")]: {
        sk: "Po kilku dniach bez odpoczynku odczuwałem silne wyczerpanie.",
        ua: "Після кількох днів без відпочинку я відчував сильне виснаження.",
        ru: "После нескольких дней без отдыха я ощущал сильное истощение.",
        en: "After a few days without rest, I felt strong exhaustion.",
        uaTokens: ["Після", "кількох", "днів", "без", "відпочинку", "я", "відчував", "сильне", "виснаження", "."],
        ruTokens: ["После", "нескольких", "дней", "без", "отдыха", "я", "ощущал", "сильное", "истощение", "."],
        enTokens: ["After", "a", "few", "days", "without", "rest", ",", "I", "felt", "strong", "exhaustion", "."],
        extraUaTokens: ["полегшення", "безсилля", "сміливості"],
        extraRuTokens: ["облегчение", "бессилие", "смелости"],
        extraEnTokens: ["relief", "helplessness", "courage"],
    },
};