import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_B1_BUILD_UA_SENTENCES_7: BuildUaSentenceDict = {
    // =========================
    // LESSON 31 — Країни (світ)
    // =========================
    [phraseKey("Stany Zjednoczone", "b1-31")]: {
        sk: "Stany Zjednoczone są jednym z najważniejszych krajów na świecie.",
        ua: "США є однією з найважливіших країн у світі.",
        ru: "США — одна из самых важных стран в мире.",
        en: "The United States is one of the most important countries in the world.",
        uaTokens: ["США", "є", "однією", "з", "найважливіших", "країн", "у", "світі", "."],
        ruTokens: ["США", "—", "одна", "из", "самых", "важных", "стран", "в", "мире", "."],
        enTokens: ["The", "United", "States", "is", "one", "of", "the", "most", "important", "countries", "in", "the", "world", "."],
        extraUaTokens: ["столиця", "історія", "Європа"],
        extraRuTokens: ["столица", "история", "Европа"],
        extraEnTokens: ["capital", "history", "Europe"],
    },

    [phraseKey("Wielka Brytania", "b1-31")]: {
        sk: "Wielka Brytania słynie z długiej historii i tradycji.",
        ua: "Велика Британія славиться довгою історією та традиціями.",
        ru: "Великобритания славится долгой историей и традициями.",
        en: "The United Kingdom is famous for its long history and traditions.",
        uaTokens: ["Велика", "Британія", "славиться", "довгою", "історією", "та", "традиціями", "."],
        ruTokens: ["Великобритания", "славится", "долгой", "историей", "и", "традициями", "."],
        enTokens: ["The", "United", "Kingdom", "is", "famous", "for", "its", "long", "history", "and", "traditions", "."],
        extraUaTokens: ["країна", "культура", "столиця"],
        extraRuTokens: ["страна", "культура", "столица"],
        extraEnTokens: ["country", "culture", "capital"],
    },

    [phraseKey("Kanada", "b1-31")]: {
        sk: "Kanada jest znana z pięknej przyrody i wysokiej jakości życia.",
        ua: "Канада відома красивою природою та високою якістю життя.",
        ru: "Канада известна красивой природой и высоким качеством жизни.",
        en: "Canada is known for beautiful nature and a high quality of life.",
        uaTokens: ["Канада", "відома", "красивою", "природою", "та", "високою", "якістю", "життя", "."],
        ruTokens: ["Канада", "известна", "красивой", "природой", "и", "высоким", "качеством", "жизни", "."],
        enTokens: ["Canada", "is", "known", "for", "beautiful", "nature", "and", "a", "high", "quality", "of", "life", "."],
        extraUaTokens: ["місто", "озеро", "гори"],
        extraRuTokens: ["город", "озеро", "горы"],
        extraEnTokens: ["city", "lake", "mountains"],
    },

    [phraseKey("Szwajcaria", "b1-31")]: {
        sk: "Szwajcaria kojarzy się wielu ludziom z bankami i górami.",
        ua: "Швейцарія асоціюється у багатьох людей з банками та горами.",
        ru: "Швейцария у многих ассоциируется с банками и горами.",
        en: "Switzerland is associated by many people with banks and mountains.",
        uaTokens: ["Швейцарія", "асоціюється", "у", "багатьох", "людей", "з", "банками", "та", "горами", "."],
        ruTokens: ["Швейцария", "у", "многих", "ассоциируется", "с", "банками", "и", "горами", "."],
        enTokens: ["Switzerland", "is", "associated", "by", "many", "people", "with", "banks", "and", "mountains", "."],
        extraUaTokens: ["країна", "природа", "місто"],
        extraRuTokens: ["страна", "природа", "город"],
        extraEnTokens: ["country", "nature", "city"],
    },

    [phraseKey("Holandia", "b1-31")]: {
        sk: "Holandia jest znana z rowerów, kanałów i tulipanów.",
        ua: "Нідерланди відомі велосипедами, каналами і тюльпанами.",
        ru: "Нидерланды известны велосипедами, каналами и тюльпанами.",
        en: "The Netherlands is known for bicycles, canals, and tulips.",
        uaTokens: ["Нідерланди", "відомі", "велосипедами", ",", "каналами", "і", "тюльпанами", "."],
        ruTokens: ["Нидерланды", "известны", "велосипедами", ",", "каналами", "и", "тюльпанами", "."],
        enTokens: ["The", "Netherlands", "is", "known", "for", "bicycles", ",", "canals", ",", "and", "tulips", "."],
        extraUaTokens: ["місто", "країна", "Європа"],
        extraRuTokens: ["город", "страна", "Европа"],
        extraEnTokens: ["city", "country", "Europe"],
    },

    [phraseKey("Belgia", "b1-31")]: {
        sk: "Belgia słynie z czekolady, frytek i siedzib europejskich instytucji.",
        ua: "Бельгія славиться шоколадом, картоплею фрі та штаб-квартирами європейських інституцій.",
        ru: "Бельгия славится шоколадом, картофелем фри и штаб-квартирами европейских институтов.",
        en: "Belgium is famous for chocolate, fries, and the headquarters of European institutions.",
        uaTokens: ["Бельгія", "славиться", "шоколадом", ",", "картоплею", "фрі", "та", "штаб-квартирами", "європейських", "інституцій", "."],
        ruTokens: ["Бельгия", "славится", "шоколадом", ",", "картофелем", "фри", "и", "штаб-квартирами", "европейских", "институтов", "."],
        enTokens: ["Belgium", "is", "famous", "for", "chocolate", ",", "fries", ",", "and", "the", "headquarters", "of", "European", "institutions", "."],
        extraUaTokens: ["місто", "країна", "культура"],
        extraRuTokens: ["город", "страна", "культура"],
        extraEnTokens: ["city", "country", "culture"],
    },

    [phraseKey("Szwecja", "b1-31")]: {
        sk: "Szwecja ma wysoki poziom życia i dobrze rozwinięty system socjalny.",
        ua: "Швеція має високий рівень життя і добре розвинену соціальну систему.",
        ru: "Швеция имеет высокий уровень жизни и хорошо развитую социальную систему.",
        en: "Sweden has a high standard of living and a well-developed social system.",
        uaTokens: ["Швеція", "має", "високий", "рівень", "життя", "і", "добре", "розвинену", "соціальну", "систему", "."],
        ruTokens: ["Швеция", "имеет", "высокий", "уровень", "жизни", "и", "хорошо", "развитую", "социальную", "систему", "."],
        enTokens: ["Sweden", "has", "a", "high", "standard", "of", "living", "and", "a", "well-developed", "social", "system", "."],
        extraUaTokens: ["суспільство", "країна", "північ"],
        extraRuTokens: ["общество", "страна", "север"],
        extraEnTokens: ["society", "country", "north"],
    },

    [phraseKey("Rosja", "b1-31")]: {
        sk: "Rosja jest największym krajem na świecie pod względem powierzchni.",
        ua: "Росія є найбільшою країною у світі за площею.",
        ru: "Россия — самая большая страна в мире по площади.",
        en: "Russia is the largest country in the world by area.",
        uaTokens: ["Росія", "є", "найбільшою", "країною", "у", "світі", "за", "площею", "."],
        ruTokens: ["Россия", "—", "самая", "большая", "страна", "в", "мире", "по", "площади", "."],
        enTokens: ["Russia", "is", "the", "largest", "country", "in", "the", "world", "by", "area", "."],
        extraUaTokens: ["кордон", "місто", "континент"],
        extraRuTokens: ["граница", "город", "континент"],
        extraEnTokens: ["border", "city", "continent"],
    },

    [phraseKey("Rumunia", "b1-31")]: {
        sk: "Rumunia ma bogatą kulturę i ciekawe tradycje regionalne.",
        ua: "Румунія має багату культуру та цікаві регіональні традиції.",
        ru: "Румыния имеет богатую культуру и интересные региональные традиции.",
        en: "Romania has a rich culture and interesting regional traditions.",
        uaTokens: ["Румунія", "має", "багату", "культуру", "та", "цікаві", "регіональні", "традиції", "."],
        ruTokens: ["Румыния", "имеет", "богатую", "культуру", "и", "интересные", "региональные", "традиции", "."],
        enTokens: ["Romania", "has", "a", "rich", "culture", "and", "interesting", "regional", "traditions", "."],
        extraUaTokens: ["країна", "історія", "столиця"],
        extraRuTokens: ["страна", "история", "столица"],
        extraEnTokens: ["country", "history", "capital"],
    },

    [phraseKey("Bułgaria", "b1-31")]: {
        sk: "Bułgaria jest popularnym kierunkiem wakacyjnym nad Morzem Czarnym.",
        ua: "Болгарія є популярним місцем відпочинку на Чорному морі.",
        ru: "Болгария — популярное место отдыха на Чёрном море.",
        en: "Bulgaria is a popular holiday destination on the Black Sea.",
        uaTokens: ["Болгарія", "є", "популярним", "місцем", "відпочинку", "на", "Чорному", "морі", "."],
        ruTokens: ["Болгария", "—", "популярное", "место", "отдыха", "на", "Чёрном", "море", "."],
        enTokens: ["Bulgaria", "is", "a", "popular", "holiday", "destination", "on", "the", "Black", "Sea", "."],
        extraUaTokens: ["літо", "море", "курорт"],
        extraRuTokens: ["лето", "море", "курорт"],
        extraEnTokens: ["summer", "sea", "resort"],
    },

    // =========================
    // LESSON 32 — Релігія (Християнство)
    // =========================
    [phraseKey("chrześcijaństwo", "b1-32")]: {
        sk: "Chrześcijaństwo jest jedną z największych religii na świecie.",
        ua: "Християнство є однією з найбільших релігій у світі.",
        ru: "Христианство — одна из крупнейших религий в мире.",
        en: "Christianity is one of the largest religions in the world.",
        uaTokens: ["Християнство", "є", "однією", "з", "найбільших", "релігій", "у", "світі", "."],
        ruTokens: ["Христианство", "—", "одна", "из", "крупнейших", "религий", "в", "мире", "."],
        enTokens: ["Christianity", "is", "one", "of", "the", "largest", "religions", "in", "the", "world", "."],
        extraUaTokens: ["церква", "віра", "Біблія"],
        extraRuTokens: ["церковь", "вера", "Библия"],
        extraEnTokens: ["church", "faith", "Bible"],
    },

    [phraseKey("Bóg", "b1-32")]: {
        sk: "Wielu ludzi wierzy, że Bóg prowadzi ich przez życie.",
        ua: "Багато людей вірять, що Бог веде їх через життя.",
        ru: "Многие люди верят, что Бог ведёт их по жизни.",
        en: "Many people believe that God guides them through life.",
        uaTokens: ["Багато", "людей", "вірять", ",", "що", "Бог", "веде", "їх", "через", "життя", "."],
        ruTokens: ["Многие", "люди", "верят", ",", "что", "Бог", "ведёт", "их", "по", "жизни", "."],
        enTokens: ["Many", "people", "believe", "that", "God", "guides", "them", "through", "life", "."],
        extraUaTokens: ["віра", "надія", "молитва"],
        extraRuTokens: ["вера", "надежда", "молитва"],
        extraEnTokens: ["faith", "hope", "prayer"],
    },

    [phraseKey("Jezus Chrystus", "b1-32")]: {
        sk: "Dla chrześcijan Jezus Chrystus jest centralną postacią wiary.",
        ua: "Для християн Ісус Христос є центральною постаттю віри.",
        ru: "Для христиан Иисус Христос — центральная фигура веры.",
        en: "For Christians, Jesus Christ is the central figure of faith.",
        uaTokens: ["Для", "християн", "Ісус", "Христос", "є", "центральною", "постаттю", "віри", "."],
        ruTokens: ["Для", "христиан", "Иисус", "Христос", "—", "центральная", "фигура", "веры", "."],
        enTokens: ["For", "Christians", ",", "Jesus", "Christ", "is", "the", "central", "figure", "of", "faith", "."],
        extraUaTokens: ["Біблія", "церква", "Бог"],
        extraRuTokens: ["Библия", "церковь", "Бог"],
        extraEnTokens: ["Bible", "church", "God"],
    },

    [phraseKey("Biblia", "b1-32")]: {
        sk: "Biblia jest dla wielu ludzi ważnym źródłem duchowej inspiracji.",
        ua: "Біблія є для багатьох людей важливим джерелом духовного натхнення.",
        ru: "Библия для многих людей является важным источником духовного вдохновения.",
        en: "The Bible is an important source of spiritual inspiration for many people.",
        uaTokens: ["Біблія", "є", "для", "багатьох", "людей", "важливим", "джерелом", "духовного", "натхнення", "."],
        ruTokens: ["Библия", "для", "многих", "людей", "является", "важным", "источником", "духовного", "вдохновения", "."],
        enTokens: ["The", "Bible", "is", "an", "important", "source", "of", "spiritual", "inspiration", "for", "many", "people", "."],
        extraUaTokens: ["віра", "церква", "молитва"],
        extraRuTokens: ["вера", "церковь", "молитва"],
        extraEnTokens: ["faith", "church", "prayer"],
    },

    [phraseKey("kościół", "b1-32")]: {
        sk: "W niedzielę wiele osób idzie do kościoła na mszę.",
        ua: "У неділю багато людей йдуть до церкви на месу.",
        ru: "В воскресенье многие люди идут в церковь на мессу.",
        en: "On Sunday, many people go to church for mass.",
        uaTokens: ["У", "неділю", "багато", "людей", "йдуть", "до", "церкви", "на", "месу", "."],
        ruTokens: ["В", "воскресенье", "многие", "люди", "идут", "в", "церковь", "на", "мессу", "."],
        enTokens: ["On", "Sunday", ",", "many", "people", "go", "to", "church", "for", "mass", "."],
        extraUaTokens: ["віра", "молитва", "свято"],
        extraRuTokens: ["вера", "молитва", "праздник"],
        extraEnTokens: ["faith", "prayer", "holiday"],
    },

    [phraseKey("modlitwa", "b1-32")]: {
        sk: "Dla niektórych modlitwa daje siłę i spokój wewnętrzny.",
        ua: "Для деяких молитва дає силу і внутрішній спокій.",
        ru: "Для некоторых молитва даёт силу и внутренний покой.",
        en: "For some people, prayer gives strength and inner peace.",
        uaTokens: ["Для", "деяких", "молитва", "дає", "силу", "і", "внутрішній", "спокій", "."],
        ruTokens: ["Для", "некоторых", "молитва", "даёт", "силу", "и", "внутренний", "покой", "."],
        enTokens: ["For", "some", "people", ",", "prayer", "gives", "strength", "and", "inner", "peace", "."],
        extraUaTokens: ["віра", "церква", "Бог"],
        extraRuTokens: ["вера", "церковь", "Бог"],
        extraEnTokens: ["faith", "church", "God"],
    },

    [phraseKey("wiara", "b1-32")]: {
        sk: "Wiara pomaga wielu ludziom przetrwać trudne chwile.",
        ua: "Віра допомагає багатьом людям пережити важкі моменти.",
        ru: "Вера помогает многим людям пережить трудные моменты.",
        en: "Faith helps many people get through difficult moments.",
        uaTokens: ["Віра", "допомагає", "багатьом", "людям", "пережити", "важкі", "моменти", "."],
        ruTokens: ["Вера", "помогает", "многим", "людям", "пережить", "трудные", "моменты", "."],
        enTokens: ["Faith", "helps", "many", "people", "get", "through", "difficult", "moments", "."],
        extraUaTokens: ["надія", "Бог", "молитва"],
        extraRuTokens: ["надежда", "Бог", "молитва"],
        extraEnTokens: ["hope", "God", "prayer"],
    },

    [phraseKey("grzech", "b1-32")]: {
        sk: "W chrześcijaństwie grzech oznacza odejście od dobra i prawdy.",
        ua: "У християнстві гріх означає відхід від добра і правди.",
        ru: "В христианстве грех означает отход от добра и истины.",
        en: "In Christianity, sin means turning away from goodness and truth.",
        uaTokens: ["У", "християнстві", "гріх", "означає", "відхід", "від", "добра", "і", "правди", "."],
        ruTokens: ["В", "христианстве", "грех", "означает", "отход", "от", "добра", "и", "истины", "."],
        enTokens: ["In", "Christianity", ",", "sin", "means", "turning", "away", "from", "goodness", "and", "truth", "."],
        extraUaTokens: ["прощення", "віра", "Біблія"],
        extraRuTokens: ["прощение", "вера", "Библия"],
        extraEnTokens: ["forgiveness", "faith", "Bible"],
    },

    [phraseKey("przebaczenie", "b1-32")]: {
        sk: "Przebaczenie bywa trudne, ale przynosi człowiekowi ulgę.",
        ua: "Прощення буває важким, але приносить людині полегшення.",
        ru: "Прощение бывает трудным, но приносит человеку облегчение.",
        en: "Forgiveness can be difficult, but it brings relief to a person.",
        uaTokens: ["Прощення", "буває", "важким", ",", "але", "приносить", "людині", "полегшення", "."],
        ruTokens: ["Прощение", "бывает", "трудным", ",", "но", "приносит", "человеку", "облегчение", "."],
        enTokens: ["Forgiveness", "can", "be", "difficult", ",", "but", "it", "brings", "relief", "to", "a", "person", "."],
        extraUaTokens: ["гріх", "віра", "любов"],
        extraRuTokens: ["грех", "вера", "любовь"],
        extraEnTokens: ["sin", "faith", "love"],
    },

    [phraseKey("życie wieczne", "b1-32")]: {
        sk: "Wierzący mają nadzieję na życie wieczne po śmierci.",
        ua: "Віруючі мають надію на вічне життя після смерті.",
        ru: "Верующие надеются на вечную жизнь после смерти.",
        en: "Believers hope for eternal life after death.",
        uaTokens: ["Віруючі", "мають", "надію", "на", "вічне", "життя", "після", "смерті", "."],
        ruTokens: ["Верующие", "надеются", "на", "вечную", "жизнь", "после", "смерти", "."],
        enTokens: ["Believers", "hope", "for", "eternal", "life", "after", "death", "."],
        extraUaTokens: ["віра", "Бог", "надія"],
        extraRuTokens: ["вера", "Бог", "надежда"],
        extraEnTokens: ["faith", "God", "hope"],
    },

    // =========================
    // LESSON 33 — Мова (спілкування і думки)
    // =========================
    [phraseKey("dialog", "b1-33")]: {
        sk: "Dobry dialog pomaga lepiej zrozumieć drugą osobę.",
        ua: "Хороший діалог допомагає краще зрозуміти іншу людину.",
        ru: "Хороший диалог помогает лучше понять другого человека.",
        en: "A good dialogue helps to understand the other person better.",
        uaTokens: ["Хороший", "діалог", "допомагає", "краще", "зрозуміти", "іншу", "людину", "."],
        ruTokens: ["Хороший", "диалог", "помогает", "лучше", "понять", "другого", "человека", "."],
        enTokens: ["A", "good", "dialogue", "helps", "to", "understand", "the", "other", "person", "better", "."],
        extraUaTokens: ["розмова", "думка", "слова"],
        extraRuTokens: ["разговор", "мнение", "слова"],
        extraEnTokens: ["conversation", "opinion", "words"],
    },

    [phraseKey("twierdzenie", "b1-33")]: {
        sk: "To twierdzenie brzmi logicznie, ale wymaga dowodów.",
        ua: "Це твердження звучить логічно, але потребує доказів.",
        ru: "Это утверждение звучит логично, но требует доказательств.",
        en: "This statement sounds logical, but it requires evidence.",
        uaTokens: ["Це", "твердження", "звучить", "логічно", ",", "але", "потребує", "доказів", "."],
        ruTokens: ["Это", "утверждение", "звучит", "логично", ",", "но", "требует", "доказательств", "."],
        enTokens: ["This", "statement", "sounds", "logical", ",", "but", "it", "requires", "evidence", "."],
        extraUaTokens: ["думка", "текст", "цитата"],
        extraRuTokens: ["мнение", "текст", "цитата"],
        extraEnTokens: ["opinion", "text", "quote"],
    },

    [phraseKey("akapit", "b1-33")]: {
        sk: "Każdy akapit powinien rozwijać jedną główną myśl.",
        ua: "Кожен абзац повинен розвивати одну головну думку.",
        ru: "Каждый абзац должен развивать одну главную мысль.",
        en: "Each paragraph should develop one main idea.",
        uaTokens: ["Кожен", "абзац", "повинен", "розвивати", "одну", "головну", "думку", "."],
        ruTokens: ["Каждый", "абзац", "должен", "развивать", "одну", "главную", "мысль", "."],
        enTokens: ["Each", "paragraph", "should", "develop", "one", "main", "idea", "."],
        extraUaTokens: ["текст", "заголовок", "цитата"],
        extraRuTokens: ["текст", "заголовок", "цитата"],
        extraEnTokens: ["text", "heading", "quote"],
    },

    [phraseKey("nagłówek", "b1-33")]: {
        sk: "Dobry nagłówek przyciąga uwagę czytelnika od razu.",
        ua: "Хороший заголовок одразу привертає увагу читача.",
        ru: "Хороший заголовок сразу привлекает внимание читателя.",
        en: "A good heading attracts the reader's attention immediately.",
        uaTokens: ["Хороший", "заголовок", "одразу", "привертає", "увагу", "читача", "."],
        ruTokens: ["Хороший", "заголовок", "сразу", "привлекает", "внимание", "читателя", "."],
        enTokens: ["A", "good", "heading", "attracts", "the", "reader's", "attention", "immediately", "."],
        extraUaTokens: ["текст", "абзац", "нотатка"],
        extraRuTokens: ["текст", "абзац", "заметка"],
        extraEnTokens: ["text", "paragraph", "note"],
    },

    [phraseKey("cytat", "b1-33")]: {
        sk: "Ten cytat dobrze oddaje sens całego tekstu.",
        ua: "Ця цитата добре передає зміст усього тексту.",
        ru: "Эта цитата хорошо передаёт смысл всего текста.",
        en: "This quote expresses the meaning of the whole text well.",
        uaTokens: ["Ця", "цитата", "добре", "передає", "зміст", "усього", "тексту", "."],
        ruTokens: ["Эта", "цитата", "хорошо", "передаёт", "смысл", "всего", "текста", "."],
        enTokens: ["This", "quote", "expresses", "the", "meaning", "of", "the", "whole", "text", "well", "."],
        extraUaTokens: ["думка", "слово", "речення"],
        extraRuTokens: ["мысль", "слово", "предложение"],
        extraEnTokens: ["idea", "word", "sentence"],
    },

    [phraseKey("notatka", "b1-33")]: {
        sk: "Zrobiłem krótką notatkę, żeby niczego nie zapomnieć.",
        ua: "Я зробив коротку примітку, щоб нічого не забути.",
        ru: "Я сделал короткую заметку, чтобы ничего не забыть.",
        en: "I made a short note so I wouldn't forget anything.",
        uaTokens: ["Я", "зробив", "коротку", "примітку", ",", "щоб", "нічого", "не", "забути", "."],
        ruTokens: ["Я", "сделал", "короткую", "заметку", ",", "чтобы", "ничего", "не", "забыть", "."],
        enTokens: ["I", "made", "a", "short", "note", "so", "I", "wouldn't", "forget", "anything", "."],
        extraUaTokens: ["зошит", "слово", "нагадування"],
        extraRuTokens: ["тетрадь", "слово", "напоминание"],
        extraEnTokens: ["notebook", "word", "reminder"],
    },

    [phraseKey("skrót", "b1-33")]: {
        sk: "Nie wszystkie skróty są zrozumiałe dla każdego odbiorcy.",
        ua: "Не всі скорочення зрозумілі для кожного читача.",
        ru: "Не все сокращения понятны каждому читателю.",
        en: "Not all abbreviations are understandable to every reader.",
        uaTokens: ["Не", "всі", "скорочення", "зрозумілі", "для", "кожного", "читача", "."],
        ruTokens: ["Не", "все", "сокращения", "понятны", "каждому", "читателю", "."],
        enTokens: ["Not", "all", "abbreviations", "are", "understandable", "to", "every", "reader", "."],
        extraUaTokens: ["слова", "текст", "речення"],
        extraRuTokens: ["слова", "текст", "предложение"],
        extraEnTokens: ["words", "text", "sentence"],
    },

    [phraseKey("ortografia", "b1-33")]: {
        sk: "Ortografia jest ważna, ponieważ błędy mogą zmienić sens zdania.",
        ua: "Правопис важливий, бо помилки можуть змінити зміст речення.",
        ru: "Правописание важно, потому что ошибки могут изменить смысл предложения.",
        en: "Spelling is important because mistakes can change the meaning of a sentence.",
        uaTokens: ["Правопис", "важливий", ",", "бо", "помилки", "можуть", "змінити", "зміст", "речення", "."],
        ruTokens: ["Правописание", "важно", ",", "потому", "что", "ошибки", "могут", "изменить", "смысл", "предложения", "."],
        enTokens: ["Spelling", "is", "important", "because", "mistakes", "can", "change", "the", "meaning", "of", "a", "sentence", "."],
        extraUaTokens: ["слово", "абзац", "цитата"],
        extraRuTokens: ["слово", "абзац", "цитата"],
        extraEnTokens: ["word", "paragraph", "quote"],
    },

    [phraseKey("połączyć słowa", "b1-33")]: {
        sk: "Trzeba umieć połączyć słowa w logiczne i poprawne zdanie.",
        ua: "Треба вміти поєднати слова в логічне і правильне речення.",
        ru: "Нужно уметь соединять слова в логичное и правильное предложение.",
        en: "You need to know how to connect words into a logical and correct sentence.",
        uaTokens: ["Треба", "вміти", "поєднати", "слова", "в", "логічне", "і", "правильне", "речення", "."],
        ruTokens: ["Нужно", "уметь", "соединять", "слова", "в", "логичное", "и", "правильное", "предложение", "."],
        enTokens: ["You", "need", "to", "know", "how", "to", "connect", "words", "into", "a", "logical", "and", "correct", "sentence", "."],
        extraUaTokens: ["думка", "текст", "правопис"],
        extraRuTokens: ["мысль", "текст", "правописание"],
        extraEnTokens: ["idea", "text", "spelling"],
    },

    [phraseKey("wymówić", "b1-33")]: {
        sk: "Niektóre polskie dźwięki trudno poprawnie wymówić.",
        ua: "Деякі польські звуки важко правильно вимовити.",
        ru: "Некоторые польские звуки трудно правильно произнести.",
        en: "Some Polish sounds are hard to pronounce correctly.",
        uaTokens: ["Деякі", "польські", "звуки", "важко", "правильно", "вимовити", "."],
        ruTokens: ["Некоторые", "польские", "звуки", "трудно", "правильно", "произнести", "."],
        enTokens: ["Some", "Polish", "sounds", "are", "hard", "to", "pronounce", "correctly", "."],
        extraUaTokens: ["слово", "літера", "мова"],
        extraRuTokens: ["слово", "буква", "язык"],
        extraEnTokens: ["word", "letter", "language"],
    },

    // =========================
    // LESSON 34 — Психологія та внутрішній стан
    // =========================
    [phraseKey("pewność siebie", "b1-34")]: {
        sk: "Pewność siebie pomaga człowiekowi podejmować trudne decyzje.",
        ua: "Впевненість у собі допомагає людині приймати складні рішення.",
        ru: "Уверенность в себе помогает человеку принимать трудные решения.",
        en: "Self-confidence helps a person make difficult decisions.",
        uaTokens: ["Впевненість", "у", "собі", "допомагає", "людині", "приймати", "складні", "рішення", "."],
        ruTokens: ["Уверенность", "в", "себе", "помогает", "человеку", "принимать", "трудные", "решения", "."],
        enTokens: ["Self-confidence", "helps", "a", "person", "make", "difficult", "decisions", "."],
        extraUaTokens: ["страх", "успіх", "мотивація"],
        extraRuTokens: ["страх", "успех", "мотивация"],
        extraEnTokens: ["fear", "success", "motivation"],
    },

    [phraseKey("motywacja", "b1-34")]: {
        sk: "Bez motywacji trudno regularnie pracować nad sobą.",
        ua: "Без мотивації важко регулярно працювати над собою.",
        ru: "Без мотивации трудно регулярно работать над собой.",
        en: "Without motivation, it is hard to work on yourself regularly.",
        uaTokens: ["Без", "мотивації", "важко", "регулярно", "працювати", "над", "собою", "."],
        ruTokens: ["Без", "мотивации", "трудно", "регулярно", "работать", "над", "собой", "."],
        enTokens: ["Without", "motivation", ",", "it", "is", "hard", "to", "work", "on", "yourself", "regularly", "."],
        extraUaTokens: ["мета", "саморозвиток", "сила"],
        extraRuTokens: ["цель", "саморазвитие", "сила"],
        extraEnTokens: ["goal", "self-development", "strength"],
    },

    [phraseKey("zdecydowanie", "b1-34")]: {
        sk: "Zdecydowanie pomaga działać szybko i bez zbędnych wahań.",
        ua: "Рішучість допомагає діяти швидко і без зайвих сумнівів.",
        ru: "Решительность помогает действовать быстро и без лишних сомнений.",
        en: "Determination helps you act quickly and without unnecessary hesitation.",
        uaTokens: ["Рішучість", "допомагає", "діяти", "швидко", "і", "без", "зайвих", "сумнівів", "."],
        ruTokens: ["Решительность", "помогает", "действовать", "быстро", "и", "без", "лишних", "сомнений", "."],
        enTokens: ["Determination", "helps", "you", "act", "quickly", "and", "without", "unnecessary", "hesitation", "."],
        extraUaTokens: ["страх", "вибір", "мета"],
        extraRuTokens: ["страх", "выбор", "цель"],
        extraEnTokens: ["fear", "choice", "goal"],
    },

    [phraseKey("rozczarować się", "b1-34")]: {
        sk: "Łatwo się rozczarować, gdy oczekiwania są zbyt wysokie.",
        ua: "Легко розчаруватися, коли очікування надто високі.",
        ru: "Легко разочароваться, когда ожидания слишком высоки.",
        en: "It is easy to become disappointed when expectations are too high.",
        uaTokens: ["Легко", "розчаруватися", ",", "коли", "очікування", "надто", "високі", "."],
        ruTokens: ["Легко", "разочароваться", ",", "когда", "ожидания", "слишком", "высоки", "."],
        enTokens: ["It", "is", "easy", "to", "become", "disappointed", "when", "expectations", "are", "too", "high", "."],
        extraUaTokens: ["надія", "страх", "успіх"],
        extraRuTokens: ["надежда", "страх", "успех"],
        extraEnTokens: ["hope", "fear", "success"],
    },

    [phraseKey("pokonać strach", "b1-34")]: {
        sk: "Żeby się rozwijać, trzeba najpierw pokonać strach przed porażką.",
        ua: "Щоб розвиватися, треба спочатку подолати страх перед поразкою.",
        ru: "Чтобы развиваться, нужно сначала преодолеть страх перед поражением.",
        en: "To grow, you first need to overcome the fear of failure.",
        uaTokens: ["Щоб", "розвиватися", ",", "треба", "спочатку", "подолати", "страх", "перед", "поразкою", "."],
        ruTokens: ["Чтобы", "развиваться", ",", "нужно", "сначала", "преодолеть", "страх", "перед", "поражением", "."],
        enTokens: ["To", "grow", ",", "you", "first", "need", "to", "overcome", "the", "fear", "of", "failure", "."],
        extraUaTokens: ["успіх", "мета", "сумніви"],
        extraRuTokens: ["успех", "цель", "сомнения"],
        extraEnTokens: ["success", "goal", "doubt"],
    },

    [phraseKey("samorozwój", "b1-34")]: {
        sk: "Samorozwój wymaga czasu, cierpliwości i systematyczności.",
        ua: "Саморозвиток вимагає часу, терпіння і систематичності.",
        ru: "Саморазвитие требует времени, терпения и систематичности.",
        en: "Self-development requires time, patience, and consistency.",
        uaTokens: ["Саморозвиток", "вимагає", "часу", ",", "терпіння", "і", "систематичності", "."],
        ruTokens: ["Саморазвитие", "требует", "времени", ",", "терпения", "и", "систематичности", "."],
        enTokens: ["Self-development", "requires", "time", ",", "patience", ",", "and", "consistency", "."],
        extraUaTokens: ["мотивація", "мета", "рішення"],
        extraRuTokens: ["мотивация", "цель", "решение"],
        extraEnTokens: ["motivation", "goal", "decision"],
    },

    [phraseKey("wewnętrzny spokój", "b1-34")]: {
        sk: "Wewnętrzny spokój pomaga zachować równowagę w trudnych chwilach.",
        ua: "Внутрішній спокій допомагає зберігати рівновагу у важкі моменти.",
        ru: "Внутреннее спокойствие помогает сохранять равновесие в трудные моменты.",
        en: "Inner peace helps maintain balance in difficult moments.",
        uaTokens: ["Внутрішній", "спокій", "допомагає", "зберігати", "рівновагу", "у", "важкі", "моменти", "."],
        ruTokens: ["Внутреннее", "спокойствие", "помогает", "сохранять", "равновесие", "в", "трудные", "моменты", "."],
        enTokens: ["Inner", "peace", "helps", "maintain", "balance", "in", "difficult", "moments", "."],
        extraUaTokens: ["молитва", "тиша", "сила"],
        extraRuTokens: ["молитва", "тишина", "сила"],
        extraEnTokens: ["prayer", "silence", "strength"],
    },

    [phraseKey("samodyscyplina", "b1-34")]: {
        sk: "Samodyscyplina jest potrzebna, żeby osiągać długoterminowe cele.",
        ua: "Самодисципліна потрібна, щоб досягати довгострокових цілей.",
        ru: "Самодисциплина нужна, чтобы достигать долгосрочных целей.",
        en: "Self-discipline is needed to achieve long-term goals.",
        uaTokens: ["Самодисципліна", "потрібна", ",", "щоб", "досягати", "довгострокових", "цілей", "."],
        ruTokens: ["Самодисциплина", "нужна", ",", "чтобы", "достигать", "долгосрочных", "целей", "."],
        enTokens: ["Self-discipline", "is", "needed", "to", "achieve", "long-term", "goals", "."],
        extraUaTokens: ["мета", "мотивація", "праця"],
        extraRuTokens: ["цель", "мотивация", "работа"],
        extraEnTokens: ["goal", "motivation", "work"],
    },

    [phraseKey("odporność", "b1-34")]: {
        sk: "Odporność psychiczna pomaga człowiekowi szybciej wracać do równowagi.",
        ua: "Психологічна стійкість допомагає людині швидше повертатися до рівноваги.",
        ru: "Психологическая устойчивость помогает человеку быстрее возвращаться к равновесию.",
        en: "Resilience helps a person return to balance more quickly.",
        uaTokens: ["Психологічна", "стійкість", "допомагає", "людині", "швидше", "повертатися", "до", "рівноваги", "."],
        ruTokens: ["Психологическая", "устойчивость", "помогает", "человеку", "быстрее", "возвращаться", "к", "равновесию", "."],
        enTokens: ["Resilience", "helps", "a", "person", "return", "to", "balance", "more", "quickly", "."],
        extraUaTokens: ["сила", "спокій", "терпіння"],
        extraRuTokens: ["сила", "спокойствие", "терпение"],
        extraEnTokens: ["strength", "calm", "patience"],
    },

    [phraseKey("poradzić sobie z problemem", "b1-34")]: {
        sk: "Z czasem nauczyłem się lepiej radzić sobie z problemem zamiast go unikać.",
        ua: "З часом я навчився краще справлятися з проблемою, а не уникати її.",
        ru: "Со временем я научился лучше справляться с проблемой, а не избегать её.",
        en: "Over time, I learned to cope with a problem better instead of avoiding it.",
        uaTokens: ["З", "часом", "я", "навчився", "краще", "справлятися", "з", "проблемою", ",", "а", "не", "уникати", "її", "."],
        ruTokens: ["Со", "временем", "я", "научился", "лучше", "справляться", "с", "проблемой", ",", "а", "не", "избегать", "её", "."],
        enTokens: ["Over", "time", ",", "I", "learned", "to", "cope", "with", "a", "problem", "better", "instead", "of", "avoiding", "it", "."],
        extraUaTokens: ["страх", "досвід", "рішення"],
        extraRuTokens: ["страх", "опыт", "решение"],
        extraEnTokens: ["fear", "experience", "decision"],
    },

    // =========================
    // LESSON 35 — Столиці
    // =========================
    [phraseKey("Kijów", "b1-35")]: {
        sk: "Kijów jest stolicą Ukrainy i ważnym centrum kulturalnym kraju.",
        ua: "Київ є столицею України та важливим культурним центром країни.",
        ru: "Киев — столица Украины и важный культурный центр страны.",
        en: "Kyiv is the capital of Ukraine and an important cultural center of the country.",
        uaTokens: ["Київ", "є", "столицею", "України", "та", "важливим", "культурним", "центром", "країни", "."],
        ruTokens: ["Киев", "—", "столица", "Украины", "и", "важный", "культурный", "центр", "страны", "."],
        enTokens: ["Kyiv", "is", "the", "capital", "of", "Ukraine", "and", "an", "important", "cultural", "center", "of", "the", "country", "."],
        extraUaTokens: ["місто", "історія", "Європа"],
        extraRuTokens: ["город", "история", "Европа"],
        extraEnTokens: ["city", "history", "Europe"],
    },

    [phraseKey("Londyn", "b1-35")]: {
        sk: "Londyn jest jednym z największych i najbardziej znanych miast Europy.",
        ua: "Лондон є одним із найбільших і найвідоміших міст Європи.",
        ru: "Лондон — один из крупнейших и самых известных городов Европы.",
        en: "London is one of the largest and most famous cities in Europe.",
        uaTokens: ["Лондон", "є", "одним", "із", "найбільших", "і", "найвідоміших", "міст", "Європи", "."],
        ruTokens: ["Лондон", "—", "один", "из", "крупнейших", "и", "самых", "известных", "городов", "Европы", "."],
        enTokens: ["London", "is", "one", "of", "the", "largest", "and", "most", "famous", "cities", "in", "Europe", "."],
        extraUaTokens: ["столиця", "місто", "туристи"],
        extraRuTokens: ["столица", "город", "туристы"],
        extraEnTokens: ["capital", "city", "tourists"],
    },

    [phraseKey("Ottawa", "b1-35")]: {
        sk: "Ottawa jest stolicą Kanady, chociaż nie jest jej największym miastem.",
        ua: "Оттава є столицею Канади, хоча не є її найбільшим містом.",
        ru: "Оттава — столица Канады, хотя это не самый большой её город.",
        en: "Ottawa is the capital of Canada, although it is not its largest city.",
        uaTokens: ["Оттава", "є", "столицею", "Канади", ",", "хоча", "не", "є", "її", "найбільшим", "містом", "."],
        ruTokens: ["Оттава", "—", "столица", "Канады", ",", "хотя", "это", "не", "самый", "большой", "её", "город", "."],
        enTokens: ["Ottawa", "is", "the", "capital", "of", "Canada", ",", "although", "it", "is", "not", "its", "largest", "city", "."],
        extraUaTokens: ["країна", "місто", "столиця"],
        extraRuTokens: ["страна", "город", "столица"],
        extraEnTokens: ["country", "city", "capital"],
    },

    [phraseKey("Berno", "b1-35")]: {
        sk: "Berno jest spokojnym miastem i pełni ważną rolę administracyjną w Szwajcarii.",
        ua: "Берн є спокійним містом і виконує важливу адміністративну роль у Швейцарії.",
        ru: "Берн — спокойный город и играет важную административную роль в Швейцарии.",
        en: "Bern is a calm city and plays an important administrative role in Switzerland.",
        uaTokens: ["Берн", "є", "спокійним", "містом", "і", "виконує", "важливу", "адміністративну", "роль", "у", "Швейцарії", "."],
        ruTokens: ["Берн", "—", "спокойный", "город", "и", "играет", "важную", "административную", "роль", "в", "Швейцарии", "."],
        enTokens: ["Bern", "is", "a", "calm", "city", "and", "plays", "an", "important", "administrative", "role", "in", "Switzerland", "."],
        extraUaTokens: ["місто", "країна", "уряд"],
        extraRuTokens: ["город", "страна", "правительство"],
        extraEnTokens: ["city", "country", "government"],
    },

    [phraseKey("Amsterdam", "b1-35")]: {
        sk: "Amsterdam przyciąga turystów swoimi kanałami, muzeami i wyjątkową atmosferą.",
        ua: "Амстердам приваблює туристів своїми каналами, музеями та особливою атмосферою.",
        ru: "Амстердам привлекает туристов своими каналами, музеями и особой атмосферой.",
        en: "Amsterdam attracts tourists with its canals, museums, and unique atmosphere.",
        uaTokens: ["Амстердам", "приваблює", "туристів", "своїми", "каналами", ",", "музеями", "та", "особливою", "атмосферою", "."],
        ruTokens: ["Амстердам", "привлекает", "туристов", "своими", "каналами", ",", "музеями", "и", "особой", "атмосферой", "."],
        enTokens: ["Amsterdam", "attracts", "tourists", "with", "its", "canals", ",", "museums", ",", "and", "unique", "atmosphere", "."],
        extraUaTokens: ["місто", "музей", "туризм"],
        extraRuTokens: ["город", "музей", "туризм"],
        extraEnTokens: ["city", "museum", "tourism"],
    },

    [phraseKey("Bruksela", "b1-35")]: {
        sk: "Bruksela jest ważnym centrum politycznym Unii Europejskiej.",
        ua: "Брюссель є важливим політичним центром Європейського Союзу.",
        ru: "Брюссель — важный политический центр Европейского Союза.",
        en: "Brussels is an important political center of the European Union.",
        uaTokens: ["Брюссель", "є", "важливим", "політичним", "центром", "Європейського", "Союзу", "."],
        ruTokens: ["Брюссель", "—", "важный", "политический", "центр", "Европейского", "Союза", "."],
        enTokens: ["Brussels", "is", "an", "important", "political", "center", "of", "the", "European", "Union", "."],
        extraUaTokens: ["Європа", "політика", "інституції"],
        extraRuTokens: ["Европа", "политика", "институты"],
        extraEnTokens: ["Europe", "politics", "institutions"],
    },

    [phraseKey("Sztokholm", "b1-35")]: {
        sk: "Sztokholm leży na wyspach i należy do najpiękniejszych stolic północy.",
        ua: "Стокгольм розташований на островах і належить до найкрасивіших столиць півночі.",
        ru: "Стокгольм расположен на островах и считается одной из самых красивых северных столиц.",
        en: "Stockholm lies on islands and is one of the most beautiful capitals of the north.",
        uaTokens: ["Стокгольм", "розташований", "на", "островах", "і", "належить", "до", "найкрасивіших", "столиць", "півночі", "."],
        ruTokens: ["Стокгольм", "расположен", "на", "островах", "и", "считается", "одной", "из", "самых", "красивых", "северных", "столиц", "."],
        enTokens: ["Stockholm", "lies", "on", "islands", "and", "is", "one", "of", "the", "most", "beautiful", "capitals", "of", "the", "north", "."],
        extraUaTokens: ["місто", "острів", "північ"],
        extraRuTokens: ["город", "остров", "север"],
        extraEnTokens: ["city", "island", "north"],
    },

    [phraseKey("Moskwa", "b1-35")]: {
        sk: "Moskwa jest bardzo dużym miastem z bogatą historią i wieloma zabytkami.",
        ua: "Москва є дуже великим містом з багатою історією та багатьма пам’ятками.",
        ru: "Москва — очень большой город с богатой историей и множеством достопримечательностей.",
        en: "Moscow is a very large city with a rich history and many landmarks.",
        uaTokens: ["Москва", "є", "дуже", "великим", "містом", "з", "багатою", "історією", "та", "багатьма", "пам’ятками", "."],
        ruTokens: ["Москва", "—", "очень", "большой", "город", "с", "богатой", "историей", "и", "множеством", "достопримечательностей", "."],
        enTokens: ["Moscow", "is", "a", "very", "large", "city", "with", "a", "rich", "history", "and", "many", "landmarks", "."],
        extraUaTokens: ["місто", "музей", "історія"],
        extraRuTokens: ["город", "музей", "история"],
        extraEnTokens: ["city", "museum", "history"],
    },

    [phraseKey("Bukareszt", "b1-35")]: {
        sk: "Bukareszt rozwija się szybko i staje się coraz bardziej nowoczesny.",
        ua: "Бухарест швидко розвивається і стає дедалі сучаснішим.",
        ru: "Бухарест быстро развивается и становится всё более современным.",
        en: "Bucharest is developing quickly and becoming more modern.",
        uaTokens: ["Бухарест", "швидко", "розвивається", "і", "стає", "дедалі", "сучаснішим", "."],
        ruTokens: ["Бухарест", "быстро", "развивается", "и", "становится", "всё", "более", "современным", "."],
        enTokens: ["Bucharest", "is", "developing", "quickly", "and", "becoming", "more", "modern", "."],
        extraUaTokens: ["місто", "країна", "архітектура"],
        extraRuTokens: ["город", "страна", "архитектура"],
        extraEnTokens: ["city", "country", "architecture"],
    },

    [phraseKey("Sofia", "b1-35")]: {
        sk: "Sofia łączy w sobie historię, kulturę i współczesne życie miejskie.",
        ua: "Софія поєднує в собі історію, культуру та сучасне міське життя.",
        ru: "София сочетает в себе историю, культуру и современную городскую жизнь.",
        en: "Sofia combines history, culture, and modern urban life.",
        uaTokens: ["Софія", "поєднує", "в", "собі", "історію", ",", "культуру", "та", "сучасне", "міське", "життя", "."],
        ruTokens: ["София", "сочетает", "в", "себе", "историю", ",", "культуру", "и", "современную", "городскую", "жизнь", "."],
        enTokens: ["Sofia", "combines", "history", ",", "culture", ",", "and", "modern", "urban", "life", "."],
        extraUaTokens: ["столиця", "місто", "традиція"],
        extraRuTokens: ["столица", "город", "традиция"],
        extraEnTokens: ["capital", "city", "tradition"],
    },
};