import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_B1_BUILD_UA_SENTENCES_1: BuildUaSentenceDict = {
  // =========================
  // LESSON B1-1 — Робота та кар’єра
  // =========================
  [phraseKey("pracovní doba", "b1-1")]: {
    sk: "Naše pracovní doba začíná v osm hodin.",
    ua: "Наш робочий час починається о восьмій годині.",
    ru: "Наше рабочее время начинается в восемь часов.",
    en: "Our working hours start at eight o’clock.",
    uaTokens: ["Наш", "робочий", "час", "починається", "о", "восьмій", "годині", "."],
    ruTokens: ["Наше", "рабочее", "время", "начинается", "в", "восемь", "часов", "."],
    enTokens: ["Our", "working", "hours", "start", "at", "eight", "o’clock", "."],
    extraUaTokens: ["закінчується", "дев’ятій", "вечора"],
    extraRuTokens: ["заканчивается", "девять", "вечера"],
    extraEnTokens: ["ends", "nine", "evening"],
  },

  [phraseKey("nástup", "b1-1")]: {
    sk: "Můj nástup do nové práce je od pondělí.",
    ua: "Мій вихід на нову роботу — з понеділка.",
    ru: "Мой выход на новую работу — с понедельника.",
    en: "I start my new job on Monday.",
    uaTokens: ["Мій", "вихід", "на", "нову", "роботу", "—", "з", "понеділка", "."],
    ruTokens: ["Мой", "выход", "на", "новую", "работу", "—", "с", "понедельника", "."],
    enTokens: ["I", "start", "my", "new", "job", "on", "Monday", "."],
    extraUaTokens: ["стару", "п’ятниці", "вчора"],
    extraRuTokens: ["старую", "пятницы", "вчера"],
    extraEnTokens: ["old", "Friday", "yesterday"],
  },

  [phraseKey("zkoušební doba", "b1-1")]: {
    sk: "Ve zkušební době musím ukázat své schopnosti.",
    ua: "На випробувальному терміні я маю показати свої здібності.",
    ru: "На испытательном сроке я должен показать свои способности.",
    en: "During the probation period, I have to show my abilities.",
    uaTokens: ["На", "випробувальному", "терміні", "я", "маю", "показати", "свої", "здібності", "."],
    ruTokens: ["На", "испытательном", "сроке", "я", "должен", "показать", "свои", "способности", "."],
    enTokens: ["During", "the", "probation", "period", ",", "I", "have", "to", "show", "my", "abilities", "."],
    extraUaTokens: ["приховати", "слабкості", "завжди"],
    extraRuTokens: ["скрыть", "слабости", "всегда"],
    extraEnTokens: ["hide", "weaknesses", "always"],
  },

  [phraseKey("pracovní poměr", "b1-1")]: {
    sk: "Pracovní poměr byl uzavřen na dobu neurčitou.",
    ua: "Трудові відносини були укладені на невизначений термін.",
    ru: "Трудовые отношения были оформлены на неопределённый срок.",
    en: "The employment relationship was concluded for an indefinite period.",
    uaTokens: ["Трудові", "відносини", "були", "укладені", "на", "невизначений", "термін", "."],
    ruTokens: ["Трудовые", "отношения", "были", "оформлены", "на", "неопределённый", "срок", "."],
    enTokens: ["The", "employment", "relationship", "was", "concluded", "for", "an", "indefinite", "period", "."],
    extraUaTokens: ["короткий", "визначений", "учора"],
    extraRuTokens: ["короткий", "определённый", "вчера"],
    extraEnTokens: ["short", "fixed", "yesterday"],
  },

  [phraseKey("výplata", "b1-1")]: {
    sk: "Výplata mi přišla dnes ráno na účet.",
    ua: "Зарплата прийшла мені сьогодні вранці на рахунок.",
    ru: "Зарплата пришла мне сегодня утром на счёт.",
    en: "My salary arrived in my account this morning.",
    uaTokens: ["Зарплата", "прийшла", "мені", "сьогодні", "вранці", "на", "рахунок", "."],
    ruTokens: ["Зарплата", "пришла", "мне", "сегодня", "утром", "на", "счёт", "."],
    enTokens: ["My", "salary", "arrived", "in", "my", "account", "this", "morning", "."],
    extraUaTokens: ["учора", "готівкою", "поштою"],
    extraRuTokens: ["вчера", "наличными", "почтой"],
    extraEnTokens: ["yesterday", "cash", "mail"],
  },

  [phraseKey("příspěvek", "b1-1")]: {
    sk: "Firma nabízí příspěvek na dopravu.",
    ua: "Фірма пропонує компенсацію на транспорт.",
    ru: "Фирма предлагает компенсацию на транспорт.",
    en: "The company offers a transport allowance.",
    uaTokens: ["Фірма", "пропонує", "компенсацію", "на", "транспорт", "."],
    ruTokens: ["Фирма", "предлагает", "компенсацию", "на", "транспорт", "."],
    enTokens: ["The", "company", "offers", "a", "transport", "allowance", "."],
    extraUaTokens: ["житло", "не", "дає"],
    extraRuTokens: ["жильё", "не", "даёт"],
    extraEnTokens: ["housing", "not", "provide"],
  },

  [phraseKey("docházka", "b1-1")]: {
    sk: "Docházka se u nás zapisuje elektronicky.",
    ua: "Табель у нас ведеться електронно.",
    ru: "Табель у нас ведётся электронно.",
    en: "Attendance is recorded electronically here.",
    uaTokens: ["Табель", "у", "нас", "ведеться", "електронно", "."],
    ruTokens: ["Табель", "у", "нас", "ведётся", "электронно", "."],
    enTokens: ["Attendance", "is", "recorded", "electronically", "here", "."],
    extraUaTokens: ["вручну", "паперово", "інколи"],
    extraRuTokens: ["вручную", "на", "бумаге", "иногда"],
    extraEnTokens: ["manually", "paper", "sometimes"],
  },

  [phraseKey("benefit", "b1-1")]: {
    sk: "Jedním z benefitů je pět týdnů dovolené.",
    ua: "Одним із бонусів є п’ять тижнів відпустки.",
    ru: "Одним из бонусов является пять недель отпуска.",
    en: "One of the benefits is five weeks of vacation.",
    uaTokens: ["Одним", "із", "бонусів", "є", "п’ять", "тижнів", "відпустки", "."],
    ruTokens: ["Одним", "из", "бонусов", "является", "пять", "недель", "отпуска", "."],
    enTokens: ["One", "of", "the", "benefits", "is", "five", "weeks", "of", "vacation", "."],
    extraUaTokens: ["три", "роботи", "дні"],
    extraRuTokens: ["три", "рабочих", "дня"],
    extraEnTokens: ["three", "working", "days"],
  },

  [phraseKey("nadřízený", "b1-1")]: {
    sk: "Můj nadřízený chce mluvit o novém projektu.",
    ua: "Мій керівник хоче поговорити про новий проєкт.",
    ru: "Мой начальник хочет поговорить о новом проекте.",
    en: "My supervisor wants to talk about the new project.",
    uaTokens: ["Мій", "керівник", "хоче", "поговорити", "про", "новий", "проєкт", "."],
    ruTokens: ["Мой", "начальник", "хочет", "поговорить", "о", "новом", "проекте", "."],
    enTokens: ["My", "supervisor", "wants", "to", "talk", "about", "the", "new", "project", "."],
    extraUaTokens: ["старий", "клієнт", "мовчати"],
    extraRuTokens: ["старый", "клиент", "молчать"],
    extraEnTokens: ["old", "client", "silent"],
  },

  [phraseKey("podřízený", "b1-1")]: {
    sk: "Dobrý vedoucí by měl naslouchat svým podřízeným.",
    ua: "Хороший керівник повинен слухати своїх підлеглих.",
    ru: "Хороший руководитель должен слушать своих подчинённых.",
    en: "A good manager should listen to their subordinates.",
    uaTokens: ["Хороший", "керівник", "повинен", "слухати", "своїх", "підлеглих", "."],
    ruTokens: ["Хороший", "руководитель", "должен", "слушать", "своих", "подчинённых", "."],
    enTokens: ["A", "good", "manager", "should", "listen", "to", "their", "subordinates", "."],
    extraUaTokens: ["ігнорувати", "клієнтів", "часто"],
    extraRuTokens: ["игнорировать", "клиентов", "часто"],
    extraEnTokens: ["ignore", "clients", "often"],
  },

  // =========================
  // LESSON B1-2 — Комунікація в команді
  // =========================
  [phraseKey("nedorozumění", "b1-2")]: {
    sk: "Mezi kolegy vzniklo zbytečné nedorozumění.",
    ua: "Між колегами виникло непотрібне непорозуміння.",
    ru: "Между коллегами возникло ненужное недоразумение.",
    en: "An unnecessary misunderstanding arose between colleagues.",
    uaTokens: ["Між", "колегами", "виникло", "непотрібне", "непорозуміння", "."],
    ruTokens: ["Между", "коллегами", "возникло", "ненужное", "недоразумение", "."],
    enTokens: ["An", "unnecessary", "misunderstanding", "arose", "between", "colleagues", "."],
    extraUaTokens: ["дружба", "приємна", "розмова"],
    extraRuTokens: ["дружба", "приятный", "разговор"],
    extraEnTokens: ["friendship", "pleasant", "conversation"],
  },

  [phraseKey("spolupráce", "b1-2")]: {
    sk: "Bez dobré spolupráce to nepůjde.",
    ua: "Без доброї співпраці це не вийде.",
    ru: "Без хорошего сотрудничества это не получится.",
    en: "Without good cooperation, it will not work.",
    uaTokens: ["Без", "доброї", "співпраці", "це", "не", "вийде", "."],
    ruTokens: ["Без", "хорошего", "сотрудничества", "это", "не", "получится", "."],
    enTokens: ["Without", "good", "cooperation", ",", "it", "will", "not", "work", "."],
    extraUaTokens: ["конфлікту", "легко", "сьогодні"],
    extraRuTokens: ["конфликта", "легко", "сегодня"],
    extraEnTokens: ["conflict", "easily", "today"],
  },

  [phraseKey("komunikace", "b1-2")]: {
    sk: "Otevřená komunikace je v týmu důležitá.",
    ua: "Відкрита комунікація в команді важлива.",
    ru: "Открытая коммуникация в команде важна.",
    en: "Open communication is important in a team.",
    uaTokens: ["Відкрита", "комунікація", "в", "команді", "важлива", "."],
    ruTokens: ["Открытая", "коммуникация", "в", "команде", "важна", "."],
    enTokens: ["Open", "communication", "is", "important", "in", "a", "team", "."],
    extraUaTokens: ["закрита", "брехня", "зайва"],
    extraRuTokens: ["закрытая", "ложь", "лишняя"],
    extraEnTokens: ["closed", "lie", "unnecessary"],
  },

  [phraseKey("vyjádřit se", "b1-2")]: {
    sk: "Každý má možnost se k tomu vyjádřit.",
    ua: "Кожен має можливість висловитися з цього приводу.",
    ru: "Каждый имеет возможность высказаться по этому поводу.",
    en: "Everyone has the opportunity to express their opinion on it.",
    uaTokens: ["Кожен", "має", "можливість", "висловитися", "з", "цього", "приводу", "."],
    ruTokens: ["Каждый", "имеет", "возможность", "высказаться", "по", "этому", "поводу", "."],
    enTokens: ["Everyone", "has", "the", "opportunity", "to", "express", "their", "opinion", "on", "it", "."],
    extraUaTokens: ["мовчати", "без", "причини"],
    extraRuTokens: ["молчать", "без", "причины"],
    extraEnTokens: ["stay", "silent", "reason"],
  },

  [phraseKey("navrhnout", "b1-2")]: {
    sk: "Chtěl bych navrhnout jiné řešení.",
    ua: "Я хотів би запропонувати інше рішення.",
    ru: "Я хотел бы предложить другое решение.",
    en: "I would like to suggest another solution.",
    uaTokens: ["Я", "хотів", "би", "запропонувати", "інше", "рішення", "."],
    ruTokens: ["Я", "хотел", "бы", "предложить", "другое", "решение", "."],
    enTokens: ["I", "would", "like", "to", "suggest", "another", "solution", "."],
    extraUaTokens: ["старе", "питання", "відкласти"],
    extraRuTokens: ["старый", "вопрос", "отложить"],
    extraEnTokens: ["old", "question", "postpone"],
  },

  [phraseKey("souhlas", "b1-2")]: {
    sk: "Bez vašeho souhlasu to nemůžeme změnit.",
    ua: "Без вашої згоди ми не можемо це змінити.",
    ru: "Без вашего согласия мы не можем это изменить.",
    en: "Without your consent, we cannot change it.",
    uaTokens: ["Без", "вашої", "згоди", "ми", "не", "можемо", "це", "змінити", "."],
    ruTokens: ["Без", "вашего", "согласия", "мы", "не", "можем", "это", "изменить", "."],
    enTokens: ["Without", "your", "consent", ",", "we", "cannot", "change", "it", "."],
    extraUaTokens: ["дозволу", "вони", "хочуть"],
    extraRuTokens: ["разрешения", "они", "хотят"],
    extraEnTokens: ["permission", "they", "want"],
  },

  [phraseKey("nesouhlas", "b1-2")]: {
    sk: "Svůj nesouhlas vysvětlil klidně a jasně.",
    ua: "Свою незгоду він пояснив спокійно і чітко.",
    ru: "Своё несогласие он объяснил спокойно и ясно.",
    en: "He explained his disagreement calmly and clearly.",
    uaTokens: ["Свою", "незгоду", "він", "пояснив", "спокійно", "і", "чітко", "."],
    ruTokens: ["Своё", "несогласие", "он", "объяснил", "спокойно", "и", "ясно", "."],
    enTokens: ["He", "explained", "his", "disagreement", "calmly", "and", "clearly", "."],
    extraUaTokens: ["згоду", "емоційно", "голосно"],
    extraRuTokens: ["согласие", "эмоционально", "громко"],
    extraEnTokens: ["agreement", "emotionally", "loudly"],
  },

  [phraseKey("vysvětlení", "b1-2")]: {
    sk: "Děkuji za podrobné vysvětlení situace.",
    ua: "Дякую за детальне пояснення ситуації.",
    ru: "Спасибо за подробное объяснение ситуации.",
    en: "Thank you for the detailed explanation of the situation.",
    uaTokens: ["Дякую", "за", "детальне", "пояснення", "ситуації", "."],
    ruTokens: ["Спасибо", "за", "подробное", "объяснение", "ситуации", "."],
    enTokens: ["Thank", "you", "for", "the", "detailed", "explanation", "of", "the", "situation", "."],
    extraUaTokens: ["коротку", "історію", "сьогодні"],
    extraRuTokens: ["короткую", "историю", "сегодня"],
    extraEnTokens: ["short", "story", "today"],
  },

  [phraseKey("upozornit", "b1-2")]: {
    sk: "Musím vás upozornit na jednu chybu.",
    ua: "Я мушу звернути вашу увагу на одну помилку.",
    ru: "Я должен обратить ваше внимание на одну ошибку.",
    en: "I have to draw your attention to one mistake.",
    uaTokens: ["Я", "мушу", "звернути", "вашу", "увагу", "на", "одну", "помилку", "."],
    ruTokens: ["Я", "должен", "обратить", "ваше", "внимание", "на", "одну", "ошибку", "."],
    enTokens: ["I", "have", "to", "draw", "your", "attention", "to", "one", "mistake", "."],
    extraUaTokens: ["похвалу", "дві", "відповіді"],
    extraRuTokens: ["похвалу", "две", "ответы"],
    extraEnTokens: ["praise", "two", "answers"],
  },

  [phraseKey("reagovat", "b1-2")]: {
    sk: "Je důležité reagovat včas na zprávy klienta.",
    ua: "Важливо вчасно реагувати на повідомлення клієнта.",
    ru: "Важно вовремя реагировать на сообщения клиента.",
    en: "It is important to respond to the client’s messages in time.",
    uaTokens: ["Важливо", "вчасно", "реагувати", "на", "повідомлення", "клієнта", "."],
    ruTokens: ["Важно", "вовремя", "реагировать", "на", "сообщения", "клиента", "."],
    enTokens: ["It", "is", "important", "to", "respond", "to", "the", "client’s", "messages", "in", "time", "."],
    extraUaTokens: ["ігнорувати", "дзвінки", "вночі"],
    extraRuTokens: ["игнорировать", "звонки", "ночью"],
    extraEnTokens: ["ignore", "calls", "night"],
  },

  // =========================
  // LESSON B1-3 — Подорожі та транспорт
  // =========================
  [phraseKey("příruční zavazadlo", "b1-3")]: {
    sk: "Do příručního zavazadla si dám jen to nejnutnější.",
    ua: "У ручну поклажу я покладу лише найнеобхідніше.",
    ru: "В ручную кладь я положу только самое необходимое.",
    en: "I will put only the essentials in my carry-on luggage.",
    uaTokens: ["У", "ручну", "поклажу", "я", "покладу", "лише", "найнеобхідніше", "."],
    ruTokens: ["В", "ручную", "кладь", "я", "положу", "только", "самое", "необходимое", "."],
    enTokens: ["I", "will", "put", "only", "the", "essentials", "in", "my", "carry-on", "luggage", "."],
    extraUaTokens: ["все", "зайве", "сьогодні"],
    extraRuTokens: ["всё", "лишнее", "сегодня"],
    extraEnTokens: ["everything", "extra", "today"],
  },

  [phraseKey("nástup", "b1-3")]: {
    sk: "Nástup do letadla začne za dvacet minut.",
    ua: "Посадка в літак почнеться за двадцять хвилин.",
    ru: "Посадка в самолёт начнётся через двадцать минут.",
    en: "Boarding the plane will begin in twenty minutes.",
    uaTokens: ["Посадка", "в", "літак", "почнеться", "за", "двадцять", "хвилин", "."],
    ruTokens: ["Посадка", "в", "самолёт", "начнётся", "через", "двадцать", "минут", "."],
    enTokens: ["Boarding", "the", "plane", "will", "begin", "in", "twenty", "minutes", "."],
    extraUaTokens: ["годин", "поїзд", "закінчиться"],
    extraRuTokens: ["часов", "поезд", "закончится"],
    extraEnTokens: ["hours", "train", "end"],
  },

  [phraseKey("cestující", "b1-3")]: {
    sk: "Cestující musí mít platný doklad.",
    ua: "Пасажир повинен мати дійсний документ.",
    ru: "Пассажир должен иметь действительный документ.",
    en: "The passenger must have a valid document.",
    uaTokens: ["Пасажир", "повинен", "мати", "дійсний", "документ", "."],
    ruTokens: ["Пассажир", "должен", "иметь", "действительный", "документ", "."],
    enTokens: ["The", "passenger", "must", "have", "a", "valid", "document", "."],
    extraUaTokens: ["квиток", "старий", "недійсний"],
    extraRuTokens: ["билет", "старый", "недействительный"],
    extraEnTokens: ["ticket", "old", "invalid"],
  },

  [phraseKey("zrušení", "b1-3")]: {
    sk: "O zrušení letu jsme se dozvěděli na letišti.",
    ua: "Про скасування рейсу ми дізналися в аеропорту.",
    ru: "Об отмене рейса мы узнали в аэропорту.",
    en: "We learned about the flight cancellation at the airport.",
    uaTokens: ["Про", "скасування", "рейсу", "ми", "дізналися", "в", "аеропорту", "."],
    ruTokens: ["Об", "отмене", "рейса", "мы", "узнали", "в", "аэропорту", "."],
    enTokens: ["We", "learned", "about", "the", "flight", "cancellation", "at", "the", "airport", "."],
    extraUaTokens: ["затримку", "поїзда", "вдома"],
    extraRuTokens: ["задержке", "поезда", "дома"],
    extraEnTokens: ["delay", "train", "home"],
  },

  [phraseKey("přestupovat", "b1-3")]: {
    sk: "V Brně musíme přestupovat na jiný vlak.",
    ua: "У Брні нам треба робити пересадку на інший потяг.",
    ru: "В Брно нам нужно пересаживаться на другой поезд.",
    en: "In Brno, we have to change to another train.",
    uaTokens: ["У", "Брні", "нам", "треба", "робити", "пересадку", "на", "інший", "потяг", "."],
    ruTokens: ["В", "Брно", "нам", "нужно", "пересаживаться", "на", "другой", "поезд", "."],
    enTokens: ["In", "Brno", ",", "we", "have", "to", "change", "to", "another", "train", "."],
    extraUaTokens: ["автобус", "прямий", "маршрут"],
    extraRuTokens: ["автобус", "прямой", "маршрут"],
    extraEnTokens: ["bus", "direct", "route"],
  },

  [phraseKey("cestovní doklad", "b1-3")]: {
    sk: "Bez cestovního dokladu nemůžete odjet.",
    ua: "Без проїзного документа ви не можете поїхати.",
    ru: "Без проездного документа вы не можете уехать.",
    en: "Without a travel document, you cannot leave.",
    uaTokens: ["Без", "проїзного", "документа", "ви", "не", "можете", "поїхати", "."],
    ruTokens: ["Без", "проездного", "документа", "вы", "не", "можете", "уехать", "."],
    enTokens: ["Without", "a", "travel", "document", ",", "you", "cannot", "leave", "."],
    extraUaTokens: ["дозволу", "прийти", "сьогодні"],
    extraRuTokens: ["разрешения", "прийти", "сегодня"],
    extraEnTokens: ["permission", "come", "today"],
  },

  [phraseKey("bezpečnostní kontrola", "b1-3")]: {
    sk: "Bezpečnostní kontrola byla tentokrát velmi rychlá.",
    ua: "Контроль безпеки цього разу був дуже швидким.",
    ru: "Контроль безопасности в этот раз был очень быстрым.",
    en: "The security check was very quick this time.",
    uaTokens: ["Контроль", "безпеки", "цього", "разу", "був", "дуже", "швидким", "."],
    ruTokens: ["Контроль", "безопасности", "в", "этот", "раз", "был", "очень", "быстрым", "."],
    enTokens: ["The", "security", "check", "was", "very", "quick", "this", "time", "."],
    extraUaTokens: ["повільним", "вчора", "увечері"],
    extraRuTokens: ["медленным", "вчера", "вечером"],
    extraEnTokens: ["slow", "yesterday", "evening"],
  },

  [phraseKey("palubní lístek", "b1-3")]: {
    sk: "Palubní lístek mám uložený v telefonu.",
    ua: "Посадковий талон у мене збережений у телефоні.",
    ru: "Посадочный талон у меня сохранён в телефоне.",
    en: "I have my boarding pass saved on my phone.",
    uaTokens: ["Посадковий", "талон", "у", "мене", "збережений", "у", "телефоні", "."],
    ruTokens: ["Посадочный", "талон", "у", "меня", "сохранён", "в", "телефоне", "."],
    enTokens: ["I", "have", "my", "boarding", "pass", "saved", "on", "my", "phone", "."],
    extraUaTokens: ["вдома", "квиток", "паперовий"],
    extraRuTokens: ["дома", "билет", "бумажный"],
    extraEnTokens: ["home", "ticket", "paper"],
  },

  [phraseKey("odvzdat zavazadlo", "b1-3")]: {
    sk: "Musíme ještě odvzdat zavazadlo u přepážky.",
    ua: "Нам ще треба здати багаж біля стійки.",
    ru: "Нам ещё нужно сдать багаж у стойки.",
    en: "We still have to check in our luggage at the counter.",
    uaTokens: ["Нам", "ще", "треба", "здати", "багаж", "біля", "стійки", "."],
    ruTokens: ["Нам", "ещё", "нужно", "сдать", "багаж", "у", "стойки", "."],
    enTokens: ["We", "still", "have", "to", "check", "in", "our", "luggage", "at", "the", "counter", "."],
    extraUaTokens: ["забрати", "паспорт", "потім"],
    extraRuTokens: ["забрать", "паспорт", "потом"],
    extraEnTokens: ["take", "passport", "later"],
  },

  [phraseKey("celní kontrola", "b1-3")]: {
    sk: "Po příletu nás čekala celní kontrola.",
    ua: "Після прильоту нас чекав митний контроль.",
    ru: "После прилёта нас ждал таможенный контроль.",
    en: "After arrival, customs control was waiting for us.",
    uaTokens: ["Після", "прильоту", "нас", "чекав", "митний", "контроль", "."],
    ruTokens: ["После", "прилёта", "нас", "ждал", "таможенный", "контроль", "."],
    enTokens: ["After", "arrival", ",", "customs", "control", "was", "waiting", "for", "us", "."],
    extraUaTokens: ["виліту", "паспортний", "огляд"],
    extraRuTokens: ["вылета", "паспортный", "осмотр"],
    extraEnTokens: ["departure", "passport", "inspection"],
  },

  // =========================
  // LESSON B1-4 — Здоров’я та лікар
  // =========================
  [phraseKey("léčba", "b1-4")]: {
    sk: "Léčba bude trvat nejméně dva týdny.",
    ua: "Лікування триватиме щонайменше два тижні.",
    ru: "Лечение будет длиться как минимум две недели.",
    en: "The treatment will last at least two weeks.",
    uaTokens: ["Лікування", "триватиме", "щонайменше", "два", "тижні", "."],
    ruTokens: ["Лечение", "будет", "длиться", "как", "минимум", "две", "недели", "."],
    enTokens: ["The", "treatment", "will", "last", "at", "least", "two", "weeks", "."],
    extraUaTokens: ["один", "день", "швидко"],
    extraRuTokens: ["один", "день", "быстро"],
    extraEnTokens: ["one", "day", "quickly"],
  },

  [phraseKey("vyšetřit", "b1-4")]: {
    sk: "Lékař mě chce znovu vyšetřit.",
    ua: "Лікар хоче ще раз мене оглянути.",
    ru: "Врач хочет снова меня осмотреть.",
    en: "The doctor wants to examine me again.",
    uaTokens: ["Лікар", "хоче", "ще", "раз", "мене", "оглянути", "."],
    ruTokens: ["Врач", "хочет", "снова", "меня", "осмотреть", "."],
    enTokens: ["The", "doctor", "wants", "to", "examine", "me", "again", "."],
    extraUaTokens: ["виписати", "ліки", "одразу"],
    extraRuTokens: ["выписать", "лекарства", "сразу"],
    extraEnTokens: ["prescribe", "medicine", "immediately"],
  },

  [phraseKey("předepsat", "b1-4")]: {
    sk: "Doktor mi předepsal silnější léky.",
    ua: "Лікар призначив мені сильніші ліки.",
    ru: "Доктор назначил мне более сильные лекарства.",
    en: "The doctor prescribed me stronger medicine.",
    uaTokens: ["Лікар", "призначив", "мені", "сильніші", "ліки", "."],
    ruTokens: ["Доктор", "назначил", "мне", "более", "сильные", "лекарства", "."],
    enTokens: ["The", "doctor", "prescribed", "me", "stronger", "medicine", "."],
    extraUaTokens: ["слабші", "вітаміни", "вчора"],
    extraRuTokens: ["слабые", "витамины", "вчера"],
    extraEnTokens: ["weaker", "vitamins", "yesterday"],
  },

  [phraseKey("zhoršit se", "b1-4")]: {
    sk: "Můj stav se přes noc zhoršil.",
    ua: "Мій стан за ніч погіршився.",
    ru: "Моё состояние за ночь ухудшилось.",
    en: "My condition got worse overnight.",
    uaTokens: ["Мій", "стан", "за", "ніч", "погіршився", "."],
    ruTokens: ["Моё", "состояние", "за", "ночь", "ухудшилось", "."],
    enTokens: ["My", "condition", "got", "worse", "overnight", "."],
    extraUaTokens: ["покращився", "за", "ранок"],
    extraRuTokens: ["улучшилось", "за", "утро"],
    extraEnTokens: ["improved", "morning", "by"],
  },

  [phraseKey("zlepšit se", "b1-4")]: {
    sk: "Po několika dnech se mi zlepšilo dýchání.",
    ua: "Через кілька днів у мене покращилося дихання.",
    ru: "Через несколько дней у меня улучшилось дыхание.",
    en: "After a few days, my breathing improved.",
    uaTokens: ["Через", "кілька", "днів", "у", "мене", "покращилося", "дихання", "."],
    ruTokens: ["Через", "несколько", "дней", "у", "меня", "улучшилось", "дыхание", "."],
    enTokens: ["After", "a", "few", "days", ",", "my", "breathing", "improved", "."],
    extraUaTokens: ["самопочуття", "погіршилося", "вчора"],
    extraRuTokens: ["самочувствие", "ухудшилось", "вчера"],
    extraEnTokens: ["condition", "worsened", "yesterday"],
  },

  [phraseKey("hospitalizace", "b1-4")]: {
    sk: "Naštěstí hospitalizace nebyla nutná.",
    ua: "На щастя, госпіталізація не була потрібна.",
    ru: "К счастью, госпитализация не понадобилась.",
    en: "Fortunately, hospitalization was not necessary.",
    uaTokens: ["На", "щастя", ",", "госпіталізація", "не", "була", "потрібна", "."],
    ruTokens: ["К", "счастью", ",", "госпитализация", "не", "понадобилась", "."],
    enTokens: ["Fortunately", ",", "hospitalization", "was", "not", "necessary", "."],
    extraUaTokens: ["термінова", "була", "ввечері"],
    extraRuTokens: ["срочная", "была", "вечером"],
    extraEnTokens: ["urgent", "was", "evening"],
  },

  [phraseKey("příznak", "b1-4")]: {
    sk: "Prvním příznakem byla vysoká teplota.",
    ua: "Першим симптомом була висока температура.",
    ru: "Первым симптомом была высокая температура.",
    en: "The first symptom was a high temperature.",
    uaTokens: ["Першим", "симптомом", "була", "висока", "температура", "."],
    ruTokens: ["Первым", "симптомом", "была", "высокая", "температура", "."],
    enTokens: ["The", "first", "symptom", "was", "a", "high", "temperature", "."],
    extraUaTokens: ["кашель", "низька", "втома"],
    extraRuTokens: ["кашель", "низкая", "усталость"],
    extraEnTokens: ["cough", "low", "fatigue"],
  },

  [phraseKey("zdravotní stav", "b1-4")]: {
    sk: "Jeho zdravotní stav se pomalu stabilizuje.",
    ua: "Його стан здоров’я повільно стабілізується.",
    ru: "Его состояние здоровья медленно стабилизируется.",
    en: "His health condition is slowly stabilizing.",
    uaTokens: ["Його", "стан", "здоров’я", "повільно", "стабілізується", "."],
    ruTokens: ["Его", "состояние", "здоровья", "медленно", "стабилизируется", "."],
    enTokens: ["His", "health", "condition", "is", "slowly", "stabilizing", "."],
    extraUaTokens: ["швидко", "погіршується", "сьогодні"],
    extraRuTokens: ["быстро", "ухудшается", "сегодня"],
    extraEnTokens: ["quickly", "worsening", "today"],
  },

  [phraseKey("uzdravení", "b1-4")]: {
    sk: "K úplnému uzdravení bude potřebovat čas.",
    ua: "Для повного одужання йому знадобиться час.",
    ru: "Для полного выздоровления ему понадобится время.",
    en: "He will need time for a full recovery.",
    uaTokens: ["Для", "повного", "одужання", "йому", "знадобиться", "час", "."],
    ruTokens: ["Для", "полного", "выздоровления", "ему", "понадобится", "время", "."],
    enTokens: ["He", "will", "need", "time", "for", "a", "full", "recovery", "."],
    extraUaTokens: ["відпочинок", "день", "лише"],
    extraRuTokens: ["отдых", "день", "только"],
    extraEnTokens: ["rest", "day", "only"],
  },

  [phraseKey("předpis", "b1-4")]: {
    sk: "Dodržujte prosím přesně lékařský předpis.",
    ua: "Будь ласка, точно дотримуйтесь лікарських призначень.",
    ru: "Пожалуйста, точно соблюдайте врачебные назначения.",
    en: "Please follow the doctor’s prescription exactly.",
    uaTokens: ["Будь", "ласка", ",", "точно", "дотримуйтесь", "лікарських", "призначень", "."],
    ruTokens: ["Пожалуйста", ",", "точно", "соблюдайте", "врачебные", "назначения", "."],
    enTokens: ["Please", "follow", "the", "doctor’s", "prescription", "exactly", "."],
    extraUaTokens: ["ігноруйте", "пораду", "вчора"],
    extraRuTokens: ["игнорируйте", "совет", "вчера"],
    extraEnTokens: ["ignore", "advice", "yesterday"],
  },

  // =========================
  // LESSON B1-5 — Емоції та стосунки
  // =========================
  [phraseKey("hádka", "b1-5")]: {
    sk: "Včera mezi nimi došlo k hádce.",
    ua: "Учора між ними сталася сварка.",
    ru: "Вчера между ними произошла ссора.",
    en: "There was an argument between them yesterday.",
    uaTokens: ["Учора", "між", "ними", "сталася", "сварка", "."],
    ruTokens: ["Вчера", "между", "ними", "произошла", "ссора", "."],
    enTokens: ["There", "was", "an", "argument", "between", "them", "yesterday", "."],
    extraUaTokens: ["примирення", "сьогодні", "вдень"],
    extraRuTokens: ["примирение", "сегодня", "днём"],
    extraEnTokens: ["reconciliation", "today", "afternoon"],
  },

  [phraseKey("smíření", "b1-5")]: {
    sk: "Po dlouhé době konečně došlo ke smíření.",
    ua: "Після тривалого часу нарешті настало примирення.",
    ru: "После долгого времени наконец наступило примирение.",
    en: "After a long time, reconciliation finally happened.",
    uaTokens: ["Після", "тривалого", "часу", "нарешті", "настало", "примирення", "."],
    ruTokens: ["После", "долгого", "времени", "наконец", "наступило", "примирение", "."],
    enTokens: ["After", "a", "long", "time", ",", "reconciliation", "finally", "happened", "."],
    extraUaTokens: ["конфлікту", "вчора", "знову"],
    extraRuTokens: ["конфликт", "вчера", "снова"],
    extraEnTokens: ["conflict", "yesterday", "again"],
  },

  [phraseKey("zklamat", "b1-5")]: {
    sk: "Nechtěl jsem tě zklamat.",
    ua: "Я не хотів тебе розчарувати.",
    ru: "Я не хотел тебя разочаровать.",
    en: "I did not want to disappoint you.",
    uaTokens: ["Я", "не", "хотів", "тебе", "розчарувати", "."],
    ruTokens: ["Я", "не", "хотел", "тебя", "разочаровать", "."],
    enTokens: ["I", "did", "not", "want", "to", "disappoint", "you", "."],
    extraUaTokens: ["похвалити", "його", "сьогодні"],
    extraRuTokens: ["похвалить", "его", "сегодня"],
    extraEnTokens: ["praise", "him", "today"],
  },

  [phraseKey("ocenit", "b1-5")]: {
    sk: "Umím ocenit upřímnost a podporu.",
    ua: "Я вмію цінувати щирість і підтримку.",
    ru: "Я умею ценить искренность и поддержку.",
    en: "I know how to appreciate honesty and support.",
    uaTokens: ["Я", "вмію", "цінувати", "щирість", "і", "підтримку", "."],
    ruTokens: ["Я", "умею", "ценить", "искренность", "и", "поддержку", "."],
    enTokens: ["I", "know", "how", "to", "appreciate", "honesty", "and", "support", "."],
    extraUaTokens: ["брехню", "зраду", "ніколи"],
    extraRuTokens: ["ложь", "предательство", "никогда"],
    extraEnTokens: ["lie", "betrayal", "never"],
  },

  [phraseKey("žárlivost", "b1-5")]: {
    sk: "Žárlivost může vztah zničit.",
    ua: "Ревнощі можуть зруйнувати стосунки.",
    ru: "Ревность может разрушить отношения.",
    en: "Jealousy can destroy a relationship.",
    uaTokens: ["Ревнощі", "можуть", "зруйнувати", "стосунки", "."],
    ruTokens: ["Ревность", "может", "разрушить", "отношения", "."],
    enTokens: ["Jealousy", "can", "destroy", "a", "relationship", "."],
    extraUaTokens: ["довіра", "зміцнити", "дружбу"],
    extraRuTokens: ["доверие", "укрепить", "дружбу"],
    extraEnTokens: ["trust", "strengthen", "friendship"],
  },

  [phraseKey("odpustit", "b1-5")]: {
    sk: "Není snadné odpustit staré chyby.",
    ua: "Нелегко пробачити старі помилки.",
    ru: "Нелегко простить старые ошибки.",
    en: "It is not easy to forgive old mistakes.",
    uaTokens: ["Нелегко", "пробачити", "старі", "помилки", "."],
    ruTokens: ["Нелегко", "простить", "старые", "ошибки", "."],
    enTokens: ["It", "is", "not", "easy", "to", "forgive", "old", "mistakes", "."],
    extraUaTokens: ["забути", "нові", "образи"],
    extraRuTokens: ["забыть", "новые", "обиды"],
    extraEnTokens: ["forget", "new", "offenses"],
  },

  [phraseKey("respekt", "b1-5")]: {
    sk: "Ve vztahu je důležitý vzájemný respekt.",
    ua: "У стосунках важлива взаємна повага.",
    ru: "В отношениях важно взаимное уважение.",
    en: "Mutual respect is important in a relationship.",
    uaTokens: ["У", "стосунках", "важлива", "взаємна", "повага", "."],
    ruTokens: ["В", "отношениях", "важно", "взаимное", "уважение", "."],
    enTokens: ["Mutual", "respect", "is", "important", "in", "a", "relationship", "."],
    extraUaTokens: ["недовіра", "сварка", "часто"],
    extraRuTokens: ["недоверие", "ссора", "часто"],
    extraEnTokens: ["distrust", "argument", "often"],
  },

  [phraseKey("urazit se", "b1-5")]: {
    sk: "Nechtěl jsem, aby ses urazil.",
    ua: "Я не хотів, щоб ти образився.",
    ru: "Я не хотел, чтобы ты обиделся.",
    en: "I did not want you to get offended.",
    uaTokens: ["Я", "не", "хотів", ",", "щоб", "ти", "образився", "."],
    ruTokens: ["Я", "не", "хотел", ",", "чтобы", "ты", "обиделся", "."],
    enTokens: ["I", "did", "not", "want", "you", "to", "get", "offended", "."],
    extraUaTokens: ["зрадів", "вона", "учора"],
    extraRuTokens: ["обрадовался", "она", "вчера"],
    extraEnTokens: ["happy", "she", "yesterday"],
  },

  [phraseKey("přiblížit se", "b1-5")]: {
    sk: "Na společném výletě jsme se víc přiblížili.",
    ua: "На спільній поїздці ми більше зблизилися.",
    ru: "На совместной поездке мы стали ближе.",
    en: "On the trip together, we became closer.",
    uaTokens: ["На", "спільній", "поїздці", "ми", "більше", "зблизилися", "."],
    ruTokens: ["На", "совместной", "поездке", "мы", "стали", "ближе", "."],
    enTokens: ["On", "the", "trip", "together", ",", "we", "became", "closer", "."],
    extraUaTokens: ["віддалилися", "вдома", "сьогодні"],
    extraRuTokens: ["отдалились", "дома", "сегодня"],
    extraEnTokens: ["drifted", "home", "today"],
  },

  [phraseKey("vztah", "b1-5")]: {
    sk: "Dobrý vztah se buduje dlouho.",
    ua: "Хороші стосунки будуються довго.",
    ru: "Хорошие отношения строятся долго.",
    en: "A good relationship is built over a long time.",
    uaTokens: ["Хороші", "стосунки", "будуються", "довго", "."],
    ruTokens: ["Хорошие", "отношения", "строятся", "долго", "."],
    enTokens: ["A", "good", "relationship", "is", "built", "over", "a", "long", "time", "."],
    extraUaTokens: ["руйнуються", "швидко", "інколи"],
    extraRuTokens: ["разрушаются", "быстро", "иногда"],
    extraEnTokens: ["break", "quickly", "sometimes"],
  },
};