import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_B1_BUILD_UA_SENTENCES_4: BuildUaSentenceDict = {
  // =========================
  // LESSON B1-16 — Культура та дозвілля
  // =========================
  [phraseKey("vkus", "b1-16")]: {
    sk: "Každý člověk má jiný vkus.",
    ua: "Кожна людина має інший смак.",
    ru: "У каждого человека свой вкус.",
    en: "Every person has a different taste.",
    uaTokens: ["Кожна", "людина", "має", "інший", "смак", "."],
    ruTokens: ["У", "каждого", "человека", "свой", "вкус", "."],
    enTokens: ["Every", "person", "has", "a", "different", "taste", "."],
    extraUaTokens: ["стиль", "одяг", "учора"],
    extraRuTokens: ["стиль", "одежда", "вчера"],
    extraEnTokens: ["style", "clothes", "yesterday"],
  },

  [phraseKey("recenze", "b1-16")]: {
    sk: "Před návštěvou jsem si přečetl recenze.",
    ua: "Перед візитом я прочитав відгуки.",
    ru: "Перед посещением я прочитал отзывы.",
    en: "Before the visit, I read the reviews.",
    uaTokens: ["Перед", "візитом", "я", "прочитав", "відгуки", "."],
    ruTokens: ["Перед", "посещением", "я", "прочитал", "отзывы", "."],
    enTokens: ["Before", "the", "visit", ",", "I", "read", "the", "reviews", "."],
    extraUaTokens: ["квитки", "після", "вистави"],
    extraRuTokens: ["билеты", "после", "спектакля"],
    extraEnTokens: ["tickets", "after", "show"],
  },

  [phraseKey("zážitek", "b1-16")]: {
    sk: "Byl to pro mě silný kulturní zážitek.",
    ua: "Це було для мене сильне культурне враження.",
    ru: "Это было для меня сильное культурное впечатление.",
    en: "It was a powerful cultural experience for me.",
    uaTokens: ["Це", "було", "для", "мене", "сильне", "культурне", "враження", "."],
    ruTokens: ["Это", "было", "для", "меня", "сильное", "культурное", "впечатление", "."],
    enTokens: ["It", "was", "a", "powerful", "cultural", "experience", "for", "me", "."],
    extraUaTokens: ["слабке", "заняття", "вчора"],
    extraRuTokens: ["слабое", "занятие", "вчера"],
    extraEnTokens: ["weak", "lesson", "yesterday"],
  },

  [phraseKey("vystoupení", "b1-16")]: {
    sk: "Její vystoupení mělo velký úspěch.",
    ua: "Її виступ мав великий успіх.",
    ru: "Её выступление имело большой успех.",
    en: "Her performance was a great success.",
    uaTokens: ["Її", "виступ", "мав", "великий", "успіх", "."],
    ruTokens: ["Её", "выступление", "имело", "большой", "успех", "."],
    enTokens: ["Her", "performance", "was", "a", "great", "success", "."],
    extraUaTokens: ["провал", "учора", "сцена"],
    extraRuTokens: ["провал", "вчера", "сцена"],
    extraEnTokens: ["failure", "yesterday", "stage"],
  },

  [phraseKey("volný čas", "b1-16")]: {
    sk: "Ve volném čase rád čtu a sportuji.",
    ua: "У вільний час я люблю читати і займатися спортом.",
    ru: "В свободное время я люблю читать и заниматься спортом.",
    en: "In my free time, I like reading and playing sports.",
    uaTokens: ["У", "вільний", "час", "я", "люблю", "читати", "і", "займатися", "спортом", "."],
    ruTokens: ["В", "свободное", "время", "я", "люблю", "читать", "и", "заниматься", "спортом", "."],
    enTokens: ["In", "my", "free", "time", ",", "I", "like", "reading", "and", "playing", "sports", "."],
    extraUaTokens: ["працювати", "вночі", "часто"],
    extraRuTokens: ["работать", "ночью", "часто"],
    extraEnTokens: ["work", "at night", "often"],
  },

  [phraseKey("účinkovat", "b1-16")]: {
    sk: "V představení účinkovalo několik známých herců.",
    ua: "У виставі брали участь кілька відомих акторів.",
    ru: "В постановке выступали несколько известных актёров.",
    en: "Several famous actors took part in the performance.",
    uaTokens: ["У", "виставі", "брали", "участь", "кілька", "відомих", "акторів", "."],
    ruTokens: ["В", "постановке", "выступали", "несколько", "известных", "актёров", "."],
    enTokens: ["Several", "famous", "actors", "took", "part", "in", "the", "performance", "."],
    extraUaTokens: ["співаків", "нових", "сьогодні"],
    extraRuTokens: ["певцов", "новых", "сегодня"],
    extraEnTokens: ["singers", "new", "today"],
  },

  [phraseKey("navštívit", "b1-16")]: {
    sk: "O víkendu chceme navštívit nové muzeum.",
    ua: "На вихідних ми хочемо відвідати новий музей.",
    ru: "На выходных мы хотим посетить новый музей.",
    en: "At the weekend, we want to visit the new museum.",
    uaTokens: ["На", "вихідних", "ми", "хочемо", "відвідати", "новий", "музей", "."],
    ruTokens: ["На", "выходных", "мы", "хотим", "посетить", "новый", "музей", "."],
    enTokens: ["At", "the", "weekend", ",", "we", "want", "to", "visit", "the", "new", "museum", "."],
    extraUaTokens: ["театр", "старий", "учора"],
    extraRuTokens: ["театр", "старый", "вчера"],
    extraEnTokens: ["theater", "old", "yesterday"],
  },

  [phraseKey("premiéra", "b1-16")]: {
    sk: "Na premiéru přišlo opravdu hodně lidí.",
    ua: "На прем’єру прийшло справді багато людей.",
    ru: "На премьеру пришло действительно много людей.",
    en: "A lot of people came to the premiere.",
    uaTokens: ["На", "прем’єру", "прийшло", "справді", "багато", "людей", "."],
    ruTokens: ["На", "премьеру", "пришло", "действительно", "много", "людей", "."],
    enTokens: ["A", "lot", "of", "people", "came", "to", "the", "premiere", "."],
    extraUaTokens: ["мало", "глядачів", "вчора"],
    extraRuTokens: ["мало", "зрителей", "вчера"],
    extraEnTokens: ["few", "viewers", "yesterday"],
  },

  [phraseKey("program akce", "b1-16")]: {
    sk: "Program akce byl velmi pestrý.",
    ua: "Програма заходу була дуже різноманітною.",
    ru: "Программа мероприятия была очень разнообразной.",
    en: "The event program was very varied.",
    uaTokens: ["Програма", "заходу", "була", "дуже", "різноманітною", "."],
    ruTokens: ["Программа", "мероприятия", "была", "очень", "разнообразной", "."],
    enTokens: ["The", "event", "program", "was", "very", "varied", "."],
    extraUaTokens: ["нудною", "короткою", "сьогодні"],
    extraRuTokens: ["скучной", "короткой", "сегодня"],
    extraEnTokens: ["boring", "short", "today"],
  },

  [phraseKey("rezervace místa", "b1-16")]: {
    sk: "Rezervace místa je nutná předem.",
    ua: "Бронювання місця потрібне заздалегідь.",
    ru: "Бронирование места необходимо заранее.",
    en: "Seat reservation is necessary in advance.",
    uaTokens: ["Бронювання", "місця", "потрібне", "заздалегідь", "."],
    ruTokens: ["Бронирование", "места", "необходимо", "заранее", "."],
    enTokens: ["Seat", "reservation", "is", "necessary", "in", "advance", "."],
    extraUaTokens: ["квитка", "після", "вистави"],
    extraRuTokens: ["билета", "после", "спектакля"],
    extraEnTokens: ["ticket", "after", "show"],
  },

  // =========================
  // LESSON B1-17 — Спорт
  // =========================
  [phraseKey("trénink", "b1-17")]: {
    sk: "Dnešní trénink byl opravdu náročný.",
    ua: "Сьогоднішнє тренування було справді важким.",
    ru: "Сегодняшняя тренировка была действительно тяжёлой.",
    en: "Today’s training was really hard.",
    uaTokens: ["Сьогоднішнє", "тренування", "було", "справді", "важким", "."],
    ruTokens: ["Сегодняшняя", "тренировка", "была", "действительно", "тяжёлой", "."],
    enTokens: ["Today’s", "training", "was", "really", "hard", "."],
    extraUaTokens: ["легким", "учора", "ввечері"],
    extraRuTokens: ["лёгкой", "вчера", "вечером"],
    extraEnTokens: ["easy", "yesterday", "evening"],
  },

  [phraseKey("zápas", "b1-17")]: {
    sk: "Zítřejší zápas bude velmi důležitý.",
    ua: "Завтрашній матч буде дуже важливим.",
    ru: "Завтрашний матч будет очень важным.",
    en: "Tomorrow’s match will be very important.",
    uaTokens: ["Завтрашній", "матч", "буде", "дуже", "важливим", "."],
    ruTokens: ["Завтрашний", "матч", "будет", "очень", "важным", "."],
    enTokens: ["Tomorrow’s", "match", "will", "be", "very", "important", "."],
    extraUaTokens: ["вчорашній", "турнір", "легким"],
    extraRuTokens: ["вчерашний", "турнир", "лёгким"],
    extraEnTokens: ["yesterday’s", "tournament", "easy"],
  },

  [phraseKey("výhra", "b1-17")]: {
    sk: "Po dlouhé době přišla zasloužená výhra.",
    ua: "Після тривалої перерви прийшла заслужена перемога.",
    ru: "После долгого перерыва пришла заслуженная победа.",
    en: "After a long break, a well-deserved victory finally came.",
    uaTokens: ["Після", "тривалої", "перерви", "прийшла", "заслужена", "перемога", "."],
    ruTokens: ["После", "долгого", "перерыва", "пришла", "заслуженная", "победа", "."],
    enTokens: ["After", "a", "long", "break", ",", "a", "well-deserved", "victory", "finally", "came", "."],
    extraUaTokens: ["поразка", "команді", "сьогодні"],
    extraRuTokens: ["поражение", "команде", "сегодня"],
    extraEnTokens: ["defeat", "team", "today"],
  },

  [phraseKey("prohra", "b1-17")]: {
    sk: "Těžká prohra tým hodně zasáhla.",
    ua: "Важка поразка сильно вдарила по команді.",
    ru: "Тяжёлое поражение сильно ударило по команде.",
    en: "A heavy defeat hit the team hard.",
    uaTokens: ["Важка", "поразка", "сильно", "вдарила", "по", "команді", "."],
    ruTokens: ["Тяжёлое", "поражение", "сильно", "ударило", "по", "команде", "."],
    enTokens: ["A", "heavy", "defeat", "hit", "the", "team", "hard", "."],
    extraUaTokens: ["перемога", "гравцях", "учора"],
    extraRuTokens: ["победа", "игроках", "вчера"],
    extraEnTokens: ["victory", "players", "yesterday"],
  },

  [phraseKey("rozhodčí", "b1-17")]: {
    sk: "Rozhodčí odpískal faul hned na začátku.",
    ua: "Суддя зафіксував фол уже на початку.",
    ru: "Судья зафиксировал фол уже в начале.",
    en: "The referee called a foul right at the beginning.",
    uaTokens: ["Суддя", "зафіксував", "фол", "уже", "на", "початку", "."],
    ruTokens: ["Судья", "зафиксировал", "фол", "уже", "в", "начале", "."],
    enTokens: ["The", "referee", "called", "a", "foul", "right", "at", "the", "beginning", "."],
    extraUaTokens: ["матч", "кінці", "поля"],
    extraRuTokens: ["матч", "в", "конце", "поля"],
    extraEnTokens: ["match", "end", "field"],
  },

  [phraseKey("soutěž", "b1-17")]: {
    sk: "Do soutěže se přihlásilo mnoho týmů.",
    ua: "На змагання зареєструвалося багато команд.",
    ru: "На соревнование зарегистрировалось много команд.",
    en: "Many teams registered for the competition.",
    uaTokens: ["На", "змагання", "зареєструвалося", "багато", "команд", "."],
    ruTokens: ["На", "соревнование", "зарегистрировалось", "много", "команд", "."],
    enTokens: ["Many", "teams", "registered", "for", "the", "competition", "."],
    extraUaTokens: ["гравців", "мало", "сьогодні"],
    extraRuTokens: ["игроков", "мало", "сегодня"],
    extraEnTokens: ["players", "few", "today"],
  },

  [phraseKey("divák", "b1-17")]: {
    sk: "Každý divák sledoval zápas s napětím.",
    ua: "Кожен глядач дивився матч із хвилюванням.",
    ru: "Каждый зритель смотрел матч с волнением.",
    en: "Every spectator watched the match with suspense.",
    uaTokens: ["Кожен", "глядач", "дивився", "матч", "із", "хвилюванням", "."],
    ruTokens: ["Каждый", "зритель", "смотрел", "матч", "с", "волнением", "."],
    enTokens: ["Every", "spectator", "watched", "the", "match", "with", "suspense", "."],
    extraUaTokens: ["спокоєм", "серіал", "вдома"],
    extraRuTokens: ["спокойствием", "сериал", "дома"],
    extraEnTokens: ["calm", "series", "at home"],
  },

  [phraseKey("tým", "b1-17")]: {
    sk: "Náš tým dnes hrál velmi dobře.",
    ua: "Наша команда сьогодні грала дуже добре.",
    ru: "Наша команда сегодня играла очень хорошо.",
    en: "Our team played very well today.",
    uaTokens: ["Наша", "команда", "сьогодні", "грала", "дуже", "добре", "."],
    ruTokens: ["Наша", "команда", "сегодня", "играла", "очень", "хорошо", "."],
    enTokens: ["Our", "team", "played", "very", "well", "today", "."],
    extraUaTokens: ["погано", "учора", "вдома"],
    extraRuTokens: ["плохо", "вчера", "дома"],
    extraEnTokens: ["badly", "yesterday", "at home"],
  },

  [phraseKey("výkon", "b1-17")]: {
    sk: "Jeho výkon ocenili i soupeři.",
    ua: "Його виступ оцінили навіть суперники.",
    ru: "Его выступление оценили даже соперники.",
    en: "Even the opponents appreciated his performance.",
    uaTokens: ["Його", "виступ", "оцінили", "навіть", "суперники", "."],
    ruTokens: ["Его", "выступление", "оценили", "даже", "соперники", "."],
    enTokens: ["Even", "the", "opponents", "appreciated", "his", "performance", "."],
    extraUaTokens: ["тренери", "не", "помітили"],
    extraRuTokens: ["тренеры", "не", "заметили"],
    extraEnTokens: ["coaches", "not", "noticed"],
  },

  [phraseKey("zranění", "b1-17")]: {
    sk: "Kvůli zranění nebude několik týdnů hrát.",
    ua: "Через травму він не гратиме кілька тижнів.",
    ru: "Из-за травмы он не будет играть несколько недель.",
    en: "Because of the injury, he will not play for several weeks.",
    uaTokens: ["Через", "травму", "він", "не", "гратиме", "кілька", "тижнів", "."],
    ruTokens: ["Из-за", "травмы", "он", "не", "будет", "играть", "несколько", "недель", "."],
    enTokens: ["Because", "of", "the", "injury", ",", "he", "will", "not", "play", "for", "several", "weeks", "."],
    extraUaTokens: ["матч", "завтра", "точно"],
    extraRuTokens: ["матч", "завтра", "точно"],
    extraEnTokens: ["match", "tomorrow", "definitely"],
  },

  // =========================
  // LESSON B1-18 — Географія
  // =========================
  [phraseKey("kontinent", "b1-18")]: {
    sk: "Afrika je velmi rozmanitý kontinent.",
    ua: "Африка — дуже різноманітний континент.",
    ru: "Африка — очень разнообразный континент.",
    en: "Africa is a very diverse continent.",
    uaTokens: ["Африка", "—", "дуже", "різноманітний", "континент", "."],
    ruTokens: ["Африка", "—", "очень", "разнообразный", "континент", "."],
    enTokens: ["Africa", "is", "a", "very", "diverse", "continent", "."],
    extraUaTokens: ["країна", "місто", "сьогодні"],
    extraRuTokens: ["страна", "город", "сегодня"],
    extraEnTokens: ["country", "city", "today"],
  },

  [phraseKey("hranice", "b1-18")]: {
    sk: "Hranice mezi státy je dobře označená.",
    ua: "Кордон між державами добре позначений.",
    ru: "Граница между государствами хорошо обозначена.",
    en: "The border between states is clearly marked.",
    uaTokens: ["Кордон", "між", "державами", "добре", "позначений", "."],
    ruTokens: ["Граница", "между", "государствами", "хорошо", "обозначена", "."],
    enTokens: ["The", "border", "between", "states", "is", "clearly", "marked", "."],
    extraUaTokens: ["містами", "погано", "схований"],
    extraRuTokens: ["городами", "плохо", "спрятана"],
    extraEnTokens: ["cities", "badly", "hidden"],
  },

  [phraseKey("obyvatelstvo", "b1-18")]: {
    sk: "Obyvatelstvo velkých měst stále roste.",
    ua: "Населення великих міст постійно зростає.",
    ru: "Население больших городов постоянно растёт.",
    en: "The population of big cities is constantly growing.",
    uaTokens: ["Населення", "великих", "міст", "постійно", "зростає", "."],
    ruTokens: ["Население", "больших", "городов", "постоянно", "растёт", "."],
    enTokens: ["The", "population", "of", "big", "cities", "is", "constantly", "growing", "."],
    extraUaTokens: ["сіл", "зменшується", "вчора"],
    extraRuTokens: ["сёл", "уменьшается", "вчера"],
    extraEnTokens: ["villages", "decreases", "yesterday"],
  },

  [phraseKey("podnebí", "b1-18")]: {
    sk: "Místní podnebí je suché a teplé.",
    ua: "Місцевий клімат сухий і теплий.",
    ru: "Местный климат сухой и тёплый.",
    en: "The local climate is dry and warm.",
    uaTokens: ["Місцевий", "клімат", "сухий", "і", "теплий", "."],
    ruTokens: ["Местный", "климат", "сухой", "и", "тёплый", "."],
    enTokens: ["The", "local", "climate", "is", "dry", "and", "warm", "."],
    extraUaTokens: ["вологий", "холодний", "узимку"],
    extraRuTokens: ["влажный", "холодный", "зимой"],
    extraEnTokens: ["humid", "cold", "in winter"],
  },

  [phraseKey("hlavní město", "b1-18")]: {
    sk: "Praha je hlavní město České republiky.",
    ua: "Прага — столиця Чеської Республіки.",
    ru: "Прага — столица Чешской Республики.",
    en: "Prague is the capital of the Czech Republic.",
    uaTokens: ["Прага", "—", "столиця", "Чеської", "Республіки", "."],
    ruTokens: ["Прага", "—", "столица", "Чешской", "Республики", "."],
    enTokens: ["Prague", "is", "the", "capital", "of", "the", "Czech", "Republic", "."],
    extraUaTokens: ["місто", "Словаччини", "учора"],
    extraRuTokens: ["город", "Словакии", "вчера"],
    extraEnTokens: ["city", "Slovakia", "yesterday"],
  },

  [phraseKey("povrch", "b1-18")]: {
    sk: "Povrch této oblasti je převážně hornatý.",
    ua: "Поверхня цієї території переважно гірська.",
    ru: "Поверхность этой области преимущественно гористая.",
    en: "The surface of this area is mostly mountainous.",
    uaTokens: ["Поверхня", "цієї", "території", "переважно", "гірська", "."],
    ruTokens: ["Поверхность", "этой", "области", "преимущественно", "гористая", "."],
    enTokens: ["The", "surface", "of", "this", "area", "is", "mostly", "mountainous", "."],
    extraUaTokens: ["рівнинна", "місцевість", "уздовж"],
    extraRuTokens: ["равнинная", "местность", "вдоль"],
    extraEnTokens: ["flat", "terrain", "along"],
  },

  [phraseKey("pobřeží", "b1-18")]: {
    sk: "Na pobřeží bývá v létě hodně turistů.",
    ua: "На узбережжі влітку буває багато туристів.",
    ru: "На побережье летом бывает много туристов.",
    en: "There are many tourists on the coast in summer.",
    uaTokens: ["На", "узбережжі", "влітку", "буває", "багато", "туристів", "."],
    ruTokens: ["На", "побережье", "летом", "бывает", "много", "туристов", "."],
    enTokens: ["There", "are", "many", "tourists", "on", "the", "coast", "in", "summer", "."],
    extraUaTokens: ["взимку", "місцевих", "людей"],
    extraRuTokens: ["зимой", "местных", "людей"],
    extraEnTokens: ["in winter", "local", "people"],
  },

  [phraseKey("ostrov", "b1-18")]: {
    sk: "Na malém ostrově žije jen pár lidí.",
    ua: "На маленькому острові живе лише кілька людей.",
    ru: "На маленьком острове живёт всего несколько человек.",
    en: "Only a few people live on the small island.",
    uaTokens: ["На", "маленькому", "острові", "живе", "лише", "кілька", "людей", "."],
    ruTokens: ["На", "маленьком", "острове", "живёт", "всего", "несколько", "человек", "."],
    enTokens: ["Only", "a", "few", "people", "live", "on", "the", "small", "island", "."],
    extraUaTokens: ["тисяч", "місті", "сьогодні"],
    extraRuTokens: ["тысяч", "городе", "сегодня"],
    extraEnTokens: ["thousands", "city", "today"],
  },

  [phraseKey("vnitrozemí", "b1-18")]: {
    sk: "Ve vnitrozemí bývá chladněji než u moře.",
    ua: "У внутрішніх районах буває холодніше, ніж біля моря.",
    ru: "Во внутренних районах бывает холоднее, чем у моря.",
    en: "It is usually colder inland than by the sea.",
    uaTokens: ["У", "внутрішніх", "районах", "буває", "холодніше", ",", "ніж", "біля", "моря", "."],
    ruTokens: ["Во", "внутренних", "районах", "бывает", "холоднее", ",", "чем", "у", "моря", "."],
    enTokens: ["It", "is", "usually", "colder", "inland", "than", "by", "the", "sea", "."],
    extraUaTokens: ["тепліше", "влітку", "завжди"],
    extraRuTokens: ["теплее", "летом", "всегда"],
    extraEnTokens: ["warmer", "in summer", "always"],
  },

  [phraseKey("zeměpis", "b1-18")]: {
    sk: "Zeměpis patřil ve škole k mým oblíbeným předmětům.",
    ua: "Географія в школі була одним із моїх улюблених предметів.",
    ru: "География в школе была одним из моих любимых предметов.",
    en: "Geography was one of my favorite subjects at school.",
    uaTokens: ["Географія", "в", "школі", "була", "одним", "із", "моїх", "улюблених", "предметів", "."],
    ruTokens: ["География", "в", "школе", "была", "одним", "из", "моих", "любимых", "предметов", "."],
    enTokens: ["Geography", "was", "one", "of", "my", "favorite", "subjects", "at", "school", "."],
    extraUaTokens: ["математика", "нудних", "уроків"],
    extraRuTokens: ["математика", "скучных", "уроков"],
    extraEnTokens: ["math", "boring", "lessons"],
  },

  // =========================
  // LESSON B1-19 — Математика
  // =========================
  [phraseKey("rovnice", "b1-19")]: {
    sk: "Tuto rovnici jsme řešili ve škole.",
    ua: "Це рівняння ми розв’язували в школі.",
    ru: "Это уравнение мы решали в школе.",
    en: "We solved this equation at school.",
    uaTokens: ["Це", "рівняння", "ми", "розв’язували", "в", "школі", "."],
    ruTokens: ["Это", "уравнение", "мы", "решали", "в", "школе", "."],
    enTokens: ["We", "solved", "this", "equation", "at", "school", "."],
    extraUaTokens: ["вдома", "задачу", "учора"],
    extraRuTokens: ["дома", "задачу", "вчера"],
    extraEnTokens: ["at home", "problem", "yesterday"],
  },

  [phraseKey("výsledek", "b1-19")]: {
    sk: "Výsledek příkladu si raději zkontroluj.",
    ua: "Результат прикладу краще перевір.",
    ru: "Результат примера лучше проверь.",
    en: "You should check the result of the example again.",
    uaTokens: ["Результат", "прикладу", "краще", "перевір", "."],
    ruTokens: ["Результат", "примера", "лучше", "проверь", "."],
    enTokens: ["You", "should", "check", "the", "result", "of", "the", "example", "again", "."],
    extraUaTokens: ["відповідь", "потім", "вчора"],
    extraRuTokens: ["ответ", "потом", "вчера"],
    extraEnTokens: ["answer", "later", "yesterday"],
  },

  [phraseKey("násobit", "b1-19")]: {
    sk: "Nejdřív budeme násobit a pak sčítat.",
    ua: "Спочатку будемо множити, а потім додавати.",
    ru: "Сначала будем умножать, а потом складывать.",
    en: "First we will multiply and then add.",
    uaTokens: ["Спочатку", "будемо", "множити", ",", "а", "потім", "додавати", "."],
    ruTokens: ["Сначала", "будем", "умножать", ",", "а", "потом", "складывать", "."],
    enTokens: ["First", "we", "will", "multiply", "and", "then", "add", "."],
    extraUaTokens: ["ділити", "віднімати", "завтра"],
    extraRuTokens: ["делить", "вычитать", "завтра"],
    extraEnTokens: ["divide", "subtract", "tomorrow"],
  },

  [phraseKey("dělit", "b1-19")]: {
    sk: "Toto číslo nelze dělit nulou.",
    ua: "Це число не можна ділити на нуль.",
    ru: "Это число нельзя делить на ноль.",
    en: "This number cannot be divided by zero.",
    uaTokens: ["Це", "число", "не", "можна", "ділити", "на", "нуль", "."],
    ruTokens: ["Это", "число", "нельзя", "делить", "на", "ноль", "."],
    enTokens: ["This", "number", "cannot", "be", "divided", "by", "zero", "."],
    extraUaTokens: ["одиницю", "легко", "вчора"],
    extraRuTokens: ["единицу", "легко", "вчера"],
    extraEnTokens: ["one", "easily", "yesterday"],
  },

  [phraseKey("odčíst", "b1-19")]: {
    sk: "Od celku musíme ještě něco odčíst.",
    ua: "Від цілого ми ще повинні щось відняти.",
    ru: "От целого мы ещё должны что-то вычесть.",
    en: "We still have to subtract something from the whole.",
    uaTokens: ["Від", "цілого", "ми", "ще", "повинні", "щось", "відняти", "."],
    ruTokens: ["От", "целого", "мы", "ещё", "должны", "что-то", "вычесть", "."],
    enTokens: ["We", "still", "have", "to", "subtract", "something", "from", "the", "whole", "."],
    extraUaTokens: ["додати", "потім", "число"],
    extraRuTokens: ["добавить", "потом", "число"],
    extraEnTokens: ["add", "later", "number"],
  },

  [phraseKey("sečíst", "b1-19")]: {
    sk: "Umíš rychle sečíst tato dvě čísla?",
    ua: "Ти вмієш швидко додати ці два числа?",
    ru: "Ты умеешь быстро сложить эти два числа?",
    en: "Can you quickly add these two numbers?",
    uaTokens: ["Ти", "вмієш", "швидко", "додати", "ці", "два", "числа", "?"],
    ruTokens: ["Ты", "умеешь", "быстро", "сложить", "эти", "два", "числа", "?"],
    enTokens: ["Can", "you", "quickly", "add", "these", "two", "numbers", "?"],
    extraUaTokens: ["відняти", "три", "завтра"],
    extraRuTokens: ["вычесть", "три", "завтра"],
    extraEnTokens: ["subtract", "three", "tomorrow"],
  },

  [phraseKey("zlomek", "b1-19")]: {
    sk: "Tento zlomek se dá ještě zkrátit.",
    ua: "Цей дріб ще можна скоротити.",
    ru: "Эту дробь ещё можно сократить.",
    en: "This fraction can still be reduced.",
    uaTokens: ["Цей", "дріб", "ще", "можна", "скоротити", "."],
    ruTokens: ["Эту", "дробь", "ещё", "можно", "сократить", "."],
    enTokens: ["This", "fraction", "can", "still", "be", "reduced", "."],
    extraUaTokens: ["розширити", "формулу", "вчора"],
    extraRuTokens: ["расширить", "формулу", "вчера"],
    extraEnTokens: ["expand", "formula", "yesterday"],
  },

  [phraseKey("procento", "b1-19")]: {
    sk: "Jedno procento z této částky není moc.",
    ua: "Один відсоток від цієї суми — це небагато.",
    ru: "Один процент от этой суммы — это немного.",
    en: "One percent of this amount is not much.",
    uaTokens: ["Один", "відсоток", "від", "цієї", "суми", "—", "це", "небагато", "."],
    ruTokens: ["Один", "процент", "от", "этой", "суммы", "—", "это", "немного", "."],
    enTokens: ["One", "percent", "of", "this", "amount", "is", "not", "much", "."],
    extraUaTokens: ["багато", "два", "числа"],
    extraRuTokens: ["много", "два", "числа"],
    extraEnTokens: ["much", "two", "numbers"],
  },

  [phraseKey("graf", "b1-19")]: {
    sk: "Graf jasně ukazuje růst cen.",
    ua: "Графік чітко показує зростання цін.",
    ru: "График ясно показывает рост цен.",
    en: "The graph clearly shows the rise in prices.",
    uaTokens: ["Графік", "чітко", "показує", "зростання", "цін", "."],
    ruTokens: ["График", "ясно", "показывает", "рост", "цен", "."],
    enTokens: ["The", "graph", "clearly", "shows", "the", "rise", "in", "prices", "."],
    extraUaTokens: ["падіння", "зарплат", "учора"],
    extraRuTokens: ["падение", "зарплат", "вчера"],
    extraEnTokens: ["drop", "salaries", "yesterday"],
  },

  [phraseKey("vypočítat", "b1-19")]: {
    sk: "Dokážeš vypočítat přesný výsledek?",
    ua: "Ти можеш обчислити точний результат?",
    ru: "Ты можешь вычислить точный результат?",
    en: "Can you calculate the exact result?",
    uaTokens: ["Ти", "можеш", "обчислити", "точний", "результат", "?"],
    ruTokens: ["Ты", "можешь", "вычислить", "точный", "результат", "?"],
    enTokens: ["Can", "you", "calculate", "the", "exact", "result", "?"],
    extraUaTokens: ["приблизний", "приклад", "завтра"],
    extraRuTokens: ["примерный", "пример", "завтра"],
    extraEnTokens: ["approximate", "example", "tomorrow"],
  },

  // =========================
  // LESSON B1-20 — Держава та суспільство
  // =========================
  [phraseKey("zákon", "b1-20")]: {
    sk: "Každý občan by měl dodržovat zákon.",
    ua: "Кожен громадянин повинен дотримуватися закону.",
    ru: "Каждый гражданин должен соблюдать закон.",
    en: "Every citizen should obey the law.",
    uaTokens: ["Кожен", "громадянин", "повинен", "дотримуватися", "закону", "."],
    ruTokens: ["Каждый", "гражданин", "должен", "соблюдать", "закон", "."],
    enTokens: ["Every", "citizen", "should", "obey", "the", "law", "."],
    extraUaTokens: ["порядку", "правил", "сьогодні"],
    extraRuTokens: ["порядок", "правила", "сегодня"],
    extraEnTokens: ["order", "rules", "today"],
  },

  [phraseKey("volby", "b1-20")]: {
    sk: "Volby se budou konat příští měsíc.",
    ua: "Вибори відбудуться наступного місяця.",
    ru: "Выборы состоятся в следующем месяце.",
    en: "The elections will take place next month.",
    uaTokens: ["Вибори", "відбудуться", "наступного", "місяця", "."],
    ruTokens: ["Выборы", "состоятся", "в", "следующем", "месяце", "."],
    enTokens: ["The", "elections", "will", "take", "place", "next", "month", "."],
    extraUaTokens: ["тижня", "завтра", "вчора"],
    extraRuTokens: ["неделе", "завтра", "вчера"],
    extraEnTokens: ["week", "tomorrow", "yesterday"],
  },

  [phraseKey("vláda", "b1-20")]: {
    sk: "Vláda představila nový plán reforem.",
    ua: "Уряд представив новий план реформ.",
    ru: "Правительство представило новый план реформ.",
    en: "The government presented a new reform plan.",
    uaTokens: ["Уряд", "представив", "новий", "план", "реформ", "."],
    ruTokens: ["Правительство", "представило", "новый", "план", "реформ", "."],
    enTokens: ["The", "government", "presented", "a", "new", "reform", "plan", "."],
    extraUaTokens: ["старий", "закон", "учора"],
    extraRuTokens: ["старый", "закон", "вчера"],
    extraEnTokens: ["old", "law", "yesterday"],
  },

  [phraseKey("občan", "b1-20")]: {
    sk: "Každý občan má svá práva i povinnosti.",
    ua: "Кожен громадянин має свої права й обов’язки.",
    ru: "Каждый гражданин имеет свои права и обязанности.",
    en: "Every citizen has rights and responsibilities.",
    uaTokens: ["Кожен", "громадянин", "має", "свої", "права", "й", "обов’язки", "."],
    ruTokens: ["Каждый", "гражданин", "имеет", "свои", "права", "и", "обязанности", "."],
    enTokens: ["Every", "citizen", "has", "rights", "and", "responsibilities", "."],
    extraUaTokens: ["мрію", "роботу", "сьогодні"],
    extraRuTokens: ["мечту", "работу", "сегодня"],
    extraEnTokens: ["dream", "job", "today"],
  },

  [phraseKey("parlament", "b1-20")]: {
    sk: "O návrhu bude rozhodovat parlament.",
    ua: "Щодо цієї пропозиції вирішуватиме парламент.",
    ru: "По этому предложению будет решать парламент.",
    en: "Parliament will decide on this proposal.",
    uaTokens: ["Щодо", "цієї", "пропозиції", "вирішуватиме", "парламент", "."],
    ruTokens: ["По", "этому", "предложению", "будет", "решать", "парламент", "."],
    enTokens: ["Parliament", "will", "decide", "on", "this", "proposal", "."],
    extraUaTokens: ["уряд", "місто", "вчора"],
    extraRuTokens: ["правительство", "город", "вчера"],
    extraEnTokens: ["government", "city", "yesterday"],
  },

  [phraseKey("prezident", "b1-20")]: {
    sk: "Prezident vystoupil s projevem v televizi.",
    ua: "Президент виступив із промовою по телебаченню.",
    ru: "Президент выступил с речью по телевидению.",
    en: "The president gave a speech on television.",
    uaTokens: ["Президент", "виступив", "із", "промовою", "по", "телебаченню", "."],
    ruTokens: ["Президент", "выступил", "с", "речью", "по", "телевидению", "."],
    enTokens: ["The", "president", "gave", "a", "speech", "on", "television", "."],
    extraUaTokens: ["інтерв’ю", "вчора", "газеті"],
    extraRuTokens: ["интервью", "вчера", "газете"],
    extraEnTokens: ["interview", "yesterday", "newspaper"],
  },

  [phraseKey("ústava", "b1-20")]: {
    sk: "Ústava určuje základní pravidla státu.",
    ua: "Конституція визначає основні правила держави.",
    ru: "Конституция определяет основные правила государства.",
    en: "The constitution defines the basic rules of the state.",
    uaTokens: ["Конституція", "визначає", "основні", "правила", "держави", "."],
    ruTokens: ["Конституция", "определяет", "основные", "правила", "государства", "."],
    enTokens: ["The", "constitution", "defines", "the", "basic", "rules", "of", "the", "state", "."],
    extraUaTokens: ["міста", "звички", "вчора"],
    extraRuTokens: ["города", "привычки", "вчера"],
    extraEnTokens: ["city", "habits", "yesterday"],
  },

  [phraseKey("ministerstvo", "b1-20")]: {
    sk: "Ministerstvo zveřejnilo nové informace.",
    ua: "Міністерство опублікувало нову інформацію.",
    ru: "Министерство опубликовало новую информацию.",
    en: "The ministry published new information.",
    uaTokens: ["Міністерство", "опублікувало", "нову", "інформацію", "."],
    ruTokens: ["Министерство", "опубликовало", "новую", "информацию", "."],
    enTokens: ["The", "ministry", "published", "new", "information", "."],
    extraUaTokens: ["стару", "новину", "сьогодні"],
    extraRuTokens: ["старую", "новость", "сегодня"],
    extraEnTokens: ["old", "news", "today"],
  },

  [phraseKey("referendum", "b1-20")]: {
    sk: "O této otázce může rozhodnout referendum.",
    ua: "Це питання може вирішити референдум.",
    ru: "Этот вопрос может решить референдум.",
    en: "This issue can be decided by a referendum.",
    uaTokens: ["Це", "питання", "може", "вирішити", "референдум", "."],
    ruTokens: ["Этот", "вопрос", "может", "решить", "референдум", "."],
    enTokens: ["This", "issue", "can", "be", "decided", "by", "a", "referendum", "."],
    extraUaTokens: ["парламент", "уряд", "вчора"],
    extraRuTokens: ["парламент", "правительство", "вчера"],
    extraEnTokens: ["parliament", "government", "yesterday"],
  },

  [phraseKey("státní správa", "b1-20")]: {
    sk: "Státní správa musí fungovat efektivně.",
    ua: "Державне управління повинно працювати ефективно.",
    ru: "Государственное управление должно работать эффективно.",
    en: "Public administration must work efficiently.",
    uaTokens: ["Державне", "управління", "повинно", "працювати", "ефективно", "."],
    ruTokens: ["Государственное", "управление", "должно", "работать", "эффективно", "."],
    enTokens: ["Public", "administration", "must", "work", "efficiently", "."],
    extraUaTokens: ["повільно", "хаотично", "сьогодні"],
    extraRuTokens: ["медленно", "хаотично", "сегодня"],
    extraEnTokens: ["slowly", "chaotically", "today"],
  },
};