import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_B1_BUILD_UA_SENTENCES_7: BuildUaSentenceDict = {
  // =========================
  // LESSON B1-31 — Країни (світ)
  // =========================
  [phraseKey("Spojené státy", "b1-31")]: {
    sk: "Spojené státy patří mezi největší země světa.",
    ua: "США належать до найбільших країн світу.",
    ru: "США относятся к крупнейшим странам мира.",
    en: "The United States is one of the largest countries in the world.",
    uaTokens: ["США", "належать", "до", "найбільших", "країн", "світу", "."],
    ruTokens: ["США", "относятся", "к", "крупнейшим", "странам", "мира", "."],
    enTokens: ["The", "United", "States", "is", "one", "of", "the", "largest", "countries", "in", "the", "world", "."],
    extraUaTokens: ["міст", "Європи", "сьогодні"],
    extraRuTokens: ["городам", "Европы", "сегодня"],
    extraEnTokens: ["cities", "Europe", "today"],
  },

  [phraseKey("Velká Británie", "b1-31")]: {
    sk: "Velká Británie je známá svou historií a tradicemi.",
    ua: "Велика Британія відома своєю історією та традиціями.",
    ru: "Великобритания известна своей историей и традициями.",
    en: "Great Britain is known for its history and traditions.",
    uaTokens: ["Велика", "Британія", "відома", "своєю", "історією", "та", "традиціями", "."],
    ruTokens: ["Великобритания", "известна", "своей", "историей", "и", "традициями", "."],
    enTokens: ["Great", "Britain", "is", "known", "for", "its", "history", "and", "traditions", "."],
    extraUaTokens: ["культурою", "спортом", "вчора"],
    extraRuTokens: ["культурой", "спортом", "вчера"],
    extraEnTokens: ["culture", "sports", "yesterday"],
  },

  [phraseKey("Kanada", "b1-31")]: {
    sk: "Kanada je oblíbená pro svou přírodu a kvalitu života.",
    ua: "Канада популярна завдяки своїй природі та якості життя.",
    ru: "Канада популярна благодаря своей природе и качеству жизни.",
    en: "Canada is popular for its nature and quality of life.",
    uaTokens: ["Канада", "популярна", "завдяки", "своїй", "природі", "та", "якості", "життя", "."],
    ruTokens: ["Канада", "популярна", "благодаря", "своей", "природе", "и", "качеству", "жизни", "."],
    enTokens: ["Canada", "is", "popular", "for", "its", "nature", "and", "quality", "of", "life", "."],
    extraUaTokens: ["роботі", "містам", "сьогодні"],
    extraRuTokens: ["работе", "городам", "сегодня"],
    extraEnTokens: ["work", "cities", "today"],
  },

  [phraseKey("Švýcarsko", "b1-31")]: {
    sk: "Švýcarsko je známé horami a vysokou životní úrovní.",
    ua: "Швейцарія відома горами та високим рівнем життя.",
    ru: "Швейцария известна горами и высоким уровнем жизни.",
    en: "Switzerland is known for its mountains and high standard of living.",
    uaTokens: ["Швейцарія", "відома", "горами", "та", "високим", "рівнем", "життя", "."],
    ruTokens: ["Швейцария", "известна", "горами", "и", "высоким", "уровнем", "жизни", "."],
    enTokens: ["Switzerland", "is", "known", "for", "its", "mountains", "and", "high", "standard", "of", "living", "."],
    extraUaTokens: ["морем", "кліматом", "вчора"],
    extraRuTokens: ["морем", "климатом", "вчера"],
    extraEnTokens: ["sea", "climate", "yesterday"],
  },

  [phraseKey("Nizozemsko", "b1-31")]: {
    sk: "V Nizozemsku lidé často jezdí na kole.",
    ua: "У Нідерландах люди часто їздять на велосипеді.",
    ru: "В Нидерландах люди часто ездят на велосипеде.",
    en: "In the Netherlands, people often ride bicycles.",
    uaTokens: ["У", "Нідерландах", "люди", "часто", "їздять", "на", "велосипеді", "."],
    ruTokens: ["В", "Нидерландах", "люди", "часто", "ездят", "на", "велосипеде", "."],
    enTokens: ["In", "the", "Netherlands", ",", "people", "often", "ride", "bicycles", "."],
    extraUaTokens: ["машині", "рідко", "вчора"],
    extraRuTokens: ["машине", "редко", "вчера"],
    extraEnTokens: ["car", "rarely", "yesterday"],
  },

  [phraseKey("Belgie", "b1-31")]: {
    sk: "Belgie je známá čokoládou a evropskými institucemi.",
    ua: "Бельгія відома шоколадом та європейськими інституціями.",
    ru: "Бельгия известна шоколадом и европейскими институтами.",
    en: "Belgium is known for chocolate and European institutions.",
    uaTokens: ["Бельгія", "відома", "шоколадом", "та", "європейськими", "інституціями", "."],
    ruTokens: ["Бельгия", "известна", "шоколадом", "и", "европейскими", "институтами", "."],
    enTokens: ["Belgium", "is", "known", "for", "chocolate", "and", "European", "institutions", "."],
    extraUaTokens: ["музеями", "спортом", "сьогодні"],
    extraRuTokens: ["музеями", "спортом", "сегодня"],
    extraEnTokens: ["museums", "sports", "today"],
  },

  [phraseKey("Švédsko", "b1-31")]: {
    sk: "Švédsko patří mezi severské státy.",
    ua: "Швеція належить до скандинавських країн.",
    ru: "Швеция относится к скандинавским странам.",
    en: "Sweden belongs to the Nordic countries.",
    uaTokens: ["Швеція", "належить", "до", "скандинавських", "країн", "."],
    ruTokens: ["Швеция", "относится", "к", "скандинавским", "странам", "."],
    enTokens: ["Sweden", "belongs", "to", "the", "Nordic", "countries", "."],
    extraUaTokens: ["південних", "міст", "вчора"],
    extraRuTokens: ["южным", "городам", "вчера"],
    extraEnTokens: ["southern", "cities", "yesterday"],
  },

  [phraseKey("Rusko", "b1-31")]: {
    sk: "Rusko je rozlohou velmi velká země.",
    ua: "Росія є дуже великою за площею країною.",
    ru: "Россия — очень большая по площади страна.",
    en: "Russia is a very large country by area.",
    uaTokens: ["Росія", "є", "дуже", "великою", "за", "площею", "країною", "."],
    ruTokens: ["Россия", "—", "очень", "большая", "по", "площади", "страна", "."],
    enTokens: ["Russia", "is", "a", "very", "large", "country", "by", "area", "."],
    extraUaTokens: ["маленькою", "державою", "сьогодні"],
    extraRuTokens: ["маленькая", "страна", "сегодня"],
    extraEnTokens: ["small", "state", "today"],
  },

  [phraseKey("Rumunsko", "b1-31")]: {
    sk: "Rumunsko leží v jihovýchodní Evropě.",
    ua: "Румунія лежить у південно-східній Європі.",
    ru: "Румыния находится в юго-восточной Европе.",
    en: "Romania is located in southeastern Europe.",
    uaTokens: ["Румунія", "лежить", "у", "південно-східній", "Європі", "."],
    ruTokens: ["Румыния", "находится", "в", "юго-восточной", "Европе", "."],
    enTokens: ["Romania", "is", "located", "in", "southeastern", "Europe", "."],
    extraUaTokens: ["західній", "Азії", "вчора"],
    extraRuTokens: ["западной", "Азии", "вчера"],
    extraEnTokens: ["western", "Asia", "yesterday"],
  },

  [phraseKey("Bulharsko", "b1-31")]: {
    sk: "Bulharsko je oblíbenou letní destinací.",
    ua: "Болгарія є популярним літнім напрямком.",
    ru: "Болгария — популярное летнее направление.",
    en: "Bulgaria is a popular summer destination.",
    uaTokens: ["Болгарія", "є", "популярним", "літнім", "напрямком", "."],
    ruTokens: ["Болгария", "—", "популярное", "летнее", "направление", "."],
    enTokens: ["Bulgaria", "is", "a", "popular", "summer", "destination", "."],
    extraUaTokens: ["зимовим", "курортом", "сьогодні"],
    extraRuTokens: ["зимним", "курортом", "сегодня"],
    extraEnTokens: ["winter", "resort", "today"],
  },

  // =========================
  // LESSON B1-32 — Релігія (Християнство)
  // =========================
  [phraseKey("křesťanství", "b1-32")]: {
    sk: "Křesťanství je jedno z nejrozšířenějších náboženství.",
    ua: "Християнство — одна з найпоширеніших релігій.",
    ru: "Христианство — одна из самых распространённых религий.",
    en: "Christianity is one of the most widespread religions.",
    uaTokens: ["Християнство", "—", "одна", "з", "найпоширеніших", "релігій", "."],
    ruTokens: ["Христианство", "—", "одна", "из", "самых", "распространённых", "религий", "."],
    enTokens: ["Christianity", "is", "one", "of", "the", "most", "widespread", "religions", "."],
    extraUaTokens: ["традицій", "книг", "вчора"],
    extraRuTokens: ["традиций", "книг", "вчера"],
    extraEnTokens: ["traditions", "books", "yesterday"],
  },

  [phraseKey("Bůh", "b1-32")]: {
    sk: "Mnoho lidí věří v Boha.",
    ua: "Багато людей вірять у Бога.",
    ru: "Многие люди верят в Бога.",
    en: "Many people believe in God.",
    uaTokens: ["Багато", "людей", "вірять", "у", "Бога", "."],
    ruTokens: ["Многие", "люди", "верят", "в", "Бога", "."],
    enTokens: ["Many", "people", "believe", "in", "God", "."],
    extraUaTokens: ["себе", "вчора", "тільки"],
    extraRuTokens: ["себя", "вчера", "только"],
    extraEnTokens: ["themselves", "yesterday", "only"],
  },

  [phraseKey("Ježíš Kristus", "b1-32")]: {
    sk: "Ježíš Kristus je ústřední postavou křesťanství.",
    ua: "Ісус Христос є центральною постаттю християнства.",
    ru: "Иисус Христос является центральной фигурой христианства.",
    en: "Jesus Christ is the central figure of Christianity.",
    uaTokens: ["Ісус", "Христос", "є", "центральною", "постаттю", "християнства", "."],
    ruTokens: ["Иисус", "Христос", "является", "центральной", "фигурой", "христианства", "."],
    enTokens: ["Jesus", "Christ", "is", "the", "central", "figure", "of", "Christianity", "."],
    extraUaTokens: ["історії", "культури", "сьогодні"],
    extraRuTokens: ["истории", "культуры", "сегодня"],
    extraEnTokens: ["history", "culture", "today"],
  },

  [phraseKey("Bible", "b1-32")]: {
    sk: "Bible je pro křesťany svatá kniha.",
    ua: "Біблія є для християн священною книгою.",
    ru: "Библия для христиан — священная книга.",
    en: "The Bible is a holy book for Christians.",
    uaTokens: ["Біблія", "є", "для", "християн", "священною", "книгою", "."],
    ruTokens: ["Библия", "для", "христиан", "—", "священная", "книга", "."],
    enTokens: ["The", "Bible", "is", "a", "holy", "book", "for", "Christians", "."],
    extraUaTokens: ["історією", "звичкою", "вчора"],
    extraRuTokens: ["историей", "привычкой", "вчера"],
    extraEnTokens: ["history", "habit", "yesterday"],
  },

  [phraseKey("církev", "b1-32")]: {
    sk: "V neděli šli spolu do církve.",
    ua: "У неділю вони разом пішли до храму.",
    ru: "В воскресенье они вместе пошли в церковь.",
    en: "On Sunday, they went to church together.",
    uaTokens: ["У", "неділю", "вони", "разом", "пішли", "до", "храму", "."],
    ruTokens: ["В", "воскресенье", "они", "вместе", "пошли", "в", "церковь", "."],
    enTokens: ["On", "Sunday", ",", "they", "went", "to", "church", "together", "."],
    extraUaTokens: ["школи", "вчора", "вранці"],
    extraRuTokens: ["школу", "вчера", "утром"],
    extraEnTokens: ["school", "yesterday", "morning"],
  },

  [phraseKey("modlitba", "b1-32")]: {
    sk: "Večer si našel čas na tichou modlitbu.",
    ua: "Увечері він знайшов час на тиху молитву.",
    ru: "Вечером он нашёл время на тихую молитву.",
    en: "In the evening, he found time for a quiet prayer.",
    uaTokens: ["Увечері", "він", "знайшов", "час", "на", "тиху", "молитву", "."],
    ruTokens: ["Вечером", "он", "нашёл", "время", "на", "тихую", "молитву", "."],
    enTokens: ["In", "the", "evening", ",", "he", "found", "time", "for", "a", "quiet", "prayer", "."],
    extraUaTokens: ["розмову", "вчора", "голосну"],
    extraRuTokens: ["разговор", "вчера", "громкий"],
    extraEnTokens: ["conversation", "yesterday", "loud"],
  },

  [phraseKey("víra", "b1-32")]: {
    sk: "Víra mu pomáhala překonat těžké chvíle.",
    ua: "Віра допомагала йому долати важкі моменти.",
    ru: "Вера помогала ему преодолевать трудные времена.",
    en: "Faith helped him get through difficult times.",
    uaTokens: ["Віра", "допомагала", "йому", "долати", "важкі", "моменти", "."],
    ruTokens: ["Вера", "помогала", "ему", "преодолевать", "трудные", "времена", "."],
    enTokens: ["Faith", "helped", "him", "get", "through", "difficult", "times", "."],
    extraUaTokens: ["страх", "сон", "сьогодні"],
    extraRuTokens: ["страх", "сон", "сегодня"],
    extraEnTokens: ["fear", "sleep", "today"],
  },

  [phraseKey("hřích", "b1-32")]: {
    sk: "V křesťanství se hřích spojuje s porušením Boží vůle.",
    ua: "У християнстві гріх пов’язують із порушенням Божої волі.",
    ru: "В христианстве грех связывают с нарушением Божьей воли.",
    en: "In Christianity, sin is associated with breaking God’s will.",
    uaTokens: ["У", "християнстві", "гріх", "пов’язують", "із", "порушенням", "Божої", "волі", "."],
    ruTokens: ["В", "христианстве", "грех", "связывают", "с", "нарушением", "Божьей", "воли", "."],
    enTokens: ["In", "Christianity", ",", "sin", "is", "associated", "with", "breaking", "God’s", "will", "."],
    extraUaTokens: ["закону", "традиції", "вчора"],
    extraRuTokens: ["закона", "традиции", "вчера"],
    extraEnTokens: ["law", "tradition", "yesterday"],
  },

  [phraseKey("odpuštění", "b1-32")]: {
    sk: "Odpuštění může přinést vnitřní pokoj.",
    ua: "Прощення може принести внутрішній мир.",
    ru: "Прощение может принести внутренний покой.",
    en: "Forgiveness can bring inner peace.",
    uaTokens: ["Прощення", "може", "принести", "внутрішній", "мир", "."],
    ruTokens: ["Прощение", "может", "принести", "внутренний", "покой", "."],
    enTokens: ["Forgiveness", "can", "bring", "inner", "peace", "."],
    extraUaTokens: ["радість", "спокій", "сьогодні"],
    extraRuTokens: ["радость", "спокойствие", "сегодня"],
    extraEnTokens: ["joy", "calm", "today"],
  },

  [phraseKey("věčný život", "b1-32")]: {
    sk: "Křesťané věří ve věčný život.",
    ua: "Християни вірять у вічне життя.",
    ru: "Христиане верят в вечную жизнь.",
    en: "Christians believe in eternal life.",
    uaTokens: ["Християни", "вірять", "у", "вічне", "життя", "."],
    ruTokens: ["Христиане", "верят", "в", "вечную", "жизнь", "."],
    enTokens: ["Christians", "believe", "in", "eternal", "life", "."],
    extraUaTokens: ["майбутнє", "щастя", "вчора"],
    extraRuTokens: ["будущее", "счастье", "вчера"],
    extraEnTokens: ["future", "happiness", "yesterday"],
  },

  // =========================
  // LESSON B1-33 — Мова (спілкування і думки)
  // =========================
  [phraseKey("dialog", "b1-33")]: {
    sk: "Na hodině jsme četli krátký dialog.",
    ua: "На уроці ми читали короткий діалог.",
    ru: "На уроке мы читали короткий диалог.",
    en: "In class, we read a short dialogue.",
    uaTokens: ["На", "уроці", "ми", "читали", "короткий", "діалог", "."],
    ruTokens: ["На", "уроке", "мы", "читали", "короткий", "диалог", "."],
    enTokens: ["In", "class", ",", "we", "read", "a", "short", "dialogue", "."],
    extraUaTokens: ["текст", "довгий", "вчора"],
    extraRuTokens: ["текст", "длинный", "вчера"],
    extraEnTokens: ["text", "long", "yesterday"],
  },

  [phraseKey("tvrzení", "b1-33")]: {
    sk: "S tímto tvrzením úplně nesouhlasím.",
    ua: "Я не зовсім погоджуюся з цим твердженням.",
    ru: "Я не совсем согласен с этим утверждением.",
    en: "I do not completely agree with this statement.",
    uaTokens: ["Я", "не", "зовсім", "погоджуюся", "з", "цим", "твердженням", "."],
    ruTokens: ["Я", "не", "совсем", "согласен", "с", "этим", "утверждением", "."],
    enTokens: ["I", "do", "not", "completely", "agree", "with", "this", "statement", "."],
    extraUaTokens: ["думкою", "вчора", "частково"],
    extraRuTokens: ["мнением", "вчера", "частично"],
    extraEnTokens: ["opinion", "yesterday", "partly"],
  },

  [phraseKey("odstavec", "b1-33")]: {
    sk: "Každý odstavec má jednu hlavní myšlenku.",
    ua: "Кожен абзац має одну головну думку.",
    ru: "Каждый абзац имеет одну главную мысль.",
    en: "Each paragraph has one main idea.",
    uaTokens: ["Кожен", "абзац", "має", "одну", "головну", "думку", "."],
    ruTokens: ["Каждый", "абзац", "имеет", "одну", "главную", "мысль", "."],
    enTokens: ["Each", "paragraph", "has", "one", "main", "idea", "."],
    extraUaTokens: ["дві", "ідеї", "вчора"],
    extraRuTokens: ["две", "идеи", "вчера"],
    extraEnTokens: ["two", "ideas", "yesterday"],
  },

  [phraseKey("nadpis", "b1-33")]: {
    sk: "Nadpis článku musí být stručný a jasný.",
    ua: "Заголовок статті повинен бути коротким і зрозумілим.",
    ru: "Заголовок статьи должен быть коротким и ясным.",
    en: "The title of the article must be short and clear.",
    uaTokens: ["Заголовок", "статті", "повинен", "бути", "коротким", "і", "зрозумілим", "."],
    ruTokens: ["Заголовок", "статьи", "должен", "быть", "коротким", "и", "ясным", "."],
    enTokens: ["The", "title", "of", "the", "article", "must", "be", "short", "and", "clear", "."],
    extraUaTokens: ["довгим", "складним", "сьогодні"],
    extraRuTokens: ["длинным", "сложным", "сегодня"],
    extraEnTokens: ["long", "complicated", "today"],
  },

  [phraseKey("citát", "b1-33")]: {
    sk: "Na začátku textu byl zajímavý citát.",
    ua: "На початку тексту була цікава цитата.",
    ru: "В начале текста была интересная цитата.",
    en: "There was an interesting quote at the beginning of the text.",
    uaTokens: ["На", "початку", "тексту", "була", "цікава", "цитата", "."],
    ruTokens: ["В", "начале", "текста", "была", "интересная", "цитата", "."],
    enTokens: ["There", "was", "an", "interesting", "quote", "at", "the", "beginning", "of", "the", "text", "."],
    extraUaTokens: ["фраза", "вчора", "вдома"],
    extraRuTokens: ["фраза", "вчера", "дома"],
    extraEnTokens: ["phrase", "yesterday", "at"],
  },

  [phraseKey("poznámka", "b1-33")]: {
    sk: "Do sešitu jsem si napsal krátkou poznámku.",
    ua: "У зошит я записав коротку нотатку.",
    ru: "В тетрадь я записал короткую заметку.",
    en: "I wrote a short note in my notebook.",
    uaTokens: ["У", "зошит", "я", "записав", "коротку", "нотатку", "."],
    ruTokens: ["В", "тетрадь", "я", "записал", "короткую", "заметку", "."],
    enTokens: ["I", "wrote", "a", "short", "note", "in", "my", "notebook", "."],
    extraUaTokens: ["довгу", "розповідь", "вчора"],
    extraRuTokens: ["длинный", "рассказ", "вчера"],
    extraEnTokens: ["long", "story", "yesterday"],
  },

  [phraseKey("zkratka", "b1-33")]: {
    sk: "Tato zkratka se používá velmi často.",
    ua: "Це скорочення використовується дуже часто.",
    ru: "Это сокращение используется очень часто.",
    en: "This abbreviation is used very often.",
    uaTokens: ["Це", "скорочення", "використовується", "дуже", "часто", "."],
    ruTokens: ["Это", "сокращение", "используется", "очень", "часто", "."],
    enTokens: ["This", "abbreviation", "is", "used", "very", "often", "."],
    extraUaTokens: ["рідко", "вчора", "слово"],
    extraRuTokens: ["редко", "вчера", "слово"],
    extraEnTokens: ["rarely", "yesterday", "word"],
  },

  [phraseKey("pravopis", "b1-33")]: {
    sk: "Musím si ještě procvičit český pravopis.",
    ua: "Мені ще треба потренувати чеський правопис.",
    ru: "Мне ещё нужно потренировать чешское правописание.",
    en: "I still need to practice Czech spelling.",
    uaTokens: ["Мені", "ще", "треба", "потренувати", "чеський", "правопис", "."],
    ruTokens: ["Мне", "ещё", "нужно", "потренировать", "чешское", "правописание", "."],
    enTokens: ["I", "still", "need", "to", "practice", "Czech", "spelling", "."],
    extraUaTokens: ["вимову", "сьогодні", "більше"],
    extraRuTokens: ["произношение", "сегодня", "больше"],
    extraEnTokens: ["pronunciation", "today", "more"],
  },

  [phraseKey("spojit slova", "b1-33")]: {
    sk: "V tomto cvičení máme spojit slova do vět.",
    ua: "У цій вправі ми маємо поєднати слова в речення.",
    ru: "В этом упражнении мы должны соединить слова в предложения.",
    en: "In this exercise, we have to connect words into sentences.",
    uaTokens: ["У", "цій", "вправі", "ми", "маємо", "поєднати", "слова", "в", "речення", "."],
    ruTokens: ["В", "этом", "упражнении", "мы", "должны", "соединить", "слова", "в", "предложения", "."],
    enTokens: ["In", "this", "exercise", ",", "we", "have", "to", "connect", "words", "into", "sentences", "."],
    extraUaTokens: ["тексти", "вчора", "разом"],
    extraRuTokens: ["тексты", "вчера", "вместе"],
    extraEnTokens: ["texts", "yesterday", "together"],
  },

  [phraseKey("vyslovit", "b1-33")]: {
    sk: "Některá česká slova je těžké správně vyslovit.",
    ua: "Деякі чеські слова важко правильно вимовити.",
    ru: "Некоторые чешские слова трудно правильно произнести.",
    en: "Some Czech words are hard to pronounce correctly.",
    uaTokens: ["Деякі", "чеські", "слова", "важко", "правильно", "вимовити", "."],
    ruTokens: ["Некоторые", "чешские", "слова", "трудно", "правильно", "произнести", "."],
    enTokens: ["Some", "Czech", "words", "are", "hard", "to", "pronounce", "correctly", "."],
    extraUaTokens: ["записати", "легко", "вчора"],
    extraRuTokens: ["записать", "легко", "вчера"],
    extraEnTokens: ["write", "easily", "yesterday"],
  },

  // =========================
  // LESSON B1-34 — Психологія та внутрішній стан
  // =========================
  [phraseKey("sebevědomí", "b1-34")]: {
    sk: "Zdravé sebevědomí pomáhá při komunikaci s lidmi.",
    ua: "Здорова впевненість у собі допомагає у спілкуванні з людьми.",
    ru: "Здоровая уверенность в себе помогает в общении с людьми.",
    en: "Healthy self-confidence helps when communicating with people.",
    uaTokens: ["Здорова", "впевненість", "у", "собі", "допомагає", "у", "спілкуванні", "з", "людьми", "."],
    ruTokens: ["Здоровая", "уверенность", "в", "себе", "помогает", "в", "общении", "с", "людьми", "."],
    enTokens: ["Healthy", "self-confidence", "helps", "when", "communicating", "with", "people", "."],
    extraUaTokens: ["страх", "вчора", "мовчанні"],
    extraRuTokens: ["страх", "вчера", "молчании"],
    extraEnTokens: ["fear", "yesterday", "silence"],
  },

  [phraseKey("motivace", "b1-34")]: {
    sk: "Silná motivace mu pomohla pokračovat dál.",
    ua: "Сильна мотивація допомогла йому рухатися далі.",
    ru: "Сильная мотивация помогла ему двигаться дальше.",
    en: "Strong motivation helped him keep moving forward.",
    uaTokens: ["Сильна", "мотивація", "допомогла", "йому", "рухатися", "далі", "."],
    ruTokens: ["Сильная", "мотивация", "помогла", "ему", "двигаться", "дальше", "."],
    enTokens: ["Strong", "motivation", "helped", "him", "keep", "moving", "forward", "."],
    extraUaTokens: ["лінощі", "зупинитися", "вчора"],
    extraRuTokens: ["лень", "остановиться", "вчера"],
    extraEnTokens: ["laziness", "stop", "yesterday"],
  },

  [phraseKey("rozhodnost", "b1-34")]: {
    sk: "V těžkých chvílích ukázala velkou rozhodnost.",
    ua: "У важкі моменти вона показала велику рішучість.",
    ru: "В трудные моменты она показала большую решительность.",
    en: "In difficult moments, she showed great determination.",
    uaTokens: ["У", "важкі", "моменти", "вона", "показала", "велику", "рішучість", "."],
    ruTokens: ["В", "трудные", "моменты", "она", "показала", "большую", "решительность", "."],
    enTokens: ["In", "difficult", "moments", ",", "she", "showed", "great", "determination", "."],
    extraUaTokens: ["слабкість", "вчора", "інколи"],
    extraRuTokens: ["слабость", "вчера", "иногда"],
    extraEnTokens: ["weakness", "yesterday", "sometimes"],
  },

  [phraseKey("být zklamaný", "b1-34")]: {
    sk: "Je normální být někdy zklamaný.",
    ua: "Нормально іноді бути розчарованим.",
    ru: "Нормально иногда быть разочарованным.",
    en: "It is normal to be disappointed sometimes.",
    uaTokens: ["Нормально", "іноді", "бути", "розчарованим", "."],
    ruTokens: ["Нормально", "иногда", "быть", "разочарованным", "."],
    enTokens: ["It", "is", "normal", "to", "be", "disappointed", "sometimes", "."],
    extraUaTokens: ["радіти", "сьогодні", "часто"],
    extraRuTokens: ["радоваться", "сегодня", "часто"],
    extraEnTokens: ["rejoice", "today", "often"],
  },

  [phraseKey("překonat strach", "b1-34")]: {
    sk: "Musel překonat strach a udělat první krok.",
    ua: "Йому довелося подолати страх і зробити перший крок.",
    ru: "Ему пришлось преодолеть страх и сделать первый шаг.",
    en: "He had to overcome fear and take the first step.",
    uaTokens: ["Йому", "довелося", "подолати", "страх", "і", "зробити", "перший", "крок", "."],
    ruTokens: ["Ему", "пришлось", "преодолеть", "страх", "и", "сделать", "первый", "шаг", "."],
    enTokens: ["He", "had", "to", "overcome", "fear", "and", "take", "the", "first", "step", "."],
    extraUaTokens: ["паніку", "вчора", "вдома"],
    extraRuTokens: ["панику", "вчера", "дома"],
    extraEnTokens: ["panic", "yesterday", "home"],
  },

  [phraseKey("seberozvoj", "b1-34")]: {
    sk: "V poslední době se hodně věnuje seberozvoji.",
    ua: "Останнім часом він багато уваги приділяє саморозвитку.",
    ru: "В последнее время он много внимания уделяет саморазвитию.",
    en: "Lately, he has been devoting a lot of attention to self-development.",
    uaTokens: ["Останнім", "часом", "він", "багато", "уваги", "приділяє", "саморозвитку", "."],
    ruTokens: ["В", "последнее", "время", "он", "много", "внимания", "уделяет", "саморазвитию", "."],
    enTokens: ["Lately", ",", "he", "has", "been", "devoting", "a", "lot", "of", "attention", "to", "self-development", "."],
    extraUaTokens: ["роботі", "відпочинку", "вчора"],
    extraRuTokens: ["работой", "отдыхом", "вчера"],
    extraEnTokens: ["work", "rest", "yesterday"],
  },

  [phraseKey("vnitřní klid", "b1-34")]: {
    sk: "Meditace mu pomáhá najít vnitřní klid.",
    ua: "Медитація допомагає йому знайти внутрішній спокій.",
    ru: "Медитация помогает ему найти внутреннее спокойствие.",
    en: "Meditation helps him find inner peace.",
    uaTokens: ["Медитація", "допомагає", "йому", "знайти", "внутрішній", "спокій", "."],
    ruTokens: ["Медитация", "помогает", "ему", "найти", "внутреннее", "спокойствие", "."],
    enTokens: ["Meditation", "helps", "him", "find", "inner", "peace", "."],
    extraUaTokens: ["радість", "вчора", "вночі"],
    extraRuTokens: ["радость", "вчера", "ночью"],
    extraEnTokens: ["yesterday", "at", "night"],
  },

  [phraseKey("sebedisciplína", "b1-34")]: {
    sk: "Bez sebedisciplíny je těžké dosáhnout cíle.",
    ua: "Без самодисципліни важко досягти мети.",
    ru: "Без самодисциплины трудно достичь цели.",
    en: "Without self-discipline, it is hard to reach a goal.",
    uaTokens: ["Без", "самодисципліни", "важко", "досягти", "мети", "."],
    ruTokens: ["Без", "самодисциплины", "трудно", "достичь", "цели", "."],
    enTokens: ["Without", "self-discipline", ",", "it", "is", "hard", "to", "reach", "a", "goal", "."],
    extraUaTokens: ["результату", "сьогодні", "легко"],
    extraRuTokens: ["результата", "сегодня", "легко"],
    extraEnTokens: ["result", "today", "easily"],
  },

  [phraseKey("odolnost", "b1-34")]: {
    sk: "Psychická odolnost se dá postupně posilovat.",
    ua: "Психологічну стійкість можна поступово зміцнювати.",
    ru: "Психологическую устойчивость можно постепенно укреплять.",
    en: "Mental resilience can be strengthened gradually.",
    uaTokens: ["Психологічну", "стійкість", "можна", "поступово", "зміцнювати", "."],
    ruTokens: ["Психологическую", "устойчивость", "можно", "постепенно", "укреплять", "."],
    enTokens: ["Mental", "resilience", "can", "be", "strengthened", "gradually", "."],
    extraUaTokens: ["слабкість", "вчора", "швидко"],
    extraRuTokens: ["слабость", "вчера", "быстро"],
    extraEnTokens: ["weakness", "yesterday", "quickly"],
  },

  [phraseKey("vyrovnat se s problémem", "b1-34")]: {
    sk: "Naučil se vyrovnat se s problémem bez paniky.",
    ua: "Він навчився справлятися з проблемою без паніки.",
    ru: "Он научился справляться с проблемой без паники.",
    en: "He learned to deal with a problem without panic.",
    uaTokens: ["Він", "навчився", "справлятися", "з", "проблемою", "без", "паніки", "."],
    ruTokens: ["Он", "научился", "справляться", "с", "проблемой", "без", "паники", "."],
    enTokens: ["He", "learned", "to", "deal", "with", "a", "problem", "without", "panic", "."],
    extraUaTokens: ["страху", "вчора", "вночі"],
    extraRuTokens: ["страха", "вчера", "ночью"],
    extraEnTokens: ["fear", "yesterday", "night"],
  },

  // =========================
  // LESSON B1-35 — Столиці
  // =========================
  [phraseKey("Kyjev", "b1-35")]: {
    sk: "Kyjev je hlavní město Ukrajiny.",
    ua: "Київ — столиця України.",
    ru: "Киев — столица Украины.",
    en: "Kyiv is the capital of Ukraine.",
    uaTokens: ["Київ", "—", "столиця", "України", "."],
    ruTokens: ["Киев", "—", "столица", "Украины", "."],
    enTokens: ["Kyiv", "is", "the", "capital", "of", "Ukraine", "."],
    extraUaTokens: ["місто", "Польщі", "сьогодні"],
    extraRuTokens: ["город", "Польши", "сегодня"],
    extraEnTokens: ["city", "Poland", "today"],
  },

  [phraseKey("Londýn", "b1-35")]: {
    sk: "Londýn je hlavní město Velké Británie.",
    ua: "Лондон — столиця Великої Британії.",
    ru: "Лондон — столица Великобритании.",
    en: "London is the capital of Great Britain.",
    uaTokens: ["Лондон", "—", "столиця", "Великої", "Британії", "."],
    ruTokens: ["Лондон", "—", "столица", "Великобритании", "."],
    enTokens: ["London", "is", "the", "capital", "of", "Great", "Britain", "."],
    extraUaTokens: ["Англії", "місто", "вчора"],
    extraRuTokens: ["Англии", "город", "вчера"],
    extraEnTokens: ["England", "city", "yesterday"],
  },

  [phraseKey("Ottawa", "b1-35")]: {
    sk: "Ottawa je hlavní město Kanady.",
    ua: "Оттава — столиця Канади.",
    ru: "Оттава — столица Канады.",
    en: "Ottawa is the capital of Canada.",
    uaTokens: ["Оттава", "—", "столиця", "Канади", "."],
    ruTokens: ["Оттава", "—", "столица", "Канады", "."],
    enTokens: ["Ottawa", "is", "the", "capital", "of", "Canada", "."],
    extraUaTokens: ["США", "місто", "сьогодні"],
    extraRuTokens: ["США", "город", "сегодня"],
    extraEnTokens: ["USA", "city", "today"],
  },

  [phraseKey("Bern", "b1-35")]: {
    sk: "Bern je hlavní město Švýcarska.",
    ua: "Берн — столиця Швейцарії.",
    ru: "Берн — столица Швейцарии.",
    en: "Bern is the capital of Switzerland.",
    uaTokens: ["Берн", "—", "столиця", "Швейцарії", "."],
    ruTokens: ["Берн", "—", "столица", "Швейцарии", "."],
    enTokens: ["Bern", "is", "the", "capital", "of", "Switzerland", "."],
    extraUaTokens: ["Австрії", "столиця", "вчора"],
    extraRuTokens: ["Австрии", "столица", "вчера"],
    extraEnTokens: ["Austria", "capital", "yesterday"],
  },

  [phraseKey("Amsterdam", "b1-35")]: {
    sk: "Amsterdam je hlavní město Nizozemska.",
    ua: "Амстердам — столиця Нідерландів.",
    ru: "Амстердам — столица Нидерландов.",
    en: "Amsterdam is the capital of the Netherlands.",
    uaTokens: ["Амстердам", "—", "столиця", "Нідерландів", "."],
    ruTokens: ["Амстердам", "—", "столица", "Нидерландов", "."],
    enTokens: ["Amsterdam", "is", "the", "capital", "of", "the", "Netherlands", "."],
    extraUaTokens: ["Бельгії", "місто", "сьогодні"],
    extraRuTokens: ["Бельгии", "город", "сегодня"],
    extraEnTokens: ["Belgium", "city", "today"],
  },

  [phraseKey("Brusel", "b1-35")]: {
    sk: "Brusel je hlavní město Belgie.",
    ua: "Брюссель — столиця Бельгії.",
    ru: "Брюссель — столица Бельгии.",
    en: "Brussels is the capital of Belgium.",
    uaTokens: ["Брюссель", "—", "столиця", "Бельгії", "."],
    ruTokens: ["Брюссель", "—", "столица", "Бельгии", "."],
    enTokens: ["Brussels", "is", "the", "capital", "of", "Belgium", "."],
    extraUaTokens: ["Франції", "місто", "вчора"],
    extraRuTokens: ["Франции", "город", "вчера"],
    extraEnTokens: ["France", "city", "yesterday"],
  },

  [phraseKey("Štokholm", "b1-35")]: {
    sk: "Štokholm je hlavní město Švédska.",
    ua: "Стокгольм — столиця Швеції.",
    ru: "Стокгольм — столица Швеции.",
    en: "Stockholm is the capital of Sweden.",
    uaTokens: ["Стокгольм", "—", "столиця", "Швеції", "."],
    ruTokens: ["Стокгольм", "—", "столица", "Швеции", "."],
    enTokens: ["Stockholm", "is", "the", "capital", "of", "Sweden", "."],
    extraUaTokens: ["Норвегії", "місто", "сьогодні"],
    extraRuTokens: ["Норвегии", "город", "сегодня"],
    extraEnTokens: ["Norway", "city", "today"],
  },

  [phraseKey("Moskva", "b1-35")]: {
    sk: "Moskva je hlavní město Ruska.",
    ua: "Москва — столиця Росії.",
    ru: "Москва — столица России.",
    en: "Moscow is the capital of Russia.",
    uaTokens: ["Москва", "—", "столиця", "Росії", "."],
    ruTokens: ["Москва", "—", "столица", "России", "."],
    enTokens: ["Moscow", "is", "the", "capital", "of", "Russia", "."],
    extraUaTokens: ["України", "місто", "вчора"],
    extraRuTokens: ["Украины", "город", "вчера"],
    extraEnTokens: ["Ukraine", "city", "yesterday"],
  },

  [phraseKey("Bukurešť", "b1-35")]: {
    sk: "Bukurešť je hlavní město Rumunska.",
    ua: "Бухарест — столиця Румунії.",
    ru: "Бухарест — столица Румынии.",
    en: "Bucharest is the capital of Romania.",
    uaTokens: ["Бухарест", "—", "столиця", "Румунії", "."],
    ruTokens: ["Бухарест", "—", "столица", "Румынии", "."],
    enTokens: ["Bucharest", "is", "the", "capital", "of", "Romania", "."],
    extraUaTokens: ["Болгарії", "місто", "сьогодні"],
    extraRuTokens: ["Болгарии", "город", "сегодня"],
    extraEnTokens: ["Bulgaria", "city", "today"],
  },

  [phraseKey("Sofia", "b1-35")]: {
    sk: "Sofia je hlavní město Bulharska.",
    ua: "Софія — столиця Болгарії.",
    ru: "София — столица Болгарии.",
    en: "Sofia is the capital of Bulgaria.",
    uaTokens: ["Софія", "—", "столиця", "Болгарії", "."],
    ruTokens: ["София", "—", "столица", "Болгарии", "."],
    enTokens: ["Sofia", "is", "the", "capital", "of", "Bulgaria", "."],
    extraUaTokens: ["Румунії", "місто", "вчора"],
    extraRuTokens: ["Румынии", "город", "вчера"],
    extraEnTokens: ["Romania", "city", "yesterday"],
  },
};