import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A0_BUILD_UA_SENTENCES_1: BuildUaSentenceDict = {
  // =========================
  // LESSON 1 — Базові слова
  // =========================
  [phraseKey("dom", "a0-1")]: {
    sk: "To jest mój dom.",
    ua: "Це мій дім.",
    ru: "Это мой дом.",
    en: "This is my house.",
    uaTokens: ["Це", "мій", "дім", "."],
    ruTokens: ["Это", "мой", "дом", "."],
    enTokens: ["This", "is", "my", "house", "."],
    extraUaTokens: ["сьогодні", "гроші", "авто"],
    extraRuTokens: ["сегодня", "деньги", "машина"],
    extraEnTokens: ["today", "money", "car"],
  },

  [phraseKey("samochód", "a0-1")]: {
    sk: "Mam nowy samochód.",
    ua: "Я маю нове авто.",
    ru: "У меня новая машина.",
    en: "I have a new car.",
    uaTokens: ["Я", "маю", "нове", "авто", "."],
    ruTokens: ["У", "меня", "новая", "машина", "."],
    enTokens: ["I", "have", "a", "new", "car", "."],
    extraUaTokens: ["дім", "гарний", "час"],
    extraRuTokens: ["дом", "хороший", "время"],
    extraEnTokens: ["house", "nice", "time"],
  },

  [phraseKey("woda", "a0-1")]: {
    sk: "Piję zimną wodę.",
    ua: "Я п’ю холодну воду.",
    ru: "Я пью холодную воду.",
    en: "I drink cold water.",
    uaTokens: ["Я", "п’ю", "холодну", "воду", "."],
    ruTokens: ["Я", "пью", "холодную", "воду", "."],
    enTokens: ["I", "drink", "cold", "water", "."],
    extraUaTokens: ["нове", "ідея", "день"],
    extraRuTokens: ["новая", "идея", "день"],
    extraEnTokens: ["new", "idea", "day"],
  },

  [phraseKey("chleb", "a0-1")]: {
    sk: "Kupuję świeży chleb.",
    ua: "Я купую свіжий хліб.",
    ru: "Я покупаю свежий хлеб.",
    en: "I buy fresh bread.",
    uaTokens: ["Я", "купую", "свіжий", "хліб", "."],
    ruTokens: ["Я", "покупаю", "свежий", "хлеб", "."],
    enTokens: ["I", "buy", "fresh", "bread", "."],
    extraUaTokens: ["воду", "гарний", "авто"],
    extraRuTokens: ["воду", "хороший", "машина"],
    extraEnTokens: ["water", "nice", "car"],
  },

  [phraseKey("szkoła", "a0-1")]: {
    sk: "Chodzę do szkoły.",
    ua: "Я ходжу до школи.",
    ru: "Я хожу в школу.",
    en: "I go to school.",
    uaTokens: ["Я", "ходжу", "до", "школи", "."],
    ruTokens: ["Я", "хожу", "в", "школу", "."],
    enTokens: ["I", "go", "to", "school", "."],
    extraUaTokens: ["дім", "мало", "сьогодні"],
    extraRuTokens: ["дом", "мало", "сегодня"],
    extraEnTokens: ["house", "little", "today"],
  },

  [phraseKey("miasto", "a0-1")]: {
    sk: "Mieszkam w mieście.",
    ua: "Я живу в місті.",
    ru: "Я живу в городе.",
    en: "I live in the city.",
    uaTokens: ["Я", "живу", "в", "місті", "."],
    ruTokens: ["Я", "живу", "в", "городе", "."],
    enTokens: ["I", "live", "in", "the", "city", "."],
    extraUaTokens: ["школа", "свіжий", "ідея"],
    extraRuTokens: ["школа", "свежий", "идея"],
    extraEnTokens: ["school", "fresh", "idea"],
  },

  [phraseKey("czas", "a0-1")]: {
    sk: "Nie mam teraz czasu.",
    ua: "Я зараз не маю часу.",
    ru: "У меня сейчас нет времени.",
    en: "I do not have time now.",
    uaTokens: ["Я", "зараз", "не", "маю", "часу", "."],
    ruTokens: ["У", "меня", "сейчас", "нет", "времени", "."],
    enTokens: ["I", "do", "not", "have", "time", "now", "."],
    extraUaTokens: ["нове", "купую", "місті"],
    extraRuTokens: ["новая", "покупаю", "городе"],
    extraEnTokens: ["new", "buy", "city"],
  },

  [phraseKey("dzień", "a0-1")]: {
    sk: "Dzisiaj jest dobry dzień.",
    ua: "Сьогодні добрий день.",
    ru: "Сегодня хороший день.",
    en: "Today is a good day.",
    uaTokens: ["Сьогодні", "добрий", "день", "."],
    ruTokens: ["Сегодня", "хороший", "день", "."],
    enTokens: ["Today", "is", "a", "good", "day", "."],
    extraUaTokens: ["гроші", "школа", "холодну"],
    extraRuTokens: ["деньги", "школа", "холодную"],
    extraEnTokens: ["money", "school", "cold"],
  },

  [phraseKey("dobry", "a0-1")]: {
    sk: "To jest dobry pomysł.",
    ua: "Це добра ідея.",
    ru: "Это хорошая идея.",
    en: "This is a good idea.",
    uaTokens: ["Це", "добра", "ідея", "."],
    ruTokens: ["Это", "хорошая", "идея", "."],
    enTokens: ["This", "is", "a", "good", "idea", "."],
    extraUaTokens: ["день", "живу", "авто"],
    extraRuTokens: ["день", "живу", "машина"],
    extraEnTokens: ["day", "live", "car"],
  },

  [phraseKey("pieniądze", "a0-1")]: {
    sk: "Potrzebuję pieniędzy.",
    ua: "Мені потрібні гроші.",
    ru: "Мне нужны деньги.",
    en: "I need money.",
    uaTokens: ["Мені", "потрібні", "гроші", "."],
    ruTokens: ["Мне", "нужны", "деньги", "."],
    enTokens: ["I", "need", "money", "."],
    extraUaTokens: ["гарний", "дім", "воду"],
    extraRuTokens: ["хороший", "дом", "воду"],
    extraEnTokens: ["nice", "house", "water"],
  },

  // =========================
  // LESSON 2 — Люди
  // =========================
  [phraseKey("człowiek", "a0-2")]: {
    sk: "Ten człowiek jest miły.",
    ua: "Ця людина приємна.",
    ru: "Этот человек приятный.",
    en: "This person is nice.",
    uaTokens: ["Ця", "людина", "приємна", "."],
    ruTokens: ["Этот", "человек", "приятный", "."],
    enTokens: ["This", "person", "is", "nice", "."],
    extraUaTokens: ["брат", "вчителька", "сьогодні"],
    extraRuTokens: ["брат", "учительница", "сегодня"],
    extraEnTokens: ["brother", "teacher", "today"],
  },

  [phraseKey("mężczyzna", "a0-2")]: {
    sk: "Ten mężczyzna pracuje tutaj.",
    ua: "Цей чоловік працює тут.",
    ru: "Этот мужчина работает здесь.",
    en: "This man works here.",
    uaTokens: ["Цей", "чоловік", "працює", "тут", "."],
    ruTokens: ["Этот", "мужчина", "работает", "здесь", "."],
    enTokens: ["This", "man", "works", "here", "."],
    extraUaTokens: ["молода", "вдома", "людина"],
    extraRuTokens: ["молодая", "дома", "человек"],
    extraEnTokens: ["young", "home", "person"],
  },

  [phraseKey("kobieta", "a0-2")]: {
    sk: "Ta kobieta jest uśmiechnięta.",
    ua: "Ця жінка усміхнена.",
    ru: "Эта женщина улыбается.",
    en: "This woman is smiling.",
    uaTokens: ["Ця", "жінка", "усміхнена", "."],
    ruTokens: ["Эта", "женщина", "улыбается", "."],
    enTokens: ["This", "woman", "is", "smiling", "."],
    extraUaTokens: ["чоловік", "один", "місті"],
    extraRuTokens: ["мужчина", "один", "городе"],
    extraEnTokens: ["man", "one", "city"],
  },

  [phraseKey("dziecko", "a0-2")]: {
    sk: "Dziecko śpi spokojnie.",
    ua: "Дитина спить спокійно.",
    ru: "Ребёнок спокойно спит.",
    en: "The child is sleeping peacefully.",
    uaTokens: ["Дитина", "спить", "спокійно", "."],
    ruTokens: ["Ребёнок", "спокойно", "спит", "."],
    enTokens: ["The", "child", "is", "sleeping", "peacefully", "."],
    extraUaTokens: ["працює", "сестра", "приємна"],
    extraRuTokens: ["работает", "сестра", "приятный"],
    extraEnTokens: ["works", "sister", "nice"],
  },

  [phraseKey("przyjaciel", "a0-2")]: {
    sk: "To jest mój przyjaciel.",
    ua: "Це мій друг.",
    ru: "Это мой друг.",
    en: "This is my friend.",
    uaTokens: ["Це", "мій", "друг", "."],
    ruTokens: ["Это", "мой", "друг", "."],
    enTokens: ["This", "is", "my", "friend", "."],
    extraUaTokens: ["жінка", "молода", "вдома"],
    extraRuTokens: ["женщина", "молодая", "дома"],
    extraEnTokens: ["woman", "young", "home"],
  },

  [phraseKey("przyjaciółka", "a0-2")]: {
    sk: "To jest moja przyjaciółka.",
    ua: "Це моя подруга.",
    ru: "Это моя подруга.",
    en: "This is my female friend.",
    uaTokens: ["Це", "моя", "подруга", "."],
    ruTokens: ["Это", "моя", "подруга", "."],
    enTokens: ["This", "is", "my", "female", "friend", "."],
    extraUaTokens: ["батько", "працює", "один"],
    extraRuTokens: ["отец", "работает", "один"],
    extraEnTokens: ["father", "works", "one"],
  },

  [phraseKey("ojciec", "a0-2")]: {
    sk: "Mój ojciec jest w domu.",
    ua: "Мій батько вдома.",
    ru: "Мой отец дома.",
    en: "My father is at home.",
    uaTokens: ["Мій", "батько", "вдома", "."],
    ruTokens: ["Мой", "отец", "дома", "."],
    enTokens: ["My", "father", "is", "at", "home", "."],
    extraUaTokens: ["подруга", "молода", "місті"],
    extraRuTokens: ["подруга", "молодая", "городе"],
    extraEnTokens: ["friend", "young", "city"],
  },

  [phraseKey("matka", "a0-2")]: {
    sk: "Moja matka gotuje obiad.",
    ua: "Моя мати готує обід.",
    ru: "Моя мать готовит обед.",
    en: "My mother is cooking lunch.",
    uaTokens: ["Моя", "мати", "готує", "обід", "."],
    ruTokens: ["Моя", "мать", "готовит", "обед", "."],
    enTokens: ["My", "mother", "is", "cooking", "lunch", "."],
    extraUaTokens: ["вчителька", "місті", "друг"],
    extraRuTokens: ["учительница", "городе", "друг"],
    extraEnTokens: ["teacher", "city", "friend"],
  },

  [phraseKey("brat", "a0-2")]: {
    sk: "Mój brat studiuje.",
    ua: "Мій брат навчається.",
    ru: "Мой брат учится.",
    en: "My brother studies.",
    uaTokens: ["Мій", "брат", "навчається", "."],
    ruTokens: ["Мой", "брат", "учится", "."],
    enTokens: ["My", "brother", "studies", "."],
    extraUaTokens: ["мати", "приємна", "працює"],
    extraRuTokens: ["мать", "приятный", "работает"],
    extraEnTokens: ["mother", "nice", "works"],
  },

  [phraseKey("siostra", "a0-2")]: {
    sk: "Moja siostra czyta książkę.",
    ua: "Моя сестра читає книжку.",
    ru: "Моя сестра читает книгу.",
    en: "My sister is reading a book.",
    uaTokens: ["Моя", "сестра", "читає", "книжку", "."],
    ruTokens: ["Моя", "сестра", "читает", "книгу", "."],
    enTokens: ["My", "sister", "is", "reading", "a", "book", "."],
    extraUaTokens: ["батько", "вчителька", "один"],
    extraRuTokens: ["отец", "учительница", "один"],
    extraEnTokens: ["father", "teacher", "one"],
  },

  // =========================
  // LESSON 3 — Дім
  // =========================
  [phraseKey("mieszkanie", "a0-3")]: {
    sk: "Mam małe mieszkanie.",
    ua: "Я маю маленьку квартиру.",
    ru: "У меня маленькая квартира.",
    en: "I have a small apartment.",
    uaTokens: ["Я", "маю", "маленьку", "квартиру", "."],
    ruTokens: ["У", "меня", "маленькая", "квартира", "."],
    enTokens: ["I", "have", "a", "small", "apartment", "."],
    extraUaTokens: ["двері", "чиста", "книга"],
    extraRuTokens: ["дверь", "чистая", "книга"],
    extraEnTokens: ["door", "clean", "book"],
  },

  [phraseKey("pokój", "a0-3")]: {
    sk: "Mój pokój jest jasny.",
    ua: "Моя кімната світла.",
    ru: "Моя комната светлая.",
    en: "My room is bright.",
    uaTokens: ["Моя", "кімната", "світла", "."],
    ruTokens: ["Моя", "комната", "светлая", "."],
    enTokens: ["My", "room", "is", "bright", "."],
    extraUaTokens: ["шафі", "столі", "зручне"],
    extraRuTokens: ["шкафу", "столе", "удобная"],
    extraEnTokens: ["wardrobe", "table", "comfortable"],
  },

  [phraseKey("kuchnia", "a0-3")]: {
    sk: "Kuchnia jest czysta.",
    ua: "Кухня чиста.",
    ru: "Кухня чистая.",
    en: "The kitchen is clean.",
    uaTokens: ["Кухня", "чиста", "."],
    ruTokens: ["Кухня", "чистая", "."],
    enTokens: ["The", "kitchen", "is", "clean", "."],
    extraUaTokens: ["відкрите", "книга", "стільцю"],
    extraRuTokens: ["открыто", "книга", "стулу"],
    extraEnTokens: ["open", "book", "chair"],
  },

  [phraseKey("łazienka", "a0-3")]: {
    sk: "Łazienka jest obok kuchni.",
    ua: "Ванна кімната біля кухні.",
    ru: "Ванная рядом с кухней.",
    en: "The bathroom is next to the kitchen.",
    uaTokens: ["Ванна", "кімната", "біля", "кухні", "."],
    ruTokens: ["Ванная", "рядом", "с", "кухней", "."],
    enTokens: ["The", "bathroom", "is", "next", "to", "the", "kitchen", "."],
    extraUaTokens: ["маленька", "шафі", "відкрите"],
    extraRuTokens: ["маленькая", "шкафу", "открыто"],
    extraEnTokens: ["small", "wardrobe", "open"],
  },

  [phraseKey("drzwi", "a0-3")]: {
    sk: "Drzwi są zamknięte.",
    ua: "Двері зачинені.",
    ru: "Дверь закрыта.",
    en: "The door is closed.",
    uaTokens: ["Двері", "зачинені", "."],
    ruTokens: ["Дверь", "закрыта", "."],
    enTokens: ["The", "door", "is", "closed", "."],
    extraUaTokens: ["світла", "книга", "кухні"],
    extraRuTokens: ["светлая", "книга", "кухне"],
    extraEnTokens: ["bright", "book", "kitchen"],
  },

  [phraseKey("okno", "a0-3")]: {
    sk: "Okno jest otwarte.",
    ua: "Вікно відкрите.",
    ru: "Окно открыто.",
    en: "The window is open.",
    uaTokens: ["Вікно", "відкрите", "."],
    ruTokens: ["Окно", "открыто", "."],
    enTokens: ["The", "window", "is", "open", "."],
    extraUaTokens: ["двері", "чиста", "квартирі"],
    extraRuTokens: ["дверь", "чистая", "квартире"],
    extraEnTokens: ["door", "clean", "apartment"],
  },

  [phraseKey("stół", "a0-3")]: {
    sk: "Na stole stoi kubek.",
    ua: "На столі стоїть чашка.",
    ru: "На столе стоит кружка.",
    en: "A mug is standing on the table.",
    uaTokens: ["На", "столі", "стоїть", "чашка", "."],
    ruTokens: ["На", "столе", "стоит", "кружка", "."],
    enTokens: ["A", "mug", "is", "standing", "on", "the", "table", "."],
    extraUaTokens: ["ліжко", "світла", "відкрите"],
    extraRuTokens: ["кровать", "светлая", "открыто"],
    extraEnTokens: ["bed", "bright", "open"],
  },

  [phraseKey("krzesło", "a0-3")]: {
    sk: "Krzesło stoi przy stole.",
    ua: "Стілець стоїть біля столу.",
    ru: "Стул стоит у стола.",
    en: "The chair is next to the table.",
    uaTokens: ["Стілець", "стоїть", "біля", "столу", "."],
    ruTokens: ["Стул", "стоит", "у", "стола", "."],
    enTokens: ["The", "chair", "is", "next", "to", "the", "table", "."],
    extraUaTokens: ["книга", "зачинені", "кімната"],
    extraRuTokens: ["книга", "закрыта", "комната"],
    extraEnTokens: ["book", "closed", "room"],
  },

  [phraseKey("łóżko", "a0-3")]: {
    sk: "Łóżko jest wygodne.",
    ua: "Ліжко зручне.",
    ru: "Кровать удобная.",
    en: "The bed is comfortable.",
    uaTokens: ["Ліжко", "зручне", "."],
    ruTokens: ["Кровать", "удобная", "."],
    enTokens: ["The", "bed", "is", "comfortable", "."],
    extraUaTokens: ["стілець", "відкрите", "кухні"],
    extraRuTokens: ["стул", "открыто", "кухне"],
    extraEnTokens: ["chair", "open", "kitchen"],
  },

  [phraseKey("szafa", "a0-3")]: {
    sk: "Ubrania są w szafie.",
    ua: "Одяг у шафі.",
    ru: "Одежда в шкафу.",
    en: "The clothes are in the wardrobe.",
    uaTokens: ["Одяг", "у", "шафі", "."],
    ruTokens: ["Одежда", "в", "шкафу", "."],
    enTokens: ["The", "clothes", "are", "in", "the", "wardrobe", "."],
    extraUaTokens: ["столі", "чиста", "біля"],
    extraRuTokens: ["столе", "чистая", "у"],
    extraEnTokens: ["table", "clean", "near"],
  },

  // =========================
  // LESSON 4 — Магазин
  // =========================
  [phraseKey("sklep", "a0-4")]: {
    sk: "Idę do sklepu.",
    ua: "Я йду до магазину.",
    ru: "Я иду в магазин.",
    en: "I am going to the shop.",
    uaTokens: ["Я", "йду", "до", "магазину", "."],
    ruTokens: ["Я", "иду", "в", "магазин", "."],
    enTokens: ["I", "am", "going", "to", "the", "shop", "."],
    extraUaTokens: ["каса", "карткою", "молоко"],
    extraRuTokens: ["касса", "картой", "молоко"],
    extraEnTokens: ["cash", "card", "milk"],
  },

  [phraseKey("kasa", "a0-4")]: {
    sk: "Kasa jest po prawej stronie.",
    ua: "Каса праворуч.",
    ru: "Касса справа.",
    en: "The cash register is on the right.",
    uaTokens: ["Каса", "праворуч", "."],
    ruTokens: ["Касса", "справа", "."],
    enTokens: ["The", "cash", "register", "is", "on", "the", "right", "."],
    extraUaTokens: ["йду", "знижка", "чек"],
    extraRuTokens: ["иду", "скидка", "чек"],
    extraEnTokens: ["go", "discount", "receipt"],
  },

  [phraseKey("cena", "a0-4")]: {
    sk: "Cena jest wysoka.",
    ua: "Ціна висока.",
    ru: "Цена высокая.",
    en: "The price is high.",
    uaTokens: ["Ціна", "висока", "."],
    ruTokens: ["Цена", "высокая", "."],
    enTokens: ["The", "price", "is", "high", "."],
    extraUaTokens: ["каса", "сумка", "молоко"],
    extraRuTokens: ["касса", "сумка", "молоко"],
    extraEnTokens: ["cash", "bag", "milk"],
  },

  [phraseKey("zniżka", "a0-4")]: {
    sk: "Dzisiaj jest zniżka.",
    ua: "Сьогодні є знижка.",
    ru: "Сегодня есть скидка.",
    en: "There is a discount today.",
    uaTokens: ["Сьогодні", "є", "знижка", "."],
    ruTokens: ["Сегодня", "есть", "скидка", "."],
    enTokens: ["There", "is", "a", "discount", "today", "."],
    extraUaTokens: ["чек", "готівкою", "ціна"],
    extraRuTokens: ["чек", "наличными", "цена"],
    extraEnTokens: ["receipt", "cash", "price"],
  },

  [phraseKey("torba", "a0-4")]: {
    sk: "Potrzebuję dużej torby.",
    ua: "Мені потрібна велика сумка.",
    ru: "Мне нужна большая сумка.",
    en: "I need a big bag.",
    uaTokens: ["Мені", "потрібна", "велика", "сумка", "."],
    ruTokens: ["Мне", "нужна", "большая", "сумка", "."],
    enTokens: ["I", "need", "a", "big", "bag", "."],
    extraUaTokens: ["чек", "хліб", "магазин"],
    extraRuTokens: ["чек", "хлеб", "магазин"],
    extraEnTokens: ["receipt", "bread", "shop"],
  },

  [phraseKey("blok", "a0-4")]: {
    sk: "Poproszę blok.",
    ua: "Будь ласка, чек.",
    ru: "Дайте, пожалуйста, чек.",
    en: "Receipt, please.",
    uaTokens: ["Будь", "ласка", ",", "чек", "."],
    ruTokens: ["Дайте", ",", "пожалуйста", ",", "чек", "."],
    enTokens: ["Receipt", ",", "please", "."],
    extraUaTokens: ["каса", "велика", "карткою"],
    extraRuTokens: ["касса", "большая", "картой"],
    extraEnTokens: ["cash", "big", "card"],
  },

  [phraseKey("gotówka", "a0-4")]: {
    sk: "Płacę gotówką.",
    ua: "Я плачу готівкою.",
    ru: "Я плачу наличными.",
    en: "I pay in cash.",
    uaTokens: ["Я", "плачу", "готівкою", "."],
    ruTokens: ["Я", "плачу", "наличными", "."],
    enTokens: ["I", "pay", "in", "cash", "."],
    extraUaTokens: ["сумка", "ціна", "молоко"],
    extraRuTokens: ["сумка", "цена", "молоко"],
    extraEnTokens: ["bag", "price", "milk"],
  },

  [phraseKey("karta", "a0-4")]: {
    sk: "Mam kartę w portfelu.",
    ua: "У мене картка в гаманці.",
    ru: "У меня карта в кошельке.",
    en: "I have a card in my wallet.",
    uaTokens: ["У", "мене", "картка", "в", "гаманці", "."],
    ruTokens: ["У", "меня", "карта", "в", "кошельке", "."],
    enTokens: ["I", "have", "a", "card", "in", "my", "wallet", "."],
    extraUaTokens: ["готівкою", "чек", "знижка"],
    extraRuTokens: ["наличными", "чек", "скидка"],
    extraEnTokens: ["cash", "receipt", "discount"],
  },

  [phraseKey("kupić", "a0-4")]: {
    sk: "Chcę kupić chleb.",
    ua: "Я хочу купити хліб.",
    ru: "Я хочу купить хлеб.",
    en: "I want to buy bread.",
    uaTokens: ["Я", "хочу", "купити", "хліб", "."],
    ruTokens: ["Я", "хочу", "купить", "хлеб", "."],
    enTokens: ["I", "want", "to", "buy", "bread", "."],
    extraUaTokens: ["карткою", "сумка", "ціна"],
    extraRuTokens: ["картой", "сумка", "цена"],
    extraEnTokens: ["card", "bag", "price"],
  },

  [phraseKey("płacić", "a0-4")]: {
    sk: "Muszę płacić kartą.",
    ua: "Мені треба платити карткою.",
    ru: "Мне нужно платить картой.",
    en: "I have to pay by card.",
    uaTokens: ["Мені", "треба", "платити", "карткою", "."],
    ruTokens: ["Мне", "нужно", "платить", "картой", "."],
    enTokens: ["I", "have", "to", "pay", "by", "card", "."],
    extraUaTokens: ["молоко", "готівкою", "каса"],
    extraRuTokens: ["молоко", "наличными", "касса"],
    extraEnTokens: ["milk", "cash", "cashier"],
  },

  // =========================
  // LESSON 5 — Їжа та напої
  // =========================
  [phraseKey("jedzenie", "a0-5")]: {
    sk: "Jedzenie jest gotowe.",
    ua: "Їжа готова.",
    ru: "Еда готова.",
    en: "The food is ready.",
    uaTokens: ["Їжа", "готова", "."],
    ruTokens: ["Еда", "готова", "."],
    enTokens: ["The", "food", "is", "ready", "."],
    extraUaTokens: ["чай", "вранці", "вода"],
    extraRuTokens: ["чай", "утром", "вода"],
    extraEnTokens: ["tea", "morning", "water"],
  },

  [phraseKey("napój", "a0-5")]: {
    sk: "To jest zimny napój.",
    ua: "Це холодний напій.",
    ru: "Это холодный напиток.",
    en: "This is a cold drink.",
    uaTokens: ["Це", "холодний", "напій", "."],
    ruTokens: ["Это", "холодный", "напиток", "."],
    enTokens: ["This", "is", "a", "cold", "drink", "."],
    extraUaTokens: ["суп", "щодня", "вода"],
    extraRuTokens: ["суп", "каждый", "вода"],
    extraEnTokens: ["soup", "daily", "water"],
  },

  [phraseKey("chleb", "a0-5")]: {
    sk: "Jem chleb na śniadanie.",
    ua: "Я їм хліб на сніданок.",
    ru: "Я ем хлеб на завтрак.",
    en: "I eat bread for breakfast.",
    uaTokens: ["Я", "їм", "хліб", "на", "сніданок", "."],
    ruTokens: ["Я", "ем", "хлеб", "на", "завтрак", "."],
    enTokens: ["I", "eat", "bread", "for", "breakfast", "."],
    extraUaTokens: ["чай", "смачна", "овочі"],
    extraRuTokens: ["чай", "вкусная", "овощи"],
    extraEnTokens: ["tea", "tasty", "vegetables"],
  },

  [phraseKey("mięso", "a0-5")]: {
    sk: "Lubię mięso z ryżem.",
    ua: "Я люблю м’ясо з рисом.",
    ru: "Я люблю мясо с рисом.",
    en: "I like meat with rice.",
    uaTokens: ["Я", "люблю", "м’ясо", "з", "рисом", "."],
    ruTokens: ["Я", "люблю", "мясо", "с", "рисом", "."],
    enTokens: ["I", "like", "meat", "with", "rice", "."],
    extraUaTokens: ["чай", "холодний", "суп"],
    extraRuTokens: ["чай", "холодный", "суп"],
    extraEnTokens: ["tea", "cold", "soup"],
  },

  [phraseKey("zupa", "a0-5")]: {
    sk: "Zupa jest bardzo smaczna.",
    ua: "Суп дуже смачний.",
    ru: "Суп очень вкусный.",
    en: "The soup is very tasty.",
    uaTokens: ["Суп", "дуже", "смачний", "."],
    ruTokens: ["Суп", "очень", "вкусный", "."],
    enTokens: ["The", "soup", "is", "very", "tasty", "."],
    extraUaTokens: ["вода", "свіжі", "чай"],
    extraRuTokens: ["вода", "свежие", "чай"],
    extraEnTokens: ["water", "fresh", "tea"],
  },

  [phraseKey("owoce", "a0-5")]: {
    sk: "Kupuję świeże owoce.",
    ua: "Я купую свіжі фрукти.",
    ru: "Я покупаю свежие фрукты.",
    en: "I buy fresh fruit.",
    uaTokens: ["Я", "купую", "свіжі", "фрукти", "."],
    ruTokens: ["Я", "покупаю", "свежие", "фрукты", "."],
    enTokens: ["I", "buy", "fresh", "fruit", "."],
    extraUaTokens: ["м’ясо", "вода", "напій"],
    extraRuTokens: ["мясо", "вода", "напиток"],
    extraEnTokens: ["meat", "water", "drink"],
  },

  [phraseKey("warzywa", "a0-5")]: {
    sk: "Warzywa są zdrowe.",
    ua: "Овочі корисні.",
    ru: "Овощи полезны.",
    en: "Vegetables are healthy.",
    uaTokens: ["Овочі", "корисні", "."],
    ruTokens: ["Овощи", "полезны", "."],
    enTokens: ["Vegetables", "are", "healthy", "."],
    extraUaTokens: ["суп", "чай", "хліб"],
    extraRuTokens: ["суп", "чай", "хлеб"],
    extraEnTokens: ["soup", "tea", "bread"],
  },

  [phraseKey("woda", "a0-5")]: {
    sk: "Piję dużo wody.",
    ua: "Я п’ю багато води.",
    ru: "Я пью много воды.",
    en: "I drink a lot of water.",
    uaTokens: ["Я", "п’ю", "багато", "води", "."],
    ruTokens: ["Я", "пью", "много", "воды", "."],
    enTokens: ["I", "drink", "a", "lot", "of", "water", "."],
    extraUaTokens: ["смачна", "чай", "суп"],
    extraRuTokens: ["вкусная", "чай", "суп"],
    extraEnTokens: ["tasty", "tea", "soup"],
  },

  [phraseKey("kawa", "a0-5")]: {
    sk: "Rano piję kawę.",
    ua: "Вранці я п’ю каву.",
    ru: "Утром я пью кофе.",
    en: "I drink coffee in the morning.",
    uaTokens: ["Вранці", "я", "п’ю", "каву", "."],
    ruTokens: ["Утром", "я", "пью", "кофе", "."],
    enTokens: ["I", "drink", "coffee", "in", "the", "morning", "."],
    extraUaTokens: ["чай", "корисні", "вода"],
    extraRuTokens: ["чай", "полезны", "вода"],
    extraEnTokens: ["tea", "healthy", "water"],
  },

  [phraseKey("herbata", "a0-5")]: {
    sk: "Wieczorem piję herbatę.",
    ua: "Увечері я п’ю чай.",
    ru: "Вечером я пью чай.",
    en: "I drink tea in the evening.",
    uaTokens: ["Увечері", "я", "п’ю", "чай", "."],
    ruTokens: ["Вечером", "я", "пью", "чай", "."],
    enTokens: ["I", "drink", "tea", "in", "the", "evening", "."],
    extraUaTokens: ["каву", "суп", "хліб"],
    extraRuTokens: ["кофе", "суп", "хлеб"],
    extraEnTokens: ["coffee", "soup", "bread"],
  },
};