import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A0_BUILD_UA_SENTENCES_2: BuildUaSentenceDict = {
    // =========================
    // LESSON 6 — Місто
    // =========================
    [phraseKey("miasto", "a0-6")]: {
        sk: "To miasto jest piękne.",
        ua: "Це місто красиве.",
        ru: "Этот город красивый.",
        en: "This city is beautiful.",
        uaTokens: ["Це", "місто", "красиве", "."],
        ruTokens: ["Этот", "город", "красивый", "."],
        enTokens: ["This", "city", "is", "beautiful", "."],
        extraUaTokens: ["вулиця", "новий", "центр"],
        extraRuTokens: ["улица", "новый", "центр"],
        extraEnTokens: ["street", "new", "center"],
    },

    [phraseKey("ulica", "a0-6")]: {
        sk: "Ta ulica jest długa.",
        ua: "Ця вулиця довга.",
        ru: "Эта улица длинная.",
        en: "This street is long.",
        uaTokens: ["Ця", "вулиця", "довга", "."],
        ruTokens: ["Эта", "улица", "длинная", "."],
        enTokens: ["This", "street", "is", "long", "."],
        extraUaTokens: ["місто", "новий", "парк"],
        extraRuTokens: ["город", "новый", "парк"],
        extraEnTokens: ["city", "new", "park"],
    },

    [phraseKey("plac", "a0-6")]: {
        sk: "Spotkajmy się na placu.",
        ua: "Зустріньмось на площі.",
        ru: "Давай встретимся на площади.",
        en: "Let’s meet at the square.",
        uaTokens: ["Зустріньмось", "на", "площі", "."],
        ruTokens: ["Давай", "встретимся", "на", "площади", "."],
        enTokens: ["Let’s", "meet", "at", "the", "square", "."],
        extraUaTokens: ["довга", "будинок", "зупинці"],
        extraRuTokens: ["длинная", "дом", "остановке"],
        extraEnTokens: ["long", "house", "stop"],
    },

    [phraseKey("dom", "a0-6")]: {
        sk: "Ten dom jest nowy.",
        ua: "Цей будинок новий.",
        ru: "Этот дом новый.",
        en: "This house is new.",
        uaTokens: ["Цей", "будинок", "новий", "."],
        ruTokens: ["Этот", "дом", "новый", "."],
        enTokens: ["This", "house", "is", "new", "."],
        extraUaTokens: ["місто", "довга", "школа"],
        extraRuTokens: ["город", "длинная", "школа"],
        extraEnTokens: ["city", "long", "school"],
    },

    [phraseKey("mieszkanie", "a0-6")]: {
        sk: "Szukam nowego mieszkania.",
        ua: "Я шукаю нову квартиру.",
        ru: "Я ищу новую квартиру.",
        en: "I am looking for a new apartment.",
        uaTokens: ["Я", "шукаю", "нову", "квартиру", "."],
        ruTokens: ["Я", "ищу", "новую", "квартиру", "."],
        enTokens: ["I", "am", "looking", "for", "a", "new", "apartment", "."],
        extraUaTokens: ["будинок", "гарний", "парк"],
        extraRuTokens: ["дом", "красивый", "парк"],
        extraEnTokens: ["house", "beautiful", "park"],
    },

    [phraseKey("szkoła", "a0-6")]: {
        sk: "Szkoła jest blisko domu.",
        ua: "Школа близько до дому.",
        ru: "Школа близко к дому.",
        en: "The school is close to home.",
        uaTokens: ["Школа", "близько", "до", "дому", "."],
        ruTokens: ["Школа", "близко", "к", "дому", "."],
        enTokens: ["The", "school", "is", "close", "to", "home", "."],
        extraUaTokens: ["місто", "нову", "зупинці"],
        extraRuTokens: ["город", "новую", "остановке"],
        extraEnTokens: ["city", "new", "stop"],
    },

    [phraseKey("szpital", "a0-6")]: {
        sk: "Szpital jest niedaleko.",
        ua: "Лікарня недалеко.",
        ru: "Больница недалеко.",
        en: "The hospital is nearby.",
        uaTokens: ["Лікарня", "недалеко", "."],
        ruTokens: ["Больница", "недалеко", "."],
        enTokens: ["The", "hospital", "is", "nearby", "."],
        extraUaTokens: ["парк", "довга", "центр"],
        extraRuTokens: ["парк", "длинная", "центр"],
        extraEnTokens: ["park", "long", "center"],
    },

    [phraseKey("przystanek", "a0-6")]: {
        sk: "Czekam na przystanku.",
        ua: "Я чекаю на зупинці.",
        ru: "Я жду на остановке.",
        en: "I am waiting at the stop.",
        uaTokens: ["Я", "чекаю", "на", "зупинці", "."],
        ruTokens: ["Я", "жду", "на", "остановке", "."],
        enTokens: ["I", "am", "waiting", "at", "the", "stop", "."],
        extraUaTokens: ["школа", "гарний", "площі"],
        extraRuTokens: ["школа", "красивый", "площади"],
        extraEnTokens: ["school", "beautiful", "square"],
    },

    [phraseKey("park", "a0-6")]: {
        sk: "Spaceruję po parku.",
        ua: "Я гуляю в парку.",
        ru: "Я гуляю по парку.",
        en: "I walk in the park.",
        uaTokens: ["Я", "гуляю", "в", "парку", "."],
        ruTokens: ["Я", "гуляю", "по", "парку", "."],
        enTokens: ["I", "walk", "in", "the", "park", "."],
        extraUaTokens: ["вулиця", "нову", "лікарня"],
        extraRuTokens: ["улица", "новую", "больница"],
        extraEnTokens: ["street", "new", "hospital"],
    },

    [phraseKey("stacja", "a0-6")]: {
        sk: "Stacja jest w centrum.",
        ua: "Станція в центрі.",
        ru: "Станция в центре.",
        en: "The station is in the center.",
        uaTokens: ["Станція", "в", "центрі", "."],
        ruTokens: ["Станция", "в", "центре", "."],
        enTokens: ["The", "station", "is", "in", "the", "center", "."],
        extraUaTokens: ["парк", "новий", "довга"],
        extraRuTokens: ["парк", "новый", "длинная"],
        extraEnTokens: ["park", "new", "long"],
    },

    // =========================
    // LESSON 7 — Транспорт
    // =========================
    [phraseKey("transport", "a0-7")]: {
        sk: "Transport w mieście jest dobry.",
        ua: "Транспорт у місті хороший.",
        ru: "Транспорт в городе хороший.",
        en: "Transport in the city is good.",
        uaTokens: ["Транспорт", "у", "місті", "хороший", "."],
        ruTokens: ["Транспорт", "в", "городе", "хороший", "."],
        enTokens: ["Transport", "in", "the", "city", "is", "good", "."],
        extraUaTokens: ["авто", "квиток", "довга"],
        extraRuTokens: ["машина", "билет", "длинная"],
        extraEnTokens: ["car", "ticket", "long"],
    },

    [phraseKey("samochód", "a0-7")]: {
        sk: "Mój samochód jest szybki.",
        ua: "Моє авто швидке.",
        ru: "Моя машина быстрая.",
        en: "My car is fast.",
        uaTokens: ["Моє", "авто", "швидке", "."],
        ruTokens: ["Моя", "машина", "быстрая", "."],
        enTokens: ["My", "car", "is", "fast", "."],
        extraUaTokens: ["транспорт", "квиток", "центр"],
        extraRuTokens: ["транспорт", "билет", "центр"],
        extraEnTokens: ["transport", "ticket", "center"],
    },

    [phraseKey("autobus", "a0-7")]: {
        sk: "Autobus już jedzie.",
        ua: "Автобус уже їде.",
        ru: "Автобус уже едет.",
        en: "The bus is already coming.",
        uaTokens: ["Автобус", "уже", "їде", "."],
        ruTokens: ["Автобус", "уже", "едет", "."],
        enTokens: ["The", "bus", "is", "already", "coming", "."],
        extraUaTokens: ["квиток", "швидке", "метро"],
        extraRuTokens: ["билет", "быстрая", "метро"],
        extraEnTokens: ["ticket", "fast", "metro"],
    },

    [phraseKey("pociąg", "a0-7")]: {
        sk: "Pociąg przyjeżdża na czas.",
        ua: "Потяг прибуває вчасно.",
        ru: "Поезд приезжает вовремя.",
        en: "The train arrives on time.",
        uaTokens: ["Потяг", "прибуває", "вчасно", "."],
        ruTokens: ["Поезд", "приезжает", "вовремя", "."],
        enTokens: ["The", "train", "arrives", "on", "time", "."],
        extraUaTokens: ["автобус", "квиток", "додому"],
        extraRuTokens: ["автобус", "билет", "домой"],
        extraEnTokens: ["bus", "ticket", "home"],
    },

    [phraseKey("tramwaj", "a0-7")]: {
        sk: "Tramwaj jedzie do centrum.",
        ua: "Трамвай їде до центру.",
        ru: "Трамвай едет в центр.",
        en: "The tram goes to the center.",
        uaTokens: ["Трамвай", "їде", "до", "центру", "."],
        ruTokens: ["Трамвай", "едет", "в", "центр", "."],
        enTokens: ["The", "tram", "goes", "to", "the", "center", "."],
        extraUaTokens: ["метро", "квиток", "швидке"],
        extraRuTokens: ["метро", "билет", "быстрое"],
        extraEnTokens: ["metro", "ticket", "fast"],
    },

    [phraseKey("metro", "a0-7")]: {
        sk: "Metro jest bardzo szybkie.",
        ua: "Метро дуже швидке.",
        ru: "Метро очень быстрое.",
        en: "The metro is very fast.",
        uaTokens: ["Метро", "дуже", "швидке", "."],
        ruTokens: ["Метро", "очень", "быстрое", "."],
        enTokens: ["The", "metro", "is", "very", "fast", "."],
        extraUaTokens: ["трамвай", "квиток", "місті"],
        extraRuTokens: ["трамвай", "билет", "городе"],
        extraEnTokens: ["tram", "ticket", "city"],
    },

    [phraseKey("taksówka", "a0-7")]: {
        sk: "Biorę taksówkę do domu.",
        ua: "Я беру таксі додому.",
        ru: "Я беру такси домой.",
        en: "I take a taxi home.",
        uaTokens: ["Я", "беру", "таксі", "додому", "."],
        ruTokens: ["Я", "беру", "такси", "домой", "."],
        enTokens: ["I", "take", "a", "taxi", "home", "."],
        extraUaTokens: ["метро", "центр", "квиток"],
        extraRuTokens: ["метро", "центр", "билет"],
        extraEnTokens: ["metro", "center", "ticket"],
    },

    [phraseKey("przystanek", "a0-7")]: {
        sk: "Przystanek jest blisko.",
        ua: "Зупинка близько.",
        ru: "Остановка близко.",
        en: "The stop is nearby.",
        uaTokens: ["Зупинка", "близько", "."],
        ruTokens: ["Остановка", "близко", "."],
        enTokens: ["The", "stop", "is", "nearby", "."],
        extraUaTokens: ["таксі", "швидке", "центр"],
        extraRuTokens: ["такси", "быстрое", "центр"],
        extraEnTokens: ["taxi", "fast", "center"],
    },

    [phraseKey("bilet", "a0-7")]: {
        sk: "Mam bilet w kieszeni.",
        ua: "У мене квиток у кишені.",
        ru: "У меня билет в кармане.",
        en: "I have a ticket in my pocket.",
        uaTokens: ["У", "мене", "квиток", "у", "кишені", "."],
        ruTokens: ["У", "меня", "билет", "в", "кармане", "."],
        enTokens: ["I", "have", "a", "ticket", "in", "my", "pocket", "."],
        extraUaTokens: ["автобус", "швидке", "центр"],
        extraRuTokens: ["автобус", "быстрое", "центр"],
        extraEnTokens: ["bus", "fast", "center"],
    },

    [phraseKey("lotnisko", "a0-7")]: {
        sk: "Lotnisko jest daleko stąd.",
        ua: "Аеропорт далеко звідси.",
        ru: "Аэропорт далеко отсюда.",
        en: "The airport is far from here.",
        uaTokens: ["Аеропорт", "далеко", "звідси", "."],
        ruTokens: ["Аэропорт", "далеко", "отсюда", "."],
        enTokens: ["The", "airport", "is", "far", "from", "here", "."],
        extraUaTokens: ["квиток", "метро", "близько"],
        extraRuTokens: ["билет", "метро", "близко"],
        extraEnTokens: ["ticket", "metro", "nearby"],
    },

    // =========================
    // LESSON 8 — Час і дні
    // =========================
    [phraseKey("czas", "a0-8")]: {
        sk: "Nie mam dużo czasu.",
        ua: "У мене немає багато часу.",
        ru: "У меня нет много времени.",
        en: "I do not have much time.",
        uaTokens: ["У", "мене", "немає", "багато", "часу", "."],
        ruTokens: ["У", "меня", "нет", "много", "времени", "."],
        enTokens: ["I", "do", "not", "have", "much", "time", "."],
        extraUaTokens: ["сьогодні", "рік", "швидко"],
        extraRuTokens: ["сегодня", "год", "быстро"],
        extraEnTokens: ["today", "year", "quickly"],
    },

    [phraseKey("dzień", "a0-8")]: {
        sk: "Każdy dzień jest ważny.",
        ua: "Кожен день важливий.",
        ru: "Каждый день важен.",
        en: "Every day is important.",
        uaTokens: ["Кожен", "день", "важливий", "."],
        ruTokens: ["Каждый", "день", "важен", "."],
        enTokens: ["Every", "day", "is", "important", "."],
        extraUaTokens: ["тиждень", "сплю", "завтра"],
        extraRuTokens: ["неделя", "сплю", "завтра"],
        extraEnTokens: ["week", "sleep", "tomorrow"],
    },

    [phraseKey("noc", "a0-8")]: {
        sk: "W nocy śpię.",
        ua: "Вночі я сплю.",
        ru: "Ночью я сплю.",
        en: "I sleep at night.",
        uaTokens: ["Вночі", "я", "сплю", "."],
        ruTokens: ["Ночью", "я", "сплю", "."],
        enTokens: ["I", "sleep", "at", "night", "."],
        extraUaTokens: ["день", "важливий", "завтра"],
        extraRuTokens: ["день", "важен", "завтра"],
        extraEnTokens: ["day", "important", "tomorrow"],
    },

    [phraseKey("tydzień", "a0-8")]: {
        sk: "Tydzień ma siedem dni.",
        ua: "Тиждень має сім днів.",
        ru: "В неделе семь дней.",
        en: "A week has seven days.",
        uaTokens: ["Тиждень", "має", "сім", "днів", "."],
        ruTokens: ["В", "неделе", "семь", "дней", "."],
        enTokens: ["A", "week", "has", "seven", "days", "."],
        extraUaTokens: ["місяць", "важливий", "часу"],
        extraRuTokens: ["месяц", "важный", "времени"],
        extraEnTokens: ["month", "important", "time"],
    },

    [phraseKey("miesiąc", "a0-8")]: {
        sk: "Miesiąc mija szybko.",
        ua: "Місяць минає швидко.",
        ru: "Месяц проходит быстро.",
        en: "A month passes quickly.",
        uaTokens: ["Місяць", "минає", "швидко", "."],
        ruTokens: ["Месяц", "проходит", "быстро", "."],
        enTokens: ["A", "month", "passes", "quickly", "."],
        extraUaTokens: ["рік", "день", "вночі"],
        extraRuTokens: ["год", "день", "ночью"],
        extraEnTokens: ["year", "day", "night"],
    },

    [phraseKey("rok", "a0-8")]: {
        sk: "Ten rok jest ważny.",
        ua: "Цей рік важливий.",
        ru: "Этот год важный.",
        en: "This year is important.",
        uaTokens: ["Цей", "рік", "важливий", "."],
        ruTokens: ["Этот", "год", "важный", "."],
        enTokens: ["This", "year", "is", "important", "."],
        extraUaTokens: ["місяць", "швидко", "завтра"],
        extraRuTokens: ["месяц", "быстро", "завтра"],
        extraEnTokens: ["month", "quickly", "tomorrow"],
    },

    [phraseKey("dziś", "a0-8")]: {
        sk: "Dziś jestem w domu.",
        ua: "Сьогодні я вдома.",
        ru: "Сегодня я дома.",
        en: "Today I am at home.",
        uaTokens: ["Сьогодні", "я", "вдома", "."],
        ruTokens: ["Сегодня", "я", "дома", "."],
        enTokens: ["Today", "I", "am", "at", "home", "."],
        extraUaTokens: ["завтра", "роботу", "важливий"],
        extraRuTokens: ["завтра", "работу", "важный"],
        extraEnTokens: ["tomorrow", "work", "important"],
    },

    [phraseKey("jutro", "a0-8")]: {
        sk: "Jutro idę do pracy.",
        ua: "Завтра я йду на роботу.",
        ru: "Завтра я иду на работу.",
        en: "Tomorrow I am going to work.",
        uaTokens: ["Завтра", "я", "йду", "на", "роботу", "."],
        ruTokens: ["Завтра", "я", "иду", "на", "работу", "."],
        enTokens: ["Tomorrow", "I", "am", "going", "to", "work", "."],
        extraUaTokens: ["сьогодні", "вдома", "день"],
        extraRuTokens: ["сегодня", "дома", "день"],
        extraEnTokens: ["today", "home", "day"],
    },

    [phraseKey("wczoraj", "a0-8")]: {
        sk: "Wczoraj byłem zmęczony.",
        ua: "Вчора я був втомлений.",
        ru: "Вчера я был уставший.",
        en: "Yesterday I was tired.",
        uaTokens: ["Вчора", "я", "був", "втомлений", "."],
        ruTokens: ["Вчера", "я", "был", "уставший", "."],
        enTokens: ["Yesterday", "I", "was", "tired", "."],
        extraUaTokens: ["завтра", "роботу", "швидко"],
        extraRuTokens: ["завтра", "работу", "быстро"],
        extraEnTokens: ["tomorrow", "work", "quickly"],
    },

    [phraseKey("godzina", "a0-8")]: {
        sk: "Mam jedną godzinę czasu.",
        ua: "Я маю одну годину часу.",
        ru: "У меня есть один час времени.",
        en: "I have one hour of time.",
        uaTokens: ["Я", "маю", "одну", "годину", "часу", "."],
        ruTokens: ["У", "меня", "есть", "один", "час", "времени", "."],
        enTokens: ["I", "have", "one", "hour", "of", "time", "."],
        extraUaTokens: ["сьогодні", "тиждень", "втомлений"],
        extraRuTokens: ["сегодня", "неделя", "уставший"],
        extraEnTokens: ["today", "week", "tired"],
    },

    // =========================
    // LESSON 9 — Робота
    // =========================
    [phraseKey("praca", "a0-9")]: {
        sk: "Moja praca jest ciekawa.",
        ua: "Моя робота цікава.",
        ru: "Моя работа интересная.",
        en: "My work is interesting.",
        uaTokens: ["Моя", "робота", "цікава", "."],
        ruTokens: ["Моя", "работа", "интересная", "."],
        enTokens: ["My", "work", "is", "interesting", "."],
        extraUaTokens: ["фірма", "договір", "ранок"],
        extraRuTokens: ["фирма", "договор", "утро"],
        extraEnTokens: ["company", "contract", "morning"],
    },

    [phraseKey("zatrudnienie", "a0-9")]: {
        sk: "Szukam nowego zatrudnienia.",
        ua: "Я шукаю нову роботу.",
        ru: "Я ищу новую работу.",
        en: "I am looking for new employment.",
        uaTokens: ["Я", "шукаю", "нову", "роботу", "."],
        ruTokens: ["Я", "ищу", "новую", "работу", "."],
        enTokens: ["I", "am", "looking", "for", "new", "employment", "."],
        extraUaTokens: ["фірма", "спокійний", "відпустка"],
        extraRuTokens: ["фирма", "спокойный", "отпуск"],
        extraEnTokens: ["company", "calm", "vacation"],
    },

    [phraseKey("firma", "a0-9")]: {
        sk: "Ta firma jest duża.",
        ua: "Ця фірма велика.",
        ru: "Эта фирма большая.",
        en: "This company is big.",
        uaTokens: ["Ця", "фірма", "велика", "."],
        ruTokens: ["Эта", "фирма", "большая", "."],
        enTokens: ["This", "company", "is", "big", "."],
        extraUaTokens: ["робота", "ранок", "договір"],
        extraRuTokens: ["работа", "утро", "договор"],
        extraEnTokens: ["work", "morning", "contract"],
    },

    [phraseKey("szef", "a0-9")]: {
        sk: "Mój szef jest spokojny.",
        ua: "Мій начальник спокійний.",
        ru: "Мой начальник спокойный.",
        en: "My boss is calm.",
        uaTokens: ["Мій", "начальник", "спокійний", "."],
        ruTokens: ["Мой", "начальник", "спокойный", "."],
        enTokens: ["My", "boss", "is", "calm", "."],
        extraUaTokens: ["фірма", "робота", "відпустка"],
        extraRuTokens: ["фирма", "работа", "отпуск"],
        extraEnTokens: ["company", "work", "vacation"],
    },

    [phraseKey("kolega", "a0-9")]: {
        sk: "Mój kolega pracuje ze mną.",
        ua: "Мій колега працює зі мною.",
        ru: "Мой коллега работает со мной.",
        en: "My colleague works with me.",
        uaTokens: ["Мій", "колега", "працює", "зі", "мною", "."],
        ruTokens: ["Мой", "коллега", "работает", "со", "мной", "."],
        enTokens: ["My", "colleague", "works", "with", "me", "."],
        extraUaTokens: ["фірма", "ранок", "спокійний"],
        extraRuTokens: ["фирма", "утро", "спокойный"],
        extraEnTokens: ["company", "morning", "calm"],
    },

    [phraseKey("wynagrodzenie", "a0-9")]: {
        sk: "Wynagrodzenie jest na koncie.",
        ua: "Зарплата на рахунку.",
        ru: "Зарплата на счёте.",
        en: "The salary is in the account.",
        uaTokens: ["Зарплата", "на", "рахунку", "."],
        ruTokens: ["Зарплата", "на", "счёте", "."],
        enTokens: ["The", "salary", "is", "in", "the", "account", "."],
        extraUaTokens: ["договір", "колега", "робота"],
        extraRuTokens: ["договор", "коллега", "работа"],
        extraEnTokens: ["contract", "colleague", "work"],
    },

    [phraseKey("umowa", "a0-9")]: {
        sk: "Podpisuję umowę dziś.",
        ua: "Я підписую договір сьогодні.",
        ru: "Я подписываю договор сегодня.",
        en: "I am signing the contract today.",
        uaTokens: ["Я", "підписую", "договір", "сьогодні", "."],
        ruTokens: ["Я", "подписываю", "договор", "сегодня", "."],
        enTokens: ["I", "am", "signing", "the", "contract", "today", "."],
        extraUaTokens: ["зарплата", "ранок", "фірма"],
        extraRuTokens: ["зарплата", "утро", "фирма"],
        extraEnTokens: ["salary", "morning", "company"],
    },

    [phraseKey("pracować", "a0-9")]: {
        sk: "Lubię pracować rano.",
        ua: "Я люблю працювати вранці.",
        ru: "Я люблю работать утром.",
        en: "I like to work in the morning.",
        uaTokens: ["Я", "люблю", "працювати", "вранці", "."],
        ruTokens: ["Я", "люблю", "работать", "утром", "."],
        enTokens: ["I", "like", "to", "work", "in", "the", "morning", "."],
        extraUaTokens: ["договір", "зарплата", "фірма"],
        extraRuTokens: ["договор", "зарплата", "фирма"],
        extraEnTokens: ["contract", "salary", "company"],
    },

    [phraseKey("praca dorywcza", "a0-9")]: {
        sk: "Mam pracę dorywczą w weekend.",
        ua: "У мене є підробіток на вихідних.",
        ru: "У меня есть подработка на выходных.",
        en: "I have a part-time job on weekends.",
        uaTokens: ["У", "мене", "є", "підробіток", "на", "вихідних", "."],
        ruTokens: ["У", "меня", "есть", "подработка", "на", "выходных", "."],
        enTokens: ["I", "have", "a", "part-time", "job", "on", "weekends", "."],
        extraUaTokens: ["ранок", "зарплата", "спокійний"],
        extraRuTokens: ["утро", "зарплата", "спокойный"],
        extraEnTokens: ["morning", "salary", "calm"],
    },

    [phraseKey("urlop", "a0-9")]: {
        sk: "Latem mam urlop.",
        ua: "Влітку я маю відпустку.",
        ru: "Летом у меня отпуск.",
        en: "I have vacation in summer.",
        uaTokens: ["Влітку", "я", "маю", "відпустку", "."],
        ruTokens: ["Летом", "у", "меня", "отпуск", "."],
        enTokens: ["I", "have", "vacation", "in", "summer", "."],
        extraUaTokens: ["робота", "фірма", "ранок"],
        extraRuTokens: ["работа", "фирма", "утро"],
        extraEnTokens: ["work", "company", "morning"],
    },

    // =========================
    // LESSON 10 — Школа
    // =========================
    [phraseKey("szkoła", "a0-10")]: {
        sk: "Szkoła zaczyna się rano.",
        ua: "Школа починається вранці.",
        ru: "Школа начинается утром.",
        en: "School starts in the morning.",
        uaTokens: ["Школа", "починається", "вранці", "."],
        ruTokens: ["Школа", "начинается", "утром", "."],
        enTokens: ["School", "starts", "in", "the", "morning", "."],
        extraUaTokens: ["учень", "тест", "стіл"],
        extraRuTokens: ["ученик", "тест", "стол"],
        extraEnTokens: ["student", "test", "table"],
    },

    [phraseKey("uczeń", "a0-10")]: {
        sk: "Ten uczeń dobrze czyta.",
        ua: "Цей учень добре читає.",
        ru: "Этот ученик хорошо читает.",
        en: "This student reads well.",
        uaTokens: ["Цей", "учень", "добре", "читає", "."],
        ruTokens: ["Этот", "ученик", "хорошо", "читает", "."],
        enTokens: ["This", "student", "reads", "well", "."],
        extraUaTokens: ["урок", "тест", "зошит"],
        extraRuTokens: ["урок", "тест", "тетрадь"],
        extraEnTokens: ["lesson", "test", "notebook"],
    },

    [phraseKey("nauczyciel", "a0-10")]: {
        sk: "Nauczyciel tłumaczy lekcję.",
        ua: "Учитель пояснює урок.",
        ru: "Учитель объясняет урок.",
        en: "The teacher explains the lesson.",
        uaTokens: ["Учитель", "пояснює", "урок", "."],
        ruTokens: ["Учитель", "объясняет", "урок", "."],
        enTokens: ["The", "teacher", "explains", "the", "lesson", "."],
        extraUaTokens: ["учень", "великий", "зошит"],
        extraRuTokens: ["ученик", "большой", "тетрадь"],
        extraEnTokens: ["student", "big", "notebook"],
    },

    [phraseKey("klasa", "a0-10")]: {
        sk: "Nasza klasa jest duża.",
        ua: "Наш клас великий.",
        ru: "Наш класс большой.",
        en: "Our classroom is big.",
        uaTokens: ["Наш", "клас", "великий", "."],
        ruTokens: ["Наш", "класс", "большой", "."],
        enTokens: ["Our", "classroom", "is", "big", "."],
        extraUaTokens: ["учень", "урок", "складне"],
        extraRuTokens: ["ученик", "урок", "сложное"],
        extraEnTokens: ["student", "lesson", "difficult"],
    },

    [phraseKey("przedmiot", "a0-10")]: {
        sk: "Mój ulubiony przedmiot to matematyka.",
        ua: "Мій улюблений предмет — математика.",
        ru: "Мой любимый предмет — математика.",
        en: "My favorite subject is mathematics.",
        uaTokens: ["Мій", "улюблений", "предмет", "—", "математика", "."],
        ruTokens: ["Мой", "любимый", "предмет", "—", "математика", "."],
        enTokens: ["My", "favorite", "subject", "is", "mathematics", "."],
        extraUaTokens: ["учень", "урок", "зошит"],
        extraRuTokens: ["ученик", "урок", "тетрадь"],
        extraEnTokens: ["student", "lesson", "notebook"],
    },

    [phraseKey("godzina", "a0-10")]: {
        sk: "Ta godzina jest trudna.",
        ua: "Цей урок складний.",
        ru: "Этот урок сложный.",
        en: "This lesson is difficult.",
        uaTokens: ["Цей", "урок", "складний", "."],
        ruTokens: ["Этот", "урок", "сложный", "."],
        enTokens: ["This", "lesson", "is", "difficult", "."],
        extraUaTokens: ["вчитель", "тест", "великий"],
        extraRuTokens: ["учитель", "тест", "большой"],
        extraEnTokens: ["teacher", "test", "big"],
    },

    [phraseKey("zadanie", "a0-10")]: {
        sk: "Mam trudne zadanie domowe.",
        ua: "У мене складне домашнє завдання.",
        ru: "У меня сложное домашнее задание.",
        en: "I have difficult homework.",
        uaTokens: ["У", "мене", "складне", "домашнє", "завдання", "."],
        ruTokens: ["У", "меня", "сложное", "домашнее", "задание", "."],
        enTokens: ["I", "have", "difficult", "homework", "."],
        extraUaTokens: ["урок", "учень", "стіл"],
        extraRuTokens: ["урок", "ученик", "стол"],
        extraEnTokens: ["lesson", "student", "table"],
    },

    [phraseKey("test", "a0-10")]: {
        sk: "Jutro piszemy test.",
        ua: "Завтра ми пишемо тест.",
        ru: "Завтра мы пишем тест.",
        en: "Tomorrow we are taking a test.",
        uaTokens: ["Завтра", "ми", "пишемо", "тест", "."],
        ruTokens: ["Завтра", "мы", "пишем", "тест", "."],
        enTokens: ["Tomorrow", "we", "are", "taking", "a", "test", "."],
        extraUaTokens: ["урок", "зошит", "великий"],
        extraRuTokens: ["урок", "тетрадь", "большой"],
        extraEnTokens: ["lesson", "notebook", "big"],
    },

    [phraseKey("zeszyt", "a0-10")]: {
        sk: "Mój zeszyt leży na stole.",
        ua: "Мій зошит лежить на столі.",
        ru: "Моя тетрадь лежит на столе.",
        en: "My notebook is on the table.",
        uaTokens: ["Мій", "зошит", "лежить", "на", "столі", "."],
        ruTokens: ["Моя", "тетрадь", "лежит", "на", "столе", "."],
        enTokens: ["My", "notebook", "is", "on", "the", "table", "."],
        extraUaTokens: ["тест", "урок", "учень"],
        extraRuTokens: ["тест", "урок", "ученик"],
        extraEnTokens: ["test", "lesson", "student"],
    },

    [phraseKey("podręcznik", "a0-10")]: {
        sk: "Podręcznik jest w plecaku.",
        ua: "Підручник у рюкзаку.",
        ru: "Учебник в рюкзаке.",
        en: "The textbook is in the backpack.",
        uaTokens: ["Підручник", "у", "рюкзаку", "."],
        ruTokens: ["Учебник", "в", "рюкзаке", "."],
        enTokens: ["The", "textbook", "is", "in", "the", "backpack", "."],
        extraUaTokens: ["зошит", "тест", "великий"],
        extraRuTokens: ["тетрадь", "тест", "большой"],
        extraEnTokens: ["notebook", "test", "big"],
    },
};