import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A0_BUILD_UA_SENTENCES_3: BuildUaSentenceDict = {
    // =========================
    // LESSON 11 — Числа
    // =========================
    [phraseKey("zero", "a0-11")]: {
        sk: "Mam zero czasu.",
        ua: "У мене нуль часу.",
        ru: "У меня ноль времени.",
        en: "I have zero time.",
        uaTokens: ["У", "мене", "нуль", "часу", "."],
        ruTokens: ["У", "меня", "ноль", "времени", "."],
        enTokens: ["I", "have", "zero", "time", "."],
        extraUaTokens: ["квиток", "будинки", "дев’ять"],
        extraRuTokens: ["билет", "дома", "девять"],
        extraEnTokens: ["ticket", "houses", "nine"],
    },

    [phraseKey("jeden", "a0-11")]: {
        sk: "Mam jeden bilet.",
        ua: "У мене один квиток.",
        ru: "У меня один билет.",
        en: "I have one ticket.",
        uaTokens: ["У", "мене", "один", "квиток", "."],
        ruTokens: ["У", "меня", "один", "билет", "."],
        enTokens: ["I", "have", "one", "ticket", "."],
        extraUaTokens: ["часу", "два", "книжок"],
        extraRuTokens: ["времени", "два", "книг"],
        extraEnTokens: ["time", "two", "books"],
    },

    [phraseKey("dwa", "a0-11")]: {
        sk: "Widzę dwa domy.",
        ua: "Я бачу два будинки.",
        ru: "Я вижу два дома.",
        en: "I see two houses.",
        uaTokens: ["Я", "бачу", "два", "будинки", "."],
        ruTokens: ["Я", "вижу", "два", "дома", "."],
        enTokens: ["I", "see", "two", "houses", "."],
        extraUaTokens: ["квиток", "три", "стільці"],
        extraRuTokens: ["билет", "три", "стула"],
        extraEnTokens: ["ticket", "three", "chairs"],
    },

    [phraseKey("trzy", "a0-11")]: {
        sk: "Mam trzy pytania.",
        ua: "У мене три питання.",
        ru: "У меня три вопроса.",
        en: "I have three questions.",
        uaTokens: ["У", "мене", "три", "питання", "."],
        ruTokens: ["У", "меня", "три", "вопроса", "."],
        enTokens: ["I", "have", "three", "questions", "."],
        extraUaTokens: ["будинки", "один", "квиток"],
        extraRuTokens: ["дома", "один", "билет"],
        extraEnTokens: ["houses", "one", "ticket"],
    },

    [phraseKey("cztery", "a0-11")]: {
        sk: "Są cztery krzesła.",
        ua: "Є чотири стільці.",
        ru: "Есть четыре стула.",
        en: "There are four chairs.",
        uaTokens: ["Є", "чотири", "стільці", "."],
        ruTokens: ["Есть", "четыре", "стула", "."],
        enTokens: ["There", "are", "four", "chairs", "."],
        extraUaTokens: ["будинки", "п’ять", "годин"],
        extraRuTokens: ["дома", "пять", "часов"],
        extraEnTokens: ["houses", "five", "hours"],
    },

    [phraseKey("pięć", "a0-11")]: {
        sk: "Mam pięć euro.",
        ua: "У мене п’ять євро.",
        ru: "У меня пять евро.",
        en: "I have five euros.",
        uaTokens: ["У", "мене", "п’ять", "євро", "."],
        ruTokens: ["У", "меня", "пять", "евро", "."],
        enTokens: ["I", "have", "five", "euros", "."],
        extraUaTokens: ["квиток", "чотири", "питання"],
        extraRuTokens: ["билет", "четыре", "вопроса"],
        extraEnTokens: ["ticket", "four", "questions"],
    },

    [phraseKey("sześć", "a0-11")]: {
        sk: "Pracuję sześć godzin.",
        ua: "Я працюю шість годин.",
        ru: "Я работаю шесть часов.",
        en: "I work six hours.",
        uaTokens: ["Я", "працюю", "шість", "годин", "."],
        ruTokens: ["Я", "работаю", "шесть", "часов", "."],
        enTokens: ["I", "work", "six", "hours", "."],
        extraUaTokens: ["євро", "сім", "квиток"],
        extraRuTokens: ["евро", "семь", "билет"],
        extraEnTokens: ["euros", "seven", "ticket"],
    },

    [phraseKey("siedem", "a0-11")]: {
        sk: "Tydzień ma siedem dni.",
        ua: "Тиждень має сім днів.",
        ru: "В неделе семь дней.",
        en: "A week has seven days.",
        uaTokens: ["Тиждень", "має", "сім", "днів", "."],
        ruTokens: ["В", "неделе", "семь", "дней", "."],
        enTokens: ["A", "week", "has", "seven", "days", "."],
        extraUaTokens: ["годин", "вісім", "книжок"],
        extraRuTokens: ["часов", "восемь", "книг"],
        extraEnTokens: ["hours", "eight", "books"],
    },

    [phraseKey("osiem", "a0-11")]: {
        sk: "Jest ósma, nie osiem.",
        ua: "Зараз восьма година, не вісім.",
        ru: "Сейчас восемь часов, а не просто восемь.",
        en: "It is eight o’clock, not just eight.",
        uaTokens: ["Зараз", "восьма", "година", ",", "не", "вісім", "."],
        ruTokens: ["Сейчас", "восемь", "часов", ",", "а", "не", "просто", "восемь", "."],
        enTokens: ["It", "is", "eight", "o’clock", ",", "not", "just", "eight", "."],
        extraUaTokens: ["днів", "дев’ять", "квиток"],
        extraRuTokens: ["дней", "девять", "билет"],
        extraEnTokens: ["days", "nine", "ticket"],
    },

    [phraseKey("dziewięć", "a0-11")]: {
        sk: "Mam dziewięć książek.",
        ua: "У мене дев’ять книжок.",
        ru: "У меня девять книг.",
        en: "I have nine books.",
        uaTokens: ["У", "мене", "дев’ять", "книжок", "."],
        ruTokens: ["У", "меня", "девять", "книг", "."],
        enTokens: ["I", "have", "nine", "books", "."],
        extraUaTokens: ["євро", "вісім", "питання"],
        extraRuTokens: ["евро", "восемь", "вопроса"],
        extraEnTokens: ["euros", "eight", "questions"],
    },

    // =========================
    // LESSON 12 — Кольори
    // =========================
    [phraseKey("kolor", "a0-12")]: {
        sk: "Jaki to kolor?",
        ua: "Який це колір?",
        ru: "Какой это цвет?",
        en: "What color is this?",
        uaTokens: ["Який", "це", "колір", "?"],
        ruTokens: ["Какой", "это", "цвет", "?"],
        enTokens: ["What", "color", "is", "this", "?"],
        extraUaTokens: ["біле", "трава", "куртка"],
        extraRuTokens: ["белая", "трава", "куртка"],
        extraEnTokens: ["white", "grass", "jacket"],
    },

    [phraseKey("biały", "a0-12")]: {
        sk: "To jest biały samochód.",
        ua: "Це біле авто.",
        ru: "Это белая машина.",
        en: "This is a white car.",
        uaTokens: ["Це", "біле", "авто", "."],
        ruTokens: ["Это", "белая", "машина", "."],
        enTokens: ["This", "is", "a", "white", "car", "."],
        extraUaTokens: ["чорна", "сумка", "трава"],
        extraRuTokens: ["чёрная", "сумка", "трава"],
        extraEnTokens: ["black", "bag", "grass"],
    },

    [phraseKey("czarny", "a0-12")]: {
        sk: "Mam czarną torbę.",
        ua: "У мене чорна сумка.",
        ru: "У меня чёрная сумка.",
        en: "I have a black bag.",
        uaTokens: ["У", "мене", "чорна", "сумка", "."],
        ruTokens: ["У", "меня", "чёрная", "сумка", "."],
        enTokens: ["I", "have", "a", "black", "bag", "."],
        extraUaTokens: ["біле", "авто", "рожева"],
        extraRuTokens: ["белая", "машина", "розовая"],
        extraEnTokens: ["white", "car", "pink"],
    },

    [phraseKey("czerwony", "a0-12")]: {
        sk: "Lubię czerwony kolor.",
        ua: "Я люблю червоний колір.",
        ru: "Я люблю красный цвет.",
        en: "I like red.",
        uaTokens: ["Я", "люблю", "червоний", "колір", "."],
        ruTokens: ["Я", "люблю", "красный", "цвет", "."],
        enTokens: ["I", "like", "red", "."],
        extraUaTokens: ["сумка", "синє", "куртка"],
        extraRuTokens: ["сумка", "синее", "куртка"],
        extraEnTokens: ["bag", "blue", "jacket"],
    },

    [phraseKey("niebieski", "a0-12")]: {
        sk: "Niebo jest niebieskie.",
        ua: "Небо синє.",
        ru: "Небо синее.",
        en: "The sky is blue.",
        uaTokens: ["Небо", "синє", "."],
        ruTokens: ["Небо", "синее", "."],
        enTokens: ["The", "sky", "is", "blue", "."],
        extraUaTokens: ["трава", "червоний", "сумка"],
        extraRuTokens: ["трава", "красный", "сумка"],
        extraEnTokens: ["grass", "red", "bag"],
    },

    [phraseKey("zielony", "a0-12")]: {
        sk: "Trawa jest zielona.",
        ua: "Трава зелена.",
        ru: "Трава зелёная.",
        en: "The grass is green.",
        uaTokens: ["Трава", "зелена", "."],
        ruTokens: ["Трава", "зелёная", "."],
        enTokens: ["The", "grass", "is", "green", "."],
        extraUaTokens: ["небо", "жовта", "куртка"],
        extraRuTokens: ["небо", "жёлтая", "куртка"],
        extraEnTokens: ["sky", "yellow", "jacket"],
    },

    [phraseKey("żółty", "a0-12")]: {
        sk: "Mam żółtą koszulkę.",
        ua: "У мене жовта футболка.",
        ru: "У меня жёлтая футболка.",
        en: "I have a yellow T-shirt.",
        uaTokens: ["У", "мене", "жовта", "футболка", "."],
        ruTokens: ["У", "меня", "жёлтая", "футболка", "."],
        enTokens: ["I", "have", "a", "yellow", "T-shirt", "."],
        extraUaTokens: ["сумка", "чорна", "трава"],
        extraRuTokens: ["сумка", "чёрная", "трава"],
        extraEnTokens: ["bag", "black", "grass"],
    },

    [phraseKey("pomarańczowy", "a0-12")]: {
        sk: "To jest pomarańczowa kurtka.",
        ua: "Це помаранчева куртка.",
        ru: "Это оранжевая куртка.",
        en: "This is an orange jacket.",
        uaTokens: ["Це", "помаранчева", "куртка", "."],
        ruTokens: ["Это", "оранжевая", "куртка", "."],
        enTokens: ["This", "is", "an", "orange", "jacket", "."],
        extraUaTokens: ["сумка", "жовта", "небо"],
        extraRuTokens: ["сумка", "жёлтая", "небо"],
        extraEnTokens: ["bag", "yellow", "sky"],
    },

    [phraseKey("różowy", "a0-12")]: {
        sk: "Lampa jest różowa.",
        ua: "Лампа рожева.",
        ru: "Лампа розовая.",
        en: "The lamp is pink.",
        uaTokens: ["Лампа", "рожева", "."],
        ruTokens: ["Лампа", "розовая", "."],
        enTokens: ["The", "lamp", "is", "pink", "."],
        extraUaTokens: ["стіл", "коричневий", "трава"],
        extraRuTokens: ["стол", "коричневый", "трава"],
        extraEnTokens: ["table", "brown", "grass"],
    },

    [phraseKey("brązowy", "a0-12")]: {
        sk: "Stół jest brązowy.",
        ua: "Стіл коричневий.",
        ru: "Стол коричневый.",
        en: "The table is brown.",
        uaTokens: ["Стіл", "коричневий", "."],
        ruTokens: ["Стол", "коричневый", "."],
        enTokens: ["The", "table", "is", "brown", "."],
        extraUaTokens: ["лампа", "рожева", "синє"],
        extraRuTokens: ["лампа", "розовая", "синее"],
        extraEnTokens: ["lamp", "pink", "blue"],
    },

    // =========================
    // LESSON 13 — Одяг
    // =========================
    [phraseKey("ubranie", "a0-13")]: {
        sk: "To ubranie jest nowe.",
        ua: "Цей одяг новий.",
        ru: "Эта одежда новая.",
        en: "This clothing is new.",
        uaTokens: ["Цей", "одяг", "новий", "."],
        ruTokens: ["Эта", "одежда", "новая", "."],
        enTokens: ["This", "clothing", "is", "new", "."],
        extraUaTokens: ["футболка", "теплий", "взуття"],
        extraRuTokens: ["футболка", "тёплый", "обувь"],
        extraEnTokens: ["T-shirt", "warm", "shoes"],
    },

    [phraseKey("koszulka", "a0-13")]: {
        sk: "Mam białą koszulkę.",
        ua: "У мене біла футболка.",
        ru: "У меня белая футболка.",
        en: "I have a white T-shirt.",
        uaTokens: ["У", "мене", "біла", "футболка", "."],
        ruTokens: ["У", "меня", "белая", "футболка", "."],
        enTokens: ["I", "have", "a", "white", "T-shirt", "."],
        extraUaTokens: ["штани", "теплий", "шапка"],
        extraRuTokens: ["брюки", "тёплый", "шапка"],
        extraEnTokens: ["trousers", "warm", "hat"],
    },

    [phraseKey("spodnie", "a0-13")]: {
        sk: "Te spodnie są wygodne.",
        ua: "Ці штани зручні.",
        ru: "Эти брюки удобные.",
        en: "These trousers are comfortable.",
        uaTokens: ["Ці", "штани", "зручні", "."],
        ruTokens: ["Эти", "брюки", "удобные", "."],
        enTokens: ["These", "trousers", "are", "comfortable", "."],
        extraUaTokens: ["футболка", "біла", "светр"],
        extraRuTokens: ["футболка", "белая", "свитер"],
        extraEnTokens: ["T-shirt", "white", "sweater"],
    },

    [phraseKey("kurtka", "a0-13")]: {
        sk: "Zakładam kurtkę.",
        ua: "Я одягаю куртку.",
        ru: "Я надеваю куртку.",
        en: "I am putting on a jacket.",
        uaTokens: ["Я", "одягаю", "куртку", "."],
        ruTokens: ["Я", "надеваю", "куртку", "."],
        enTokens: ["I", "am", "putting", "on", "a", "jacket", "."],
        extraUaTokens: ["футболка", "теплий", "шапка"],
        extraRuTokens: ["футболка", "тёплый", "шапка"],
        extraEnTokens: ["T-shirt", "warm", "hat"],
    },

    [phraseKey("buty", "a0-13")]: {
        sk: "Moje buty są czyste.",
        ua: "Моє взуття чисте.",
        ru: "Моя обувь чистая.",
        en: "My shoes are clean.",
        uaTokens: ["Моє", "взуття", "чисте", "."],
        ruTokens: ["Моя", "обувь", "чистая", "."],
        enTokens: ["My", "shoes", "are", "clean", "."],
        extraUaTokens: ["куртка", "тепле", "ліжком"],
        extraRuTokens: ["куртка", "тёплое", "кроватью"],
        extraEnTokens: ["jacket", "warm", "bed"],
    },

    [phraseKey("płaszcz", "a0-13")]: {
        sk: "Ten płaszcz jest ciepły.",
        ua: "Це пальто тепле.",
        ru: "Это пальто тёплое.",
        en: "This coat is warm.",
        uaTokens: ["Це", "пальто", "тепле", "."],
        ruTokens: ["Это", "пальто", "тёплое", "."],
        enTokens: ["This", "coat", "is", "warm", "."],
        extraUaTokens: ["сукня", "красива", "шапка"],
        extraRuTokens: ["платье", "красивое", "шапка"],
        extraEnTokens: ["dress", "beautiful", "hat"],
    },

    [phraseKey("sukienka", "a0-13")]: {
        sk: "Ta sukienka jest piękna.",
        ua: "Ця сукня красива.",
        ru: "Это платье красивое.",
        en: "This dress is beautiful.",
        uaTokens: ["Ця", "сукня", "красива", "."],
        ruTokens: ["Это", "платье", "красивое", "."],
        enTokens: ["This", "dress", "is", "beautiful", "."],
        extraUaTokens: ["пальто", "тепле", "шапка"],
        extraRuTokens: ["пальто", "тёплое", "шапка"],
        extraEnTokens: ["coat", "warm", "hat"],
    },

    [phraseKey("czapka", "a0-13")]: {
        sk: "Mam zimową czapkę.",
        ua: "У мене зимова шапка.",
        ru: "У меня зимняя шапка.",
        en: "I have a winter hat.",
        uaTokens: ["У", "мене", "зимова", "шапка", "."],
        ruTokens: ["У", "меня", "зимняя", "шапка", "."],
        enTokens: ["I", "have", "a", "winter", "hat", "."],
        extraUaTokens: ["сукня", "красива", "куртка"],
        extraRuTokens: ["платье", "красивое", "куртка"],
        extraEnTokens: ["dress", "beautiful", "jacket"],
    },

    [phraseKey("skarpetki", "a0-13")]: {
        sk: "Skarpetki są pod łóżkiem.",
        ua: "Шкарпетки під ліжком.",
        ru: "Носки под кроватью.",
        en: "The socks are under the bed.",
        uaTokens: ["Шкарпетки", "під", "ліжком", "."],
        ruTokens: ["Носки", "под", "кроватью", "."],
        enTokens: ["The", "socks", "are", "under", "the", "bed", "."],
        extraUaTokens: ["шапка", "тепле", "взуття"],
        extraRuTokens: ["шапка", "тёплое", "обувь"],
        extraEnTokens: ["hat", "warm", "shoes"],
    },

    [phraseKey("sweter", "a0-13")]: {
        sk: "Noszę ciepły sweter.",
        ua: "Я ношу теплий светр.",
        ru: "Я ношу тёплый свитер.",
        en: "I wear a warm sweater.",
        uaTokens: ["Я", "ношу", "теплий", "светр", "."],
        ruTokens: ["Я", "ношу", "тёплый", "свитер", "."],
        enTokens: ["I", "wear", "a", "warm", "sweater", "."],
        extraUaTokens: ["шапка", "красива", "куртка"],
        extraRuTokens: ["шапка", "красивая", "куртка"],
        extraEnTokens: ["hat", "beautiful", "jacket"],
    },

    // =========================
    // LESSON 14 — Тіло людини
    // =========================
    [phraseKey("ciało", "a0-14")]: {
        sk: "Ciało potrzebuje odpoczynku.",
        ua: "Тілу потрібен відпочинок.",
        ru: "Телу нужен отдых.",
        en: "The body needs rest.",
        uaTokens: ["Тілу", "потрібен", "відпочинок", "."],
        ruTokens: ["Телу", "нужен", "отдых", "."],
        enTokens: ["The", "body", "needs", "rest", "."],
        extraUaTokens: ["голова", "холодний", "швидко"],
        extraRuTokens: ["голова", "холодный", "быстро"],
        extraEnTokens: ["head", "cold", "quickly"],
    },

    [phraseKey("głowa", "a0-14")]: {
        sk: "Boli mnie głowa.",
        ua: "У мене болить голова.",
        ru: "У меня болит голова.",
        en: "My head hurts.",
        uaTokens: ["У", "мене", "болить", "голова", "."],
        ruTokens: ["У", "меня", "болит", "голова", "."],
        enTokens: ["My", "head", "hurts", "."],
        extraUaTokens: ["руку", "холодний", "відпочинок"],
        extraRuTokens: ["руку", "холодный", "отдых"],
        extraEnTokens: ["hand", "cold", "rest"],
    },

    [phraseKey("oko", "a0-14")]: {
        sk: "Mam niebieskie oczy.",
        ua: "У мене сині очі.",
        ru: "У меня голубые глаза.",
        en: "I have blue eyes.",
        uaTokens: ["У", "мене", "сині", "очі", "."],
        ruTokens: ["У", "меня", "голубые", "глаза", "."],
        enTokens: ["I", "have", "blue", "eyes", "."],
        extraUaTokens: ["голова", "ніс", "холодний"],
        extraRuTokens: ["голова", "нос", "холодный"],
        extraEnTokens: ["head", "nose", "cold"],
    },

    [phraseKey("nos", "a0-14")]: {
        sk: "Mój nos jest zimny.",
        ua: "Мій ніс холодний.",
        ru: "Мой нос холодный.",
        en: "My nose is cold.",
        uaTokens: ["Мій", "ніс", "холодний", "."],
        ruTokens: ["Мой", "нос", "холодный", "."],
        enTokens: ["My", "nose", "is", "cold", "."],
        extraUaTokens: ["очі", "сині", "руку"],
        extraRuTokens: ["глаза", "голубые", "руку"],
        extraEnTokens: ["eyes", "blue", "hand"],
    },

    [phraseKey("usta", "a0-14")]: {
        sk: "Otwórz usta, proszę.",
        ua: "Відкрий рот, будь ласка.",
        ru: "Открой рот, пожалуйста.",
        en: "Open your mouth, please.",
        uaTokens: ["Відкрий", "рот", ",", "будь", "ласка", "."],
        ruTokens: ["Открой", "рот", ",", "пожалуйста", "."],
        enTokens: ["Open", "your", "mouth", ",", "please", "."],
        extraUaTokens: ["руку", "холодний", "швидко"],
        extraRuTokens: ["руку", "холодный", "быстро"],
        extraEnTokens: ["hand", "cold", "quickly"],
    },

    [phraseKey("ręka", "a0-14")]: {
        sk: "Podnieś rękę.",
        ua: "Підніми руку.",
        ru: "Подними руку.",
        en: "Raise your hand.",
        uaTokens: ["Підніми", "руку", "."],
        ruTokens: ["Подними", "руку", "."],
        enTokens: ["Raise", "your", "hand", "."],
        extraUaTokens: ["нога", "болить", "рот"],
        extraRuTokens: ["нога", "болит", "рот"],
        extraEnTokens: ["leg", "hurts", "mouth"],
    },

    [phraseKey("noga", "a0-14")]: {
        sk: "Boli mnie noga.",
        ua: "У мене болить нога.",
        ru: "У меня болит нога.",
        en: "My leg hurts.",
        uaTokens: ["У", "мене", "болить", "нога", "."],
        ruTokens: ["У", "меня", "болит", "нога", "."],
        enTokens: ["My", "leg", "hurts", "."],
        extraUaTokens: ["руку", "спина", "швидко"],
        extraRuTokens: ["руку", "спина", "быстро"],
        extraEnTokens: ["hand", "back", "quickly"],
    },

    [phraseKey("plecy", "a0-14")]: {
        sk: "Bolą mnie plecy.",
        ua: "У мене болить спина.",
        ru: "У меня болит спина.",
        en: "My back hurts.",
        uaTokens: ["У", "мене", "болить", "спина", "."],
        ruTokens: ["У", "меня", "болит", "спина", "."],
        enTokens: ["My", "back", "hurts", "."],
        extraUaTokens: ["нога", "живіт", "руку"],
        extraRuTokens: ["нога", "живот", "руку"],
        extraEnTokens: ["leg", "stomach", "hand"],
    },

    [phraseKey("brzuch", "a0-14")]: {
        sk: "Boli mnie brzuch.",
        ua: "У мене болить живіт.",
        ru: "У меня болит живот.",
        en: "My stomach hurts.",
        uaTokens: ["У", "мене", "болить", "живіт", "."],
        ruTokens: ["У", "меня", "болит", "живот", "."],
        enTokens: ["My", "stomach", "hurts", "."],
        extraUaTokens: ["спина", "голова", "швидко"],
        extraRuTokens: ["спина", "голова", "быстро"],
        extraEnTokens: ["back", "head", "quickly"],
    },

    [phraseKey("serce", "a0-14")]: {
        sk: "Moje serce bije szybko.",
        ua: "Моє серце б’ється швидко.",
        ru: "Моё сердце бьётся быстро.",
        en: "My heart beats fast.",
        uaTokens: ["Моє", "серце", "б’ється", "швидко", "."],
        ruTokens: ["Моё", "сердце", "бьётся", "быстро", "."],
        enTokens: ["My", "heart", "beats", "fast", "."],
        extraUaTokens: ["живіт", "холодний", "руку"],
        extraRuTokens: ["живот", "холодный", "руку"],
        extraEnTokens: ["stomach", "cold", "hand"],
    },

    // =========================
    // LESSON 15 — Здоров’я
    // =========================
    [phraseKey("zdrowie", "a0-15")]: {
        sk: "Zdrowie jest ważne.",
        ua: "Здоров’я важливе.",
        ru: "Здоровье важно.",
        en: "Health is important.",
        uaTokens: ["Здоров’я", "важливе", "."],
        ruTokens: ["Здоровье", "важно", "."],
        enTokens: ["Health", "is", "important", "."],
        extraUaTokens: ["лікар", "сильний", "кашель"],
        extraRuTokens: ["врач", "сильную", "кашель"],
        extraEnTokens: ["doctor", "strong", "cough"],
    },

    [phraseKey("choroba", "a0-15")]: {
        sk: "To jest poważna choroba.",
        ua: "Це серйозна хвороба.",
        ru: "Это серьёзная болезнь.",
        en: "This is a serious illness.",
        uaTokens: ["Це", "серйозна", "хвороба", "."],
        ruTokens: ["Это", "серьёзная", "болезнь", "."],
        enTokens: ["This", "is", "a", "serious", "illness", "."],
        extraUaTokens: ["лікар", "кашель", "швидко"],
        extraRuTokens: ["врач", "кашель", "быстро"],
        extraEnTokens: ["doctor", "cough", "quickly"],
    },

    [phraseKey("lekarz", "a0-15")]: {
        sk: "Idę do lekarza.",
        ua: "Я йду до лікаря.",
        ru: "Я иду к врачу.",
        en: "I am going to the doctor.",
        uaTokens: ["Я", "йду", "до", "лікаря", "."],
        ruTokens: ["Я", "иду", "к", "врачу", "."],
        enTokens: ["I", "am", "going", "to", "the", "doctor", "."],
        extraUaTokens: ["хвороба", "ліки", "кашель"],
        extraRuTokens: ["болезнь", "лекарство", "кашель"],
        extraEnTokens: ["illness", "medicine", "cough"],
    },

    [phraseKey("szpital", "a0-15")]: {
        sk: "Szpital jest blisko.",
        ua: "Лікарня близько.",
        ru: "Больница рядом.",
        en: "The hospital is nearby.",
        uaTokens: ["Лікарня", "близько", "."],
        ruTokens: ["Больница", "рядом", "."],
        enTokens: ["The", "hospital", "is", "nearby", "."],
        extraUaTokens: ["лікар", "температура", "сильний"],
        extraRuTokens: ["врач", "температура", "сильную"],
        extraEnTokens: ["doctor", "temperature", "strong"],
    },

    [phraseKey("lek", "a0-15")]: {
        sk: "Muszę wziąć lek.",
        ua: "Мені треба прийняти ліки.",
        ru: "Мне нужно принять лекарство.",
        en: "I need to take medicine.",
        uaTokens: ["Мені", "треба", "прийняти", "ліки", "."],
        ruTokens: ["Мне", "нужно", "принять", "лекарство", "."],
        enTokens: ["I", "need", "to", "take", "medicine", "."],
        extraUaTokens: ["лікар", "кашель", "швидко"],
        extraRuTokens: ["врач", "кашель", "быстро"],
        extraEnTokens: ["doctor", "cough", "quickly"],
    },

    [phraseKey("ból", "a0-15")]: {
        sk: "Czuję silny ból.",
        ua: "Я відчуваю сильний біль.",
        ru: "Я чувствую сильную боль.",
        en: "I feel severe pain.",
        uaTokens: ["Я", "відчуваю", "сильний", "біль", "."],
        ruTokens: ["Я", "чувствую", "сильную", "боль", "."],
        enTokens: ["I", "feel", "severe", "pain", "."],
        extraUaTokens: ["ліки", "кашель", "лікарня"],
        extraRuTokens: ["лекарство", "кашель", "больница"],
        extraEnTokens: ["medicine", "cough", "hospital"],
    },

    [phraseKey("temperatura", "a0-15")]: {
        sk: "Mam wysoką temperaturę.",
        ua: "У мене висока температура.",
        ru: "У меня высокая температура.",
        en: "I have a high temperature.",
        uaTokens: ["У", "мене", "висока", "температура", "."],
        ruTokens: ["У", "меня", "высокая", "температура", "."],
        enTokens: ["I", "have", "a", "high", "temperature", "."],
        extraUaTokens: ["кашель", "лікар", "важливе"],
        extraRuTokens: ["кашель", "врач", "важно"],
        extraEnTokens: ["cough", "doctor", "important"],
    },

    [phraseKey("kaszel", "a0-15")]: {
        sk: "Mam suchy kaszel.",
        ua: "У мене сухий кашель.",
        ru: "У меня сухой кашель.",
        en: "I have a dry cough.",
        uaTokens: ["У", "мене", "сухий", "кашель", "."],
        ruTokens: ["У", "меня", "сухой", "кашель", "."],
        enTokens: ["I", "have", "a", "dry", "cough", "."],
        extraUaTokens: ["температура", "лікар", "сильний"],
        extraRuTokens: ["температура", "врач", "сильную"],
        extraEnTokens: ["temperature", "doctor", "strong"],
    },

    [phraseKey("przeziębienie", "a0-15")]: {
        sk: "Mam przeziębienie.",
        ua: "У мене застуда.",
        ru: "У меня простуда.",
        en: "I have a cold.",
        uaTokens: ["У", "мене", "застуда", "."],
        ruTokens: ["У", "меня", "простуда", "."],
        enTokens: ["I", "have", "a", "cold", "."],
        extraUaTokens: ["кашель", "лікар", "швидко"],
        extraRuTokens: ["кашель", "врач", "быстро"],
        extraEnTokens: ["cough", "doctor", "quickly"],
    },

    [phraseKey("wyzdrowieć", "a0-15")]: {
        sk: "Chcę szybko wyzdrowieć.",
        ua: "Я хочу швидко одужати.",
        ru: "Я хочу быстро выздороветь.",
        en: "I want to recover quickly.",
        uaTokens: ["Я", "хочу", "швидко", "одужати", "."],
        ruTokens: ["Я", "хочу", "быстро", "выздороветь", "."],
        enTokens: ["I", "want", "to", "recover", "quickly", "."],
        extraUaTokens: ["кашель", "ліки", "температура"],
        extraRuTokens: ["кашель", "лекарство", "температура"],
        extraEnTokens: ["cough", "medicine", "temperature"],
    },
};