// app/learning/build-ua-sentences/a2/a2-1.ts
import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A2_BUILD_UA_SENTENCES_1: BuildUaSentenceDict = {
  // =========================
  // LESSON 1 — Dom a bývanie (rozšírené)
  // =========================
  [phraseKey("nájom", "a2-1")]: {
    sk: "Platím nájom každý mesiac.",
    ua: "Я плачу оренду щомісяця.",
    ru: "Я плачу аренду каждый месяц.",
    en: "I pay rent every month.",
    uaTokens: ["Я", "плачу", "оренду", "щомісяця", "."],
    ruTokens: ["Я", "плачу", "аренду", "каждый", "месяц", "."],
    enTokens: ["I", "pay", "rent", "every", "month", "."],
    extraUaTokens: ["квартира", "будинок", "рахунок"],
    extraRuTokens: ["квартира", "дом", "счёт"],
    extraEnTokens: ["apartment", "house", "bill"],
  },

  [phraseKey("nájomná zmluva", "a2-1")]: {
    sk: "Podpísali sme nájomnú zmluvu na jeden rok.",
    ua: "Ми підписали договір оренди на один рік.",
    ru: "Мы подписали договор аренды на один год.",
    en: "We signed a rental contract for one year.",
    uaTokens: ["Ми", "підписали", "договір", "оренди", "на", "один", "рік", "."],
    ruTokens: ["Мы", "подписали", "договор", "аренды", "на", "один", "год", "."],
    enTokens: ["We", "signed", "a", "rental", "contract", "for", "one", "year", "."],
    extraUaTokens: ["власник", "документ", "житло"],
    extraRuTokens: ["владелец", "документ", "жильё"],
    extraEnTokens: ["owner", "document", "housing"],
  },

  [phraseKey("majiteľ", "a2-1")]: {
    sk: "Majiteľ bytu býva vedľa.",
    ua: "Власник квартири живе поруч.",
    ru: "Владелец квартиры живёт рядом.",
    en: "The apartment owner lives nearby.",
    uaTokens: ["Власник", "квартири", "живе", "поруч", "."],
    ruTokens: ["Владелец", "квартиры", "живёт", "рядом", "."],
    enTokens: ["The", "apartment", "owner", "lives", "nearby", "."],
    extraUaTokens: ["сусід", "під'їзд", "двері"],
    extraRuTokens: ["сосед", "подъезд", "дверь"],
    extraEnTokens: ["neighbor", "entrance", "door"],
  },

  [phraseKey("podnájomník", "a2-1")]: {
    sk: "Podnájomník musí dodržiavať pravidlá domu.",
    ua: "Орендар має дотримуватися правил будинку.",
    ru: "Арендатор должен соблюдать правила дома.",
    en: "The tenant must follow the house rules.",
    uaTokens: ["Орендар", "має", "дотримуватися", "правил", "будинку", "."],
    ruTokens: ["Арендатор", "должен", "соблюдать", "правила", "дома", "."],
    enTokens: ["The", "tenant", "must", "follow", "the", "house", "rules", "."],
    extraUaTokens: ["тиша", "кухня", "поверх"],
    extraRuTokens: ["тишина", "кухня", "этаж"],
    extraEnTokens: ["silence", "kitchen", "floor"],
  },

  [phraseKey("účty", "a2-1")]: {
    sk: "Tento mesiac sú účty vyššie.",
    ua: "Цього місяця рахунки вищі.",
    ru: "В этом месяце счета выше.",
    en: "This month the bills are higher.",
    uaTokens: ["Цього", "місяця", "рахунки", "вищі", "."],
    ruTokens: ["В", "этом", "месяце", "счета", "выше", "."],
    enTokens: ["This", "month", "the", "bills", "are", "higher", "."],
    extraUaTokens: ["електрика", "вода", "газ"],
    extraRuTokens: ["электричество", "вода", "газ"],
    extraEnTokens: ["electricity", "water", "gas"],
  },

  [phraseKey("energie", "a2-1")]: {
    sk: "V cene nájmu sú energie.",
    ua: "У вартість оренди входять комунальні послуги.",
    ru: "В стоимость аренды входят коммунальные услуги.",
    en: "Utilities are included in the rent.",
    uaTokens: ["У", "вартість", "оренди", "входять", "комунальні", "послуги", "."],
    ruTokens: ["В", "стоимость", "аренды", "входят", "коммунальные", "услуги", "."],
    enTokens: ["Utilities", "are", "included", "in", "the", "rent", "."],
    extraUaTokens: ["опалення", "світло", "платіж"],
    extraRuTokens: ["отопление", "свет", "платёж"],
    extraEnTokens: ["heating", "light", "payment"],
  },

  [phraseKey("oprava", "a2-1")]: {
    sk: "Oprava práčky bude zajtra.",
    ua: "Ремонт пральної машини буде завтра.",
    ru: "Ремонт стиральной машины будет завтра.",
    en: "The washing machine repair is scheduled for tomorrow.",
    uaTokens: ["Ремонт", "пральної", "машини", "буде", "завтра", "."],
    ruTokens: ["Ремонт", "стиральной", "машины", "будет", "завтра", "."],
    enTokens: ["The", "washing", "machine", "repair", "is", "scheduled", "for", "tomorrow", "."],
    extraUaTokens: ["майстер", "інструмент", "техніка"],
    extraRuTokens: ["мастер", "инструмент", "техника"],
    extraEnTokens: ["repairman", "tool", "equipment"],
  },

  [phraseKey("pokazený", "a2-1")]: {
    sk: "Výťah je pokazený.",
    ua: "Ліфт зламаний.",
    ru: "Лифт сломан.",
    en: "The elevator is broken.",
    uaTokens: ["Ліфт", "зламаний", "."],
    ruTokens: ["Лифт", "сломан", "."],
    enTokens: ["The", "elevator", "is", "broken", "."],
    extraUaTokens: ["сходи", "кнопка", "будівля"],
    extraRuTokens: ["лестница", "кнопка", "здание"],
    extraEnTokens: ["stairs", "button", "building"],
  },

  [phraseKey("sused", "a2-1")]: {
    sk: "Sused je večer veľmi hlučný.",
    ua: "Сусід увечері дуже шумний.",
    ru: "Сосед вечером очень шумный.",
    en: "The neighbor is very noisy in the evening.",
    uaTokens: ["Сусід", "увечері", "дуже", "шумний", "."],
    ruTokens: ["Сосед", "вечером", "очень", "шумный", "."],
    enTokens: ["The", "neighbor", "is", "very", "noisy", "in", "the", "evening", "."],
    extraUaTokens: ["музика", "стіна", "ніч"],
    extraRuTokens: ["музыка", "стена", "ночь"],
    extraEnTokens: ["music", "wall", "night"],
  },

  [phraseKey("sťahovanie", "a2-1")]: {
    sk: "Sťahovanie plánujeme na budúci víkend.",
    ua: "Переїзд плануємо на наступні вихідні.",
    ru: "Переезд планируем на следующие выходные.",
    en: "We are planning the move for next weekend.",
    uaTokens: ["Переїзд", "плануємо", "на", "наступні", "вихідні", "."],
    ruTokens: ["Переезд", "планируем", "на", "следующие", "выходные", "."],
    enTokens: ["We", "are", "planning", "the", "move", "for", "next", "weekend", "."],
    extraUaTokens: ["коробки", "меблі", "машина"],
    extraRuTokens: ["коробки", "мебель", "машина"],
    extraEnTokens: ["boxes", "furniture", "car"],
  },

  // =========================
  // LESSON 2 — U lekára
  // =========================
  [phraseKey("vyšetrenie", "a2-2")]: {
    sk: "Zajtra mám vyšetrenie u lekára.",
    ua: "Завтра маю обстеження у лікаря.",
    ru: "Завтра у меня обследование у врача.",
    en: "Tomorrow I have a medical examination.",
    uaTokens: ["Завтра", "маю", "обстеження", "у", "лікаря", "."],
    ruTokens: ["Завтра", "у", "меня", "обследование", "у", "врача", "."],
    enTokens: ["Tomorrow", "I", "have", "a", "medical", "examination", "."],
    extraUaTokens: ["поліклініка", "кабінет", "запис"],
    extraRuTokens: ["поликлиника", "кабинет", "запись"],
    extraEnTokens: ["clinic", "office", "appointment"],
  },

  [phraseKey("diagnóza", "a2-2")]: {
    sk: "Lekár mi vysvetlil diagnózu.",
    ua: "Лікар мені пояснив діагноз.",
    ru: "Врач мне объяснил диагноз.",
    en: "The doctor explained the diagnosis to me.",
    uaTokens: ["Лікар", "мені", "пояснив", "діагноз", "."],
    ruTokens: ["Врач", "мне", "объяснил", "диагноз", "."],
    enTokens: ["The", "doctor", "explained", "the", "diagnosis", "to", "me", "."],
    extraUaTokens: ["хвороба", "аналіз", "лікування"],
    extraRuTokens: ["болезнь", "анализ", "лечение"],
    extraEnTokens: ["illness", "test", "treatment"],
  },

  [phraseKey("príznak", "a2-2")]: {
    sk: "Hlavný príznak je kašeľ.",
    ua: "Основний симптом — кашель.",
    ru: "Главный симптом — кашель.",
    en: "The main symptom is a cough.",
    uaTokens: ["Основний", "симптом", "—", "кашель", "."],
    ruTokens: ["Главный", "симптом", "—", "кашель", "."],
    enTokens: ["The", "main", "symptom", "is", "a", "cough", "."],
    extraUaTokens: ["температура", "нежить", "горло"],
    extraRuTokens: ["температура", "насморк", "горло"],
    extraEnTokens: ["fever", "nose", "throat"],
  },

  [phraseKey("bolesť hrdla", "a2-2")]: {
    sk: "Mám bolesť hrdla už tri dni.",
    ua: "У мене болить горло вже три дні.",
    ru: "У меня болит горло уже три дня.",
    en: "I have had a sore throat for three days already.",
    uaTokens: ["У", "мене", "болить", "горло", "вже", "три", "дні", "."],
    ruTokens: ["У", "меня", "болит", "горло", "уже", "три", "дня", "."],
    enTokens: ["I", "have", "had", "a", "sore", "throat", "for", "three", "days", "already", "."],
    extraUaTokens: ["ковтати", "чай", "ліки"],
    extraRuTokens: ["глотать", "чай", "лекарство"],
    extraEnTokens: ["swallow", "tea", "medicine"],
  },

  [phraseKey("teplomer", "a2-2")]: {
    sk: "Máte doma teplomer?",
    ua: "У вас є вдома термометр?",
    ru: "У вас дома есть термометр?",
    en: "Do you have a thermometer at home?",
    uaTokens: ["У", "вас", "є", "вдома", "термометр", "?"],
    ruTokens: ["У", "вас", "дома", "есть", "термометр", "?"],
    enTokens: ["Do", "you", "have", "a", "thermometer", "at", "home", "?"],
    extraUaTokens: ["аптека", "лихоманка", "градуси"],
    extraRuTokens: ["аптека", "лихорадка", "градусы"],
    extraEnTokens: ["pharmacy", "fever", "degrees"],
  },

  [phraseKey("krvný tlak", "a2-2")]: {
    sk: "Zmerali mi krvný tlak.",
    ua: "Мені виміряли артеріальний тиск.",
    ru: "Мне измерили артериальное давление.",
    en: "They measured my blood pressure.",
    uaTokens: ["Мені", "виміряли", "артеріальний", "тиск", "."],
    ruTokens: ["Мне", "измерили", "артериальное", "давление", "."],
    enTokens: ["They", "measured", "my", "blood", "pressure", "."],
    extraUaTokens: ["серце", "медсестра", "результат"],
    extraRuTokens: ["сердце", "медсестра", "результат"],
    extraEnTokens: ["heart", "nurse", "result"],
  },

  [phraseKey("recept", "a2-2")]: {
    sk: "Dostal som recept na antibiotiká.",
    ua: "Я отримав рецепт на антибіотики.",
    ru: "Я получил рецепт на антибиотики.",
    en: "I got a prescription for antibiotics.",
    uaTokens: ["Я", "отримав", "рецепт", "на", "антибіотики", "."],
    ruTokens: ["Я", "получил", "рецепт", "на", "антибиотики", "."],
    enTokens: ["I", "got", "a", "prescription", "for", "antibiotics", "."],
    extraUaTokens: ["аптека", "таблетки", "лікар"],
    extraRuTokens: ["аптека", "таблетки", "врач"],
    extraEnTokens: ["pharmacy", "tablets", "doctor"],
  },

  [phraseKey("alergia", "a2-2")]: {
    sk: "Mám alergiu na peľ.",
    ua: "У мене алергія на пилок.",
    ru: "У меня аллергия на пыльцу.",
    en: "I am allergic to pollen.",
    uaTokens: ["У", "мене", "алергія", "на", "пилок", "."],
    ruTokens: ["У", "меня", "аллергия", "на", "пыльцу", "."],
    enTokens: ["I", "am", "allergic", "to", "pollen", "."],
    extraUaTokens: ["весна", "очі", "ніс"],
    extraRuTokens: ["весна", "глаза", "нос"],
    extraEnTokens: ["spring", "eyes", "nose"],
  },

  [phraseKey("zápal", "a2-2")]: {
    sk: "Vyzerá to na zápal priedušiek.",
    ua: "Схоже на запалення бронхів.",
    ru: "Похоже на воспаление бронхов.",
    en: "It looks like bronchitis.",
    uaTokens: ["Схоже", "на", "запалення", "бронхів", "."],
    ruTokens: ["Похоже", "на", "воспаление", "бронхов", "."],
    enTokens: ["It", "looks", "like", "bronchitis", "."],
    extraUaTokens: ["кашель", "легені", "дихання"],
    extraRuTokens: ["кашель", "лёгкие", "дыхание"],
    extraEnTokens: ["cough", "lungs", "breathing"],
  },

  [phraseKey("odporúčanie", "a2-2")]: {
    sk: "Podľa odporúčania lekára teraz oddychujem.",
    ua: "За рекомендацією лікаря зараз відпочиваю.",
    ru: "По рекомендации врача я сейчас отдыхаю.",
    en: "Following the doctor's recommendation, I am resting now.",
    uaTokens: ["За", "рекомендацією", "лікаря", "зараз", "відпочиваю", "."],
    ruTokens: ["По", "рекомендации", "врача", "я", "сейчас", "отдыхаю", "."],
    enTokens: ["Following", "the", "doctor's", "recommendation", ",", "I", "am", "resting", "now", "."],
    extraUaTokens: ["постіль", "спокій", "здоров'я"],
    extraRuTokens: ["постель", "покой", "здоровье"],
    extraEnTokens: ["bed", "rest", "health"],
  },

  // =========================
  // LESSON 3 — Mesto a služby
  // =========================
  [phraseKey("mestský úrad", "a2-3")]: {
    sk: "Potrebujem ísť na mestský úrad.",
    ua: "Мені потрібно піти до мерії.",
    ru: "Мне нужно пойти в мэрию.",
    en: "I need to go to the city hall.",
    uaTokens: ["Мені", "потрібно", "піти", "до", "мерії", "."],
    ruTokens: ["Мне", "нужно", "пойти", "в", "мэрию", "."],
    enTokens: ["I", "need", "to", "go", "to", "the", "city", "hall", "."],
    extraUaTokens: ["документи", "місто", "черга"],
    extraRuTokens: ["документы", "город", "очередь"],
    extraEnTokens: ["documents", "city", "queue"],
  },

  [phraseKey("oddelenie", "a2-3")]: {
    sk: "Na ktorom oddelení to vybavím?",
    ua: "У якому відділі я це оформлю?",
    ru: "В каком отделе я это оформлю?",
    en: "In which department can I arrange this?",
    uaTokens: ["У", "якому", "відділі", "я", "це", "оформлю", "?"],
    ruTokens: ["В", "каком", "отделе", "я", "это", "оформлю", "?"],
    enTokens: ["In", "which", "department", "can", "I", "arrange", "this", "?"],
    extraUaTokens: ["віконце", "довідка", "поверх"],
    extraRuTokens: ["окно", "справка", "этаж"],
    extraEnTokens: ["window", "certificate", "floor"],
  },

  [phraseKey("žiadateľ", "a2-3")]: {
    sk: "Žiadateľ musí vyplniť formulár.",
    ua: "Заявник має заповнити бланк.",
    ru: "Заявитель должен заполнить бланк.",
    en: "The applicant must fill out the form.",
    uaTokens: ["Заявник", "має", "заповнити", "бланк", "."],
    ruTokens: ["Заявитель", "должен", "заполнить", "бланк", "."],
    enTokens: ["The", "applicant", "must", "fill", "out", "the", "form", "."],
    extraUaTokens: ["підпис", "дані", "анкета"],
    extraRuTokens: ["подпись", "данные", "анкета"],
    extraEnTokens: ["signature", "data", "questionnaire"],
  },

  [phraseKey("žiadosť", "a2-3")]: {
    sk: "Podal som žiadosť o potvrdenie.",
    ua: "Я подав заяву на довідку.",
    ru: "Я подал заявление на справку.",
    en: "I submitted an application for a certificate.",
    uaTokens: ["Я", "подав", "заяву", "на", "довідку", "."],
    ruTokens: ["Я", "подал", "заявление", "на", "справку", "."],
    enTokens: ["I", "submitted", "an", "application", "for", "a", "certificate", "."],
    extraUaTokens: ["форма", "документ", "печатка"],
    extraRuTokens: ["форма", "документ", "печать"],
    extraEnTokens: ["form", "document", "stamp"],
  },

  [phraseKey("doklad", "a2-3")]: {
    sk: "Prosím, pripravte si doklad totožnosti.",
    ua: "Будь ласка, підготуйте документ, що посвідчує особу.",
    ru: "Пожалуйста, подготовьте документ, удостоверяющий личность.",
    en: "Please prepare your identity document.",
    uaTokens: ["Будь", "ласка", ",", "підготуйте", "документ", ",", "що", "посвідчує", "особу", "."],
    ruTokens: ["Пожалуйста", ",", "подготовьте", "документ", ",", "удостоверяющий", "личность", "."],
    enTokens: ["Please", "prepare", "your", "identity", "document", "."],
    extraUaTokens: ["паспорт", "карта", "номер"],
    extraRuTokens: ["паспорт", "карта", "номер"],
    extraEnTokens: ["passport", "card", "number"],
  },

  [phraseKey("potvrdenie", "a2-3")]: {
    sk: "Potvrdenie vám pošleme e-mailom.",
    ua: "Підтвердження надішлемо вам електронною поштою.",
    ru: "Подтверждение отправим вам по e-mail.",
    en: "We will send you the confirmation by e-mail.",
    uaTokens: ["Підтвердження", "надішлемо", "вам", "електронною", "поштою", "."],
    ruTokens: ["Подтверждение", "отправим", "вам", "по", "e-mail", "."],
    enTokens: ["We", "will", "send", "you", "the", "confirmation", "by", "e-mail", "."],
    extraUaTokens: ["лист", "адреса", "повідомлення"],
    extraRuTokens: ["письмо", "адрес", "сообщение"],
    extraEnTokens: ["letter", "address", "message"],
  },

  [phraseKey("poplatok", "a2-3")]: {
    sk: "Správny poplatok je desať eur.",
    ua: "Адміністративний збір — десять євро.",
    ru: "Административный сбор — десять евро.",
    en: "The administrative fee is ten euros.",
    uaTokens: ["Адміністративний", "збір", "—", "десять", "євро", "."],
    ruTokens: ["Административный", "сбор", "—", "десять", "евро", "."],
    enTokens: ["The", "administrative", "fee", "is", "ten", "euros", "."],
    extraUaTokens: ["каса", "оплата", "послуга"],
    extraRuTokens: ["касса", "оплата", "услуга"],
    extraEnTokens: ["desk", "payment", "service"],
  },

  [phraseKey("objednať sa", "a2-3")]: {
    sk: "Musím sa objednať vopred.",
    ua: "Мені потрібно записатися заздалегідь.",
    ru: "Мне нужно записаться заранее.",
    en: "I need to make an appointment in advance.",
    uaTokens: ["Мені", "потрібно", "записатися", "заздалегідь", "."],
    ruTokens: ["Мне", "нужно", "записаться", "заранее", "."],
    enTokens: ["I", "need", "to", "make", "an", "appointment", "in", "advance", "."],
    extraUaTokens: ["дата", "час", "візит"],
    extraRuTokens: ["дата", "время", "визит"],
    extraEnTokens: ["date", "time", "visit"],
  },

  [phraseKey("otváracie hodiny", "a2-3")]: {
    sk: "Aké sú otváracie hodiny?",
    ua: "Які години роботи?",
    ru: "Какие часы работы?",
    en: "What are the opening hours?",
    uaTokens: ["Які", "години", "роботи", "?"],
    ruTokens: ["Какие", "часы", "работы", "?"],
    enTokens: ["What", "are", "the", "opening", "hours", "?"],
    extraUaTokens: ["понеділок", "п'ятниця", "обід"],
    extraRuTokens: ["понедельник", "пятница", "обед"],
    extraEnTokens: ["Monday", "Friday", "lunch"],
  },

  [phraseKey("formulár", "a2-3")]: {
    sk: "Kde nájdem tento formulár?",
    ua: "Де я знайду цей бланк?",
    ru: "Где я найду этот бланк?",
    en: "Where can I find this form?",
    uaTokens: ["Де", "я", "знайду", "цей", "бланк", "?"],
    ruTokens: ["Где", "я", "найду", "этот", "бланк", "?"],
    enTokens: ["Where", "can", "I", "find", "this", "form", "?"],
    extraUaTokens: ["стіл", "сайт", "відділ"],
    extraRuTokens: ["стол", "сайт", "отдел"],
    extraEnTokens: ["desk", "website", "department"],
  },

  // =========================
  // LESSON 4 — Práca a kariéra
  // =========================
  [phraseKey("pohovor", "a2-4")]: {
    sk: "Zajtra mám pracovný pohovor.",
    ua: "Завтра маю співбесіду.",
    ru: "Завтра у меня собеседование.",
    en: "Tomorrow I have a job interview.",
    uaTokens: ["Завтра", "маю", "співбесіду", "."],
    ruTokens: ["Завтра", "у", "меня", "собеседование", "."],
    enTokens: ["Tomorrow", "I", "have", "a", "job", "interview", "."],
    extraUaTokens: ["робота", "компанія", "кандидат"],
    extraRuTokens: ["работа", "компания", "кандидат"],
    extraEnTokens: ["job", "company", "candidate"],
  },

  [phraseKey("životopis", "a2-4")]: {
    sk: "Pošlem vám životopis v PDF.",
    ua: "Я надішлю вам резюме у PDF.",
    ru: "Я отправлю вам резюме в PDF.",
    en: "I will send you my CV in PDF.",
    uaTokens: ["Я", "надішлю", "вам", "резюме", "у", "PDF", "."],
    ruTokens: ["Я", "отправлю", "вам", "резюме", "в", "PDF", "."],
    enTokens: ["I", "will", "send", "you", "my", "CV", "in", "PDF", "."],
    extraUaTokens: ["досвід", "файл", "електронна", "пошта"],
    extraRuTokens: ["опыт", "файл", "электронная", "почта"],
    extraEnTokens: ["experience", "file", "e-mail"],
  },

  [phraseKey("prax", "a2-4")]: {
    sk: "Mám trojročnú prax v servise.",
    ua: "У мене трирічний досвід роботи в сервісі.",
    ru: "У меня трёхлетний опыт работы в сервисе.",
    en: "I have three years of work experience in service.",
    uaTokens: ["У", "мене", "трирічний", "досвід", "роботи", "в", "сервісі", "."],
    ruTokens: ["У", "меня", "трёхлетний", "опыт", "работы", "в", "сервисе", "."],
    enTokens: ["I", "have", "three", "years", "of", "work", "experience", "in", "service", "."],
    extraUaTokens: ["майстерня", "професія", "навички"],
    extraRuTokens: ["мастерская", "профессия", "навыки"],
    extraEnTokens: ["workshop", "profession", "skills"],
  },

  [phraseKey("zručnosť", "a2-4")]: {
    sk: "Táto zručnosť je pre túto pozíciu dôležitá.",
    ua: "Ця навичка важлива для цієї посади.",
    ru: "Этот навык важен для этой должности.",
    en: "This skill is important for this position.",
    uaTokens: ["Ця", "навичка", "важлива", "для", "цієї", "посади", "."],
    ruTokens: ["Этот", "навык", "важен", "для", "этой", "должности", "."],
    enTokens: ["This", "skill", "is", "important", "for", "this", "position", "."],
    extraUaTokens: ["уміння", "роботодавець", "вимога"],
    extraRuTokens: ["умение", "работодатель", "требование"],
    extraEnTokens: ["ability", "employer", "requirement"],
  },

  [phraseKey("požiadavka", "a2-4")]: {
    sk: "Jedna požiadavka je angličtina.",
    ua: "Одна вимога — англійська.",
    ru: "Одно требование — английский.",
    en: "One requirement is English.",
    uaTokens: ["Одна", "вимога", "—", "англійська", "."],
    ruTokens: ["Одно", "требование", "—", "английский", "."],
    enTokens: ["One", "requirement", "is", "English", "."],
    extraUaTokens: ["мова", "рівень", "комунікація"],
    extraRuTokens: ["язык", "уровень", "коммуникация"],
    extraEnTokens: ["language", "level", "communication"],
  },

  [phraseKey("pracovná ponuka", "a2-4")]: {
    sk: "Našiel som zaujímavú pracovnú ponuku.",
    ua: "Я знайшов цікаву вакансію.",
    ru: "Я нашёл интересную вакансию.",
    en: "I found an interesting job offer.",
    uaTokens: ["Я", "знайшов", "цікаву", "вакансію", "."],
    ruTokens: ["Я", "нашёл", "интересную", "вакансию", "."],
    enTokens: ["I", "found", "an", "interesting", "job", "offer", "."],
    extraUaTokens: ["сайт", "оголошення", "компанія"],
    extraRuTokens: ["сайт", "объявление", "компания"],
    extraEnTokens: ["website", "advertisement", "company"],
  },

  [phraseKey("pracovná pozícia", "a2-4")]: {
    sk: "Táto pracovná pozícia je na plný úväzok.",
    ua: "Ця посада на повну зайнятість.",
    ru: "Эта должность на полную занятость.",
    en: "This position is full-time.",
    uaTokens: ["Ця", "посада", "на", "повну", "зайнятість", "."],
    ruTokens: ["Эта", "должность", "на", "полную", "занятость", "."],
    enTokens: ["This", "position", "is", "full-time", "."],
    extraUaTokens: ["графік", "контракт", "офіс"],
    extraRuTokens: ["график", "контракт", "офис"],
    extraEnTokens: ["schedule", "contract", "office"],
  },

  [phraseKey("zodpovednosť", "a2-4")]: {
    sk: "Moja zodpovednosť bude komunikácia so zákazníkmi.",
    ua: "Моя відповідальність — комунікація з клієнтами.",
    ru: "Моя ответственность — коммуникация с клиентами.",
    en: "My responsibility will be communication with clients.",
    uaTokens: ["Моя", "відповідальність", "—", "комунікація", "з", "клієнтами", "."],
    ruTokens: ["Моя", "ответственность", "—", "коммуникация", "с", "клиентами", "."],
    enTokens: ["My", "responsibility", "will", "be", "communication", "with", "clients", "."],
    extraUaTokens: ["дзвінки", "сервіс", "допомога"],
    extraRuTokens: ["звонки", "сервис", "помощь"],
    extraEnTokens: ["calls", "service", "help"],
  },

  [phraseKey("výhody", "a2-4")]: {
    sk: "Medzi výhody patrí aj stravné.",
    ua: "Серед бонусів є також компенсація на їжу.",
    ru: "Среди бонусов есть также компенсация на еду.",
    en: "The benefits also include a meal allowance.",
    uaTokens: ["Серед", "бонусів", "є", "також", "компенсація", "на", "їжу", "."],
    ruTokens: ["Среди", "бонусов", "есть", "также", "компенсация", "на", "еду", "."],
    enTokens: ["The", "benefits", "also", "include", "a", "meal", "allowance", "."],
    extraUaTokens: ["зарплата", "премія", "відпустка"],
    extraRuTokens: ["зарплата", "премия", "отпуск"],
    extraEnTokens: ["salary", "bonus", "vacation"],
  },

  [phraseKey("skúšobná doba", "a2-4")]: {
    sk: "Skúšobná doba trvá tri mesiace.",
    ua: "Випробувальний термін триває три місяці.",
    ru: "Испытательный срок длится три месяца.",
    en: "The probation period lasts three months.",
    uaTokens: ["Випробувальний", "термін", "триває", "три", "місяці", "."],
    ruTokens: ["Испытательный", "срок", "длится", "три", "месяца", "."],
    enTokens: ["The", "probation", "period", "lasts", "three", "months", "."],
    extraUaTokens: ["робота", "початок", "умови"],
    extraRuTokens: ["работа", "начало", "условия"],
    extraEnTokens: ["job", "start", "conditions"],
  },

  // =========================
  // LESSON 5 — Cestovanie (situácie)
  // =========================
  [phraseKey("rezervácia", "a2-5")]: {
    sk: "Moja rezervácia je na meno Novák.",
    ua: "Моє бронювання на прізвище Новак.",
    ru: "Моё бронирование на фамилию Новак.",
    en: "My reservation is under the name Novák.",
    uaTokens: ["Моє", "бронювання", "на", "прізвище", "Новак", "."],
    ruTokens: ["Моё", "бронирование", "на", "фамилию", "Новак", "."],
    enTokens: ["My", "reservation", "is", "under", "the", "name", "Novák", "."],
    extraUaTokens: ["готель", "номер", "стійка"],
    extraRuTokens: ["отель", "номер", "стойка"],
    extraEnTokens: ["hotel", "room", "desk"],
  },

  [phraseKey("ubytovanie", "a2-5")]: {
    sk: "Hľadáme lacné ubytovanie pri stanici.",
    ua: "Шукаємо недороге проживання біля вокзалу.",
    ru: "Ищем недорогое жильё рядом с вокзалом.",
    en: "We are looking for cheap accommodation near the station.",
    uaTokens: ["Шукаємо", "недороге", "проживання", "біля", "вокзалу", "."],
    ruTokens: ["Ищем", "недорогое", "жильё", "рядом", "с", "вокзалом", "."],
    enTokens: ["We", "are", "looking", "for", "cheap", "accommodation", "near", "the", "station", "."],
    extraUaTokens: ["центр", "кімната", "подорож"],
    extraRuTokens: ["центр", "комната", "поездка"],
    extraEnTokens: ["center", "room", "trip"],
  },

  [phraseKey("potvrdiť", "a2-5")]: {
    sk: "Môžete mi potvrdiť rezerváciu?",
    ua: "Можете підтвердити моє бронювання?",
    ru: "Можете подтвердить моё бронирование?",
    en: "Can you confirm my reservation?",
    uaTokens: ["Можете", "підтвердити", "моє", "бронювання", "?"],
    ruTokens: ["Можете", "подтвердить", "моё", "бронирование", "?"],
    enTokens: ["Can", "you", "confirm", "my", "reservation", "?"],
    extraUaTokens: ["лист", "дата", "ім'я"],
    extraRuTokens: ["письмо", "дата", "имя"],
    extraEnTokens: ["letter", "date", "name"],
  },

  [phraseKey("zrušiť", "a2-5")]: {
    sk: "Chcel by som zrušiť objednávku.",
    ua: "Я хотів би скасувати замовлення.",
    ru: "Я хотел бы отменить заказ.",
    en: "I would like to cancel the booking.",
    uaTokens: ["Я", "хотів", "би", "скасувати", "замовлення", "."],
    ruTokens: ["Я", "хотел", "бы", "отменить", "заказ", "."],
    enTokens: ["I", "would", "like", "to", "cancel", "the", "booking", "."],
    extraUaTokens: ["квиток", "номер", "помилка"],
    extraRuTokens: ["билет", "номер", "ошибка"],
    extraEnTokens: ["ticket", "number", "mistake"],
  },

  [phraseKey("meškanie", "a2-5")]: {
    sk: "Let má meškanie dve hodiny.",
    ua: "Рейс затримується на дві години.",
    ru: "Рейс задерживается на два часа.",
    en: "The flight is delayed by two hours.",
    uaTokens: ["Рейс", "затримується", "на", "дві", "години", "."],
    ruTokens: ["Рейс", "задерживается", "на", "два", "часа", "."],
    enTokens: ["The", "flight", "is", "delayed", "by", "two", "hours", "."],
    extraUaTokens: ["аеропорт", "табло", "виліт"],
    extraRuTokens: ["аэропорт", "табло", "вылет"],
    extraEnTokens: ["airport", "board", "departure"],
  },

  [phraseKey("presun", "a2-5")]: {
    sk: "Potrebujem presun na letisko.",
    ua: "Мені потрібен трансфер до аеропорту.",
    ru: "Мне нужен трансфер в аэропорт.",
    en: "I need a transfer to the airport.",
    uaTokens: ["Мені", "потрібен", "трансфер", "до", "аеропорту", "."],
    ruTokens: ["Мне", "нужен", "трансфер", "в", "аэропорт", "."],
    enTokens: ["I", "need", "a", "transfer", "to", "the", "airport", "."],
    extraUaTokens: ["таксі", "багаж", "дорога"],
    extraRuTokens: ["такси", "багаж", "дорога"],
    extraEnTokens: ["taxi", "luggage", "road"],
  },

  [phraseKey("jednosmerný", "a2-5")]: {
    sk: "Prosím si jednosmerný lístok.",
    ua: "Будь ласка, один квиток в один бік.",
    ru: "Пожалуйста, билет в одну сторону.",
    en: "One one-way ticket, please.",
    uaTokens: ["Будь", "ласка", ",", "один", "квиток", "в", "один", "бік", "."],
    ruTokens: ["Пожалуйста", ",", "билет", "в", "одну", "сторону", "."],
    enTokens: ["One", "one-way", "ticket", ",", "please", "."],
    extraUaTokens: ["каса", "маршрут", "станція"],
    extraRuTokens: ["касса", "маршрут", "станция"],
    extraEnTokens: ["office", "route", "station"],
  },

  [phraseKey("spiatočný", "a2-5")]: {
    sk: "Kúpim si spiatočný lístok.",
    ua: "Я куплю квиток туди-й-назад.",
    ru: "Я куплю билет туда-обратно.",
    en: "I will buy a round-trip ticket.",
    uaTokens: ["Я", "куплю", "квиток", "туди-й-назад", "."],
    ruTokens: ["Я", "куплю", "билет", "туда-обратно", "."],
    enTokens: ["I", "will", "buy", "a", "round-trip", "ticket", "."],
    extraUaTokens: ["поїзд", "касир", "дорога"],
    extraRuTokens: ["поезд", "кассир", "дорога"],
    extraEnTokens: ["train", "cashier", "road"],
  },

  [phraseKey("cestovné poistenie", "a2-5")]: {
    sk: "Máte cestovné poistenie?",
    ua: "У вас є туристична страховка?",
    ru: "У вас есть туристическая страховка?",
    en: "Do you have travel insurance?",
    uaTokens: ["У", "вас", "є", "туристична", "страховка", "?"],
    ruTokens: ["У", "вас", "есть", "туристическая", "страховка", "?"],
    enTokens: ["Do", "you", "have", "travel", "insurance", "?"],
    extraUaTokens: ["лікар", "випадок", "документ"],
    extraRuTokens: ["врач", "случай", "документ"],
    extraEnTokens: ["doctor", "case", "document"],
  },

  [phraseKey("batožina", "a2-5")]: {
    sk: "Moja batožina je príliš ťažká.",
    ua: "Мій багаж занадто важкий.",
    ru: "Мой багаж слишком тяжёлый.",
    en: "My luggage is too heavy.",
    uaTokens: ["Мій", "багаж", "занадто", "важкий", "."],
    ruTokens: ["Мой", "багаж", "слишком", "тяжёлый", "."],
    enTokens: ["My", "luggage", "is", "too", "heavy", "."],
    extraUaTokens: ["валіза", "вага", "реєстрація"],
    extraRuTokens: ["чемодан", "вес", "регистрация"],
    extraEnTokens: ["suitcase", "weight", "check-in"],
  },
};