// app/learning/build-ua-sentences/a2/a2-5.ts
import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A2_BUILD_UA_SENTENCES_5: BuildUaSentenceDict = {
  // =========================
  // LESSON 21 — Dom (problémy a majster)
  // =========================
  [phraseKey("porucha", "a2-21")]: {
    sk: "Máme poruchu na kúrení.",
    ua: "У нас поломка в опаленні.",
    ru: "У нас неисправность отопления.",
    en: "We have a problem with the heating.",
    uaTokens: ["У", "нас", "поломка", "в", "опаленні", "."],
    ruTokens: ["У", "нас", "неисправность", "отопления", "."],
    enTokens: ["We", "have", "a", "problem", "with", "the", "heating", "."],
    extraUaTokens: ["майстер", "ремонт", "будинок"],
    extraRuTokens: ["мастер", "ремонт", "дом"],
    extraEnTokens: ["repairman", "repair", "house"],
  },

  [phraseKey("inštalatér", "a2-21")]: {
    sk: "Zavolám inštalatéra, lebo tečie voda.",
    ua: "Я викличу сантехніка, бо тече вода.",
    ru: "Я вызову сантехника, потому что течёт вода.",
    en: "I will call a plumber because water is leaking.",
    uaTokens: ["Я", "викличу", "сантехніка", ",", "бо", "тече", "вода", "."],
    ruTokens: ["Я", "вызову", "сантехника", ",", "потому", "что", "течёт", "вода", "."],
    enTokens: ["I", "will", "call", "a", "plumber", "because", "water", "is", "leaking", "."],
    extraUaTokens: ["труба", "ванна", "терміново"],
    extraRuTokens: ["труба", "ванна", "срочно"],
    extraEnTokens: ["pipe", "bathtub", "urgent"],
  },

  [phraseKey("elektrikár", "a2-21")]: {
    sk: "Potrebujeme elektrikára na opravu zásuvky.",
    ua: "Нам потрібен електрик для ремонту розетки.",
    ru: "Нам нужен электрик для ремонта розетки.",
    en: "We need an electrician to repair the socket.",
    uaTokens: ["Нам", "потрібен", "електрик", "для", "ремонту", "розетки", "."],
    ruTokens: ["Нам", "нужен", "электрик", "для", "ремонта", "розетки", "."],
    enTokens: ["We", "need", "an", "electrician", "to", "repair", "the", "socket", "."],
    extraUaTokens: ["дріт", "струм", "кімната"],
    extraRuTokens: ["провод", "ток", "комната"],
    extraEnTokens: ["wire", "electricity", "room"],
  },

  [phraseKey("opraviť", "a2-21")]: {
    sk: "Viete to opraviť ešte dnes?",
    ua: "Ви можете це відремонтувати ще сьогодні?",
    ru: "Вы можете это отремонтировать ещё сегодня?",
    en: "Can you repair it today?",
    uaTokens: ["Ви", "можете", "це", "відремонтувати", "ще", "сьогодні", "?"],
    ruTokens: ["Вы", "можете", "это", "отремонтировать", "ещё", "сегодня", "?"],
    enTokens: ["Can", "you", "repair", "it", "today", "?"],
    extraUaTokens: ["майстер", "швидко", "проблема"],
    extraRuTokens: ["мастер", "быстро", "проблема"],
    extraEnTokens: ["repairman", "quickly", "problem"],
  },

  [phraseKey("vymeniť", "a2-21")]: {
    sk: "Musíme vymeniť staré tesnenie.",
    ua: "Треба замінити стару прокладку.",
    ru: "Нужно заменить старую прокладку.",
    en: "We need to replace the old gasket.",
    uaTokens: ["Треба", "замінити", "стару", "прокладку", "."],
    ruTokens: ["Нужно", "заменить", "старую", "прокладку", "."],
    enTokens: ["We", "need", "to", "replace", "the", "old", "gasket", "."],
    extraUaTokens: ["кран", "вода", "деталь"],
    extraRuTokens: ["кран", "вода", "деталь"],
    extraEnTokens: ["tap", "water", "part"],
  },

  [phraseKey("prietok", "a2-21")]: {
    sk: "Prietok vody je príliš silný.",
    ua: "Потік води занадто сильний.",
    ru: "Поток воды слишком сильный.",
    en: "The water flow is too strong.",
    uaTokens: ["Потік", "води", "занадто", "сильний", "."],
    ruTokens: ["Поток", "воды", "слишком", "сильный", "."],
    enTokens: ["The", "water", "flow", "is", "too", "strong", "."],
    extraUaTokens: ["кран", "тиск", "труба"],
    extraRuTokens: ["кран", "давление", "труба"],
    extraEnTokens: ["tap", "pressure", "pipe"],
  },

  [phraseKey("upchatie", "a2-21")]: {
    sk: "Upchatie v kuchyni musíme vyčistiť.",
    ua: "Засмічення на кухні треба прочистити.",
    ru: "Засор на кухне нужно прочистить.",
    en: "We need to clear the blockage in the kitchen.",
    uaTokens: ["Засмічення", "на", "кухні", "треба", "прочистити", "."],
    ruTokens: ["Засор", "на", "кухне", "нужно", "прочистить", "."],
    enTokens: ["We", "need", "to", "clear", "the", "blockage", "in", "the", "kitchen", "."],
    extraUaTokens: ["мийка", "вода", "труба"],
    extraRuTokens: ["мойка", "вода", "труба"],
    extraEnTokens: ["sink", "water", "pipe"],
  },

  [phraseKey("zatekať", "a2-21")]: {
    sk: "Zo stropu zateká po daždi.",
    ua: "Після дощу протікає зі стелі.",
    ru: "После дождя протекает с потолка.",
    en: "After the rain, water leaks from the ceiling.",
    uaTokens: ["Після", "дощу", "протікає", "зі", "стелі", "."],
    ruTokens: ["После", "дождя", "протекает", "с", "потолка", "."],
    enTokens: ["After", "the", "rain", ",", "water", "leaks", "from", "the", "ceiling", "."],
    extraUaTokens: ["дах", "пляма", "стіна"],
    extraRuTokens: ["крыша", "пятно", "стена"],
    extraEnTokens: ["roof", "stain", "wall"],
  },

  [phraseKey("poškodenie", "a2-21")]: {
    sk: "Poškodenie je väčšie, než sme si mysleli.",
    ua: "Пошкодження більше, ніж ми думали.",
    ru: "Повреждение больше, чем мы думали.",
    en: "The damage is bigger than we thought.",
    uaTokens: ["Пошкодження", "більше", ",", "ніж", "ми", "думали", "."],
    ruTokens: ["Повреждение", "больше", ",", "чем", "мы", "думали", "."],
    enTokens: ["The", "damage", "is", "bigger", "than", "we", "thought", "."],
    extraUaTokens: ["ремонт", "проблема", "серйозно"],
    extraRuTokens: ["ремонт", "проблема", "серьёзно"],
    extraEnTokens: ["repair", "problem", "serious"],
  },

  [phraseKey("náhradný diel", "a2-21")]: {
    sk: "Potrebujem objednať náhradný diel.",
    ua: "Мені треба замовити запасну частину.",
    ru: "Мне нужно заказать запасную часть.",
    en: "I need to order a spare part.",
    uaTokens: ["Мені", "треба", "замовити", "запасну", "частину", "."],
    ruTokens: ["Мне", "нужно", "заказать", "запасную", "часть", "."],
    enTokens: ["I", "need", "to", "order", "a", "spare", "part", "."],
    extraUaTokens: ["деталь", "майстер", "ремонт"],
    extraRuTokens: ["деталь", "мастер", "ремонт"],
    extraEnTokens: ["part", "repairman", "repair"],
  },

  // =========================
  // LESSON 22 — Zdravie (lekáreň a liečba)
  // =========================
  [phraseKey("vedľajšie účinky", "a2-22")]: {
    sk: "Môže to mať vedľajšie účinky?",
    ua: "Це може мати побічні ефекти?",
    ru: "Это может иметь побочные эффекты?",
    en: "Can it have side effects?",
    uaTokens: ["Це", "може", "мати", "побічні", "ефекти", "?"],
    ruTokens: ["Это", "может", "иметь", "побочные", "эффекты", "?"],
    enTokens: ["Can", "it", "have", "side", "effects", "?"],
    extraUaTokens: ["ліки", "інструкція", "обережно"],
    extraRuTokens: ["лекарство", "инструкция", "осторожно"],
    extraEnTokens: ["medicine", "instructions", "careful"],
  },

  [phraseKey("dávkovanie", "a2-22")]: {
    sk: "Aké je správne dávkovanie?",
    ua: "Яке правильне дозування?",
    ru: "Какая правильная дозировка?",
    en: "What is the correct dosage?",
    uaTokens: ["Яке", "правильне", "дозування", "?"],
    ruTokens: ["Какая", "правильная", "дозировка", "?"],
    enTokens: ["What", "is", "the", "correct", "dosage", "?"],
    extraUaTokens: ["лікар", "таблетки", "раз"],
    extraRuTokens: ["врач", "таблетки", "раз"],
    extraEnTokens: ["doctor", "tablets", "time"],
  },

  [phraseKey("návod", "a2-22")]: {
    sk: "Prečítajte si návod pred použitím.",
    ua: "Прочитайте інструкцію перед використанням.",
    ru: "Прочитайте инструкцию перед использованием.",
    en: "Read the instructions before use.",
    uaTokens: ["Прочитайте", "інструкцію", "перед", "використанням", "."],
    ruTokens: ["Прочитайте", "инструкцию", "перед", "использованием", "."],
    enTokens: ["Read", "the", "instructions", "before", "use", "."],
    extraUaTokens: ["упаковка", "уважно", "ліки"],
    extraRuTokens: ["упаковка", "внимательно", "лекарство"],
    extraEnTokens: ["package", "carefully", "medicine"],
  },

  [phraseKey("liek proti bolesti", "a2-22")]: {
    sk: "Prosím si liek proti bolesti hlavy.",
    ua: "Мені потрібне знеболювальне від головного болю.",
    ru: "Мне нужно обезболивающее от головной боли.",
    en: "I need pain relief for a headache.",
    uaTokens: ["Мені", "потрібне", "знеболювальне", "від", "головного", "болю", "."],
    ruTokens: ["Мне", "нужно", "обезболивающее", "от", "головной", "боли", "."],
    enTokens: ["I", "need", "pain", "relief", "for", "a", "headache", "."],
    extraUaTokens: ["аптека", "таблетка", "голова"],
    extraRuTokens: ["аптека", "таблетка", "голова"],
    extraEnTokens: ["pharmacy", "tablet", "head"],
  },

  [phraseKey("antibiotiká", "a2-22")]: {
    sk: "Antibiotiká beriem len podľa lekára.",
    ua: "Антибіотики приймаю лише за призначенням лікаря.",
    ru: "Антибиотики принимаю только по назначению врача.",
    en: "I take antibiotics only as prescribed by the doctor.",
    uaTokens: ["Антибіотики", "приймаю", "лише", "за", "призначенням", "лікаря", "."],
    ruTokens: ["Антибиотики", "принимаю", "только", "по", "назначению", "врача", "."],
    enTokens: ["I", "take", "antibiotics", "only", "as", "prescribed", "by", "the", "doctor", "."],
    extraUaTokens: ["рецепт", "курс", "обережно"],
    extraRuTokens: ["рецепт", "курс", "осторожно"],
    extraEnTokens: ["prescription", "course", "carefully"],
  },

  [phraseKey("očkovanie", "a2-22")]: {
    sk: "Kedy je ďalšie očkovanie?",
    ua: "Коли наступна вакцинація?",
    ru: "Когда следующая вакцинация?",
    en: "When is the next vaccination?",
    uaTokens: ["Коли", "наступна", "вакцинація", "?"],
    ruTokens: ["Когда", "следующая", "вакцинация", "?"],
    enTokens: ["When", "is", "the", "next", "vaccination", "?"],
    extraUaTokens: ["лікар", "дата", "поліклініка"],
    extraRuTokens: ["врач", "дата", "поликлиника"],
    extraEnTokens: ["doctor", "date", "clinic"],
  },

  [phraseKey("recept", "a2-22")]: {
    sk: "Na tento liek potrebujete recept.",
    ua: "На ці ліки потрібен рецепт.",
    ru: "На это лекарство нужен рецепт.",
    en: "You need a prescription for this medicine.",
    uaTokens: ["На", "ці", "ліки", "потрібен", "рецепт", "."],
    ruTokens: ["На", "это", "лекарство", "нужен", "рецепт", "."],
    enTokens: ["You", "need", "a", "prescription", "for", "this", "medicine", "."],
    extraUaTokens: ["аптека", "лікар", "документ"],
    extraRuTokens: ["аптека", "врач", "документ"],
    extraEnTokens: ["pharmacy", "doctor", "document"],
  },

  [phraseKey("bez receptu", "a2-22")]: {
    sk: "Máte niečo bez receptu?",
    ua: "У вас є щось без рецепта?",
    ru: "У вас есть что-то без рецепта?",
    en: "Do you have anything without a prescription?",
    uaTokens: ["У", "вас", "є", "щось", "без", "рецепта", "?"],
    ruTokens: ["У", "вас", "есть", "что-то", "без", "рецепта", "?"],
    enTokens: ["Do", "you", "have", "anything", "without", "a", "prescription", "?"],
    extraUaTokens: ["аптека", "сироп", "таблетки"],
    extraRuTokens: ["аптека", "сироп", "таблетки"],
    extraEnTokens: ["pharmacy", "syrup", "tablets"],
  },

  [phraseKey("kontrola", "a2-22")]: {
    sk: "Na kontrolu prídem o týždeň.",
    ua: "На контроль прийду за тиждень.",
    ru: "На контроль приду через неделю.",
    en: "I will come for a check-up in a week.",
    uaTokens: ["На", "контроль", "прийду", "за", "тиждень", "."],
    ruTokens: ["На", "контроль", "приду", "через", "неделю", "."],
    enTokens: ["I", "will", "come", "for", "a", "check-up", "in", "a", "week", "."],
    uaAltAnswers: [
      ["На", "огляд", "прийду", "за", "тиждень", "."],
    ],
    ruAltAnswers: [
      ["На", "осмотр", "приду", "через", "неделю", "."],
    ],
    extraUaTokens: ["лікар", "запис", "кабінет"],
    extraRuTokens: ["врач", "запись", "кабинет"],
    extraEnTokens: ["doctor", "appointment", "office"],
  },

  [phraseKey("uzdravovať sa", "a2-22")]: {
    sk: "Pomaly sa uzdravujem, ale ešte kašlem.",
    ua: "Я повільно одужую, але ще кашляю.",
    ru: "Я медленно выздоравливаю, но ещё кашляю.",
    en: "I am recovering slowly, but I am still coughing.",
    uaTokens: ["Я", "повільно", "одужую", ",", "але", "ще", "кашляю", "."],
    ruTokens: ["Я", "медленно", "выздоравливаю", ",", "но", "ещё", "кашляю", "."],
    enTokens: ["I", "am", "recovering", "slowly", ",", "but", "I", "am", "still", "coughing", "."],
    extraUaTokens: ["чай", "ліжко", "лікування"],
    extraRuTokens: ["чай", "кровать", "лечение"],
    extraEnTokens: ["tea", "bed", "treatment"],
  },

  // =========================
  // LESSON 23 — Mesto (bezpečnosť a služby)
  // =========================
  [phraseKey("nehoda", "a2-23")]: {
    sk: "Stala sa nehoda na križovatke.",
    ua: "На перехресті сталася аварія.",
    ru: "На перекрёстке произошла авария.",
    en: "There was an accident at the intersection.",
    uaTokens: ["На", "перехресті", "сталася", "аварія", "."],
    ruTokens: ["На", "перекрёстке", "произошла", "авария", "."],
    enTokens: ["There", "was", "an", "accident", "at", "the", "intersection", "."],
    extraUaTokens: ["машина", "дорога", "поліція"],
    extraRuTokens: ["машина", "дорога", "полиция"],
    extraEnTokens: ["car", "road", "police"],
  },

  [phraseKey("záchranka", "a2-23")]: {
    sk: "Zavolajte záchranku, prosím!",
    ua: "Викличте швидку, будь ласка!",
    ru: "Вызовите скорую, пожалуйста!",
    en: "Call an ambulance, please!",
    uaTokens: ["Викличте", "швидку", ",", "будь", "ласка", "!"],
    ruTokens: ["Вызовите", "скорую", ",", "пожалуйста", "!"],
    enTokens: ["Call", "an", "ambulance", ",", "please", "!"],
    extraUaTokens: ["лікар", "терміново", "допомога"],
    extraRuTokens: ["врач", "срочно", "помощь"],
    extraEnTokens: ["doctor", "urgent", "help"],
  },

  [phraseKey("hasiči", "a2-23")]: {
    sk: "Hasiči prišli o pár minút.",
    ua: "Пожежники приїхали за кілька хвилин.",
    ru: "Пожарные приехали через несколько минут.",
    en: "The firefighters arrived in a few minutes.",
    uaTokens: ["Пожежники", "приїхали", "за", "кілька", "хвилин", "."],
    ruTokens: ["Пожарные", "приехали", "через", "несколько", "минут", "."],
    enTokens: ["The", "firefighters", "arrived", "in", "a", "few", "minutes", "."],
    extraUaTokens: ["вогонь", "дим", "сирена"],
    extraRuTokens: ["огонь", "дым", "сирена"],
    extraEnTokens: ["fire", "smoke", "siren"],
  },

  [phraseKey("policajná stanica", "a2-23")]: {
    sk: "Kde je najbližšia policajná stanica?",
    ua: "Де найближчий відділок поліції?",
    ru: "Где ближайший отдел полиции?",
    en: "Where is the nearest police station?",
    uaTokens: ["Де", "найближчий", "відділок", "поліції", "?"],
    ruTokens: ["Где", "ближайший", "отдел", "полиции", "?"],
    enTokens: ["Where", "is", "the", "nearest", "police", "station", "?"],
    extraUaTokens: ["місто", "карта", "вулиця"],
    extraRuTokens: ["город", "карта", "улица"],
    extraEnTokens: ["city", "map", "street"],
  },

  [phraseKey("svedok", "a2-23")]: {
    sk: "Bol tam nejaký svedok?",
    ua: "Там був якийсь свідок?",
    ru: "Там был какой-то свидетель?",
    en: "Was there any witness there?",
    uaTokens: ["Там", "був", "якийсь", "свідок", "?"],
    ruTokens: ["Там", "был", "какой-то", "свидетель", "?"],
    enTokens: ["Was", "there", "any", "witness", "there", "?"],
    extraUaTokens: ["бачити", "людина", "аварія"],
    extraRuTokens: ["видеть", "человек", "авария"],
    extraEnTokens: ["see", "person", "accident"],
  },

  [phraseKey("krádež", "a2-23")]: {
    sk: "Chcem nahlásiť krádež.",
    ua: "Я хочу заявити про крадіжку.",
    ru: "Я хочу заявить о краже.",
    en: "I want to report a theft.",
    uaTokens: ["Я", "хочу", "заявити", "про", "крадіжку", "."],
    ruTokens: ["Я", "хочу", "заявить", "о", "краже", "."],
    enTokens: ["I", "want", "to", "report", "a", "theft", "."],
    extraUaTokens: ["поліція", "магазин", "документи"],
    extraRuTokens: ["полиция", "магазин", "документы"],
    extraEnTokens: ["police", "store", "documents"],
  },

  [phraseKey("nahlásiť", "a2-23")]: {
    sk: "Musíte to nahlásiť na polícii.",
    ua: "Ви повинні повідомити про це в поліції.",
    ru: "Вы должны сообщить об этом в полиции.",
    en: "You must report it to the police.",
    uaTokens: ["Ви", "повинні", "повідомити", "про", "це", "в", "поліції", "."],
    ruTokens: ["Вы", "должны", "сообщить", "об", "этом", "в", "полиции", "."],
    enTokens: ["You", "must", "report", "it", "to", "the", "police", "."],
    extraUaTokens: ["заява", "офіційно", "протокол"],
    extraRuTokens: ["заявление", "официально", "протокол"],
    extraEnTokens: ["statement", "officially", "report"],
  },

  [phraseKey("doklady", "a2-23")]: {
    sk: "Stratil som doklady aj kartu.",
    ua: "Я загубив документи і картку.",
    ru: "Я потерял документы и карту.",
    en: "I lost my documents and card.",
    uaTokens: ["Я", "загубив", "документи", "і", "картку", "."],
    ruTokens: ["Я", "потерял", "документы", "и", "карту", "."],
    enTokens: ["I", "lost", "my", "documents", "and", "card", "."],
    extraUaTokens: ["гаманець", "сумка", "терміново"],
    extraRuTokens: ["кошелёк", "сумка", "срочно"],
    extraEnTokens: ["wallet", "bag", "urgent"],
  },

  [phraseKey("stratiť", "a2-23")]: {
    sk: "Nechcem stratiť kľúče.",
    ua: "Я не хочу загубити ключі.",
    ru: "Я не хочу потерять ключи.",
    en: "I do not want to lose the keys.",
    uaTokens: ["Я", "не", "хочу", "загубити", "ключі", "."],
    ruTokens: ["Я", "не", "хочу", "потерять", "ключи", "."],
    enTokens: ["I", "do", "not", "want", "to", "lose", "the", "keys", "."],
    extraUaTokens: ["будинок", "двері", "кишеня"],
    extraRuTokens: ["дом", "дверь", "карман"],
    extraEnTokens: ["house", "door", "pocket"],
  },

  [phraseKey("nájsť", "a2-23")]: {
    sk: "Dúfam, že to ešte nájdem.",
    ua: "Сподіваюся, що я це ще знайду.",
    ru: "Надеюсь, что я это ещё найду.",
    en: "I hope I will still find it.",
    uaTokens: ["Сподіваюся", ",", "що", "я", "це", "ще", "знайду", "."],
    ruTokens: ["Надеюсь", ",", "что", "я", "это", "ещё", "найду", "."],
    enTokens: ["I", "hope", "I", "will", "still", "find", "it", "."],
    extraUaTokens: ["пошук", "вдома", "річ"],
    extraRuTokens: ["поиск", "дома", "вещь"],
    extraEnTokens: ["search", "home", "thing"],
  },

  // =========================
  // LESSON 24 — Jedlo (nákupy a varenie)
  // =========================
  [phraseKey("ingrediencie", "a2-24")]: {
    sk: "Mám všetky ingrediencie doma.",
    ua: "У мене вдома є всі інгредієнти.",
    ru: "У меня дома есть все ингредиенты.",
    en: "I have all the ingredients at home.",
    uaTokens: ["У", "мене", "вдома", "є", "всі", "інгредієнти", "."],
    ruTokens: ["У", "меня", "дома", "есть", "все", "ингредиенты", "."],
    enTokens: ["I", "have", "all", "the", "ingredients", "at", "home", "."],
    extraUaTokens: ["рецепт", "кухня", "продукти"],
    extraRuTokens: ["рецепт", "кухня", "продукты"],
    extraEnTokens: ["recipe", "kitchen", "products"],
  },

  [phraseKey("recept (kuchársky)", "a2-24")]: {
    sk: "Tento recept je jednoduchý a rýchly.",
    ua: "Цей кулінарний рецепт простий і швидкий.",
    ru: "Этот рецепт простой и быстрый.",
    en: "This recipe is simple and quick.",
    uaTokens: ["Цей", "кулінарний", "рецепт", "простий", "і", "швидкий", "."],
    ruTokens: ["Этот", "рецепт", "простой", "и", "быстрый", "."],
    enTokens: ["This", "recipe", "is", "simple", "and", "quick", "."],
    extraUaTokens: ["готувати", "вечеря", "страва"],
    extraRuTokens: ["готовить", "ужин", "блюдо"],
    extraEnTokens: ["cook", "dinner", "dish"],
  },

  [phraseKey("nakrájať", "a2-24")]: {
    sk: "Môžete nakrájať cibuľu na malé kúsky?",
    ua: "Можеш нарізати цибулю на маленькі шматочки?",
    ru: "Можешь нарезать лук на маленькие кусочки?",
    en: "Can you cut the onion into small pieces?",
    uaTokens: ["Можеш", "нарізати", "цибулю", "на", "маленькі", "шматочки", "?"],
    ruTokens: ["Можешь", "нарезать", "лук", "на", "маленькие", "кусочки", "?"],
    enTokens: ["Can", "you", "cut", "the", "onion", "into", "small", "pieces", "?"],
    extraUaTokens: ["ніж", "дошка", "кухня"],
    extraRuTokens: ["нож", "доска", "кухня"],
    extraEnTokens: ["knife", "board", "kitchen"],
  },

  [phraseKey("zmiešať", "a2-24")]: {
    sk: "Najprv treba zmiešať múku s vodou.",
    ua: "Спочатку треба змішати борошно з водою.",
    ru: "Сначала нужно смешать муку с водой.",
    en: "First, you need to mix flour with water.",
    uaTokens: ["Спочатку", "треба", "змішати", "борошно", "з", "водою", "."],
    ruTokens: ["Сначала", "нужно", "смешать", "муку", "с", "водой", "."],
    enTokens: ["First", ",", "you", "need", "to", "mix", "flour", "with", "water", "."],
    extraUaTokens: ["миска", "тісто", "ложка"],
    extraRuTokens: ["миска", "тесто", "ложка"],
    extraEnTokens: ["bowl", "dough", "spoon"],
  },

  [phraseKey("osmažiť", "a2-24")]: {
    sk: "Osmažím mäso na panvici.",
    ua: "Я підсмажу м’ясо на пательні.",
    ru: "Я поджарю мясо на сковороде.",
    en: "I will fry the meat in the pan.",
    uaTokens: ["Я", "підсмажу", "м’ясо", "на", "пательні", "."],
    ruTokens: ["Я", "поджарю", "мясо", "на", "сковороде", "."],
    enTokens: ["I", "will", "fry", "the", "meat", "in", "the", "pan", "."],
    extraUaTokens: ["олія", "вогонь", "кухня"],
    extraRuTokens: ["масло", "огонь", "кухня"],
    extraEnTokens: ["oil", "fire", "kitchen"],
  },

  [phraseKey("uvariť", "a2-24")]: {
    sk: "Musím uvariť polievku.",
    ua: "Мені треба зварити суп.",
    ru: "Мне нужно сварить суп.",
    en: "I need to cook soup.",
    uaTokens: ["Мені", "треба", "зварити", "суп", "."],
    ruTokens: ["Мне", "нужно", "сварить", "суп", "."],
    enTokens: ["I", "need", "to", "cook", "soup", "."],
    extraUaTokens: ["каструля", "овочі", "обід"],
    extraRuTokens: ["кастрюля", "овощи", "обед"],
    extraEnTokens: ["pot", "vegetables", "lunch"],
  },

  [phraseKey("upiecť", "a2-24")]: {
    sk: "Na víkend chcem upiecť koláč.",
    ua: "На вихідні хочу спекти пиріг.",
    ru: "На выходные хочу испечь пирог.",
    en: "I want to bake a pie for the weekend.",
    uaTokens: ["На", "вихідні", "хочу", "спекти", "пиріг", "."],
    ruTokens: ["На", "выходные", "хочу", "испечь", "пирог", "."],
    enTokens: ["I", "want", "to", "bake", "a", "pie", "for", "the", "weekend", "."],
    extraUaTokens: ["духовка", "тісто", "солодке"],
    extraRuTokens: ["духовка", "тесто", "сладкое"],
    extraEnTokens: ["oven", "dough", "sweet"],
  },

  [phraseKey("ochutiť", "a2-24")]: {
    sk: "Nezabudnite to ochutiť soľou a korením.",
    ua: "Не забудьте приправити це сіллю та перцем.",
    ru: "Не забудьте приправить это солью и перцем.",
    en: "Do not forget to season it with salt and pepper.",
    uaTokens: ["Не", "забудьте", "приправити", "це", "сіллю", "та", "перцем", "."],
    ruTokens: ["Не", "забудьте", "приправить", "это", "солью", "и", "перцем", "."],
    enTokens: ["Do", "not", "forget", "to", "season", "it", "with", "salt", "and", "pepper", "."],
    extraUaTokens: ["смак", "страва", "кухня"],
    extraRuTokens: ["вкус", "блюдо", "кухня"],
    extraEnTokens: ["taste", "dish", "kitchen"],
  },

  [phraseKey("porcia", "a2-24")]: {
    sk: "Dám si menšiu porciu.",
    ua: "Я візьму меншу порцію.",
    ru: "Я возьму меньшую порцию.",
    en: "I will take a smaller portion.",
    uaTokens: ["Я", "візьму", "меншу", "порцію", "."],
    ruTokens: ["Я", "возьму", "меньшую", "порцию", "."],
    enTokens: ["I", "will", "take", "a", "smaller", "portion", "."],
    extraUaTokens: ["тарілка", "обід", "їжа"],
    extraRuTokens: ["тарелка", "обед", "еда"],
    extraEnTokens: ["plate", "lunch", "food"],
  },

  [phraseKey("zvyšky", "a2-24")]: {
    sk: "Zvyšky odložím do chladničky.",
    ua: "Залишки їжі покладу в холодильник.",
    ru: "Остатки еды положу в холодильник.",
    en: "I will put the leftovers in the fridge.",
    uaTokens: ["Залишки", "їжі", "покладу", "в", "холодильник", "."],
    ruTokens: ["Остатки", "еды", "положу", "в", "холодильник", "."],
    enTokens: ["I", "will", "put", "the", "leftovers", "in", "the", "fridge", "."],
    extraUaTokens: ["контейнер", "вечеря", "полиця"],
    extraRuTokens: ["контейнер", "ужин", "полка"],
    extraEnTokens: ["container", "dinner", "shelf"],
  },

  // =========================
  // LESSON 25 — Cestovanie (plánovanie trasy)
  // =========================
  [phraseKey("itinerár", "a2-25")]: {
    sk: "Pripravil som si itinerár na celý týždeň.",
    ua: "Я підготував маршрут подорожі на весь тиждень.",
    ru: "Я подготовил маршрут поездки на всю неделю.",
    en: "I prepared a travel itinerary for the whole week.",
    uaTokens: ["Я", "підготував", "маршрут", "подорожі", "на", "весь", "тиждень", "."],
    ruTokens: ["Я", "подготовил", "маршрут", "поездки", "на", "всю", "неделю", "."],
    enTokens: ["I", "prepared", "a", "travel", "itinerary", "for", "the", "whole", "week", "."],
    uaAltAnswers: [
      ["Я", "підготував", "план", "подорожі", "на", "весь", "тиждень", "."],
    ],
    ruAltAnswers: [
      ["Я", "подготовил", "план", "поездки", "на", "всю", "неделю", "."],
    ],
    extraUaTokens: ["місто", "готель", "карта"],
    extraRuTokens: ["город", "отель", "карта"],
    extraEnTokens: ["city", "hotel", "map"],
  },

  [phraseKey("prestup", "a2-25")]: {
    sk: "Máme prestup vo Viedni.",
    ua: "У нас пересадка у Відні.",
    ru: "У нас пересадка в Вене.",
    en: "We have a transfer in Vienna.",
    uaTokens: ["У", "нас", "пересадка", "у", "Відні", "."],
    ruTokens: ["У", "нас", "пересадка", "в", "Вене", "."],
    enTokens: ["We", "have", "a", "transfer", "in", "Vienna", "."],
    extraUaTokens: ["вокзал", "поїзд", "час"],
    extraRuTokens: ["вокзал", "поезд", "время"],
    extraEnTokens: ["station", "train", "time"],
  },

  [phraseKey("spoj", "a2-25")]: {
    sk: "Toto spojenie mi vyhovuje najviac.",
    ua: "Це сполучення мені підходить найбільше.",
    ru: "Этот рейс мне подходит больше всего.",
    en: "This connection suits me the most.",
    uaTokens: ["Це", "сполучення", "мені", "підходить", "найбільше", "."],
    ruTokens: ["Этот", "рейс", "мне", "подходит", "больше", "всего", "."],
    enTokens: ["This", "connection", "suits", "me", "the", "most", "."],
    ruAltAnswers: [
      ["Это", "сообщение", "мне", "подходит", "больше", "всего", "."],
    ],
    extraUaTokens: ["маршрут", "розклад", "зручно"],
    extraRuTokens: ["маршрут", "расписание", "удобно"],
    extraEnTokens: ["route", "schedule", "convenient"],
  },

  [phraseKey("oneskorenie", "a2-25")]: {
    sk: "Vlak má oneskorenie dvadsať minút.",
    ua: "Потяг має затримку двадцять хвилин.",
    ru: "Поезд задерживается на двадцать минут.",
    en: "The train is delayed by twenty minutes.",
    uaTokens: ["Потяг", "має", "затримку", "двадцять", "хвилин", "."],
    ruTokens: ["Поезд", "задерживается", "на", "двадцать", "минут", "."],
    enTokens: ["The", "train", "is", "delayed", "by", "twenty", "minutes", "."],
    extraUaTokens: ["станція", "табло", "очікувати"],
    extraRuTokens: ["станция", "табло", "ждать"],
    extraEnTokens: ["station", "board", "wait"],
  },

  [phraseKey("zrušený", "a2-25")]: {
    sk: "Tento let je zrušený.",
    ua: "Цей рейс скасований.",
    ru: "Этот рейс отменён.",
    en: "This flight is cancelled.",
    uaTokens: ["Цей", "рейс", "скасований", "."],
    ruTokens: ["Этот", "рейс", "отменён", "."],
    enTokens: ["This", "flight", "is", "cancelled", "."],
    extraUaTokens: ["аеропорт", "квиток", "інформація"],
    extraRuTokens: ["аэропорт", "билет", "информация"],
    extraEnTokens: ["airport", "ticket", "information"],
  },

  [phraseKey("odbavenie", "a2-25")]: {
    sk: "Odbavenie začína dve hodiny pred odletom.",
    ua: "Реєстрація починається за дві години до вильоту.",
    ru: "Регистрация начинается за два часа до вылета.",
    en: "Check-in starts two hours before departure.",
    uaTokens: ["Реєстрація", "починається", "за", "дві", "години", "до", "вильоту", "."],
    ruTokens: ["Регистрация", "начинается", "за", "два", "часа", "до", "вылета", "."],
    enTokens: ["Check-in", "starts", "two", "hours", "before", "departure", "."],
    extraUaTokens: ["паспорт", "багаж", "черга"],
    extraRuTokens: ["паспорт", "багаж", "очередь"],
    extraEnTokens: ["passport", "luggage", "queue"],
  },

  [phraseKey("cestovný poriadok", "a2-25")]: {
    sk: "Pozriem si cestovný poriadok online.",
    ua: "Я подивлюся розклад руху онлайн.",
    ru: "Я посмотрю расписание движения онлайн.",
    en: "I will check the timetable online.",
    uaTokens: ["Я", "подивлюся", "розклад", "руху", "онлайн", "."],
    ruTokens: ["Я", "посмотрю", "расписание", "движения", "онлайн", "."],
    enTokens: ["I", "will", "check", "the", "timetable", "online", "."],
    extraUaTokens: ["автобус", "поїзд", "сайт"],
    extraRuTokens: ["автобус", "поезд", "сайт"],
    extraEnTokens: ["bus", "train", "website"],
  },

  [phraseKey("spiatočný lístok", "a2-25")]: {
    sk: "Chcem spiatočný lístok, prosím.",
    ua: "Мені потрібен квиток туди-назад, будь ласка.",
    ru: "Мне нужен билет туда-обратно, пожалуйста.",
    en: "I need a return ticket, please.",
    uaTokens: ["Мені", "потрібен", "квиток", "туди-назад", ",", "будь", "ласка", "."],
    ruTokens: ["Мне", "нужен", "билет", "туда-обратно", ",", "пожалуйста", "."],
    enTokens: ["I", "need", "a", "return", "ticket", ",", "please", "."],
    extraUaTokens: ["каса", "подорож", "дата"],
    extraRuTokens: ["касса", "поездка", "дата"],
    extraEnTokens: ["ticket office", "trip", "date"],
  },

  [phraseKey("jednosmerný lístok", "a2-25")]: {
    sk: "Stačí mi jednosmerný lístok.",
    ua: "Мені достатньо квитка в один бік.",
    ru: "Мне достаточно билета в одну сторону.",
    en: "A one-way ticket is enough for me.",
    uaTokens: ["Мені", "достатньо", "квитка", "в", "один", "бік", "."],
    ruTokens: ["Мне", "достаточно", "билета", "в", "одну", "сторону", "."],
    enTokens: ["A", "one-way", "ticket", "is", "enough", "for", "me", "."],
    extraUaTokens: ["станція", "маршрут", "каса"],
    extraRuTokens: ["станция", "маршрут", "касса"],
    extraEnTokens: ["station", "route", "ticket office"],
  },

  [phraseKey("cestovný lístok", "a2-25")]: {
    sk: "Kde si môžem kúpiť cestovný lístok?",
    ua: "Де я можу купити квиток?",
    ru: "Где я могу купить билет?",
    en: "Where can I buy a ticket?",
    uaTokens: ["Де", "я", "можу", "купити", "квиток", "?"],
    ruTokens: ["Где", "я", "могу", "купить", "билет", "?"],
    enTokens: ["Where", "can", "I", "buy", "a", "ticket", "?"],
    extraUaTokens: ["автомат", "каса", "зупинка"],
    extraRuTokens: ["автомат", "касса", "остановка"],
    extraEnTokens: ["machine", "ticket office", "stop"],
  },
};