// app/learning/build-ua-sentences/a2/a2-7.ts
import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A2_BUILD_UA_SENTENCES_7: BuildUaSentenceDict = {
  // =========================
  // LESSON 31 — Bývanie (hľadanie a prenájom)
  // =========================
  [phraseKey("ponuka", "a2-31")]: {
    sk: "Táto ponuka je pre mňa zaujímavá.",
    ua: "Ця пропозиція для мене цікава.",
    ru: "Это предложение для меня интересное.",
    en: "This offer is interesting to me.",
    uaTokens: ["Ця", "пропозиція", "для", "мене", "цікава", "."],
    ruTokens: ["Это", "предложение", "для", "меня", "интересное", "."],
    enTokens: ["This", "offer", "is", "interesting", "to", "me", "."],
    extraUaTokens: ["квартира", "оренда", "сайт"],
    extraRuTokens: ["квартира", "аренда", "сайт"],
    extraEnTokens: ["apartment", "rent", "website"],
  },

  [phraseKey("dopyt", "a2-31")]: {
    sk: "Dopyt po bytoch je tu vysoký.",
    ua: "Попит на квартири тут високий.",
    ru: "Спрос на квартиры здесь высокий.",
    en: "Demand for apartments is high here.",
    uaTokens: ["Попит", "на", "квартири", "тут", "високий", "."],
    ruTokens: ["Спрос", "на", "квартиры", "здесь", "высокий", "."],
    enTokens: ["Demand", "for", "apartments", "is", "high", "here", "."],
    extraUaTokens: ["ринок", "місто", "житло"],
    extraRuTokens: ["рынок", "город", "жильё"],
    extraEnTokens: ["market", "city", "housing"],
  },

  [phraseKey("obhliadka", "a2-31")]: {
    sk: "Môžem si dohodnúť obhliadku bytu?",
    ua: "Можу домовитися про огляд квартири?",
    ru: "Могу договориться об осмотре квартиры?",
    en: "Can I arrange a viewing of the apartment?",
    uaTokens: ["Можу", "домовитися", "про", "огляд", "квартири", "?"],
    ruTokens: ["Могу", "договориться", "об", "осмотре", "квартиры", "?"],
    enTokens: ["Can", "I", "arrange", "a", "viewing", "of", "the", "apartment", "?"],
    extraUaTokens: ["агент", "час", "адреса"],
    extraRuTokens: ["агент", "время", "адрес"],
    extraEnTokens: ["agent", "time", "address"],
  },

  [phraseKey("záloha", "a2-31")]: {
    sk: "Je potrebná záloha pri podpise zmluvy?",
    ua: "Потрібен депозит при підписанні договору?",
    ru: "Нужен депозит при подписании договора?",
    en: "Is a deposit required when signing the contract?",
    uaTokens: ["Потрібен", "депозит", "при", "підписанні", "договору", "?"],
    ruTokens: ["Нужен", "депозит", "при", "подписании", "договора", "?"],
    enTokens: ["Is", "a", "deposit", "required", "when", "signing", "the", "contract", "?"],
    uaAltAnswers: [
      ["Потрібна", "застава", "при", "підписанні", "договору", "?"],
    ],
    ruAltAnswers: [
      ["Нужен", "залог", "при", "подписании", "договора", "?"],
    ],
    extraUaTokens: ["гроші", "оренда", "власник"],
    extraRuTokens: ["деньги", "аренда", "владелец"],
    extraEnTokens: ["money", "rent", "landlord"],
  },

  [phraseKey("kaucia", "a2-31")]: {
    sk: "Kaucia je vo výške dvoch mesačných nájmov.",
    ua: "Кауція у розмірі двох місячних оплат.",
    ru: "Депозит в размере двух месячных оплат.",
    en: "The deposit is equal to two monthly payments.",
    uaTokens: ["Кауція", "у", "розмірі", "двох", "місячних", "оплат", "."],
    ruTokens: ["Депозит", "в", "размере", "двух", "месячных", "оплат", "."],
    enTokens: ["The", "deposit", "is", "equal", "to", "two", "monthly", "payments", "."],
    uaAltAnswers: [
      ["Депозит", "у", "розмірі", "двох", "місячних", "оплат", "."],
    ],
    ruAltAnswers: [
      ["Кауция", "в", "размере", "двух", "месячных", "оплат", "."],
    ],
    extraUaTokens: ["договір", "сума", "квартира"],
    extraRuTokens: ["договор", "сумма", "квартира"],
    extraEnTokens: ["contract", "amount", "apartment"],
  },

  [phraseKey("mesačné", "a2-31")]: {
    sk: "Aké je mesačné, prosím?",
    ua: "Яка щомісячна оплата, будь ласка?",
    ru: "Какая ежемесячная оплата, пожалуйста?",
    en: "What is the monthly payment, please?",
    uaTokens: ["Яка", "щомісячна", "оплата", ",", "будь", "ласка", "?"],
    ruTokens: ["Какая", "ежемесячная", "оплата", ",", "пожалуйста", "?"],
    enTokens: ["What", "is", "the", "monthly", "payment", ",", "please", "?"],
    extraUaTokens: ["оренда", "сума", "платіж"],
    extraRuTokens: ["аренда", "сумма", "платёж"],
    extraEnTokens: ["rent", "amount", "fee"],
  },

  [phraseKey("energie v cene", "a2-31")]: {
    sk: "Sú energie v cene nájmu?",
    ua: "Комунальні включені в ціну оренди?",
    ru: "Коммунальные включены в цену аренды?",
    en: "Are utilities included in the rent?",
    uaTokens: ["Комунальні", "включені", "в", "ціну", "оренди", "?"],
    ruTokens: ["Коммунальные", "включены", "в", "цену", "аренды", "?"],
    enTokens: ["Are", "utilities", "included", "in", "the", "rent", "?"],
    extraUaTokens: ["вода", "світло", "газ"],
    extraRuTokens: ["вода", "свет", "газ"],
    extraEnTokens: ["water", "electricity", "gas"],
  },

  [phraseKey("zariadený", "a2-31")]: {
    sk: "Hľadám zariadený byt.",
    ua: "Я шукаю мебльовану квартиру.",
    ru: "Я ищу меблированную квартиру.",
    en: "I am looking for a furnished apartment.",
    uaTokens: ["Я", "шукаю", "мебльовану", "квартиру", "."],
    ruTokens: ["Я", "ищу", "меблированную", "квартиру", "."],
    enTokens: ["I", "am", "looking", "for", "a", "furnished", "apartment", "."],
    extraUaTokens: ["ліжко", "шафа", "кухня"],
    extraRuTokens: ["кровать", "шкаф", "кухня"],
    extraEnTokens: ["bed", "wardrobe", "kitchen"],
  },

  [phraseKey("nezariadený", "a2-31")]: {
    sk: "Je to nezariadený byt, však?",
    ua: "Це немебльована квартира, так?",
    ru: "Это немеблированная квартира, да?",
    en: "This is an unfurnished apartment, right?",
    uaTokens: ["Це", "немебльована", "квартира", ",", "так", "?"],
    ruTokens: ["Это", "немеблированная", "квартира", ",", "да", "?"],
    enTokens: ["This", "is", "an", "unfurnished", "apartment", ",", "right", "?"],
    extraUaTokens: ["порожньо", "меблі", "кімната"],
    extraRuTokens: ["пусто", "мебель", "комната"],
    extraEnTokens: ["empty", "furniture", "room"],
  },

  [phraseKey("spolubývanie", "a2-31")]: {
    sk: "Spolubývanie mi vyhovuje, ak sú pravidlá jasné.",
    ua: "Спільне проживання мені підходить, якщо правила ясні.",
    ru: "Совместное проживание мне подходит, если правила понятны.",
    en: "Shared accommodation works for me if the rules are clear.",
    uaTokens: ["Спільне", "проживання", "мені", "підходить", ",", "якщо", "правила", "ясні", "."],
    ruTokens: ["Совместное", "проживание", "мне", "подходит", ",", "если", "правила", "понятны", "."],
    enTokens: ["Shared", "accommodation", "works", "for", "me", "if", "the", "rules", "are", "clear", "."],
    extraUaTokens: ["сусіди", "кухня", "тиша"],
    extraRuTokens: ["соседи", "кухня", "тишина"],
    extraEnTokens: ["roommates", "kitchen", "quiet"],
  },

  // =========================
  // LESSON 32 — Práca (profesionálne zručnosti)
  // =========================
  [phraseKey("schopnosť", "a2-32")]: {
    sk: "Mám schopnosť riešiť problémy rýchlo.",
    ua: "Я маю здатність швидко вирішувати проблеми.",
    ru: "У меня есть способность быстро решать проблемы.",
    en: "I have the ability to solve problems quickly.",
    uaTokens: ["Я", "маю", "здатність", "швидко", "вирішувати", "проблеми", "."],
    ruTokens: ["У", "меня", "есть", "способность", "быстро", "решать", "проблемы", "."],
    enTokens: ["I", "have", "the", "ability", "to", "solve", "problems", "quickly", "."],
    extraUaTokens: ["робота", "досвід", "завдання"],
    extraRuTokens: ["работа", "опыт", "задача"],
    extraEnTokens: ["work", "experience", "task"],
  },

  [phraseKey("zručnosť", "a2-32")]: {
    sk: "Táto zručnosť je pre túto pozíciu dôležitá.",
    ua: "Ця навичка важлива для цієї посади.",
    ru: "Этот навык важен для этой должности.",
    en: "This skill is important for this position.",
    uaTokens: ["Ця", "навичка", "важлива", "для", "цієї", "посади", "."],
    ruTokens: ["Этот", "навык", "важен", "для", "этой", "должности", "."],
    enTokens: ["This", "skill", "is", "important", "for", "this", "position", "."],
    extraUaTokens: ["кар’єра", "уміння", "роботодавець"],
    extraRuTokens: ["карьера", "умение", "работодатель"],
    extraEnTokens: ["career", "ability", "employer"],
  },

  [phraseKey("skúsenosti", "a2-32")]: {
    sk: "Mám skúsenosti v tomto odbore.",
    ua: "Я маю досвід у цій сфері.",
    ru: "У меня есть опыт в этой сфере.",
    en: "I have experience in this field.",
    uaTokens: ["Я", "маю", "досвід", "у", "цій", "сфері", "."],
    ruTokens: ["У", "меня", "есть", "опыт", "в", "этой", "сфере", "."],
    enTokens: ["I", "have", "experience", "in", "this", "field", "."],
    extraUaTokens: ["робота", "проєкт", "практика"],
    extraRuTokens: ["работа", "проект", "практика"],
    extraEnTokens: ["work", "project", "practice"],
  },

  [phraseKey("zodpovedný", "a2-32")]: {
    sk: "Som zodpovedný a dodržujem termíny.",
    ua: "Я відповідальний і дотримуюся термінів.",
    ru: "Я ответственный и соблюдаю сроки.",
    en: "I am responsible and meet deadlines.",
    uaTokens: ["Я", "відповідальний", "і", "дотримуюся", "термінів", "."],
    ruTokens: ["Я", "ответственный", "и", "соблюдаю", "сроки", "."],
    enTokens: ["I", "am", "responsible", "and", "meet", "deadlines", "."],
    extraUaTokens: ["дедлайн", "робота", "точність"],
    extraRuTokens: ["дедлайн", "работа", "точность"],
    extraEnTokens: ["deadline", "work", "accuracy"],
  },

  [phraseKey("samostatný", "a2-32")]: {
    sk: "Viem pracovať samostatne.",
    ua: "Я вмію працювати самостійно.",
    ru: "Я умею работать самостоятельно.",
    en: "I can work independently.",
    uaTokens: ["Я", "вмію", "працювати", "самостійно", "."],
    ruTokens: ["Я", "умею", "работать", "самостоятельно", "."],
    enTokens: ["I", "can", "work", "independently", "."],
    extraUaTokens: ["проєкт", "завдання", "офіс"],
    extraRuTokens: ["проект", "задача", "офис"],
    extraEnTokens: ["project", "task", "office"],
  },

  [phraseKey("presný", "a2-32")]: {
    sk: "Som presný, najmä pri detailoch.",
    ua: "Я точний, особливо в деталях.",
    ru: "Я точный, особенно в деталях.",
    en: "I am precise, especially with details.",
    uaTokens: ["Я", "точний", ",", "особливо", "в", "деталях", "."],
    ruTokens: ["Я", "точный", ",", "особенно", "в", "деталях", "."],
    enTokens: ["I", "am", "precise", ",", "especially", "with", "details", "."],
    extraUaTokens: ["уважно", "помилка", "якість"],
    extraRuTokens: ["внимательно", "ошибка", "качество"],
    extraEnTokens: ["carefully", "mistake", "quality"],
  },

  [phraseKey("spoľahlivý", "a2-32")]: {
    sk: "Kolegovia ma považujú za spoľahlivého.",
    ua: "Колеги вважають мене надійним.",
    ru: "Коллеги считают меня надёжным.",
    en: "Colleagues consider me reliable.",
    uaTokens: ["Колеги", "вважають", "мене", "надійним", "."],
    ruTokens: ["Коллеги", "считают", "меня", "надёжным", "."],
    enTokens: ["Colleagues", "consider", "me", "reliable", "."],
    extraUaTokens: ["команда", "довіра", "робота"],
    extraRuTokens: ["команда", "доверие", "работа"],
    extraEnTokens: ["team", "trust", "work"],
  },

  [phraseKey("komunikatívny", "a2-32")]: {
    sk: "Som komunikatívny a rád pracujem s ľuďmi.",
    ua: "Я комунікабельний і люблю працювати з людьми.",
    ru: "Я коммуникабельный и люблю работать с людьми.",
    en: "I am sociable and like working with people.",
    uaTokens: ["Я", "комунікабельний", "і", "люблю", "працювати", "з", "людьми", "."],
    ruTokens: ["Я", "коммуникабельный", "и", "люблю", "работать", "с", "людьми", "."],
    enTokens: ["I", "am", "sociable", "and", "like", "working", "with", "people", "."],
    extraUaTokens: ["клієнти", "розмова", "колеги"],
    extraRuTokens: ["клиенты", "разговор", "коллеги"],
    extraEnTokens: ["clients", "conversation", "colleagues"],
  },

  [phraseKey("flexibilný", "a2-32")]: {
    sk: "Som flexibilný, keď sa zmení plán.",
    ua: "Я гнучкий, коли план змінюється.",
    ru: "Я гибкий, когда план меняется.",
    en: "I am flexible when the plan changes.",
    uaTokens: ["Я", "гнучкий", ",", "коли", "план", "змінюється", "."],
    ruTokens: ["Я", "гибкий", ",", "когда", "план", "меняется", "."],
    enTokens: ["I", "am", "flexible", "when", "the", "plan", "changes", "."],
    extraUaTokens: ["графік", "робота", "зміни"],
    extraRuTokens: ["график", "работа", "изменения"],
    extraEnTokens: ["schedule", "work", "changes"],
  },

  [phraseKey("učiť sa rýchlo", "a2-32")]: {
    sk: "Viem sa učiť rýchlo a prispôsobiť sa.",
    ua: "Я вмію швидко вчитися й адаптуватися.",
    ru: "Я умею быстро учиться и адаптироваться.",
    en: "I can learn quickly and adapt.",
    uaTokens: ["Я", "вмію", "швидко", "вчитися", "й", "адаптуватися", "."],
    ruTokens: ["Я", "умею", "быстро", "учиться", "и", "адаптироваться", "."],
    enTokens: ["I", "can", "learn", "quickly", "and", "adapt", "."],
    extraUaTokens: ["нова", "робота", "ситуація"],
    extraRuTokens: ["новая", "работа", "ситуация"],
    extraEnTokens: ["new", "job", "situation"],
  },

  // =========================
  // LESSON 33 — Oddych a voľný čas
  // =========================
  [phraseKey("voľný čas", "a2-33")]: {
    sk: "Vo voľnom čase rád športujem.",
    ua: "У вільний час я люблю займатися спортом.",
    ru: "В свободное время я люблю заниматься спортом.",
    en: "In my free time, I like playing sports.",
    uaTokens: ["У", "вільний", "час", "я", "люблю", "займатися", "спортом", "."],
    ruTokens: ["В", "свободное", "время", "я", "люблю", "заниматься", "спортом", "."],
    enTokens: ["In", "my", "free", "time", ",", "I", "like", "playing", "sports", "."],
    extraUaTokens: ["відпочинок", "хобі", "парк"],
    extraRuTokens: ["отдых", "хобби", "парк"],
    extraEnTokens: ["rest", "hobby", "park"],
  },

  [phraseKey("oddýchnuť si", "a2-33")]: {
    sk: "Potrebujem si trochu oddýchnuť.",
    ua: "Мені треба трохи відпочити.",
    ru: "Мне нужно немного отдохнуть.",
    en: "I need to rest a little.",
    uaTokens: ["Мені", "треба", "трохи", "відпочити", "."],
    ruTokens: ["Мне", "нужно", "немного", "отдохнуть", "."],
    enTokens: ["I", "need", "to", "rest", "a", "little", "."],
    extraUaTokens: ["робота", "сон", "спокій"],
    extraRuTokens: ["работа", "сон", "спокойствие"],
    extraEnTokens: ["work", "sleep", "calm"],
  },

  [phraseKey("zábava", "a2-33")]: {
    sk: "To bola naozaj dobrá zábava.",
    ua: "Це була справді хороша розвага.",
    ru: "Это было действительно хорошее развлечение.",
    en: "That was really good fun.",
    uaTokens: ["Це", "була", "справді", "хороша", "розвага", "."],
    ruTokens: ["Это", "было", "действительно", "хорошее", "развлечение", "."],
    enTokens: ["That", "was", "really", "good", "fun", "."],
    extraUaTokens: ["друзі", "вечір", "сміх"],
    extraRuTokens: ["друзья", "вечер", "смех"],
    extraEnTokens: ["friends", "evening", "laughter"],
  },

  [phraseKey("podujatie", "a2-33")]: {
    sk: "Aké podujatie sa koná cez víkend?",
    ua: "Яка подія відбувається на вихідних?",
    ru: "Какое мероприятие проходит на выходных?",
    en: "What event is taking place this weekend?",
    uaTokens: ["Яка", "подія", "відбувається", "на", "вихідних", "?"],
    ruTokens: ["Какое", "мероприятие", "проходит", "на", "выходных", "?"],
    enTokens: ["What", "event", "is", "taking", "place", "this", "weekend", "?"],
    extraUaTokens: ["афіша", "місто", "дата"],
    extraRuTokens: ["афиша", "город", "дата"],
    extraEnTokens: ["poster", "city", "date"],
  },

  [phraseKey("festival", "a2-33")]: {
    sk: "Na festival pôjdeme spolu.",
    ua: "Ми підемо на фестиваль разом.",
    ru: "Мы пойдём на фестиваль вместе.",
    en: "We will go to the festival together.",
    uaTokens: ["Ми", "підемо", "на", "фестиваль", "разом", "."],
    ruTokens: ["Мы", "пойдём", "на", "фестиваль", "вместе", "."],
    enTokens: ["We", "will", "go", "to", "the", "festival", "together", "."],
    extraUaTokens: ["музика", "літо", "друзі"],
    extraRuTokens: ["музыка", "лето", "друзья"],
    extraEnTokens: ["music", "summer", "friends"],
  },

  [phraseKey("vstupenka", "a2-33")]: {
    sk: "Kde si môžem kúpiť vstupenku?",
    ua: "Де я можу купити квиток?",
    ru: "Где я могу купить билет?",
    en: "Where can I buy a ticket?",
    uaTokens: ["Де", "я", "можу", "купити", "квиток", "?"],
    ruTokens: ["Где", "я", "могу", "купить", "билет", "?"],
    enTokens: ["Where", "can", "I", "buy", "a", "ticket", "?"],
    extraUaTokens: ["каса", "сайт", "ціна"],
    extraRuTokens: ["касса", "сайт", "цена"],
    extraEnTokens: ["box office", "website", "price"],
  },

  [phraseKey("predstavenie", "a2-33")]: {
    sk: "Predstavenie sa začne o ôsmej.",
    ua: "Вистава почнеться о восьмій.",
    ru: "Спектакль начнётся в восемь.",
    en: "The performance starts at eight.",
    uaTokens: ["Вистава", "почнеться", "о", "восьмій", "."],
    ruTokens: ["Спектакль", "начнётся", "в", "восемь", "."],
    enTokens: ["The", "performance", "starts", "at", "eight", "."],
    extraUaTokens: ["театр", "сцена", "вечір"],
    extraRuTokens: ["театр", "сцена", "вечер"],
    extraEnTokens: ["theater", "stage", "evening"],
  },

  [phraseKey("koncert", "a2-33")]: {
    sk: "Koncert bol vypredaný.",
    ua: "Концерт був розпроданий.",
    ru: "Концерт был распродан.",
    en: "The concert was sold out.",
    uaTokens: ["Концерт", "був", "розпроданий", "."],
    ruTokens: ["Концерт", "был", "распродан", "."],
    enTokens: ["The", "concert", "was", "sold", "out", "."],
    extraUaTokens: ["зал", "квитки", "музика"],
    extraRuTokens: ["зал", "билеты", "музыка"],
    extraEnTokens: ["hall", "tickets", "music"],
  },

  [phraseKey("výstava", "a2-33")]: {
    sk: "Tá výstava ma veľmi zaujala.",
    ua: "Ця виставка мене дуже зацікавила.",
    ru: "Эта выставка меня очень заинтересовала.",
    en: "I found that exhibition very interesting.",
    uaTokens: ["Ця", "виставка", "мене", "дуже", "зацікавила", "."],
    ruTokens: ["Эта", "выставка", "меня", "очень", "заинтересовала", "."],
    enTokens: ["I", "found", "that", "exhibition", "very", "interesting", "."],
    extraUaTokens: ["музей", "картини", "мистецтво"],
    extraRuTokens: ["музей", "картины", "искусство"],
    extraEnTokens: ["museum", "paintings", "art"],
  },

  [phraseKey("rezervovať miesto", "a2-33")]: {
    sk: "Chcem si rezervovať miesto v prvom rade.",
    ua: "Я хочу забронювати місце в першому ряду.",
    ru: "Я хочу забронировать место в первом ряду.",
    en: "I want to reserve a seat in the first row.",
    uaTokens: ["Я", "хочу", "забронювати", "місце", "в", "першому", "ряду", "."],
    ruTokens: ["Я", "хочу", "забронировать", "место", "в", "первом", "ряду", "."],
    enTokens: ["I", "want", "to", "reserve", "a", "seat", "in", "the", "first", "row", "."],
    extraUaTokens: ["сцена", "квиток", "театр"],
    extraRuTokens: ["сцена", "билет", "театр"],
    extraEnTokens: ["stage", "ticket", "theater"],
  },

  // =========================
  // LESSON 34 — Servis (dielňa, oprava)
  // =========================
  [phraseKey("servis", "a2-34")]: {
    sk: "Auto dám do servisu zajtra.",
    ua: "Я віддам авто в сервіс завтра.",
    ru: "Я отдам машину в сервис завтра.",
    en: "I will take the car in for service tomorrow.",
    uaTokens: ["Я", "віддам", "авто", "в", "сервіс", "завтра", "."],
    ruTokens: ["Я", "отдам", "машину", "в", "сервис", "завтра", "."],
    enTokens: ["I", "will", "take", "the", "car", "in", "for", "service", "tomorrow", "."],
    extraUaTokens: ["ремонт", "майстер", "машина"],
    extraRuTokens: ["ремонт", "мастер", "машина"],
    extraEnTokens: ["repair", "mechanic", "car"],
  },

  [phraseKey("objednať termín", "a2-34")]: {
    sk: "Potrebujem objednať termín na opravu.",
    ua: "Мені треба записатися на ремонт.",
    ru: "Мне нужно записаться на ремонт.",
    en: "I need to book an appointment for the repair.",
    uaTokens: ["Мені", "треба", "записатися", "на", "ремонт", "."],
    ruTokens: ["Мне", "нужно", "записаться", "на", "ремонт", "."],
    enTokens: ["I", "need", "to", "book", "an", "appointment", "for", "the", "repair", "."],
    extraUaTokens: ["сервіс", "календар", "візит"],
    extraRuTokens: ["сервис", "календарь", "визит"],
    extraEnTokens: ["service", "calendar", "visit"],
  },

  [phraseKey("diagnostika", "a2-34")]: {
    sk: "Najprv urobíme diagnostiku.",
    ua: "Спочатку зробимо діагностику.",
    ru: "Сначала сделаем диагностику.",
    en: "First, we will run diagnostics.",
    uaTokens: ["Спочатку", "зробимо", "діагностику", "."],
    ruTokens: ["Сначала", "сделаем", "диагностику", "."],
    enTokens: ["First", ",", "we", "will", "run", "diagnostics", "."],
    extraUaTokens: ["система", "перевірка", "авто"],
    extraRuTokens: ["система", "проверка", "авто"],
    extraEnTokens: ["system", "check", "car"],
  },

  [phraseKey("porucha", "a2-34")]: {
    sk: "Porucha sa objavila počas jazdy.",
    ua: "Несправність з’явилася під час їзди.",
    ru: "Неисправность появилась во время езды.",
    en: "The malfunction appeared while driving.",
    uaTokens: ["Несправність", "з’явилася", "під", "час", "їзди", "."],
    ruTokens: ["Неисправность", "появилась", "во", "время", "езды", "."],
    enTokens: ["The", "malfunction", "appeared", "while", "driving", "."],
    extraUaTokens: ["двигун", "лампа", "дорога"],
    extraRuTokens: ["двигатель", "лампа", "дорога"],
    extraEnTokens: ["engine", "light", "road"],
  },

  [phraseKey("oprava", "a2-34")]: {
    sk: "Oprava bude trvať asi dve hodiny.",
    ua: "Ремонт триватиме приблизно дві години.",
    ru: "Ремонт займёт примерно два часа.",
    en: "The repair will take about two hours.",
    uaTokens: ["Ремонт", "триватиме", "приблизно", "дві", "години", "."],
    ruTokens: ["Ремонт", "займёт", "примерно", "два", "часа", "."],
    enTokens: ["The", "repair", "will", "take", "about", "two", "hours", "."],
    extraUaTokens: ["майстер", "деталь", "сервіс"],
    extraRuTokens: ["мастер", "деталь", "сервис"],
    extraEnTokens: ["mechanic", "part", "service"],
  },

  [phraseKey("náhradné diely", "a2-34")]: {
    sk: "Náhradné diely nie sú momentálne skladom.",
    ua: "Запасних частин зараз немає в наявності.",
    ru: "Запасных частей сейчас нет в наличии.",
    en: "Spare parts are currently not in stock.",
    uaTokens: ["Запасних", "частин", "зараз", "немає", "в", "наявності", "."],
    ruTokens: ["Запасных", "частей", "сейчас", "нет", "в", "наличии", "."],
    enTokens: ["Spare", "parts", "are", "currently", "not", "in", "stock", "."],
    extraUaTokens: ["замовити", "склад", "поставка"],
    extraRuTokens: ["заказать", "склад", "поставка"],
    extraEnTokens: ["order", "warehouse", "delivery"],
  },

  [phraseKey("cenník", "a2-34")]: {
    sk: "Môžem vidieť cenník služieb?",
    ua: "Можна побачити прайс послуг?",
    ru: "Можно увидеть прайс услуг?",
    en: "Can I see the price list for services?",
    uaTokens: ["Можна", "побачити", "прайс", "послуг", "?"],
    ruTokens: ["Можно", "увидеть", "прайс", "услуг", "?"],
    enTokens: ["Can", "I", "see", "the", "price", "list", "for", "services", "?"],
    extraUaTokens: ["ціна", "ремонт", "сервіс"],
    extraRuTokens: ["цена", "ремонт", "сервис"],
    extraEnTokens: ["price", "repair", "service"],
  },

  [phraseKey("odhad ceny", "a2-34")]: {
    sk: "Dáte mi odhad ceny pred opravou?",
    ua: "Дасте мені оцінку вартості перед ремонтом?",
    ru: "Дадите мне оценку стоимости перед ремонтом?",
    en: "Will you give me a cost estimate before the repair?",
    uaTokens: ["Дасте", "мені", "оцінку", "вартості", "перед", "ремонтом", "?"],
    ruTokens: ["Дадите", "мне", "оценку", "стоимости", "перед", "ремонтом", "?"],
    enTokens: ["Will", "you", "give", "me", "a", "cost", "estimate", "before", "the", "repair", "?"],
    extraUaTokens: ["сума", "майстер", "деталі"],
    extraRuTokens: ["сумма", "мастер", "детали"],
    extraEnTokens: ["amount", "mechanic", "parts"],
  },

  [phraseKey("schváliť", "a2-34")]: {
    sk: "Prosím, najprv mi to pošlite na schválenie.",
    ua: "Будь ласка, спочатку надішліть мені це на затвердження.",
    ru: "Пожалуйста, сначала отправьте мне это на согласование.",
    en: "Please send it to me for approval first.",
    uaTokens: ["Будь", "ласка", ",", "спочатку", "надішліть", "мені", "це", "на", "затвердження", "."],
    ruTokens: ["Пожалуйста", ",", "сначала", "отправьте", "мне", "это", "на", "согласование", "."],
    enTokens: ["Please", "send", "it", "to", "me", "for", "approval", "first", "."],
    extraUaTokens: ["лист", "ремонт", "ціна"],
    extraRuTokens: ["письмо", "ремонт", "цена"],
    extraEnTokens: ["email", "repair", "price"],
  },

  [phraseKey("záruka", "a2-34")]: {
    sk: "Na túto opravu je záruka.",
    ua: "На цей ремонт є гарантія.",
    ru: "На этот ремонт есть гарантия.",
    en: "There is a warranty for this repair.",
    uaTokens: ["На", "цей", "ремонт", "є", "гарантія", "."],
    ruTokens: ["На", "этот", "ремонт", "есть", "гарантия", "."],
    enTokens: ["There", "is", "a", "warranty", "for", "this", "repair", "."],
    extraUaTokens: ["сервіс", "якість", "документ"],
    extraRuTokens: ["сервис", "качество", "документ"],
    extraEnTokens: ["service", "quality", "document"],
  },

  // =========================
  // LESSON 35 — V obchode (zložitejšie situácie)
  // =========================
  [phraseKey("dostupnosť", "a2-35")]: {
    sk: "Chcem si overiť dostupnosť tovaru.",
    ua: "Я хочу перевірити наявність товару.",
    ru: "Я хочу проверить наличие товара.",
    en: "I want to check the availability of the product.",
    uaTokens: ["Я", "хочу", "перевірити", "наявність", "товару", "."],
    ruTokens: ["Я", "хочу", "проверить", "наличие", "товара", "."],
    enTokens: ["I", "want", "to", "check", "the", "availability", "of", "the", "product", "."],
    extraUaTokens: ["магазин", "сайт", "замовлення"],
    extraRuTokens: ["магазин", "сайт", "заказ"],
    extraEnTokens: ["store", "website", "order"],
  },

  [phraseKey("skladom", "a2-35")]: {
    sk: "Je to skladom, alebo to musím objednať?",
    ua: "Це є в наявності, чи треба замовити?",
    ru: "Это есть в наличии или нужно заказать?",
    en: "Is it in stock, or do I have to order it?",
    uaTokens: ["Це", "є", "в", "наявності", ",", "чи", "треба", "замовити", "?"],
    ruTokens: ["Это", "есть", "в", "наличии", "или", "нужно", "заказать", "?"],
    enTokens: ["Is", "it", "in", "stock", ",", "or", "do", "I", "have", "to", "order", "it", "?"],
    extraUaTokens: ["товар", "магазин", "онлайн"],
    extraRuTokens: ["товар", "магазин", "онлайн"],
    extraEnTokens: ["product", "store", "online"],
  },

  [phraseKey("vypredané", "a2-35")]: {
    sk: "Je mi ľúto, je to vypredané.",
    ua: "На жаль, це розпродано.",
    ru: "К сожалению, это распродано.",
    en: "Unfortunately, it is sold out.",
    uaTokens: ["На", "жаль", ",", "це", "розпродано", "."],
    ruTokens: ["К", "сожалению", ",", "это", "распродано", "."],
    enTokens: ["Unfortunately", ",", "it", "is", "sold", "out", "."],
    extraUaTokens: ["немає", "залишилося", "товар"],
    extraRuTokens: ["нет", "осталось", "товар"],
    extraEnTokens: ["none", "left", "product"],
  },

  [phraseKey("objednať", "a2-35")]: {
    sk: "Môžem si to objednať online?",
    ua: "Я можу це замовити онлайн?",
    ru: "Я могу это заказать онлайн?",
    en: "Can I order it online?",
    uaTokens: ["Я", "можу", "це", "замовити", "онлайн", "?"],
    ruTokens: ["Я", "могу", "это", "заказать", "онлайн", "?"],
    enTokens: ["Can", "I", "order", "it", "online", "?"],
    extraUaTokens: ["сайт", "доставка", "кошик"],
    extraRuTokens: ["сайт", "доставка", "корзина"],
    extraEnTokens: ["website", "delivery", "cart"],
  },

  [phraseKey("dodanie", "a2-35")]: {
    sk: "Kedy bude dodanie?",
    ua: "Коли буде доставка?",
    ru: "Когда будет доставка?",
    en: "When will the delivery be?",
    uaTokens: ["Коли", "буде", "доставка", "?"],
    ruTokens: ["Когда", "будет", "доставка", "?"],
    enTokens: ["When", "will", "the", "delivery", "be", "?"],
    uaAltAnswers: [
      ["Коли", "буде", "поставка", "?"],
    ],
    ruAltAnswers: [
      ["Когда", "будет", "поставка", "?"],
    ],
    extraUaTokens: ["кур’єр", "термін", "товар"],
    extraRuTokens: ["курьер", "срок", "товар"],
    extraEnTokens: ["courier", "time", "product"],
  },

  [phraseKey("dodacia lehota", "a2-35")]: {
    sk: "Dodacia lehota je tri až päť dní.",
    ua: "Термін доставки — три-п’ять днів.",
    ru: "Срок доставки — три-пять дней.",
    en: "The delivery time is three to five days.",
    uaTokens: ["Термін", "доставки", "—", "три-п’ять", "днів", "."],
    ruTokens: ["Срок", "доставки", "—", "три-пять", "дней", "."],
    enTokens: ["The", "delivery", "time", "is", "three", "to", "five", "days", "."],
    extraUaTokens: ["очікування", "замовлення", "дата"],
    extraRuTokens: ["ожидание", "заказ", "дата"],
    extraEnTokens: ["waiting", "order", "date"],
  },

  [phraseKey("poškozené zboží", "a2-35")]: {
    sk: "Dostal jsem poškozené zboží.",
    ua: "Я отримав пошкоджений товар.",
    ru: "Я получил повреждённый товар.",
    en: "I received a damaged product.",
    uaTokens: ["Я", "отримав", "пошкоджений", "товар", "."],
    ruTokens: ["Я", "получил", "повреждённый", "товар", "."],
    enTokens: ["I", "received", "a", "damaged", "product", "."],
    extraUaTokens: ["новий", "вчора", "чек"],
    extraRuTokens: ["новый", "вчера", "чек"],
    extraEnTokens: ["new", "yesterday", "receipt"],
  },

  [phraseKey("vymeniť tovar", "a2-35")]: {
    sk: "Chcem vymeniť tovar za nový kus.",
    ua: "Я хочу обміняти товар на новий.",
    ru: "Я хочу обменять товар на новый.",
    en: "I want to exchange the product for a new one.",
    uaTokens: ["Я", "хочу", "обміняти", "товар", "на", "новий", "."],
    ruTokens: ["Я", "хочу", "обменять", "товар", "на", "новый", "."],
    enTokens: ["I", "want", "to", "exchange", "the", "product", "for", "a", "new", "one", "."],
    extraUaTokens: ["чек", "магазин", "гарантія"],
    extraRuTokens: ["чек", "магазин", "гарантия"],
    extraEnTokens: ["receipt", "store", "warranty"],
  },

  [phraseKey("vrátiť peniaze", "a2-35")]: {
    sk: "Môžete mi vrátiť peniaze na kartu?",
    ua: "Ви можете повернути гроші на картку?",
    ru: "Вы можете вернуть деньги на карту?",
    en: "Can you refund the money to my card?",
    uaTokens: ["Ви", "можете", "повернути", "гроші", "на", "картку", "?"],
    ruTokens: ["Вы", "можете", "вернуть", "деньги", "на", "карту", "?"],
    enTokens: ["Can", "you", "refund", "the", "money", "to", "my", "card", "?"],
    extraUaTokens: ["оплата", "банк", "чек"],
    extraRuTokens: ["оплата", "банк", "чек"],
    extraEnTokens: ["payment", "bank", "receipt"],
  },

  [phraseKey("reklamačné oddelenie", "a2-35")]: {
    sk: "Kde je reklamačné oddelenie?",
    ua: "Де відділ рекламацій?",
    ru: "Где отдел рекламаций?",
    en: "Where is the complaints department?",
    uaTokens: ["Де", "відділ", "рекламацій", "?"],
    ruTokens: ["Где", "отдел", "рекламаций", "?"],
    enTokens: ["Where", "is", "the", "complaints", "department", "?"],
    extraUaTokens: ["магазин", "скарга", "повернення"],
    extraRuTokens: ["магазин", "жалоба", "возврат"],
    extraEnTokens: ["store", "complaint", "return"],
  },
};