// app/learning/build-ua-sentences/a2/a2-7.ts
import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const A2_BUILD_UA_SENTENCES_9: BuildUaSentenceDict = {
    // =========================
    // LESSON 41 — Plány a ciele
    // =========================
    [phraseKey("ambícia", "a2-41")]: {
        sk: "Moja ambícia je zlepšiť sa v práci.",
        ua: "Моя амбіція — стати кращим у своїй роботі.",
        ru: "Моя амбиция — стать лучше в своей работе.",
        en: "My ambition is to become better at my job.",
        uaTokens: ["Моя", "амбіція", "—", "стати", "кращим", "у", "своїй", "роботі", "."],
        ruTokens: ["Моя", "амбиция", "—", "стать", "лучше", "в", "своей", "работе", "."],
        enTokens: ["My", "ambition", "is", "to", "become", "better", "at", "my", "job", "."],
        extraUaTokens: ["мета", "успіх", "план"],
        extraRuTokens: ["цель", "успех", "план"],
        extraEnTokens: ["goal", "success", "plan"],
    },

    [phraseKey("stratégia", "a2-41")]: {
        sk: "Potrebujeme jasnú stratégiu.",
        ua: "Нам потрібна чітка стратегія.",
        ru: "Нам нужна чёткая стратегия.",
        en: "We need a clear strategy.",
        uaTokens: ["Нам", "потрібна", "чітка", "стратегія", "."],
        ruTokens: ["Нам", "нужна", "чёткая", "стратегия", "."],
        enTokens: ["We", "need", "a", "clear", "strategy", "."],
        extraUaTokens: ["рішення", "ціль", "метод"],
        extraRuTokens: ["решение", "цель", "метод"],
        extraEnTokens: ["solution", "goal", "method"],
    },

    [phraseKey("odhodlanie", "a2-41")]: {
        sk: "Bez odhodlania to nepôjde.",
        ua: "Без рішучості це не вийде.",
        ru: "Без решимости это не получится.",
        en: "Without determination, it will not work.",
        uaTokens: ["Без", "рішучості", "це", "не", "вийде", "."],
        ruTokens: ["Без", "решимости", "это", "не", "получится", "."],
        enTokens: ["Without", "determination", ",", "it", "will", "not", "work", "."],
        extraUaTokens: ["сила", "характер", "витримка"],
        extraRuTokens: ["сила", "характер", "выдержка"],
        extraEnTokens: ["strength", "character", "endurance"],
    },

    [phraseKey("zvážiť", "a2-41")]: {
        sk: "Musím zvážiť všetky možnosti.",
        ua: "Мені треба зважити всі варіанти.",
        ru: "Мне нужно взвесить все варианты.",
        en: "I need to consider all the options.",
        uaTokens: ["Мені", "треба", "зважити", "всі", "варіанти", "."],
        ruTokens: ["Мне", "нужно", "взвесить", "все", "варианты", "."],
        enTokens: ["I", "need", "to", "consider", "all", "the", "options", "."],
        extraUaTokens: ["обрати", "рішення", "спосіб"],
        extraRuTokens: ["выбрать", "решение", "способ"],
        extraEnTokens: ["choose", "decision", "method"],
    },

    [phraseKey("prispôsobiť sa", "a2-41")]: {
        sk: "Viem sa prispôsobiť novým podmienkam.",
        ua: "Я вмію пристосуватися до нових умов.",
        ru: "Я умею приспособиться к новым условиям.",
        en: "I can adapt to new conditions.",
        uaTokens: ["Я", "вмію", "пристосуватися", "до", "нових", "умов", "."],
        ruTokens: ["Я", "умею", "приспособиться", "к", "новым", "условиям", "."],
        enTokens: ["I", "can", "adapt", "to", "new", "conditions", "."],
        extraUaTokens: ["змін", "ситуації", "швидко"],
        extraRuTokens: ["изменениям", "ситуации", "быстро"],
        extraEnTokens: ["changes", "situation", "quickly"],
    },

    [phraseKey("priorita", "a2-41")]: {
        sk: "Moja priorita je zdravie.",
        ua: "Мій пріоритет — здоров’я.",
        ru: "Мой приоритет — здоровье.",
        en: "My priority is health.",
        uaTokens: ["Мій", "пріоритет", "—", "здоров’я", "."],
        ruTokens: ["Мой", "приоритет", "—", "здоровье", "."],
        enTokens: ["My", "priority", "is", "health", "."],
        extraUaTokens: ["робота", "сім’я", "відпочинок"],
        extraRuTokens: ["работа", "семья", "отдых"],
        extraEnTokens: ["work", "family", "rest"],
    },

    [phraseKey("dosiahnuť", "a2-41")]: {
        sk: "Chcem dosiahnuť lepšie výsledky.",
        ua: "Я хочу досягти кращих результатів.",
        ru: "Я хочу достичь лучших результатов.",
        en: "I want to achieve better results.",
        uaTokens: ["Я", "хочу", "досягти", "кращих", "результатів", "."],
        ruTokens: ["Я", "хочу", "достичь", "лучших", "результатов", "."],
        enTokens: ["I", "want", "to", "achieve", "better", "results", "."],
        extraUaTokens: ["успіху", "мети", "більше"],
        extraRuTokens: ["успеха", "цели", "больше"],
        extraEnTokens: ["success", "goal", "more"],
    },

    [phraseKey("pokrok", "a2-41")]: {
        sk: "Vidím pokrok každý týždeň.",
        ua: "Я бачу прогрес щотижня.",
        ru: "Я вижу прогресс каждую неделю.",
        en: "I see progress every week.",
        uaTokens: ["Я", "бачу", "прогрес", "щотижня", "."],
        ruTokens: ["Я", "вижу", "прогресс", "каждую", "неделю", "."],
        enTokens: ["I", "see", "progress", "every", "week", "."],
        extraUaTokens: ["розвиток", "успіх", "зміни"],
        extraRuTokens: ["развитие", "успех", "изменения"],
        extraEnTokens: ["development", "success", "changes"],
    },

    [phraseKey("vytrvať", "a2-41")]: {
        sk: "Musíš vytrvať a nevzdať sa.",
        ua: "Треба витримати й не здатися.",
        ru: "Нужно выдержать и не сдаться.",
        en: "You have to persevere and not give up.",
        uaTokens: ["Треба", "витримати", "й", "не", "здатися", "."],
        ruTokens: ["Нужно", "выдержать", "и", "не", "сдаться", "."],
        enTokens: ["You", "have", "to", "persevere", "and", "not", "give", "up", "."],
        extraUaTokens: ["далі", "до", "кінця"],
        extraRuTokens: ["дальше", "до", "конца"],
        extraEnTokens: ["further", "until", "end"],
    },

    [phraseKey("pokračovať", "a2-41")]: {
        sk: "Môžeme pokračovať zajtra.",
        ua: "Можемо продовжити завтра.",
        ru: "Мы можем продолжить завтра.",
        en: "We can continue tomorrow.",
        uaTokens: ["Можемо", "продовжити", "завтра", "."],
        ruTokens: ["Мы", "можем", "продолжить", "завтра", "."],
        enTokens: ["We", "can", "continue", "tomorrow", "."],
        extraUaTokens: ["сьогодні", "пізніше", "разом"],
        extraRuTokens: ["сегодня", "позже", "вместе"],
        extraEnTokens: ["today", "later", "together"],
    },

    // =========================
    // LESSON 42 — V meste (orientácia)
    // =========================
    [phraseKey("smer", "a2-42")]: {
        sk: "Ktorým smerom je stanica?",
        ua: "У якому напрямку вокзал?",
        ru: "В каком направлении вокзал?",
        en: "In which direction is the station?",
        uaTokens: ["У", "якому", "напрямку", "вокзал", "?"],
        ruTokens: ["В", "каком", "направлении", "вокзал", "?"],
        enTokens: ["In", "which", "direction", "is", "the", "station", "?"],
        extraUaTokens: ["місто", "карта", "вулиця"],
        extraRuTokens: ["город", "карта", "улица"],
        extraEnTokens: ["city", "map", "street"],
    },

    [phraseKey("odbočiť", "a2-42")]: {
        sk: "Na križovatke odbočte doprava.",
        ua: "На перехресті поверніть праворуч.",
        ru: "На перекрёстке поверните направо.",
        en: "Turn right at the intersection.",
        uaTokens: ["На", "перехресті", "поверніть", "праворуч", "."],
        ruTokens: ["На", "перекрёстке", "поверните", "направо", "."],
        enTokens: ["Turn", "right", "at", "the", "intersection", "."],
        extraUaTokens: ["ліворуч", "прямо", "світлофор"],
        extraRuTokens: ["налево", "прямо", "светофор"],
        extraEnTokens: ["left", "straight", "light"],
    },

    [phraseKey("kruhový objazd", "a2-42")]: {
        sk: "Na kruhovom objazde choďte druhým výjazdom.",
        ua: "На кільці їдьте другим виїздом.",
        ru: "На круговом перекрёстке езжайте вторым съездом.",
        en: "At the roundabout, take the second exit.",
        uaTokens: ["На", "кільці", "їдьте", "другим", "виїздом", "."],
        ruTokens: ["На", "круговом", "перекрёстке", "езжайте", "вторым", "съездом", "."],
        enTokens: ["At", "the", "roundabout", ",", "take", "the", "second", "exit", "."],
        extraUaTokens: ["першим", "третім", "дорога"],
        extraRuTokens: ["первым", "третьим", "дорога"],
        extraEnTokens: ["first", "third", "road"],
    },

    [phraseKey("prechod pre chodcov", "a2-42")]: {
        sk: "Prejdite cez prechod pre chodcov.",
        ua: "Перейдіть через пішохідний перехід.",
        ru: "Перейдите через пешеходный переход.",
        en: "Cross the pedestrian crossing.",
        uaTokens: ["Перейдіть", "через", "пішохідний", "перехід", "."],
        ruTokens: ["Перейдите", "через", "пешеходный", "переход", "."],
        enTokens: ["Cross", "the", "pedestrian", "crossing", "."],
        extraUaTokens: ["обережно", "дорога", "світлофор"],
        extraRuTokens: ["осторожно", "дорога", "светофор"],
        extraEnTokens: ["carefully", "road", "light"],
    },

    [phraseKey("zákaz", "a2-42")]: {
        sk: "Tu je zákaz parkovania.",
        ua: "Тут заборона паркування.",
        ru: "Здесь запрет парковки.",
        en: "Parking is forbidden here.",
        uaTokens: ["Тут", "заборона", "паркування", "."],
        ruTokens: ["Здесь", "запрет", "парковки", "."],
        enTokens: ["Parking", "is", "forbidden", "here", "."],
        extraUaTokens: ["стоянка", "машина", "знак"],
        extraRuTokens: ["стоянка", "машина", "знак"],
        extraEnTokens: ["parking", "car", "sign"],
    },

    [phraseKey("povolené", "a2-42")]: {
        sk: "Tu je povolené odbočiť vľavo.",
        ua: "Тут дозволено повернути ліворуч.",
        ru: "Здесь разрешено повернуть налево.",
        en: "Turning left is allowed here.",
        uaTokens: ["Тут", "дозволено", "повернути", "ліворуч", "."],
        ruTokens: ["Здесь", "разрешено", "повернуть", "налево", "."],
        enTokens: ["Turning", "left", "is", "allowed", "here", "."],
        extraUaTokens: ["праворуч", "знак", "рух"],
        extraRuTokens: ["направо", "знак", "движение"],
        extraEnTokens: ["right", "sign", "traffic"],
    },

    [phraseKey("obchádzka", "a2-42")]: {
        sk: "Cesta je uzavretá, je tu obchádzka.",
        ua: "Дорога закрита, тут об’їзд.",
        ru: "Дорога закрыта, здесь объезд.",
        en: "The road is closed, there is a detour here.",
        uaTokens: ["Дорога", "закрита", ",", "тут", "об’їзд", "."],
        ruTokens: ["Дорога", "закрыта", ",", "здесь", "объезд", "."],
        enTokens: ["The", "road", "is", "closed", ",", "there", "is", "a", "detour", "here", "."],
        extraUaTokens: ["ремонт", "шлях", "міст"],
        extraRuTokens: ["ремонт", "путь", "мост"],
        extraEnTokens: ["repair", "route", "bridge"],
    },

    [phraseKey("zablúdiť", "a2-42")]: {
        sk: "Myslím, že som zablúdil.",
        ua: "Мені здається, що я заблукав.",
        ru: "Кажется, я заблудился.",
        en: "I think I got lost.",
        uaTokens: ["Мені", "здається", ",", "що", "я", "заблукав", "."],
        ruTokens: ["Кажется", ",", "я", "заблудился", "."],
        enTokens: ["I", "think", "I", "got", "lost", "."],
        extraUaTokens: ["карта", "допомога", "адреса"],
        extraRuTokens: ["карта", "помощь", "адрес"],
        extraEnTokens: ["map", "help", "address"],
    },

    [phraseKey("nasledovať", "a2-42")]: {
        sk: "Nasledujte túto ulicu až po most.",
        ua: "Слідуйте цією вулицею аж до мосту.",
        ru: "Следуйте по этой улице до моста.",
        en: "Follow this street all the way to the bridge.",
        uaTokens: ["Слідуйте", "цією", "вулицею", "аж", "до", "мосту", "."],
        ruTokens: ["Следуйте", "по", "этой", "улице", "до", "моста", "."],
        enTokens: ["Follow", "this", "street", "all", "the", "way", "to", "the", "bridge", "."],
        extraUaTokens: ["прямо", "далі", "будинок"],
        extraRuTokens: ["прямо", "дальше", "дом"],
        extraEnTokens: ["straight", "further", "house"],
    },

    [phraseKey("orientovať sa", "a2-42")]: {
        sk: "Neviem sa tu dobre orientovať.",
        ua: "Я тут погано орієнтуюся.",
        ru: "Я здесь плохо ориентируюсь.",
        en: "I do not know my way around here well.",
        uaTokens: ["Я", "тут", "погано", "орієнтуюся", "."],
        ruTokens: ["Я", "здесь", "плохо", "ориентируюсь", "."],
        enTokens: ["I", "do", "not", "know", "my", "way", "around", "here", "well", "."],
        extraUaTokens: ["карта", "місто", "район"],
        extraRuTokens: ["карта", "город", "район"],
        extraEnTokens: ["map", "city", "district"],
    },

    // =========================
    // LESSON 43 — Zvyky a rutina
    // =========================
    [phraseKey("zvyk", "a2-43")]: {
        sk: "Mám zvyk vstávať skoro.",
        ua: "Я маю звичку вставати рано.",
        ru: "У меня привычка вставать рано.",
        en: "I have a habit of getting up early.",
        uaTokens: ["Я", "маю", "звичку", "вставати", "рано", "."],
        ruTokens: ["У", "меня", "привычка", "вставать", "рано", "."],
        enTokens: ["I", "have", "a", "habit", "of", "getting", "up", "early", "."],
        extraUaTokens: ["щодня", "вранці", "завжди"],
        extraRuTokens: ["каждый", "утром", "всегда"],
        extraEnTokens: ["daily", "morning", "always"],
    },

    [phraseKey("rutina", "a2-43")]: {
        sk: "Moja ranná rutina trvá desať minút.",
        ua: "Моя ранкова рутина триває десять хвилин.",
        ru: "Моя утренняя рутина длится десять минут.",
        en: "My morning routine takes ten minutes.",
        uaTokens: ["Моя", "ранкова", "рутина", "триває", "десять", "хвилин", "."],
        ruTokens: ["Моя", "утренняя", "рутина", "длится", "десять", "минут", "."],
        enTokens: ["My", "morning", "routine", "takes", "ten", "minutes", "."],
        extraUaTokens: ["швидко", "кава", "душ"],
        extraRuTokens: ["быстро", "кофе", "душ"],
        extraEnTokens: ["quickly", "coffee", "shower"],
    },

    [phraseKey("zvyknúť si", "a2-43")]: {
        sk: "Musel som si zvyknúť na nový režim.",
        ua: "Мені довелося звикнути до нового режиму.",
        ru: "Мне пришлось привыкнуть к новому режиму.",
        en: "I had to get used to the new routine.",
        uaTokens: ["Мені", "довелося", "звикнути", "до", "нового", "режиму", "."],
        ruTokens: ["Мне", "пришлось", "привыкнуть", "к", "новому", "режиму", "."],
        enTokens: ["I", "had", "to", "get", "used", "to", "the", "new", "routine", "."],
        extraUaTokens: ["роботи", "життя", "графіка"],
        extraRuTokens: ["работы", "жизни", "графика"],
        extraEnTokens: ["work", "life", "schedule"],
    },

    [phraseKey("odvyknúť si", "a2-43")]: {
        sk: "Chcem si odvyknúť od sladkého.",
        ua: "Я хочу відвикнути від солодкого.",
        ru: "Я хочу отвыкнуть от сладкого.",
        en: "I want to give up sweets.",
        uaTokens: ["Я", "хочу", "відвикнути", "від", "солодкого", "."],
        ruTokens: ["Я", "хочу", "отвыкнуть", "от", "сладкого", "."],
        enTokens: ["I", "want", "to", "give", "up", "sweets", "."],
        extraUaTokens: ["цукру", "звички", "шоколаду"],
        extraRuTokens: ["сахара", "привычки", "шоколада"],
        extraEnTokens: ["sugar", "habit", "chocolate"],
    },

    [phraseKey("pravidelne", "a2-43")]: {
        sk: "Snažím sa cvičiť pravidelne.",
        ua: "Я намагаюся тренуватися регулярно.",
        ru: "Я стараюсь тренироваться регулярно.",
        en: "I try to exercise regularly.",
        uaTokens: ["Я", "намагаюся", "тренуватися", "регулярно", "."],
        ruTokens: ["Я", "стараюсь", "тренироваться", "регулярно", "."],
        enTokens: ["I", "try", "to", "exercise", "regularly", "."],
        extraUaTokens: ["щодня", "спорт", "режим"],
        extraRuTokens: ["ежедневно", "спорт", "режим"],
        extraEnTokens: ["daily", "sport", "routine"],
    },

    [phraseKey("výnimka", "a2-43")]: {
        sk: "Dnes urobím výnimku.",
        ua: "Сьогодні зроблю виняток.",
        ru: "Сегодня сделаю исключение.",
        en: "Today I will make an exception.",
        uaTokens: ["Сьогодні", "зроблю", "виняток", "."],
        ruTokens: ["Сегодня", "сделаю", "исключение", "."],
        enTokens: ["Today", "I", "will", "make", "an", "exception", "."],
        extraUaTokens: ["раз", "правило", "інколи"],
        extraRuTokens: ["раз", "правило", "иногда"],
        extraEnTokens: ["once", "rule", "sometimes"],
    },

    [phraseKey("zlepšiť", "a2-43")]: {
        sk: "Chcem zlepšiť svoju kondíciu.",
        ua: "Я хочу покращити свою фізичну форму.",
        ru: "Я хочу улучшить свою физическую форму.",
        en: "I want to improve my physical shape.",
        uaTokens: ["Я", "хочу", "покращити", "свою", "фізичну", "форму", "."],
        ruTokens: ["Я", "хочу", "улучшить", "свою", "физическую", "форму", "."],
        enTokens: ["I", "want", "to", "improve", "my", "physical", "shape", "."],
        extraUaTokens: ["здоров’я", "тіло", "силу"],
        extraRuTokens: ["здоровье", "тело", "силу"],
        extraEnTokens: ["health", "body", "strength"],
    },

    [phraseKey("zhoršiť", "a2-43")]: {
        sk: "Stres môže zhoršiť spánok.",
        ua: "Стрес може погіршити сон.",
        ru: "Стресс может ухудшить сон.",
        en: "Stress can worsen sleep.",
        uaTokens: ["Стрес", "може", "погіршити", "сон", "."],
        ruTokens: ["Стресс", "может", "ухудшить", "сон", "."],
        enTokens: ["Stress", "can", "worsen", "sleep", "."],
        extraUaTokens: ["настрій", "здоров’я", "стан"],
        extraRuTokens: ["настроение", "здоровье", "состояние"],
        extraEnTokens: ["mood", "health", "condition"],
    },

    [phraseKey("zdravý štýl", "a2-43")]: {
        sk: "Zdravý štýl je pre mňa dôležitý.",
        ua: "Здоровий стиль життя для мене важливий.",
        ru: "Здоровый образ жизни для меня важен.",
        en: "A healthy lifestyle is important to me.",
        uaTokens: ["Здоровий", "стиль", "життя", "для", "мене", "важливий", "."],
        ruTokens: ["Здоровый", "образ", "жизни", "для", "меня", "важен", "."],
        enTokens: ["A", "healthy", "lifestyle", "is", "important", "to", "me", "."],
        extraUaTokens: ["харчування", "спорт", "сон"],
        extraRuTokens: ["питание", "спорт", "сон"],
        extraEnTokens: ["nutrition", "sport", "sleep"],
    },

    [phraseKey("disciplína", "a2-43")]: {
        sk: "Bez disciplíny to nejde.",
        ua: "Без дисципліни це не працює.",
        ru: "Без дисциплины это не работает.",
        en: "Without discipline, it does not work.",
        uaTokens: ["Без", "дисципліни", "це", "не", "працює", "."],
        ruTokens: ["Без", "дисциплины", "это", "не", "работает", "."],
        enTokens: ["Without", "discipline", ",", "it", "does", "not", "work", "."],
        extraUaTokens: ["режим", "мета", "успіх"],
        extraRuTokens: ["режим", "цель", "успех"],
        extraEnTokens: ["routine", "goal", "success"],
    },

    // =========================
    // LESSON 44 — Charakter a správanie
    // =========================
    [phraseKey("správanie", "a2-44")]: {
        sk: "Jeho správanie ma prekvapilo.",
        ua: "Його поведінка мене здивувала.",
        ru: "Его поведение меня удивило.",
        en: "His behavior surprised me.",
        uaTokens: ["Його", "поведінка", "мене", "здивувала", "."],
        ruTokens: ["Его", "поведение", "меня", "удивило", "."],
        enTokens: ["His", "behavior", "surprised", "me", "."],
        extraUaTokens: ["характер", "вчинок", "людина"],
        extraRuTokens: ["характер", "поступок", "человек"],
        extraEnTokens: ["character", "action", "person"],
    },

    [phraseKey("zdvorilý", "a2-44")]: {
        sk: "Bol veľmi zdvorilý k zákazníkom.",
        ua: "Він був дуже ввічливий до клієнтів.",
        ru: "Он был очень вежлив с клиентами.",
        en: "He was very polite to the customers.",
        uaTokens: ["Він", "був", "дуже", "ввічливий", "до", "клієнтів", "."],
        ruTokens: ["Он", "был", "очень", "вежлив", "с", "клиентами", "."],
        enTokens: ["He", "was", "very", "polite", "to", "the", "customers", "."],
        extraUaTokens: ["добрий", "спокійний", "людяний"],
        extraRuTokens: ["добрый", "спокойный", "человечный"],
        extraEnTokens: ["kind", "calm", "humane"],
    },

    [phraseKey("drzý", "a2-44")]: {
        sk: "Nemusíš byť taký drzý.",
        ua: "Не треба бути таким зухвалим.",
        ru: "Не нужно быть таким дерзким.",
        en: "You do not have to be so rude.",
        uaTokens: ["Не", "треба", "бути", "таким", "зухвалим", "."],
        ruTokens: ["Не", "нужно", "быть", "таким", "дерзким", "."],
        enTokens: ["You", "do", "not", "have", "to", "be", "so", "rude", "."],
        extraUaTokens: ["грубим", "різким", "невихованим"],
        extraRuTokens: ["грубым", "резким", "невоспитанным"],
        extraEnTokens: ["rough", "harsh", "impolite"],
    },

    [phraseKey("trpezlivý", "a2-44")]: {
        sk: "Buď trpezlivý, prosím.",
        ua: "Будь терплячим, будь ласка.",
        ru: "Будь терпеливым, пожалуйста.",
        en: "Be patient, please.",
        uaTokens: ["Будь", "терплячим", ",", "будь", "ласка", "."],
        ruTokens: ["Будь", "терпеливым", ",", "пожалуйста", "."],
        enTokens: ["Be", "patient", ",", "please", "."],
        extraUaTokens: ["спокійним", "уважним", "добрим"],
        extraRuTokens: ["спокойным", "внимательным", "добрым"],
        extraEnTokens: ["calm", "attentive", "kind"],
    },

    [phraseKey("netrpezlivý", "a2-44")]: {
        sk: "Je netrpezlivý, keď musí čakať.",
        ua: "Він нетерплячий, коли треба чекати.",
        ru: "Он нетерпелив, когда нужно ждать.",
        en: "He is impatient when he has to wait.",
        uaTokens: ["Він", "нетерплячий", ",", "коли", "треба", "чекати", "."],
        ruTokens: ["Он", "нетерпелив", ",", "когда", "нужно", "ждать", "."],
        enTokens: ["He", "is", "impatient", "when", "he", "has", "to", "wait", "."],
        extraUaTokens: ["довго", "черга", "час"],
        extraRuTokens: ["долго", "очередь", "время"],
        extraEnTokens: ["long", "queue", "time"],
    },

    [phraseKey("ochotný", "a2-44")]: {
        sk: "Personál bol ochotný pomôcť.",
        ua: "Персонал був готовий допомогти.",
        ru: "Персонал был готов помочь.",
        en: "The staff were willing to help.",
        uaTokens: ["Персонал", "був", "готовий", "допомогти", "."],
        ruTokens: ["Персонал", "был", "готов", "помочь", "."],
        enTokens: ["The", "staff", "were", "willing", "to", "help", "."],
        extraUaTokens: ["одразу", "людям", "клієнту"],
        extraRuTokens: ["сразу", "людям", "клиенту"],
        extraEnTokens: ["immediately", "people", "client"],
    },

    [phraseKey("tvrdohlavý", "a2-44")]: {
        sk: "Niekedy som až príliš tvrdohlavý.",
        ua: "Іноді я аж занадто впертий.",
        ru: "Иногда я слишком упрямый.",
        en: "Sometimes I am just too stubborn.",
        uaTokens: ["Іноді", "я", "аж", "занадто", "впертий", "."],
        ruTokens: ["Иногда", "я", "слишком", "упрямый", "."],
        enTokens: ["Sometimes", "I", "am", "just", "too", "stubborn", "."],
        extraUaTokens: ["характер", "думка", "свій"],
        extraRuTokens: ["характер", "мнение", "свой"],
        extraEnTokens: ["character", "opinion", "own"],
    },

    [phraseKey("priateľský", "a2-44")]: {
        sk: "Má priateľský prístup.",
        ua: "Він має дружній підхід.",
        ru: "У него дружелюбный подход.",
        en: "He has a friendly approach.",
        uaTokens: ["Він", "має", "дружній", "підхід", "."],
        ruTokens: ["У", "него", "дружелюбный", "подход", "."],
        enTokens: ["He", "has", "a", "friendly", "approach", "."],
        extraUaTokens: ["до", "людей", "роботи"],
        extraRuTokens: ["к", "людям", "работе"],
        extraEnTokens: ["to", "people", "work"],
    },

    [phraseKey("zodpovedný", "a2-44")]: {
        sk: "Je zodpovedný za výsledok.",
        ua: "Він відповідальний за результат.",
        ru: "Он ответственен за результат.",
        en: "He is responsible for the result.",
        uaTokens: ["Він", "відповідальний", "за", "результат", "."],
        ruTokens: ["Он", "ответственен", "за", "результат", "."],
        enTokens: ["He", "is", "responsible", "for", "the", "result", "."],
        extraUaTokens: ["роботу", "справу", "проєкт"],
        extraRuTokens: ["работу", "дело", "проект"],
        extraEnTokens: ["work", "task", "project"],
    },

    [phraseKey("lenivý", "a2-44")]: {
        sk: "Nechcem byť lenivý, chcem sa zlepšiť.",
        ua: "Я не хочу бути ледачим, хочу покращитися.",
        ru: "Я не хочу быть ленивым, хочу улучшиться.",
        en: "I do not want to be lazy, I want to improve.",
        uaTokens: ["Я", "не", "хочу", "бути", "ледачим", ",", "хочу", "покращитися", "."],
        ruTokens: ["Я", "не", "хочу", "быть", "ленивым", ",", "хочу", "улучшиться", "."],
        enTokens: ["I", "do", "not", "want", "to", "be", "lazy", ",", "I", "want", "to", "improve", "."],
        extraUaTokens: ["активним", "кращим", "сильнішим"],
        extraRuTokens: ["активным", "лучше", "сильнее"],
        extraEnTokens: ["active", "better", "stronger"],
    },

    // =========================
    // LESSON 45 — Problémy a riešenia
    // =========================
    [phraseKey("situácia", "a2-45")]: {
        sk: "Situácia sa zmenila.",
        ua: "Ситуація змінилася.",
        ru: "Ситуация изменилась.",
        en: "The situation has changed.",
        uaTokens: ["Ситуація", "змінилася", "."],
        ruTokens: ["Ситуация", "изменилась", "."],
        enTokens: ["The", "situation", "has", "changed", "."],
        extraUaTokens: ["раптом", "сьогодні", "повністю"],
        extraRuTokens: ["внезапно", "сегодня", "полностью"],
        extraEnTokens: ["suddenly", "today", "completely"],
    },

    [phraseKey("problém", "a2-45")]: {
        sk: "Máme problém s termínom.",
        ua: "У нас проблема з терміном.",
        ru: "У нас проблема со сроком.",
        en: "We have a problem with the deadline.",
        uaTokens: ["У", "нас", "проблема", "з", "терміном", "."],
        ruTokens: ["У", "нас", "проблема", "со", "сроком", "."],
        enTokens: ["We", "have", "a", "problem", "with", "the", "deadline", "."],
        extraUaTokens: ["час", "зустріч", "робота"],
        extraRuTokens: ["время", "встреча", "работа"],
        extraEnTokens: ["time", "meeting", "work"],
    },

    [phraseKey("riešenie", "a2-45")]: {
        sk: "Hľadáme najlepšie riešenie.",
        ua: "Ми шукаємо найкраще рішення.",
        ru: "Мы ищем лучшее решение.",
        en: "We are looking for the best solution.",
        uaTokens: ["Ми", "шукаємо", "найкраще", "рішення", "."],
        ruTokens: ["Мы", "ищем", "лучшее", "решение", "."],
        enTokens: ["We", "are", "looking", "for", "the", "best", "solution", "."],
        extraUaTokens: ["варіант", "вихід", "спосіб"],
        extraRuTokens: ["вариант", "выход", "способ"],
        extraEnTokens: ["option", "way", "method"],
    },

    [phraseKey("možnosť", "a2-45")]: {
        sk: "Je to jedna z možností.",
        ua: "Це один із варіантів.",
        ru: "Это один из вариантов.",
        en: "It is one of the options.",
        uaTokens: ["Це", "один", "із", "варіантів", "."],
        ruTokens: ["Это", "один", "из", "вариантов", "."],
        enTokens: ["It", "is", "one", "of", "the", "options", "."],
        extraUaTokens: ["інших", "рішень", "способів"],
        extraRuTokens: ["других", "решений", "способов"],
        extraEnTokens: ["other", "solutions", "ways"],
    },

    [phraseKey("riziko", "a2-45")]: {
        sk: "Je tu určité riziko.",
        ua: "Тут є певний ризик.",
        ru: "Здесь есть определённый риск.",
        en: "There is a certain risk here.",
        uaTokens: ["Тут", "є", "певний", "ризик", "."],
        ruTokens: ["Здесь", "есть", "определённый", "риск", "."],
        enTokens: ["There", "is", "a", "certain", "risk", "here", "."],
        extraUaTokens: ["небезпека", "можливість", "втрата"],
        extraRuTokens: ["опасность", "возможность", "потеря"],
        extraEnTokens: ["danger", "possibility", "loss"],
    },

    [phraseKey("dôsledok", "a2-45")]: {
        sk: "Každé rozhodnutie má dôsledok.",
        ua: "Кожне рішення має наслідки.",
        ru: "Каждое решение имеет последствия.",
        en: "Every decision has consequences.",
        uaTokens: ["Кожне", "рішення", "має", "наслідки", "."],
        ruTokens: ["Каждое", "решение", "имеет", "последствия", "."],
        enTokens: ["Every", "decision", "has", "consequences", "."],
        uaAltAnswers: [
            ["Кожне", "рішення", "має", "наслідок", "."],
        ],
        extraUaTokens: ["результат", "вплив", "ефект"],
        extraRuTokens: ["результат", "влияние", "эффект"],
        extraEnTokens: ["result", "impact", "effect"],
    },

    [phraseKey("výsledok", "a2-45")]: {
        sk: "Výsledok uvidíme čoskoro.",
        ua: "Результат побачимо скоро.",
        ru: "Результат увидим скоро.",
        en: "We will see the result soon.",
        uaTokens: ["Результат", "побачимо", "скоро", "."],
        ruTokens: ["Результат", "увидим", "скоро", "."],
        enTokens: ["We", "will", "see", "the", "result", "soon", "."],
        extraUaTokens: ["завтра", "потім", "пізніше"],
        extraRuTokens: ["завтра", "потом", "позже"],
        extraEnTokens: ["tomorrow", "then", "later"],
    },

    [phraseKey("zvládnuť", "a2-45")]: {
        sk: "Spolu to zvládneme.",
        ua: "Разом ми з цим впораємося.",
        ru: "Вместе мы с этим справимся.",
        en: "Together we will handle it.",
        uaTokens: ["Разом", "ми", "з", "цим", "впораємося", "."],
        ruTokens: ["Вместе", "мы", "с", "этим", "справимся", "."],
        enTokens: ["Together", "we", "will", "handle", "it", "."],
        extraUaTokens: ["точно", "успішно", "разом"],
        extraRuTokens: ["точно", "успешно", "вместе"],
        extraEnTokens: ["definitely", "successfully", "together"],
    },

    [phraseKey("poradiť si", "a2-45")]: {
        sk: "Musím si s tým nejako poradiť.",
        ua: "Мені треба якось із цим дати собі раду.",
        ru: "Мне нужно как-то с этим справиться.",
        en: "I need to deal with it somehow.",
        uaTokens: ["Мені", "треба", "якось", "із", "цим", "дати", "собі", "раду", "."],
        ruTokens: ["Мне", "нужно", "как-то", "с", "этим", "справиться", "."],
        enTokens: ["I", "need", "to", "deal", "with", "it", "somehow", "."],
        extraUaTokens: ["самому", "швидко", "зараз"],
        extraRuTokens: ["самому", "быстро", "сейчас"],
        extraEnTokens: ["myself", "quickly", "now"],
    },

    [phraseKey("pokus", "a2-45")]: {
        sk: "Dáme tomu ešte jeden pokus.",
        ua: "Дамо цьому ще одну спробу.",
        ru: "Дадим этому ещё одну попытку.",
        en: "We will give it one more try.",
        uaTokens: ["Дамо", "цьому", "ще", "одну", "спробу", "."],
        ruTokens: ["Дадим", "этому", "ещё", "одну", "попытку", "."],
        enTokens: ["We", "will", "give", "it", "one", "more", "try", "."],
        extraUaTokens: ["раз", "остання", "можливість"],
        extraRuTokens: ["раз", "последняя", "возможность"],
        extraEnTokens: ["once", "last", "chance"],
    },
};