import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A2_BUILD_UA_SENTENCES_1: BuildUaSentenceDict = {
    // =========================
    // LESSON 1 — Дім і побут (розширено)
    // =========================
    [phraseKey("czynsz", "a2-1")]: {
        sk: "Czynsz trzeba płacić do dziesiątego dnia miesiąca.",
        ua: "Оренду треба платити до десятого числа місяця.",
        ru: "Аренду нужно платить до десятого числа месяца.",
        en: "The rent has to be paid by the tenth day of the month.",
        uaTokens: ["Оренду", "треба", "платити", "до", "десятого", "числа", "місяця", "."],
        ruTokens: ["Аренду", "нужно", "платить", "до", "десятого", "числа", "месяца", "."],
        enTokens: ["The", "rent", "has", "to", "be", "paid", "by", "the", "tenth", "day", "of", "the", "month", "."],
        extraUaTokens: ["договір", "енергію", "сусід"],
        extraRuTokens: ["договор", "энергию", "сосед"],
        extraEnTokens: ["agreement", "energy", "neighbor"],
    },

    [phraseKey("umowa najmu", "a2-1")]: {
        sk: "Musimy podpisać umowę najmu.",
        ua: "Ми повинні підписати договір оренди.",
        ru: "Мы должны подписать договор аренды.",
        en: "We need to sign the rental agreement.",
        uaTokens: ["Ми", "повинні", "підписати", "договір", "оренди", "."],
        ruTokens: ["Мы", "должны", "подписать", "договор", "аренды", "."],
        enTokens: ["We", "need", "to", "sign", "the", "rental", "agreement", "."],
        extraUaTokens: ["оренду", "енергію", "квартири"],
        extraRuTokens: ["аренду", "энергию", "квартиры"],
        extraEnTokens: ["rent", "energy", "apartment"],
    },

    [phraseKey("właściciel", "a2-1")]: {
        sk: "Właściciel mieszkania mieszka za granicą.",
        ua: "Власник квартири живе за кордоном.",
        ru: "Владелец квартиры живёт за границей.",
        en: "The owner of the apartment lives abroad.",
        uaTokens: ["Власник", "квартири", "живе", "за", "кордоном", "."],
        ruTokens: ["Владелец", "квартиры", "живёт", "за", "границей", "."],
        enTokens: ["The", "owner", "of", "the", "apartment", "lives", "abroad", "."],
        extraUaTokens: ["орендар", "ремонт", "тижня"],
        extraRuTokens: ["арендатор", "ремонт", "недели"],
        extraEnTokens: ["subtenant", "repair", "week"],
    },

    [phraseKey("podnajemca", "a2-1")]: {
        sk: "Podnajemca musi przestrzegać zasad domu.",
        ua: "Орендар повинен дотримуватися правил будинку.",
        ru: "Арендатор должен соблюдать правила дома.",
        en: "The subtenant has to follow the house rules.",
        uaTokens: ["Орендар", "повинен", "дотримуватися", "правил", "будинку", "."],
        ruTokens: ["Арендатор", "должен", "соблюдать", "правила", "дома", "."],
        enTokens: ["The", "subtenant", "has", "to", "follow", "the", "house", "rules", "."],
        extraUaTokens: ["власник", "енергію", "сусід"],
        extraRuTokens: ["владелец", "энергию", "сосед"],
        extraEnTokens: ["owner", "energy", "neighbor"],
    },

    [phraseKey("rachunki", "a2-1")]: {
        sk: "Rachunki za prąd i wodę są bardzo wysokie.",
        ua: "Рахунки за електрику і воду дуже високі.",
        ru: "Счета за электричество и воду очень высокие.",
        en: "The bills for electricity and water are very high.",
        uaTokens: ["Рахунки", "за", "електрику", "і", "воду", "дуже", "високі", "."],
        ruTokens: ["Счета", "за", "электричество", "и", "воду", "очень", "высокие", "."],
        enTokens: ["The", "bills", "for", "electricity", "and", "water", "are", "very", "high", "."],
        extraUaTokens: ["оренду", "енергію", "ремонт"],
        extraRuTokens: ["аренду", "энергию", "ремонт"],
        extraEnTokens: ["rent", "energy", "repair"],
    },

    [phraseKey("energia", "a2-1")]: {
        sk: "Musimy oszczędzać energię.",
        ua: "Ми повинні економити енергію.",
        ru: "Мы должны экономить энергию.",
        en: "We need to save energy.",
        uaTokens: ["Ми", "повинні", "економити", "енергію", "."],
        ruTokens: ["Мы", "должны", "экономить", "энергию", "."],
        enTokens: ["We", "need", "to", "save", "energy", "."],
        extraUaTokens: ["рахунки", "орендар", "сусід"],
        extraRuTokens: ["счета", "арендатор", "сосед"],
        extraEnTokens: ["bills", "subtenant", "neighbor"],
    },

    [phraseKey("naprawa", "a2-1")]: {
        sk: "Naprawa pralki potrwa kilka dni.",
        ua: "Ремонт пральної машини триватиме кілька днів.",
        ru: "Ремонт стиральной машины займёт несколько дней.",
        en: "The repair of the washing machine will take a few days.",
        uaTokens: ["Ремонт", "пральної", "машини", "триватиме", "кілька", "днів", "."],
        ruTokens: ["Ремонт", "стиральной", "машины", "займёт", "несколько", "дней", "."],
        enTokens: ["The", "repair", "of", "the", "washing", "machine", "will", "take", "a", "few", "days", "."],
        extraUaTokens: ["духовка", "енергію", "сусід"],
        extraRuTokens: ["духовка", "энергию", "сосед"],
        extraEnTokens: ["oven", "energy", "neighbor"],
    },

    [phraseKey("zepsuty", "a2-1")]: {
        sk: "Piekarnik jest zepsuty od zeszłego tygodnia.",
        ua: "Духовка зламана ще з минулого тижня.",
        ru: "Духовка сломана с прошлой недели.",
        en: "The oven has been broken since last week.",
        uaTokens: ["Духовка", "зламана", "ще", "з", "минулого", "тижня", "."],
        ruTokens: ["Духовка", "сломана", "с", "прошлой", "недели", "."],
        enTokens: ["The", "oven", "has", "been", "broken", "since", "last", "week", "."],
        extraUaTokens: ["ремонт", "машини", "сусід"],
        extraRuTokens: ["ремонт", "машины", "сосед"],
        extraEnTokens: ["repair", "machine", "neighbor"],
    },

    [phraseKey("sąsiad", "a2-1")]: {
        sk: "Mój sąsiad zawsze pomaga mi z ciężkimi rzeczami.",
        ua: "Мій сусід завжди допомагає мені з важкими речами.",
        ru: "Мой сосед всегда помогает мне с тяжёлыми вещами.",
        en: "My neighbor always helps me with heavy things.",
        uaTokens: ["Мій", "сусід", "завжди", "допомагає", "мені", "з", "важкими", "речами", "."],
        ruTokens: ["Мой", "сосед", "всегда", "помогает", "мне", "с", "тяжёлыми", "вещами", "."],
        enTokens: ["My", "neighbor", "always", "helps", "me", "with", "heavy", "things", "."],
        uaAltAnswers: [
            ["Мій", "сусід", "завжди", "мені", "допомагає", "з", "важкими", "речами", "."]
        ],
        ruAltAnswers: [
            ["Мой", "сосед", "всегда", "мне", "помогает", "с", "тяжёлыми", "вещами", "."]
        ],
        extraUaTokens: ["духовка", "оренду", "договір"],
        extraRuTokens: ["духовка", "аренду", "договор"],
        extraEnTokens: ["oven", "rent", "agreement"],
    },
    [phraseKey("przeprowadzka", "a2-1")]: {
        sk: "Przeprowadzka do nowego mieszkania była bardzo męcząca.",
        ua: "Переїзд до нової квартири був дуже виснажливим.",
        ru: "Переезд в новую квартиру был очень утомительным.",
        en: "Moving to the new apartment was very exhausting.",
        uaTokens: ["Переїзд", "до", "нової", "квартири", "був", "дуже", "виснажливим", "."],
        ruTokens: ["Переезд", "в", "новую", "квартиру", "был", "очень", "утомительным", "."],
        enTokens: ["Moving", "to", "the", "new", "apartment", "was", "very", "exhausting", "."],
        extraUaTokens: ["сусід", "оренду", "днів"],
        extraRuTokens: ["сосед", "аренду", "дней"],
        extraEnTokens: ["neighbor", "rent", "days"],
    },

    // =========================
    // LESSON 2 — У лікаря
    // =========================
    [phraseKey("badanie", "a2-2")]: {
        sk: "Lekarz zlecił dodatkowe badanie.",
        ua: "Лікар призначив додаткове обстеження.",
        ru: "Врач назначил дополнительное обследование.",
        en: "The doctor ordered an additional examination.",
        uaTokens: ["Лікар", "призначив", "додаткове", "обстеження", "."],
        ruTokens: ["Врач", "назначил", "дополнительное", "обследование", "."],
        enTokens: ["The", "doctor", "ordered", "an", "additional", "examination", "."],
        extraUaTokens: ["діагноз", "термометр", "алергія"],
        extraRuTokens: ["диагноз", "термометр", "аллергия"],
        extraEnTokens: ["diagnosis", "thermometer", "allergy"],
    },

    [phraseKey("diagnoza", "a2-2")]: {
        sk: "Diagnoza była dla mnie zaskoczeniem.",
        ua: "Діагноз був для мене несподіванкою.",
        ru: "Диагноз стал для меня неожиданностью.",
        en: "The diagnosis was a surprise for me.",
        uaTokens: ["Діагноз", "був", "для", "мене", "несподіванкою", "."],
        ruTokens: ["Диагноз", "стал", "для", "меня", "неожиданностью", "."],
        enTokens: ["The", "diagnosis", "was", "a", "surprise", "for", "me", "."],
        extraUaTokens: ["обстеження", "температура", "аптеці"],
        extraRuTokens: ["обследование", "температура", "аптеке"],
        extraEnTokens: ["examination", "temperature", "pharmacy"],
    },

    [phraseKey("objaw", "a2-2")]: {
        sk: "Pierwszym objawem była wysoka temperatura.",
        ua: "Першим симптомом була висока температура.",
        ru: "Первым симптомом была высокая температура.",
        en: "The first symptom was a high temperature.",
        uaTokens: ["Першим", "симптомом", "була", "висока", "температура", "."],
        ruTokens: ["Первым", "симптомом", "была", "высокая", "температура", "."],
        enTokens: ["The", "first", "symptom", "was", "a", "high", "temperature", "."],
        extraUaTokens: ["діагноз", "горлі", "аптеці"],
        extraRuTokens: ["диагноз", "горле", "аптеке"],
        extraEnTokens: ["diagnosis", "throat", "pharmacy"],
    },

    [phraseKey("ból gardła", "a2-2")]: {
        sk: "Od rana mam silny ból gardła.",
        ua: "З самого ранку в мене сильний біль у горлі.",
        ru: "С самого утра у меня сильная боль в горле.",
        en: "I have had a strong sore throat since morning.",
        uaTokens: ["З", "самого", "ранку", "в", "мене", "сильний", "біль", "у", "горлі", "."],
        ruTokens: ["С", "самого", "утра", "у", "меня", "сильная", "боль", "в", "горле", "."],
        enTokens: ["I", "have", "had", "a", "strong", "sore", "throat", "since", "morning", "."],
        extraUaTokens: ["симптомом", "термометр", "пилок"],
        extraRuTokens: ["симптомом", "термометр", "пыльцу"],
        extraEnTokens: ["symptom", "thermometer", "pollen"],
    },

    [phraseKey("termometr", "a2-2")]: {
        sk: "Nie mogę znaleźć termometru.",
        ua: "Я не можу знайти термометр.",
        ru: "Я не могу найти термометр.",
        en: "I cannot find the thermometer.",
        uaTokens: ["Я", "не", "можу", "знайти", "термометр", "."],
        ruTokens: ["Я", "не", "могу", "найти", "термометр", "."],
        enTokens: ["I", "cannot", "find", "the", "thermometer", "."],
        extraUaTokens: ["обстеження", "температура", "аптеці"],
        extraRuTokens: ["обследование", "температура", "аптеке"],
        extraEnTokens: ["examination", "temperature", "pharmacy"],
    },

    [phraseKey("ciśnienie krwi", "a2-2")]: {
        sk: "Lekarz zmierzył mi ciśnienie krwi.",
        ua: "Лікар виміряв мені артеріальний тиск.",
        ru: "Врач измерил мне артериальное давление.",
        en: "The doctor measured my blood pressure.",
        uaTokens: ["Лікар", "виміряв", "мені", "артеріальний", "тиск", "."],
        ruTokens: ["Врач", "измерил", "мне", "артериальное", "давление", "."],
        enTokens: ["The", "doctor", "measured", "my", "blood", "pressure", "."],
        extraUaTokens: ["обстеження", "діагноз", "аптеці"],
        extraRuTokens: ["обследование", "диагноз", "аптеке"],
        extraEnTokens: ["examination", "diagnosis", "pharmacy"],
    },

    [phraseKey("recepta", "a2-2")]: {
        sk: "Muszę wykupić receptę w aptece.",
        ua: "Мені треба забрати рецепт в аптеці.",
        ru: "Мне нужно выкупить рецепт в аптеке.",
        en: "I need to fill the prescription at the pharmacy.",
        uaTokens: ["Мені", "треба", "забрати", "рецепт", "в", "аптеці", "."],
        ruTokens: ["Мне", "нужно", "выкупить", "рецепт", "в", "аптеке", "."],
        enTokens: ["I", "need", "to", "fill", "the", "prescription", "at", "the", "pharmacy", "."],
        extraUaTokens: ["термометр", "пилок", "бронхів"],
        extraRuTokens: ["термометр", "пыльцу", "бронхов"],
        extraEnTokens: ["thermometer", "pollen", "bronchi"],
    },

    [phraseKey("alergia", "a2-2")]: {
        sk: "Mam alergię na pyłki.",
        ua: "У мене алергія на пилок.",
        ru: "У меня аллергия на пыльцу.",
        en: "I am allergic to pollen.",
        uaTokens: ["У", "мене", "алергія", "на", "пилок", "."],
        ruTokens: ["У", "меня", "аллергия", "на", "пыльцу", "."],
        enTokens: ["I", "am", "allergic", "to", "pollen", "."],
        extraUaTokens: ["термометр", "рецепт", "бронхів"],
        extraRuTokens: ["термометр", "рецепт", "бронхов"],
        extraEnTokens: ["thermometer", "prescription", "bronchi"],
    },

    [phraseKey("zapalenie", "a2-2")]: {
        sk: "Lekarz podejrzewa zapalenie oskrzeli.",
        ua: "Лікар підозрює запалення бронхів.",
        ru: "Врач подозревает воспаление бронхов.",
        en: "The doctor suspects bronchitis.",
        uaTokens: ["Лікар", "підозрює", "запалення", "бронхів", "."],
        ruTokens: ["Врач", "подозревает", "воспаление", "бронхов", "."],
        enTokens: ["The", "doctor", "suspects", "bronchitis", "."],
        extraUaTokens: ["алергія", "аптеці", "відпочивати"],
        extraRuTokens: ["аллергия", "аптеке", "отдыхать"],
        extraEnTokens: ["allergy", "pharmacy", "rest"],
    },

    [phraseKey("rekomendacja", "a2-2")]: {
        sk: "Dostałem rekomendację, żeby więcej odpoczywać.",
        ua: "Я отримав рекомендацію більше відпочивати.",
        ru: "Я получил рекомендацию больше отдыхать.",
        en: "I got a recommendation to rest more.",
        uaTokens: ["Я", "отримав", "рекомендацію", "більше", "відпочивати", "."],
        ruTokens: ["Я", "получил", "рекомендацию", "больше", "отдыхать", "."],
        enTokens: ["I", "got", "a", "recommendation", "to", "rest", "more", "."],
        extraUaTokens: ["діагноз", "термометр", "бронхів"],
        extraRuTokens: ["диагноз", "термометр", "бронхов"],
        extraEnTokens: ["diagnosis", "thermometer", "bronchi"],
    },

    // =========================
    // LESSON 3 — Місто та послуги
    // =========================
    [phraseKey("urząd miejski", "a2-3")]: {
        sk: "Muszę załatwić tę sprawę w urzędzie miejskim.",
        ua: "Мені треба владнати цю справу в міській раді.",
        ru: "Мне нужно решить этот вопрос в мэрии.",
        en: "I need to handle this matter at the city hall.",
        uaTokens: ["Мені", "треба", "владнати", "цю", "справу", "в", "міській", "раді", "."],
        ruTokens: ["Мне", "нужно", "решить", "этот", "вопрос", "в", "мэрии", "."],
        enTokens: ["I", "need", "to", "handle", "this", "matter", "at", "the", "city", "hall", "."],
        extraUaTokens: ["відділу", "форму", "готівкою"],
        extraRuTokens: ["отдел", "форму", "наличными"],
        extraEnTokens: ["department", "form", "cash"],
    },

    [phraseKey("oddział", "a2-3")]: {
        sk: "Nie wiem, do którego oddziału mam iść.",
        ua: "Я не знаю, до якого відділу мені йти.",
        ru: "Я не знаю, в какой отдел мне идти.",
        en: "I do not know which department I should go to.",
        uaTokens: ["Я", "не", "знаю", ",", "до", "якого", "відділу", "мені", "йти", "."],
        ruTokens: ["Я", "не", "знаю", ",", "в", "какой", "отдел", "мне", "идти", "."],
        enTokens: ["I", "do", "not", "know", "which", "department", "I", "should", "go", "to", "."],
        extraUaTokens: ["справу", "заявник", "карткою"],
        extraRuTokens: ["вопрос", "заявитель", "картой"],
        extraEnTokens: ["matter", "applicant", "card"],
    },

    [phraseKey("wnioskodawca", "a2-3")]: {
        sk: "Wnioskodawca musi podpisać formularz.",
        ua: "Заявник повинен підписати форму.",
        ru: "Заявитель должен подписать форму.",
        en: "The applicant has to sign the form.",
        uaTokens: ["Заявник", "повинен", "підписати", "форму", "."],
        ruTokens: ["Заявитель", "должен", "подписать", "форму", "."],
        enTokens: ["The", "applicant", "has", "to", "sign", "the", "form", "."],
        extraUaTokens: ["відділу", "прописки", "готівкою"],
        extraRuTokens: ["отдел", "регистрации", "наличными"],
        extraEnTokens: ["department", "registration", "cash"],
    },

    [phraseKey("wniosek", "a2-3")]: {
        sk: "Złożyłem już wniosek o kartę pobytu.",
        ua: "Я вже подав заяву на карту побиту.",
        ru: "Я уже подал заявление на карту пребывания.",
        en: "I have already submitted the application for the residence card.",
        uaTokens: ["Я", "вже", "подав", "заяву", "на", "карту", "побиту", "."],
        ruTokens: ["Я", "уже", "подал", "заявление", "на", "карту", "пребывания", "."],
        enTokens: ["I", "have", "already", "submitted", "the", "application", "for", "the", "residence", "card", "."],
        extraUaTokens: ["форму", "документи", "візит"],
        extraRuTokens: ["форму", "документы", "приём"],
        extraEnTokens: ["form", "documents", "appointment"],
    },

    [phraseKey("dokument", "a2-3")]: {
        sk: "Proszę przygotować wszystkie dokumenty.",
        ua: "Будь ласка, підготуйте всі документи.",
        ru: "Пожалуйста, подготовьте все документы.",
        en: "Please prepare all the documents.",
        uaTokens: ["Будь", "ласка", ",", "підготуйте", "всі", "документи", "."],
        ruTokens: ["Пожалуйста", ",", "подготовьте", "все", "документы", "."],
        enTokens: ["Please", "prepare", "all", "the", "documents", "."],
        extraUaTokens: ["заяву", "карткою", "сайті"],
        extraRuTokens: ["заявление", "картой", "сайте"],
        extraEnTokens: ["application", "card", "website"],
    },

    [phraseKey("potwierdzenie", "a2-3")]: {
        sk: "Potrzebuję potwierdzenia zameldowania.",
        ua: "Мені потрібне підтвердження прописки.",
        ru: "Мне нужно подтверждение регистрации.",
        en: "I need a confirmation of residence registration.",
        uaTokens: ["Мені", "потрібне", "підтвердження", "прописки", "."],
        ruTokens: ["Мне", "нужно", "подтверждение", "регистрации", "."],
        enTokens: ["I", "need", "a", "confirmation", "of", "residence", "registration", "."],
        extraUaTokens: ["документи", "готівкою", "візит"],
        extraRuTokens: ["документы", "наличными", "приём"],
        extraEnTokens: ["documents", "cash", "appointment"],
    },

    [phraseKey("opłata", "a2-3")]: {
        sk: "Opłatę można uiścić kartą lub gotówką.",
        ua: "Збір можна сплатити карткою або готівкою.",
        ru: "Сбор можно оплатить картой или наличными.",
        en: "The fee can be paid by card or cash.",
        uaTokens: ["Збір", "можна", "сплатити", "карткою", "або", "готівкою", "."],
        ruTokens: ["Сбор", "можно", "оплатить", "картой", "или", "наличными", "."],
        enTokens: ["The", "fee", "can", "be", "paid", "by", "card", "or", "cash", "."],
        extraUaTokens: ["документи", "заяву", "сайті"],
        extraRuTokens: ["документы", "заявление", "сайте"],
        extraEnTokens: ["documents", "application", "website"],
    },

    [phraseKey("umówić się", "a2-3")]: {
        sk: "Muszę się umówić na wizytę.",
        ua: "Мені треба записатися на візит.",
        ru: "Мне нужно записаться на приём.",
        en: "I need to make an appointment.",
        uaTokens: ["Мені", "треба", "записатися", "на", "візит", "."],
        ruTokens: ["Мне", "нужно", "записаться", "на", "приём", "."],
        enTokens: ["I", "need", "to", "make", "an", "appointment", "."],
        extraUaTokens: ["документи", "карткою", "сайті"],
        extraRuTokens: ["документы", "картой", "сайте"],
        extraEnTokens: ["documents", "card", "website"],
    },

    [phraseKey("godziny otwarcia", "a2-3")]: {
        sk: "Sprawdziłem godziny otwarcia na stronie internetowej.",
        ua: "Я перевірив години роботи на сайті.",
        ru: "Я проверил часы работы на сайте.",
        en: "I checked the opening hours on the website.",
        uaTokens: ["Я", "перевірив", "години", "роботи", "на", "сайті", "."],
        ruTokens: ["Я", "проверил", "часы", "работы", "на", "сайте", "."],
        enTokens: ["I", "checked", "the", "opening", "hours", "on", "the", "website", "."],
        extraUaTokens: ["візит", "готівкою", "форму"],
        extraRuTokens: ["приём", "наличными", "форму"],
        extraEnTokens: ["appointment", "cash", "form"],
    },

    [phraseKey("formularz", "a2-3")]: {
        sk: "Musisz dokładnie wypełnić formularz.",
        ua: "Ти повинен уважно заповнити форму.",
        ru: "Ты должен внимательно заполнить форму.",
        en: "You have to fill out the form carefully.",
        uaTokens: ["Ти", "повинен", "уважно", "заповнити", "форму", "."],
        ruTokens: ["Ты", "должен", "внимательно", "заполнить", "форму", "."],
        enTokens: ["You", "have", "to", "fill", "out", "the", "form", "carefully", "."],
        extraUaTokens: ["заяву", "документи", "прописки"],
        extraRuTokens: ["заявление", "документы", "регистрации"],
        extraEnTokens: ["application", "documents", "registration"],
    },

    // =========================
    // LESSON 4 — Робота та карʼєра
    // =========================
    [phraseKey("rozmowa kwalifikacyjna", "a2-4")]: {
        sk: "Jutro mam rozmowę kwalifikacyjną.",
        ua: "Завтра в мене співбесіда.",
        ru: "Завтра у меня собеседование.",
        en: "Tomorrow I have a job interview.",
        uaTokens: ["Завтра", "в", "мене", "співбесіда", "."],
        ruTokens: ["Завтра", "у", "меня", "собеседование", "."],
        enTokens: ["Tomorrow", "I", "have", "a", "job", "interview", "."],
        extraUaTokens: ["резюме", "досвід", "графік"],
        extraRuTokens: ["резюме", "опыт", "график"],
        extraEnTokens: ["CV", "experience", "schedule"],
    },

    [phraseKey("życiorys", "a2-4")]: {
        sk: "Muszę zaktualizować swój życiorys.",
        ua: "Мені треба оновити своє резюме.",
        ru: "Мне нужно обновить своё резюме.",
        en: "I need to update my CV.",
        uaTokens: ["Мені", "треба", "оновити", "своє", "резюме", "."],
        ruTokens: ["Мне", "нужно", "обновить", "своё", "резюме", "."],
        enTokens: ["I", "need", "to", "update", "my", "CV", "."],
        extraUaTokens: ["співбесіда", "галузі", "графік"],
        extraRuTokens: ["собеседование", "сфере", "график"],
        extraEnTokens: ["interview", "field", "schedule"],
    },

    [phraseKey("praktyka", "a2-4")]: {
        sk: "Mam już dwuletnią praktykę w tej branży.",
        ua: "Я вже маю дворічний досвід у цій галузі.",
        ru: "У меня уже есть двухлетний опыт в этой сфере.",
        en: "I already have two years of experience in this field.",
        uaTokens: ["Я", "вже", "маю", "дворічний", "досвід", "у", "цій", "галузі", "."],
        ruTokens: ["У", "меня", "уже", "есть", "двухлетний", "опыт", "в", "этой", "сфере", "."],
        enTokens: ["I", "already", "have", "two", "years", "of", "experience", "in", "this", "field", "."],
        extraUaTokens: ["резюме", "навичка", "вакансія"],
        extraRuTokens: ["резюме", "навык", "вакансия"],
        extraEnTokens: ["CV", "skill", "offer"],
    },

    [phraseKey("umiejętność", "a2-4")]: {
        sk: "Znajomość języków to ważna umiejętność.",
        ua: "Знання мов — це важлива навичка.",
        ru: "Знание языков — это важный навык.",
        en: "Knowledge of languages is an important skill.",
        uaTokens: ["Знання", "мов", "—", "це", "важлива", "навичка", "."],
        ruTokens: ["Знание", "языков", "—", "это", "важный", "навык", "."],
        enTokens: ["Knowledge", "of", "languages", "is", "an", "important", "skill", "."],
        extraUaTokens: ["резюме", "вимога", "графік"],
        extraRuTokens: ["резюме", "требование", "график"],
        extraEnTokens: ["CV", "requirement", "schedule"],
    },

    [phraseKey("wymaganie", "a2-4")]: {
        sk: "To wymaganie jest dla mnie zrozumiałe.",
        ua: "Ця вимога для мене зрозуміла.",
        ru: "Это требование мне понятно.",
        en: "This requirement is clear to me.",
        uaTokens: ["Ця", "вимога", "для", "мене", "зрозуміла", "."],
        ruTokens: ["Это", "требование", "мне", "понятно", "."],
        enTokens: ["This", "requirement", "is", "clear", "to", "me", "."],
        extraUaTokens: ["навичка", "вакансія", "посада"],
        extraRuTokens: ["навык", "вакансия", "должность"],
        extraEnTokens: ["skill", "offer", "position"],
    },

    [phraseKey("oferta pracy", "a2-4")]: {
        sk: "Ta oferta pracy wygląda bardzo interesująco.",
        ua: "Ця вакансія виглядає дуже цікаво.",
        ru: "Эта вакансия выглядит очень интересно.",
        en: "This job offer looks very interesting.",
        uaTokens: ["Ця", "вакансія", "виглядає", "дуже", "цікаво", "."],
        ruTokens: ["Эта", "вакансия", "выглядит", "очень", "интересно", "."],
        enTokens: ["This", "job", "offer", "looks", "very", "interesting", "."],
        extraUaTokens: ["вимога", "посада", "графік"],
        extraRuTokens: ["требование", "должность", "график"],
        extraEnTokens: ["requirement", "position", "schedule"],
    },

    [phraseKey("stanowisko pracy", "a2-4")]: {
        sk: "Aplikuję na stanowisko w biurze.",
        ua: "Я подаюся на посаду в офісі.",
        ru: "Я подаюсь на должность в офисе.",
        en: "I am applying for a job position in an office.",
        uaTokens: ["Я", "подаюся", "на", "посаду", "в", "офісі", "."],
        ruTokens: ["Я", "подаюсь", "на", "должность", "в", "офисе", "."],
        enTokens: ["I", "am", "applying", "for", "a", "job", "position", "in", "an", "office", "."],
        extraUaTokens: ["вакансія", "відповідальністю", "резюме"],
        extraRuTokens: ["вакансия", "ответственностью", "резюме"],
        extraEnTokens: ["offer", "responsibility", "CV"],
    },

    [phraseKey("odpowiedzialność", "a2-4")]: {
        sk: "To stanowisko wiąże się z dużą odpowiedzialnością.",
        ua: "Ця посада пов’язана з великою відповідальністю.",
        ru: "Эта должность связана с большой ответственностью.",
        en: "This position comes with great responsibility.",
        uaTokens: ["Ця", "посада", "пов’язана", "з", "великою", "відповідальністю", "."],
        ruTokens: ["Эта", "должность", "связана", "с", "большой", "ответственностью", "."],
        enTokens: ["This", "position", "comes", "with", "great", "responsibility", "."],
        extraUaTokens: ["вакансія", "навичка", "графік"],
        extraRuTokens: ["вакансия", "навык", "график"],
        extraEnTokens: ["offer", "skill", "schedule"],
    },

    [phraseKey("zalety", "a2-4")]: {
        sk: "Jedną z zalet tej pracy jest elastyczny grafik.",
        ua: "Однією з переваг цієї роботи є гнучкий графік.",
        ru: "Одним из преимуществ этой работы является гибкий график.",
        en: "One of the advantages of this job is a flexible schedule.",
        uaTokens: ["Однією", "з", "переваг", "цієї", "роботи", "є", "гнучкий", "графік", "."],
        ruTokens: ["Одним", "из", "преимуществ", "этой", "работы", "является", "гибкий", "график", "."],
        enTokens: ["One", "of", "the", "advantages", "of", "this", "job", "is", "a", "flexible", "schedule", "."],
        extraUaTokens: ["вакансія", "посада", "триває"],
        extraRuTokens: ["вакансия", "должность", "длится"],
        extraEnTokens: ["offer", "position", "lasts"],
    },

    [phraseKey("okres próbny", "a2-4")]: {
        sk: "Okres próbny trwa trzy miesiące.",
        ua: "Випробувальний термін триває три місяці.",
        ru: "Испытательный срок длится три месяца.",
        en: "The probation period lasts three months.",
        uaTokens: ["Випробувальний", "термін", "триває", "три", "місяці", "."],
        ruTokens: ["Испытательный", "срок", "длится", "три", "месяца", "."],
        enTokens: ["The", "probation", "period", "lasts", "three", "months", "."],
        extraUaTokens: ["графік", "посада", "резюме"],
        extraRuTokens: ["график", "должность", "резюме"],
        extraEnTokens: ["schedule", "position", "CV"],
    },

    // =========================
    // LESSON 5 — Подорожі (ситуації)
    // =========================
    [phraseKey("rezerwacja", "a2-5")]: {
        sk: "Moja rezerwacja została potwierdzona.",
        ua: "Моє бронювання було підтверджене.",
        ru: "Моё бронирование было подтверждено.",
        en: "My reservation has been confirmed.",
        uaTokens: ["Моє", "бронювання", "було", "підтверджене", "."],
        ruTokens: ["Моё", "бронирование", "было", "подтверждено", "."],
        enTokens: ["My", "reservation", "has", "been", "confirmed", "."],
        extraUaTokens: ["проживання", "прибуття", "багаж"],
        extraRuTokens: ["жильё", "приезда", "багаж"],
        extraEnTokens: ["accommodation", "arrival", "luggage"],
    },

    [phraseKey("zakwaterowanie", "a2-5")]: {
        sk: "Szukamy taniego zakwaterowania blisko centrum.",
        ua: "Ми шукаємо недороге проживання близько до центру.",
        ru: "Мы ищем недорогое жильё недалеко от центра.",
        en: "We are looking for cheap accommodation close to the center.",
        uaTokens: ["Ми", "шукаємо", "недороге", "проживання", "близько", "до", "центру", "."],
        ruTokens: ["Мы", "ищем", "недорогое", "жильё", "недалеко", "от", "центра", "."],
        enTokens: ["We", "are", "looking", "for", "cheap", "accommodation", "close", "to", "the", "center", "."],
        extraUaTokens: ["бронювання", "прибуття", "квиток"],
        extraRuTokens: ["бронирование", "приезда", "билет"],
        extraEnTokens: ["reservation", "arrival", "ticket"],
    },

    [phraseKey("potwierdzić", "a2-5")]: {
        sk: "Proszę potwierdzić godzinę przyjazdu.",
        ua: "Будь ласка, підтвердьте час прибуття.",
        ru: "Пожалуйста, подтвердите время приезда.",
        en: "Please confirm the arrival time.",
        uaTokens: ["Будь", "ласка", ",", "підтвердьте", "час", "прибуття", "."],
        ruTokens: ["Пожалуйста", ",", "подтвердите", "время", "приезда", "."],
        enTokens: ["Please", "confirm", "the", "arrival", "time", "."],
        extraUaTokens: ["бронювання", "рейс", "місто"],
        extraRuTokens: ["бронирование", "рейс", "город"],
        extraEnTokens: ["reservation", "flight", "city"],
    },

    [phraseKey("anulować", "a2-5")]: {
        sk: "Musiałem anulować podróż w ostatniej chwili.",
        ua: "Мені довелося скасувати поїздку в останній момент.",
        ru: "Мне пришлось отменить поездку в последний момент.",
        en: "I had to cancel the trip at the last moment.",
        uaTokens: ["Мені", "довелося", "скасувати", "поїздку", "в", "останній", "момент", "."],
        ruTokens: ["Мне", "пришлось", "отменить", "поездку", "в", "последний", "момент", "."],
        enTokens: ["I", "had", "to", "cancel", "the", "trip", "at", "the", "last", "moment", "."],
        extraUaTokens: ["прибуття", "запізнення", "квиток"],
        extraRuTokens: ["приезда", "задержка", "билет"],
        extraEnTokens: ["arrival", "delay", "ticket"],
    },

    [phraseKey("spóźnienie", "a2-5")]: {
        sk: "Pociąg ma trzydzieści minut spóźnienia.",
        ua: "Поїзд має тридцять хвилин запізнення.",
        ru: "Поезд задерживается на тридцать минут.",
        en: "The train is thirty minutes late.",
        uaTokens: ["Поїзд", "має", "тридцять", "хвилин", "запізнення", "."],
        ruTokens: ["Поезд", "задерживается", "на", "тридцать", "минут", "."],
        enTokens: ["The", "train", "is", "thirty", "minutes", "late", "."],
        extraUaTokens: ["прибуття", "рейс", "багаж"],
        extraRuTokens: ["приезда", "рейс", "багаж"],
        extraEnTokens: ["arrival", "flight", "luggage"],
    },

    [phraseKey("przeniesienie", "a2-5")]: {
        sk: "Linia lotnicza zaoferowała przeniesienie na inny lot.",
        ua: "Авіакомпанія запропонувала переведення на інший рейс.",
        ru: "Авиакомпания предложила перенос на другой рейс.",
        en: "The airline offered a transfer to another flight.",
        uaTokens: ["Авіакомпанія", "запропонувала", "переведення", "на", "інший", "рейс", "."],
        ruTokens: ["Авиакомпания", "предложила", "перенос", "на", "другой", "рейс", "."],
        enTokens: ["The", "airline", "offered", "a", "transfer", "to", "another", "flight", "."],
        extraUaTokens: ["запізнення", "квиток", "багаж"],
        extraRuTokens: ["задержка", "билет", "багаж"],
        extraEnTokens: ["delay", "ticket", "luggage"],
    },

    [phraseKey("jednokierunkowy", "a2-5")]: {
        sk: "Chcę kupić bilet jednokierunkowy.",
        ua: "Я хочу купити квиток в один бік.",
        ru: "Я хочу купить билет в одну сторону.",
        en: "I want to buy a one-way ticket.",
        uaTokens: ["Я", "хочу", "купити", "квиток", "в", "один", "бік", "."],
        ruTokens: ["Я", "хочу", "купить", "билет", "в", "одну", "сторону", "."],
        enTokens: ["I", "want", "to", "buy", "a", "one-way", "ticket", "."],
        extraUaTokens: ["зворотний", "неділю", "рейс"],
        extraRuTokens: ["обратный", "воскресенье", "рейс"],
        extraEnTokens: ["return", "Sunday", "flight"],
    },

    [phraseKey("powrotny", "a2-5")]: {
        sk: "Potrzebuję biletu powrotnego na niedzielę.",
        ua: "Мені потрібен зворотний квиток на неділю.",
        ru: "Мне нужен обратный билет на воскресенье.",
        en: "I need a return ticket for Sunday.",
        uaTokens: ["Мені", "потрібен", "зворотний", "квиток", "на", "неділю", "."],
        ruTokens: ["Мне", "нужен", "обратный", "билет", "на", "воскресенье", "."],
        enTokens: ["I", "need", "a", "return", "ticket", "for", "Sunday", "."],
        extraUaTokens: ["один", "бік", "рейс"],
        extraRuTokens: ["одну", "сторону", "рейс"],
        extraEnTokens: ["one-way", "flight", "arrival"],
    },

    [phraseKey("ubezpieczenie podróżne", "a2-5")]: {
        sk: "Przed wyjazdem wykupiłem ubezpieczenie podróżne.",
        ua: "Перед поїздкою я оформив туристичну страховку.",
        ru: "Перед поездкой я оформил туристическую страховку.",
        en: "Before the trip I bought travel insurance.",
        uaTokens: ["Перед", "поїздкою", "я", "оформив", "туристичну", "страховку", "."],
        ruTokens: ["Перед", "поездкой", "я", "оформил", "туристическую", "страховку", "."],
        enTokens: ["Before", "the", "trip", "I", "bought", "travel", "insurance", "."],
        extraUaTokens: ["квиток", "рейс", "багаж"],
        extraRuTokens: ["билет", "рейс", "багаж"],
        extraEnTokens: ["ticket", "flight", "luggage"],
    },

    [phraseKey("bagaż", "a2-5")]: {
        sk: "Mój bagaż został wysłany do innego miasta.",
        ua: "Мій багаж відправили в інше місто.",
        ru: "Мой багаж отправили в другой город.",
        en: "My luggage was sent to another city.",
        uaTokens: ["Мій", "багаж", "відправили", "в", "інше", "місто", "."],
        ruTokens: ["Мой", "багаж", "отправили", "в", "другой", "город", "."],
        enTokens: ["My", "luggage", "was", "sent", "to", "another", "city", "."],
        extraUaTokens: ["рейс", "квиток", "прибуття"],
        extraRuTokens: ["рейс", "билет", "приезда"],
        extraEnTokens: ["flight", "ticket", "arrival"],
    },
};