import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A2_BUILD_UA_SENTENCES_3: BuildUaSentenceDict = {
    // =========================
    // LESSON 11 — Харчування та здорові звички
    // =========================
    [phraseKey("dieta", "a2-11")]: {
        sk: "Staram się trzymać zdrowej diety.",
        ua: "Я намагаюся дотримуватися здорового харчування.",
        ru: "Я стараюсь придерживаться здорового питания.",
        en: "I try to follow a healthy diet.",
        uaTokens: ["Я", "намагаюся", "дотримуватися", "здорового", "харчування", "."],
        ruTokens: ["Я", "стараюсь", "придерживаться", "здорового", "питания", "."],
        enTokens: ["I", "try", "to", "follow", "a", "healthy", "diet", "."],
        extraUaTokens: ["шкідливого", "спорту", "вчора"],
        extraRuTokens: ["вредного", "спорта", "вчера"],
        extraEnTokens: ["unhealthy", "sport", "yesterday"],
    },

    [phraseKey("zdrowe jedzenie", "a2-11")]: {
        sk: "Zdrowe jedzenie daje mi więcej energii.",
        ua: "Здорова їжа дає мені більше енергії.",
        ru: "Здоровая еда даёт мне больше энергии.",
        en: "Healthy food gives me more energy.",
        uaTokens: ["Здорова", "їжа", "дає", "мені", "більше", "енергії", "."],
        ruTokens: ["Здоровая", "еда", "даёт", "мне", "больше", "энергии", "."],
        enTokens: ["Healthy", "food", "gives", "me", "more", "energy", "."],
        extraUaTokens: ["менше", "сну", "сьогодні"],
        extraRuTokens: ["меньше", "сна", "сегодня"],
        extraEnTokens: ["less", "sleep", "today"],
    },

    [phraseKey("niezdrowe", "a2-11")]: {
        sk: "Fast food jest zazwyczaj niezdrowy.",
        ua: "Фастфуд зазвичай нездоровий.",
        ru: "Фастфуд обычно вредный.",
        en: "Fast food is usually unhealthy.",
        uaTokens: ["Фастфуд", "зазвичай", "нездоровий", "."],
        ruTokens: ["Фастфуд", "обычно", "вредный", "."],
        enTokens: ["Fast", "food", "is", "usually", "unhealthy", "."],
        extraUaTokens: ["корисний", "салат", "інколи"],
        extraRuTokens: ["полезный", "салат", "иногда"],
        extraEnTokens: ["healthy", "salad", "sometimes"],
    },

    [phraseKey("kalorie", "a2-11")]: {
        sk: "Nie liczę codziennie kalorii.",
        ua: "Я не рахую калорії щодня.",
        ru: "Я не считаю калории каждый день.",
        en: "I do not count calories every day.",
        uaTokens: ["Я", "не", "рахую", "калорії", "щодня", "."],
        ruTokens: ["Я", "не", "считаю", "калории", "каждый", "день", "."],
        enTokens: ["I", "do", "not", "count", "calories", "every", "day", "."],
        extraUaTokens: ["білок", "завжди", "уважно"],
        extraRuTokens: ["белок", "всегда", "внимательно"],
        extraEnTokens: ["protein", "always", "carefully"],
    },

    [phraseKey("witaminy", "a2-11")]: {
        sk: "Owoce i warzywa zawierają dużo witamin.",
        ua: "Фрукти й овочі містять багато вітамінів.",
        ru: "Фрукты и овощи содержат много витаминов.",
        en: "Fruit and vegetables contain a lot of vitamins.",
        uaTokens: ["Фрукти", "й", "овочі", "містять", "багато", "вітамінів", "."],
        ruTokens: ["Фрукты", "и", "овощи", "содержат", "много", "витаминов", "."],
        enTokens: ["Fruit", "and", "vegetables", "contain", "a", "lot", "of", "vitamins", "."],
        extraUaTokens: ["цукру", "мало", "взимку"],
        extraRuTokens: ["сахара", "мало", "зимой"],
        extraEnTokens: ["sugar", "little", "winter"],
    },

    [phraseKey("białko", "a2-11")]: {
        sk: "Po treningu staram się jeść więcej białka.",
        ua: "Після тренування я намагаюся їсти більше білка.",
        ru: "После тренировки я стараюсь есть больше белка.",
        en: "After training I try to eat more protein.",
        uaTokens: ["Після", "тренування", "я", "намагаюся", "їсти", "більше", "білка", "."],
        ruTokens: ["После", "тренировки", "я", "стараюсь", "есть", "больше", "белка", "."],
        enTokens: ["After", "training", "I", "try", "to", "eat", "more", "protein", "."],
        extraUaTokens: ["жиру", "менше", "вчора"],
        extraRuTokens: ["жира", "меньше", "вчера"],
        extraEnTokens: ["fat", "less", "yesterday"],
    },

    [phraseKey("tłuszcze", "a2-11")]: {
        sk: "Nie wszystkie tłuszcze są szkodliwe.",
        ua: "Не всі жири шкідливі.",
        ru: "Не все жиры вредны.",
        en: "Not all fats are harmful.",
        uaTokens: ["Не", "всі", "жири", "шкідливі", "."],
        ruTokens: ["Не", "все", "жиры", "вредны", "."],
        enTokens: ["Not", "all", "fats", "are", "harmful", "."],
        extraUaTokens: ["корисні", "цукор", "завжди"],
        extraRuTokens: ["полезны", "сахар", "всегда"],
        extraEnTokens: ["healthy", "sugar", "always"],
    },

    [phraseKey("cukier", "a2-11")]: {
        sk: "Chcę ograniczyć cukier w diecie.",
        ua: "Я хочу обмежити цукор у раціоні.",
        ru: "Я хочу ограничить сахар в рационе.",
        en: "I want to reduce sugar in my diet.",
        uaTokens: ["Я", "хочу", "обмежити", "цукор", "у", "раціоні", "."],
        ruTokens: ["Я", "хочу", "ограничить", "сахар", "в", "рационе", "."],
        enTokens: ["I", "want", "to", "reduce", "sugar", "in", "my", "diet", "."],
        extraUaTokens: ["сіль", "додати", "більше"],
        extraRuTokens: ["соль", "добавить", "больше"],
        extraEnTokens: ["salt", "add", "more"],
    },

    [phraseKey("sól", "a2-11")]: {
        sk: "Lekarz zalecił mi mniej soli.",
        ua: "Лікар порадив мені менше солі.",
        ru: "Врач посоветовал мне меньше соли.",
        en: "The doctor advised me to eat less salt.",
        uaTokens: ["Лікар", "порадив", "мені", "менше", "солі", "."],
        ruTokens: ["Врач", "посоветовал", "мне", "меньше", "соли", "."],
        enTokens: ["The", "doctor", "advised", "me", "to", "eat", "less", "salt", "."],
        extraUaTokens: ["цукру", "більше", "сьогодні"],
        extraRuTokens: ["сахара", "больше", "сегодня"],
        extraEnTokens: ["sugar", "more", "today"],
    },

    [phraseKey("nawodnienie", "a2-11")]: {
        sk: "Dobre nawodnienie jest bardzo ważne latem.",
        ua: "Хороша гідратація дуже важлива влітку.",
        ru: "Хорошая гидратация очень важна летом.",
        en: "Good hydration is very important in summer.",
        uaTokens: ["Хороша", "гідратація", "дуже", "важлива", "влітку", "."],
        ruTokens: ["Хорошая", "гидратация", "очень", "важна", "летом", "."],
        enTokens: ["Good", "hydration", "is", "very", "important", "in", "summer", "."],
        extraUaTokens: ["взимку", "непотрібна", "вода"],
        extraRuTokens: ["зимой", "неважна", "вода"],
        extraEnTokens: ["winter", "unimportant", "water"],
    },

    // =========================
    // LESSON 12 — Спорт і активність
    // =========================
    [phraseKey("trening", "a2-12")]: {
        sk: "Dzisiejszy trening był bardzo intensywny.",
        ua: "Сьогоднішнє тренування було дуже інтенсивним.",
        ru: "Сегодняшняя тренировка была очень интенсивной.",
        en: "Today's training was very intense.",
        uaTokens: ["Сьогоднішнє", "тренування", "було", "дуже", "інтенсивним", "."],
        ruTokens: ["Сегодняшняя", "тренировка", "была", "очень", "интенсивной", "."],
        enTokens: ["Today's", "training", "was", "very", "intense", "."],
        extraUaTokens: ["легким", "учора", "ранок"],
        extraRuTokens: ["лёгкой", "вчера", "утро"],
        extraEnTokens: ["easy", "yesterday", "morning"],
    },

    [phraseKey("ćwiczyć", "a2-12")]: {
        sk: "Staram się ćwiczyć trzy razy w tygodniu.",
        ua: "Я намагаюся тренуватися три рази на тиждень.",
        ru: "Я стараюсь тренироваться три раза в неделю.",
        en: "I try to exercise three times a week.",
        uaTokens: ["Я", "намагаюся", "тренуватися", "три", "рази", "на", "тиждень", "."],
        ruTokens: ["Я", "стараюсь", "тренироваться", "три", "раза", "в", "неделю", "."],
        enTokens: ["I", "try", "to", "exercise", "three", "times", "a", "week", "."],
        extraUaTokens: ["два", "місяць", "рідко"],
        extraRuTokens: ["два", "месяц", "редко"],
        extraEnTokens: ["two", "month", "rarely"],
    },

    [phraseKey("siłownia", "a2-12")]: {
        sk: "Po pracy idę na siłownię.",
        ua: "Після роботи я йду в спортзал.",
        ru: "После работы я иду в спортзал.",
        en: "After work I go to the gym.",
        uaTokens: ["Після", "роботи", "я", "йду", "в", "спортзал", "."],
        ruTokens: ["После", "работы", "я", "иду", "в", "спортзал", "."],
        enTokens: ["After", "work", "I", "go", "to", "the", "gym", "."],
        extraUaTokens: ["додому", "сьогодні", "вранці"],
        extraRuTokens: ["домой", "сегодня", "утром"],
        extraEnTokens: ["home", "today", "morning"],
    },

    [phraseKey("wytrwałość", "a2-12")]: {
        sk: "W bieganiu liczy się wytrwałość.",
        ua: "У бігу важлива витривалість.",
        ru: "В беге важна выносливость.",
        en: "Endurance matters in running.",
        uaTokens: ["У", "бігу", "важлива", "витривалість", "."],
        ruTokens: ["В", "беге", "важна", "выносливость", "."],
        enTokens: ["Endurance", "matters", "in", "running", "."],
        extraUaTokens: ["сила", "швидкість", "завтра"],
        extraRuTokens: ["сила", "скорость", "завтра"],
        extraEnTokens: ["strength", "speed", "tomorrow"],
    },

    [phraseKey("siła", "a2-12")]: {
        sk: "Ćwiczenia pomagają budować siłę.",
        ua: "Вправи допомагають розвивати силу.",
        ru: "Упражнения помогают развивать силу.",
        en: "Exercises help build strength.",
        uaTokens: ["Вправи", "допомагають", "розвивати", "силу", "."],
        ruTokens: ["Упражнения", "помогают", "развивать", "силу", "."],
        enTokens: ["Exercises", "help", "build", "strength", "."],
        extraUaTokens: ["витривалість", "повільно", "інколи"],
        extraRuTokens: ["выносливость", "медленно", "иногда"],
        extraEnTokens: ["endurance", "slowly", "sometimes"],
    },

    [phraseKey("tempo", "a2-12")]: {
        sk: "Na początku biegnij wolnym tempem.",
        ua: "На початку біжи повільним темпом.",
        ru: "Вначале беги в медленном темпе.",
        en: "At the beginning, run at a slow pace.",
        uaTokens: ["На", "початку", "біжи", "повільним", "темпом", "."],
        ruTokens: ["Вначале", "беги", "в", "медленном", "темпе", "."],
        enTokens: ["At", "the", "beginning", ",", "run", "at", "a", "slow", "pace", "."],
        extraUaTokens: ["швидким", "фініш", "потім"],
        extraRuTokens: ["быстрым", "финиш", "потом"],
        extraEnTokens: ["fast", "finish", "later"],
    },

    [phraseKey("rozgrzać się", "a2-12")]: {
        sk: "Przed treningiem trzeba się dobrze rozgrzać.",
        ua: "Перед тренуванням треба добре розігрітися.",
        ru: "Перед тренировкой нужно хорошо разогреться.",
        en: "You need to warm up well before training.",
        uaTokens: ["Перед", "тренуванням", "треба", "добре", "розігрітися", "."],
        ruTokens: ["Перед", "тренировкой", "нужно", "хорошо", "разогреться", "."],
        enTokens: ["You", "need", "to", "warm", "up", "well", "before", "training", "."],
        extraUaTokens: ["після", "охолонути", "швидко"],
        extraRuTokens: ["после", "остыть", "быстро"],
        extraEnTokens: ["after", "cool", "down"],
    },

    [phraseKey("rozciągnąć się", "a2-12")]: {
        sk: "Po ćwiczeniach warto się rozciągnąć.",
        ua: "Після вправ варто розтягнутися.",
        ru: "После упражнений стоит потянуться.",
        en: "It is worth stretching after exercise.",
        uaTokens: ["Після", "вправ", "варто", "розтягнутися", "."],
        ruTokens: ["После", "упражнений", "стоит", "потянуться", "."],
        enTokens: ["It", "is", "worth", "stretching", "after", "exercise", "."],
        extraUaTokens: ["до", "бігти", "одразу"],
        extraRuTokens: ["до", "бежать", "сразу"],
        extraEnTokens: ["before", "run", "immediately"],
    },

    [phraseKey("uraz", "a2-12")]: {
        sk: "Przez uraz nie mogę teraz trenować.",
        ua: "Через травму я зараз не можу тренуватися.",
        ru: "Из-за травмы я сейчас не могу тренироваться.",
        en: "Because of the injury I cannot train now.",
        uaTokens: ["Через", "травму", "я", "зараз", "не", "можу", "тренуватися", "."],
        ruTokens: ["Из-за", "травмы", "я", "сейчас", "не", "могу", "тренироваться", "."],
        enTokens: ["Because", "of", "the", "injury", "I", "cannot", "train", "now", "."],
        extraUaTokens: ["здоровий", "завтра", "біг"],
        extraRuTokens: ["здоров", "завтра", "бег"],
        extraEnTokens: ["healthy", "tomorrow", "run"],
    },

    [phraseKey("regeneracja", "a2-12")]: {
        sk: "Regeneracja jest tak samo ważna jak trening.",
        ua: "Відновлення так само важливе, як і тренування.",
        ru: "Восстановление так же важно, как и тренировка.",
        en: "Recovery is just as important as training.",
        uaTokens: ["Відновлення", "так", "само", "важливе", ",", "як", "і", "тренування", "."],
        ruTokens: ["Восстановление", "так", "же", "важно", ",", "как", "и", "тренировка", "."],
        enTokens: ["Recovery", "is", "just", "as", "important", "as", "training", "."],
        extraUaTokens: ["сон", "менш", "сьогодні"],
        extraRuTokens: ["сон", "менее", "сегодня"],
        extraEnTokens: ["sleep", "less", "today"],
    },

    // =========================
    // LESSON 13 — Відносини та спілкування
    // =========================
    [phraseKey("relacja", "a2-13")]: {
        sk: "Dobra relacja wymaga czasu.",
        ua: "Хороші стосунки потребують часу.",
        ru: "Хорошие отношения требуют времени.",
        en: "A good relationship requires time.",
        uaTokens: ["Хороші", "стосунки", "потребують", "часу", "."],
        ruTokens: ["Хорошие", "отношения", "требуют", "времени", "."],
        enTokens: ["A", "good", "relationship", "requires", "time", "."],
        extraUaTokens: ["терпіння", "грошей", "вчора"],
        extraRuTokens: ["терпения", "денег", "вчера"],
        extraEnTokens: ["patience", "money", "yesterday"],
    },

    [phraseKey("zaufanie", "a2-13")]: {
        sk: "Zaufanie buduje się powoli.",
        ua: "Довіра будується повільно.",
        ru: "Доверие строится медленно.",
        en: "Trust is built slowly.",
        uaTokens: ["Довіра", "будується", "повільно", "."],
        ruTokens: ["Доверие", "строится", "медленно", "."],
        enTokens: ["Trust", "is", "built", "slowly", "."],
        extraUaTokens: ["швидко", "руйнується", "інколи"],
        extraRuTokens: ["быстро", "разрушается", "иногда"],
        extraEnTokens: ["quickly", "breaks", "sometimes"],
    },

    [phraseKey("szacunek", "a2-13")]: {
        sk: "W każdej relacji ważny jest szacunek.",
        ua: "У кожних стосунках важлива повага.",
        ru: "В любых отношениях важно уважение.",
        en: "Respect is important in every relationship.",
        uaTokens: ["У", "кожних", "стосунках", "важлива", "повага", "."],
        ruTokens: ["В", "любых", "отношениях", "важно", "уважение", "."],
        enTokens: ["Respect", "is", "important", "in", "every", "relationship", "."],
        extraUaTokens: ["злість", "менше", "сьогодні"],
        extraRuTokens: ["злость", "меньше", "сегодня"],
        extraEnTokens: ["anger", "less", "today"],
    },

    [phraseKey("wsparcie", "a2-13")]: {
        sk: "W trudnych chwilach potrzebujemy wsparcia.",
        ua: "У важкі моменти нам потрібна підтримка.",
        ru: "В трудные моменты нам нужна поддержка.",
        en: "In difficult moments we need support.",
        uaTokens: ["У", "важкі", "моменти", "нам", "потрібна", "підтримка", "."],
        ruTokens: ["В", "трудные", "моменты", "нам", "нужна", "поддержка", "."],
        enTokens: ["In", "difficult", "moments", "we", "need", "support", "."],
        extraUaTokens: ["самотність", "радість", "вчора"],
        extraRuTokens: ["одиночество", "радость", "вчера"],
        extraEnTokens: ["loneliness", "joy", "yesterday"],
    },

    [phraseKey("kłócić się", "a2-13")]: {
        sk: "Nie lubię kłócić się o drobiazgi.",
        ua: "Я не люблю сваритися через дрібниці.",
        ru: "Я не люблю ссориться из-за мелочей.",
        en: "I do not like arguing about small things.",
        uaTokens: ["Я", "не", "люблю", "сваритися", "через", "дрібниці", "."],
        ruTokens: ["Я", "не", "люблю", "ссориться", "из-за", "мелочей", "."],
        enTokens: ["I", "do", "not", "like", "arguing", "about", "small", "things", "."],
        extraUaTokens: ["миритися", "часто", "друзі"],
        extraRuTokens: ["мириться", "часто", "друзья"],
        extraEnTokens: ["make", "peace", "friends"],
    },

    [phraseKey("pogodzić się", "a2-13")]: {
        sk: "Po rozmowie udało nam się pogodzić.",
        ua: "Після розмови нам вдалося помиритися.",
        ru: "После разговора нам удалось помириться.",
        en: "After the conversation we managed to make peace.",
        uaTokens: ["Після", "розмови", "нам", "вдалося", "помиритися", "."],
        ruTokens: ["После", "разговора", "нам", "удалось", "помириться", "."],
        enTokens: ["After", "the", "conversation", "we", "managed", "to", "make", "peace", "."],
        extraUaTokens: ["посваритися", "знову", "завтра"],
        extraRuTokens: ["поссориться", "снова", "завтра"],
        extraEnTokens: ["argue", "again", "tomorrow"],
    },

    [phraseKey("umowa", "a2-13")]: {
        sk: "Doszliśmy do wspólnej umowy.",
        ua: "Ми дійшли спільної домовленості.",
        ru: "Мы пришли к общему соглашению.",
        en: "We came to a mutual agreement.",
        uaTokens: ["Ми", "дійшли", "спільної", "домовленості", "."],
        ruTokens: ["Мы", "пришли", "к", "общему", "соглашению", "."],
        enTokens: ["We", "came", "to", "a", "mutual", "agreement", "."],
        extraUaTokens: ["суперечки", "без", "кінця"],
        extraRuTokens: ["споры", "без", "конца"],
        extraEnTokens: ["arguments", "without", "end"],
    },

    [phraseKey("kompromis", "a2-13")]: {
        sk: "Najlepszym rozwiązaniem był kompromis.",
        ua: "Найкращим рішенням був компроміс.",
        ru: "Лучшим решением был компромисс.",
        en: "The best solution was a compromise.",
        uaTokens: ["Найкращим", "рішенням", "був", "компроміс", "."],
        ruTokens: ["Лучшим", "решением", "был", "компромисс", "."],
        enTokens: ["The", "best", "solution", "was", "a", "compromise", "."],
        extraUaTokens: ["сварка", "гіршим", "учора"],
        extraRuTokens: ["ссора", "худшим", "вчера"],
        extraEnTokens: ["quarrel", "worse", "yesterday"],
    },

    [phraseKey("szczery", "a2-13")]: {
        sk: "Wolę szczere rozmowy.",
        ua: "Я віддаю перевагу щирим розмовам.",
        ru: "Я предпочитаю искренние разговоры.",
        en: "I prefer sincere conversations.",
        uaTokens: ["Я", "віддаю", "перевагу", "щирим", "розмовам", "."],
        ruTokens: ["Я", "предпочитаю", "искренние", "разговоры", "."],
        enTokens: ["I", "prefer", "sincere", "conversations", "."],
        extraUaTokens: ["брехливим", "словам", "ніколи"],
        extraRuTokens: ["лживые", "слова", "никогда"],
        extraEnTokens: ["false", "words", "never"],
    },

    [phraseKey("cierpliwość", "a2-13")]: {
        sk: "Do pracy z ludźmi potrzebna jest cierpliwość.",
        ua: "Для роботи з людьми потрібне терпіння.",
        ru: "Для работы с людьми нужно терпение.",
        en: "Patience is needed for working with people.",
        uaTokens: ["Для", "роботи", "з", "людьми", "потрібне", "терпіння", "."],
        ruTokens: ["Для", "работы", "с", "людьми", "нужно", "терпение", "."],
        enTokens: ["Patience", "is", "needed", "for", "working", "with", "people", "."],
        extraUaTokens: ["злість", "зовсім", "завтра"],
        extraRuTokens: ["злость", "совсем", "завтра"],
        extraEnTokens: ["anger", "at", "all"],
    },

    // =========================
    // LESSON 14 — Покупки онлайн і доставка
    // =========================
    [phraseKey("zamówienie", "a2-14")]: {
        sk: "Moje zamówienie zostało już wysłane.",
        ua: "Моє замовлення вже відправили.",
        ru: "Мой заказ уже отправили.",
        en: "My order has already been shipped.",
        uaTokens: ["Моє", "замовлення", "вже", "відправили", "."],
        ruTokens: ["Мой", "заказ", "уже", "отправили", "."],
        enTokens: ["My", "order", "has", "already", "been", "shipped", "."],
        extraUaTokens: ["скасували", "пізно", "вчора"],
        extraRuTokens: ["отменили", "поздно", "вчера"],
        extraEnTokens: ["cancelled", "late", "yesterday"],
    },

    [phraseKey("doręczenie", "a2-14")]: {
        sk: "Doręczenie paczki przewidziano na jutro.",
        ua: "Доставку посилки заплановано на завтра.",
        ru: "Доставка посылки запланирована на завтра.",
        en: "The package delivery is scheduled for tomorrow.",
        uaTokens: ["Доставку", "посилки", "заплановано", "на", "завтра", "."],
        ruTokens: ["Доставка", "посылки", "запланирована", "на", "завтра", "."],
        enTokens: ["The", "package", "delivery", "is", "scheduled", "for", "tomorrow", "."],
        extraUaTokens: ["сьогодні", "скасовано", "ранок"],
        extraRuTokens: ["сегодня", "отменена", "утро"],
        extraEnTokens: ["today", "cancelled", "morning"],
    },

    [phraseKey("paczka", "a2-14")]: {
        sk: "Paczka dotarła szybciej, niż się spodziewałem.",
        ua: "Посилка прибула швидше, ніж я очікував.",
        ru: "Посылка пришла быстрее, чем я ожидал.",
        en: "The package arrived faster than I expected.",
        uaTokens: ["Посилка", "прибула", "швидше", ",", "ніж", "я", "очікував", "."],
        ruTokens: ["Посылка", "пришла", "быстрее", ",", "чем", "я", "ожидал", "."],
        enTokens: ["The", "package", "arrived", "faster", "than", "I", "expected", "."],
        extraUaTokens: ["пізніше", "кур’єр", "сьогодні"],
        extraRuTokens: ["позже", "курьер", "сегодня"],
        extraEnTokens: ["later", "courier", "today"],
    },

    [phraseKey("kurier", "a2-14")]: {
        sk: "Kurier zadzwonił do mnie rano.",
        ua: "Кур’єр подзвонив мені вранці.",
        ru: "Курьер позвонил мне утром.",
        en: "The courier called me in the morning.",
        uaTokens: ["Кур’єр", "подзвонив", "мені", "вранці", "."],
        ruTokens: ["Курьер", "позвонил", "мне", "утром", "."],
        enTokens: ["The", "courier", "called", "me", "in", "the", "morning", "."],
        extraUaTokens: ["увечері", "посилка", "завтра"],
        extraRuTokens: ["вечером", "посылка", "завтра"],
        extraEnTokens: ["evening", "package", "tomorrow"],
    },

    [phraseKey("śledzenie przesyłki", "a2-14")]: {
        sk: "Dzięki śledzeniu przesyłki wiem, gdzie jest paczka.",
        ua: "Завдяки відстеженню посилки я знаю, де вона.",
        ru: "Благодаря отслеживанию посылки я знаю, где она.",
        en: "Thanks to parcel tracking, I know where the package is.",
        uaTokens: ["Завдяки", "відстеженню", "посилки", "я", "знаю", ",", "де", "вона", "."],
        ruTokens: ["Благодаря", "отслеживанию", "посылки", "я", "знаю", ",", "где", "она", "."],
        enTokens: ["Thanks", "to", "parcel", "tracking", ",", "I", "know", "where", "the", "package", "is", "."],
        extraUaTokens: ["загубилася", "кур’єр", "учора"],
        extraRuTokens: ["потерялась", "курьер", "вчера"],
        extraEnTokens: ["lost", "courier", "yesterday"],
    },

    [phraseKey("adres dostawy", "a2-14")]: {
        sk: "Muszę poprawić adres dostawy.",
        ua: "Мені треба виправити адресу доставки.",
        ru: "Мне нужно исправить адрес доставки.",
        en: "I need to correct the delivery address.",
        uaTokens: ["Мені", "треба", "виправити", "адресу", "доставки", "."],
        ruTokens: ["Мне", "нужно", "исправить", "адрес", "доставки", "."],
        enTokens: ["I", "need", "to", "correct", "the", "delivery", "address", "."],
        extraUaTokens: ["номер", "будинку", "пізніше"],
        extraRuTokens: ["номер", "дома", "позже"],
        extraEnTokens: ["house", "number", "later"],
    },

    [phraseKey("zwrot", "a2-14")]: {
        sk: "Chcę zrobić zwrot, bo rozmiar jest zły.",
        ua: "Я хочу зробити повернення, бо розмір не підходить.",
        ru: "Я хочу сделать возврат, потому что размер не подходит.",
        en: "I want to make a return because the size is wrong.",
        uaTokens: ["Я", "хочу", "зробити", "повернення", ",", "бо", "розмір", "не", "підходить", "."],
        ruTokens: ["Я", "хочу", "сделать", "возврат", ",", "потому", "что", "размер", "не", "подходит", "."],
        enTokens: ["I", "want", "to", "make", "a", "return", "because", "the", "size", "is", "wrong", "."],
        extraUaTokens: ["обмін", "колір", "сьогодні"],
        extraRuTokens: ["обмен", "цвет", "сегодня"],
        extraEnTokens: ["exchange", "color", "today"],
    },

    [phraseKey("wymiana", "a2-14")]: {
        sk: "Możliwa jest tylko wymiana, nie zwrot pieniędzy.",
        ua: "Можливий лише обмін, а не повернення грошей.",
        ru: "Возможен только обмен, а не возврат денег.",
        en: "Only an exchange is possible, not a refund.",
        uaTokens: ["Можливий", "лише", "обмін", ",", "а", "не", "повернення", "грошей", "."],
        ruTokens: ["Возможен", "только", "обмен", ",", "а", "не", "возврат", "денег", "."],
        enTokens: ["Only", "an", "exchange", "is", "possible", ",", "not", "a", "refund", "."],
        extraUaTokens: ["знижка", "розмір", "вчора"],
        extraRuTokens: ["скидка", "размер", "вчера"],
        extraEnTokens: ["discount", "size", "yesterday"],
    },

    [phraseKey("opłata pocztowa", "a2-14")]: {
        sk: "Opłata pocztowa była wyższa niż zwykle.",
        ua: "Вартість доставки була вищою, ніж зазвичай.",
        ru: "Стоимость доставки была выше, чем обычно.",
        en: "The shipping cost was higher than usual.",
        uaTokens: ["Вартість", "доставки", "була", "вищою", ",", "ніж", "зазвичай", "."],
        ruTokens: ["Стоимость", "доставки", "была", "выше", ",", "чем", "обычно", "."],
        enTokens: ["The", "shipping", "cost", "was", "higher", "than", "usual", "."],
        extraUaTokens: ["нижчою", "ціна", "сьогодні"],
        extraRuTokens: ["ниже", "цена", "сегодня"],
        extraEnTokens: ["lower", "price", "today"],
    },

    [phraseKey("płatność kartą", "a2-14")]: {
        sk: "Najczęściej wybieram płatność kartą.",
        ua: "Найчастіше я обираю оплату карткою.",
        ru: "Чаще всего я выбираю оплату картой.",
        en: "I most often choose card payment.",
        uaTokens: ["Найчастіше", "я", "обираю", "оплату", "карткою", "."],
        ruTokens: ["Чаще", "всего", "я", "выбираю", "оплату", "картой", "."],
        enTokens: ["I", "most", "often", "choose", "card", "payment", "."],
        extraUaTokens: ["готівкою", "магазин", "інколи"],
        extraRuTokens: ["наличными", "магазин", "иногда"],
        extraEnTokens: ["cash", "shop", "sometimes"],
    },

    // =========================
    // LESSON 15 — Технології (побутові ситуації)
    // =========================
    [phraseKey("ustawić", "a2-15")]: {
        sk: "Muszę ustawić nowy router.",
        ua: "Мені треба налаштувати новий роутер.",
        ru: "Мне нужно настроить новый роутер.",
        en: "I need to set up the new router.",
        uaTokens: ["Мені", "треба", "налаштувати", "новий", "роутер", "."],
        ruTokens: ["Мне", "нужно", "настроить", "новый", "роутер", "."],
        enTokens: ["I", "need", "to", "set", "up", "the", "new", "router", "."],
        extraUaTokens: ["старий", "телефон", "завтра"],
        extraRuTokens: ["старый", "телефон", "завтра"],
        extraEnTokens: ["old", "phone", "tomorrow"],
    },

    [phraseKey("aktualizacja", "a2-15")]: {
        sk: "Telefon potrzebuje aktualizacji systemu.",
        ua: "Телефон потребує оновлення системи.",
        ru: "Телефону нужно обновление системы.",
        en: "The phone needs a system update.",
        uaTokens: ["Телефон", "потребує", "оновлення", "системи", "."],
        ruTokens: ["Телефону", "нужно", "обновление", "системы", "."],
        enTokens: ["The", "phone", "needs", "a", "system", "update", "."],
        extraUaTokens: ["перезавантаження", "старої", "програми"],
        extraRuTokens: ["перезагрузка", "старой", "программы"],
        extraEnTokens: ["restart", "old", "program"],
    },

    [phraseKey("połączenie", "a2-15")]: {
        sk: "Połączenie z internetem jest niestabilne.",
        ua: "Підключення до інтернету нестабільне.",
        ru: "Подключение к интернету нестабильное.",
        en: "The internet connection is unstable.",
        uaTokens: ["Підключення", "до", "інтернету", "нестабільне", "."],
        ruTokens: ["Подключение", "к", "интернету", "нестабильное", "."],
        enTokens: ["The", "internet", "connection", "is", "unstable", "."],
        extraUaTokens: ["сигнал", "сильний", "сьогодні"],
        extraRuTokens: ["сигнал", "сильный", "сегодня"],
        extraEnTokens: ["signal", "strong", "today"],
    },

    [phraseKey("sygnał", "a2-15")]: {
        sk: "W tym pokoju sygnał jest bardzo słaby.",
        ua: "У цій кімнаті сигнал дуже слабкий.",
        ru: "В этой комнате сигнал очень слабый.",
        en: "The signal is very weak in this room.",
        uaTokens: ["У", "цій", "кімнаті", "сигнал", "дуже", "слабкий", "."],
        ruTokens: ["В", "этой", "комнате", "сигнал", "очень", "слабый", "."],
        enTokens: ["The", "signal", "is", "very", "weak", "in", "this", "room", "."],
        extraUaTokens: ["сильний", "кухня", "вчора"],
        extraRuTokens: ["сильный", "кухня", "вчера"],
        extraEnTokens: ["strong", "kitchen", "yesterday"],
    },

    [phraseKey("awaria", "a2-15")]: {
        sk: "Z powodu awarii nie było internetu przez dwie godziny.",
        ua: "Через збій не було інтернету дві години.",
        ru: "Из-за сбоя не было интернета два часа.",
        en: "Because of the outage, there was no internet for two hours.",
        uaTokens: ["Через", "збій", "не", "було", "інтернету", "дві", "години", "."],
        ruTokens: ["Из-за", "сбоя", "не", "было", "интернета", "два", "часа", "."],
        enTokens: ["Because", "of", "the", "outage", ",", "there", "was", "no", "internet", "for", "two", "hours", "."],
        extraUaTokens: ["світло", "цілий", "день"],
        extraRuTokens: ["свет", "целый", "день"],
        extraEnTokens: ["electricity", "whole", "day"],
    },

    [phraseKey("zaciąć się", "a2-15")]: {
        sk: "Komputer zaciął się podczas pracy.",
        ua: "Комп’ютер завис під час роботи.",
        ru: "Компьютер завис во время работы.",
        en: "The computer froze while I was working.",
        uaTokens: ["Комп’ютер", "завис", "під", "час", "роботи", "."],
        ruTokens: ["Компьютер", "завис", "во", "время", "работы", "."],
        enTokens: ["The", "computer", "froze", "while", "I", "was", "working", "."],
        extraUaTokens: ["телефон", "після", "оновлення"],
        extraRuTokens: ["телефон", "после", "обновления"],
        extraEnTokens: ["phone", "after", "update"],
    },

    [phraseKey("zrestartować", "a2-15")]: {
        sk: "Spróbuj zrestartować urządzenie.",
        ua: "Спробуй перезавантажити пристрій.",
        ru: "Попробуй перезагрузить устройство.",
        en: "Try restarting the device.",
        uaTokens: ["Спробуй", "перезавантажити", "пристрій", "."],
        ruTokens: ["Попробуй", "перезагрузить", "устройство", "."],
        enTokens: ["Try", "restarting", "the", "device", "."],
        extraUaTokens: ["вимкнути", "роутер", "спочатку"],
        extraRuTokens: ["выключить", "роутер", "сначала"],
        extraEnTokens: ["turn", "off", "router"],
    },

    [phraseKey("zainstalować", "a2-15")]: {
        sk: "Muszę zainstalować nową aplikację.",
        ua: "Мені треба встановити новий додаток.",
        ru: "Мне нужно установить новое приложение.",
        en: "I need to install a new app.",
        uaTokens: ["Мені", "треба", "встановити", "новий", "додаток", "."],
        ruTokens: ["Мне", "нужно", "установить", "новое", "приложение", "."],
        enTokens: ["I", "need", "to", "install", "a", "new", "app", "."],
        extraUaTokens: ["старий", "видалити", "потім"],
        extraRuTokens: ["старое", "удалить", "потом"],
        extraEnTokens: ["old", "delete", "later"],
    },

    [phraseKey("usunąć", "a2-15")]: {
        sk: "Chcę usunąć niepotrzebne pliki.",
        ua: "Я хочу видалити непотрібні файли.",
        ru: "Я хочу удалить ненужные файлы.",
        en: "I want to delete unnecessary files.",
        uaTokens: ["Я", "хочу", "видалити", "непотрібні", "файли", "."],
        ruTokens: ["Я", "хочу", "удалить", "ненужные", "файлы", "."],
        enTokens: ["I", "want", "to", "delete", "unnecessary", "files", "."],
        extraUaTokens: ["зберегти", "важливі", "документи"],
        extraRuTokens: ["сохранить", "важные", "документы"],
        extraEnTokens: ["save", "important", "documents"],
    },

    [phraseKey("odnowić", "a2-15")]: {
        sk: "Muszę odnowić hasło do konta.",
        ua: "Мені треба відновити пароль до акаунта.",
        ru: "Мне нужно восстановить пароль к аккаунту.",
        en: "I need to restore the account password.",
        uaTokens: ["Мені", "треба", "відновити", "пароль", "до", "акаунта", "."],
        ruTokens: ["Мне", "нужно", "восстановить", "пароль", "к", "аккаунту", "."],
        enTokens: ["I", "need", "to", "restore", "the", "account", "password", "."],
        extraUaTokens: ["логін", "забути", "вчора"],
        extraRuTokens: ["логин", "забыть", "вчера"],
        extraEnTokens: ["login", "forget", "yesterday"],
    },
};