import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const PL_A2_BUILD_UA_SENTENCES_4: BuildUaSentenceDict = {
    // =========================
    // LESSON 16 — Освіта і навчання
    // =========================
    [phraseKey("kurs", "a2-16")]: {
        sk: "Zapisałem się na kurs języka polskiego.",
        ua: "Я записався на курс польської мови.",
        ru: "Я записался на курс польского языка.",
        en: "I signed up for a Polish language course.",
        uaTokens: ["Я", "записався", "на", "курс", "польської", "мови", "."],
        ruTokens: ["Я", "записался", "на", "курс", "польского", "языка", "."],
        enTokens: ["I", "signed", "up", "for", "a", "Polish", "language", "course", "."],
        extraUaTokens: ["лекція", "нотатки", "сертифікат"],
        extraRuTokens: ["лекция", "заметки", "сертификат"],
        extraEnTokens: ["lecture", "notes", "certificate"],
    },

    [phraseKey("wykład", "a2-16")]: {
        sk: "Dzisiejszy wykład był bardzo ciekawy.",
        ua: "Сьогоднішня лекція була дуже цікавою.",
        ru: "Сегодняшняя лекция была очень интересной.",
        en: "Today's lecture was very interesting.",
        uaTokens: ["Сьогоднішня", "лекція", "була", "дуже", "цікавою", "."],
        ruTokens: ["Сегодняшняя", "лекция", "была", "очень", "интересной", "."],
        enTokens: ["Today's", "lecture", "was", "very", "interesting", "."],
        extraUaTokens: ["курс", "нотатки", "слова"],
        extraRuTokens: ["курс", "заметки", "слова"],
        extraEnTokens: ["course", "notes", "words"],
    },

    [phraseKey("notatki", "a2-16")]: {
        sk: "Zrobiłem dokładne notatki z lekcji.",
        ua: "Я зробив детальні нотатки з уроку.",
        ru: "Я сделал подробные заметки с урока.",
        en: "I made detailed notes from the lesson.",
        uaTokens: ["Я", "зробив", "детальні", "нотатки", "з", "уроку", "."],
        ruTokens: ["Я", "сделал", "подробные", "заметки", "с", "урока", "."],
        enTokens: ["I", "made", "detailed", "notes", "from", "the", "lesson", "."],
        extraUaTokens: ["лекція", "завдання", "сертифікат"],
        extraRuTokens: ["лекция", "задание", "сертификат"],
        extraEnTokens: ["lecture", "homework", "certificate"],
    },

    [phraseKey("praca domowa", "a2-16")]: {
        sk: "Muszę jeszcze skończyć pracę domową.",
        ua: "Мені ще треба закінчити домашнє завдання.",
        ru: "Мне ещё нужно закончить домашнее задание.",
        en: "I still need to finish my homework.",
        uaTokens: ["Мені", "ще", "треба", "закінчити", "домашнє", "завдання", "."],
        ruTokens: ["Мне", "ещё", "нужно", "закончить", "домашнее", "задание", "."],
        enTokens: ["I", "still", "need", "to", "finish", "my", "homework", "."],
        extraUaTokens: ["нотатки", "іспит", "слова"],
        extraRuTokens: ["заметки", "экзамен", "слова"],
        extraEnTokens: ["notes", "exam", "words"],
    },

    [phraseKey("egzamin", "a2-16")]: {
        sk: "Egzamin odbędzie się w przyszłym tygodniu.",
        ua: "Іспит відбудеться наступного тижня.",
        ru: "Экзамен состоится на следующей неделе.",
        en: "The exam will take place next week.",
        uaTokens: ["Іспит", "відбудеться", "наступного", "тижня", "."],
        ruTokens: ["Экзамен", "состоится", "на", "следующей", "неделе", "."],
        enTokens: ["The", "exam", "will", "take", "place", "next", "week", "."],
        extraUaTokens: ["курс", "сертифікат", "щодня"],
        extraRuTokens: ["курс", "сертификат", "каждый"],
        extraEnTokens: ["course", "certificate", "daily"],
    },

    [phraseKey("certyfikat", "a2-16")]: {
        sk: "Po kursie dostanę certyfikat.",
        ua: "Після курсу я отримаю сертифікат.",
        ru: "После курса я получу сертификат.",
        en: "I will get a certificate after the course.",
        uaTokens: ["Після", "курсу", "я", "отримаю", "сертифікат", "."],
        ruTokens: ["После", "курса", "я", "получу", "сертификат", "."],
        enTokens: ["I", "will", "get", "a", "certificate", "after", "the", "course", "."],
        extraUaTokens: ["лекція", "іспит", "уроку"],
        extraRuTokens: ["лекция", "экзамен", "урока"],
        extraEnTokens: ["lecture", "exam", "lesson"],
    },

    [phraseKey("umiejętność", "a2-16")]: {
        sk: "Pisanie to ważna umiejętność.",
        ua: "Писання — це важлива навичка.",
        ru: "Письмо — это важный навык.",
        en: "Writing is an important skill.",
        uaTokens: ["Писання", "—", "це", "важлива", "навичка", "."],
        ruTokens: ["Письмо", "—", "это", "важный", "навык", "."],
        enTokens: ["Writing", "is", "an", "important", "skill", "."],
        extraUaTokens: ["курс", "слова", "тексти"],
        extraRuTokens: ["курс", "слова", "тексты"],
        extraEnTokens: ["course", "words", "texts"],
    },

    [phraseKey("poprawić się", "a2-16")]: {
        sk: "Chcę poprawić się w mówieniu.",
        ua: "Я хочу покращитися в говорінні.",
        ru: "Я хочу улучшиться в разговорной речи.",
        en: "I want to improve my speaking.",
        uaTokens: ["Я", "хочу", "покращитися", "в", "говорінні", "."],
        ruTokens: ["Я", "хочу", "улучшиться", "в", "разговорной", "речи", "."],
        enTokens: ["I", "want", "to", "improve", "my", "speaking", "."],
        extraUaTokens: ["курс", "слова", "тексти"],
        extraRuTokens: ["курс", "слова", "тексты"],
        extraEnTokens: ["course", "words", "texts"],
    },

    [phraseKey("powtarzać", "a2-16")]: {
        sk: "Muszę powtarzać nowe słowa codziennie.",
        ua: "Мені треба повторювати нові слова щодня.",
        ru: "Мне нужно повторять новые слова каждый день.",
        en: "I need to repeat new words every day.",
        uaTokens: ["Мені", "треба", "повторювати", "нові", "слова", "щодня", "."],
        ruTokens: ["Мне", "нужно", "повторять", "новые", "слова", "каждый", "день", "."],
        enTokens: ["I", "need", "to", "repeat", "new", "words", "every", "day", "."],
        extraUaTokens: ["курс", "лекція", "сертифікат"],
        extraRuTokens: ["курс", "лекция", "сертификат"],
        extraEnTokens: ["course", "lecture", "certificate"],
    },

    [phraseKey("uczyć się na pamięć", "a2-16")]: {
        sk: "Nie lubię uczyć się tekstów na pamięć.",
        ua: "Я не люблю вчити тексти напам’ять.",
        ru: "Я не люблю учить тексты наизусть.",
        en: "I do not like learning texts by heart.",
        uaTokens: ["Я", "не", "люблю", "вчити", "тексти", "напам’ять", "."],
        ruTokens: ["Я", "не", "люблю", "учить", "тексты", "наизусть", "."],
        enTokens: ["I", "do", "not", "like", "learning", "texts", "by", "heart", "."],
        extraUaTokens: ["слова", "лекція", "щодня"],
        extraRuTokens: ["слова", "лекция", "каждый"],
        extraEnTokens: ["words", "lecture", "daily"],
    },

    // =========================
    // LESSON 17 — На роботі (комунікація)
    // =========================
    [phraseKey("podzielić zadania", "a2-17")]: {
        sk: "Musimy podzielić zadania między cały zespół.",
        ua: "Ми повинні розподілити завдання між усією командою.",
        ru: "Мы должны распределить задачи между всей командой.",
        en: "We need to distribute tasks among the whole team.",
        uaTokens: ["Ми", "повинні", "розподілити", "завдання", "між", "усією", "командою", "."],
        ruTokens: ["Мы", "должны", "распределить", "задачи", "между", "всей", "командой", "."],
        enTokens: ["We", "need", "to", "distribute", "tasks", "among", "the", "whole", "team", "."],
        extraUaTokens: ["клієнтами", "звіт", "проєкт"],
        extraRuTokens: ["клиентами", "отчёт", "проект"],
        extraEnTokens: ["clients", "report", "project"],
    },

    [phraseKey("współpracować", "a2-17")]: {
        sk: "Lubię współpracować z doświadczonymi ludźmi.",
        ua: "Я люблю співпрацювати з досвідченими людьми.",
        ru: "Я люблю сотрудничать с опытными людьми.",
        en: "I like cooperating with experienced people.",
        uaTokens: ["Я", "люблю", "співпрацювати", "з", "досвідченими", "людьми", "."],
        ruTokens: ["Я", "люблю", "сотрудничать", "с", "опытными", "людьми", "."],
        enTokens: ["I", "like", "cooperating", "with", "experienced", "people", "."],
        extraUaTokens: ["командою", "клієнтами", "рішення"],
        extraRuTokens: ["командой", "клиентами", "решение"],
        extraEnTokens: ["team", "clients", "solution"],
    },

    [phraseKey("priorytet", "a2-17")]: {
        sk: "To zadanie jest dziś naszym priorytetem.",
        ua: "Це завдання сьогодні є нашим пріоритетом.",
        ru: "Эта задача сегодня является нашим приоритетом.",
        en: "This task is our priority today.",
        uaTokens: ["Це", "завдання", "сьогодні", "є", "нашим", "пріоритетом", "."],
        ruTokens: ["Эта", "задача", "сегодня", "является", "нашим", "приоритетом", "."],
        enTokens: ["This", "task", "is", "our", "priority", "today", "."],
        extraUaTokens: ["командою", "документ", "звіт"],
        extraRuTokens: ["командой", "документ", "отчёт"],
        extraEnTokens: ["team", "document", "report"],
    },

    [phraseKey("odpowiadać", "a2-17")]: {
        sk: "Odpowiadam za kontakt z klientami.",
        ua: "Я відповідаю за контакт із клієнтами.",
        ru: "Я отвечаю за контакт с клиентами.",
        en: "I am responsible for contact with clients.",
        uaTokens: ["Я", "відповідаю", "за", "контакт", "із", "клієнтами", "."],
        ruTokens: ["Я", "отвечаю", "за", "контакт", "с", "клиентами", "."],
        enTokens: ["I", "am", "responsible", "for", "contact", "with", "clients", "."],
        extraUaTokens: ["командою", "звіт", "документ"],
        extraRuTokens: ["командой", "отчёт", "документ"],
        extraEnTokens: ["team", "report", "document"],
    },

    [phraseKey("przekazać", "a2-17")]: {
        sk: "Muszę przekazać raport kierownikowi.",
        ua: "Мені треба передати звіт керівнику.",
        ru: "Мне нужно передать отчёт руководителю.",
        en: "I need to hand the report to the manager.",
        uaTokens: ["Мені", "треба", "передати", "звіт", "керівнику", "."],
        ruTokens: ["Мне", "нужно", "передать", "отчёт", "руководителю", "."],
        enTokens: ["I", "need", "to", "hand", "the", "report", "to", "the", "manager", "."],
        extraUaTokens: ["клієнтами", "документ", "проєкт"],
        extraRuTokens: ["клиентами", "документ", "проект"],
        extraEnTokens: ["clients", "document", "project"],
    },

    [phraseKey("sprawdzić", "a2-17")]: {
        sk: "Proszę sprawdzić ten dokument jeszcze raz.",
        ua: "Будь ласка, перевір цей документ ще раз.",
        ru: "Пожалуйста, проверь этот документ ещё раз.",
        en: "Please check this document one more time.",
        uaTokens: ["Будь", "ласка", ",", "перевір", "цей", "документ", "ще", "раз", "."],
        ruTokens: ["Пожалуйста", ",", "проверь", "этот", "документ", "ещё", "раз", "."],
        enTokens: ["Please", "check", "this", "document", "one", "more", "time", "."],
        extraUaTokens: ["звіт", "керівнику", "клієнтів"],
        extraRuTokens: ["отчёт", "руководителю", "клиентов"],
        extraEnTokens: ["report", "manager", "clients"],
    },

    [phraseKey("organizować", "a2-17")]: {
        sk: "Nasza firma organizuje spotkanie dla klientów.",
        ua: "Наша компанія організовує зустріч для клієнтів.",
        ru: "Наша компания организует встречу для клиентов.",
        en: "Our company is organizing a meeting for clients.",
        uaTokens: ["Наша", "компанія", "організовує", "зустріч", "для", "клієнтів", "."],
        ruTokens: ["Наша", "компания", "организует", "встречу", "для", "клиентов", "."],
        enTokens: ["Our", "company", "is", "organizing", "a", "meeting", "for", "clients", "."],
        extraUaTokens: ["документ", "звіт", "рішення"],
        extraRuTokens: ["документ", "отчёт", "решение"],
        extraEnTokens: ["document", "report", "solution"],
    },

    [phraseKey("informacja zwrotna", "a2-17")]: {
        sk: "Dziękuję za szczerą informację zwrotną.",
        ua: "Дякую за щирий зворотний зв’язок.",
        ru: "Спасибо за искреннюю обратную связь.",
        en: "Thank you for the honest feedback.",
        uaTokens: ["Дякую", "за", "щирий", "зворотний", "зв’язок", "."],
        ruTokens: ["Спасибо", "за", "искреннюю", "обратную", "связь", "."],
        enTokens: ["Thank", "you", "for", "the", "honest", "feedback", "."],
        extraUaTokens: ["клієнтами", "рішення", "проєкт"],
        extraRuTokens: ["клиентами", "решение", "проект"],
        extraEnTokens: ["clients", "solution", "project"],
    },

    [phraseKey("zaproponować rozwiązanie", "a2-17")]: {
        sk: "Musimy szybko zaproponować rozwiązanie.",
        ua: "Ми повинні швидко запропонувати рішення.",
        ru: "Мы должны быстро предложить решение.",
        en: "We need to propose a solution quickly.",
        uaTokens: ["Ми", "повинні", "швидко", "запропонувати", "рішення", "."],
        ruTokens: ["Мы", "должны", "быстро", "предложить", "решение", "."],
        enTokens: ["We", "need", "to", "propose", "a", "solution", "quickly", "."],
        extraUaTokens: ["проєкт", "звіт", "клієнтів"],
        extraRuTokens: ["проект", "отчёт", "клиентов"],
        extraEnTokens: ["project", "report", "clients"],
    },

    [phraseKey("dokończyć", "a2-17")]: {
        sk: "Chcę dokończyć ten projekt dziś wieczorem.",
        ua: "Я хочу завершити цей проєкт сьогодні ввечері.",
        ru: "Я хочу закончить этот проект сегодня вечером.",
        en: "I want to complete this project this evening.",
        uaTokens: ["Я", "хочу", "завершити", "цей", "проєкт", "сьогодні", "ввечері", "."],
        ruTokens: ["Я", "хочу", "закончить", "этот", "проект", "сегодня", "вечером", "."],
        enTokens: ["I", "want", "to", "complete", "this", "project", "this", "evening", "."],
        extraUaTokens: ["рішення", "звіт", "документ"],
        extraRuTokens: ["решение", "отчёт", "документ"],
        extraEnTokens: ["solution", "report", "document"],
    },

    // =========================
    // LESSON 18 — Банківські справи
    // =========================
    [phraseKey("założyć konto", "a2-18")]: {
        sk: "Chcę założyć konto w nowym banku.",
        ua: "Я хочу відкрити рахунок у новому банку.",
        ru: "Я хочу открыть счёт в новом банке.",
        en: "I want to open an account in a new bank.",
        uaTokens: ["Я", "хочу", "відкрити", "рахунок", "у", "новому", "банку", "."],
        ruTokens: ["Я", "хочу", "открыть", "счёт", "в", "новом", "банке", "."],
        enTokens: ["I", "want", "to", "open", "an", "account", "in", "a", "new", "bank", "."],
        extraUaTokens: ["готівку", "переказати", "картка"],
        extraRuTokens: ["наличные", "перевести", "карта"],
        extraEnTokens: ["cash", "transfer", "card"],
    },

    [phraseKey("wybór", "a2-18")]: {
        sk: "Wczoraj zrobiłem wybór gotówki z bankomatu.",
        ua: "Учора я зняв готівку з банкомата.",
        ru: "Вчера я снял наличные в банкомате.",
        en: "Yesterday I made a cash withdrawal from the ATM.",
        uaTokens: ["Учора", "я", "зняв", "готівку", "з", "банкомата", "."],
        ruTokens: ["Вчера", "я", "снял", "наличные", "в", "банкомате", "."],
        enTokens: ["Yesterday", "I", "made", "a", "cash", "withdrawal", "from", "the", "ATM", "."],
        extraUaTokens: ["рахунок", "внести", "ліміт"],
        extraRuTokens: ["счёт", "внести", "лимит"],
        extraEnTokens: ["account", "deposit", "limit"],
    },

    [phraseKey("wkład", "a2-18")]: {
        sk: "Chcę zrobić wkład na konto.",
        ua: "Я хочу внести гроші на рахунок.",
        ru: "Я хочу внести деньги на счёт.",
        en: "I want to make a deposit into the account.",
        uaTokens: ["Я", "хочу", "внести", "гроші", "на", "рахунок", "."],
        ruTokens: ["Я", "хочу", "внести", "деньги", "на", "счёт", "."],
        enTokens: ["I", "want", "to", "make", "a", "deposit", "into", "the", "account", "."],
        extraUaTokens: ["готівку", "банкомата", "ліміт"],
        extraRuTokens: ["наличные", "банкомата", "лимит"],
        extraEnTokens: ["cash", "ATM", "limit"],
    },

    [phraseKey("przenieść", "a2-18")]: {
        sk: "Muszę przenieść pieniądze na inne konto.",
        ua: "Мені треба перевести гроші на інший рахунок.",
        ru: "Мне нужно перевести деньги на другой счёт.",
        en: "I need to transfer money to another account.",
        uaTokens: ["Мені", "треба", "перевести", "гроші", "на", "інший", "рахунок", "."],
        ruTokens: ["Мне", "нужно", "перевести", "деньги", "на", "другой", "счёт", "."],
        enTokens: ["I", "need", "to", "transfer", "money", "to", "another", "account", "."],
        extraUaTokens: ["внести", "картка", "комісію"],
        extraRuTokens: ["внести", "карта", "комиссию"],
        extraEnTokens: ["deposit", "card", "fee"],
    },

    [phraseKey("karta płatnicza", "a2-18")]: {
        sk: "Moja karta płatnicza nie działa.",
        ua: "Моя платіжна картка не працює.",
        ru: "Моя платёжная карта не работает.",
        en: "My payment card is not working.",
        uaTokens: ["Моя", "платіжна", "картка", "не", "працює", "."],
        ruTokens: ["Моя", "платёжная", "карта", "не", "работает", "."],
        enTokens: ["My", "payment", "card", "is", "not", "working", "."],
        extraUaTokens: ["пін-код", "рахунок", "комісію"],
        extraRuTokens: ["пин-код", "счёт", "комиссию"],
        extraEnTokens: ["PIN", "account", "fee"],
    },

    [phraseKey("kod PIN", "a2-18")]: {
        sk: "Zapomniałem kodu PIN.",
        ua: "Я забув пін-код.",
        ru: "Я забыл пин-код.",
        en: "I forgot the PIN code.",
        uaTokens: ["Я", "забув", "пін-код", "."],
        ruTokens: ["Я", "забыл", "пин-код", "."],
        enTokens: ["I", "forgot", "the", "PIN", "code", "."],
        extraUaTokens: ["картка", "рахунок", "ліміт"],
        extraRuTokens: ["карта", "счёт", "лимит"],
        extraEnTokens: ["card", "account", "limit"],
    },

    [phraseKey("limit", "a2-18")]: {
        sk: "Mam ustawiony dzienny limit wypłat.",
        ua: "У мене встановлений денний ліміт на зняття.",
        ru: "У меня установлен дневной лимит на снятие.",
        en: "I have a daily withdrawal limit set.",
        uaTokens: ["У", "мене", "встановлений", "денний", "ліміт", "на", "зняття", "."],
        ruTokens: ["У", "меня", "установлен", "дневной", "лимит", "на", "снятие", "."],
        enTokens: ["I", "have", "a", "daily", "withdrawal", "limit", "set", "."],
        extraUaTokens: ["пін-код", "картка", "виписка"],
        extraRuTokens: ["пин-код", "карта", "выписка"],
        extraEnTokens: ["PIN", "card", "statement"],
    },

    [phraseKey("opłata", "a2-18")]: {
        sk: "Bank pobrał dodatkową opłatę.",
        ua: "Банк зняв додаткову комісію.",
        ru: "Банк снял дополнительную комиссию.",
        en: "The bank charged an additional fee.",
        uaTokens: ["Банк", "зняв", "додаткову", "комісію", "."],
        ruTokens: ["Банк", "снял", "дополнительную", "комиссию", "."],
        enTokens: ["The", "bank", "charged", "an", "additional", "fee", "."],
        extraUaTokens: ["рахунок", "картка", "виписка"],
        extraRuTokens: ["счёт", "карта", "выписка"],
        extraEnTokens: ["account", "card", "statement"],
    },

    [phraseKey("wyciąg", "a2-18")]: {
        sk: "Potrzebuję wyciągu z konta za ostatni miesiąc.",
        ua: "Мені потрібна виписка з рахунку за останній місяць.",
        ru: "Мне нужна выписка по счёту за последний месяц.",
        en: "I need a bank statement for the last month.",
        uaTokens: ["Мені", "потрібна", "виписка", "з", "рахунку", "за", "останній", "місяць", "."],
        ruTokens: ["Мне", "нужна", "выписка", "по", "счёту", "за", "последний", "месяц", "."],
        enTokens: ["I", "need", "a", "bank", "statement", "for", "the", "last", "month", "."],
        extraUaTokens: ["комісію", "картка", "гаманець"],
        extraRuTokens: ["комиссию", "карта", "кошелёк"],
        extraEnTokens: ["fee", "card", "wallet"],
    },

    [phraseKey("zablokować kartę", "a2-18")]: {
        sk: "Musiałem zablokować kartę po zgubieniu portfela.",
        ua: "Мені довелося заблокувати картку після втрати гаманця.",
        ru: "Мне пришлось заблокировать карту после потери кошелька.",
        en: "I had to block the card after losing my wallet.",
        uaTokens: ["Мені", "довелося", "заблокувати", "картку", "після", "втрати", "гаманця", "."],
        ruTokens: ["Мне", "пришлось", "заблокировать", "карту", "после", "потери", "кошелька", "."],
        enTokens: ["I", "had", "to", "block", "the", "card", "after", "losing", "my", "wallet", "."],
        extraUaTokens: ["пін-код", "рахунок", "комісію"],
        extraRuTokens: ["пин-код", "счёт", "комиссию"],
        extraEnTokens: ["PIN", "account", "fee"],
    },

    // =========================
    // LESSON 19 — Державні документи
    // =========================
    [phraseKey("zezwolenie", "a2-19")]: {
        sk: "Muszę złożyć wniosek o zezwolenie.",
        ua: "Мені треба подати заяву на дозвіл.",
        ru: "Мне нужно подать заявление на разрешение.",
        en: "I need to submit an application for a permit.",
        uaTokens: ["Мені", "треба", "подати", "заяву", "на", "дозвіл", "."],
        ruTokens: ["Мне", "нужно", "подать", "заявление", "на", "разрешение", "."],
        enTokens: ["I", "need", "to", "submit", "an", "application", "for", "a", "permit", "."],
        extraUaTokens: ["рішення", "реєстрація", "підпис"],
        extraRuTokens: ["решение", "регистрация", "подпись"],
        extraEnTokens: ["decision", "registration", "signature"],
    },

    [phraseKey("pobyt", "a2-19")]: {
        sk: "Czekam na decyzję w sprawie pobytu.",
        ua: "Я чекаю на рішення щодо дозволу на проживання.",
        ru: "Я жду решения по поводу вида на жительство.",
        en: "I am waiting for the decision about my residence permit.",
        uaTokens: ["Я", "чекаю", "на", "рішення", "щодо", "дозволу", "на", "проживання", "."],
        ruTokens: ["Я", "жду", "решения", "по", "поводу", "вида", "на", "жительство", "."],
        enTokens: ["I", "am", "waiting", "for", "the", "decision", "about", "my", "residence", "permit", "."],
        extraUaTokens: ["заяву", "реєстрація", "формальності"],
        extraRuTokens: ["заявление", "регистрация", "формальности"],
        extraEnTokens: ["application", "registration", "formalities"],
    },

    [phraseKey("dowód osobisty", "a2-19")]: {
        sk: "Proszę pokazać dowód osobisty.",
        ua: "Будь ласка, покажіть ID-картку.",
        ru: "Пожалуйста, покажите удостоверение личности.",
        en: "Please show your ID card.",
        uaTokens: ["Будь", "ласка", ",", "покажіть", "ID-картку", "."],
        ruTokens: ["Пожалуйста", ",", "покажите", "удостоверение", "личности", "."],
        enTokens: ["Please", "show", "your", "ID", "card", "."],
        extraUaTokens: ["реєстрація", "підпис", "фотографію"],
        extraRuTokens: ["регистрация", "подпись", "фотографию"],
        extraEnTokens: ["registration", "signature", "photograph"],
    },

    [phraseKey("rejestracja", "a2-19")]: {
        sk: "Rejestracja przebiegła bez problemów.",
        ua: "Реєстрація пройшла без проблем.",
        ru: "Регистрация прошла без проблем.",
        en: "The registration went without problems.",
        uaTokens: ["Реєстрація", "пройшла", "без", "проблем", "."],
        ruTokens: ["Регистрация", "прошла", "без", "проблем", "."],
        enTokens: ["The", "registration", "went", "without", "problems", "."],
        extraUaTokens: ["підпис", "формальності", "PESEL"],
        extraRuTokens: ["подпись", "формальности", "PESEL"],
        extraEnTokens: ["signature", "formalities", "PESEL"],
    },

    [phraseKey("podpis", "a2-19")]: {
        sk: "Tutaj potrzebny jest twój podpis.",
        ua: "Тут потрібен твій підпис.",
        ru: "Здесь нужна твоя подпись.",
        en: "Your signature is needed here.",
        uaTokens: ["Тут", "потрібен", "твій", "підпис", "."],
        ruTokens: ["Здесь", "нужна", "твоя", "подпись", "."],
        enTokens: ["Your", "signature", "is", "needed", "here", "."],
        extraUaTokens: ["реєстрація", "фотографію", "дані"],
        extraRuTokens: ["регистрация", "фотографию", "данные"],
        extraEnTokens: ["registration", "photograph", "data"],
    },

    [phraseKey("fotografia", "a2-19")]: {
        sk: "Do wniosku trzeba dołączyć fotografię.",
        ua: "До заяви треба додати фотографію.",
        ru: "К заявлению нужно приложить фотографию.",
        en: "A photograph needs to be attached to the application.",
        uaTokens: ["До", "заяви", "треба", "додати", "фотографію", "."],
        ruTokens: ["К", "заявлению", "нужно", "приложить", "фотографию", "."],
        enTokens: ["A", "photograph", "needs", "to", "be", "attached", "to", "the", "application", "."],
        extraUaTokens: ["підпис", "PESEL", "дані"],
        extraRuTokens: ["подпись", "PESEL", "данные"],
        extraEnTokens: ["signature", "PESEL", "data"],
    },

    [phraseKey("zweryfikować", "a2-19")]: {
        sk: "Urząd musi zweryfikować wszystkie dane.",
        ua: "Установа повинна перевірити всі дані.",
        ru: "Учреждение должно проверить все данные.",
        en: "The office needs to verify all the data.",
        uaTokens: ["Установа", "повинна", "перевірити", "всі", "дані", "."],
        ruTokens: ["Учреждение", "должно", "проверить", "все", "данные", "."],
        enTokens: ["The", "office", "needs", "to", "verify", "all", "the", "data", "."],
        extraUaTokens: ["реєстрація", "підпис", "формальності"],
        extraRuTokens: ["регистрация", "подпись", "формальности"],
        extraEnTokens: ["registration", "signature", "formalities"],
    },

    [phraseKey("termin spotkania", "a2-19")]: {
        sk: "Termin spotkania został przesunięty.",
        ua: "Дату прийому було перенесено.",
        ru: "Дата приёма была перенесена.",
        en: "The appointment date has been rescheduled.",
        uaTokens: ["Дату", "прийому", "було", "перенесено", "."],
        ruTokens: ["Дата", "приёма", "была", "перенесена", "."],
        enTokens: ["The", "appointment", "date", "has", "been", "rescheduled", "."],
        extraUaTokens: ["реєстрація", "підпис", "PESEL"],
        extraRuTokens: ["регистрация", "подпись", "PESEL"],
        extraEnTokens: ["registration", "signature", "PESEL"],
    },

    [phraseKey("załatwić", "a2-19")]: {
        sk: "Chcę dziś załatwić wszystkie formalności.",
        ua: "Я хочу сьогодні оформити всі формальності.",
        ru: "Я хочу сегодня оформить все формальности.",
        en: "I want to handle all the formalities today.",
        uaTokens: ["Я", "хочу", "сьогодні", "оформити", "всі", "формальності", "."],
        ruTokens: ["Я", "хочу", "сегодня", "оформить", "все", "формальности", "."],
        enTokens: ["I", "want", "to", "handle", "all", "the", "formalities", "today", "."],
        extraUaTokens: ["реєстрація", "підпис", "дані"],
        extraRuTokens: ["регистрация", "подпись", "данные"],
        extraEnTokens: ["registration", "signature", "data"],
    },

    [phraseKey("numer PESEL", "a2-19")]: {
        sk: "Muszę podać numer PESEL w formularzu.",
        ua: "Мені треба вказати ідентифікаційний номер у формі.",
        ru: "Мне нужно указать идентификационный номер в форме.",
        en: "I need to provide the personal identification number in the form.",
        uaTokens: ["Мені", "треба", "вказати", "ідентифікаційний", "номер", "у", "формі", "."],
        ruTokens: ["Мне", "нужно", "указать", "идентификационный", "номер", "в", "форме", "."],
        enTokens: ["I", "need", "to", "provide", "the", "personal", "identification", "number", "in", "the", "form", "."],
        extraUaTokens: ["підпис", "дані", "заяви"],
        extraRuTokens: ["подпись", "данные", "заявлению"],
        extraEnTokens: ["signature", "data", "application"],
    },

    // =========================
    // LESSON 20 — Повторення A2 (11–19)
    // =========================
    [phraseKey("dieta", "a2-20")]: {
        sk: "Dobra dieta pomaga mi lepiej się czuć.",
        ua: "Хороше харчування допомагає мені краще почуватися.",
        ru: "Хорошее питание помогает мне лучше себя чувствовать.",
        en: "A good diet helps me feel better.",
        uaTokens: ["Хороше", "харчування", "допомагає", "мені", "краще", "почуватися", "."],
        ruTokens: ["Хорошее", "питание", "помогает", "мне", "лучше", "себя", "чувствовать", "."],
        enTokens: ["A", "good", "diet", "helps", "me", "feel", "better", "."],
        extraUaTokens: ["тренування", "компроміс", "доставка"],
        extraRuTokens: ["тренировка", "компромисс", "доставка"],
        extraEnTokens: ["training", "compromise", "delivery"],
    },

    [phraseKey("trening", "a2-20")]: {
        sk: "Regularny trening daje dobre efekty.",
        ua: "Регулярне тренування дає хороші результати.",
        ru: "Регулярная тренировка даёт хорошие результаты.",
        en: "Regular training gives good results.",
        uaTokens: ["Регулярне", "тренування", "дає", "хороші", "результати", "."],
        ruTokens: ["Регулярная", "тренировка", "даёт", "хорошие", "результаты", "."],
        enTokens: ["Regular", "training", "gives", "good", "results", "."],
        extraUaTokens: ["харчування", "компроміс", "оновлення"],
        extraRuTokens: ["питание", "компромисс", "обновление"],
        extraEnTokens: ["diet", "compromise", "update"],
    },

    [phraseKey("kompromis", "a2-20")]: {
        sk: "Czasami kompromis jest najlepszym wyjściem.",
        ua: "Іноді компроміс — це найкращий вихід.",
        ru: "Иногда компромисс — это лучший выход.",
        en: "Sometimes compromise is the best solution.",
        uaTokens: ["Іноді", "компроміс", "—", "це", "найкращий", "вихід", "."],
        ruTokens: ["Иногда", "компромисс", "—", "это", "лучший", "выход", "."],
        enTokens: ["Sometimes", "compromise", "is", "the", "best", "solution", "."],
        extraUaTokens: ["тренування", "лекції", "оновлення"],
        extraRuTokens: ["тренировка", "лекции", "обновление"],
        extraEnTokens: ["training", "lecture", "update"],
    },

    [phraseKey("doręczenie", "a2-20")]: {
        sk: "Doręczenie paczki opóźniło się o jeden dzień.",
        ua: "Доставка посилки затрималася на один день.",
        ru: "Доставка посылки задержалась на один день.",
        en: "The package delivery was delayed by one day.",
        uaTokens: ["Доставка", "посилки", "затрималася", "на", "один", "день", "."],
        ruTokens: ["Доставка", "посылки", "задержалась", "на", "один", "день", "."],
        enTokens: ["The", "package", "delivery", "was", "delayed", "by", "one", "day", "."],
        extraUaTokens: ["оновлення", "лекції", "виписку"],
        extraRuTokens: ["обновление", "лекции", "выписку"],
        extraEnTokens: ["update", "lecture", "statement"],
    },

    [phraseKey("aktualizacja", "a2-20")]: {
        sk: "Po aktualizacji telefon działa szybciej.",
        ua: "Після оновлення телефон працює швидше.",
        ru: "После обновления телефон работает быстрее.",
        en: "After the update the phone works faster.",
        uaTokens: ["Після", "оновлення", "телефон", "працює", "швидше", "."],
        ruTokens: ["После", "обновления", "телефон", "работает", "быстрее", "."],
        enTokens: ["After", "the", "update", "the", "phone", "works", "faster", "."],
        extraUaTokens: ["доставка", "компроміс", "виписку"],
        extraRuTokens: ["доставка", "компромисс", "выписку"],
        extraEnTokens: ["delivery", "compromise", "statement"],
    },

    [phraseKey("wykład", "a2-20")]: {
        sk: "Na wykładzie dowiedziałem się wielu nowych rzeczy.",
        ua: "На лекції я дізнався багато нового.",
        ru: "На лекции я узнал много нового.",
        en: "I learned many new things during the lecture.",
        uaTokens: ["На", "лекції", "я", "дізнався", "багато", "нового", "."],
        ruTokens: ["На", "лекции", "я", "узнал", "много", "нового", "."],
        enTokens: ["I", "learned", "many", "new", "things", "during", "the", "lecture", "."],
        extraUaTokens: ["зворотний", "зв’язок", "оновлення"],
        extraRuTokens: ["обратная", "связь", "обновление"],
        extraEnTokens: ["feedback", "update", "delivery"],
    },

    [phraseKey("informacja zwrotna", "a2-20")]: {
        sk: "Twoja informacja zwrotna bardzo mi pomogła.",
        ua: "Твій зворотний зв’язок дуже мені допоміг.",
        ru: "Твоя обратная связь очень мне помогла.",
        en: "Your feedback helped me a lot.",
        uaTokens: ["Твій", "зворотний", "зв’язок", "дуже", "мені", "допоміг", "."],
        ruTokens: ["Твоя", "обратная", "связь", "очень", "мне", "помогла", "."],
        enTokens: ["Your", "feedback", "helped", "me", "a", "lot", "."],
        extraUaTokens: ["лекції", "оновлення", "дозволу"],
        extraRuTokens: ["лекции", "обновление", "разрешения"],
        extraEnTokens: ["lecture", "update", "permit"],
    },

    [phraseKey("wyciąg", "a2-20")]: {
        sk: "Pobrałem wyciąg z konta w aplikacji.",
        ua: "Я завантажив виписку з рахунку в додатку.",
        ru: "Я скачал выписку по счёту в приложении.",
        en: "I downloaded the bank statement in the app.",
        uaTokens: ["Я", "завантажив", "виписку", "з", "рахунку", "в", "додатку", "."],
        ruTokens: ["Я", "скачал", "выписку", "по", "счёту", "в", "приложении", "."],
        enTokens: ["I", "downloaded", "the", "bank", "statement", "in", "the", "app", "."],
        extraUaTokens: ["оновлення", "доставка", "дозволу"],
        extraRuTokens: ["обновление", "доставка", "разрешения"],
        extraEnTokens: ["update", "delivery", "permit"],
    },

    [phraseKey("zezwolenie", "a2-20")]: {
        sk: "Bez zezwolenia nie można rozpocząć pracy.",
        ua: "Без дозволу не можна почати роботу.",
        ru: "Без разрешения нельзя начать работу.",
        en: "Without a permit you cannot start working.",
        uaTokens: ["Без", "дозволу", "не", "можна", "почати", "роботу", "."],
        ruTokens: ["Без", "разрешения", "нельзя", "начать", "работу", "."],
        enTokens: ["Without", "a", "permit", "you", "cannot", "start", "working", "."],
        extraUaTokens: ["формальності", "виписку", "зв’язок"],
        extraRuTokens: ["формальности", "выписку", "связь"],
        extraEnTokens: ["formalities", "statement", "feedback"],
    },

    [phraseKey("załatwić", "a2-20")]: {
        sk: "Muszę załatwić jeszcze kilka spraw.",
        ua: "Мені треба владнати ще кілька справ.",
        ru: "Мне нужно уладить ещё несколько дел.",
        en: "I still need to handle a few more things.",
        uaTokens: ["Мені", "треба", "владнати", "ще", "кілька", "справ", "."],
        ruTokens: ["Мне", "нужно", "уладить", "ещё", "несколько", "дел", "."],
        enTokens: ["I", "still", "need", "to", "handle", "a", "few", "more", "things", "."],
        extraUaTokens: ["дозволу", "оновлення", "компроміс"],
        extraRuTokens: ["разрешения", "обновление", "компромисс"],
        extraEnTokens: ["permit", "update", "compromise"],
    },
};