import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_A1_BUILD_UA_SENTENCES_3: BuildUaSentenceDict = {
  // =========================
  // LESSON A1-11 — Опис людини
  // =========================
  [phraseKey("vysoký", "a1-11")]: {
    sk: "Můj bratr je velmi vysoký.",
    ua: "Мій брат дуже високий.",
    ru: "Мой брат очень высокий.",
    en: "My brother is very tall.",
    uaTokens: ["Мій", "брат", "дуже", "високий", "."],
    ruTokens: ["Мой", "брат", "очень", "высокий", "."],
    enTokens: ["My", "brother", "is", "very", "tall", "."],
    extraUaTokens: ["низький", "сьогодні", "він"],
    extraRuTokens: ["низкий", "сегодня", "он"],
    extraEnTokens: ["short", "today", "he"],
  },

  [phraseKey("nízký", "a1-11")]: {
    sk: "Ten chlapec je spíš nízký.",
    ua: "Той хлопець доволі низький.",
    ru: "Этот парень довольно низкий.",
    en: "That boy is rather short.",
    uaTokens: ["Той", "хлопець", "доволі", "низький", "."],
    ruTokens: ["Этот", "парень", "довольно", "низкий", "."],
    enTokens: ["That", "boy", "is", "rather", "short", "."],
    extraUaTokens: ["високий", "дуже", "він"],
    extraRuTokens: ["высокий", "очень", "он"],
    extraEnTokens: ["tall", "very", "he"],
  },

  [phraseKey("mladý", "a1-11")]: {
    sk: "Ještě je velmi mladý.",
    ua: "Він ще дуже молодий.",
    ru: "Он ещё очень молодой.",
    en: "He is still very young.",
    uaTokens: ["Він", "ще", "дуже", "молодий", "."],
    ruTokens: ["Он", "ещё", "очень", "молодой", "."],
    enTokens: ["He", "is", "still", "very", "young", "."],
    extraUaTokens: ["старий", "вже", "зовсім"],
    extraRuTokens: ["старый", "уже", "совсем"],
    extraEnTokens: ["old", "already", "quite"],
  },

  [phraseKey("starý", "a1-11")]: {
    sk: "To je starý dům.",
    ua: "Це старий будинок.",
    ru: "Это старый дом.",
    en: "This is an old house.",
    uaTokens: ["Це", "старий", "будинок", "."],
    ruTokens: ["Это", "старый", "дом", "."],
    enTokens: ["This", "is", "an", "old", "house", "."],
    extraUaTokens: ["новий", "великий", "мій"],
    extraRuTokens: ["новый", "большой", "мой"],
    extraEnTokens: ["new", "big", "my"],
  },

  [phraseKey("silný", "a1-11")]: {
    sk: "Ten muž je opravdu silný.",
    ua: "Той чоловік справді сильний.",
    ru: "Этот мужчина действительно сильный.",
    en: "That man is really strong.",
    uaTokens: ["Той", "чоловік", "справді", "сильний", "."],
    ruTokens: ["Этот", "мужчина", "действительно", "сильный", "."],
    enTokens: ["That", "man", "is", "really", "strong", "."],
    extraUaTokens: ["слабкий", "дуже", "сьогодні"],
    extraRuTokens: ["слабый", "очень", "сегодня"],
    extraEnTokens: ["weak", "very", "today"],
  },

  [phraseKey("slabý", "a1-11")]: {
    sk: "Po nemoci jsem byl slabý.",
    ua: "Після хвороби я був слабкий.",
    ru: "После болезни я был слабый.",
    en: "After the illness I was weak.",
    uaTokens: ["Після", "хвороби", "я", "був", "слабкий", "."],
    ruTokens: ["После", "болезни", "я", "был", "слабый", "."],
    enTokens: ["After", "the", "illness", "I", "was", "weak", "."],
    extraUaTokens: ["сильний", "дуже", "знову"],
    extraRuTokens: ["сильный", "очень", "снова"],
    extraEnTokens: ["strong", "very", "again"],
  },

  [phraseKey("hezký", "a1-11")]: {
    sk: "Má hezký úsměv.",
    ua: "У неї гарна усмішка.",
    ru: "У неё красивая улыбка.",
    en: "She has a nice smile.",
    uaTokens: ["У", "неї", "гарна", "усмішка", "."],
    ruTokens: ["У", "неё", "красивая", "улыбка", "."],
    enTokens: ["She", "has", "a", "nice", "smile", "."],
    extraUaTokens: ["очі", "дуже", "сьогодні"],
    extraRuTokens: ["глаза", "очень", "сегодня"],
    extraEnTokens: ["eyes", "very", "today"],
  },

  [phraseKey("ošklivý", "a1-11")]: {
    sk: "To slovo zní ošklivě.",
    ua: "Це слово звучить негарно.",
    ru: "Это слово звучит некрасиво.",
    en: "That word sounds ugly.",
    uaTokens: ["Це", "слово", "звучить", "негарно", "."],
    ruTokens: ["Это", "слово", "звучит", "некрасиво", "."],
    enTokens: ["That", "word", "sounds", "ugly", "."],
    extraUaTokens: ["гарно", "дуже", "інколи"],
    extraRuTokens: ["красиво", "очень", "иногда"],
    extraEnTokens: ["nicely", "very", "sometimes"],
  },

  [phraseKey("milý", "a1-11")]: {
    sk: "Byla na mě velmi milá.",
    ua: "Вона була зі мною дуже милою.",
    ru: "Она была ко мне очень мила.",
    en: "She was very kind to me.",
    uaTokens: ["Вона", "була", "зі", "мною", "дуже", "милою", "."],
    ruTokens: ["Она", "была", "ко", "мне", "очень", "мила", "."],
    enTokens: ["She", "was", "very", "kind", "to", "me", "."],
    extraUaTokens: ["добра", "сьогодні", "завжди"],
    extraRuTokens: ["добрая", "сегодня", "всегда"],
    extraEnTokens: ["kind", "today", "always"],
  },

  [phraseKey("vážný", "a1-11")]: {
    sk: "Dnes vypadá dost vážně.",
    ua: "Сьогодні він виглядає досить серйозно.",
    ru: "Сегодня он выглядит довольно серьёзно.",
    en: "Today he looks quite serious.",
    uaTokens: ["Сьогодні", "він", "виглядає", "досить", "серйозно", "."],
    ruTokens: ["Сегодня", "он", "выглядит", "довольно", "серьёзно", "."],
    enTokens: ["Today", "he", "looks", "quite", "serious", "."],
    extraUaTokens: ["весело", "дуже", "зараз"],
    extraRuTokens: ["весело", "очень", "сейчас"],
    extraEnTokens: ["cheerful", "very", "now"],
  },

  // =========================
  // LESSON A1-12 — Час
  // =========================
  [phraseKey("ráno", "a1-12")]: {
    sk: "Ráno piju vždy kávu.",
    ua: "Вранці я завжди п’ю каву.",
    ru: "Утром я всегда пью кофе.",
    en: "In the morning I always drink coffee.",
    uaTokens: ["Вранці", "я", "завжди", "п’ю", "каву", "."],
    ruTokens: ["Утром", "я", "всегда", "пью", "кофе", "."],
    enTokens: ["In", "the", "morning", "I", "always", "drink", "coffee", "."],
    extraUaTokens: ["чай", "увечері", "інколи"],
    extraRuTokens: ["чай", "вечером", "иногда"],
    extraEnTokens: ["tea", "evening", "sometimes"],
  },

  [phraseKey("oběd", "a1-12")]: {
    sk: "Na oběd máme polévku.",
    ua: "На обід у нас суп.",
    ru: "На обед у нас суп.",
    en: "We have soup for lunch.",
    uaTokens: ["На", "обід", "у", "нас", "суп", "."],
    ruTokens: ["На", "обед", "у", "нас", "суп", "."],
    enTokens: ["We", "have", "soup", "for", "lunch", "."],
    extraUaTokens: ["вечерю", "каша", "сьогодні"],
    extraRuTokens: ["ужин", "каша", "сегодня"],
    extraEnTokens: ["dinner", "porridge", "today"],
  },

  [phraseKey("večer", "a1-12")]: {
    sk: "Večer chodím na procházku.",
    ua: "Увечері я ходжу на прогулянку.",
    ru: "Вечером я хожу на прогулку.",
    en: "In the evening I go for a walk.",
    uaTokens: ["Увечері", "я", "ходжу", "на", "прогулянку", "."],
    ruTokens: ["Вечером", "я", "хожу", "на", "прогулку", "."],
    enTokens: ["In", "the", "evening", "I", "go", "for", "a", "walk", "."],
    extraUaTokens: ["вранці", "роботу", "часто"],
    extraRuTokens: ["утром", "работу", "часто"],
    extraEnTokens: ["morning", "work", "often"],
  },

  [phraseKey("půlnoc", "a1-12")]: {
    sk: "Domů jsme přišli až o půlnoci.",
    ua: "Додому ми прийшли аж опівночі.",
    ru: "Домой мы пришли только в полночь.",
    en: "We came home only at midnight.",
    uaTokens: ["Додому", "ми", "прийшли", "аж", "опівночі", "."],
    ruTokens: ["Домой", "мы", "пришли", "только", "в", "полночь", "."],
    enTokens: ["We", "came", "home", "only", "at", "midnight", "."],
    extraUaTokens: ["вранці", "пізно", "дуже"],
    extraRuTokens: ["утром", "поздно", "очень"],
    extraEnTokens: ["morning", "late", "very"],
  },

  [phraseKey("dnes", "a1-12")]: {
    sk: "Dnes nemám moc času.",
    ua: "Сьогодні в мене не дуже багато часу.",
    ru: "Сегодня у меня не очень много времени.",
    en: "Today I do not have much time.",
    uaTokens: ["Сьогодні", "в", "мене", "не", "дуже", "багато", "часу", "."],
    ruTokens: ["Сегодня", "у", "меня", "не", "очень", "много", "времени", "."],
    enTokens: ["Today", "I", "do", "not", "have", "much", "time", "."],
    extraUaTokens: ["завтра", "грошей", "роботи"],
    extraRuTokens: ["завтра", "денег", "работы"],
    extraEnTokens: ["tomorrow", "money", "work"],
  },

  [phraseKey("zítra", "a1-12")]: {
    sk: "Zítra jedeme do Prahy.",
    ua: "Завтра ми їдемо до Праги.",
    ru: "Завтра мы едем в Прагу.",
    en: "Tomorrow we are going to Prague.",
    uaTokens: ["Завтра", "ми", "їдемо", "до", "Праги", "."],
    ruTokens: ["Завтра", "мы", "едем", "в", "Прагу", "."],
    enTokens: ["Tomorrow", "we", "are", "going", "to", "Prague", "."],
    extraUaTokens: ["Брно", "сьогодні", "разом"],
    extraRuTokens: ["Брно", "сегодня", "вместе"],
    extraEnTokens: ["Brno", "today", "together"],
  },

  [phraseKey("pozítří", "a1-12")]: {
    sk: "Pozítří mám volno.",
    ua: "Післязавтра в мене вихідний.",
    ru: "Послезавтра у меня выходной.",
    en: "The day after tomorrow I have a day off.",
    uaTokens: ["Післязавтра", "в", "мене", "вихідний", "."],
    ruTokens: ["Послезавтра", "у", "меня", "выходной", "."],
    enTokens: ["The", "day", "after", "tomorrow", "I", "have", "a", "day", "off", "."],
    extraUaTokens: ["завтра", "робота", "буде"],
    extraRuTokens: ["завтра", "работа", "будет"],
    extraEnTokens: ["tomorrow", "work", "later"],
  },

  [phraseKey("vždy", "a1-12")]: {
    sk: "Vždy přijdu včas.",
    ua: "Я завжди приходжу вчасно.",
    ru: "Я всегда прихожу вовремя.",
    en: "I always arrive on time.",
    uaTokens: ["Я", "завжди", "приходжу", "вчасно", "."],
    ruTokens: ["Я", "всегда", "прихожу", "вовремя", "."],
    enTokens: ["I", "always", "arrive", "on", "time", "."],
    extraUaTokens: ["пізно", "інколи", "додому"],
    extraRuTokens: ["поздно", "иногда", "домой"],
    extraEnTokens: ["late", "sometimes", "home"],
  },

  [phraseKey("často", "a1-12")]: {
    sk: "Často myslím na rodinu.",
    ua: "Я часто думаю про родину.",
    ru: "Я часто думаю о семье.",
    en: "I often think about my family.",
    uaTokens: ["Я", "часто", "думаю", "про", "родину", "."],
    ruTokens: ["Я", "часто", "думаю", "о", "семье", "."],
    enTokens: ["I", "often", "think", "about", "my", "family", "."],
    extraUaTokens: ["роботу", "рідко", "сьогодні"],
    extraRuTokens: ["работе", "редко", "сегодня"],
    extraEnTokens: ["work", "rarely", "today"],
  },

  [phraseKey("někdy", "a1-12")]: {
    sk: "Někdy pracuji i v sobotu.",
    ua: "Інколи я працюю і в суботу.",
    ru: "Иногда я работаю и в субботу.",
    en: "Sometimes I work on Saturday too.",
    uaTokens: ["Інколи", "я", "працюю", "і", "в", "суботу", "."],
    ruTokens: ["Иногда", "я", "работаю", "и", "в", "субботу", "."],
    enTokens: ["Sometimes", "I", "work", "on", "Saturday", "too", "."],
    extraUaTokens: ["неділю", "часто", "теж"],
    extraRuTokens: ["воскресенье", "часто", "тоже"],
    extraEnTokens: ["Sunday", "often", "too"],
  },

  // =========================
  // LESSON A1-13 — Дім
  // =========================
  [phraseKey("chodba", "a1-13")]: {
    sk: "Na chodbě je tma.",
    ua: "У коридорі темно.",
    ru: "В коридоре темно.",
    en: "It is dark in the hallway.",
    uaTokens: ["У", "коридорі", "темно", "."],
    ruTokens: ["В", "коридоре", "темно", "."],
    enTokens: ["It", "is", "dark", "in", "the", "hallway", "."],
    extraUaTokens: ["світло", "вже", "сьогодні"],
    extraRuTokens: ["светло", "уже", "сегодня"],
    extraEnTokens: ["light", "already", "today"],
  },

  [phraseKey("balkon", "a1-13")]: {
    sk: "V létě sedíme na balkoně.",
    ua: "Влітку ми сидимо на балконі.",
    ru: "Летом мы сидим на балконе.",
    en: "In summer we sit on the balcony.",
    uaTokens: ["Влітку", "ми", "сидимо", "на", "балконі", "."],
    ruTokens: ["Летом", "мы", "сидим", "на", "балконе", "."],
    enTokens: ["In", "summer", "we", "sit", "on", "the", "balcony", "."],
    extraUaTokens: ["взимку", "разом", "часто"],
    extraRuTokens: ["зимой", "вместе", "часто"],
    extraEnTokens: ["winter", "together", "often"],
  },

  [phraseKey("sklep", "a1-13")]: {
    sk: "Kolo mám ve sklepě.",
    ua: "Велосипед у мене в підвалі.",
    ru: "Велосипед у меня в подвале.",
    en: "My bicycle is in the basement.",
    uaTokens: ["Велосипед", "у", "мене", "в", "підвалі", "."],
    ruTokens: ["Велосипед", "у", "меня", "в", "подвале", "."],
    enTokens: ["My", "bicycle", "is", "in", "the", "basement", "."],
    extraUaTokens: ["гаражі", "машина", "стояла"],
    extraRuTokens: ["гараже", "машина", "стояла"],
    extraEnTokens: ["garage", "car", "stood"],
  },

  [phraseKey("výtah", "a1-13")]: {
    sk: "Výtah dnes nefunguje.",
    ua: "Ліфт сьогодні не працює.",
    ru: "Лифт сегодня не работает.",
    en: "The lift is not working today.",
    uaTokens: ["Ліфт", "сьогодні", "не", "працює", "."],
    ruTokens: ["Лифт", "сегодня", "не", "работает", "."],
    enTokens: ["The", "lift", "is", "not", "working", "today", "."],
    extraUaTokens: ["сходи", "вже", "там"],
    extraRuTokens: ["лестница", "уже", "там"],
    extraEnTokens: ["stairs", "already", "there"],
  },

  [phraseKey("schody", "a1-13")]: {
    sk: "Musíme jít po schodech.",
    ua: "Нам треба йти по сходах.",
    ru: "Нам нужно идти по лестнице.",
    en: "We need to take the stairs.",
    uaTokens: ["Нам", "треба", "йти", "по", "сходах", "."],
    ruTokens: ["Нам", "нужно", "идти", "по", "лестнице", "."],
    enTokens: ["We", "need", "to", "take", "the", "stairs", "."],
    extraUaTokens: ["ліфтом", "вгору", "сьогодні"],
    extraRuTokens: ["лифтом", "наверх", "сегодня"],
    extraEnTokens: ["lift", "upstairs", "today"],
  },

  [phraseKey("zahrada", "a1-13")]: {
    sk: "Za domem máme malou zahradu.",
    ua: "За будинком у нас маленький сад.",
    ru: "За домом у нас маленький сад.",
    en: "We have a small garden behind the house.",
    uaTokens: ["За", "будинком", "у", "нас", "маленький", "сад", "."],
    ruTokens: ["За", "домом", "у", "нас", "маленький", "сад", "."],
    enTokens: ["We", "have", "a", "small", "garden", "behind", "the", "house", "."],
    extraUaTokens: ["великий", "город", "гарний"],
    extraRuTokens: ["большой", "огород", "красивый"],
    extraEnTokens: ["big", "vegetable-garden", "beautiful"],
  },

  [phraseKey("garáž", "a1-13")]: {
    sk: "Auto stojí v garáži.",
    ua: "Авто стоїть у гаражі.",
    ru: "Машина стоит в гараже.",
    en: "The car is in the garage.",
    uaTokens: ["Авто", "стоїть", "у", "гаражі", "."],
    ruTokens: ["Машина", "стоит", "в", "гараже", "."],
    enTokens: ["The", "car", "is", "in", "the", "garage", "."],
    extraUaTokens: ["вулиці", "велосипед", "зараз"],
    extraRuTokens: ["улице", "велосипед", "сейчас"],
    extraEnTokens: ["street", "bicycle", "now"],
  },

  [phraseKey("zeď", "a1-13")]: {
    sk: "Na zdi visí obraz.",
    ua: "На стіні висить картина.",
    ru: "На стене висит картина.",
    en: "A picture is hanging on the wall.",
    uaTokens: ["На", "стіні", "висить", "картина", "."],
    ruTokens: ["На", "стене", "висит", "картина", "."],
    enTokens: ["A", "picture", "is", "hanging", "on", "the", "wall", "."],
    extraUaTokens: ["дзеркало", "гарна", "там"],
    extraRuTokens: ["зеркало", "красивая", "там"],
    extraEnTokens: ["mirror", "beautiful", "there"],
  },

  [phraseKey("strop", "a1-13")]: {
    sk: "Strop je docela vysoký.",
    ua: "Стеля досить висока.",
    ru: "Потолок довольно высокий.",
    en: "The ceiling is quite high.",
    uaTokens: ["Стеля", "досить", "висока", "."],
    ruTokens: ["Потолок", "довольно", "высокий", "."],
    enTokens: ["The", "ceiling", "is", "quite", "high", "."],
    extraUaTokens: ["низька", "тут", "дуже"],
    extraRuTokens: ["низкий", "здесь", "очень"],
    extraEnTokens: ["low", "here", "very"],
  },

  [phraseKey("podlaha", "a1-13")]: {
    sk: "Podlaha je právě umytá.",
    ua: "Підлога щойно вимита.",
    ru: "Пол только что вымыт.",
    en: "The floor has just been washed.",
    uaTokens: ["Підлога", "щойно", "вимита", "."],
    ruTokens: ["Пол", "только", "что", "вымыт", "."],
    enTokens: ["The", "floor", "has", "just", "been", "washed", "."],
    extraUaTokens: ["брудна", "сьогодні", "ще"],
    extraRuTokens: ["грязный", "сегодня", "ещё"],
    extraEnTokens: ["dirty", "today", "still"],
  },

  // =========================
  // LESSON A1-14 — Покупки
  // =========================
  [phraseKey("prodávat", "a1-14")]: {
    sk: "Tady prodávají čerstvé pečivo.",
    ua: "Тут продають свіжу випічку.",
    ru: "Здесь продают свежую выпечку.",
    en: "They sell fresh pastries here.",
    uaTokens: ["Тут", "продають", "свіжу", "випічку", "."],
    ruTokens: ["Здесь", "продают", "свежую", "выпечку", "."],
    enTokens: ["They", "sell", "fresh", "pastries", "here", "."],
    extraUaTokens: ["хліб", "дешево", "сьогодні"],
    extraRuTokens: ["хлеб", "дёшево", "сегодня"],
    extraEnTokens: ["bread", "cheaply", "today"],
  },

  [phraseKey("kupovat", "a1-14")]: {
    sk: "Chci koupovat kvalitní věci.",
    ua: "Я хочу купувати якісні речі.",
    ru: "Я хочу покупать качественные вещи.",
    en: "I want to buy quality things.",
    uaTokens: ["Я", "хочу", "купувати", "якісні", "речі", "."],
    ruTokens: ["Я", "хочу", "покупать", "качественные", "вещи", "."],
    enTokens: ["I", "want", "to", "buy", "quality", "things", "."],
    extraUaTokens: ["дешеві", "товари", "завжди"],
    extraRuTokens: ["дешёвые", "товары", "всегда"],
    extraEnTokens: ["cheap", "goods", "always"],
  },

  [phraseKey("levný", "a1-14")]: {
    sk: "Ten obchod je opravdu levný.",
    ua: "Той магазин справді дешевий.",
    ru: "Этот магазин действительно дешёвый.",
    en: "That shop is really cheap.",
    uaTokens: ["Той", "магазин", "справді", "дешевий", "."],
    ruTokens: ["Этот", "магазин", "действительно", "дешёвый", "."],
    enTokens: ["That", "shop", "is", "really", "cheap", "."],
    extraUaTokens: ["дорогий", "дуже", "сьогодні"],
    extraRuTokens: ["дорогой", "очень", "сегодня"],
    extraEnTokens: ["expensive", "very", "today"],
  },

  [phraseKey("drahý", "a1-14")]: {
    sk: "Tohle je pro mě moc drahé.",
    ua: "Це для мене надто дорого.",
    ru: "Это для меня слишком дорого.",
    en: "This is too expensive for me.",
    uaTokens: ["Це", "для", "мене", "надто", "дорого", "."],
    ruTokens: ["Это", "для", "меня", "слишком", "дорого", "."],
    enTokens: ["This", "is", "too", "expensive", "for", "me", "."],
    extraUaTokens: ["дешево", "сьогодні", "дуже"],
    extraRuTokens: ["дёшево", "сегодня", "очень"],
    extraEnTokens: ["cheap", "today", "very"],
  },

  [phraseKey("kvalita", "a1-14")]: {
    sk: "Kvalita je pro mě důležitá.",
    ua: "Якість для мене важлива.",
    ru: "Качество для меня важно.",
    en: "Quality is important to me.",
    uaTokens: ["Якість", "для", "мене", "важлива", "."],
    ruTokens: ["Качество", "для", "меня", "важно", "."],
    enTokens: ["Quality", "is", "important", "to", "me", "."],
    extraUaTokens: ["ціна", "теж", "дуже"],
    extraRuTokens: ["цена", "тоже", "очень"],
    extraEnTokens: ["price", "too", "very"],
  },

  [phraseKey("značka", "a1-14")]: {
    sk: "Ta značka je hodně známá.",
    ua: "Цей бренд дуже відомий.",
    ru: "Этот бренд очень известный.",
    en: "That brand is very well known.",
    uaTokens: ["Цей", "бренд", "дуже", "відомий", "."],
    ruTokens: ["Этот", "бренд", "очень", "известный", "."],
    enTokens: ["That", "brand", "is", "very", "well", "known", "."],
    extraUaTokens: ["новий", "товар", "сьогодні"],
    extraRuTokens: ["новый", "товар", "сегодня"],
    extraEnTokens: ["new", "product", "today"],
  },

  [phraseKey("akce", "a1-14")]: {
    sk: "Dnes je na to velká akce.",
    ua: "Сьогодні на це велика акція.",
    ru: "Сегодня на это большая акция.",
    en: "Today there is a big sale on it.",
    uaTokens: ["Сьогодні", "на", "це", "велика", "акція", "."],
    ruTokens: ["Сегодня", "на", "это", "большая", "акция", "."],
    enTokens: ["Today", "there", "is", "a", "big", "sale", "on", "it", "."],
    extraUaTokens: ["знижка", "маленька", "є"],
    extraRuTokens: ["скидка", "маленькая", "есть"],
    extraEnTokens: ["discount", "small", "is"],
  },

  [phraseKey("zlevněný", "a1-14")]: {
    sk: "Ten výrobek je teď zlevněný.",
    ua: "Цей товар зараз зі знижкою.",
    ru: "Этот товар сейчас со скидкой.",
    en: "This product is discounted now.",
    uaTokens: ["Цей", "товар", "зараз", "зі", "знижкою", "."],
    ruTokens: ["Этот", "товар", "сейчас", "со", "скидкой", "."],
    enTokens: ["This", "product", "is", "discounted", "now", "."],
    extraUaTokens: ["дорогий", "новий", "дуже"],
    extraRuTokens: ["дорогой", "новый", "очень"],
    extraEnTokens: ["expensive", "new", "very"],
  },

  [phraseKey("pokladna", "a1-14")]: {
    sk: "U pokladny čeká hodně lidí.",
    ua: "Біля каси чекає багато людей.",
    ru: "У кассы ждёт много людей.",
    en: "Many people are waiting at the checkout.",
    uaTokens: ["Біля", "каси", "чекає", "багато", "людей", "."],
    ruTokens: ["У", "кассы", "ждёт", "много", "людей", "."],
    enTokens: ["Many", "people", "are", "waiting", "at", "the", "checkout", "."],
    extraUaTokens: ["черга", "довга", "сьогодні"],
    extraRuTokens: ["очередь", "длинная", "сегодня"],
    extraEnTokens: ["queue", "long", "today"],
  },

  [phraseKey("účtenka", "a1-14")]: {
    sk: "Nezapomeňte si účtenku.",
    ua: "Не забудьте свій чек.",
    ru: "Не забудьте свой чек.",
    en: "Do not forget your receipt.",
    uaTokens: ["Не", "забудьте", "свій", "чек", "."],
    ruTokens: ["Не", "забудьте", "свой", "чек", "."],
    enTokens: ["Do", "not", "forget", "your", "receipt", "."],
    extraUaTokens: ["товар", "будь", "ласка"],
    extraRuTokens: ["товар", "пожалуйста", "сейчас"],
    extraEnTokens: ["product", "please", "now"],
  },

  // =========================
  // LESSON A1-15 — Подорожі
  // =========================
  [phraseKey("hotel", "a1-15")]: {
    sk: "Ten hotel je blízko centra.",
    ua: "Той готель близько до центру.",
    ru: "Этот отель недалеко от центра.",
    en: "That hotel is close to the city center.",
    uaTokens: ["Той", "готель", "близько", "до", "центру", "."],
    ruTokens: ["Этот", "отель", "недалеко", "от", "центра", "."],
    enTokens: ["That", "hotel", "is", "close", "to", "the", "city", "center", "."],
    extraUaTokens: ["далеко", "вокзалу", "дуже"],
    extraRuTokens: ["далеко", "вокзала", "очень"],
    extraEnTokens: ["far", "station", "very"],
  },

  [phraseKey("ubytování", "a1-15")]: {
    sk: "Hledáme levné ubytování.",
    ua: "Ми шукаємо недороге житло.",
    ru: "Мы ищем недорогое жильё.",
    en: "We are looking for cheap accommodation.",
    uaTokens: ["Ми", "шукаємо", "недороге", "житло", "."],
    ruTokens: ["Мы", "ищем", "недорогое", "жильё", "."],
    enTokens: ["We", "are", "looking", "for", "cheap", "accommodation", "."],
    extraUaTokens: ["готель", "сьогодні", "гарне"],
    extraRuTokens: ["отель", "сегодня", "хорошее"],
    extraEnTokens: ["hotel", "today", "nice"],
  },

  [phraseKey("turista", "a1-15")]: {
    sk: "Ve městě je hodně turistů.",
    ua: "У місті багато туристів.",
    ru: "В городе много туристов.",
    en: "There are many tourists in the city.",
    uaTokens: ["У", "місті", "багато", "туристів", "."],
    ruTokens: ["В", "городе", "много", "туристов", "."],
    enTokens: ["There", "are", "many", "tourists", "in", "the", "city", "."],
    extraUaTokens: ["людей", "влітку", "дуже"],
    extraRuTokens: ["людей", "летом", "очень"],
    extraEnTokens: ["people", "summer", "very"],
  },

  [phraseKey("průvodce", "a1-15")]: {
    sk: "Náš průvodce mluvil česky i anglicky.",
    ua: "Наш гід говорив чеською й англійською.",
    ru: "Наш гид говорил по-чешски и по-английски.",
    en: "Our guide spoke Czech and English.",
    uaTokens: ["Наш", "гід", "говорив", "чеською", "й", "англійською", "."],
    ruTokens: ["Наш", "гид", "говорил", "по-чешски", "и", "по-английски", "."],
    enTokens: ["Our", "guide", "spoke", "Czech", "and", "English", "."],
    extraUaTokens: ["німецькою", "дуже", "добре"],
    extraRuTokens: ["по-немецки", "очень", "хорошо"],
    extraEnTokens: ["German", "very", "well"],
  },

  [phraseKey("exkurze", "a1-15")]: {
    sk: "Zítra máme exkurzi po městě.",
    ua: "Завтра у нас екскурсія містом.",
    ru: "Завтра у нас экскурсия по городу.",
    en: "Tomorrow we have a city tour.",
    uaTokens: ["Завтра", "у", "нас", "екскурсія", "містом", "."],
    ruTokens: ["Завтра", "у", "нас", "экскурсия", "по", "городу", "."],
    enTokens: ["Tomorrow", "we", "have", "a", "city", "tour", "."],
    extraUaTokens: ["музеєм", "довга", "буде"],
    extraRuTokens: ["музею", "долгая", "будет"],
    extraEnTokens: ["museum", "long", "tomorrow"],
  },

  [phraseKey("pláž", "a1-15")]: {
    sk: "Na pláži bylo dnes horko.",
    ua: "На пляжі сьогодні було спекотно.",
    ru: "На пляже сегодня было жарко.",
    en: "It was hot on the beach today.",
    uaTokens: ["На", "пляжі", "сьогодні", "було", "спекотно", "."],
    ruTokens: ["На", "пляже", "сегодня", "было", "жарко", "."],
    enTokens: ["It", "was", "hot", "on", "the", "beach", "today", "."],
    extraUaTokens: ["прохолодно", "вранці", "дуже"],
    extraRuTokens: ["прохладно", "утром", "очень"],
    extraEnTokens: ["cool", "morning", "very"],
  },

  [phraseKey("hory", "a1-15")]: {
    sk: "V zimě jezdíme do hor.",
    ua: "Взимку ми їздимо в гори.",
    ru: "Зимой мы ездим в горы.",
    en: "In winter we go to the mountains.",
    uaTokens: ["Взимку", "ми", "їздимо", "в", "гори", "."],
    ruTokens: ["Зимой", "мы", "ездим", "в", "горы", "."],
    enTokens: ["In", "winter", "we", "go", "to", "the", "mountains", "."],
    extraUaTokens: ["море", "влітку", "часто"],
    extraRuTokens: ["море", "летом", "часто"],
    extraEnTokens: ["sea", "summer", "often"],
  },

  [phraseKey("moře", "a1-15")]: {
    sk: "V létě chceme jet k moři.",
    ua: "Влітку ми хочемо поїхати до моря.",
    ru: "Летом мы хотим поехать к морю.",
    en: "In summer we want to go to the sea.",
    uaTokens: ["Влітку", "ми", "хочемо", "поїхати", "до", "моря", "."],
    ruTokens: ["Летом", "мы", "хотим", "поехать", "к", "морю", "."],
    enTokens: ["In", "summer", "we", "want", "to", "go", "to", "the", "sea", "."],
    extraUaTokens: ["гори", "разом", "завтра"],
    extraRuTokens: ["горы", "вместе", "завтра"],
    extraEnTokens: ["mountains", "together", "tomorrow"],
  },

  [phraseKey("rezervovat", "a1-15")]: {
    sk: "Musíme si rezervovat pokoj.",
    ua: "Нам треба забронювати номер.",
    ru: "Нам нужно забронировать номер.",
    en: "We need to book a room.",
    uaTokens: ["Нам", "треба", "забронювати", "номер", "."],
    ruTokens: ["Нам", "нужно", "забронировать", "номер", "."],
    enTokens: ["We", "need", "to", "book", "a", "room", "."],
    extraUaTokens: ["готель", "сьогодні", "двомісний"],
    extraRuTokens: ["отель", "сегодня", "двухместный"],
    extraEnTokens: ["hotel", "today", "double"],
  },

  [phraseKey("dovolená", "a1-15")]: {
    sk: "Letní dovolená byla skvělá.",
    ua: "Літня відпустка була чудова.",
    ru: "Летний отпуск был отличным.",
    en: "The summer vacation was great.",
    uaTokens: ["Літня", "відпустка", "була", "чудова", "."],
    ruTokens: ["Летний", "отпуск", "был", "отличным", "."],
    enTokens: ["The", "summer", "vacation", "was", "great", "."],
    extraUaTokens: ["коротка", "зимова", "дуже"],
    extraRuTokens: ["короткий", "зимний", "очень"],
    extraEnTokens: ["short", "winter", "very"],
  },
};