import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_A1_BUILD_UA_SENTENCES_8: BuildUaSentenceDict = {
  // =========================
  // LESSON A1-36 — Транспорт (дії)
  // =========================
  [phraseKey("nastoupit", "a1-36")]: {
    sk: "Musíme nastoupit do tramvaje.",
    ua: "Нам треба сісти в трамвай.",
    ru: "Нам нужно сесть в трамвай.",
    en: "We need to get on the tram.",
    uaTokens: ["Нам", "треба", "сісти", "в", "трамвай", "."],
    ruTokens: ["Нам", "нужно", "сесть", "в", "трамвай", "."],
    enTokens: ["We", "need", "to", "get", "on", "the", "tram", "."],
    extraUaTokens: ["автобус", "зараз", "швидко"],
    extraRuTokens: ["автобус", "сейчас", "быстро"],
    extraEnTokens: ["bus", "now", "quickly"],
  },

  [phraseKey("vystoupit", "a1-36")]: {
    sk: "Vystoupím na další zastávce.",
    ua: "Я вийду на наступній зупинці.",
    ru: "Я выйду на следующей остановке.",
    en: "I will get off at the next stop.",
    uaTokens: ["Я", "вийду", "на", "наступній", "зупинці", "."],
    ruTokens: ["Я", "выйду", "на", "следующей", "остановке", "."],
    enTokens: ["I", "will", "get", "off", "at", "the", "next", "stop", "."],
    extraUaTokens: ["потім", "зараз", "там"],
    extraRuTokens: ["потом", "сейчас", "там"],
    extraEnTokens: ["later", "now", "there"],
  },

  [phraseKey("přestoupit", "a1-36")]: {
    sk: "Musíme přestoupit na autobus.",
    ua: "Нам треба пересісти на автобус.",
    ru: "Нам нужно пересесть на автобус.",
    en: "We need to change to a bus.",
    uaTokens: ["Нам", "треба", "пересісти", "на", "автобус", "."],
    ruTokens: ["Нам", "нужно", "пересесть", "на", "автобус", "."],
    enTokens: ["We", "need", "to", "change", "to", "a", "bus", "."],
    extraUaTokens: ["трамвай", "зараз", "ще"],
    extraRuTokens: ["трамвай", "сейчас", "ещё"],
    extraEnTokens: ["tram", "now", "still"],
  },

  [phraseKey("zpozdit se", "a1-36")]: {
    sk: "Ten vlak se často zpozdí.",
    ua: "Той поїзд часто запізнюється.",
    ru: "Этот поезд часто опаздывает.",
    en: "That train is often late.",
    uaTokens: ["Той", "поїзд", "часто", "запізнюється", "."],
    ruTokens: ["Этот", "поезд", "часто", "опаздывает", "."],
    enTokens: ["That", "train", "is", "often", "late", "."],
    extraUaTokens: ["сьогодні", "дуже", "знову"],
    extraRuTokens: ["сегодня", "очень", "снова"],
    extraEnTokens: ["today", "very", "again"],
  },

  [phraseKey("čekat", "a1-36")]: {
    sk: "Nechci dlouho čekat venku.",
    ua: "Я не хочу довго чекати надворі.",
    ru: "Я не хочу долго ждать на улице.",
    en: "I do not want to wait outside for a long time.",
    uaTokens: ["Я", "не", "хочу", "довго", "чекати", "надворі", "."],
    ruTokens: ["Я", "не", "хочу", "долго", "ждать", "на", "улице", "."],
    enTokens: ["I", "do", "not", "want", "to", "wait", "outside", "for", "a", "long", "time", "."],
    extraUaTokens: ["зараз", "тут", "ще"],
    extraRuTokens: ["сейчас", "тут", "ещё"],
    extraEnTokens: ["now", "here", "still"],
  },

  [phraseKey("odejít", "a1-36")]: {
    sk: "Musím odejít dřív.",
    ua: "Мені треба піти раніше.",
    ru: "Мне нужно уйти раньше.",
    en: "I need to leave earlier.",
    uaTokens: ["Мені", "треба", "піти", "раніше", "."],
    ruTokens: ["Мне", "нужно", "уйти", "раньше", "."],
    enTokens: ["I", "need", "to", "leave", "earlier", "."],
    extraUaTokens: ["сьогодні", "зараз", "вже"],
    extraRuTokens: ["сегодня", "сейчас", "уже"],
    extraEnTokens: ["today", "now", "already"],
  },

  [phraseKey("přijít", "a1-36")]: {
    sk: "Můžeš přijít v osm?",
    ua: "Ти можеш прийти о восьмій?",
    ru: "Ты можешь прийти в восемь?",
    en: "Can you come at eight?",
    uaTokens: ["Ти", "можеш", "прийти", "о", "восьмій", "?"],
    ruTokens: ["Ты", "можешь", "прийти", "в", "восемь", "?"],
    enTokens: ["Can", "you", "come", "at", "eight", "?"],
    extraUaTokens: ["завтра", "вже", "сюди"],
    extraRuTokens: ["завтра", "уже", "сюда"],
    extraEnTokens: ["tomorrow", "already", "here"],
  },

  [phraseKey("řídit", "a1-36")]: {
    sk: "Můj bratr umí dobře řídit.",
    ua: "Мій брат уміє добре керувати.",
    ru: "Мой брат умеет хорошо водить.",
    en: "My brother can drive well.",
    uaTokens: ["Мій", "брат", "уміє", "добре", "керувати", "."],
    ruTokens: ["Мой", "брат", "умеет", "хорошо", "водить", "."],
    enTokens: ["My", "brother", "can", "drive", "well", "."],
    extraUaTokens: ["авто", "дуже", "вже"],
    extraRuTokens: ["машину", "очень", "уже"],
    extraEnTokens: ["car", "very", "already"],
  },

  [phraseKey("parkovat", "a1-36")]: {
    sk: "Tady nesmíš parkovat.",
    ua: "Тут не можна паркуватися.",
    ru: "Здесь нельзя парковаться.",
    en: "You cannot park here.",
    uaTokens: ["Тут", "не", "можна", "паркуватися", "."],
    ruTokens: ["Здесь", "нельзя", "парковаться", "."],
    enTokens: ["You", "cannot", "park", "here", "."],
    extraUaTokens: ["сьогодні", "вже", "там"],
    extraRuTokens: ["сегодня", "уже", "там"],
    extraEnTokens: ["today", "already", "there"],
  },

  [phraseKey("zastavit", "a1-36")]: {
    sk: "Prosím, zastavte u obchodu.",
    ua: "Будь ласка, зупиніться біля магазину.",
    ru: "Пожалуйста, остановитесь у магазина.",
    en: "Please stop by the shop.",
    uaTokens: ["Будь", "ласка", ",", "зупиніться", "біля", "магазину", "."],
    ruTokens: ["Пожалуйста", ",", "остановитесь", "у", "магазина", "."],
    enTokens: ["Please", "stop", "by", "the", "shop", "."],
    extraUaTokens: ["тут", "зараз", "ще"],
    extraRuTokens: ["тут", "сейчас", "ещё"],
    extraEnTokens: ["here", "now", "still"],
  },

  // =========================
  // LESSON A1-37 — Плани
  // =========================
  [phraseKey("plán", "a1-37")]: {
    sk: "Mám plán na celý týden.",
    ua: "У мене є план на весь тиждень.",
    ru: "У меня есть план на всю неделю.",
    en: "I have a plan for the whole week.",
    uaTokens: ["У", "мене", "є", "план", "на", "весь", "тиждень", "."],
    ruTokens: ["У", "меня", "есть", "план", "на", "всю", "неделю", "."],
    enTokens: ["I", "have", "a", "plan", "for", "the", "whole", "week", "."],
    extraUaTokens: ["місяць", "новий", "вже"],
    extraRuTokens: ["месяц", "новый", "уже"],
    extraEnTokens: ["month", "new", "already"],
  },

  [phraseKey("cíl", "a1-37")]: {
    sk: "Můj cíl je naučit se česky.",
    ua: "Моя ціль — вивчити чеську.",
    ru: "Моя цель — выучить чешский.",
    en: "My goal is to learn Czech.",
    uaTokens: ["Моя", "ціль", "—", "вивчити", "чеську", "."],
    ruTokens: ["Моя", "цель", "—", "выучить", "чешский", "."],
    enTokens: ["My", "goal", "is", "to", "learn", "Czech", "."],
    extraUaTokens: ["швидко", "добре", "ще"],
    extraRuTokens: ["быстро", "хорошо", "ещё"],
    extraEnTokens: ["quickly", "well", "still"],
  },

  [phraseKey("budoucnost", "a1-37")]: {
    sk: "Na budoucnost myslím často.",
    ua: "Я часто думаю про майбутнє.",
    ru: "Я часто думаю о будущем.",
    en: "I often think about the future.",
    uaTokens: ["Я", "часто", "думаю", "про", "майбутнє", "."],
    ruTokens: ["Я", "часто", "думаю", "о", "будущем", "."],
    enTokens: ["I", "often", "think", "about", "the", "future", "."],
    extraUaTokens: ["родину", "сьогодні", "теж"],
    extraRuTokens: ["семье", "сегодня", "тоже"],
    extraEnTokens: ["family", "today", "too"],
  },

  [phraseKey("připravit", "a1-37")]: {
    sk: "Musím připravit dokumenty.",
    ua: "Мені треба підготувати документи.",
    ru: "Мне нужно подготовить документы.",
    en: "I need to prepare the documents.",
    uaTokens: ["Мені", "треба", "підготувати", "документи", "."],
    ruTokens: ["Мне", "нужно", "подготовить", "документы", "."],
    enTokens: ["I", "need", "to", "prepare", "the", "documents", "."],
    extraUaTokens: ["сьогодні", "ще", "всі"],
    extraRuTokens: ["сегодня", "ещё", "все"],
    extraEnTokens: ["today", "still", "all"],
  },

  [phraseKey("budoucí týden", "a1-37")]: {
    sk: "Budoucí týden budu mít volno.",
    ua: "Наступного тижня я буду вільний.",
    ru: "На следующей неделе я буду свободен.",
    en: "Next week I will be free.",
    uaTokens: ["Наступного", "тижня", "я", "буду", "вільний", "."],
    ruTokens: ["На", "следующей", "неделе", "я", "буду", "свободен", "."],
    enTokens: ["Next", "week", "I", "will", "be", "free", "."],
    extraUaTokens: ["робота", "завтра", "ще"],
    extraRuTokens: ["работа", "завтра", "ещё"],
    extraEnTokens: ["work", "tomorrow", "still"],
  },

  [phraseKey("doufat", "a1-37")]: {
    sk: "Doufám v lepší práci.",
    ua: "Я сподіваюся на кращу роботу.",
    ru: "Я надеюсь на лучшую работу.",
    en: "I hope for a better job.",
    uaTokens: ["Я", "сподіваюся", "на", "кращу", "роботу", "."],
    ruTokens: ["Я", "надеюсь", "на", "лучшую", "работу", "."],
    enTokens: ["I", "hope", "for", "a", "better", "job", "."],
    extraUaTokens: ["майбутнє", "сьогодні", "теж"],
    extraRuTokens: ["будущее", "сегодня", "тоже"],
    extraEnTokens: ["future", "today", "too"],
  },

  [phraseKey("rozhodnout se", "a1-37")]: {
    sk: "Ještě jsem se nerozhodl.",
    ua: "Я ще не вирішив.",
    ru: "Я ещё не решил.",
    en: "I have not decided yet.",
    uaTokens: ["Я", "ще", "не", "вирішив", "."],
    ruTokens: ["Я", "ещё", "не", "решил", "."],
    enTokens: ["I", "have", "not", "decided", "yet", "."],
    extraUaTokens: ["зараз", "точно", "вже"],
    extraRuTokens: ["сейчас", "точно", "уже"],
    extraEnTokens: ["now", "exactly", "already"],
  },

  [phraseKey("naplánovat", "a1-37")]: {
    sk: "Chci naplánovat dovolenou.",
    ua: "Я хочу запланувати відпустку.",
    ru: "Я хочу запланировать отпуск.",
    en: "I want to plan a vacation.",
    uaTokens: ["Я", "хочу", "запланувати", "відпустку", "."],
    ruTokens: ["Я", "хочу", "запланировать", "отпуск", "."],
    enTokens: ["I", "want", "to", "plan", "a", "vacation", "."],
    extraUaTokens: ["поїздку", "сьогодні", "ще"],
    extraRuTokens: ["поездку", "сегодня", "ещё"],
    extraEnTokens: ["trip", "today", "still"],
  },

  [phraseKey("termín", "a1-37")]: {
    sk: "Jaký je termín odevzdání?",
    ua: "Який термін здачі?",
    ru: "Какой срок сдачи?",
    en: "What is the deadline?",
    uaTokens: ["Який", "термін", "здачі", "?"],
    ruTokens: ["Какой", "срок", "сдачи", "?"],
    enTokens: ["What", "is", "the", "deadline", "?"],
    extraUaTokens: ["роботи", "точний", "ще"],
    extraRuTokens: ["работы", "точный", "ещё"],
    extraEnTokens: ["work", "exact", "still"],
  },

  [phraseKey("pokračovat", "a1-37")]: {
    sk: "Chci pokračovat v kurzu.",
    ua: "Я хочу продовжити курс.",
    ru: "Я хочу продолжить курс.",
    en: "I want to continue the course.",
    uaTokens: ["Я", "хочу", "продовжити", "курс", "."],
    ruTokens: ["Я", "хочу", "продолжить", "курс", "."],
    enTokens: ["I", "want", "to", "continue", "the", "course", "."],
    extraUaTokens: ["далі", "ще", "навчання"],
    extraRuTokens: ["дальше", "ещё", "обучение"],
    extraEnTokens: ["further", "still", "learning"],
  },

  // =========================
  // LESSON A1-38 — Ситуації в магазині
  // =========================
  [phraseKey("reklamace", "a1-38")]: {
    sk: "Chci podat reklamaci.",
    ua: "Я хочу подати скаргу.",
    ru: "Я хочу подать рекламацию.",
    en: "I want to file a complaint.",
    uaTokens: ["Я", "хочу", "подати", "скаргу", "."],
    ruTokens: ["Я", "хочу", "подать", "рекламацию", "."],
    enTokens: ["I", "want", "to", "file", "a", "complaint", "."],
    extraUaTokens: ["на", "товар", "цей"],
    extraRuTokens: ["на", "товар", "этот"],
    extraEnTokens: ["about", "product", "this"],
  },

  [phraseKey("zboží", "a1-38")]: {
    sk: "To zboží je poškozené.",
    ua: "Цей товар пошкоджений.",
    ru: "Этот товар повреждён.",
    en: "This product is damaged.",
    uaTokens: ["Цей", "товар", "пошкоджений", "."],
    ruTokens: ["Этот", "товар", "повреждён", "."],
    enTokens: ["This", "product", "is", "damaged", "."],
    extraUaTokens: ["новий", "сьогодні", "вже"],
    extraRuTokens: ["новый", "сегодня", "уже"],
    extraEnTokens: ["new", "today", "already"],
  },

  [phraseKey("sklad", "a1-38")]: {
    sk: "To teď nemáme na skladě.",
    ua: "Зараз цього немає на складі.",
    ru: "Сейчас этого нет на складе.",
    en: "We do not have it in stock now.",
    uaTokens: ["Зараз", "цього", "немає", "на", "складі", "."],
    ruTokens: ["Сейчас", "этого", "нет", "на", "складе", "."],
    enTokens: ["We", "do", "not", "have", "it", "in", "stock", "now", "."],
    extraUaTokens: ["магазині", "вже", "ще"],
    extraRuTokens: ["магазине", "уже", "ещё"],
    extraEnTokens: ["store", "already", "still"],
  },

  [phraseKey("účtenka", "a1-38")]: {
    sk: "Máte ještě účtenku?",
    ua: "У вас ще є чек?",
    ru: "У вас ещё есть чек?",
    en: "Do you still have the receipt?",
    uaTokens: ["У", "вас", "ще", "є", "чек", "?"],
    ruTokens: ["У", "вас", "ещё", "есть", "чек", "?"],
    enTokens: ["Do", "you", "still", "have", "the", "receipt", "?"],
    extraUaTokens: ["товар", "цей", "зараз"],
    extraRuTokens: ["товар", "этот", "сейчас"],
    extraEnTokens: ["product", "this", "now"],
  },

  [phraseKey("záruka", "a1-38")]: {
    sk: "Na ten výrobek je záruka dva roky.",
    ua: "На цей виріб діє гарантія два роки.",
    ru: "На этот товар действует гарантия два года.",
    en: "This product has a two-year warranty.",
    uaTokens: ["На", "цей", "виріб", "діє", "гарантія", "два", "роки", "."],
    ruTokens: ["На", "этот", "товар", "действует", "гарантия", "два", "года", "."],
    enTokens: ["This", "product", "has", "a", "two-year", "warranty", "."],
    extraUaTokens: ["довга", "ще", "нова"],
    extraRuTokens: ["долгая", "ещё", "новая"],
    extraEnTokens: ["long", "still", "new"],
  },

  [phraseKey("poškozený", "a1-38")]: {
    sk: "Balík přišel poškozený.",
    ua: "Пакунок прийшов пошкодженим.",
    ru: "Посылка пришла повреждённой.",
    en: "The package arrived damaged.",
    uaTokens: ["Пакунок", "прийшов", "пошкодженим", "."],
    ruTokens: ["Посылка", "пришла", "повреждённой", "."],
    enTokens: ["The", "package", "arrived", "damaged", "."],
    extraUaTokens: ["сьогодні", "вже", "трохи"],
    extraRuTokens: ["сегодня", "уже", "немного"],
    extraEnTokens: ["today", "already", "slightly"],
  },

  [phraseKey("prodavač", "a1-38")]: {
    sk: "Prodavač mi poradil dobře.",
    ua: "Продавець дав мені добру пораду.",
    ru: "Продавец дал мне хороший совет.",
    en: "The shop assistant gave me good advice.",
    uaTokens: ["Продавець", "дав", "мені", "добру", "пораду", "."],
    ruTokens: ["Продавец", "дал", "мне", "хороший", "совет", "."],
    enTokens: ["The", "shop", "assistant", "gave", "me", "good", "advice", "."],
    extraUaTokens: ["сьогодні", "дуже", "ввічливо"],
    extraRuTokens: ["сегодня", "очень", "вежливо"],
    extraEnTokens: ["today", "very", "politely"],
  },

  [phraseKey("zákazník", "a1-38")]: {
    sk: "Zákazník čeká u pokladny.",
    ua: "Клієнт чекає біля каси.",
    ru: "Клиент ждёт у кассы.",
    en: "The customer is waiting by the checkout.",
    uaTokens: ["Клієнт", "чекає", "біля", "каси", "."],
    ruTokens: ["Клиент", "ждёт", "у", "кассы", "."],
    enTokens: ["The", "customer", "is", "waiting", "by", "the", "checkout", "."],
    extraUaTokens: ["довго", "сьогодні", "ще"],
    extraRuTokens: ["долго", "сегодня", "ещё"],
    extraEnTokens: ["long", "today", "still"],
  },

  [phraseKey("reklamovat", "a1-38")]: {
    sk: "Chci reklamovat tento výrobek.",
    ua: "Я хочу подати скаргу на цей товар.",
    ru: "Я хочу подать рекламацию на этот товар.",
    en: "I want to make a complaint about this product.",
    uaTokens: ["Я", "хочу", "подати", "скаргу", "на", "цей", "товар", "."],
    ruTokens: ["Я", "хочу", "подать", "рекламацию", "на", "этот", "товар", "."],
    enTokens: ["I", "want", "to", "make", "a", "complaint", "about", "this", "product", "."],
    extraUaTokens: ["зараз", "через", "поломку"],
    extraRuTokens: ["сейчас", "из-за", "поломки"],
    extraEnTokens: ["now", "because", "breakdown"],
  },

  [phraseKey("výměna", "a1-38")]: {
    sk: "Možná bude lepší výměna.",
    ua: "Можливо, кращим буде обмін.",
    ru: "Возможно, лучше будет обмен.",
    en: "Maybe an exchange will be better.",
    uaTokens: ["Можливо", ",", "кращим", "буде", "обмін", "."],
    ruTokens: ["Возможно", ",", "лучше", "будет", "обмен", "."],
    enTokens: ["Maybe", "an", "exchange", "will", "be", "better", "."],
    extraUaTokens: ["повернення", "сьогодні", "ще"],
    extraRuTokens: ["возврат", "сегодня", "ещё"],
    extraEnTokens: ["return", "today", "still"],
  },

  // =========================
  // LESSON A1-39 — Абстрактні слова
  // =========================
  [phraseKey("život", "a1-39")]: {
    sk: "Život není vždy jednoduchý.",
    ua: "Життя не завжди просте.",
    ru: "Жизнь не всегда простая.",
    en: "Life is not always easy.",
    uaTokens: ["Життя", "не", "завжди", "просте", "."],
    ruTokens: ["Жизнь", "не", "всегда", "простая", "."],
    enTokens: ["Life", "is", "not", "always", "easy", "."],
    extraUaTokens: ["важке", "дуже", "інколи"],
    extraRuTokens: ["тяжёлая", "очень", "иногда"],
    extraEnTokens: ["hard", "very", "sometimes"],
  },

  [phraseKey("čas", "a1-39")]: {
    sk: "Nemám teď moc času.",
    ua: "У мене зараз не дуже багато часу.",
    ru: "У меня сейчас не очень много времени.",
    en: "I do not have much time right now.",
    uaTokens: ["У", "мене", "зараз", "не", "дуже", "багато", "часу", "."],
    ruTokens: ["У", "меня", "сейчас", "не", "очень", "много", "времени", "."],
    enTokens: ["I", "do", "not", "have", "much", "time", "right", "now", "."],
    extraUaTokens: ["грошей", "сьогодні", "ще"],
    extraRuTokens: ["денег", "сегодня", "ещё"],
    extraEnTokens: ["money", "today", "still"],
  },

  [phraseKey("možnost", "a1-39")]: {
    sk: "Je tu ještě jedna možnost.",
    ua: "Тут є ще одна можливість.",
    ru: "Тут есть ещё одна возможность.",
    en: "There is one more option here.",
    uaTokens: ["Тут", "є", "ще", "одна", "можливість", "."],
    ruTokens: ["Тут", "есть", "ещё", "одна", "возможность", "."],
    enTokens: ["There", "is", "one", "more", "option", "here", "."],
    extraUaTokens: ["варіант", "новий", "ще"],
    extraRuTokens: ["вариант", "новый", "ещё"],
    extraEnTokens: ["variant", "new", "still"],
  },

  [phraseKey("důvod", "a1-39")]: {
    sk: "Neznám přesný důvod.",
    ua: "Я не знаю точної причини.",
    ru: "Я не знаю точной причины.",
    en: "I do not know the exact reason.",
    uaTokens: ["Я", "не", "знаю", "точної", "причини", "."],
    ruTokens: ["Я", "не", "знаю", "точной", "причины", "."],
    enTokens: ["I", "do", "not", "know", "the", "exact", "reason", "."],
    extraUaTokens: ["цього", "зараз", "ще"],
    extraRuTokens: ["этого", "сейчас", "ещё"],
    extraEnTokens: ["this", "now", "still"],
  },

  [phraseKey("význam", "a1-39")]: {
    sk: "To slovo má jiný význam.",
    ua: "Це слово має інше значення.",
    ru: "Это слово имеет другое значение.",
    en: "This word has a different meaning.",
    uaTokens: ["Це", "слово", "має", "інше", "значення", "."],
    ruTokens: ["Это", "слово", "имеет", "другое", "значение", "."],
    enTokens: ["This", "word", "has", "a", "different", "meaning", "."],
    extraUaTokens: ["сьогодні", "тут", "ще"],
    extraRuTokens: ["сегодня", "тут", "ещё"],
    extraEnTokens: ["today", "here", "still"],
  },

  [phraseKey("pravda", "a1-39")]: {
    sk: "Říkáš pravdu?",
    ua: "Ти кажеш правду?",
    ru: "Ты говоришь правду?",
    en: "Are you telling the truth?",
    uaTokens: ["Ти", "кажеш", "правду", "?"],
    ruTokens: ["Ты", "говоришь", "правду", "?"],
    enTokens: ["Are", "you", "telling", "the", "truth", "?"],
    extraUaTokens: ["зараз", "мені", "ще"],
    extraRuTokens: ["сейчас", "мне", "ещё"],
    extraEnTokens: ["now", "me", "still"],
  },

  [phraseKey("lež", "a1-39")]: {
    sk: "To byla jen lež.",
    ua: "Це була лише брехня.",
    ru: "Это была только ложь.",
    en: "That was only a lie.",
    uaTokens: ["Це", "була", "лише", "брехня", "."],
    ruTokens: ["Это", "была", "только", "ложь", "."],
    enTokens: ["That", "was", "only", "a", "lie", "."],
    extraUaTokens: ["правда", "сьогодні", "не"],
    extraRuTokens: ["правда", "сегодня", "не"],
    extraEnTokens: ["truth", "today", "not"],
  },

  [phraseKey("úspěch", "a1-39")]: {
    sk: "To byl velký úspěch.",
    ua: "Це був великий успіх.",
    ru: "Это был большой успех.",
    en: "That was a great success.",
    uaTokens: ["Це", "був", "великий", "успіх", "."],
    ruTokens: ["Это", "был", "большой", "успех", "."],
    enTokens: ["That", "was", "a", "great", "success", "."],
    extraUaTokens: ["справжній", "сьогодні", "дуже"],
    extraRuTokens: ["настоящий", "сегодня", "очень"],
    extraEnTokens: ["real", "today", "very"],
  },

  [phraseKey("neúspěch", "a1-39")]: {
    sk: "Každý neúspěch něco učí.",
    ua: "Кожна невдача чогось вчить.",
    ru: "Каждая неудача чему-то учит.",
    en: "Every failure teaches something.",
    uaTokens: ["Кожна", "невдача", "чогось", "вчить", "."],
    ruTokens: ["Каждая", "неудача", "чему-то", "учит", "."],
    enTokens: ["Every", "failure", "teaches", "something", "."],
    extraUaTokens: ["досвіду", "життя", "ще"],
    extraRuTokens: ["опыту", "жизни", "ещё"],
    extraEnTokens: ["experience", "life", "still"],
  },

  [phraseKey("zkušenost", "a1-39")]: {
    sk: "To byla dobrá zkušenost.",
    ua: "Це був хороший досвід.",
    ru: "Это был хороший опыт.",
    en: "That was a good experience.",
    uaTokens: ["Це", "був", "хороший", "досвід", "."],
    ruTokens: ["Это", "был", "хороший", "опыт", "."],
    enTokens: ["That", "was", "a", "good", "experience", "."],
    extraUaTokens: ["новий", "дуже", "для"],
    extraRuTokens: ["новый", "очень", "для"],
    extraEnTokens: ["new", "very", "for"],
  },

  // =========================
  // LESSON A1-40 — Повторення A1
  // =========================
  [phraseKey("učit se", "a1-40")]: {
    sk: "Chci se učit každý den.",
    ua: "Я хочу вчитися щодня.",
    ru: "Я хочу учиться каждый день.",
    en: "I want to study every day.",
    uaTokens: ["Я", "хочу", "вчитися", "щодня", "."],
    ruTokens: ["Я", "хочу", "учиться", "каждый", "день", "."],
    enTokens: ["I", "want", "to", "study", "every", "day", "."],
    extraUaTokens: ["більше", "ще", "зараз"],
    extraRuTokens: ["больше", "ещё", "сейчас"],
    extraEnTokens: ["more", "still", "now"],
  },

  [phraseKey("cestovat", "a1-40")]: {
    sk: "Rád cestuju po Evropě.",
    ua: "Я люблю подорожувати Європою.",
    ru: "Я люблю путешествовать по Европе.",
    en: "I like traveling around Europe.",
    uaTokens: ["Я", "люблю", "подорожувати", "Європою", "."],
    ruTokens: ["Я", "люблю", "путешествовать", "по", "Европе", "."],
    enTokens: ["I", "like", "traveling", "around", "Europe", "."],
    extraUaTokens: ["влітку", "дуже", "часто"],
    extraRuTokens: ["летом", "очень", "часто"],
    extraEnTokens: ["summer", "very", "often"],
  },

  [phraseKey("pomoct", "a1-40")]: {
    sk: "Můžeš mi pomoct s taškou?",
    ua: "Можеш мені допомогти з сумкою?",
    ru: "Можешь мне помочь с сумкой?",
    en: "Can you help me with the bag?",
    uaTokens: ["Можеш", "мені", "допомогти", "з", "сумкою", "?"],
    ruTokens: ["Можешь", "мне", "помочь", "с", "сумкой", "?"],
    enTokens: ["Can", "you", "help", "me", "with", "the", "bag", "?"],
    extraUaTokens: ["валізою", "ще", "тут"],
    extraRuTokens: ["чемоданом", "ещё", "тут"],
    extraEnTokens: ["suitcase", "still", "here"],
  },

  [phraseKey("psát", "a1-40")]: {
    sk: "Musím psát e-mail.",
    ua: "Мені треба написати e-mail.",
    ru: "Мне нужно написать e-mail.",
    en: "I need to write an e-mail.",
    uaTokens: ["Мені", "треба", "написати", "e-mail", "."],
    ruTokens: ["Мне", "нужно", "написать", "e-mail", "."],
    enTokens: ["I", "need", "to", "write", "an", "e-mail", "."],
    extraUaTokens: ["лист", "сьогодні", "ще"],
    extraRuTokens: ["письмо", "сегодня", "ещё"],
    extraEnTokens: ["letter", "today", "still"],
  },

  [phraseKey("vrátit se", "a1-40")]: {
    sk: "Chci se vrátit domů brzy.",
    ua: "Я хочу повернутися додому рано.",
    ru: "Я хочу вернуться домой рано.",
    en: "I want to return home early.",
    uaTokens: ["Я", "хочу", "повернутися", "додому", "рано", "."],
    ruTokens: ["Я", "хочу", "вернуться", "домой", "рано", "."],
    enTokens: ["I", "want", "to", "return", "home", "early", "."],
    extraUaTokens: ["сьогодні", "ще", "швидко"],
    extraRuTokens: ["сегодня", "ещё", "быстро"],
    extraEnTokens: ["today", "still", "quickly"],
  },

  [phraseKey("zůstat", "a1-40")]: {
    sk: "Dnes chci zůstat doma.",
    ua: "Сьогодні я хочу залишитися вдома.",
    ru: "Сегодня я хочу остаться дома.",
    en: "Today I want to stay at home.",
    uaTokens: ["Сьогодні", "я", "хочу", "залишитися", "вдома", "."],
    ruTokens: ["Сегодня", "я", "хочу", "остаться", "дома", "."],
    enTokens: ["Today", "I", "want", "to", "stay", "at", "home", "."],
    extraUaTokens: ["спокійно", "ще", "тут"],
    extraRuTokens: ["спокойно", "ещё", "тут"],
    extraEnTokens: ["calmly", "still", "here"],
  },

  [phraseKey("změnit", "a1-40")]: {
    sk: "Musím změnit svůj plán.",
    ua: "Мені треба змінити свій план.",
    ru: "Мне нужно изменить свой план.",
    en: "I need to change my plan.",
    uaTokens: ["Мені", "треба", "змінити", "свій", "план", "."],
    ruTokens: ["Мне", "нужно", "изменить", "свой", "план", "."],
    enTokens: ["I", "need", "to", "change", "my", "plan", "."],
    extraUaTokens: ["сьогодні", "ще", "трохи"],
    extraRuTokens: ["сегодня", "ещё", "немного"],
    extraEnTokens: ["today", "still", "slightly"],
  },

  [phraseKey("ukázat", "a1-40")]: {
    sk: "Můžu ti to ukázat.",
    ua: "Я можу тобі це показати.",
    ru: "Я могу тебе это показать.",
    en: "I can show it to you.",
    uaTokens: ["Я", "можу", "тобі", "це", "показати", "."],
    ruTokens: ["Я", "могу", "тебе", "это", "показать", "."],
    enTokens: ["I", "can", "show", "it", "to", "you", "."],
    extraUaTokens: ["зараз", "ще", "раз"],
    extraRuTokens: ["сейчас", "ещё", "раз"],
    extraEnTokens: ["now", "still", "again"],
  },

  [phraseKey("nést", "a1-40")]: {
    sk: "Nemůžu nést tu krabici sám.",
    ua: "Я не можу нести цю коробку сам.",
    ru: "Я не могу нести эту коробку сам.",
    en: "I cannot carry this box by myself.",
    uaTokens: ["Я", "не", "можу", "нести", "цю", "коробку", "сам", "."],
    ruTokens: ["Я", "не", "могу", "нести", "эту", "коробку", "сам", "."],
    enTokens: ["I", "cannot", "carry", "this", "box", "by", "myself", "."],
    extraUaTokens: ["важку", "зараз", "дуже"],
    extraRuTokens: ["тяжёлую", "сейчас", "очень"],
    extraEnTokens: ["heavy", "now", "very"],
  },

  [phraseKey("sedět", "a1-40")]: {
    sk: "Nechci dlouho sedět doma.",
    ua: "Я не хочу довго сидіти вдома.",
    ru: "Я не хочу долго сидеть дома.",
    en: "I do not want to sit at home for a long time.",
    uaTokens: ["Я", "не", "хочу", "довго", "сидіти", "вдома", "."],
    ruTokens: ["Я", "не", "хочу", "долго", "сидеть", "дома", "."],
    enTokens: ["I", "do", "not", "want", "to", "sit", "at", "home", "for", "a", "long", "time", "."],
    extraUaTokens: ["сьогодні", "ще", "сам"],
    extraRuTokens: ["сегодня", "ещё", "сам"],
    extraEnTokens: ["today", "still", "alone"],
  },
};