import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_A0_BUILD_UA_SENTENCES_1: BuildUaSentenceDict = {
    // =========================
    // LESSON 1 — Базові слова
    // =========================
    [phraseKey("dům", "a0-1")]: {
        sk: "To je můj dům.",
        ua: "Це мій дім.",
        ru: "Это мой дом.",
        en: "This is my house.",
        uaTokens: ["Це", "мій", "дім", "."],
        ruTokens: ["Это", "мой", "дом", "."],
        enTokens: ["This", "is", "my", "house", "."],
        extraUaTokens: ["сьогодні", "гроші", "великий"],
        extraRuTokens: ["сегодня", "деньги", "большой"],
        extraEnTokens: ["today", "money", "big"],
    },

    [phraseKey("auto", "a0-1")]: {
        sk: "Mám nové auto.",
        ua: "Я маю нове авто.",
        ru: "У меня новая машина.",
        en: "I have a new car.",
        uaTokens: ["Я", "маю", "нове", "авто", "."],
        ruTokens: ["У", "меня", "новая", "машина", "."],
        enTokens: ["I", "have", "a", "new", "car", "."],
        extraUaTokens: ["гарний", "дім", "вчора"],
        extraRuTokens: ["красивый", "дом", "вчера"],
        extraEnTokens: ["beautiful", "house", "yesterday"],
    },

    [phraseKey("voda", "a0-1")]: {
        sk: "Piju studenou vodu.",
        ua: "Я п’ю холодну воду.",
        ru: "Я пью холодную воду.",
        en: "I drink cold water.",
        uaTokens: ["Я", "п’ю", "холодну", "воду", "."],
        ruTokens: ["Я", "пью", "холодную", "воду", "."],
        enTokens: ["I", "drink", "cold", "water", "."],
        extraUaTokens: ["теплий", "чай", "рано"],
        extraRuTokens: ["тёплый", "чай", "рано"],
        extraEnTokens: ["warm", "tea", "early"],
    },

    [phraseKey("chléb", "a0-1")]: {
        sk: "Kupuju čerstvý chléb.",
        ua: "Я купую свіжий хліб.",
        ru: "Я покупаю свежий хлеб.",
        en: "I buy fresh bread.",
        uaTokens: ["Я", "купую", "свіжий", "хліб", "."],
        ruTokens: ["Я", "покупаю", "свежий", "хлеб", "."],
        enTokens: ["I", "buy", "fresh", "bread", "."],
        extraUaTokens: ["воду", "швидко", "малий"],
        extraRuTokens: ["воду", "быстро", "маленький"],
        extraEnTokens: ["water", "quickly", "small"],
    },

    [phraseKey("škola", "a0-1")]: {
        sk: "Chodím do školy.",
        ua: "Я ходжу до школи.",
        ru: "Я хожу в школу.",
        en: "I go to school.",
        uaTokens: ["Я", "ходжу", "до", "школи", "."],
        ruTokens: ["Я", "хожу", "в", "школу", "."],
        enTokens: ["I", "go", "to", "school", "."],
        extraUaTokens: ["додому", "сьогодні", "повільно"],
        extraRuTokens: ["домой", "сегодня", "медленно"],
        extraEnTokens: ["home", "today", "slowly"],
    },

    [phraseKey("město", "a0-1")]: {
        sk: "Bydlím ve městě.",
        ua: "Я живу в місті.",
        ru: "Я живу в городе.",
        en: "I live in the city.",
        uaTokens: ["Я", "живу", "в", "місті", "."],
        ruTokens: ["Я", "живу", "в", "городе", "."],
        enTokens: ["I", "live", "in", "the", "city", "."],
        extraUaTokens: ["селі", "зараз", "великий"],
        extraRuTokens: ["деревне", "сейчас", "большой"],
        extraEnTokens: ["village", "now", "big"],
    },

    [phraseKey("čas", "a0-1")]: {
        sk: "Nemám moc času.",
        ua: "У мене мало часу.",
        ru: "У меня мало времени.",
        en: "I have little time.",
        uaTokens: ["У", "мене", "мало", "часу", "."],
        ruTokens: ["У", "меня", "мало", "времени", "."],
        enTokens: ["I", "have", "little", "time", "."],
        extraUaTokens: ["грошей", "вчора", "новий"],
        extraRuTokens: ["денег", "вчера", "новый"],
        extraEnTokens: ["money", "yesterday", "new"],
    },

    [phraseKey("den", "a0-1")]: {
        sk: "Dnes je hezký den.",
        ua: "Сьогодні гарний день.",
        ru: "Сегодня хороший день.",
        en: "Today is a nice day.",
        uaTokens: ["Сьогодні", "гарний", "день", "."],
        ruTokens: ["Сегодня", "хороший", "день", "."],
        enTokens: ["Today", "is", "a", "nice", "day", "."],
        extraUaTokens: ["місяць", "дуже", "вдома"],
        extraRuTokens: ["месяц", "очень", "дома"],
        extraEnTokens: ["month", "very", "home"],
    },

    [phraseKey("dobrý", "a0-1")]: {
        sk: "To je dobrý nápad.",
        ua: "Це хороша ідея.",
        ru: "Это хорошая идея.",
        en: "That is a good idea.",
        uaTokens: ["Це", "хороша", "ідея", "."],
        ruTokens: ["Это", "хорошая", "идея", "."],
        enTokens: ["That", "is", "a", "good", "idea", "."],
        extraUaTokens: ["сьогодні", "план", "малий"],
        extraRuTokens: ["сегодня", "план", "маленький"],
        extraEnTokens: ["today", "plan", "small"],
    },

    [phraseKey("peníze", "a0-1")]: {
        sk: "Nemám dost peněz.",
        ua: "У мене недостатньо грошей.",
        ru: "У меня недостаточно денег.",
        en: "I do not have enough money.",
        uaTokens: ["У", "мене", "недостатньо", "грошей", "."],
        ruTokens: ["У", "меня", "недостаточно", "денег", "."],
        enTokens: ["I", "do", "not", "have", "enough", "money", "."],
        extraUaTokens: ["часу", "завтра", "смачний"],
        extraRuTokens: ["времени", "завтра", "вкусный"],
        extraEnTokens: ["time", "tomorrow", "tasty"],
    },

    // =========================
    // LESSON 2 — Люди
    // =========================
    [phraseKey("člověk", "a0-2")]: {
        sk: "Ten člověk je milý.",
        ua: "Та людина добра.",
        ru: "Этот человек добрый.",
        en: "That person is kind.",
        uaTokens: ["Та", "людина", "добра", "."],
        ruTokens: ["Этот", "человек", "добрый", "."],
        enTokens: ["That", "person", "is", "kind", "."],
        extraUaTokens: ["висока", "сьогодні", "вулиця"],
        extraRuTokens: ["высокая", "сегодня", "улица"],
        extraEnTokens: ["tall", "today", "street"],
    },

    [phraseKey("muž", "a0-2")]: {
        sk: "Ten muž pracuje.",
        ua: "Той чоловік працює.",
        ru: "Тот мужчина работает.",
        en: "That man is working.",
        uaTokens: ["Той", "чоловік", "працює", "."],
        ruTokens: ["Тот", "мужчина", "работает", "."],
        enTokens: ["That", "man", "is", "working", "."],
        extraUaTokens: ["вчора", "вдома", "новий"],
        extraRuTokens: ["вчера", "дома", "новый"],
        extraEnTokens: ["yesterday", "home", "new"],
    },

    [phraseKey("žena", "a0-2")]: {
        sk: "Ta žena je učitelka.",
        ua: "Та жінка — вчителька.",
        ru: "Та женщина — учительница.",
        en: "That woman is a teacher.",
        uaTokens: ["Та", "жінка", "—", "вчителька", "."],
        ruTokens: ["Та", "женщина", "—", "учительница", "."],
        enTokens: ["That", "woman", "is", "a", "teacher", "."],
        extraUaTokens: ["добра", "сьогодні", "там"],
        extraRuTokens: ["добрая", "сегодня", "там"],
        extraEnTokens: ["kind", "today", "there"],
    },

    [phraseKey("dítě", "a0-2")]: {
        sk: "Dítě si hraje.",
        ua: "Дитина грається.",
        ru: "Ребёнок играет.",
        en: "The child is playing.",
        uaTokens: ["Дитина", "грається", "."],
        ruTokens: ["Ребёнок", "играет", "."],
        enTokens: ["The", "child", "is", "playing", "."],
        extraUaTokens: ["вдома", "тихо", "малий"],
        extraRuTokens: ["дома", "тихо", "маленький"],
        extraEnTokens: ["home", "quietly", "small"],
    },

    [phraseKey("kamarád", "a0-2")]: {
        sk: "To je můj dobrý kamarád.",
        ua: "Це мій хороший друг.",
        ru: "Это мой хороший друг.",
        en: "This is my good friend.",
        uaTokens: ["Це", "мій", "хороший", "друг", "."],
        ruTokens: ["Это", "мой", "хороший", "друг", "."],
        enTokens: ["This", "is", "my", "good", "friend", "."],
        extraUaTokens: ["сьогодні", "старий", "учень"],
        extraRuTokens: ["сегодня", "старый", "ученик"],
        extraEnTokens: ["today", "old", "student"],
    },

    [phraseKey("kamarádka", "a0-2")]: {
        sk: "Moje kamarádka studuje.",
        ua: "Моя подруга навчається.",
        ru: "Моя подруга учится.",
        en: "My female friend is studying.",
        uaTokens: ["Моя", "подруга", "навчається", "."],
        ruTokens: ["Моя", "подруга", "учится", "."],
        enTokens: ["My", "female", "friend", "is", "studying", "."],
        extraUaTokens: ["вдома", "завтра", "висока"],
        extraRuTokens: ["дома", "завтра", "высокая"],
        extraEnTokens: ["home", "tomorrow", "tall"],
    },

    [phraseKey("otec", "a0-2")]: {
        sk: "Můj otec pracuje ve městě.",
        ua: "Мій батько працює в місті.",
        ru: "Мой отец работает в городе.",
        en: "My father works in the city.",
        uaTokens: ["Мій", "батько", "працює", "в", "місті", "."],
        ruTokens: ["Мой", "отец", "работает", "в", "городе", "."],
        enTokens: ["My", "father", "works", "in", "the", "city", "."],
        extraUaTokens: ["сьогодні", "рано", "школа"],
        extraRuTokens: ["сегодня", "рано", "школа"],
        extraEnTokens: ["today", "early", "school"],
    },

    [phraseKey("matka", "a0-2")]: {
        sk: "Moje matka je doma.",
        ua: "Моя мати вдома.",
        ru: "Моя мать дома.",
        en: "My mother is at home.",
        uaTokens: ["Моя", "мати", "вдома", "."],
        ruTokens: ["Моя", "мать", "дома", "."],
        enTokens: ["My", "mother", "is", "at", "home", "."],
        extraUaTokens: ["зараз", "добра", "вулиця"],
        extraRuTokens: ["сейчас", "добрая", "улица"],
        extraEnTokens: ["now", "kind", "street"],
    },

    [phraseKey("bratr", "a0-2")]: {
        sk: "Můj bratr je mladý.",
        ua: "Мій брат молодий.",
        ru: "Мой брат молодой.",
        en: "My brother is young.",
        uaTokens: ["Мій", "брат", "молодий", "."],
        ruTokens: ["Мой", "брат", "молодой", "."],
        enTokens: ["My", "brother", "is", "young", "."],
        extraUaTokens: ["високий", "сьогодні", "парк"],
        extraRuTokens: ["высокий", "сегодня", "парк"],
        extraEnTokens: ["tall", "today", "park"],
    },

    [phraseKey("sestra", "a0-2")]: {
        sk: "Moje sestra chodí do školy.",
        ua: "Моя сестра ходить до школи.",
        ru: "Моя сестра ходит в школу.",
        en: "My sister goes to school.",
        uaTokens: ["Моя", "сестра", "ходить", "до", "школи", "."],
        ruTokens: ["Моя", "сестра", "ходит", "в", "школу", "."],
        enTokens: ["My", "sister", "goes", "to", "school", "."],
        extraUaTokens: ["додому", "рано", "чай"],
        extraRuTokens: ["домой", "рано", "чай"],
        extraEnTokens: ["home", "early", "tea"],
    },

    // =========================
    // LESSON 3 — Дім
    // =========================
    [phraseKey("byt", "a0-3")]: {
        sk: "Bydlím v malém bytě.",
        ua: "Я живу в маленькій квартирі.",
        ru: "Я живу в маленькой квартире.",
        en: "I live in a small apartment.",
        uaTokens: ["Я", "живу", "в", "маленькій", "квартирі", "."],
        ruTokens: ["Я", "живу", "в", "маленькой", "квартире", "."],
        enTokens: ["I", "live", "in", "a", "small", "apartment", "."],
        extraUaTokens: ["будинку", "сьогодні", "новий"],
        extraRuTokens: ["доме", "сегодня", "новый"],
        extraEnTokens: ["house", "today", "new"],
    },

    [phraseKey("pokoj", "a0-3")]: {
        sk: "Mám světlý pokoj.",
        ua: "У мене світла кімната.",
        ru: "У меня светлая комната.",
        en: "I have a bright room.",
        uaTokens: ["У", "мене", "світла", "кімната", "."],
        ruTokens: ["У", "меня", "светлая", "комната", "."],
        enTokens: ["I", "have", "a", "bright", "room", "."],
        extraUaTokens: ["велика", "кухня", "вчора"],
        extraRuTokens: ["большая", "кухня", "вчера"],
        extraEnTokens: ["big", "kitchen", "yesterday"],
    },

    [phraseKey("kuchyně", "a0-3")]: {
        sk: "Kuchyně je čistá.",
        ua: "Кухня чиста.",
        ru: "Кухня чистая.",
        en: "The kitchen is clean.",
        uaTokens: ["Кухня", "чиста", "."],
        ruTokens: ["Кухня", "чистая", "."],
        enTokens: ["The", "kitchen", "is", "clean", "."],
        extraUaTokens: ["світла", "сьогодні", "вдома"],
        extraRuTokens: ["светлая", "сегодня", "дома"],
        extraEnTokens: ["bright", "today", "home"],
    },

    [phraseKey("koupelna", "a0-3")]: {
        sk: "Koupelna je vedle pokoje.",
        ua: "Ванна кімната біля кімнати.",
        ru: "Ванная рядом с комнатой.",
        en: "The bathroom is next to the room.",
        uaTokens: ["Ванна", "кімната", "біля", "кімнати", "."],
        ruTokens: ["Ванная", "рядом", "с", "комнатой", "."],
        enTokens: ["The", "bathroom", "is", "next", "to", "the", "room", "."],
        extraUaTokens: ["кухні", "сьогодні", "нова"],
        extraRuTokens: ["кухни", "сегодня", "новая"],
        extraEnTokens: ["kitchen", "today", "new"],
    },

    [phraseKey("dveře", "a0-3")]: {
        sk: "Dveře jsou otevřené.",
        ua: "Двері відкриті.",
        ru: "Двери открыты.",
        en: "The door is open.",
        uaTokens: ["Двері", "відкриті", "."],
        ruTokens: ["Двери", "открыты", "."],
        enTokens: ["The", "door", "is", "open", "."],
        extraUaTokens: ["вікно", "зараз", "велике"],
        extraRuTokens: ["окно", "сейчас", "большое"],
        extraEnTokens: ["window", "now", "big"],
    },

    [phraseKey("okno", "a0-3")]: {
        sk: "Okno je zavřené.",
        ua: "Вікно зачинене.",
        ru: "Окно закрыто.",
        en: "The window is closed.",
        uaTokens: ["Вікно", "зачинене", "."],
        ruTokens: ["Окно", "закрыто", "."],
        enTokens: ["The", "window", "is", "closed", "."],
        extraUaTokens: ["двері", "вчора", "мале"],
        extraRuTokens: ["двери", "вчера", "маленькое"],
        extraEnTokens: ["door", "yesterday", "small"],
    },

    [phraseKey("stůl", "a0-3")]: {
        sk: "Na stole je kniha.",
        ua: "На столі книга.",
        ru: "На столе книга.",
        en: "There is a book on the table.",
        uaTokens: ["На", "столі", "книга", "."],
        ruTokens: ["На", "столе", "книга", "."],
        enTokens: ["There", "is", "a", "book", "on", "the", "table", "."],
        uaAltAnswers: [
            ["Книга", "на", "столі", "."],
        ],
        ruAltAnswers: [
            ["Книга", "на", "столе", "."],
        ],
        enAltAnswers: [
            ["A", "book", "is", "on", "the", "table", "."],
            ["The", "book", "is", "on", "the", "table", "."],
        ],
        extraUaTokens: ["зошит", "вчора", "новий"],
        extraRuTokens: ["тетрадь", "вчера", "новый"],
        extraEnTokens: ["notebook", "yesterday", "new"],
    },

    [phraseKey("židle", "a0-3")]: {
        sk: "Ta židle je pohodlná.",
        ua: "Той стілець зручний.",
        ru: "Этот стул удобный.",
        en: "That chair is comfortable.",
        uaTokens: ["Той", "стілець", "зручний", "."],
        ruTokens: ["Этот", "стул", "удобный", "."],
        enTokens: ["That", "chair", "is", "comfortable", "."],
        extraUaTokens: ["старий", "сьогодні", "стіл"],
        extraRuTokens: ["старый", "сегодня", "стол"],
        extraEnTokens: ["old", "today", "table"],
    },

    [phraseKey("postel", "a0-3")]: {
        sk: "Postel je v pokoji.",
        ua: "Ліжко в кімнаті.",
        ru: "Кровать в комнате.",
        en: "The bed is in the room.",
        uaTokens: ["Ліжко", "в", "кімнаті", "."],
        ruTokens: ["Кровать", "в", "комнате", "."],
        enTokens: ["The", "bed", "is", "in", "the", "room", "."],
        extraUaTokens: ["велике", "вдома", "стілець"],
        extraRuTokens: ["большая", "дома", "стул"],
        extraEnTokens: ["big", "home", "chair"],
    },

    [phraseKey("skříň", "a0-3")]: {
        sk: "Oblečení je ve skříni.",
        ua: "Одяг у шафі.",
        ru: "Одежда в шкафу.",
        en: "The clothes are in the wardrobe.",
        uaTokens: ["Одяг", "у", "шафі", "."],
        ruTokens: ["Одежда", "в", "шкафу", "."],
        enTokens: ["The", "clothes", "are", "in", "the", "wardrobe", "."],
        extraUaTokens: ["сьогодні", "чистий", "стіл"],
        extraRuTokens: ["сегодня", "чистый", "стол"],
        extraEnTokens: ["today", "clean", "table"],
    },

    // =========================
    // LESSON 4 — Магазин
    // =========================
    [phraseKey("obchod", "a0-4")]: {
        sk: "Jdu do obchodu.",
        ua: "Я йду до магазину.",
        ru: "Я иду в магазин.",
        en: "I am going to the shop.",
        uaTokens: ["Я", "йду", "до", "магазину", "."],
        ruTokens: ["Я", "иду", "в", "магазин", "."],
        enTokens: ["I", "am", "going", "to", "the", "shop", "."],
        extraUaTokens: ["додому", "зараз", "малий"],
        extraRuTokens: ["домой", "сейчас", "маленький"],
        extraEnTokens: ["home", "now", "small"],
    },

    [phraseKey("kasa", "a0-4")]: {
        sk: "Platím u kasy.",
        ua: "Я плачу на касі.",
        ru: "Я плачу на кассе.",
        en: "I am paying at the checkout.",
        uaTokens: ["Я", "плачу", "на", "касі", "."],
        ruTokens: ["Я", "плачу", "на", "кассе", "."],
        enTokens: ["I", "am", "paying", "at", "the", "checkout", "."],
        extraUaTokens: ["готівкою", "швидко", "сьогодні"],
        extraRuTokens: ["наличными", "быстро", "сегодня"],
        extraEnTokens: ["cash", "quickly", "today"],
    },

    [phraseKey("cena", "a0-4")]: {
        sk: "Ta cena je vysoká.",
        ua: "Ця ціна висока.",
        ru: "Эта цена высокая.",
        en: "This price is high.",
        uaTokens: ["Ця", "ціна", "висока", "."],
        ruTokens: ["Эта", "цена", "высокая", "."],
        enTokens: ["This", "price", "is", "high", "."],
        extraUaTokens: ["низька", "вчора", "сумка"],
        extraRuTokens: ["низкая", "вчера", "сумка"],
        extraEnTokens: ["low", "yesterday", "bag"],
    },

    [phraseKey("sleva", "a0-4")]: {
        sk: "Dnes je velká sleva.",
        ua: "Сьогодні велика знижка.",
        ru: "Сегодня большая скидка.",
        en: "There is a big discount today.",
        uaTokens: ["Сьогодні", "велика", "знижка", "."],
        ruTokens: ["Сегодня", "большая", "скидка", "."],
        enTokens: ["There", "is", "a", "big", "discount", "today", "."],
        extraUaTokens: ["ціна", "мала", "там"],
        extraRuTokens: ["цена", "маленькая", "там"],
        extraEnTokens: ["price", "small", "there"],
    },

    [phraseKey("taška", "a0-4")]: {
        sk: "Mám velkou tašku.",
        ua: "У мене велика сумка.",
        ru: "У меня большая сумка.",
        en: "I have a big bag.",
        uaTokens: ["У", "мене", "велика", "сумка", "."],
        ruTokens: ["У", "меня", "большая", "сумка", "."],
        enTokens: ["I", "have", "a", "big", "bag", "."],
        extraUaTokens: ["чорна", "сьогодні", "ціна"],
        extraRuTokens: ["чёрная", "сегодня", "цена"],
        extraEnTokens: ["black", "today", "price"],
    },

    [phraseKey("účtenka", "a0-4")]: {
        sk: "Prosím, účtenku.",
        ua: "Чек, будь ласка.",
        ru: "Чек, пожалуйста.",
        en: "A receipt, please.",
        uaTokens: ["Чек", ",", "будь", "ласка", "."],
        ruTokens: ["Чек", ",", "пожалуйста", "."],
        enTokens: ["A", "receipt", ",", "please", "."],
        extraUaTokens: ["сумка", "великий", "зараз"],
        extraRuTokens: ["сумка", "большой", "сейчас"],
        extraEnTokens: ["bag", "big", "now"],
    },

    [phraseKey("hotovost", "a0-4")]: {
        sk: "Platím hotovostí.",
        ua: "Я плачу готівкою.",
        ru: "Я плачу наличными.",
        en: "I pay in cash.",
        uaTokens: ["Я", "плачу", "готівкою", "."],
        ruTokens: ["Я", "плачу", "наличными", "."],
        enTokens: ["I", "pay", "in", "cash", "."],
        extraUaTokens: ["карткою", "сьогодні", "магазин"],
        extraRuTokens: ["картой", "сегодня", "магазин"],
        extraEnTokens: ["card", "today", "shop"],
    },

    [phraseKey("karta", "a0-4")]: {
        sk: "Můžu platit kartou.",
        ua: "Я можу платити карткою.",
        ru: "Я могу платить картой.",
        en: "I can pay by card.",
        uaTokens: ["Я", "можу", "платити", "карткою", "."],
        ruTokens: ["Я", "могу", "платить", "картой", "."],
        enTokens: ["I", "can", "pay", "by", "card", "."],
        extraUaTokens: ["готівкою", "вчора", "каса"],
        extraRuTokens: ["наличными", "вчера", "касса"],
        extraEnTokens: ["cash", "yesterday", "checkout"],
    },

    [phraseKey("koupit", "a0-4")]: {
        sk: "Chci koupit chléb.",
        ua: "Я хочу купити хліб.",
        ru: "Я хочу купить хлеб.",
        en: "I want to buy bread.",
        uaTokens: ["Я", "хочу", "купити", "хліб", "."],
        ruTokens: ["Я", "хочу", "купить", "хлеб", "."],
        enTokens: ["I", "want", "to", "buy", "bread", "."],
        extraUaTokens: ["воду", "завтра", "магазин"],
        extraRuTokens: ["воду", "завтра", "магазин"],
        extraEnTokens: ["water", "tomorrow", "shop"],
    },

    [phraseKey("platit", "a0-4")]: {
        sk: "Musím platit hned.",
        ua: "Я мушу платити зараз.",
        ru: "Я должен платить сейчас.",
        en: "I must pay now.",
        uaTokens: ["Я", "мушу", "платити", "зараз", "."],
        ruTokens: ["Я", "должен", "платить", "сейчас", "."],
        enTokens: ["I", "must", "pay", "now", "."],
        extraUaTokens: ["потім", "вчора", "ціна"],
        extraRuTokens: ["потом", "вчера", "цена"],
        extraEnTokens: ["later", "yesterday", "price"],
    },

    // =========================
    // LESSON 5 — Їжа та напої
    // =========================
    [phraseKey("jídlo", "a0-5")]: {
        sk: "To jídlo je dobré.",
        ua: "Ця їжа смачна.",
        ru: "Эта еда вкусная.",
        en: "This food is tasty.",
        uaTokens: ["Ця", "їжа", "смачна", "."],
        ruTokens: ["Эта", "еда", "вкусная", "."],
        enTokens: ["This", "food", "is", "tasty", "."],
        extraUaTokens: ["гаряча", "сьогодні", "чай"],
        extraRuTokens: ["горячая", "сегодня", "чай"],
        extraEnTokens: ["hot", "today", "tea"],
    },

    [phraseKey("nápoj", "a0-5")]: {
        sk: "Studený nápoj je v lednici.",
        ua: "Холодний напій у холодильнику.",
        ru: "Холодный напиток в холодильнике.",
        en: "The cold drink is in the fridge.",
        uaTokens: ["Холодний", "напій", "у", "холодильнику", "."],
        ruTokens: ["Холодный", "напиток", "в", "холодильнике", "."],
        enTokens: ["The", "cold", "drink", "is", "in", "the", "fridge", "."],
        uaAltAnswers: [
            ["У", "холодильнику", "холодний", "напій", "."],
        ],
        ruAltAnswers: [
            ["В", "холодильнике", "холодный", "напиток", "."],
        ],
        enAltAnswers: [
            ["In", "the", "fridge", "is", "the", "cold", "drink", "."],
        ],
        extraUaTokens: ["гарячий", "вчора", "сік"],
        extraRuTokens: ["горячий", "вчера", "сок"],
        extraEnTokens: ["hot", "yesterday", "juice"],
    },

    [phraseKey("chléb", "a0-5")]: {
        sk: "Každé ráno jím chléb.",
        ua: "Щоранку я їм хліб.",
        ru: "Каждое утро я ем хлеб.",
        en: "Every morning I eat bread.",
        uaTokens: ["Щоранку", "я", "їм", "хліб", "."],
        ruTokens: ["Каждое", "утро", "я", "ем", "хлеб", "."],
        enTokens: ["Every", "morning", "I", "eat", "bread", "."],
        uaAltAnswers: [
            ["Я", "щоранку", "їм", "хліб", "."],
        ],
        ruAltAnswers: [
            ["Я", "каждое", "утро", "ем", "хлеб", "."],
        ],
        enAltAnswers: [
            ["I", "eat", "bread", "every", "morning", "."],
        ],
        extraUaTokens: ["сир", "сьогодні", "швидко"],
        extraRuTokens: ["сыр", "сегодня", "быстро"],
        extraEnTokens: ["cheese", "today", "quickly"],
    },

    [phraseKey("maso", "a0-5")]: {
        sk: "Dnes vařím maso.",
        ua: "Сьогодні я готую м’ясо.",
        ru: "Сегодня я готовлю мясо.",
        en: "Today I am cooking meat.",
        uaTokens: ["Сьогодні", "я", "готую", "м’ясо", "."],
        ruTokens: ["Сегодня", "я", "готовлю", "мясо", "."],
        enTokens: ["Today", "I", "am", "cooking", "meat", "."],
        extraUaTokens: ["суп", "ввечері", "великий"],
        extraRuTokens: ["суп", "вечером", "большой"],
        extraEnTokens: ["soup", "evening", "big"],
    },

    [phraseKey("polévka", "a0-5")]: {
        sk: "Polévka je teplá.",
        ua: "Суп теплий.",
        ru: "Суп тёплый.",
        en: "The soup is warm.",
        uaTokens: ["Суп", "теплий", "."],
        ruTokens: ["Суп", "тёплый", "."],
        enTokens: ["The", "soup", "is", "warm", "."],
        extraUaTokens: ["смачний", "сьогодні", "чай"],
        extraRuTokens: ["вкусный", "сегодня", "чай"],
        extraEnTokens: ["tasty", "today", "tea"],
    },

    [phraseKey("ovoce", "a0-5")]: {
        sk: "Ovoce je zdravé.",
        ua: "Фрукти корисні.",
        ru: "Фрукты полезны.",
        en: "Fruit is healthy.",
        uaTokens: ["Фрукти", "корисні", "."],
        ruTokens: ["Фрукты", "полезны", "."],
        enTokens: ["Fruit", "is", "healthy", "."],
        extraUaTokens: ["свіжі", "завтра", "суп"],
        extraRuTokens: ["свежие", "завтра", "суп"],
        extraEnTokens: ["fresh", "tomorrow", "soup"],
    },

    [phraseKey("zelenina", "a0-5")]: {
        sk: "Jím hodně zeleniny.",
        ua: "Я їм багато овочів.",
        ru: "Я ем много овощей.",
        en: "I eat a lot of vegetables.",
        uaTokens: ["Я", "їм", "багато", "овочів", "."],
        ruTokens: ["Я", "ем", "много", "овощей", "."],
        enTokens: ["I", "eat", "a", "lot", "of", "vegetables", "."],
        extraUaTokens: ["фруктів", "сьогодні", "смачний"],
        extraRuTokens: ["фруктов", "сегодня", "вкусный"],
        extraEnTokens: ["fruit", "today", "tasty"],
    },

    [phraseKey("voda", "a0-5")]: {
        sk: "Piju jen vodu.",
        ua: "Я п’ю тільки воду.",
        ru: "Я пью только воду.",
        en: "I drink only water.",
        uaTokens: ["Я", "п’ю", "тільки", "воду", "."],
        ruTokens: ["Я", "пью", "только", "воду", "."],
        enTokens: ["I", "drink", "only", "water", "."],
        extraUaTokens: ["чай", "рано", "холодний"],
        extraRuTokens: ["чай", "рано", "холодный"],
        extraEnTokens: ["tea", "early", "cold"],
    },

    [phraseKey("káva", "a0-5")]: {
        sk: "Ráno piju kávu.",
        ua: "Вранці я п’ю каву.",
        ru: "Утром я пью кофе.",
        en: "In the morning I drink coffee.",
        uaTokens: ["Вранці", "я", "п’ю", "каву", "."],
        ruTokens: ["Утром", "я", "пью", "кофе", "."],
        enTokens: ["In", "the", "morning", "I", "drink", "coffee", "."],
        extraUaTokens: ["чай", "щодня", "гарячий"],
        extraRuTokens: ["чай", "каждый", "горячий"],
        extraEnTokens: ["tea", "daily", "hot"],
    },

    [phraseKey("čaj", "a0-5")]: {
        sk: "Večer si dám čaj.",
        ua: "Увечері я вип’ю чай.",
        ru: "Вечером я выпью чай.",
        en: "In the evening I will drink tea.",
        uaTokens: ["Увечері", "я", "вип’ю", "чай", "."],
        ruTokens: ["Вечером", "я", "выпью", "чай", "."],
        enTokens: ["In", "the", "evening", "I", "will", "drink", "tea", "."],
        extraUaTokens: ["каву", "завтра", "теплий"],
        extraRuTokens: ["кофе", "завтра", "тёплый"],
        extraEnTokens: ["coffee", "tomorrow", "warm"],
    },
};