import { phraseKey } from "@/app/learning/phrases/phraseKey";
import type { BuildUaSentenceDict } from "../registry";

export const CS_A0_BUILD_UA_SENTENCES_6: BuildUaSentenceDict = {
  // =========================
  // LESSON 26 — Готель і ресторан
  // =========================
  [phraseKey("hotel", "a0-26")]: {
    sk: "Ten hotel je velmi čistý.",
    ua: "Той готель дуже чистий.",
    ru: "Этот отель очень чистый.",
    en: "That hotel is very clean.",
    uaTokens: ["Той", "готель", "дуже", "чистий", "."],
    ruTokens: ["Этот", "отель", "очень", "чистый", "."],
    enTokens: ["That", "hotel", "is", "very", "clean", "."],
    extraUaTokens: ["новий", "сьогодні", "великий"],
    extraRuTokens: ["новый", "сегодня", "большой"],
    extraEnTokens: ["new", "today", "big"],
  },

  [phraseKey("pokoj", "a0-26")]: {
    sk: "Náš pokoj je v druhém patře.",
    ua: "Наш номер на другому поверсі.",
    ru: "Наш номер на втором этаже.",
    en: "Our room is on the second floor.",
    uaTokens: ["Наш", "номер", "на", "другому", "поверсі", "."],
    ruTokens: ["Наш", "номер", "на", "втором", "этаже", "."],
    enTokens: ["Our", "room", "is", "on", "the", "second", "floor", "."],
    extraUaTokens: ["великий", "сьогодні", "світлий"],
    extraRuTokens: ["большой", "сегодня", "светлый"],
    extraEnTokens: ["big", "today", "bright"],
  },

  [phraseKey("recepce", "a0-26")]: {
    sk: "Recepce je otevřená celý den.",
    ua: "Ресепшн відкритий увесь день.",
    ru: "Ресепшн открыт весь день.",
    en: "The reception is open all day.",
    uaTokens: ["Ресепшн", "відкритий", "увесь", "день", "."],
    ruTokens: ["Ресепшн", "открыт", "весь", "день", "."],
    enTokens: ["The", "reception", "is", "open", "all", "day", "."],
    extraUaTokens: ["сьогодні", "довго", "ще"],
    extraRuTokens: ["сегодня", "долго", "ещё"],
    extraEnTokens: ["today", "long", "still"],
  },

  [phraseKey("restaurace", "a0-26")]: {
    sk: "Ta restaurace je blízko hotelu.",
    ua: "Той ресторан близько до готелю.",
    ru: "Этот ресторан рядом с отелем.",
    en: "That restaurant is near the hotel.",
    uaTokens: ["Той", "ресторан", "близько", "до", "готелю", "."],
    ruTokens: ["Этот", "ресторан", "рядом", "с", "отелем", "."],
    enTokens: ["That", "restaurant", "is", "near", "the", "hotel", "."],
    extraUaTokens: ["дуже", "гарний", "сьогодні"],
    extraRuTokens: ["очень", "хороший", "сегодня"],
    extraEnTokens: ["very", "nice", "today"],
  },

  [phraseKey("menu", "a0-26")]: {
    sk: "Můžu prosím vidět menu?",
    ua: "Можна, будь ласка, меню?",
    ru: "Можно, пожалуйста, меню?",
    en: "Can I see the menu, please?",
    uaTokens: ["Можна", ",", "будь", "ласка", ",", "меню", "?"],
    ruTokens: ["Можно", ",", "пожалуйста", ",", "меню", "?"],
    enTokens: ["Can", "I", "see", "the", "menu", ",", "please", "?"],
    extraUaTokens: ["зараз", "ще", "раз"],
    extraRuTokens: ["сейчас", "ещё", "раз"],
    extraEnTokens: ["now", "one", "again"],
  },

  [phraseKey("objednat", "a0-26")]: {
    sk: "Chci si objednat večeři.",
    ua: "Я хочу замовити вечерю.",
    ru: "Я хочу заказать ужин.",
    en: "I want to order dinner.",
    uaTokens: ["Я", "хочу", "замовити", "вечерю", "."],
    ruTokens: ["Я", "хочу", "заказать", "ужин", "."],
    enTokens: ["I", "want", "to", "order", "dinner", "."],
    extraUaTokens: ["зараз", "смачну", "ще"],
    extraRuTokens: ["сейчас", "вкусный", "ещё"],
    extraEnTokens: ["now", "tasty", "more"],
  },

  [phraseKey("snídaně", "a0-26")]: {
    sk: "Snídaně je od sedmi hodin.",
    ua: "Сніданок з сьомої години.",
    ru: "Завтрак с семи часов.",
    en: "Breakfast is from seven o'clock.",
    uaTokens: ["Сніданок", "з", "сьомої", "години", "."],
    ruTokens: ["Завтрак", "с", "семи", "часов", "."],
    enTokens: ["Breakfast", "is", "from", "seven", "o'clock", "."],
    extraUaTokens: ["вранці", "щодня", "рано"],
    extraRuTokens: ["утром", "каждый", "рано"],
    extraEnTokens: ["morning", "everyday", "early"],
  },

  [phraseKey("oběd", "a0-26")]: {
    sk: "Na oběd si dám polévku.",
    ua: "На обід я візьму суп.",
    ru: "На обед я возьму суп.",
    en: "I will have soup for lunch.",
    uaTokens: ["На", "обід", "я", "візьму", "суп", "."],
    ruTokens: ["На", "обед", "я", "возьму", "суп", "."],
    enTokens: ["I", "will", "have", "soup", "for", "lunch", "."],
    extraUaTokens: ["сьогодні", "гарячий", "смачний"],
    extraRuTokens: ["сегодня", "горячий", "вкусный"],
    extraEnTokens: ["today", "hot", "tasty"],
  },

  [phraseKey("večeře", "a0-26")]: {
    sk: "Večeře byla výborná.",
    ua: "Вечеря була чудова.",
    ru: "Ужин был отличным.",
    en: "Dinner was excellent.",
    uaTokens: ["Вечеря", "була", "чудова", "."],
    ruTokens: ["Ужин", "был", "отличным", "."],
    enTokens: ["Dinner", "was", "excellent", "."],
    extraUaTokens: ["сьогодні", "дуже", "смачна"],
    extraRuTokens: ["сегодня", "очень", "вкусным"],
    extraEnTokens: ["today", "very", "tasty"],
  },

  [phraseKey("účet", "a0-26")]: {
    sk: "Můžu zaplatit účet?",
    ua: "Можна оплатити рахунок?",
    ru: "Можно оплатить счёт?",
    en: "Can I pay the bill?",
    uaTokens: ["Можна", "оплатити", "рахунок", "?"],
    ruTokens: ["Можно", "оплатить", "счёт", "?"],
    enTokens: ["Can", "I", "pay", "the", "bill", "?"],
    extraUaTokens: ["зараз", "будь", "ласка"],
    extraRuTokens: ["сейчас", "пожалуйста", "уже"],
    extraEnTokens: ["now", "please", "already"],
  },

  // =========================
  // LESSON 27 — Гроші
  // =========================
  [phraseKey("peníze", "a0-27")]: {
    sk: "Nemám u sebe moc peněz.",
    ua: "У мене з собою небагато грошей.",
    ru: "У меня с собой не очень много денег.",
    en: "I do not have much money with me.",
    uaTokens: ["У", "мене", "з", "собою", "небагато", "грошей", "."],
    ruTokens: ["У", "меня", "с", "собой", "не", "очень", "много", "денег", "."],
    enTokens: ["I", "do", "not", "have", "much", "money", "with", "me", "."],
    extraUaTokens: ["сьогодні", "вже", "готівки"],
    extraRuTokens: ["сегодня", "уже", "наличных"],
    extraEnTokens: ["today", "already", "cash"],
  },

  [phraseKey("euro", "a0-27")]: {
    sk: "Platím jen v eurech.",
    ua: "Я плачу тільки в євро.",
    ru: "Я плачу только в евро.",
    en: "I pay only in euros.",
    uaTokens: ["Я", "плачу", "тільки", "в", "євро", "."],
    ruTokens: ["Я", "плачу", "только", "в", "евро", "."],
    enTokens: ["I", "pay", "only", "in", "euros", "."],
    extraUaTokens: ["сьогодні", "готівкою", "зараз"],
    extraRuTokens: ["сегодня", "наличными", "сейчас"],
    extraEnTokens: ["today", "cash", "now"],
  },

  [phraseKey("cena", "a0-27")]: {
    sk: "Ta cena je příliš vysoká.",
    ua: "Ця ціна занадто висока.",
    ru: "Эта цена слишком высокая.",
    en: "That price is too high.",
    uaTokens: ["Ця", "ціна", "занадто", "висока", "."],
    ruTokens: ["Эта", "цена", "слишком", "высокая", "."],
    enTokens: ["That", "price", "is", "too", "high", "."],
    extraUaTokens: ["сьогодні", "дуже", "велика"],
    extraRuTokens: ["сегодня", "очень", "большая"],
    extraEnTokens: ["today", "very", "big"],
  },

  [phraseKey("platba", "a0-27")]: {
    sk: "Platba kartou je možná.",
    ua: "Оплата карткою можлива.",
    ru: "Оплата картой возможна.",
    en: "Payment by card is possible.",
    uaTokens: ["Оплата", "карткою", "можлива", "."],
    ruTokens: ["Оплата", "картой", "возможна", "."],
    enTokens: ["Payment", "by", "card", "is", "possible", "."],
    extraUaTokens: ["зараз", "тут", "також"],
    extraRuTokens: ["сейчас", "здесь", "тоже"],
    extraEnTokens: ["now", "here", "also"],
  },

  [phraseKey("hotovost", "a0-27")]: {
    sk: "Máte hotovost?",
    ua: "У вас є готівка?",
    ru: "У вас есть наличные?",
    en: "Do you have cash?",
    uaTokens: ["У", "вас", "є", "готівка", "?"],
    ruTokens: ["У", "вас", "есть", "наличные", "?"],
    enTokens: ["Do", "you", "have", "cash", "?"],
    extraUaTokens: ["зараз", "із", "собою"],
    extraRuTokens: ["сейчас", "с", "собой"],
    extraEnTokens: ["now", "with", "you"],
  },

  [phraseKey("karta", "a0-27")]: {
    sk: "Moje karta nefunguje.",
    ua: "Моя картка не працює.",
    ru: "Моя карта не работает.",
    en: "My card is not working.",
    uaTokens: ["Моя", "картка", "не", "працює", "."],
    ruTokens: ["Моя", "карта", "не", "работает", "."],
    enTokens: ["My", "card", "is", "not", "working", "."],
    extraUaTokens: ["сьогодні", "знову", "чомусь"],
    extraRuTokens: ["сегодня", "снова", "почему-то"],
    extraEnTokens: ["today", "again", "somehow"],
  },

  [phraseKey("účet", "a0-27")]: {
    sk: "Pošlu peníze na účet.",
    ua: "Я надішлю гроші на рахунок.",
    ru: "Я отправлю деньги на счёт.",
    en: "I will send money to the account.",
    uaTokens: ["Я", "надішлю", "гроші", "на", "рахунок", "."],
    ruTokens: ["Я", "отправлю", "деньги", "на", "счёт", "."],
    enTokens: ["I", "will", "send", "money", "to", "the", "account", "."],
    extraUaTokens: ["сьогодні", "пізніше", "тобі"],
    extraRuTokens: ["сегодня", "позже", "тебе"],
    extraEnTokens: ["today", "later", "to-you"],
  },

  [phraseKey("banka", "a0-27")]: {
    sk: "Dnes musím do banky.",
    ua: "Сьогодні мені треба в банк.",
    ru: "Сегодня мне нужно в банк.",
    en: "Today I need to go to the bank.",
    uaTokens: ["Сьогодні", "мені", "треба", "в", "банк", "."],
    ruTokens: ["Сегодня", "мне", "нужно", "в", "банк", "."],
    enTokens: ["Today", "I", "need", "to", "go", "to", "the", "bank", "."],
    extraUaTokens: ["зараз", "швидко", "піти"],
    extraRuTokens: ["сейчас", "быстро", "пойти"],
    extraEnTokens: ["now", "quickly", "go"],
  },

  [phraseKey("sleva", "a0-27")]: {
    sk: "Je na to nějaká sleva?",
    ua: "На це є якась знижка?",
    ru: "На это есть какая-то скидка?",
    en: "Is there any discount on this?",
    uaTokens: ["На", "це", "є", "якась", "знижка", "?"],
    ruTokens: ["На", "это", "есть", "какая-то", "скидка", "?"],
    enTokens: ["Is", "there", "any", "discount", "on", "this", "?"],
    extraUaTokens: ["сьогодні", "велика", "тут"],
    extraRuTokens: ["сегодня", "большая", "здесь"],
    extraEnTokens: ["today", "big", "here"],
  },

  [phraseKey("výdaje", "a0-27")]: {
    sk: "Moje výdaje jsou vysoké.",
    ua: "Мої витрати високі.",
    ru: "Мои расходы высокие.",
    en: "My expenses are high.",
    uaTokens: ["Мої", "витрати", "високі", "."],
    ruTokens: ["Мои", "расходы", "высокие", "."],
    enTokens: ["My", "expenses", "are", "high", "."],
    extraUaTokens: ["цього", "місяця", "дуже"],
    extraRuTokens: ["этого", "месяца", "очень"],
    extraEnTokens: ["this", "month", "very"],
  },

  // =========================
  // LESSON 28 — Технології
  // =========================
  [phraseKey("technologie", "a0-28")]: {
    sk: "Moderní technologie mě baví.",
    ua: "Мені подобаються сучасні технології.",
    ru: "Мне нравятся современные технологии.",
    en: "I like modern technology.",
    uaTokens: ["Мені", "подобаються", "сучасні", "технології", "."],
    ruTokens: ["Мне", "нравятся", "современные", "технологии", "."],
    enTokens: ["I", "like", "modern", "technology", "."],
    extraUaTokens: ["дуже", "сьогодні", "нові"],
    extraRuTokens: ["очень", "сегодня", "новые"],
    extraEnTokens: ["very", "today", "new"],
  },

  [phraseKey("počítač", "a0-28")]: {
    sk: "Můj počítač je pomalý.",
    ua: "Мій комп’ютер повільний.",
    ru: "Мой компьютер медленный.",
    en: "My computer is slow.",
    uaTokens: ["Мій", "комп’ютер", "повільний", "."],
    ruTokens: ["Мой", "компьютер", "медленный", "."],
    enTokens: ["My", "computer", "is", "slow", "."],
    extraUaTokens: ["сьогодні", "дуже", "старий"],
    extraRuTokens: ["сегодня", "очень", "старый"],
    extraEnTokens: ["today", "very", "old"],
  },

  [phraseKey("telefon", "a0-28")]: {
    sk: "Kde je můj telefon?",
    ua: "Де мій телефон?",
    ru: "Где мой телефон?",
    en: "Where is my phone?",
    uaTokens: ["Де", "мій", "телефон", "?"],
    ruTokens: ["Где", "мой", "телефон", "?"],
    enTokens: ["Where", "is", "my", "phone", "?"],
    extraUaTokens: ["зараз", "вже", "тут"],
    extraRuTokens: ["сейчас", "уже", "здесь"],
    extraEnTokens: ["now", "already", "here"],
  },

  [phraseKey("internet", "a0-28")]: {
    sk: "Dnes mi nejde internet.",
    ua: "Сьогодні в мене не працює інтернет.",
    ru: "Сегодня у меня не работает интернет.",
    en: "My internet is not working today.",
    uaTokens: ["Сьогодні", "в", "мене", "не", "працює", "інтернет", "."],
    ruTokens: ["Сегодня", "у", "меня", "не", "работает", "интернет", "."],
    enTokens: ["My", "internet", "is", "not", "working", "today", "."],
    extraUaTokens: ["знову", "дуже", "повільно"],
    extraRuTokens: ["снова", "очень", "медленно"],
    extraEnTokens: ["again", "very", "slowly"],
  },

  [phraseKey("aplikace", "a0-28")]: {
    sk: "Ta aplikace je užitečná.",
    ua: "Цей додаток корисний.",
    ru: "Это приложение полезное.",
    en: "This app is useful.",
    uaTokens: ["Цей", "додаток", "корисний", "."],
    ruTokens: ["Это", "приложение", "полезное", "."],
    enTokens: ["This", "app", "is", "useful", "."],
    extraUaTokens: ["новий", "сьогодні", "зручний"],
    extraRuTokens: ["новое", "сегодня", "удобное"],
    extraEnTokens: ["new", "today", "comfortable"],
  },

  [phraseKey("program", "a0-28")]: {
    sk: "Ten program často používám.",
    ua: "Я часто користуюся цією програмою.",
    ru: "Я часто пользуюсь этой программой.",
    en: "I use this program often.",
    uaTokens: ["Я", "часто", "користуюся", "цією", "програмою", "."],
    ruTokens: ["Я", "часто", "пользуюсь", "этой", "программой", "."],
    enTokens: ["I", "use", "this", "program", "often", "."],
    extraUaTokens: ["щодня", "сьогодні", "зручно"],
    extraRuTokens: ["каждый", "сегодня", "удобно"],
    extraEnTokens: ["everyday", "today", "easily"],
  },

  [phraseKey("systém", "a0-28")]: {
    sk: "Ten systém je jednoduchý.",
    ua: "Ця система проста.",
    ru: "Эта система простая.",
    en: "This system is simple.",
    uaTokens: ["Ця", "система", "проста", "."],
    ruTokens: ["Эта", "система", "простая", "."],
    enTokens: ["This", "system", "is", "simple", "."],
    extraUaTokens: ["нова", "сьогодні", "дуже"],
    extraRuTokens: ["новая", "сегодня", "очень"],
    extraEnTokens: ["new", "today", "very"],
  },

  [phraseKey("síť", "a0-28")]: {
    sk: "Síť je teď slabá.",
    ua: "Мережа зараз слабка.",
    ru: "Сеть сейчас слабая.",
    en: "The network is weak now.",
    uaTokens: ["Мережа", "зараз", "слабка", "."],
    ruTokens: ["Сеть", "сейчас", "слабая", "."],
    enTokens: ["The", "network", "is", "weak", "now", "."],
    extraUaTokens: ["дуже", "сьогодні", "погана"],
    extraRuTokens: ["очень", "сегодня", "плохая"],
    extraEnTokens: ["very", "today", "bad"],
  },

  [phraseKey("data", "a0-28")]: {
    sk: "Musím uložit všechna data.",
    ua: "Мені треба зберегти всі дані.",
    ru: "Мне нужно сохранить все данные.",
    en: "I need to save all the data.",
    uaTokens: ["Мені", "треба", "зберегти", "всі", "дані", "."],
    ruTokens: ["Мне", "нужно", "сохранить", "все", "данные", "."],
    enTokens: ["I", "need", "to", "save", "all", "the", "data", "."],
    extraUaTokens: ["сьогодні", "швидко", "зараз"],
    extraRuTokens: ["сегодня", "быстро", "сейчас"],
    extraEnTokens: ["today", "quickly", "now"],
  },

  [phraseKey("heslo", "a0-28")]: {
    sk: "Zapomněl jsem heslo.",
    ua: "Я забув пароль.",
    ru: "Я забыл пароль.",
    en: "I forgot the password.",
    uaTokens: ["Я", "забув", "пароль", "."],
    ruTokens: ["Я", "забыл", "пароль", "."],
    enTokens: ["I", "forgot", "the", "password", "."],
    extraUaTokens: ["знову", "сьогодні", "свій"],
    extraRuTokens: ["снова", "сегодня", "свой"],
    extraEnTokens: ["again", "today", "my"],
  },

  // =========================
  // LESSON 29 — Повсякденні фрази
  // =========================
  [phraseKey("dobrý den", "a0-29")]: {
    sk: "Dobrý den, jak se máte?",
    ua: "Добрий день, як ви?",
    ru: "Добрый день, как вы?",
    en: "Good afternoon, how are you?",
    uaTokens: ["Добрий", "день", ",", "як", "ви", "?"],
    ruTokens: ["Добрый", "день", ",", "как", "вы", "?"],
    enTokens: ["Good", "afternoon", ",", "how", "are", "you", "?"],
    extraUaTokens: ["сьогодні", "там", "пане"],
    extraRuTokens: ["сегодня", "там", "господин"],
    extraEnTokens: ["today", "there", "sir"],
  },

  [phraseKey("ahoj", "a0-29")]: {
    sk: "Ahoj, rád tě vidím.",
    ua: "Привіт, радий тебе бачити.",
    ru: "Привет, рад тебя видеть.",
    en: "Hi, I am glad to see you.",
    uaTokens: ["Привіт", ",", "радий", "тебе", "бачити", "."],
    ruTokens: ["Привет", ",", "рад", "тебя", "видеть", "."],
    enTokens: ["Hi", ",", "I", "am", "glad", "to", "see", "you", "."],
    extraUaTokens: ["знову", "сьогодні", "дуже"],
    extraRuTokens: ["снова", "сегодня", "очень"],
    extraEnTokens: ["again", "today", "very"],
  },

  [phraseKey("děkuji", "a0-29")]: {
    sk: "Děkuji za pomoc.",
    ua: "Дякую за допомогу.",
    ru: "Спасибо за помощь.",
    en: "Thank you for your help.",
    uaTokens: ["Дякую", "за", "допомогу", "."],
    ruTokens: ["Спасибо", "за", "помощь", "."],
    enTokens: ["Thank", "you", "for", "your", "help", "."],
    extraUaTokens: ["велику", "сьогодні", "щиро"],
    extraRuTokens: ["большую", "сегодня", "искренне"],
    extraEnTokens: ["big", "today", "sincerely"],
  },

  [phraseKey("prosím", "a0-29")]: {
    sk: "Jednu kávu, prosím.",
    ua: "Одну каву, будь ласка.",
    ru: "Один кофе, пожалуйста.",
    en: "One coffee, please.",
    uaTokens: ["Одну", "каву", ",", "будь", "ласка", "."],
    ruTokens: ["Один", "кофе", ",", "пожалуйста", "."],
    enTokens: ["One", "coffee", ",", "please", "."],
    extraUaTokens: ["зараз", "ще", "гарячу"],
    extraRuTokens: ["сейчас", "ещё", "горячий"],
    extraEnTokens: ["now", "another", "hot"],
  },

  [phraseKey("omlouvám se", "a0-29")]: {
    sk: "Omlouvám se za zpoždění.",
    ua: "Перепрошую за запізнення.",
    ru: "Извиняюсь за опоздание.",
    en: "I am sorry for being late.",
    uaTokens: ["Перепрошую", "за", "запізнення", "."],
    ruTokens: ["Извиняюсь", "за", "опоздание", "."],
    enTokens: ["I", "am", "sorry", "for", "being", "late", "."],
    extraUaTokens: ["сьогодні", "дуже", "щиро"],
    extraRuTokens: ["сегодня", "очень", "искренне"],
    extraEnTokens: ["today", "very", "sincerely"],
  },

  [phraseKey("rozumím", "a0-29")]: {
    sk: "Ano, rozumím vám.",
    ua: "Так, я вас розумію.",
    ru: "Да, я вас понимаю.",
    en: "Yes, I understand you.",
    uaTokens: ["Так", ",", "я", "вас", "розумію", "."],
    ruTokens: ["Да", ",", "я", "вас", "понимаю", "."],
    enTokens: ["Yes", ",", "I", "understand", "you", "."],
    extraUaTokens: ["добре", "зараз", "вже"],
    extraRuTokens: ["хорошо", "сейчас", "уже"],
    extraEnTokens: ["well", "now", "already"],
  },

  [phraseKey("nerozumím", "a0-29")]: {
    sk: "Promiňte, nerozumím.",
    ua: "Пробачте, я не розумію.",
    ru: "Извините, я не понимаю.",
    en: "Sorry, I do not understand.",
    uaTokens: ["Пробачте", ",", "я", "не", "розумію", "."],
    ruTokens: ["Извините", ",", "я", "не", "понимаю", "."],
    enTokens: ["Sorry", ",", "I", "do", "not", "understand", "."],
    extraUaTokens: ["ще", "трохи", "зараз"],
    extraRuTokens: ["ещё", "немного", "сейчас"],
    extraEnTokens: ["still", "little", "now"],
  },

  [phraseKey("pomozte", "a0-29")]: {
    sk: "Prosím, pomozte mi.",
    ua: "Будь ласка, допоможіть мені.",
    ru: "Пожалуйста, помогите мне.",
    en: "Please help me.",
    uaTokens: ["Будь", "ласка", ",", "допоможіть", "мені", "."],
    ruTokens: ["Пожалуйста", ",", "помогите", "мне", "."],
    enTokens: ["Please", "help", "me", "."],
    extraUaTokens: ["зараз", "дуже", "терміново"],
    extraRuTokens: ["сейчас", "очень", "срочно"],
    extraEnTokens: ["now", "very", "urgently"],
  },

  [phraseKey("jasné", "a0-29")]: {
    sk: "Jasné, to chápu.",
    ua: "Ясно, я це розумію.",
    ru: "Ясно, я это понимаю.",
    en: "Alright, I understand that.",
    uaTokens: ["Ясно", ",", "я", "це", "розумію", "."],
    ruTokens: ["Ясно", ",", "я", "это", "понимаю", "."],
    enTokens: ["Alright", ",", "I", "understand", "that", "."],
    extraUaTokens: ["добре", "зараз", "вже"],
    extraRuTokens: ["хорошо", "сейчас", "уже"],
    extraEnTokens: ["good", "now", "already"],
  },

  [phraseKey("dobře", "a0-29")]: {
    sk: "Dobře, udělám to.",
    ua: "Добре, я це зроблю.",
    ru: "Хорошо, я это сделаю.",
    en: "Okay, I will do it.",
    uaTokens: ["Добре", ",", "я", "це", "зроблю", "."],
    ruTokens: ["Хорошо", ",", "я", "это", "сделаю", "."],
    enTokens: ["Okay", ",", "I", "will", "do", "it", "."],
    extraUaTokens: ["сьогодні", "пізніше", "точно"],
    extraRuTokens: ["сегодня", "позже", "точно"],
    extraEnTokens: ["today", "later", "for-sure"],
  },

  // =========================
  // LESSON 30 — Повторення бази
  // =========================
  [phraseKey("já", "a0-30")]: {
    sk: "Já jsem tady.",
    ua: "Я тут.",
    ru: "Я здесь.",
    en: "I am here.",
    uaTokens: ["Я", "тут", "."],
    ruTokens: ["Я", "здесь", "."],
    enTokens: ["I", "am", "here", "."],
    extraUaTokens: ["зараз", "вже", "сам"],
    extraRuTokens: ["сейчас", "уже", "сам"],
    extraEnTokens: ["now", "already", "alone"],
  },

  [phraseKey("ty", "a0-30")]: {
    sk: "Ty jsi můj kamarád.",
    ua: "Ти мій друг.",
    ru: "Ты мой друг.",
    en: "You are my friend.",
    uaTokens: ["Ти", "мій", "друг", "."],
    ruTokens: ["Ты", "мой", "друг", "."],
    enTokens: ["You", "are", "my", "friend", "."],
    extraUaTokens: ["добрий", "сьогодні", "старий"],
    extraRuTokens: ["хороший", "сегодня", "старый"],
    extraEnTokens: ["good", "today", "old"],
  },

  [phraseKey("on", "a0-30")]: {
    sk: "On už je doma.",
    ua: "Він уже вдома.",
    ru: "Он уже дома.",
    en: "He is already at home.",
    uaTokens: ["Він", "уже", "вдома", "."],
    ruTokens: ["Он", "уже", "дома", "."],
    enTokens: ["He", "is", "already", "at", "home", "."],
    extraUaTokens: ["зараз", "сьогодні", "сам"],
    extraRuTokens: ["сейчас", "сегодня", "сам"],
    extraEnTokens: ["now", "today", "alone"],
  },

  [phraseKey("ona", "a0-30")]: {
    sk: "Ona pracuje v Praze.",
    ua: "Вона працює в Празі.",
    ru: "Она работает в Праге.",
    en: "She works in Prague.",
    uaTokens: ["Вона", "працює", "в", "Празі", "."],
    ruTokens: ["Она", "работает", "в", "Праге", "."],
    enTokens: ["She", "works", "in", "Prague", "."],
    extraUaTokens: ["зараз", "сьогодні", "там"],
    extraRuTokens: ["сейчас", "сегодня", "там"],
    extraEnTokens: ["now", "today", "there"],
  },

  [phraseKey("my", "a0-30")]: {
    sk: "My se učíme česky.",
    ua: "Ми вчимо чеську.",
    ru: "Мы учим чешский.",
    en: "We are learning Czech.",
    uaTokens: ["Ми", "вчимо", "чеську", "."],
    ruTokens: ["Мы", "учим", "чешский", "."],
    enTokens: ["We", "are", "learning", "Czech", "."],
    extraUaTokens: ["разом", "сьогодні", "щодня"],
    extraRuTokens: ["вместе", "сегодня", "каждый"],
    extraEnTokens: ["together", "today", "everyday"],
  },

  [phraseKey("vy", "a0-30")]: {
    sk: "Vy jste velmi milí.",
    ua: "Ви дуже милі.",
    ru: "Вы очень милые.",
    en: "You are very kind.",
    uaTokens: ["Ви", "дуже", "милі", "."],
    ruTokens: ["Вы", "очень", "милые", "."],
    enTokens: ["You", "are", "very", "kind", "."],
    extraUaTokens: ["сьогодні", "всі", "тут"],
    extraRuTokens: ["сегодня", "все", "здесь"],
    extraEnTokens: ["today", "all", "here"],
  },

  [phraseKey("oni", "a0-30")]: {
    sk: "Oni bydlí blízko nás.",
    ua: "Вони живуть недалеко від нас.",
    ru: "Они живут недалеко от нас.",
    en: "They live near us.",
    uaTokens: ["Вони", "живуть", "недалеко", "від", "нас", "."],
    ruTokens: ["Они", "живут", "недалеко", "от", "нас", "."],
    enTokens: ["They", "live", "near", "us", "."],
    extraUaTokens: ["зараз", "десь", "поруч"],
    extraRuTokens: ["сейчас", "где-то", "рядом"],
    extraEnTokens: ["now", "somewhere", "nearby"],
  },

  [phraseKey("být", "a0-30")]: {
    sk: "Chci být doma.",
    ua: "Я хочу бути вдома.",
    ru: "Я хочу быть дома.",
    en: "I want to be at home.",
    uaTokens: ["Я", "хочу", "бути", "вдома", "."],
    ruTokens: ["Я", "хочу", "быть", "дома", "."],
    enTokens: ["I", "want", "to", "be", "at", "home", "."],
    extraUaTokens: ["зараз", "вже", "спокійно"],
    extraRuTokens: ["сейчас", "уже", "спокойно"],
    extraEnTokens: ["now", "already", "calmly"],
  },

  [phraseKey("mít", "a0-30")]: {
    sk: "Chci mít volný večer.",
    ua: "Я хочу мати вільний вечір.",
    ru: "Я хочу иметь свободный вечер.",
    en: "I want to have a free evening.",
    uaTokens: ["Я", "хочу", "мати", "вільний", "вечір", "."],
    ruTokens: ["Я", "хочу", "иметь", "свободный", "вечер", "."],
    enTokens: ["I", "want", "to", "have", "a", "free", "evening", "."],
    extraUaTokens: ["сьогодні", "спокійний", "тихий"],
    extraRuTokens: ["сегодня", "спокойный", "тихий"],
    extraEnTokens: ["today", "calm", "quiet"],
  },

  [phraseKey("jít", "a0-30")]: {
    sk: "Musíme už jít.",
    ua: "Нам уже треба йти.",
    ru: "Нам уже нужно идти.",
    en: "We need to leave now.",
    uaTokens: ["Нам", "уже", "треба", "йти", "."],
    ruTokens: ["Нам", "уже", "нужно", "идти", "."],
    enTokens: ["We", "need", "to", "leave", "now", "."],
    extraUaTokens: ["зараз", "додому", "швидко"],
    extraRuTokens: ["сейчас", "домой", "быстро"],
    extraEnTokens: ["now", "home", "quickly"],
  },
};